In [47]:
import logging
import re
from typing import List, Optional, Any

import numpy as np
from sklearn.ensemble import RandomForestClassifier
from scipy.sparse import csr_matrix
import pandas as pd
from skfp.fingerprints import AtomPairFingerprint, TopologicalTorsionFingerprint
from rdkit import Chem
from skfp.fingerprints import RDKit2DDescriptorsFingerprint
from rdkit.Chem import SaltRemover
from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.pipeline import Pipeline, FeatureUnion
from sklearn.metrics import f1_score

from collections import defaultdict
from typing import List, Tuple, Dict

import numpy as np
from rdkit import Chem
from rdkit.Chem.Scaffolds import MurckoScaffold

# Autentyczne klasy z ekosystemu scikit-fingerprints
from skfp.fingerprints import ECFPFingerprint, MACCSFingerprint

In [2]:
class DAGMolStandardizer(BaseEstimator, TransformerMixin):
    """Niskopoziomowy transformator RDKit przygotowujący grafy pod klasyfikację ChEBI.

    Klasa parsuje SMILES, weryfikuje poprawność, usuwa sole, ale w przeciwieństwie
    do filtrów ADME, nie usuwa skrajnie dużych molekuł, ponieważ ontologia ChEBI
    zawiera również makromolekuły i złożone peptydy.

    Atrybuty:
        salt_remover (SaltRemover): Instancja do odcinania asocjatów jonowych.
    """

    def __init__(self) -> None:
        """Inicjalizacja standardyzatora z modułem SaltRemover."""
        self.salt_remover = SaltRemover.SaltRemover()

    def fit(self, X: List[str], y: Optional[Any] = None) -> 'DAGMolStandardizer':
        """Metoda dopasowania (statyczna standaryzacja nie wymaga treningu).

        Args:
            X: Lista ciągów znaków SMILES (33 668 instancji).
            y: Etykiety (ignorowane na etapie wektoryzacji).

        Returns:
            Instancja samej siebie.
        """
        return self

    def transform(self, X: List[str]) -> List[Optional[Chem.Mol]]:
        """Aplikuje standaryzację na grafach molekularnych.

        Args:
            X: Lista ciągów SMILES.

        Returns:
            Lista wyczyszczonych obiektów rdkit.Chem.Mol. Niewłaściwe SMILES
            zwracają wartość None, co zapobiega awarii potoku.
        """
        standardized_mols = []
        for smiles in X:
            mol = Chem.MolFromSmiles(smiles)
            if mol is None:
                logging.warning(f"Odrzucono uszkodzony SMILES: {smiles}")
                standardized_mols.append(None)
                continue

            # Bezpieczne usunięcie krystalizatorów i resztek rozpuszczalników
            clean_mol = self.salt_remover.StripMol(mol, dontRemoveEverything=True)

            if clean_mol is not None:
                Chem.SanitizeMol(clean_mol)

            standardized_mols.append(clean_mol)

        return standardized_mols


def build_chebi_feature_pipeline() -> Pipeline:
    """Konstruuje potok inżynierii cech zoptymalizowany pod klasyfikację strukturalną DAG.

    Używa obiektu FeatureUnion do równoległego złączenia zliczeniowych promieni otoczenia
    (ECFP) z deterministycznym detektorem grup funkcyjnych (MACCS Keys). Całość
    operuje na rzadkich macierzach pamięci.

    Returns:
        Obiekt sklearn.pipeline.Pipeline ustandaryzowany do integracji z docelowym
        estymatorem (np. estymatorami drzewiastymi wspierającymi MultiOutput).
    """
    # Zderzamy detekcję grup funkcyjnych (MACCS) z głęboką analizą promieniową (ECFP)
    # n_jobs=-1 gwarantuje zużycie 100% lokalnego procesora
    feature_fusion = FeatureUnion(transformer_list=[
        ('maccs_keys', MACCSFingerprint(sparse=True, n_jobs=-1)),
        ('ecfp_counts', ECFPFingerprint(count=True, sparse=True, n_jobs=-1))
    ], n_jobs=-1)

    pipeline = Pipeline(steps=[
        # Krok 1: Walidacja i czyszczenie
        ('standardization', DAGMolStandardizer()),

        # Omijamy filtrację Lipinskiego - ChEBI bada strukturę, a nie wchłanialność leku!

        # Krok 2: Generacja zoptymalizowanej, rzadkiej macierzy fuzji
        ('hybrid_vectorization', feature_fusion),

        ('atom_pair', AtomPairFingerprint(count=True, sparse=True, n_jobs=-1)),

        ('torsion', TopologicalTorsionFingerprint(count=True, sparse=True, n_jobs=-1)),

        ('rdkit_descriptors', RDKit2DDescriptorsFingerprint(sparse=False, n_jobs=-1))

        # Uwaga: Estymator zostanie dodany w kolejnym kroku, po omówieniu strategii dla DAG.
    ])

    return pipeline

In [3]:
preprocess_pipeline = build_chebi_feature_pipeline()

In [8]:
data_path = '../../1_ontology/data/chebi_dataset_train.parquet'
df = pd.read_parquet(data_path)

In [10]:
df

,mol_id,SMILES,class_0,class_1,class_2,class_3,class_4,class_5,class_6,class_7,...,class_490,class_491,class_492,class_493,class_494,class_495,class_496,class_497,class_498,class_499
0,mol_12500,CCCCC/C=C\CCCCCCCC(=O)O,1,1,1,1,1,1,1,1,...,0,0,0,0,0,0,0,0,0,0
1,mol_15962,Cc1cc2cc(O)cc(O)c2c(C)n1,1,1,1,1,1,1,1,1,...,0,0,0,0,0,0,0,0,0,0
2,mol_42147,C[C@H](CCC[C@@H](C)C=O)[C@H]1CC[C@H]2[C@@H]3CC...,1,1,1,1,1,1,1,1,...,0,0,0,0,0,0,0,0,0,0
3,mol_43459,CCN=C1C=CC(=C(c2ccc(NCC)cc2)c2ccc(NCC)c(C)c2)C=C1,1,1,1,1,1,1,1,0,...,0,0,0,0,0,0,0,0,0,0
4,mol_12734,C[C@H](CCC(O)=N[C@@H](Cc1c[nH]c2ccccc12)C(=O)O...,1,1,1,1,1,1,1,1,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33663,mol_26342,C[C@H](OP(=O)(O)OC[C@@H](O)[C@@H](O)[C@@H](O)C...,1,1,1,1,1,1,1,1,...,0,0,0,0,0,0,0,0,0,0
33664,mol_5233,O=C(Nc1ccc(Cl)cc1)Nc1ccc(Cl)cc1,1,1,1,1,1,1,1,0,...,0,0,0,0,0,0,0,0,0,0
33665,mol_36641,Cc1cn([C@H]2C[C@H](OP(=O)(O)OC[C@H]3O[C@@H](n4...,1,1,1,1,1,1,1,0,...,0,0,0,0,0,0,0,0,0,0
33666,mol_9633,O=C([O-])C(O)Cc1c[nH]c2ccccc12,1,1,1,1,1,1,1,1,...,0,0,0,0,0,0,0,0,0,0
33667,mol_22966,[Cr].[I-].[O].[O].[O],1,1,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0

In [33]:
def generate_scaffold(smiles: str, include_chirality: bool = False) -> str:
    """Generuje rusztowanie Bemis-Murcko dla podanego ciągu SMILES.

    Args:
        smiles (str): Ciąg znaków SMILES molekuły.
        include_chirality (bool): Czy uwzględniać stereochemię w rusztowaniu.

    Returns:
        str: SMILES rusztowania lub pusty ciąg, jeśli parsowanie zawiodło.
    """
    mol = Chem.MolFromSmiles(smiles)
    if mol is None:
        return ""
    # Generowanie rusztowania (szkieletu pierścieniowego z łącznikami)
    scaffold = MurckoScaffold.MurckoScaffoldSmiles(
        mol=mol, includeChirality=include_chirality
    )
    return scaffold


def scaffold_split(
    df: pd.DataFrame,
    smiles_col: str = 'SMILES',
    train_size: float = 0.8
) -> Tuple[pd.DataFrame, pd.DataFrame]:
    """Wykonuje podział zbioru danych w oparciu o unikalne rusztowania molekularne.

    Zapewnia, że wszystkie molekuły o tym samym rdzeniu (scaffold) znajdują się
    wyłącznie w jednym ze zbiorów (treningowym lub testowym).

    Args:
        df (pd.DataFrame): Wejściowy zbiór danych ChEBI.
        smiles_col (str): Nazwa kolumny z ciągami SMILES.
        train_size (float): Proporcja zbioru treningowego.

    Returns:
        Tuple[pd.DataFrame, pd.DataFrame]: Ramki danych (train, test).
    """
    logging.info("Rozpoczynam generowanie rusztowań dla Scaffold Split...")

    # Grupowanie indeksów według unikalnych rusztowań
    scaffolds: Dict[str, List[int]] = defaultdict(list)
    for idx, smiles in enumerate(df[smiles_col]):
        scaff_smiles = generate_scaffold(smiles)
        scaffolds[scaff_smiles].append(idx)

    # Sortowanie grup od największej do najmniejszej (praktyka stabilizująca podział)
    scaffold_sets = sorted(scaffolds.values(), key=len, reverse=True)

    train_indices: List[int] = []
    test_indices: List[int] = []
    n_train_cutoff = int(len(df) * train_size)

    for scaffold_set in scaffold_sets:
        if len(train_indices) + len(scaffold_set) <= n_train_cutoff:
            train_indices.extend(scaffold_set)
        else:
            test_indices.extend(scaffold_set)

    print(f"Podział zakończony. Train: {len(train_indices)}, Test: {len(test_indices)}")
    return df.iloc[train_indices], df.iloc[test_indices]

In [34]:
df_train, df_test = scaffold_split(df)

[20:57:17] WARNING: not removing hydrogen atom without neighbors
[20:57:17] WARNING: not removing hydrogen atom without neighbors
[20:57:17] WARNING: not removing hydrogen atom without neighbors
[20:57:17] WARNING: not removing hydrogen atom without neighbors
[20:57:18] WARNING: not removing hydrogen atom without neighbors
[20:57:18] WARNING: not removing hydrogen atom without neighbors
[20:57:18] WARNING: not removing hydrogen atom without neighbors
[20:57:18] WARNING: not removing hydrogen atom without neighbors
[20:57:18] WARNING: not removing hydrogen atom without neighbors
[20:57:18] Unusual charge on atom 0 number of radical electrons set to zero
[20:57:19] WARNING: not removing hydrogen atom without neighbors
[20:57:19] WARNING: not removing hydrogen atom without neighbors
[20:57:19] WARNING: not removing hydrogen atom without neighbors
[20:57:19] WARNING: not removing hydrogen atom without neighbors
[20:57:19] WARNING: not removing hydrogen atom without neighbors
[20:57:19] WARNING: not removing hydrogen atom without neighbors
[20:57:19] WARNING: not removing hydrogen atom without neighbors
[20:57:19] WARNING: not removing hydrogen atom without neighbors
[20:57:19] WARNING: not removing hydrogen atom without neighbors
[20:57:19] WARNING: not removing hydrogen atom without neighbors
[20:57:19] WARNING: not removing hydrogen atom without neighbors
[20:57:19] WARNING: not removing hydrogen atom without neighbors
[20:57:19] WARNING: not removing hydrogen atom without neighbors
[20:57:19] WARNING: not removing hydrogen atom without neighbors
[20:57:19] WARNING: not removing hydrogen atom without neighbors
[20:57:19] WARNING: not removing hydrogen atom without neighbors
[20:57:19] WARNING: not removing hydrogen atom without neighbors
[20:57:19] WARNING: not removing hydrogen atom without neighbors
[20:57:20] WARNING: not removing hydrogen atom without neighbors
[20:57:20] WARNING: not removing hydrogen atom without neighbors
[20:57:20] WARNING: not removing hydrogen atom without neighbors
[20:57:21] WARNING: not removing hydrogen atom without neighbors
[20:57:21] WARNING: not removing hydrogen atom without neighbors
[20:57:21] WARNING: not removing hydrogen atom without neighbors
[20:57:21] WARNING: not removing hydrogen atom without neighbors
[20:57:21] WARNING: not removing hydrogen atom without neighbors
[20:57:21] WARNING: not removing hydrogen atom without neighbors
[20:57:21] WARNING: not removing hydrogen atom without neighbors
[20:57:21] WARNING: not removing hydrogen atom without neighbors
[20:57:21] WARNING: not removing hydrogen atom without neighbors
[20:57:22] WARNING: not removing hydrogen atom without neighbors
[20:57:22] WARNING: not removing hydrogen atom without neighbors
[20:57:22] WARNING: not removing hydrogen atom without neighbors
[20:57:22] WARNING: not removing hydrogen atom without neighbors
[20:57:22] WARNING: not removing hydrogen atom without neighbors
[20:57:22] Unusual charge on atom 0 number of radical electrons set to zero
[20:57:22] WARNING: not removing hydrogen atom without neighbors
[20:57:22] WARNING: not removing hydrogen atom without neighbors
[20:57:22] WARNING: not removing hydrogen atom without neighbors
[20:57:22] WARNING: not removing hydrogen atom without neighbors
[20:57:22] WARNING: not removing hydrogen atom without neighbors
[20:57:22] WARNING: not removing hydrogen atom without neighbors
[20:57:22] WARNING: not removing hydrogen atom without neighbors
[20:57:22] WARNING: not removing hydrogen atom without neighbors
[20:57:22] WARNING: not removing hydrogen atom without neighbors
[20:57:23] WARNING: not removing hydrogen atom without neighbors
[20:57:23] WARNING: not removing hydrogen atom without neighbors
[20:57:24] WARNING: not removing hydrogen atom without neighbors
[20:57:24] WARNING: not removing hydrogen atom without neighbors
[20:57:24] WARNING: not removing hydrogen atom without neighbors
[20:57:24] WARNING: not removing hydrogen atom without neighbors
[20:57:24] WARNING: not removing hydrogen atom without neighbors
[20:57:24] WARNING: not removing hydrogen atom without neighbors
[20:57:24] WARNING: not removing hydrogen atom without neighbors
[20:57:25] WARNING: not removing hydrogen atom without neighbors
[20:57:25] WARNING: not removing hydrogen atom without neighbors
[20:57:25] WARNING: not removing hydrogen atom without neighbors
[20:57:25] WARNING: not removing hydrogen atom without neighbors
[20:57:25] WARNING: not removing hydrogen atom without neighbors
[20:57:25] WARNING: not removing hydrogen atom without neighbors
[20:57:25] WARNING: not removing hydrogen atom without neighbors
[20:57:25] WARNING: not removing hydrogen atom without neighbors
[20:57:25] WARNING: not removing hydrogen atom without neighbors
[20:57:25] WARNING: not removing hydrogen atom without neighbors
[20:57:25] WARNING: not removing hydrogen atom without neighbors
[20:57:25] WARNING: not removing hydrogen atom without neighbors
[20:57:25] WARNING: not removing hydrogen atom without neighbors
[20:57:25] WARNING: not removing hydrogen atom without neighbors
[20:57:25] WARNING: not removing hydrogen atom without neighbors
[20:57:25] WARNING: not removing hydrogen atom without neighbors
[20:57:25] WARNING: not removing hydrogen atom without neighbors
[20:57:25] WARNING: not removing hydrogen atom without neighbors
[20:57:25] WARNING: not removing hydrogen atom without neighbors
[20:57:25] WARNING: not removing hydrogen atom without neighbors
[20:57:25] WARNING: not removing hydrogen atom without neighbors
[20:57:25] WARNING: not removing hydrogen atom without neighbors
[20:57:25] WARNING: not removing hydrogen atom without neighbors
[20:57:26] WARNING: not removing hydrogen atom without neighbors
[20:57:27] WARNING: not removing hydrogen atom without neighbors
[20:57:27] WARNING: not removing hydrogen atom without neighbors
[20:57:27] WARNING: not removing hydrogen atom without neighbors
[20:57:27] WARNING: not removing hydrogen atom without neighbors
[20:57:27] WARNING: not removing hydrogen atom without neighbors
[20:57:27] WARNING: not removing hydrogen atom without neighbors
[20:57:27] WARNING: not removing hydrogen atom without neighbors
[20:57:27] WARNING: not removing hydrogen atom without neighbors
[20:57:27] WARNING: not removing hydrogen atom without neighbors
[20:57:27] WARNING: not removing hydrogen atom without neighbors
[20:57:27] WARNING: not removing hydrogen atom without neighbors
[20:57:27] WARNING: not removing hydrogen atom without neighbors
[20:57:27] WARNING: not removing hydrogen atom without neighbors
[20:57:27] WARNING: not removing hydrogen atom without neighbors
[20:57:27] WARNING: not removing hydrogen atom without neighbors
[20:57:27] WARNING: not removing hydrogen atom without neighbors
[20:57:27] WARNING: not removing hydrogen atom without neighbors
[20:57:27] WARNING: not removing hydrogen atom without neighbors
[20:57:27] WARNING: not removing hydrogen atom without neighbors
[20:57:27] WARNING: not removing hydrogen atom without neighbors
[20:57:27] WARNING: not removing hydrogen atom without neighbors
[20:57:27] WARNING: not removing hydrogen atom without neighbors
[20:57:27] WARNING: not removing hydrogen atom without neighbors
[20:57:28] WARNING: not removing hydrogen atom without neighbors
[20:57:28] WARNING: not removing hydrogen atom without neighbors
[20:57:28] WARNING: not removing hydrogen atom without neighbors
[20:57:28] WARNING: not removing hydrogen atom without neighbors
[20:57:28] WARNING: not removing hydrogen atom without neighbors
[20:57:28] WARNING: not removing hydrogen atom without neighbors
[20:57:28] WARNING: not removing hydrogen atom without neighbors
[20:57:28] WARNING: not removing hydrogen atom without neighbors

Podział zakończony. Train: 26934, Test: 6734

[20:57:28] WARNING: not removing hydrogen atom without neighbors
[20:57:28] WARNING: not removing hydrogen atom without neighbors
[20:57:28] WARNING: not removing hydrogen atom without neighbors
[20:57:28] WARNING: not removing hydrogen atom without neighbors

In [40]:
def parse_hierarchy(file_path: str) -> Dict[str, List[str]]:
    """Parsuje plik chebi_classes.txt w celu wyodrębnienia relacji is_a.

    Args:
        file_path (str): Ścieżka do pliku z definicjami klas ChEBI.

    Returns:
        Dict[str, List[str]]: Mapowanie: klasa_dziecko -> lista_klas_rodziców.
    """
    parents = {}
    with open(file_path, "r", encoding="utf-8") as f:
        content = f.read()

    # Podział na poszczególne termy w pliku OBO/ChEBI
    terms = content.split("[Term]")
    for term in terms[1:]:
        # Wyciągnięcie ID klasy
        id_match = re.search(r"^id:\s*(class_\d+)", term, re.MULTILINE)
        if not id_match:
            continue
        child_id = id_match.group(1)

        # Wyciągnięcie wszystkich klas nadrzędnych (is_a)
        is_a_matches = re.findall(r"^is_a:\s*(class_\d+)", term, re.MULTILINE)
        parents[child_id] = is_a_matches
    return parents

def apply_transitive_closure(
    y: np.ndarray,
    columns: List[str],
    hierarchy: Dict[str, List[str]]
) -> np.ndarray:
    """Wymusza spójność hierarchiczną w macierzy etykiet y.

    Zapewnia, że jeśli molekuła należy do klasy specyficznej, to należy również
    do wszystkich jej klas nadrzędnych w grafie DAG.

    Args:
        y (np.ndarray): Macierz binarnych etykiet.
        columns (List[str]): Lista nazw kolumn klas.
        hierarchy (Dict[str, List[str]]): Słownik relacji is_a.

    Returns:
        np.ndarray: Przetworzona macierz y z domknięciem przechodnim.
    """
    col_to_idx = {name: i for i, name in enumerate(columns)}
    y_closed = y.copy()

    # Sortowanie kolumn malejąco (od liści do korzenia grafu)
    for col_name in reversed(columns):
        if col_name in hierarchy:
            child_idx = col_to_idx[col_name]
            for parent_name in hierarchy[col_name]:
                if parent_name in col_to_idx:
                    parent_idx = col_to_idx[parent_name]
                    # Logiczne OR: jeśli dziecko ma cechę, rodzic też musi ją mieć
                    y_closed[:, parent_idx] = np.maximum(
                        y_closed[:, parent_idx], y_closed[:, child_idx]
                    )
    return y_closed

In [43]:
# 1. Parsowanie hierarchii z pliku
hierarchy_map = parse_hierarchy("chebi_classes.txt")

# 2. Wyciągnięcie surowych etykiet y z Twoich ramek danych
# class_cols to lista: ['class_0', 'class_1', ..., 'class_499']
class_cols = [col for col in df_train.columns if col.startswith("class_")]
y_train_raw = df_train[class_cols].values
y_test_raw = df_test[class_cols].values

# 3. Aplikacja Transitive Closure (kluczowe dla F1-Macro i spójności)
logging.info("Aplikuję domknięcie przechodnie dla hierarchii ChEBI...")
y_train = apply_transitive_closure(y_train_raw, class_cols, hierarchy_map)
y_test = apply_transitive_closure(y_test_raw, class_cols, hierarchy_map)

In [46]:
model = RandomForestClassifier(
    n_estimators=500,
    class_weight="balanced_subsample",
    n_jobs=-1,
    random_state=42
)

logging.info("Rozpoczynam trening modelu baseline (Random Forest)...")
model.fit(X_train, y_train)

RandomForestClassifier(class_weight='balanced_subsample', n_estimators=500,
                       n_jobs=-1, random_state=42)

In [48]:
y_pred = model.predict(X_test)
macro_f1 = f1_score(y_test, y_pred, average="macro")
logging.info(f"Trening zakończony. Wynik F1-Macro: {macro_f1:.4f}")

C:\Users\domin\PycharmProjects\ml-train-lgbm\.venv\lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true nor predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

In [49]:
macro_f1

0.18211360433312065

In [90]:
import importlib
import chebi_feature_pipeline  # Importujemy cały moduł

# Przeładowujemy moduł
importlib.reload(chebi_feature_pipeline)

# Wyciągamy odświeżoną funkcję i klasę
from chebi_feature_pipeline import preprocess_chebi_data, FeatureConfig

X_train, X_test = preprocess_chebi_data(df_train, df_test, smiles_col='SMILES')

[21:46:55] WARNING: not removing hydrogen atom without neighbors
[21:46:55] WARNING: not removing hydrogen atom without neighbors
[21:46:55] WARNING: not removing hydrogen atom without neighbors
[21:46:55] WARNING: not removing hydrogen atom without neighbors
[21:46:55] WARNING: not removing hydrogen atom without neighbors
[21:46:55] WARNING: not removing hydrogen atom without neighbors
[21:46:55] WARNING: not removing hydrogen atom without neighbors
[21:46:55] WARNING: not removing hydrogen atom without neighbors
[21:46:55] WARNING: not removing hydrogen atom without neighbors
[21:46:55] Unusual charge on atom 0 number of radical electrons set to zero
[21:46:55] Unusual charge on atom 0 number of radical electrons set to zero
[21:46:55] WARNING: not removing hydrogen atom without neighbors
[21:46:55] WARNING: not removing hydrogen atom without neighbors
[21:46:55] WARNING: not removing hydrogen atom without neighbors
[21:46:55] WARNING: not removing hydrogen atom without neighbors
[21:46:55] WARNING: not removing hydrogen atom without neighbors
[21:46:55] WARNING: not removing hydrogen atom without neighbors
[21:46:55] WARNING: not removing hydrogen atom without neighbors
[21:46:55] WARNING: not removing hydrogen atom without neighbors
[21:46:55] WARNING: not removing hydrogen atom without neighbors
[21:46:55] WARNING: not removing hydrogen atom without neighbors
[21:46:55] WARNING: not removing hydrogen atom without neighbors
[21:46:55] WARNING: not removing hydrogen atom without neighbors
[21:46:55] WARNING: not removing hydrogen atom without neighbors
[21:46:55] WARNING: not removing hydrogen atom without neighbors
[21:46:55] WARNING: not removing hydrogen atom without neighbors
[21:46:55] WARNING: not removing hydrogen atom without neighbors
[21:46:55] WARNING: not removing hydrogen atom without neighbors
[21:46:55] WARNING: not removing hydrogen atom without neighbors
[21:46:55] WARNING: not removing hydrogen atom without neighbors
[21:46:55] WARNING: not removing hydrogen atom without neighbors
[21:46:55] WARNING: not removing hydrogen atom without neighbors
[21:46:55] WARNING: not removing hydrogen atom without neighbors
[21:46:55] WARNING: not removing hydrogen atom without neighbors
[21:46:55] WARNING: not removing hydrogen atom without neighbors
[21:46:55] WARNING: not removing hydrogen atom without neighbors
[21:46:55] WARNING: not removing hydrogen atom without neighbors
[21:46:55] WARNING: not removing hydrogen atom without neighbors
[21:46:55] WARNING: not removing hydrogen atom without neighbors
[21:46:55] WARNING: not removing hydrogen atom without neighbors
[21:46:55] WARNING: not removing hydrogen atom without neighbors
[21:46:55] WARNING: not removing hydrogen atom without neighbors
[21:46:55] WARNING: not removing hydrogen atom without neighbors
[21:46:55] WARNING: not removing hydrogen atom without neighbors
[21:46:55] WARNING: not removing hydrogen atom without neighbors
[21:46:55] WARNING: not removing hydrogen atom without neighbors
[21:46:55] Unusual charge on atom 0 number of radical electrons set to zero
[21:46:55] Unusual charge on atom 0 number of radical electrons set to zero
[21:46:55] WARNING: not removing hydrogen atom without neighbors
[21:46:55] WARNING: not removing hydrogen atom without neighbors
[21:46:55] WARNING: not removing hydrogen atom without neighbors
[21:46:55] WARNING: not removing hydrogen atom without neighbors
[21:46:55] WARNING: not removing hydrogen atom without neighbors
[21:46:55] WARNING: not removing hydrogen atom without neighbors
[21:46:55] WARNING: not removing hydrogen atom without neighbors
[21:46:55] WARNING: not removing hydrogen atom without neighbors
[21:46:56] WARNING: not removing hydrogen atom without neighbors
[21:46:56] WARNING: not removing hydrogen atom without neighbors
[21:46:56] WARNING: not removing hydrogen atom without neighbors
[21:46:56] WARNING: not removing hydrogen atom without neighbors
[21:46:56] WARNING: not removing hydrogen atom without neighbors
[21:46:56] WARNING: not removing hydrogen atom without neighbors
[21:46:56] WARNING: not removing hydrogen atom without neighbors
[21:46:56] WARNING: not removing hydrogen atom without neighbors
[21:46:56] WARNING: not removing hydrogen atom without neighbors
[21:46:56] WARNING: not removing hydrogen atom without neighbors
[21:46:56] WARNING: not removing hydrogen atom without neighbors
[21:46:56] WARNING: not removing hydrogen atom without neighbors
[21:46:56] WARNING: not removing hydrogen atom without neighbors
[21:46:56] WARNING: not removing hydrogen atom without neighbors
[21:46:56] WARNING: not removing hydrogen atom without neighbors
[21:46:56] WARNING: not removing hydrogen atom without neighbors
[21:46:56] WARNING: not removing hydrogen atom without neighbors
[21:46:56] WARNING: not removing hydrogen atom without neighbors
[21:46:56] WARNING: not removing hydrogen atom without neighbors
[21:46:56] WARNING: not removing hydrogen atom without neighbors
[21:46:56] WARNING: not removing hydrogen atom without neighbors
[21:46:56] WARNING: not removing hydrogen atom without neighbors
[21:46:56] WARNING: not removing hydrogen atom without neighbors
[21:46:56] WARNING: not removing hydrogen atom without neighbors
[21:46:56] WARNING: not removing hydrogen atom without neighbors
[21:46:56] WARNING: not removing hydrogen atom without neighbors
[21:46:56] WARNING: not removing hydrogen atom without neighbors
[21:46:56] WARNING: not removing hydrogen atom without neighbors
[21:46:56] WARNING: not removing hydrogen atom without neighbors
[21:46:56] WARNING: not removing hydrogen atom without neighbors
[21:46:56] WARNING: not removing hydrogen atom without neighbors
[21:46:56] WARNING: not removing hydrogen atom without neighbors
[21:46:56] WARNING: not removing hydrogen atom without neighbors
[21:46:56] WARNING: not removing hydrogen atom without neighbors
[21:46:56] WARNING: not removing hydrogen atom without neighbors
[21:46:56] WARNING: not removing hydrogen atom without neighbors
[21:46:56] WARNING: not removing hydrogen atom without neighbors
[21:46:56] WARNING: not removing hydrogen atom without neighbors
[21:46:56] WARNING: not removing hydrogen atom without neighbors
[21:46:56] WARNING: not removing hydrogen atom without neighbors
[21:46:56] WARNING: not removing hydrogen atom without neighbors
[21:46:56] WARNING: not removing hydrogen atom without neighbors
[21:46:56] WARNING: not removing hydrogen atom without neighbors
[21:46:56] WARNING: not removing hydrogen atom without neighbors
[21:46:56] WARNING: not removing hydrogen atom without neighbors
[21:46:56] WARNING: not removing hydrogen atom without neighbors
[21:46:56] WARNING: not removing hydrogen atom without neighbors
[21:46:56] WARNING: not removing hydrogen atom without neighbors
[21:46:56] WARNING: not removing hydrogen atom without neighbors
[21:46:56] WARNING: not removing hydrogen atom without neighbors
[21:46:56] WARNING: not removing hydrogen atom without neighbors
[21:46:56] WARNING: not removing hydrogen atom without neighbors
[21:46:56] WARNING: not removing hydrogen atom without neighbors
[21:46:56] WARNING: not removing hydrogen atom without neighbors
[21:46:56] WARNING: not removing hydrogen atom without neighbors
[21:46:56] WARNING: not removing hydrogen atom without neighbors
[21:46:56] WARNING: not removing hydrogen atom without neighbors
[21:46:56] WARNING: not removing hydrogen atom without neighbors
[21:46:56] WARNING: not removing hydrogen atom without neighbors
[21:46:56] WARNING: not removing hydrogen atom without neighbors
[21:46:56] WARNING: not removing hydrogen atom without neighbors
[21:46:56] WARNING: not removing hydrogen atom without neighbors
[21:46:56] WARNING: not removing hydrogen atom without neighbors
[21:46:56] WARNING: not removing hydrogen atom without neighbors
[21:46:56] WARNING: not removing hydrogen atom without neighbors
[21:46:59] WARNING: not removing hydrogen atom without neighbors
[21:46:59] WARNING: not removing hydrogen atom without neighbors
[21:49:15] WARNING: not removing hydrogen atom without neighbors
[21:49:15] WARNING: not removing hydrogen atom without neighbors
C:\Users\domin\PycharmProjects\ml-train-lgbm\.venv\lib\site-packages\sklearn\pipeline.py:61: FutureWarning: This Pipeline instance is not fitted yet. Call 'fit' with appropriate arguments before using other methods such as transform, predict, etc. This will raise an error in 1.8 instead of the current warning.
  warnings.warn(
C:\Users\domin\PycharmProjects\ml-train-lgbm\.venv\lib\site-packages\sklearn\pipeline.py:61: FutureWarning: This Pipeline instance is not fitted yet. Call 'fit' with appropriate arguments before using other methods such as transform, predict, etc. This will raise an error in 1.8 instead of the current warning.
  warnings.warn(
C:\Users\domin\PycharmProjects\ml-train-lgbm\.venv\lib\site-packages\sklearn\pipeline.py:61: FutureWarning: This Pipeline instance is not fitted yet. Call 'fit' with appropriate arguments before using other methods such as transform, predict, etc. This will raise an error in 1.8 instead of the current warning.
  warnings.warn(
C:\Users\domin\PycharmProjects\ml-train-lgbm\.venv\lib\site-packages\sklearn\pipeline.py:61: FutureWarning: This Pipeline instance is not fitted yet. Call 'fit' with appropriate arguments before using other methods such as transform, predict, etc. This will raise an error in 1.8 instead of the current warning.
  warnings.warn(

In [92]:
import networkx as nx
import sys

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
    handlers=[logging.StreamHandler(sys.stdout)],
)
log = logging.getLogger(__name__)

In [99]:
# ============================================================
# CELL 1 — Importy
# ============================================================
import logging
import sys
import time
from typing import List, Tuple

import lightgbm as lgb
import networkx as nx
import numpy as np
import pandas as pd
from sklearn.metrics import f1_score
from tqdm.notebook import tqdm

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
    handlers=[logging.StreamHandler(sys.stdout)],
)
log = logging.getLogger(__name__)


# ============================================================
# CELL 2 — Kolumny etykiet (zakładamy że df_train już istnieje)
# ============================================================
LABEL_PREFIX = "class_"
label_cols = [c for c in df_train.columns if c.startswith(LABEL_PREFIX)]
n_classes  = len(label_cols)

y_train = df_train[label_cols].values.astype(np.float32)
y_test  = df_test[label_cols].values.astype(np.float32)  # usuń jeśli test bez etykiet

print(f"Liczba klas : {n_classes}")
print(f"X_train     : {X_train.shape}")
print(f"X_test      : {X_test.shape}")
print(f"y_train     : {y_train.shape}")

Liczba klas : 500
X_train     : (26934, 11460)
X_test      : (6734, 11460)
y_train     : (26934, 500)

In [100]:
# ============================================================
# CELL 3 — Parser DAG z chebi_classes.txt
# ============================================================
def parse_chebi_dag(obo_path: str) -> nx.DiGraph:
    """Buduje DAG z relacji is_a. Krawędź: child → parent."""
    dag = nx.DiGraph()
    current_id = None
    with open(obo_path, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if line == "[Term]":
                current_id = None
            elif line.startswith("id:"):
                current_id = line.split("id:")[1].strip()
                dag.add_node(current_id)
            elif line.startswith("is_a:") and current_id:
                parent = line.split("is_a:")[1].strip().split()[0]
                dag.add_edge(current_id, parent)
    log.info(f"DAG: {dag.number_of_nodes()} węzłów, {dag.number_of_edges()} krawędzi")
    return dag


dag = parse_chebi_dag("chebi_classes.txt")

In [101]:
# ============================================================
# CELL 4 — Propagacja etykiet w górę DAG (postprocessing)
# ============================================================
def propagate_labels_upward(
    y_pred: np.ndarray,
    dag: nx.DiGraph,
    class_columns: List[str],
) -> np.ndarray:
    """Jeśli dziecko=1, wszyscy przodkowie=1. Redukuje niespójności DAG."""
    col_to_idx = {col: i for i, col in enumerate(class_columns)}
    result = y_pred.copy()
    try:
        topo_order = list(nx.topological_sort(dag))
    except nx.NetworkXUnfeasible:
        log.warning("DAG zawiera cykl – pomijam propagację.")
        return result
    for node in topo_order:
        if node not in col_to_idx:
            continue
        active = np.where(result[:, col_to_idx[node]] == 1)[0]
        if len(active) == 0:
            continue
        for parent in dag.successors(node):
            if parent in col_to_idx:
                result[active, col_to_idx[parent]] = 1
    fixed = int(np.sum(result) - np.sum(y_pred))
    log.info(f"Propagacja DAG: naprawiono {fixed} niespójnych etykiet.")
    return result


def count_dag_inconsistencies(
    y_prob: np.ndarray,
    dag: nx.DiGraph,
    class_columns: List[str],
) -> int:
    """Liczy pary (próbka, krawędź) gdzie P(dziecko) > P(rodzic)."""
    col_to_idx = {col: i for i, col in enumerate(class_columns)}
    total = 0
    for child, parent in dag.edges():
        if child not in col_to_idx or parent not in col_to_idx:
            continue
        total += int(np.sum(
            y_prob[:, col_to_idx[child]] > y_prob[:, col_to_idx[parent]]
        ))
    return total

In [102]:
# ============================================================
# CELL 5 — Konfiguracja LightGBM
# ============================================================
LGBM_PARAMS = {
    "objective":         "binary",
    "metric":            "binary_logloss",
    "boosting_type":     "gbdt",
    "num_leaves":        63,
    "learning_rate":     0.05,
    "feature_fraction":  0.8,
    "bagging_fraction":  0.8,
    "bagging_freq":      5,
    "min_child_samples": 20,
    "reg_alpha":         0.1,
    "reg_lambda":        0.1,
    "is_unbalance":      True,  # obsługa niezbalansowanych klas ChEBI
    "verbose":           -1,
    "n_jobs":            -1,
}

N_ESTIMATORS = 300   # zwiększ do 500–1000 na finalnym treningu
EARLY_STOP   = 30    # rundy bez poprawy → stop
THRESHOLD    = 0.5   # próg decyzyjny
F1_PERIOD    = 20    # co ile rund liczyć F1 w callbacku

In [103]:
# ============================================================
# CELL 6 — Callback F1 dla pojedynczego klasyfikatora binarnego
# ============================================================
class F1Callback:
    """Liczy binary F1 na zbiorze testowym co F1_PERIOD rund boostingu."""

    def __init__(self, X_eval, y_eval_col, period=20, threshold=0.5):
        self.X_eval     = X_eval
        self.y_eval_col = y_eval_col
        self.period     = period
        self.threshold  = threshold
        self.history: List[Tuple[int, float]] = []

    def __call__(self, env: lgb.callback.CallbackEnv) -> None:
        if (env.iteration + 1) % self.period != 0:
            return
        y_prob = env.model.predict(self.X_eval)
        y_pred = (y_prob >= self.threshold).astype(int)
        f1 = f1_score(self.y_eval_col, y_pred, average="binary", zero_division=0)
        self.history.append((env.iteration + 1, f1))

In [120]:
# ============================================================
# CELL 7 — Trening: pętla po klasach z monitoringiem F1 macro
# ============================================================

# 1. Instalacja za pomocą %pip (lepiej niż !pip, bo celuje dokładnie w ten kernel)
import tqdm
if hasattr(tqdm, 'notebook'):
    from tqdm import tqdm as tqdm_base
    tqdm = tqdm_base
else:
    from tqdm import tqdm

# 3. Opcjonalne: Sprawdzenie czy import już przechodzi
try:
    import ipywidgets
    print("Sukces: ipywidgets zaimportowane bez restartu!")
except ImportError:
    print("Niestety, dla ipywidgets specyfika widgetów Jupyter może wymagać odświeżenia strony (F5).")
t0 = time.time()

models           = []
f1_per_class     = {}
prob_matrix_test = np.zeros((X_test.shape[0], n_classes), dtype=np.float32)

pbar = tqdm(range(n_classes), desc="Trening klas", unit="klasa", leave=True)

for i in pbar:
    class_name = label_cols[i]
    y_tr_col   = y_train[:, i]
    y_te_col   = y_test[:, i]

    dtrain = lgb.Dataset(X_train, label=y_tr_col, free_raw_data=False)
    deval  = lgb.Dataset(X_test,  label=y_te_col, reference=dtrain, free_raw_data=False)

    f1_cb = F1Callback(X_test, y_te_col, period=F1_PERIOD, threshold=THRESHOLD)

    model = lgb.train(
        params=LGBM_PARAMS,
        train_set=dtrain,
        num_boost_round=N_ESTIMATORS,
        valid_sets=[deval],
        callbacks=[
            lgb.early_stopping(EARLY_STOP, verbose=False),
            lgb.early_stopping(EARLY_STOP, verbose=False),
            f1_cb,
        ],
    )

    models.append(model)

    # Finalne F1 dla tej klasy na zbiorze testowym
    y_prob = model.predict(X_test).astype(np.float32)
    prob_matrix_test[:, i] = y_prob
    f1 = f1_score(y_te_col, (y_prob >= THRESHOLD).astype(int),
                  average="binary", zero_division=0)
    f1_per_class[class_name] = f1

    running_macro = float(np.mean(list(f1_per_class.values())))
    pbar.set_postfix({
        "klasa":    class_name,
        "F1_klasy": f"{f1:.4f}",
        "F1_macro": f"{running_macro:.4f}",
        "drzewa":   model.num_trees(),
    })

pbar.close()

elapsed        = time.time() - t0
final_macro_f1 = float(np.mean(list(f1_per_class.values())))

print(f"\n{'='*55}")
print(f"  TRENING ZAKOŃCZONY  ({elapsed/60:.1f} min)")
print(f"  Macro-averaged F1 (test): {final_macro_f1:.4f}")
print(f"{'='*55}")

sorted_f1 = sorted(f1_per_class.items(), key=lambda x: x[1])
print("\nNajgorsze 5 klas:")
for name, score in sorted_f1[:5]:
    print(f"  {name}: {score:.4f}")
print("\nNajlepsze 5 klas:")
for name, score in sorted_f1[-5:]:
    print(f"  {name}: {score:.4f}")

Sukces: ipywidgets zaimportowane bez restartu!

Trening klas:   0%|          | 0/500 [00:00<?, ?klasa/s]




Trening klas:   0%|          | 0/500 [00:02<?, ?klasa/s, klasa=class_0, F1_klasy=1.0000, F1_macro=1.0000, drzewa=1]




Trening klas:   0%|          | 1/500 [00:02<24:56,  3.00s/klasa, klasa=class_0, F1_klasy=1.0000, F1_macro=1.0000, drzewa=1]

[1]	valid_0's binary_logloss: 0
[2]	valid_0's binary_logloss: 0
[3]	valid_0's binary_logloss: 0
[4]	valid_0's binary_logloss: 0
[5]	valid_0's binary_logloss: 0
[6]	valid_0's binary_logloss: 0
[7]	valid_0's binary_logloss: 0
[8]	valid_0's binary_logloss: 0
[9]	valid_0's binary_logloss: 0
[10]	valid_0's binary_logloss: 0
[11]	valid_0's binary_logloss: 0
[12]	valid_0's binary_logloss: 0
[13]	valid_0's binary_logloss: 0
[14]	valid_0's binary_logloss: 0
[15]	valid_0's binary_logloss: 0
[16]	valid_0's binary_logloss: 0
[17]	valid_0's binary_logloss: 0
[18]	valid_0's binary_logloss: 0
[19]	valid_0's binary_logloss: 0
[20]	valid_0's binary_logloss: 0
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[21]	valid_0's binary_logloss: 0
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[22]	valid_0's binary_logloss: 0
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[23]	valid_0's binary_logloss: 0
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[24]	valid_0's binary_logloss: 0
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[25]	valid_0's binary_logloss: 0
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[26]	valid_0's binary_logloss: 0
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[27]	valid_0's binary_logloss: 0
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[28]	valid_0's binary_logloss: 0
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[29]	valid_0's binary_logloss: 0
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[30]	valid_0's binary_logloss: 0
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[31]	valid_0's binary_logloss: 0
[1]	valid_0's binary_logloss: 0.0360259
[2]	valid_0's binary_logloss: 0.0343935
[3]	valid_0's binary_logloss: 0.0331649
[4]	valid_0's binary_logloss: 0.0321593
[5]	valid_0's binary_logloss: 0.0312026
[6]	valid_0's binary_logloss: 0.0358416
[7]	valid_0's binary_logloss: 0.0346057
[8]	valid_0's binary_logloss: 0.0335054
[9]	valid_0's binary_logloss: 0.0324937
[10]	valid_0's binary_logloss: 0.0315355
[11]	valid_0's binary_logloss: 0.0306579
[12]	valid_0's binary_logloss: 0.0297869
[13]	valid_0's binary_logloss: 0.0289491
[14]	valid_0's binary_logloss: 0.0280962
[15]	valid_0's binary_logloss: 0.0272625
[16]	valid_0's binary_logloss: 0.0266275
[17]	valid_0's binary_logloss: 0.0260306
[18]	valid_0's binary_logloss: 0.0254627
[19]	valid_0's binary_logloss: 0.024966
[20]	valid_0's binary_logloss: 0.0244954
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0239631
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0234317
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.0229179
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0224684
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.0220427
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.0216538
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.0212422
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.0208293
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.0204894
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.0201543
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.0198587
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.0195354
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.0192452
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.0189563
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.0187057
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.0184441
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.0181848
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.0179357
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.0177628
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.0175462
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.017341
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.017182
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.0170082
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.0169303
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.0168344
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.0166935
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.0165766
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.016508
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.0164355
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.0163485
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.0162868
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.0162153
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.016148
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.0160863
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.0160163
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.0159496
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.0158776
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.0158341
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.0158087
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.0157294
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.0157382
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.015687
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.0156381
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.0156121
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.0155763
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.015521
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.0155153
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.0155284
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.0155033
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.0155016
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.0154875
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.0154797
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.0154873
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.0154706
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.0154876
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.0154457
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.0154369
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.015445
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.0154443
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.015449
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.0154775
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.0154757
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.0154783
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.0155117
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.0155335
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.0155663
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.0156162
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.0156137
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.0156483
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.015671
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.0157084
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.0157416
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.0157852
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.0158206
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.015834
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.0158471
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.0158534
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.0158755
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.0159198
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.015966
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.0159833
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.0160068
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.0160421
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.0160456
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.0160711
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

Trening klas:   0%|          | 1/500 [00:08<24:56,  3.00s/klasa, klasa=class_1, F1_klasy=0.9988, F1_macro=0.9994, drzewa=77]




Trening klas:   0%|          | 2/500 [00:08<36:37,  4.41s/klasa, klasa=class_1, F1_klasy=0.9988, F1_macro=0.9994, drzewa=77]

[106]	valid_0's binary_logloss: 0.0160907
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.0161291
[1]	valid_0's binary_logloss: 0.0866751
[2]	valid_0's binary_logloss: 0.0848415
[3]	valid_0's binary_logloss: 0.0840685
[4]	valid_0's binary_logloss: 0.0836208
[5]	valid_0's binary_logloss: 0.0828395
[6]	valid_0's binary_logloss: 0.0832251
[7]	valid_0's binary_logloss: 0.0831984
[8]	valid_0's binary_logloss: 0.0836776
[9]	valid_0's binary_logloss: 0.0839725
[10]	valid_0's binary_logloss: 0.0836089
[11]	valid_0's binary_logloss: 0.0827259
[12]	valid_0's binary_logloss: 0.0824719
[13]	valid_0's binary_logloss: 0.081908
[14]	valid_0's binary_logloss: 0.0814966
[15]	valid_0's binary_logloss: 0.0808376
[16]	valid_0's binary_logloss: 0.0809013
[17]	valid_0's binary_logloss: 0.0803889
[18]	valid_0's binary_logloss: 0.0802883
[19]	valid_0's binary_logloss: 0.0804135
[20]	valid_0's binary_logloss: 0.0799439
[21]	valid_0's binary_logloss: 0.0800023
[22]	valid_0's binary_logloss: 0.0795666
[23]	valid_0's binary_logloss: 0.0793627
[24]	valid_0's binary_logloss: 0.0790836
[25]	valid_0's binary_logloss: 0.0788631
[26]	valid_0's binary_logloss: 0.0787891
[27]	valid_0's binary_logloss: 0.078495
[28]	valid_0's binary_logloss: 0.0785572
[29]	valid_0's binary_logloss: 0.0781956
[30]	valid_0's binary_logloss: 0.0777814
[31]	valid_0's binary_logloss: 0.0771564
[32]	valid_0's binary_logloss: 0.076431
[33]	valid_0's binary_logloss: 0.0759346
[34]	valid_0's binary_logloss: 0.0757263
[35]	valid_0's binary_logloss: 0.0753575
[36]	valid_0's binary_logloss: 0.0753853
[37]	valid_0's binary_logloss: 0.0754111
[38]	valid_0's binary_logloss: 0.0751778
[39]	valid_0's binary_logloss: 0.0751238
[40]	valid_0's binary_logloss: 0.0750567
[41]	valid_0's binary_logloss: 0.0748217
[42]	valid_0's binary_logloss: 0.0745384
[43]	valid_0's binary_logloss: 0.0741022
[44]	valid_0's binary_logloss: 0.0737197
[45]	valid_0's binary_logloss: 0.0734942
[46]	valid_0's binary_logloss: 0.0730956
[47]	valid_0's binary_logloss: 0.072882
[48]	valid_0's binary_logloss: 0.0724751
[49]	valid_0's binary_logloss: 0.0722975
[50]	valid_0's binary_logloss: 0.0717582
[51]	valid_0's binary_logloss: 0.0718462
[52]	valid_0's binary_logloss: 0.0717478
[53]	valid_0's binary_logloss: 0.0716909
[54]	valid_0's binary_logloss: 0.0716914
[55]	valid_0's binary_logloss: 0.0716798
[56]	valid_0's binary_logloss: 0.0714384
[57]	valid_0's binary_logloss: 0.0711422
[58]	valid_0's binary_logloss: 0.0708786
[59]	valid_0's binary_logloss: 0.0704818
[60]	valid_0's binary_logloss: 0.0702979
[61]	valid_0's binary_logloss: 0.0702788
[62]	valid_0's binary_logloss: 0.0704081
[63]	valid_0's binary_logloss: 0.0701384
[64]	valid_0's binary_logloss: 0.0700805
[65]	valid_0's binary_logloss: 0.0702928
[66]	valid_0's binary_logloss: 0.0702516
[67]	valid_0's binary_logloss: 0.0702962
[68]	valid_0's binary_logloss: 0.0702667
[69]	valid_0's binary_logloss: 0.0702211
[70]	valid_0's binary_logloss: 0.0700643
[71]	valid_0's binary_logloss: 0.0701632
[72]	valid_0's binary_logloss: 0.0698317
[73]	valid_0's binary_logloss: 0.0696882
[74]	valid_0's binary_logloss: 0.0696886
[75]	valid_0's binary_logloss: 0.0694852
[76]	valid_0's binary_logloss: 0.0695027
[77]	valid_0's binary_logloss: 0.0693803
[78]	valid_0's binary_logloss: 0.0692568
[79]	valid_0's binary_logloss: 0.069225
[80]	valid_0's binary_logloss: 0.0691999
[81]	valid_0's binary_logloss: 0.0690847
[82]	valid_0's binary_logloss: 0.0691095
[83]	valid_0's binary_logloss: 0.0691136
[84]	valid_0's binary_logloss: 0.0692133
[85]	valid_0's binary_logloss: 0.0691566
[86]	valid_0's binary_logloss: 0.0689645
[87]	valid_0's binary_logloss: 0.0689073
[88]	valid_0's binary_logloss: 0.0688308
[89]	valid_0's binary_logloss: 0.0688451
[90]	valid_0's binary_logloss: 0.0688713
[91]	valid_0's binary_logloss: 0.0690684
[92]	valid_0's binary_logloss: 0.0694226
[93]	valid_0's binary_logloss: 0.0696958
[94]	valid_0's binary_logloss: 0.0696545
[95]	valid_0's binary_logloss: 0.069729
[96]	valid_0's binary_logloss: 0.0697619
[97]	valid_0's binary_logloss: 0.0696032
[98]	valid_0's binary_logloss: 0.0695677
[99]	valid_0's binary_logloss: 0.0697065
[100]	valid_0's binary_logloss: 0.0697065
[101]	valid_0's binary_logloss: 0.0697086
[102]	valid_0's binary_logloss: 0.0699127
[103]	valid_0's binary_logloss: 0.0699414
[104]	valid_0's binary_logloss: 0.0700509
[105]	valid_0's binary_logloss: 0.070068
[106]	valid_0's binary_logloss: 0.0700847
[107]	valid_0's binary_logloss: 0.0703445
[108]	valid_0's binary_logloss: 0.0706169
[109]	valid_0's binary_logloss: 0.0708581
[110]	valid_0's binary_logloss: 0.0709873
[111]	valid_0's binary_logloss: 0.0710643
[112]	valid_0's binary_logloss: 0.0712169
[113]	valid_0's binary_logloss: 0.071419
[114]	valid_0's binary_logloss: 0.0715999
[115]	valid_0's binary_logloss: 0.0717262
[116]	valid_0's binary_logloss: 0.0719056
[117]	valid_0's binary_logloss: 0.0721363
[118]	valid_0's binary_logloss: 0.0723317

Trening klas:   0%|          | 2/500 [00:16<36:37,  4.41s/klasa, klasa=class_2, F1_klasy=0.9907, F1_macro=0.9965, drzewa=88]




Trening klas:   1%|          | 3/500 [00:16<51:29,  6.22s/klasa, klasa=class_2, F1_klasy=0.9907, F1_macro=0.9965, drzewa=88]

[1]	valid_0's binary_logloss: 0.108135
[2]	valid_0's binary_logloss: 0.106113
[3]	valid_0's binary_logloss: 0.104284
[4]	valid_0's binary_logloss: 0.10306
[5]	valid_0's binary_logloss: 0.102793
[6]	valid_0's binary_logloss: 0.103361
[7]	valid_0's binary_logloss: 0.103678
[8]	valid_0's binary_logloss: 0.103442
[9]	valid_0's binary_logloss: 0.103422
[10]	valid_0's binary_logloss: 0.103943
[11]	valid_0's binary_logloss: 0.103187
[12]	valid_0's binary_logloss: 0.102664
[13]	valid_0's binary_logloss: 0.102289
[14]	valid_0's binary_logloss: 0.101922
[15]	valid_0's binary_logloss: 0.101649
[16]	valid_0's binary_logloss: 0.101186
[17]	valid_0's binary_logloss: 0.100707
[18]	valid_0's binary_logloss: 0.100518
[19]	valid_0's binary_logloss: 0.100576
[20]	valid_0's binary_logloss: 0.0999885
[21]	valid_0's binary_logloss: 0.0993456
[22]	valid_0's binary_logloss: 0.0987371
[23]	valid_0's binary_logloss: 0.0978955
[24]	valid_0's binary_logloss: 0.0975852
[25]	valid_0's binary_logloss: 0.0972258
[26]	valid_0's binary_logloss: 0.0969567
[27]	valid_0's binary_logloss: 0.0964996
[28]	valid_0's binary_logloss: 0.0965442
[29]	valid_0's binary_logloss: 0.0964702
[30]	valid_0's binary_logloss: 0.0963694
[31]	valid_0's binary_logloss: 0.0955174
[32]	valid_0's binary_logloss: 0.0946732
[33]	valid_0's binary_logloss: 0.0940632
[34]	valid_0's binary_logloss: 0.0937599
[35]	valid_0's binary_logloss: 0.0933805
[36]	valid_0's binary_logloss: 0.0934852
[37]	valid_0's binary_logloss: 0.0936167
[38]	valid_0's binary_logloss: 0.0934675
[39]	valid_0's binary_logloss: 0.0937452
[40]	valid_0's binary_logloss: 0.0934407
[41]	valid_0's binary_logloss: 0.0934384
[42]	valid_0's binary_logloss: 0.0935041
[43]	valid_0's binary_logloss: 0.0933402
[44]	valid_0's binary_logloss: 0.0933422
[45]	valid_0's binary_logloss: 0.0934854
[46]	valid_0's binary_logloss: 0.0933837
[47]	valid_0's binary_logloss: 0.093534
[48]	valid_0's binary_logloss: 0.0936179
[49]	valid_0's binary_logloss: 0.0934127
[50]	valid_0's binary_logloss: 0.0933416
[51]	valid_0's binary_logloss: 0.0935264
[52]	valid_0's binary_logloss: 0.0933183
[53]	valid_0's binary_logloss: 0.0930627
[54]	valid_0's binary_logloss: 0.0926008
[55]	valid_0's binary_logloss: 0.092463
[56]	valid_0's binary_logloss: 0.0919827
[57]	valid_0's binary_logloss: 0.0920704
[58]	valid_0's binary_logloss: 0.0916523
[59]	valid_0's binary_logloss: 0.0915221
[60]	valid_0's binary_logloss: 0.0909734
[61]	valid_0's binary_logloss: 0.0903777
[62]	valid_0's binary_logloss: 0.0899849
[63]	valid_0's binary_logloss: 0.0894772
[64]	valid_0's binary_logloss: 0.0889646
[65]	valid_0's binary_logloss: 0.0890018
[66]	valid_0's binary_logloss: 0.0886044
[67]	valid_0's binary_logloss: 0.0885254
[68]	valid_0's binary_logloss: 0.0883713
[69]	valid_0's binary_logloss: 0.0881344
[70]	valid_0's binary_logloss: 0.0878319
[71]	valid_0's binary_logloss: 0.087665
[72]	valid_0's binary_logloss: 0.0873625
[73]	valid_0's binary_logloss: 0.0869584
[74]	valid_0's binary_logloss: 0.0868025
[75]	valid_0's binary_logloss: 0.0868433
[76]	valid_0's binary_logloss: 0.0866778
[77]	valid_0's binary_logloss: 0.0866617
[78]	valid_0's binary_logloss: 0.0865567
[79]	valid_0's binary_logloss: 0.0862656
[80]	valid_0's binary_logloss: 0.0860155
[81]	valid_0's binary_logloss: 0.0858298
[82]	valid_0's binary_logloss: 0.0856
[83]	valid_0's binary_logloss: 0.0855516
[84]	valid_0's binary_logloss: 0.0853116
[85]	valid_0's binary_logloss: 0.085163
[86]	valid_0's binary_logloss: 0.0849437
[87]	valid_0's binary_logloss: 0.0846281
[88]	valid_0's binary_logloss: 0.0842337
[89]	valid_0's binary_logloss: 0.0840704
[90]	valid_0's binary_logloss: 0.083898
[91]	valid_0's binary_logloss: 0.0840506
[92]	valid_0's binary_logloss: 0.083957
[93]	valid_0's binary_logloss: 0.0839465
[94]	valid_0's binary_logloss: 0.0837696
[95]	valid_0's binary_logloss: 0.0838045
[96]	valid_0's binary_logloss: 0.0835485
[97]	valid_0's binary_logloss: 0.0834746
[98]	valid_0's binary_logloss: 0.0833857
[99]	valid_0's binary_logloss: 0.0832832
[100]	valid_0's binary_logloss: 0.0830426
[101]	valid_0's binary_logloss: 0.0826772
[102]	valid_0's binary_logloss: 0.0822531
[103]	valid_0's binary_logloss: 0.0819795
[104]	valid_0's binary_logloss: 0.0818354
[105]	valid_0's binary_logloss: 0.0816503
[106]	valid_0's binary_logloss: 0.0817237
[107]	valid_0's binary_logloss: 0.0815001
[108]	valid_0's binary_logloss: 0.0815637
[109]	valid_0's binary_logloss: 0.0814811
[110]	valid_0's binary_logloss: 0.0813952
[111]	valid_0's binary_logloss: 0.0815772
[112]	valid_0's binary_logloss: 0.081487
[113]	valid_0's binary_logloss: 0.0816173
[114]	valid_0's binary_logloss: 0.0817882
[115]	valid_0's binary_logloss: 0.0819091
[116]	valid_0's binary_logloss: 0.081589
[117]	valid_0's binary_logloss: 0.08141
[118]	valid_0's binary_logloss: 0.0812923
[119]	valid_0's binary_logloss: 0.0811421
[120]	valid_0's binary_logloss: 0.080993
[121]	valid_0's binary_logloss: 0.0809111
[122]	valid_0's binary_logloss: 0.081116
[123]	valid_0's binary_logloss: 0.0812766
[124]	valid_0's binary_logloss: 0.0814706
[125]	valid_0's binary_logloss: 0.0815668
[126]	valid_0's binary_logloss: 0.0814993
[127]	valid_0's binary_logloss: 0.0812445
[128]	valid_0's binary_logloss: 0.0811704
[129]	valid_0's binary_logloss: 0.0814521
[130]	valid_0's binary_logloss: 0.0815943
[131]	valid_0's binary_logloss: 0.0817183
[132]	valid_0's binary_logloss: 0.0820004
[133]	valid_0's binary_logloss: 0.0821718
[134]	valid_0's binary_logloss: 0.0822509
[135]	valid_0's binary_logloss: 0.0821929
[136]	valid_0's binary_logloss: 0.0821987
[137]	valid_0's binary_logloss: 0.0821486
[138]	valid_0's binary_logloss: 0.0822205
[139]	valid_0's binary_logloss: 0.0821192
[140]	valid_0's binary_logloss: 0.0819731
[141]	valid_0's binary_logloss: 0.0818268
[142]	valid_0's binary_logloss: 0.0819394
[143]	valid_0's binary_logloss: 0.0821004
[144]	valid_0's binary_logloss: 0.0822852
[145]	valid_0's binary_logloss: 0.082243
[146]	valid_0's binary_logloss: 0.0822162
[147]	valid_0's binary_logloss: 0.08236
[148]	valid_0's binary_logloss: 0.0820878

Trening klas:   1%|          | 3/500 [00:27<51:29,  6.22s/klasa, klasa=class_3, F1_klasy=0.9868, F1_macro=0.9941, drzewa=121]




Trening klas:   1%|          | 4/500 [00:27<1:05:53,  7.97s/klasa, klasa=class_3, F1_klasy=0.9868, F1_macro=0.9941, drzewa=121]

[149]	valid_0's binary_logloss: 0.0818825
[150]	valid_0's binary_logloss: 0.0817539
[151]	valid_0's binary_logloss: 0.0819931
[1]	valid_0's binary_logloss: 0.207578
[2]	valid_0's binary_logloss: 0.20479
[3]	valid_0's binary_logloss: 0.204021
[4]	valid_0's binary_logloss: 0.202857
[5]	valid_0's binary_logloss: 0.202824
[6]	valid_0's binary_logloss: 0.204224
[7]	valid_0's binary_logloss: 0.20624
[8]	valid_0's binary_logloss: 0.208276
[9]	valid_0's binary_logloss: 0.209564
[10]	valid_0's binary_logloss: 0.212376
[11]	valid_0's binary_logloss: 0.213741
[12]	valid_0's binary_logloss: 0.215402
[13]	valid_0's binary_logloss: 0.216752
[14]	valid_0's binary_logloss: 0.217879
[15]	valid_0's binary_logloss: 0.218252
[16]	valid_0's binary_logloss: 0.219679
[17]	valid_0's binary_logloss: 0.220106
[18]	valid_0's binary_logloss: 0.219826
[19]	valid_0's binary_logloss: 0.219762
[20]	valid_0's binary_logloss: 0.219697
[21]	valid_0's binary_logloss: 0.22051
[22]	valid_0's binary_logloss: 0.221929
[23]	valid_0's binary_logloss: 0.221819
[24]	valid_0's binary_logloss: 0.222401
[25]	valid_0's binary_logloss: 0.222064
[26]	valid_0's binary_logloss: 0.222485
[27]	valid_0's binary_logloss: 0.223239
[28]	valid_0's binary_logloss: 0.22355
[29]	valid_0's binary_logloss: 0.223729
[30]	valid_0's binary_logloss: 0.223673
[31]	valid_0's binary_logloss: 0.224554
[32]	valid_0's binary_logloss: 0.225407
[33]	valid_0's binary_logloss: 0.224927
[34]	valid_0's binary_logloss: 0.225199
[35]	valid_0's binary_logloss: 0.225311

Trening klas:   1%|          | 4/500 [00:31<1:05:53,  7.97s/klasa, klasa=class_4, F1_klasy=0.9726, F1_macro=0.9898, drzewa=5]




Trening klas:   1%|          | 5/500 [00:31<54:33,  6.61s/klasa, klasa=class_4, F1_klasy=0.9726, F1_macro=0.9898, drzewa=5]

[1]	valid_0's binary_logloss: 0.209407
[2]	valid_0's binary_logloss: 0.206605
[3]	valid_0's binary_logloss: 0.205257
[4]	valid_0's binary_logloss: 0.20432
[5]	valid_0's binary_logloss: 0.204648
[6]	valid_0's binary_logloss: 0.206572
[7]	valid_0's binary_logloss: 0.208189
[8]	valid_0's binary_logloss: 0.209848
[9]	valid_0's binary_logloss: 0.210803
[10]	valid_0's binary_logloss: 0.212494
[11]	valid_0's binary_logloss: 0.213807
[12]	valid_0's binary_logloss: 0.215695
[13]	valid_0's binary_logloss: 0.217007
[14]	valid_0's binary_logloss: 0.217464
[15]	valid_0's binary_logloss: 0.218443
[16]	valid_0's binary_logloss: 0.219167
[17]	valid_0's binary_logloss: 0.220112
[18]	valid_0's binary_logloss: 0.221659
[19]	valid_0's binary_logloss: 0.221731
[20]	valid_0's binary_logloss: 0.221659
[21]	valid_0's binary_logloss: 0.222222
[22]	valid_0's binary_logloss: 0.222841
[23]	valid_0's binary_logloss: 0.223647
[24]	valid_0's binary_logloss: 0.224574
[25]	valid_0's binary_logloss: 0.224817
[26]	valid_0's binary_logloss: 0.224441
[27]	valid_0's binary_logloss: 0.22505
[28]	valid_0's binary_logloss: 0.225215
[29]	valid_0's binary_logloss: 0.225187
[30]	valid_0's binary_logloss: 0.224933
[31]	valid_0's binary_logloss: 0.224973
[32]	valid_0's binary_logloss: 0.225391
[33]	valid_0's binary_logloss: 0.225826
[34]	valid_0's binary_logloss: 0.226621

Trening klas:   1%|          | 5/500 [00:35<54:33,  6.61s/klasa, klasa=class_5, F1_klasy=0.9724, F1_macro=0.9869, drzewa=4]




Trening klas:   1%|          | 6/500 [00:35<47:14,  5.74s/klasa, klasa=class_5, F1_klasy=0.9724, F1_macro=0.9869, drzewa=4]

[1]	valid_0's binary_logloss: 0.420707
[2]	valid_0's binary_logloss: 0.405326
[3]	valid_0's binary_logloss: 0.392596
[4]	valid_0's binary_logloss: 0.382222
[5]	valid_0's binary_logloss: 0.372686
[6]	valid_0's binary_logloss: 0.364253
[7]	valid_0's binary_logloss: 0.35722
[8]	valid_0's binary_logloss: 0.348472
[9]	valid_0's binary_logloss: 0.343141
[10]	valid_0's binary_logloss: 0.338421
[11]	valid_0's binary_logloss: 0.332441
[12]	valid_0's binary_logloss: 0.326513
[13]	valid_0's binary_logloss: 0.321661
[14]	valid_0's binary_logloss: 0.317818
[15]	valid_0's binary_logloss: 0.313997
[16]	valid_0's binary_logloss: 0.312558
[17]	valid_0's binary_logloss: 0.309821
[18]	valid_0's binary_logloss: 0.307377
[19]	valid_0's binary_logloss: 0.30406
[20]	valid_0's binary_logloss: 0.301849
[21]	valid_0's binary_logloss: 0.299617
[22]	valid_0's binary_logloss: 0.297462
[23]	valid_0's binary_logloss: 0.29523
[24]	valid_0's binary_logloss: 0.294065
[25]	valid_0's binary_logloss: 0.291734
[26]	valid_0's binary_logloss: 0.289946
[27]	valid_0's binary_logloss: 0.288503
[28]	valid_0's binary_logloss: 0.288082
[29]	valid_0's binary_logloss: 0.286315
[30]	valid_0's binary_logloss: 0.284397
[31]	valid_0's binary_logloss: 0.282724
[32]	valid_0's binary_logloss: 0.281245
[33]	valid_0's binary_logloss: 0.280154
[34]	valid_0's binary_logloss: 0.279126
[35]	valid_0's binary_logloss: 0.277646
[36]	valid_0's binary_logloss: 0.275937
[37]	valid_0's binary_logloss: 0.274565
[38]	valid_0's binary_logloss: 0.273029
[39]	valid_0's binary_logloss: 0.271891
[40]	valid_0's binary_logloss: 0.270814
[41]	valid_0's binary_logloss: 0.26968
[42]	valid_0's binary_logloss: 0.268672
[43]	valid_0's binary_logloss: 0.267838
[44]	valid_0's binary_logloss: 0.267471
[45]	valid_0's binary_logloss: 0.266701
[46]	valid_0's binary_logloss: 0.265283
[47]	valid_0's binary_logloss: 0.264108
[48]	valid_0's binary_logloss: 0.26244
[49]	valid_0's binary_logloss: 0.261127
[50]	valid_0's binary_logloss: 0.260385
[51]	valid_0's binary_logloss: 0.259789
[52]	valid_0's binary_logloss: 0.259298
[53]	valid_0's binary_logloss: 0.25884
[54]	valid_0's binary_logloss: 0.25783
[55]	valid_0's binary_logloss: 0.257114
[56]	valid_0's binary_logloss: 0.256316
[57]	valid_0's binary_logloss: 0.255777
[58]	valid_0's binary_logloss: 0.254754
[59]	valid_0's binary_logloss: 0.253577
[60]	valid_0's binary_logloss: 0.253372
[61]	valid_0's binary_logloss: 0.252259
[62]	valid_0's binary_logloss: 0.251494
[63]	valid_0's binary_logloss: 0.25081
[64]	valid_0's binary_logloss: 0.250484
[65]	valid_0's binary_logloss: 0.24989
[66]	valid_0's binary_logloss: 0.249258
[67]	valid_0's binary_logloss: 0.248736
[68]	valid_0's binary_logloss: 0.248263
[69]	valid_0's binary_logloss: 0.247677
[70]	valid_0's binary_logloss: 0.247133
[71]	valid_0's binary_logloss: 0.246207
[72]	valid_0's binary_logloss: 0.245311
[73]	valid_0's binary_logloss: 0.244201
[74]	valid_0's binary_logloss: 0.243211
[75]	valid_0's binary_logloss: 0.242565
[76]	valid_0's binary_logloss: 0.241623
[77]	valid_0's binary_logloss: 0.240791
[78]	valid_0's binary_logloss: 0.240266
[79]	valid_0's binary_logloss: 0.239262
[80]	valid_0's binary_logloss: 0.2389
[81]	valid_0's binary_logloss: 0.23783
[82]	valid_0's binary_logloss: 0.237538
[83]	valid_0's binary_logloss: 0.237082
[84]	valid_0's binary_logloss: 0.236762
[85]	valid_0's binary_logloss: 0.236735
[86]	valid_0's binary_logloss: 0.236009
[87]	valid_0's binary_logloss: 0.235653
[88]	valid_0's binary_logloss: 0.235361
[89]	valid_0's binary_logloss: 0.234903
[90]	valid_0's binary_logloss: 0.234678
[91]	valid_0's binary_logloss: 0.233769
[92]	valid_0's binary_logloss: 0.233301
[93]	valid_0's binary_logloss: 0.232676
[94]	valid_0's binary_logloss: 0.231866
[95]	valid_0's binary_logloss: 0.231724
[96]	valid_0's binary_logloss: 0.23109
[97]	valid_0's binary_logloss: 0.230557
[98]	valid_0's binary_logloss: 0.229842
[99]	valid_0's binary_logloss: 0.229543
[100]	valid_0's binary_logloss: 0.229071
[101]	valid_0's binary_logloss: 0.228055
[102]	valid_0's binary_logloss: 0.227733
[103]	valid_0's binary_logloss: 0.227156
[104]	valid_0's binary_logloss: 0.226786
[105]	valid_0's binary_logloss: 0.226025
[106]	valid_0's binary_logloss: 0.225747
[107]	valid_0's binary_logloss: 0.225354
[108]	valid_0's binary_logloss: 0.225136
[109]	valid_0's binary_logloss: 0.22468
[110]	valid_0's binary_logloss: 0.224508
[111]	valid_0's binary_logloss: 0.224279
[112]	valid_0's binary_logloss: 0.223701
[113]	valid_0's binary_logloss: 0.223491
[114]	valid_0's binary_logloss: 0.222936
[115]	valid_0's binary_logloss: 0.22279
[116]	valid_0's binary_logloss: 0.222266
[117]	valid_0's binary_logloss: 0.221719
[118]	valid_0's binary_logloss: 0.221451
[119]	valid_0's binary_logloss: 0.221192
[120]	valid_0's binary_logloss: 0.220933
[121]	valid_0's binary_logloss: 0.220643
[122]	valid_0's binary_logloss: 0.220627
[123]	valid_0's binary_logloss: 0.220579
[124]	valid_0's binary_logloss: 0.220389
[125]	valid_0's binary_logloss: 0.219884
[126]	valid_0's binary_logloss: 0.219801
[127]	valid_0's binary_logloss: 0.219415
[128]	valid_0's binary_logloss: 0.219243
[129]	valid_0's binary_logloss: 0.218955
[130]	valid_0's binary_logloss: 0.218675
[131]	valid_0's binary_logloss: 0.218422
[132]	valid_0's binary_logloss: 0.21805
[133]	valid_0's binary_logloss: 0.217685
[134]	valid_0's binary_logloss: 0.21729
[135]	valid_0's binary_logloss: 0.217229
[136]	valid_0's binary_logloss: 0.216794
[137]	valid_0's binary_logloss: 0.216588
[138]	valid_0's binary_logloss: 0.216611
[139]	valid_0's binary_logloss: 0.216315
[140]	valid_0's binary_logloss: 0.216089
[141]	valid_0's binary_logloss: 0.2157
[142]	valid_0's binary_logloss: 0.215544
[143]	valid_0's binary_logloss: 0.215671
[144]	valid_0's binary_logloss: 0.215606
[145]	valid_0's binary_logloss: 0.215164
[146]	valid_0's binary_logloss: 0.21512
[147]	valid_0's binary_logloss: 0.214811
[148]	valid_0's binary_logloss: 0.2147
[149]	valid_0's binary_logloss: 0.214487
[150]	valid_0's binary_logloss: 0.214171
[151]	valid_0's binary_logloss: 0.213966
[152]	valid_0's binary_logloss: 0.21393
[153]	valid_0's binary_logloss: 0.213673
[154]	valid_0's binary_logloss: 0.213335
[155]	valid_0's binary_logloss: 0.212735
[156]	valid_0's binary_logloss: 0.212695
[157]	valid_0's binary_logloss: 0.212764
[158]	valid_0's binary_logloss: 0.212623
[159]	valid_0's binary_logloss: 0.212643
[160]	valid_0's binary_logloss: 0.212507
[161]	valid_0's binary_logloss: 0.212413
[162]	valid_0's binary_logloss: 0.212381
[163]	valid_0's binary_logloss: 0.212479
[164]	valid_0's binary_logloss: 0.212518
[165]	valid_0's binary_logloss: 0.212518
[166]	valid_0's binary_logloss: 0.212558
[167]	valid_0's binary_logloss: 0.212475
[168]	valid_0's binary_logloss: 0.212488
[169]	valid_0's binary_logloss: 0.212414
[170]	valid_0's binary_logloss: 0.212098
[171]	valid_0's binary_logloss: 0.211749
[172]	valid_0's binary_logloss: 0.211542
[173]	valid_0's binary_logloss: 0.211446
[174]	valid_0's binary_logloss: 0.211172
[175]	valid_0's binary_logloss: 0.211277
[176]	valid_0's binary_logloss: 0.211075
[177]	valid_0's binary_logloss: 0.211041
[178]	valid_0's binary_logloss: 0.210823
[179]	valid_0's binary_logloss: 0.210661
[180]	valid_0's binary_logloss: 0.210692
[181]	valid_0's binary_logloss: 0.210529
[182]	valid_0's binary_logloss: 0.210317
[183]	valid_0's binary_logloss: 0.210226
[184]	valid_0's binary_logloss: 0.210088
[185]	valid_0's binary_logloss: 0.209941
[186]	valid_0's binary_logloss: 0.209757
[187]	valid_0's binary_logloss: 0.209621
[188]	valid_0's binary_logloss: 0.209461
[189]	valid_0's binary_logloss: 0.209302
[190]	valid_0's binary_logloss: 0.209099
[191]	valid_0's binary_logloss: 0.209115
[192]	valid_0's binary_logloss: 0.209085
[193]	valid_0's binary_logloss: 0.20908
[194]	valid_0's binary_logloss: 0.208985
[195]	valid_0's binary_logloss: 0.208848
[196]	valid_0's binary_logloss: 0.208908
[197]	valid_0's binary_logloss: 0.208782
[198]	valid_0's binary_logloss: 0.208825
[199]	valid_0's binary_logloss: 0.20892
[200]	valid_0's binary_logloss: 0.208952
[201]	valid_0's binary_logloss: 0.208803
[202]	valid_0's binary_logloss: 0.20858
[203]	valid_0's binary_logloss: 0.208457
[204]	valid_0's binary_logloss: 0.208438
[205]	valid_0's binary_logloss: 0.208321
[206]	valid_0's binary_logloss: 0.208184
[207]	valid_0's binary_logloss: 0.207904
[208]	valid_0's binary_logloss: 0.20783
[209]	valid_0's binary_logloss: 0.207805
[210]	valid_0's binary_logloss: 0.207846
[211]	valid_0's binary_logloss: 0.207807
[212]	valid_0's binary_logloss: 0.207815
[213]	valid_0's binary_logloss: 0.20776
[214]	valid_0's binary_logloss: 0.207885
[215]	valid_0's binary_logloss: 0.207824
[216]	valid_0's binary_logloss: 0.207758
[217]	valid_0's binary_logloss: 0.207708
[218]	valid_0's binary_logloss: 0.20779
[219]	valid_0's binary_logloss: 0.20789
[220]	valid_0's binary_logloss: 0.207991
[221]	valid_0's binary_logloss: 0.208098
[222]	valid_0's binary_logloss: 0.207964
[223]	valid_0's binary_logloss: 0.208136
[224]	valid_0's binary_logloss: 0.208113
[225]	valid_0's binary_logloss: 0.20826
[226]	valid_0's binary_logloss: 0.20844
[227]	valid_0's binary_logloss: 0.208432
[228]	valid_0's binary_logloss: 0.208496
[229]	valid_0's binary_logloss: 0.208401
[230]	valid_0's binary_logloss: 0.208444
[231]	valid_0's binary_logloss: 0.208523
[232]	valid_0's binary_logloss: 0.208508
[233]	valid_0's binary_logloss: 0.208644
[234]	valid_0's binary_logloss: 0.208666
[235]	valid_0's binary_logloss: 0.208773
[236]	valid_0's binary_logloss: 0.208584
[237]	valid_0's binary_logloss: 0.208607
[238]	valid_0's binary_logloss: 0.208617
[239]	valid_0's binary_logloss: 0.208705
[240]	valid_0's binary_logloss: 0.208948
[241]	valid_0's binary_logloss: 0.208906
[242]	valid_0's binary_logloss: 0.208996
[243]	valid_0's binary_logloss: 0.208958
[244]	valid_0's binary_logloss: 0.208857
[245]	valid_0's binary_logloss: 0.208874
[246]	valid_0's binary_logloss: 0.2089
[247]	valid_0's binary_logloss: 0.208926

Trening klas:   1%|          | 6/500 [00:53<47:14,  5.74s/klasa, klasa=class_6, F1_klasy=0.9553, F1_macro=0.9824, drzewa=217]




Trening klas:   1%|▏         | 7/500 [00:53<1:20:20,  9.78s/klasa, klasa=class_6, F1_klasy=0.9553, F1_macro=0.9824, drzewa=217]

[1]	valid_0's binary_logloss: 0.562123
[2]	valid_0's binary_logloss: 0.539135
[3]	valid_0's binary_logloss: 0.518051
[4]	valid_0's binary_logloss: 0.500551
[5]	valid_0's binary_logloss: 0.484998
[6]	valid_0's binary_logloss: 0.470951
[7]	valid_0's binary_logloss: 0.457919
[8]	valid_0's binary_logloss: 0.446401
[9]	valid_0's binary_logloss: 0.435812
[10]	valid_0's binary_logloss: 0.426705
[11]	valid_0's binary_logloss: 0.41864
[12]	valid_0's binary_logloss: 0.410082
[13]	valid_0's binary_logloss: 0.402609
[14]	valid_0's binary_logloss: 0.395743
[15]	valid_0's binary_logloss: 0.388969
[16]	valid_0's binary_logloss: 0.382562
[17]	valid_0's binary_logloss: 0.377077
[18]	valid_0's binary_logloss: 0.37162
[19]	valid_0's binary_logloss: 0.3666
[20]	valid_0's binary_logloss: 0.361752
[21]	valid_0's binary_logloss: 0.357272
[22]	valid_0's binary_logloss: 0.353262
[23]	valid_0's binary_logloss: 0.34977
[24]	valid_0's binary_logloss: 0.345979
[25]	valid_0's binary_logloss: 0.342856
[26]	valid_0's binary_logloss: 0.339219
[27]	valid_0's binary_logloss: 0.336459
[28]	valid_0's binary_logloss: 0.333971
[29]	valid_0's binary_logloss: 0.331117
[30]	valid_0's binary_logloss: 0.328654
[31]	valid_0's binary_logloss: 0.326377
[32]	valid_0's binary_logloss: 0.323671
[33]	valid_0's binary_logloss: 0.321711
[34]	valid_0's binary_logloss: 0.31993
[35]	valid_0's binary_logloss: 0.318276
[36]	valid_0's binary_logloss: 0.316862
[37]	valid_0's binary_logloss: 0.315256
[38]	valid_0's binary_logloss: 0.313426
[39]	valid_0's binary_logloss: 0.31169
[40]	valid_0's binary_logloss: 0.310496
[41]	valid_0's binary_logloss: 0.309108
[42]	valid_0's binary_logloss: 0.307476
[43]	valid_0's binary_logloss: 0.306402
[44]	valid_0's binary_logloss: 0.30497
[45]	valid_0's binary_logloss: 0.30379
[46]	valid_0's binary_logloss: 0.302517
[47]	valid_0's binary_logloss: 0.301583
[48]	valid_0's binary_logloss: 0.300754
[49]	valid_0's binary_logloss: 0.299602
[50]	valid_0's binary_logloss: 0.298412
[51]	valid_0's binary_logloss: 0.297354
[52]	valid_0's binary_logloss: 0.296565
[53]	valid_0's binary_logloss: 0.295684
[54]	valid_0's binary_logloss: 0.29478
[55]	valid_0's binary_logloss: 0.2942
[56]	valid_0's binary_logloss: 0.293558
[57]	valid_0's binary_logloss: 0.292665
[58]	valid_0's binary_logloss: 0.29174
[59]	valid_0's binary_logloss: 0.29048
[60]	valid_0's binary_logloss: 0.289325
[61]	valid_0's binary_logloss: 0.289022
[62]	valid_0's binary_logloss: 0.288354
[63]	valid_0's binary_logloss: 0.288012
[64]	valid_0's binary_logloss: 0.287863
[65]	valid_0's binary_logloss: 0.287749
[66]	valid_0's binary_logloss: 0.287112
[67]	valid_0's binary_logloss: 0.28662
[68]	valid_0's binary_logloss: 0.286093
[69]	valid_0's binary_logloss: 0.285973
[70]	valid_0's binary_logloss: 0.285678
[71]	valid_0's binary_logloss: 0.285451
[72]	valid_0's binary_logloss: 0.28544
[73]	valid_0's binary_logloss: 0.285251
[74]	valid_0's binary_logloss: 0.284503
[75]	valid_0's binary_logloss: 0.28394
[76]	valid_0's binary_logloss: 0.283127
[77]	valid_0's binary_logloss: 0.282226
[78]	valid_0's binary_logloss: 0.281449
[79]	valid_0's binary_logloss: 0.280781
[80]	valid_0's binary_logloss: 0.279729
[81]	valid_0's binary_logloss: 0.279413
[82]	valid_0's binary_logloss: 0.278665
[83]	valid_0's binary_logloss: 0.278168
[84]	valid_0's binary_logloss: 0.277715
[85]	valid_0's binary_logloss: 0.277406
[86]	valid_0's binary_logloss: 0.276868
[87]	valid_0's binary_logloss: 0.276295
[88]	valid_0's binary_logloss: 0.275497
[89]	valid_0's binary_logloss: 0.275051
[90]	valid_0's binary_logloss: 0.274411
[91]	valid_0's binary_logloss: 0.27417
[92]	valid_0's binary_logloss: 0.273502
[93]	valid_0's binary_logloss: 0.273495
[94]	valid_0's binary_logloss: 0.273045
[95]	valid_0's binary_logloss: 0.272688
[96]	valid_0's binary_logloss: 0.272194
[97]	valid_0's binary_logloss: 0.271887
[98]	valid_0's binary_logloss: 0.271428
[99]	valid_0's binary_logloss: 0.270988
[100]	valid_0's binary_logloss: 0.270729
[101]	valid_0's binary_logloss: 0.270631
[102]	valid_0's binary_logloss: 0.2704
[103]	valid_0's binary_logloss: 0.270116
[104]	valid_0's binary_logloss: 0.269704
[105]	valid_0's binary_logloss: 0.269197
[106]	valid_0's binary_logloss: 0.268617
[107]	valid_0's binary_logloss: 0.268237
[108]	valid_0's binary_logloss: 0.267954
[109]	valid_0's binary_logloss: 0.267912
[110]	valid_0's binary_logloss: 0.267702
[111]	valid_0's binary_logloss: 0.267533
[112]	valid_0's binary_logloss: 0.267467
[113]	valid_0's binary_logloss: 0.267116
[114]	valid_0's binary_logloss: 0.266907
[115]	valid_0's binary_logloss: 0.26696
[116]	valid_0's binary_logloss: 0.266639
[117]	valid_0's binary_logloss: 0.266286
[118]	valid_0's binary_logloss: 0.265749
[119]	valid_0's binary_logloss: 0.26529
[120]	valid_0's binary_logloss: 0.265031
[121]	valid_0's binary_logloss: 0.264771
[122]	valid_0's binary_logloss: 0.264645
[123]	valid_0's binary_logloss: 0.264561
[124]	valid_0's binary_logloss: 0.264543
[125]	valid_0's binary_logloss: 0.264409
[126]	valid_0's binary_logloss: 0.264471
[127]	valid_0's binary_logloss: 0.26457
[128]	valid_0's binary_logloss: 0.2642
[129]	valid_0's binary_logloss: 0.264158
[130]	valid_0's binary_logloss: 0.264351
[131]	valid_0's binary_logloss: 0.26408
[132]	valid_0's binary_logloss: 0.263825
[133]	valid_0's binary_logloss: 0.263873
[134]	valid_0's binary_logloss: 0.263651
[135]	valid_0's binary_logloss: 0.263405
[136]	valid_0's binary_logloss: 0.263198
[137]	valid_0's binary_logloss: 0.262836
[138]	valid_0's binary_logloss: 0.262566
[139]	valid_0's binary_logloss: 0.262377
[140]	valid_0's binary_logloss: 0.262386
[141]	valid_0's binary_logloss: 0.261979
[142]	valid_0's binary_logloss: 0.261601
[143]	valid_0's binary_logloss: 0.261413
[144]	valid_0's binary_logloss: 0.261139
[145]	valid_0's binary_logloss: 0.260827
[146]	valid_0's binary_logloss: 0.260288
[147]	valid_0's binary_logloss: 0.260221
[148]	valid_0's binary_logloss: 0.260095
[149]	valid_0's binary_logloss: 0.259971
[150]	valid_0's binary_logloss: 0.259881
[151]	valid_0's binary_logloss: 0.259604
[152]	valid_0's binary_logloss: 0.259476
[153]	valid_0's binary_logloss: 0.259569
[154]	valid_0's binary_logloss: 0.25923
[155]	valid_0's binary_logloss: 0.258953
[156]	valid_0's binary_logloss: 0.25857
[157]	valid_0's binary_logloss: 0.258347
[158]	valid_0's binary_logloss: 0.258286
[159]	valid_0's binary_logloss: 0.25818
[160]	valid_0's binary_logloss: 0.258146
[161]	valid_0's binary_logloss: 0.258094
[162]	valid_0's binary_logloss: 0.258098
[163]	valid_0's binary_logloss: 0.258069
[164]	valid_0's binary_logloss: 0.258172
[165]	valid_0's binary_logloss: 0.25792
[166]	valid_0's binary_logloss: 0.257927
[167]	valid_0's binary_logloss: 0.257668
[168]	valid_0's binary_logloss: 0.257432
[169]	valid_0's binary_logloss: 0.25729
[170]	valid_0's binary_logloss: 0.257052
[171]	valid_0's binary_logloss: 0.256926
[172]	valid_0's binary_logloss: 0.25685
[173]	valid_0's binary_logloss: 0.256906
[174]	valid_0's binary_logloss: 0.256967
[175]	valid_0's binary_logloss: 0.256905
[176]	valid_0's binary_logloss: 0.25676
[177]	valid_0's binary_logloss: 0.256791
[178]	valid_0's binary_logloss: 0.256912
[179]	valid_0's binary_logloss: 0.256925
[180]	valid_0's binary_logloss: 0.256641
[181]	valid_0's binary_logloss: 0.256515
[182]	valid_0's binary_logloss: 0.256386
[183]	valid_0's binary_logloss: 0.256381
[184]	valid_0's binary_logloss: 0.256244
[185]	valid_0's binary_logloss: 0.256155
[186]	valid_0's binary_logloss: 0.256208
[187]	valid_0's binary_logloss: 0.25634
[188]	valid_0's binary_logloss: 0.256293
[189]	valid_0's binary_logloss: 0.256256
[190]	valid_0's binary_logloss: 0.256102
[191]	valid_0's binary_logloss: 0.255924
[192]	valid_0's binary_logloss: 0.25597
[193]	valid_0's binary_logloss: 0.255656
[194]	valid_0's binary_logloss: 0.255653
[195]	valid_0's binary_logloss: 0.255586
[196]	valid_0's binary_logloss: 0.255488
[197]	valid_0's binary_logloss: 0.255282
[198]	valid_0's binary_logloss: 0.255288
[199]	valid_0's binary_logloss: 0.255049
[200]	valid_0's binary_logloss: 0.255025
[201]	valid_0's binary_logloss: 0.255011
[202]	valid_0's binary_logloss: 0.255015
[203]	valid_0's binary_logloss: 0.255315
[204]	valid_0's binary_logloss: 0.255275
[205]	valid_0's binary_logloss: 0.255388
[206]	valid_0's binary_logloss: 0.255498
[207]	valid_0's binary_logloss: 0.255449
[208]	valid_0's binary_logloss: 0.255467
[209]	valid_0's binary_logloss: 0.255576
[210]	valid_0's binary_logloss: 0.255458
[211]	valid_0's binary_logloss: 0.255563
[212]	valid_0's binary_logloss: 0.255619
[213]	valid_0's binary_logloss: 0.255503
[214]	valid_0's binary_logloss: 0.255433
[215]	valid_0's binary_logloss: 0.255586
[216]	valid_0's binary_logloss: 0.255753
[217]	valid_0's binary_logloss: 0.255873
[218]	valid_0's binary_logloss: 0.255995
[219]	valid_0's binary_logloss: 0.256052
[220]	valid_0's binary_logloss: 0.256144
[221]	valid_0's binary_logloss: 0.255988
[222]	valid_0's binary_logloss: 0.255858
[223]	valid_0's binary_logloss: 0.255917
[224]	valid_0's binary_logloss: 0.25606
[225]	valid_0's binary_logloss: 0.256008
[226]	valid_0's binary_logloss: 0.256029
[227]	valid_0's binary_logloss: 0.255923
[228]	valid_0's binary_logloss: 0.255792
[229]	valid_0's binary_logloss: 0.255737

Trening klas:   1%|▏         | 7/500 [01:10<1:20:20,  9.78s/klasa, klasa=class_7, F1_klasy=0.9274, F1_macro=0.9755, drzewa=201]




Trening klas:   2%|▏         | 8/500 [01:10<1:39:33, 12.14s/klasa, klasa=class_7, F1_klasy=0.9274, F1_macro=0.9755, drzewa=201]

[230]	valid_0's binary_logloss: 0.255746
[231]	valid_0's binary_logloss: 0.255441
[1]	valid_0's binary_logloss: 0.585979
[2]	valid_0's binary_logloss: 0.560309
[3]	valid_0's binary_logloss: 0.537888
[4]	valid_0's binary_logloss: 0.518746
[5]	valid_0's binary_logloss: 0.502625
[6]	valid_0's binary_logloss: 0.48802
[7]	valid_0's binary_logloss: 0.473868
[8]	valid_0's binary_logloss: 0.461522
[9]	valid_0's binary_logloss: 0.449875
[10]	valid_0's binary_logloss: 0.43948
[11]	valid_0's binary_logloss: 0.429735
[12]	valid_0's binary_logloss: 0.421044
[13]	valid_0's binary_logloss: 0.413105
[14]	valid_0's binary_logloss: 0.405699
[15]	valid_0's binary_logloss: 0.398452
[16]	valid_0's binary_logloss: 0.391755
[17]	valid_0's binary_logloss: 0.386292
[18]	valid_0's binary_logloss: 0.381004
[19]	valid_0's binary_logloss: 0.376097
[20]	valid_0's binary_logloss: 0.371146
[21]	valid_0's binary_logloss: 0.365837
[22]	valid_0's binary_logloss: 0.361244
[23]	valid_0's binary_logloss: 0.356623
[24]	valid_0's binary_logloss: 0.352838
[25]	valid_0's binary_logloss: 0.348856
[26]	valid_0's binary_logloss: 0.345642
[27]	valid_0's binary_logloss: 0.342163
[28]	valid_0's binary_logloss: 0.339674
[29]	valid_0's binary_logloss: 0.337388
[30]	valid_0's binary_logloss: 0.33475
[31]	valid_0's binary_logloss: 0.331085
[32]	valid_0's binary_logloss: 0.327798
[33]	valid_0's binary_logloss: 0.325343
[34]	valid_0's binary_logloss: 0.323204
[35]	valid_0's binary_logloss: 0.321636
[36]	valid_0's binary_logloss: 0.319458
[37]	valid_0's binary_logloss: 0.318027
[38]	valid_0's binary_logloss: 0.316981
[39]	valid_0's binary_logloss: 0.315582
[40]	valid_0's binary_logloss: 0.314343
[41]	valid_0's binary_logloss: 0.312656
[42]	valid_0's binary_logloss: 0.311597
[43]	valid_0's binary_logloss: 0.310233
[44]	valid_0's binary_logloss: 0.30831
[45]	valid_0's binary_logloss: 0.307045
[46]	valid_0's binary_logloss: 0.305924
[47]	valid_0's binary_logloss: 0.30452
[48]	valid_0's binary_logloss: 0.303077
[49]	valid_0's binary_logloss: 0.302292
[50]	valid_0's binary_logloss: 0.301575
[51]	valid_0's binary_logloss: 0.299915
[52]	valid_0's binary_logloss: 0.298734
[53]	valid_0's binary_logloss: 0.297963
[54]	valid_0's binary_logloss: 0.296261
[55]	valid_0's binary_logloss: 0.295836
[56]	valid_0's binary_logloss: 0.294413
[57]	valid_0's binary_logloss: 0.293542
[58]	valid_0's binary_logloss: 0.292395
[59]	valid_0's binary_logloss: 0.29077
[60]	valid_0's binary_logloss: 0.289257
[61]	valid_0's binary_logloss: 0.288432
[62]	valid_0's binary_logloss: 0.287594
[63]	valid_0's binary_logloss: 0.287006
[64]	valid_0's binary_logloss: 0.286627
[65]	valid_0's binary_logloss: 0.285921
[66]	valid_0's binary_logloss: 0.285071
[67]	valid_0's binary_logloss: 0.284391
[68]	valid_0's binary_logloss: 0.283688
[69]	valid_0's binary_logloss: 0.283211
[70]	valid_0's binary_logloss: 0.282506
[71]	valid_0's binary_logloss: 0.281497
[72]	valid_0's binary_logloss: 0.280889
[73]	valid_0's binary_logloss: 0.280344
[74]	valid_0's binary_logloss: 0.279373
[75]	valid_0's binary_logloss: 0.279053
[76]	valid_0's binary_logloss: 0.278375
[77]	valid_0's binary_logloss: 0.277633
[78]	valid_0's binary_logloss: 0.276971
[79]	valid_0's binary_logloss: 0.27638
[80]	valid_0's binary_logloss: 0.275836
[81]	valid_0's binary_logloss: 0.275688
[82]	valid_0's binary_logloss: 0.275283
[83]	valid_0's binary_logloss: 0.274957
[84]	valid_0's binary_logloss: 0.274549
[85]	valid_0's binary_logloss: 0.274049
[86]	valid_0's binary_logloss: 0.27326
[87]	valid_0's binary_logloss: 0.27267
[88]	valid_0's binary_logloss: 0.271717
[89]	valid_0's binary_logloss: 0.271716
[90]	valid_0's binary_logloss: 0.271356
[91]	valid_0's binary_logloss: 0.271083
[92]	valid_0's binary_logloss: 0.270827
[93]	valid_0's binary_logloss: 0.270176
[94]	valid_0's binary_logloss: 0.269813
[95]	valid_0's binary_logloss: 0.269646
[96]	valid_0's binary_logloss: 0.269672
[97]	valid_0's binary_logloss: 0.269104
[98]	valid_0's binary_logloss: 0.268833
[99]	valid_0's binary_logloss: 0.268756
[100]	valid_0's binary_logloss: 0.268204
[101]	valid_0's binary_logloss: 0.268003
[102]	valid_0's binary_logloss: 0.267712
[103]	valid_0's binary_logloss: 0.267334
[104]	valid_0's binary_logloss: 0.266985
[105]	valid_0's binary_logloss: 0.266879
[106]	valid_0's binary_logloss: 0.266404
[107]	valid_0's binary_logloss: 0.26628
[108]	valid_0's binary_logloss: 0.265745
[109]	valid_0's binary_logloss: 0.265513
[110]	valid_0's binary_logloss: 0.265365
[111]	valid_0's binary_logloss: 0.265527
[112]	valid_0's binary_logloss: 0.265472
[113]	valid_0's binary_logloss: 0.265568
[114]	valid_0's binary_logloss: 0.26558
[115]	valid_0's binary_logloss: 0.265674
[116]	valid_0's binary_logloss: 0.265321
[117]	valid_0's binary_logloss: 0.264618
[118]	valid_0's binary_logloss: 0.264163
[119]	valid_0's binary_logloss: 0.263984
[120]	valid_0's binary_logloss: 0.263591
[121]	valid_0's binary_logloss: 0.263484
[122]	valid_0's binary_logloss: 0.26296
[123]	valid_0's binary_logloss: 0.262758
[124]	valid_0's binary_logloss: 0.262466
[125]	valid_0's binary_logloss: 0.262173
[126]	valid_0's binary_logloss: 0.262033
[127]	valid_0's binary_logloss: 0.262067
[128]	valid_0's binary_logloss: 0.262024
[129]	valid_0's binary_logloss: 0.261611
[130]	valid_0's binary_logloss: 0.261381
[131]	valid_0's binary_logloss: 0.261343
[132]	valid_0's binary_logloss: 0.261305
[133]	valid_0's binary_logloss: 0.261224
[134]	valid_0's binary_logloss: 0.261216
[135]	valid_0's binary_logloss: 0.260826
[136]	valid_0's binary_logloss: 0.260659
[137]	valid_0's binary_logloss: 0.260473
[138]	valid_0's binary_logloss: 0.25975
[139]	valid_0's binary_logloss: 0.259502
[140]	valid_0's binary_logloss: 0.259224
[141]	valid_0's binary_logloss: 0.259299
[142]	valid_0's binary_logloss: 0.259207
[143]	valid_0's binary_logloss: 0.2589
[144]	valid_0's binary_logloss: 0.25848
[145]	valid_0's binary_logloss: 0.258226
[146]	valid_0's binary_logloss: 0.257988
[147]	valid_0's binary_logloss: 0.257704
[148]	valid_0's binary_logloss: 0.257327
[149]	valid_0's binary_logloss: 0.257232
[150]	valid_0's binary_logloss: 0.257008
[151]	valid_0's binary_logloss: 0.256844
[152]	valid_0's binary_logloss: 0.256653
[153]	valid_0's binary_logloss: 0.256547
[154]	valid_0's binary_logloss: 0.256126
[155]	valid_0's binary_logloss: 0.25583
[156]	valid_0's binary_logloss: 0.255584
[157]	valid_0's binary_logloss: 0.25547
[158]	valid_0's binary_logloss: 0.254998
[159]	valid_0's binary_logloss: 0.254693
[160]	valid_0's binary_logloss: 0.254589
[161]	valid_0's binary_logloss: 0.254561
[162]	valid_0's binary_logloss: 0.254539
[163]	valid_0's binary_logloss: 0.254344
[164]	valid_0's binary_logloss: 0.254278
[165]	valid_0's binary_logloss: 0.254211
[166]	valid_0's binary_logloss: 0.254077
[167]	valid_0's binary_logloss: 0.253909
[168]	valid_0's binary_logloss: 0.25386
[169]	valid_0's binary_logloss: 0.25366
[170]	valid_0's binary_logloss: 0.253748
[171]	valid_0's binary_logloss: 0.253883
[172]	valid_0's binary_logloss: 0.253712
[173]	valid_0's binary_logloss: 0.253566
[174]	valid_0's binary_logloss: 0.253489
[175]	valid_0's binary_logloss: 0.253376
[176]	valid_0's binary_logloss: 0.253345
[177]	valid_0's binary_logloss: 0.253326
[178]	valid_0's binary_logloss: 0.253118
[179]	valid_0's binary_logloss: 0.253043
[180]	valid_0's binary_logloss: 0.253081
[181]	valid_0's binary_logloss: 0.252914
[182]	valid_0's binary_logloss: 0.252779
[183]	valid_0's binary_logloss: 0.252786
[184]	valid_0's binary_logloss: 0.252626
[185]	valid_0's binary_logloss: 0.252577
[186]	valid_0's binary_logloss: 0.252516
[187]	valid_0's binary_logloss: 0.252352
[188]	valid_0's binary_logloss: 0.252236
[189]	valid_0's binary_logloss: 0.252094
[190]	valid_0's binary_logloss: 0.252051
[191]	valid_0's binary_logloss: 0.251959
[192]	valid_0's binary_logloss: 0.251947
[193]	valid_0's binary_logloss: 0.25217
[194]	valid_0's binary_logloss: 0.252126
[195]	valid_0's binary_logloss: 0.252238
[196]	valid_0's binary_logloss: 0.252338
[197]	valid_0's binary_logloss: 0.252198
[198]	valid_0's binary_logloss: 0.252156
[199]	valid_0's binary_logloss: 0.252143
[200]	valid_0's binary_logloss: 0.252056
[201]	valid_0's binary_logloss: 0.252129
[202]	valid_0's binary_logloss: 0.252149
[203]	valid_0's binary_logloss: 0.252116
[204]	valid_0's binary_logloss: 0.252002
[205]	valid_0's binary_logloss: 0.251818
[206]	valid_0's binary_logloss: 0.251813
[207]	valid_0's binary_logloss: 0.251604
[208]	valid_0's binary_logloss: 0.251255
[209]	valid_0's binary_logloss: 0.251248
[210]	valid_0's binary_logloss: 0.251417
[211]	valid_0's binary_logloss: 0.251432
[212]	valid_0's binary_logloss: 0.251493
[213]	valid_0's binary_logloss: 0.251383
[214]	valid_0's binary_logloss: 0.251116
[215]	valid_0's binary_logloss: 0.251042
[216]	valid_0's binary_logloss: 0.251134
[217]	valid_0's binary_logloss: 0.251032
[218]	valid_0's binary_logloss: 0.250972
[219]	valid_0's binary_logloss: 0.251086
[220]	valid_0's binary_logloss: 0.250963
[221]	valid_0's binary_logloss: 0.250823
[222]	valid_0's binary_logloss: 0.250632
[223]	valid_0's binary_logloss: 0.250405
[224]	valid_0's binary_logloss: 0.250204
[225]	valid_0's binary_logloss: 0.249911
[226]	valid_0's binary_logloss: 0.249893
[227]	valid_0's binary_logloss: 0.249904
[228]	valid_0's binary_logloss: 0.249914
[229]	valid_0's binary_logloss: 0.24997
[230]	valid_0's binary_logloss: 0.250001
[231]	valid_0's binary_logloss: 0.249784
[232]	valid_0's binary_logloss: 0.249737
[233]	valid_0's binary_logloss: 0.249682
[234]	valid_0's binary_logloss: 0.249337
[235]	valid_0's binary_logloss: 0.249463
[236]	valid_0's binary_logloss: 0.249136
[237]	valid_0's binary_logloss: 0.249174
[238]	valid_0's binary_logloss: 0.249034
[239]	valid_0's binary_logloss: 0.249112
[240]	valid_0's binary_logloss: 0.249045
[241]	valid_0's binary_logloss: 0.249046
[242]	valid_0's binary_logloss: 0.248845
[243]	valid_0's binary_logloss: 0.248786
[244]	valid_0's binary_logloss: 0.248689
[245]	valid_0's binary_logloss: 0.248608
[246]	valid_0's binary_logloss: 0.248681
[247]	valid_0's binary_logloss: 0.24873
[248]	valid_0's binary_logloss: 0.24857
[249]	valid_0's binary_logloss: 0.248339
[250]	valid_0's binary_logloss: 0.248448
[251]	valid_0's binary_logloss: 0.248334
[252]	valid_0's binary_logloss: 0.248068
[253]	valid_0's binary_logloss: 0.247996
[254]	valid_0's binary_logloss: 0.248086
[255]	valid_0's binary_logloss: 0.247975
[256]	valid_0's binary_logloss: 0.247762
[257]	valid_0's binary_logloss: 0.247683
[258]	valid_0's binary_logloss: 0.247846
[259]	valid_0's binary_logloss: 0.247874
[260]	valid_0's binary_logloss: 0.248044
[261]	valid_0's binary_logloss: 0.248114
[262]	valid_0's binary_logloss: 0.247995
[263]	valid_0's binary_logloss: 0.247813
[264]	valid_0's binary_logloss: 0.247666
[265]	valid_0's binary_logloss: 0.247786
[266]	valid_0's binary_logloss: 0.247999
[267]	valid_0's binary_logloss: 0.248235
[268]	valid_0's binary_logloss: 0.248544
[269]	valid_0's binary_logloss: 0.248621
[270]	valid_0's binary_logloss: 0.248747
[271]	valid_0's binary_logloss: 0.248495
[272]	valid_0's binary_logloss: 0.248301
[273]	valid_0's binary_logloss: 0.248302
[274]	valid_0's binary_logloss: 0.248046
[275]	valid_0's binary_logloss: 0.248111
[276]	valid_0's binary_logloss: 0.248074
[277]	valid_0's binary_logloss: 0.248257
[278]	valid_0's binary_logloss: 0.248224
[279]	valid_0's binary_logloss: 0.248352
[280]	valid_0's binary_logloss: 0.248447
[281]	valid_0's binary_logloss: 0.24837
[282]	valid_0's binary_logloss: 0.248469
[283]	valid_0's binary_logloss: 0.248419
[284]	valid_0's binary_logloss: 0.248557
[285]	valid_0's binary_logloss: 0.248434
[286]	valid_0's binary_logloss: 0.24843
[287]	valid_0's binary_logloss: 0.248482
[288]	valid_0's binary_logloss: 0.248603
[289]	valid_0's binary_logloss: 0.248532
[290]	valid_0's binary_logloss: 0.248501
[291]	valid_0's binary_logloss: 0.248654
[292]	valid_0's binary_logloss: 0.248692
[293]	valid_0's binary_logloss: 0.248583
[294]	valid_0's binary_logloss: 0.248741

Trening klas:   2%|▏         | 8/500 [01:32<1:39:33, 12.14s/klasa, klasa=class_8, F1_klasy=0.9245, F1_macro=0.9698, drzewa=264]




Trening klas:   2%|▏         | 9/500 [01:32<2:04:21, 15.20s/klasa, klasa=class_8, F1_klasy=0.9245, F1_macro=0.9698, drzewa=264]

[1]	valid_0's binary_logloss: 0.507776
[2]	valid_0's binary_logloss: 0.486754
[3]	valid_0's binary_logloss: 0.467699
[4]	valid_0's binary_logloss: 0.450804
[5]	valid_0's binary_logloss: 0.434904
[6]	valid_0's binary_logloss: 0.420091
[7]	valid_0's binary_logloss: 0.406562
[8]	valid_0's binary_logloss: 0.394626
[9]	valid_0's binary_logloss: 0.383002
[10]	valid_0's binary_logloss: 0.372727
[11]	valid_0's binary_logloss: 0.36277
[12]	valid_0's binary_logloss: 0.353514
[13]	valid_0's binary_logloss: 0.344467
[14]	valid_0's binary_logloss: 0.336007
[15]	valid_0's binary_logloss: 0.327967
[16]	valid_0's binary_logloss: 0.320028
[17]	valid_0's binary_logloss: 0.313314
[18]	valid_0's binary_logloss: 0.306811
[19]	valid_0's binary_logloss: 0.300935
[20]	valid_0's binary_logloss: 0.295763
[21]	valid_0's binary_logloss: 0.290641
[22]	valid_0's binary_logloss: 0.285396
[23]	valid_0's binary_logloss: 0.280862
[24]	valid_0's binary_logloss: 0.276507
[25]	valid_0's binary_logloss: 0.27246
[26]	valid_0's binary_logloss: 0.268725
[27]	valid_0's binary_logloss: 0.265335
[28]	valid_0's binary_logloss: 0.261597
[29]	valid_0's binary_logloss: 0.258422
[30]	valid_0's binary_logloss: 0.255783
[31]	valid_0's binary_logloss: 0.25305
[32]	valid_0's binary_logloss: 0.250475
[33]	valid_0's binary_logloss: 0.247869
[34]	valid_0's binary_logloss: 0.245024
[35]	valid_0's binary_logloss: 0.242636
[36]	valid_0's binary_logloss: 0.240624
[37]	valid_0's binary_logloss: 0.238727
[38]	valid_0's binary_logloss: 0.236921
[39]	valid_0's binary_logloss: 0.235227
[40]	valid_0's binary_logloss: 0.233614
[41]	valid_0's binary_logloss: 0.231842
[42]	valid_0's binary_logloss: 0.230165
[43]	valid_0's binary_logloss: 0.228608
[44]	valid_0's binary_logloss: 0.226804
[45]	valid_0's binary_logloss: 0.225192
[46]	valid_0's binary_logloss: 0.223808
[47]	valid_0's binary_logloss: 0.222717
[48]	valid_0's binary_logloss: 0.221236
[49]	valid_0's binary_logloss: 0.220061
[50]	valid_0's binary_logloss: 0.218955
[51]	valid_0's binary_logloss: 0.217661
[52]	valid_0's binary_logloss: 0.216626
[53]	valid_0's binary_logloss: 0.215604
[54]	valid_0's binary_logloss: 0.214514
[55]	valid_0's binary_logloss: 0.213669
[56]	valid_0's binary_logloss: 0.212933
[57]	valid_0's binary_logloss: 0.212256
[58]	valid_0's binary_logloss: 0.211451
[59]	valid_0's binary_logloss: 0.21058
[60]	valid_0's binary_logloss: 0.209883
[61]	valid_0's binary_logloss: 0.209044
[62]	valid_0's binary_logloss: 0.20817
[63]	valid_0's binary_logloss: 0.207555
[64]	valid_0's binary_logloss: 0.206829
[65]	valid_0's binary_logloss: 0.206288
[66]	valid_0's binary_logloss: 0.205978
[67]	valid_0's binary_logloss: 0.205257
[68]	valid_0's binary_logloss: 0.204815
[69]	valid_0's binary_logloss: 0.20439
[70]	valid_0's binary_logloss: 0.204075
[71]	valid_0's binary_logloss: 0.203464
[72]	valid_0's binary_logloss: 0.203107
[73]	valid_0's binary_logloss: 0.202391
[74]	valid_0's binary_logloss: 0.201961
[75]	valid_0's binary_logloss: 0.201297
[76]	valid_0's binary_logloss: 0.200468
[77]	valid_0's binary_logloss: 0.199989
[78]	valid_0's binary_logloss: 0.199066
[79]	valid_0's binary_logloss: 0.198563
[80]	valid_0's binary_logloss: 0.197817
[81]	valid_0's binary_logloss: 0.197301
[82]	valid_0's binary_logloss: 0.196769
[83]	valid_0's binary_logloss: 0.196616
[84]	valid_0's binary_logloss: 0.196281
[85]	valid_0's binary_logloss: 0.195818
[86]	valid_0's binary_logloss: 0.195429
[87]	valid_0's binary_logloss: 0.194995
[88]	valid_0's binary_logloss: 0.194539
[89]	valid_0's binary_logloss: 0.194061
[90]	valid_0's binary_logloss: 0.19339
[91]	valid_0's binary_logloss: 0.192764
[92]	valid_0's binary_logloss: 0.192507
[93]	valid_0's binary_logloss: 0.192232
[94]	valid_0's binary_logloss: 0.191717
[95]	valid_0's binary_logloss: 0.191564
[96]	valid_0's binary_logloss: 0.191097
[97]	valid_0's binary_logloss: 0.190426
[98]	valid_0's binary_logloss: 0.189882
[99]	valid_0's binary_logloss: 0.189481
[100]	valid_0's binary_logloss: 0.189069
[101]	valid_0's binary_logloss: 0.188585
[102]	valid_0's binary_logloss: 0.188049
[103]	valid_0's binary_logloss: 0.187483
[104]	valid_0's binary_logloss: 0.186993
[105]	valid_0's binary_logloss: 0.18658
[106]	valid_0's binary_logloss: 0.186369
[107]	valid_0's binary_logloss: 0.186352
[108]	valid_0's binary_logloss: 0.185992
[109]	valid_0's binary_logloss: 0.185692
[110]	valid_0's binary_logloss: 0.18557
[111]	valid_0's binary_logloss: 0.185317
[112]	valid_0's binary_logloss: 0.185168
[113]	valid_0's binary_logloss: 0.185252
[114]	valid_0's binary_logloss: 0.185167
[115]	valid_0's binary_logloss: 0.184915
[116]	valid_0's binary_logloss: 0.184554
[117]	valid_0's binary_logloss: 0.184429
[118]	valid_0's binary_logloss: 0.184105
[119]	valid_0's binary_logloss: 0.183788
[120]	valid_0's binary_logloss: 0.183432
[121]	valid_0's binary_logloss: 0.18313
[122]	valid_0's binary_logloss: 0.182889
[123]	valid_0's binary_logloss: 0.182659
[124]	valid_0's binary_logloss: 0.182584
[125]	valid_0's binary_logloss: 0.182187
[126]	valid_0's binary_logloss: 0.182199
[127]	valid_0's binary_logloss: 0.182173
[128]	valid_0's binary_logloss: 0.182102
[129]	valid_0's binary_logloss: 0.182181
[130]	valid_0's binary_logloss: 0.182101
[131]	valid_0's binary_logloss: 0.182091
[132]	valid_0's binary_logloss: 0.1818
[133]	valid_0's binary_logloss: 0.181719
[134]	valid_0's binary_logloss: 0.181737
[135]	valid_0's binary_logloss: 0.181714
[136]	valid_0's binary_logloss: 0.181558
[137]	valid_0's binary_logloss: 0.181262
[138]	valid_0's binary_logloss: 0.180891
[139]	valid_0's binary_logloss: 0.180655
[140]	valid_0's binary_logloss: 0.180536
[141]	valid_0's binary_logloss: 0.180342
[142]	valid_0's binary_logloss: 0.180271
[143]	valid_0's binary_logloss: 0.18026
[144]	valid_0's binary_logloss: 0.180073
[145]	valid_0's binary_logloss: 0.180117
[146]	valid_0's binary_logloss: 0.179782
[147]	valid_0's binary_logloss: 0.179357
[148]	valid_0's binary_logloss: 0.179255
[149]	valid_0's binary_logloss: 0.178938
[150]	valid_0's binary_logloss: 0.178592
[151]	valid_0's binary_logloss: 0.178562
[152]	valid_0's binary_logloss: 0.178517
[153]	valid_0's binary_logloss: 0.178407
[154]	valid_0's binary_logloss: 0.178542
[155]	valid_0's binary_logloss: 0.178441
[156]	valid_0's binary_logloss: 0.178407
[157]	valid_0's binary_logloss: 0.17814
[158]	valid_0's binary_logloss: 0.178146
[159]	valid_0's binary_logloss: 0.178095
[160]	valid_0's binary_logloss: 0.177988
[161]	valid_0's binary_logloss: 0.177868
[162]	valid_0's binary_logloss: 0.177902
[163]	valid_0's binary_logloss: 0.177823
[164]	valid_0's binary_logloss: 0.177803
[165]	valid_0's binary_logloss: 0.177753
[166]	valid_0's binary_logloss: 0.177889
[167]	valid_0's binary_logloss: 0.177902
[168]	valid_0's binary_logloss: 0.178001
[169]	valid_0's binary_logloss: 0.178123
[170]	valid_0's binary_logloss: 0.178201
[171]	valid_0's binary_logloss: 0.178263
[172]	valid_0's binary_logloss: 0.178288
[173]	valid_0's binary_logloss: 0.178299
[174]	valid_0's binary_logloss: 0.178061
[175]	valid_0's binary_logloss: 0.178064
[176]	valid_0's binary_logloss: 0.177915
[177]	valid_0's binary_logloss: 0.177929
[178]	valid_0's binary_logloss: 0.177726
[179]	valid_0's binary_logloss: 0.177659
[180]	valid_0's binary_logloss: 0.1776
[181]	valid_0's binary_logloss: 0.177636
[182]	valid_0's binary_logloss: 0.1777
[183]	valid_0's binary_logloss: 0.177655
[184]	valid_0's binary_logloss: 0.177601
[185]	valid_0's binary_logloss: 0.177615
[186]	valid_0's binary_logloss: 0.177597
[187]	valid_0's binary_logloss: 0.177609
[188]	valid_0's binary_logloss: 0.177562
[189]	valid_0's binary_logloss: 0.177434
[190]	valid_0's binary_logloss: 0.177336
[191]	valid_0's binary_logloss: 0.177119
[192]	valid_0's binary_logloss: 0.17715
[193]	valid_0's binary_logloss: 0.17703
[194]	valid_0's binary_logloss: 0.177187
[195]	valid_0's binary_logloss: 0.177194
[196]	valid_0's binary_logloss: 0.17692
[197]	valid_0's binary_logloss: 0.176809
[198]	valid_0's binary_logloss: 0.176805
[199]	valid_0's binary_logloss: 0.176728
[200]	valid_0's binary_logloss: 0.17662
[201]	valid_0's binary_logloss: 0.176529
[202]	valid_0's binary_logloss: 0.17642
[203]	valid_0's binary_logloss: 0.176458
[204]	valid_0's binary_logloss: 0.176453
[205]	valid_0's binary_logloss: 0.176486
[206]	valid_0's binary_logloss: 0.176516
[207]	valid_0's binary_logloss: 0.176508
[208]	valid_0's binary_logloss: 0.176568
[209]	valid_0's binary_logloss: 0.176534
[210]	valid_0's binary_logloss: 0.176497
[211]	valid_0's binary_logloss: 0.17657
[212]	valid_0's binary_logloss: 0.176574
[213]	valid_0's binary_logloss: 0.176637
[214]	valid_0's binary_logloss: 0.176691
[215]	valid_0's binary_logloss: 0.176684
[216]	valid_0's binary_logloss: 0.176556
[217]	valid_0's binary_logloss: 0.176616
[218]	valid_0's binary_logloss: 0.176778
[219]	valid_0's binary_logloss: 0.176775
[220]	valid_0's binary_logloss: 0.176798
[221]	valid_0's binary_logloss: 0.17672
[222]	valid_0's binary_logloss: 0.176666
[223]	valid_0's binary_logloss: 0.17675
[224]	valid_0's binary_logloss: 0.176634
[225]	valid_0's binary_logloss: 0.176655
[226]	valid_0's binary_logloss: 0.176572
[227]	valid_0's binary_logloss: 0.176436
[228]	valid_0's binary_logloss: 0.176441
[229]	valid_0's binary_logloss: 0.176328
[230]	valid_0's binary_logloss: 0.176323
[231]	valid_0's binary_logloss: 0.176234
[232]	valid_0's binary_logloss: 0.176247
[233]	valid_0's binary_logloss: 0.176267
[234]	valid_0's binary_logloss: 0.176273
[235]	valid_0's binary_logloss: 0.176225
[236]	valid_0's binary_logloss: 0.176238
[237]	valid_0's binary_logloss: 0.176138
[238]	valid_0's binary_logloss: 0.176028
[239]	valid_0's binary_logloss: 0.175998
[240]	valid_0's binary_logloss: 0.176045
[241]	valid_0's binary_logloss: 0.176038
[242]	valid_0's binary_logloss: 0.176018
[243]	valid_0's binary_logloss: 0.176018
[244]	valid_0's binary_logloss: 0.176099
[245]	valid_0's binary_logloss: 0.176059
[246]	valid_0's binary_logloss: 0.176047
[247]	valid_0's binary_logloss: 0.176159
[248]	valid_0's binary_logloss: 0.17612
[249]	valid_0's binary_logloss: 0.176159
[250]	valid_0's binary_logloss: 0.176294
[251]	valid_0's binary_logloss: 0.176191
[252]	valid_0's binary_logloss: 0.176144
[253]	valid_0's binary_logloss: 0.17604
[254]	valid_0's binary_logloss: 0.176019
[255]	valid_0's binary_logloss: 0.175957
[256]	valid_0's binary_logloss: 0.175997
[257]	valid_0's binary_logloss: 0.175739
[258]	valid_0's binary_logloss: 0.175673
[259]	valid_0's binary_logloss: 0.175626
[260]	valid_0's binary_logloss: 0.175489
[261]	valid_0's binary_logloss: 0.175447
[262]	valid_0's binary_logloss: 0.175467
[263]	valid_0's binary_logloss: 0.175555
[264]	valid_0's binary_logloss: 0.175517
[265]	valid_0's binary_logloss: 0.175549
[266]	valid_0's binary_logloss: 0.17561
[267]	valid_0's binary_logloss: 0.175496
[268]	valid_0's binary_logloss: 0.175502
[269]	valid_0's binary_logloss: 0.175643
[270]	valid_0's binary_logloss: 0.175713
[271]	valid_0's binary_logloss: 0.175769
[272]	valid_0's binary_logloss: 0.175882
[273]	valid_0's binary_logloss: 0.175843
[274]	valid_0's binary_logloss: 0.175904
[275]	valid_0's binary_logloss: 0.175832
[276]	valid_0's binary_logloss: 0.175897
[277]	valid_0's binary_logloss: 0.175796
[278]	valid_0's binary_logloss: 0.17592
[279]	valid_0's binary_logloss: 0.17602
[280]	valid_0's binary_logloss: 0.176078
[281]	valid_0's binary_logloss: 0.176177
[282]	valid_0's binary_logloss: 0.176169
[283]	valid_0's binary_logloss: 0.176218
[284]	valid_0's binary_logloss: 0.176491
[285]	valid_0's binary_logloss: 0.176673
[286]	valid_0's binary_logloss: 0.176725
[287]	valid_0's binary_logloss: 0.176723
[288]	valid_0's binary_logloss: 0.176572
[289]	valid_0's binary_logloss: 0.176548
[290]	valid_0's binary_logloss: 0.176676
[291]	valid_0's binary_logloss: 0.176647

Trening klas:   2%|▏         | 9/500 [01:54<2:04:21, 15.20s/klasa, klasa=class_9, F1_klasy=0.9650, F1_macro=0.9693, drzewa=261]




Trening klas:   2%|▏         | 10/500 [01:54<2:19:03, 17.03s/klasa, klasa=class_9, F1_klasy=0.9650, F1_macro=0.9693, drzewa=261]

[1]	valid_0's binary_logloss: 0.705603
[2]	valid_0's binary_logloss: 0.679666
[3]	valid_0's binary_logloss: 0.657037
[4]	valid_0's binary_logloss: 0.637256
[5]	valid_0's binary_logloss: 0.617478
[6]	valid_0's binary_logloss: 0.600747
[7]	valid_0's binary_logloss: 0.585782
[8]	valid_0's binary_logloss: 0.571915
[9]	valid_0's binary_logloss: 0.558939
[10]	valid_0's binary_logloss: 0.547633
[11]	valid_0's binary_logloss: 0.537027
[12]	valid_0's binary_logloss: 0.527655
[13]	valid_0's binary_logloss: 0.519118
[14]	valid_0's binary_logloss: 0.51063
[15]	valid_0's binary_logloss: 0.504591
[16]	valid_0's binary_logloss: 0.49854
[17]	valid_0's binary_logloss: 0.49215
[18]	valid_0's binary_logloss: 0.485674
[19]	valid_0's binary_logloss: 0.480243
[20]	valid_0's binary_logloss: 0.475694
[21]	valid_0's binary_logloss: 0.470516
[22]	valid_0's binary_logloss: 0.464891
[23]	valid_0's binary_logloss: 0.460622
[24]	valid_0's binary_logloss: 0.456176
[25]	valid_0's binary_logloss: 0.452589
[26]	valid_0's binary_logloss: 0.449506
[27]	valid_0's binary_logloss: 0.446865
[28]	valid_0's binary_logloss: 0.443831
[29]	valid_0's binary_logloss: 0.440957
[30]	valid_0's binary_logloss: 0.438731
[31]	valid_0's binary_logloss: 0.435376
[32]	valid_0's binary_logloss: 0.433199
[33]	valid_0's binary_logloss: 0.430621
[34]	valid_0's binary_logloss: 0.428317
[35]	valid_0's binary_logloss: 0.426459
[36]	valid_0's binary_logloss: 0.424225
[37]	valid_0's binary_logloss: 0.422367
[38]	valid_0's binary_logloss: 0.421429
[39]	valid_0's binary_logloss: 0.420119
[40]	valid_0's binary_logloss: 0.418413
[41]	valid_0's binary_logloss: 0.417516
[42]	valid_0's binary_logloss: 0.416042
[43]	valid_0's binary_logloss: 0.415353
[44]	valid_0's binary_logloss: 0.414121
[45]	valid_0's binary_logloss: 0.412728
[46]	valid_0's binary_logloss: 0.411862
[47]	valid_0's binary_logloss: 0.410075
[48]	valid_0's binary_logloss: 0.408995
[49]	valid_0's binary_logloss: 0.407918
[50]	valid_0's binary_logloss: 0.406968
[51]	valid_0's binary_logloss: 0.406069
[52]	valid_0's binary_logloss: 0.405772
[53]	valid_0's binary_logloss: 0.405407
[54]	valid_0's binary_logloss: 0.404432
[55]	valid_0's binary_logloss: 0.403096
[56]	valid_0's binary_logloss: 0.402088
[57]	valid_0's binary_logloss: 0.401323
[58]	valid_0's binary_logloss: 0.400879
[59]	valid_0's binary_logloss: 0.400401
[60]	valid_0's binary_logloss: 0.399265
[61]	valid_0's binary_logloss: 0.398037
[62]	valid_0's binary_logloss: 0.397184
[63]	valid_0's binary_logloss: 0.396779
[64]	valid_0's binary_logloss: 0.395637
[65]	valid_0's binary_logloss: 0.395042
[66]	valid_0's binary_logloss: 0.394553
[67]	valid_0's binary_logloss: 0.393791
[68]	valid_0's binary_logloss: 0.39316
[69]	valid_0's binary_logloss: 0.392961
[70]	valid_0's binary_logloss: 0.392528
[71]	valid_0's binary_logloss: 0.391405
[72]	valid_0's binary_logloss: 0.3908
[73]	valid_0's binary_logloss: 0.390439
[74]	valid_0's binary_logloss: 0.390076
[75]	valid_0's binary_logloss: 0.389514
[76]	valid_0's binary_logloss: 0.389294
[77]	valid_0's binary_logloss: 0.388739
[78]	valid_0's binary_logloss: 0.388406
[79]	valid_0's binary_logloss: 0.388024
[80]	valid_0's binary_logloss: 0.387891
[81]	valid_0's binary_logloss: 0.387836
[82]	valid_0's binary_logloss: 0.387793
[83]	valid_0's binary_logloss: 0.387696
[84]	valid_0's binary_logloss: 0.386995
[85]	valid_0's binary_logloss: 0.386283
[86]	valid_0's binary_logloss: 0.385973
[87]	valid_0's binary_logloss: 0.385641
[88]	valid_0's binary_logloss: 0.385247
[89]	valid_0's binary_logloss: 0.385231
[90]	valid_0's binary_logloss: 0.385265
[91]	valid_0's binary_logloss: 0.385151
[92]	valid_0's binary_logloss: 0.384704
[93]	valid_0's binary_logloss: 0.384776
[94]	valid_0's binary_logloss: 0.384333
[95]	valid_0's binary_logloss: 0.384254
[96]	valid_0's binary_logloss: 0.383734
[97]	valid_0's binary_logloss: 0.383526
[98]	valid_0's binary_logloss: 0.382951
[99]	valid_0's binary_logloss: 0.382851
[100]	valid_0's binary_logloss: 0.38255
[101]	valid_0's binary_logloss: 0.382182
[102]	valid_0's binary_logloss: 0.38191
[103]	valid_0's binary_logloss: 0.381664
[104]	valid_0's binary_logloss: 0.381687
[105]	valid_0's binary_logloss: 0.38155
[106]	valid_0's binary_logloss: 0.380997
[107]	valid_0's binary_logloss: 0.380636
[108]	valid_0's binary_logloss: 0.380568
[109]	valid_0's binary_logloss: 0.380507
[110]	valid_0's binary_logloss: 0.380403
[111]	valid_0's binary_logloss: 0.379915
[112]	valid_0's binary_logloss: 0.379637
[113]	valid_0's binary_logloss: 0.379454
[114]	valid_0's binary_logloss: 0.379063
[115]	valid_0's binary_logloss: 0.378675
[116]	valid_0's binary_logloss: 0.378353
[117]	valid_0's binary_logloss: 0.37809
[118]	valid_0's binary_logloss: 0.377886
[119]	valid_0's binary_logloss: 0.377739
[120]	valid_0's binary_logloss: 0.37762
[121]	valid_0's binary_logloss: 0.377412
[122]	valid_0's binary_logloss: 0.377062
[123]	valid_0's binary_logloss: 0.377
[124]	valid_0's binary_logloss: 0.377141
[125]	valid_0's binary_logloss: 0.377047
[126]	valid_0's binary_logloss: 0.376595
[127]	valid_0's binary_logloss: 0.376384
[128]	valid_0's binary_logloss: 0.375921
[129]	valid_0's binary_logloss: 0.375925
[130]	valid_0's binary_logloss: 0.375698
[131]	valid_0's binary_logloss: 0.375213
[132]	valid_0's binary_logloss: 0.374847
[133]	valid_0's binary_logloss: 0.374375
[134]	valid_0's binary_logloss: 0.373784
[135]	valid_0's binary_logloss: 0.373263
[136]	valid_0's binary_logloss: 0.373016
[137]	valid_0's binary_logloss: 0.372983
[138]	valid_0's binary_logloss: 0.372752
[139]	valid_0's binary_logloss: 0.372726
[140]	valid_0's binary_logloss: 0.372456
[141]	valid_0's binary_logloss: 0.372396
[142]	valid_0's binary_logloss: 0.372433
[143]	valid_0's binary_logloss: 0.372564
[144]	valid_0's binary_logloss: 0.372623
[145]	valid_0's binary_logloss: 0.372408
[146]	valid_0's binary_logloss: 0.372247
[147]	valid_0's binary_logloss: 0.372062
[148]	valid_0's binary_logloss: 0.37193
[149]	valid_0's binary_logloss: 0.371684
[150]	valid_0's binary_logloss: 0.371759
[151]	valid_0's binary_logloss: 0.371775
[152]	valid_0's binary_logloss: 0.371837
[153]	valid_0's binary_logloss: 0.371471
[154]	valid_0's binary_logloss: 0.371511
[155]	valid_0's binary_logloss: 0.371735
[156]	valid_0's binary_logloss: 0.371457
[157]	valid_0's binary_logloss: 0.371153
[158]	valid_0's binary_logloss: 0.370729
[159]	valid_0's binary_logloss: 0.37072
[160]	valid_0's binary_logloss: 0.370391
[161]	valid_0's binary_logloss: 0.370551
[162]	valid_0's binary_logloss: 0.370295
[163]	valid_0's binary_logloss: 0.370141
[164]	valid_0's binary_logloss: 0.370249
[165]	valid_0's binary_logloss: 0.370314
[166]	valid_0's binary_logloss: 0.370248
[167]	valid_0's binary_logloss: 0.369864
[168]	valid_0's binary_logloss: 0.369935
[169]	valid_0's binary_logloss: 0.370031
[170]	valid_0's binary_logloss: 0.37019
[171]	valid_0's binary_logloss: 0.369962
[172]	valid_0's binary_logloss: 0.3703
[173]	valid_0's binary_logloss: 0.370192
[174]	valid_0's binary_logloss: 0.370364
[175]	valid_0's binary_logloss: 0.370596
[176]	valid_0's binary_logloss: 0.370451
[177]	valid_0's binary_logloss: 0.370164
[178]	valid_0's binary_logloss: 0.370108
[179]	valid_0's binary_logloss: 0.369833
[180]	valid_0's binary_logloss: 0.3699
[181]	valid_0's binary_logloss: 0.36977
[182]	valid_0's binary_logloss: 0.369653
[183]	valid_0's binary_logloss: 0.369451
[184]	valid_0's binary_logloss: 0.369508
[185]	valid_0's binary_logloss: 0.369421
[186]	valid_0's binary_logloss: 0.369247
[187]	valid_0's binary_logloss: 0.369295
[188]	valid_0's binary_logloss: 0.368975
[189]	valid_0's binary_logloss: 0.368948
[190]	valid_0's binary_logloss: 0.368796
[191]	valid_0's binary_logloss: 0.369136
[192]	valid_0's binary_logloss: 0.369523
[193]	valid_0's binary_logloss: 0.369548
[194]	valid_0's binary_logloss: 0.369421
[195]	valid_0's binary_logloss: 0.369629
[196]	valid_0's binary_logloss: 0.369623
[197]	valid_0's binary_logloss: 0.369423
[198]	valid_0's binary_logloss: 0.368948
[199]	valid_0's binary_logloss: 0.369192
[200]	valid_0's binary_logloss: 0.369232
[201]	valid_0's binary_logloss: 0.369088
[202]	valid_0's binary_logloss: 0.369003
[203]	valid_0's binary_logloss: 0.369246
[204]	valid_0's binary_logloss: 0.3692
[205]	valid_0's binary_logloss: 0.368825
[206]	valid_0's binary_logloss: 0.368812
[207]	valid_0's binary_logloss: 0.368699
[208]	valid_0's binary_logloss: 0.368555
[209]	valid_0's binary_logloss: 0.368381
[210]	valid_0's binary_logloss: 0.368222
[211]	valid_0's binary_logloss: 0.368079
[212]	valid_0's binary_logloss: 0.368248
[213]	valid_0's binary_logloss: 0.367974
[214]	valid_0's binary_logloss: 0.367854
[215]	valid_0's binary_logloss: 0.36785
[216]	valid_0's binary_logloss: 0.36745
[217]	valid_0's binary_logloss: 0.367227
[218]	valid_0's binary_logloss: 0.367033
[219]	valid_0's binary_logloss: 0.366937
[220]	valid_0's binary_logloss: 0.366684
[221]	valid_0's binary_logloss: 0.36668
[222]	valid_0's binary_logloss: 0.366748
[223]	valid_0's binary_logloss: 0.367055
[224]	valid_0's binary_logloss: 0.367237
[225]	valid_0's binary_logloss: 0.367532
[226]	valid_0's binary_logloss: 0.367676
[227]	valid_0's binary_logloss: 0.367784
[228]	valid_0's binary_logloss: 0.367765
[229]	valid_0's binary_logloss: 0.368031
[230]	valid_0's binary_logloss: 0.368096
[231]	valid_0's binary_logloss: 0.36793
[232]	valid_0's binary_logloss: 0.368093
[233]	valid_0's binary_logloss: 0.368383
[234]	valid_0's binary_logloss: 0.368646
[235]	valid_0's binary_logloss: 0.368731
[236]	valid_0's binary_logloss: 0.368597
[237]	valid_0's binary_logloss: 0.368555
[238]	valid_0's binary_logloss: 0.368445
[239]	valid_0's binary_logloss: 0.368387
[240]	valid_0's binary_logloss: 0.368092
[241]	valid_0's binary_logloss: 0.368334
[242]	valid_0's binary_logloss: 0.368424
[243]	valid_0's binary_logloss: 0.368557
[244]	valid_0's binary_logloss: 0.368666
[245]	valid_0's binary_logloss: 0.368747
[246]	valid_0's binary_logloss: 0.368913
[247]	valid_0's binary_logloss: 0.36908
[248]	valid_0's binary_logloss: 0.36898
[249]	valid_0's binary_logloss: 0.36914
[250]	valid_0's binary_logloss: 0.369089
[251]	valid_0's binary_logloss: 0.36924

Trening klas:   2%|▏         | 10/500 [02:12<2:19:03, 17.03s/klasa, klasa=class_10, F1_klasy=0.8408, F1_macro=0.9577, drzewa=221]




Trening klas:   2%|▏         | 11/500 [02:12<2:22:01, 17.43s/klasa, klasa=class_10, F1_klasy=0.8408, F1_macro=0.9577, drzewa=221]

[1]	valid_0's binary_logloss: 0.620728
[2]	valid_0's binary_logloss: 0.59623
[3]	valid_0's binary_logloss: 0.572979
[4]	valid_0's binary_logloss: 0.552171
[5]	valid_0's binary_logloss: 0.533723
[6]	valid_0's binary_logloss: 0.516778
[7]	valid_0's binary_logloss: 0.500948
[8]	valid_0's binary_logloss: 0.485665
[9]	valid_0's binary_logloss: 0.472172
[10]	valid_0's binary_logloss: 0.459177
[11]	valid_0's binary_logloss: 0.447035
[12]	valid_0's binary_logloss: 0.435772
[13]	valid_0's binary_logloss: 0.424694
[14]	valid_0's binary_logloss: 0.414995
[15]	valid_0's binary_logloss: 0.405413
[16]	valid_0's binary_logloss: 0.396503
[17]	valid_0's binary_logloss: 0.388251
[18]	valid_0's binary_logloss: 0.380677
[19]	valid_0's binary_logloss: 0.37343
[20]	valid_0's binary_logloss: 0.366535
[21]	valid_0's binary_logloss: 0.360162
[22]	valid_0's binary_logloss: 0.354093
[23]	valid_0's binary_logloss: 0.348503
[24]	valid_0's binary_logloss: 0.343504
[25]	valid_0's binary_logloss: 0.338498
[26]	valid_0's binary_logloss: 0.333874
[27]	valid_0's binary_logloss: 0.32893
[28]	valid_0's binary_logloss: 0.324869
[29]	valid_0's binary_logloss: 0.321308
[30]	valid_0's binary_logloss: 0.317346
[31]	valid_0's binary_logloss: 0.3139
[32]	valid_0's binary_logloss: 0.310333
[33]	valid_0's binary_logloss: 0.306535
[34]	valid_0's binary_logloss: 0.30382
[35]	valid_0's binary_logloss: 0.300235
[36]	valid_0's binary_logloss: 0.297413
[37]	valid_0's binary_logloss: 0.29489
[38]	valid_0's binary_logloss: 0.292567
[39]	valid_0's binary_logloss: 0.29041
[40]	valid_0's binary_logloss: 0.288131
[41]	valid_0's binary_logloss: 0.285843
[42]	valid_0's binary_logloss: 0.283869
[43]	valid_0's binary_logloss: 0.281917
[44]	valid_0's binary_logloss: 0.280587
[45]	valid_0's binary_logloss: 0.279104
[46]	valid_0's binary_logloss: 0.27725
[47]	valid_0's binary_logloss: 0.275698
[48]	valid_0's binary_logloss: 0.274369
[49]	valid_0's binary_logloss: 0.272522
[50]	valid_0's binary_logloss: 0.271297
[51]	valid_0's binary_logloss: 0.269607
[52]	valid_0's binary_logloss: 0.268065
[53]	valid_0's binary_logloss: 0.266648
[54]	valid_0's binary_logloss: 0.265187
[55]	valid_0's binary_logloss: 0.263803
[56]	valid_0's binary_logloss: 0.262895
[57]	valid_0's binary_logloss: 0.261876
[58]	valid_0's binary_logloss: 0.260858
[59]	valid_0's binary_logloss: 0.26005
[60]	valid_0's binary_logloss: 0.25912
[61]	valid_0's binary_logloss: 0.258194
[62]	valid_0's binary_logloss: 0.257418
[63]	valid_0's binary_logloss: 0.256867
[64]	valid_0's binary_logloss: 0.256079
[65]	valid_0's binary_logloss: 0.255043
[66]	valid_0's binary_logloss: 0.254093
[67]	valid_0's binary_logloss: 0.253476
[68]	valid_0's binary_logloss: 0.253158
[69]	valid_0's binary_logloss: 0.252365
[70]	valid_0's binary_logloss: 0.252092
[71]	valid_0's binary_logloss: 0.25123
[72]	valid_0's binary_logloss: 0.250589
[73]	valid_0's binary_logloss: 0.249945
[74]	valid_0's binary_logloss: 0.249336
[75]	valid_0's binary_logloss: 0.248587
[76]	valid_0's binary_logloss: 0.248242
[77]	valid_0's binary_logloss: 0.247797
[78]	valid_0's binary_logloss: 0.247318
[79]	valid_0's binary_logloss: 0.24699
[80]	valid_0's binary_logloss: 0.246529
[81]	valid_0's binary_logloss: 0.246024
[82]	valid_0's binary_logloss: 0.24566
[83]	valid_0's binary_logloss: 0.245363
[84]	valid_0's binary_logloss: 0.245182
[85]	valid_0's binary_logloss: 0.244983
[86]	valid_0's binary_logloss: 0.244393
[87]	valid_0's binary_logloss: 0.243817
[88]	valid_0's binary_logloss: 0.24349
[89]	valid_0's binary_logloss: 0.243315
[90]	valid_0's binary_logloss: 0.24298
[91]	valid_0's binary_logloss: 0.242697
[92]	valid_0's binary_logloss: 0.242086
[93]	valid_0's binary_logloss: 0.241776
[94]	valid_0's binary_logloss: 0.24168
[95]	valid_0's binary_logloss: 0.241378
[96]	valid_0's binary_logloss: 0.241236
[97]	valid_0's binary_logloss: 0.240911
[98]	valid_0's binary_logloss: 0.240785
[99]	valid_0's binary_logloss: 0.240767
[100]	valid_0's binary_logloss: 0.240764
[101]	valid_0's binary_logloss: 0.240622
[102]	valid_0's binary_logloss: 0.240539
[103]	valid_0's binary_logloss: 0.240461
[104]	valid_0's binary_logloss: 0.240369
[105]	valid_0's binary_logloss: 0.240282
[106]	valid_0's binary_logloss: 0.239855
[107]	valid_0's binary_logloss: 0.239481
[108]	valid_0's binary_logloss: 0.239337
[109]	valid_0's binary_logloss: 0.239089
[110]	valid_0's binary_logloss: 0.238802
[111]	valid_0's binary_logloss: 0.238546
[112]	valid_0's binary_logloss: 0.238307
[113]	valid_0's binary_logloss: 0.238112
[114]	valid_0's binary_logloss: 0.237985
[115]	valid_0's binary_logloss: 0.237956
[116]	valid_0's binary_logloss: 0.237901
[117]	valid_0's binary_logloss: 0.237796
[118]	valid_0's binary_logloss: 0.237558
[119]	valid_0's binary_logloss: 0.237322
[120]	valid_0's binary_logloss: 0.237223
[121]	valid_0's binary_logloss: 0.236787
[122]	valid_0's binary_logloss: 0.236558
[123]	valid_0's binary_logloss: 0.236436
[124]	valid_0's binary_logloss: 0.236312
[125]	valid_0's binary_logloss: 0.236246
[126]	valid_0's binary_logloss: 0.236231
[127]	valid_0's binary_logloss: 0.236146
[128]	valid_0's binary_logloss: 0.236209
[129]	valid_0's binary_logloss: 0.236197
[130]	valid_0's binary_logloss: 0.236411
[131]	valid_0's binary_logloss: 0.236291
[132]	valid_0's binary_logloss: 0.236207
[133]	valid_0's binary_logloss: 0.236147
[134]	valid_0's binary_logloss: 0.236154
[135]	valid_0's binary_logloss: 0.23595
[136]	valid_0's binary_logloss: 0.235757
[137]	valid_0's binary_logloss: 0.235584
[138]	valid_0's binary_logloss: 0.235638
[139]	valid_0's binary_logloss: 0.235589
[140]	valid_0's binary_logloss: 0.23542
[141]	valid_0's binary_logloss: 0.235261
[142]	valid_0's binary_logloss: 0.235304
[143]	valid_0's binary_logloss: 0.235392
[144]	valid_0's binary_logloss: 0.235349
[145]	valid_0's binary_logloss: 0.235262
[146]	valid_0's binary_logloss: 0.235106
[147]	valid_0's binary_logloss: 0.235128
[148]	valid_0's binary_logloss: 0.235208
[149]	valid_0's binary_logloss: 0.235044
[150]	valid_0's binary_logloss: 0.235174
[151]	valid_0's binary_logloss: 0.235045
[152]	valid_0's binary_logloss: 0.235093
[153]	valid_0's binary_logloss: 0.235037
[154]	valid_0's binary_logloss: 0.234985
[155]	valid_0's binary_logloss: 0.235004
[156]	valid_0's binary_logloss: 0.235032
[157]	valid_0's binary_logloss: 0.235019
[158]	valid_0's binary_logloss: 0.235015
[159]	valid_0's binary_logloss: 0.235096
[160]	valid_0's binary_logloss: 0.234921
[161]	valid_0's binary_logloss: 0.234781
[162]	valid_0's binary_logloss: 0.234551
[163]	valid_0's binary_logloss: 0.234514
[164]	valid_0's binary_logloss: 0.234373
[165]	valid_0's binary_logloss: 0.234346
[166]	valid_0's binary_logloss: 0.234263
[167]	valid_0's binary_logloss: 0.234243
[168]	valid_0's binary_logloss: 0.234154
[169]	valid_0's binary_logloss: 0.2341
[170]	valid_0's binary_logloss: 0.234125
[171]	valid_0's binary_logloss: 0.234032
[172]	valid_0's binary_logloss: 0.233982
[173]	valid_0's binary_logloss: 0.234059
[174]	valid_0's binary_logloss: 0.234145
[175]	valid_0's binary_logloss: 0.234164
[176]	valid_0's binary_logloss: 0.23425
[177]	valid_0's binary_logloss: 0.234331
[178]	valid_0's binary_logloss: 0.23425
[179]	valid_0's binary_logloss: 0.234187
[180]	valid_0's binary_logloss: 0.234195
[181]	valid_0's binary_logloss: 0.234302
[182]	valid_0's binary_logloss: 0.2344
[183]	valid_0's binary_logloss: 0.234305
[184]	valid_0's binary_logloss: 0.234314
[185]	valid_0's binary_logloss: 0.234412
[186]	valid_0's binary_logloss: 0.23446
[187]	valid_0's binary_logloss: 0.234407
[188]	valid_0's binary_logloss: 0.234509
[189]	valid_0's binary_logloss: 0.234605
[190]	valid_0's binary_logloss: 0.23446
[191]	valid_0's binary_logloss: 0.234377
[192]	valid_0's binary_logloss: 0.234303
[193]	valid_0's binary_logloss: 0.234453
[194]	valid_0's binary_logloss: 0.234398
[195]	valid_0's binary_logloss: 0.234454
[196]	valid_0's binary_logloss: 0.234437
[197]	valid_0's binary_logloss: 0.234381
[198]	valid_0's binary_logloss: 0.234524
[199]	valid_0's binary_logloss: 0.234438
[200]	valid_0's binary_logloss: 0.23444
[201]	valid_0's binary_logloss: 0.234419
[202]	valid_0's binary_logloss: 0.234536

Trening klas:   2%|▏         | 11/500 [02:28<2:22:01, 17.43s/klasa, klasa=class_11, F1_klasy=0.9343, F1_macro=0.9557, drzewa=172]




Trening klas:   2%|▏         | 12/500 [02:28<2:19:44, 17.18s/klasa, klasa=class_11, F1_klasy=0.9343, F1_macro=0.9557, drzewa=172]

[1]	valid_0's binary_logloss: 0.634535
[2]	valid_0's binary_logloss: 0.608463
[3]	valid_0's binary_logloss: 0.583629
[4]	valid_0's binary_logloss: 0.560993
[5]	valid_0's binary_logloss: 0.540423
[6]	valid_0's binary_logloss: 0.521736
[7]	valid_0's binary_logloss: 0.504985
[8]	valid_0's binary_logloss: 0.489083
[9]	valid_0's binary_logloss: 0.473941
[10]	valid_0's binary_logloss: 0.460383
[11]	valid_0's binary_logloss: 0.447474
[12]	valid_0's binary_logloss: 0.43512
[13]	valid_0's binary_logloss: 0.423806
[14]	valid_0's binary_logloss: 0.413706
[15]	valid_0's binary_logloss: 0.403947
[16]	valid_0's binary_logloss: 0.394545
[17]	valid_0's binary_logloss: 0.386416
[18]	valid_0's binary_logloss: 0.378308
[19]	valid_0's binary_logloss: 0.370928
[20]	valid_0's binary_logloss: 0.364288
[21]	valid_0's binary_logloss: 0.357618
[22]	valid_0's binary_logloss: 0.351143
[23]	valid_0's binary_logloss: 0.345481
[24]	valid_0's binary_logloss: 0.340492
[25]	valid_0's binary_logloss: 0.335242
[26]	valid_0's binary_logloss: 0.330692
[27]	valid_0's binary_logloss: 0.325924
[28]	valid_0's binary_logloss: 0.321605
[29]	valid_0's binary_logloss: 0.317797
[30]	valid_0's binary_logloss: 0.31428
[31]	valid_0's binary_logloss: 0.31088
[32]	valid_0's binary_logloss: 0.30748
[33]	valid_0's binary_logloss: 0.303843
[34]	valid_0's binary_logloss: 0.300608
[35]	valid_0's binary_logloss: 0.297698
[36]	valid_0's binary_logloss: 0.294968
[37]	valid_0's binary_logloss: 0.292189
[38]	valid_0's binary_logloss: 0.289642
[39]	valid_0's binary_logloss: 0.287164
[40]	valid_0's binary_logloss: 0.284951
[41]	valid_0's binary_logloss: 0.283092
[42]	valid_0's binary_logloss: 0.281217
[43]	valid_0's binary_logloss: 0.27938
[44]	valid_0's binary_logloss: 0.277499
[45]	valid_0's binary_logloss: 0.275759
[46]	valid_0's binary_logloss: 0.27423
[47]	valid_0's binary_logloss: 0.272064
[48]	valid_0's binary_logloss: 0.269938
[49]	valid_0's binary_logloss: 0.268066
[50]	valid_0's binary_logloss: 0.266047
[51]	valid_0's binary_logloss: 0.264363
[52]	valid_0's binary_logloss: 0.262887
[53]	valid_0's binary_logloss: 0.261581
[54]	valid_0's binary_logloss: 0.260015
[55]	valid_0's binary_logloss: 0.258775
[56]	valid_0's binary_logloss: 0.257893
[57]	valid_0's binary_logloss: 0.25671
[58]	valid_0's binary_logloss: 0.255743
[59]	valid_0's binary_logloss: 0.254849
[60]	valid_0's binary_logloss: 0.254072
[61]	valid_0's binary_logloss: 0.253035
[62]	valid_0's binary_logloss: 0.252046
[63]	valid_0's binary_logloss: 0.251184
[64]	valid_0's binary_logloss: 0.250328
[65]	valid_0's binary_logloss: 0.249472
[66]	valid_0's binary_logloss: 0.248552
[67]	valid_0's binary_logloss: 0.248005
[68]	valid_0's binary_logloss: 0.247298
[69]	valid_0's binary_logloss: 0.246758
[70]	valid_0's binary_logloss: 0.246414
[71]	valid_0's binary_logloss: 0.245934
[72]	valid_0's binary_logloss: 0.245365
[73]	valid_0's binary_logloss: 0.244665
[74]	valid_0's binary_logloss: 0.24361
[75]	valid_0's binary_logloss: 0.243289
[76]	valid_0's binary_logloss: 0.242951
[77]	valid_0's binary_logloss: 0.242721
[78]	valid_0's binary_logloss: 0.242483
[79]	valid_0's binary_logloss: 0.242216
[80]	valid_0's binary_logloss: 0.241754
[81]	valid_0's binary_logloss: 0.241216
[82]	valid_0's binary_logloss: 0.240845
[83]	valid_0's binary_logloss: 0.240375
[84]	valid_0's binary_logloss: 0.239988
[85]	valid_0's binary_logloss: 0.239773
[86]	valid_0's binary_logloss: 0.239494
[87]	valid_0's binary_logloss: 0.239322
[88]	valid_0's binary_logloss: 0.239074
[89]	valid_0's binary_logloss: 0.238915
[90]	valid_0's binary_logloss: 0.238813
[91]	valid_0's binary_logloss: 0.238308
[92]	valid_0's binary_logloss: 0.237612
[93]	valid_0's binary_logloss: 0.237193
[94]	valid_0's binary_logloss: 0.236776
[95]	valid_0's binary_logloss: 0.236608
[96]	valid_0's binary_logloss: 0.236521
[97]	valid_0's binary_logloss: 0.236502
[98]	valid_0's binary_logloss: 0.236367
[99]	valid_0's binary_logloss: 0.236135
[100]	valid_0's binary_logloss: 0.235979
[101]	valid_0's binary_logloss: 0.235606
[102]	valid_0's binary_logloss: 0.23545
[103]	valid_0's binary_logloss: 0.235386
[104]	valid_0's binary_logloss: 0.235308
[105]	valid_0's binary_logloss: 0.234984
[106]	valid_0's binary_logloss: 0.234834
[107]	valid_0's binary_logloss: 0.234552
[108]	valid_0's binary_logloss: 0.234179
[109]	valid_0's binary_logloss: 0.234132
[110]	valid_0's binary_logloss: 0.233775
[111]	valid_0's binary_logloss: 0.233607
[112]	valid_0's binary_logloss: 0.233273
[113]	valid_0's binary_logloss: 0.23334
[114]	valid_0's binary_logloss: 0.233026
[115]	valid_0's binary_logloss: 0.233113
[116]	valid_0's binary_logloss: 0.232889
[117]	valid_0's binary_logloss: 0.232769
[118]	valid_0's binary_logloss: 0.232544
[119]	valid_0's binary_logloss: 0.232433
[120]	valid_0's binary_logloss: 0.232332
[121]	valid_0's binary_logloss: 0.232104
[122]	valid_0's binary_logloss: 0.231878
[123]	valid_0's binary_logloss: 0.231528
[124]	valid_0's binary_logloss: 0.231336
[125]	valid_0's binary_logloss: 0.231394
[126]	valid_0's binary_logloss: 0.231392
[127]	valid_0's binary_logloss: 0.231204
[128]	valid_0's binary_logloss: 0.231106
[129]	valid_0's binary_logloss: 0.231033
[130]	valid_0's binary_logloss: 0.23106
[131]	valid_0's binary_logloss: 0.231013
[132]	valid_0's binary_logloss: 0.230867
[133]	valid_0's binary_logloss: 0.230772
[134]	valid_0's binary_logloss: 0.23063
[135]	valid_0's binary_logloss: 0.230584
[136]	valid_0's binary_logloss: 0.230573
[137]	valid_0's binary_logloss: 0.230592
[138]	valid_0's binary_logloss: 0.230721
[139]	valid_0's binary_logloss: 0.230735
[140]	valid_0's binary_logloss: 0.230708
[141]	valid_0's binary_logloss: 0.23056
[142]	valid_0's binary_logloss: 0.230612
[143]	valid_0's binary_logloss: 0.230429
[144]	valid_0's binary_logloss: 0.230241
[145]	valid_0's binary_logloss: 0.230011
[146]	valid_0's binary_logloss: 0.23004
[147]	valid_0's binary_logloss: 0.229822
[148]	valid_0's binary_logloss: 0.229703
[149]	valid_0's binary_logloss: 0.229619
[150]	valid_0's binary_logloss: 0.229567
[151]	valid_0's binary_logloss: 0.229422
[152]	valid_0's binary_logloss: 0.229379
[153]	valid_0's binary_logloss: 0.229254
[154]	valid_0's binary_logloss: 0.229173
[155]	valid_0's binary_logloss: 0.229142
[156]	valid_0's binary_logloss: 0.229292
[157]	valid_0's binary_logloss: 0.229386
[158]	valid_0's binary_logloss: 0.229389
[159]	valid_0's binary_logloss: 0.229393
[160]	valid_0's binary_logloss: 0.229052
[161]	valid_0's binary_logloss: 0.229061
[162]	valid_0's binary_logloss: 0.229088
[163]	valid_0's binary_logloss: 0.229029
[164]	valid_0's binary_logloss: 0.228901
[165]	valid_0's binary_logloss: 0.228803
[166]	valid_0's binary_logloss: 0.22872
[167]	valid_0's binary_logloss: 0.228528
[168]	valid_0's binary_logloss: 0.228516
[169]	valid_0's binary_logloss: 0.228428
[170]	valid_0's binary_logloss: 0.228397
[171]	valid_0's binary_logloss: 0.228572
[172]	valid_0's binary_logloss: 0.228612
[173]	valid_0's binary_logloss: 0.228494
[174]	valid_0's binary_logloss: 0.228401
[175]	valid_0's binary_logloss: 0.22842
[176]	valid_0's binary_logloss: 0.228355
[177]	valid_0's binary_logloss: 0.228449
[178]	valid_0's binary_logloss: 0.228476
[179]	valid_0's binary_logloss: 0.228515
[180]	valid_0's binary_logloss: 0.228527
[181]	valid_0's binary_logloss: 0.228588
[182]	valid_0's binary_logloss: 0.228552
[183]	valid_0's binary_logloss: 0.228573
[184]	valid_0's binary_logloss: 0.228584
[185]	valid_0's binary_logloss: 0.228677
[186]	valid_0's binary_logloss: 0.228803
[187]	valid_0's binary_logloss: 0.228771
[188]	valid_0's binary_logloss: 0.228763
[189]	valid_0's binary_logloss: 0.228725
[190]	valid_0's binary_logloss: 0.228447
[191]	valid_0's binary_logloss: 0.228335
[192]	valid_0's binary_logloss: 0.228245
[193]	valid_0's binary_logloss: 0.228214
[194]	valid_0's binary_logloss: 0.228278
[195]	valid_0's binary_logloss: 0.228334
[196]	valid_0's binary_logloss: 0.228253
[197]	valid_0's binary_logloss: 0.228255
[198]	valid_0's binary_logloss: 0.228232
[199]	valid_0's binary_logloss: 0.228061
[200]	valid_0's binary_logloss: 0.228037
[201]	valid_0's binary_logloss: 0.228101
[202]	valid_0's binary_logloss: 0.228243
[203]	valid_0's binary_logloss: 0.228122
[204]	valid_0's binary_logloss: 0.22809
[205]	valid_0's binary_logloss: 0.22807
[206]	valid_0's binary_logloss: 0.228099
[207]	valid_0's binary_logloss: 0.228042
[208]	valid_0's binary_logloss: 0.228091
[209]	valid_0's binary_logloss: 0.228106
[210]	valid_0's binary_logloss: 0.228017
[211]	valid_0's binary_logloss: 0.228126
[212]	valid_0's binary_logloss: 0.228141
[213]	valid_0's binary_logloss: 0.228228
[214]	valid_0's binary_logloss: 0.228354
[215]	valid_0's binary_logloss: 0.228401
[216]	valid_0's binary_logloss: 0.228416
[217]	valid_0's binary_logloss: 0.228401
[218]	valid_0's binary_logloss: 0.228343
[219]	valid_0's binary_logloss: 0.228542
[220]	valid_0's binary_logloss: 0.228574
[221]	valid_0's binary_logloss: 0.228464
[222]	valid_0's binary_logloss: 0.228381
[223]	valid_0's binary_logloss: 0.228449
[224]	valid_0's binary_logloss: 0.228376
[225]	valid_0's binary_logloss: 0.228389
[226]	valid_0's binary_logloss: 0.228432
[227]	valid_0's binary_logloss: 0.228443
[228]	valid_0's binary_logloss: 0.228445
[229]	valid_0's binary_logloss: 0.228302
[230]	valid_0's binary_logloss: 0.228403
[231]	valid_0's binary_logloss: 0.228486
[232]	valid_0's binary_logloss: 0.228406
[233]	valid_0's binary_logloss: 0.228296
[234]	valid_0's binary_logloss: 0.228245
[235]	valid_0's binary_logloss: 0.228316
[236]	valid_0's binary_logloss: 0.228231
[237]	valid_0's binary_logloss: 0.22826
[238]	valid_0's binary_logloss: 0.228371
[239]	valid_0's binary_logloss: 0.22846

Trening klas:   2%|▏         | 12/500 [02:48<2:19:44, 17.18s/klasa, klasa=class_12, F1_klasy=0.9350, F1_macro=0.9541, drzewa=210]




Trening klas:   3%|▎         | 13/500 [02:48<2:24:23, 17.79s/klasa, klasa=class_12, F1_klasy=0.9350, F1_macro=0.9541, drzewa=210]

[240]	valid_0's binary_logloss: 0.228408
[1]	valid_0's binary_logloss: 0.660853
[2]	valid_0's binary_logloss: 0.633202
[3]	valid_0's binary_logloss: 0.607191
[4]	valid_0's binary_logloss: 0.584667
[5]	valid_0's binary_logloss: 0.564015
[6]	valid_0's binary_logloss: 0.543943
[7]	valid_0's binary_logloss: 0.525099
[8]	valid_0's binary_logloss: 0.507753
[9]	valid_0's binary_logloss: 0.491803
[10]	valid_0's binary_logloss: 0.478086
[11]	valid_0's binary_logloss: 0.465436
[12]	valid_0's binary_logloss: 0.453417
[13]	valid_0's binary_logloss: 0.441939
[14]	valid_0's binary_logloss: 0.430862
[15]	valid_0's binary_logloss: 0.421525
[16]	valid_0's binary_logloss: 0.412402
[17]	valid_0's binary_logloss: 0.403672
[18]	valid_0's binary_logloss: 0.395848
[19]	valid_0's binary_logloss: 0.388129
[20]	valid_0's binary_logloss: 0.3811
[21]	valid_0's binary_logloss: 0.374238
[22]	valid_0's binary_logloss: 0.368267
[23]	valid_0's binary_logloss: 0.362276
[24]	valid_0's binary_logloss: 0.356435
[25]	valid_0's binary_logloss: 0.351322
[26]	valid_0's binary_logloss: 0.346025
[27]	valid_0's binary_logloss: 0.341334
[28]	valid_0's binary_logloss: 0.337296
[29]	valid_0's binary_logloss: 0.333295
[30]	valid_0's binary_logloss: 0.329738
[31]	valid_0's binary_logloss: 0.325643
[32]	valid_0's binary_logloss: 0.322157
[33]	valid_0's binary_logloss: 0.318373
[34]	valid_0's binary_logloss: 0.315362
[35]	valid_0's binary_logloss: 0.312238
[36]	valid_0's binary_logloss: 0.309005
[37]	valid_0's binary_logloss: 0.305987
[38]	valid_0's binary_logloss: 0.303339
[39]	valid_0's binary_logloss: 0.30065
[40]	valid_0's binary_logloss: 0.298286
[41]	valid_0's binary_logloss: 0.295964
[42]	valid_0's binary_logloss: 0.293892
[43]	valid_0's binary_logloss: 0.291869
[44]	valid_0's binary_logloss: 0.289673
[45]	valid_0's binary_logloss: 0.287912
[46]	valid_0's binary_logloss: 0.285963
[47]	valid_0's binary_logloss: 0.284225
[48]	valid_0's binary_logloss: 0.282198
[49]	valid_0's binary_logloss: 0.280927
[50]	valid_0's binary_logloss: 0.279495
[51]	valid_0's binary_logloss: 0.277715
[52]	valid_0's binary_logloss: 0.275925
[53]	valid_0's binary_logloss: 0.274504
[54]	valid_0's binary_logloss: 0.272922
[55]	valid_0's binary_logloss: 0.272075
[56]	valid_0's binary_logloss: 0.270985
[57]	valid_0's binary_logloss: 0.269916
[58]	valid_0's binary_logloss: 0.268712
[59]	valid_0's binary_logloss: 0.267486
[60]	valid_0's binary_logloss: 0.266768
[61]	valid_0's binary_logloss: 0.265827
[62]	valid_0's binary_logloss: 0.264708
[63]	valid_0's binary_logloss: 0.264063
[64]	valid_0's binary_logloss: 0.263043
[65]	valid_0's binary_logloss: 0.261898
[66]	valid_0's binary_logloss: 0.260798
[67]	valid_0's binary_logloss: 0.260141
[68]	valid_0's binary_logloss: 0.259263
[69]	valid_0's binary_logloss: 0.258542
[70]	valid_0's binary_logloss: 0.257756
[71]	valid_0's binary_logloss: 0.256954
[72]	valid_0's binary_logloss: 0.256352
[73]	valid_0's binary_logloss: 0.255666
[74]	valid_0's binary_logloss: 0.255239
[75]	valid_0's binary_logloss: 0.254626
[76]	valid_0's binary_logloss: 0.254259
[77]	valid_0's binary_logloss: 0.253652
[78]	valid_0's binary_logloss: 0.252996
[79]	valid_0's binary_logloss: 0.252558
[80]	valid_0's binary_logloss: 0.252015
[81]	valid_0's binary_logloss: 0.251669
[82]	valid_0's binary_logloss: 0.251401
[83]	valid_0's binary_logloss: 0.251096
[84]	valid_0's binary_logloss: 0.250801
[85]	valid_0's binary_logloss: 0.250578
[86]	valid_0's binary_logloss: 0.250174
[87]	valid_0's binary_logloss: 0.249669
[88]	valid_0's binary_logloss: 0.249182
[89]	valid_0's binary_logloss: 0.248972
[90]	valid_0's binary_logloss: 0.248473
[91]	valid_0's binary_logloss: 0.247953
[92]	valid_0's binary_logloss: 0.247677
[93]	valid_0's binary_logloss: 0.247328
[94]	valid_0's binary_logloss: 0.247257
[95]	valid_0's binary_logloss: 0.246976
[96]	valid_0's binary_logloss: 0.246487
[97]	valid_0's binary_logloss: 0.246536
[98]	valid_0's binary_logloss: 0.246323
[99]	valid_0's binary_logloss: 0.245928
[100]	valid_0's binary_logloss: 0.245759
[101]	valid_0's binary_logloss: 0.245707
[102]	valid_0's binary_logloss: 0.245737
[103]	valid_0's binary_logloss: 0.245379
[104]	valid_0's binary_logloss: 0.245047
[105]	valid_0's binary_logloss: 0.244597
[106]	valid_0's binary_logloss: 0.244458
[107]	valid_0's binary_logloss: 0.244388
[108]	valid_0's binary_logloss: 0.244285
[109]	valid_0's binary_logloss: 0.244132
[110]	valid_0's binary_logloss: 0.244071
[111]	valid_0's binary_logloss: 0.243996
[112]	valid_0's binary_logloss: 0.243651
[113]	valid_0's binary_logloss: 0.243188
[114]	valid_0's binary_logloss: 0.243233
[115]	valid_0's binary_logloss: 0.24305
[116]	valid_0's binary_logloss: 0.243026
[117]	valid_0's binary_logloss: 0.242764
[118]	valid_0's binary_logloss: 0.242568
[119]	valid_0's binary_logloss: 0.24242
[120]	valid_0's binary_logloss: 0.242433
[121]	valid_0's binary_logloss: 0.242441
[122]	valid_0's binary_logloss: 0.242528
[123]	valid_0's binary_logloss: 0.242403
[124]	valid_0's binary_logloss: 0.242278
[125]	valid_0's binary_logloss: 0.242305
[126]	valid_0's binary_logloss: 0.24218
[127]	valid_0's binary_logloss: 0.242032
[128]	valid_0's binary_logloss: 0.242163
[129]	valid_0's binary_logloss: 0.242017
[130]	valid_0's binary_logloss: 0.241913
[131]	valid_0's binary_logloss: 0.241789
[132]	valid_0's binary_logloss: 0.241459
[133]	valid_0's binary_logloss: 0.241418
[134]	valid_0's binary_logloss: 0.241686
[135]	valid_0's binary_logloss: 0.241588
[136]	valid_0's binary_logloss: 0.241429
[137]	valid_0's binary_logloss: 0.241196
[138]	valid_0's binary_logloss: 0.241138
[139]	valid_0's binary_logloss: 0.241136
[140]	valid_0's binary_logloss: 0.241199
[141]	valid_0's binary_logloss: 0.240989
[142]	valid_0's binary_logloss: 0.240822
[143]	valid_0's binary_logloss: 0.240954
[144]	valid_0's binary_logloss: 0.240864
[145]	valid_0's binary_logloss: 0.240978
[146]	valid_0's binary_logloss: 0.240943
[147]	valid_0's binary_logloss: 0.240812
[148]	valid_0's binary_logloss: 0.240425
[149]	valid_0's binary_logloss: 0.240286
[150]	valid_0's binary_logloss: 0.240178
[151]	valid_0's binary_logloss: 0.240179
[152]	valid_0's binary_logloss: 0.240169
[153]	valid_0's binary_logloss: 0.240073
[154]	valid_0's binary_logloss: 0.23993
[155]	valid_0's binary_logloss: 0.239879
[156]	valid_0's binary_logloss: 0.239784
[157]	valid_0's binary_logloss: 0.239591
[158]	valid_0's binary_logloss: 0.239587
[159]	valid_0's binary_logloss: 0.239333
[160]	valid_0's binary_logloss: 0.239332
[161]	valid_0's binary_logloss: 0.239195
[162]	valid_0's binary_logloss: 0.239095
[163]	valid_0's binary_logloss: 0.238762
[164]	valid_0's binary_logloss: 0.238623
[165]	valid_0's binary_logloss: 0.238594
[166]	valid_0's binary_logloss: 0.238698
[167]	valid_0's binary_logloss: 0.238699
[168]	valid_0's binary_logloss: 0.23877
[169]	valid_0's binary_logloss: 0.238761
[170]	valid_0's binary_logloss: 0.23887
[171]	valid_0's binary_logloss: 0.238825
[172]	valid_0's binary_logloss: 0.238667
[173]	valid_0's binary_logloss: 0.238723
[174]	valid_0's binary_logloss: 0.238676
[175]	valid_0's binary_logloss: 0.238635
[176]	valid_0's binary_logloss: 0.238582
[177]	valid_0's binary_logloss: 0.238538
[178]	valid_0's binary_logloss: 0.238421
[179]	valid_0's binary_logloss: 0.238293
[180]	valid_0's binary_logloss: 0.238362
[181]	valid_0's binary_logloss: 0.238253
[182]	valid_0's binary_logloss: 0.238086
[183]	valid_0's binary_logloss: 0.23807
[184]	valid_0's binary_logloss: 0.238263
[185]	valid_0's binary_logloss: 0.238246
[186]	valid_0's binary_logloss: 0.238232
[187]	valid_0's binary_logloss: 0.238217
[188]	valid_0's binary_logloss: 0.238034
[189]	valid_0's binary_logloss: 0.237932
[190]	valid_0's binary_logloss: 0.237923
[191]	valid_0's binary_logloss: 0.237788
[192]	valid_0's binary_logloss: 0.237736
[193]	valid_0's binary_logloss: 0.237933
[194]	valid_0's binary_logloss: 0.238075
[195]	valid_0's binary_logloss: 0.238089
[196]	valid_0's binary_logloss: 0.23817
[197]	valid_0's binary_logloss: 0.238209
[198]	valid_0's binary_logloss: 0.23829
[199]	valid_0's binary_logloss: 0.238337
[200]	valid_0's binary_logloss: 0.238271
[201]	valid_0's binary_logloss: 0.23815
[202]	valid_0's binary_logloss: 0.23827
[203]	valid_0's binary_logloss: 0.238263
[204]	valid_0's binary_logloss: 0.238333
[205]	valid_0's binary_logloss: 0.238467
[206]	valid_0's binary_logloss: 0.2384
[207]	valid_0's binary_logloss: 0.238425
[208]	valid_0's binary_logloss: 0.238397
[209]	valid_0's binary_logloss: 0.238331
[210]	valid_0's binary_logloss: 0.238401
[211]	valid_0's binary_logloss: 0.238415
[212]	valid_0's binary_logloss: 0.238359
[213]	valid_0's binary_logloss: 0.238335
[214]	valid_0's binary_logloss: 0.238588
[215]	valid_0's binary_logloss: 0.238727
[216]	valid_0's binary_logloss: 0.238671
[217]	valid_0's binary_logloss: 0.238634
[218]	valid_0's binary_logloss: 0.238557
[219]	valid_0's binary_logloss: 0.238632
[220]	valid_0's binary_logloss: 0.238542

Trening klas:   3%|▎         | 13/500 [03:06<2:24:23, 17.79s/klasa, klasa=class_13, F1_klasy=0.9382, F1_macro=0.9530, drzewa=192]




Trening klas:   3%|▎         | 14/500 [03:06<2:25:53, 18.01s/klasa, klasa=class_13, F1_klasy=0.9382, F1_macro=0.9530, drzewa=192]

[221]	valid_0's binary_logloss: 0.238564
[222]	valid_0's binary_logloss: 0.238885
[1]	valid_0's binary_logloss: 0.661897
[2]	valid_0's binary_logloss: 0.634055
[3]	valid_0's binary_logloss: 0.609103
[4]	valid_0's binary_logloss: 0.586372
[5]	valid_0's binary_logloss: 0.566233
[6]	valid_0's binary_logloss: 0.545878
[7]	valid_0's binary_logloss: 0.527476
[8]	valid_0's binary_logloss: 0.510615
[9]	valid_0's binary_logloss: 0.49499
[10]	valid_0's binary_logloss: 0.481405
[11]	valid_0's binary_logloss: 0.468817
[12]	valid_0's binary_logloss: 0.457064
[13]	valid_0's binary_logloss: 0.445688
[14]	valid_0's binary_logloss: 0.434531
[15]	valid_0's binary_logloss: 0.424856
[16]	valid_0's binary_logloss: 0.416165
[17]	valid_0's binary_logloss: 0.407686
[18]	valid_0's binary_logloss: 0.399474
[19]	valid_0's binary_logloss: 0.39187
[20]	valid_0's binary_logloss: 0.384868
[21]	valid_0's binary_logloss: 0.378737
[22]	valid_0's binary_logloss: 0.372366
[23]	valid_0's binary_logloss: 0.366494
[24]	valid_0's binary_logloss: 0.360717
[25]	valid_0's binary_logloss: 0.355538
[26]	valid_0's binary_logloss: 0.350346
[27]	valid_0's binary_logloss: 0.345922
[28]	valid_0's binary_logloss: 0.341599
[29]	valid_0's binary_logloss: 0.337652
[30]	valid_0's binary_logloss: 0.33362
[31]	valid_0's binary_logloss: 0.329497
[32]	valid_0's binary_logloss: 0.325866
[33]	valid_0's binary_logloss: 0.322549
[34]	valid_0's binary_logloss: 0.319106
[35]	valid_0's binary_logloss: 0.316277
[36]	valid_0's binary_logloss: 0.313477
[37]	valid_0's binary_logloss: 0.310398
[38]	valid_0's binary_logloss: 0.307585
[39]	valid_0's binary_logloss: 0.304866
[40]	valid_0's binary_logloss: 0.302451
[41]	valid_0's binary_logloss: 0.300127
[42]	valid_0's binary_logloss: 0.29797
[43]	valid_0's binary_logloss: 0.296348
[44]	valid_0's binary_logloss: 0.2946
[45]	valid_0's binary_logloss: 0.292382
[46]	valid_0's binary_logloss: 0.290665
[47]	valid_0's binary_logloss: 0.28936
[48]	valid_0's binary_logloss: 0.287434
[49]	valid_0's binary_logloss: 0.28603
[50]	valid_0's binary_logloss: 0.284323
[51]	valid_0's binary_logloss: 0.282549
[52]	valid_0's binary_logloss: 0.280929
[53]	valid_0's binary_logloss: 0.279453
[54]	valid_0's binary_logloss: 0.27796
[55]	valid_0's binary_logloss: 0.276646
[56]	valid_0's binary_logloss: 0.27526
[57]	valid_0's binary_logloss: 0.274253
[58]	valid_0's binary_logloss: 0.273383
[59]	valid_0's binary_logloss: 0.272438
[60]	valid_0's binary_logloss: 0.271293
[61]	valid_0's binary_logloss: 0.270491
[62]	valid_0's binary_logloss: 0.269522
[63]	valid_0's binary_logloss: 0.268853
[64]	valid_0's binary_logloss: 0.267781
[65]	valid_0's binary_logloss: 0.266921
[66]	valid_0's binary_logloss: 0.266414
[67]	valid_0's binary_logloss: 0.265223
[68]	valid_0's binary_logloss: 0.264365
[69]	valid_0's binary_logloss: 0.263783
[70]	valid_0's binary_logloss: 0.263254
[71]	valid_0's binary_logloss: 0.262559
[72]	valid_0's binary_logloss: 0.262027
[73]	valid_0's binary_logloss: 0.261393
[74]	valid_0's binary_logloss: 0.260623
[75]	valid_0's binary_logloss: 0.259986
[76]	valid_0's binary_logloss: 0.259472
[77]	valid_0's binary_logloss: 0.258849
[78]	valid_0's binary_logloss: 0.2584
[79]	valid_0's binary_logloss: 0.258092
[80]	valid_0's binary_logloss: 0.257555
[81]	valid_0's binary_logloss: 0.257358
[82]	valid_0's binary_logloss: 0.256895
[83]	valid_0's binary_logloss: 0.256396
[84]	valid_0's binary_logloss: 0.256033
[85]	valid_0's binary_logloss: 0.255612
[86]	valid_0's binary_logloss: 0.255277
[87]	valid_0's binary_logloss: 0.254983
[88]	valid_0's binary_logloss: 0.254691
[89]	valid_0's binary_logloss: 0.25409
[90]	valid_0's binary_logloss: 0.253874
[91]	valid_0's binary_logloss: 0.253463
[92]	valid_0's binary_logloss: 0.253289
[93]	valid_0's binary_logloss: 0.253257
[94]	valid_0's binary_logloss: 0.252923
[95]	valid_0's binary_logloss: 0.252892
[96]	valid_0's binary_logloss: 0.25284
[97]	valid_0's binary_logloss: 0.252508
[98]	valid_0's binary_logloss: 0.252182
[99]	valid_0's binary_logloss: 0.251913
[100]	valid_0's binary_logloss: 0.251782
[101]	valid_0's binary_logloss: 0.251626
[102]	valid_0's binary_logloss: 0.251517
[103]	valid_0's binary_logloss: 0.251325
[104]	valid_0's binary_logloss: 0.251157
[105]	valid_0's binary_logloss: 0.250947
[106]	valid_0's binary_logloss: 0.250748
[107]	valid_0's binary_logloss: 0.250417
[108]	valid_0's binary_logloss: 0.250199
[109]	valid_0's binary_logloss: 0.249919
[110]	valid_0's binary_logloss: 0.249826
[111]	valid_0's binary_logloss: 0.249445
[112]	valid_0's binary_logloss: 0.249016
[113]	valid_0's binary_logloss: 0.248933
[114]	valid_0's binary_logloss: 0.248871
[115]	valid_0's binary_logloss: 0.248872
[116]	valid_0's binary_logloss: 0.248793
[117]	valid_0's binary_logloss: 0.24874
[118]	valid_0's binary_logloss: 0.248568
[119]	valid_0's binary_logloss: 0.248445
[120]	valid_0's binary_logloss: 0.248279
[121]	valid_0's binary_logloss: 0.248087
[122]	valid_0's binary_logloss: 0.248148
[123]	valid_0's binary_logloss: 0.248098
[124]	valid_0's binary_logloss: 0.248065
[125]	valid_0's binary_logloss: 0.24805
[126]	valid_0's binary_logloss: 0.247883
[127]	valid_0's binary_logloss: 0.247672
[128]	valid_0's binary_logloss: 0.24753
[129]	valid_0's binary_logloss: 0.247677
[130]	valid_0's binary_logloss: 0.247778
[131]	valid_0's binary_logloss: 0.24741
[132]	valid_0's binary_logloss: 0.247304
[133]	valid_0's binary_logloss: 0.247377
[134]	valid_0's binary_logloss: 0.247454
[135]	valid_0's binary_logloss: 0.247304
[136]	valid_0's binary_logloss: 0.247043
[137]	valid_0's binary_logloss: 0.246885
[138]	valid_0's binary_logloss: 0.246795
[139]	valid_0's binary_logloss: 0.24675
[140]	valid_0's binary_logloss: 0.246717
[141]	valid_0's binary_logloss: 0.246688
[142]	valid_0's binary_logloss: 0.246653
[143]	valid_0's binary_logloss: 0.246863
[144]	valid_0's binary_logloss: 0.246811
[145]	valid_0's binary_logloss: 0.24675
[146]	valid_0's binary_logloss: 0.246574
[147]	valid_0's binary_logloss: 0.24644
[148]	valid_0's binary_logloss: 0.246429
[149]	valid_0's binary_logloss: 0.246217
[150]	valid_0's binary_logloss: 0.246224
[151]	valid_0's binary_logloss: 0.246123
[152]	valid_0's binary_logloss: 0.246058
[153]	valid_0's binary_logloss: 0.246066
[154]	valid_0's binary_logloss: 0.246166
[155]	valid_0's binary_logloss: 0.245966
[156]	valid_0's binary_logloss: 0.245822
[157]	valid_0's binary_logloss: 0.245638
[158]	valid_0's binary_logloss: 0.245514
[159]	valid_0's binary_logloss: 0.245515
[160]	valid_0's binary_logloss: 0.245379
[161]	valid_0's binary_logloss: 0.245354
[162]	valid_0's binary_logloss: 0.245289
[163]	valid_0's binary_logloss: 0.245318
[164]	valid_0's binary_logloss: 0.245297
[165]	valid_0's binary_logloss: 0.245193
[166]	valid_0's binary_logloss: 0.245215
[167]	valid_0's binary_logloss: 0.245214
[168]	valid_0's binary_logloss: 0.245221
[169]	valid_0's binary_logloss: 0.245171
[170]	valid_0's binary_logloss: 0.245159
[171]	valid_0's binary_logloss: 0.245047
[172]	valid_0's binary_logloss: 0.24496
[173]	valid_0's binary_logloss: 0.244951
[174]	valid_0's binary_logloss: 0.244988
[175]	valid_0's binary_logloss: 0.245024
[176]	valid_0's binary_logloss: 0.244966
[177]	valid_0's binary_logloss: 0.244911
[178]	valid_0's binary_logloss: 0.244947
[179]	valid_0's binary_logloss: 0.244945
[180]	valid_0's binary_logloss: 0.244862
[181]	valid_0's binary_logloss: 0.244777
[182]	valid_0's binary_logloss: 0.244829
[183]	valid_0's binary_logloss: 0.244698
[184]	valid_0's binary_logloss: 0.244919
[185]	valid_0's binary_logloss: 0.24505
[186]	valid_0's binary_logloss: 0.245069
[187]	valid_0's binary_logloss: 0.245128
[188]	valid_0's binary_logloss: 0.245288
[189]	valid_0's binary_logloss: 0.245192
[190]	valid_0's binary_logloss: 0.245377
[191]	valid_0's binary_logloss: 0.245474
[192]	valid_0's binary_logloss: 0.245708
[193]	valid_0's binary_logloss: 0.245693
[194]	valid_0's binary_logloss: 0.245634
[195]	valid_0's binary_logloss: 0.245655
[196]	valid_0's binary_logloss: 0.245724
[197]	valid_0's binary_logloss: 0.245756
[198]	valid_0's binary_logloss: 0.245644
[199]	valid_0's binary_logloss: 0.245543
[200]	valid_0's binary_logloss: 0.245696
[201]	valid_0's binary_logloss: 0.245557
[202]	valid_0's binary_logloss: 0.245528
[203]	valid_0's binary_logloss: 0.245428
[204]	valid_0's binary_logloss: 0.245225
[205]	valid_0's binary_logloss: 0.245351
[206]	valid_0's binary_logloss: 0.245322
[207]	valid_0's binary_logloss: 0.245235
[208]	valid_0's binary_logloss: 0.245425
[209]	valid_0's binary_logloss: 0.245556
[210]	valid_0's binary_logloss: 0.245676
[211]	valid_0's binary_logloss: 0.24566
[212]	valid_0's binary_logloss: 0.245829

Trening klas:   3%|▎         | 14/500 [03:24<2:25:53, 18.01s/klasa, klasa=class_14, F1_klasy=0.9369, F1_macro=0.9519, drzewa=183]




Trening klas:   3%|▎         | 15/500 [03:24<2:24:48, 17.91s/klasa, klasa=class_14, F1_klasy=0.9369, F1_macro=0.9519, drzewa=183]

[213]	valid_0's binary_logloss: 0.245719
[1]	valid_0's binary_logloss: 0.671314
[2]	valid_0's binary_logloss: 0.637845
[3]	valid_0's binary_logloss: 0.607129
[4]	valid_0's binary_logloss: 0.579855
[5]	valid_0's binary_logloss: 0.555286
[6]	valid_0's binary_logloss: 0.532552
[7]	valid_0's binary_logloss: 0.510831
[8]	valid_0's binary_logloss: 0.491026
[9]	valid_0's binary_logloss: 0.472682
[10]	valid_0's binary_logloss: 0.455337
[11]	valid_0's binary_logloss: 0.439443
[12]	valid_0's binary_logloss: 0.424789
[13]	valid_0's binary_logloss: 0.411505
[14]	valid_0's binary_logloss: 0.399693
[15]	valid_0's binary_logloss: 0.388618
[16]	valid_0's binary_logloss: 0.378051
[17]	valid_0's binary_logloss: 0.367797
[18]	valid_0's binary_logloss: 0.35827
[19]	valid_0's binary_logloss: 0.349504
[20]	valid_0's binary_logloss: 0.341194
[21]	valid_0's binary_logloss: 0.333458
[22]	valid_0's binary_logloss: 0.326074
[23]	valid_0's binary_logloss: 0.319004
[24]	valid_0's binary_logloss: 0.312471
[25]	valid_0's binary_logloss: 0.306666
[26]	valid_0's binary_logloss: 0.301376
[27]	valid_0's binary_logloss: 0.29612
[28]	valid_0's binary_logloss: 0.291028
[29]	valid_0's binary_logloss: 0.286563
[30]	valid_0's binary_logloss: 0.282514
[31]	valid_0's binary_logloss: 0.278577
[32]	valid_0's binary_logloss: 0.274968
[33]	valid_0's binary_logloss: 0.271731
[34]	valid_0's binary_logloss: 0.268879
[35]	valid_0's binary_logloss: 0.265761
[36]	valid_0's binary_logloss: 0.262763
[37]	valid_0's binary_logloss: 0.259905
[38]	valid_0's binary_logloss: 0.257454
[39]	valid_0's binary_logloss: 0.254887
[40]	valid_0's binary_logloss: 0.252633
[41]	valid_0's binary_logloss: 0.250167
[42]	valid_0's binary_logloss: 0.248072
[43]	valid_0's binary_logloss: 0.245992
[44]	valid_0's binary_logloss: 0.24446
[45]	valid_0's binary_logloss: 0.242654
[46]	valid_0's binary_logloss: 0.24091
[47]	valid_0's binary_logloss: 0.239231
[48]	valid_0's binary_logloss: 0.237914
[49]	valid_0's binary_logloss: 0.236413
[50]	valid_0's binary_logloss: 0.234861
[51]	valid_0's binary_logloss: 0.233489
[52]	valid_0's binary_logloss: 0.232278
[53]	valid_0's binary_logloss: 0.231336
[54]	valid_0's binary_logloss: 0.230079
[55]	valid_0's binary_logloss: 0.229177
[56]	valid_0's binary_logloss: 0.228182
[57]	valid_0's binary_logloss: 0.227026
[58]	valid_0's binary_logloss: 0.225729
[59]	valid_0's binary_logloss: 0.224989
[60]	valid_0's binary_logloss: 0.224074
[61]	valid_0's binary_logloss: 0.22333
[62]	valid_0's binary_logloss: 0.222161
[63]	valid_0's binary_logloss: 0.221622
[64]	valid_0's binary_logloss: 0.220696
[65]	valid_0's binary_logloss: 0.220011
[66]	valid_0's binary_logloss: 0.219295
[67]	valid_0's binary_logloss: 0.218362
[68]	valid_0's binary_logloss: 0.217458
[69]	valid_0's binary_logloss: 0.217012
[70]	valid_0's binary_logloss: 0.216342
[71]	valid_0's binary_logloss: 0.216184
[72]	valid_0's binary_logloss: 0.215801
[73]	valid_0's binary_logloss: 0.215508
[74]	valid_0's binary_logloss: 0.215167
[75]	valid_0's binary_logloss: 0.214801
[76]	valid_0's binary_logloss: 0.214357
[77]	valid_0's binary_logloss: 0.214045
[78]	valid_0's binary_logloss: 0.213899
[79]	valid_0's binary_logloss: 0.213271
[80]	valid_0's binary_logloss: 0.213076
[81]	valid_0's binary_logloss: 0.212682
[82]	valid_0's binary_logloss: 0.212443
[83]	valid_0's binary_logloss: 0.212066
[84]	valid_0's binary_logloss: 0.211892
[85]	valid_0's binary_logloss: 0.2117
[86]	valid_0's binary_logloss: 0.211395
[87]	valid_0's binary_logloss: 0.21107
[88]	valid_0's binary_logloss: 0.210928
[89]	valid_0's binary_logloss: 0.210932
[90]	valid_0's binary_logloss: 0.21074
[91]	valid_0's binary_logloss: 0.210237
[92]	valid_0's binary_logloss: 0.209933
[93]	valid_0's binary_logloss: 0.209831
[94]	valid_0's binary_logloss: 0.20972
[95]	valid_0's binary_logloss: 0.209409
[96]	valid_0's binary_logloss: 0.209443
[97]	valid_0's binary_logloss: 0.20902
[98]	valid_0's binary_logloss: 0.208721
[99]	valid_0's binary_logloss: 0.20855
[100]	valid_0's binary_logloss: 0.208543
[101]	valid_0's binary_logloss: 0.208371
[102]	valid_0's binary_logloss: 0.20807
[103]	valid_0's binary_logloss: 0.207956
[104]	valid_0's binary_logloss: 0.207748
[105]	valid_0's binary_logloss: 0.207777
[106]	valid_0's binary_logloss: 0.207919
[107]	valid_0's binary_logloss: 0.207754
[108]	valid_0's binary_logloss: 0.207739
[109]	valid_0's binary_logloss: 0.207943
[110]	valid_0's binary_logloss: 0.207778
[111]	valid_0's binary_logloss: 0.207822
[112]	valid_0's binary_logloss: 0.207869
[113]	valid_0's binary_logloss: 0.207866
[114]	valid_0's binary_logloss: 0.207787
[115]	valid_0's binary_logloss: 0.207649
[116]	valid_0's binary_logloss: 0.207464
[117]	valid_0's binary_logloss: 0.20751
[118]	valid_0's binary_logloss: 0.207422
[119]	valid_0's binary_logloss: 0.207458
[120]	valid_0's binary_logloss: 0.207438
[121]	valid_0's binary_logloss: 0.207473
[122]	valid_0's binary_logloss: 0.207268
[123]	valid_0's binary_logloss: 0.207079
[124]	valid_0's binary_logloss: 0.206993
[125]	valid_0's binary_logloss: 0.206776
[126]	valid_0's binary_logloss: 0.206668
[127]	valid_0's binary_logloss: 0.206522
[128]	valid_0's binary_logloss: 0.206403
[129]	valid_0's binary_logloss: 0.206095
[130]	valid_0's binary_logloss: 0.205872
[131]	valid_0's binary_logloss: 0.205895
[132]	valid_0's binary_logloss: 0.205709
[133]	valid_0's binary_logloss: 0.205886
[134]	valid_0's binary_logloss: 0.205831
[135]	valid_0's binary_logloss: 0.205476
[136]	valid_0's binary_logloss: 0.205562
[137]	valid_0's binary_logloss: 0.205578
[138]	valid_0's binary_logloss: 0.20547
[139]	valid_0's binary_logloss: 0.205348
[140]	valid_0's binary_logloss: 0.205308
[141]	valid_0's binary_logloss: 0.20534
[142]	valid_0's binary_logloss: 0.205343
[143]	valid_0's binary_logloss: 0.205589
[144]	valid_0's binary_logloss: 0.205609
[145]	valid_0's binary_logloss: 0.2057
[146]	valid_0's binary_logloss: 0.205765
[147]	valid_0's binary_logloss: 0.205642
[148]	valid_0's binary_logloss: 0.20545
[149]	valid_0's binary_logloss: 0.205404
[150]	valid_0's binary_logloss: 0.20566
[151]	valid_0's binary_logloss: 0.205721
[152]	valid_0's binary_logloss: 0.205571
[153]	valid_0's binary_logloss: 0.205626
[154]	valid_0's binary_logloss: 0.2056
[155]	valid_0's binary_logloss: 0.20557
[156]	valid_0's binary_logloss: 0.205371
[157]	valid_0's binary_logloss: 0.205188
[158]	valid_0's binary_logloss: 0.205057
[159]	valid_0's binary_logloss: 0.205159
[160]	valid_0's binary_logloss: 0.205158
[161]	valid_0's binary_logloss: 0.205105
[162]	valid_0's binary_logloss: 0.205073
[163]	valid_0's binary_logloss: 0.205097
[164]	valid_0's binary_logloss: 0.205133
[165]	valid_0's binary_logloss: 0.205146
[166]	valid_0's binary_logloss: 0.205242
[167]	valid_0's binary_logloss: 0.205172
[168]	valid_0's binary_logloss: 0.205187
[169]	valid_0's binary_logloss: 0.20542
[170]	valid_0's binary_logloss: 0.205455
[171]	valid_0's binary_logloss: 0.205438
[172]	valid_0's binary_logloss: 0.205505
[173]	valid_0's binary_logloss: 0.205371
[174]	valid_0's binary_logloss: 0.205523
[175]	valid_0's binary_logloss: 0.20544
[176]	valid_0's binary_logloss: 0.205498
[177]	valid_0's binary_logloss: 0.205576
[178]	valid_0's binary_logloss: 0.205691
[179]	valid_0's binary_logloss: 0.205604
[180]	valid_0's binary_logloss: 0.205645
[181]	valid_0's binary_logloss: 0.205682
[182]	valid_0's binary_logloss: 0.205791
[183]	valid_0's binary_logloss: 0.205886
[184]	valid_0's binary_logloss: 0.205898
[185]	valid_0's binary_logloss: 0.206106
[186]	valid_0's binary_logloss: 0.206069
[187]	valid_0's binary_logloss: 0.206076

Trening klas:   3%|▎         | 15/500 [03:38<2:24:48, 17.91s/klasa, klasa=class_15, F1_klasy=0.9299, F1_macro=0.9505, drzewa=158]




Trening klas:   3%|▎         | 16/500 [03:38<2:15:25, 16.79s/klasa, klasa=class_15, F1_klasy=0.9299, F1_macro=0.9505, drzewa=158]

[188]	valid_0's binary_logloss: 0.206397
[1]	valid_0's binary_logloss: 0.821617
[2]	valid_0's binary_logloss: 0.774785
[3]	valid_0's binary_logloss: 0.733825
[4]	valid_0's binary_logloss: 0.696318
[5]	valid_0's binary_logloss: 0.663686
[6]	valid_0's binary_logloss: 0.633914
[7]	valid_0's binary_logloss: 0.607292
[8]	valid_0's binary_logloss: 0.583835
[9]	valid_0's binary_logloss: 0.562705
[10]	valid_0's binary_logloss: 0.542342
[11]	valid_0's binary_logloss: 0.524158
[12]	valid_0's binary_logloss: 0.506884
[13]	valid_0's binary_logloss: 0.491293
[14]	valid_0's binary_logloss: 0.477329
[15]	valid_0's binary_logloss: 0.464285
[16]	valid_0's binary_logloss: 0.45285
[17]	valid_0's binary_logloss: 0.440979
[18]	valid_0's binary_logloss: 0.430977
[19]	valid_0's binary_logloss: 0.4216
[20]	valid_0's binary_logloss: 0.412943
[21]	valid_0's binary_logloss: 0.404363
[22]	valid_0's binary_logloss: 0.396208
[23]	valid_0's binary_logloss: 0.388587
[24]	valid_0's binary_logloss: 0.381101
[25]	valid_0's binary_logloss: 0.374846
[26]	valid_0's binary_logloss: 0.368612
[27]	valid_0's binary_logloss: 0.362801
[28]	valid_0's binary_logloss: 0.3578
[29]	valid_0's binary_logloss: 0.353013
[30]	valid_0's binary_logloss: 0.348315
[31]	valid_0's binary_logloss: 0.34422
[32]	valid_0's binary_logloss: 0.340113
[33]	valid_0's binary_logloss: 0.33665
[34]	valid_0's binary_logloss: 0.333126
[35]	valid_0's binary_logloss: 0.32995
[36]	valid_0's binary_logloss: 0.326554
[37]	valid_0's binary_logloss: 0.323747
[38]	valid_0's binary_logloss: 0.320687
[39]	valid_0's binary_logloss: 0.318239
[40]	valid_0's binary_logloss: 0.315813
[41]	valid_0's binary_logloss: 0.313522
[42]	valid_0's binary_logloss: 0.311341
[43]	valid_0's binary_logloss: 0.30925
[44]	valid_0's binary_logloss: 0.307164
[45]	valid_0's binary_logloss: 0.305506
[46]	valid_0's binary_logloss: 0.303824
[47]	valid_0's binary_logloss: 0.302325
[48]	valid_0's binary_logloss: 0.300291
[49]	valid_0's binary_logloss: 0.298759
[50]	valid_0's binary_logloss: 0.296924
[51]	valid_0's binary_logloss: 0.295417
[52]	valid_0's binary_logloss: 0.294126
[53]	valid_0's binary_logloss: 0.292638
[54]	valid_0's binary_logloss: 0.291346
[55]	valid_0's binary_logloss: 0.290097
[56]	valid_0's binary_logloss: 0.288811
[57]	valid_0's binary_logloss: 0.287671
[58]	valid_0's binary_logloss: 0.286896
[59]	valid_0's binary_logloss: 0.285835
[60]	valid_0's binary_logloss: 0.284723
[61]	valid_0's binary_logloss: 0.284098
[62]	valid_0's binary_logloss: 0.283165
[63]	valid_0's binary_logloss: 0.282312
[64]	valid_0's binary_logloss: 0.281789
[65]	valid_0's binary_logloss: 0.280874
[66]	valid_0's binary_logloss: 0.280104
[67]	valid_0's binary_logloss: 0.279444
[68]	valid_0's binary_logloss: 0.278522
[69]	valid_0's binary_logloss: 0.277687
[70]	valid_0's binary_logloss: 0.277246
[71]	valid_0's binary_logloss: 0.276692
[72]	valid_0's binary_logloss: 0.276095
[73]	valid_0's binary_logloss: 0.275683
[74]	valid_0's binary_logloss: 0.275386
[75]	valid_0's binary_logloss: 0.275117
[76]	valid_0's binary_logloss: 0.274699
[77]	valid_0's binary_logloss: 0.273958
[78]	valid_0's binary_logloss: 0.273698
[79]	valid_0's binary_logloss: 0.273637
[80]	valid_0's binary_logloss: 0.273302
[81]	valid_0's binary_logloss: 0.272912
[82]	valid_0's binary_logloss: 0.272724
[83]	valid_0's binary_logloss: 0.272525
[84]	valid_0's binary_logloss: 0.272317
[85]	valid_0's binary_logloss: 0.272158
[86]	valid_0's binary_logloss: 0.271664
[87]	valid_0's binary_logloss: 0.27153
[88]	valid_0's binary_logloss: 0.271513
[89]	valid_0's binary_logloss: 0.271339
[90]	valid_0's binary_logloss: 0.270995
[91]	valid_0's binary_logloss: 0.27081
[92]	valid_0's binary_logloss: 0.270664
[93]	valid_0's binary_logloss: 0.270021
[94]	valid_0's binary_logloss: 0.269358
[95]	valid_0's binary_logloss: 0.269105
[96]	valid_0's binary_logloss: 0.268851
[97]	valid_0's binary_logloss: 0.268729
[98]	valid_0's binary_logloss: 0.268572
[99]	valid_0's binary_logloss: 0.268454
[100]	valid_0's binary_logloss: 0.268128
[101]	valid_0's binary_logloss: 0.267969
[102]	valid_0's binary_logloss: 0.267757
[103]	valid_0's binary_logloss: 0.267488
[104]	valid_0's binary_logloss: 0.267589
[105]	valid_0's binary_logloss: 0.267522
[106]	valid_0's binary_logloss: 0.267419
[107]	valid_0's binary_logloss: 0.267405
[108]	valid_0's binary_logloss: 0.267039
[109]	valid_0's binary_logloss: 0.266929
[110]	valid_0's binary_logloss: 0.267019
[111]	valid_0's binary_logloss: 0.266685
[112]	valid_0's binary_logloss: 0.266533
[113]	valid_0's binary_logloss: 0.266429
[114]	valid_0's binary_logloss: 0.266146
[115]	valid_0's binary_logloss: 0.266052
[116]	valid_0's binary_logloss: 0.266008
[117]	valid_0's binary_logloss: 0.266062
[118]	valid_0's binary_logloss: 0.266051
[119]	valid_0's binary_logloss: 0.265868
[120]	valid_0's binary_logloss: 0.265795
[121]	valid_0's binary_logloss: 0.265653
[122]	valid_0's binary_logloss: 0.26559
[123]	valid_0's binary_logloss: 0.26559
[124]	valid_0's binary_logloss: 0.265831
[125]	valid_0's binary_logloss: 0.265529
[126]	valid_0's binary_logloss: 0.265368
[127]	valid_0's binary_logloss: 0.264984
[128]	valid_0's binary_logloss: 0.264891
[129]	valid_0's binary_logloss: 0.264822
[130]	valid_0's binary_logloss: 0.2646
[131]	valid_0's binary_logloss: 0.264569
[132]	valid_0's binary_logloss: 0.264585
[133]	valid_0's binary_logloss: 0.264616
[134]	valid_0's binary_logloss: 0.264678
[135]	valid_0's binary_logloss: 0.264582
[136]	valid_0's binary_logloss: 0.264628
[137]	valid_0's binary_logloss: 0.264688
[138]	valid_0's binary_logloss: 0.264881
[139]	valid_0's binary_logloss: 0.264751
[140]	valid_0's binary_logloss: 0.264512
[141]	valid_0's binary_logloss: 0.264399
[142]	valid_0's binary_logloss: 0.264341
[143]	valid_0's binary_logloss: 0.264422
[144]	valid_0's binary_logloss: 0.264479
[145]	valid_0's binary_logloss: 0.264606
[146]	valid_0's binary_logloss: 0.264568
[147]	valid_0's binary_logloss: 0.264479
[148]	valid_0's binary_logloss: 0.264463
[149]	valid_0's binary_logloss: 0.264521
[150]	valid_0's binary_logloss: 0.264571
[151]	valid_0's binary_logloss: 0.264616
[152]	valid_0's binary_logloss: 0.264612
[153]	valid_0's binary_logloss: 0.264467
[154]	valid_0's binary_logloss: 0.264304
[155]	valid_0's binary_logloss: 0.264407
[156]	valid_0's binary_logloss: 0.264488
[157]	valid_0's binary_logloss: 0.264587
[158]	valid_0's binary_logloss: 0.264737
[159]	valid_0's binary_logloss: 0.264736
[160]	valid_0's binary_logloss: 0.264813
[161]	valid_0's binary_logloss: 0.264767
[162]	valid_0's binary_logloss: 0.264615
[163]	valid_0's binary_logloss: 0.26447
[164]	valid_0's binary_logloss: 0.264476
[165]	valid_0's binary_logloss: 0.264271
[166]	valid_0's binary_logloss: 0.264074
[167]	valid_0's binary_logloss: 0.26418
[168]	valid_0's binary_logloss: 0.264252
[169]	valid_0's binary_logloss: 0.264221
[170]	valid_0's binary_logloss: 0.264317
[171]	valid_0's binary_logloss: 0.264272
[172]	valid_0's binary_logloss: 0.264249
[173]	valid_0's binary_logloss: 0.264196
[174]	valid_0's binary_logloss: 0.264043
[175]	valid_0's binary_logloss: 0.263784
[176]	valid_0's binary_logloss: 0.263747
[177]	valid_0's binary_logloss: 0.263595
[178]	valid_0's binary_logloss: 0.263651
[179]	valid_0's binary_logloss: 0.263484
[180]	valid_0's binary_logloss: 0.263375
[181]	valid_0's binary_logloss: 0.26325
[182]	valid_0's binary_logloss: 0.26321
[183]	valid_0's binary_logloss: 0.263222
[184]	valid_0's binary_logloss: 0.26331
[185]	valid_0's binary_logloss: 0.263317
[186]	valid_0's binary_logloss: 0.263378
[187]	valid_0's binary_logloss: 0.263483
[188]	valid_0's binary_logloss: 0.263464
[189]	valid_0's binary_logloss: 0.263456
[190]	valid_0's binary_logloss: 0.263626
[191]	valid_0's binary_logloss: 0.263732
[192]	valid_0's binary_logloss: 0.263818
[193]	valid_0's binary_logloss: 0.263751
[194]	valid_0's binary_logloss: 0.263698
[195]	valid_0's binary_logloss: 0.2635
[196]	valid_0's binary_logloss: 0.26347
[197]	valid_0's binary_logloss: 0.263593
[198]	valid_0's binary_logloss: 0.263652
[199]	valid_0's binary_logloss: 0.263773
[200]	valid_0's binary_logloss: 0.263809
[201]	valid_0's binary_logloss: 0.263858
[202]	valid_0's binary_logloss: 0.263851
[203]	valid_0's binary_logloss: 0.263997
[204]	valid_0's binary_logloss: 0.263994
[205]	valid_0's binary_logloss: 0.264076
[206]	valid_0's binary_logloss: 0.264273
[207]	valid_0's binary_logloss: 0.264424
[208]	valid_0's binary_logloss: 0.264573
[209]	valid_0's binary_logloss: 0.264696
[210]	valid_0's binary_logloss: 0.264658
[211]	valid_0's binary_logloss: 0.264777
[212]	valid_0's binary_logloss: 0.264753

Trening klas:   3%|▎         | 16/500 [03:55<2:15:25, 16.79s/klasa, klasa=class_16, F1_klasy=0.9293, F1_macro=0.9493, drzewa=182]




Trening klas:   3%|▎         | 17/500 [03:55<2:14:52, 16.76s/klasa, klasa=class_16, F1_klasy=0.9293, F1_macro=0.9493, drzewa=182]

[1]	valid_0's binary_logloss: 0.816251
[2]	valid_0's binary_logloss: 0.770843
[3]	valid_0's binary_logloss: 0.730161
[4]	valid_0's binary_logloss: 0.693371
[5]	valid_0's binary_logloss: 0.661774
[6]	valid_0's binary_logloss: 0.632597
[7]	valid_0's binary_logloss: 0.60665
[8]	valid_0's binary_logloss: 0.583337
[9]	valid_0's binary_logloss: 0.56204
[10]	valid_0's binary_logloss: 0.542615
[11]	valid_0's binary_logloss: 0.525145
[12]	valid_0's binary_logloss: 0.508687
[13]	valid_0's binary_logloss: 0.493501
[14]	valid_0's binary_logloss: 0.479689
[15]	valid_0's binary_logloss: 0.466828
[16]	valid_0's binary_logloss: 0.455802
[17]	valid_0's binary_logloss: 0.444289
[18]	valid_0's binary_logloss: 0.434466
[19]	valid_0's binary_logloss: 0.425327
[20]	valid_0's binary_logloss: 0.417081
[21]	valid_0's binary_logloss: 0.409036
[22]	valid_0's binary_logloss: 0.401678
[23]	valid_0's binary_logloss: 0.394893
[24]	valid_0's binary_logloss: 0.388061
[25]	valid_0's binary_logloss: 0.381896
[26]	valid_0's binary_logloss: 0.376163
[27]	valid_0's binary_logloss: 0.371258
[28]	valid_0's binary_logloss: 0.365975
[29]	valid_0's binary_logloss: 0.360996
[30]	valid_0's binary_logloss: 0.356776
[31]	valid_0's binary_logloss: 0.352883
[32]	valid_0's binary_logloss: 0.349204
[33]	valid_0's binary_logloss: 0.346082
[34]	valid_0's binary_logloss: 0.342603
[35]	valid_0's binary_logloss: 0.339824
[36]	valid_0's binary_logloss: 0.336957
[37]	valid_0's binary_logloss: 0.333894
[38]	valid_0's binary_logloss: 0.331228
[39]	valid_0's binary_logloss: 0.328935
[40]	valid_0's binary_logloss: 0.326587
[41]	valid_0's binary_logloss: 0.324524
[42]	valid_0's binary_logloss: 0.322722
[43]	valid_0's binary_logloss: 0.320705
[44]	valid_0's binary_logloss: 0.318778
[45]	valid_0's binary_logloss: 0.317305
[46]	valid_0's binary_logloss: 0.31577
[47]	valid_0's binary_logloss: 0.314301
[48]	valid_0's binary_logloss: 0.312981
[49]	valid_0's binary_logloss: 0.311436
[50]	valid_0's binary_logloss: 0.31055
[51]	valid_0's binary_logloss: 0.309254
[52]	valid_0's binary_logloss: 0.307889
[53]	valid_0's binary_logloss: 0.306299
[54]	valid_0's binary_logloss: 0.305353
[55]	valid_0's binary_logloss: 0.304402
[56]	valid_0's binary_logloss: 0.303631
[57]	valid_0's binary_logloss: 0.302661
[58]	valid_0's binary_logloss: 0.301507
[59]	valid_0's binary_logloss: 0.301005
[60]	valid_0's binary_logloss: 0.300082
[61]	valid_0's binary_logloss: 0.299213
[62]	valid_0's binary_logloss: 0.298468
[63]	valid_0's binary_logloss: 0.297972
[64]	valid_0's binary_logloss: 0.297584
[65]	valid_0's binary_logloss: 0.296615
[66]	valid_0's binary_logloss: 0.295766
[67]	valid_0's binary_logloss: 0.294905
[68]	valid_0's binary_logloss: 0.293866
[69]	valid_0's binary_logloss: 0.293027
[70]	valid_0's binary_logloss: 0.292404
[71]	valid_0's binary_logloss: 0.291929
[72]	valid_0's binary_logloss: 0.291481
[73]	valid_0's binary_logloss: 0.291137
[74]	valid_0's binary_logloss: 0.290603
[75]	valid_0's binary_logloss: 0.290412
[76]	valid_0's binary_logloss: 0.29011
[77]	valid_0's binary_logloss: 0.289575
[78]	valid_0's binary_logloss: 0.289201
[79]	valid_0's binary_logloss: 0.288733
[80]	valid_0's binary_logloss: 0.288392
[81]	valid_0's binary_logloss: 0.288027
[82]	valid_0's binary_logloss: 0.287716
[83]	valid_0's binary_logloss: 0.287124
[84]	valid_0's binary_logloss: 0.287047
[85]	valid_0's binary_logloss: 0.286681
[86]	valid_0's binary_logloss: 0.286161
[87]	valid_0's binary_logloss: 0.286032
[88]	valid_0's binary_logloss: 0.285906
[89]	valid_0's binary_logloss: 0.285603
[90]	valid_0's binary_logloss: 0.28533
[91]	valid_0's binary_logloss: 0.28527
[92]	valid_0's binary_logloss: 0.285241
[93]	valid_0's binary_logloss: 0.284903
[94]	valid_0's binary_logloss: 0.284624
[95]	valid_0's binary_logloss: 0.284995
[96]	valid_0's binary_logloss: 0.284756
[97]	valid_0's binary_logloss: 0.284509
[98]	valid_0's binary_logloss: 0.284634
[99]	valid_0's binary_logloss: 0.28426
[100]	valid_0's binary_logloss: 0.284065
[101]	valid_0's binary_logloss: 0.284053
[102]	valid_0's binary_logloss: 0.283666
[103]	valid_0's binary_logloss: 0.283441
[104]	valid_0's binary_logloss: 0.283121
[105]	valid_0's binary_logloss: 0.283042
[106]	valid_0's binary_logloss: 0.282853
[107]	valid_0's binary_logloss: 0.28272
[108]	valid_0's binary_logloss: 0.282943
[109]	valid_0's binary_logloss: 0.282992
[110]	valid_0's binary_logloss: 0.28272
[111]	valid_0's binary_logloss: 0.282819
[112]	valid_0's binary_logloss: 0.282752
[113]	valid_0's binary_logloss: 0.282693
[114]	valid_0's binary_logloss: 0.282554
[115]	valid_0's binary_logloss: 0.282517
[116]	valid_0's binary_logloss: 0.282623
[117]	valid_0's binary_logloss: 0.282571
[118]	valid_0's binary_logloss: 0.282571
[119]	valid_0's binary_logloss: 0.282658
[120]	valid_0's binary_logloss: 0.282916
[121]	valid_0's binary_logloss: 0.282577
[122]	valid_0's binary_logloss: 0.282462
[123]	valid_0's binary_logloss: 0.282278
[124]	valid_0's binary_logloss: 0.282473
[125]	valid_0's binary_logloss: 0.282618
[126]	valid_0's binary_logloss: 0.282478
[127]	valid_0's binary_logloss: 0.282126
[128]	valid_0's binary_logloss: 0.281899
[129]	valid_0's binary_logloss: 0.281959
[130]	valid_0's binary_logloss: 0.281872
[131]	valid_0's binary_logloss: 0.281769
[132]	valid_0's binary_logloss: 0.28174
[133]	valid_0's binary_logloss: 0.281805
[134]	valid_0's binary_logloss: 0.281814
[135]	valid_0's binary_logloss: 0.281901
[136]	valid_0's binary_logloss: 0.281813
[137]	valid_0's binary_logloss: 0.281762
[138]	valid_0's binary_logloss: 0.281739
[139]	valid_0's binary_logloss: 0.281716
[140]	valid_0's binary_logloss: 0.281685
[141]	valid_0's binary_logloss: 0.281593
[142]	valid_0's binary_logloss: 0.281244
[143]	valid_0's binary_logloss: 0.281227
[144]	valid_0's binary_logloss: 0.281388
[145]	valid_0's binary_logloss: 0.281333
[146]	valid_0's binary_logloss: 0.281629
[147]	valid_0's binary_logloss: 0.281782
[148]	valid_0's binary_logloss: 0.281655
[149]	valid_0's binary_logloss: 0.281497
[150]	valid_0's binary_logloss: 0.281772
[151]	valid_0's binary_logloss: 0.28186
[152]	valid_0's binary_logloss: 0.281997
[153]	valid_0's binary_logloss: 0.281998
[154]	valid_0's binary_logloss: 0.281809
[155]	valid_0's binary_logloss: 0.281866
[156]	valid_0's binary_logloss: 0.281814
[157]	valid_0's binary_logloss: 0.281743
[158]	valid_0's binary_logloss: 0.281768
[159]	valid_0's binary_logloss: 0.281862
[160]	valid_0's binary_logloss: 0.281841
[161]	valid_0's binary_logloss: 0.281835
[162]	valid_0's binary_logloss: 0.281778
[163]	valid_0's binary_logloss: 0.281978
[164]	valid_0's binary_logloss: 0.281974
[165]	valid_0's binary_logloss: 0.281817
[166]	valid_0's binary_logloss: 0.281648
[167]	valid_0's binary_logloss: 0.281586
[168]	valid_0's binary_logloss: 0.281557
[169]	valid_0's binary_logloss: 0.281514
[170]	valid_0's binary_logloss: 0.281503
[171]	valid_0's binary_logloss: 0.281817
[172]	valid_0's binary_logloss: 0.281711

Trening klas:   3%|▎         | 17/500 [04:08<2:14:52, 16.76s/klasa, klasa=class_17, F1_klasy=0.9243, F1_macro=0.9479, drzewa=143]




Trening klas:   4%|▎         | 18/500 [04:08<2:05:32, 15.63s/klasa, klasa=class_17, F1_klasy=0.9243, F1_macro=0.9479, drzewa=143]

[173]	valid_0's binary_logloss: 0.281653
[1]	valid_0's binary_logloss: 0.697628
[2]	valid_0's binary_logloss: 0.657435
[3]	valid_0's binary_logloss: 0.62108
[4]	valid_0's binary_logloss: 0.588216
[5]	valid_0's binary_logloss: 0.560098
[6]	valid_0's binary_logloss: 0.534409
[7]	valid_0's binary_logloss: 0.510958
[8]	valid_0's binary_logloss: 0.489023
[9]	valid_0's binary_logloss: 0.469105
[10]	valid_0's binary_logloss: 0.450665
[11]	valid_0's binary_logloss: 0.433582
[12]	valid_0's binary_logloss: 0.418758
[13]	valid_0's binary_logloss: 0.40437
[14]	valid_0's binary_logloss: 0.390748
[15]	valid_0's binary_logloss: 0.379004
[16]	valid_0's binary_logloss: 0.367669
[17]	valid_0's binary_logloss: 0.356549
[18]	valid_0's binary_logloss: 0.346341
[19]	valid_0's binary_logloss: 0.337135
[20]	valid_0's binary_logloss: 0.328846
[21]	valid_0's binary_logloss: 0.321285
[22]	valid_0's binary_logloss: 0.314223
[23]	valid_0's binary_logloss: 0.307664
[24]	valid_0's binary_logloss: 0.301527
[25]	valid_0's binary_logloss: 0.295319
[26]	valid_0's binary_logloss: 0.290124
[27]	valid_0's binary_logloss: 0.285019
[28]	valid_0's binary_logloss: 0.279752
[29]	valid_0's binary_logloss: 0.275233
[30]	valid_0's binary_logloss: 0.271211
[31]	valid_0's binary_logloss: 0.267386
[32]	valid_0's binary_logloss: 0.263648
[33]	valid_0's binary_logloss: 0.26057
[34]	valid_0's binary_logloss: 0.257328
[35]	valid_0's binary_logloss: 0.254131
[36]	valid_0's binary_logloss: 0.251492
[37]	valid_0's binary_logloss: 0.248889
[38]	valid_0's binary_logloss: 0.246491
[39]	valid_0's binary_logloss: 0.244209
[40]	valid_0's binary_logloss: 0.242037
[41]	valid_0's binary_logloss: 0.239755
[42]	valid_0's binary_logloss: 0.237795
[43]	valid_0's binary_logloss: 0.235494
[44]	valid_0's binary_logloss: 0.234012
[45]	valid_0's binary_logloss: 0.232518
[46]	valid_0's binary_logloss: 0.231117
[47]	valid_0's binary_logloss: 0.229726
[48]	valid_0's binary_logloss: 0.228421
[49]	valid_0's binary_logloss: 0.227465
[50]	valid_0's binary_logloss: 0.225963
[51]	valid_0's binary_logloss: 0.225298
[52]	valid_0's binary_logloss: 0.224529
[53]	valid_0's binary_logloss: 0.22316
[54]	valid_0's binary_logloss: 0.222315
[55]	valid_0's binary_logloss: 0.221541
[56]	valid_0's binary_logloss: 0.220562
[57]	valid_0's binary_logloss: 0.219568
[58]	valid_0's binary_logloss: 0.218602
[59]	valid_0's binary_logloss: 0.217871
[60]	valid_0's binary_logloss: 0.217028
[61]	valid_0's binary_logloss: 0.216218
[62]	valid_0's binary_logloss: 0.215229
[63]	valid_0's binary_logloss: 0.214509
[64]	valid_0's binary_logloss: 0.213656
[65]	valid_0's binary_logloss: 0.212916
[66]	valid_0's binary_logloss: 0.212505
[67]	valid_0's binary_logloss: 0.212008
[68]	valid_0's binary_logloss: 0.211164
[69]	valid_0's binary_logloss: 0.210612
[70]	valid_0's binary_logloss: 0.209996
[71]	valid_0's binary_logloss: 0.209646
[72]	valid_0's binary_logloss: 0.209167
[73]	valid_0's binary_logloss: 0.208668
[74]	valid_0's binary_logloss: 0.208153
[75]	valid_0's binary_logloss: 0.207745
[76]	valid_0's binary_logloss: 0.207485
[77]	valid_0's binary_logloss: 0.207308
[78]	valid_0's binary_logloss: 0.206867
[79]	valid_0's binary_logloss: 0.206869
[80]	valid_0's binary_logloss: 0.206319
[81]	valid_0's binary_logloss: 0.20625
[82]	valid_0's binary_logloss: 0.206415
[83]	valid_0's binary_logloss: 0.206486
[84]	valid_0's binary_logloss: 0.206514
[85]	valid_0's binary_logloss: 0.20628
[86]	valid_0's binary_logloss: 0.206159
[87]	valid_0's binary_logloss: 0.206011
[88]	valid_0's binary_logloss: 0.205909
[89]	valid_0's binary_logloss: 0.205697
[90]	valid_0's binary_logloss: 0.205416
[91]	valid_0's binary_logloss: 0.205221
[92]	valid_0's binary_logloss: 0.204991
[93]	valid_0's binary_logloss: 0.204946
[94]	valid_0's binary_logloss: 0.204725
[95]	valid_0's binary_logloss: 0.204591
[96]	valid_0's binary_logloss: 0.204208
[97]	valid_0's binary_logloss: 0.204001
[98]	valid_0's binary_logloss: 0.203814
[99]	valid_0's binary_logloss: 0.203728
[100]	valid_0's binary_logloss: 0.203557
[101]	valid_0's binary_logloss: 0.203354
[102]	valid_0's binary_logloss: 0.203266
[103]	valid_0's binary_logloss: 0.203256
[104]	valid_0's binary_logloss: 0.203054
[105]	valid_0's binary_logloss: 0.202995
[106]	valid_0's binary_logloss: 0.203031
[107]	valid_0's binary_logloss: 0.203167
[108]	valid_0's binary_logloss: 0.203403
[109]	valid_0's binary_logloss: 0.203216
[110]	valid_0's binary_logloss: 0.20343
[111]	valid_0's binary_logloss: 0.203162
[112]	valid_0's binary_logloss: 0.20301
[113]	valid_0's binary_logloss: 0.203269
[114]	valid_0's binary_logloss: 0.203365
[115]	valid_0's binary_logloss: 0.20346
[116]	valid_0's binary_logloss: 0.203281
[117]	valid_0's binary_logloss: 0.203265
[118]	valid_0's binary_logloss: 0.203227
[119]	valid_0's binary_logloss: 0.203259
[120]	valid_0's binary_logloss: 0.203253
[121]	valid_0's binary_logloss: 0.203153
[122]	valid_0's binary_logloss: 0.203193
[123]	valid_0's binary_logloss: 0.203153
[124]	valid_0's binary_logloss: 0.203034
[125]	valid_0's binary_logloss: 0.203164
[126]	valid_0's binary_logloss: 0.203
[127]	valid_0's binary_logloss: 0.202844
[128]	valid_0's binary_logloss: 0.202957
[129]	valid_0's binary_logloss: 0.202855
[130]	valid_0's binary_logloss: 0.202722
[131]	valid_0's binary_logloss: 0.202672
[132]	valid_0's binary_logloss: 0.202813
[133]	valid_0's binary_logloss: 0.203081
[134]	valid_0's binary_logloss: 0.203189
[135]	valid_0's binary_logloss: 0.20305
[136]	valid_0's binary_logloss: 0.203253
[137]	valid_0's binary_logloss: 0.20328
[138]	valid_0's binary_logloss: 0.203438
[139]	valid_0's binary_logloss: 0.203522
[140]	valid_0's binary_logloss: 0.203499
[141]	valid_0's binary_logloss: 0.203419
[142]	valid_0's binary_logloss: 0.203271
[143]	valid_0's binary_logloss: 0.203191
[144]	valid_0's binary_logloss: 0.20305
[145]	valid_0's binary_logloss: 0.203066
[146]	valid_0's binary_logloss: 0.202991
[147]	valid_0's binary_logloss: 0.20294
[148]	valid_0's binary_logloss: 0.203121
[149]	valid_0's binary_logloss: 0.203209
[150]	valid_0's binary_logloss: 0.203231
[151]	valid_0's binary_logloss: 0.203423
[152]	valid_0's binary_logloss: 0.203558
[153]	valid_0's binary_logloss: 0.203452
[154]	valid_0's binary_logloss: 0.203372
[155]	valid_0's binary_logloss: 0.20364
[156]	valid_0's binary_logloss: 0.203719
[157]	valid_0's binary_logloss: 0.20358
[158]	valid_0's binary_logloss: 0.203626
[159]	valid_0's binary_logloss: 0.203502
[160]	valid_0's binary_logloss: 0.203499
[161]	valid_0's binary_logloss: 0.203489

Trening klas:   4%|▎         | 18/500 [04:20<2:05:32, 15.63s/klasa, klasa=class_18, F1_klasy=0.9278, F1_macro=0.9468, drzewa=131]




Trening klas:   4%|▍         | 19/500 [04:20<1:56:16, 14.50s/klasa, klasa=class_18, F1_klasy=0.9278, F1_macro=0.9468, drzewa=131]

[1]	valid_0's binary_logloss: 0.596132
[2]	valid_0's binary_logloss: 0.574435
[3]	valid_0's binary_logloss: 0.555144
[4]	valid_0's binary_logloss: 0.536423
[5]	valid_0's binary_logloss: 0.519772
[6]	valid_0's binary_logloss: 0.505711
[7]	valid_0's binary_logloss: 0.493068
[8]	valid_0's binary_logloss: 0.481246
[9]	valid_0's binary_logloss: 0.47032
[10]	valid_0's binary_logloss: 0.459546
[11]	valid_0's binary_logloss: 0.449467
[12]	valid_0's binary_logloss: 0.44038
[13]	valid_0's binary_logloss: 0.431742
[14]	valid_0's binary_logloss: 0.424605
[15]	valid_0's binary_logloss: 0.417632
[16]	valid_0's binary_logloss: 0.410352
[17]	valid_0's binary_logloss: 0.403341
[18]	valid_0's binary_logloss: 0.397303
[19]	valid_0's binary_logloss: 0.391393
[20]	valid_0's binary_logloss: 0.386758
[21]	valid_0's binary_logloss: 0.382602
[22]	valid_0's binary_logloss: 0.377889
[23]	valid_0's binary_logloss: 0.373404
[24]	valid_0's binary_logloss: 0.369392
[25]	valid_0's binary_logloss: 0.366236
[26]	valid_0's binary_logloss: 0.363096
[27]	valid_0's binary_logloss: 0.360138
[28]	valid_0's binary_logloss: 0.356993
[29]	valid_0's binary_logloss: 0.354271
[30]	valid_0's binary_logloss: 0.351943
[31]	valid_0's binary_logloss: 0.349729
[32]	valid_0's binary_logloss: 0.347231
[33]	valid_0's binary_logloss: 0.345084
[34]	valid_0's binary_logloss: 0.343052
[35]	valid_0's binary_logloss: 0.34149
[36]	valid_0's binary_logloss: 0.339319
[37]	valid_0's binary_logloss: 0.337634
[38]	valid_0's binary_logloss: 0.335649
[39]	valid_0's binary_logloss: 0.333944
[40]	valid_0's binary_logloss: 0.332257
[41]	valid_0's binary_logloss: 0.330742
[42]	valid_0's binary_logloss: 0.329265
[43]	valid_0's binary_logloss: 0.32805
[44]	valid_0's binary_logloss: 0.326606
[45]	valid_0's binary_logloss: 0.325373
[46]	valid_0's binary_logloss: 0.324186
[47]	valid_0's binary_logloss: 0.32267
[48]	valid_0's binary_logloss: 0.32163
[49]	valid_0's binary_logloss: 0.320346
[50]	valid_0's binary_logloss: 0.319213
[51]	valid_0's binary_logloss: 0.318179
[52]	valid_0's binary_logloss: 0.3169
[53]	valid_0's binary_logloss: 0.315461
[54]	valid_0's binary_logloss: 0.314789
[55]	valid_0's binary_logloss: 0.314025
[56]	valid_0's binary_logloss: 0.313013
[57]	valid_0's binary_logloss: 0.312122
[58]	valid_0's binary_logloss: 0.311689
[59]	valid_0's binary_logloss: 0.310745
[60]	valid_0's binary_logloss: 0.310143
[61]	valid_0's binary_logloss: 0.309433
[62]	valid_0's binary_logloss: 0.308518
[63]	valid_0's binary_logloss: 0.307803
[64]	valid_0's binary_logloss: 0.306923
[65]	valid_0's binary_logloss: 0.3066
[66]	valid_0's binary_logloss: 0.305993
[67]	valid_0's binary_logloss: 0.305363
[68]	valid_0's binary_logloss: 0.304571
[69]	valid_0's binary_logloss: 0.304357
[70]	valid_0's binary_logloss: 0.304131
[71]	valid_0's binary_logloss: 0.303419
[72]	valid_0's binary_logloss: 0.303166
[73]	valid_0's binary_logloss: 0.303019
[74]	valid_0's binary_logloss: 0.302536
[75]	valid_0's binary_logloss: 0.302134
[76]	valid_0's binary_logloss: 0.30152
[77]	valid_0's binary_logloss: 0.300833
[78]	valid_0's binary_logloss: 0.300563
[79]	valid_0's binary_logloss: 0.299839
[80]	valid_0's binary_logloss: 0.299221
[81]	valid_0's binary_logloss: 0.298872
[82]	valid_0's binary_logloss: 0.298391
[83]	valid_0's binary_logloss: 0.298151
[84]	valid_0's binary_logloss: 0.297772
[85]	valid_0's binary_logloss: 0.297511
[86]	valid_0's binary_logloss: 0.297354
[87]	valid_0's binary_logloss: 0.296982
[88]	valid_0's binary_logloss: 0.296884
[89]	valid_0's binary_logloss: 0.2963
[90]	valid_0's binary_logloss: 0.296148
[91]	valid_0's binary_logloss: 0.295891
[92]	valid_0's binary_logloss: 0.295868
[93]	valid_0's binary_logloss: 0.295464
[94]	valid_0's binary_logloss: 0.295385
[95]	valid_0's binary_logloss: 0.295025
[96]	valid_0's binary_logloss: 0.294917
[97]	valid_0's binary_logloss: 0.29473
[98]	valid_0's binary_logloss: 0.294712
[99]	valid_0's binary_logloss: 0.294627
[100]	valid_0's binary_logloss: 0.294209
[101]	valid_0's binary_logloss: 0.293884
[102]	valid_0's binary_logloss: 0.293629
[103]	valid_0's binary_logloss: 0.293495
[104]	valid_0's binary_logloss: 0.293201
[105]	valid_0's binary_logloss: 0.293056
[106]	valid_0's binary_logloss: 0.292971
[107]	valid_0's binary_logloss: 0.292682
[108]	valid_0's binary_logloss: 0.292515
[109]	valid_0's binary_logloss: 0.292186
[110]	valid_0's binary_logloss: 0.292158
[111]	valid_0's binary_logloss: 0.291982
[112]	valid_0's binary_logloss: 0.291782
[113]	valid_0's binary_logloss: 0.291697
[114]	valid_0's binary_logloss: 0.291681
[115]	valid_0's binary_logloss: 0.291638
[116]	valid_0's binary_logloss: 0.291317
[117]	valid_0's binary_logloss: 0.291074
[118]	valid_0's binary_logloss: 0.291048
[119]	valid_0's binary_logloss: 0.291049
[120]	valid_0's binary_logloss: 0.290654
[121]	valid_0's binary_logloss: 0.290384
[122]	valid_0's binary_logloss: 0.290169
[123]	valid_0's binary_logloss: 0.290075
[124]	valid_0's binary_logloss: 0.289773
[125]	valid_0's binary_logloss: 0.289601
[126]	valid_0's binary_logloss: 0.289355
[127]	valid_0's binary_logloss: 0.28939
[128]	valid_0's binary_logloss: 0.289484
[129]	valid_0's binary_logloss: 0.289504
[130]	valid_0's binary_logloss: 0.289433
[131]	valid_0's binary_logloss: 0.289303
[132]	valid_0's binary_logloss: 0.289127
[133]	valid_0's binary_logloss: 0.289
[134]	valid_0's binary_logloss: 0.288973
[135]	valid_0's binary_logloss: 0.288706
[136]	valid_0's binary_logloss: 0.288661
[137]	valid_0's binary_logloss: 0.28877
[138]	valid_0's binary_logloss: 0.288773
[139]	valid_0's binary_logloss: 0.28883
[140]	valid_0's binary_logloss: 0.288711
[141]	valid_0's binary_logloss: 0.288822
[142]	valid_0's binary_logloss: 0.288787
[143]	valid_0's binary_logloss: 0.28864
[144]	valid_0's binary_logloss: 0.288699
[145]	valid_0's binary_logloss: 0.288858
[146]	valid_0's binary_logloss: 0.288842
[147]	valid_0's binary_logloss: 0.288974
[148]	valid_0's binary_logloss: 0.288804
[149]	valid_0's binary_logloss: 0.288926
[150]	valid_0's binary_logloss: 0.288766
[151]	valid_0's binary_logloss: 0.288698
[152]	valid_0's binary_logloss: 0.288568
[153]	valid_0's binary_logloss: 0.288426
[154]	valid_0's binary_logloss: 0.288573
[155]	valid_0's binary_logloss: 0.288537
[156]	valid_0's binary_logloss: 0.288458
[157]	valid_0's binary_logloss: 0.288251
[158]	valid_0's binary_logloss: 0.288201
[159]	valid_0's binary_logloss: 0.288181
[160]	valid_0's binary_logloss: 0.288055
[161]	valid_0's binary_logloss: 0.287973
[162]	valid_0's binary_logloss: 0.28751
[163]	valid_0's binary_logloss: 0.287526
[164]	valid_0's binary_logloss: 0.287402
[165]	valid_0's binary_logloss: 0.28749
[166]	valid_0's binary_logloss: 0.287534
[167]	valid_0's binary_logloss: 0.287499
[168]	valid_0's binary_logloss: 0.287522
[169]	valid_0's binary_logloss: 0.287664
[170]	valid_0's binary_logloss: 0.287705
[171]	valid_0's binary_logloss: 0.287623
[172]	valid_0's binary_logloss: 0.287559
[173]	valid_0's binary_logloss: 0.287408
[174]	valid_0's binary_logloss: 0.287485
[175]	valid_0's binary_logloss: 0.287254
[176]	valid_0's binary_logloss: 0.28731
[177]	valid_0's binary_logloss: 0.287203
[178]	valid_0's binary_logloss: 0.287207
[179]	valid_0's binary_logloss: 0.28695
[180]	valid_0's binary_logloss: 0.286941
[181]	valid_0's binary_logloss: 0.286976
[182]	valid_0's binary_logloss: 0.287014
[183]	valid_0's binary_logloss: 0.287074
[184]	valid_0's binary_logloss: 0.287075
[185]	valid_0's binary_logloss: 0.287107
[186]	valid_0's binary_logloss: 0.287136
[187]	valid_0's binary_logloss: 0.28714
[188]	valid_0's binary_logloss: 0.28711
[189]	valid_0's binary_logloss: 0.287327
[190]	valid_0's binary_logloss: 0.287296
[191]	valid_0's binary_logloss: 0.287383
[192]	valid_0's binary_logloss: 0.287763
[193]	valid_0's binary_logloss: 0.28789
[194]	valid_0's binary_logloss: 0.287994
[195]	valid_0's binary_logloss: 0.288125
[196]	valid_0's binary_logloss: 0.288074
[197]	valid_0's binary_logloss: 0.288121
[198]	valid_0's binary_logloss: 0.288099
[199]	valid_0's binary_logloss: 0.288027
[200]	valid_0's binary_logloss: 0.288203
[201]	valid_0's binary_logloss: 0.288033
[202]	valid_0's binary_logloss: 0.288063
[203]	valid_0's binary_logloss: 0.288034
[204]	valid_0's binary_logloss: 0.287992
[205]	valid_0's binary_logloss: 0.287976
[206]	valid_0's binary_logloss: 0.287887
[207]	valid_0's binary_logloss: 0.287579
[208]	valid_0's binary_logloss: 0.28766
[209]	valid_0's binary_logloss: 0.287814
[210]	valid_0's binary_logloss: 0.287779

Trening klas:   4%|▍         | 19/500 [04:35<1:56:16, 14.50s/klasa, klasa=class_19, F1_klasy=0.7991, F1_macro=0.9395, drzewa=180]




Trening klas:   4%|▍         | 20/500 [04:35<1:59:00, 14.88s/klasa, klasa=class_19, F1_klasy=0.7991, F1_macro=0.9395, drzewa=180]

[1]	valid_0's binary_logloss: 0.684532
[2]	valid_0's binary_logloss: 0.643413
[3]	valid_0's binary_logloss: 0.606581
[4]	valid_0's binary_logloss: 0.574269
[5]	valid_0's binary_logloss: 0.546043
[6]	valid_0's binary_logloss: 0.51993
[7]	valid_0's binary_logloss: 0.496594
[8]	valid_0's binary_logloss: 0.476419
[9]	valid_0's binary_logloss: 0.456943
[10]	valid_0's binary_logloss: 0.439973
[11]	valid_0's binary_logloss: 0.423573
[12]	valid_0's binary_logloss: 0.409382
[13]	valid_0's binary_logloss: 0.396063
[14]	valid_0's binary_logloss: 0.384171
[15]	valid_0's binary_logloss: 0.373017
[16]	valid_0's binary_logloss: 0.362504
[17]	valid_0's binary_logloss: 0.352748
[18]	valid_0's binary_logloss: 0.343608
[19]	valid_0's binary_logloss: 0.335052
[20]	valid_0's binary_logloss: 0.327461
[21]	valid_0's binary_logloss: 0.320466
[22]	valid_0's binary_logloss: 0.31326
[23]	valid_0's binary_logloss: 0.306955
[24]	valid_0's binary_logloss: 0.301548
[25]	valid_0's binary_logloss: 0.295842
[26]	valid_0's binary_logloss: 0.290689
[27]	valid_0's binary_logloss: 0.286372
[28]	valid_0's binary_logloss: 0.282077
[29]	valid_0's binary_logloss: 0.2779
[30]	valid_0's binary_logloss: 0.274427
[31]	valid_0's binary_logloss: 0.270932
[32]	valid_0's binary_logloss: 0.267315
[33]	valid_0's binary_logloss: 0.264223
[34]	valid_0's binary_logloss: 0.26127
[35]	valid_0's binary_logloss: 0.258465
[36]	valid_0's binary_logloss: 0.255799
[37]	valid_0's binary_logloss: 0.253271
[38]	valid_0's binary_logloss: 0.251039
[39]	valid_0's binary_logloss: 0.249229
[40]	valid_0's binary_logloss: 0.247391
[41]	valid_0's binary_logloss: 0.245906
[42]	valid_0's binary_logloss: 0.244421
[43]	valid_0's binary_logloss: 0.24319
[44]	valid_0's binary_logloss: 0.241725
[45]	valid_0's binary_logloss: 0.240486
[46]	valid_0's binary_logloss: 0.238974
[47]	valid_0's binary_logloss: 0.238124
[48]	valid_0's binary_logloss: 0.236766
[49]	valid_0's binary_logloss: 0.235773
[50]	valid_0's binary_logloss: 0.235212
[51]	valid_0's binary_logloss: 0.234276
[52]	valid_0's binary_logloss: 0.233661
[53]	valid_0's binary_logloss: 0.232755
[54]	valid_0's binary_logloss: 0.232028
[55]	valid_0's binary_logloss: 0.231349
[56]	valid_0's binary_logloss: 0.230235
[57]	valid_0's binary_logloss: 0.229508
[58]	valid_0's binary_logloss: 0.228551
[59]	valid_0's binary_logloss: 0.227746
[60]	valid_0's binary_logloss: 0.226893
[61]	valid_0's binary_logloss: 0.22624
[62]	valid_0's binary_logloss: 0.225633
[63]	valid_0's binary_logloss: 0.225168
[64]	valid_0's binary_logloss: 0.224389
[65]	valid_0's binary_logloss: 0.223846
[66]	valid_0's binary_logloss: 0.223154
[67]	valid_0's binary_logloss: 0.222922
[68]	valid_0's binary_logloss: 0.222256
[69]	valid_0's binary_logloss: 0.221757
[70]	valid_0's binary_logloss: 0.221164
[71]	valid_0's binary_logloss: 0.221125
[72]	valid_0's binary_logloss: 0.221232
[73]	valid_0's binary_logloss: 0.221149
[74]	valid_0's binary_logloss: 0.22113
[75]	valid_0's binary_logloss: 0.220651
[76]	valid_0's binary_logloss: 0.220129
[77]	valid_0's binary_logloss: 0.219457
[78]	valid_0's binary_logloss: 0.219089
[79]	valid_0's binary_logloss: 0.218622
[80]	valid_0's binary_logloss: 0.218181
[81]	valid_0's binary_logloss: 0.217748
[82]	valid_0's binary_logloss: 0.217337
[83]	valid_0's binary_logloss: 0.21727
[84]	valid_0's binary_logloss: 0.217199
[85]	valid_0's binary_logloss: 0.216903
[86]	valid_0's binary_logloss: 0.216765
[87]	valid_0's binary_logloss: 0.216897
[88]	valid_0's binary_logloss: 0.216769
[89]	valid_0's binary_logloss: 0.216802
[90]	valid_0's binary_logloss: 0.216454
[91]	valid_0's binary_logloss: 0.216195
[92]	valid_0's binary_logloss: 0.216387
[93]	valid_0's binary_logloss: 0.216315
[94]	valid_0's binary_logloss: 0.216361
[95]	valid_0's binary_logloss: 0.216159
[96]	valid_0's binary_logloss: 0.216256
[97]	valid_0's binary_logloss: 0.216212
[98]	valid_0's binary_logloss: 0.216386
[99]	valid_0's binary_logloss: 0.216375
[100]	valid_0's binary_logloss: 0.216216
[101]	valid_0's binary_logloss: 0.216182
[102]	valid_0's binary_logloss: 0.216169
[103]	valid_0's binary_logloss: 0.215895
[104]	valid_0's binary_logloss: 0.21585
[105]	valid_0's binary_logloss: 0.215929
[106]	valid_0's binary_logloss: 0.215885
[107]	valid_0's binary_logloss: 0.215578
[108]	valid_0's binary_logloss: 0.215329
[109]	valid_0's binary_logloss: 0.215112
[110]	valid_0's binary_logloss: 0.215076
[111]	valid_0's binary_logloss: 0.214917
[112]	valid_0's binary_logloss: 0.21483
[113]	valid_0's binary_logloss: 0.214593
[114]	valid_0's binary_logloss: 0.214423
[115]	valid_0's binary_logloss: 0.214389
[116]	valid_0's binary_logloss: 0.214154
[117]	valid_0's binary_logloss: 0.213961
[118]	valid_0's binary_logloss: 0.213841
[119]	valid_0's binary_logloss: 0.213822
[120]	valid_0's binary_logloss: 0.213646
[121]	valid_0's binary_logloss: 0.213607
[122]	valid_0's binary_logloss: 0.213294
[123]	valid_0's binary_logloss: 0.213143
[124]	valid_0's binary_logloss: 0.213052
[125]	valid_0's binary_logloss: 0.213079
[126]	valid_0's binary_logloss: 0.212863
[127]	valid_0's binary_logloss: 0.212682
[128]	valid_0's binary_logloss: 0.212675
[129]	valid_0's binary_logloss: 0.212498
[130]	valid_0's binary_logloss: 0.212509
[131]	valid_0's binary_logloss: 0.212707
[132]	valid_0's binary_logloss: 0.212777
[133]	valid_0's binary_logloss: 0.212762
[134]	valid_0's binary_logloss: 0.212759
[135]	valid_0's binary_logloss: 0.21266
[136]	valid_0's binary_logloss: 0.212513
[137]	valid_0's binary_logloss: 0.212275
[138]	valid_0's binary_logloss: 0.212238
[139]	valid_0's binary_logloss: 0.211961
[140]	valid_0's binary_logloss: 0.212044
[141]	valid_0's binary_logloss: 0.211821
[142]	valid_0's binary_logloss: 0.211775
[143]	valid_0's binary_logloss: 0.211799
[144]	valid_0's binary_logloss: 0.211765
[145]	valid_0's binary_logloss: 0.211792
[146]	valid_0's binary_logloss: 0.211867
[147]	valid_0's binary_logloss: 0.211907
[148]	valid_0's binary_logloss: 0.212111
[149]	valid_0's binary_logloss: 0.212261
[150]	valid_0's binary_logloss: 0.212343
[151]	valid_0's binary_logloss: 0.212235
[152]	valid_0's binary_logloss: 0.212367
[153]	valid_0's binary_logloss: 0.212388
[154]	valid_0's binary_logloss: 0.212288
[155]	valid_0's binary_logloss: 0.212402
[156]	valid_0's binary_logloss: 0.212381
[157]	valid_0's binary_logloss: 0.212227
[158]	valid_0's binary_logloss: 0.21233
[159]	valid_0's binary_logloss: 0.212397
[160]	valid_0's binary_logloss: 0.212348
[161]	valid_0's binary_logloss: 0.212275
[162]	valid_0's binary_logloss: 0.212062
[163]	valid_0's binary_logloss: 0.211915
[164]	valid_0's binary_logloss: 0.211927
[165]	valid_0's binary_logloss: 0.212019
[166]	valid_0's binary_logloss: 0.212026
[167]	valid_0's binary_logloss: 0.211963
[168]	valid_0's binary_logloss: 0.211957
[169]	valid_0's binary_logloss: 0.211957
[170]	valid_0's binary_logloss: 0.212024
[171]	valid_0's binary_logloss: 0.211941
[172]	valid_0's binary_logloss: 0.21189
[173]	valid_0's binary_logloss: 0.211973
[174]	valid_0's binary_logloss: 0.212011

Trening klas:   4%|▍         | 20/500 [04:48<1:59:00, 14.88s/klasa, klasa=class_20, F1_klasy=0.9160, F1_macro=0.9383, drzewa=144]




Trening klas:   4%|▍         | 21/500 [04:48<1:53:28, 14.21s/klasa, klasa=class_20, F1_klasy=0.9160, F1_macro=0.9383, drzewa=144]

[1]	valid_0's binary_logloss: 0.588511
[2]	valid_0's binary_logloss: 0.565098
[3]	valid_0's binary_logloss: 0.544334
[4]	valid_0's binary_logloss: 0.52478
[5]	valid_0's binary_logloss: 0.507339
[6]	valid_0's binary_logloss: 0.492368
[7]	valid_0's binary_logloss: 0.479386
[8]	valid_0's binary_logloss: 0.467125
[9]	valid_0's binary_logloss: 0.455619
[10]	valid_0's binary_logloss: 0.44463
[11]	valid_0's binary_logloss: 0.43394
[12]	valid_0's binary_logloss: 0.424592
[13]	valid_0's binary_logloss: 0.415536
[14]	valid_0's binary_logloss: 0.408034
[15]	valid_0's binary_logloss: 0.40058
[16]	valid_0's binary_logloss: 0.393758
[17]	valid_0's binary_logloss: 0.387783
[18]	valid_0's binary_logloss: 0.381812
[19]	valid_0's binary_logloss: 0.376761
[20]	valid_0's binary_logloss: 0.371677
[21]	valid_0's binary_logloss: 0.366827
[22]	valid_0's binary_logloss: 0.36151
[23]	valid_0's binary_logloss: 0.356766
[24]	valid_0's binary_logloss: 0.352769
[25]	valid_0's binary_logloss: 0.348759
[26]	valid_0's binary_logloss: 0.345274
[27]	valid_0's binary_logloss: 0.342488
[28]	valid_0's binary_logloss: 0.339124
[29]	valid_0's binary_logloss: 0.336006
[30]	valid_0's binary_logloss: 0.333336
[31]	valid_0's binary_logloss: 0.330453
[32]	valid_0's binary_logloss: 0.327822
[33]	valid_0's binary_logloss: 0.325729
[34]	valid_0's binary_logloss: 0.323441
[35]	valid_0's binary_logloss: 0.321441
[36]	valid_0's binary_logloss: 0.319038
[37]	valid_0's binary_logloss: 0.317107
[38]	valid_0's binary_logloss: 0.315361
[39]	valid_0's binary_logloss: 0.313719
[40]	valid_0's binary_logloss: 0.312385
[41]	valid_0's binary_logloss: 0.310542
[42]	valid_0's binary_logloss: 0.309037
[43]	valid_0's binary_logloss: 0.307733
[44]	valid_0's binary_logloss: 0.306493
[45]	valid_0's binary_logloss: 0.305052
[46]	valid_0's binary_logloss: 0.304156
[47]	valid_0's binary_logloss: 0.302882
[48]	valid_0's binary_logloss: 0.301547
[49]	valid_0's binary_logloss: 0.300509
[50]	valid_0's binary_logloss: 0.299522
[51]	valid_0's binary_logloss: 0.298619
[52]	valid_0's binary_logloss: 0.297694
[53]	valid_0's binary_logloss: 0.296901
[54]	valid_0's binary_logloss: 0.295732
[55]	valid_0's binary_logloss: 0.294895
[56]	valid_0's binary_logloss: 0.293966
[57]	valid_0's binary_logloss: 0.293081
[58]	valid_0's binary_logloss: 0.292227
[59]	valid_0's binary_logloss: 0.291606
[60]	valid_0's binary_logloss: 0.290848
[61]	valid_0's binary_logloss: 0.290192
[62]	valid_0's binary_logloss: 0.289419
[63]	valid_0's binary_logloss: 0.289014
[64]	valid_0's binary_logloss: 0.288153
[65]	valid_0's binary_logloss: 0.287448
[66]	valid_0's binary_logloss: 0.286991
[67]	valid_0's binary_logloss: 0.28647
[68]	valid_0's binary_logloss: 0.285746
[69]	valid_0's binary_logloss: 0.285008
[70]	valid_0's binary_logloss: 0.284927
[71]	valid_0's binary_logloss: 0.284659
[72]	valid_0's binary_logloss: 0.284224
[73]	valid_0's binary_logloss: 0.283763
[74]	valid_0's binary_logloss: 0.283184
[75]	valid_0's binary_logloss: 0.282783
[76]	valid_0's binary_logloss: 0.282432
[77]	valid_0's binary_logloss: 0.281892
[78]	valid_0's binary_logloss: 0.281491
[79]	valid_0's binary_logloss: 0.28112
[80]	valid_0's binary_logloss: 0.280562
[81]	valid_0's binary_logloss: 0.280091
[82]	valid_0's binary_logloss: 0.279751
[83]	valid_0's binary_logloss: 0.279465
[84]	valid_0's binary_logloss: 0.279259
[85]	valid_0's binary_logloss: 0.279087
[86]	valid_0's binary_logloss: 0.278971
[87]	valid_0's binary_logloss: 0.278861
[88]	valid_0's binary_logloss: 0.278486
[89]	valid_0's binary_logloss: 0.278041
[90]	valid_0's binary_logloss: 0.278173
[91]	valid_0's binary_logloss: 0.277948
[92]	valid_0's binary_logloss: 0.277666
[93]	valid_0's binary_logloss: 0.277352
[94]	valid_0's binary_logloss: 0.277219
[95]	valid_0's binary_logloss: 0.276993
[96]	valid_0's binary_logloss: 0.276595
[97]	valid_0's binary_logloss: 0.276502
[98]	valid_0's binary_logloss: 0.276459
[99]	valid_0's binary_logloss: 0.276204
[100]	valid_0's binary_logloss: 0.275774
[101]	valid_0's binary_logloss: 0.275595
[102]	valid_0's binary_logloss: 0.274973
[103]	valid_0's binary_logloss: 0.274756
[104]	valid_0's binary_logloss: 0.274543
[105]	valid_0's binary_logloss: 0.274257
[106]	valid_0's binary_logloss: 0.274167
[107]	valid_0's binary_logloss: 0.274297
[108]	valid_0's binary_logloss: 0.274089
[109]	valid_0's binary_logloss: 0.27391
[110]	valid_0's binary_logloss: 0.274071
[111]	valid_0's binary_logloss: 0.273738
[112]	valid_0's binary_logloss: 0.273788
[113]	valid_0's binary_logloss: 0.273471
[114]	valid_0's binary_logloss: 0.273473
[115]	valid_0's binary_logloss: 0.273233
[116]	valid_0's binary_logloss: 0.273094
[117]	valid_0's binary_logloss: 0.273004
[118]	valid_0's binary_logloss: 0.273057
[119]	valid_0's binary_logloss: 0.27303
[120]	valid_0's binary_logloss: 0.273037
[121]	valid_0's binary_logloss: 0.272945
[122]	valid_0's binary_logloss: 0.272662
[123]	valid_0's binary_logloss: 0.272651
[124]	valid_0's binary_logloss: 0.272691
[125]	valid_0's binary_logloss: 0.272515
[126]	valid_0's binary_logloss: 0.272326
[127]	valid_0's binary_logloss: 0.272206
[128]	valid_0's binary_logloss: 0.272162
[129]	valid_0's binary_logloss: 0.27188
[130]	valid_0's binary_logloss: 0.271564
[131]	valid_0's binary_logloss: 0.271491
[132]	valid_0's binary_logloss: 0.271473
[133]	valid_0's binary_logloss: 0.271344
[134]	valid_0's binary_logloss: 0.271132
[135]	valid_0's binary_logloss: 0.270996
[136]	valid_0's binary_logloss: 0.270938
[137]	valid_0's binary_logloss: 0.271043
[138]	valid_0's binary_logloss: 0.270916
[139]	valid_0's binary_logloss: 0.270798
[140]	valid_0's binary_logloss: 0.270933
[141]	valid_0's binary_logloss: 0.270767
[142]	valid_0's binary_logloss: 0.270664
[143]	valid_0's binary_logloss: 0.270587
[144]	valid_0's binary_logloss: 0.270525
[145]	valid_0's binary_logloss: 0.270316
[146]	valid_0's binary_logloss: 0.270197
[147]	valid_0's binary_logloss: 0.270233
[148]	valid_0's binary_logloss: 0.270408
[149]	valid_0's binary_logloss: 0.270401
[150]	valid_0's binary_logloss: 0.270447
[151]	valid_0's binary_logloss: 0.270256
[152]	valid_0's binary_logloss: 0.270135
[153]	valid_0's binary_logloss: 0.269808
[154]	valid_0's binary_logloss: 0.269831
[155]	valid_0's binary_logloss: 0.269865
[156]	valid_0's binary_logloss: 0.269822
[157]	valid_0's binary_logloss: 0.269802
[158]	valid_0's binary_logloss: 0.269868
[159]	valid_0's binary_logloss: 0.269767
[160]	valid_0's binary_logloss: 0.269731
[161]	valid_0's binary_logloss: 0.26971
[162]	valid_0's binary_logloss: 0.269643
[163]	valid_0's binary_logloss: 0.269774
[164]	valid_0's binary_logloss: 0.269774
[165]	valid_0's binary_logloss: 0.269842
[166]	valid_0's binary_logloss: 0.269655
[167]	valid_0's binary_logloss: 0.26974
[168]	valid_0's binary_logloss: 0.269602
[169]	valid_0's binary_logloss: 0.269454
[170]	valid_0's binary_logloss: 0.269362
[171]	valid_0's binary_logloss: 0.269172
[172]	valid_0's binary_logloss: 0.269041
[173]	valid_0's binary_logloss: 0.268874
[174]	valid_0's binary_logloss: 0.268809
[175]	valid_0's binary_logloss: 0.268786
[176]	valid_0's binary_logloss: 0.268868
[177]	valid_0's binary_logloss: 0.268867
[178]	valid_0's binary_logloss: 0.268875
[179]	valid_0's binary_logloss: 0.268688
[180]	valid_0's binary_logloss: 0.26861
[181]	valid_0's binary_logloss: 0.268485
[182]	valid_0's binary_logloss: 0.268416
[183]	valid_0's binary_logloss: 0.268315
[184]	valid_0's binary_logloss: 0.268136
[185]	valid_0's binary_logloss: 0.268097
[186]	valid_0's binary_logloss: 0.26771
[187]	valid_0's binary_logloss: 0.26764
[188]	valid_0's binary_logloss: 0.267561
[189]	valid_0's binary_logloss: 0.267311
[190]	valid_0's binary_logloss: 0.267273
[191]	valid_0's binary_logloss: 0.267289
[192]	valid_0's binary_logloss: 0.267519
[193]	valid_0's binary_logloss: 0.267411
[194]	valid_0's binary_logloss: 0.267462
[195]	valid_0's binary_logloss: 0.267577
[196]	valid_0's binary_logloss: 0.267652
[197]	valid_0's binary_logloss: 0.267697
[198]	valid_0's binary_logloss: 0.267786
[199]	valid_0's binary_logloss: 0.267982
[200]	valid_0's binary_logloss: 0.268124
[201]	valid_0's binary_logloss: 0.268255
[202]	valid_0's binary_logloss: 0.268188
[203]	valid_0's binary_logloss: 0.268145
[204]	valid_0's binary_logloss: 0.268217
[205]	valid_0's binary_logloss: 0.268265
[206]	valid_0's binary_logloss: 0.268338
[207]	valid_0's binary_logloss: 0.268395
[208]	valid_0's binary_logloss: 0.268488
[209]	valid_0's binary_logloss: 0.268581
[210]	valid_0's binary_logloss: 0.268773
[211]	valid_0's binary_logloss: 0.268619
[212]	valid_0's binary_logloss: 0.268637
[213]	valid_0's binary_logloss: 0.268604
[214]	valid_0's binary_logloss: 0.268594
[215]	valid_0's binary_logloss: 0.268818
[216]	valid_0's binary_logloss: 0.268803
[217]	valid_0's binary_logloss: 0.269084
[218]	valid_0's binary_logloss: 0.268968

Trening klas:   4%|▍         | 21/500 [05:05<1:53:28, 14.21s/klasa, klasa=class_21, F1_klasy=0.8102, F1_macro=0.9325, drzewa=190]




Trening klas:   4%|▍         | 22/500 [05:05<1:59:00, 14.94s/klasa, klasa=class_21, F1_klasy=0.8102, F1_macro=0.9325, drzewa=190]

[219]	valid_0's binary_logloss: 0.269027
[220]	valid_0's binary_logloss: 0.268988
[1]	valid_0's binary_logloss: 0.574603
[2]	valid_0's binary_logloss: 0.543553
[3]	valid_0's binary_logloss: 0.516931
[4]	valid_0's binary_logloss: 0.49261
[5]	valid_0's binary_logloss: 0.471481
[6]	valid_0's binary_logloss: 0.452078
[7]	valid_0's binary_logloss: 0.434825
[8]	valid_0's binary_logloss: 0.41908
[9]	valid_0's binary_logloss: 0.404666
[10]	valid_0's binary_logloss: 0.390926
[11]	valid_0's binary_logloss: 0.377903
[12]	valid_0's binary_logloss: 0.365805
[13]	valid_0's binary_logloss: 0.355192
[14]	valid_0's binary_logloss: 0.345394
[15]	valid_0's binary_logloss: 0.336114
[16]	valid_0's binary_logloss: 0.327625
[17]	valid_0's binary_logloss: 0.319876
[18]	valid_0's binary_logloss: 0.312701
[19]	valid_0's binary_logloss: 0.306031
[20]	valid_0's binary_logloss: 0.299842
[21]	valid_0's binary_logloss: 0.294271
[22]	valid_0's binary_logloss: 0.289523
[23]	valid_0's binary_logloss: 0.284919
[24]	valid_0's binary_logloss: 0.280445
[25]	valid_0's binary_logloss: 0.276192
[26]	valid_0's binary_logloss: 0.272518
[27]	valid_0's binary_logloss: 0.269174
[28]	valid_0's binary_logloss: 0.265485
[29]	valid_0's binary_logloss: 0.262238
[30]	valid_0's binary_logloss: 0.258791
[31]	valid_0's binary_logloss: 0.255943
[32]	valid_0's binary_logloss: 0.253027
[33]	valid_0's binary_logloss: 0.250032
[34]	valid_0's binary_logloss: 0.24742
[35]	valid_0's binary_logloss: 0.244885
[36]	valid_0's binary_logloss: 0.242414
[37]	valid_0's binary_logloss: 0.239997
[38]	valid_0's binary_logloss: 0.237832
[39]	valid_0's binary_logloss: 0.235761
[40]	valid_0's binary_logloss: 0.233733
[41]	valid_0's binary_logloss: 0.232355
[42]	valid_0's binary_logloss: 0.230645
[43]	valid_0's binary_logloss: 0.229605
[44]	valid_0's binary_logloss: 0.228584
[45]	valid_0's binary_logloss: 0.227252
[46]	valid_0's binary_logloss: 0.226042
[47]	valid_0's binary_logloss: 0.224502
[48]	valid_0's binary_logloss: 0.223794
[49]	valid_0's binary_logloss: 0.222952
[50]	valid_0's binary_logloss: 0.222008
[51]	valid_0's binary_logloss: 0.221154
[52]	valid_0's binary_logloss: 0.22019
[53]	valid_0's binary_logloss: 0.219334
[54]	valid_0's binary_logloss: 0.218844
[55]	valid_0's binary_logloss: 0.218429
[56]	valid_0's binary_logloss: 0.21794
[57]	valid_0's binary_logloss: 0.217337
[58]	valid_0's binary_logloss: 0.216644
[59]	valid_0's binary_logloss: 0.216101
[60]	valid_0's binary_logloss: 0.215437
[61]	valid_0's binary_logloss: 0.215022
[62]	valid_0's binary_logloss: 0.214671
[63]	valid_0's binary_logloss: 0.214648
[64]	valid_0's binary_logloss: 0.214344
[65]	valid_0's binary_logloss: 0.214028
[66]	valid_0's binary_logloss: 0.213517
[67]	valid_0's binary_logloss: 0.213071
[68]	valid_0's binary_logloss: 0.212579
[69]	valid_0's binary_logloss: 0.212266
[70]	valid_0's binary_logloss: 0.211754
[71]	valid_0's binary_logloss: 0.211342
[72]	valid_0's binary_logloss: 0.210993
[73]	valid_0's binary_logloss: 0.210743
[74]	valid_0's binary_logloss: 0.210062
[75]	valid_0's binary_logloss: 0.210117
[76]	valid_0's binary_logloss: 0.209938
[77]	valid_0's binary_logloss: 0.21002
[78]	valid_0's binary_logloss: 0.209908
[79]	valid_0's binary_logloss: 0.209727
[80]	valid_0's binary_logloss: 0.209509
[81]	valid_0's binary_logloss: 0.209143
[82]	valid_0's binary_logloss: 0.209258
[83]	valid_0's binary_logloss: 0.2091
[84]	valid_0's binary_logloss: 0.208809
[85]	valid_0's binary_logloss: 0.208697
[86]	valid_0's binary_logloss: 0.208565
[87]	valid_0's binary_logloss: 0.208305
[88]	valid_0's binary_logloss: 0.208201
[89]	valid_0's binary_logloss: 0.208127
[90]	valid_0's binary_logloss: 0.207944
[91]	valid_0's binary_logloss: 0.207724
[92]	valid_0's binary_logloss: 0.207545
[93]	valid_0's binary_logloss: 0.207243
[94]	valid_0's binary_logloss: 0.206728
[95]	valid_0's binary_logloss: 0.206775
[96]	valid_0's binary_logloss: 0.206959
[97]	valid_0's binary_logloss: 0.206887
[98]	valid_0's binary_logloss: 0.20678
[99]	valid_0's binary_logloss: 0.206869
[100]	valid_0's binary_logloss: 0.206793
[101]	valid_0's binary_logloss: 0.206562
[102]	valid_0's binary_logloss: 0.206547
[103]	valid_0's binary_logloss: 0.2063
[104]	valid_0's binary_logloss: 0.206184
[105]	valid_0's binary_logloss: 0.205881
[106]	valid_0's binary_logloss: 0.205826
[107]	valid_0's binary_logloss: 0.205714
[108]	valid_0's binary_logloss: 0.205836
[109]	valid_0's binary_logloss: 0.205975
[110]	valid_0's binary_logloss: 0.205786
[111]	valid_0's binary_logloss: 0.205721
[112]	valid_0's binary_logloss: 0.205729
[113]	valid_0's binary_logloss: 0.205664
[114]	valid_0's binary_logloss: 0.205561
[115]	valid_0's binary_logloss: 0.205615
[116]	valid_0's binary_logloss: 0.205711
[117]	valid_0's binary_logloss: 0.205792
[118]	valid_0's binary_logloss: 0.20592
[119]	valid_0's binary_logloss: 0.206041
[120]	valid_0's binary_logloss: 0.205853
[121]	valid_0's binary_logloss: 0.205966
[122]	valid_0's binary_logloss: 0.20599
[123]	valid_0's binary_logloss: 0.20607
[124]	valid_0's binary_logloss: 0.206217
[125]	valid_0's binary_logloss: 0.206147
[126]	valid_0's binary_logloss: 0.206044
[127]	valid_0's binary_logloss: 0.205946
[128]	valid_0's binary_logloss: 0.206093
[129]	valid_0's binary_logloss: 0.206027
[130]	valid_0's binary_logloss: 0.205892
[131]	valid_0's binary_logloss: 0.205776
[132]	valid_0's binary_logloss: 0.205731
[133]	valid_0's binary_logloss: 0.205539
[134]	valid_0's binary_logloss: 0.205634
[135]	valid_0's binary_logloss: 0.205584
[136]	valid_0's binary_logloss: 0.205591
[137]	valid_0's binary_logloss: 0.205868
[138]	valid_0's binary_logloss: 0.205749
[139]	valid_0's binary_logloss: 0.205893
[140]	valid_0's binary_logloss: 0.205918
[141]	valid_0's binary_logloss: 0.205737
[142]	valid_0's binary_logloss: 0.205737
[143]	valid_0's binary_logloss: 0.205764
[144]	valid_0's binary_logloss: 0.205969
[145]	valid_0's binary_logloss: 0.206031
[146]	valid_0's binary_logloss: 0.206066
[147]	valid_0's binary_logloss: 0.205853
[148]	valid_0's binary_logloss: 0.205897
[149]	valid_0's binary_logloss: 0.205928
[150]	valid_0's binary_logloss: 0.205858
[151]	valid_0's binary_logloss: 0.206032
[152]	valid_0's binary_logloss: 0.206117
[153]	valid_0's binary_logloss: 0.206199
[154]	valid_0's binary_logloss: 0.20639
[155]	valid_0's binary_logloss: 0.206413
[156]	valid_0's binary_logloss: 0.206584
[157]	valid_0's binary_logloss: 0.206682
[158]	valid_0's binary_logloss: 0.206837
[159]	valid_0's binary_logloss: 0.206931
[160]	valid_0's binary_logloss: 0.206943
[161]	valid_0's binary_logloss: 0.207227
[162]	valid_0's binary_logloss: 0.20737
[163]	valid_0's binary_logloss: 0.207513

Trening klas:   4%|▍         | 22/500 [05:18<1:59:00, 14.94s/klasa, klasa=class_22, F1_klasy=0.8684, F1_macro=0.9297, drzewa=133]




Trening klas:   5%|▍         | 23/500 [05:18<1:54:20, 14.38s/klasa, klasa=class_22, F1_klasy=0.8684, F1_macro=0.9297, drzewa=133]

[1]	valid_0's binary_logloss: 0.57446
[2]	valid_0's binary_logloss: 0.543393
[3]	valid_0's binary_logloss: 0.516756
[4]	valid_0's binary_logloss: 0.492541
[5]	valid_0's binary_logloss: 0.471438
[6]	valid_0's binary_logloss: 0.452021
[7]	valid_0's binary_logloss: 0.434745
[8]	valid_0's binary_logloss: 0.418979
[9]	valid_0's binary_logloss: 0.404455
[10]	valid_0's binary_logloss: 0.390689
[11]	valid_0's binary_logloss: 0.377653
[12]	valid_0's binary_logloss: 0.365668
[13]	valid_0's binary_logloss: 0.355118
[14]	valid_0's binary_logloss: 0.345438
[15]	valid_0's binary_logloss: 0.33619
[16]	valid_0's binary_logloss: 0.327694
[17]	valid_0's binary_logloss: 0.319992
[18]	valid_0's binary_logloss: 0.312867
[19]	valid_0's binary_logloss: 0.306274
[20]	valid_0's binary_logloss: 0.299866
[21]	valid_0's binary_logloss: 0.294299
[22]	valid_0's binary_logloss: 0.28927
[23]	valid_0's binary_logloss: 0.284523
[24]	valid_0's binary_logloss: 0.279978
[25]	valid_0's binary_logloss: 0.275518
[26]	valid_0's binary_logloss: 0.271802
[27]	valid_0's binary_logloss: 0.268229
[28]	valid_0's binary_logloss: 0.264633
[29]	valid_0's binary_logloss: 0.261528
[30]	valid_0's binary_logloss: 0.2581
[31]	valid_0's binary_logloss: 0.255418
[32]	valid_0's binary_logloss: 0.252787
[33]	valid_0's binary_logloss: 0.249811
[34]	valid_0's binary_logloss: 0.247095
[35]	valid_0's binary_logloss: 0.244319
[36]	valid_0's binary_logloss: 0.241721
[37]	valid_0's binary_logloss: 0.239854
[38]	valid_0's binary_logloss: 0.237892
[39]	valid_0's binary_logloss: 0.23585
[40]	valid_0's binary_logloss: 0.233855
[41]	valid_0's binary_logloss: 0.232371
[42]	valid_0's binary_logloss: 0.230359
[43]	valid_0's binary_logloss: 0.22912
[44]	valid_0's binary_logloss: 0.228024
[45]	valid_0's binary_logloss: 0.226642
[46]	valid_0's binary_logloss: 0.225254
[47]	valid_0's binary_logloss: 0.223761
[48]	valid_0's binary_logloss: 0.222732
[49]	valid_0's binary_logloss: 0.221832
[50]	valid_0's binary_logloss: 0.220957
[51]	valid_0's binary_logloss: 0.220296
[52]	valid_0's binary_logloss: 0.21919
[53]	valid_0's binary_logloss: 0.218389
[54]	valid_0's binary_logloss: 0.21752
[55]	valid_0's binary_logloss: 0.217134
[56]	valid_0's binary_logloss: 0.216466
[57]	valid_0's binary_logloss: 0.215822
[58]	valid_0's binary_logloss: 0.214997
[59]	valid_0's binary_logloss: 0.214482
[60]	valid_0's binary_logloss: 0.214056
[61]	valid_0's binary_logloss: 0.213616
[62]	valid_0's binary_logloss: 0.213222
[63]	valid_0's binary_logloss: 0.212841
[64]	valid_0's binary_logloss: 0.212636
[65]	valid_0's binary_logloss: 0.21252
[66]	valid_0's binary_logloss: 0.212052
[67]	valid_0's binary_logloss: 0.211608
[68]	valid_0's binary_logloss: 0.211228
[69]	valid_0's binary_logloss: 0.210969
[70]	valid_0's binary_logloss: 0.210651
[71]	valid_0's binary_logloss: 0.210428
[72]	valid_0's binary_logloss: 0.210033
[73]	valid_0's binary_logloss: 0.209764
[74]	valid_0's binary_logloss: 0.209327
[75]	valid_0's binary_logloss: 0.209091
[76]	valid_0's binary_logloss: 0.208838
[77]	valid_0's binary_logloss: 0.208761
[78]	valid_0's binary_logloss: 0.208635
[79]	valid_0's binary_logloss: 0.208511
[80]	valid_0's binary_logloss: 0.208339
[81]	valid_0's binary_logloss: 0.208024
[82]	valid_0's binary_logloss: 0.207991
[83]	valid_0's binary_logloss: 0.207769
[84]	valid_0's binary_logloss: 0.207797
[85]	valid_0's binary_logloss: 0.207568
[86]	valid_0's binary_logloss: 0.207209
[87]	valid_0's binary_logloss: 0.206983
[88]	valid_0's binary_logloss: 0.206773
[89]	valid_0's binary_logloss: 0.206628
[90]	valid_0's binary_logloss: 0.206345
[91]	valid_0's binary_logloss: 0.206027
[92]	valid_0's binary_logloss: 0.205831
[93]	valid_0's binary_logloss: 0.205581
[94]	valid_0's binary_logloss: 0.205498
[95]	valid_0's binary_logloss: 0.205473
[96]	valid_0's binary_logloss: 0.205338
[97]	valid_0's binary_logloss: 0.205461
[98]	valid_0's binary_logloss: 0.205255
[99]	valid_0's binary_logloss: 0.205206
[100]	valid_0's binary_logloss: 0.205273
[101]	valid_0's binary_logloss: 0.205432
[102]	valid_0's binary_logloss: 0.205432
[103]	valid_0's binary_logloss: 0.205462
[104]	valid_0's binary_logloss: 0.205272
[105]	valid_0's binary_logloss: 0.205502
[106]	valid_0's binary_logloss: 0.205253
[107]	valid_0's binary_logloss: 0.204831
[108]	valid_0's binary_logloss: 0.204561
[109]	valid_0's binary_logloss: 0.20445
[110]	valid_0's binary_logloss: 0.204412
[111]	valid_0's binary_logloss: 0.204519
[112]	valid_0's binary_logloss: 0.204379
[113]	valid_0's binary_logloss: 0.204254
[114]	valid_0's binary_logloss: 0.204185
[115]	valid_0's binary_logloss: 0.204066
[116]	valid_0's binary_logloss: 0.20429
[117]	valid_0's binary_logloss: 0.204008
[118]	valid_0's binary_logloss: 0.204144
[119]	valid_0's binary_logloss: 0.204283
[120]	valid_0's binary_logloss: 0.204235
[121]	valid_0's binary_logloss: 0.204234
[122]	valid_0's binary_logloss: 0.204166
[123]	valid_0's binary_logloss: 0.204243
[124]	valid_0's binary_logloss: 0.204184
[125]	valid_0's binary_logloss: 0.204213
[126]	valid_0's binary_logloss: 0.204086
[127]	valid_0's binary_logloss: 0.204065
[128]	valid_0's binary_logloss: 0.204113
[129]	valid_0's binary_logloss: 0.204065
[130]	valid_0's binary_logloss: 0.204139
[131]	valid_0's binary_logloss: 0.204048
[132]	valid_0's binary_logloss: 0.204038
[133]	valid_0's binary_logloss: 0.204002
[134]	valid_0's binary_logloss: 0.203895
[135]	valid_0's binary_logloss: 0.203871
[136]	valid_0's binary_logloss: 0.203892
[137]	valid_0's binary_logloss: 0.203735
[138]	valid_0's binary_logloss: 0.203888
[139]	valid_0's binary_logloss: 0.203879
[140]	valid_0's binary_logloss: 0.204074
[141]	valid_0's binary_logloss: 0.204065
[142]	valid_0's binary_logloss: 0.2041
[143]	valid_0's binary_logloss: 0.204136
[144]	valid_0's binary_logloss: 0.204221
[145]	valid_0's binary_logloss: 0.204416
[146]	valid_0's binary_logloss: 0.2044
[147]	valid_0's binary_logloss: 0.204427
[148]	valid_0's binary_logloss: 0.20462
[149]	valid_0's binary_logloss: 0.204708
[150]	valid_0's binary_logloss: 0.204795
[151]	valid_0's binary_logloss: 0.20483
[152]	valid_0's binary_logloss: 0.204693
[153]	valid_0's binary_logloss: 0.204869
[154]	valid_0's binary_logloss: 0.204914
[155]	valid_0's binary_logloss: 0.205137
[156]	valid_0's binary_logloss: 0.205332
[157]	valid_0's binary_logloss: 0.205725
[158]	valid_0's binary_logloss: 0.205797
[159]	valid_0's binary_logloss: 0.205908
[160]	valid_0's binary_logloss: 0.205765
[161]	valid_0's binary_logloss: 0.205792
[162]	valid_0's binary_logloss: 0.205742
[163]	valid_0's binary_logloss: 0.20577
[164]	valid_0's binary_logloss: 0.205621
[165]	valid_0's binary_logloss: 0.205821
[166]	valid_0's binary_logloss: 0.205835

Trening klas:   5%|▍         | 23/500 [05:31<1:54:20, 14.38s/klasa, klasa=class_23, F1_klasy=0.8701, F1_macro=0.9272, drzewa=137]




Trening klas:   5%|▍         | 24/500 [05:31<1:50:32, 13.93s/klasa, klasa=class_23, F1_klasy=0.8701, F1_macro=0.9272, drzewa=137]

[167]	valid_0's binary_logloss: 0.205835
[1]	valid_0's binary_logloss: 0.544295
[2]	valid_0's binary_logloss: 0.519184
[3]	valid_0's binary_logloss: 0.497391
[4]	valid_0's binary_logloss: 0.478702
[5]	valid_0's binary_logloss: 0.460977
[6]	valid_0's binary_logloss: 0.445943
[7]	valid_0's binary_logloss: 0.431882
[8]	valid_0's binary_logloss: 0.419278
[9]	valid_0's binary_logloss: 0.407906
[10]	valid_0's binary_logloss: 0.396771
[11]	valid_0's binary_logloss: 0.386239
[12]	valid_0's binary_logloss: 0.376657
[13]	valid_0's binary_logloss: 0.368625
[14]	valid_0's binary_logloss: 0.360661
[15]	valid_0's binary_logloss: 0.353557
[16]	valid_0's binary_logloss: 0.346677
[17]	valid_0's binary_logloss: 0.339938
[18]	valid_0's binary_logloss: 0.334194
[19]	valid_0's binary_logloss: 0.329137
[20]	valid_0's binary_logloss: 0.323788
[21]	valid_0's binary_logloss: 0.318579
[22]	valid_0's binary_logloss: 0.313639
[23]	valid_0's binary_logloss: 0.309268
[24]	valid_0's binary_logloss: 0.305476
[25]	valid_0's binary_logloss: 0.301477
[26]	valid_0's binary_logloss: 0.297227
[27]	valid_0's binary_logloss: 0.293902
[28]	valid_0's binary_logloss: 0.290432
[29]	valid_0's binary_logloss: 0.287564
[30]	valid_0's binary_logloss: 0.284897
[31]	valid_0's binary_logloss: 0.282362
[32]	valid_0's binary_logloss: 0.279817
[33]	valid_0's binary_logloss: 0.276895
[34]	valid_0's binary_logloss: 0.274712
[35]	valid_0's binary_logloss: 0.272164
[36]	valid_0's binary_logloss: 0.270061
[37]	valid_0's binary_logloss: 0.268112
[38]	valid_0's binary_logloss: 0.266757
[39]	valid_0's binary_logloss: 0.265152
[40]	valid_0's binary_logloss: 0.263714
[41]	valid_0's binary_logloss: 0.262409
[42]	valid_0's binary_logloss: 0.261046
[43]	valid_0's binary_logloss: 0.259684
[44]	valid_0's binary_logloss: 0.258565
[45]	valid_0's binary_logloss: 0.257552
[46]	valid_0's binary_logloss: 0.256322
[47]	valid_0's binary_logloss: 0.25537
[48]	valid_0's binary_logloss: 0.254458
[49]	valid_0's binary_logloss: 0.25343
[50]	valid_0's binary_logloss: 0.252338
[51]	valid_0's binary_logloss: 0.251652
[52]	valid_0's binary_logloss: 0.250563
[53]	valid_0's binary_logloss: 0.249408
[54]	valid_0's binary_logloss: 0.248709
[55]	valid_0's binary_logloss: 0.247642
[56]	valid_0's binary_logloss: 0.247171
[57]	valid_0's binary_logloss: 0.246325
[58]	valid_0's binary_logloss: 0.245779
[59]	valid_0's binary_logloss: 0.245181
[60]	valid_0's binary_logloss: 0.244492
[61]	valid_0's binary_logloss: 0.243722
[62]	valid_0's binary_logloss: 0.242977
[63]	valid_0's binary_logloss: 0.242376
[64]	valid_0's binary_logloss: 0.241663
[65]	valid_0's binary_logloss: 0.24096
[66]	valid_0's binary_logloss: 0.240404
[67]	valid_0's binary_logloss: 0.239747
[68]	valid_0's binary_logloss: 0.239209
[69]	valid_0's binary_logloss: 0.238838
[70]	valid_0's binary_logloss: 0.238303
[71]	valid_0's binary_logloss: 0.237957
[72]	valid_0's binary_logloss: 0.237511
[73]	valid_0's binary_logloss: 0.23699
[74]	valid_0's binary_logloss: 0.23679
[75]	valid_0's binary_logloss: 0.236328
[76]	valid_0's binary_logloss: 0.235849
[77]	valid_0's binary_logloss: 0.235392
[78]	valid_0's binary_logloss: 0.235218
[79]	valid_0's binary_logloss: 0.234683
[80]	valid_0's binary_logloss: 0.234259
[81]	valid_0's binary_logloss: 0.233703
[82]	valid_0's binary_logloss: 0.233406
[83]	valid_0's binary_logloss: 0.233268
[84]	valid_0's binary_logloss: 0.232653
[85]	valid_0's binary_logloss: 0.232373
[86]	valid_0's binary_logloss: 0.231967
[87]	valid_0's binary_logloss: 0.23164
[88]	valid_0's binary_logloss: 0.231431
[89]	valid_0's binary_logloss: 0.231027
[90]	valid_0's binary_logloss: 0.230973
[91]	valid_0's binary_logloss: 0.230617
[92]	valid_0's binary_logloss: 0.230381
[93]	valid_0's binary_logloss: 0.230072
[94]	valid_0's binary_logloss: 0.229757
[95]	valid_0's binary_logloss: 0.22946
[96]	valid_0's binary_logloss: 0.229033
[97]	valid_0's binary_logloss: 0.228731
[98]	valid_0's binary_logloss: 0.228566
[99]	valid_0's binary_logloss: 0.228496
[100]	valid_0's binary_logloss: 0.228406
[101]	valid_0's binary_logloss: 0.228067
[102]	valid_0's binary_logloss: 0.227833
[103]	valid_0's binary_logloss: 0.227641
[104]	valid_0's binary_logloss: 0.227435
[105]	valid_0's binary_logloss: 0.227386
[106]	valid_0's binary_logloss: 0.227202
[107]	valid_0's binary_logloss: 0.227106
[108]	valid_0's binary_logloss: 0.22689
[109]	valid_0's binary_logloss: 0.226706
[110]	valid_0's binary_logloss: 0.226398
[111]	valid_0's binary_logloss: 0.226246
[112]	valid_0's binary_logloss: 0.226083
[113]	valid_0's binary_logloss: 0.226056
[114]	valid_0's binary_logloss: 0.226006
[115]	valid_0's binary_logloss: 0.226094
[116]	valid_0's binary_logloss: 0.226084
[117]	valid_0's binary_logloss: 0.226217
[118]	valid_0's binary_logloss: 0.226187
[119]	valid_0's binary_logloss: 0.226184
[120]	valid_0's binary_logloss: 0.226027
[121]	valid_0's binary_logloss: 0.225849
[122]	valid_0's binary_logloss: 0.225874
[123]	valid_0's binary_logloss: 0.225617
[124]	valid_0's binary_logloss: 0.225586
[125]	valid_0's binary_logloss: 0.225387
[126]	valid_0's binary_logloss: 0.225217
[127]	valid_0's binary_logloss: 0.22533
[128]	valid_0's binary_logloss: 0.225404
[129]	valid_0's binary_logloss: 0.225273
[130]	valid_0's binary_logloss: 0.225122
[131]	valid_0's binary_logloss: 0.22501
[132]	valid_0's binary_logloss: 0.225021
[133]	valid_0's binary_logloss: 0.224837
[134]	valid_0's binary_logloss: 0.22498
[135]	valid_0's binary_logloss: 0.225019
[136]	valid_0's binary_logloss: 0.224766
[137]	valid_0's binary_logloss: 0.22472
[138]	valid_0's binary_logloss: 0.224601
[139]	valid_0's binary_logloss: 0.22465
[140]	valid_0's binary_logloss: 0.224522
[141]	valid_0's binary_logloss: 0.224384
[142]	valid_0's binary_logloss: 0.224429
[143]	valid_0's binary_logloss: 0.224427
[144]	valid_0's binary_logloss: 0.224523
[145]	valid_0's binary_logloss: 0.224591
[146]	valid_0's binary_logloss: 0.22455
[147]	valid_0's binary_logloss: 0.224489
[148]	valid_0's binary_logloss: 0.2246
[149]	valid_0's binary_logloss: 0.224449
[150]	valid_0's binary_logloss: 0.224278
[151]	valid_0's binary_logloss: 0.22422
[152]	valid_0's binary_logloss: 0.224176
[153]	valid_0's binary_logloss: 0.22418
[154]	valid_0's binary_logloss: 0.224196
[155]	valid_0's binary_logloss: 0.224259
[156]	valid_0's binary_logloss: 0.224116
[157]	valid_0's binary_logloss: 0.224114
[158]	valid_0's binary_logloss: 0.224173
[159]	valid_0's binary_logloss: 0.224165
[160]	valid_0's binary_logloss: 0.224097
[161]	valid_0's binary_logloss: 0.22407
[162]	valid_0's binary_logloss: 0.224131
[163]	valid_0's binary_logloss: 0.224187
[164]	valid_0's binary_logloss: 0.224207
[165]	valid_0's binary_logloss: 0.22428
[166]	valid_0's binary_logloss: 0.224136
[167]	valid_0's binary_logloss: 0.22417
[168]	valid_0's binary_logloss: 0.224265
[169]	valid_0's binary_logloss: 0.224299
[170]	valid_0's binary_logloss: 0.224303
[171]	valid_0's binary_logloss: 0.224275
[172]	valid_0's binary_logloss: 0.224381
[173]	valid_0's binary_logloss: 0.224377
[174]	valid_0's binary_logloss: 0.224527
[175]	valid_0's binary_logloss: 0.224526
[176]	valid_0's binary_logloss: 0.224574
[177]	valid_0's binary_logloss: 0.224394
[178]	valid_0's binary_logloss: 0.22447
[179]	valid_0's binary_logloss: 0.224338
[180]	valid_0's binary_logloss: 0.224359
[181]	valid_0's binary_logloss: 0.224556
[182]	valid_0's binary_logloss: 0.224382
[183]	valid_0's binary_logloss: 0.224248
[184]	valid_0's binary_logloss: 0.224218
[185]	valid_0's binary_logloss: 0.224154
[186]	valid_0's binary_logloss: 0.224224
[187]	valid_0's binary_logloss: 0.224314
[188]	valid_0's binary_logloss: 0.224215
[189]	valid_0's binary_logloss: 0.224183
[190]	valid_0's binary_logloss: 0.224124
[191]	valid_0's binary_logloss: 0.224211

Trening klas:   5%|▍         | 24/500 [05:46<1:50:32, 13.93s/klasa, klasa=class_24, F1_klasy=0.8226, F1_macro=0.9231, drzewa=161]




Trening klas:   5%|▌         | 25/500 [05:46<1:54:10, 14.42s/klasa, klasa=class_24, F1_klasy=0.8226, F1_macro=0.9231, drzewa=161]

[1]	valid_0's binary_logloss: 0.875951
[2]	valid_0's binary_logloss: 0.803801
[3]	valid_0's binary_logloss: 0.743954
[4]	valid_0's binary_logloss: 0.693991
[5]	valid_0's binary_logloss: 0.651675
[6]	valid_0's binary_logloss: 0.615068
[7]	valid_0's binary_logloss: 0.583328
[8]	valid_0's binary_logloss: 0.555069
[9]	valid_0's binary_logloss: 0.530287
[10]	valid_0's binary_logloss: 0.507557
[11]	valid_0's binary_logloss: 0.487515
[12]	valid_0's binary_logloss: 0.469139
[13]	valid_0's binary_logloss: 0.452182
[14]	valid_0's binary_logloss: 0.436554
[15]	valid_0's binary_logloss: 0.422337
[16]	valid_0's binary_logloss: 0.410141
[17]	valid_0's binary_logloss: 0.398131
[18]	valid_0's binary_logloss: 0.387247
[19]	valid_0's binary_logloss: 0.377285
[20]	valid_0's binary_logloss: 0.368404
[21]	valid_0's binary_logloss: 0.36012
[22]	valid_0's binary_logloss: 0.352496
[23]	valid_0's binary_logloss: 0.345511
[24]	valid_0's binary_logloss: 0.339231
[25]	valid_0's binary_logloss: 0.333086
[26]	valid_0's binary_logloss: 0.32756
[27]	valid_0's binary_logloss: 0.322711
[28]	valid_0's binary_logloss: 0.318179
[29]	valid_0's binary_logloss: 0.314124
[30]	valid_0's binary_logloss: 0.310275
[31]	valid_0's binary_logloss: 0.306716
[32]	valid_0's binary_logloss: 0.303562
[33]	valid_0's binary_logloss: 0.30013
[34]	valid_0's binary_logloss: 0.297553
[35]	valid_0's binary_logloss: 0.295547
[36]	valid_0's binary_logloss: 0.293495
[37]	valid_0's binary_logloss: 0.291322
[38]	valid_0's binary_logloss: 0.289682
[39]	valid_0's binary_logloss: 0.287948
[40]	valid_0's binary_logloss: 0.286454
[41]	valid_0's binary_logloss: 0.284386
[42]	valid_0's binary_logloss: 0.283331
[43]	valid_0's binary_logloss: 0.281904
[44]	valid_0's binary_logloss: 0.280909
[45]	valid_0's binary_logloss: 0.279691
[46]	valid_0's binary_logloss: 0.278757
[47]	valid_0's binary_logloss: 0.27744
[48]	valid_0's binary_logloss: 0.276748
[49]	valid_0's binary_logloss: 0.27654
[50]	valid_0's binary_logloss: 0.276002
[51]	valid_0's binary_logloss: 0.275467
[52]	valid_0's binary_logloss: 0.27481
[53]	valid_0's binary_logloss: 0.273951
[54]	valid_0's binary_logloss: 0.273422
[55]	valid_0's binary_logloss: 0.272232
[56]	valid_0's binary_logloss: 0.271774
[57]	valid_0's binary_logloss: 0.270855
[58]	valid_0's binary_logloss: 0.269945
[59]	valid_0's binary_logloss: 0.26939
[60]	valid_0's binary_logloss: 0.268685
[61]	valid_0's binary_logloss: 0.26868
[62]	valid_0's binary_logloss: 0.268801
[63]	valid_0's binary_logloss: 0.268962
[64]	valid_0's binary_logloss: 0.269245
[65]	valid_0's binary_logloss: 0.269207
[66]	valid_0's binary_logloss: 0.26915
[67]	valid_0's binary_logloss: 0.268992
[68]	valid_0's binary_logloss: 0.269003
[69]	valid_0's binary_logloss: 0.269023
[70]	valid_0's binary_logloss: 0.269093
[71]	valid_0's binary_logloss: 0.268999
[72]	valid_0's binary_logloss: 0.268893
[73]	valid_0's binary_logloss: 0.269209
[74]	valid_0's binary_logloss: 0.268844
[75]	valid_0's binary_logloss: 0.26901
[76]	valid_0's binary_logloss: 0.269443
[77]	valid_0's binary_logloss: 0.269182
[78]	valid_0's binary_logloss: 0.269235
[79]	valid_0's binary_logloss: 0.268889
[80]	valid_0's binary_logloss: 0.268823
[81]	valid_0's binary_logloss: 0.268878
[82]	valid_0's binary_logloss: 0.269329
[83]	valid_0's binary_logloss: 0.269451
[84]	valid_0's binary_logloss: 0.269479
[85]	valid_0's binary_logloss: 0.269648
[86]	valid_0's binary_logloss: 0.269708
[87]	valid_0's binary_logloss: 0.269972
[88]	valid_0's binary_logloss: 0.270582
[89]	valid_0's binary_logloss: 0.270777
[90]	valid_0's binary_logloss: 0.270862
[91]	valid_0's binary_logloss: 0.270813

Trening klas:   5%|▌         | 25/500 [05:53<1:54:10, 14.42s/klasa, klasa=class_25, F1_klasy=0.9103, F1_macro=0.9226, drzewa=61]




Trening klas:   5%|▌         | 26/500 [05:53<1:36:30, 12.22s/klasa, klasa=class_25, F1_klasy=0.9103, F1_macro=0.9226, drzewa=61]

[1]	valid_0's binary_logloss: 0.875072
[2]	valid_0's binary_logloss: 0.803013
[3]	valid_0's binary_logloss: 0.743324
[4]	valid_0's binary_logloss: 0.693852
[5]	valid_0's binary_logloss: 0.651675
[6]	valid_0's binary_logloss: 0.615041
[7]	valid_0's binary_logloss: 0.583673
[8]	valid_0's binary_logloss: 0.555315
[9]	valid_0's binary_logloss: 0.53062
[10]	valid_0's binary_logloss: 0.507919
[11]	valid_0's binary_logloss: 0.487864
[12]	valid_0's binary_logloss: 0.469817
[13]	valid_0's binary_logloss: 0.453176
[14]	valid_0's binary_logloss: 0.437866
[15]	valid_0's binary_logloss: 0.42394
[16]	valid_0's binary_logloss: 0.41133
[17]	valid_0's binary_logloss: 0.39958
[18]	valid_0's binary_logloss: 0.38866
[19]	valid_0's binary_logloss: 0.378683
[20]	valid_0's binary_logloss: 0.370061
[21]	valid_0's binary_logloss: 0.361964
[22]	valid_0's binary_logloss: 0.354523
[23]	valid_0's binary_logloss: 0.347886
[24]	valid_0's binary_logloss: 0.341294
[25]	valid_0's binary_logloss: 0.335434
[26]	valid_0's binary_logloss: 0.329615
[27]	valid_0's binary_logloss: 0.324738
[28]	valid_0's binary_logloss: 0.319929
[29]	valid_0's binary_logloss: 0.315725
[30]	valid_0's binary_logloss: 0.31188
[31]	valid_0's binary_logloss: 0.308255
[32]	valid_0's binary_logloss: 0.304982
[33]	valid_0's binary_logloss: 0.302041
[34]	valid_0's binary_logloss: 0.299279
[35]	valid_0's binary_logloss: 0.297218
[36]	valid_0's binary_logloss: 0.295137
[37]	valid_0's binary_logloss: 0.29322
[38]	valid_0's binary_logloss: 0.291293
[39]	valid_0's binary_logloss: 0.28944
[40]	valid_0's binary_logloss: 0.288141
[41]	valid_0's binary_logloss: 0.286223
[42]	valid_0's binary_logloss: 0.28491
[43]	valid_0's binary_logloss: 0.283509
[44]	valid_0's binary_logloss: 0.282506
[45]	valid_0's binary_logloss: 0.281389
[46]	valid_0's binary_logloss: 0.280692
[47]	valid_0's binary_logloss: 0.27973
[48]	valid_0's binary_logloss: 0.278655
[49]	valid_0's binary_logloss: 0.278417
[50]	valid_0's binary_logloss: 0.27776
[51]	valid_0's binary_logloss: 0.277212
[52]	valid_0's binary_logloss: 0.276793
[53]	valid_0's binary_logloss: 0.275689
[54]	valid_0's binary_logloss: 0.274881
[55]	valid_0's binary_logloss: 0.273993
[56]	valid_0's binary_logloss: 0.27347
[57]	valid_0's binary_logloss: 0.272528
[58]	valid_0's binary_logloss: 0.271595
[59]	valid_0's binary_logloss: 0.271216
[60]	valid_0's binary_logloss: 0.270348
[61]	valid_0's binary_logloss: 0.270675
[62]	valid_0's binary_logloss: 0.270474
[63]	valid_0's binary_logloss: 0.270682
[64]	valid_0's binary_logloss: 0.270886
[65]	valid_0's binary_logloss: 0.270926
[66]	valid_0's binary_logloss: 0.270513
[67]	valid_0's binary_logloss: 0.270639
[68]	valid_0's binary_logloss: 0.270607
[69]	valid_0's binary_logloss: 0.270548
[70]	valid_0's binary_logloss: 0.270655
[71]	valid_0's binary_logloss: 0.270754
[72]	valid_0's binary_logloss: 0.270855
[73]	valid_0's binary_logloss: 0.27106
[74]	valid_0's binary_logloss: 0.271127
[75]	valid_0's binary_logloss: 0.271121
[76]	valid_0's binary_logloss: 0.271639
[77]	valid_0's binary_logloss: 0.271574
[78]	valid_0's binary_logloss: 0.272026
[79]	valid_0's binary_logloss: 0.272082
[80]	valid_0's binary_logloss: 0.272084
[81]	valid_0's binary_logloss: 0.27198
[82]	valid_0's binary_logloss: 0.272366
[83]	valid_0's binary_logloss: 0.272295
[84]	valid_0's binary_logloss: 0.2724
[85]	valid_0's binary_logloss: 0.27241
[86]	valid_0's binary_logloss: 0.272272
[87]	valid_0's binary_logloss: 0.272274
[88]	valid_0's binary_logloss: 0.272513
[89]	valid_0's binary_logloss: 0.27256
[90]	valid_0's binary_logloss: 0.272534

Trening klas:   5%|▌         | 26/500 [06:04<1:36:30, 12.22s/klasa, klasa=class_26, F1_klasy=0.9095, F1_macro=0.9221, drzewa=60]




Trening klas:   5%|▌         | 27/500 [06:04<1:32:04, 11.68s/klasa, klasa=class_26, F1_klasy=0.9095, F1_macro=0.9221, drzewa=60]

[1]	valid_0's binary_logloss: 0.675897
[2]	valid_0's binary_logloss: 0.636741
[3]	valid_0's binary_logloss: 0.602922
[4]	valid_0's binary_logloss: 0.575876
[5]	valid_0's binary_logloss: 0.551736
[6]	valid_0's binary_logloss: 0.532107
[7]	valid_0's binary_logloss: 0.514836
[8]	valid_0's binary_logloss: 0.499035
[9]	valid_0's binary_logloss: 0.485715
[10]	valid_0's binary_logloss: 0.473008
[11]	valid_0's binary_logloss: 0.462205
[12]	valid_0's binary_logloss: 0.452524
[13]	valid_0's binary_logloss: 0.444271
[14]	valid_0's binary_logloss: 0.437094
[15]	valid_0's binary_logloss: 0.430299
[16]	valid_0's binary_logloss: 0.424626
[17]	valid_0's binary_logloss: 0.418989
[18]	valid_0's binary_logloss: 0.413884
[19]	valid_0's binary_logloss: 0.409804
[20]	valid_0's binary_logloss: 0.405622
[21]	valid_0's binary_logloss: 0.402304
[22]	valid_0's binary_logloss: 0.399386
[23]	valid_0's binary_logloss: 0.396947
[24]	valid_0's binary_logloss: 0.394866
[25]	valid_0's binary_logloss: 0.392344
[26]	valid_0's binary_logloss: 0.38988
[27]	valid_0's binary_logloss: 0.387462
[28]	valid_0's binary_logloss: 0.38558
[29]	valid_0's binary_logloss: 0.383646
[30]	valid_0's binary_logloss: 0.382002
[31]	valid_0's binary_logloss: 0.380614
[32]	valid_0's binary_logloss: 0.379193
[33]	valid_0's binary_logloss: 0.378269
[34]	valid_0's binary_logloss: 0.376937
[35]	valid_0's binary_logloss: 0.375731
[36]	valid_0's binary_logloss: 0.374697
[37]	valid_0's binary_logloss: 0.373725
[38]	valid_0's binary_logloss: 0.373283
[39]	valid_0's binary_logloss: 0.371966
[40]	valid_0's binary_logloss: 0.371274
[41]	valid_0's binary_logloss: 0.370814
[42]	valid_0's binary_logloss: 0.371003
[43]	valid_0's binary_logloss: 0.370583
[44]	valid_0's binary_logloss: 0.370348
[45]	valid_0's binary_logloss: 0.370715
[46]	valid_0's binary_logloss: 0.370563
[47]	valid_0's binary_logloss: 0.370132
[48]	valid_0's binary_logloss: 0.369205
[49]	valid_0's binary_logloss: 0.368604
[50]	valid_0's binary_logloss: 0.368542
[51]	valid_0's binary_logloss: 0.367497
[52]	valid_0's binary_logloss: 0.366819
[53]	valid_0's binary_logloss: 0.365382
[54]	valid_0's binary_logloss: 0.365015
[55]	valid_0's binary_logloss: 0.364654
[56]	valid_0's binary_logloss: 0.363867
[57]	valid_0's binary_logloss: 0.363521
[58]	valid_0's binary_logloss: 0.362935
[59]	valid_0's binary_logloss: 0.362424
[60]	valid_0's binary_logloss: 0.361651
[61]	valid_0's binary_logloss: 0.361541
[62]	valid_0's binary_logloss: 0.361466
[63]	valid_0's binary_logloss: 0.36143
[64]	valid_0's binary_logloss: 0.36145
[65]	valid_0's binary_logloss: 0.361419
[66]	valid_0's binary_logloss: 0.360763
[67]	valid_0's binary_logloss: 0.360437
[68]	valid_0's binary_logloss: 0.359639
[69]	valid_0's binary_logloss: 0.35917
[70]	valid_0's binary_logloss: 0.358789
[71]	valid_0's binary_logloss: 0.358631
[72]	valid_0's binary_logloss: 0.357742
[73]	valid_0's binary_logloss: 0.357187
[74]	valid_0's binary_logloss: 0.356681
[75]	valid_0's binary_logloss: 0.356396
[76]	valid_0's binary_logloss: 0.355721
[77]	valid_0's binary_logloss: 0.355462
[78]	valid_0's binary_logloss: 0.355136
[79]	valid_0's binary_logloss: 0.354991
[80]	valid_0's binary_logloss: 0.354691
[81]	valid_0's binary_logloss: 0.35496
[82]	valid_0's binary_logloss: 0.354931
[83]	valid_0's binary_logloss: 0.35453
[84]	valid_0's binary_logloss: 0.354442
[85]	valid_0's binary_logloss: 0.353828
[86]	valid_0's binary_logloss: 0.353356
[87]	valid_0's binary_logloss: 0.352884
[88]	valid_0's binary_logloss: 0.352555
[89]	valid_0's binary_logloss: 0.352581
[90]	valid_0's binary_logloss: 0.352067
[91]	valid_0's binary_logloss: 0.351959
[92]	valid_0's binary_logloss: 0.351922
[93]	valid_0's binary_logloss: 0.351481
[94]	valid_0's binary_logloss: 0.351159
[95]	valid_0's binary_logloss: 0.351159
[96]	valid_0's binary_logloss: 0.350618
[97]	valid_0's binary_logloss: 0.350353
[98]	valid_0's binary_logloss: 0.350345
[99]	valid_0's binary_logloss: 0.350125
[100]	valid_0's binary_logloss: 0.350009
[101]	valid_0's binary_logloss: 0.34986
[102]	valid_0's binary_logloss: 0.349487
[103]	valid_0's binary_logloss: 0.349708
[104]	valid_0's binary_logloss: 0.349551
[105]	valid_0's binary_logloss: 0.349291
[106]	valid_0's binary_logloss: 0.348724
[107]	valid_0's binary_logloss: 0.348574
[108]	valid_0's binary_logloss: 0.348499
[109]	valid_0's binary_logloss: 0.348125
[110]	valid_0's binary_logloss: 0.347563
[111]	valid_0's binary_logloss: 0.34703
[112]	valid_0's binary_logloss: 0.34719
[113]	valid_0's binary_logloss: 0.347281
[114]	valid_0's binary_logloss: 0.347354
[115]	valid_0's binary_logloss: 0.347415
[116]	valid_0's binary_logloss: 0.34723
[117]	valid_0's binary_logloss: 0.346637
[118]	valid_0's binary_logloss: 0.34599
[119]	valid_0's binary_logloss: 0.345967
[120]	valid_0's binary_logloss: 0.346038
[121]	valid_0's binary_logloss: 0.345705
[122]	valid_0's binary_logloss: 0.345683
[123]	valid_0's binary_logloss: 0.345574
[124]	valid_0's binary_logloss: 0.345372
[125]	valid_0's binary_logloss: 0.345316
[126]	valid_0's binary_logloss: 0.345421
[127]	valid_0's binary_logloss: 0.345281
[128]	valid_0's binary_logloss: 0.344834
[129]	valid_0's binary_logloss: 0.344641
[130]	valid_0's binary_logloss: 0.344801
[131]	valid_0's binary_logloss: 0.34441
[132]	valid_0's binary_logloss: 0.344364
[133]	valid_0's binary_logloss: 0.343938
[134]	valid_0's binary_logloss: 0.344069
[135]	valid_0's binary_logloss: 0.343901
[136]	valid_0's binary_logloss: 0.343931
[137]	valid_0's binary_logloss: 0.343814
[138]	valid_0's binary_logloss: 0.343753
[139]	valid_0's binary_logloss: 0.343311
[140]	valid_0's binary_logloss: 0.343149
[141]	valid_0's binary_logloss: 0.342702
[142]	valid_0's binary_logloss: 0.342483
[143]	valid_0's binary_logloss: 0.342575
[144]	valid_0's binary_logloss: 0.342403
[145]	valid_0's binary_logloss: 0.34213
[146]	valid_0's binary_logloss: 0.342118
[147]	valid_0's binary_logloss: 0.342228
[148]	valid_0's binary_logloss: 0.342155
[149]	valid_0's binary_logloss: 0.342231
[150]	valid_0's binary_logloss: 0.342222
[151]	valid_0's binary_logloss: 0.342088
[152]	valid_0's binary_logloss: 0.34237
[153]	valid_0's binary_logloss: 0.341977
[154]	valid_0's binary_logloss: 0.34186
[155]	valid_0's binary_logloss: 0.341949
[156]	valid_0's binary_logloss: 0.341958
[157]	valid_0's binary_logloss: 0.34209
[158]	valid_0's binary_logloss: 0.342239
[159]	valid_0's binary_logloss: 0.342326
[160]	valid_0's binary_logloss: 0.342544
[161]	valid_0's binary_logloss: 0.342464
[162]	valid_0's binary_logloss: 0.342418
[163]	valid_0's binary_logloss: 0.342527
[164]	valid_0's binary_logloss: 0.342652
[165]	valid_0's binary_logloss: 0.342686
[166]	valid_0's binary_logloss: 0.342643
[167]	valid_0's binary_logloss: 0.342798
[168]	valid_0's binary_logloss: 0.342737
[169]	valid_0's binary_logloss: 0.342886
[170]	valid_0's binary_logloss: 0.342808
[171]	valid_0's binary_logloss: 0.342782
[172]	valid_0's binary_logloss: 0.343094
[173]	valid_0's binary_logloss: 0.343257
[174]	valid_0's binary_logloss: 0.343303
[175]	valid_0's binary_logloss: 0.343272
[176]	valid_0's binary_logloss: 0.343242
[177]	valid_0's binary_logloss: 0.343569
[178]	valid_0's binary_logloss: 0.343611
[179]	valid_0's binary_logloss: 0.343523
[180]	valid_0's binary_logloss: 0.343591
[181]	valid_0's binary_logloss: 0.34382
[182]	valid_0's binary_logloss: 0.343998
[183]	valid_0's binary_logloss: 0.344097
[184]	valid_0's binary_logloss: 0.344001

Trening klas:   5%|▌         | 27/500 [06:17<1:32:04, 11.68s/klasa, klasa=class_27, F1_klasy=0.8070, F1_macro=0.9180, drzewa=154]




Trening klas:   6%|▌         | 28/500 [06:17<1:34:50, 12.06s/klasa, klasa=class_27, F1_klasy=0.8070, F1_macro=0.9180, drzewa=154]

[1]	valid_0's binary_logloss: 0.675414
[2]	valid_0's binary_logloss: 0.636287
[3]	valid_0's binary_logloss: 0.602478
[4]	valid_0's binary_logloss: 0.575273
[5]	valid_0's binary_logloss: 0.551092
[6]	valid_0's binary_logloss: 0.531692
[7]	valid_0's binary_logloss: 0.513989
[8]	valid_0's binary_logloss: 0.498413
[9]	valid_0's binary_logloss: 0.484667
[10]	valid_0's binary_logloss: 0.472291
[11]	valid_0's binary_logloss: 0.461679
[12]	valid_0's binary_logloss: 0.452115
[13]	valid_0's binary_logloss: 0.443803
[14]	valid_0's binary_logloss: 0.436886
[15]	valid_0's binary_logloss: 0.429744
[16]	valid_0's binary_logloss: 0.423835
[17]	valid_0's binary_logloss: 0.418221
[18]	valid_0's binary_logloss: 0.412888
[19]	valid_0's binary_logloss: 0.408225
[20]	valid_0's binary_logloss: 0.404097
[21]	valid_0's binary_logloss: 0.400893
[22]	valid_0's binary_logloss: 0.397786
[23]	valid_0's binary_logloss: 0.395354
[24]	valid_0's binary_logloss: 0.393298
[25]	valid_0's binary_logloss: 0.390087
[26]	valid_0's binary_logloss: 0.387777
[27]	valid_0's binary_logloss: 0.385656
[28]	valid_0's binary_logloss: 0.38331
[29]	valid_0's binary_logloss: 0.381681
[30]	valid_0's binary_logloss: 0.379933
[31]	valid_0's binary_logloss: 0.378688
[32]	valid_0's binary_logloss: 0.377001
[33]	valid_0's binary_logloss: 0.375979
[34]	valid_0's binary_logloss: 0.375047
[35]	valid_0's binary_logloss: 0.373544
[36]	valid_0's binary_logloss: 0.372687
[37]	valid_0's binary_logloss: 0.371585
[38]	valid_0's binary_logloss: 0.371068
[39]	valid_0's binary_logloss: 0.3697
[40]	valid_0's binary_logloss: 0.369076
[41]	valid_0's binary_logloss: 0.368848
[42]	valid_0's binary_logloss: 0.3689
[43]	valid_0's binary_logloss: 0.368154
[44]	valid_0's binary_logloss: 0.368015
[45]	valid_0's binary_logloss: 0.368083
[46]	valid_0's binary_logloss: 0.366973
[47]	valid_0's binary_logloss: 0.366195
[48]	valid_0's binary_logloss: 0.365589
[49]	valid_0's binary_logloss: 0.36528
[50]	valid_0's binary_logloss: 0.365238
[51]	valid_0's binary_logloss: 0.36483
[52]	valid_0's binary_logloss: 0.364309
[53]	valid_0's binary_logloss: 0.363698
[54]	valid_0's binary_logloss: 0.363493
[55]	valid_0's binary_logloss: 0.362999
[56]	valid_0's binary_logloss: 0.362336
[57]	valid_0's binary_logloss: 0.361492
[58]	valid_0's binary_logloss: 0.361005
[59]	valid_0's binary_logloss: 0.360357
[60]	valid_0's binary_logloss: 0.360248
[61]	valid_0's binary_logloss: 0.360022
[62]	valid_0's binary_logloss: 0.359722
[63]	valid_0's binary_logloss: 0.35999
[64]	valid_0's binary_logloss: 0.359674
[65]	valid_0's binary_logloss: 0.360167
[66]	valid_0's binary_logloss: 0.359075
[67]	valid_0's binary_logloss: 0.358175
[68]	valid_0's binary_logloss: 0.357651
[69]	valid_0's binary_logloss: 0.357127
[70]	valid_0's binary_logloss: 0.35672
[71]	valid_0's binary_logloss: 0.355991
[72]	valid_0's binary_logloss: 0.355258
[73]	valid_0's binary_logloss: 0.354796
[74]	valid_0's binary_logloss: 0.354384
[75]	valid_0's binary_logloss: 0.354241
[76]	valid_0's binary_logloss: 0.353323
[77]	valid_0's binary_logloss: 0.352772
[78]	valid_0's binary_logloss: 0.352483
[79]	valid_0's binary_logloss: 0.35197
[80]	valid_0's binary_logloss: 0.351367
[81]	valid_0's binary_logloss: 0.351166
[82]	valid_0's binary_logloss: 0.351118
[83]	valid_0's binary_logloss: 0.350868
[84]	valid_0's binary_logloss: 0.350799
[85]	valid_0's binary_logloss: 0.350774
[86]	valid_0's binary_logloss: 0.350682
[87]	valid_0's binary_logloss: 0.350464
[88]	valid_0's binary_logloss: 0.350153
[89]	valid_0's binary_logloss: 0.350141
[90]	valid_0's binary_logloss: 0.349709
[91]	valid_0's binary_logloss: 0.349246
[92]	valid_0's binary_logloss: 0.349005
[93]	valid_0's binary_logloss: 0.348776
[94]	valid_0's binary_logloss: 0.348554
[95]	valid_0's binary_logloss: 0.348278
[96]	valid_0's binary_logloss: 0.34809
[97]	valid_0's binary_logloss: 0.347528
[98]	valid_0's binary_logloss: 0.347383
[99]	valid_0's binary_logloss: 0.347135
[100]	valid_0's binary_logloss: 0.346846
[101]	valid_0's binary_logloss: 0.34671
[102]	valid_0's binary_logloss: 0.346657
[103]	valid_0's binary_logloss: 0.347109
[104]	valid_0's binary_logloss: 0.346902
[105]	valid_0's binary_logloss: 0.346399
[106]	valid_0's binary_logloss: 0.346187
[107]	valid_0's binary_logloss: 0.345957
[108]	valid_0's binary_logloss: 0.345223
[109]	valid_0's binary_logloss: 0.344772
[110]	valid_0's binary_logloss: 0.344194
[111]	valid_0's binary_logloss: 0.344032
[112]	valid_0's binary_logloss: 0.344129
[113]	valid_0's binary_logloss: 0.344242
[114]	valid_0's binary_logloss: 0.343958
[115]	valid_0's binary_logloss: 0.343888
[116]	valid_0's binary_logloss: 0.343433
[117]	valid_0's binary_logloss: 0.343527
[118]	valid_0's binary_logloss: 0.342928
[119]	valid_0's binary_logloss: 0.342932
[120]	valid_0's binary_logloss: 0.343139
[121]	valid_0's binary_logloss: 0.342913
[122]	valid_0's binary_logloss: 0.342678
[123]	valid_0's binary_logloss: 0.342236
[124]	valid_0's binary_logloss: 0.341976
[125]	valid_0's binary_logloss: 0.342002
[126]	valid_0's binary_logloss: 0.341702
[127]	valid_0's binary_logloss: 0.341335
[128]	valid_0's binary_logloss: 0.341603
[129]	valid_0's binary_logloss: 0.34181
[130]	valid_0's binary_logloss: 0.341799
[131]	valid_0's binary_logloss: 0.341512
[132]	valid_0's binary_logloss: 0.341501
[133]	valid_0's binary_logloss: 0.3413
[134]	valid_0's binary_logloss: 0.341449
[135]	valid_0's binary_logloss: 0.34156
[136]	valid_0's binary_logloss: 0.341535
[137]	valid_0's binary_logloss: 0.341765
[138]	valid_0's binary_logloss: 0.341613
[139]	valid_0's binary_logloss: 0.341456
[140]	valid_0's binary_logloss: 0.341367
[141]	valid_0's binary_logloss: 0.341119
[142]	valid_0's binary_logloss: 0.341135
[143]	valid_0's binary_logloss: 0.341061
[144]	valid_0's binary_logloss: 0.340811
[145]	valid_0's binary_logloss: 0.340744
[146]	valid_0's binary_logloss: 0.340919
[147]	valid_0's binary_logloss: 0.340991
[148]	valid_0's binary_logloss: 0.340987
[149]	valid_0's binary_logloss: 0.34115
[150]	valid_0's binary_logloss: 0.341011
[151]	valid_0's binary_logloss: 0.341037
[152]	valid_0's binary_logloss: 0.340961
[153]	valid_0's binary_logloss: 0.340853
[154]	valid_0's binary_logloss: 0.341006
[155]	valid_0's binary_logloss: 0.34081
[156]	valid_0's binary_logloss: 0.340503
[157]	valid_0's binary_logloss: 0.34035
[158]	valid_0's binary_logloss: 0.340363
[159]	valid_0's binary_logloss: 0.340547
[160]	valid_0's binary_logloss: 0.340577
[161]	valid_0's binary_logloss: 0.340481
[162]	valid_0's binary_logloss: 0.340479
[163]	valid_0's binary_logloss: 0.340378
[164]	valid_0's binary_logloss: 0.340421
[165]	valid_0's binary_logloss: 0.340357
[166]	valid_0's binary_logloss: 0.340132
[167]	valid_0's binary_logloss: 0.34005
[168]	valid_0's binary_logloss: 0.34
[169]	valid_0's binary_logloss: 0.340193
[170]	valid_0's binary_logloss: 0.33999
[171]	valid_0's binary_logloss: 0.339868
[172]	valid_0's binary_logloss: 0.339792
[173]	valid_0's binary_logloss: 0.340043
[174]	valid_0's binary_logloss: 0.339819
[175]	valid_0's binary_logloss: 0.339823
[176]	valid_0's binary_logloss: 0.340073
[177]	valid_0's binary_logloss: 0.340094
[178]	valid_0's binary_logloss: 0.340189
[179]	valid_0's binary_logloss: 0.340269
[180]	valid_0's binary_logloss: 0.340182
[181]	valid_0's binary_logloss: 0.340251
[182]	valid_0's binary_logloss: 0.340496
[183]	valid_0's binary_logloss: 0.3406
[184]	valid_0's binary_logloss: 0.340666
[185]	valid_0's binary_logloss: 0.340954
[186]	valid_0's binary_logloss: 0.340546
[187]	valid_0's binary_logloss: 0.34044
[188]	valid_0's binary_logloss: 0.340554
[189]	valid_0's binary_logloss: 0.340335
[190]	valid_0's binary_logloss: 0.340409
[191]	valid_0's binary_logloss: 0.340455
[192]	valid_0's binary_logloss: 0.340332
[193]	valid_0's binary_logloss: 0.340406
[194]	valid_0's binary_logloss: 0.340601
[195]	valid_0's binary_logloss: 0.34072
[196]	valid_0's binary_logloss: 0.340814
[197]	valid_0's binary_logloss: 0.34084
[198]	valid_0's binary_logloss: 0.340983
[199]	valid_0's binary_logloss: 0.340853
[200]	valid_0's binary_logloss: 0.340745
[201]	valid_0's binary_logloss: 0.340944
[202]	valid_0's binary_logloss: 0.340821

Trening klas:   6%|▌         | 28/500 [06:31<1:34:50, 12.06s/klasa, klasa=class_28, F1_klasy=0.8115, F1_macro=0.9143, drzewa=172]




Trening klas:   6%|▌         | 29/500 [06:31<1:39:10, 12.63s/klasa, klasa=class_28, F1_klasy=0.8115, F1_macro=0.9143, drzewa=172]

[1]	valid_0's binary_logloss: 0.427084
[2]	valid_0's binary_logloss: 0.403281
[3]	valid_0's binary_logloss: 0.38283
[4]	valid_0's binary_logloss: 0.364621
[5]	valid_0's binary_logloss: 0.349041
[6]	valid_0's binary_logloss: 0.334796
[7]	valid_0's binary_logloss: 0.321987
[8]	valid_0's binary_logloss: 0.31004
[9]	valid_0's binary_logloss: 0.299061
[10]	valid_0's binary_logloss: 0.289055
[11]	valid_0's binary_logloss: 0.278923
[12]	valid_0's binary_logloss: 0.270167
[13]	valid_0's binary_logloss: 0.262321
[14]	valid_0's binary_logloss: 0.254311
[15]	valid_0's binary_logloss: 0.247463
[16]	valid_0's binary_logloss: 0.240692
[17]	valid_0's binary_logloss: 0.234154
[18]	valid_0's binary_logloss: 0.228181
[19]	valid_0's binary_logloss: 0.222967
[20]	valid_0's binary_logloss: 0.218134
[21]	valid_0's binary_logloss: 0.213438
[22]	valid_0's binary_logloss: 0.20894
[23]	valid_0's binary_logloss: 0.204546
[24]	valid_0's binary_logloss: 0.200703
[25]	valid_0's binary_logloss: 0.196991
[26]	valid_0's binary_logloss: 0.193284
[27]	valid_0's binary_logloss: 0.190055
[28]	valid_0's binary_logloss: 0.186272
[29]	valid_0's binary_logloss: 0.183155
[30]	valid_0's binary_logloss: 0.180301
[31]	valid_0's binary_logloss: 0.177446
[32]	valid_0's binary_logloss: 0.174375
[33]	valid_0's binary_logloss: 0.171439
[34]	valid_0's binary_logloss: 0.16917
[35]	valid_0's binary_logloss: 0.166761
[36]	valid_0's binary_logloss: 0.164091
[37]	valid_0's binary_logloss: 0.161996
[38]	valid_0's binary_logloss: 0.159361
[39]	valid_0's binary_logloss: 0.156539
[40]	valid_0's binary_logloss: 0.154841
[41]	valid_0's binary_logloss: 0.153167
[42]	valid_0's binary_logloss: 0.151427
[43]	valid_0's binary_logloss: 0.149503
[44]	valid_0's binary_logloss: 0.147522
[45]	valid_0's binary_logloss: 0.145881
[46]	valid_0's binary_logloss: 0.144559
[47]	valid_0's binary_logloss: 0.142998
[48]	valid_0's binary_logloss: 0.141506
[49]	valid_0's binary_logloss: 0.140152
[50]	valid_0's binary_logloss: 0.138742
[51]	valid_0's binary_logloss: 0.137547
[52]	valid_0's binary_logloss: 0.13623
[53]	valid_0's binary_logloss: 0.134849
[54]	valid_0's binary_logloss: 0.133586
[55]	valid_0's binary_logloss: 0.132449
[56]	valid_0's binary_logloss: 0.13172
[57]	valid_0's binary_logloss: 0.130507
[58]	valid_0's binary_logloss: 0.129386
[59]	valid_0's binary_logloss: 0.128346
[60]	valid_0's binary_logloss: 0.127302
[61]	valid_0's binary_logloss: 0.126349
[62]	valid_0's binary_logloss: 0.125842
[63]	valid_0's binary_logloss: 0.125091
[64]	valid_0's binary_logloss: 0.124541
[65]	valid_0's binary_logloss: 0.124036
[66]	valid_0's binary_logloss: 0.123346
[67]	valid_0's binary_logloss: 0.122573
[68]	valid_0's binary_logloss: 0.121906
[69]	valid_0's binary_logloss: 0.121456
[70]	valid_0's binary_logloss: 0.120789
[71]	valid_0's binary_logloss: 0.120201
[72]	valid_0's binary_logloss: 0.119444
[73]	valid_0's binary_logloss: 0.118729
[74]	valid_0's binary_logloss: 0.118321
[75]	valid_0's binary_logloss: 0.117811
[76]	valid_0's binary_logloss: 0.117196
[77]	valid_0's binary_logloss: 0.116409
[78]	valid_0's binary_logloss: 0.115904
[79]	valid_0's binary_logloss: 0.115295
[80]	valid_0's binary_logloss: 0.114946
[81]	valid_0's binary_logloss: 0.114353
[82]	valid_0's binary_logloss: 0.114028
[83]	valid_0's binary_logloss: 0.113708
[84]	valid_0's binary_logloss: 0.11347
[85]	valid_0's binary_logloss: 0.113064
[86]	valid_0's binary_logloss: 0.11293
[87]	valid_0's binary_logloss: 0.112476
[88]	valid_0's binary_logloss: 0.112258
[89]	valid_0's binary_logloss: 0.111922
[90]	valid_0's binary_logloss: 0.111534
[91]	valid_0's binary_logloss: 0.111247
[92]	valid_0's binary_logloss: 0.110946
[93]	valid_0's binary_logloss: 0.110702
[94]	valid_0's binary_logloss: 0.110705
[95]	valid_0's binary_logloss: 0.110641
[96]	valid_0's binary_logloss: 0.110617
[97]	valid_0's binary_logloss: 0.110465
[98]	valid_0's binary_logloss: 0.110391
[99]	valid_0's binary_logloss: 0.110063
[100]	valid_0's binary_logloss: 0.109824
[101]	valid_0's binary_logloss: 0.10956
[102]	valid_0's binary_logloss: 0.109022
[103]	valid_0's binary_logloss: 0.10868
[104]	valid_0's binary_logloss: 0.108601
[105]	valid_0's binary_logloss: 0.108286
[106]	valid_0's binary_logloss: 0.107998
[107]	valid_0's binary_logloss: 0.107872
[108]	valid_0's binary_logloss: 0.107414
[109]	valid_0's binary_logloss: 0.107214
[110]	valid_0's binary_logloss: 0.107131
[111]	valid_0's binary_logloss: 0.107287
[112]	valid_0's binary_logloss: 0.107169
[113]	valid_0's binary_logloss: 0.106804
[114]	valid_0's binary_logloss: 0.106386
[115]	valid_0's binary_logloss: 0.105999
[116]	valid_0's binary_logloss: 0.105945
[117]	valid_0's binary_logloss: 0.105725
[118]	valid_0's binary_logloss: 0.105869
[119]	valid_0's binary_logloss: 0.105713
[120]	valid_0's binary_logloss: 0.105738
[121]	valid_0's binary_logloss: 0.105552
[122]	valid_0's binary_logloss: 0.105466
[123]	valid_0's binary_logloss: 0.105145
[124]	valid_0's binary_logloss: 0.104888
[125]	valid_0's binary_logloss: 0.104878
[126]	valid_0's binary_logloss: 0.104976
[127]	valid_0's binary_logloss: 0.104939
[128]	valid_0's binary_logloss: 0.104898
[129]	valid_0's binary_logloss: 0.104863
[130]	valid_0's binary_logloss: 0.104703
[131]	valid_0's binary_logloss: 0.104671
[132]	valid_0's binary_logloss: 0.104513
[133]	valid_0's binary_logloss: 0.104572
[134]	valid_0's binary_logloss: 0.104526
[135]	valid_0's binary_logloss: 0.104409
[136]	valid_0's binary_logloss: 0.104448
[137]	valid_0's binary_logloss: 0.10443
[138]	valid_0's binary_logloss: 0.104494
[139]	valid_0's binary_logloss: 0.104207
[140]	valid_0's binary_logloss: 0.104172
[141]	valid_0's binary_logloss: 0.103973
[142]	valid_0's binary_logloss: 0.103925
[143]	valid_0's binary_logloss: 0.103757
[144]	valid_0's binary_logloss: 0.103622
[145]	valid_0's binary_logloss: 0.103695
[146]	valid_0's binary_logloss: 0.103577
[147]	valid_0's binary_logloss: 0.103432
[148]	valid_0's binary_logloss: 0.103305
[149]	valid_0's binary_logloss: 0.103271
[150]	valid_0's binary_logloss: 0.103314
[151]	valid_0's binary_logloss: 0.103201
[152]	valid_0's binary_logloss: 0.103263
[153]	valid_0's binary_logloss: 0.103177
[154]	valid_0's binary_logloss: 0.103252
[155]	valid_0's binary_logloss: 0.103329
[156]	valid_0's binary_logloss: 0.103281
[157]	valid_0's binary_logloss: 0.103271
[158]	valid_0's binary_logloss: 0.103244
[159]	valid_0's binary_logloss: 0.103258
[160]	valid_0's binary_logloss: 0.103399
[161]	valid_0's binary_logloss: 0.103393
[162]	valid_0's binary_logloss: 0.103169
[163]	valid_0's binary_logloss: 0.103099
[164]	valid_0's binary_logloss: 0.103044
[165]	valid_0's binary_logloss: 0.103063
[166]	valid_0's binary_logloss: 0.103067
[167]	valid_0's binary_logloss: 0.103009
[168]	valid_0's binary_logloss: 0.10302
[169]	valid_0's binary_logloss: 0.103077
[170]	valid_0's binary_logloss: 0.10324
[171]	valid_0's binary_logloss: 0.10313
[172]	valid_0's binary_logloss: 0.103215
[173]	valid_0's binary_logloss: 0.103114
[174]	valid_0's binary_logloss: 0.103143
[175]	valid_0's binary_logloss: 0.10305
[176]	valid_0's binary_logloss: 0.102966
[177]	valid_0's binary_logloss: 0.102964
[178]	valid_0's binary_logloss: 0.103043
[179]	valid_0's binary_logloss: 0.103171
[180]	valid_0's binary_logloss: 0.103078
[181]	valid_0's binary_logloss: 0.103042
[182]	valid_0's binary_logloss: 0.103004
[183]	valid_0's binary_logloss: 0.102809
[184]	valid_0's binary_logloss: 0.102726
[185]	valid_0's binary_logloss: 0.102667
[186]	valid_0's binary_logloss: 0.102662
[187]	valid_0's binary_logloss: 0.102685
[188]	valid_0's binary_logloss: 0.102705
[189]	valid_0's binary_logloss: 0.102734
[190]	valid_0's binary_logloss: 0.102767
[191]	valid_0's binary_logloss: 0.102748
[192]	valid_0's binary_logloss: 0.102701
[193]	valid_0's binary_logloss: 0.102637
[194]	valid_0's binary_logloss: 0.102769
[195]	valid_0's binary_logloss: 0.102611
[196]	valid_0's binary_logloss: 0.10256
[197]	valid_0's binary_logloss: 0.102571
[198]	valid_0's binary_logloss: 0.102632
[199]	valid_0's binary_logloss: 0.102715
[200]	valid_0's binary_logloss: 0.102834
[201]	valid_0's binary_logloss: 0.103018
[202]	valid_0's binary_logloss: 0.103252
[203]	valid_0's binary_logloss: 0.103397
[204]	valid_0's binary_logloss: 0.103507
[205]	valid_0's binary_logloss: 0.103544
[206]	valid_0's binary_logloss: 0.103629
[207]	valid_0's binary_logloss: 0.103718
[208]	valid_0's binary_logloss: 0.103777
[209]	valid_0's binary_logloss: 0.103735
[210]	valid_0's binary_logloss: 0.103737
[211]	valid_0's binary_logloss: 0.103835
[212]	valid_0's binary_logloss: 0.103961
[213]	valid_0's binary_logloss: 0.104071
[214]	valid_0's binary_logloss: 0.104198
[215]	valid_0's binary_logloss: 0.104301
[216]	valid_0's binary_logloss: 0.104556
[217]	valid_0's binary_logloss: 0.104537
[218]	valid_0's binary_logloss: 0.104771
[219]	valid_0's binary_logloss: 0.104714
[220]	valid_0's binary_logloss: 0.104734
[221]	valid_0's binary_logloss: 0.104596
[222]	valid_0's binary_logloss: 0.104523
[223]	valid_0's binary_logloss: 0.104502
[224]	valid_0's binary_logloss: 0.104569
[225]	valid_0's binary_logloss: 0.104604
[226]	valid_0's binary_logloss: 0.104556

Trening klas:   6%|▌         | 29/500 [06:48<1:39:10, 12.63s/klasa, klasa=class_29, F1_klasy=0.8922, F1_macro=0.9136, drzewa=196]




Trening klas:   6%|▌         | 30/500 [06:48<1:49:57, 14.04s/klasa, klasa=class_29, F1_klasy=0.8922, F1_macro=0.9136, drzewa=196]

[1]	valid_0's binary_logloss: 0.767049
[2]	valid_0's binary_logloss: 0.702083
[3]	valid_0's binary_logloss: 0.649611
[4]	valid_0's binary_logloss: 0.605788
[5]	valid_0's binary_logloss: 0.569953
[6]	valid_0's binary_logloss: 0.53928
[7]	valid_0's binary_logloss: 0.512149
[8]	valid_0's binary_logloss: 0.489208
[9]	valid_0's binary_logloss: 0.469602
[10]	valid_0's binary_logloss: 0.451601
[11]	valid_0's binary_logloss: 0.434998
[12]	valid_0's binary_logloss: 0.419919
[13]	valid_0's binary_logloss: 0.406534
[14]	valid_0's binary_logloss: 0.394367
[15]	valid_0's binary_logloss: 0.383489
[16]	valid_0's binary_logloss: 0.374003
[17]	valid_0's binary_logloss: 0.365393
[18]	valid_0's binary_logloss: 0.357098
[19]	valid_0's binary_logloss: 0.350061
[20]	valid_0's binary_logloss: 0.342991
[21]	valid_0's binary_logloss: 0.337029
[22]	valid_0's binary_logloss: 0.331464
[23]	valid_0's binary_logloss: 0.326375
[24]	valid_0's binary_logloss: 0.321806
[25]	valid_0's binary_logloss: 0.318403
[26]	valid_0's binary_logloss: 0.31467
[27]	valid_0's binary_logloss: 0.311043
[28]	valid_0's binary_logloss: 0.307967
[29]	valid_0's binary_logloss: 0.305011
[30]	valid_0's binary_logloss: 0.302746
[31]	valid_0's binary_logloss: 0.29946
[32]	valid_0's binary_logloss: 0.296974
[33]	valid_0's binary_logloss: 0.294605
[34]	valid_0's binary_logloss: 0.293139
[35]	valid_0's binary_logloss: 0.291818
[36]	valid_0's binary_logloss: 0.290175
[37]	valid_0's binary_logloss: 0.288705
[38]	valid_0's binary_logloss: 0.287705
[39]	valid_0's binary_logloss: 0.286502
[40]	valid_0's binary_logloss: 0.285295
[41]	valid_0's binary_logloss: 0.28479
[42]	valid_0's binary_logloss: 0.283942
[43]	valid_0's binary_logloss: 0.282567
[44]	valid_0's binary_logloss: 0.282213
[45]	valid_0's binary_logloss: 0.281916
[46]	valid_0's binary_logloss: 0.2815
[47]	valid_0's binary_logloss: 0.280722
[48]	valid_0's binary_logloss: 0.280638
[49]	valid_0's binary_logloss: 0.280272
[50]	valid_0's binary_logloss: 0.279886
[51]	valid_0's binary_logloss: 0.278923
[52]	valid_0's binary_logloss: 0.278708
[53]	valid_0's binary_logloss: 0.27896
[54]	valid_0's binary_logloss: 0.279173
[55]	valid_0's binary_logloss: 0.279115
[56]	valid_0's binary_logloss: 0.279113
[57]	valid_0's binary_logloss: 0.279416
[58]	valid_0's binary_logloss: 0.279724
[59]	valid_0's binary_logloss: 0.27973
[60]	valid_0's binary_logloss: 0.279501
[61]	valid_0's binary_logloss: 0.280171
[62]	valid_0's binary_logloss: 0.28071
[63]	valid_0's binary_logloss: 0.280741
[64]	valid_0's binary_logloss: 0.281341
[65]	valid_0's binary_logloss: 0.281551
[66]	valid_0's binary_logloss: 0.281658
[67]	valid_0's binary_logloss: 0.281759
[68]	valid_0's binary_logloss: 0.281641
[69]	valid_0's binary_logloss: 0.281916
[70]	valid_0's binary_logloss: 0.281954
[71]	valid_0's binary_logloss: 0.281977
[72]	valid_0's binary_logloss: 0.28216
[73]	valid_0's binary_logloss: 0.282217
[74]	valid_0's binary_logloss: 0.282532
[75]	valid_0's binary_logloss: 0.282628
[76]	valid_0's binary_logloss: 0.282485
[77]	valid_0's binary_logloss: 0.28286
[78]	valid_0's binary_logloss: 0.282919
[79]	valid_0's binary_logloss: 0.283208
[80]	valid_0's binary_logloss: 0.28363
[81]	valid_0's binary_logloss: 0.28399

Trening klas:   6%|▌         | 30/500 [06:55<1:49:57, 14.04s/klasa, klasa=class_30, F1_klasy=0.8734, F1_macro=0.9123, drzewa=52]




Trening klas:   6%|▌         | 31/500 [06:55<1:32:27, 11.83s/klasa, klasa=class_30, F1_klasy=0.8734, F1_macro=0.9123, drzewa=52]

[82]	valid_0's binary_logloss: 0.284632
[1]	valid_0's binary_logloss: 0.478985
[2]	valid_0's binary_logloss: 0.45114
[3]	valid_0's binary_logloss: 0.427923
[4]	valid_0's binary_logloss: 0.408513
[5]	valid_0's binary_logloss: 0.391084
[6]	valid_0's binary_logloss: 0.376701
[7]	valid_0's binary_logloss: 0.363046
[8]	valid_0's binary_logloss: 0.351052
[9]	valid_0's binary_logloss: 0.34077
[10]	valid_0's binary_logloss: 0.331282
[11]	valid_0's binary_logloss: 0.322612
[12]	valid_0's binary_logloss: 0.314609
[13]	valid_0's binary_logloss: 0.307157
[14]	valid_0's binary_logloss: 0.299972
[15]	valid_0's binary_logloss: 0.293717
[16]	valid_0's binary_logloss: 0.287463
[17]	valid_0's binary_logloss: 0.28216
[18]	valid_0's binary_logloss: 0.277403
[19]	valid_0's binary_logloss: 0.272987
[20]	valid_0's binary_logloss: 0.268831
[21]	valid_0's binary_logloss: 0.264786
[22]	valid_0's binary_logloss: 0.260958
[23]	valid_0's binary_logloss: 0.257357
[24]	valid_0's binary_logloss: 0.253868
[25]	valid_0's binary_logloss: 0.251255
[26]	valid_0's binary_logloss: 0.248817
[27]	valid_0's binary_logloss: 0.246396
[28]	valid_0's binary_logloss: 0.244567
[29]	valid_0's binary_logloss: 0.242828
[30]	valid_0's binary_logloss: 0.240821
[31]	valid_0's binary_logloss: 0.239128
[32]	valid_0's binary_logloss: 0.237389
[33]	valid_0's binary_logloss: 0.235191
[34]	valid_0's binary_logloss: 0.23375
[35]	valid_0's binary_logloss: 0.231608
[36]	valid_0's binary_logloss: 0.229987
[37]	valid_0's binary_logloss: 0.229073
[38]	valid_0's binary_logloss: 0.227815
[39]	valid_0's binary_logloss: 0.226438
[40]	valid_0's binary_logloss: 0.225118
[41]	valid_0's binary_logloss: 0.223941
[42]	valid_0's binary_logloss: 0.223039
[43]	valid_0's binary_logloss: 0.222283
[44]	valid_0's binary_logloss: 0.221588
[45]	valid_0's binary_logloss: 0.22102
[46]	valid_0's binary_logloss: 0.220453
[47]	valid_0's binary_logloss: 0.219413
[48]	valid_0's binary_logloss: 0.218454
[49]	valid_0's binary_logloss: 0.218049
[50]	valid_0's binary_logloss: 0.216835
[51]	valid_0's binary_logloss: 0.2164
[52]	valid_0's binary_logloss: 0.215856
[53]	valid_0's binary_logloss: 0.214955
[54]	valid_0's binary_logloss: 0.214032
[55]	valid_0's binary_logloss: 0.213561
[56]	valid_0's binary_logloss: 0.212881
[57]	valid_0's binary_logloss: 0.211875
[58]	valid_0's binary_logloss: 0.211109
[59]	valid_0's binary_logloss: 0.210533
[60]	valid_0's binary_logloss: 0.210028
[61]	valid_0's binary_logloss: 0.20963
[62]	valid_0's binary_logloss: 0.209436
[63]	valid_0's binary_logloss: 0.208856
[64]	valid_0's binary_logloss: 0.208695
[65]	valid_0's binary_logloss: 0.208589
[66]	valid_0's binary_logloss: 0.20808
[67]	valid_0's binary_logloss: 0.207665
[68]	valid_0's binary_logloss: 0.207208
[69]	valid_0's binary_logloss: 0.206807
[70]	valid_0's binary_logloss: 0.206222
[71]	valid_0's binary_logloss: 0.205521
[72]	valid_0's binary_logloss: 0.204819
[73]	valid_0's binary_logloss: 0.204214
[74]	valid_0's binary_logloss: 0.203888
[75]	valid_0's binary_logloss: 0.203518
[76]	valid_0's binary_logloss: 0.203156
[77]	valid_0's binary_logloss: 0.202649
[78]	valid_0's binary_logloss: 0.202188
[79]	valid_0's binary_logloss: 0.201652
[80]	valid_0's binary_logloss: 0.201168
[81]	valid_0's binary_logloss: 0.200818
[82]	valid_0's binary_logloss: 0.200528
[83]	valid_0's binary_logloss: 0.199925
[84]	valid_0's binary_logloss: 0.199704
[85]	valid_0's binary_logloss: 0.199311
[86]	valid_0's binary_logloss: 0.198926
[87]	valid_0's binary_logloss: 0.198918
[88]	valid_0's binary_logloss: 0.198527
[89]	valid_0's binary_logloss: 0.198289
[90]	valid_0's binary_logloss: 0.197909
[91]	valid_0's binary_logloss: 0.19748
[92]	valid_0's binary_logloss: 0.197151
[93]	valid_0's binary_logloss: 0.19649
[94]	valid_0's binary_logloss: 0.196064
[95]	valid_0's binary_logloss: 0.195642
[96]	valid_0's binary_logloss: 0.195336
[97]	valid_0's binary_logloss: 0.195148
[98]	valid_0's binary_logloss: 0.195144
[99]	valid_0's binary_logloss: 0.195044
[100]	valid_0's binary_logloss: 0.194669
[101]	valid_0's binary_logloss: 0.194554
[102]	valid_0's binary_logloss: 0.194337
[103]	valid_0's binary_logloss: 0.194211
[104]	valid_0's binary_logloss: 0.193785
[105]	valid_0's binary_logloss: 0.193473
[106]	valid_0's binary_logloss: 0.193317
[107]	valid_0's binary_logloss: 0.193127
[108]	valid_0's binary_logloss: 0.192754
[109]	valid_0's binary_logloss: 0.192653
[110]	valid_0's binary_logloss: 0.192518
[111]	valid_0's binary_logloss: 0.192207
[112]	valid_0's binary_logloss: 0.192101
[113]	valid_0's binary_logloss: 0.192145
[114]	valid_0's binary_logloss: 0.192007
[115]	valid_0's binary_logloss: 0.191887
[116]	valid_0's binary_logloss: 0.191751
[117]	valid_0's binary_logloss: 0.19192
[118]	valid_0's binary_logloss: 0.191928
[119]	valid_0's binary_logloss: 0.191955
[120]	valid_0's binary_logloss: 0.191795
[121]	valid_0's binary_logloss: 0.191705
[122]	valid_0's binary_logloss: 0.191476
[123]	valid_0's binary_logloss: 0.191559
[124]	valid_0's binary_logloss: 0.191226
[125]	valid_0's binary_logloss: 0.191149
[126]	valid_0's binary_logloss: 0.191178
[127]	valid_0's binary_logloss: 0.191058
[128]	valid_0's binary_logloss: 0.191009
[129]	valid_0's binary_logloss: 0.191142
[130]	valid_0's binary_logloss: 0.191122
[131]	valid_0's binary_logloss: 0.190964
[132]	valid_0's binary_logloss: 0.190877
[133]	valid_0's binary_logloss: 0.190953
[134]	valid_0's binary_logloss: 0.190967
[135]	valid_0's binary_logloss: 0.190912
[136]	valid_0's binary_logloss: 0.190864
[137]	valid_0's binary_logloss: 0.19075
[138]	valid_0's binary_logloss: 0.190489
[139]	valid_0's binary_logloss: 0.190492
[140]	valid_0's binary_logloss: 0.190233
[141]	valid_0's binary_logloss: 0.190187
[142]	valid_0's binary_logloss: 0.189909
[143]	valid_0's binary_logloss: 0.189962
[144]	valid_0's binary_logloss: 0.190031
[145]	valid_0's binary_logloss: 0.189941
[146]	valid_0's binary_logloss: 0.18971
[147]	valid_0's binary_logloss: 0.189733
[148]	valid_0's binary_logloss: 0.189708
[149]	valid_0's binary_logloss: 0.189579
[150]	valid_0's binary_logloss: 0.189514
[151]	valid_0's binary_logloss: 0.18964
[152]	valid_0's binary_logloss: 0.189612
[153]	valid_0's binary_logloss: 0.189744
[154]	valid_0's binary_logloss: 0.189747
[155]	valid_0's binary_logloss: 0.189877
[156]	valid_0's binary_logloss: 0.189844
[157]	valid_0's binary_logloss: 0.189911
[158]	valid_0's binary_logloss: 0.190177
[159]	valid_0's binary_logloss: 0.189973
[160]	valid_0's binary_logloss: 0.189964
[161]	valid_0's binary_logloss: 0.190133
[162]	valid_0's binary_logloss: 0.190283
[163]	valid_0's binary_logloss: 0.190389
[164]	valid_0's binary_logloss: 0.190329
[165]	valid_0's binary_logloss: 0.190377
[166]	valid_0's binary_logloss: 0.190445
[167]	valid_0's binary_logloss: 0.190499
[168]	valid_0's binary_logloss: 0.19068
[169]	valid_0's binary_logloss: 0.190835
[170]	valid_0's binary_logloss: 0.190926
[171]	valid_0's binary_logloss: 0.190863
[172]	valid_0's binary_logloss: 0.190834
[173]	valid_0's binary_logloss: 0.190684
[174]	valid_0's binary_logloss: 0.190447
[175]	valid_0's binary_logloss: 0.190505
[176]	valid_0's binary_logloss: 0.190488
[177]	valid_0's binary_logloss: 0.190585
[178]	valid_0's binary_logloss: 0.190653
[179]	valid_0's binary_logloss: 0.190457
[180]	valid_0's binary_logloss: 0.190716

Trening klas:   6%|▌         | 31/500 [07:08<1:32:27, 11.83s/klasa, klasa=class_31, F1_klasy=0.8238, F1_macro=0.9095, drzewa=150]




Trening klas:   6%|▋         | 32/500 [07:08<1:36:42, 12.40s/klasa, klasa=class_31, F1_klasy=0.8238, F1_macro=0.9095, drzewa=150]

[1]	valid_0's binary_logloss: 0.33917
[2]	valid_0's binary_logloss: 0.317846
[3]	valid_0's binary_logloss: 0.29913
[4]	valid_0's binary_logloss: 0.282192
[5]	valid_0's binary_logloss: 0.266973
[6]	valid_0's binary_logloss: 0.252875
[7]	valid_0's binary_logloss: 0.240436
[8]	valid_0's binary_logloss: 0.228645
[9]	valid_0's binary_logloss: 0.217838
[10]	valid_0's binary_logloss: 0.20756
[11]	valid_0's binary_logloss: 0.198156
[12]	valid_0's binary_logloss: 0.189526
[13]	valid_0's binary_logloss: 0.181466
[14]	valid_0's binary_logloss: 0.174202
[15]	valid_0's binary_logloss: 0.167262
[16]	valid_0's binary_logloss: 0.160672
[17]	valid_0's binary_logloss: 0.154352
[18]	valid_0's binary_logloss: 0.148609
[19]	valid_0's binary_logloss: 0.143294
[20]	valid_0's binary_logloss: 0.13807
[21]	valid_0's binary_logloss: 0.133192
[22]	valid_0's binary_logloss: 0.12864
[23]	valid_0's binary_logloss: 0.124294
[24]	valid_0's binary_logloss: 0.120421
[25]	valid_0's binary_logloss: 0.116488
[26]	valid_0's binary_logloss: 0.112942
[27]	valid_0's binary_logloss: 0.109715
[28]	valid_0's binary_logloss: 0.106675
[29]	valid_0's binary_logloss: 0.103775
[30]	valid_0's binary_logloss: 0.10095
[31]	valid_0's binary_logloss: 0.0983043
[32]	valid_0's binary_logloss: 0.095841
[33]	valid_0's binary_logloss: 0.0934614
[34]	valid_0's binary_logloss: 0.091333
[35]	valid_0's binary_logloss: 0.0893813
[36]	valid_0's binary_logloss: 0.0875164
[37]	valid_0's binary_logloss: 0.0855811
[38]	valid_0's binary_logloss: 0.0838203
[39]	valid_0's binary_logloss: 0.0821029
[40]	valid_0's binary_logloss: 0.0804561
[41]	valid_0's binary_logloss: 0.0788878
[42]	valid_0's binary_logloss: 0.0775748
[43]	valid_0's binary_logloss: 0.0761391
[44]	valid_0's binary_logloss: 0.0748179
[45]	valid_0's binary_logloss: 0.0735941
[46]	valid_0's binary_logloss: 0.0724601
[47]	valid_0's binary_logloss: 0.0713674
[48]	valid_0's binary_logloss: 0.0704009
[49]	valid_0's binary_logloss: 0.0694897
[50]	valid_0's binary_logloss: 0.0686116
[51]	valid_0's binary_logloss: 0.0676608
[52]	valid_0's binary_logloss: 0.0667161
[53]	valid_0's binary_logloss: 0.065913
[54]	valid_0's binary_logloss: 0.065038
[55]	valid_0's binary_logloss: 0.0643228
[56]	valid_0's binary_logloss: 0.0636927
[57]	valid_0's binary_logloss: 0.0630318
[58]	valid_0's binary_logloss: 0.0622836
[59]	valid_0's binary_logloss: 0.0616699
[60]	valid_0's binary_logloss: 0.061105
[61]	valid_0's binary_logloss: 0.0605906
[62]	valid_0's binary_logloss: 0.0601848
[63]	valid_0's binary_logloss: 0.0597568
[64]	valid_0's binary_logloss: 0.0593606
[65]	valid_0's binary_logloss: 0.0590764
[66]	valid_0's binary_logloss: 0.0585973
[67]	valid_0's binary_logloss: 0.0582793
[68]	valid_0's binary_logloss: 0.0580878
[69]	valid_0's binary_logloss: 0.0577205
[70]	valid_0's binary_logloss: 0.0573651
[71]	valid_0's binary_logloss: 0.0569365
[72]	valid_0's binary_logloss: 0.0566297
[73]	valid_0's binary_logloss: 0.0563427
[74]	valid_0's binary_logloss: 0.056075
[75]	valid_0's binary_logloss: 0.0559251
[76]	valid_0's binary_logloss: 0.055625
[77]	valid_0's binary_logloss: 0.0553532
[78]	valid_0's binary_logloss: 0.0551011
[79]	valid_0's binary_logloss: 0.0549502
[80]	valid_0's binary_logloss: 0.0547042
[81]	valid_0's binary_logloss: 0.0546443
[82]	valid_0's binary_logloss: 0.0545337
[83]	valid_0's binary_logloss: 0.0545209
[84]	valid_0's binary_logloss: 0.054316
[85]	valid_0's binary_logloss: 0.0541639
[86]	valid_0's binary_logloss: 0.0540953
[87]	valid_0's binary_logloss: 0.053932
[88]	valid_0's binary_logloss: 0.0537453
[89]	valid_0's binary_logloss: 0.0536877
[90]	valid_0's binary_logloss: 0.0536384
[91]	valid_0's binary_logloss: 0.0535074
[92]	valid_0's binary_logloss: 0.0534633
[93]	valid_0's binary_logloss: 0.0533861
[94]	valid_0's binary_logloss: 0.0532943
[95]	valid_0's binary_logloss: 0.0532967
[96]	valid_0's binary_logloss: 0.053
[97]	valid_0's binary_logloss: 0.0527566
[98]	valid_0's binary_logloss: 0.0526582
[99]	valid_0's binary_logloss: 0.0524872
[100]	valid_0's binary_logloss: 0.0523278
[101]	valid_0's binary_logloss: 0.0522901
[102]	valid_0's binary_logloss: 0.0522649
[103]	valid_0's binary_logloss: 0.0522285
[104]	valid_0's binary_logloss: 0.0523492
[105]	valid_0's binary_logloss: 0.0524046
[106]	valid_0's binary_logloss: 0.0524361
[107]	valid_0's binary_logloss: 0.0524457
[108]	valid_0's binary_logloss: 0.0525501
[109]	valid_0's binary_logloss: 0.0525516
[110]	valid_0's binary_logloss: 0.0525549
[111]	valid_0's binary_logloss: 0.052622
[112]	valid_0's binary_logloss: 0.0525817
[113]	valid_0's binary_logloss: 0.052607
[114]	valid_0's binary_logloss: 0.0525474
[115]	valid_0's binary_logloss: 0.0526042
[116]	valid_0's binary_logloss: 0.0525363
[117]	valid_0's binary_logloss: 0.0525246
[118]	valid_0's binary_logloss: 0.0525398
[119]	valid_0's binary_logloss: 0.0525138
[120]	valid_0's binary_logloss: 0.0525168
[121]	valid_0's binary_logloss: 0.0524627
[122]	valid_0's binary_logloss: 0.0524057
[123]	valid_0's binary_logloss: 0.0524403
[124]	valid_0's binary_logloss: 0.0525326
[125]	valid_0's binary_logloss: 0.0524914
[126]	valid_0's binary_logloss: 0.0524483
[127]	valid_0's binary_logloss: 0.052353
[128]	valid_0's binary_logloss: 0.0523538
[129]	valid_0's binary_logloss: 0.0522934
[130]	valid_0's binary_logloss: 0.0521725
[131]	valid_0's binary_logloss: 0.0520927
[132]	valid_0's binary_logloss: 0.0520461
[133]	valid_0's binary_logloss: 0.0520086
[134]	valid_0's binary_logloss: 0.0519119
[135]	valid_0's binary_logloss: 0.0519129
[136]	valid_0's binary_logloss: 0.0519141
[137]	valid_0's binary_logloss: 0.0519544
[138]	valid_0's binary_logloss: 0.052028
[139]	valid_0's binary_logloss: 0.052133
[140]	valid_0's binary_logloss: 0.0521796
[141]	valid_0's binary_logloss: 0.0522913
[142]	valid_0's binary_logloss: 0.052309
[143]	valid_0's binary_logloss: 0.0523617
[144]	valid_0's binary_logloss: 0.0524424
[145]	valid_0's binary_logloss: 0.0524894
[146]	valid_0's binary_logloss: 0.0524181
[147]	valid_0's binary_logloss: 0.0524228
[148]	valid_0's binary_logloss: 0.0523646
[149]	valid_0's binary_logloss: 0.0523084
[150]	valid_0's binary_logloss: 0.0523282
[151]	valid_0's binary_logloss: 0.0523754
[152]	valid_0's binary_logloss: 0.0522688
[153]	valid_0's binary_logloss: 0.0522996
[154]	valid_0's binary_logloss: 0.0523266
[155]	valid_0's binary_logloss: 0.0524241
[156]	valid_0's binary_logloss: 0.0525102
[157]	valid_0's binary_logloss: 0.0526062
[158]	valid_0's binary_logloss: 0.0525729
[159]	valid_0's binary_logloss: 0.0527798
[160]	valid_0's binary_logloss: 0.0528924
[161]	valid_0's binary_logloss: 0.0528705
[162]	valid_0's binary_logloss: 0.0528499
[163]	valid_0's binary_logloss: 0.0529582

Trening klas:   6%|▋         | 32/500 [07:19<1:36:42, 12.40s/klasa, klasa=class_32, F1_klasy=0.8953, F1_macro=0.9091, drzewa=134]




Trening klas:   7%|▋         | 33/500 [07:19<1:32:22, 11.87s/klasa, klasa=class_32, F1_klasy=0.8953, F1_macro=0.9091, drzewa=134]

[164]	valid_0's binary_logloss: 0.0530386
[1]	valid_0's binary_logloss: 0.444077
[2]	valid_0's binary_logloss: 0.411878
[3]	valid_0's binary_logloss: 0.385029
[4]	valid_0's binary_logloss: 0.361881
[5]	valid_0's binary_logloss: 0.342095
[6]	valid_0's binary_logloss: 0.32455
[7]	valid_0's binary_logloss: 0.309546
[8]	valid_0's binary_logloss: 0.296148
[9]	valid_0's binary_logloss: 0.283861
[10]	valid_0's binary_logloss: 0.27338
[11]	valid_0's binary_logloss: 0.262705
[12]	valid_0's binary_logloss: 0.253336
[13]	valid_0's binary_logloss: 0.244841
[14]	valid_0's binary_logloss: 0.236632
[15]	valid_0's binary_logloss: 0.229243
[16]	valid_0's binary_logloss: 0.22303
[17]	valid_0's binary_logloss: 0.21668
[18]	valid_0's binary_logloss: 0.21074
[19]	valid_0's binary_logloss: 0.205226
[20]	valid_0's binary_logloss: 0.200329
[21]	valid_0's binary_logloss: 0.196292
[22]	valid_0's binary_logloss: 0.192205
[23]	valid_0's binary_logloss: 0.188785
[24]	valid_0's binary_logloss: 0.185485
[25]	valid_0's binary_logloss: 0.182455
[26]	valid_0's binary_logloss: 0.17936
[27]	valid_0's binary_logloss: 0.176289
[28]	valid_0's binary_logloss: 0.173783
[29]	valid_0's binary_logloss: 0.171627
[30]	valid_0's binary_logloss: 0.169384
[31]	valid_0's binary_logloss: 0.16722
[32]	valid_0's binary_logloss: 0.165084
[33]	valid_0's binary_logloss: 0.163128
[34]	valid_0's binary_logloss: 0.161095
[35]	valid_0's binary_logloss: 0.159703
[36]	valid_0's binary_logloss: 0.158405
[37]	valid_0's binary_logloss: 0.1572
[38]	valid_0's binary_logloss: 0.156371
[39]	valid_0's binary_logloss: 0.155674
[40]	valid_0's binary_logloss: 0.154369
[41]	valid_0's binary_logloss: 0.153347
[42]	valid_0's binary_logloss: 0.1527
[43]	valid_0's binary_logloss: 0.151894
[44]	valid_0's binary_logloss: 0.151042
[45]	valid_0's binary_logloss: 0.150527
[46]	valid_0's binary_logloss: 0.149848
[47]	valid_0's binary_logloss: 0.148948
[48]	valid_0's binary_logloss: 0.148319
[49]	valid_0's binary_logloss: 0.147659
[50]	valid_0's binary_logloss: 0.147191
[51]	valid_0's binary_logloss: 0.14619
[52]	valid_0's binary_logloss: 0.145643
[53]	valid_0's binary_logloss: 0.144982
[54]	valid_0's binary_logloss: 0.144403
[55]	valid_0's binary_logloss: 0.14403
[56]	valid_0's binary_logloss: 0.143761
[57]	valid_0's binary_logloss: 0.143246
[58]	valid_0's binary_logloss: 0.142791
[59]	valid_0's binary_logloss: 0.142415
[60]	valid_0's binary_logloss: 0.142003
[61]	valid_0's binary_logloss: 0.141334
[62]	valid_0's binary_logloss: 0.141267
[63]	valid_0's binary_logloss: 0.140563
[64]	valid_0's binary_logloss: 0.140049
[65]	valid_0's binary_logloss: 0.139417
[66]	valid_0's binary_logloss: 0.138899
[67]	valid_0's binary_logloss: 0.138406
[68]	valid_0's binary_logloss: 0.138171
[69]	valid_0's binary_logloss: 0.138125
[70]	valid_0's binary_logloss: 0.137886
[71]	valid_0's binary_logloss: 0.137752
[72]	valid_0's binary_logloss: 0.137607
[73]	valid_0's binary_logloss: 0.137383
[74]	valid_0's binary_logloss: 0.137086
[75]	valid_0's binary_logloss: 0.136816
[76]	valid_0's binary_logloss: 0.136351
[77]	valid_0's binary_logloss: 0.135929
[78]	valid_0's binary_logloss: 0.135641
[79]	valid_0's binary_logloss: 0.13572
[80]	valid_0's binary_logloss: 0.135243
[81]	valid_0's binary_logloss: 0.134867
[82]	valid_0's binary_logloss: 0.13433
[83]	valid_0's binary_logloss: 0.134238
[84]	valid_0's binary_logloss: 0.134193
[85]	valid_0's binary_logloss: 0.133889
[86]	valid_0's binary_logloss: 0.133685
[87]	valid_0's binary_logloss: 0.133851
[88]	valid_0's binary_logloss: 0.133786
[89]	valid_0's binary_logloss: 0.133824
[90]	valid_0's binary_logloss: 0.133867
[91]	valid_0's binary_logloss: 0.133203
[92]	valid_0's binary_logloss: 0.133178
[93]	valid_0's binary_logloss: 0.1331
[94]	valid_0's binary_logloss: 0.133033
[95]	valid_0's binary_logloss: 0.133283
[96]	valid_0's binary_logloss: 0.133271
[97]	valid_0's binary_logloss: 0.133056
[98]	valid_0's binary_logloss: 0.132727
[99]	valid_0's binary_logloss: 0.132873
[100]	valid_0's binary_logloss: 0.132895
[101]	valid_0's binary_logloss: 0.13277
[102]	valid_0's binary_logloss: 0.132707
[103]	valid_0's binary_logloss: 0.132849
[104]	valid_0's binary_logloss: 0.132713
[105]	valid_0's binary_logloss: 0.132861
[106]	valid_0's binary_logloss: 0.132818
[107]	valid_0's binary_logloss: 0.132764
[108]	valid_0's binary_logloss: 0.132744
[109]	valid_0's binary_logloss: 0.132629
[110]	valid_0's binary_logloss: 0.132706
[111]	valid_0's binary_logloss: 0.132566
[112]	valid_0's binary_logloss: 0.132616
[113]	valid_0's binary_logloss: 0.132448
[114]	valid_0's binary_logloss: 0.132229
[115]	valid_0's binary_logloss: 0.132234
[116]	valid_0's binary_logloss: 0.132245
[117]	valid_0's binary_logloss: 0.13224
[118]	valid_0's binary_logloss: 0.132133
[119]	valid_0's binary_logloss: 0.132055
[120]	valid_0's binary_logloss: 0.13235
[121]	valid_0's binary_logloss: 0.132316
[122]	valid_0's binary_logloss: 0.132523
[123]	valid_0's binary_logloss: 0.132687
[124]	valid_0's binary_logloss: 0.132803
[125]	valid_0's binary_logloss: 0.132847
[126]	valid_0's binary_logloss: 0.132864
[127]	valid_0's binary_logloss: 0.132689
[128]	valid_0's binary_logloss: 0.132473
[129]	valid_0's binary_logloss: 0.132385
[130]	valid_0's binary_logloss: 0.132215
[131]	valid_0's binary_logloss: 0.13209
[132]	valid_0's binary_logloss: 0.132175
[133]	valid_0's binary_logloss: 0.131922
[134]	valid_0's binary_logloss: 0.132064
[135]	valid_0's binary_logloss: 0.132146
[136]	valid_0's binary_logloss: 0.132422
[137]	valid_0's binary_logloss: 0.132549
[138]	valid_0's binary_logloss: 0.132404
[139]	valid_0's binary_logloss: 0.132243
[140]	valid_0's binary_logloss: 0.132286
[141]	valid_0's binary_logloss: 0.132308
[142]	valid_0's binary_logloss: 0.1323
[143]	valid_0's binary_logloss: 0.132455
[144]	valid_0's binary_logloss: 0.132497
[145]	valid_0's binary_logloss: 0.132676
[146]	valid_0's binary_logloss: 0.132536
[147]	valid_0's binary_logloss: 0.132784
[148]	valid_0's binary_logloss: 0.132877
[149]	valid_0's binary_logloss: 0.132796
[150]	valid_0's binary_logloss: 0.133022
[151]	valid_0's binary_logloss: 0.133033
[152]	valid_0's binary_logloss: 0.133209
[153]	valid_0's binary_logloss: 0.133398
[154]	valid_0's binary_logloss: 0.133527
[155]	valid_0's binary_logloss: 0.133562
[156]	valid_0's binary_logloss: 0.133386
[157]	valid_0's binary_logloss: 0.133545
[158]	valid_0's binary_logloss: 0.133673
[159]	valid_0's binary_logloss: 0.133872
[160]	valid_0's binary_logloss: 0.134029
[161]	valid_0's binary_logloss: 0.133947
[162]	valid_0's binary_logloss: 0.134014
[163]	valid_0's binary_logloss: 0.134024

Trening klas:   7%|▋         | 33/500 [07:30<1:32:22, 11.87s/klasa, klasa=class_33, F1_klasy=0.8830, F1_macro=0.9083, drzewa=133]




Trening klas:   7%|▋         | 34/500 [07:30<1:30:18, 11.63s/klasa, klasa=class_33, F1_klasy=0.8830, F1_macro=0.9083, drzewa=133]

[1]	valid_0's binary_logloss: 0.315415
[2]	valid_0's binary_logloss: 0.295976
[3]	valid_0's binary_logloss: 0.279115
[4]	valid_0's binary_logloss: 0.264371
[5]	valid_0's binary_logloss: 0.251316
[6]	valid_0's binary_logloss: 0.239149
[7]	valid_0's binary_logloss: 0.228162
[8]	valid_0's binary_logloss: 0.217996
[9]	valid_0's binary_logloss: 0.208539
[10]	valid_0's binary_logloss: 0.200055
[11]	valid_0's binary_logloss: 0.191913
[12]	valid_0's binary_logloss: 0.184201
[13]	valid_0's binary_logloss: 0.177227
[14]	valid_0's binary_logloss: 0.170785
[15]	valid_0's binary_logloss: 0.164645
[16]	valid_0's binary_logloss: 0.158811
[17]	valid_0's binary_logloss: 0.153297
[18]	valid_0's binary_logloss: 0.148023
[19]	valid_0's binary_logloss: 0.143037
[20]	valid_0's binary_logloss: 0.138396
[21]	valid_0's binary_logloss: 0.134171
[22]	valid_0's binary_logloss: 0.130271
[23]	valid_0's binary_logloss: 0.126589
[24]	valid_0's binary_logloss: 0.12302
[25]	valid_0's binary_logloss: 0.119795
[26]	valid_0's binary_logloss: 0.116922
[27]	valid_0's binary_logloss: 0.114243
[28]	valid_0's binary_logloss: 0.11148
[29]	valid_0's binary_logloss: 0.109018
[30]	valid_0's binary_logloss: 0.106676
[31]	valid_0's binary_logloss: 0.104379
[32]	valid_0's binary_logloss: 0.102261
[33]	valid_0's binary_logloss: 0.100379
[34]	valid_0's binary_logloss: 0.098636
[35]	valid_0's binary_logloss: 0.0970807
[36]	valid_0's binary_logloss: 0.0953473
[37]	valid_0's binary_logloss: 0.0936535
[38]	valid_0's binary_logloss: 0.0920171
[39]	valid_0's binary_logloss: 0.0905224
[40]	valid_0's binary_logloss: 0.0891685
[41]	valid_0's binary_logloss: 0.0877979
[42]	valid_0's binary_logloss: 0.0866586
[43]	valid_0's binary_logloss: 0.085557
[44]	valid_0's binary_logloss: 0.0843766
[45]	valid_0's binary_logloss: 0.0833423
[46]	valid_0's binary_logloss: 0.0825199
[47]	valid_0's binary_logloss: 0.0816954
[48]	valid_0's binary_logloss: 0.080748
[49]	valid_0's binary_logloss: 0.0799684
[50]	valid_0's binary_logloss: 0.0791634
[51]	valid_0's binary_logloss: 0.0782594
[52]	valid_0's binary_logloss: 0.077634
[53]	valid_0's binary_logloss: 0.0771188
[54]	valid_0's binary_logloss: 0.0764948
[55]	valid_0's binary_logloss: 0.0758735
[56]	valid_0's binary_logloss: 0.0753458
[57]	valid_0's binary_logloss: 0.0749623
[58]	valid_0's binary_logloss: 0.0744169
[59]	valid_0's binary_logloss: 0.0738718
[60]	valid_0's binary_logloss: 0.0734008
[61]	valid_0's binary_logloss: 0.0729743
[62]	valid_0's binary_logloss: 0.0725842
[63]	valid_0's binary_logloss: 0.0721542
[64]	valid_0's binary_logloss: 0.0718042
[65]	valid_0's binary_logloss: 0.071616
[66]	valid_0's binary_logloss: 0.0712963
[67]	valid_0's binary_logloss: 0.0710936
[68]	valid_0's binary_logloss: 0.070803
[69]	valid_0's binary_logloss: 0.0706497
[70]	valid_0's binary_logloss: 0.0704794
[71]	valid_0's binary_logloss: 0.0702334
[72]	valid_0's binary_logloss: 0.0700314
[73]	valid_0's binary_logloss: 0.0697845
[74]	valid_0's binary_logloss: 0.0696925
[75]	valid_0's binary_logloss: 0.06953
[76]	valid_0's binary_logloss: 0.0691633
[77]	valid_0's binary_logloss: 0.0689216
[78]	valid_0's binary_logloss: 0.0686906
[79]	valid_0's binary_logloss: 0.068501
[80]	valid_0's binary_logloss: 0.0683595
[81]	valid_0's binary_logloss: 0.0682183
[82]	valid_0's binary_logloss: 0.0680626
[83]	valid_0's binary_logloss: 0.0680051
[84]	valid_0's binary_logloss: 0.0678592
[85]	valid_0's binary_logloss: 0.0678288
[86]	valid_0's binary_logloss: 0.06779
[87]	valid_0's binary_logloss: 0.0678237
[88]	valid_0's binary_logloss: 0.0678596
[89]	valid_0's binary_logloss: 0.0678393
[90]	valid_0's binary_logloss: 0.0678016
[91]	valid_0's binary_logloss: 0.067739
[92]	valid_0's binary_logloss: 0.0674609
[93]	valid_0's binary_logloss: 0.0673531
[94]	valid_0's binary_logloss: 0.0672159
[95]	valid_0's binary_logloss: 0.0670826
[96]	valid_0's binary_logloss: 0.0671304
[97]	valid_0's binary_logloss: 0.0670724
[98]	valid_0's binary_logloss: 0.0669675
[99]	valid_0's binary_logloss: 0.0667955
[100]	valid_0's binary_logloss: 0.0668125
[101]	valid_0's binary_logloss: 0.0668667
[102]	valid_0's binary_logloss: 0.0669601
[103]	valid_0's binary_logloss: 0.0669505
[104]	valid_0's binary_logloss: 0.0670446
[105]	valid_0's binary_logloss: 0.0672529
[106]	valid_0's binary_logloss: 0.0673516
[107]	valid_0's binary_logloss: 0.0673317
[108]	valid_0's binary_logloss: 0.0671701
[109]	valid_0's binary_logloss: 0.0672086
[110]	valid_0's binary_logloss: 0.0671925
[111]	valid_0's binary_logloss: 0.0672739
[112]	valid_0's binary_logloss: 0.0672934
[113]	valid_0's binary_logloss: 0.067314
[114]	valid_0's binary_logloss: 0.0674544
[115]	valid_0's binary_logloss: 0.0674955
[116]	valid_0's binary_logloss: 0.0675167
[117]	valid_0's binary_logloss: 0.0673386
[118]	valid_0's binary_logloss: 0.0673907
[119]	valid_0's binary_logloss: 0.0673155
[120]	valid_0's binary_logloss: 0.067339
[121]	valid_0's binary_logloss: 0.0674009
[122]	valid_0's binary_logloss: 0.06743
[123]	valid_0's binary_logloss: 0.0674444
[124]	valid_0's binary_logloss: 0.0676188
[125]	valid_0's binary_logloss: 0.0676569
[126]	valid_0's binary_logloss: 0.0675884
[127]	valid_0's binary_logloss: 0.0676032
[128]	valid_0's binary_logloss: 0.0676236

Trening klas:   7%|▋         | 34/500 [07:38<1:30:18, 11.63s/klasa, klasa=class_34, F1_klasy=0.8484, F1_macro=0.9066, drzewa=99]




Trening klas:   7%|▋         | 35/500 [07:38<1:21:58, 10.58s/klasa, klasa=class_34, F1_klasy=0.8484, F1_macro=0.9066, drzewa=99]

[129]	valid_0's binary_logloss: 0.0676398
[1]	valid_0's binary_logloss: 0.444398
[2]	valid_0's binary_logloss: 0.404305
[3]	valid_0's binary_logloss: 0.372869
[4]	valid_0's binary_logloss: 0.346287
[5]	valid_0's binary_logloss: 0.323926
[6]	valid_0's binary_logloss: 0.30411
[7]	valid_0's binary_logloss: 0.286356
[8]	valid_0's binary_logloss: 0.271083
[9]	valid_0's binary_logloss: 0.256606
[10]	valid_0's binary_logloss: 0.243553
[11]	valid_0's binary_logloss: 0.231941
[12]	valid_0's binary_logloss: 0.220996
[13]	valid_0's binary_logloss: 0.210767
[14]	valid_0's binary_logloss: 0.201438
[15]	valid_0's binary_logloss: 0.193163
[16]	valid_0's binary_logloss: 0.185049
[17]	valid_0's binary_logloss: 0.177178
[18]	valid_0's binary_logloss: 0.170064
[19]	valid_0's binary_logloss: 0.163428
[20]	valid_0's binary_logloss: 0.157258
[21]	valid_0's binary_logloss: 0.151622
[22]	valid_0's binary_logloss: 0.146191
[23]	valid_0's binary_logloss: 0.14119
[24]	valid_0's binary_logloss: 0.136689
[25]	valid_0's binary_logloss: 0.132285
[26]	valid_0's binary_logloss: 0.128408
[27]	valid_0's binary_logloss: 0.124641
[28]	valid_0's binary_logloss: 0.121296
[29]	valid_0's binary_logloss: 0.117902
[30]	valid_0's binary_logloss: 0.114746
[31]	valid_0's binary_logloss: 0.11141
[32]	valid_0's binary_logloss: 0.108625
[33]	valid_0's binary_logloss: 0.105726
[34]	valid_0's binary_logloss: 0.102905
[35]	valid_0's binary_logloss: 0.100432
[36]	valid_0's binary_logloss: 0.0981223
[37]	valid_0's binary_logloss: 0.0960585
[38]	valid_0's binary_logloss: 0.0940518
[39]	valid_0's binary_logloss: 0.0919334
[40]	valid_0's binary_logloss: 0.0902845
[41]	valid_0's binary_logloss: 0.0884086
[42]	valid_0's binary_logloss: 0.0866631
[43]	valid_0's binary_logloss: 0.0851966
[44]	valid_0's binary_logloss: 0.0838501
[45]	valid_0's binary_logloss: 0.0823239
[46]	valid_0's binary_logloss: 0.0809152
[47]	valid_0's binary_logloss: 0.0795652
[48]	valid_0's binary_logloss: 0.0783761
[49]	valid_0's binary_logloss: 0.0774183
[50]	valid_0's binary_logloss: 0.0763814
[51]	valid_0's binary_logloss: 0.0754417
[52]	valid_0's binary_logloss: 0.0745388
[53]	valid_0's binary_logloss: 0.0736124
[54]	valid_0's binary_logloss: 0.0728314
[55]	valid_0's binary_logloss: 0.0719569
[56]	valid_0's binary_logloss: 0.0711773
[57]	valid_0's binary_logloss: 0.0705529
[58]	valid_0's binary_logloss: 0.0699118
[59]	valid_0's binary_logloss: 0.0691531
[60]	valid_0's binary_logloss: 0.0685453
[61]	valid_0's binary_logloss: 0.0679791
[62]	valid_0's binary_logloss: 0.0674311
[63]	valid_0's binary_logloss: 0.0669154
[64]	valid_0's binary_logloss: 0.0665871
[65]	valid_0's binary_logloss: 0.0661789
[66]	valid_0's binary_logloss: 0.0657375
[67]	valid_0's binary_logloss: 0.0653951
[68]	valid_0's binary_logloss: 0.0649496
[69]	valid_0's binary_logloss: 0.0645368
[70]	valid_0's binary_logloss: 0.0641656
[71]	valid_0's binary_logloss: 0.0638826
[72]	valid_0's binary_logloss: 0.063546
[73]	valid_0's binary_logloss: 0.0630206
[74]	valid_0's binary_logloss: 0.0626307
[75]	valid_0's binary_logloss: 0.0624198
[76]	valid_0's binary_logloss: 0.0619828
[77]	valid_0's binary_logloss: 0.0617609
[78]	valid_0's binary_logloss: 0.0616135
[79]	valid_0's binary_logloss: 0.0613228
[80]	valid_0's binary_logloss: 0.0610285
[81]	valid_0's binary_logloss: 0.0608462
[82]	valid_0's binary_logloss: 0.0605642
[83]	valid_0's binary_logloss: 0.0603166
[84]	valid_0's binary_logloss: 0.0598266
[85]	valid_0's binary_logloss: 0.0596407
[86]	valid_0's binary_logloss: 0.0592885
[87]	valid_0's binary_logloss: 0.0591512
[88]	valid_0's binary_logloss: 0.0589579
[89]	valid_0's binary_logloss: 0.0587162
[90]	valid_0's binary_logloss: 0.0583928
[91]	valid_0's binary_logloss: 0.0578996
[92]	valid_0's binary_logloss: 0.0577072
[93]	valid_0's binary_logloss: 0.0574206
[94]	valid_0's binary_logloss: 0.0572918
[95]	valid_0's binary_logloss: 0.057227
[96]	valid_0's binary_logloss: 0.0570563
[97]	valid_0's binary_logloss: 0.056962
[98]	valid_0's binary_logloss: 0.0569658
[99]	valid_0's binary_logloss: 0.0569717
[100]	valid_0's binary_logloss: 0.056888
[101]	valid_0's binary_logloss: 0.0568173
[102]	valid_0's binary_logloss: 0.0565745
[103]	valid_0's binary_logloss: 0.0565501
[104]	valid_0's binary_logloss: 0.0565315
[105]	valid_0's binary_logloss: 0.0564995
[106]	valid_0's binary_logloss: 0.0566933
[107]	valid_0's binary_logloss: 0.0566864
[108]	valid_0's binary_logloss: 0.0567044
[109]	valid_0's binary_logloss: 0.0564207
[110]	valid_0's binary_logloss: 0.0563562
[111]	valid_0's binary_logloss: 0.0563408
[112]	valid_0's binary_logloss: 0.0563466
[113]	valid_0's binary_logloss: 0.0562951
[114]	valid_0's binary_logloss: 0.0563497
[115]	valid_0's binary_logloss: 0.0565202
[116]	valid_0's binary_logloss: 0.0565493
[117]	valid_0's binary_logloss: 0.0565693
[118]	valid_0's binary_logloss: 0.0566049
[119]	valid_0's binary_logloss: 0.0565371
[120]	valid_0's binary_logloss: 0.0565186
[121]	valid_0's binary_logloss: 0.0565948
[122]	valid_0's binary_logloss: 0.0567299
[123]	valid_0's binary_logloss: 0.0568388
[124]	valid_0's binary_logloss: 0.0568477
[125]	valid_0's binary_logloss: 0.0568981
[126]	valid_0's binary_logloss: 0.0569045
[127]	valid_0's binary_logloss: 0.056952
[128]	valid_0's binary_logloss: 0.0569312
[129]	valid_0's binary_logloss: 0.0569685
[130]	valid_0's binary_logloss: 0.0569902
[131]	valid_0's binary_logloss: 0.0570588
[132]	valid_0's binary_logloss: 0.057135
[133]	valid_0's binary_logloss: 0.0571763
[134]	valid_0's binary_logloss: 0.0573232
[135]	valid_0's binary_logloss: 0.0575005
[136]	valid_0's binary_logloss: 0.0575685
[137]	valid_0's binary_logloss: 0.0575958
[138]	valid_0's binary_logloss: 0.0578064
[139]	valid_0's binary_logloss: 0.0579053
[140]	valid_0's binary_logloss: 0.0580285
[141]	valid_0's binary_logloss: 0.0581369

Trening klas:   7%|▋         | 35/500 [07:47<1:21:58, 10.58s/klasa, klasa=class_35, F1_klasy=0.9478, F1_macro=0.9077, drzewa=113]




Trening klas:   7%|▋         | 36/500 [07:47<1:18:48, 10.19s/klasa, klasa=class_35, F1_klasy=0.9478, F1_macro=0.9077, drzewa=113]

[142]	valid_0's binary_logloss: 0.0582348
[143]	valid_0's binary_logloss: 0.0582781
[1]	valid_0's binary_logloss: 0.663095
[2]	valid_0's binary_logloss: 0.59716
[3]	valid_0's binary_logloss: 0.547758
[4]	valid_0's binary_logloss: 0.509075
[5]	valid_0's binary_logloss: 0.47698
[6]	valid_0's binary_logloss: 0.449161
[7]	valid_0's binary_logloss: 0.425506
[8]	valid_0's binary_logloss: 0.40516
[9]	valid_0's binary_logloss: 0.387235
[10]	valid_0's binary_logloss: 0.370836
[11]	valid_0's binary_logloss: 0.356607
[12]	valid_0's binary_logloss: 0.343774
[13]	valid_0's binary_logloss: 0.331973
[14]	valid_0's binary_logloss: 0.32209
[15]	valid_0's binary_logloss: 0.313571
[16]	valid_0's binary_logloss: 0.304631
[17]	valid_0's binary_logloss: 0.297141
[18]	valid_0's binary_logloss: 0.290399
[19]	valid_0's binary_logloss: 0.284554
[20]	valid_0's binary_logloss: 0.279196
[21]	valid_0's binary_logloss: 0.273985
[22]	valid_0's binary_logloss: 0.269177
[23]	valid_0's binary_logloss: 0.265055
[24]	valid_0's binary_logloss: 0.261579
[25]	valid_0's binary_logloss: 0.25801
[26]	valid_0's binary_logloss: 0.255198
[27]	valid_0's binary_logloss: 0.252154
[28]	valid_0's binary_logloss: 0.249339
[29]	valid_0's binary_logloss: 0.247118
[30]	valid_0's binary_logloss: 0.244913
[31]	valid_0's binary_logloss: 0.242847
[32]	valid_0's binary_logloss: 0.240802
[33]	valid_0's binary_logloss: 0.239259
[34]	valid_0's binary_logloss: 0.237837
[35]	valid_0's binary_logloss: 0.23686
[36]	valid_0's binary_logloss: 0.235745
[37]	valid_0's binary_logloss: 0.234514
[38]	valid_0's binary_logloss: 0.233364
[39]	valid_0's binary_logloss: 0.232508
[40]	valid_0's binary_logloss: 0.23185
[41]	valid_0's binary_logloss: 0.231204
[42]	valid_0's binary_logloss: 0.231071
[43]	valid_0's binary_logloss: 0.230533
[44]	valid_0's binary_logloss: 0.230281
[45]	valid_0's binary_logloss: 0.23003
[46]	valid_0's binary_logloss: 0.229957
[47]	valid_0's binary_logloss: 0.229935
[48]	valid_0's binary_logloss: 0.229897
[49]	valid_0's binary_logloss: 0.2301
[50]	valid_0's binary_logloss: 0.230275
[51]	valid_0's binary_logloss: 0.23061
[52]	valid_0's binary_logloss: 0.230936
[53]	valid_0's binary_logloss: 0.230936
[54]	valid_0's binary_logloss: 0.231315
[55]	valid_0's binary_logloss: 0.231731
[56]	valid_0's binary_logloss: 0.232254
[57]	valid_0's binary_logloss: 0.232882
[58]	valid_0's binary_logloss: 0.233094
[59]	valid_0's binary_logloss: 0.232803
[60]	valid_0's binary_logloss: 0.232819
[61]	valid_0's binary_logloss: 0.233081
[62]	valid_0's binary_logloss: 0.233695
[63]	valid_0's binary_logloss: 0.233898
[64]	valid_0's binary_logloss: 0.234273
[65]	valid_0's binary_logloss: 0.234527
[66]	valid_0's binary_logloss: 0.235418
[67]	valid_0's binary_logloss: 0.235632
[68]	valid_0's binary_logloss: 0.235767
[69]	valid_0's binary_logloss: 0.235819
[70]	valid_0's binary_logloss: 0.23604
[71]	valid_0's binary_logloss: 0.236204
[72]	valid_0's binary_logloss: 0.236104
[73]	valid_0's binary_logloss: 0.236315
[74]	valid_0's binary_logloss: 0.236757
[75]	valid_0's binary_logloss: 0.236992
[76]	valid_0's binary_logloss: 0.237516
[77]	valid_0's binary_logloss: 0.23812
[78]	valid_0's binary_logloss: 0.238701

Trening klas:   7%|▋         | 36/500 [07:53<1:18:48, 10.19s/klasa, klasa=class_36, F1_klasy=0.8677, F1_macro=0.9067, drzewa=48]




Trening klas:   7%|▋         | 37/500 [07:53<1:07:26,  8.74s/klasa, klasa=class_36, F1_klasy=0.8677, F1_macro=0.9067, drzewa=48]

[1]	valid_0's binary_logloss: 0.286478
[2]	valid_0's binary_logloss: 0.267749
[3]	valid_0's binary_logloss: 0.251537
[4]	valid_0's binary_logloss: 0.237858
[5]	valid_0's binary_logloss: 0.225881
[6]	valid_0's binary_logloss: 0.214953
[7]	valid_0's binary_logloss: 0.204813
[8]	valid_0's binary_logloss: 0.195727
[9]	valid_0's binary_logloss: 0.187736
[10]	valid_0's binary_logloss: 0.180104
[11]	valid_0's binary_logloss: 0.173304
[12]	valid_0's binary_logloss: 0.166865
[13]	valid_0's binary_logloss: 0.160749
[14]	valid_0's binary_logloss: 0.15491
[15]	valid_0's binary_logloss: 0.149594
[16]	valid_0's binary_logloss: 0.144603
[17]	valid_0's binary_logloss: 0.139988
[18]	valid_0's binary_logloss: 0.135775
[19]	valid_0's binary_logloss: 0.131579
[20]	valid_0's binary_logloss: 0.127562
[21]	valid_0's binary_logloss: 0.123885
[22]	valid_0's binary_logloss: 0.120513
[23]	valid_0's binary_logloss: 0.117423
[24]	valid_0's binary_logloss: 0.114481
[25]	valid_0's binary_logloss: 0.111781
[26]	valid_0's binary_logloss: 0.109221
[27]	valid_0's binary_logloss: 0.106692
[28]	valid_0's binary_logloss: 0.104071
[29]	valid_0's binary_logloss: 0.101715
[30]	valid_0's binary_logloss: 0.0994907
[31]	valid_0's binary_logloss: 0.097666
[32]	valid_0's binary_logloss: 0.0957518
[33]	valid_0's binary_logloss: 0.094075
[34]	valid_0's binary_logloss: 0.092383
[35]	valid_0's binary_logloss: 0.0907808
[36]	valid_0's binary_logloss: 0.0894148
[37]	valid_0's binary_logloss: 0.0882948
[38]	valid_0's binary_logloss: 0.0871839
[39]	valid_0's binary_logloss: 0.0861357
[40]	valid_0's binary_logloss: 0.0849896
[41]	valid_0's binary_logloss: 0.0837121
[42]	valid_0's binary_logloss: 0.0827231
[43]	valid_0's binary_logloss: 0.0814275
[44]	valid_0's binary_logloss: 0.0803148
[45]	valid_0's binary_logloss: 0.0790902
[46]	valid_0's binary_logloss: 0.0783256
[47]	valid_0's binary_logloss: 0.0776609
[48]	valid_0's binary_logloss: 0.0768471
[49]	valid_0's binary_logloss: 0.0762988
[50]	valid_0's binary_logloss: 0.0756532
[51]	valid_0's binary_logloss: 0.0749376
[52]	valid_0's binary_logloss: 0.0741904
[53]	valid_0's binary_logloss: 0.0734817
[54]	valid_0's binary_logloss: 0.0728721
[55]	valid_0's binary_logloss: 0.0721646
[56]	valid_0's binary_logloss: 0.07189
[57]	valid_0's binary_logloss: 0.0716467
[58]	valid_0's binary_logloss: 0.0711229
[59]	valid_0's binary_logloss: 0.070551
[60]	valid_0's binary_logloss: 0.0701327
[61]	valid_0's binary_logloss: 0.0700583
[62]	valid_0's binary_logloss: 0.0699071
[63]	valid_0's binary_logloss: 0.0696351
[64]	valid_0's binary_logloss: 0.0692454
[65]	valid_0's binary_logloss: 0.0688317
[66]	valid_0's binary_logloss: 0.0684566
[67]	valid_0's binary_logloss: 0.0681297
[68]	valid_0's binary_logloss: 0.0678035
[69]	valid_0's binary_logloss: 0.0675791
[70]	valid_0's binary_logloss: 0.0675718
[71]	valid_0's binary_logloss: 0.0672088
[72]	valid_0's binary_logloss: 0.0669609
[73]	valid_0's binary_logloss: 0.0666765
[74]	valid_0's binary_logloss: 0.0663051
[75]	valid_0's binary_logloss: 0.0661477
[76]	valid_0's binary_logloss: 0.0659553
[77]	valid_0's binary_logloss: 0.065589
[78]	valid_0's binary_logloss: 0.0651866
[79]	valid_0's binary_logloss: 0.0649463
[80]	valid_0's binary_logloss: 0.0648098
[81]	valid_0's binary_logloss: 0.064617
[82]	valid_0's binary_logloss: 0.0643639
[83]	valid_0's binary_logloss: 0.0641754
[84]	valid_0's binary_logloss: 0.0640152
[85]	valid_0's binary_logloss: 0.0638078
[86]	valid_0's binary_logloss: 0.0635973
[87]	valid_0's binary_logloss: 0.0632915
[88]	valid_0's binary_logloss: 0.062937
[89]	valid_0's binary_logloss: 0.0627923
[90]	valid_0's binary_logloss: 0.0628089
[91]	valid_0's binary_logloss: 0.0625169
[92]	valid_0's binary_logloss: 0.0623483
[93]	valid_0's binary_logloss: 0.062101
[94]	valid_0's binary_logloss: 0.0619727
[95]	valid_0's binary_logloss: 0.0617859
[96]	valid_0's binary_logloss: 0.0618106
[97]	valid_0's binary_logloss: 0.0619857
[98]	valid_0's binary_logloss: 0.0622922
[99]	valid_0's binary_logloss: 0.0623218
[100]	valid_0's binary_logloss: 0.0624579
[101]	valid_0's binary_logloss: 0.0625139
[102]	valid_0's binary_logloss: 0.0626605
[103]	valid_0's binary_logloss: 0.062715
[104]	valid_0's binary_logloss: 0.0628503
[105]	valid_0's binary_logloss: 0.0628251
[106]	valid_0's binary_logloss: 0.0629007
[107]	valid_0's binary_logloss: 0.0626831
[108]	valid_0's binary_logloss: 0.0625715
[109]	valid_0's binary_logloss: 0.0625495
[110]	valid_0's binary_logloss: 0.0625666
[111]	valid_0's binary_logloss: 0.0626441
[112]	valid_0's binary_logloss: 0.0625669
[113]	valid_0's binary_logloss: 0.0624359
[114]	valid_0's binary_logloss: 0.0624385
[115]	valid_0's binary_logloss: 0.0624929
[116]	valid_0's binary_logloss: 0.0624638
[117]	valid_0's binary_logloss: 0.0626121
[118]	valid_0's binary_logloss: 0.0626988
[119]	valid_0's binary_logloss: 0.0626123
[120]	valid_0's binary_logloss: 0.062786
[121]	valid_0's binary_logloss: 0.0629584
[122]	valid_0's binary_logloss: 0.0633228
[123]	valid_0's binary_logloss: 0.0635994
[124]	valid_0's binary_logloss: 0.0636705
[125]	valid_0's binary_logloss: 0.0639361

Trening klas:   7%|▋         | 37/500 [08:01<1:07:26,  8.74s/klasa, klasa=class_37, F1_klasy=0.8759, F1_macro=0.9059, drzewa=95]




Trening klas:   8%|▊         | 38/500 [08:01<1:05:18,  8.48s/klasa, klasa=class_37, F1_klasy=0.8759, F1_macro=0.9059, drzewa=95]

[1]	valid_0's binary_logloss: 0.245403
[2]	valid_0's binary_logloss: 0.229411
[3]	valid_0's binary_logloss: 0.215264
[4]	valid_0's binary_logloss: 0.202749
[5]	valid_0's binary_logloss: 0.191928
[6]	valid_0's binary_logloss: 0.181686
[7]	valid_0's binary_logloss: 0.172235
[8]	valid_0's binary_logloss: 0.163735
[9]	valid_0's binary_logloss: 0.155659
[10]	valid_0's binary_logloss: 0.148259
[11]	valid_0's binary_logloss: 0.141299
[12]	valid_0's binary_logloss: 0.134835
[13]	valid_0's binary_logloss: 0.128741
[14]	valid_0's binary_logloss: 0.123277
[15]	valid_0's binary_logloss: 0.118119
[16]	valid_0's binary_logloss: 0.113106
[17]	valid_0's binary_logloss: 0.108378
[18]	valid_0's binary_logloss: 0.104043
[19]	valid_0's binary_logloss: 0.0998954
[20]	valid_0's binary_logloss: 0.09594
[21]	valid_0's binary_logloss: 0.0923242
[22]	valid_0's binary_logloss: 0.0888819
[23]	valid_0's binary_logloss: 0.0856689
[24]	valid_0's binary_logloss: 0.0826442
[25]	valid_0's binary_logloss: 0.0798214
[26]	valid_0's binary_logloss: 0.0771253
[27]	valid_0's binary_logloss: 0.0746566
[28]	valid_0's binary_logloss: 0.0723336
[29]	valid_0's binary_logloss: 0.0701562
[30]	valid_0's binary_logloss: 0.0679326
[31]	valid_0's binary_logloss: 0.0658189
[32]	valid_0's binary_logloss: 0.0638904
[33]	valid_0's binary_logloss: 0.0620083
[34]	valid_0's binary_logloss: 0.0602141
[35]	valid_0's binary_logloss: 0.0586246
[36]	valid_0's binary_logloss: 0.0570585
[37]	valid_0's binary_logloss: 0.0555103
[38]	valid_0's binary_logloss: 0.0541308
[39]	valid_0's binary_logloss: 0.0528265
[40]	valid_0's binary_logloss: 0.0515655
[41]	valid_0's binary_logloss: 0.0503946
[42]	valid_0's binary_logloss: 0.0492636
[43]	valid_0's binary_logloss: 0.0482051
[44]	valid_0's binary_logloss: 0.047144
[45]	valid_0's binary_logloss: 0.0461731
[46]	valid_0's binary_logloss: 0.0453038
[47]	valid_0's binary_logloss: 0.0444226
[48]	valid_0's binary_logloss: 0.0436114
[49]	valid_0's binary_logloss: 0.0428144
[50]	valid_0's binary_logloss: 0.0420194
[51]	valid_0's binary_logloss: 0.0413098
[52]	valid_0's binary_logloss: 0.0407139
[53]	valid_0's binary_logloss: 0.0401556
[54]	valid_0's binary_logloss: 0.0396175
[55]	valid_0's binary_logloss: 0.0390915
[56]	valid_0's binary_logloss: 0.0386109
[57]	valid_0's binary_logloss: 0.0381266
[58]	valid_0's binary_logloss: 0.0376693
[59]	valid_0's binary_logloss: 0.0372132
[60]	valid_0's binary_logloss: 0.0368286
[61]	valid_0's binary_logloss: 0.036433
[62]	valid_0's binary_logloss: 0.0361117
[63]	valid_0's binary_logloss: 0.0357972
[64]	valid_0's binary_logloss: 0.0355246
[65]	valid_0's binary_logloss: 0.0352292
[66]	valid_0's binary_logloss: 0.0348884
[67]	valid_0's binary_logloss: 0.034534
[68]	valid_0's binary_logloss: 0.0342473
[69]	valid_0's binary_logloss: 0.0339685
[70]	valid_0's binary_logloss: 0.0337432
[71]	valid_0's binary_logloss: 0.033651
[72]	valid_0's binary_logloss: 0.0333919
[73]	valid_0's binary_logloss: 0.0332144
[74]	valid_0's binary_logloss: 0.0331053
[75]	valid_0's binary_logloss: 0.0329176
[76]	valid_0's binary_logloss: 0.0327734
[77]	valid_0's binary_logloss: 0.0326692
[78]	valid_0's binary_logloss: 0.0325483
[79]	valid_0's binary_logloss: 0.0324782
[80]	valid_0's binary_logloss: 0.0322935
[81]	valid_0's binary_logloss: 0.0321278
[82]	valid_0's binary_logloss: 0.0320564
[83]	valid_0's binary_logloss: 0.0319411
[84]	valid_0's binary_logloss: 0.0318354
[85]	valid_0's binary_logloss: 0.0316905
[86]	valid_0's binary_logloss: 0.0316342
[87]	valid_0's binary_logloss: 0.0315379
[88]	valid_0's binary_logloss: 0.0315355
[89]	valid_0's binary_logloss: 0.0314753
[90]	valid_0's binary_logloss: 0.0314136
[91]	valid_0's binary_logloss: 0.0314645
[92]	valid_0's binary_logloss: 0.0312972
[93]	valid_0's binary_logloss: 0.0312462
[94]	valid_0's binary_logloss: 0.0310969
[95]	valid_0's binary_logloss: 0.03108
[96]	valid_0's binary_logloss: 0.0309448
[97]	valid_0's binary_logloss: 0.0308468
[98]	valid_0's binary_logloss: 0.030662
[99]	valid_0's binary_logloss: 0.030556
[100]	valid_0's binary_logloss: 0.0304783
[101]	valid_0's binary_logloss: 0.0304403
[102]	valid_0's binary_logloss: 0.0304635
[103]	valid_0's binary_logloss: 0.0305506
[104]	valid_0's binary_logloss: 0.0306417
[105]	valid_0's binary_logloss: 0.0305915
[106]	valid_0's binary_logloss: 0.0305742
[107]	valid_0's binary_logloss: 0.0306259
[108]	valid_0's binary_logloss: 0.0306497
[109]	valid_0's binary_logloss: 0.0306305
[110]	valid_0's binary_logloss: 0.030689
[111]	valid_0's binary_logloss: 0.0306385
[112]	valid_0's binary_logloss: 0.0305466
[113]	valid_0's binary_logloss: 0.0305551
[114]	valid_0's binary_logloss: 0.030535
[115]	valid_0's binary_logloss: 0.0304135
[116]	valid_0's binary_logloss: 0.0304429
[117]	valid_0's binary_logloss: 0.030439
[118]	valid_0's binary_logloss: 0.0303709
[119]	valid_0's binary_logloss: 0.0303992
[120]	valid_0's binary_logloss: 0.0303837
[121]	valid_0's binary_logloss: 0.0303939
[122]	valid_0's binary_logloss: 0.0303538
[123]	valid_0's binary_logloss: 0.0303938
[124]	valid_0's binary_logloss: 0.0303121
[125]	valid_0's binary_logloss: 0.0303146
[126]	valid_0's binary_logloss: 0.030406
[127]	valid_0's binary_logloss: 0.0304724
[128]	valid_0's binary_logloss: 0.0305368
[129]	valid_0's binary_logloss: 0.0305051
[130]	valid_0's binary_logloss: 0.0305515
[131]	valid_0's binary_logloss: 0.0306343
[132]	valid_0's binary_logloss: 0.0307184
[133]	valid_0's binary_logloss: 0.0308145
[134]	valid_0's binary_logloss: 0.0308209
[135]	valid_0's binary_logloss: 0.0308458
[136]	valid_0's binary_logloss: 0.0308127
[137]	valid_0's binary_logloss: 0.0307733
[138]	valid_0's binary_logloss: 0.0308007
[139]	valid_0's binary_logloss: 0.0308158
[140]	valid_0's binary_logloss: 0.0307338
[141]	valid_0's binary_logloss: 0.0306872
[142]	valid_0's binary_logloss: 0.0306064
[143]	valid_0's binary_logloss: 0.0306341
[144]	valid_0's binary_logloss: 0.0306772
[145]	valid_0's binary_logloss: 0.030689
[146]	valid_0's binary_logloss: 0.030768
[147]	valid_0's binary_logloss: 0.0307981
[148]	valid_0's binary_logloss: 0.030838
[149]	valid_0's binary_logloss: 0.030895
[150]	valid_0's binary_logloss: 0.0309956
[151]	valid_0's binary_logloss: 0.0310147
[152]	valid_0's binary_logloss: 0.0310772
[153]	valid_0's binary_logloss: 0.0309265
[154]	valid_0's binary_logloss: 0.0308833

Trening klas:   8%|▊         | 38/500 [08:11<1:05:18,  8.48s/klasa, klasa=class_38, F1_klasy=0.8967, F1_macro=0.9056, drzewa=124]




Trening klas:   8%|▊         | 39/500 [08:11<1:08:47,  8.95s/klasa, klasa=class_38, F1_klasy=0.8967, F1_macro=0.9056, drzewa=124]

[1]	valid_0's binary_logloss: 0.642036
[2]	valid_0's binary_logloss: 0.576825
[3]	valid_0's binary_logloss: 0.529636
[4]	valid_0's binary_logloss: 0.492352
[5]	valid_0's binary_logloss: 0.462255
[6]	valid_0's binary_logloss: 0.438133
[7]	valid_0's binary_logloss: 0.417991
[8]	valid_0's binary_logloss: 0.401132
[9]	valid_0's binary_logloss: 0.385933
[10]	valid_0's binary_logloss: 0.373172
[11]	valid_0's binary_logloss: 0.360841
[12]	valid_0's binary_logloss: 0.350017
[13]	valid_0's binary_logloss: 0.340833
[14]	valid_0's binary_logloss: 0.332686
[15]	valid_0's binary_logloss: 0.325023
[16]	valid_0's binary_logloss: 0.317729
[17]	valid_0's binary_logloss: 0.310714
[18]	valid_0's binary_logloss: 0.305393
[19]	valid_0's binary_logloss: 0.300549
[20]	valid_0's binary_logloss: 0.2953
[21]	valid_0's binary_logloss: 0.291313
[22]	valid_0's binary_logloss: 0.287883
[23]	valid_0's binary_logloss: 0.284377
[24]	valid_0's binary_logloss: 0.282027
[25]	valid_0's binary_logloss: 0.279337
[26]	valid_0's binary_logloss: 0.276882
[27]	valid_0's binary_logloss: 0.274907
[28]	valid_0's binary_logloss: 0.272942
[29]	valid_0's binary_logloss: 0.27102
[30]	valid_0's binary_logloss: 0.269577
[31]	valid_0's binary_logloss: 0.267621
[32]	valid_0's binary_logloss: 0.266237
[33]	valid_0's binary_logloss: 0.265059
[34]	valid_0's binary_logloss: 0.263942
[35]	valid_0's binary_logloss: 0.263286
[36]	valid_0's binary_logloss: 0.262468
[37]	valid_0's binary_logloss: 0.261088
[38]	valid_0's binary_logloss: 0.260001
[39]	valid_0's binary_logloss: 0.259412
[40]	valid_0's binary_logloss: 0.258824
[41]	valid_0's binary_logloss: 0.258685
[42]	valid_0's binary_logloss: 0.258233
[43]	valid_0's binary_logloss: 0.257635
[44]	valid_0's binary_logloss: 0.257338
[45]	valid_0's binary_logloss: 0.25743
[46]	valid_0's binary_logloss: 0.25738
[47]	valid_0's binary_logloss: 0.257309
[48]	valid_0's binary_logloss: 0.257317
[49]	valid_0's binary_logloss: 0.257235
[50]	valid_0's binary_logloss: 0.257
[51]	valid_0's binary_logloss: 0.256516
[52]	valid_0's binary_logloss: 0.255878
[53]	valid_0's binary_logloss: 0.255299
[54]	valid_0's binary_logloss: 0.255148
[55]	valid_0's binary_logloss: 0.254745
[56]	valid_0's binary_logloss: 0.255256
[57]	valid_0's binary_logloss: 0.254956
[58]	valid_0's binary_logloss: 0.254934
[59]	valid_0's binary_logloss: 0.254883
[60]	valid_0's binary_logloss: 0.25524
[61]	valid_0's binary_logloss: 0.255575
[62]	valid_0's binary_logloss: 0.256151
[63]	valid_0's binary_logloss: 0.256626
[64]	valid_0's binary_logloss: 0.257048
[65]	valid_0's binary_logloss: 0.257329
[66]	valid_0's binary_logloss: 0.257114
[67]	valid_0's binary_logloss: 0.256962
[68]	valid_0's binary_logloss: 0.257066
[69]	valid_0's binary_logloss: 0.256981
[70]	valid_0's binary_logloss: 0.257167
[71]	valid_0's binary_logloss: 0.256922
[72]	valid_0's binary_logloss: 0.257537
[73]	valid_0's binary_logloss: 0.258129
[74]	valid_0's binary_logloss: 0.258035
[75]	valid_0's binary_logloss: 0.2585
[76]	valid_0's binary_logloss: 0.25831
[77]	valid_0's binary_logloss: 0.257951
[78]	valid_0's binary_logloss: 0.257978
[79]	valid_0's binary_logloss: 0.257929
[80]	valid_0's binary_logloss: 0.257823
[81]	valid_0's binary_logloss: 0.258027
[82]	valid_0's binary_logloss: 0.258365
[83]	valid_0's binary_logloss: 0.258499

Trening klas:   8%|▊         | 39/500 [08:17<1:08:47,  8.95s/klasa, klasa=class_39, F1_klasy=0.8276, F1_macro=0.9037, drzewa=55]




Trening klas:   8%|▊         | 40/500 [08:17<1:02:30,  8.15s/klasa, klasa=class_39, F1_klasy=0.8276, F1_macro=0.9037, drzewa=55]

[84]	valid_0's binary_logloss: 0.258356
[85]	valid_0's binary_logloss: 0.258412
[1]	valid_0's binary_logloss: 0.642036
[2]	valid_0's binary_logloss: 0.576825
[3]	valid_0's binary_logloss: 0.529636
[4]	valid_0's binary_logloss: 0.492352
[5]	valid_0's binary_logloss: 0.462255
[6]	valid_0's binary_logloss: 0.438133
[7]	valid_0's binary_logloss: 0.417991
[8]	valid_0's binary_logloss: 0.401132
[9]	valid_0's binary_logloss: 0.385933
[10]	valid_0's binary_logloss: 0.373172
[11]	valid_0's binary_logloss: 0.360841
[12]	valid_0's binary_logloss: 0.350017
[13]	valid_0's binary_logloss: 0.340833
[14]	valid_0's binary_logloss: 0.332686
[15]	valid_0's binary_logloss: 0.325023
[16]	valid_0's binary_logloss: 0.317729
[17]	valid_0's binary_logloss: 0.310714
[18]	valid_0's binary_logloss: 0.305393
[19]	valid_0's binary_logloss: 0.300549
[20]	valid_0's binary_logloss: 0.2953
[21]	valid_0's binary_logloss: 0.291313
[22]	valid_0's binary_logloss: 0.287883
[23]	valid_0's binary_logloss: 0.284377
[24]	valid_0's binary_logloss: 0.282027
[25]	valid_0's binary_logloss: 0.279337
[26]	valid_0's binary_logloss: 0.276882
[27]	valid_0's binary_logloss: 0.274907
[28]	valid_0's binary_logloss: 0.272942
[29]	valid_0's binary_logloss: 0.27102
[30]	valid_0's binary_logloss: 0.269577
[31]	valid_0's binary_logloss: 0.267621
[32]	valid_0's binary_logloss: 0.266237
[33]	valid_0's binary_logloss: 0.265059
[34]	valid_0's binary_logloss: 0.263942
[35]	valid_0's binary_logloss: 0.263286
[36]	valid_0's binary_logloss: 0.262468
[37]	valid_0's binary_logloss: 0.261088
[38]	valid_0's binary_logloss: 0.260001
[39]	valid_0's binary_logloss: 0.259412
[40]	valid_0's binary_logloss: 0.258824
[41]	valid_0's binary_logloss: 0.258685
[42]	valid_0's binary_logloss: 0.258233
[43]	valid_0's binary_logloss: 0.257635
[44]	valid_0's binary_logloss: 0.257338
[45]	valid_0's binary_logloss: 0.25743
[46]	valid_0's binary_logloss: 0.25738
[47]	valid_0's binary_logloss: 0.257309
[48]	valid_0's binary_logloss: 0.257317
[49]	valid_0's binary_logloss: 0.257235
[50]	valid_0's binary_logloss: 0.257
[51]	valid_0's binary_logloss: 0.256516
[52]	valid_0's binary_logloss: 0.255878
[53]	valid_0's binary_logloss: 0.255299
[54]	valid_0's binary_logloss: 0.255148
[55]	valid_0's binary_logloss: 0.254745
[56]	valid_0's binary_logloss: 0.255256
[57]	valid_0's binary_logloss: 0.254956
[58]	valid_0's binary_logloss: 0.254934
[59]	valid_0's binary_logloss: 0.254883
[60]	valid_0's binary_logloss: 0.25524
[61]	valid_0's binary_logloss: 0.255575
[62]	valid_0's binary_logloss: 0.256151
[63]	valid_0's binary_logloss: 0.256626
[64]	valid_0's binary_logloss: 0.257048
[65]	valid_0's binary_logloss: 0.257329
[66]	valid_0's binary_logloss: 0.257114
[67]	valid_0's binary_logloss: 0.256962
[68]	valid_0's binary_logloss: 0.257066
[69]	valid_0's binary_logloss: 0.256981
[70]	valid_0's binary_logloss: 0.257167
[71]	valid_0's binary_logloss: 0.256922
[72]	valid_0's binary_logloss: 0.257537
[73]	valid_0's binary_logloss: 0.258129
[74]	valid_0's binary_logloss: 0.258035
[75]	valid_0's binary_logloss: 0.2585
[76]	valid_0's binary_logloss: 0.25831
[77]	valid_0's binary_logloss: 0.257951
[78]	valid_0's binary_logloss: 0.257978
[79]	valid_0's binary_logloss: 0.257929
[80]	valid_0's binary_logloss: 0.257823
[81]	valid_0's binary_logloss: 0.258027
[82]	valid_0's binary_logloss: 0.258365
[83]	valid_0's binary_logloss: 0.258499
[84]	valid_0's binary_logloss: 0.258356
[85]	valid_0's binary_logloss: 0.258412

Trening klas:   8%|▊         | 40/500 [08:23<1:02:30,  8.15s/klasa, klasa=class_40, F1_klasy=0.8276, F1_macro=0.9018, drzewa=55]




Trening klas:   8%|▊         | 41/500 [08:23<57:51,  7.56s/klasa, klasa=class_40, F1_klasy=0.8276, F1_macro=0.9018, drzewa=55]

[1]	valid_0's binary_logloss: 0.235806
[2]	valid_0's binary_logloss: 0.220092
[3]	valid_0's binary_logloss: 0.206692
[4]	valid_0's binary_logloss: 0.19475
[5]	valid_0's binary_logloss: 0.184429
[6]	valid_0's binary_logloss: 0.17461
[7]	valid_0's binary_logloss: 0.165683
[8]	valid_0's binary_logloss: 0.15725
[9]	valid_0's binary_logloss: 0.149516
[10]	valid_0's binary_logloss: 0.142691
[11]	valid_0's binary_logloss: 0.135954
[12]	valid_0's binary_logloss: 0.129665
[13]	valid_0's binary_logloss: 0.123877
[14]	valid_0's binary_logloss: 0.118378
[15]	valid_0's binary_logloss: 0.113274
[16]	valid_0's binary_logloss: 0.108359
[17]	valid_0's binary_logloss: 0.103991
[18]	valid_0's binary_logloss: 0.0998818
[19]	valid_0's binary_logloss: 0.0960902
[20]	valid_0's binary_logloss: 0.0923543
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0888848
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0857119
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.0827485
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0797822
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.076997
[26]	valid_0's binary_logloss: 0.0744329
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.071928
[28]	valid_0's binary_logloss: 0.0696084
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.0674538
[30]	valid_0's binary_logloss: 0.0653584
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.0634309
[32]	valid_0's binary_logloss: 0.0617002
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.0601068
[34]	valid_0's binary_logloss: 0.0583655
[35]	valid_0's binary_logloss: 0.0568367
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.0553135
[37]	valid_0's binary_logloss: 0.0539058
[38]	valid_0's binary_logloss: 0.0526041
[39]	valid_0's binary_logloss: 0.0513003
[40]	valid_0's binary_logloss: 0.0500591
[41]	valid_0's binary_logloss: 0.0489794
[42]	valid_0's binary_logloss: 0.0478231
[43]	valid_0's binary_logloss: 0.046816
[44]	valid_0's binary_logloss: 0.0457826
[45]	valid_0's binary_logloss: 0.044898
[46]	valid_0's binary_logloss: 0.0439929
[47]	valid_0's binary_logloss: 0.0431762
[48]	valid_0's binary_logloss: 0.0423972
[49]	valid_0's binary_logloss: 0.041705
[50]	valid_0's binary_logloss: 0.0409968
[51]	valid_0's binary_logloss: 0.0403964
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.0398335
[53]	valid_0's binary_logloss: 0.0393142
[54]	valid_0's binary_logloss: 0.0386919
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.0382452
[56]	valid_0's binary_logloss: 0.0377869
[57]	valid_0's binary_logloss: 0.0373836
[58]	valid_0's binary_logloss: 0.0369302
[59]	valid_0's binary_logloss: 0.0365461
[60]	valid_0's binary_logloss: 0.0361942
[61]	valid_0's binary_logloss: 0.0359384
[62]	valid_0's binary_logloss: 0.0356179
[63]	valid_0's binary_logloss: 0.0353122
[64]	valid_0's binary_logloss: 0.0350606
[65]	valid_0's binary_logloss: 0.0348298
[66]	valid_0's binary_logloss: 0.0346544
[67]	valid_0's binary_logloss: 0.0344921
[68]	valid_0's binary_logloss: 0.0342474
[69]	valid_0's binary_logloss: 0.0340747
[70]	valid_0's binary_logloss: 0.0339311
[71]	valid_0's binary_logloss: 0.0337538
[72]	valid_0's binary_logloss: 0.0335824
[73]	valid_0's binary_logloss: 0.0334104
[74]	valid_0's binary_logloss: 0.0332879
[75]	valid_0's binary_logloss: 0.0332227
[76]	valid_0's binary_logloss: 0.0330982
[77]	valid_0's binary_logloss: 0.0328658
[78]	valid_0's binary_logloss: 0.0327441
[79]	valid_0's binary_logloss: 0.0327482
[80]	valid_0's binary_logloss: 0.0326559
[81]	valid_0's binary_logloss: 0.0324733
[82]	valid_0's binary_logloss: 0.0324023
[83]	valid_0's binary_logloss: 0.0322596
[84]	valid_0's binary_logloss: 0.0321143
[85]	valid_0's binary_logloss: 0.0320101
[86]	valid_0's binary_logloss: 0.0318946
[87]	valid_0's binary_logloss: 0.0317606
[88]	valid_0's binary_logloss: 0.0317372
[89]	valid_0's binary_logloss: 0.0316706
[90]	valid_0's binary_logloss: 0.0316236
[91]	valid_0's binary_logloss: 0.0314842
[92]	valid_0's binary_logloss: 0.0315323
[93]	valid_0's binary_logloss: 0.0315456
[94]	valid_0's binary_logloss: 0.031523
[95]	valid_0's binary_logloss: 0.0314412
[96]	valid_0's binary_logloss: 0.0313085
[97]	valid_0's binary_logloss: 0.0312398
[98]	valid_0's binary_logloss: 0.0311284
[99]	valid_0's binary_logloss: 0.0310459
[100]	valid_0's binary_logloss: 0.0310064
[101]	valid_0's binary_logloss: 0.031047
[102]	valid_0's binary_logloss: 0.031036
[103]	valid_0's binary_logloss: 0.0311467
[104]	valid_0's binary_logloss: 0.0312349
[105]	valid_0's binary_logloss: 0.0313232
[106]	valid_0's binary_logloss: 0.0312988
[107]	valid_0's binary_logloss: 0.0313724
[108]	valid_0's binary_logloss: 0.0314069
[109]	valid_0's binary_logloss: 0.0314626
[110]	valid_0's binary_logloss: 0.0315078
[111]	valid_0's binary_logloss: 0.0316349
[112]	valid_0's binary_logloss: 0.0315793
[113]	valid_0's binary_logloss: 0.0316054
[114]	valid_0's binary_logloss: 0.0315863
[115]	valid_0's binary_logloss: 0.0316668
[116]	valid_0's binary_logloss: 0.0317219
[117]	valid_0's binary_logloss: 0.031772
[118]	valid_0's binary_logloss: 0.0317881
[119]	valid_0's binary_logloss: 0.031808
[120]	valid_0's binary_logloss: 0.0318439
[121]	valid_0's binary_logloss: 0.031766
[122]	valid_0's binary_logloss: 0.0318092
[123]	valid_0's binary_logloss: 0.0319184
[124]	valid_0's binary_logloss: 0.0319583
[125]	valid_0's binary_logloss: 0.0319328
[126]	valid_0's binary_logloss: 0.032021
[127]	valid_0's binary_logloss: 0.0320557
[128]	valid_0's binary_logloss: 0.0322449
[129]	valid_0's binary_logloss: 0.0323087

Trening klas:   8%|▊         | 41/500 [08:30<57:51,  7.56s/klasa, klasa=class_41, F1_klasy=0.8879, F1_macro=0.9015, drzewa=100]




Trening klas:   8%|▊         | 42/500 [08:30<57:00,  7.47s/klasa, klasa=class_41, F1_klasy=0.8879, F1_macro=0.9015, drzewa=100]

[130]	valid_0's binary_logloss: 0.0323399
[1]	valid_0's binary_logloss: 0.436564
[2]	valid_0's binary_logloss: 0.398631
[3]	valid_0's binary_logloss: 0.370299
[4]	valid_0's binary_logloss: 0.34876
[5]	valid_0's binary_logloss: 0.329983
[6]	valid_0's binary_logloss: 0.313979
[7]	valid_0's binary_logloss: 0.300237
[8]	valid_0's binary_logloss: 0.288506
[9]	valid_0's binary_logloss: 0.278329
[10]	valid_0's binary_logloss: 0.269276
[11]	valid_0's binary_logloss: 0.2612
[12]	valid_0's binary_logloss: 0.25372
[13]	valid_0's binary_logloss: 0.246721
[14]	valid_0's binary_logloss: 0.240308
[15]	valid_0's binary_logloss: 0.233957
[16]	valid_0's binary_logloss: 0.228544
[17]	valid_0's binary_logloss: 0.223801
[18]	valid_0's binary_logloss: 0.219427
[19]	valid_0's binary_logloss: 0.215173
[20]	valid_0's binary_logloss: 0.211259
[21]	valid_0's binary_logloss: 0.207662
[22]	valid_0's binary_logloss: 0.204374
[23]	valid_0's binary_logloss: 0.201258
[24]	valid_0's binary_logloss: 0.198925
[25]	valid_0's binary_logloss: 0.196547
[26]	valid_0's binary_logloss: 0.194491
[27]	valid_0's binary_logloss: 0.191855
[28]	valid_0's binary_logloss: 0.18992
[29]	valid_0's binary_logloss: 0.1884
[30]	valid_0's binary_logloss: 0.187099
[31]	valid_0's binary_logloss: 0.185774
[32]	valid_0's binary_logloss: 0.184345
[33]	valid_0's binary_logloss: 0.18332
[34]	valid_0's binary_logloss: 0.182218
[35]	valid_0's binary_logloss: 0.181209
[36]	valid_0's binary_logloss: 0.180239
[37]	valid_0's binary_logloss: 0.179261
[38]	valid_0's binary_logloss: 0.178631
[39]	valid_0's binary_logloss: 0.178025
[40]	valid_0's binary_logloss: 0.177721
[41]	valid_0's binary_logloss: 0.177206
[42]	valid_0's binary_logloss: 0.176789
[43]	valid_0's binary_logloss: 0.176548
[44]	valid_0's binary_logloss: 0.175973
[45]	valid_0's binary_logloss: 0.175395
[46]	valid_0's binary_logloss: 0.175015
[47]	valid_0's binary_logloss: 0.17465
[48]	valid_0's binary_logloss: 0.173921
[49]	valid_0's binary_logloss: 0.173645
[50]	valid_0's binary_logloss: 0.172805
[51]	valid_0's binary_logloss: 0.172248
[52]	valid_0's binary_logloss: 0.172013
[53]	valid_0's binary_logloss: 0.170949
[54]	valid_0's binary_logloss: 0.170597
[55]	valid_0's binary_logloss: 0.170239
[56]	valid_0's binary_logloss: 0.169717
[57]	valid_0's binary_logloss: 0.168713
[58]	valid_0's binary_logloss: 0.168758
[59]	valid_0's binary_logloss: 0.168289
[60]	valid_0's binary_logloss: 0.167846
[61]	valid_0's binary_logloss: 0.167826
[62]	valid_0's binary_logloss: 0.167823
[63]	valid_0's binary_logloss: 0.167674
[64]	valid_0's binary_logloss: 0.167151
[65]	valid_0's binary_logloss: 0.167001
[66]	valid_0's binary_logloss: 0.166917
[67]	valid_0's binary_logloss: 0.166471
[68]	valid_0's binary_logloss: 0.165949
[69]	valid_0's binary_logloss: 0.165628
[70]	valid_0's binary_logloss: 0.165244
[71]	valid_0's binary_logloss: 0.164969
[72]	valid_0's binary_logloss: 0.164634
[73]	valid_0's binary_logloss: 0.164857
[74]	valid_0's binary_logloss: 0.164313
[75]	valid_0's binary_logloss: 0.164282
[76]	valid_0's binary_logloss: 0.164053
[77]	valid_0's binary_logloss: 0.163556
[78]	valid_0's binary_logloss: 0.163566
[79]	valid_0's binary_logloss: 0.16309
[80]	valid_0's binary_logloss: 0.16275
[81]	valid_0's binary_logloss: 0.162645
[82]	valid_0's binary_logloss: 0.162431
[83]	valid_0's binary_logloss: 0.162399
[84]	valid_0's binary_logloss: 0.162466
[85]	valid_0's binary_logloss: 0.161781
[86]	valid_0's binary_logloss: 0.161865
[87]	valid_0's binary_logloss: 0.161866
[88]	valid_0's binary_logloss: 0.161726
[89]	valid_0's binary_logloss: 0.161452
[90]	valid_0's binary_logloss: 0.161624
[91]	valid_0's binary_logloss: 0.161074
[92]	valid_0's binary_logloss: 0.160825
[93]	valid_0's binary_logloss: 0.160935
[94]	valid_0's binary_logloss: 0.160598
[95]	valid_0's binary_logloss: 0.160276
[96]	valid_0's binary_logloss: 0.159975
[97]	valid_0's binary_logloss: 0.159508
[98]	valid_0's binary_logloss: 0.159099
[99]	valid_0's binary_logloss: 0.158649
[100]	valid_0's binary_logloss: 0.158242
[101]	valid_0's binary_logloss: 0.15832
[102]	valid_0's binary_logloss: 0.158233
[103]	valid_0's binary_logloss: 0.158019
[104]	valid_0's binary_logloss: 0.157953
[105]	valid_0's binary_logloss: 0.157872
[106]	valid_0's binary_logloss: 0.157891
[107]	valid_0's binary_logloss: 0.157921
[108]	valid_0's binary_logloss: 0.157806
[109]	valid_0's binary_logloss: 0.158086
[110]	valid_0's binary_logloss: 0.157776
[111]	valid_0's binary_logloss: 0.157902
[112]	valid_0's binary_logloss: 0.157927
[113]	valid_0's binary_logloss: 0.157685
[114]	valid_0's binary_logloss: 0.157551
[115]	valid_0's binary_logloss: 0.157485
[116]	valid_0's binary_logloss: 0.157751
[117]	valid_0's binary_logloss: 0.157981
[118]	valid_0's binary_logloss: 0.158008
[119]	valid_0's binary_logloss: 0.157666
[120]	valid_0's binary_logloss: 0.157801
[121]	valid_0's binary_logloss: 0.157861
[122]	valid_0's binary_logloss: 0.157812
[123]	valid_0's binary_logloss: 0.157821
[124]	valid_0's binary_logloss: 0.15778
[125]	valid_0's binary_logloss: 0.157787
[126]	valid_0's binary_logloss: 0.157651
[127]	valid_0's binary_logloss: 0.157486
[128]	valid_0's binary_logloss: 0.15721
[129]	valid_0's binary_logloss: 0.157128
[130]	valid_0's binary_logloss: 0.157336
[131]	valid_0's binary_logloss: 0.157124
[132]	valid_0's binary_logloss: 0.157261
[133]	valid_0's binary_logloss: 0.157346
[134]	valid_0's binary_logloss: 0.157371
[135]	valid_0's binary_logloss: 0.157516
[136]	valid_0's binary_logloss: 0.157559
[137]	valid_0's binary_logloss: 0.157527
[138]	valid_0's binary_logloss: 0.157386
[139]	valid_0's binary_logloss: 0.15747
[140]	valid_0's binary_logloss: 0.157328
[141]	valid_0's binary_logloss: 0.157342
[142]	valid_0's binary_logloss: 0.157231
[143]	valid_0's binary_logloss: 0.15738
[144]	valid_0's binary_logloss: 0.15755
[145]	valid_0's binary_logloss: 0.157525
[146]	valid_0's binary_logloss: 0.157375
[147]	valid_0's binary_logloss: 0.157074
[148]	valid_0's binary_logloss: 0.157229
[149]	valid_0's binary_logloss: 0.157187
[150]	valid_0's binary_logloss: 0.157401
[151]	valid_0's binary_logloss: 0.15739
[152]	valid_0's binary_logloss: 0.157248
[153]	valid_0's binary_logloss: 0.157387
[154]	valid_0's binary_logloss: 0.157628
[155]	valid_0's binary_logloss: 0.157805
[156]	valid_0's binary_logloss: 0.157942
[157]	valid_0's binary_logloss: 0.157906
[158]	valid_0's binary_logloss: 0.157771
[159]	valid_0's binary_logloss: 0.157699
[160]	valid_0's binary_logloss: 0.157759
[161]	valid_0's binary_logloss: 0.157649
[162]	valid_0's binary_logloss: 0.157454
[163]	valid_0's binary_logloss: 0.157386
[164]	valid_0's binary_logloss: 0.157042
[165]	valid_0's binary_logloss: 0.157076
[166]	valid_0's binary_logloss: 0.156972
[167]	valid_0's binary_logloss: 0.157013
[168]	valid_0's binary_logloss: 0.156814
[169]	valid_0's binary_logloss: 0.15662
[170]	valid_0's binary_logloss: 0.156496
[171]	valid_0's binary_logloss: 0.156263
[172]	valid_0's binary_logloss: 0.156422
[173]	valid_0's binary_logloss: 0.156558
[174]	valid_0's binary_logloss: 0.156783
[175]	valid_0's binary_logloss: 0.156823
[176]	valid_0's binary_logloss: 0.156703
[177]	valid_0's binary_logloss: 0.15693
[178]	valid_0's binary_logloss: 0.157035
[179]	valid_0's binary_logloss: 0.156867
[180]	valid_0's binary_logloss: 0.156697
[181]	valid_0's binary_logloss: 0.157004
[182]	valid_0's binary_logloss: 0.157182
[183]	valid_0's binary_logloss: 0.157232
[184]	valid_0's binary_logloss: 0.157225
[185]	valid_0's binary_logloss: 0.157384
[186]	valid_0's binary_logloss: 0.157338
[187]	valid_0's binary_logloss: 0.157337
[188]	valid_0's binary_logloss: 0.157427
[189]	valid_0's binary_logloss: 0.157449
[190]	valid_0's binary_logloss: 0.157503
[191]	valid_0's binary_logloss: 0.157509
[192]	valid_0's binary_logloss: 0.157648
[193]	valid_0's binary_logloss: 0.157702
[194]	valid_0's binary_logloss: 0.157842
[195]	valid_0's binary_logloss: 0.157819
[196]	valid_0's binary_logloss: 0.158054
[197]	valid_0's binary_logloss: 0.158084
[198]	valid_0's binary_logloss: 0.158201
[199]	valid_0's binary_logloss: 0.158337
[200]	valid_0's binary_logloss: 0.158261
[201]	valid_0's binary_logloss: 0.158317

Trening klas:   8%|▊         | 42/500 [08:43<57:00,  7.47s/klasa, klasa=class_42, F1_klasy=0.8472, F1_macro=0.9002, drzewa=171]




Trening klas:   9%|▊         | 43/500 [08:43<1:09:16,  9.09s/klasa, klasa=class_42, F1_klasy=0.8472, F1_macro=0.9002, drzewa=171]

[1]	valid_0's binary_logloss: 0.417714
[2]	valid_0's binary_logloss: 0.3765
[3]	valid_0's binary_logloss: 0.344848
[4]	valid_0's binary_logloss: 0.318776
[5]	valid_0's binary_logloss: 0.297167
[6]	valid_0's binary_logloss: 0.279208
[7]	valid_0's binary_logloss: 0.262832
[8]	valid_0's binary_logloss: 0.248348
[9]	valid_0's binary_logloss: 0.235257
[10]	valid_0's binary_logloss: 0.223814
[11]	valid_0's binary_logloss: 0.213419
[12]	valid_0's binary_logloss: 0.204151
[13]	valid_0's binary_logloss: 0.195655
[14]	valid_0's binary_logloss: 0.187706
[15]	valid_0's binary_logloss: 0.180662
[16]	valid_0's binary_logloss: 0.173647
[17]	valid_0's binary_logloss: 0.167443
[18]	valid_0's binary_logloss: 0.161365
[19]	valid_0's binary_logloss: 0.155856
[20]	valid_0's binary_logloss: 0.150595
[21]	valid_0's binary_logloss: 0.145851
[22]	valid_0's binary_logloss: 0.141493
[23]	valid_0's binary_logloss: 0.137775
[24]	valid_0's binary_logloss: 0.133769
[25]	valid_0's binary_logloss: 0.130187
[26]	valid_0's binary_logloss: 0.126879
[27]	valid_0's binary_logloss: 0.123798
[28]	valid_0's binary_logloss: 0.121036
[29]	valid_0's binary_logloss: 0.118277
[30]	valid_0's binary_logloss: 0.115172
[31]	valid_0's binary_logloss: 0.112296
[32]	valid_0's binary_logloss: 0.109762
[33]	valid_0's binary_logloss: 0.107218
[34]	valid_0's binary_logloss: 0.105141
[35]	valid_0's binary_logloss: 0.103084
[36]	valid_0's binary_logloss: 0.100836
[37]	valid_0's binary_logloss: 0.0986731
[38]	valid_0's binary_logloss: 0.0968059
[39]	valid_0's binary_logloss: 0.0952315
[40]	valid_0's binary_logloss: 0.0931891
[41]	valid_0's binary_logloss: 0.0917973
[42]	valid_0's binary_logloss: 0.0905318
[43]	valid_0's binary_logloss: 0.0887461
[44]	valid_0's binary_logloss: 0.0872632
[45]	valid_0's binary_logloss: 0.086206
[46]	valid_0's binary_logloss: 0.0851104
[47]	valid_0's binary_logloss: 0.0838244
[48]	valid_0's binary_logloss: 0.0827734
[49]	valid_0's binary_logloss: 0.0818935
[50]	valid_0's binary_logloss: 0.0809982
[51]	valid_0's binary_logloss: 0.0799601
[52]	valid_0's binary_logloss: 0.0792181
[53]	valid_0's binary_logloss: 0.0782642
[54]	valid_0's binary_logloss: 0.0776969
[55]	valid_0's binary_logloss: 0.0768959
[56]	valid_0's binary_logloss: 0.0763383
[57]	valid_0's binary_logloss: 0.0756012
[58]	valid_0's binary_logloss: 0.0747983
[59]	valid_0's binary_logloss: 0.0742269
[60]	valid_0's binary_logloss: 0.0736607
[61]	valid_0's binary_logloss: 0.0729233
[62]	valid_0's binary_logloss: 0.0722422
[63]	valid_0's binary_logloss: 0.0716856
[64]	valid_0's binary_logloss: 0.0712142
[65]	valid_0's binary_logloss: 0.0704854
[66]	valid_0's binary_logloss: 0.0695966
[67]	valid_0's binary_logloss: 0.0687872
[68]	valid_0's binary_logloss: 0.0681378
[69]	valid_0's binary_logloss: 0.0674847
[70]	valid_0's binary_logloss: 0.0671322
[71]	valid_0's binary_logloss: 0.0667345
[72]	valid_0's binary_logloss: 0.0665045
[73]	valid_0's binary_logloss: 0.0662942
[74]	valid_0's binary_logloss: 0.0659291
[75]	valid_0's binary_logloss: 0.0655844
[76]	valid_0's binary_logloss: 0.0652567
[77]	valid_0's binary_logloss: 0.0651135
[78]	valid_0's binary_logloss: 0.0648175
[79]	valid_0's binary_logloss: 0.064523
[80]	valid_0's binary_logloss: 0.0639499
[81]	valid_0's binary_logloss: 0.0637669
[82]	valid_0's binary_logloss: 0.0638017
[83]	valid_0's binary_logloss: 0.0636948
[84]	valid_0's binary_logloss: 0.0634896
[85]	valid_0's binary_logloss: 0.0633362
[86]	valid_0's binary_logloss: 0.0630955
[87]	valid_0's binary_logloss: 0.0629528
[88]	valid_0's binary_logloss: 0.0628694
[89]	valid_0's binary_logloss: 0.0626318
[90]	valid_0's binary_logloss: 0.0624757
[91]	valid_0's binary_logloss: 0.0623736
[92]	valid_0's binary_logloss: 0.0622109
[93]	valid_0's binary_logloss: 0.0619738
[94]	valid_0's binary_logloss: 0.0616165
[95]	valid_0's binary_logloss: 0.06159
[96]	valid_0's binary_logloss: 0.0615523
[97]	valid_0's binary_logloss: 0.0614961
[98]	valid_0's binary_logloss: 0.0613253
[99]	valid_0's binary_logloss: 0.061362
[100]	valid_0's binary_logloss: 0.0610133
[101]	valid_0's binary_logloss: 0.0607896
[102]	valid_0's binary_logloss: 0.0606504
[103]	valid_0's binary_logloss: 0.0605587
[104]	valid_0's binary_logloss: 0.0605414
[105]	valid_0's binary_logloss: 0.0604129
[106]	valid_0's binary_logloss: 0.0603756
[107]	valid_0's binary_logloss: 0.0600233
[108]	valid_0's binary_logloss: 0.0599184
[109]	valid_0's binary_logloss: 0.0598731
[110]	valid_0's binary_logloss: 0.0597669
[111]	valid_0's binary_logloss: 0.0595861
[112]	valid_0's binary_logloss: 0.0594408
[113]	valid_0's binary_logloss: 0.0594266
[114]	valid_0's binary_logloss: 0.0594327
[115]	valid_0's binary_logloss: 0.0594394
[116]	valid_0's binary_logloss: 0.0594378
[117]	valid_0's binary_logloss: 0.0593963
[118]	valid_0's binary_logloss: 0.0593957
[119]	valid_0's binary_logloss: 0.0594215
[120]	valid_0's binary_logloss: 0.0594101
[121]	valid_0's binary_logloss: 0.0594227
[122]	valid_0's binary_logloss: 0.0594457
[123]	valid_0's binary_logloss: 0.0593184
[124]	valid_0's binary_logloss: 0.0591844
[125]	valid_0's binary_logloss: 0.0592649
[126]	valid_0's binary_logloss: 0.0593268
[127]	valid_0's binary_logloss: 0.0592904
[128]	valid_0's binary_logloss: 0.0591864
[129]	valid_0's binary_logloss: 0.0591236
[130]	valid_0's binary_logloss: 0.059131
[131]	valid_0's binary_logloss: 0.0591234
[132]	valid_0's binary_logloss: 0.0591286
[133]	valid_0's binary_logloss: 0.0590952
[134]	valid_0's binary_logloss: 0.0591546
[135]	valid_0's binary_logloss: 0.0592086
[136]	valid_0's binary_logloss: 0.0592022
[137]	valid_0's binary_logloss: 0.0592541
[138]	valid_0's binary_logloss: 0.0592844
[139]	valid_0's binary_logloss: 0.0592575
[140]	valid_0's binary_logloss: 0.0593614
[141]	valid_0's binary_logloss: 0.0594192
[142]	valid_0's binary_logloss: 0.0595358
[143]	valid_0's binary_logloss: 0.0595645
[144]	valid_0's binary_logloss: 0.0594866
[145]	valid_0's binary_logloss: 0.0594778
[146]	valid_0's binary_logloss: 0.0596414
[147]	valid_0's binary_logloss: 0.0597237
[148]	valid_0's binary_logloss: 0.0597829
[149]	valid_0's binary_logloss: 0.0598416
[150]	valid_0's binary_logloss: 0.0599329
[151]	valid_0's binary_logloss: 0.059916
[152]	valid_0's binary_logloss: 0.0597992
[153]	valid_0's binary_logloss: 0.0598385
[154]	valid_0's binary_logloss: 0.0599155
[155]	valid_0's binary_logloss: 0.0599458
[156]	valid_0's binary_logloss: 0.0597969
[157]	valid_0's binary_logloss: 0.0598518
[158]	valid_0's binary_logloss: 0.0599783
[159]	valid_0's binary_logloss: 0.0599427
[160]	valid_0's binary_logloss: 0.0599945
[161]	valid_0's binary_logloss: 0.0601286
[162]	valid_0's binary_logloss: 0.0602229
[163]	valid_0's binary_logloss: 0.0602692

Trening klas:   9%|▊         | 43/500 [08:54<1:09:16,  9.09s/klasa, klasa=class_43, F1_klasy=0.9387, F1_macro=0.9011, drzewa=133]




Trening klas:   9%|▉         | 44/500 [08:54<1:13:02,  9.61s/klasa, klasa=class_43, F1_klasy=0.9387, F1_macro=0.9011, drzewa=133]

[1]	valid_0's binary_logloss: 0.255077
[2]	valid_0's binary_logloss: 0.239417
[3]	valid_0's binary_logloss: 0.226086
[4]	valid_0's binary_logloss: 0.214718
[5]	valid_0's binary_logloss: 0.204396
[6]	valid_0's binary_logloss: 0.195387
[7]	valid_0's binary_logloss: 0.187148
[8]	valid_0's binary_logloss: 0.17938
[9]	valid_0's binary_logloss: 0.172381
[10]	valid_0's binary_logloss: 0.166066
[11]	valid_0's binary_logloss: 0.159955
[12]	valid_0's binary_logloss: 0.154346
[13]	valid_0's binary_logloss: 0.149523
[14]	valid_0's binary_logloss: 0.144738
[15]	valid_0's binary_logloss: 0.140467
[16]	valid_0's binary_logloss: 0.136239
[17]	valid_0's binary_logloss: 0.132514
[18]	valid_0's binary_logloss: 0.128741
[19]	valid_0's binary_logloss: 0.125311
[20]	valid_0's binary_logloss: 0.122377
[21]	valid_0's binary_logloss: 0.119487
[22]	valid_0's binary_logloss: 0.116815
[23]	valid_0's binary_logloss: 0.114337
[24]	valid_0's binary_logloss: 0.112012
[25]	valid_0's binary_logloss: 0.109448
[26]	valid_0's binary_logloss: 0.1073
[27]	valid_0's binary_logloss: 0.105162
[28]	valid_0's binary_logloss: 0.103262
[29]	valid_0's binary_logloss: 0.101237
[30]	valid_0's binary_logloss: 0.099344
[31]	valid_0's binary_logloss: 0.0977066
[32]	valid_0's binary_logloss: 0.0960687
[33]	valid_0's binary_logloss: 0.0945477
[34]	valid_0's binary_logloss: 0.0930825
[35]	valid_0's binary_logloss: 0.0918039
[36]	valid_0's binary_logloss: 0.0903475
[37]	valid_0's binary_logloss: 0.0889923
[38]	valid_0's binary_logloss: 0.0878186
[39]	valid_0's binary_logloss: 0.0867301
[40]	valid_0's binary_logloss: 0.0856294
[41]	valid_0's binary_logloss: 0.0844891
[42]	valid_0's binary_logloss: 0.0833132
[43]	valid_0's binary_logloss: 0.0823211
[44]	valid_0's binary_logloss: 0.0814061
[45]	valid_0's binary_logloss: 0.0806582
[46]	valid_0's binary_logloss: 0.0798184
[47]	valid_0's binary_logloss: 0.07897
[48]	valid_0's binary_logloss: 0.0782258
[49]	valid_0's binary_logloss: 0.0774986
[50]	valid_0's binary_logloss: 0.0768226
[51]	valid_0's binary_logloss: 0.0761546
[52]	valid_0's binary_logloss: 0.0756423
[53]	valid_0's binary_logloss: 0.075148
[54]	valid_0's binary_logloss: 0.0748526
[55]	valid_0's binary_logloss: 0.0743574
[56]	valid_0's binary_logloss: 0.0739253
[57]	valid_0's binary_logloss: 0.0735491
[58]	valid_0's binary_logloss: 0.0732339
[59]	valid_0's binary_logloss: 0.0729174
[60]	valid_0's binary_logloss: 0.0726254
[61]	valid_0's binary_logloss: 0.0721399
[62]	valid_0's binary_logloss: 0.0718194
[63]	valid_0's binary_logloss: 0.071601
[64]	valid_0's binary_logloss: 0.0715483
[65]	valid_0's binary_logloss: 0.071426
[66]	valid_0's binary_logloss: 0.0711535
[67]	valid_0's binary_logloss: 0.0709653
[68]	valid_0's binary_logloss: 0.0706209
[69]	valid_0's binary_logloss: 0.0703566
[70]	valid_0's binary_logloss: 0.0700266
[71]	valid_0's binary_logloss: 0.0698195
[72]	valid_0's binary_logloss: 0.0696797
[73]	valid_0's binary_logloss: 0.0694125
[74]	valid_0's binary_logloss: 0.0692884
[75]	valid_0's binary_logloss: 0.0688728
[76]	valid_0's binary_logloss: 0.0687741
[77]	valid_0's binary_logloss: 0.0686323
[78]	valid_0's binary_logloss: 0.0685919
[79]	valid_0's binary_logloss: 0.0686214
[80]	valid_0's binary_logloss: 0.068491
[81]	valid_0's binary_logloss: 0.0684257
[82]	valid_0's binary_logloss: 0.0683356
[83]	valid_0's binary_logloss: 0.0684277
[84]	valid_0's binary_logloss: 0.0684418
[85]	valid_0's binary_logloss: 0.0681629
[86]	valid_0's binary_logloss: 0.0680466
[87]	valid_0's binary_logloss: 0.0680018
[88]	valid_0's binary_logloss: 0.0681313
[89]	valid_0's binary_logloss: 0.0681307
[90]	valid_0's binary_logloss: 0.0680776
[91]	valid_0's binary_logloss: 0.067856
[92]	valid_0's binary_logloss: 0.0677135
[93]	valid_0's binary_logloss: 0.067433
[94]	valid_0's binary_logloss: 0.0673003
[95]	valid_0's binary_logloss: 0.0672619
[96]	valid_0's binary_logloss: 0.0672727
[97]	valid_0's binary_logloss: 0.0672507
[98]	valid_0's binary_logloss: 0.0673632
[99]	valid_0's binary_logloss: 0.0675057
[100]	valid_0's binary_logloss: 0.067509
[101]	valid_0's binary_logloss: 0.0676637
[102]	valid_0's binary_logloss: 0.0676708
[103]	valid_0's binary_logloss: 0.0677859
[104]	valid_0's binary_logloss: 0.0679288
[105]	valid_0's binary_logloss: 0.0680161
[106]	valid_0's binary_logloss: 0.0681184
[107]	valid_0's binary_logloss: 0.0680628
[108]	valid_0's binary_logloss: 0.0683394
[109]	valid_0's binary_logloss: 0.0684471
[110]	valid_0's binary_logloss: 0.0686014
[111]	valid_0's binary_logloss: 0.0685298
[112]	valid_0's binary_logloss: 0.0686792
[113]	valid_0's binary_logloss: 0.0686989
[114]	valid_0's binary_logloss: 0.0688128
[115]	valid_0's binary_logloss: 0.0689553
[116]	valid_0's binary_logloss: 0.0689403
[117]	valid_0's binary_logloss: 0.0688292
[118]	valid_0's binary_logloss: 0.0686845
[119]	valid_0's binary_logloss: 0.0687956
[120]	valid_0's binary_logloss: 0.0688006
[121]	valid_0's binary_logloss: 0.0689429
[122]	valid_0's binary_logloss: 0.0690499
[123]	valid_0's binary_logloss: 0.0690759
[124]	valid_0's binary_logloss: 0.0691696
[125]	valid_0's binary_logloss: 0.0692854
[126]	valid_0's binary_logloss: 0.0693473
[127]	valid_0's binary_logloss: 0.0694101

Trening klas:   9%|▉         | 44/500 [09:03<1:13:02,  9.61s/klasa, klasa=class_44, F1_klasy=0.8208, F1_macro=0.8993, drzewa=97]




Trening klas:   9%|▉         | 45/500 [09:03<1:12:15,  9.53s/klasa, klasa=class_44, F1_klasy=0.8208, F1_macro=0.8993, drzewa=97]

[1]	valid_0's binary_logloss: 0.415909
[2]	valid_0's binary_logloss: 0.381055
[3]	valid_0's binary_logloss: 0.354429
[4]	valid_0's binary_logloss: 0.334003
[5]	valid_0's binary_logloss: 0.31702
[6]	valid_0's binary_logloss: 0.302901
[7]	valid_0's binary_logloss: 0.289897
[8]	valid_0's binary_logloss: 0.278825
[9]	valid_0's binary_logloss: 0.269054
[10]	valid_0's binary_logloss: 0.26003
[11]	valid_0's binary_logloss: 0.251999
[12]	valid_0's binary_logloss: 0.244704
[13]	valid_0's binary_logloss: 0.238727
[14]	valid_0's binary_logloss: 0.232721
[15]	valid_0's binary_logloss: 0.227874
[16]	valid_0's binary_logloss: 0.222844
[17]	valid_0's binary_logloss: 0.218255
[18]	valid_0's binary_logloss: 0.214481
[19]	valid_0's binary_logloss: 0.211127
[20]	valid_0's binary_logloss: 0.208046
[21]	valid_0's binary_logloss: 0.204694
[22]	valid_0's binary_logloss: 0.201979
[23]	valid_0's binary_logloss: 0.199152
[24]	valid_0's binary_logloss: 0.196731
[25]	valid_0's binary_logloss: 0.194394
[26]	valid_0's binary_logloss: 0.192395
[27]	valid_0's binary_logloss: 0.190606
[28]	valid_0's binary_logloss: 0.189417
[29]	valid_0's binary_logloss: 0.188404
[30]	valid_0's binary_logloss: 0.187365
[31]	valid_0's binary_logloss: 0.186647
[32]	valid_0's binary_logloss: 0.184898
[33]	valid_0's binary_logloss: 0.184211
[34]	valid_0's binary_logloss: 0.183317
[35]	valid_0's binary_logloss: 0.18262
[36]	valid_0's binary_logloss: 0.181507
[37]	valid_0's binary_logloss: 0.180381
[38]	valid_0's binary_logloss: 0.179938
[39]	valid_0's binary_logloss: 0.179062
[40]	valid_0's binary_logloss: 0.178245
[41]	valid_0's binary_logloss: 0.178
[42]	valid_0's binary_logloss: 0.177174
[43]	valid_0's binary_logloss: 0.176576
[44]	valid_0's binary_logloss: 0.175939
[45]	valid_0's binary_logloss: 0.174946
[46]	valid_0's binary_logloss: 0.174454
[47]	valid_0's binary_logloss: 0.173865
[48]	valid_0's binary_logloss: 0.173292
[49]	valid_0's binary_logloss: 0.173006
[50]	valid_0's binary_logloss: 0.17247
[51]	valid_0's binary_logloss: 0.17229
[52]	valid_0's binary_logloss: 0.172101
[53]	valid_0's binary_logloss: 0.171582
[54]	valid_0's binary_logloss: 0.171363
[55]	valid_0's binary_logloss: 0.171455
[56]	valid_0's binary_logloss: 0.170639
[57]	valid_0's binary_logloss: 0.16998
[58]	valid_0's binary_logloss: 0.169937
[59]	valid_0's binary_logloss: 0.169461
[60]	valid_0's binary_logloss: 0.169146
[61]	valid_0's binary_logloss: 0.169001
[62]	valid_0's binary_logloss: 0.168945
[63]	valid_0's binary_logloss: 0.169116
[64]	valid_0's binary_logloss: 0.168846
[65]	valid_0's binary_logloss: 0.168892
[66]	valid_0's binary_logloss: 0.168551
[67]	valid_0's binary_logloss: 0.168245
[68]	valid_0's binary_logloss: 0.167637
[69]	valid_0's binary_logloss: 0.167029
[70]	valid_0's binary_logloss: 0.166237
[71]	valid_0's binary_logloss: 0.165647
[72]	valid_0's binary_logloss: 0.164778
[73]	valid_0's binary_logloss: 0.164261
[74]	valid_0's binary_logloss: 0.164083
[75]	valid_0's binary_logloss: 0.163884
[76]	valid_0's binary_logloss: 0.163679
[77]	valid_0's binary_logloss: 0.163155
[78]	valid_0's binary_logloss: 0.163155
[79]	valid_0's binary_logloss: 0.162952
[80]	valid_0's binary_logloss: 0.162752
[81]	valid_0's binary_logloss: 0.162503
[82]	valid_0's binary_logloss: 0.161814
[83]	valid_0's binary_logloss: 0.161814
[84]	valid_0's binary_logloss: 0.161517
[85]	valid_0's binary_logloss: 0.161216
[86]	valid_0's binary_logloss: 0.161263
[87]	valid_0's binary_logloss: 0.161155
[88]	valid_0's binary_logloss: 0.16058
[89]	valid_0's binary_logloss: 0.160232
[90]	valid_0's binary_logloss: 0.16005
[91]	valid_0's binary_logloss: 0.159576
[92]	valid_0's binary_logloss: 0.159397
[93]	valid_0's binary_logloss: 0.159419
[94]	valid_0's binary_logloss: 0.159334
[95]	valid_0's binary_logloss: 0.158993
[96]	valid_0's binary_logloss: 0.158815
[97]	valid_0's binary_logloss: 0.158662
[98]	valid_0's binary_logloss: 0.158476
[99]	valid_0's binary_logloss: 0.158471
[100]	valid_0's binary_logloss: 0.158314
[101]	valid_0's binary_logloss: 0.158113
[102]	valid_0's binary_logloss: 0.158155
[103]	valid_0's binary_logloss: 0.157901
[104]	valid_0's binary_logloss: 0.157862
[105]	valid_0's binary_logloss: 0.15785
[106]	valid_0's binary_logloss: 0.157511
[107]	valid_0's binary_logloss: 0.157803
[108]	valid_0's binary_logloss: 0.157465
[109]	valid_0's binary_logloss: 0.157599
[110]	valid_0's binary_logloss: 0.157429
[111]	valid_0's binary_logloss: 0.157267
[112]	valid_0's binary_logloss: 0.157044
[113]	valid_0's binary_logloss: 0.156936
[114]	valid_0's binary_logloss: 0.156899
[115]	valid_0's binary_logloss: 0.156922
[116]	valid_0's binary_logloss: 0.156853
[117]	valid_0's binary_logloss: 0.156558
[118]	valid_0's binary_logloss: 0.156097
[119]	valid_0's binary_logloss: 0.155731
[120]	valid_0's binary_logloss: 0.155467
[121]	valid_0's binary_logloss: 0.155411
[122]	valid_0's binary_logloss: 0.155432
[123]	valid_0's binary_logloss: 0.155822
[124]	valid_0's binary_logloss: 0.155911
[125]	valid_0's binary_logloss: 0.155955
[126]	valid_0's binary_logloss: 0.155924
[127]	valid_0's binary_logloss: 0.155994
[128]	valid_0's binary_logloss: 0.155814
[129]	valid_0's binary_logloss: 0.155901
[130]	valid_0's binary_logloss: 0.155968
[131]	valid_0's binary_logloss: 0.155843
[132]	valid_0's binary_logloss: 0.155831
[133]	valid_0's binary_logloss: 0.155575
[134]	valid_0's binary_logloss: 0.155671
[135]	valid_0's binary_logloss: 0.155608
[136]	valid_0's binary_logloss: 0.155696
[137]	valid_0's binary_logloss: 0.15558
[138]	valid_0's binary_logloss: 0.155318
[139]	valid_0's binary_logloss: 0.155316
[140]	valid_0's binary_logloss: 0.15536
[141]	valid_0's binary_logloss: 0.155259
[142]	valid_0's binary_logloss: 0.15533
[143]	valid_0's binary_logloss: 0.155266
[144]	valid_0's binary_logloss: 0.155263
[145]	valid_0's binary_logloss: 0.15505
[146]	valid_0's binary_logloss: 0.155035
[147]	valid_0's binary_logloss: 0.154918
[148]	valid_0's binary_logloss: 0.154468
[149]	valid_0's binary_logloss: 0.154653
[150]	valid_0's binary_logloss: 0.154841
[151]	valid_0's binary_logloss: 0.154706
[152]	valid_0's binary_logloss: 0.154723
[153]	valid_0's binary_logloss: 0.154796
[154]	valid_0's binary_logloss: 0.154927
[155]	valid_0's binary_logloss: 0.154944
[156]	valid_0's binary_logloss: 0.154812
[157]	valid_0's binary_logloss: 0.154837
[158]	valid_0's binary_logloss: 0.154922
[159]	valid_0's binary_logloss: 0.154962
[160]	valid_0's binary_logloss: 0.154995
[161]	valid_0's binary_logloss: 0.154741
[162]	valid_0's binary_logloss: 0.154365
[163]	valid_0's binary_logloss: 0.154246
[164]	valid_0's binary_logloss: 0.154199
[165]	valid_0's binary_logloss: 0.153965
[166]	valid_0's binary_logloss: 0.153764
[167]	valid_0's binary_logloss: 0.153781
[168]	valid_0's binary_logloss: 0.153858
[169]	valid_0's binary_logloss: 0.153678
[170]	valid_0's binary_logloss: 0.153201
[171]	valid_0's binary_logloss: 0.153261
[172]	valid_0's binary_logloss: 0.153449
[173]	valid_0's binary_logloss: 0.153407
[174]	valid_0's binary_logloss: 0.153487
[175]	valid_0's binary_logloss: 0.153368
[176]	valid_0's binary_logloss: 0.153371
[177]	valid_0's binary_logloss: 0.153425
[178]	valid_0's binary_logloss: 0.153346
[179]	valid_0's binary_logloss: 0.153399
[180]	valid_0's binary_logloss: 0.153454
[181]	valid_0's binary_logloss: 0.153465
[182]	valid_0's binary_logloss: 0.153532
[183]	valid_0's binary_logloss: 0.15372
[184]	valid_0's binary_logloss: 0.153701
[185]	valid_0's binary_logloss: 0.153968
[186]	valid_0's binary_logloss: 0.153847
[187]	valid_0's binary_logloss: 0.153769
[188]	valid_0's binary_logloss: 0.153695
[189]	valid_0's binary_logloss: 0.153602
[190]	valid_0's binary_logloss: 0.153332
[191]	valid_0's binary_logloss: 0.15341
[192]	valid_0's binary_logloss: 0.153644
[193]	valid_0's binary_logloss: 0.15377
[194]	valid_0's binary_logloss: 0.153854
[195]	valid_0's binary_logloss: 0.153973
[196]	valid_0's binary_logloss: 0.153966
[197]	valid_0's binary_logloss: 0.153896
[198]	valid_0's binary_logloss: 0.153989
[199]	valid_0's binary_logloss: 0.15401

Trening klas:   9%|▉         | 45/500 [09:16<1:12:15,  9.53s/klasa, klasa=class_45, F1_klasy=0.8329, F1_macro=0.8979, drzewa=170]




Trening klas:   9%|▉         | 46/500 [09:16<1:20:02, 10.58s/klasa, klasa=class_45, F1_klasy=0.8329, F1_macro=0.8979, drzewa=170]

[200]	valid_0's binary_logloss: 0.154003
[1]	valid_0's binary_logloss: 0.235298
[2]	valid_0's binary_logloss: 0.218227
[3]	valid_0's binary_logloss: 0.203863
[4]	valid_0's binary_logloss: 0.191484
[5]	valid_0's binary_logloss: 0.180458
[6]	valid_0's binary_logloss: 0.170614
[7]	valid_0's binary_logloss: 0.161671
[8]	valid_0's binary_logloss: 0.153559
[9]	valid_0's binary_logloss: 0.146147
[10]	valid_0's binary_logloss: 0.13932
[11]	valid_0's binary_logloss: 0.132935
[12]	valid_0's binary_logloss: 0.127021
[13]	valid_0's binary_logloss: 0.121659
[14]	valid_0's binary_logloss: 0.116647
[15]	valid_0's binary_logloss: 0.111966
[16]	valid_0's binary_logloss: 0.107661
[17]	valid_0's binary_logloss: 0.103613
[18]	valid_0's binary_logloss: 0.0997856
[19]	valid_0's binary_logloss: 0.0963018
[20]	valid_0's binary_logloss: 0.0929215
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0898628
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0869649
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.0842946
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.081756
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.0793997
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.0770901
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.0749512
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.0729581
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.0711119
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.0693458
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.0676949
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.0661592
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.06469
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.0633294
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.062036
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.0607675
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.0595812
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.0584456
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.0574032
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.056424
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.0554426
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.054619
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.0539749
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.0531272
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.052326
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.051707
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.0509825
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.050259
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.0497376
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.0491056
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.0484217
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.0478246
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.0472159
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.0464994
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.0459207
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.0453118
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.0448232
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.0443543
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.0439255
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.0434896
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.0429311
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.0427485
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.0422588
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.0419715
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.0417214
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.0411557
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.0408223
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.0404216
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.039912
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.0393635
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.038636
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.037939
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.0376407
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.0373901
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.0368215
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.036502
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.0362416
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.0361301
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.0358096
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.0357107
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.0355417
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.0353707
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.0350783
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.0348874
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.0346981
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.0345743
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.0345766
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.0346995
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.0346303
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.0344665
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.0341671
[92]	valid_0's binary_logloss: 0.0339309
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.0338157
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.0337427
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.0335204
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.0333242
[97]	valid_0's binary_logloss: 0.0330622
[98]	valid_0's binary_logloss: 0.032743
[99]	valid_0's binary_logloss: 0.0325358
[100]	valid_0's binary_logloss: 0.0323243
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.032364
[102]	valid_0's binary_logloss: 0.0321816
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.032097
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.0321828
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.0321633
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.0318082
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.0319071
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.0317784
[109]	valid_0's binary_logloss: 0.03148
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.0314166
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.0315083
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 0.0313674
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 0.0314042
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 0.0312929
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 0.0314219
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[116]	valid_0's binary_logloss: 0.0314754
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[117]	valid_0's binary_logloss: 0.0313043
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[118]	valid_0's binary_logloss: 0.0312185
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[119]	valid_0's binary_logloss: 0.0310118
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[120]	valid_0's binary_logloss: 0.0309549
[121]	valid_0's binary_logloss: 0.0310476
[122]	valid_0's binary_logloss: 0.0311102
[123]	valid_0's binary_logloss: 0.0310655
[124]	valid_0's binary_logloss: 0.0311379
[125]	valid_0's binary_logloss: 0.0312629
[126]	valid_0's binary_logloss: 0.031415
[127]	valid_0's binary_logloss: 0.0316095
[128]	valid_0's binary_logloss: 0.0317699
[129]	valid_0's binary_logloss: 0.0318539
[130]	valid_0's binary_logloss: 0.0320332
[131]	valid_0's binary_logloss: 0.0321763
[132]	valid_0's binary_logloss: 0.0320506
[133]	valid_0's binary_logloss: 0.0321419
[134]	valid_0's binary_logloss: 0.0321373
[135]	valid_0's binary_logloss: 0.03231
[136]	valid_0's binary_logloss: 0.0322941
[137]	valid_0's binary_logloss: 0.0324005
[138]	valid_0's binary_logloss: 0.0324532
[139]	valid_0's binary_logloss: 0.0324559
[140]	valid_0's binary_logloss: 0.0325579
[141]	valid_0's binary_logloss: 0.0326059
[142]	valid_0's binary_logloss: 0.032671
[143]	valid_0's binary_logloss: 0.0327689
[144]	valid_0's binary_logloss: 0.0328962
[145]	valid_0's binary_logloss: 0.0329948
[146]	valid_0's binary_logloss: 0.033253
[147]	valid_0's binary_logloss: 0.0334044
[148]	valid_0's binary_logloss: 0.0335168

Trening klas:   9%|▉         | 46/500 [09:23<1:20:02, 10.58s/klasa, klasa=class_46, F1_klasy=0.9155, F1_macro=0.8982, drzewa=120]




Trening klas:   9%|▉         | 47/500 [09:23<1:11:38,  9.49s/klasa, klasa=class_46, F1_klasy=0.9155, F1_macro=0.8982, drzewa=120]

[149]	valid_0's binary_logloss: 0.0336922
[150]	valid_0's binary_logloss: 0.0338119
[1]	valid_0's binary_logloss: 0.246673
[2]	valid_0's binary_logloss: 0.231983
[3]	valid_0's binary_logloss: 0.219661
[4]	valid_0's binary_logloss: 0.208768
[5]	valid_0's binary_logloss: 0.199103
[6]	valid_0's binary_logloss: 0.190578
[7]	valid_0's binary_logloss: 0.18258
[8]	valid_0's binary_logloss: 0.175331
[9]	valid_0's binary_logloss: 0.168557
[10]	valid_0's binary_logloss: 0.162411
[11]	valid_0's binary_logloss: 0.156463
[12]	valid_0's binary_logloss: 0.151275
[13]	valid_0's binary_logloss: 0.146339
[14]	valid_0's binary_logloss: 0.141834
[15]	valid_0's binary_logloss: 0.137713
[16]	valid_0's binary_logloss: 0.133938
[17]	valid_0's binary_logloss: 0.130028
[18]	valid_0's binary_logloss: 0.126334
[19]	valid_0's binary_logloss: 0.122955
[20]	valid_0's binary_logloss: 0.119974
[21]	valid_0's binary_logloss: 0.117017
[22]	valid_0's binary_logloss: 0.114191
[23]	valid_0's binary_logloss: 0.111632
[24]	valid_0's binary_logloss: 0.109348
[25]	valid_0's binary_logloss: 0.107181
[26]	valid_0's binary_logloss: 0.104812
[27]	valid_0's binary_logloss: 0.102513
[28]	valid_0's binary_logloss: 0.100364
[29]	valid_0's binary_logloss: 0.0984959
[30]	valid_0's binary_logloss: 0.0967583
[31]	valid_0's binary_logloss: 0.0952704
[32]	valid_0's binary_logloss: 0.0938799
[33]	valid_0's binary_logloss: 0.0924043
[34]	valid_0's binary_logloss: 0.0910343
[35]	valid_0's binary_logloss: 0.0896982
[36]	valid_0's binary_logloss: 0.0884525
[37]	valid_0's binary_logloss: 0.0871027
[38]	valid_0's binary_logloss: 0.0860952
[39]	valid_0's binary_logloss: 0.0849321
[40]	valid_0's binary_logloss: 0.0840288
[41]	valid_0's binary_logloss: 0.0830692
[42]	valid_0's binary_logloss: 0.0821179
[43]	valid_0's binary_logloss: 0.0811104
[44]	valid_0's binary_logloss: 0.080028
[45]	valid_0's binary_logloss: 0.0790745
[46]	valid_0's binary_logloss: 0.0783899
[47]	valid_0's binary_logloss: 0.0776043
[48]	valid_0's binary_logloss: 0.0770363
[49]	valid_0's binary_logloss: 0.0763918
[50]	valid_0's binary_logloss: 0.075785
[51]	valid_0's binary_logloss: 0.0753249
[52]	valid_0's binary_logloss: 0.074704
[53]	valid_0's binary_logloss: 0.0742335
[54]	valid_0's binary_logloss: 0.0738372
[55]	valid_0's binary_logloss: 0.0735293
[56]	valid_0's binary_logloss: 0.0732655
[57]	valid_0's binary_logloss: 0.072865
[58]	valid_0's binary_logloss: 0.0725656
[59]	valid_0's binary_logloss: 0.072281
[60]	valid_0's binary_logloss: 0.0719423
[61]	valid_0's binary_logloss: 0.0715107
[62]	valid_0's binary_logloss: 0.0713199
[63]	valid_0's binary_logloss: 0.0710329
[64]	valid_0's binary_logloss: 0.0705584
[65]	valid_0's binary_logloss: 0.0700599
[66]	valid_0's binary_logloss: 0.0697774
[67]	valid_0's binary_logloss: 0.06947
[68]	valid_0's binary_logloss: 0.0692549
[69]	valid_0's binary_logloss: 0.0691424
[70]	valid_0's binary_logloss: 0.0688698
[71]	valid_0's binary_logloss: 0.0686746
[72]	valid_0's binary_logloss: 0.0686493
[73]	valid_0's binary_logloss: 0.0684509
[74]	valid_0's binary_logloss: 0.0683419
[75]	valid_0's binary_logloss: 0.068205
[76]	valid_0's binary_logloss: 0.0680818
[77]	valid_0's binary_logloss: 0.0679199
[78]	valid_0's binary_logloss: 0.0677292
[79]	valid_0's binary_logloss: 0.0675691
[80]	valid_0's binary_logloss: 0.0676191
[81]	valid_0's binary_logloss: 0.067645
[82]	valid_0's binary_logloss: 0.0674723
[83]	valid_0's binary_logloss: 0.0674242
[84]	valid_0's binary_logloss: 0.0673324
[85]	valid_0's binary_logloss: 0.0673576
[86]	valid_0's binary_logloss: 0.0673066
[87]	valid_0's binary_logloss: 0.0673568
[88]	valid_0's binary_logloss: 0.0674533
[89]	valid_0's binary_logloss: 0.0673242
[90]	valid_0's binary_logloss: 0.0675091
[91]	valid_0's binary_logloss: 0.0673281
[92]	valid_0's binary_logloss: 0.0672715
[93]	valid_0's binary_logloss: 0.0672887
[94]	valid_0's binary_logloss: 0.0673461
[95]	valid_0's binary_logloss: 0.0673678
[96]	valid_0's binary_logloss: 0.0674243
[97]	valid_0's binary_logloss: 0.0673823
[98]	valid_0's binary_logloss: 0.0672768
[99]	valid_0's binary_logloss: 0.0672489
[100]	valid_0's binary_logloss: 0.0671056
[101]	valid_0's binary_logloss: 0.0672593
[102]	valid_0's binary_logloss: 0.0674223
[103]	valid_0's binary_logloss: 0.0674486
[104]	valid_0's binary_logloss: 0.067497
[105]	valid_0's binary_logloss: 0.0674777
[106]	valid_0's binary_logloss: 0.0675389
[107]	valid_0's binary_logloss: 0.0674549
[108]	valid_0's binary_logloss: 0.06757
[109]	valid_0's binary_logloss: 0.0675802
[110]	valid_0's binary_logloss: 0.0676344
[111]	valid_0's binary_logloss: 0.0676549
[112]	valid_0's binary_logloss: 0.0675892
[113]	valid_0's binary_logloss: 0.0675224
[114]	valid_0's binary_logloss: 0.0676015
[115]	valid_0's binary_logloss: 0.0675346
[116]	valid_0's binary_logloss: 0.0675087
[117]	valid_0's binary_logloss: 0.0674585
[118]	valid_0's binary_logloss: 0.0674581
[119]	valid_0's binary_logloss: 0.0674182
[120]	valid_0's binary_logloss: 0.067296
[121]	valid_0's binary_logloss: 0.0672645
[122]	valid_0's binary_logloss: 0.0673704
[123]	valid_0's binary_logloss: 0.0673995
[124]	valid_0's binary_logloss: 0.067608
[125]	valid_0's binary_logloss: 0.0677981
[126]	valid_0's binary_logloss: 0.0677767
[127]	valid_0's binary_logloss: 0.0678619

Trening klas:   9%|▉         | 47/500 [09:33<1:11:38,  9.49s/klasa, klasa=class_47, F1_klasy=0.8147, F1_macro=0.8965, drzewa=100]




Trening klas:  10%|▉         | 48/500 [09:33<1:11:10,  9.45s/klasa, klasa=class_47, F1_klasy=0.8147, F1_macro=0.8965, drzewa=100]

[128]	valid_0's binary_logloss: 0.0679274
[129]	valid_0's binary_logloss: 0.0679562
[130]	valid_0's binary_logloss: 0.0679873
[1]	valid_0's binary_logloss: 0.231516
[2]	valid_0's binary_logloss: 0.21469
[3]	valid_0's binary_logloss: 0.200576
[4]	valid_0's binary_logloss: 0.188386
[5]	valid_0's binary_logloss: 0.177542
[6]	valid_0's binary_logloss: 0.167878
[7]	valid_0's binary_logloss: 0.159097
[8]	valid_0's binary_logloss: 0.151088
[9]	valid_0's binary_logloss: 0.14378
[10]	valid_0's binary_logloss: 0.137109
[11]	valid_0's binary_logloss: 0.130815
[12]	valid_0's binary_logloss: 0.12508
[13]	valid_0's binary_logloss: 0.119823
[14]	valid_0's binary_logloss: 0.114932
[15]	valid_0's binary_logloss: 0.110321
[16]	valid_0's binary_logloss: 0.106099
[17]	valid_0's binary_logloss: 0.10206
[18]	valid_0's binary_logloss: 0.0983331
[19]	valid_0's binary_logloss: 0.0946548
[20]	valid_0's binary_logloss: 0.0913122
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0882624
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0854136
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.0827714
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0802127
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.0778513
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.0755162
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.073365
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.0714994
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.0695904
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.0678073
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.0661749
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.0647443
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.0632964
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.0619605
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.0606508
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.0595513
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.0585133
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.0575144
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.0567355
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.0558723
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.0548319
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.053985
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.0533611
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.0524561
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.0516111
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.0509971
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.0502096
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.0495039
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.049006
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.048335
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.0476208
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.0470046
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.0463323
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.045719
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.0448434
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.0444161
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.0438063
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.0434096
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.0429375
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.0424342
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.0419926
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.0413055
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.0411778
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.0408478
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.0406213
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.0401537
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.0397707
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.0394804
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.038954
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.0384456
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.0376173
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.0368548
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.036526
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.0360131
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.0353713
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.0350854
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.0347287
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.0344948
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.0342365
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.0340165
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.0336695
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.0334696
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.0332193
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.032939
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.0326731
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.0325779
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.0324231
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.0324141
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.0324606
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.0321757
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.0319846
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.0317497
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.0315405
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.031312
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.0313356
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.0310341
[97]	valid_0's binary_logloss: 0.030767
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.0305798
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.0303647
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.0302534
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.0303067
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.0303069
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.030354
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.0303441
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.0302616
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.0302108
[107]	valid_0's binary_logloss: 0.030132
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.0299956
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.0299855
[110]	valid_0's binary_logloss: 0.0298593
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.0298254
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 0.0297005
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 0.0296202
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 0.029379
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 0.0295938
[116]	valid_0's binary_logloss: 0.0295011
[117]	valid_0's binary_logloss: 0.0293969
[118]	valid_0's binary_logloss: 0.0294789
[119]	valid_0's binary_logloss: 0.0296346
[120]	valid_0's binary_logloss: 0.0294486
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[121]	valid_0's binary_logloss: 0.0295409
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[122]	valid_0's binary_logloss: 0.0295689
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[123]	valid_0's binary_logloss: 0.0295832
[124]	valid_0's binary_logloss: 0.0297898
[125]	valid_0's binary_logloss: 0.0299253
[126]	valid_0's binary_logloss: 0.0301454
[127]	valid_0's binary_logloss: 0.0302759
[128]	valid_0's binary_logloss: 0.0303835
[129]	valid_0's binary_logloss: 0.0305608
[130]	valid_0's binary_logloss: 0.03074
[131]	valid_0's binary_logloss: 0.0305576
[132]	valid_0's binary_logloss: 0.0305883
[133]	valid_0's binary_logloss: 0.0307441
[134]	valid_0's binary_logloss: 0.0306899
[135]	valid_0's binary_logloss: 0.0308456
[136]	valid_0's binary_logloss: 0.0305975
[137]	valid_0's binary_logloss: 0.0306287
[138]	valid_0's binary_logloss: 0.0304625
[139]	valid_0's binary_logloss: 0.0305348
[140]	valid_0's binary_logloss: 0.0305287
[141]	valid_0's binary_logloss: 0.0305338
[142]	valid_0's binary_logloss: 0.0306384
[143]	valid_0's binary_logloss: 0.030646
[144]	valid_0's binary_logloss: 0.0305865

Trening klas:  10%|▉         | 48/500 [09:39<1:11:10,  9.45s/klasa, klasa=class_48, F1_klasy=0.9231, F1_macro=0.8970, drzewa=114]




Trening klas:  10%|▉         | 49/500 [09:39<1:04:48,  8.62s/klasa, klasa=class_48, F1_klasy=0.9231, F1_macro=0.8970, drzewa=114]

[1]	valid_0's binary_logloss: 0.228185
[2]	valid_0's binary_logloss: 0.211427
[3]	valid_0's binary_logloss: 0.197361
[4]	valid_0's binary_logloss: 0.18526
[5]	valid_0's binary_logloss: 0.174491
[6]	valid_0's binary_logloss: 0.164819
[7]	valid_0's binary_logloss: 0.15616
[8]	valid_0's binary_logloss: 0.14826
[9]	valid_0's binary_logloss: 0.141018
[10]	valid_0's binary_logloss: 0.134442
[11]	valid_0's binary_logloss: 0.128204
[12]	valid_0's binary_logloss: 0.122495
[13]	valid_0's binary_logloss: 0.117146
[14]	valid_0's binary_logloss: 0.112262
[15]	valid_0's binary_logloss: 0.107652
[16]	valid_0's binary_logloss: 0.103265
[17]	valid_0's binary_logloss: 0.0991844
[18]	valid_0's binary_logloss: 0.0953751
[19]	valid_0's binary_logloss: 0.0918551
[20]	valid_0's binary_logloss: 0.0885696
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0852391
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0822665
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.0795071
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0767717
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.0744568
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.0721391
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.0699875
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.0679704
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.0660598
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.0642916
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.0625829
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.0610467
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.0595482
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.0581902
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.0569449
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.0557867
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.0546321
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.053579
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.0525031
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.0516112
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.0506102
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.0498054
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.0490295
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.0481466
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.0473571
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.0467771
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.0460169
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.0452838
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.0447249
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.0440952
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.0435225
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.0430141
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.0424412
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.0418648
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.0411548
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.0407306
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.0402044
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.0397232
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.0391828
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.0387302
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.0383265
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.0382104
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.0378629
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.0374795
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.0372213
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.0368364
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.0366459
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.0362617
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.0357878
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.0353515
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.0346794
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.0340765
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.033789
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.0335358
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.0329761
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.032815
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.0324997
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.0323831
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.0321569
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.0319506
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.031934
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.031764
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.0316401
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.0313032
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.0312571
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.0311569
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.0310308
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.030953
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.0308142
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.0304968
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.0305213
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.030487
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.030469
[94]	valid_0's binary_logloss: 0.0303116
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.0303182
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.0300109
[97]	valid_0's binary_logloss: 0.0297328
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.0295645
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.0294232
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.0293481
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.0291049
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.0291337
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.0290565
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.0290456
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.0288962
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.0288343
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.0287672
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.0285838
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.0284636
[110]	valid_0's binary_logloss: 0.0283639
[111]	valid_0's binary_logloss: 0.0282735
[112]	valid_0's binary_logloss: 0.0281904
[113]	valid_0's binary_logloss: 0.028244
[114]	valid_0's binary_logloss: 0.028235
[115]	valid_0's binary_logloss: 0.0283953
[116]	valid_0's binary_logloss: 0.0284225
[117]	valid_0's binary_logloss: 0.0284116
[118]	valid_0's binary_logloss: 0.0283325
[119]	valid_0's binary_logloss: 0.0283664
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[120]	valid_0's binary_logloss: 0.0282805
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[121]	valid_0's binary_logloss: 0.0283646
[122]	valid_0's binary_logloss: 0.0284843
[123]	valid_0's binary_logloss: 0.0286159
[124]	valid_0's binary_logloss: 0.0287637
[125]	valid_0's binary_logloss: 0.0287356
[126]	valid_0's binary_logloss: 0.0288453
[127]	valid_0's binary_logloss: 0.0288638
[128]	valid_0's binary_logloss: 0.0290222
[129]	valid_0's binary_logloss: 0.0289837
[130]	valid_0's binary_logloss: 0.0291055
[131]	valid_0's binary_logloss: 0.0291231
[132]	valid_0's binary_logloss: 0.0292714
[133]	valid_0's binary_logloss: 0.0294016
[134]	valid_0's binary_logloss: 0.0294444
[135]	valid_0's binary_logloss: 0.0296309
[136]	valid_0's binary_logloss: 0.0297413
[137]	valid_0's binary_logloss: 0.0295748
[138]	valid_0's binary_logloss: 0.029691
[139]	valid_0's binary_logloss: 0.029736
[140]	valid_0's binary_logloss: 0.0297526
[141]	valid_0's binary_logloss: 0.0296871

Trening klas:  10%|▉         | 49/500 [09:46<1:04:48,  8.62s/klasa, klasa=class_49, F1_klasy=0.9249, F1_macro=0.8976, drzewa=112]




Trening klas:  10%|█         | 50/500 [09:46<59:48,  7.97s/klasa, klasa=class_49, F1_klasy=0.9249, F1_macro=0.8976, drzewa=112]

[142]	valid_0's binary_logloss: 0.0297106
[1]	valid_0's binary_logloss: 0.244342
[2]	valid_0's binary_logloss: 0.228837
[3]	valid_0's binary_logloss: 0.215854
[4]	valid_0's binary_logloss: 0.204895
[5]	valid_0's binary_logloss: 0.194851
[6]	valid_0's binary_logloss: 0.185923
[7]	valid_0's binary_logloss: 0.177864
[8]	valid_0's binary_logloss: 0.170617
[9]	valid_0's binary_logloss: 0.163919
[10]	valid_0's binary_logloss: 0.157432
[11]	valid_0's binary_logloss: 0.151641
[12]	valid_0's binary_logloss: 0.146527
[13]	valid_0's binary_logloss: 0.14145
[14]	valid_0's binary_logloss: 0.13691
[15]	valid_0's binary_logloss: 0.132764
[16]	valid_0's binary_logloss: 0.128728
[17]	valid_0's binary_logloss: 0.124967
[18]	valid_0's binary_logloss: 0.121124
[19]	valid_0's binary_logloss: 0.11777
[20]	valid_0's binary_logloss: 0.114656
[21]	valid_0's binary_logloss: 0.111974
[22]	valid_0's binary_logloss: 0.109175
[23]	valid_0's binary_logloss: 0.106859
[24]	valid_0's binary_logloss: 0.104404
[25]	valid_0's binary_logloss: 0.102146
[26]	valid_0's binary_logloss: 0.0998856
[27]	valid_0's binary_logloss: 0.0980005
[28]	valid_0's binary_logloss: 0.0960321
[29]	valid_0's binary_logloss: 0.0941278
[30]	valid_0's binary_logloss: 0.0924303
[31]	valid_0's binary_logloss: 0.0907355
[32]	valid_0's binary_logloss: 0.089097
[33]	valid_0's binary_logloss: 0.0876622
[34]	valid_0's binary_logloss: 0.0864958
[35]	valid_0's binary_logloss: 0.0852249
[36]	valid_0's binary_logloss: 0.083936
[37]	valid_0's binary_logloss: 0.0827951
[38]	valid_0's binary_logloss: 0.0818704
[39]	valid_0's binary_logloss: 0.080973
[40]	valid_0's binary_logloss: 0.0798291
[41]	valid_0's binary_logloss: 0.0786453
[42]	valid_0's binary_logloss: 0.0778265
[43]	valid_0's binary_logloss: 0.076933
[44]	valid_0's binary_logloss: 0.0760809
[45]	valid_0's binary_logloss: 0.0751579
[46]	valid_0's binary_logloss: 0.0743292
[47]	valid_0's binary_logloss: 0.0736842
[48]	valid_0's binary_logloss: 0.0730957
[49]	valid_0's binary_logloss: 0.0725522
[50]	valid_0's binary_logloss: 0.0720318
[51]	valid_0's binary_logloss: 0.0715288
[52]	valid_0's binary_logloss: 0.0711322
[53]	valid_0's binary_logloss: 0.070658
[54]	valid_0's binary_logloss: 0.0701918
[55]	valid_0's binary_logloss: 0.0697651
[56]	valid_0's binary_logloss: 0.0695397
[57]	valid_0's binary_logloss: 0.069231
[58]	valid_0's binary_logloss: 0.0689147
[59]	valid_0's binary_logloss: 0.0685985
[60]	valid_0's binary_logloss: 0.0684909
[61]	valid_0's binary_logloss: 0.0682059
[62]	valid_0's binary_logloss: 0.0678542
[63]	valid_0's binary_logloss: 0.0675876
[64]	valid_0's binary_logloss: 0.0674119
[65]	valid_0's binary_logloss: 0.0671864
[66]	valid_0's binary_logloss: 0.0669372
[67]	valid_0's binary_logloss: 0.0667421
[68]	valid_0's binary_logloss: 0.0666476
[69]	valid_0's binary_logloss: 0.0664627
[70]	valid_0's binary_logloss: 0.0661518
[71]	valid_0's binary_logloss: 0.0662215
[72]	valid_0's binary_logloss: 0.0662488
[73]	valid_0's binary_logloss: 0.0661239
[74]	valid_0's binary_logloss: 0.0660753
[75]	valid_0's binary_logloss: 0.0659859
[76]	valid_0's binary_logloss: 0.0658625
[77]	valid_0's binary_logloss: 0.0657611
[78]	valid_0's binary_logloss: 0.0657657
[79]	valid_0's binary_logloss: 0.0656895
[80]	valid_0's binary_logloss: 0.0656891
[81]	valid_0's binary_logloss: 0.0656466
[82]	valid_0's binary_logloss: 0.0655797
[83]	valid_0's binary_logloss: 0.0656057
[84]	valid_0's binary_logloss: 0.0656039
[85]	valid_0's binary_logloss: 0.0655416
[86]	valid_0's binary_logloss: 0.0655837
[87]	valid_0's binary_logloss: 0.0656746
[88]	valid_0's binary_logloss: 0.0656246
[89]	valid_0's binary_logloss: 0.0654575
[90]	valid_0's binary_logloss: 0.0653618
[91]	valid_0's binary_logloss: 0.065106
[92]	valid_0's binary_logloss: 0.0650333
[93]	valid_0's binary_logloss: 0.0649746
[94]	valid_0's binary_logloss: 0.0648866
[95]	valid_0's binary_logloss: 0.064688
[96]	valid_0's binary_logloss: 0.0645966
[97]	valid_0's binary_logloss: 0.0645305
[98]	valid_0's binary_logloss: 0.0647056
[99]	valid_0's binary_logloss: 0.0647114
[100]	valid_0's binary_logloss: 0.0647974
[101]	valid_0's binary_logloss: 0.0649084
[102]	valid_0's binary_logloss: 0.0649908
[103]	valid_0's binary_logloss: 0.0651246
[104]	valid_0's binary_logloss: 0.0652754
[105]	valid_0's binary_logloss: 0.0652553
[106]	valid_0's binary_logloss: 0.0655321
[107]	valid_0's binary_logloss: 0.0657571
[108]	valid_0's binary_logloss: 0.0660575
[109]	valid_0's binary_logloss: 0.0660781
[110]	valid_0's binary_logloss: 0.0660976
[111]	valid_0's binary_logloss: 0.0660963
[112]	valid_0's binary_logloss: 0.0661602
[113]	valid_0's binary_logloss: 0.0662714
[114]	valid_0's binary_logloss: 0.0663295
[115]	valid_0's binary_logloss: 0.066376
[116]	valid_0's binary_logloss: 0.0664102
[117]	valid_0's binary_logloss: 0.0664492
[118]	valid_0's binary_logloss: 0.0663439
[119]	valid_0's binary_logloss: 0.0664596
[120]	valid_0's binary_logloss: 0.0664796
[121]	valid_0's binary_logloss: 0.0664249
[122]	valid_0's binary_logloss: 0.0665144
[123]	valid_0's binary_logloss: 0.0667464
[124]	valid_0's binary_logloss: 0.0667946
[125]	valid_0's binary_logloss: 0.0667679
[126]	valid_0's binary_logloss: 0.0668438

Trening klas:  10%|█         | 50/500 [09:56<59:48,  7.97s/klasa, klasa=class_50, F1_klasy=0.8196, F1_macro=0.8961, drzewa=97]




Trening klas:  10%|█         | 51/500 [09:56<1:03:21,  8.47s/klasa, klasa=class_50, F1_klasy=0.8196, F1_macro=0.8961, drzewa=97]

[127]	valid_0's binary_logloss: 0.0669252
[1]	valid_0's binary_logloss: 0.244274
[2]	valid_0's binary_logloss: 0.228855
[3]	valid_0's binary_logloss: 0.21571
[4]	valid_0's binary_logloss: 0.205063
[5]	valid_0's binary_logloss: 0.194999
[6]	valid_0's binary_logloss: 0.186093
[7]	valid_0's binary_logloss: 0.178036
[8]	valid_0's binary_logloss: 0.170628
[9]	valid_0's binary_logloss: 0.164047
[10]	valid_0's binary_logloss: 0.157739
[11]	valid_0's binary_logloss: 0.151952
[12]	valid_0's binary_logloss: 0.146773
[13]	valid_0's binary_logloss: 0.141598
[14]	valid_0's binary_logloss: 0.137042
[15]	valid_0's binary_logloss: 0.132734
[16]	valid_0's binary_logloss: 0.128492
[17]	valid_0's binary_logloss: 0.124583
[18]	valid_0's binary_logloss: 0.120867
[19]	valid_0's binary_logloss: 0.117314
[20]	valid_0's binary_logloss: 0.114215
[21]	valid_0's binary_logloss: 0.111227
[22]	valid_0's binary_logloss: 0.108491
[23]	valid_0's binary_logloss: 0.1059
[24]	valid_0's binary_logloss: 0.103433
[25]	valid_0's binary_logloss: 0.101143
[26]	valid_0's binary_logloss: 0.0992129
[27]	valid_0's binary_logloss: 0.0974967
[28]	valid_0's binary_logloss: 0.0955535
[29]	valid_0's binary_logloss: 0.0937343
[30]	valid_0's binary_logloss: 0.0919972
[31]	valid_0's binary_logloss: 0.0903464
[32]	valid_0's binary_logloss: 0.0888656
[33]	valid_0's binary_logloss: 0.087376
[34]	valid_0's binary_logloss: 0.0861236
[35]	valid_0's binary_logloss: 0.0848514
[36]	valid_0's binary_logloss: 0.0837149
[37]	valid_0's binary_logloss: 0.0825288
[38]	valid_0's binary_logloss: 0.0814606
[39]	valid_0's binary_logloss: 0.0805867
[40]	valid_0's binary_logloss: 0.079621
[41]	valid_0's binary_logloss: 0.0785927
[42]	valid_0's binary_logloss: 0.0775472
[43]	valid_0's binary_logloss: 0.0767512
[44]	valid_0's binary_logloss: 0.0760597
[45]	valid_0's binary_logloss: 0.0752557
[46]	valid_0's binary_logloss: 0.0745847
[47]	valid_0's binary_logloss: 0.0739278
[48]	valid_0's binary_logloss: 0.0733815
[49]	valid_0's binary_logloss: 0.0728117
[50]	valid_0's binary_logloss: 0.0724049
[51]	valid_0's binary_logloss: 0.0719669
[52]	valid_0's binary_logloss: 0.0715978
[53]	valid_0's binary_logloss: 0.0712883
[54]	valid_0's binary_logloss: 0.0708829
[55]	valid_0's binary_logloss: 0.0704594
[56]	valid_0's binary_logloss: 0.070304
[57]	valid_0's binary_logloss: 0.0698183
[58]	valid_0's binary_logloss: 0.0693554
[59]	valid_0's binary_logloss: 0.0690063
[60]	valid_0's binary_logloss: 0.0689131
[61]	valid_0's binary_logloss: 0.0686801
[62]	valid_0's binary_logloss: 0.0683548
[63]	valid_0's binary_logloss: 0.0680172
[64]	valid_0's binary_logloss: 0.0678099
[65]	valid_0's binary_logloss: 0.067543
[66]	valid_0's binary_logloss: 0.0672803
[67]	valid_0's binary_logloss: 0.0671823
[68]	valid_0's binary_logloss: 0.0669536
[69]	valid_0's binary_logloss: 0.0667944
[70]	valid_0's binary_logloss: 0.0665363
[71]	valid_0's binary_logloss: 0.0663953
[72]	valid_0's binary_logloss: 0.0663711
[73]	valid_0's binary_logloss: 0.0664902
[74]	valid_0's binary_logloss: 0.0663816
[75]	valid_0's binary_logloss: 0.0662585
[76]	valid_0's binary_logloss: 0.0661559
[77]	valid_0's binary_logloss: 0.0661089
[78]	valid_0's binary_logloss: 0.0658638
[79]	valid_0's binary_logloss: 0.0658272
[80]	valid_0's binary_logloss: 0.0657867
[81]	valid_0's binary_logloss: 0.0657138
[82]	valid_0's binary_logloss: 0.0656969
[83]	valid_0's binary_logloss: 0.0657445
[84]	valid_0's binary_logloss: 0.0656024
[85]	valid_0's binary_logloss: 0.0654687
[86]	valid_0's binary_logloss: 0.0655355
[87]	valid_0's binary_logloss: 0.0655446
[88]	valid_0's binary_logloss: 0.065622
[89]	valid_0's binary_logloss: 0.065502
[90]	valid_0's binary_logloss: 0.0656355
[91]	valid_0's binary_logloss: 0.0654737
[92]	valid_0's binary_logloss: 0.0652465
[93]	valid_0's binary_logloss: 0.0651579
[94]	valid_0's binary_logloss: 0.0650027
[95]	valid_0's binary_logloss: 0.0649901
[96]	valid_0's binary_logloss: 0.0650232
[97]	valid_0's binary_logloss: 0.0649461
[98]	valid_0's binary_logloss: 0.064995
[99]	valid_0's binary_logloss: 0.0650786
[100]	valid_0's binary_logloss: 0.0651908
[101]	valid_0's binary_logloss: 0.0652033
[102]	valid_0's binary_logloss: 0.0652234
[103]	valid_0's binary_logloss: 0.0653239
[104]	valid_0's binary_logloss: 0.06553
[105]	valid_0's binary_logloss: 0.0655336
[106]	valid_0's binary_logloss: 0.0655644
[107]	valid_0's binary_logloss: 0.0657449
[108]	valid_0's binary_logloss: 0.0657718
[109]	valid_0's binary_logloss: 0.0658738
[110]	valid_0's binary_logloss: 0.0659119
[111]	valid_0's binary_logloss: 0.0659757
[112]	valid_0's binary_logloss: 0.0661007
[113]	valid_0's binary_logloss: 0.0661206
[114]	valid_0's binary_logloss: 0.066117
[115]	valid_0's binary_logloss: 0.0661047
[116]	valid_0's binary_logloss: 0.0661494
[117]	valid_0's binary_logloss: 0.0662674
[118]	valid_0's binary_logloss: 0.0663686
[119]	valid_0's binary_logloss: 0.0664654
[120]	valid_0's binary_logloss: 0.0664228
[121]	valid_0's binary_logloss: 0.0664944
[122]	valid_0's binary_logloss: 0.0666245
[123]	valid_0's binary_logloss: 0.0667261
[124]	valid_0's binary_logloss: 0.066826
[125]	valid_0's binary_logloss: 0.0667827
[126]	valid_0's binary_logloss: 0.0668727
[127]	valid_0's binary_logloss: 0.0668739

Trening klas:  10%|█         | 51/500 [10:05<1:03:21,  8.47s/klasa, klasa=class_51, F1_klasy=0.8159, F1_macro=0.8945, drzewa=97]




Trening klas:  10%|█         | 52/500 [10:05<1:05:49,  8.82s/klasa, klasa=class_51, F1_klasy=0.8159, F1_macro=0.8945, drzewa=97]

[1]	valid_0's binary_logloss: 0.226184
[2]	valid_0's binary_logloss: 0.209653
[3]	valid_0's binary_logloss: 0.195798
[4]	valid_0's binary_logloss: 0.183903
[5]	valid_0's binary_logloss: 0.173283
[6]	valid_0's binary_logloss: 0.163825
[7]	valid_0's binary_logloss: 0.155261
[8]	valid_0's binary_logloss: 0.147443
[9]	valid_0's binary_logloss: 0.140292
[10]	valid_0's binary_logloss: 0.133745
[11]	valid_0's binary_logloss: 0.127595
[12]	valid_0's binary_logloss: 0.121928
[13]	valid_0's binary_logloss: 0.116688
[14]	valid_0's binary_logloss: 0.111849
[15]	valid_0's binary_logloss: 0.107339
[16]	valid_0's binary_logloss: 0.103211
[17]	valid_0's binary_logloss: 0.0991924
[18]	valid_0's binary_logloss: 0.0955741
[19]	valid_0's binary_logloss: 0.092175
[20]	valid_0's binary_logloss: 0.0889582
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0859823
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0832238
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.0806591
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0781311
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.0758797
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.0738657
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.0717486
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.0697455
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.0678788
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.0661334
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.0644778
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.0630234
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.0615686
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.0602005
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.0589408
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.0579269
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.0570061
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.0560007
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.0550866
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.0542045
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.0532199
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.0524488
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.0516638
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.0507836
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.0500136
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.0493518
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.0487178
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.0481175
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.0475497
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.0470837
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.0464926
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.0459244
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.0452832
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.0447531
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.0442682
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.0436677
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.0431195
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.0424953
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.0416305
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.0411086
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.0407572
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.0406464
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.0403025
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.0399997
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.0397018
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.0393113
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.0389188
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.0386672
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.0382147
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.0378249
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.0372805
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.0368227
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.0366861
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.0366141
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.036164
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.0359245
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.0355761
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.0354086
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.0352584
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.0348271
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.034807
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.0346164
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.0343482
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.0338726
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.0337175
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.033448
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.0331131
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.0327659
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.0325693
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.0322815
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.0320624
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.0316993
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.0313756
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.0314815
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.0311757
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.030953
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.0308103
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.0304493
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.0303805
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.030275
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.0301409
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.0300574
[103]	valid_0's binary_logloss: 0.0300686
[104]	valid_0's binary_logloss: 0.0302097
[105]	valid_0's binary_logloss: 0.0301958
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.0301798
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.0301877
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.0300279
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.0299575
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.029796
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.0295955
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 0.029547
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 0.0296897
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 0.0296311
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 0.0297384
[116]	valid_0's binary_logloss: 0.0298012
[117]	valid_0's binary_logloss: 0.0297527
[118]	valid_0's binary_logloss: 0.0296032
[119]	valid_0's binary_logloss: 0.029575
[120]	valid_0's binary_logloss: 0.0295772
[121]	valid_0's binary_logloss: 0.0296719
[122]	valid_0's binary_logloss: 0.0298488
[123]	valid_0's binary_logloss: 0.0299202
[124]	valid_0's binary_logloss: 0.0300976
[125]	valid_0's binary_logloss: 0.0302414
[126]	valid_0's binary_logloss: 0.0302038
[127]	valid_0's binary_logloss: 0.0302488
[128]	valid_0's binary_logloss: 0.0302542
[129]	valid_0's binary_logloss: 0.0302129
[130]	valid_0's binary_logloss: 0.0303126
[131]	valid_0's binary_logloss: 0.030325
[132]	valid_0's binary_logloss: 0.030465
[133]	valid_0's binary_logloss: 0.0306448
[134]	valid_0's binary_logloss: 0.0306764
[135]	valid_0's binary_logloss: 0.0307832
[136]	valid_0's binary_logloss: 0.0308249
[137]	valid_0's binary_logloss: 0.0307283
[138]	valid_0's binary_logloss: 0.030753
[139]	valid_0's binary_logloss: 0.0309303
[140]	valid_0's binary_logloss: 0.0309878

Trening klas:  10%|█         | 52/500 [10:12<1:05:49,  8.82s/klasa, klasa=class_52, F1_klasy=0.9243, F1_macro=0.8951, drzewa=112]




Trening klas:  11%|█         | 53/500 [10:12<1:01:06,  8.20s/klasa, klasa=class_52, F1_klasy=0.9243, F1_macro=0.8951, drzewa=112]

[141]	valid_0's binary_logloss: 0.0310202
[142]	valid_0's binary_logloss: 0.0311131
[1]	valid_0's binary_logloss: 0.378831
[2]	valid_0's binary_logloss: 0.347077
[3]	valid_0's binary_logloss: 0.322284
[4]	valid_0's binary_logloss: 0.303812
[5]	valid_0's binary_logloss: 0.288505
[6]	valid_0's binary_logloss: 0.274914
[7]	valid_0's binary_logloss: 0.26371
[8]	valid_0's binary_logloss: 0.253617
[9]	valid_0's binary_logloss: 0.244637
[10]	valid_0's binary_logloss: 0.237269
[11]	valid_0's binary_logloss: 0.230131
[12]	valid_0's binary_logloss: 0.2232
[13]	valid_0's binary_logloss: 0.217301
[14]	valid_0's binary_logloss: 0.21181
[15]	valid_0's binary_logloss: 0.207057
[16]	valid_0's binary_logloss: 0.202802
[17]	valid_0's binary_logloss: 0.199101
[18]	valid_0's binary_logloss: 0.195779
[19]	valid_0's binary_logloss: 0.192586
[20]	valid_0's binary_logloss: 0.190076
[21]	valid_0's binary_logloss: 0.187154
[22]	valid_0's binary_logloss: 0.18432
[23]	valid_0's binary_logloss: 0.182558
[24]	valid_0's binary_logloss: 0.180008
[25]	valid_0's binary_logloss: 0.177792
[26]	valid_0's binary_logloss: 0.176026
[27]	valid_0's binary_logloss: 0.174619
[28]	valid_0's binary_logloss: 0.173316
[29]	valid_0's binary_logloss: 0.172219
[30]	valid_0's binary_logloss: 0.171186
[31]	valid_0's binary_logloss: 0.170069
[32]	valid_0's binary_logloss: 0.168081
[33]	valid_0's binary_logloss: 0.167395
[34]	valid_0's binary_logloss: 0.166704
[35]	valid_0's binary_logloss: 0.166069
[36]	valid_0's binary_logloss: 0.165655
[37]	valid_0's binary_logloss: 0.164535
[38]	valid_0's binary_logloss: 0.164169
[39]	valid_0's binary_logloss: 0.163733
[40]	valid_0's binary_logloss: 0.16335
[41]	valid_0's binary_logloss: 0.162909
[42]	valid_0's binary_logloss: 0.161888
[43]	valid_0's binary_logloss: 0.16063
[44]	valid_0's binary_logloss: 0.159162
[45]	valid_0's binary_logloss: 0.158179
[46]	valid_0's binary_logloss: 0.15711
[47]	valid_0's binary_logloss: 0.156601
[48]	valid_0's binary_logloss: 0.155813
[49]	valid_0's binary_logloss: 0.155179
[50]	valid_0's binary_logloss: 0.154371
[51]	valid_0's binary_logloss: 0.15424
[52]	valid_0's binary_logloss: 0.15396
[53]	valid_0's binary_logloss: 0.153299
[54]	valid_0's binary_logloss: 0.152955
[55]	valid_0's binary_logloss: 0.152659
[56]	valid_0's binary_logloss: 0.152499
[57]	valid_0's binary_logloss: 0.152037
[58]	valid_0's binary_logloss: 0.150989
[59]	valid_0's binary_logloss: 0.150758
[60]	valid_0's binary_logloss: 0.15029
[61]	valid_0's binary_logloss: 0.150066
[62]	valid_0's binary_logloss: 0.149928
[63]	valid_0's binary_logloss: 0.149741
[64]	valid_0's binary_logloss: 0.149101
[65]	valid_0's binary_logloss: 0.148882
[66]	valid_0's binary_logloss: 0.148577
[67]	valid_0's binary_logloss: 0.147994
[68]	valid_0's binary_logloss: 0.147704
[69]	valid_0's binary_logloss: 0.147453
[70]	valid_0's binary_logloss: 0.146984
[71]	valid_0's binary_logloss: 0.146824
[72]	valid_0's binary_logloss: 0.146965
[73]	valid_0's binary_logloss: 0.146593
[74]	valid_0's binary_logloss: 0.146793
[75]	valid_0's binary_logloss: 0.146741
[76]	valid_0's binary_logloss: 0.146553
[77]	valid_0's binary_logloss: 0.146349
[78]	valid_0's binary_logloss: 0.146339
[79]	valid_0's binary_logloss: 0.146082
[80]	valid_0's binary_logloss: 0.145958
[81]	valid_0's binary_logloss: 0.14577
[82]	valid_0's binary_logloss: 0.14529
[83]	valid_0's binary_logloss: 0.144862
[84]	valid_0's binary_logloss: 0.144516
[85]	valid_0's binary_logloss: 0.143928
[86]	valid_0's binary_logloss: 0.144149
[87]	valid_0's binary_logloss: 0.144469
[88]	valid_0's binary_logloss: 0.144616
[89]	valid_0's binary_logloss: 0.14497
[90]	valid_0's binary_logloss: 0.144886
[91]	valid_0's binary_logloss: 0.144468
[92]	valid_0's binary_logloss: 0.144454
[93]	valid_0's binary_logloss: 0.14405
[94]	valid_0's binary_logloss: 0.144031
[95]	valid_0's binary_logloss: 0.144321
[96]	valid_0's binary_logloss: 0.143822
[97]	valid_0's binary_logloss: 0.143355
[98]	valid_0's binary_logloss: 0.142846
[99]	valid_0's binary_logloss: 0.142359
[100]	valid_0's binary_logloss: 0.141956
[101]	valid_0's binary_logloss: 0.142347
[102]	valid_0's binary_logloss: 0.142602
[103]	valid_0's binary_logloss: 0.142655
[104]	valid_0's binary_logloss: 0.142704
[105]	valid_0's binary_logloss: 0.142555
[106]	valid_0's binary_logloss: 0.142229
[107]	valid_0's binary_logloss: 0.142053
[108]	valid_0's binary_logloss: 0.142207
[109]	valid_0's binary_logloss: 0.142284
[110]	valid_0's binary_logloss: 0.142385
[111]	valid_0's binary_logloss: 0.142229
[112]	valid_0's binary_logloss: 0.141992
[113]	valid_0's binary_logloss: 0.1419
[114]	valid_0's binary_logloss: 0.141606
[115]	valid_0's binary_logloss: 0.141329
[116]	valid_0's binary_logloss: 0.141499
[117]	valid_0's binary_logloss: 0.141209
[118]	valid_0's binary_logloss: 0.141389
[119]	valid_0's binary_logloss: 0.141503
[120]	valid_0's binary_logloss: 0.141552
[121]	valid_0's binary_logloss: 0.141352
[122]	valid_0's binary_logloss: 0.141475
[123]	valid_0's binary_logloss: 0.141603
[124]	valid_0's binary_logloss: 0.141258
[125]	valid_0's binary_logloss: 0.141229
[126]	valid_0's binary_logloss: 0.141216
[127]	valid_0's binary_logloss: 0.141226
[128]	valid_0's binary_logloss: 0.14108
[129]	valid_0's binary_logloss: 0.141292
[130]	valid_0's binary_logloss: 0.141045
[131]	valid_0's binary_logloss: 0.141019
[132]	valid_0's binary_logloss: 0.140921
[133]	valid_0's binary_logloss: 0.14106
[134]	valid_0's binary_logloss: 0.141169
[135]	valid_0's binary_logloss: 0.140833
[136]	valid_0's binary_logloss: 0.140568
[137]	valid_0's binary_logloss: 0.140033
[138]	valid_0's binary_logloss: 0.139911
[139]	valid_0's binary_logloss: 0.139555
[140]	valid_0's binary_logloss: 0.139424
[141]	valid_0's binary_logloss: 0.139471
[142]	valid_0's binary_logloss: 0.13947
[143]	valid_0's binary_logloss: 0.139623
[144]	valid_0's binary_logloss: 0.139661
[145]	valid_0's binary_logloss: 0.139734
[146]	valid_0's binary_logloss: 0.139966
[147]	valid_0's binary_logloss: 0.139803
[148]	valid_0's binary_logloss: 0.139716
[149]	valid_0's binary_logloss: 0.139413
[150]	valid_0's binary_logloss: 0.139179
[151]	valid_0's binary_logloss: 0.138927
[152]	valid_0's binary_logloss: 0.138841
[153]	valid_0's binary_logloss: 0.138835
[154]	valid_0's binary_logloss: 0.138747
[155]	valid_0's binary_logloss: 0.138579
[156]	valid_0's binary_logloss: 0.138815
[157]	valid_0's binary_logloss: 0.138853
[158]	valid_0's binary_logloss: 0.138819
[159]	valid_0's binary_logloss: 0.138724
[160]	valid_0's binary_logloss: 0.138827
[161]	valid_0's binary_logloss: 0.138699
[162]	valid_0's binary_logloss: 0.138316
[163]	valid_0's binary_logloss: 0.138128
[164]	valid_0's binary_logloss: 0.138065
[165]	valid_0's binary_logloss: 0.137982
[166]	valid_0's binary_logloss: 0.138083
[167]	valid_0's binary_logloss: 0.138197
[168]	valid_0's binary_logloss: 0.138112
[169]	valid_0's binary_logloss: 0.138375
[170]	valid_0's binary_logloss: 0.138328
[171]	valid_0's binary_logloss: 0.138625
[172]	valid_0's binary_logloss: 0.138676
[173]	valid_0's binary_logloss: 0.13859
[174]	valid_0's binary_logloss: 0.138692
[175]	valid_0's binary_logloss: 0.138773
[176]	valid_0's binary_logloss: 0.13876
[177]	valid_0's binary_logloss: 0.138851
[178]	valid_0's binary_logloss: 0.139005
[179]	valid_0's binary_logloss: 0.139039
[180]	valid_0's binary_logloss: 0.138987
[181]	valid_0's binary_logloss: 0.13884
[182]	valid_0's binary_logloss: 0.138901
[183]	valid_0's binary_logloss: 0.138903
[184]	valid_0's binary_logloss: 0.138676
[185]	valid_0's binary_logloss: 0.138906
[186]	valid_0's binary_logloss: 0.138937
[187]	valid_0's binary_logloss: 0.138834
[188]	valid_0's binary_logloss: 0.13891
[189]	valid_0's binary_logloss: 0.138815
[190]	valid_0's binary_logloss: 0.13881
[191]	valid_0's binary_logloss: 0.138808
[192]	valid_0's binary_logloss: 0.139099
[193]	valid_0's binary_logloss: 0.139296

Trening klas:  11%|█         | 53/500 [10:26<1:01:06,  8.20s/klasa, klasa=class_53, F1_klasy=0.8245, F1_macro=0.8938, drzewa=165]




Trening klas:  11%|█         | 54/500 [10:26<1:13:16,  9.86s/klasa, klasa=class_53, F1_klasy=0.8245, F1_macro=0.8938, drzewa=165]

[194]	valid_0's binary_logloss: 0.139419
[195]	valid_0's binary_logloss: 0.139436
[1]	valid_0's binary_logloss: 0.212739
[2]	valid_0's binary_logloss: 0.199857
[3]	valid_0's binary_logloss: 0.188885
[4]	valid_0's binary_logloss: 0.179186
[5]	valid_0's binary_logloss: 0.17123
[6]	valid_0's binary_logloss: 0.163587
[7]	valid_0's binary_logloss: 0.156626
[8]	valid_0's binary_logloss: 0.150504
[9]	valid_0's binary_logloss: 0.144388
[10]	valid_0's binary_logloss: 0.138913
[11]	valid_0's binary_logloss: 0.133825
[12]	valid_0's binary_logloss: 0.129029
[13]	valid_0's binary_logloss: 0.124633
[14]	valid_0's binary_logloss: 0.120716
[15]	valid_0's binary_logloss: 0.11693
[16]	valid_0's binary_logloss: 0.113213
[17]	valid_0's binary_logloss: 0.109775
[18]	valid_0's binary_logloss: 0.106534
[19]	valid_0's binary_logloss: 0.103779
[20]	valid_0's binary_logloss: 0.100991
[21]	valid_0's binary_logloss: 0.0981194
[22]	valid_0's binary_logloss: 0.0955828
[23]	valid_0's binary_logloss: 0.093123
[24]	valid_0's binary_logloss: 0.090645
[25]	valid_0's binary_logloss: 0.0884766
[26]	valid_0's binary_logloss: 0.0863172
[27]	valid_0's binary_logloss: 0.0844261
[28]	valid_0's binary_logloss: 0.0829991
[29]	valid_0's binary_logloss: 0.0814919
[30]	valid_0's binary_logloss: 0.0798745
[31]	valid_0's binary_logloss: 0.0783227
[32]	valid_0's binary_logloss: 0.0770576
[33]	valid_0's binary_logloss: 0.0758469
[34]	valid_0's binary_logloss: 0.0745189
[35]	valid_0's binary_logloss: 0.0733099
[36]	valid_0's binary_logloss: 0.0720644
[37]	valid_0's binary_logloss: 0.0710926
[38]	valid_0's binary_logloss: 0.0702374
[39]	valid_0's binary_logloss: 0.0691717
[40]	valid_0's binary_logloss: 0.0682733
[41]	valid_0's binary_logloss: 0.0673235
[42]	valid_0's binary_logloss: 0.0663666
[43]	valid_0's binary_logloss: 0.0655193
[44]	valid_0's binary_logloss: 0.0646951
[45]	valid_0's binary_logloss: 0.0639606
[46]	valid_0's binary_logloss: 0.0633435
[47]	valid_0's binary_logloss: 0.0626764
[48]	valid_0's binary_logloss: 0.0619803
[49]	valid_0's binary_logloss: 0.0613223
[50]	valid_0's binary_logloss: 0.0606243
[51]	valid_0's binary_logloss: 0.0599957
[52]	valid_0's binary_logloss: 0.0593941
[53]	valid_0's binary_logloss: 0.0588414
[54]	valid_0's binary_logloss: 0.0583034
[55]	valid_0's binary_logloss: 0.0579431
[56]	valid_0's binary_logloss: 0.0574547
[57]	valid_0's binary_logloss: 0.0570784
[58]	valid_0's binary_logloss: 0.0566662
[59]	valid_0's binary_logloss: 0.0561938
[60]	valid_0's binary_logloss: 0.0558513
[61]	valid_0's binary_logloss: 0.0555168
[62]	valid_0's binary_logloss: 0.0550846
[63]	valid_0's binary_logloss: 0.0548046
[64]	valid_0's binary_logloss: 0.0543389
[65]	valid_0's binary_logloss: 0.054197
[66]	valid_0's binary_logloss: 0.0538108
[67]	valid_0's binary_logloss: 0.053506
[68]	valid_0's binary_logloss: 0.053102
[69]	valid_0's binary_logloss: 0.0528031
[70]	valid_0's binary_logloss: 0.0525035
[71]	valid_0's binary_logloss: 0.0521346
[72]	valid_0's binary_logloss: 0.0518888
[73]	valid_0's binary_logloss: 0.0516653
[74]	valid_0's binary_logloss: 0.0514363
[75]	valid_0's binary_logloss: 0.0514304
[76]	valid_0's binary_logloss: 0.0512596
[77]	valid_0's binary_logloss: 0.0510006
[78]	valid_0's binary_logloss: 0.0509786
[79]	valid_0's binary_logloss: 0.0507599
[80]	valid_0's binary_logloss: 0.0506263
[81]	valid_0's binary_logloss: 0.0505407
[82]	valid_0's binary_logloss: 0.0504043
[83]	valid_0's binary_logloss: 0.0502215
[84]	valid_0's binary_logloss: 0.0501302
[85]	valid_0's binary_logloss: 0.0499737
[86]	valid_0's binary_logloss: 0.0499351
[87]	valid_0's binary_logloss: 0.0499222
[88]	valid_0's binary_logloss: 0.0498265
[89]	valid_0's binary_logloss: 0.0497759
[90]	valid_0's binary_logloss: 0.049684
[91]	valid_0's binary_logloss: 0.0495608
[92]	valid_0's binary_logloss: 0.0495256
[93]	valid_0's binary_logloss: 0.0494475
[94]	valid_0's binary_logloss: 0.0493934
[95]	valid_0's binary_logloss: 0.0493714
[96]	valid_0's binary_logloss: 0.0494346
[97]	valid_0's binary_logloss: 0.0493489
[98]	valid_0's binary_logloss: 0.0492243
[99]	valid_0's binary_logloss: 0.0491426
[100]	valid_0's binary_logloss: 0.0490497
[101]	valid_0's binary_logloss: 0.0488793
[102]	valid_0's binary_logloss: 0.0488447
[103]	valid_0's binary_logloss: 0.0488954
[104]	valid_0's binary_logloss: 0.0489054
[105]	valid_0's binary_logloss: 0.0489079
[106]	valid_0's binary_logloss: 0.0489142
[107]	valid_0's binary_logloss: 0.048941
[108]	valid_0's binary_logloss: 0.049092
[109]	valid_0's binary_logloss: 0.0491493
[110]	valid_0's binary_logloss: 0.0490987
[111]	valid_0's binary_logloss: 0.0490597
[112]	valid_0's binary_logloss: 0.0490197
[113]	valid_0's binary_logloss: 0.0489998
[114]	valid_0's binary_logloss: 0.0490276
[115]	valid_0's binary_logloss: 0.0490489
[116]	valid_0's binary_logloss: 0.0489756
[117]	valid_0's binary_logloss: 0.0489283
[118]	valid_0's binary_logloss: 0.0489029
[119]	valid_0's binary_logloss: 0.0489061
[120]	valid_0's binary_logloss: 0.0488306
[121]	valid_0's binary_logloss: 0.0489059
[122]	valid_0's binary_logloss: 0.0489659
[123]	valid_0's binary_logloss: 0.0488048
[124]	valid_0's binary_logloss: 0.0487755
[125]	valid_0's binary_logloss: 0.0486677
[126]	valid_0's binary_logloss: 0.0487665
[127]	valid_0's binary_logloss: 0.048744
[128]	valid_0's binary_logloss: 0.0488187
[129]	valid_0's binary_logloss: 0.0488892
[130]	valid_0's binary_logloss: 0.0489861
[131]	valid_0's binary_logloss: 0.0489376
[132]	valid_0's binary_logloss: 0.0489563
[133]	valid_0's binary_logloss: 0.0489095
[134]	valid_0's binary_logloss: 0.0488984
[135]	valid_0's binary_logloss: 0.0489663
[136]	valid_0's binary_logloss: 0.0489944
[137]	valid_0's binary_logloss: 0.0490278
[138]	valid_0's binary_logloss: 0.048992
[139]	valid_0's binary_logloss: 0.0489558
[140]	valid_0's binary_logloss: 0.0490054
[141]	valid_0's binary_logloss: 0.0489441
[142]	valid_0's binary_logloss: 0.048939
[143]	valid_0's binary_logloss: 0.0489477
[144]	valid_0's binary_logloss: 0.0489505
[145]	valid_0's binary_logloss: 0.0490118
[146]	valid_0's binary_logloss: 0.0490546
[147]	valid_0's binary_logloss: 0.049079
[148]	valid_0's binary_logloss: 0.0490688
[149]	valid_0's binary_logloss: 0.0490967
[150]	valid_0's binary_logloss: 0.049087
[151]	valid_0's binary_logloss: 0.0489455
[152]	valid_0's binary_logloss: 0.0489188
[153]	valid_0's binary_logloss: 0.0488612
[154]	valid_0's binary_logloss: 0.0488481
[155]	valid_0's binary_logloss: 0.0488805

Trening klas:  11%|█         | 54/500 [10:36<1:13:16,  9.86s/klasa, klasa=class_54, F1_klasy=0.7969, F1_macro=0.8920, drzewa=125]




Trening klas:  11%|█         | 55/500 [10:36<1:14:41, 10.07s/klasa, klasa=class_54, F1_klasy=0.7969, F1_macro=0.8920, drzewa=125]

[1]	valid_0's binary_logloss: 0.37242
[2]	valid_0's binary_logloss: 0.347904
[3]	valid_0's binary_logloss: 0.329397
[4]	valid_0's binary_logloss: 0.31469
[5]	valid_0's binary_logloss: 0.303438
[6]	valid_0's binary_logloss: 0.294456
[7]	valid_0's binary_logloss: 0.286105
[8]	valid_0's binary_logloss: 0.280097
[9]	valid_0's binary_logloss: 0.274459
[10]	valid_0's binary_logloss: 0.269554
[11]	valid_0's binary_logloss: 0.264805
[12]	valid_0's binary_logloss: 0.261075
[13]	valid_0's binary_logloss: 0.258386
[14]	valid_0's binary_logloss: 0.255706
[15]	valid_0's binary_logloss: 0.253211
[16]	valid_0's binary_logloss: 0.25027
[17]	valid_0's binary_logloss: 0.248048
[18]	valid_0's binary_logloss: 0.245746
[19]	valid_0's binary_logloss: 0.243891
[20]	valid_0's binary_logloss: 0.242267
[21]	valid_0's binary_logloss: 0.240834
[22]	valid_0's binary_logloss: 0.238759
[23]	valid_0's binary_logloss: 0.238
[24]	valid_0's binary_logloss: 0.23698
[25]	valid_0's binary_logloss: 0.235163
[26]	valid_0's binary_logloss: 0.23394
[27]	valid_0's binary_logloss: 0.233179
[28]	valid_0's binary_logloss: 0.231997
[29]	valid_0's binary_logloss: 0.23108
[30]	valid_0's binary_logloss: 0.230236
[31]	valid_0's binary_logloss: 0.228884
[32]	valid_0's binary_logloss: 0.228168
[33]	valid_0's binary_logloss: 0.227661
[34]	valid_0's binary_logloss: 0.226294
[35]	valid_0's binary_logloss: 0.22496
[36]	valid_0's binary_logloss: 0.224398
[37]	valid_0's binary_logloss: 0.223867
[38]	valid_0's binary_logloss: 0.223543
[39]	valid_0's binary_logloss: 0.223015
[40]	valid_0's binary_logloss: 0.222507
[41]	valid_0's binary_logloss: 0.222189
[42]	valid_0's binary_logloss: 0.221775
[43]	valid_0's binary_logloss: 0.221032
[44]	valid_0's binary_logloss: 0.220826
[45]	valid_0's binary_logloss: 0.220315
[46]	valid_0's binary_logloss: 0.220169
[47]	valid_0's binary_logloss: 0.219433
[48]	valid_0's binary_logloss: 0.219234
[49]	valid_0's binary_logloss: 0.218905
[50]	valid_0's binary_logloss: 0.218431
[51]	valid_0's binary_logloss: 0.217576
[52]	valid_0's binary_logloss: 0.217008
[53]	valid_0's binary_logloss: 0.216436
[54]	valid_0's binary_logloss: 0.215646
[55]	valid_0's binary_logloss: 0.215449
[56]	valid_0's binary_logloss: 0.2154
[57]	valid_0's binary_logloss: 0.215325
[58]	valid_0's binary_logloss: 0.215555
[59]	valid_0's binary_logloss: 0.215746
[60]	valid_0's binary_logloss: 0.215888
[61]	valid_0's binary_logloss: 0.215516
[62]	valid_0's binary_logloss: 0.215321
[63]	valid_0's binary_logloss: 0.215341
[64]	valid_0's binary_logloss: 0.215203
[65]	valid_0's binary_logloss: 0.215105
[66]	valid_0's binary_logloss: 0.214474
[67]	valid_0's binary_logloss: 0.214057
[68]	valid_0's binary_logloss: 0.213703
[69]	valid_0's binary_logloss: 0.213256
[70]	valid_0's binary_logloss: 0.212765
[71]	valid_0's binary_logloss: 0.212455
[72]	valid_0's binary_logloss: 0.212247
[73]	valid_0's binary_logloss: 0.212048
[74]	valid_0's binary_logloss: 0.211803
[75]	valid_0's binary_logloss: 0.211524
[76]	valid_0's binary_logloss: 0.211461
[77]	valid_0's binary_logloss: 0.21162
[78]	valid_0's binary_logloss: 0.211604
[79]	valid_0's binary_logloss: 0.211696
[80]	valid_0's binary_logloss: 0.211459
[81]	valid_0's binary_logloss: 0.211014
[82]	valid_0's binary_logloss: 0.211198
[83]	valid_0's binary_logloss: 0.211008
[84]	valid_0's binary_logloss: 0.210608
[85]	valid_0's binary_logloss: 0.210889
[86]	valid_0's binary_logloss: 0.210794
[87]	valid_0's binary_logloss: 0.210593
[88]	valid_0's binary_logloss: 0.210283
[89]	valid_0's binary_logloss: 0.20991
[90]	valid_0's binary_logloss: 0.210051
[91]	valid_0's binary_logloss: 0.209821
[92]	valid_0's binary_logloss: 0.209796
[93]	valid_0's binary_logloss: 0.209856
[94]	valid_0's binary_logloss: 0.21002
[95]	valid_0's binary_logloss: 0.21028
[96]	valid_0's binary_logloss: 0.210132
[97]	valid_0's binary_logloss: 0.210399
[98]	valid_0's binary_logloss: 0.210051
[99]	valid_0's binary_logloss: 0.2101
[100]	valid_0's binary_logloss: 0.210212
[101]	valid_0's binary_logloss: 0.210214
[102]	valid_0's binary_logloss: 0.210175
[103]	valid_0's binary_logloss: 0.210209
[104]	valid_0's binary_logloss: 0.210194
[105]	valid_0's binary_logloss: 0.209966
[106]	valid_0's binary_logloss: 0.209979
[107]	valid_0's binary_logloss: 0.209915
[108]	valid_0's binary_logloss: 0.209793
[109]	valid_0's binary_logloss: 0.20972
[110]	valid_0's binary_logloss: 0.209455
[111]	valid_0's binary_logloss: 0.209543
[112]	valid_0's binary_logloss: 0.209628
[113]	valid_0's binary_logloss: 0.209679
[114]	valid_0's binary_logloss: 0.209797
[115]	valid_0's binary_logloss: 0.209985
[116]	valid_0's binary_logloss: 0.210031
[117]	valid_0's binary_logloss: 0.209599
[118]	valid_0's binary_logloss: 0.209512
[119]	valid_0's binary_logloss: 0.209442
[120]	valid_0's binary_logloss: 0.209191
[121]	valid_0's binary_logloss: 0.208917
[122]	valid_0's binary_logloss: 0.209149
[123]	valid_0's binary_logloss: 0.209454
[124]	valid_0's binary_logloss: 0.209604
[125]	valid_0's binary_logloss: 0.209785
[126]	valid_0's binary_logloss: 0.209814
[127]	valid_0's binary_logloss: 0.210007
[128]	valid_0's binary_logloss: 0.210129
[129]	valid_0's binary_logloss: 0.209895
[130]	valid_0's binary_logloss: 0.210066
[131]	valid_0's binary_logloss: 0.209999
[132]	valid_0's binary_logloss: 0.209857
[133]	valid_0's binary_logloss: 0.209875
[134]	valid_0's binary_logloss: 0.210053
[135]	valid_0's binary_logloss: 0.210203
[136]	valid_0's binary_logloss: 0.210106
[137]	valid_0's binary_logloss: 0.209876
[138]	valid_0's binary_logloss: 0.209983
[139]	valid_0's binary_logloss: 0.209934
[140]	valid_0's binary_logloss: 0.209842
[141]	valid_0's binary_logloss: 0.209598
[142]	valid_0's binary_logloss: 0.209608
[143]	valid_0's binary_logloss: 0.209386
[144]	valid_0's binary_logloss: 0.209347
[145]	valid_0's binary_logloss: 0.209131
[146]	valid_0's binary_logloss: 0.209273
[147]	valid_0's binary_logloss: 0.209228
[148]	valid_0's binary_logloss: 0.209055
[149]	valid_0's binary_logloss: 0.208903
[150]	valid_0's binary_logloss: 0.209
[151]	valid_0's binary_logloss: 0.20897
[152]	valid_0's binary_logloss: 0.208839
[153]	valid_0's binary_logloss: 0.208729
[154]	valid_0's binary_logloss: 0.208839
[155]	valid_0's binary_logloss: 0.208995
[156]	valid_0's binary_logloss: 0.208953
[157]	valid_0's binary_logloss: 0.20905
[158]	valid_0's binary_logloss: 0.209149
[159]	valid_0's binary_logloss: 0.209074
[160]	valid_0's binary_logloss: 0.209033
[161]	valid_0's binary_logloss: 0.208849
[162]	valid_0's binary_logloss: 0.209068
[163]	valid_0's binary_logloss: 0.209131
[164]	valid_0's binary_logloss: 0.209054
[165]	valid_0's binary_logloss: 0.209091
[166]	valid_0's binary_logloss: 0.209234
[167]	valid_0's binary_logloss: 0.209468
[168]	valid_0's binary_logloss: 0.209633
[169]	valid_0's binary_logloss: 0.209816
[170]	valid_0's binary_logloss: 0.210079
[171]	valid_0's binary_logloss: 0.209816
[172]	valid_0's binary_logloss: 0.209641
[173]	valid_0's binary_logloss: 0.209537
[174]	valid_0's binary_logloss: 0.209698
[175]	valid_0's binary_logloss: 0.209678
[176]	valid_0's binary_logloss: 0.209643
[177]	valid_0's binary_logloss: 0.209897
[178]	valid_0's binary_logloss: 0.209831
[179]	valid_0's binary_logloss: 0.209866
[180]	valid_0's binary_logloss: 0.209967
[181]	valid_0's binary_logloss: 0.210231
[182]	valid_0's binary_logloss: 0.210396
[183]	valid_0's binary_logloss: 0.210761

Trening klas:  11%|█         | 55/500 [10:50<1:14:41, 10.07s/klasa, klasa=class_55, F1_klasy=0.6438, F1_macro=0.8876, drzewa=153]




Trening klas:  11%|█         | 56/500 [10:50<1:21:39, 11.04s/klasa, klasa=class_55, F1_klasy=0.6438, F1_macro=0.8876, drzewa=153]

[1]	valid_0's binary_logloss: 0.504335
[2]	valid_0's binary_logloss: 0.447497
[3]	valid_0's binary_logloss: 0.407529
[4]	valid_0's binary_logloss: 0.379361
[5]	valid_0's binary_logloss: 0.35415
[6]	valid_0's binary_logloss: 0.334445
[7]	valid_0's binary_logloss: 0.317427
[8]	valid_0's binary_logloss: 0.303025
[9]	valid_0's binary_logloss: 0.290319
[10]	valid_0's binary_logloss: 0.278273
[11]	valid_0's binary_logloss: 0.269344
[12]	valid_0's binary_logloss: 0.260678
[13]	valid_0's binary_logloss: 0.252878
[14]	valid_0's binary_logloss: 0.245589
[15]	valid_0's binary_logloss: 0.239146
[16]	valid_0's binary_logloss: 0.233156
[17]	valid_0's binary_logloss: 0.227273
[18]	valid_0's binary_logloss: 0.222253
[19]	valid_0's binary_logloss: 0.217322
[20]	valid_0's binary_logloss: 0.213182
[21]	valid_0's binary_logloss: 0.209457
[22]	valid_0's binary_logloss: 0.206067
[23]	valid_0's binary_logloss: 0.203171
[24]	valid_0's binary_logloss: 0.200643
[25]	valid_0's binary_logloss: 0.198118
[26]	valid_0's binary_logloss: 0.196061
[27]	valid_0's binary_logloss: 0.194098
[28]	valid_0's binary_logloss: 0.192483
[29]	valid_0's binary_logloss: 0.19053
[30]	valid_0's binary_logloss: 0.188857
[31]	valid_0's binary_logloss: 0.187202
[32]	valid_0's binary_logloss: 0.186124
[33]	valid_0's binary_logloss: 0.184835
[34]	valid_0's binary_logloss: 0.184003
[35]	valid_0's binary_logloss: 0.183294
[36]	valid_0's binary_logloss: 0.182471
[37]	valid_0's binary_logloss: 0.18173
[38]	valid_0's binary_logloss: 0.181126
[39]	valid_0's binary_logloss: 0.180508
[40]	valid_0's binary_logloss: 0.180592
[41]	valid_0's binary_logloss: 0.180002
[42]	valid_0's binary_logloss: 0.179842
[43]	valid_0's binary_logloss: 0.179635
[44]	valid_0's binary_logloss: 0.179229
[45]	valid_0's binary_logloss: 0.178763
[46]	valid_0's binary_logloss: 0.178679
[47]	valid_0's binary_logloss: 0.178742
[48]	valid_0's binary_logloss: 0.178924
[49]	valid_0's binary_logloss: 0.178849
[50]	valid_0's binary_logloss: 0.178565
[51]	valid_0's binary_logloss: 0.178956
[52]	valid_0's binary_logloss: 0.17945
[53]	valid_0's binary_logloss: 0.179825
[54]	valid_0's binary_logloss: 0.18017
[55]	valid_0's binary_logloss: 0.180589
[56]	valid_0's binary_logloss: 0.180922
[57]	valid_0's binary_logloss: 0.181218
[58]	valid_0's binary_logloss: 0.181985
[59]	valid_0's binary_logloss: 0.182369
[60]	valid_0's binary_logloss: 0.182454
[61]	valid_0's binary_logloss: 0.182949
[62]	valid_0's binary_logloss: 0.183221
[63]	valid_0's binary_logloss: 0.183779
[64]	valid_0's binary_logloss: 0.184394
[65]	valid_0's binary_logloss: 0.185076
[66]	valid_0's binary_logloss: 0.185522
[67]	valid_0's binary_logloss: 0.185957
[68]	valid_0's binary_logloss: 0.186113
[69]	valid_0's binary_logloss: 0.18622
[70]	valid_0's binary_logloss: 0.186558
[71]	valid_0's binary_logloss: 0.187047
[72]	valid_0's binary_logloss: 0.187759
[73]	valid_0's binary_logloss: 0.188209
[74]	valid_0's binary_logloss: 0.188811
[75]	valid_0's binary_logloss: 0.189195
[76]	valid_0's binary_logloss: 0.189681
[77]	valid_0's binary_logloss: 0.19029
[78]	valid_0's binary_logloss: 0.191017
[79]	valid_0's binary_logloss: 0.19147
[80]	valid_0's binary_logloss: 0.19183

Trening klas:  11%|█         | 56/500 [10:56<1:21:39, 11.04s/klasa, klasa=class_56, F1_klasy=0.8374, F1_macro=0.8867, drzewa=50]




Trening klas:  11%|█▏        | 57/500 [10:56<1:10:22,  9.53s/klasa, klasa=class_56, F1_klasy=0.8374, F1_macro=0.8867, drzewa=50]

[1]	valid_0's binary_logloss: 0.374182
[2]	valid_0's binary_logloss: 0.331932
[3]	valid_0's binary_logloss: 0.301927
[4]	valid_0's binary_logloss: 0.277796
[5]	valid_0's binary_logloss: 0.258748
[6]	valid_0's binary_logloss: 0.242188
[7]	valid_0's binary_logloss: 0.228338
[8]	valid_0's binary_logloss: 0.21616
[9]	valid_0's binary_logloss: 0.205293
[10]	valid_0's binary_logloss: 0.195724
[11]	valid_0's binary_logloss: 0.187036
[12]	valid_0's binary_logloss: 0.179551
[13]	valid_0's binary_logloss: 0.172563
[14]	valid_0's binary_logloss: 0.16671
[15]	valid_0's binary_logloss: 0.161164
[16]	valid_0's binary_logloss: 0.155985
[17]	valid_0's binary_logloss: 0.151129
[18]	valid_0's binary_logloss: 0.146807
[19]	valid_0's binary_logloss: 0.142815
[20]	valid_0's binary_logloss: 0.139244
[21]	valid_0's binary_logloss: 0.135561
[22]	valid_0's binary_logloss: 0.132287
[23]	valid_0's binary_logloss: 0.129441
[24]	valid_0's binary_logloss: 0.126791
[25]	valid_0's binary_logloss: 0.124441
[26]	valid_0's binary_logloss: 0.122235
[27]	valid_0's binary_logloss: 0.120179
[28]	valid_0's binary_logloss: 0.118469
[29]	valid_0's binary_logloss: 0.11675
[30]	valid_0's binary_logloss: 0.115384
[31]	valid_0's binary_logloss: 0.113701
[32]	valid_0's binary_logloss: 0.112273
[33]	valid_0's binary_logloss: 0.111006
[34]	valid_0's binary_logloss: 0.109671
[35]	valid_0's binary_logloss: 0.1087
[36]	valid_0's binary_logloss: 0.107533
[37]	valid_0's binary_logloss: 0.106592
[38]	valid_0's binary_logloss: 0.105633
[39]	valid_0's binary_logloss: 0.104753
[40]	valid_0's binary_logloss: 0.104068
[41]	valid_0's binary_logloss: 0.103222
[42]	valid_0's binary_logloss: 0.102632
[43]	valid_0's binary_logloss: 0.10195
[44]	valid_0's binary_logloss: 0.101334
[45]	valid_0's binary_logloss: 0.100896
[46]	valid_0's binary_logloss: 0.100531
[47]	valid_0's binary_logloss: 0.100246
[48]	valid_0's binary_logloss: 0.0998927
[49]	valid_0's binary_logloss: 0.0999182
[50]	valid_0's binary_logloss: 0.0997099
[51]	valid_0's binary_logloss: 0.099489
[52]	valid_0's binary_logloss: 0.0992975
[53]	valid_0's binary_logloss: 0.0991223
[54]	valid_0's binary_logloss: 0.0989719
[55]	valid_0's binary_logloss: 0.0988928
[56]	valid_0's binary_logloss: 0.0987676
[57]	valid_0's binary_logloss: 0.0990382
[58]	valid_0's binary_logloss: 0.0990245
[59]	valid_0's binary_logloss: 0.0990368
[60]	valid_0's binary_logloss: 0.0990913
[61]	valid_0's binary_logloss: 0.0991126
[62]	valid_0's binary_logloss: 0.098954
[63]	valid_0's binary_logloss: 0.0989673
[64]	valid_0's binary_logloss: 0.0991593
[65]	valid_0's binary_logloss: 0.0994396
[66]	valid_0's binary_logloss: 0.0993859
[67]	valid_0's binary_logloss: 0.0992213
[68]	valid_0's binary_logloss: 0.0991634
[69]	valid_0's binary_logloss: 0.099246
[70]	valid_0's binary_logloss: 0.0993085
[71]	valid_0's binary_logloss: 0.099374
[72]	valid_0's binary_logloss: 0.0995807
[73]	valid_0's binary_logloss: 0.0998646
[74]	valid_0's binary_logloss: 0.100037
[75]	valid_0's binary_logloss: 0.100143
[76]	valid_0's binary_logloss: 0.10012
[77]	valid_0's binary_logloss: 0.100185
[78]	valid_0's binary_logloss: 0.100132
[79]	valid_0's binary_logloss: 0.100183
[80]	valid_0's binary_logloss: 0.099992
[81]	valid_0's binary_logloss: 0.100054
[82]	valid_0's binary_logloss: 0.100142
[83]	valid_0's binary_logloss: 0.100328
[84]	valid_0's binary_logloss: 0.100451
[85]	valid_0's binary_logloss: 0.100577

Trening klas:  11%|█▏        | 57/500 [11:02<1:10:22,  9.53s/klasa, klasa=class_57, F1_klasy=0.8812, F1_macro=0.8866, drzewa=56]




Trening klas:  12%|█▏        | 58/500 [11:02<1:03:47,  8.66s/klasa, klasa=class_57, F1_klasy=0.8812, F1_macro=0.8866, drzewa=56]

[86]	valid_0's binary_logloss: 0.10092
[1]	valid_0's binary_logloss: 0.422456
[2]	valid_0's binary_logloss: 0.393981
[3]	valid_0's binary_logloss: 0.373859
[4]	valid_0's binary_logloss: 0.358813
[5]	valid_0's binary_logloss: 0.348327
[6]	valid_0's binary_logloss: 0.337955
[7]	valid_0's binary_logloss: 0.328436
[8]	valid_0's binary_logloss: 0.320503
[9]	valid_0's binary_logloss: 0.31379
[10]	valid_0's binary_logloss: 0.307649
[11]	valid_0's binary_logloss: 0.302983
[12]	valid_0's binary_logloss: 0.2986
[13]	valid_0's binary_logloss: 0.294512
[14]	valid_0's binary_logloss: 0.290433
[15]	valid_0's binary_logloss: 0.28775
[16]	valid_0's binary_logloss: 0.285249
[17]	valid_0's binary_logloss: 0.283094
[18]	valid_0's binary_logloss: 0.28166
[19]	valid_0's binary_logloss: 0.280482
[20]	valid_0's binary_logloss: 0.27893
[21]	valid_0's binary_logloss: 0.277706
[22]	valid_0's binary_logloss: 0.276733
[23]	valid_0's binary_logloss: 0.274909
[24]	valid_0's binary_logloss: 0.274547
[25]	valid_0's binary_logloss: 0.273446
[26]	valid_0's binary_logloss: 0.272198
[27]	valid_0's binary_logloss: 0.271503
[28]	valid_0's binary_logloss: 0.270473
[29]	valid_0's binary_logloss: 0.269936
[30]	valid_0's binary_logloss: 0.268984
[31]	valid_0's binary_logloss: 0.268222
[32]	valid_0's binary_logloss: 0.267738
[33]	valid_0's binary_logloss: 0.267313
[34]	valid_0's binary_logloss: 0.265959
[35]	valid_0's binary_logloss: 0.265395
[36]	valid_0's binary_logloss: 0.264666
[37]	valid_0's binary_logloss: 0.263902
[38]	valid_0's binary_logloss: 0.263477
[39]	valid_0's binary_logloss: 0.262714
[40]	valid_0's binary_logloss: 0.262218
[41]	valid_0's binary_logloss: 0.261962
[42]	valid_0's binary_logloss: 0.26117
[43]	valid_0's binary_logloss: 0.260994
[44]	valid_0's binary_logloss: 0.260512
[45]	valid_0's binary_logloss: 0.260519
[46]	valid_0's binary_logloss: 0.260056
[47]	valid_0's binary_logloss: 0.259905
[48]	valid_0's binary_logloss: 0.260267
[49]	valid_0's binary_logloss: 0.260223
[50]	valid_0's binary_logloss: 0.260239
[51]	valid_0's binary_logloss: 0.2604
[52]	valid_0's binary_logloss: 0.260362
[53]	valid_0's binary_logloss: 0.260108
[54]	valid_0's binary_logloss: 0.260266
[55]	valid_0's binary_logloss: 0.260291
[56]	valid_0's binary_logloss: 0.260221
[57]	valid_0's binary_logloss: 0.2601
[58]	valid_0's binary_logloss: 0.260093
[59]	valid_0's binary_logloss: 0.260084
[60]	valid_0's binary_logloss: 0.260321
[61]	valid_0's binary_logloss: 0.259931
[62]	valid_0's binary_logloss: 0.259867
[63]	valid_0's binary_logloss: 0.259974
[64]	valid_0's binary_logloss: 0.259407
[65]	valid_0's binary_logloss: 0.259217
[66]	valid_0's binary_logloss: 0.258399
[67]	valid_0's binary_logloss: 0.258117
[68]	valid_0's binary_logloss: 0.257972
[69]	valid_0's binary_logloss: 0.257694
[70]	valid_0's binary_logloss: 0.257443
[71]	valid_0's binary_logloss: 0.257335
[72]	valid_0's binary_logloss: 0.257424
[73]	valid_0's binary_logloss: 0.257316
[74]	valid_0's binary_logloss: 0.257073
[75]	valid_0's binary_logloss: 0.256903
[76]	valid_0's binary_logloss: 0.255992
[77]	valid_0's binary_logloss: 0.25547
[78]	valid_0's binary_logloss: 0.255921
[79]	valid_0's binary_logloss: 0.255886
[80]	valid_0's binary_logloss: 0.255917
[81]	valid_0's binary_logloss: 0.25627
[82]	valid_0's binary_logloss: 0.256267
[83]	valid_0's binary_logloss: 0.256531
[84]	valid_0's binary_logloss: 0.256982
[85]	valid_0's binary_logloss: 0.257256
[86]	valid_0's binary_logloss: 0.257376
[87]	valid_0's binary_logloss: 0.257577
[88]	valid_0's binary_logloss: 0.257399
[89]	valid_0's binary_logloss: 0.257257
[90]	valid_0's binary_logloss: 0.257449
[91]	valid_0's binary_logloss: 0.257118
[92]	valid_0's binary_logloss: 0.256987
[93]	valid_0's binary_logloss: 0.256717
[94]	valid_0's binary_logloss: 0.256326
[95]	valid_0's binary_logloss: 0.256126
[96]	valid_0's binary_logloss: 0.255501
[97]	valid_0's binary_logloss: 0.255341
[98]	valid_0's binary_logloss: 0.255526
[99]	valid_0's binary_logloss: 0.255042
[100]	valid_0's binary_logloss: 0.255197
[101]	valid_0's binary_logloss: 0.255352
[102]	valid_0's binary_logloss: 0.255709
[103]	valid_0's binary_logloss: 0.255957
[104]	valid_0's binary_logloss: 0.256145
[105]	valid_0's binary_logloss: 0.256212
[106]	valid_0's binary_logloss: 0.256205
[107]	valid_0's binary_logloss: 0.256153
[108]	valid_0's binary_logloss: 0.256332
[109]	valid_0's binary_logloss: 0.256107
[110]	valid_0's binary_logloss: 0.25594
[111]	valid_0's binary_logloss: 0.255781
[112]	valid_0's binary_logloss: 0.25562
[113]	valid_0's binary_logloss: 0.255829
[114]	valid_0's binary_logloss: 0.255834
[115]	valid_0's binary_logloss: 0.255916
[116]	valid_0's binary_logloss: 0.255731
[117]	valid_0's binary_logloss: 0.255534
[118]	valid_0's binary_logloss: 0.255847
[119]	valid_0's binary_logloss: 0.256009
[120]	valid_0's binary_logloss: 0.256128
[121]	valid_0's binary_logloss: 0.256002
[122]	valid_0's binary_logloss: 0.256207
[123]	valid_0's binary_logloss: 0.256036
[124]	valid_0's binary_logloss: 0.256091
[125]	valid_0's binary_logloss: 0.255904
[126]	valid_0's binary_logloss: 0.255825

Trening klas:  12%|█▏        | 58/500 [11:13<1:03:47,  8.66s/klasa, klasa=class_58, F1_klasy=0.6670, F1_macro=0.8829, drzewa=99]




Trening klas:  12%|█▏        | 59/500 [11:13<1:07:55,  9.24s/klasa, klasa=class_58, F1_klasy=0.6670, F1_macro=0.8829, drzewa=99]

[127]	valid_0's binary_logloss: 0.255842
[128]	valid_0's binary_logloss: 0.255605
[129]	valid_0's binary_logloss: 0.255503
[1]	valid_0's binary_logloss: 0.421732
[2]	valid_0's binary_logloss: 0.393242
[3]	valid_0's binary_logloss: 0.373104
[4]	valid_0's binary_logloss: 0.358041
[5]	valid_0's binary_logloss: 0.347539
[6]	valid_0's binary_logloss: 0.337152
[7]	valid_0's binary_logloss: 0.327617
[8]	valid_0's binary_logloss: 0.319669
[9]	valid_0's binary_logloss: 0.312939
[10]	valid_0's binary_logloss: 0.306782
[11]	valid_0's binary_logloss: 0.3021
[12]	valid_0's binary_logloss: 0.297702
[13]	valid_0's binary_logloss: 0.293598
[14]	valid_0's binary_logloss: 0.289504
[15]	valid_0's binary_logloss: 0.286805
[16]	valid_0's binary_logloss: 0.284289
[17]	valid_0's binary_logloss: 0.282118
[18]	valid_0's binary_logloss: 0.280668
[19]	valid_0's binary_logloss: 0.279475
[20]	valid_0's binary_logloss: 0.277907
[21]	valid_0's binary_logloss: 0.27668
[22]	valid_0's binary_logloss: 0.275695
[23]	valid_0's binary_logloss: 0.273867
[24]	valid_0's binary_logloss: 0.273488
[25]	valid_0's binary_logloss: 0.272372
[26]	valid_0's binary_logloss: 0.271108
[27]	valid_0's binary_logloss: 0.270398
[28]	valid_0's binary_logloss: 0.269353
[29]	valid_0's binary_logloss: 0.268801
[30]	valid_0's binary_logloss: 0.267835
[31]	valid_0's binary_logloss: 0.267056
[32]	valid_0's binary_logloss: 0.266559
[33]	valid_0's binary_logloss: 0.266116
[34]	valid_0's binary_logloss: 0.264777
[35]	valid_0's binary_logloss: 0.264196
[36]	valid_0's binary_logloss: 0.263466
[37]	valid_0's binary_logloss: 0.262718
[38]	valid_0's binary_logloss: 0.262309
[39]	valid_0's binary_logloss: 0.261545
[40]	valid_0's binary_logloss: 0.261047
[41]	valid_0's binary_logloss: 0.260801
[42]	valid_0's binary_logloss: 0.259993
[43]	valid_0's binary_logloss: 0.259818
[44]	valid_0's binary_logloss: 0.259329
[45]	valid_0's binary_logloss: 0.259346
[46]	valid_0's binary_logloss: 0.258867
[47]	valid_0's binary_logloss: 0.258702
[48]	valid_0's binary_logloss: 0.259064
[49]	valid_0's binary_logloss: 0.259005
[50]	valid_0's binary_logloss: 0.259006
[51]	valid_0's binary_logloss: 0.259152
[52]	valid_0's binary_logloss: 0.259099
[53]	valid_0's binary_logloss: 0.258855
[54]	valid_0's binary_logloss: 0.258998
[55]	valid_0's binary_logloss: 0.259008
[56]	valid_0's binary_logloss: 0.258948
[57]	valid_0's binary_logloss: 0.258822
[58]	valid_0's binary_logloss: 0.258818
[59]	valid_0's binary_logloss: 0.258809
[60]	valid_0's binary_logloss: 0.259031
[61]	valid_0's binary_logloss: 0.258643
[62]	valid_0's binary_logloss: 0.258577
[63]	valid_0's binary_logloss: 0.258681
[64]	valid_0's binary_logloss: 0.258124
[65]	valid_0's binary_logloss: 0.257926
[66]	valid_0's binary_logloss: 0.257092
[67]	valid_0's binary_logloss: 0.256795
[68]	valid_0's binary_logloss: 0.256641
[69]	valid_0's binary_logloss: 0.256349
[70]	valid_0's binary_logloss: 0.256106
[71]	valid_0's binary_logloss: 0.256008
[72]	valid_0's binary_logloss: 0.256095
[73]	valid_0's binary_logloss: 0.255975
[74]	valid_0's binary_logloss: 0.25573
[75]	valid_0's binary_logloss: 0.255544
[76]	valid_0's binary_logloss: 0.254634
[77]	valid_0's binary_logloss: 0.254113
[78]	valid_0's binary_logloss: 0.254559
[79]	valid_0's binary_logloss: 0.254533
[80]	valid_0's binary_logloss: 0.254573
[81]	valid_0's binary_logloss: 0.254929
[82]	valid_0's binary_logloss: 0.254926
[83]	valid_0's binary_logloss: 0.255169
[84]	valid_0's binary_logloss: 0.255582
[85]	valid_0's binary_logloss: 0.255843
[86]	valid_0's binary_logloss: 0.255974
[87]	valid_0's binary_logloss: 0.256167
[88]	valid_0's binary_logloss: 0.255989
[89]	valid_0's binary_logloss: 0.255853
[90]	valid_0's binary_logloss: 0.25605
[91]	valid_0's binary_logloss: 0.255701
[92]	valid_0's binary_logloss: 0.255561
[93]	valid_0's binary_logloss: 0.255296
[94]	valid_0's binary_logloss: 0.254896
[95]	valid_0's binary_logloss: 0.25468
[96]	valid_0's binary_logloss: 0.254037
[97]	valid_0's binary_logloss: 0.253856
[98]	valid_0's binary_logloss: 0.254035
[99]	valid_0's binary_logloss: 0.253531
[100]	valid_0's binary_logloss: 0.25369
[101]	valid_0's binary_logloss: 0.253829
[102]	valid_0's binary_logloss: 0.254176
[103]	valid_0's binary_logloss: 0.254415
[104]	valid_0's binary_logloss: 0.254589
[105]	valid_0's binary_logloss: 0.254656
[106]	valid_0's binary_logloss: 0.254635
[107]	valid_0's binary_logloss: 0.254569
[108]	valid_0's binary_logloss: 0.254738
[109]	valid_0's binary_logloss: 0.254519
[110]	valid_0's binary_logloss: 0.254342
[111]	valid_0's binary_logloss: 0.254171
[112]	valid_0's binary_logloss: 0.254003
[113]	valid_0's binary_logloss: 0.254196
[114]	valid_0's binary_logloss: 0.254193
[115]	valid_0's binary_logloss: 0.254257
[116]	valid_0's binary_logloss: 0.25406
[117]	valid_0's binary_logloss: 0.253852
[118]	valid_0's binary_logloss: 0.254165
[119]	valid_0's binary_logloss: 0.254336
[120]	valid_0's binary_logloss: 0.254459
[121]	valid_0's binary_logloss: 0.254315
[122]	valid_0's binary_logloss: 0.254503
[123]	valid_0's binary_logloss: 0.254305
[124]	valid_0's binary_logloss: 0.254346
[125]	valid_0's binary_logloss: 0.25416
[126]	valid_0's binary_logloss: 0.254063
[127]	valid_0's binary_logloss: 0.254064
[128]	valid_0's binary_logloss: 0.253809

Trening klas:  12%|█▏        | 59/500 [11:23<1:07:55,  9.24s/klasa, klasa=class_59, F1_klasy=0.6676, F1_macro=0.8793, drzewa=99]




Trening klas:  12%|█▏        | 60/500 [11:23<1:09:25,  9.47s/klasa, klasa=class_59, F1_klasy=0.6676, F1_macro=0.8793, drzewa=99]

[129]	valid_0's binary_logloss: 0.253693
[1]	valid_0's binary_logloss: 0.285203
[2]	valid_0's binary_logloss: 0.25736
[3]	valid_0's binary_logloss: 0.237474
[4]	valid_0's binary_logloss: 0.221388
[5]	valid_0's binary_logloss: 0.20775
[6]	valid_0's binary_logloss: 0.196514
[7]	valid_0's binary_logloss: 0.186978
[8]	valid_0's binary_logloss: 0.178577
[9]	valid_0's binary_logloss: 0.170689
[10]	valid_0's binary_logloss: 0.163513
[11]	valid_0's binary_logloss: 0.15751
[12]	valid_0's binary_logloss: 0.151814
[13]	valid_0's binary_logloss: 0.146784
[14]	valid_0's binary_logloss: 0.141999
[15]	valid_0's binary_logloss: 0.137602
[16]	valid_0's binary_logloss: 0.13331
[17]	valid_0's binary_logloss: 0.129611
[18]	valid_0's binary_logloss: 0.126377
[19]	valid_0's binary_logloss: 0.123289
[20]	valid_0's binary_logloss: 0.120452
[21]	valid_0's binary_logloss: 0.117732
[22]	valid_0's binary_logloss: 0.115403
[23]	valid_0's binary_logloss: 0.113348
[24]	valid_0's binary_logloss: 0.111446
[25]	valid_0's binary_logloss: 0.109636
[26]	valid_0's binary_logloss: 0.107796
[27]	valid_0's binary_logloss: 0.106082
[28]	valid_0's binary_logloss: 0.104392
[29]	valid_0's binary_logloss: 0.103042
[30]	valid_0's binary_logloss: 0.101774
[31]	valid_0's binary_logloss: 0.100487
[32]	valid_0's binary_logloss: 0.0993435
[33]	valid_0's binary_logloss: 0.0984118
[34]	valid_0's binary_logloss: 0.097644
[35]	valid_0's binary_logloss: 0.0968268
[36]	valid_0's binary_logloss: 0.0962481
[37]	valid_0's binary_logloss: 0.0955995
[38]	valid_0's binary_logloss: 0.094817
[39]	valid_0's binary_logloss: 0.0942031
[40]	valid_0's binary_logloss: 0.0938617
[41]	valid_0's binary_logloss: 0.0932143
[42]	valid_0's binary_logloss: 0.0927208
[43]	valid_0's binary_logloss: 0.0924528
[44]	valid_0's binary_logloss: 0.0920086
[45]	valid_0's binary_logloss: 0.091719
[46]	valid_0's binary_logloss: 0.091455
[47]	valid_0's binary_logloss: 0.0912774
[48]	valid_0's binary_logloss: 0.0910622
[49]	valid_0's binary_logloss: 0.0909711
[50]	valid_0's binary_logloss: 0.0908009
[51]	valid_0's binary_logloss: 0.0905248
[52]	valid_0's binary_logloss: 0.0904492
[53]	valid_0's binary_logloss: 0.0903168
[54]	valid_0's binary_logloss: 0.0903656
[55]	valid_0's binary_logloss: 0.0903755
[56]	valid_0's binary_logloss: 0.090448
[57]	valid_0's binary_logloss: 0.0905436
[58]	valid_0's binary_logloss: 0.0906262
[59]	valid_0's binary_logloss: 0.090762
[60]	valid_0's binary_logloss: 0.090962
[61]	valid_0's binary_logloss: 0.0909359
[62]	valid_0's binary_logloss: 0.0911252
[63]	valid_0's binary_logloss: 0.0910623
[64]	valid_0's binary_logloss: 0.0910713
[65]	valid_0's binary_logloss: 0.0911245
[66]	valid_0's binary_logloss: 0.09118
[67]	valid_0's binary_logloss: 0.0912623
[68]	valid_0's binary_logloss: 0.0914282
[69]	valid_0's binary_logloss: 0.0915947
[70]	valid_0's binary_logloss: 0.091685
[71]	valid_0's binary_logloss: 0.0919586
[72]	valid_0's binary_logloss: 0.0916042
[73]	valid_0's binary_logloss: 0.0914237
[74]	valid_0's binary_logloss: 0.0915535
[75]	valid_0's binary_logloss: 0.0914214
[76]	valid_0's binary_logloss: 0.0912721
[77]	valid_0's binary_logloss: 0.0915062
[78]	valid_0's binary_logloss: 0.0913028
[79]	valid_0's binary_logloss: 0.0912514
[80]	valid_0's binary_logloss: 0.0914599
[81]	valid_0's binary_logloss: 0.0913709

Trening klas:  12%|█▏        | 60/500 [11:29<1:09:25,  9.47s/klasa, klasa=class_60, F1_klasy=0.8556, F1_macro=0.8789, drzewa=53]




Trening klas:  12%|█▏        | 61/500 [11:29<1:02:04,  8.48s/klasa, klasa=class_60, F1_klasy=0.8556, F1_macro=0.8789, drzewa=53]

[82]	valid_0's binary_logloss: 0.0912592
[83]	valid_0's binary_logloss: 0.0912315
[1]	valid_0's binary_logloss: 0.444739
[2]	valid_0's binary_logloss: 0.408657
[3]	valid_0's binary_logloss: 0.382265
[4]	valid_0's binary_logloss: 0.362999
[5]	valid_0's binary_logloss: 0.347698
[6]	valid_0's binary_logloss: 0.33276
[7]	valid_0's binary_logloss: 0.320259
[8]	valid_0's binary_logloss: 0.309424
[9]	valid_0's binary_logloss: 0.29928
[10]	valid_0's binary_logloss: 0.291342
[11]	valid_0's binary_logloss: 0.284892
[12]	valid_0's binary_logloss: 0.27858
[13]	valid_0's binary_logloss: 0.272924
[14]	valid_0's binary_logloss: 0.2679
[15]	valid_0's binary_logloss: 0.263041
[16]	valid_0's binary_logloss: 0.258975
[17]	valid_0's binary_logloss: 0.254958
[18]	valid_0's binary_logloss: 0.251167
[19]	valid_0's binary_logloss: 0.247937
[20]	valid_0's binary_logloss: 0.244707
[21]	valid_0's binary_logloss: 0.241755
[22]	valid_0's binary_logloss: 0.23921
[23]	valid_0's binary_logloss: 0.236954
[24]	valid_0's binary_logloss: 0.234743
[25]	valid_0's binary_logloss: 0.232262
[26]	valid_0's binary_logloss: 0.231221
[27]	valid_0's binary_logloss: 0.229966
[28]	valid_0's binary_logloss: 0.228887
[29]	valid_0's binary_logloss: 0.227767
[30]	valid_0's binary_logloss: 0.225964
[31]	valid_0's binary_logloss: 0.224206
[32]	valid_0's binary_logloss: 0.222516
[33]	valid_0's binary_logloss: 0.220936
[34]	valid_0's binary_logloss: 0.219599
[35]	valid_0's binary_logloss: 0.218405
[36]	valid_0's binary_logloss: 0.217807
[37]	valid_0's binary_logloss: 0.2167
[38]	valid_0's binary_logloss: 0.215879
[39]	valid_0's binary_logloss: 0.21561
[40]	valid_0's binary_logloss: 0.215182
[41]	valid_0's binary_logloss: 0.215053
[42]	valid_0's binary_logloss: 0.21429
[43]	valid_0's binary_logloss: 0.213639
[44]	valid_0's binary_logloss: 0.213079
[45]	valid_0's binary_logloss: 0.21269
[46]	valid_0's binary_logloss: 0.212001
[47]	valid_0's binary_logloss: 0.212065
[48]	valid_0's binary_logloss: 0.211708
[49]	valid_0's binary_logloss: 0.211509
[50]	valid_0's binary_logloss: 0.211491
[51]	valid_0's binary_logloss: 0.21148
[52]	valid_0's binary_logloss: 0.211303
[53]	valid_0's binary_logloss: 0.21183
[54]	valid_0's binary_logloss: 0.211111
[55]	valid_0's binary_logloss: 0.211478
[56]	valid_0's binary_logloss: 0.211149
[57]	valid_0's binary_logloss: 0.210756
[58]	valid_0's binary_logloss: 0.210467
[59]	valid_0's binary_logloss: 0.210191
[60]	valid_0's binary_logloss: 0.210075
[61]	valid_0's binary_logloss: 0.210961
[62]	valid_0's binary_logloss: 0.211137
[63]	valid_0's binary_logloss: 0.211192
[64]	valid_0's binary_logloss: 0.211586
[65]	valid_0's binary_logloss: 0.212001
[66]	valid_0's binary_logloss: 0.212411
[67]	valid_0's binary_logloss: 0.212215
[68]	valid_0's binary_logloss: 0.212198
[69]	valid_0's binary_logloss: 0.21205
[70]	valid_0's binary_logloss: 0.211967
[71]	valid_0's binary_logloss: 0.212464
[72]	valid_0's binary_logloss: 0.213381
[73]	valid_0's binary_logloss: 0.213488
[74]	valid_0's binary_logloss: 0.213508
[75]	valid_0's binary_logloss: 0.213072
[76]	valid_0's binary_logloss: 0.212763
[77]	valid_0's binary_logloss: 0.213067
[78]	valid_0's binary_logloss: 0.212699
[79]	valid_0's binary_logloss: 0.212609
[80]	valid_0's binary_logloss: 0.2119
[81]	valid_0's binary_logloss: 0.212071
[82]	valid_0's binary_logloss: 0.211612
[83]	valid_0's binary_logloss: 0.2111
[84]	valid_0's binary_logloss: 0.210898
[85]	valid_0's binary_logloss: 0.210425
[86]	valid_0's binary_logloss: 0.210667
[87]	valid_0's binary_logloss: 0.210273
[88]	valid_0's binary_logloss: 0.210501
[89]	valid_0's binary_logloss: 0.210961
[90]	valid_0's binary_logloss: 0.210788

Trening klas:  12%|█▏        | 61/500 [11:35<1:02:04,  8.48s/klasa, klasa=class_61, F1_klasy=0.7348, F1_macro=0.8766, drzewa=60]




Trening klas:  12%|█▏        | 62/500 [11:35<57:01,  7.81s/klasa, klasa=class_61, F1_klasy=0.7348, F1_macro=0.8766, drzewa=60]

[1]	valid_0's binary_logloss: 0.367111
[2]	valid_0's binary_logloss: 0.333859
[3]	valid_0's binary_logloss: 0.311959
[4]	valid_0's binary_logloss: 0.29465
[5]	valid_0's binary_logloss: 0.281769
[6]	valid_0's binary_logloss: 0.27133
[7]	valid_0's binary_logloss: 0.261569
[8]	valid_0's binary_logloss: 0.254072
[9]	valid_0's binary_logloss: 0.247162
[10]	valid_0's binary_logloss: 0.241609
[11]	valid_0's binary_logloss: 0.236597
[12]	valid_0's binary_logloss: 0.232594
[13]	valid_0's binary_logloss: 0.228883
[14]	valid_0's binary_logloss: 0.225233
[15]	valid_0's binary_logloss: 0.221777
[16]	valid_0's binary_logloss: 0.219213
[17]	valid_0's binary_logloss: 0.216814
[18]	valid_0's binary_logloss: 0.2147
[19]	valid_0's binary_logloss: 0.212583
[20]	valid_0's binary_logloss: 0.210473
[21]	valid_0's binary_logloss: 0.208775
[22]	valid_0's binary_logloss: 0.207479
[23]	valid_0's binary_logloss: 0.205872
[24]	valid_0's binary_logloss: 0.204312
[25]	valid_0's binary_logloss: 0.202584
[26]	valid_0's binary_logloss: 0.20123
[27]	valid_0's binary_logloss: 0.200559
[28]	valid_0's binary_logloss: 0.199728
[29]	valid_0's binary_logloss: 0.199142
[30]	valid_0's binary_logloss: 0.198775
[31]	valid_0's binary_logloss: 0.197699
[32]	valid_0's binary_logloss: 0.196662
[33]	valid_0's binary_logloss: 0.19598
[34]	valid_0's binary_logloss: 0.195373
[35]	valid_0's binary_logloss: 0.194655
[36]	valid_0's binary_logloss: 0.194187
[37]	valid_0's binary_logloss: 0.193871
[38]	valid_0's binary_logloss: 0.194083
[39]	valid_0's binary_logloss: 0.193729
[40]	valid_0's binary_logloss: 0.193771
[41]	valid_0's binary_logloss: 0.193696
[42]	valid_0's binary_logloss: 0.193187
[43]	valid_0's binary_logloss: 0.192769
[44]	valid_0's binary_logloss: 0.192771
[45]	valid_0's binary_logloss: 0.193332
[46]	valid_0's binary_logloss: 0.192205
[47]	valid_0's binary_logloss: 0.191386
[48]	valid_0's binary_logloss: 0.190986
[49]	valid_0's binary_logloss: 0.190127
[50]	valid_0's binary_logloss: 0.189982
[51]	valid_0's binary_logloss: 0.189832
[52]	valid_0's binary_logloss: 0.190149
[53]	valid_0's binary_logloss: 0.19028
[54]	valid_0's binary_logloss: 0.19054
[55]	valid_0's binary_logloss: 0.190327
[56]	valid_0's binary_logloss: 0.190276
[57]	valid_0's binary_logloss: 0.190128
[58]	valid_0's binary_logloss: 0.190196
[59]	valid_0's binary_logloss: 0.190396
[60]	valid_0's binary_logloss: 0.190469
[61]	valid_0's binary_logloss: 0.190592
[62]	valid_0's binary_logloss: 0.190664
[63]	valid_0's binary_logloss: 0.190079
[64]	valid_0's binary_logloss: 0.190327
[65]	valid_0's binary_logloss: 0.19052
[66]	valid_0's binary_logloss: 0.190657
[67]	valid_0's binary_logloss: 0.190519
[68]	valid_0's binary_logloss: 0.190555
[69]	valid_0's binary_logloss: 0.190672
[70]	valid_0's binary_logloss: 0.19052
[71]	valid_0's binary_logloss: 0.190641
[72]	valid_0's binary_logloss: 0.19065
[73]	valid_0's binary_logloss: 0.190788
[74]	valid_0's binary_logloss: 0.191117
[75]	valid_0's binary_logloss: 0.191236
[76]	valid_0's binary_logloss: 0.191539
[77]	valid_0's binary_logloss: 0.191695
[78]	valid_0's binary_logloss: 0.191856
[79]	valid_0's binary_logloss: 0.192083
[80]	valid_0's binary_logloss: 0.192157

Trening klas:  12%|█▏        | 62/500 [11:41<57:01,  7.81s/klasa, klasa=class_62, F1_klasy=0.7183, F1_macro=0.8741, drzewa=51]




Trening klas:  13%|█▎        | 63/500 [11:41<52:29,  7.21s/klasa, klasa=class_62, F1_klasy=0.7183, F1_macro=0.8741, drzewa=51]

[81]	valid_0's binary_logloss: 0.192458
[1]	valid_0's binary_logloss: 0.150052
[2]	valid_0's binary_logloss: 0.140366
[3]	valid_0's binary_logloss: 0.133033
[4]	valid_0's binary_logloss: 0.125946
[5]	valid_0's binary_logloss: 0.120075
[6]	valid_0's binary_logloss: 0.114486
[7]	valid_0's binary_logloss: 0.109462
[8]	valid_0's binary_logloss: 0.104682
[9]	valid_0's binary_logloss: 0.100171
[10]	valid_0's binary_logloss: 0.096264
[11]	valid_0's binary_logloss: 0.0924189
[12]	valid_0's binary_logloss: 0.0888688
[13]	valid_0's binary_logloss: 0.0853422
[14]	valid_0's binary_logloss: 0.081982
[15]	valid_0's binary_logloss: 0.0791333
[16]	valid_0's binary_logloss: 0.0765935
[17]	valid_0's binary_logloss: 0.0740832
[18]	valid_0's binary_logloss: 0.0718436
[19]	valid_0's binary_logloss: 0.0696154
[20]	valid_0's binary_logloss: 0.0675048
[21]	valid_0's binary_logloss: 0.065347
[22]	valid_0's binary_logloss: 0.0633849
[23]	valid_0's binary_logloss: 0.0615344
[24]	valid_0's binary_logloss: 0.0598488
[25]	valid_0's binary_logloss: 0.0582245
[26]	valid_0's binary_logloss: 0.056833
[27]	valid_0's binary_logloss: 0.0555718
[28]	valid_0's binary_logloss: 0.0543477
[29]	valid_0's binary_logloss: 0.0531268
[30]	valid_0's binary_logloss: 0.0519298
[31]	valid_0's binary_logloss: 0.0508313
[32]	valid_0's binary_logloss: 0.0497539
[33]	valid_0's binary_logloss: 0.0486004
[34]	valid_0's binary_logloss: 0.0474773
[35]	valid_0's binary_logloss: 0.0465844
[36]	valid_0's binary_logloss: 0.0456738
[37]	valid_0's binary_logloss: 0.0447777
[38]	valid_0's binary_logloss: 0.0440745
[39]	valid_0's binary_logloss: 0.0434278
[40]	valid_0's binary_logloss: 0.0426062
[41]	valid_0's binary_logloss: 0.0418539
[42]	valid_0's binary_logloss: 0.0410773
[43]	valid_0's binary_logloss: 0.0403415
[44]	valid_0's binary_logloss: 0.0395393
[45]	valid_0's binary_logloss: 0.0388111
[46]	valid_0's binary_logloss: 0.0383864
[47]	valid_0's binary_logloss: 0.0378369
[48]	valid_0's binary_logloss: 0.0374342
[49]	valid_0's binary_logloss: 0.037064
[50]	valid_0's binary_logloss: 0.0367161
[51]	valid_0's binary_logloss: 0.0364073
[52]	valid_0's binary_logloss: 0.0359075
[53]	valid_0's binary_logloss: 0.0355198
[54]	valid_0's binary_logloss: 0.0351204
[55]	valid_0's binary_logloss: 0.034722
[56]	valid_0's binary_logloss: 0.0343643
[57]	valid_0's binary_logloss: 0.0341784
[58]	valid_0's binary_logloss: 0.0338765
[59]	valid_0's binary_logloss: 0.0335925
[60]	valid_0's binary_logloss: 0.0333089
[61]	valid_0's binary_logloss: 0.0331956
[62]	valid_0's binary_logloss: 0.0330381
[63]	valid_0's binary_logloss: 0.0327908
[64]	valid_0's binary_logloss: 0.0326136
[65]	valid_0's binary_logloss: 0.0324484
[66]	valid_0's binary_logloss: 0.0322507
[67]	valid_0's binary_logloss: 0.0320748
[68]	valid_0's binary_logloss: 0.0319201
[69]	valid_0's binary_logloss: 0.0317762
[70]	valid_0's binary_logloss: 0.0314464
[71]	valid_0's binary_logloss: 0.0313878
[72]	valid_0's binary_logloss: 0.0313138
[73]	valid_0's binary_logloss: 0.0312901
[74]	valid_0's binary_logloss: 0.0311181
[75]	valid_0's binary_logloss: 0.0311307
[76]	valid_0's binary_logloss: 0.030968
[77]	valid_0's binary_logloss: 0.0306994
[78]	valid_0's binary_logloss: 0.0304454
[79]	valid_0's binary_logloss: 0.0303831
[80]	valid_0's binary_logloss: 0.0302074
[81]	valid_0's binary_logloss: 0.0301364
[82]	valid_0's binary_logloss: 0.030066
[83]	valid_0's binary_logloss: 0.0299609
[84]	valid_0's binary_logloss: 0.0299392
[85]	valid_0's binary_logloss: 0.0299017
[86]	valid_0's binary_logloss: 0.0298744
[87]	valid_0's binary_logloss: 0.029686
[88]	valid_0's binary_logloss: 0.0296169
[89]	valid_0's binary_logloss: 0.0296123
[90]	valid_0's binary_logloss: 0.0294815
[91]	valid_0's binary_logloss: 0.029467
[92]	valid_0's binary_logloss: 0.0294302
[93]	valid_0's binary_logloss: 0.0293839
[94]	valid_0's binary_logloss: 0.0293313
[95]	valid_0's binary_logloss: 0.0293421
[96]	valid_0's binary_logloss: 0.0291675
[97]	valid_0's binary_logloss: 0.0291447
[98]	valid_0's binary_logloss: 0.0291266
[99]	valid_0's binary_logloss: 0.0290254
[100]	valid_0's binary_logloss: 0.0289267
[101]	valid_0's binary_logloss: 0.0289195
[102]	valid_0's binary_logloss: 0.0289218
[103]	valid_0's binary_logloss: 0.0288962
[104]	valid_0's binary_logloss: 0.0289446
[105]	valid_0's binary_logloss: 0.0289827
[106]	valid_0's binary_logloss: 0.0289916
[107]	valid_0's binary_logloss: 0.0289831
[108]	valid_0's binary_logloss: 0.0290488
[109]	valid_0's binary_logloss: 0.0290573
[110]	valid_0's binary_logloss: 0.0290656
[111]	valid_0's binary_logloss: 0.0291827
[112]	valid_0's binary_logloss: 0.0291903
[113]	valid_0's binary_logloss: 0.0291528
[114]	valid_0's binary_logloss: 0.0291204
[115]	valid_0's binary_logloss: 0.0291578
[116]	valid_0's binary_logloss: 0.0292213
[117]	valid_0's binary_logloss: 0.0292097
[118]	valid_0's binary_logloss: 0.0292515
[119]	valid_0's binary_logloss: 0.0292995
[120]	valid_0's binary_logloss: 0.0293416
[121]	valid_0's binary_logloss: 0.0293937
[122]	valid_0's binary_logloss: 0.0294269
[123]	valid_0's binary_logloss: 0.0294503
[124]	valid_0's binary_logloss: 0.0294712
[125]	valid_0's binary_logloss: 0.0295509
[126]	valid_0's binary_logloss: 0.029576
[127]	valid_0's binary_logloss: 0.029589
[128]	valid_0's binary_logloss: 0.029584
[129]	valid_0's binary_logloss: 0.0294927
[130]	valid_0's binary_logloss: 0.0295262
[131]	valid_0's binary_logloss: 0.0296029

Trening klas:  13%|█▎        | 63/500 [11:51<52:29,  7.21s/klasa, klasa=class_63, F1_klasy=0.7896, F1_macro=0.8728, drzewa=103]




Trening klas:  13%|█▎        | 64/500 [11:51<59:03,  8.13s/klasa, klasa=class_63, F1_klasy=0.7896, F1_macro=0.8728, drzewa=103]

[132]	valid_0's binary_logloss: 0.0295207
[133]	valid_0's binary_logloss: 0.0297076
[1]	valid_0's binary_logloss: 0.276935
[2]	valid_0's binary_logloss: 0.256679
[3]	valid_0's binary_logloss: 0.241402
[4]	valid_0's binary_logloss: 0.230105
[5]	valid_0's binary_logloss: 0.220838
[6]	valid_0's binary_logloss: 0.213409
[7]	valid_0's binary_logloss: 0.207382
[8]	valid_0's binary_logloss: 0.202394
[9]	valid_0's binary_logloss: 0.198197
[10]	valid_0's binary_logloss: 0.194289
[11]	valid_0's binary_logloss: 0.190832
[12]	valid_0's binary_logloss: 0.187803
[13]	valid_0's binary_logloss: 0.184316
[14]	valid_0's binary_logloss: 0.18225
[15]	valid_0's binary_logloss: 0.180327
[16]	valid_0's binary_logloss: 0.178551
[17]	valid_0's binary_logloss: 0.177021
[18]	valid_0's binary_logloss: 0.176062
[19]	valid_0's binary_logloss: 0.174922
[20]	valid_0's binary_logloss: 0.173969
[21]	valid_0's binary_logloss: 0.173043
[22]	valid_0's binary_logloss: 0.172078
[23]	valid_0's binary_logloss: 0.17111
[24]	valid_0's binary_logloss: 0.169749
[25]	valid_0's binary_logloss: 0.169236
[26]	valid_0's binary_logloss: 0.168699
[27]	valid_0's binary_logloss: 0.168706
[28]	valid_0's binary_logloss: 0.16747
[29]	valid_0's binary_logloss: 0.167051
[30]	valid_0's binary_logloss: 0.166191
[31]	valid_0's binary_logloss: 0.165127
[32]	valid_0's binary_logloss: 0.164813
[33]	valid_0's binary_logloss: 0.164408
[34]	valid_0's binary_logloss: 0.164062
[35]	valid_0's binary_logloss: 0.16333
[36]	valid_0's binary_logloss: 0.162898
[37]	valid_0's binary_logloss: 0.162767
[38]	valid_0's binary_logloss: 0.162398
[39]	valid_0's binary_logloss: 0.161819
[40]	valid_0's binary_logloss: 0.161212
[41]	valid_0's binary_logloss: 0.160536
[42]	valid_0's binary_logloss: 0.160343
[43]	valid_0's binary_logloss: 0.160099
[44]	valid_0's binary_logloss: 0.159665
[45]	valid_0's binary_logloss: 0.159563
[46]	valid_0's binary_logloss: 0.159487
[47]	valid_0's binary_logloss: 0.159351
[48]	valid_0's binary_logloss: 0.159238
[49]	valid_0's binary_logloss: 0.159254
[50]	valid_0's binary_logloss: 0.159049
[51]	valid_0's binary_logloss: 0.158592
[52]	valid_0's binary_logloss: 0.158461
[53]	valid_0's binary_logloss: 0.15833
[54]	valid_0's binary_logloss: 0.15811
[55]	valid_0's binary_logloss: 0.158019
[56]	valid_0's binary_logloss: 0.158093
[57]	valid_0's binary_logloss: 0.158235
[58]	valid_0's binary_logloss: 0.158085
[59]	valid_0's binary_logloss: 0.157895
[60]	valid_0's binary_logloss: 0.157378
[61]	valid_0's binary_logloss: 0.157035
[62]	valid_0's binary_logloss: 0.156297
[63]	valid_0's binary_logloss: 0.155885
[64]	valid_0's binary_logloss: 0.155505
[65]	valid_0's binary_logloss: 0.155077
[66]	valid_0's binary_logloss: 0.154747
[67]	valid_0's binary_logloss: 0.154514
[68]	valid_0's binary_logloss: 0.154243
[69]	valid_0's binary_logloss: 0.154008
[70]	valid_0's binary_logloss: 0.153861
[71]	valid_0's binary_logloss: 0.153626
[72]	valid_0's binary_logloss: 0.153546
[73]	valid_0's binary_logloss: 0.153527
[74]	valid_0's binary_logloss: 0.153416
[75]	valid_0's binary_logloss: 0.153333
[76]	valid_0's binary_logloss: 0.153071
[77]	valid_0's binary_logloss: 0.152353
[78]	valid_0's binary_logloss: 0.151779
[79]	valid_0's binary_logloss: 0.151382
[80]	valid_0's binary_logloss: 0.151275
[81]	valid_0's binary_logloss: 0.151357
[82]	valid_0's binary_logloss: 0.150978
[83]	valid_0's binary_logloss: 0.150753
[84]	valid_0's binary_logloss: 0.150777
[85]	valid_0's binary_logloss: 0.150556
[86]	valid_0's binary_logloss: 0.150357
[87]	valid_0's binary_logloss: 0.15075
[88]	valid_0's binary_logloss: 0.150539
[89]	valid_0's binary_logloss: 0.150493
[90]	valid_0's binary_logloss: 0.150257
[91]	valid_0's binary_logloss: 0.149923
[92]	valid_0's binary_logloss: 0.149475
[93]	valid_0's binary_logloss: 0.149413
[94]	valid_0's binary_logloss: 0.149119
[95]	valid_0's binary_logloss: 0.148826
[96]	valid_0's binary_logloss: 0.148893
[97]	valid_0's binary_logloss: 0.148604
[98]	valid_0's binary_logloss: 0.148476
[99]	valid_0's binary_logloss: 0.148258
[100]	valid_0's binary_logloss: 0.148023
[101]	valid_0's binary_logloss: 0.147825
[102]	valid_0's binary_logloss: 0.14774
[103]	valid_0's binary_logloss: 0.147339
[104]	valid_0's binary_logloss: 0.147068
[105]	valid_0's binary_logloss: 0.146908
[106]	valid_0's binary_logloss: 0.146574
[107]	valid_0's binary_logloss: 0.146574
[108]	valid_0's binary_logloss: 0.146479
[109]	valid_0's binary_logloss: 0.146334
[110]	valid_0's binary_logloss: 0.146197
[111]	valid_0's binary_logloss: 0.146315
[112]	valid_0's binary_logloss: 0.146271
[113]	valid_0's binary_logloss: 0.146267
[114]	valid_0's binary_logloss: 0.146169
[115]	valid_0's binary_logloss: 0.145951
[116]	valid_0's binary_logloss: 0.145953
[117]	valid_0's binary_logloss: 0.145914
[118]	valid_0's binary_logloss: 0.145968
[119]	valid_0's binary_logloss: 0.145892
[120]	valid_0's binary_logloss: 0.145564
[121]	valid_0's binary_logloss: 0.145634
[122]	valid_0's binary_logloss: 0.145622
[123]	valid_0's binary_logloss: 0.145549
[124]	valid_0's binary_logloss: 0.145316
[125]	valid_0's binary_logloss: 0.145254
[126]	valid_0's binary_logloss: 0.145327
[127]	valid_0's binary_logloss: 0.145163
[128]	valid_0's binary_logloss: 0.145398
[129]	valid_0's binary_logloss: 0.145559
[130]	valid_0's binary_logloss: 0.145538
[131]	valid_0's binary_logloss: 0.145649
[132]	valid_0's binary_logloss: 0.145666
[133]	valid_0's binary_logloss: 0.145905
[134]	valid_0's binary_logloss: 0.145962
[135]	valid_0's binary_logloss: 0.145916
[136]	valid_0's binary_logloss: 0.146181
[137]	valid_0's binary_logloss: 0.146042
[138]	valid_0's binary_logloss: 0.146064
[139]	valid_0's binary_logloss: 0.145887
[140]	valid_0's binary_logloss: 0.145806
[141]	valid_0's binary_logloss: 0.145658
[142]	valid_0's binary_logloss: 0.145523
[143]	valid_0's binary_logloss: 0.145597
[144]	valid_0's binary_logloss: 0.145554
[145]	valid_0's binary_logloss: 0.145375
[146]	valid_0's binary_logloss: 0.145481
[147]	valid_0's binary_logloss: 0.145525
[148]	valid_0's binary_logloss: 0.145663
[149]	valid_0's binary_logloss: 0.145636
[150]	valid_0's binary_logloss: 0.145656
[151]	valid_0's binary_logloss: 0.145702
[152]	valid_0's binary_logloss: 0.145735
[153]	valid_0's binary_logloss: 0.145722
[154]	valid_0's binary_logloss: 0.145677
[155]	valid_0's binary_logloss: 0.145515
[156]	valid_0's binary_logloss: 0.14567

Trening klas:  13%|█▎        | 64/500 [12:04<59:03,  8.13s/klasa, klasa=class_64, F1_klasy=0.6958, F1_macro=0.8700, drzewa=127]




Trening klas:  13%|█▎        | 65/500 [12:04<1:07:59,  9.38s/klasa, klasa=class_64, F1_klasy=0.6958, F1_macro=0.8700, drzewa=127]

[157]	valid_0's binary_logloss: 0.145602
[1]	valid_0's binary_logloss: 0.137559
[2]	valid_0's binary_logloss: 0.128589
[3]	valid_0's binary_logloss: 0.121025
[4]	valid_0's binary_logloss: 0.114344
[5]	valid_0's binary_logloss: 0.1087
[6]	valid_0's binary_logloss: 0.103365
[7]	valid_0's binary_logloss: 0.098386
[8]	valid_0's binary_logloss: 0.0937203
[9]	valid_0's binary_logloss: 0.0894706
[10]	valid_0's binary_logloss: 0.0856055
[11]	valid_0's binary_logloss: 0.0818747
[12]	valid_0's binary_logloss: 0.0783267
[13]	valid_0's binary_logloss: 0.0750203
[14]	valid_0's binary_logloss: 0.0718968
[15]	valid_0's binary_logloss: 0.0691237
[16]	valid_0's binary_logloss: 0.0665101
[17]	valid_0's binary_logloss: 0.0639689
[18]	valid_0's binary_logloss: 0.0615627
[19]	valid_0's binary_logloss: 0.0592688
[20]	valid_0's binary_logloss: 0.0571802
[21]	valid_0's binary_logloss: 0.0551633
[22]	valid_0's binary_logloss: 0.0534247
[23]	valid_0's binary_logloss: 0.051679
[24]	valid_0's binary_logloss: 0.0499876
[25]	valid_0's binary_logloss: 0.0484319
[26]	valid_0's binary_logloss: 0.0469234
[27]	valid_0's binary_logloss: 0.045523
[28]	valid_0's binary_logloss: 0.0441716
[29]	valid_0's binary_logloss: 0.0428948
[30]	valid_0's binary_logloss: 0.0416203
[31]	valid_0's binary_logloss: 0.0404302
[32]	valid_0's binary_logloss: 0.0393987
[33]	valid_0's binary_logloss: 0.0383095
[34]	valid_0's binary_logloss: 0.0373058
[35]	valid_0's binary_logloss: 0.036293
[36]	valid_0's binary_logloss: 0.035387
[37]	valid_0's binary_logloss: 0.0345244
[38]	valid_0's binary_logloss: 0.0337473
[39]	valid_0's binary_logloss: 0.033042
[40]	valid_0's binary_logloss: 0.0322433
[41]	valid_0's binary_logloss: 0.0315127
[42]	valid_0's binary_logloss: 0.0307507
[43]	valid_0's binary_logloss: 0.0300564
[44]	valid_0's binary_logloss: 0.0294424
[45]	valid_0's binary_logloss: 0.0289561
[46]	valid_0's binary_logloss: 0.0283834
[47]	valid_0's binary_logloss: 0.0279046
[48]	valid_0's binary_logloss: 0.0274198
[49]	valid_0's binary_logloss: 0.0269599
[50]	valid_0's binary_logloss: 0.026626
[51]	valid_0's binary_logloss: 0.0262839
[52]	valid_0's binary_logloss: 0.0259494
[53]	valid_0's binary_logloss: 0.0256113
[54]	valid_0's binary_logloss: 0.0252152
[55]	valid_0's binary_logloss: 0.0248797
[56]	valid_0's binary_logloss: 0.0246757
[57]	valid_0's binary_logloss: 0.0243802
[58]	valid_0's binary_logloss: 0.0241516
[59]	valid_0's binary_logloss: 0.0239427
[60]	valid_0's binary_logloss: 0.0237578
[61]	valid_0's binary_logloss: 0.0234599
[62]	valid_0's binary_logloss: 0.0231621
[63]	valid_0's binary_logloss: 0.0229161
[64]	valid_0's binary_logloss: 0.0226887
[65]	valid_0's binary_logloss: 0.0225353
[66]	valid_0's binary_logloss: 0.0223763
[67]	valid_0's binary_logloss: 0.0222223
[68]	valid_0's binary_logloss: 0.0220447
[69]	valid_0's binary_logloss: 0.021874
[70]	valid_0's binary_logloss: 0.0217927
[71]	valid_0's binary_logloss: 0.0216351
[72]	valid_0's binary_logloss: 0.0215161
[73]	valid_0's binary_logloss: 0.0213549
[74]	valid_0's binary_logloss: 0.0211588
[75]	valid_0's binary_logloss: 0.0210247
[76]	valid_0's binary_logloss: 0.0209034
[77]	valid_0's binary_logloss: 0.020869
[78]	valid_0's binary_logloss: 0.0207849
[79]	valid_0's binary_logloss: 0.020704
[80]	valid_0's binary_logloss: 0.0205649
[81]	valid_0's binary_logloss: 0.0203813
[82]	valid_0's binary_logloss: 0.0202551
[83]	valid_0's binary_logloss: 0.0200919
[84]	valid_0's binary_logloss: 0.0199091
[85]	valid_0's binary_logloss: 0.0197739
[86]	valid_0's binary_logloss: 0.0197057
[87]	valid_0's binary_logloss: 0.0196868
[88]	valid_0's binary_logloss: 0.0196676
[89]	valid_0's binary_logloss: 0.0196841
[90]	valid_0's binary_logloss: 0.0196518
[91]	valid_0's binary_logloss: 0.0195701
[92]	valid_0's binary_logloss: 0.0195841
[93]	valid_0's binary_logloss: 0.0195034
[94]	valid_0's binary_logloss: 0.0193872
[95]	valid_0's binary_logloss: 0.0193612
[96]	valid_0's binary_logloss: 0.0192549
[97]	valid_0's binary_logloss: 0.0192275
[98]	valid_0's binary_logloss: 0.0191596
[99]	valid_0's binary_logloss: 0.0190935
[100]	valid_0's binary_logloss: 0.0190173
[101]	valid_0's binary_logloss: 0.0188975
[102]	valid_0's binary_logloss: 0.0188533
[103]	valid_0's binary_logloss: 0.0187854
[104]	valid_0's binary_logloss: 0.0187803
[105]	valid_0's binary_logloss: 0.0187403
[106]	valid_0's binary_logloss: 0.018762
[107]	valid_0's binary_logloss: 0.0188236
[108]	valid_0's binary_logloss: 0.0188428
[109]	valid_0's binary_logloss: 0.0188825
[110]	valid_0's binary_logloss: 0.0188901
[111]	valid_0's binary_logloss: 0.0188498
[112]	valid_0's binary_logloss: 0.0188019
[113]	valid_0's binary_logloss: 0.0186725
[114]	valid_0's binary_logloss: 0.0186303
[115]	valid_0's binary_logloss: 0.018544
[116]	valid_0's binary_logloss: 0.0185788
[117]	valid_0's binary_logloss: 0.0185274
[118]	valid_0's binary_logloss: 0.0184717
[119]	valid_0's binary_logloss: 0.0185417
[120]	valid_0's binary_logloss: 0.018488
[121]	valid_0's binary_logloss: 0.0183731
[122]	valid_0's binary_logloss: 0.0182788
[123]	valid_0's binary_logloss: 0.0182134
[124]	valid_0's binary_logloss: 0.0182322
[125]	valid_0's binary_logloss: 0.0182219
[126]	valid_0's binary_logloss: 0.0182253
[127]	valid_0's binary_logloss: 0.0182417
[128]	valid_0's binary_logloss: 0.0182673
[129]	valid_0's binary_logloss: 0.0182902
[130]	valid_0's binary_logloss: 0.0183548
[131]	valid_0's binary_logloss: 0.0184025
[132]	valid_0's binary_logloss: 0.0185286
[133]	valid_0's binary_logloss: 0.0185759
[134]	valid_0's binary_logloss: 0.0186418
[135]	valid_0's binary_logloss: 0.0187204
[136]	valid_0's binary_logloss: 0.0186967
[137]	valid_0's binary_logloss: 0.0186563
[138]	valid_0's binary_logloss: 0.0186953
[139]	valid_0's binary_logloss: 0.0186938
[140]	valid_0's binary_logloss: 0.018582
[141]	valid_0's binary_logloss: 0.0186187
[142]	valid_0's binary_logloss: 0.0186565
[143]	valid_0's binary_logloss: 0.0186525
[144]	valid_0's binary_logloss: 0.0186829
[145]	valid_0's binary_logloss: 0.0187222
[146]	valid_0's binary_logloss: 0.0188194
[147]	valid_0's binary_logloss: 0.0188592
[148]	valid_0's binary_logloss: 0.0189374
[149]	valid_0's binary_logloss: 0.0188594
[150]	valid_0's binary_logloss: 0.0188712

Trening klas:  13%|█▎        | 65/500 [12:13<1:07:59,  9.38s/klasa, klasa=class_65, F1_klasy=0.8140, F1_macro=0.8692, drzewa=123]




Trening klas:  13%|█▎        | 66/500 [12:13<1:08:19,  9.45s/klasa, klasa=class_65, F1_klasy=0.8140, F1_macro=0.8692, drzewa=123]

[151]	valid_0's binary_logloss: 0.0188369
[152]	valid_0's binary_logloss: 0.018857
[153]	valid_0's binary_logloss: 0.0187454
[1]	valid_0's binary_logloss: 0.134968
[2]	valid_0's binary_logloss: 0.126047
[3]	valid_0's binary_logloss: 0.118669
[4]	valid_0's binary_logloss: 0.112159
[5]	valid_0's binary_logloss: 0.106442
[6]	valid_0's binary_logloss: 0.10117
[7]	valid_0's binary_logloss: 0.0961898
[8]	valid_0's binary_logloss: 0.0916709
[9]	valid_0's binary_logloss: 0.0874375
[10]	valid_0's binary_logloss: 0.0837691
[11]	valid_0's binary_logloss: 0.0800733
[12]	valid_0's binary_logloss: 0.0765176
[13]	valid_0's binary_logloss: 0.0733652
[14]	valid_0's binary_logloss: 0.0703826
[15]	valid_0's binary_logloss: 0.0676616
[16]	valid_0's binary_logloss: 0.0649363
[17]	valid_0's binary_logloss: 0.0623963
[18]	valid_0's binary_logloss: 0.0600457
[19]	valid_0's binary_logloss: 0.0578377
[20]	valid_0's binary_logloss: 0.0557256
[21]	valid_0's binary_logloss: 0.0537373
[22]	valid_0's binary_logloss: 0.051953
[23]	valid_0's binary_logloss: 0.0502173
[24]	valid_0's binary_logloss: 0.0484999
[25]	valid_0's binary_logloss: 0.0469386
[26]	valid_0's binary_logloss: 0.0455178
[27]	valid_0's binary_logloss: 0.044169
[28]	valid_0's binary_logloss: 0.0428434
[29]	valid_0's binary_logloss: 0.0415504
[30]	valid_0's binary_logloss: 0.0404185
[31]	valid_0's binary_logloss: 0.0392908
[32]	valid_0's binary_logloss: 0.0382394
[33]	valid_0's binary_logloss: 0.0371679
[34]	valid_0's binary_logloss: 0.0362384
[35]	valid_0's binary_logloss: 0.0352574
[36]	valid_0's binary_logloss: 0.0343786
[37]	valid_0's binary_logloss: 0.0334515
[38]	valid_0's binary_logloss: 0.0327218
[39]	valid_0's binary_logloss: 0.0318852
[40]	valid_0's binary_logloss: 0.0310972
[41]	valid_0's binary_logloss: 0.0303335
[42]	valid_0's binary_logloss: 0.029575
[43]	valid_0's binary_logloss: 0.0289621
[44]	valid_0's binary_logloss: 0.0283019
[45]	valid_0's binary_logloss: 0.0276664
[46]	valid_0's binary_logloss: 0.0271982
[47]	valid_0's binary_logloss: 0.0266962
[48]	valid_0's binary_logloss: 0.0262857
[49]	valid_0's binary_logloss: 0.0258625
[50]	valid_0's binary_logloss: 0.0254669
[51]	valid_0's binary_logloss: 0.0250904
[52]	valid_0's binary_logloss: 0.0247143
[53]	valid_0's binary_logloss: 0.0243481
[54]	valid_0's binary_logloss: 0.0240536
[55]	valid_0's binary_logloss: 0.0237427
[56]	valid_0's binary_logloss: 0.0235212
[57]	valid_0's binary_logloss: 0.0232627
[58]	valid_0's binary_logloss: 0.0231049
[59]	valid_0's binary_logloss: 0.0230018
[60]	valid_0's binary_logloss: 0.0228516
[61]	valid_0's binary_logloss: 0.0226432
[62]	valid_0's binary_logloss: 0.0224179
[63]	valid_0's binary_logloss: 0.0222282
[64]	valid_0's binary_logloss: 0.0220388
[65]	valid_0's binary_logloss: 0.0218641
[66]	valid_0's binary_logloss: 0.0216568
[67]	valid_0's binary_logloss: 0.0214556
[68]	valid_0's binary_logloss: 0.0213005
[69]	valid_0's binary_logloss: 0.0211562
[70]	valid_0's binary_logloss: 0.0209726
[71]	valid_0's binary_logloss: 0.0208419
[72]	valid_0's binary_logloss: 0.0207555
[73]	valid_0's binary_logloss: 0.0205987
[74]	valid_0's binary_logloss: 0.0202654
[75]	valid_0's binary_logloss: 0.0201657
[76]	valid_0's binary_logloss: 0.0200214
[77]	valid_0's binary_logloss: 0.0197928
[78]	valid_0's binary_logloss: 0.0196098
[79]	valid_0's binary_logloss: 0.0195461
[80]	valid_0's binary_logloss: 0.0193419
[81]	valid_0's binary_logloss: 0.019233
[82]	valid_0's binary_logloss: 0.0190824
[83]	valid_0's binary_logloss: 0.018944
[84]	valid_0's binary_logloss: 0.0188226
[85]	valid_0's binary_logloss: 0.0187386
[86]	valid_0's binary_logloss: 0.018646
[87]	valid_0's binary_logloss: 0.0185561
[88]	valid_0's binary_logloss: 0.0184958
[89]	valid_0's binary_logloss: 0.0184828
[90]	valid_0's binary_logloss: 0.0183633
[91]	valid_0's binary_logloss: 0.0182846
[92]	valid_0's binary_logloss: 0.0182459
[93]	valid_0's binary_logloss: 0.0181975
[94]	valid_0's binary_logloss: 0.0181849
[95]	valid_0's binary_logloss: 0.0181988
[96]	valid_0's binary_logloss: 0.0180845
[97]	valid_0's binary_logloss: 0.0181078
[98]	valid_0's binary_logloss: 0.0180069
[99]	valid_0's binary_logloss: 0.0179205
[100]	valid_0's binary_logloss: 0.0178817
[101]	valid_0's binary_logloss: 0.0178753
[102]	valid_0's binary_logloss: 0.0178553
[103]	valid_0's binary_logloss: 0.0179261
[104]	valid_0's binary_logloss: 0.0178774
[105]	valid_0's binary_logloss: 0.0179271
[106]	valid_0's binary_logloss: 0.0180794
[107]	valid_0's binary_logloss: 0.0181644
[108]	valid_0's binary_logloss: 0.0182294
[109]	valid_0's binary_logloss: 0.0182538
[110]	valid_0's binary_logloss: 0.0182113
[111]	valid_0's binary_logloss: 0.0182024
[112]	valid_0's binary_logloss: 0.0182143
[113]	valid_0's binary_logloss: 0.01815
[114]	valid_0's binary_logloss: 0.018224
[115]	valid_0's binary_logloss: 0.0182759
[116]	valid_0's binary_logloss: 0.0181485
[117]	valid_0's binary_logloss: 0.018124
[118]	valid_0's binary_logloss: 0.0181361
[119]	valid_0's binary_logloss: 0.0181488
[120]	valid_0's binary_logloss: 0.0181313
[121]	valid_0's binary_logloss: 0.0180571
[122]	valid_0's binary_logloss: 0.0179739
[123]	valid_0's binary_logloss: 0.017878
[124]	valid_0's binary_logloss: 0.0177874
[125]	valid_0's binary_logloss: 0.0178102
[126]	valid_0's binary_logloss: 0.0179217
[127]	valid_0's binary_logloss: 0.017983
[128]	valid_0's binary_logloss: 0.0180816
[129]	valid_0's binary_logloss: 0.0182095
[130]	valid_0's binary_logloss: 0.0182445
[131]	valid_0's binary_logloss: 0.0182658
[132]	valid_0's binary_logloss: 0.0183146
[133]	valid_0's binary_logloss: 0.0183266
[134]	valid_0's binary_logloss: 0.0184408
[135]	valid_0's binary_logloss: 0.0184295
[136]	valid_0's binary_logloss: 0.0184194
[137]	valid_0's binary_logloss: 0.0183348
[138]	valid_0's binary_logloss: 0.0183151
[139]	valid_0's binary_logloss: 0.0182807
[140]	valid_0's binary_logloss: 0.0182764
[141]	valid_0's binary_logloss: 0.0182776
[142]	valid_0's binary_logloss: 0.0182959
[143]	valid_0's binary_logloss: 0.0182837
[144]	valid_0's binary_logloss: 0.0183212
[145]	valid_0's binary_logloss: 0.0184006
[146]	valid_0's binary_logloss: 0.0184345
[147]	valid_0's binary_logloss: 0.0184865
[148]	valid_0's binary_logloss: 0.0185285
[149]	valid_0's binary_logloss: 0.0185652
[150]	valid_0's binary_logloss: 0.018517
[151]	valid_0's binary_logloss: 0.0185233
[152]	valid_0's binary_logloss: 0.0185015

Trening klas:  13%|█▎        | 66/500 [12:23<1:08:19,  9.45s/klasa, klasa=class_66, F1_klasy=0.8156, F1_macro=0.8684, drzewa=124]




Trening klas:  13%|█▎        | 67/500 [12:23<1:09:02,  9.57s/klasa, klasa=class_66, F1_klasy=0.8156, F1_macro=0.8684, drzewa=124]

[153]	valid_0's binary_logloss: 0.0184683
[154]	valid_0's binary_logloss: 0.0184757
[1]	valid_0's binary_logloss: 0.449078
[2]	valid_0's binary_logloss: 0.41065
[3]	valid_0's binary_logloss: 0.38518
[4]	valid_0's binary_logloss: 0.367026
[5]	valid_0's binary_logloss: 0.352972
[6]	valid_0's binary_logloss: 0.341921
[7]	valid_0's binary_logloss: 0.330902
[8]	valid_0's binary_logloss: 0.323173
[9]	valid_0's binary_logloss: 0.314029
[10]	valid_0's binary_logloss: 0.307769
[11]	valid_0's binary_logloss: 0.302644
[12]	valid_0's binary_logloss: 0.298035
[13]	valid_0's binary_logloss: 0.293607
[14]	valid_0's binary_logloss: 0.288792
[15]	valid_0's binary_logloss: 0.285646
[16]	valid_0's binary_logloss: 0.282568
[17]	valid_0's binary_logloss: 0.28055
[18]	valid_0's binary_logloss: 0.278232
[19]	valid_0's binary_logloss: 0.275555
[20]	valid_0's binary_logloss: 0.273578
[21]	valid_0's binary_logloss: 0.271082
[22]	valid_0's binary_logloss: 0.26995
[23]	valid_0's binary_logloss: 0.269249
[24]	valid_0's binary_logloss: 0.268223
[25]	valid_0's binary_logloss: 0.265993
[26]	valid_0's binary_logloss: 0.265415
[27]	valid_0's binary_logloss: 0.264075
[28]	valid_0's binary_logloss: 0.263554
[29]	valid_0's binary_logloss: 0.262527
[30]	valid_0's binary_logloss: 0.262432
[31]	valid_0's binary_logloss: 0.261648
[32]	valid_0's binary_logloss: 0.261122
[33]	valid_0's binary_logloss: 0.260366
[34]	valid_0's binary_logloss: 0.260199
[35]	valid_0's binary_logloss: 0.259641
[36]	valid_0's binary_logloss: 0.258982
[37]	valid_0's binary_logloss: 0.258618
[38]	valid_0's binary_logloss: 0.258265
[39]	valid_0's binary_logloss: 0.257462
[40]	valid_0's binary_logloss: 0.256698
[41]	valid_0's binary_logloss: 0.257238
[42]	valid_0's binary_logloss: 0.256291
[43]	valid_0's binary_logloss: 0.256505
[44]	valid_0's binary_logloss: 0.256341
[45]	valid_0's binary_logloss: 0.256756
[46]	valid_0's binary_logloss: 0.256781
[47]	valid_0's binary_logloss: 0.256697
[48]	valid_0's binary_logloss: 0.256677
[49]	valid_0's binary_logloss: 0.256338
[50]	valid_0's binary_logloss: 0.256595
[51]	valid_0's binary_logloss: 0.25572
[52]	valid_0's binary_logloss: 0.255084
[53]	valid_0's binary_logloss: 0.255051
[54]	valid_0's binary_logloss: 0.254446
[55]	valid_0's binary_logloss: 0.254529
[56]	valid_0's binary_logloss: 0.254101
[57]	valid_0's binary_logloss: 0.254263
[58]	valid_0's binary_logloss: 0.25394
[59]	valid_0's binary_logloss: 0.254121
[60]	valid_0's binary_logloss: 0.253801
[61]	valid_0's binary_logloss: 0.254004
[62]	valid_0's binary_logloss: 0.254141
[63]	valid_0's binary_logloss: 0.254301
[64]	valid_0's binary_logloss: 0.254561
[65]	valid_0's binary_logloss: 0.254461
[66]	valid_0's binary_logloss: 0.254419
[67]	valid_0's binary_logloss: 0.254831
[68]	valid_0's binary_logloss: 0.255558
[69]	valid_0's binary_logloss: 0.255378
[70]	valid_0's binary_logloss: 0.255311
[71]	valid_0's binary_logloss: 0.255511
[72]	valid_0's binary_logloss: 0.256376
[73]	valid_0's binary_logloss: 0.257317
[74]	valid_0's binary_logloss: 0.257724
[75]	valid_0's binary_logloss: 0.258094
[76]	valid_0's binary_logloss: 0.258016
[77]	valid_0's binary_logloss: 0.257908
[78]	valid_0's binary_logloss: 0.257867
[79]	valid_0's binary_logloss: 0.257881
[80]	valid_0's binary_logloss: 0.25769
[81]	valid_0's binary_logloss: 0.257883
[82]	valid_0's binary_logloss: 0.257918
[83]	valid_0's binary_logloss: 0.257946
[84]	valid_0's binary_logloss: 0.257832
[85]	valid_0's binary_logloss: 0.258383
[86]	valid_0's binary_logloss: 0.258728
[87]	valid_0's binary_logloss: 0.259138

Trening klas:  13%|█▎        | 67/500 [12:31<1:09:02,  9.57s/klasa, klasa=class_67, F1_klasy=0.6863, F1_macro=0.8657, drzewa=60]




Trening klas:  14%|█▎        | 68/500 [12:31<1:04:23,  8.94s/klasa, klasa=class_67, F1_klasy=0.6863, F1_macro=0.8657, drzewa=60]

[88]	valid_0's binary_logloss: 0.259432
[89]	valid_0's binary_logloss: 0.259624
[90]	valid_0's binary_logloss: 0.259911
[1]	valid_0's binary_logloss: 0.448737
[2]	valid_0's binary_logloss: 0.411563
[3]	valid_0's binary_logloss: 0.385506
[4]	valid_0's binary_logloss: 0.366322
[5]	valid_0's binary_logloss: 0.353016
[6]	valid_0's binary_logloss: 0.341116
[7]	valid_0's binary_logloss: 0.329846
[8]	valid_0's binary_logloss: 0.321965
[9]	valid_0's binary_logloss: 0.314151
[10]	valid_0's binary_logloss: 0.307835
[11]	valid_0's binary_logloss: 0.302284
[12]	valid_0's binary_logloss: 0.297439
[13]	valid_0's binary_logloss: 0.29254
[14]	valid_0's binary_logloss: 0.288524
[15]	valid_0's binary_logloss: 0.284789
[16]	valid_0's binary_logloss: 0.281762
[17]	valid_0's binary_logloss: 0.278953
[18]	valid_0's binary_logloss: 0.276673
[19]	valid_0's binary_logloss: 0.274392
[20]	valid_0's binary_logloss: 0.271931
[21]	valid_0's binary_logloss: 0.27032
[22]	valid_0's binary_logloss: 0.268333
[23]	valid_0's binary_logloss: 0.267144
[24]	valid_0's binary_logloss: 0.26599
[25]	valid_0's binary_logloss: 0.264211
[26]	valid_0's binary_logloss: 0.262674
[27]	valid_0's binary_logloss: 0.260915
[28]	valid_0's binary_logloss: 0.259205
[29]	valid_0's binary_logloss: 0.258198
[30]	valid_0's binary_logloss: 0.257722
[31]	valid_0's binary_logloss: 0.257208
[32]	valid_0's binary_logloss: 0.256409
[33]	valid_0's binary_logloss: 0.255818
[34]	valid_0's binary_logloss: 0.254858
[35]	valid_0's binary_logloss: 0.254201
[36]	valid_0's binary_logloss: 0.252997
[37]	valid_0's binary_logloss: 0.253068
[38]	valid_0's binary_logloss: 0.252166
[39]	valid_0's binary_logloss: 0.251523
[40]	valid_0's binary_logloss: 0.250884
[41]	valid_0's binary_logloss: 0.251363
[42]	valid_0's binary_logloss: 0.251169
[43]	valid_0's binary_logloss: 0.251687
[44]	valid_0's binary_logloss: 0.251832
[45]	valid_0's binary_logloss: 0.252025
[46]	valid_0's binary_logloss: 0.252029
[47]	valid_0's binary_logloss: 0.252084
[48]	valid_0's binary_logloss: 0.252144
[49]	valid_0's binary_logloss: 0.252036
[50]	valid_0's binary_logloss: 0.251857
[51]	valid_0's binary_logloss: 0.251538
[52]	valid_0's binary_logloss: 0.251673
[53]	valid_0's binary_logloss: 0.251856
[54]	valid_0's binary_logloss: 0.251133
[55]	valid_0's binary_logloss: 0.251035
[56]	valid_0's binary_logloss: 0.250663
[57]	valid_0's binary_logloss: 0.250475
[58]	valid_0's binary_logloss: 0.24987
[59]	valid_0's binary_logloss: 0.249881
[60]	valid_0's binary_logloss: 0.249911
[61]	valid_0's binary_logloss: 0.249824
[62]	valid_0's binary_logloss: 0.249861
[63]	valid_0's binary_logloss: 0.250133
[64]	valid_0's binary_logloss: 0.250297
[65]	valid_0's binary_logloss: 0.250709
[66]	valid_0's binary_logloss: 0.250725
[67]	valid_0's binary_logloss: 0.250731
[68]	valid_0's binary_logloss: 0.250649
[69]	valid_0's binary_logloss: 0.250784
[70]	valid_0's binary_logloss: 0.251371
[71]	valid_0's binary_logloss: 0.251775
[72]	valid_0's binary_logloss: 0.252343
[73]	valid_0's binary_logloss: 0.253022
[74]	valid_0's binary_logloss: 0.253793
[75]	valid_0's binary_logloss: 0.254235
[76]	valid_0's binary_logloss: 0.254891
[77]	valid_0's binary_logloss: 0.254435
[78]	valid_0's binary_logloss: 0.254578
[79]	valid_0's binary_logloss: 0.254868
[80]	valid_0's binary_logloss: 0.254815
[81]	valid_0's binary_logloss: 0.25514
[82]	valid_0's binary_logloss: 0.255677
[83]	valid_0's binary_logloss: 0.256205
[84]	valid_0's binary_logloss: 0.256711
[85]	valid_0's binary_logloss: 0.257398
[86]	valid_0's binary_logloss: 0.257503
[87]	valid_0's binary_logloss: 0.25812
[88]	valid_0's binary_logloss: 0.258464
[89]	valid_0's binary_logloss: 0.258923

Trening klas:  14%|█▎        | 68/500 [12:38<1:04:23,  8.94s/klasa, klasa=class_68, F1_klasy=0.6942, F1_macro=0.8632, drzewa=61]




Trening klas:  14%|█▍        | 69/500 [12:38<1:00:48,  8.47s/klasa, klasa=class_68, F1_klasy=0.6942, F1_macro=0.8632, drzewa=61]

[90]	valid_0's binary_logloss: 0.259359
[91]	valid_0's binary_logloss: 0.259692
[1]	valid_0's binary_logloss: 0.448447
[2]	valid_0's binary_logloss: 0.411331
[3]	valid_0's binary_logloss: 0.385316
[4]	valid_0's binary_logloss: 0.366165
[5]	valid_0's binary_logloss: 0.352887
[6]	valid_0's binary_logloss: 0.341013
[7]	valid_0's binary_logloss: 0.329764
[8]	valid_0's binary_logloss: 0.321904
[9]	valid_0's binary_logloss: 0.314107
[10]	valid_0's binary_logloss: 0.307809
[11]	valid_0's binary_logloss: 0.302274
[12]	valid_0's binary_logloss: 0.297443
[13]	valid_0's binary_logloss: 0.292559
[14]	valid_0's binary_logloss: 0.288556
[15]	valid_0's binary_logloss: 0.284835
[16]	valid_0's binary_logloss: 0.281821
[17]	valid_0's binary_logloss: 0.279024
[18]	valid_0's binary_logloss: 0.276756
[19]	valid_0's binary_logloss: 0.274486
[20]	valid_0's binary_logloss: 0.272036
[21]	valid_0's binary_logloss: 0.270436
[22]	valid_0's binary_logloss: 0.26846
[23]	valid_0's binary_logloss: 0.26728
[24]	valid_0's binary_logloss: 0.266137
[25]	valid_0's binary_logloss: 0.264368
[26]	valid_0's binary_logloss: 0.26284
[27]	valid_0's binary_logloss: 0.261091
[28]	valid_0's binary_logloss: 0.25939
[29]	valid_0's binary_logloss: 0.258393
[30]	valid_0's binary_logloss: 0.257926
[31]	valid_0's binary_logloss: 0.257421
[32]	valid_0's binary_logloss: 0.256631
[33]	valid_0's binary_logloss: 0.256048
[34]	valid_0's binary_logloss: 0.255097
[35]	valid_0's binary_logloss: 0.254448
[36]	valid_0's binary_logloss: 0.253252
[37]	valid_0's binary_logloss: 0.253332
[38]	valid_0's binary_logloss: 0.252437
[39]	valid_0's binary_logloss: 0.251803
[40]	valid_0's binary_logloss: 0.251172
[41]	valid_0's binary_logloss: 0.251659
[42]	valid_0's binary_logloss: 0.251473
[43]	valid_0's binary_logloss: 0.251998
[44]	valid_0's binary_logloss: 0.252151
[45]	valid_0's binary_logloss: 0.252352
[46]	valid_0's binary_logloss: 0.252363
[47]	valid_0's binary_logloss: 0.252426
[48]	valid_0's binary_logloss: 0.252493
[49]	valid_0's binary_logloss: 0.252393
[50]	valid_0's binary_logloss: 0.252221
[51]	valid_0's binary_logloss: 0.25191
[52]	valid_0's binary_logloss: 0.252052
[53]	valid_0's binary_logloss: 0.252242
[54]	valid_0's binary_logloss: 0.251527
[55]	valid_0's binary_logloss: 0.251436
[56]	valid_0's binary_logloss: 0.251071
[57]	valid_0's binary_logloss: 0.25089
[58]	valid_0's binary_logloss: 0.250292
[59]	valid_0's binary_logloss: 0.25031
[60]	valid_0's binary_logloss: 0.250347
[61]	valid_0's binary_logloss: 0.250267
[62]	valid_0's binary_logloss: 0.250311
[63]	valid_0's binary_logloss: 0.250589
[64]	valid_0's binary_logloss: 0.25076
[65]	valid_0's binary_logloss: 0.251179
[66]	valid_0's binary_logloss: 0.251201
[67]	valid_0's binary_logloss: 0.251213
[68]	valid_0's binary_logloss: 0.251138
[69]	valid_0's binary_logloss: 0.251279
[70]	valid_0's binary_logloss: 0.251872
[71]	valid_0's binary_logloss: 0.252281
[72]	valid_0's binary_logloss: 0.252855
[73]	valid_0's binary_logloss: 0.253541
[74]	valid_0's binary_logloss: 0.254318
[75]	valid_0's binary_logloss: 0.254766
[76]	valid_0's binary_logloss: 0.255428
[77]	valid_0's binary_logloss: 0.254978
[78]	valid_0's binary_logloss: 0.255128
[79]	valid_0's binary_logloss: 0.255425
[80]	valid_0's binary_logloss: 0.255377
[81]	valid_0's binary_logloss: 0.255708
[82]	valid_0's binary_logloss: 0.256251
[83]	valid_0's binary_logloss: 0.256786
[84]	valid_0's binary_logloss: 0.257297
[85]	valid_0's binary_logloss: 0.25799
[86]	valid_0's binary_logloss: 0.258101
[87]	valid_0's binary_logloss: 0.258722
[88]	valid_0's binary_logloss: 0.259072
[89]	valid_0's binary_logloss: 0.259536
[90]	valid_0's binary_logloss: 0.259976
[91]	valid_0's binary_logloss: 0.260315

Trening klas:  14%|█▍        | 69/500 [12:45<1:00:48,  8.47s/klasa, klasa=class_69, F1_klasy=0.6936, F1_macro=0.8608, drzewa=61]




Trening klas:  14%|█▍        | 70/500 [12:45<57:54,  8.08s/klasa, klasa=class_69, F1_klasy=0.6936, F1_macro=0.8608, drzewa=61]

[1]	valid_0's binary_logloss: 0.359594
[2]	valid_0's binary_logloss: 0.324132
[3]	valid_0's binary_logloss: 0.301036
[4]	valid_0's binary_logloss: 0.284133
[5]	valid_0's binary_logloss: 0.27107
[6]	valid_0's binary_logloss: 0.259015
[7]	valid_0's binary_logloss: 0.248876
[8]	valid_0's binary_logloss: 0.241414
[9]	valid_0's binary_logloss: 0.233635
[10]	valid_0's binary_logloss: 0.226994
[11]	valid_0's binary_logloss: 0.221683
[12]	valid_0's binary_logloss: 0.217406
[13]	valid_0's binary_logloss: 0.21314
[14]	valid_0's binary_logloss: 0.20982
[15]	valid_0's binary_logloss: 0.20584
[16]	valid_0's binary_logloss: 0.202482
[17]	valid_0's binary_logloss: 0.199501
[18]	valid_0's binary_logloss: 0.19648
[19]	valid_0's binary_logloss: 0.194597
[20]	valid_0's binary_logloss: 0.192236
[21]	valid_0's binary_logloss: 0.190014
[22]	valid_0's binary_logloss: 0.187901
[23]	valid_0's binary_logloss: 0.186213
[24]	valid_0's binary_logloss: 0.184823
[25]	valid_0's binary_logloss: 0.183221
[26]	valid_0's binary_logloss: 0.181979
[27]	valid_0's binary_logloss: 0.181066
[28]	valid_0's binary_logloss: 0.179584
[29]	valid_0's binary_logloss: 0.178349
[30]	valid_0's binary_logloss: 0.177569
[31]	valid_0's binary_logloss: 0.176549
[32]	valid_0's binary_logloss: 0.175641
[33]	valid_0's binary_logloss: 0.175342
[34]	valid_0's binary_logloss: 0.17501
[35]	valid_0's binary_logloss: 0.173978
[36]	valid_0's binary_logloss: 0.173287
[37]	valid_0's binary_logloss: 0.172338
[38]	valid_0's binary_logloss: 0.171595
[39]	valid_0's binary_logloss: 0.171078
[40]	valid_0's binary_logloss: 0.170564
[41]	valid_0's binary_logloss: 0.170268
[42]	valid_0's binary_logloss: 0.169623
[43]	valid_0's binary_logloss: 0.169182
[44]	valid_0's binary_logloss: 0.16892
[45]	valid_0's binary_logloss: 0.168028
[46]	valid_0's binary_logloss: 0.16787
[47]	valid_0's binary_logloss: 0.167798
[48]	valid_0's binary_logloss: 0.167827
[49]	valid_0's binary_logloss: 0.167467
[50]	valid_0's binary_logloss: 0.167171
[51]	valid_0's binary_logloss: 0.167038
[52]	valid_0's binary_logloss: 0.166942
[53]	valid_0's binary_logloss: 0.166488
[54]	valid_0's binary_logloss: 0.166259
[55]	valid_0's binary_logloss: 0.165992
[56]	valid_0's binary_logloss: 0.166011
[57]	valid_0's binary_logloss: 0.166073
[58]	valid_0's binary_logloss: 0.165986
[59]	valid_0's binary_logloss: 0.165769
[60]	valid_0's binary_logloss: 0.165555
[61]	valid_0's binary_logloss: 0.16533
[62]	valid_0's binary_logloss: 0.165181
[63]	valid_0's binary_logloss: 0.16498
[64]	valid_0's binary_logloss: 0.16513
[65]	valid_0's binary_logloss: 0.164731
[66]	valid_0's binary_logloss: 0.164789
[67]	valid_0's binary_logloss: 0.164587
[68]	valid_0's binary_logloss: 0.164714
[69]	valid_0's binary_logloss: 0.164837
[70]	valid_0's binary_logloss: 0.164621
[71]	valid_0's binary_logloss: 0.164798
[72]	valid_0's binary_logloss: 0.164883
[73]	valid_0's binary_logloss: 0.165094
[74]	valid_0's binary_logloss: 0.165259
[75]	valid_0's binary_logloss: 0.165384
[76]	valid_0's binary_logloss: 0.165338
[77]	valid_0's binary_logloss: 0.165291
[78]	valid_0's binary_logloss: 0.165446
[79]	valid_0's binary_logloss: 0.165248
[80]	valid_0's binary_logloss: 0.165403
[81]	valid_0's binary_logloss: 0.16564
[82]	valid_0's binary_logloss: 0.165441
[83]	valid_0's binary_logloss: 0.165439
[84]	valid_0's binary_logloss: 0.165708
[85]	valid_0's binary_logloss: 0.165604
[86]	valid_0's binary_logloss: 0.165564
[87]	valid_0's binary_logloss: 0.165711
[88]	valid_0's binary_logloss: 0.165831
[89]	valid_0's binary_logloss: 0.165785
[90]	valid_0's binary_logloss: 0.165663
[91]	valid_0's binary_logloss: 0.165513
[92]	valid_0's binary_logloss: 0.165333
[93]	valid_0's binary_logloss: 0.165188
[94]	valid_0's binary_logloss: 0.165191
[95]	valid_0's binary_logloss: 0.165407

Trening klas:  14%|█▍        | 70/500 [12:52<57:54,  8.08s/klasa, klasa=class_70, F1_klasy=0.7789, F1_macro=0.8596, drzewa=67]




Trening klas:  14%|█▍        | 71/500 [12:52<56:09,  7.85s/klasa, klasa=class_70, F1_klasy=0.7789, F1_macro=0.8596, drzewa=67]

[96]	valid_0's binary_logloss: 0.165117
[97]	valid_0's binary_logloss: 0.164957
[1]	valid_0's binary_logloss: 0.322648
[2]	valid_0's binary_logloss: 0.288472
[3]	valid_0's binary_logloss: 0.265714
[4]	valid_0's binary_logloss: 0.247705
[5]	valid_0's binary_logloss: 0.233608
[6]	valid_0's binary_logloss: 0.222139
[7]	valid_0's binary_logloss: 0.212479
[8]	valid_0's binary_logloss: 0.204465
[9]	valid_0's binary_logloss: 0.197114
[10]	valid_0's binary_logloss: 0.190375
[11]	valid_0's binary_logloss: 0.184728
[12]	valid_0's binary_logloss: 0.179827
[13]	valid_0's binary_logloss: 0.17533
[14]	valid_0's binary_logloss: 0.171181
[15]	valid_0's binary_logloss: 0.167486
[16]	valid_0's binary_logloss: 0.163587
[17]	valid_0's binary_logloss: 0.160409
[18]	valid_0's binary_logloss: 0.157007
[19]	valid_0's binary_logloss: 0.154024
[20]	valid_0's binary_logloss: 0.151201
[21]	valid_0's binary_logloss: 0.148956
[22]	valid_0's binary_logloss: 0.146622
[23]	valid_0's binary_logloss: 0.144007
[24]	valid_0's binary_logloss: 0.142184
[25]	valid_0's binary_logloss: 0.140149
[26]	valid_0's binary_logloss: 0.138502
[27]	valid_0's binary_logloss: 0.137507
[28]	valid_0's binary_logloss: 0.136152
[29]	valid_0's binary_logloss: 0.134514
[30]	valid_0's binary_logloss: 0.133357
[31]	valid_0's binary_logloss: 0.131932
[32]	valid_0's binary_logloss: 0.130451
[33]	valid_0's binary_logloss: 0.129423
[34]	valid_0's binary_logloss: 0.128487
[35]	valid_0's binary_logloss: 0.127522
[36]	valid_0's binary_logloss: 0.126775
[37]	valid_0's binary_logloss: 0.125579
[38]	valid_0's binary_logloss: 0.125047
[39]	valid_0's binary_logloss: 0.124233
[40]	valid_0's binary_logloss: 0.123569
[41]	valid_0's binary_logloss: 0.122895
[42]	valid_0's binary_logloss: 0.122669
[43]	valid_0's binary_logloss: 0.122328
[44]	valid_0's binary_logloss: 0.121834
[45]	valid_0's binary_logloss: 0.121328
[46]	valid_0's binary_logloss: 0.120962
[47]	valid_0's binary_logloss: 0.120675
[48]	valid_0's binary_logloss: 0.120295
[49]	valid_0's binary_logloss: 0.119934
[50]	valid_0's binary_logloss: 0.119707
[51]	valid_0's binary_logloss: 0.119186
[52]	valid_0's binary_logloss: 0.118534
[53]	valid_0's binary_logloss: 0.118209
[54]	valid_0's binary_logloss: 0.117726
[55]	valid_0's binary_logloss: 0.117724
[56]	valid_0's binary_logloss: 0.117495
[57]	valid_0's binary_logloss: 0.117103
[58]	valid_0's binary_logloss: 0.116686
[59]	valid_0's binary_logloss: 0.116077
[60]	valid_0's binary_logloss: 0.115849
[61]	valid_0's binary_logloss: 0.115373
[62]	valid_0's binary_logloss: 0.115333
[63]	valid_0's binary_logloss: 0.115107
[64]	valid_0's binary_logloss: 0.115044
[65]	valid_0's binary_logloss: 0.114743
[66]	valid_0's binary_logloss: 0.114856
[67]	valid_0's binary_logloss: 0.115037
[68]	valid_0's binary_logloss: 0.114976
[69]	valid_0's binary_logloss: 0.114778
[70]	valid_0's binary_logloss: 0.114656
[71]	valid_0's binary_logloss: 0.114279
[72]	valid_0's binary_logloss: 0.114103
[73]	valid_0's binary_logloss: 0.113775
[74]	valid_0's binary_logloss: 0.113767
[75]	valid_0's binary_logloss: 0.113563
[76]	valid_0's binary_logloss: 0.113095
[77]	valid_0's binary_logloss: 0.112861
[78]	valid_0's binary_logloss: 0.112418
[79]	valid_0's binary_logloss: 0.111993
[80]	valid_0's binary_logloss: 0.111721
[81]	valid_0's binary_logloss: 0.111488
[82]	valid_0's binary_logloss: 0.111483
[83]	valid_0's binary_logloss: 0.111391
[84]	valid_0's binary_logloss: 0.110994
[85]	valid_0's binary_logloss: 0.110732
[86]	valid_0's binary_logloss: 0.110467
[87]	valid_0's binary_logloss: 0.110433
[88]	valid_0's binary_logloss: 0.11008
[89]	valid_0's binary_logloss: 0.109939
[90]	valid_0's binary_logloss: 0.109534
[91]	valid_0's binary_logloss: 0.109608
[92]	valid_0's binary_logloss: 0.109441
[93]	valid_0's binary_logloss: 0.109112
[94]	valid_0's binary_logloss: 0.109058
[95]	valid_0's binary_logloss: 0.109029
[96]	valid_0's binary_logloss: 0.109155
[97]	valid_0's binary_logloss: 0.108921
[98]	valid_0's binary_logloss: 0.108594
[99]	valid_0's binary_logloss: 0.10827
[100]	valid_0's binary_logloss: 0.108148
[101]	valid_0's binary_logloss: 0.108026
[102]	valid_0's binary_logloss: 0.108184
[103]	valid_0's binary_logloss: 0.108157
[104]	valid_0's binary_logloss: 0.108034
[105]	valid_0's binary_logloss: 0.108369
[106]	valid_0's binary_logloss: 0.108744
[107]	valid_0's binary_logloss: 0.108817
[108]	valid_0's binary_logloss: 0.108825
[109]	valid_0's binary_logloss: 0.108922
[110]	valid_0's binary_logloss: 0.109074
[111]	valid_0's binary_logloss: 0.109047
[112]	valid_0's binary_logloss: 0.10898
[113]	valid_0's binary_logloss: 0.108754
[114]	valid_0's binary_logloss: 0.108825
[115]	valid_0's binary_logloss: 0.108986
[116]	valid_0's binary_logloss: 0.109102
[117]	valid_0's binary_logloss: 0.109273
[118]	valid_0's binary_logloss: 0.109157
[119]	valid_0's binary_logloss: 0.109331
[120]	valid_0's binary_logloss: 0.109508
[121]	valid_0's binary_logloss: 0.109328
[122]	valid_0's binary_logloss: 0.109316
[123]	valid_0's binary_logloss: 0.109221
[124]	valid_0's binary_logloss: 0.109313
[125]	valid_0's binary_logloss: 0.109455
[126]	valid_0's binary_logloss: 0.109469
[127]	valid_0's binary_logloss: 0.109514
[128]	valid_0's binary_logloss: 0.109612
[129]	valid_0's binary_logloss: 0.109727
[130]	valid_0's binary_logloss: 0.10984

Trening klas:  14%|█▍        | 71/500 [13:02<56:09,  7.85s/klasa, klasa=class_71, F1_klasy=0.8589, F1_macro=0.8596, drzewa=101]




Trening klas:  14%|█▍        | 72/500 [13:02<59:27,  8.34s/klasa, klasa=class_71, F1_klasy=0.8589, F1_macro=0.8596, drzewa=101]

[131]	valid_0's binary_logloss: 0.11004
[1]	valid_0's binary_logloss: 0.152602
[2]	valid_0's binary_logloss: 0.139795
[3]	valid_0's binary_logloss: 0.129879
[4]	valid_0's binary_logloss: 0.12157
[5]	valid_0's binary_logloss: 0.114591
[6]	valid_0's binary_logloss: 0.108428
[7]	valid_0's binary_logloss: 0.103013
[8]	valid_0's binary_logloss: 0.0981493
[9]	valid_0's binary_logloss: 0.0936752
[10]	valid_0's binary_logloss: 0.0896771
[11]	valid_0's binary_logloss: 0.085992
[12]	valid_0's binary_logloss: 0.0825736
[13]	valid_0's binary_logloss: 0.0795009
[14]	valid_0's binary_logloss: 0.0767971
[15]	valid_0's binary_logloss: 0.0742027
[16]	valid_0's binary_logloss: 0.0716413
[17]	valid_0's binary_logloss: 0.0692565
[18]	valid_0's binary_logloss: 0.06699
[19]	valid_0's binary_logloss: 0.0649065
[20]	valid_0's binary_logloss: 0.0629701
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0613035
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0596956
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.0582375
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0569539
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.0556315
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.054443
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.0533551
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.0523876
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.0514882
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.0506772
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.0498381
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.048868
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.0481839
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.0474107
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.0468466
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.0462996
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.0459244
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.0455946
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.0451637
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.0449166
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.0446342
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.0443744
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.0441915
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.0438934
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.0437271
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.0435428
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.0431047
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.0427838
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.0423902
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.0419953
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.0418684
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.041701
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.0415614
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.0414407
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.0410361
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.040716
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.0403921
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.0401208
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.0398354
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.0395601
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.0392049
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.0389702
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.0385282
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.0382997
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.0375766
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.0373376
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.0371849
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.0370319
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.03678
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.0367287
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.0362116
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.035839
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.0354087
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.0350826
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.0348131
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.0344656
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.0342629
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.0341463
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.0341321
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.0338101
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.0334592
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.0332231
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.0329669
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.0327981
[85]	valid_0's binary_logloss: 0.0323952
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.0322071
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.0319992
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.0318934
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.0317512
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.031733
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.0314944
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.0312022
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.0308471
[94]	valid_0's binary_logloss: 0.0308323
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.0305291
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.030296
[97]	valid_0's binary_logloss: 0.0304089
[98]	valid_0's binary_logloss: 0.0300584
[99]	valid_0's binary_logloss: 0.0301679
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.0300381
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.0298491
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.0298581
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.0295364
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.0294952
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.0292672
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.0292769
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.0290256
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.0288453
[109]	valid_0's binary_logloss: 0.0285136
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.0282642
[111]	valid_0's binary_logloss: 0.0279718
[112]	valid_0's binary_logloss: 0.0279596
[113]	valid_0's binary_logloss: 0.0278982
[114]	valid_0's binary_logloss: 0.0278736
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 0.027963
[116]	valid_0's binary_logloss: 0.0278023
[117]	valid_0's binary_logloss: 0.0275935
[118]	valid_0's binary_logloss: 0.0272714
[119]	valid_0's binary_logloss: 0.0270877
[120]	valid_0's binary_logloss: 0.0271423
[121]	valid_0's binary_logloss: 0.0270587
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[122]	valid_0's binary_logloss: 0.0269764
[123]	valid_0's binary_logloss: 0.0269453
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[124]	valid_0's binary_logloss: 0.0270297
[125]	valid_0's binary_logloss: 0.0271778
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[126]	valid_0's binary_logloss: 0.0270111
[127]	valid_0's binary_logloss: 0.0267868
[128]	valid_0's binary_logloss: 0.026778
[129]	valid_0's binary_logloss: 0.0267387
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[130]	valid_0's binary_logloss: 0.0267684
[131]	valid_0's binary_logloss: 0.0268534
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[132]	valid_0's binary_logloss: 0.0269728
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[133]	valid_0's binary_logloss: 0.027098
[134]	valid_0's binary_logloss: 0.0271012
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[135]	valid_0's binary_logloss: 0.027108
[136]	valid_0's binary_logloss: 0.0270503
[137]	valid_0's binary_logloss: 0.026981
[138]	valid_0's binary_logloss: 0.0270088
[139]	valid_0's binary_logloss: 0.0270914
[140]	valid_0's binary_logloss: 0.027043
[141]	valid_0's binary_logloss: 0.0269579
[142]	valid_0's binary_logloss: 0.0268885
[143]	valid_0's binary_logloss: 0.027022
[144]	valid_0's binary_logloss: 0.0270348
[145]	valid_0's binary_logloss: 0.0272256
[146]	valid_0's binary_logloss: 0.0272685
[147]	valid_0's binary_logloss: 0.0272821
[148]	valid_0's binary_logloss: 0.0272711
[149]	valid_0's binary_logloss: 0.0273482
[150]	valid_0's binary_logloss: 0.0274294
[151]	valid_0's binary_logloss: 0.0274962
[152]	valid_0's binary_logloss: 0.0275451
[153]	valid_0's binary_logloss: 0.0275658
[154]	valid_0's binary_logloss: 0.0275119
[155]	valid_0's binary_logloss: 0.027646
[156]	valid_0's binary_logloss: 0.0276714
[157]	valid_0's binary_logloss: 0.0276389
[158]	valid_0's binary_logloss: 0.0277154

Trening klas:  14%|█▍        | 72/500 [13:09<59:27,  8.34s/klasa, klasa=class_72, F1_klasy=0.8955, F1_macro=0.8601, drzewa=129]




Trening klas:  15%|█▍        | 73/500 [13:09<56:54,  8.00s/klasa, klasa=class_72, F1_klasy=0.8955, F1_macro=0.8601, drzewa=129]

[159]	valid_0's binary_logloss: 0.0278055
[1]	valid_0's binary_logloss: 0.151503
[2]	valid_0's binary_logloss: 0.139103
[3]	valid_0's binary_logloss: 0.129463
[4]	valid_0's binary_logloss: 0.121361
[5]	valid_0's binary_logloss: 0.114538
[6]	valid_0's binary_logloss: 0.108645
[7]	valid_0's binary_logloss: 0.103409
[8]	valid_0's binary_logloss: 0.0987539
[9]	valid_0's binary_logloss: 0.0944462
[10]	valid_0's binary_logloss: 0.0905944
[11]	valid_0's binary_logloss: 0.0869692
[12]	valid_0's binary_logloss: 0.0835761
[13]	valid_0's binary_logloss: 0.0805
[14]	valid_0's binary_logloss: 0.0776909
[15]	valid_0's binary_logloss: 0.0751761
[16]	valid_0's binary_logloss: 0.0727235
[17]	valid_0's binary_logloss: 0.0704441
[18]	valid_0's binary_logloss: 0.0683717
[19]	valid_0's binary_logloss: 0.0664271
[20]	valid_0's binary_logloss: 0.0646134
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.06298
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0614529
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.0600499
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0586677
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.0574772
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.0561625
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.0550459
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.0540953
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.0531337
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.052248
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.051221
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.0504794
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.0497932
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.0492501
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.0487693
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.0483161
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.0479105
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.0475784
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.0472223
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.046764
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.0465721
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.0463803
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.0462066
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.046032
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.0459369
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.0457205
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.0455456
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.0451819
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.0452344
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.0449557
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.0445689
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.0441763
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.0440915
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.0436881
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.0435634
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.0434832
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.0434179
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.0433243
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.0433005
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.0430405
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.0427127
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.0426303
[63]	valid_0's binary_logloss: 0.042193
[64]	valid_0's binary_logloss: 0.0419089
[65]	valid_0's binary_logloss: 0.0415192
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.0412071
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.0408715
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.040593
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.0402621
[70]	valid_0's binary_logloss: 0.0395712
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.0392936
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.0390042
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.0388653
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.0387288
[75]	valid_0's binary_logloss: 0.0383242
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.0380731
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.0373591
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.0371581
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.0369381
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.036785
[81]	valid_0's binary_logloss: 0.036422
[82]	valid_0's binary_logloss: 0.0361679
[83]	valid_0's binary_logloss: 0.0358669
[84]	valid_0's binary_logloss: 0.0354944
[85]	valid_0's binary_logloss: 0.035496
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.0354107
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.0350576
[88]	valid_0's binary_logloss: 0.0348551
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.034568
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.0343228
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.0340811
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.0340108
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.0336945
[94]	valid_0's binary_logloss: 0.0333751
[95]	valid_0's binary_logloss: 0.0331263
[96]	valid_0's binary_logloss: 0.0330206
[97]	valid_0's binary_logloss: 0.0330559
[98]	valid_0's binary_logloss: 0.0327672
[99]	valid_0's binary_logloss: 0.0326819
[100]	valid_0's binary_logloss: 0.03247
[101]	valid_0's binary_logloss: 0.0325254
[102]	valid_0's binary_logloss: 0.032567
[103]	valid_0's binary_logloss: 0.0325327
[104]	valid_0's binary_logloss: 0.0325421
[105]	valid_0's binary_logloss: 0.0319706
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.0314957
[107]	valid_0's binary_logloss: 0.0312875
[108]	valid_0's binary_logloss: 0.0311169
[109]	valid_0's binary_logloss: 0.0309962
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.0308922
[111]	valid_0's binary_logloss: 0.0309255
[112]	valid_0's binary_logloss: 0.0308515
[113]	valid_0's binary_logloss: 0.0307907
[114]	valid_0's binary_logloss: 0.0304612
[115]	valid_0's binary_logloss: 0.0304409
[116]	valid_0's binary_logloss: 0.0304119
[117]	valid_0's binary_logloss: 0.0302633
[118]	valid_0's binary_logloss: 0.0300892
[119]	valid_0's binary_logloss: 0.0298988
[120]	valid_0's binary_logloss: 0.0301001
[121]	valid_0's binary_logloss: 0.0300582
[122]	valid_0's binary_logloss: 0.0301485
[123]	valid_0's binary_logloss: 0.0302337
[124]	valid_0's binary_logloss: 0.0302657
[125]	valid_0's binary_logloss: 0.0303213
[126]	valid_0's binary_logloss: 0.0301663
[127]	valid_0's binary_logloss: 0.0300304
[128]	valid_0's binary_logloss: 0.0299639
[129]	valid_0's binary_logloss: 0.0300479
[130]	valid_0's binary_logloss: 0.0300477
[131]	valid_0's binary_logloss: 0.0302583
[132]	valid_0's binary_logloss: 0.0302714
[133]	valid_0's binary_logloss: 0.030193
[134]	valid_0's binary_logloss: 0.0301018
[135]	valid_0's binary_logloss: 0.0303363
[136]	valid_0's binary_logloss: 0.0301747
[137]	valid_0's binary_logloss: 0.0301729
[138]	valid_0's binary_logloss: 0.0301597
[139]	valid_0's binary_logloss: 0.030234
[140]	valid_0's binary_logloss: 0.0303662
[141]	valid_0's binary_logloss: 0.0303166
[142]	valid_0's binary_logloss: 0.0303167
[143]	valid_0's binary_logloss: 0.0302028
[144]	valid_0's binary_logloss: 0.0300954
[145]	valid_0's binary_logloss: 0.0300266
[146]	valid_0's binary_logloss: 0.0300882
[147]	valid_0's binary_logloss: 0.0300958
[148]	valid_0's binary_logloss: 0.0300354

Trening klas:  15%|█▍        | 73/500 [13:17<56:54,  8.00s/klasa, klasa=class_73, F1_klasy=0.8920, F1_macro=0.8606, drzewa=119]




Trening klas:  15%|█▍        | 74/500 [13:17<55:41,  7.84s/klasa, klasa=class_73, F1_klasy=0.8920, F1_macro=0.8606, drzewa=119]

[149]	valid_0's binary_logloss: 0.0302113
[1]	valid_0's binary_logloss: 0.150639
[2]	valid_0's binary_logloss: 0.138292
[3]	valid_0's binary_logloss: 0.128522
[4]	valid_0's binary_logloss: 0.120401
[5]	valid_0's binary_logloss: 0.113516
[6]	valid_0's binary_logloss: 0.107564
[7]	valid_0's binary_logloss: 0.1023
[8]	valid_0's binary_logloss: 0.0975149
[9]	valid_0's binary_logloss: 0.0932312
[10]	valid_0's binary_logloss: 0.0893304
[11]	valid_0's binary_logloss: 0.0856445
[12]	valid_0's binary_logloss: 0.0824407
[13]	valid_0's binary_logloss: 0.0794378
[14]	valid_0's binary_logloss: 0.0766462
[15]	valid_0's binary_logloss: 0.0740583
[16]	valid_0's binary_logloss: 0.0716171
[17]	valid_0's binary_logloss: 0.069271
[18]	valid_0's binary_logloss: 0.0670743
[19]	valid_0's binary_logloss: 0.0649851
[20]	valid_0's binary_logloss: 0.06301
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0611734
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.059625
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.0580261
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0565627
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.0553377
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.0542358
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.0531877
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.0522732
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.05152
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.0505603
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.0497596
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.049037
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.0483849
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.0478616
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.0473353
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.0469208
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.0461913
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.0457871
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.0454134
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.0450888
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.0447693
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.0445943
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.0444631
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.0443346
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.044037
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.0438723
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.0435229
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.0432024
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.0431024
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.0428202
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.0428088
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.0427179
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.0426393
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.0421613
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.0417664
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.0416435
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.0415917
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.0412907
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.0412527
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.0408497
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.040533
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.0404838
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.0400331
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.0391906
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.0382759
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.0379859
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.0376938
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.0374831
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.0372405
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.0371845
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.0370049
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.0368098
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.0363332
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.0360839
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.0357284
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.0355536
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.0353306
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.0350987
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.0348753
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.0347256
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.0347751
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.0344278
[83]	valid_0's binary_logloss: 0.0343351
[84]	valid_0's binary_logloss: 0.034396
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.0344944
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.0343982
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.0341545
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.0338169
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.0337723
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.0337276
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.0333348
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.0329111
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.0326417
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.0324736
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.0324351
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.0321959
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.0321463
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.0320061
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.0319151
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.0317865
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.0311942
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.0311766
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.0309525
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.0308113
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.0304992
[106]	valid_0's binary_logloss: 0.030153
[107]	valid_0's binary_logloss: 0.0299543
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.0296766
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.0296388
[110]	valid_0's binary_logloss: 0.0295014
[111]	valid_0's binary_logloss: 0.0295112
[112]	valid_0's binary_logloss: 0.0295786
[113]	valid_0's binary_logloss: 0.0297045
[114]	valid_0's binary_logloss: 0.0296896
[115]	valid_0's binary_logloss: 0.0298826
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[116]	valid_0's binary_logloss: 0.0297988
[117]	valid_0's binary_logloss: 0.0296354
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[118]	valid_0's binary_logloss: 0.0295177
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[119]	valid_0's binary_logloss: 0.0292748
[120]	valid_0's binary_logloss: 0.0290505
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[121]	valid_0's binary_logloss: 0.0291373
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[122]	valid_0's binary_logloss: 0.0291653
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[123]	valid_0's binary_logloss: 0.0290983
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[124]	valid_0's binary_logloss: 0.0291039
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[125]	valid_0's binary_logloss: 0.029209
[126]	valid_0's binary_logloss: 0.0291498
[127]	valid_0's binary_logloss: 0.0291636
[128]	valid_0's binary_logloss: 0.0291393
[129]	valid_0's binary_logloss: 0.0290618
[130]	valid_0's binary_logloss: 0.0290778
[131]	valid_0's binary_logloss: 0.0291633
[132]	valid_0's binary_logloss: 0.0292062
[133]	valid_0's binary_logloss: 0.0291713
[134]	valid_0's binary_logloss: 0.0291611
[135]	valid_0's binary_logloss: 0.0293042
[136]	valid_0's binary_logloss: 0.0293935
[137]	valid_0's binary_logloss: 0.0294272
[138]	valid_0's binary_logloss: 0.0294603
[139]	valid_0's binary_logloss: 0.0294095
[140]	valid_0's binary_logloss: 0.029363
[141]	valid_0's binary_logloss: 0.0292348
[142]	valid_0's binary_logloss: 0.0294348
[143]	valid_0's binary_logloss: 0.0295821
[144]	valid_0's binary_logloss: 0.0298222
[145]	valid_0's binary_logloss: 0.0300302
[146]	valid_0's binary_logloss: 0.0301068
[147]	valid_0's binary_logloss: 0.0302269

Trening klas:  15%|█▍        | 74/500 [13:24<55:41,  7.84s/klasa, klasa=class_74, F1_klasy=0.8974, F1_macro=0.8610, drzewa=120]

[148]	valid_0's binary_logloss: 0.0302302
[149]	valid_0's binary_logloss: 0.0303434
[150]	valid_0's binary_logloss: 0.0305031

Trening klas:  15%|█▌        | 75/500 [13:24<54:22,  7.68s/klasa, klasa=class_74, F1_klasy=0.8974, F1_macro=0.8610, drzewa=120]

[1]	valid_0's binary_logloss: 0.31791
[2]	valid_0's binary_logloss: 0.283656
[3]	valid_0's binary_logloss: 0.260406
[4]	valid_0's binary_logloss: 0.242683
[5]	valid_0's binary_logloss: 0.228675
[6]	valid_0's binary_logloss: 0.217316
[7]	valid_0's binary_logloss: 0.207812
[8]	valid_0's binary_logloss: 0.199905
[9]	valid_0's binary_logloss: 0.192553
[10]	valid_0's binary_logloss: 0.185942
[11]	valid_0's binary_logloss: 0.179894
[12]	valid_0's binary_logloss: 0.174841
[13]	valid_0's binary_logloss: 0.170439
[14]	valid_0's binary_logloss: 0.166339
[15]	valid_0's binary_logloss: 0.162414
[16]	valid_0's binary_logloss: 0.159165
[17]	valid_0's binary_logloss: 0.156008
[18]	valid_0's binary_logloss: 0.153342
[19]	valid_0's binary_logloss: 0.15068
[20]	valid_0's binary_logloss: 0.148121
[21]	valid_0's binary_logloss: 0.146196
[22]	valid_0's binary_logloss: 0.14377
[23]	valid_0's binary_logloss: 0.14153
[24]	valid_0's binary_logloss: 0.139921
[25]	valid_0's binary_logloss: 0.138234
[26]	valid_0's binary_logloss: 0.136259
[27]	valid_0's binary_logloss: 0.135257
[28]	valid_0's binary_logloss: 0.133409
[29]	valid_0's binary_logloss: 0.131683
[30]	valid_0's binary_logloss: 0.130607
[31]	valid_0's binary_logloss: 0.129637
[32]	valid_0's binary_logloss: 0.128369
[33]	valid_0's binary_logloss: 0.12776
[34]	valid_0's binary_logloss: 0.126722
[35]	valid_0's binary_logloss: 0.125916
[36]	valid_0's binary_logloss: 0.125536
[37]	valid_0's binary_logloss: 0.124824
[38]	valid_0's binary_logloss: 0.124376
[39]	valid_0's binary_logloss: 0.123573
[40]	valid_0's binary_logloss: 0.122883
[41]	valid_0's binary_logloss: 0.122021
[42]	valid_0's binary_logloss: 0.121735
[43]	valid_0's binary_logloss: 0.121045
[44]	valid_0's binary_logloss: 0.120581
[45]	valid_0's binary_logloss: 0.12003
[46]	valid_0's binary_logloss: 0.119437
[47]	valid_0's binary_logloss: 0.119475
[48]	valid_0's binary_logloss: 0.119014
[49]	valid_0's binary_logloss: 0.118175
[50]	valid_0's binary_logloss: 0.11786
[51]	valid_0's binary_logloss: 0.117025
[52]	valid_0's binary_logloss: 0.116703
[53]	valid_0's binary_logloss: 0.116279
[54]	valid_0's binary_logloss: 0.115762
[55]	valid_0's binary_logloss: 0.115458
[56]	valid_0's binary_logloss: 0.115373
[57]	valid_0's binary_logloss: 0.11525
[58]	valid_0's binary_logloss: 0.11513
[59]	valid_0's binary_logloss: 0.115035
[60]	valid_0's binary_logloss: 0.114806
[61]	valid_0's binary_logloss: 0.114285
[62]	valid_0's binary_logloss: 0.114138
[63]	valid_0's binary_logloss: 0.113804
[64]	valid_0's binary_logloss: 0.113644
[65]	valid_0's binary_logloss: 0.113429
[66]	valid_0's binary_logloss: 0.113392
[67]	valid_0's binary_logloss: 0.11332
[68]	valid_0's binary_logloss: 0.113471
[69]	valid_0's binary_logloss: 0.113413
[70]	valid_0's binary_logloss: 0.113395
[71]	valid_0's binary_logloss: 0.112907
[72]	valid_0's binary_logloss: 0.112845
[73]	valid_0's binary_logloss: 0.112412
[74]	valid_0's binary_logloss: 0.112112
[75]	valid_0's binary_logloss: 0.11213
[76]	valid_0's binary_logloss: 0.111681
[77]	valid_0's binary_logloss: 0.111376
[78]	valid_0's binary_logloss: 0.111
[79]	valid_0's binary_logloss: 0.110689
[80]	valid_0's binary_logloss: 0.110327
[81]	valid_0's binary_logloss: 0.110136
[82]	valid_0's binary_logloss: 0.110095
[83]	valid_0's binary_logloss: 0.109894
[84]	valid_0's binary_logloss: 0.109876
[85]	valid_0's binary_logloss: 0.110064
[86]	valid_0's binary_logloss: 0.109908
[87]	valid_0's binary_logloss: 0.109776
[88]	valid_0's binary_logloss: 0.109677
[89]	valid_0's binary_logloss: 0.109602
[90]	valid_0's binary_logloss: 0.109393
[91]	valid_0's binary_logloss: 0.109566
[92]	valid_0's binary_logloss: 0.109267
[93]	valid_0's binary_logloss: 0.109139
[94]	valid_0's binary_logloss: 0.109003
[95]	valid_0's binary_logloss: 0.109045
[96]	valid_0's binary_logloss: 0.108923
[97]	valid_0's binary_logloss: 0.108773
[98]	valid_0's binary_logloss: 0.108709
[99]	valid_0's binary_logloss: 0.108522
[100]	valid_0's binary_logloss: 0.10849
[101]	valid_0's binary_logloss: 0.108573
[102]	valid_0's binary_logloss: 0.10847
[103]	valid_0's binary_logloss: 0.108592
[104]	valid_0's binary_logloss: 0.108663
[105]	valid_0's binary_logloss: 0.10881
[106]	valid_0's binary_logloss: 0.108725
[107]	valid_0's binary_logloss: 0.10872
[108]	valid_0's binary_logloss: 0.10885
[109]	valid_0's binary_logloss: 0.108885
[110]	valid_0's binary_logloss: 0.108522
[111]	valid_0's binary_logloss: 0.108738
[112]	valid_0's binary_logloss: 0.108819
[113]	valid_0's binary_logloss: 0.108755
[114]	valid_0's binary_logloss: 0.108828
[115]	valid_0's binary_logloss: 0.108892
[116]	valid_0's binary_logloss: 0.108997
[117]	valid_0's binary_logloss: 0.108882
[118]	valid_0's binary_logloss: 0.109059
[119]	valid_0's binary_logloss: 0.109297
[120]	valid_0's binary_logloss: 0.109543
[121]	valid_0's binary_logloss: 0.109342
[122]	valid_0's binary_logloss: 0.109442
[123]	valid_0's binary_logloss: 0.109602
[124]	valid_0's binary_logloss: 0.109682
[125]	valid_0's binary_logloss: 0.109698
[126]	valid_0's binary_logloss: 0.109847
[127]	valid_0's binary_logloss: 0.110064
[128]	valid_0's binary_logloss: 0.109906
[129]	valid_0's binary_logloss: 0.110033
[130]	valid_0's binary_logloss: 0.110114

Trening klas:  15%|█▌        | 75/500 [13:34<54:22,  7.68s/klasa, klasa=class_75, F1_klasy=0.8540, F1_macro=0.8610, drzewa=102]




Trening klas:  15%|█▌        | 76/500 [13:34<59:29,  8.42s/klasa, klasa=class_75, F1_klasy=0.8540, F1_macro=0.8610, drzewa=102]

[131]	valid_0's binary_logloss: 0.110194
[132]	valid_0's binary_logloss: 0.11029
[1]	valid_0's binary_logloss: 0.145261
[2]	valid_0's binary_logloss: 0.133334
[3]	valid_0's binary_logloss: 0.124146
[4]	valid_0's binary_logloss: 0.116473
[5]	valid_0's binary_logloss: 0.109992
[6]	valid_0's binary_logloss: 0.104428
[7]	valid_0's binary_logloss: 0.0995089
[8]	valid_0's binary_logloss: 0.0950909
[9]	valid_0's binary_logloss: 0.0911101
[10]	valid_0's binary_logloss: 0.0873535
[11]	valid_0's binary_logloss: 0.0839419
[12]	valid_0's binary_logloss: 0.0808957
[13]	valid_0's binary_logloss: 0.0781082
[14]	valid_0's binary_logloss: 0.0754831
[15]	valid_0's binary_logloss: 0.0731727
[16]	valid_0's binary_logloss: 0.0710054
[17]	valid_0's binary_logloss: 0.069025
[18]	valid_0's binary_logloss: 0.0671991
[19]	valid_0's binary_logloss: 0.0655641
[20]	valid_0's binary_logloss: 0.0638322
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0622464
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0608309
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.0593855
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0581604
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.0569504
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.0558307
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.0548348
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.053963
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.0533141
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.0525072
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.051702
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.0510128
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.050408
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.0499373
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.0493825
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.048992
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.0486643
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.0484007
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.0481157
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.048081
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.0478922
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.0476945
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.0475793
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.0475165
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.0475613
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.0474525
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.0467305
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.0460986
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.0458233
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.0452513
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.0450256
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.0448457
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.0445258
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.0442678
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.0439809
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.0438873
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.0438952
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.0438666
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.043634
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.0436216
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.0433036
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.0430605
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.0426507
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.0423442
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.0419661
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.0417287
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.0413961
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.0410649
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.0407092
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.0404099
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.0395439
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.0387895
[73]	valid_0's binary_logloss: 0.0386836
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.0388631
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.0382933
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.0379277
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.0375079
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.0368475
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.0366164
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.0360342
[81]	valid_0's binary_logloss: 0.036179
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.0360624
[83]	valid_0's binary_logloss: 0.0359459
[84]	valid_0's binary_logloss: 0.0349875
[85]	valid_0's binary_logloss: 0.0349107
[86]	valid_0's binary_logloss: 0.034098
[87]	valid_0's binary_logloss: 0.0337973
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.0336827
[89]	valid_0's binary_logloss: 0.0332226
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.0327763
[91]	valid_0's binary_logloss: 0.0323662
[92]	valid_0's binary_logloss: 0.0324346
[93]	valid_0's binary_logloss: 0.0321876
[94]	valid_0's binary_logloss: 0.0323077
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.0322502
[96]	valid_0's binary_logloss: 0.032207
[97]	valid_0's binary_logloss: 0.0320818
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.0319746
[99]	valid_0's binary_logloss: 0.0319259
[100]	valid_0's binary_logloss: 0.031822
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.0314792
[102]	valid_0's binary_logloss: 0.0312008
[103]	valid_0's binary_logloss: 0.0312473
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.0311195
[105]	valid_0's binary_logloss: 0.0312467
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.0313112
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.0313887
[108]	valid_0's binary_logloss: 0.0314238
[109]	valid_0's binary_logloss: 0.0313699
[110]	valid_0's binary_logloss: 0.0314267
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.0313298
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 0.031271
[113]	valid_0's binary_logloss: 0.0314467
[114]	valid_0's binary_logloss: 0.0313451
[115]	valid_0's binary_logloss: 0.0313175
[116]	valid_0's binary_logloss: 0.0311754
[117]	valid_0's binary_logloss: 0.0311032
[118]	valid_0's binary_logloss: 0.0310825
[119]	valid_0's binary_logloss: 0.0311094
[120]	valid_0's binary_logloss: 0.0311909
[121]	valid_0's binary_logloss: 0.031384
[122]	valid_0's binary_logloss: 0.0313739
[123]	valid_0's binary_logloss: 0.0314544
[124]	valid_0's binary_logloss: 0.0316179
[125]	valid_0's binary_logloss: 0.0317094
[126]	valid_0's binary_logloss: 0.0317151
[127]	valid_0's binary_logloss: 0.0315158
[128]	valid_0's binary_logloss: 0.0315744
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[129]	valid_0's binary_logloss: 0.0315663
[130]	valid_0's binary_logloss: 0.0315401
[131]	valid_0's binary_logloss: 0.0317364
[132]	valid_0's binary_logloss: 0.0318596
[133]	valid_0's binary_logloss: 0.0320208
[134]	valid_0's binary_logloss: 0.0321314
[135]	valid_0's binary_logloss: 0.0322811
[136]	valid_0's binary_logloss: 0.0323595
[137]	valid_0's binary_logloss: 0.0323692
[138]	valid_0's binary_logloss: 0.0324132
[139]	valid_0's binary_logloss: 0.0323462
[140]	valid_0's binary_logloss: 0.032446
[141]	valid_0's binary_logloss: 0.0323681
[142]	valid_0's binary_logloss: 0.0325828
[143]	valid_0's binary_logloss: 0.0327933
[144]	valid_0's binary_logloss: 0.0328024
[145]	valid_0's binary_logloss: 0.0328543
[146]	valid_0's binary_logloss: 0.0328497
[147]	valid_0's binary_logloss: 0.0329529
[148]	valid_0's binary_logloss: 0.0329134

Trening klas:  15%|█▌        | 76/500 [13:42<59:29,  8.42s/klasa, klasa=class_76, F1_klasy=0.8619, F1_macro=0.8610, drzewa=118]




Trening klas:  15%|█▌        | 77/500 [13:42<57:30,  8.16s/klasa, klasa=class_76, F1_klasy=0.8619, F1_macro=0.8610, drzewa=118]

[1]	valid_0's binary_logloss: 0.32071
[2]	valid_0's binary_logloss: 0.298033
[3]	valid_0's binary_logloss: 0.28358
[4]	valid_0's binary_logloss: 0.273387
[5]	valid_0's binary_logloss: 0.264196
[6]	valid_0's binary_logloss: 0.256559
[7]	valid_0's binary_logloss: 0.250388
[8]	valid_0's binary_logloss: 0.245842
[9]	valid_0's binary_logloss: 0.240976
[10]	valid_0's binary_logloss: 0.236951
[11]	valid_0's binary_logloss: 0.233213
[12]	valid_0's binary_logloss: 0.229505
[13]	valid_0's binary_logloss: 0.226073
[14]	valid_0's binary_logloss: 0.223097
[15]	valid_0's binary_logloss: 0.220349
[16]	valid_0's binary_logloss: 0.218284
[17]	valid_0's binary_logloss: 0.215943
[18]	valid_0's binary_logloss: 0.21393
[19]	valid_0's binary_logloss: 0.212652
[20]	valid_0's binary_logloss: 0.21175
[21]	valid_0's binary_logloss: 0.210505
[22]	valid_0's binary_logloss: 0.209397
[23]	valid_0's binary_logloss: 0.208223
[24]	valid_0's binary_logloss: 0.207743
[25]	valid_0's binary_logloss: 0.207114
[26]	valid_0's binary_logloss: 0.206031
[27]	valid_0's binary_logloss: 0.20517
[28]	valid_0's binary_logloss: 0.204432
[29]	valid_0's binary_logloss: 0.203222
[30]	valid_0's binary_logloss: 0.202882
[31]	valid_0's binary_logloss: 0.20194
[32]	valid_0's binary_logloss: 0.201227
[33]	valid_0's binary_logloss: 0.200871
[34]	valid_0's binary_logloss: 0.199838
[35]	valid_0's binary_logloss: 0.199866
[36]	valid_0's binary_logloss: 0.199637
[37]	valid_0's binary_logloss: 0.199091
[38]	valid_0's binary_logloss: 0.199073
[39]	valid_0's binary_logloss: 0.199069
[40]	valid_0's binary_logloss: 0.1987
[41]	valid_0's binary_logloss: 0.198441
[42]	valid_0's binary_logloss: 0.197177
[43]	valid_0's binary_logloss: 0.196477
[44]	valid_0's binary_logloss: 0.195808
[45]	valid_0's binary_logloss: 0.194959
[46]	valid_0's binary_logloss: 0.194618
[47]	valid_0's binary_logloss: 0.194343
[48]	valid_0's binary_logloss: 0.194275
[49]	valid_0's binary_logloss: 0.194108
[50]	valid_0's binary_logloss: 0.193984
[51]	valid_0's binary_logloss: 0.193799
[52]	valid_0's binary_logloss: 0.193367
[53]	valid_0's binary_logloss: 0.193089
[54]	valid_0's binary_logloss: 0.192722
[55]	valid_0's binary_logloss: 0.193088
[56]	valid_0's binary_logloss: 0.193204
[57]	valid_0's binary_logloss: 0.192895
[58]	valid_0's binary_logloss: 0.192053
[59]	valid_0's binary_logloss: 0.192024
[60]	valid_0's binary_logloss: 0.19159
[61]	valid_0's binary_logloss: 0.191749
[62]	valid_0's binary_logloss: 0.19146
[63]	valid_0's binary_logloss: 0.191783
[64]	valid_0's binary_logloss: 0.191261
[65]	valid_0's binary_logloss: 0.191502
[66]	valid_0's binary_logloss: 0.191596
[67]	valid_0's binary_logloss: 0.191084
[68]	valid_0's binary_logloss: 0.19142
[69]	valid_0's binary_logloss: 0.190758
[70]	valid_0's binary_logloss: 0.190425
[71]	valid_0's binary_logloss: 0.190136
[72]	valid_0's binary_logloss: 0.189986
[73]	valid_0's binary_logloss: 0.190233
[74]	valid_0's binary_logloss: 0.190081
[75]	valid_0's binary_logloss: 0.190421
[76]	valid_0's binary_logloss: 0.190334
[77]	valid_0's binary_logloss: 0.19041
[78]	valid_0's binary_logloss: 0.18998
[79]	valid_0's binary_logloss: 0.190196
[80]	valid_0's binary_logloss: 0.19
[81]	valid_0's binary_logloss: 0.189657
[82]	valid_0's binary_logloss: 0.189581
[83]	valid_0's binary_logloss: 0.189449
[84]	valid_0's binary_logloss: 0.189464
[85]	valid_0's binary_logloss: 0.189552
[86]	valid_0's binary_logloss: 0.189425
[87]	valid_0's binary_logloss: 0.189401
[88]	valid_0's binary_logloss: 0.188917
[89]	valid_0's binary_logloss: 0.189138
[90]	valid_0's binary_logloss: 0.189104
[91]	valid_0's binary_logloss: 0.188862
[92]	valid_0's binary_logloss: 0.188412
[93]	valid_0's binary_logloss: 0.188255
[94]	valid_0's binary_logloss: 0.188069
[95]	valid_0's binary_logloss: 0.187761
[96]	valid_0's binary_logloss: 0.18737
[97]	valid_0's binary_logloss: 0.187535
[98]	valid_0's binary_logloss: 0.187609
[99]	valid_0's binary_logloss: 0.187804
[100]	valid_0's binary_logloss: 0.187651
[101]	valid_0's binary_logloss: 0.187417
[102]	valid_0's binary_logloss: 0.187441
[103]	valid_0's binary_logloss: 0.187214
[104]	valid_0's binary_logloss: 0.186849
[105]	valid_0's binary_logloss: 0.186909
[106]	valid_0's binary_logloss: 0.186667
[107]	valid_0's binary_logloss: 0.186345
[108]	valid_0's binary_logloss: 0.186249
[109]	valid_0's binary_logloss: 0.18607
[110]	valid_0's binary_logloss: 0.185821
[111]	valid_0's binary_logloss: 0.18566
[112]	valid_0's binary_logloss: 0.185622
[113]	valid_0's binary_logloss: 0.185415
[114]	valid_0's binary_logloss: 0.185334
[115]	valid_0's binary_logloss: 0.185413
[116]	valid_0's binary_logloss: 0.18531
[117]	valid_0's binary_logloss: 0.185321
[118]	valid_0's binary_logloss: 0.18491
[119]	valid_0's binary_logloss: 0.185383
[120]	valid_0's binary_logloss: 0.185057
[121]	valid_0's binary_logloss: 0.184837
[122]	valid_0's binary_logloss: 0.18444
[123]	valid_0's binary_logloss: 0.184052
[124]	valid_0's binary_logloss: 0.183799
[125]	valid_0's binary_logloss: 0.183802
[126]	valid_0's binary_logloss: 0.183402
[127]	valid_0's binary_logloss: 0.183343
[128]	valid_0's binary_logloss: 0.183239
[129]	valid_0's binary_logloss: 0.183318
[130]	valid_0's binary_logloss: 0.183244
[131]	valid_0's binary_logloss: 0.183402
[132]	valid_0's binary_logloss: 0.183549
[133]	valid_0's binary_logloss: 0.183518
[134]	valid_0's binary_logloss: 0.183493
[135]	valid_0's binary_logloss: 0.183327
[136]	valid_0's binary_logloss: 0.183285
[137]	valid_0's binary_logloss: 0.183315
[138]	valid_0's binary_logloss: 0.183389
[139]	valid_0's binary_logloss: 0.183404
[140]	valid_0's binary_logloss: 0.183249
[141]	valid_0's binary_logloss: 0.183342
[142]	valid_0's binary_logloss: 0.18322
[143]	valid_0's binary_logloss: 0.183073
[144]	valid_0's binary_logloss: 0.1831
[145]	valid_0's binary_logloss: 0.183104
[146]	valid_0's binary_logloss: 0.183562
[147]	valid_0's binary_logloss: 0.183616
[148]	valid_0's binary_logloss: 0.183639
[149]	valid_0's binary_logloss: 0.183594
[150]	valid_0's binary_logloss: 0.183404
[151]	valid_0's binary_logloss: 0.183506
[152]	valid_0's binary_logloss: 0.183593
[153]	valid_0's binary_logloss: 0.183366
[154]	valid_0's binary_logloss: 0.183584
[155]	valid_0's binary_logloss: 0.183531
[156]	valid_0's binary_logloss: 0.183578
[157]	valid_0's binary_logloss: 0.183607
[158]	valid_0's binary_logloss: 0.183511
[159]	valid_0's binary_logloss: 0.183276
[160]	valid_0's binary_logloss: 0.183124
[161]	valid_0's binary_logloss: 0.182923
[162]	valid_0's binary_logloss: 0.182817
[163]	valid_0's binary_logloss: 0.182669
[164]	valid_0's binary_logloss: 0.182501
[165]	valid_0's binary_logloss: 0.182645
[166]	valid_0's binary_logloss: 0.182467
[167]	valid_0's binary_logloss: 0.182407
[168]	valid_0's binary_logloss: 0.182543
[169]	valid_0's binary_logloss: 0.18247
[170]	valid_0's binary_logloss: 0.182533
[171]	valid_0's binary_logloss: 0.18269
[172]	valid_0's binary_logloss: 0.182782
[173]	valid_0's binary_logloss: 0.183054
[174]	valid_0's binary_logloss: 0.183382
[175]	valid_0's binary_logloss: 0.183356
[176]	valid_0's binary_logloss: 0.183368
[177]	valid_0's binary_logloss: 0.183488
[178]	valid_0's binary_logloss: 0.18356
[179]	valid_0's binary_logloss: 0.183295
[180]	valid_0's binary_logloss: 0.183423
[181]	valid_0's binary_logloss: 0.183486
[182]	valid_0's binary_logloss: 0.183616
[183]	valid_0's binary_logloss: 0.18366
[184]	valid_0's binary_logloss: 0.183797
[185]	valid_0's binary_logloss: 0.183866
[186]	valid_0's binary_logloss: 0.18408
[187]	valid_0's binary_logloss: 0.184495
[188]	valid_0's binary_logloss: 0.18452
[189]	valid_0's binary_logloss: 0.184843
[190]	valid_0's binary_logloss: 0.185033
[191]	valid_0's binary_logloss: 0.185067
[192]	valid_0's binary_logloss: 0.184892
[193]	valid_0's binary_logloss: 0.184884
[194]	valid_0's binary_logloss: 0.184776
[195]	valid_0's binary_logloss: 0.18474
[196]	valid_0's binary_logloss: 0.184813

Trening klas:  15%|█▌        | 77/500 [13:55<57:30,  8.16s/klasa, klasa=class_77, F1_klasy=0.6684, F1_macro=0.8585, drzewa=167]




Trening klas:  16%|█▌        | 78/500 [13:55<1:09:05,  9.82s/klasa, klasa=class_77, F1_klasy=0.6684, F1_macro=0.8585, drzewa=167]

[197]	valid_0's binary_logloss: 0.184894
[1]	valid_0's binary_logloss: 0.366009
[2]	valid_0's binary_logloss: 0.334714
[3]	valid_0's binary_logloss: 0.312894
[4]	valid_0's binary_logloss: 0.294844
[5]	valid_0's binary_logloss: 0.280757
[6]	valid_0's binary_logloss: 0.269317
[7]	valid_0's binary_logloss: 0.259517
[8]	valid_0's binary_logloss: 0.250816
[9]	valid_0's binary_logloss: 0.243914
[10]	valid_0's binary_logloss: 0.238166
[11]	valid_0's binary_logloss: 0.232958
[12]	valid_0's binary_logloss: 0.228732
[13]	valid_0's binary_logloss: 0.224698
[14]	valid_0's binary_logloss: 0.220333
[15]	valid_0's binary_logloss: 0.217197
[16]	valid_0's binary_logloss: 0.213385
[17]	valid_0's binary_logloss: 0.210231
[18]	valid_0's binary_logloss: 0.208082
[19]	valid_0's binary_logloss: 0.205531
[20]	valid_0's binary_logloss: 0.202962
[21]	valid_0's binary_logloss: 0.201377
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.199301
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.197973
[24]	valid_0's binary_logloss: 0.196286
[25]	valid_0's binary_logloss: 0.194151
[26]	valid_0's binary_logloss: 0.192243
[27]	valid_0's binary_logloss: 0.190562
[28]	valid_0's binary_logloss: 0.189414
[29]	valid_0's binary_logloss: 0.187971
[30]	valid_0's binary_logloss: 0.186836
[31]	valid_0's binary_logloss: 0.18582
[32]	valid_0's binary_logloss: 0.184861
[33]	valid_0's binary_logloss: 0.18447
[34]	valid_0's binary_logloss: 0.184082
[35]	valid_0's binary_logloss: 0.183642
[36]	valid_0's binary_logloss: 0.183034
[37]	valid_0's binary_logloss: 0.182389
[38]	valid_0's binary_logloss: 0.181694
[39]	valid_0's binary_logloss: 0.181578
[40]	valid_0's binary_logloss: 0.181186
[41]	valid_0's binary_logloss: 0.180259
[42]	valid_0's binary_logloss: 0.17947
[43]	valid_0's binary_logloss: 0.178583
[44]	valid_0's binary_logloss: 0.178674
[45]	valid_0's binary_logloss: 0.178518
[46]	valid_0's binary_logloss: 0.178312
[47]	valid_0's binary_logloss: 0.178285
[48]	valid_0's binary_logloss: 0.178026
[49]	valid_0's binary_logloss: 0.177819
[50]	valid_0's binary_logloss: 0.177748
[51]	valid_0's binary_logloss: 0.177766
[52]	valid_0's binary_logloss: 0.178168
[53]	valid_0's binary_logloss: 0.178064
[54]	valid_0's binary_logloss: 0.17786
[55]	valid_0's binary_logloss: 0.177978
[56]	valid_0's binary_logloss: 0.178152
[57]	valid_0's binary_logloss: 0.177651
[58]	valid_0's binary_logloss: 0.177369
[59]	valid_0's binary_logloss: 0.177102
[60]	valid_0's binary_logloss: 0.177029
[61]	valid_0's binary_logloss: 0.177153
[62]	valid_0's binary_logloss: 0.177167
[63]	valid_0's binary_logloss: 0.17753
[64]	valid_0's binary_logloss: 0.177793
[65]	valid_0's binary_logloss: 0.17818
[66]	valid_0's binary_logloss: 0.178526
[67]	valid_0's binary_logloss: 0.178461
[68]	valid_0's binary_logloss: 0.178287
[69]	valid_0's binary_logloss: 0.178026
[70]	valid_0's binary_logloss: 0.177617
[71]	valid_0's binary_logloss: 0.177858
[72]	valid_0's binary_logloss: 0.17808
[73]	valid_0's binary_logloss: 0.178188
[74]	valid_0's binary_logloss: 0.178151
[75]	valid_0's binary_logloss: 0.17848
[76]	valid_0's binary_logloss: 0.178795
[77]	valid_0's binary_logloss: 0.179477
[78]	valid_0's binary_logloss: 0.179928
[79]	valid_0's binary_logloss: 0.180357
[80]	valid_0's binary_logloss: 0.18098
[81]	valid_0's binary_logloss: 0.180933
[82]	valid_0's binary_logloss: 0.180992
[83]	valid_0's binary_logloss: 0.181158
[84]	valid_0's binary_logloss: 0.181479
[85]	valid_0's binary_logloss: 0.181712
[86]	valid_0's binary_logloss: 0.182176
[87]	valid_0's binary_logloss: 0.18263
[88]	valid_0's binary_logloss: 0.182855
[89]	valid_0's binary_logloss: 0.183055

Trening klas:  16%|█▌        | 78/500 [14:01<1:09:05,  9.82s/klasa, klasa=class_78, F1_klasy=0.7293, F1_macro=0.8569, drzewa=60]




Trening klas:  16%|█▌        | 79/500 [14:01<1:00:11,  8.58s/klasa, klasa=class_78, F1_klasy=0.7293, F1_macro=0.8569, drzewa=60]

[90]	valid_0's binary_logloss: 0.183869
[1]	valid_0's binary_logloss: 0.160371
[2]	valid_0's binary_logloss: 0.148931
[3]	valid_0's binary_logloss: 0.140434
[4]	valid_0's binary_logloss: 0.133657
[5]	valid_0's binary_logloss: 0.127745
[6]	valid_0's binary_logloss: 0.122267
[7]	valid_0's binary_logloss: 0.117468
[8]	valid_0's binary_logloss: 0.113381
[9]	valid_0's binary_logloss: 0.109541
[10]	valid_0's binary_logloss: 0.105822
[11]	valid_0's binary_logloss: 0.102648
[12]	valid_0's binary_logloss: 0.0996893
[13]	valid_0's binary_logloss: 0.0968823
[14]	valid_0's binary_logloss: 0.0943659
[15]	valid_0's binary_logloss: 0.0919694
[16]	valid_0's binary_logloss: 0.0901383
[17]	valid_0's binary_logloss: 0.0882796
[18]	valid_0's binary_logloss: 0.0863425
[19]	valid_0's binary_logloss: 0.084569
[20]	valid_0's binary_logloss: 0.0826222
[21]	valid_0's binary_logloss: 0.0810072
[22]	valid_0's binary_logloss: 0.0793745
[23]	valid_0's binary_logloss: 0.077955
[24]	valid_0's binary_logloss: 0.0767391
[25]	valid_0's binary_logloss: 0.0753958
[26]	valid_0's binary_logloss: 0.0740829
[27]	valid_0's binary_logloss: 0.0731139
[28]	valid_0's binary_logloss: 0.072253
[29]	valid_0's binary_logloss: 0.0713283
[30]	valid_0's binary_logloss: 0.0704114
[31]	valid_0's binary_logloss: 0.0695011
[32]	valid_0's binary_logloss: 0.0686198
[33]	valid_0's binary_logloss: 0.0677903
[34]	valid_0's binary_logloss: 0.0669487
[35]	valid_0's binary_logloss: 0.0663011
[36]	valid_0's binary_logloss: 0.0656421
[37]	valid_0's binary_logloss: 0.0650918
[38]	valid_0's binary_logloss: 0.0646293
[39]	valid_0's binary_logloss: 0.0641789
[40]	valid_0's binary_logloss: 0.0635998
[41]	valid_0's binary_logloss: 0.0631033
[42]	valid_0's binary_logloss: 0.0626191
[43]	valid_0's binary_logloss: 0.062118
[44]	valid_0's binary_logloss: 0.0618322
[45]	valid_0's binary_logloss: 0.0615238
[46]	valid_0's binary_logloss: 0.0612845
[47]	valid_0's binary_logloss: 0.0611072
[48]	valid_0's binary_logloss: 0.06069
[49]	valid_0's binary_logloss: 0.0604899
[50]	valid_0's binary_logloss: 0.0602884
[51]	valid_0's binary_logloss: 0.0601899
[52]	valid_0's binary_logloss: 0.0602324
[53]	valid_0's binary_logloss: 0.0599377
[54]	valid_0's binary_logloss: 0.0598426
[55]	valid_0's binary_logloss: 0.0598671
[56]	valid_0's binary_logloss: 0.0599137
[57]	valid_0's binary_logloss: 0.0599275
[58]	valid_0's binary_logloss: 0.059901
[59]	valid_0's binary_logloss: 0.0599348
[60]	valid_0's binary_logloss: 0.0597197
[61]	valid_0's binary_logloss: 0.059632
[62]	valid_0's binary_logloss: 0.0593437
[63]	valid_0's binary_logloss: 0.0592915
[64]	valid_0's binary_logloss: 0.0590865
[65]	valid_0's binary_logloss: 0.0590461
[66]	valid_0's binary_logloss: 0.058994
[67]	valid_0's binary_logloss: 0.0588936
[68]	valid_0's binary_logloss: 0.0588629
[69]	valid_0's binary_logloss: 0.0587765
[70]	valid_0's binary_logloss: 0.0590111
[71]	valid_0's binary_logloss: 0.0588787
[72]	valid_0's binary_logloss: 0.0589
[73]	valid_0's binary_logloss: 0.0587806
[74]	valid_0's binary_logloss: 0.0586841
[75]	valid_0's binary_logloss: 0.058681
[76]	valid_0's binary_logloss: 0.0585077
[77]	valid_0's binary_logloss: 0.0583695
[78]	valid_0's binary_logloss: 0.0583111
[79]	valid_0's binary_logloss: 0.0583619
[80]	valid_0's binary_logloss: 0.058474
[81]	valid_0's binary_logloss: 0.0586259
[82]	valid_0's binary_logloss: 0.0587837
[83]	valid_0's binary_logloss: 0.0588276
[84]	valid_0's binary_logloss: 0.0587768
[85]	valid_0's binary_logloss: 0.0589701
[86]	valid_0's binary_logloss: 0.0591076
[87]	valid_0's binary_logloss: 0.0590334
[88]	valid_0's binary_logloss: 0.0590884
[89]	valid_0's binary_logloss: 0.0589989
[90]	valid_0's binary_logloss: 0.0590951
[91]	valid_0's binary_logloss: 0.0591395
[92]	valid_0's binary_logloss: 0.0590006
[93]	valid_0's binary_logloss: 0.0590199
[94]	valid_0's binary_logloss: 0.0590175
[95]	valid_0's binary_logloss: 0.0589003
[96]	valid_0's binary_logloss: 0.0589494
[97]	valid_0's binary_logloss: 0.0590044
[98]	valid_0's binary_logloss: 0.0588309
[99]	valid_0's binary_logloss: 0.058855
[100]	valid_0's binary_logloss: 0.0590912
[101]	valid_0's binary_logloss: 0.0590137
[102]	valid_0's binary_logloss: 0.0590394
[103]	valid_0's binary_logloss: 0.0590416
[104]	valid_0's binary_logloss: 0.0590598
[105]	valid_0's binary_logloss: 0.0591235
[106]	valid_0's binary_logloss: 0.0590717
[107]	valid_0's binary_logloss: 0.0590875

Trening klas:  16%|█▌        | 79/500 [14:08<1:00:11,  8.58s/klasa, klasa=class_79, F1_klasy=0.7348, F1_macro=0.8553, drzewa=78]




Trening klas:  16%|█▌        | 80/500 [14:08<57:41,  8.24s/klasa, klasa=class_79, F1_klasy=0.7348, F1_macro=0.8553, drzewa=78]

[108]	valid_0's binary_logloss: 0.0592431
[1]	valid_0's binary_logloss: 0.309599
[2]	valid_0's binary_logloss: 0.27484
[3]	valid_0's binary_logloss: 0.251051
[4]	valid_0's binary_logloss: 0.233286
[5]	valid_0's binary_logloss: 0.218957
[6]	valid_0's binary_logloss: 0.206909
[7]	valid_0's binary_logloss: 0.196763
[8]	valid_0's binary_logloss: 0.188245
[9]	valid_0's binary_logloss: 0.180933
[10]	valid_0's binary_logloss: 0.174513
[11]	valid_0's binary_logloss: 0.168799
[12]	valid_0's binary_logloss: 0.163409
[13]	valid_0's binary_logloss: 0.159026
[14]	valid_0's binary_logloss: 0.154884
[15]	valid_0's binary_logloss: 0.15139
[16]	valid_0's binary_logloss: 0.148322
[17]	valid_0's binary_logloss: 0.145372
[18]	valid_0's binary_logloss: 0.142954
[19]	valid_0's binary_logloss: 0.140749
[20]	valid_0's binary_logloss: 0.138747
[21]	valid_0's binary_logloss: 0.137173
[22]	valid_0's binary_logloss: 0.135521
[23]	valid_0's binary_logloss: 0.134137
[24]	valid_0's binary_logloss: 0.132848
[25]	valid_0's binary_logloss: 0.131674
[26]	valid_0's binary_logloss: 0.130849
[27]	valid_0's binary_logloss: 0.130002
[28]	valid_0's binary_logloss: 0.129184
[29]	valid_0's binary_logloss: 0.128602
[30]	valid_0's binary_logloss: 0.127972
[31]	valid_0's binary_logloss: 0.127443
[32]	valid_0's binary_logloss: 0.126907
[33]	valid_0's binary_logloss: 0.126667
[34]	valid_0's binary_logloss: 0.126404
[35]	valid_0's binary_logloss: 0.126173
[36]	valid_0's binary_logloss: 0.125678
[37]	valid_0's binary_logloss: 0.125679
[38]	valid_0's binary_logloss: 0.125819
[39]	valid_0's binary_logloss: 0.125689
[40]	valid_0's binary_logloss: 0.125713
[41]	valid_0's binary_logloss: 0.1258
[42]	valid_0's binary_logloss: 0.126067
[43]	valid_0's binary_logloss: 0.12621
[44]	valid_0's binary_logloss: 0.126379
[45]	valid_0's binary_logloss: 0.126545
[46]	valid_0's binary_logloss: 0.126704
[47]	valid_0's binary_logloss: 0.127095
[48]	valid_0's binary_logloss: 0.12722
[49]	valid_0's binary_logloss: 0.12731
[50]	valid_0's binary_logloss: 0.127591
[51]	valid_0's binary_logloss: 0.127705
[52]	valid_0's binary_logloss: 0.128017
[53]	valid_0's binary_logloss: 0.128345
[54]	valid_0's binary_logloss: 0.128529
[55]	valid_0's binary_logloss: 0.128506
[56]	valid_0's binary_logloss: 0.12866
[57]	valid_0's binary_logloss: 0.128796
[58]	valid_0's binary_logloss: 0.129206
[59]	valid_0's binary_logloss: 0.129677
[60]	valid_0's binary_logloss: 0.13013
[61]	valid_0's binary_logloss: 0.130113
[62]	valid_0's binary_logloss: 0.129905
[63]	valid_0's binary_logloss: 0.130285
[64]	valid_0's binary_logloss: 0.130501
[65]	valid_0's binary_logloss: 0.130693

Trening klas:  16%|█▌        | 80/500 [14:13<57:41,  8.24s/klasa, klasa=class_80, F1_klasy=0.8064, F1_macro=0.8547, drzewa=36]




Trening klas:  16%|█▌        | 81/500 [14:13<50:19,  7.21s/klasa, klasa=class_80, F1_klasy=0.8064, F1_macro=0.8547, drzewa=36]

[66]	valid_0's binary_logloss: 0.131182
[1]	valid_0's binary_logloss: 0.384099
[2]	valid_0's binary_logloss: 0.353542
[3]	valid_0's binary_logloss: 0.329118
[4]	valid_0's binary_logloss: 0.311
[5]	valid_0's binary_logloss: 0.298363
[6]	valid_0's binary_logloss: 0.286175
[7]	valid_0's binary_logloss: 0.274528
[8]	valid_0's binary_logloss: 0.266238
[9]	valid_0's binary_logloss: 0.260197
[10]	valid_0's binary_logloss: 0.253518
[11]	valid_0's binary_logloss: 0.248727
[12]	valid_0's binary_logloss: 0.242882
[13]	valid_0's binary_logloss: 0.23793
[14]	valid_0's binary_logloss: 0.234263
[15]	valid_0's binary_logloss: 0.230653
[16]	valid_0's binary_logloss: 0.226478
[17]	valid_0's binary_logloss: 0.221751
[18]	valid_0's binary_logloss: 0.217746
[19]	valid_0's binary_logloss: 0.214735
[20]	valid_0's binary_logloss: 0.211257
[21]	valid_0's binary_logloss: 0.208679
[22]	valid_0's binary_logloss: 0.205652
[23]	valid_0's binary_logloss: 0.203417
[24]	valid_0's binary_logloss: 0.20124
[25]	valid_0's binary_logloss: 0.199092
[26]	valid_0's binary_logloss: 0.19798
[27]	valid_0's binary_logloss: 0.197079
[28]	valid_0's binary_logloss: 0.19594
[29]	valid_0's binary_logloss: 0.195262
[30]	valid_0's binary_logloss: 0.194572
[31]	valid_0's binary_logloss: 0.19318
[32]	valid_0's binary_logloss: 0.191801
[33]	valid_0's binary_logloss: 0.190056
[34]	valid_0's binary_logloss: 0.189336
[35]	valid_0's binary_logloss: 0.188592
[36]	valid_0's binary_logloss: 0.187334
[37]	valid_0's binary_logloss: 0.186679
[38]	valid_0's binary_logloss: 0.18615
[39]	valid_0's binary_logloss: 0.185105
[40]	valid_0's binary_logloss: 0.183918
[41]	valid_0's binary_logloss: 0.183312
[42]	valid_0's binary_logloss: 0.182578
[43]	valid_0's binary_logloss: 0.181995
[44]	valid_0's binary_logloss: 0.181607
[45]	valid_0's binary_logloss: 0.181062
[46]	valid_0's binary_logloss: 0.181027
[47]	valid_0's binary_logloss: 0.181162
[48]	valid_0's binary_logloss: 0.180979
[49]	valid_0's binary_logloss: 0.181034
[50]	valid_0's binary_logloss: 0.180615
[51]	valid_0's binary_logloss: 0.180022
[52]	valid_0's binary_logloss: 0.17953
[53]	valid_0's binary_logloss: 0.179255
[54]	valid_0's binary_logloss: 0.179197
[55]	valid_0's binary_logloss: 0.178337
[56]	valid_0's binary_logloss: 0.177736
[57]	valid_0's binary_logloss: 0.177477
[58]	valid_0's binary_logloss: 0.177549
[59]	valid_0's binary_logloss: 0.177475
[60]	valid_0's binary_logloss: 0.17708
[61]	valid_0's binary_logloss: 0.177144
[62]	valid_0's binary_logloss: 0.176911
[63]	valid_0's binary_logloss: 0.176665
[64]	valid_0's binary_logloss: 0.176666
[65]	valid_0's binary_logloss: 0.176891
[66]	valid_0's binary_logloss: 0.176721
[67]	valid_0's binary_logloss: 0.176393
[68]	valid_0's binary_logloss: 0.176313
[69]	valid_0's binary_logloss: 0.176336
[70]	valid_0's binary_logloss: 0.176288
[71]	valid_0's binary_logloss: 0.176702
[72]	valid_0's binary_logloss: 0.177078
[73]	valid_0's binary_logloss: 0.176956
[74]	valid_0's binary_logloss: 0.176824
[75]	valid_0's binary_logloss: 0.176998
[76]	valid_0's binary_logloss: 0.1774
[77]	valid_0's binary_logloss: 0.177743
[78]	valid_0's binary_logloss: 0.178024
[79]	valid_0's binary_logloss: 0.178327
[80]	valid_0's binary_logloss: 0.178222
[81]	valid_0's binary_logloss: 0.178185
[82]	valid_0's binary_logloss: 0.177998
[83]	valid_0's binary_logloss: 0.177685
[84]	valid_0's binary_logloss: 0.177772
[85]	valid_0's binary_logloss: 0.177152
[86]	valid_0's binary_logloss: 0.177369
[87]	valid_0's binary_logloss: 0.177405
[88]	valid_0's binary_logloss: 0.178046
[89]	valid_0's binary_logloss: 0.178523
[90]	valid_0's binary_logloss: 0.178856
[91]	valid_0's binary_logloss: 0.179355
[92]	valid_0's binary_logloss: 0.179889
[93]	valid_0's binary_logloss: 0.18041
[94]	valid_0's binary_logloss: 0.180736
[95]	valid_0's binary_logloss: 0.181013
[96]	valid_0's binary_logloss: 0.181649
[97]	valid_0's binary_logloss: 0.182075

Trening klas:  16%|█▌        | 81/500 [14:20<50:19,  7.21s/klasa, klasa=class_81, F1_klasy=0.7315, F1_macro=0.8532, drzewa=70]




Trening klas:  16%|█▋        | 82/500 [14:20<48:42,  6.99s/klasa, klasa=class_81, F1_klasy=0.7315, F1_macro=0.8532, drzewa=70]

[98]	valid_0's binary_logloss: 0.182421
[99]	valid_0's binary_logloss: 0.182883
[100]	valid_0's binary_logloss: 0.183554
[1]	valid_0's binary_logloss: 0.384145
[2]	valid_0's binary_logloss: 0.353538
[3]	valid_0's binary_logloss: 0.329115
[4]	valid_0's binary_logloss: 0.310998
[5]	valid_0's binary_logloss: 0.297995
[6]	valid_0's binary_logloss: 0.285733
[7]	valid_0's binary_logloss: 0.274366
[8]	valid_0's binary_logloss: 0.266128
[9]	valid_0's binary_logloss: 0.259439
[10]	valid_0's binary_logloss: 0.253129
[11]	valid_0's binary_logloss: 0.247371
[12]	valid_0's binary_logloss: 0.242709
[13]	valid_0's binary_logloss: 0.237875
[14]	valid_0's binary_logloss: 0.235218
[15]	valid_0's binary_logloss: 0.230579
[16]	valid_0's binary_logloss: 0.226657
[17]	valid_0's binary_logloss: 0.222955
[18]	valid_0's binary_logloss: 0.219718
[19]	valid_0's binary_logloss: 0.216505
[20]	valid_0's binary_logloss: 0.213754
[21]	valid_0's binary_logloss: 0.211075
[22]	valid_0's binary_logloss: 0.208739
[23]	valid_0's binary_logloss: 0.206054
[24]	valid_0's binary_logloss: 0.203495
[25]	valid_0's binary_logloss: 0.201168
[26]	valid_0's binary_logloss: 0.199531
[27]	valid_0's binary_logloss: 0.197628
[28]	valid_0's binary_logloss: 0.196374
[29]	valid_0's binary_logloss: 0.195323
[30]	valid_0's binary_logloss: 0.193929
[31]	valid_0's binary_logloss: 0.192202
[32]	valid_0's binary_logloss: 0.190736
[33]	valid_0's binary_logloss: 0.189113
[34]	valid_0's binary_logloss: 0.188212
[35]	valid_0's binary_logloss: 0.187301
[36]	valid_0's binary_logloss: 0.185792
[37]	valid_0's binary_logloss: 0.184904
[38]	valid_0's binary_logloss: 0.183552
[39]	valid_0's binary_logloss: 0.182737
[40]	valid_0's binary_logloss: 0.181601
[41]	valid_0's binary_logloss: 0.180571
[42]	valid_0's binary_logloss: 0.179535
[43]	valid_0's binary_logloss: 0.178872
[44]	valid_0's binary_logloss: 0.178439
[45]	valid_0's binary_logloss: 0.178249
[46]	valid_0's binary_logloss: 0.177752
[47]	valid_0's binary_logloss: 0.177943
[48]	valid_0's binary_logloss: 0.177635
[49]	valid_0's binary_logloss: 0.177749
[50]	valid_0's binary_logloss: 0.177468
[51]	valid_0's binary_logloss: 0.177323
[52]	valid_0's binary_logloss: 0.176856
[53]	valid_0's binary_logloss: 0.176588
[54]	valid_0's binary_logloss: 0.176089
[55]	valid_0's binary_logloss: 0.175961
[56]	valid_0's binary_logloss: 0.17608
[57]	valid_0's binary_logloss: 0.175561
[58]	valid_0's binary_logloss: 0.175195
[59]	valid_0's binary_logloss: 0.17557
[60]	valid_0's binary_logloss: 0.176008
[61]	valid_0's binary_logloss: 0.176278
[62]	valid_0's binary_logloss: 0.175937
[63]	valid_0's binary_logloss: 0.175899
[64]	valid_0's binary_logloss: 0.17593
[65]	valid_0's binary_logloss: 0.17581
[66]	valid_0's binary_logloss: 0.17625
[67]	valid_0's binary_logloss: 0.176175
[68]	valid_0's binary_logloss: 0.175907
[69]	valid_0's binary_logloss: 0.175865
[70]	valid_0's binary_logloss: 0.176001
[71]	valid_0's binary_logloss: 0.176324
[72]	valid_0's binary_logloss: 0.17717
[73]	valid_0's binary_logloss: 0.177178
[74]	valid_0's binary_logloss: 0.176759
[75]	valid_0's binary_logloss: 0.177145
[76]	valid_0's binary_logloss: 0.17737
[77]	valid_0's binary_logloss: 0.177669
[78]	valid_0's binary_logloss: 0.177954
[79]	valid_0's binary_logloss: 0.177849
[80]	valid_0's binary_logloss: 0.17801
[81]	valid_0's binary_logloss: 0.177799
[82]	valid_0's binary_logloss: 0.177787
[83]	valid_0's binary_logloss: 0.177731
[84]	valid_0's binary_logloss: 0.177831
[85]	valid_0's binary_logloss: 0.17764
[86]	valid_0's binary_logloss: 0.17758
[87]	valid_0's binary_logloss: 0.177529
[88]	valid_0's binary_logloss: 0.177623

Trening klas:  16%|█▋        | 82/500 [14:26<48:42,  6.99s/klasa, klasa=class_82, F1_klasy=0.7278, F1_macro=0.8517, drzewa=58]




Trening klas:  17%|█▋        | 83/500 [14:26<46:21,  6.67s/klasa, klasa=class_82, F1_klasy=0.7278, F1_macro=0.8517, drzewa=58]

[1]	valid_0's binary_logloss: 0.123278
[2]	valid_0's binary_logloss: 0.114791
[3]	valid_0's binary_logloss: 0.10784
[4]	valid_0's binary_logloss: 0.101772
[5]	valid_0's binary_logloss: 0.096691
[6]	valid_0's binary_logloss: 0.0919961
[7]	valid_0's binary_logloss: 0.087488
[8]	valid_0's binary_logloss: 0.0832596
[9]	valid_0's binary_logloss: 0.0793551
[10]	valid_0's binary_logloss: 0.0758143
[11]	valid_0's binary_logloss: 0.0726292
[12]	valid_0's binary_logloss: 0.0694779
[13]	valid_0's binary_logloss: 0.0665481
[14]	valid_0's binary_logloss: 0.063789
[15]	valid_0's binary_logloss: 0.0612527
[16]	valid_0's binary_logloss: 0.0587068
[17]	valid_0's binary_logloss: 0.0563282
[18]	valid_0's binary_logloss: 0.0541624
[19]	valid_0's binary_logloss: 0.0520645
[20]	valid_0's binary_logloss: 0.0502454
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0485113
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0468059
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.0453283
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0438593
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.0422883
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.0409799
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.0397969
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.0386538
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.0375486
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.036501
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.0355197
[32]	valid_0's binary_logloss: 0.0345823
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.0336652
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.0328563
[35]	valid_0's binary_logloss: 0.0321202
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.0313972
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.0306393
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.0298952
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.0291965
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.0286742
[41]	valid_0's binary_logloss: 0.0279926
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.027303
[43]	valid_0's binary_logloss: 0.0267669
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.0261847
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.0256089
[46]	valid_0's binary_logloss: 0.0251141
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.0247317
[48]	valid_0's binary_logloss: 0.024319
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.02394
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.0235962
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.0232746
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.0229283
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.0225415
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.0222323
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.0219243
[56]	valid_0's binary_logloss: 0.0216387
[57]	valid_0's binary_logloss: 0.0213472
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.0212061
[59]	valid_0's binary_logloss: 0.020967
[60]	valid_0's binary_logloss: 0.0207812
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.0205988
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.0204802
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.0203808
[64]	valid_0's binary_logloss: 0.0202535
[65]	valid_0's binary_logloss: 0.0201246
[66]	valid_0's binary_logloss: 0.0198936
[67]	valid_0's binary_logloss: 0.0197378
[68]	valid_0's binary_logloss: 0.0195929
[69]	valid_0's binary_logloss: 0.0193928
[70]	valid_0's binary_logloss: 0.0192367
[71]	valid_0's binary_logloss: 0.0191387
[72]	valid_0's binary_logloss: 0.019036
[73]	valid_0's binary_logloss: 0.0189038
[74]	valid_0's binary_logloss: 0.0188368
[75]	valid_0's binary_logloss: 0.0187358
[76]	valid_0's binary_logloss: 0.018635
[77]	valid_0's binary_logloss: 0.0185501
[78]	valid_0's binary_logloss: 0.0183072
[79]	valid_0's binary_logloss: 0.0182182
[80]	valid_0's binary_logloss: 0.0181568
[81]	valid_0's binary_logloss: 0.018097
[82]	valid_0's binary_logloss: 0.0180194
[83]	valid_0's binary_logloss: 0.0179299
[84]	valid_0's binary_logloss: 0.0178841
[85]	valid_0's binary_logloss: 0.0178475
[86]	valid_0's binary_logloss: 0.0178553
[87]	valid_0's binary_logloss: 0.0178172
[88]	valid_0's binary_logloss: 0.0177929
[89]	valid_0's binary_logloss: 0.0177775
[90]	valid_0's binary_logloss: 0.0177445
[91]	valid_0's binary_logloss: 0.0177226
[92]	valid_0's binary_logloss: 0.0176478
[93]	valid_0's binary_logloss: 0.0176722
[94]	valid_0's binary_logloss: 0.0176416
[95]	valid_0's binary_logloss: 0.0176063
[96]	valid_0's binary_logloss: 0.0175072
[97]	valid_0's binary_logloss: 0.0173966
[98]	valid_0's binary_logloss: 0.0172713
[99]	valid_0's binary_logloss: 0.0171209
[100]	valid_0's binary_logloss: 0.0170658
[101]	valid_0's binary_logloss: 0.0170845
[102]	valid_0's binary_logloss: 0.017137
[103]	valid_0's binary_logloss: 0.017134
[104]	valid_0's binary_logloss: 0.0170822
[105]	valid_0's binary_logloss: 0.0170065
[106]	valid_0's binary_logloss: 0.0169384
[107]	valid_0's binary_logloss: 0.0170041
[108]	valid_0's binary_logloss: 0.0170652
[109]	valid_0's binary_logloss: 0.0171694
[110]	valid_0's binary_logloss: 0.0171372
[111]	valid_0's binary_logloss: 0.0171843
[112]	valid_0's binary_logloss: 0.0172033
[113]	valid_0's binary_logloss: 0.0171235
[114]	valid_0's binary_logloss: 0.0171342
[115]	valid_0's binary_logloss: 0.0171127
[116]	valid_0's binary_logloss: 0.0170513
[117]	valid_0's binary_logloss: 0.0170269
[118]	valid_0's binary_logloss: 0.0170298
[119]	valid_0's binary_logloss: 0.0169597
[120]	valid_0's binary_logloss: 0.0169559
[121]	valid_0's binary_logloss: 0.0170074
[122]	valid_0's binary_logloss: 0.0170251
[123]	valid_0's binary_logloss: 0.0170304
[124]	valid_0's binary_logloss: 0.0169911
[125]	valid_0's binary_logloss: 0.0169418
[126]	valid_0's binary_logloss: 0.0170499
[127]	valid_0's binary_logloss: 0.0170525
[128]	valid_0's binary_logloss: 0.0171156
[129]	valid_0's binary_logloss: 0.0171806
[130]	valid_0's binary_logloss: 0.0172508
[131]	valid_0's binary_logloss: 0.0173674
[132]	valid_0's binary_logloss: 0.0173159
[133]	valid_0's binary_logloss: 0.0173905
[134]	valid_0's binary_logloss: 0.0175308
[135]	valid_0's binary_logloss: 0.017579
[136]	valid_0's binary_logloss: 0.0175433

Trening klas:  17%|█▋        | 83/500 [14:33<46:21,  6.67s/klasa, klasa=class_83, F1_klasy=0.8436, F1_macro=0.8516, drzewa=106]




Trening klas:  17%|█▋        | 84/500 [14:33<48:52,  7.05s/klasa, klasa=class_83, F1_klasy=0.8436, F1_macro=0.8516, drzewa=106]

[1]	valid_0's binary_logloss: 0.25519
[2]	valid_0's binary_logloss: 0.225782
[3]	valid_0's binary_logloss: 0.204888
[4]	valid_0's binary_logloss: 0.18849
[5]	valid_0's binary_logloss: 0.175826
[6]	valid_0's binary_logloss: 0.165145
[7]	valid_0's binary_logloss: 0.156034
[8]	valid_0's binary_logloss: 0.14813
[9]	valid_0's binary_logloss: 0.141107
[10]	valid_0's binary_logloss: 0.134967
[11]	valid_0's binary_logloss: 0.129582
[12]	valid_0's binary_logloss: 0.124551
[13]	valid_0's binary_logloss: 0.119995
[14]	valid_0's binary_logloss: 0.116118
[15]	valid_0's binary_logloss: 0.112396
[16]	valid_0's binary_logloss: 0.109007
[17]	valid_0's binary_logloss: 0.106196
[18]	valid_0's binary_logloss: 0.103536
[19]	valid_0's binary_logloss: 0.101033
[20]	valid_0's binary_logloss: 0.0988342
[21]	valid_0's binary_logloss: 0.096808
[22]	valid_0's binary_logloss: 0.0948204
[23]	valid_0's binary_logloss: 0.0928687
[24]	valid_0's binary_logloss: 0.0912273
[25]	valid_0's binary_logloss: 0.0896659
[26]	valid_0's binary_logloss: 0.0881807
[27]	valid_0's binary_logloss: 0.0868085
[28]	valid_0's binary_logloss: 0.0855241
[29]	valid_0's binary_logloss: 0.0843022
[30]	valid_0's binary_logloss: 0.0833086
[31]	valid_0's binary_logloss: 0.0824069
[32]	valid_0's binary_logloss: 0.0814825
[33]	valid_0's binary_logloss: 0.0808635
[34]	valid_0's binary_logloss: 0.0802014
[35]	valid_0's binary_logloss: 0.0796372
[36]	valid_0's binary_logloss: 0.0789777
[37]	valid_0's binary_logloss: 0.078465
[38]	valid_0's binary_logloss: 0.0778051
[39]	valid_0's binary_logloss: 0.0773602
[40]	valid_0's binary_logloss: 0.0768049
[41]	valid_0's binary_logloss: 0.0764232
[42]	valid_0's binary_logloss: 0.0761455
[43]	valid_0's binary_logloss: 0.0759412
[44]	valid_0's binary_logloss: 0.0757552
[45]	valid_0's binary_logloss: 0.0757464
[46]	valid_0's binary_logloss: 0.0755564
[47]	valid_0's binary_logloss: 0.0753339
[48]	valid_0's binary_logloss: 0.0749531
[49]	valid_0's binary_logloss: 0.0747324
[50]	valid_0's binary_logloss: 0.0745227
[51]	valid_0's binary_logloss: 0.0743289
[52]	valid_0's binary_logloss: 0.0742965
[53]	valid_0's binary_logloss: 0.0741623
[54]	valid_0's binary_logloss: 0.0740339
[55]	valid_0's binary_logloss: 0.0740923
[56]	valid_0's binary_logloss: 0.073849
[57]	valid_0's binary_logloss: 0.0736519
[58]	valid_0's binary_logloss: 0.0733795
[59]	valid_0's binary_logloss: 0.0734886
[60]	valid_0's binary_logloss: 0.0736277
[61]	valid_0's binary_logloss: 0.0737749
[62]	valid_0's binary_logloss: 0.0736924
[63]	valid_0's binary_logloss: 0.0737797
[64]	valid_0's binary_logloss: 0.0737653
[65]	valid_0's binary_logloss: 0.0739027
[66]	valid_0's binary_logloss: 0.0743076
[67]	valid_0's binary_logloss: 0.0745884
[68]	valid_0's binary_logloss: 0.0748549
[69]	valid_0's binary_logloss: 0.0750728
[70]	valid_0's binary_logloss: 0.0753182
[71]	valid_0's binary_logloss: 0.0753248
[72]	valid_0's binary_logloss: 0.0754995
[73]	valid_0's binary_logloss: 0.0756283
[74]	valid_0's binary_logloss: 0.0755181
[75]	valid_0's binary_logloss: 0.0755829
[76]	valid_0's binary_logloss: 0.0757811
[77]	valid_0's binary_logloss: 0.0758681
[78]	valid_0's binary_logloss: 0.0758286
[79]	valid_0's binary_logloss: 0.0760999
[80]	valid_0's binary_logloss: 0.0761871
[81]	valid_0's binary_logloss: 0.0761001
[82]	valid_0's binary_logloss: 0.0762397
[83]	valid_0's binary_logloss: 0.0761423
[84]	valid_0's binary_logloss: 0.0761198
[85]	valid_0's binary_logloss: 0.0762319

Trening klas:  17%|█▋        | 84/500 [14:39<48:52,  7.05s/klasa, klasa=class_84, F1_klasy=0.8659, F1_macro=0.8518, drzewa=58]




Trening klas:  17%|█▋        | 85/500 [14:39<46:14,  6.69s/klasa, klasa=class_84, F1_klasy=0.8659, F1_macro=0.8518, drzewa=58]

[86]	valid_0's binary_logloss: 0.0760079
[87]	valid_0's binary_logloss: 0.0760079
[88]	valid_0's binary_logloss: 0.0757722
[1]	valid_0's binary_logloss: 0.259869
[2]	valid_0's binary_logloss: 0.226785
[3]	valid_0's binary_logloss: 0.204353
[4]	valid_0's binary_logloss: 0.187168
[5]	valid_0's binary_logloss: 0.173459
[6]	valid_0's binary_logloss: 0.161519
[7]	valid_0's binary_logloss: 0.151302
[8]	valid_0's binary_logloss: 0.142572
[9]	valid_0's binary_logloss: 0.134672
[10]	valid_0's binary_logloss: 0.12782
[11]	valid_0's binary_logloss: 0.121858
[12]	valid_0's binary_logloss: 0.116177
[13]	valid_0's binary_logloss: 0.111144
[14]	valid_0's binary_logloss: 0.106428
[15]	valid_0's binary_logloss: 0.102029
[16]	valid_0's binary_logloss: 0.0982418
[17]	valid_0's binary_logloss: 0.0948247
[18]	valid_0's binary_logloss: 0.0915004
[19]	valid_0's binary_logloss: 0.0884637
[20]	valid_0's binary_logloss: 0.0857627
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.083197
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0809805
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.0788576
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0767934
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.0746977
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.0728512
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.0710944
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.0693612
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.0678982
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.0662392
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.0645681
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.0635432
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.0626506
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.0617909
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.0610009
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.0601054
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.0592595
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.0585839
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.0579556
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.057439
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.0563753
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.0558897
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.0552502
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.0547241
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.0542436
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.053784
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.0533313
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.052915
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.0526106
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.0523391
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.0521084
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.0518815
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.0518069
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.0514986
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.0512007
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.0511839
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.0512542
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.0512895
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.0513903
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.0514223
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.0510392
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.0508107
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.0508151
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.0505672
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.0505643
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.0503506
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.0500769
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.0498332
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.0494511
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.0490979
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.0489394
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.0488382
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.0487322
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.0486091
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.0487085
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.0488387
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.0488167
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.0488102
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.0488098
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.0489197
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.0488805
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.0488676
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.0488646
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.0486618
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.0486675
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.0488176
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.0488773
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.04895
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.049107
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.0490528
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.0490148
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.0490961
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.0492378
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.0491888
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.0492932
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.0491739
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.0493802
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.0495868
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.0495469
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

Trening klas:  17%|█▋        | 85/500 [14:44<46:14,  6.69s/klasa, klasa=class_85, F1_klasy=0.9186, F1_macro=0.8526, drzewa=74]




Trening klas:  17%|█▋        | 86/500 [14:44<41:53,  6.07s/klasa, klasa=class_85, F1_klasy=0.9186, F1_macro=0.8526, drzewa=74]

[100]	valid_0's binary_logloss: 0.0496492
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.0497496
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.0499546
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.0501138
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.0499805
[1]	valid_0's binary_logloss: 0.288875
[2]	valid_0's binary_logloss: 0.255815
[3]	valid_0's binary_logloss: 0.2341
[4]	valid_0's binary_logloss: 0.217642
[5]	valid_0's binary_logloss: 0.204149
[6]	valid_0's binary_logloss: 0.192349
[7]	valid_0's binary_logloss: 0.182993
[8]	valid_0's binary_logloss: 0.174544
[9]	valid_0's binary_logloss: 0.166982
[10]	valid_0's binary_logloss: 0.160203
[11]	valid_0's binary_logloss: 0.154059
[12]	valid_0's binary_logloss: 0.148388
[13]	valid_0's binary_logloss: 0.143347
[14]	valid_0's binary_logloss: 0.139025
[15]	valid_0's binary_logloss: 0.134895
[16]	valid_0's binary_logloss: 0.130703
[17]	valid_0's binary_logloss: 0.127042
[18]	valid_0's binary_logloss: 0.123882
[19]	valid_0's binary_logloss: 0.121063
[20]	valid_0's binary_logloss: 0.118443
[21]	valid_0's binary_logloss: 0.115472
[22]	valid_0's binary_logloss: 0.113065
[23]	valid_0's binary_logloss: 0.110997
[24]	valid_0's binary_logloss: 0.108997
[25]	valid_0's binary_logloss: 0.106862
[26]	valid_0's binary_logloss: 0.105145
[27]	valid_0's binary_logloss: 0.103486
[28]	valid_0's binary_logloss: 0.101874
[29]	valid_0's binary_logloss: 0.100475
[30]	valid_0's binary_logloss: 0.0991582
[31]	valid_0's binary_logloss: 0.0978188
[32]	valid_0's binary_logloss: 0.0966531
[33]	valid_0's binary_logloss: 0.0957951
[34]	valid_0's binary_logloss: 0.094566
[35]	valid_0's binary_logloss: 0.0935759
[36]	valid_0's binary_logloss: 0.0928456
[37]	valid_0's binary_logloss: 0.0919499
[38]	valid_0's binary_logloss: 0.0911468
[39]	valid_0's binary_logloss: 0.0904354
[40]	valid_0's binary_logloss: 0.0897559
[41]	valid_0's binary_logloss: 0.089007
[42]	valid_0's binary_logloss: 0.0885946
[43]	valid_0's binary_logloss: 0.0879256
[44]	valid_0's binary_logloss: 0.0874401
[45]	valid_0's binary_logloss: 0.0869236
[46]	valid_0's binary_logloss: 0.0866819
[47]	valid_0's binary_logloss: 0.0862677
[48]	valid_0's binary_logloss: 0.085827
[49]	valid_0's binary_logloss: 0.0853716
[50]	valid_0's binary_logloss: 0.0849667
[51]	valid_0's binary_logloss: 0.0847533
[52]	valid_0's binary_logloss: 0.0844168
[53]	valid_0's binary_logloss: 0.0843688
[54]	valid_0's binary_logloss: 0.0842742
[55]	valid_0's binary_logloss: 0.0840845
[56]	valid_0's binary_logloss: 0.0837097
[57]	valid_0's binary_logloss: 0.0835277
[58]	valid_0's binary_logloss: 0.0831728
[59]	valid_0's binary_logloss: 0.0830271
[60]	valid_0's binary_logloss: 0.0830252
[61]	valid_0's binary_logloss: 0.0827169
[62]	valid_0's binary_logloss: 0.0827003
[63]	valid_0's binary_logloss: 0.0826793
[64]	valid_0's binary_logloss: 0.0824424
[65]	valid_0's binary_logloss: 0.0823495
[66]	valid_0's binary_logloss: 0.0820824
[67]	valid_0's binary_logloss: 0.0821019
[68]	valid_0's binary_logloss: 0.0820614
[69]	valid_0's binary_logloss: 0.0819931
[70]	valid_0's binary_logloss: 0.0820441
[71]	valid_0's binary_logloss: 0.0822038
[72]	valid_0's binary_logloss: 0.0820794
[73]	valid_0's binary_logloss: 0.0821211
[74]	valid_0's binary_logloss: 0.0823221
[75]	valid_0's binary_logloss: 0.0824528
[76]	valid_0's binary_logloss: 0.0826096
[77]	valid_0's binary_logloss: 0.0826257
[78]	valid_0's binary_logloss: 0.0827539
[79]	valid_0's binary_logloss: 0.0828852
[80]	valid_0's binary_logloss: 0.0829754
[81]	valid_0's binary_logloss: 0.0830269
[82]	valid_0's binary_logloss: 0.0831625
[83]	valid_0's binary_logloss: 0.0833473
[84]	valid_0's binary_logloss: 0.0834043
[85]	valid_0's binary_logloss: 0.0832939
[86]	valid_0's binary_logloss: 0.083256
[87]	valid_0's binary_logloss: 0.0835045
[88]	valid_0's binary_logloss: 0.083502
[89]	valid_0's binary_logloss: 0.0836716
[90]	valid_0's binary_logloss: 0.0837381
[91]	valid_0's binary_logloss: 0.0836867
[92]	valid_0's binary_logloss: 0.08362
[93]	valid_0's binary_logloss: 0.0838506
[94]	valid_0's binary_logloss: 0.0839026
[95]	valid_0's binary_logloss: 0.0839425
[96]	valid_0's binary_logloss: 0.0839426
[97]	valid_0's binary_logloss: 0.0839651

Trening klas:  17%|█▋        | 86/500 [14:50<41:53,  6.07s/klasa, klasa=class_86, F1_klasy=0.8634, F1_macro=0.8527, drzewa=69]




Trening klas:  17%|█▋        | 87/500 [14:50<42:39,  6.20s/klasa, klasa=class_86, F1_klasy=0.8634, F1_macro=0.8527, drzewa=69]

[98]	valid_0's binary_logloss: 0.084066
[99]	valid_0's binary_logloss: 0.0842421
[1]	valid_0's binary_logloss: 0.242981
[2]	valid_0's binary_logloss: 0.227088
[3]	valid_0's binary_logloss: 0.216044
[4]	valid_0's binary_logloss: 0.208495
[5]	valid_0's binary_logloss: 0.202818
[6]	valid_0's binary_logloss: 0.197876
[7]	valid_0's binary_logloss: 0.194329
[8]	valid_0's binary_logloss: 0.191552
[9]	valid_0's binary_logloss: 0.188509
[10]	valid_0's binary_logloss: 0.185729
[11]	valid_0's binary_logloss: 0.183738
[12]	valid_0's binary_logloss: 0.181177
[13]	valid_0's binary_logloss: 0.17924
[14]	valid_0's binary_logloss: 0.177798
[15]	valid_0's binary_logloss: 0.176493
[16]	valid_0's binary_logloss: 0.175215
[17]	valid_0's binary_logloss: 0.174379
[18]	valid_0's binary_logloss: 0.173477
[19]	valid_0's binary_logloss: 0.172782
[20]	valid_0's binary_logloss: 0.172184
[21]	valid_0's binary_logloss: 0.171651
[22]	valid_0's binary_logloss: 0.170909
[23]	valid_0's binary_logloss: 0.169973
[24]	valid_0's binary_logloss: 0.169736
[25]	valid_0's binary_logloss: 0.169245
[26]	valid_0's binary_logloss: 0.168935
[27]	valid_0's binary_logloss: 0.169032
[28]	valid_0's binary_logloss: 0.169052
[29]	valid_0's binary_logloss: 0.16937
[30]	valid_0's binary_logloss: 0.169281
[31]	valid_0's binary_logloss: 0.16888
[32]	valid_0's binary_logloss: 0.16855
[33]	valid_0's binary_logloss: 0.168022
[34]	valid_0's binary_logloss: 0.167914
[35]	valid_0's binary_logloss: 0.167879
[36]	valid_0's binary_logloss: 0.168121
[37]	valid_0's binary_logloss: 0.168136
[38]	valid_0's binary_logloss: 0.168697
[39]	valid_0's binary_logloss: 0.168676
[40]	valid_0's binary_logloss: 0.168383
[41]	valid_0's binary_logloss: 0.168376
[42]	valid_0's binary_logloss: 0.168021
[43]	valid_0's binary_logloss: 0.167727
[44]	valid_0's binary_logloss: 0.167343
[45]	valid_0's binary_logloss: 0.167394
[46]	valid_0's binary_logloss: 0.166696
[47]	valid_0's binary_logloss: 0.166844
[48]	valid_0's binary_logloss: 0.166839
[49]	valid_0's binary_logloss: 0.166946
[50]	valid_0's binary_logloss: 0.166676
[51]	valid_0's binary_logloss: 0.166509
[52]	valid_0's binary_logloss: 0.16627
[53]	valid_0's binary_logloss: 0.166256
[54]	valid_0's binary_logloss: 0.166215
[55]	valid_0's binary_logloss: 0.165898
[56]	valid_0's binary_logloss: 0.165916
[57]	valid_0's binary_logloss: 0.166194
[58]	valid_0's binary_logloss: 0.166534
[59]	valid_0's binary_logloss: 0.166509
[60]	valid_0's binary_logloss: 0.167006
[61]	valid_0's binary_logloss: 0.167068
[62]	valid_0's binary_logloss: 0.16697
[63]	valid_0's binary_logloss: 0.166651
[64]	valid_0's binary_logloss: 0.166554
[65]	valid_0's binary_logloss: 0.166402
[66]	valid_0's binary_logloss: 0.165932
[67]	valid_0's binary_logloss: 0.165588
[68]	valid_0's binary_logloss: 0.165783
[69]	valid_0's binary_logloss: 0.16561
[70]	valid_0's binary_logloss: 0.165225
[71]	valid_0's binary_logloss: 0.165138
[72]	valid_0's binary_logloss: 0.165482
[73]	valid_0's binary_logloss: 0.165417
[74]	valid_0's binary_logloss: 0.165456
[75]	valid_0's binary_logloss: 0.165204
[76]	valid_0's binary_logloss: 0.165261
[77]	valid_0's binary_logloss: 0.165449
[78]	valid_0's binary_logloss: 0.165499
[79]	valid_0's binary_logloss: 0.165458
[80]	valid_0's binary_logloss: 0.165979
[81]	valid_0's binary_logloss: 0.166069
[82]	valid_0's binary_logloss: 0.16618
[83]	valid_0's binary_logloss: 0.166377
[84]	valid_0's binary_logloss: 0.166033
[85]	valid_0's binary_logloss: 0.166023
[86]	valid_0's binary_logloss: 0.165579
[87]	valid_0's binary_logloss: 0.165417
[88]	valid_0's binary_logloss: 0.165426
[89]	valid_0's binary_logloss: 0.165669
[90]	valid_0's binary_logloss: 0.165342
[91]	valid_0's binary_logloss: 0.165497
[92]	valid_0's binary_logloss: 0.165674
[93]	valid_0's binary_logloss: 0.165597
[94]	valid_0's binary_logloss: 0.165621
[95]	valid_0's binary_logloss: 0.165554
[96]	valid_0's binary_logloss: 0.165639
[97]	valid_0's binary_logloss: 0.165718
[98]	valid_0's binary_logloss: 0.16579
[99]	valid_0's binary_logloss: 0.165993

Trening klas:  17%|█▋        | 87/500 [14:59<42:39,  6.20s/klasa, klasa=class_87, F1_klasy=0.5651, F1_macro=0.8494, drzewa=71]




Trening klas:  18%|█▊        | 88/500 [14:59<47:52,  6.97s/klasa, klasa=class_87, F1_klasy=0.5651, F1_macro=0.8494, drzewa=71]

[100]	valid_0's binary_logloss: 0.165839
[101]	valid_0's binary_logloss: 0.165972
[1]	valid_0's binary_logloss: 0.261476
[2]	valid_0's binary_logloss: 0.226865
[3]	valid_0's binary_logloss: 0.202897
[4]	valid_0's binary_logloss: 0.184866
[5]	valid_0's binary_logloss: 0.170227
[6]	valid_0's binary_logloss: 0.158237
[7]	valid_0's binary_logloss: 0.148163
[8]	valid_0's binary_logloss: 0.139214
[9]	valid_0's binary_logloss: 0.131612
[10]	valid_0's binary_logloss: 0.124624
[11]	valid_0's binary_logloss: 0.118555
[12]	valid_0's binary_logloss: 0.11311
[13]	valid_0's binary_logloss: 0.10797
[14]	valid_0's binary_logloss: 0.103613
[15]	valid_0's binary_logloss: 0.0993092
[16]	valid_0's binary_logloss: 0.0953379
[17]	valid_0's binary_logloss: 0.0917169
[18]	valid_0's binary_logloss: 0.0885473
[19]	valid_0's binary_logloss: 0.0855989
[20]	valid_0's binary_logloss: 0.082726
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0803643
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0780873
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.0761732
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0744638
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.0727989
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.071268
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.0698838
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.0685306
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.0670291
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.0657151
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.0644798
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.0631837
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.062177
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.0613221
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.0604562
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.0597618
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.0588765
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.0582123
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.0575842
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.0571244
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.0566322
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.0561011
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.0558647
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.055522
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.0551219
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.0548572
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.0546294
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.0544879
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.0542328
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.0541513
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.0539982
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.0539146
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.0539193
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.0538997
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.0539441
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.0538858
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.0538535
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.0539418
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.0539349
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.0540033
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.0540462
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.0540245
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.0540764
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.0540786
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.0540962
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.0540986
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.054036
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.0539892
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.054082
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.0540911
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.0539228
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.0537646
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.0536476
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.0537411
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.0535887
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.0535877
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.0536302
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.0535369
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.0535366
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.0534776
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.0533322
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.0532839
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.0532438
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.0532316
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.0532235
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.053346
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.0534632
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.0534978
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.0535106
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.0536047
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.0534898
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.053496
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.053408
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.0534932
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.053548
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.0534515
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.0535255
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.0534688
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.0534341
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.0533968
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.0532589
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.0531561
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.0532282
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.0530179
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.0531429
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.0532114
[107]	valid_0's binary_logloss: 0.0530332
[108]	valid_0's binary_logloss: 0.052955
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.0530239
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.0531761
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.0531051
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 0.0530135
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 0.052959
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 0.0528808
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 0.0529581
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[116]	valid_0's binary_logloss: 0.053034
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[117]	valid_0's binary_logloss: 0.0530814
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[118]	valid_0's binary_logloss: 0.0531312
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[119]	valid_0's binary_logloss: 0.053123
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[120]	valid_0's binary_logloss: 0.0531917
[121]	valid_0's binary_logloss: 0.0530649
[122]	valid_0's binary_logloss: 0.0529905
[123]	valid_0's binary_logloss: 0.0530213
[124]	valid_0's binary_logloss: 0.0530935
[125]	valid_0's binary_logloss: 0.0530875
[126]	valid_0's binary_logloss: 0.0530629
[127]	valid_0's binary_logloss: 0.0531256
[128]	valid_0's binary_logloss: 0.0531742
[129]	valid_0's binary_logloss: 0.0532364
[130]	valid_0's binary_logloss: 0.0532116
[131]	valid_0's binary_logloss: 0.0531973
[132]	valid_0's binary_logloss: 0.053213
[133]	valid_0's binary_logloss: 0.0532576
[134]	valid_0's binary_logloss: 0.0533774
[135]	valid_0's binary_logloss: 0.0533349
[136]	valid_0's binary_logloss: 0.053382
[137]	valid_0's binary_logloss: 0.0532741
[138]	valid_0's binary_logloss: 0.0533583
[139]	valid_0's binary_logloss: 0.0535706
[140]	valid_0's binary_logloss: 0.0536532
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[141]	valid_0's binary_logloss: 0.0539323
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

Trening klas:  18%|█▊        | 88/500 [15:06<47:52,  6.97s/klasa, klasa=class_88, F1_klasy=0.9266, F1_macro=0.8503, drzewa=114]




Trening klas:  18%|█▊        | 89/500 [15:06<47:27,  6.93s/klasa, klasa=class_88, F1_klasy=0.9266, F1_macro=0.8503, drzewa=114]

[142]	valid_0's binary_logloss: 0.0541392
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[143]	valid_0's binary_logloss: 0.0542688
[144]	valid_0's binary_logloss: 0.0544211
[1]	valid_0's binary_logloss: 0.277164
[2]	valid_0's binary_logloss: 0.256436
[3]	valid_0's binary_logloss: 0.242685
[4]	valid_0's binary_logloss: 0.232105
[5]	valid_0's binary_logloss: 0.22478
[6]	valid_0's binary_logloss: 0.21769
[7]	valid_0's binary_logloss: 0.21077
[8]	valid_0's binary_logloss: 0.206455
[9]	valid_0's binary_logloss: 0.201066
[10]	valid_0's binary_logloss: 0.196735
[11]	valid_0's binary_logloss: 0.192708
[12]	valid_0's binary_logloss: 0.189262
[13]	valid_0's binary_logloss: 0.186579
[14]	valid_0's binary_logloss: 0.18406
[15]	valid_0's binary_logloss: 0.181755
[16]	valid_0's binary_logloss: 0.180128
[17]	valid_0's binary_logloss: 0.178262
[18]	valid_0's binary_logloss: 0.17683
[19]	valid_0's binary_logloss: 0.175
[20]	valid_0's binary_logloss: 0.173071
[21]	valid_0's binary_logloss: 0.171643
[22]	valid_0's binary_logloss: 0.170292
[23]	valid_0's binary_logloss: 0.16945
[24]	valid_0's binary_logloss: 0.168164
[25]	valid_0's binary_logloss: 0.167612
[26]	valid_0's binary_logloss: 0.166614
[27]	valid_0's binary_logloss: 0.166092
[28]	valid_0's binary_logloss: 0.165483
[29]	valid_0's binary_logloss: 0.164084
[30]	valid_0's binary_logloss: 0.163586
[31]	valid_0's binary_logloss: 0.163166
[32]	valid_0's binary_logloss: 0.162464
[33]	valid_0's binary_logloss: 0.162229
[34]	valid_0's binary_logloss: 0.161458
[35]	valid_0's binary_logloss: 0.161135
[36]	valid_0's binary_logloss: 0.160531
[37]	valid_0's binary_logloss: 0.160384
[38]	valid_0's binary_logloss: 0.160327
[39]	valid_0's binary_logloss: 0.159845
[40]	valid_0's binary_logloss: 0.159438
[41]	valid_0's binary_logloss: 0.159089
[42]	valid_0's binary_logloss: 0.158744
[43]	valid_0's binary_logloss: 0.158332
[44]	valid_0's binary_logloss: 0.157985
[45]	valid_0's binary_logloss: 0.157608
[46]	valid_0's binary_logloss: 0.157363
[47]	valid_0's binary_logloss: 0.15695
[48]	valid_0's binary_logloss: 0.156527
[49]	valid_0's binary_logloss: 0.156184
[50]	valid_0's binary_logloss: 0.156054
[51]	valid_0's binary_logloss: 0.156031
[52]	valid_0's binary_logloss: 0.15616
[53]	valid_0's binary_logloss: 0.156009
[54]	valid_0's binary_logloss: 0.156092
[55]	valid_0's binary_logloss: 0.156235
[56]	valid_0's binary_logloss: 0.156253
[57]	valid_0's binary_logloss: 0.155893
[58]	valid_0's binary_logloss: 0.155997
[59]	valid_0's binary_logloss: 0.155944
[60]	valid_0's binary_logloss: 0.155631
[61]	valid_0's binary_logloss: 0.155858
[62]	valid_0's binary_logloss: 0.15613
[63]	valid_0's binary_logloss: 0.156054
[64]	valid_0's binary_logloss: 0.15603
[65]	valid_0's binary_logloss: 0.156325
[66]	valid_0's binary_logloss: 0.156168
[67]	valid_0's binary_logloss: 0.155942
[68]	valid_0's binary_logloss: 0.155644
[69]	valid_0's binary_logloss: 0.155274
[70]	valid_0's binary_logloss: 0.155092
[71]	valid_0's binary_logloss: 0.154898
[72]	valid_0's binary_logloss: 0.154931
[73]	valid_0's binary_logloss: 0.155055
[74]	valid_0's binary_logloss: 0.154708
[75]	valid_0's binary_logloss: 0.154735
[76]	valid_0's binary_logloss: 0.154477
[77]	valid_0's binary_logloss: 0.154292
[78]	valid_0's binary_logloss: 0.154221
[79]	valid_0's binary_logloss: 0.15426
[80]	valid_0's binary_logloss: 0.154134
[81]	valid_0's binary_logloss: 0.154103
[82]	valid_0's binary_logloss: 0.154139
[83]	valid_0's binary_logloss: 0.154197
[84]	valid_0's binary_logloss: 0.154083
[85]	valid_0's binary_logloss: 0.15415
[86]	valid_0's binary_logloss: 0.1539
[87]	valid_0's binary_logloss: 0.153624
[88]	valid_0's binary_logloss: 0.153678
[89]	valid_0's binary_logloss: 0.153507
[90]	valid_0's binary_logloss: 0.153483
[91]	valid_0's binary_logloss: 0.153425
[92]	valid_0's binary_logloss: 0.153422
[93]	valid_0's binary_logloss: 0.153568
[94]	valid_0's binary_logloss: 0.153674
[95]	valid_0's binary_logloss: 0.153785
[96]	valid_0's binary_logloss: 0.153738
[97]	valid_0's binary_logloss: 0.153732
[98]	valid_0's binary_logloss: 0.15369
[99]	valid_0's binary_logloss: 0.153531
[100]	valid_0's binary_logloss: 0.153477
[101]	valid_0's binary_logloss: 0.153421
[102]	valid_0's binary_logloss: 0.153217
[103]	valid_0's binary_logloss: 0.153298
[104]	valid_0's binary_logloss: 0.153142
[105]	valid_0's binary_logloss: 0.15294
[106]	valid_0's binary_logloss: 0.152828
[107]	valid_0's binary_logloss: 0.152743
[108]	valid_0's binary_logloss: 0.152686
[109]	valid_0's binary_logloss: 0.152708
[110]	valid_0's binary_logloss: 0.15272
[111]	valid_0's binary_logloss: 0.152741
[112]	valid_0's binary_logloss: 0.152894
[113]	valid_0's binary_logloss: 0.153029
[114]	valid_0's binary_logloss: 0.153167
[115]	valid_0's binary_logloss: 0.153293
[116]	valid_0's binary_logloss: 0.153318
[117]	valid_0's binary_logloss: 0.153367
[118]	valid_0's binary_logloss: 0.153354
[119]	valid_0's binary_logloss: 0.153482
[120]	valid_0's binary_logloss: 0.153196
[121]	valid_0's binary_logloss: 0.15291
[122]	valid_0's binary_logloss: 0.152854
[123]	valid_0's binary_logloss: 0.153021
[124]	valid_0's binary_logloss: 0.15331
[125]	valid_0's binary_logloss: 0.153221
[126]	valid_0's binary_logloss: 0.153112
[127]	valid_0's binary_logloss: 0.152913
[128]	valid_0's binary_logloss: 0.152797
[129]	valid_0's binary_logloss: 0.152631
[130]	valid_0's binary_logloss: 0.152715
[131]	valid_0's binary_logloss: 0.152762
[132]	valid_0's binary_logloss: 0.152745
[133]	valid_0's binary_logloss: 0.152874
[134]	valid_0's binary_logloss: 0.152969
[135]	valid_0's binary_logloss: 0.153038
[136]	valid_0's binary_logloss: 0.153058
[137]	valid_0's binary_logloss: 0.153393
[138]	valid_0's binary_logloss: 0.153574
[139]	valid_0's binary_logloss: 0.153653
[140]	valid_0's binary_logloss: 0.153742
[141]	valid_0's binary_logloss: 0.153787
[142]	valid_0's binary_logloss: 0.153804
[143]	valid_0's binary_logloss: 0.153711
[144]	valid_0's binary_logloss: 0.153795
[145]	valid_0's binary_logloss: 0.153912
[146]	valid_0's binary_logloss: 0.153831
[147]	valid_0's binary_logloss: 0.153848
[148]	valid_0's binary_logloss: 0.153886
[149]	valid_0's binary_logloss: 0.153866
[150]	valid_0's binary_logloss: 0.15406
[151]	valid_0's binary_logloss: 0.154051
[152]	valid_0's binary_logloss: 0.15424
[153]	valid_0's binary_logloss: 0.154167
[154]	valid_0's binary_logloss: 0.154194
[155]	valid_0's binary_logloss: 0.154249
[156]	valid_0's binary_logloss: 0.154311
[157]	valid_0's binary_logloss: 0.15439
[158]	valid_0's binary_logloss: 0.154609
[159]	valid_0's binary_logloss: 0.154783

Trening klas:  18%|█▊        | 89/500 [15:17<47:27,  6.93s/klasa, klasa=class_89, F1_klasy=0.6587, F1_macro=0.8482, drzewa=129]




Trening klas:  18%|█▊        | 90/500 [15:17<56:20,  8.25s/klasa, klasa=class_89, F1_klasy=0.6587, F1_macro=0.8482, drzewa=129]

[1]	valid_0's binary_logloss: 0.219109
[2]	valid_0's binary_logloss: 0.194926
[3]	valid_0's binary_logloss: 0.179724
[4]	valid_0's binary_logloss: 0.167177
[5]	valid_0's binary_logloss: 0.157929
[6]	valid_0's binary_logloss: 0.149914
[7]	valid_0's binary_logloss: 0.142976
[8]	valid_0's binary_logloss: 0.137261
[9]	valid_0's binary_logloss: 0.132096
[10]	valid_0's binary_logloss: 0.127535
[11]	valid_0's binary_logloss: 0.123182
[12]	valid_0's binary_logloss: 0.119631
[13]	valid_0's binary_logloss: 0.116279
[14]	valid_0's binary_logloss: 0.113068
[15]	valid_0's binary_logloss: 0.110318
[16]	valid_0's binary_logloss: 0.108053
[17]	valid_0's binary_logloss: 0.105748
[18]	valid_0's binary_logloss: 0.103766
[19]	valid_0's binary_logloss: 0.101786
[20]	valid_0's binary_logloss: 0.0999599
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0983893
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0968659
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.0955887
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0943446
[25]	valid_0's binary_logloss: 0.093194
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.0918882
[27]	valid_0's binary_logloss: 0.0909447
[28]	valid_0's binary_logloss: 0.0900535
[29]	valid_0's binary_logloss: 0.0890408
[30]	valid_0's binary_logloss: 0.0881746
[31]	valid_0's binary_logloss: 0.0872214
[32]	valid_0's binary_logloss: 0.0863357
[33]	valid_0's binary_logloss: 0.0855042
[34]	valid_0's binary_logloss: 0.0846204
[35]	valid_0's binary_logloss: 0.083817
[36]	valid_0's binary_logloss: 0.0831955
[37]	valid_0's binary_logloss: 0.0825421
[38]	valid_0's binary_logloss: 0.08193
[39]	valid_0's binary_logloss: 0.0816363
[40]	valid_0's binary_logloss: 0.081035
[41]	valid_0's binary_logloss: 0.0807098
[42]	valid_0's binary_logloss: 0.0805384
[43]	valid_0's binary_logloss: 0.080365
[44]	valid_0's binary_logloss: 0.0800563
[45]	valid_0's binary_logloss: 0.0797794
[46]	valid_0's binary_logloss: 0.0793458
[47]	valid_0's binary_logloss: 0.0791035
[48]	valid_0's binary_logloss: 0.0789187
[49]	valid_0's binary_logloss: 0.078575
[50]	valid_0's binary_logloss: 0.0784211
[51]	valid_0's binary_logloss: 0.0783018
[52]	valid_0's binary_logloss: 0.078413
[53]	valid_0's binary_logloss: 0.0785194
[54]	valid_0's binary_logloss: 0.0783522
[55]	valid_0's binary_logloss: 0.0783795
[56]	valid_0's binary_logloss: 0.0781569
[57]	valid_0's binary_logloss: 0.0779134
[58]	valid_0's binary_logloss: 0.0779518
[59]	valid_0's binary_logloss: 0.0775777
[60]	valid_0's binary_logloss: 0.0775962
[61]	valid_0's binary_logloss: 0.0773173
[62]	valid_0's binary_logloss: 0.0773689
[63]	valid_0's binary_logloss: 0.0773595
[64]	valid_0's binary_logloss: 0.0774563
[65]	valid_0's binary_logloss: 0.077437
[66]	valid_0's binary_logloss: 0.0774002
[67]	valid_0's binary_logloss: 0.0769855
[68]	valid_0's binary_logloss: 0.0767754
[69]	valid_0's binary_logloss: 0.0764377
[70]	valid_0's binary_logloss: 0.0764053
[71]	valid_0's binary_logloss: 0.0761562
[72]	valid_0's binary_logloss: 0.0758548
[73]	valid_0's binary_logloss: 0.0757111
[74]	valid_0's binary_logloss: 0.0756533
[75]	valid_0's binary_logloss: 0.0756058
[76]	valid_0's binary_logloss: 0.0756408
[77]	valid_0's binary_logloss: 0.0755336
[78]	valid_0's binary_logloss: 0.0753512
[79]	valid_0's binary_logloss: 0.0751783
[80]	valid_0's binary_logloss: 0.0749903
[81]	valid_0's binary_logloss: 0.074842
[82]	valid_0's binary_logloss: 0.075012
[83]	valid_0's binary_logloss: 0.0748353
[84]	valid_0's binary_logloss: 0.0748466
[85]	valid_0's binary_logloss: 0.0747785
[86]	valid_0's binary_logloss: 0.0747628
[87]	valid_0's binary_logloss: 0.0747625
[88]	valid_0's binary_logloss: 0.0747219
[89]	valid_0's binary_logloss: 0.0745972
[90]	valid_0's binary_logloss: 0.0746541
[91]	valid_0's binary_logloss: 0.0747444
[92]	valid_0's binary_logloss: 0.0746923
[93]	valid_0's binary_logloss: 0.0746714
[94]	valid_0's binary_logloss: 0.0748005
[95]	valid_0's binary_logloss: 0.0748894
[96]	valid_0's binary_logloss: 0.0748406
[97]	valid_0's binary_logloss: 0.0746325
[98]	valid_0's binary_logloss: 0.0745488
[99]	valid_0's binary_logloss: 0.0745963
[100]	valid_0's binary_logloss: 0.0746198
[101]	valid_0's binary_logloss: 0.074627
[102]	valid_0's binary_logloss: 0.0746334
[103]	valid_0's binary_logloss: 0.0748457
[104]	valid_0's binary_logloss: 0.0749166
[105]	valid_0's binary_logloss: 0.0749129
[106]	valid_0's binary_logloss: 0.075074
[107]	valid_0's binary_logloss: 0.0752245
[108]	valid_0's binary_logloss: 0.0753887
[109]	valid_0's binary_logloss: 0.0755637
[110]	valid_0's binary_logloss: 0.0756856
[111]	valid_0's binary_logloss: 0.0756909
[112]	valid_0's binary_logloss: 0.0757657
[113]	valid_0's binary_logloss: 0.0758802
[114]	valid_0's binary_logloss: 0.0759065
[115]	valid_0's binary_logloss: 0.0761393
[116]	valid_0's binary_logloss: 0.0762051
[117]	valid_0's binary_logloss: 0.0763711
[118]	valid_0's binary_logloss: 0.0767189
[119]	valid_0's binary_logloss: 0.0767902
[120]	valid_0's binary_logloss: 0.0769293
[121]	valid_0's binary_logloss: 0.0770414
[122]	valid_0's binary_logloss: 0.0770819
[123]	valid_0's binary_logloss: 0.0772214
[124]	valid_0's binary_logloss: 0.0771955
[125]	valid_0's binary_logloss: 0.0774676
[126]	valid_0's binary_logloss: 0.0777449

Trening klas:  18%|█▊        | 90/500 [15:25<56:20,  8.25s/klasa, klasa=class_90, F1_klasy=0.8140, F1_macro=0.8478, drzewa=98]




Trening klas:  18%|█▊        | 91/500 [15:25<54:48,  8.04s/klasa, klasa=class_90, F1_klasy=0.8140, F1_macro=0.8478, drzewa=98]

[127]	valid_0's binary_logloss: 0.0777228
[128]	valid_0's binary_logloss: 0.077831
[1]	valid_0's binary_logloss: 0.220147
[2]	valid_0's binary_logloss: 0.194736
[3]	valid_0's binary_logloss: 0.178107
[4]	valid_0's binary_logloss: 0.164977
[5]	valid_0's binary_logloss: 0.154876
[6]	valid_0's binary_logloss: 0.14594
[7]	valid_0's binary_logloss: 0.137955
[8]	valid_0's binary_logloss: 0.13133
[9]	valid_0's binary_logloss: 0.125504
[10]	valid_0's binary_logloss: 0.120285
[11]	valid_0's binary_logloss: 0.116151
[12]	valid_0's binary_logloss: 0.11243
[13]	valid_0's binary_logloss: 0.108667
[14]	valid_0's binary_logloss: 0.105346
[15]	valid_0's binary_logloss: 0.102215
[16]	valid_0's binary_logloss: 0.0993103
[17]	valid_0's binary_logloss: 0.0969821
[18]	valid_0's binary_logloss: 0.0945818
[19]	valid_0's binary_logloss: 0.0923102
[20]	valid_0's binary_logloss: 0.0904919
[21]	valid_0's binary_logloss: 0.0888344
[22]	valid_0's binary_logloss: 0.0870319
[23]	valid_0's binary_logloss: 0.0853082
[24]	valid_0's binary_logloss: 0.0837168
[25]	valid_0's binary_logloss: 0.0823259
[26]	valid_0's binary_logloss: 0.0809344
[27]	valid_0's binary_logloss: 0.0796136
[28]	valid_0's binary_logloss: 0.0784563
[29]	valid_0's binary_logloss: 0.077376
[30]	valid_0's binary_logloss: 0.0762369
[31]	valid_0's binary_logloss: 0.0752839
[32]	valid_0's binary_logloss: 0.0742244
[33]	valid_0's binary_logloss: 0.0733538
[34]	valid_0's binary_logloss: 0.0726015
[35]	valid_0's binary_logloss: 0.0716333
[36]	valid_0's binary_logloss: 0.0708233
[37]	valid_0's binary_logloss: 0.0700768
[38]	valid_0's binary_logloss: 0.0691923
[39]	valid_0's binary_logloss: 0.0686983
[40]	valid_0's binary_logloss: 0.0680387
[41]	valid_0's binary_logloss: 0.0675147
[42]	valid_0's binary_logloss: 0.0671103
[43]	valid_0's binary_logloss: 0.0667311
[44]	valid_0's binary_logloss: 0.0663077
[45]	valid_0's binary_logloss: 0.0656532
[46]	valid_0's binary_logloss: 0.0653444
[47]	valid_0's binary_logloss: 0.0650601
[48]	valid_0's binary_logloss: 0.0646083
[49]	valid_0's binary_logloss: 0.064532
[50]	valid_0's binary_logloss: 0.0644256
[51]	valid_0's binary_logloss: 0.0640745
[52]	valid_0's binary_logloss: 0.0638987
[53]	valid_0's binary_logloss: 0.0633596
[54]	valid_0's binary_logloss: 0.0632947
[55]	valid_0's binary_logloss: 0.0629882
[56]	valid_0's binary_logloss: 0.062878
[57]	valid_0's binary_logloss: 0.0627016
[58]	valid_0's binary_logloss: 0.0626854
[59]	valid_0's binary_logloss: 0.0624812
[60]	valid_0's binary_logloss: 0.0623541
[61]	valid_0's binary_logloss: 0.0622961
[62]	valid_0's binary_logloss: 0.0622105
[63]	valid_0's binary_logloss: 0.0620209
[64]	valid_0's binary_logloss: 0.061987
[65]	valid_0's binary_logloss: 0.0619853
[66]	valid_0's binary_logloss: 0.0621306
[67]	valid_0's binary_logloss: 0.0623248
[68]	valid_0's binary_logloss: 0.0625068
[69]	valid_0's binary_logloss: 0.0624365
[70]	valid_0's binary_logloss: 0.0625138
[71]	valid_0's binary_logloss: 0.0621515
[72]	valid_0's binary_logloss: 0.0618886
[73]	valid_0's binary_logloss: 0.0616467
[74]	valid_0's binary_logloss: 0.0614356
[75]	valid_0's binary_logloss: 0.0615454
[76]	valid_0's binary_logloss: 0.0614935
[77]	valid_0's binary_logloss: 0.0616294
[78]	valid_0's binary_logloss: 0.0617593
[79]	valid_0's binary_logloss: 0.061709
[80]	valid_0's binary_logloss: 0.0615362
[81]	valid_0's binary_logloss: 0.0614506
[82]	valid_0's binary_logloss: 0.0614494
[83]	valid_0's binary_logloss: 0.0616084
[84]	valid_0's binary_logloss: 0.0616915
[85]	valid_0's binary_logloss: 0.06183
[86]	valid_0's binary_logloss: 0.0618638
[87]	valid_0's binary_logloss: 0.0617437
[88]	valid_0's binary_logloss: 0.0617628
[89]	valid_0's binary_logloss: 0.0616253
[90]	valid_0's binary_logloss: 0.0615656
[91]	valid_0's binary_logloss: 0.0617574
[92]	valid_0's binary_logloss: 0.0618305
[93]	valid_0's binary_logloss: 0.0621476
[94]	valid_0's binary_logloss: 0.0623955
[95]	valid_0's binary_logloss: 0.06274
[96]	valid_0's binary_logloss: 0.0628653
[97]	valid_0's binary_logloss: 0.0628008
[98]	valid_0's binary_logloss: 0.0628216
[99]	valid_0's binary_logloss: 0.0627174
[100]	valid_0's binary_logloss: 0.0627674
[101]	valid_0's binary_logloss: 0.0627997
[102]	valid_0's binary_logloss: 0.0628882
[103]	valid_0's binary_logloss: 0.0628724
[104]	valid_0's binary_logloss: 0.0630269

Trening klas:  18%|█▊        | 91/500 [15:31<54:48,  8.04s/klasa, klasa=class_91, F1_klasy=0.8695, F1_macro=0.8480, drzewa=74]




Trening klas:  18%|█▊        | 92/500 [15:31<51:37,  7.59s/klasa, klasa=class_91, F1_klasy=0.8695, F1_macro=0.8480, drzewa=74]

[1]	valid_0's binary_logloss: 0.25194
[2]	valid_0's binary_logloss: 0.224641
[3]	valid_0's binary_logloss: 0.205947
[4]	valid_0's binary_logloss: 0.192571
[5]	valid_0's binary_logloss: 0.181315
[6]	valid_0's binary_logloss: 0.1727
[7]	valid_0's binary_logloss: 0.164904
[8]	valid_0's binary_logloss: 0.158326
[9]	valid_0's binary_logloss: 0.15222
[10]	valid_0's binary_logloss: 0.147172
[11]	valid_0's binary_logloss: 0.142124
[12]	valid_0's binary_logloss: 0.137469
[13]	valid_0's binary_logloss: 0.133323
[14]	valid_0's binary_logloss: 0.129426
[15]	valid_0's binary_logloss: 0.125508
[16]	valid_0's binary_logloss: 0.122368
[17]	valid_0's binary_logloss: 0.119473
[18]	valid_0's binary_logloss: 0.116808
[19]	valid_0's binary_logloss: 0.114565
[20]	valid_0's binary_logloss: 0.112497
[21]	valid_0's binary_logloss: 0.110347
[22]	valid_0's binary_logloss: 0.108392
[23]	valid_0's binary_logloss: 0.106569
[24]	valid_0's binary_logloss: 0.104785
[25]	valid_0's binary_logloss: 0.103325
[26]	valid_0's binary_logloss: 0.101844
[27]	valid_0's binary_logloss: 0.100308
[28]	valid_0's binary_logloss: 0.099036
[29]	valid_0's binary_logloss: 0.0978317
[30]	valid_0's binary_logloss: 0.0967373
[31]	valid_0's binary_logloss: 0.0956492
[32]	valid_0's binary_logloss: 0.0947704
[33]	valid_0's binary_logloss: 0.093699
[34]	valid_0's binary_logloss: 0.0927109
[35]	valid_0's binary_logloss: 0.0920362
[36]	valid_0's binary_logloss: 0.0914698
[37]	valid_0's binary_logloss: 0.0908023
[38]	valid_0's binary_logloss: 0.0900366
[39]	valid_0's binary_logloss: 0.0892626
[40]	valid_0's binary_logloss: 0.0885746
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.0880381
[42]	valid_0's binary_logloss: 0.0875962
[43]	valid_0's binary_logloss: 0.0870715
[44]	valid_0's binary_logloss: 0.0864611
[45]	valid_0's binary_logloss: 0.0860418
[46]	valid_0's binary_logloss: 0.0856387
[47]	valid_0's binary_logloss: 0.0853682
[48]	valid_0's binary_logloss: 0.084959
[49]	valid_0's binary_logloss: 0.0846407
[50]	valid_0's binary_logloss: 0.0841322
[51]	valid_0's binary_logloss: 0.0838454
[52]	valid_0's binary_logloss: 0.0837479
[53]	valid_0's binary_logloss: 0.0835559
[54]	valid_0's binary_logloss: 0.0833063
[55]	valid_0's binary_logloss: 0.0831923
[56]	valid_0's binary_logloss: 0.0831927
[57]	valid_0's binary_logloss: 0.0832153
[58]	valid_0's binary_logloss: 0.0833501
[59]	valid_0's binary_logloss: 0.0834612
[60]	valid_0's binary_logloss: 0.083246
[61]	valid_0's binary_logloss: 0.0829417
[62]	valid_0's binary_logloss: 0.0828141
[63]	valid_0's binary_logloss: 0.0828367
[64]	valid_0's binary_logloss: 0.0829442
[65]	valid_0's binary_logloss: 0.082874
[66]	valid_0's binary_logloss: 0.082786
[67]	valid_0's binary_logloss: 0.0828148
[68]	valid_0's binary_logloss: 0.0829568
[69]	valid_0's binary_logloss: 0.0829301
[70]	valid_0's binary_logloss: 0.0829476
[71]	valid_0's binary_logloss: 0.0831375
[72]	valid_0's binary_logloss: 0.0831427
[73]	valid_0's binary_logloss: 0.0833939
[74]	valid_0's binary_logloss: 0.0834035
[75]	valid_0's binary_logloss: 0.0834212
[76]	valid_0's binary_logloss: 0.0836116
[77]	valid_0's binary_logloss: 0.0835531
[78]	valid_0's binary_logloss: 0.0838449
[79]	valid_0's binary_logloss: 0.0840191
[80]	valid_0's binary_logloss: 0.0842273
[81]	valid_0's binary_logloss: 0.084425
[82]	valid_0's binary_logloss: 0.0844462
[83]	valid_0's binary_logloss: 0.0845611
[84]	valid_0's binary_logloss: 0.0846343
[85]	valid_0's binary_logloss: 0.0846536
[86]	valid_0's binary_logloss: 0.0848312
[87]	valid_0's binary_logloss: 0.0850512
[88]	valid_0's binary_logloss: 0.0852448
[89]	valid_0's binary_logloss: 0.0855228
[90]	valid_0's binary_logloss: 0.0857244
[91]	valid_0's binary_logloss: 0.0859125
[92]	valid_0's binary_logloss: 0.0858979
[93]	valid_0's binary_logloss: 0.0859096

Trening klas:  18%|█▊        | 92/500 [15:38<51:37,  7.59s/klasa, klasa=class_92, F1_klasy=0.8571, F1_macro=0.8481, drzewa=66]




Trening klas:  19%|█▊        | 93/500 [15:38<48:45,  7.19s/klasa, klasa=class_92, F1_klasy=0.8571, F1_macro=0.8481, drzewa=66]

[94]	valid_0's binary_logloss: 0.0859769
[95]	valid_0's binary_logloss: 0.0861169
[96]	valid_0's binary_logloss: 0.086267
[1]	valid_0's binary_logloss: 0.202474
[2]	valid_0's binary_logloss: 0.183745
[3]	valid_0's binary_logloss: 0.171744
[4]	valid_0's binary_logloss: 0.162245
[5]	valid_0's binary_logloss: 0.155128
[6]	valid_0's binary_logloss: 0.149695
[7]	valid_0's binary_logloss: 0.144841
[8]	valid_0's binary_logloss: 0.140511
[9]	valid_0's binary_logloss: 0.137436
[10]	valid_0's binary_logloss: 0.134412
[11]	valid_0's binary_logloss: 0.131836
[12]	valid_0's binary_logloss: 0.129936
[13]	valid_0's binary_logloss: 0.127565
[14]	valid_0's binary_logloss: 0.125662
[15]	valid_0's binary_logloss: 0.123594
[16]	valid_0's binary_logloss: 0.122138
[17]	valid_0's binary_logloss: 0.120317
[18]	valid_0's binary_logloss: 0.119197
[19]	valid_0's binary_logloss: 0.117976
[20]	valid_0's binary_logloss: 0.116765
[21]	valid_0's binary_logloss: 0.11515
[22]	valid_0's binary_logloss: 0.113504
[23]	valid_0's binary_logloss: 0.112341
[24]	valid_0's binary_logloss: 0.111562
[25]	valid_0's binary_logloss: 0.110477
[26]	valid_0's binary_logloss: 0.109652
[27]	valid_0's binary_logloss: 0.109031
[28]	valid_0's binary_logloss: 0.108016
[29]	valid_0's binary_logloss: 0.107779
[30]	valid_0's binary_logloss: 0.107071
[31]	valid_0's binary_logloss: 0.106303
[32]	valid_0's binary_logloss: 0.105402
[33]	valid_0's binary_logloss: 0.104944
[34]	valid_0's binary_logloss: 0.104528
[35]	valid_0's binary_logloss: 0.104276
[36]	valid_0's binary_logloss: 0.10375
[37]	valid_0's binary_logloss: 0.103311
[38]	valid_0's binary_logloss: 0.103082
[39]	valid_0's binary_logloss: 0.10275
[40]	valid_0's binary_logloss: 0.10237
[41]	valid_0's binary_logloss: 0.102045
[42]	valid_0's binary_logloss: 0.101905
[43]	valid_0's binary_logloss: 0.101829
[44]	valid_0's binary_logloss: 0.101583
[45]	valid_0's binary_logloss: 0.101423
[46]	valid_0's binary_logloss: 0.100913
[47]	valid_0's binary_logloss: 0.100683
[48]	valid_0's binary_logloss: 0.100671
[49]	valid_0's binary_logloss: 0.100581
[50]	valid_0's binary_logloss: 0.100585
[51]	valid_0's binary_logloss: 0.100224
[52]	valid_0's binary_logloss: 0.100004
[53]	valid_0's binary_logloss: 0.0996155
[54]	valid_0's binary_logloss: 0.0991144
[55]	valid_0's binary_logloss: 0.0988274
[56]	valid_0's binary_logloss: 0.0988276
[57]	valid_0's binary_logloss: 0.0987165
[58]	valid_0's binary_logloss: 0.098707
[59]	valid_0's binary_logloss: 0.0985213
[60]	valid_0's binary_logloss: 0.0984822
[61]	valid_0's binary_logloss: 0.0982006
[62]	valid_0's binary_logloss: 0.0979386
[63]	valid_0's binary_logloss: 0.0976741
[64]	valid_0's binary_logloss: 0.0974674
[65]	valid_0's binary_logloss: 0.0972348
[66]	valid_0's binary_logloss: 0.0971154
[67]	valid_0's binary_logloss: 0.0973145
[68]	valid_0's binary_logloss: 0.096947
[69]	valid_0's binary_logloss: 0.0971063
[70]	valid_0's binary_logloss: 0.0970379
[71]	valid_0's binary_logloss: 0.0967997
[72]	valid_0's binary_logloss: 0.0967486
[73]	valid_0's binary_logloss: 0.0965855
[74]	valid_0's binary_logloss: 0.0963048
[75]	valid_0's binary_logloss: 0.0960806
[76]	valid_0's binary_logloss: 0.0957287
[77]	valid_0's binary_logloss: 0.094951
[78]	valid_0's binary_logloss: 0.094708
[79]	valid_0's binary_logloss: 0.0944678
[80]	valid_0's binary_logloss: 0.0938615
[81]	valid_0's binary_logloss: 0.0942274
[82]	valid_0's binary_logloss: 0.0942451
[83]	valid_0's binary_logloss: 0.0941975
[84]	valid_0's binary_logloss: 0.0942573
[85]	valid_0's binary_logloss: 0.0941946
[86]	valid_0's binary_logloss: 0.0938812
[87]	valid_0's binary_logloss: 0.0937254
[88]	valid_0's binary_logloss: 0.0935891
[89]	valid_0's binary_logloss: 0.0935252
[90]	valid_0's binary_logloss: 0.093254
[91]	valid_0's binary_logloss: 0.0931218
[92]	valid_0's binary_logloss: 0.0927842
[93]	valid_0's binary_logloss: 0.0927655
[94]	valid_0's binary_logloss: 0.0927685
[95]	valid_0's binary_logloss: 0.0925301
[96]	valid_0's binary_logloss: 0.092411
[97]	valid_0's binary_logloss: 0.092239
[98]	valid_0's binary_logloss: 0.0921941
[99]	valid_0's binary_logloss: 0.0923587
[100]	valid_0's binary_logloss: 0.0923031
[101]	valid_0's binary_logloss: 0.0923171
[102]	valid_0's binary_logloss: 0.0922078
[103]	valid_0's binary_logloss: 0.0922743
[104]	valid_0's binary_logloss: 0.0923176
[105]	valid_0's binary_logloss: 0.0923814
[106]	valid_0's binary_logloss: 0.0925737
[107]	valid_0's binary_logloss: 0.0925404
[108]	valid_0's binary_logloss: 0.0925794
[109]	valid_0's binary_logloss: 0.0924095
[110]	valid_0's binary_logloss: 0.0923837
[111]	valid_0's binary_logloss: 0.0923452
[112]	valid_0's binary_logloss: 0.0922093
[113]	valid_0's binary_logloss: 0.0921691
[114]	valid_0's binary_logloss: 0.0921528
[115]	valid_0's binary_logloss: 0.0921109
[116]	valid_0's binary_logloss: 0.0921955
[117]	valid_0's binary_logloss: 0.0920546
[118]	valid_0's binary_logloss: 0.0922367
[119]	valid_0's binary_logloss: 0.0921396
[120]	valid_0's binary_logloss: 0.0921033
[121]	valid_0's binary_logloss: 0.0920959
[122]	valid_0's binary_logloss: 0.0923857
[123]	valid_0's binary_logloss: 0.0923309
[124]	valid_0's binary_logloss: 0.0926688
[125]	valid_0's binary_logloss: 0.0927149
[126]	valid_0's binary_logloss: 0.0930816
[127]	valid_0's binary_logloss: 0.0933932
[128]	valid_0's binary_logloss: 0.0936767
[129]	valid_0's binary_logloss: 0.0940439
[130]	valid_0's binary_logloss: 0.0943456
[131]	valid_0's binary_logloss: 0.0943726
[132]	valid_0's binary_logloss: 0.0943538
[133]	valid_0's binary_logloss: 0.0946669
[134]	valid_0's binary_logloss: 0.0947311
[135]	valid_0's binary_logloss: 0.0949952
[136]	valid_0's binary_logloss: 0.0947895
[137]	valid_0's binary_logloss: 0.0949142
[138]	valid_0's binary_logloss: 0.0950723
[139]	valid_0's binary_logloss: 0.0952669
[140]	valid_0's binary_logloss: 0.0954356
[141]	valid_0's binary_logloss: 0.0953852
[142]	valid_0's binary_logloss: 0.0953824
[143]	valid_0's binary_logloss: 0.095411
[144]	valid_0's binary_logloss: 0.0953034
[145]	valid_0's binary_logloss: 0.0953029
[146]	valid_0's binary_logloss: 0.095228

Trening klas:  19%|█▊        | 93/500 [15:48<48:45,  7.19s/klasa, klasa=class_93, F1_klasy=0.7988, F1_macro=0.8476, drzewa=117]




Trening klas:  19%|█▉        | 94/500 [15:48<55:14,  8.16s/klasa, klasa=class_93, F1_klasy=0.7988, F1_macro=0.8476, drzewa=117]

[147]	valid_0's binary_logloss: 0.095159
[1]	valid_0's binary_logloss: 0.0917345
[2]	valid_0's binary_logloss: 0.0830894
[3]	valid_0's binary_logloss: 0.0767202
[4]	valid_0's binary_logloss: 0.0714243
[5]	valid_0's binary_logloss: 0.0668698
[6]	valid_0's binary_logloss: 0.0628527
[7]	valid_0's binary_logloss: 0.059331
[8]	valid_0's binary_logloss: 0.056117
[9]	valid_0's binary_logloss: 0.0531282
[10]	valid_0's binary_logloss: 0.0504468
[11]	valid_0's binary_logloss: 0.0478396
[12]	valid_0's binary_logloss: 0.0454171
[13]	valid_0's binary_logloss: 0.0431455
[14]	valid_0's binary_logloss: 0.0410258
[15]	valid_0's binary_logloss: 0.0390783
[16]	valid_0's binary_logloss: 0.0371318
[17]	valid_0's binary_logloss: 0.0354406
[18]	valid_0's binary_logloss: 0.0338553
[19]	valid_0's binary_logloss: 0.0323389
[20]	valid_0's binary_logloss: 0.0309295
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0294554
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0280928
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.0267911
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0255736
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.0243847
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.02324
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.0222083
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.0212057
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.0203655
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.0194938
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.0186364
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.0178539
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.0170874
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.0163739
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.015757
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.0151752
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.0145828
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.0140326
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.0134887
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.013002
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.0125476
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.0120386
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.0115705
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.0111197
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.0106784
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.0102988
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.00994323
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.00956975
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.00925419
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.00891567
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.00858932
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.00827699
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.00798072
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.00770097
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.00743313
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.00718881
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.0069503
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.0067205
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.00650357
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.00630148
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.00611853
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.00595318
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.00579733
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.00562521
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.00546015
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.00534071
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.00522367
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.00512035
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.00503883
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.0049458
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.00481495
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.00470023
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.00459095
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.00447117
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.00437108
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.00427663
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.00419583
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.00408934
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.00401969
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.00393521
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.00385488
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.00379803
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.003751
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.00368944
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.0036327
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.00358483
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.00353134
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.00349492
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.00344861
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.00340491
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.00336804
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.00333319
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.00329934
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.00327291
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.00324539
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.00322327
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.00320635
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.00319447
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.00317633
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.00316637
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.00313064
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.00308637
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.00305251
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.00301334
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.00296974
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.00296918
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.00295687
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.00296437
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.00295984
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.00294755
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.0029343
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 0.00292259
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 0.00293379
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 0.00290985
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 0.0028921
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[116]	valid_0's binary_logloss: 0.00288707
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[117]	valid_0's binary_logloss: 0.00289495
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[118]	valid_0's binary_logloss: 0.00288082
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[119]	valid_0's binary_logloss: 0.00286451
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[120]	valid_0's binary_logloss: 0.00284212
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[121]	valid_0's binary_logloss: 0.00281856
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[122]	valid_0's binary_logloss: 0.00281248
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[123]	valid_0's binary_logloss: 0.00281455
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[124]	valid_0's binary_logloss: 0.00279697
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[125]	valid_0's binary_logloss: 0.00278523
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[126]	valid_0's binary_logloss: 0.0027827
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[127]	valid_0's binary_logloss: 0.0028079
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[128]	valid_0's binary_logloss: 0.00280916
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[129]	valid_0's binary_logloss: 0.00281335
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[130]	valid_0's binary_logloss: 0.00280598
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[131]	valid_0's binary_logloss: 0.00279093
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[132]	valid_0's binary_logloss: 0.0027981
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[133]	valid_0's binary_logloss: 0.00280443
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[134]	valid_0's binary_logloss: 0.00280849
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[135]	valid_0's binary_logloss: 0.00280952
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[136]	valid_0's binary_logloss: 0.00282889
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[137]	valid_0's binary_logloss: 0.00283504
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[138]	valid_0's binary_logloss: 0.00283819
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[139]	valid_0's binary_logloss: 0.00284924
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[140]	valid_0's binary_logloss: 0.00285251
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[141]	valid_0's binary_logloss: 0.00285458
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[142]	valid_0's binary_logloss: 0.00284592
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[143]	valid_0's binary_logloss: 0.00285337
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[144]	valid_0's binary_logloss: 0.00287805
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[145]	valid_0's binary_logloss: 0.00289117
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[146]	valid_0's binary_logloss: 0.00289729
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[147]	valid_0's binary_logloss: 0.0028998
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[148]	valid_0's binary_logloss: 0.0029057
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[149]	valid_0's binary_logloss: 0.00290734
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[150]	valid_0's binary_logloss: 0.00291509
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[151]	valid_0's binary_logloss: 0.00292087
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[152]	valid_0's binary_logloss: 0.00293149
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

Trening klas:  19%|█▉        | 94/500 [15:53<55:14,  8.16s/klasa, klasa=class_94, F1_klasy=0.9836, F1_macro=0.8490, drzewa=126]




Trening klas:  19%|█▉        | 95/500 [15:53<48:53,  7.24s/klasa, klasa=class_94, F1_klasy=0.9836, F1_macro=0.8490, drzewa=126]

[153]	valid_0's binary_logloss: 0.00293064
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[154]	valid_0's binary_logloss: 0.0029378
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[155]	valid_0's binary_logloss: 0.00294282
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[156]	valid_0's binary_logloss: 0.00295727
[1]	valid_0's binary_logloss: 0.0778911
[2]	valid_0's binary_logloss: 0.0727242
[3]	valid_0's binary_logloss: 0.068512
[4]	valid_0's binary_logloss: 0.0647847
[5]	valid_0's binary_logloss: 0.0614452
[6]	valid_0's binary_logloss: 0.0589471
[7]	valid_0's binary_logloss: 0.0564893
[8]	valid_0's binary_logloss: 0.0541706
[9]	valid_0's binary_logloss: 0.0519921
[10]	valid_0's binary_logloss: 0.0499242
[11]	valid_0's binary_logloss: 0.0480401
[12]	valid_0's binary_logloss: 0.0461527
[13]	valid_0's binary_logloss: 0.0443041
[14]	valid_0's binary_logloss: 0.0426242
[15]	valid_0's binary_logloss: 0.0410625
[16]	valid_0's binary_logloss: 0.0396801
[17]	valid_0's binary_logloss: 0.0382685
[18]	valid_0's binary_logloss: 0.0371089
[19]	valid_0's binary_logloss: 0.0359199
[20]	valid_0's binary_logloss: 0.0347251
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0336638
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.032659
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.031713
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0308496
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.0298824
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.0290769
[27]	valid_0's binary_logloss: 0.0283475
[28]	valid_0's binary_logloss: 0.0276266
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.0269276
[30]	valid_0's binary_logloss: 0.0262557
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.0256078
[32]	valid_0's binary_logloss: 0.0249943
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.0244212
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.0238922
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.0233611
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.0228249
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.0223328
[38]	valid_0's binary_logloss: 0.021909
[39]	valid_0's binary_logloss: 0.0215095
[40]	valid_0's binary_logloss: 0.0211397
[41]	valid_0's binary_logloss: 0.0207463
[42]	valid_0's binary_logloss: 0.0203896
[43]	valid_0's binary_logloss: 0.0200069
[44]	valid_0's binary_logloss: 0.0196288
[45]	valid_0's binary_logloss: 0.0193423
[46]	valid_0's binary_logloss: 0.0190338
[47]	valid_0's binary_logloss: 0.0188268
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.0185927
[49]	valid_0's binary_logloss: 0.0184189
[50]	valid_0's binary_logloss: 0.0182194
[51]	valid_0's binary_logloss: 0.0179241
[52]	valid_0's binary_logloss: 0.0177047
[53]	valid_0's binary_logloss: 0.0175577
[54]	valid_0's binary_logloss: 0.0173385
[55]	valid_0's binary_logloss: 0.0171948
[56]	valid_0's binary_logloss: 0.017024
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.0169141
[58]	valid_0's binary_logloss: 0.0168085
[59]	valid_0's binary_logloss: 0.0166641
[60]	valid_0's binary_logloss: 0.0164255
[61]	valid_0's binary_logloss: 0.0162758
[62]	valid_0's binary_logloss: 0.0161745
[63]	valid_0's binary_logloss: 0.016111
[64]	valid_0's binary_logloss: 0.0160371
[65]	valid_0's binary_logloss: 0.0158708
[66]	valid_0's binary_logloss: 0.0157813
[67]	valid_0's binary_logloss: 0.0156805
[68]	valid_0's binary_logloss: 0.0156286
[69]	valid_0's binary_logloss: 0.0155763
[70]	valid_0's binary_logloss: 0.0154581
[71]	valid_0's binary_logloss: 0.01533
[72]	valid_0's binary_logloss: 0.0152527
[73]	valid_0's binary_logloss: 0.0150872
[74]	valid_0's binary_logloss: 0.0149867
[75]	valid_0's binary_logloss: 0.0148595
[76]	valid_0's binary_logloss: 0.0147906
[77]	valid_0's binary_logloss: 0.0147725
[78]	valid_0's binary_logloss: 0.0147118
[79]	valid_0's binary_logloss: 0.0146468
[80]	valid_0's binary_logloss: 0.014521
[81]	valid_0's binary_logloss: 0.0144499
[82]	valid_0's binary_logloss: 0.0143449
[83]	valid_0's binary_logloss: 0.0142701
[84]	valid_0's binary_logloss: 0.0141742
[85]	valid_0's binary_logloss: 0.0141249
[86]	valid_0's binary_logloss: 0.0140784
[87]	valid_0's binary_logloss: 0.0139794
[88]	valid_0's binary_logloss: 0.0139858
[89]	valid_0's binary_logloss: 0.0140013
[90]	valid_0's binary_logloss: 0.01396
[91]	valid_0's binary_logloss: 0.0139192
[92]	valid_0's binary_logloss: 0.0138944
[93]	valid_0's binary_logloss: 0.0138927
[94]	valid_0's binary_logloss: 0.0139848
[95]	valid_0's binary_logloss: 0.0139948
[96]	valid_0's binary_logloss: 0.0140002
[97]	valid_0's binary_logloss: 0.0139646
[98]	valid_0's binary_logloss: 0.0139878
[99]	valid_0's binary_logloss: 0.0139784
[100]	valid_0's binary_logloss: 0.0139393
[101]	valid_0's binary_logloss: 0.0139376
[102]	valid_0's binary_logloss: 0.0139497
[103]	valid_0's binary_logloss: 0.0139139
[104]	valid_0's binary_logloss: 0.0138711
[105]	valid_0's binary_logloss: 0.0138398
[106]	valid_0's binary_logloss: 0.0138324
[107]	valid_0's binary_logloss: 0.0138433
[108]	valid_0's binary_logloss: 0.0138248
[109]	valid_0's binary_logloss: 0.0139005
[110]	valid_0's binary_logloss: 0.0139211
[111]	valid_0's binary_logloss: 0.0138859
[112]	valid_0's binary_logloss: 0.0138352
[113]	valid_0's binary_logloss: 0.0138284
[114]	valid_0's binary_logloss: 0.0138399
[115]	valid_0's binary_logloss: 0.0138818
[116]	valid_0's binary_logloss: 0.0138243
[117]	valid_0's binary_logloss: 0.0137405
[118]	valid_0's binary_logloss: 0.013766
[119]	valid_0's binary_logloss: 0.0137514
[120]	valid_0's binary_logloss: 0.0137779
[121]	valid_0's binary_logloss: 0.0137686
[122]	valid_0's binary_logloss: 0.0138346
[123]	valid_0's binary_logloss: 0.0138664
[124]	valid_0's binary_logloss: 0.0138133
[125]	valid_0's binary_logloss: 0.0138376
[126]	valid_0's binary_logloss: 0.0138556
[127]	valid_0's binary_logloss: 0.013882
[128]	valid_0's binary_logloss: 0.0138595
[129]	valid_0's binary_logloss: 0.013842
[130]	valid_0's binary_logloss: 0.013906
[131]	valid_0's binary_logloss: 0.0138269
[132]	valid_0's binary_logloss: 0.013829
[133]	valid_0's binary_logloss: 0.0138841
[134]	valid_0's binary_logloss: 0.0138494
[135]	valid_0's binary_logloss: 0.0138561
[136]	valid_0's binary_logloss: 0.0138775
[137]	valid_0's binary_logloss: 0.0138763
[138]	valid_0's binary_logloss: 0.013865
[139]	valid_0's binary_logloss: 0.0138335
[140]	valid_0's binary_logloss: 0.0137834
[141]	valid_0's binary_logloss: 0.0138095
[142]	valid_0's binary_logloss: 0.0137652
[143]	valid_0's binary_logloss: 0.0137495
[144]	valid_0's binary_logloss: 0.0137847
[145]	valid_0's binary_logloss: 0.0137702
[146]	valid_0's binary_logloss: 0.0137951

Trening klas:  19%|█▉        | 95/500 [16:01<48:53,  7.24s/klasa, klasa=class_95, F1_klasy=0.7467, F1_macro=0.8480, drzewa=117]




Trening klas:  19%|█▉        | 96/500 [16:01<50:23,  7.48s/klasa, klasa=class_95, F1_klasy=0.7467, F1_macro=0.8480, drzewa=117]

[147]	valid_0's binary_logloss: 0.0138471
[1]	valid_0's binary_logloss: 0.210734
[2]	valid_0's binary_logloss: 0.190666
[3]	valid_0's binary_logloss: 0.177715
[4]	valid_0's binary_logloss: 0.166895
[5]	valid_0's binary_logloss: 0.159121
[6]	valid_0's binary_logloss: 0.152145
[7]	valid_0's binary_logloss: 0.146466
[8]	valid_0's binary_logloss: 0.142035
[9]	valid_0's binary_logloss: 0.138015
[10]	valid_0's binary_logloss: 0.134866
[11]	valid_0's binary_logloss: 0.132168
[12]	valid_0's binary_logloss: 0.129445
[13]	valid_0's binary_logloss: 0.127208
[14]	valid_0's binary_logloss: 0.125138
[15]	valid_0's binary_logloss: 0.123525
[16]	valid_0's binary_logloss: 0.121896
[17]	valid_0's binary_logloss: 0.120519
[18]	valid_0's binary_logloss: 0.119357
[19]	valid_0's binary_logloss: 0.118275
[20]	valid_0's binary_logloss: 0.11737
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.116383
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.115457
[23]	valid_0's binary_logloss: 0.114677
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.113984
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.113148
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.112652
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.11221
[28]	valid_0's binary_logloss: 0.111768
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.111567
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.111586
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.110927
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.110382
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.110177
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.110084
[35]	valid_0's binary_logloss: 0.109876
[36]	valid_0's binary_logloss: 0.109383
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.109255
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.109114
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.109161
[40]	valid_0's binary_logloss: 0.10909
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.109249
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.109221
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.10946
[44]	valid_0's binary_logloss: 0.109753
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.109855
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.109778
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.109838
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.109653
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.10965
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.109985
[51]	valid_0's binary_logloss: 0.110098
[52]	valid_0's binary_logloss: 0.110075
[53]	valid_0's binary_logloss: 0.110296
[54]	valid_0's binary_logloss: 0.110477
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.111133
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.11135
[57]	valid_0's binary_logloss: 0.111284
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.111315
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.111481
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.111844
[61]	valid_0's binary_logloss: 0.11202
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.112277
[63]	valid_0's binary_logloss: 0.112215
[64]	valid_0's binary_logloss: 0.112562
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.112838
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.113164
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.113297
[68]	valid_0's binary_logloss: 0.113494

Trening klas:  19%|█▉        | 96/500 [16:05<50:23,  7.48s/klasa, klasa=class_96, F1_klasy=0.6987, F1_macro=0.8464, drzewa=40]




Trening klas:  19%|█▉        | 97/500 [16:05<43:26,  6.47s/klasa, klasa=class_96, F1_klasy=0.6987, F1_macro=0.8464, drzewa=40]

[69]	valid_0's binary_logloss: 0.113538
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.113831
[1]	valid_0's binary_logloss: 0.139223
[2]	valid_0's binary_logloss: 0.123166
[3]	valid_0's binary_logloss: 0.112175
[4]	valid_0's binary_logloss: 0.10358
[5]	valid_0's binary_logloss: 0.0966488
[6]	valid_0's binary_logloss: 0.0909064
[7]	valid_0's binary_logloss: 0.0856942
[8]	valid_0's binary_logloss: 0.0811052
[9]	valid_0's binary_logloss: 0.0770187
[10]	valid_0's binary_logloss: 0.0735493
[11]	valid_0's binary_logloss: 0.0704723
[12]	valid_0's binary_logloss: 0.0677059
[13]	valid_0's binary_logloss: 0.0651168
[14]	valid_0's binary_logloss: 0.0627809
[15]	valid_0's binary_logloss: 0.0604685
[16]	valid_0's binary_logloss: 0.0584139
[17]	valid_0's binary_logloss: 0.0565001
[18]	valid_0's binary_logloss: 0.0546411
[19]	valid_0's binary_logloss: 0.0529038
[20]	valid_0's binary_logloss: 0.0512627
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0497832
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0484275
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.0473594
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0462192
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.0453403
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.0444541
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.043585
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.0427883
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.0420322
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.041403
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.0407116
[32]	valid_0's binary_logloss: 0.0399903
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.0394818
[34]	valid_0's binary_logloss: 0.0389041
[35]	valid_0's binary_logloss: 0.0384785
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.0380066
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.0375698
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.0371404
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.0368023
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.0364572
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.0359769
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.0357015
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.035505
[44]	valid_0's binary_logloss: 0.0350795
[45]	valid_0's binary_logloss: 0.0347148
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.0344224
[47]	valid_0's binary_logloss: 0.0343152
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.0341026
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.0338885
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.0337136
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.0336456
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.0335196
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.0333968
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.0333215
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.0332916
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.0331829
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.0331574
[58]	valid_0's binary_logloss: 0.0330885
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.0330659
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.0330176
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.0330722
[62]	valid_0's binary_logloss: 0.0329189
[63]	valid_0's binary_logloss: 0.0328918
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.0328731
[65]	valid_0's binary_logloss: 0.0328909
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.0328461
[67]	valid_0's binary_logloss: 0.0327688
[68]	valid_0's binary_logloss: 0.0327841
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.032685
[70]	valid_0's binary_logloss: 0.032671
[71]	valid_0's binary_logloss: 0.0324886
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.0322359
[73]	valid_0's binary_logloss: 0.0321571
[74]	valid_0's binary_logloss: 0.0321022
[75]	valid_0's binary_logloss: 0.0320824
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.0321791
[77]	valid_0's binary_logloss: 0.0320982
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.0321153
[79]	valid_0's binary_logloss: 0.0321318
[80]	valid_0's binary_logloss: 0.0321532
[81]	valid_0's binary_logloss: 0.0320937
[82]	valid_0's binary_logloss: 0.0320487
[83]	valid_0's binary_logloss: 0.0319874
[84]	valid_0's binary_logloss: 0.0319191
[85]	valid_0's binary_logloss: 0.0319682
[86]	valid_0's binary_logloss: 0.0320846
[87]	valid_0's binary_logloss: 0.0322067
[88]	valid_0's binary_logloss: 0.0322775
[89]	valid_0's binary_logloss: 0.0324117
[90]	valid_0's binary_logloss: 0.0324317
[91]	valid_0's binary_logloss: 0.0323968
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.0323908
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.0324185
[94]	valid_0's binary_logloss: 0.0324681
[95]	valid_0's binary_logloss: 0.032489
[96]	valid_0's binary_logloss: 0.0323834
[97]	valid_0's binary_logloss: 0.0323065
[98]	valid_0's binary_logloss: 0.032259
[99]	valid_0's binary_logloss: 0.0321722
[100]	valid_0's binary_logloss: 0.0322092
[101]	valid_0's binary_logloss: 0.0320277
[102]	valid_0's binary_logloss: 0.0320285
[103]	valid_0's binary_logloss: 0.0319223
[104]	valid_0's binary_logloss: 0.0318664
[105]	valid_0's binary_logloss: 0.0318559
[106]	valid_0's binary_logloss: 0.0320188
[107]	valid_0's binary_logloss: 0.0320202
[108]	valid_0's binary_logloss: 0.0320935
[109]	valid_0's binary_logloss: 0.0321227
[110]	valid_0's binary_logloss: 0.0322102
[111]	valid_0's binary_logloss: 0.0321667
[112]	valid_0's binary_logloss: 0.0321981
[113]	valid_0's binary_logloss: 0.0322372
[114]	valid_0's binary_logloss: 0.0324196
[115]	valid_0's binary_logloss: 0.032391
[116]	valid_0's binary_logloss: 0.0324632
[117]	valid_0's binary_logloss: 0.0324805
[118]	valid_0's binary_logloss: 0.0324862
[119]	valid_0's binary_logloss: 0.0325041
[120]	valid_0's binary_logloss: 0.0325816
[121]	valid_0's binary_logloss: 0.0326578
[122]	valid_0's binary_logloss: 0.0327523
[123]	valid_0's binary_logloss: 0.0327485
[124]	valid_0's binary_logloss: 0.0329056
[125]	valid_0's binary_logloss: 0.033072
[126]	valid_0's binary_logloss: 0.0330685
[127]	valid_0's binary_logloss: 0.0330156
[128]	valid_0's binary_logloss: 0.0330155
[129]	valid_0's binary_logloss: 0.0328419
[130]	valid_0's binary_logloss: 0.0327486
[131]	valid_0's binary_logloss: 0.0328425
[132]	valid_0's binary_logloss: 0.0328975

Trening klas:  19%|█▉        | 97/500 [16:15<43:26,  6.47s/klasa, klasa=class_97, F1_klasy=0.8956, F1_macro=0.8469, drzewa=105]




Trening klas:  20%|█▉        | 98/500 [16:15<49:23,  7.37s/klasa, klasa=class_97, F1_klasy=0.8956, F1_macro=0.8469, drzewa=105]

[133]	valid_0's binary_logloss: 0.0327694
[134]	valid_0's binary_logloss: 0.0327313
[135]	valid_0's binary_logloss: 0.0327677
[1]	valid_0's binary_logloss: 0.0726825
[2]	valid_0's binary_logloss: 0.0698985
[3]	valid_0's binary_logloss: 0.0676088
[4]	valid_0's binary_logloss: 0.065932
[5]	valid_0's binary_logloss: 0.0638584
[6]	valid_0's binary_logloss: 0.0621003
[7]	valid_0's binary_logloss: 0.0605199
[8]	valid_0's binary_logloss: 0.0592092
[9]	valid_0's binary_logloss: 0.0573336
[10]	valid_0's binary_logloss: 0.0556249
[11]	valid_0's binary_logloss: 0.0541781
[12]	valid_0's binary_logloss: 0.0527905
[13]	valid_0's binary_logloss: 0.0511931
[14]	valid_0's binary_logloss: 0.0499659
[15]	valid_0's binary_logloss: 0.0487515
[16]	valid_0's binary_logloss: 0.047654
[17]	valid_0's binary_logloss: 0.046541
[18]	valid_0's binary_logloss: 0.0453041
[19]	valid_0's binary_logloss: 0.0441625
[20]	valid_0's binary_logloss: 0.0431604
[21]	valid_0's binary_logloss: 0.0423333
[22]	valid_0's binary_logloss: 0.0415049
[23]	valid_0's binary_logloss: 0.0404604
[24]	valid_0's binary_logloss: 0.0395382
[25]	valid_0's binary_logloss: 0.0385555
[26]	valid_0's binary_logloss: 0.0378738
[27]	valid_0's binary_logloss: 0.037121
[28]	valid_0's binary_logloss: 0.0362038
[29]	valid_0's binary_logloss: 0.0355629
[30]	valid_0's binary_logloss: 0.0348828
[31]	valid_0's binary_logloss: 0.0342479
[32]	valid_0's binary_logloss: 0.0336404
[33]	valid_0's binary_logloss: 0.0331039
[34]	valid_0's binary_logloss: 0.0327447
[35]	valid_0's binary_logloss: 0.0322855
[36]	valid_0's binary_logloss: 0.0317255
[37]	valid_0's binary_logloss: 0.0312262
[38]	valid_0's binary_logloss: 0.0307668
[39]	valid_0's binary_logloss: 0.0301556
[40]	valid_0's binary_logloss: 0.0295994
[41]	valid_0's binary_logloss: 0.02889
[42]	valid_0's binary_logloss: 0.0283145
[43]	valid_0's binary_logloss: 0.0279335
[44]	valid_0's binary_logloss: 0.0275508
[45]	valid_0's binary_logloss: 0.0270378
[46]	valid_0's binary_logloss: 0.0265874
[47]	valid_0's binary_logloss: 0.0261983
[48]	valid_0's binary_logloss: 0.0256403
[49]	valid_0's binary_logloss: 0.0252195
[50]	valid_0's binary_logloss: 0.0249064
[51]	valid_0's binary_logloss: 0.024683
[52]	valid_0's binary_logloss: 0.0241833
[53]	valid_0's binary_logloss: 0.0238488
[54]	valid_0's binary_logloss: 0.0235922
[55]	valid_0's binary_logloss: 0.0232882
[56]	valid_0's binary_logloss: 0.0232118
[57]	valid_0's binary_logloss: 0.0228973
[58]	valid_0's binary_logloss: 0.0228068
[59]	valid_0's binary_logloss: 0.0225689
[60]	valid_0's binary_logloss: 0.0224426
[61]	valid_0's binary_logloss: 0.0222676
[62]	valid_0's binary_logloss: 0.0220913
[63]	valid_0's binary_logloss: 0.0219249
[64]	valid_0's binary_logloss: 0.0215547
[65]	valid_0's binary_logloss: 0.0213552
[66]	valid_0's binary_logloss: 0.0212528
[67]	valid_0's binary_logloss: 0.0211364
[68]	valid_0's binary_logloss: 0.0209572
[69]	valid_0's binary_logloss: 0.0207621
[70]	valid_0's binary_logloss: 0.0204988
[71]	valid_0's binary_logloss: 0.0202652
[72]	valid_0's binary_logloss: 0.0199904
[73]	valid_0's binary_logloss: 0.019869
[74]	valid_0's binary_logloss: 0.0196638
[75]	valid_0's binary_logloss: 0.0194322
[76]	valid_0's binary_logloss: 0.019185
[77]	valid_0's binary_logloss: 0.0188927
[78]	valid_0's binary_logloss: 0.018704
[79]	valid_0's binary_logloss: 0.0186175
[80]	valid_0's binary_logloss: 0.0184668
[81]	valid_0's binary_logloss: 0.0183351
[82]	valid_0's binary_logloss: 0.0181165
[83]	valid_0's binary_logloss: 0.0178898
[84]	valid_0's binary_logloss: 0.0177668
[85]	valid_0's binary_logloss: 0.0175978
[86]	valid_0's binary_logloss: 0.0175859
[87]	valid_0's binary_logloss: 0.0175254
[88]	valid_0's binary_logloss: 0.0174266
[89]	valid_0's binary_logloss: 0.0173173
[90]	valid_0's binary_logloss: 0.0172467
[91]	valid_0's binary_logloss: 0.0170845
[92]	valid_0's binary_logloss: 0.0169688
[93]	valid_0's binary_logloss: 0.0168716
[94]	valid_0's binary_logloss: 0.0168215
[95]	valid_0's binary_logloss: 0.0167175
[96]	valid_0's binary_logloss: 0.0166459
[97]	valid_0's binary_logloss: 0.0166022
[98]	valid_0's binary_logloss: 0.0165575
[99]	valid_0's binary_logloss: 0.0163788
[100]	valid_0's binary_logloss: 0.0162876
[101]	valid_0's binary_logloss: 0.0161181
[102]	valid_0's binary_logloss: 0.0159936
[103]	valid_0's binary_logloss: 0.0159522
[104]	valid_0's binary_logloss: 0.0159074
[105]	valid_0's binary_logloss: 0.015825
[106]	valid_0's binary_logloss: 0.0158116
[107]	valid_0's binary_logloss: 0.0157022
[108]	valid_0's binary_logloss: 0.0156345
[109]	valid_0's binary_logloss: 0.0155924
[110]	valid_0's binary_logloss: 0.0155198
[111]	valid_0's binary_logloss: 0.0154752
[112]	valid_0's binary_logloss: 0.0153952
[113]	valid_0's binary_logloss: 0.0153722
[114]	valid_0's binary_logloss: 0.0153633
[115]	valid_0's binary_logloss: 0.0152542
[116]	valid_0's binary_logloss: 0.0151871
[117]	valid_0's binary_logloss: 0.0151573
[118]	valid_0's binary_logloss: 0.0150688
[119]	valid_0's binary_logloss: 0.0150021
[120]	valid_0's binary_logloss: 0.0148687
[121]	valid_0's binary_logloss: 0.0146953
[122]	valid_0's binary_logloss: 0.0146272
[123]	valid_0's binary_logloss: 0.0145779
[124]	valid_0's binary_logloss: 0.0145103
[125]	valid_0's binary_logloss: 0.0144559
[126]	valid_0's binary_logloss: 0.0144516
[127]	valid_0's binary_logloss: 0.0144437
[128]	valid_0's binary_logloss: 0.01445
[129]	valid_0's binary_logloss: 0.014457
[130]	valid_0's binary_logloss: 0.0144336
[131]	valid_0's binary_logloss: 0.0144856
[132]	valid_0's binary_logloss: 0.0144419
[133]	valid_0's binary_logloss: 0.0144412
[134]	valid_0's binary_logloss: 0.0144035
[135]	valid_0's binary_logloss: 0.0143596
[136]	valid_0's binary_logloss: 0.0143567
[137]	valid_0's binary_logloss: 0.0142833
[138]	valid_0's binary_logloss: 0.0142626
[139]	valid_0's binary_logloss: 0.0142347
[140]	valid_0's binary_logloss: 0.014221
[141]	valid_0's binary_logloss: 0.0141473
[142]	valid_0's binary_logloss: 0.0140531
[143]	valid_0's binary_logloss: 0.0139978
[144]	valid_0's binary_logloss: 0.0139207
[145]	valid_0's binary_logloss: 0.01393
[146]	valid_0's binary_logloss: 0.0138805
[147]	valid_0's binary_logloss: 0.0138707
[148]	valid_0's binary_logloss: 0.0138329
[149]	valid_0's binary_logloss: 0.0138567
[150]	valid_0's binary_logloss: 0.0138406
[151]	valid_0's binary_logloss: 0.0138468
[152]	valid_0's binary_logloss: 0.0138858
[153]	valid_0's binary_logloss: 0.0138688
[154]	valid_0's binary_logloss: 0.0139008
[155]	valid_0's binary_logloss: 0.0139541
[156]	valid_0's binary_logloss: 0.0139733
[157]	valid_0's binary_logloss: 0.0139387
[158]	valid_0's binary_logloss: 0.0139167
[159]	valid_0's binary_logloss: 0.0138912
[160]	valid_0's binary_logloss: 0.0138514
[161]	valid_0's binary_logloss: 0.0138328
[162]	valid_0's binary_logloss: 0.013805
[163]	valid_0's binary_logloss: 0.0138055
[164]	valid_0's binary_logloss: 0.0138188
[165]	valid_0's binary_logloss: 0.0137864
[166]	valid_0's binary_logloss: 0.0137782
[167]	valid_0's binary_logloss: 0.0137917
[168]	valid_0's binary_logloss: 0.0137866
[169]	valid_0's binary_logloss: 0.013818
[170]	valid_0's binary_logloss: 0.0137782
[171]	valid_0's binary_logloss: 0.0137496
[172]	valid_0's binary_logloss: 0.0137496
[173]	valid_0's binary_logloss: 0.0137608
[174]	valid_0's binary_logloss: 0.0136815
[175]	valid_0's binary_logloss: 0.0136498
[176]	valid_0's binary_logloss: 0.013649
[177]	valid_0's binary_logloss: 0.0136315
[178]	valid_0's binary_logloss: 0.0136248
[179]	valid_0's binary_logloss: 0.0136102
[180]	valid_0's binary_logloss: 0.0135691
[181]	valid_0's binary_logloss: 0.013568
[182]	valid_0's binary_logloss: 0.0135372
[183]	valid_0's binary_logloss: 0.0134948
[184]	valid_0's binary_logloss: 0.0134371
[185]	valid_0's binary_logloss: 0.0134586
[186]	valid_0's binary_logloss: 0.01346
[187]	valid_0's binary_logloss: 0.0134387
[188]	valid_0's binary_logloss: 0.0134536
[189]	valid_0's binary_logloss: 0.013451
[190]	valid_0's binary_logloss: 0.0134367
[191]	valid_0's binary_logloss: 0.0133977
[192]	valid_0's binary_logloss: 0.013363
[193]	valid_0's binary_logloss: 0.0133414
[194]	valid_0's binary_logloss: 0.0133251
[195]	valid_0's binary_logloss: 0.0132699
[196]	valid_0's binary_logloss: 0.0132636
[197]	valid_0's binary_logloss: 0.013312
[198]	valid_0's binary_logloss: 0.0133344
[199]	valid_0's binary_logloss: 0.0132931
[200]	valid_0's binary_logloss: 0.0132573
[201]	valid_0's binary_logloss: 0.0132558
[202]	valid_0's binary_logloss: 0.0132213
[203]	valid_0's binary_logloss: 0.0132471
[204]	valid_0's binary_logloss: 0.0132484
[205]	valid_0's binary_logloss: 0.0132563
[206]	valid_0's binary_logloss: 0.0131873
[207]	valid_0's binary_logloss: 0.0131854
[208]	valid_0's binary_logloss: 0.013235
[209]	valid_0's binary_logloss: 0.0132576
[210]	valid_0's binary_logloss: 0.013227
[211]	valid_0's binary_logloss: 0.0132711
[212]	valid_0's binary_logloss: 0.0132809
[213]	valid_0's binary_logloss: 0.013276
[214]	valid_0's binary_logloss: 0.0132755
[215]	valid_0's binary_logloss: 0.0132813
[216]	valid_0's binary_logloss: 0.0133018
[217]	valid_0's binary_logloss: 0.0133605
[218]	valid_0's binary_logloss: 0.0133778
[219]	valid_0's binary_logloss: 0.0133749
[220]	valid_0's binary_logloss: 0.013366
[221]	valid_0's binary_logloss: 0.0133556
[222]	valid_0's binary_logloss: 0.0133488
[223]	valid_0's binary_logloss: 0.0133507
[224]	valid_0's binary_logloss: 0.0133901
[225]	valid_0's binary_logloss: 0.0133638
[226]	valid_0's binary_logloss: 0.0134018
[227]	valid_0's binary_logloss: 0.0134249
[228]	valid_0's binary_logloss: 0.0133783
[229]	valid_0's binary_logloss: 0.0134021
[230]	valid_0's binary_logloss: 0.0134384
[231]	valid_0's binary_logloss: 0.0134773
[232]	valid_0's binary_logloss: 0.01346
[233]	valid_0's binary_logloss: 0.0134207
[234]	valid_0's binary_logloss: 0.0134068
[235]	valid_0's binary_logloss: 0.0134051

Trening klas:  20%|█▉        | 98/500 [16:31<49:23,  7.37s/klasa, klasa=class_98, F1_klasy=0.7010, F1_macro=0.8455, drzewa=207]




Trening klas:  20%|█▉        | 99/500 [16:31<1:07:34, 10.11s/klasa, klasa=class_98, F1_klasy=0.7010, F1_macro=0.8455, drzewa=207]

[236]	valid_0's binary_logloss: 0.0134307
[237]	valid_0's binary_logloss: 0.013416
[1]	valid_0's binary_logloss: 0.163838
[2]	valid_0's binary_logloss: 0.151228
[3]	valid_0's binary_logloss: 0.142573
[4]	valid_0's binary_logloss: 0.135964
[5]	valid_0's binary_logloss: 0.131078
[6]	valid_0's binary_logloss: 0.126671
[7]	valid_0's binary_logloss: 0.123025
[8]	valid_0's binary_logloss: 0.119624
[9]	valid_0's binary_logloss: 0.116757
[10]	valid_0's binary_logloss: 0.114307
[11]	valid_0's binary_logloss: 0.111773
[12]	valid_0's binary_logloss: 0.109809
[13]	valid_0's binary_logloss: 0.108021
[14]	valid_0's binary_logloss: 0.106577
[15]	valid_0's binary_logloss: 0.104864
[16]	valid_0's binary_logloss: 0.103478
[17]	valid_0's binary_logloss: 0.102434
[18]	valid_0's binary_logloss: 0.101405
[19]	valid_0's binary_logloss: 0.100464
[20]	valid_0's binary_logloss: 0.0996957
[21]	valid_0's binary_logloss: 0.0990055
[22]	valid_0's binary_logloss: 0.0984569
[23]	valid_0's binary_logloss: 0.0978202
[24]	valid_0's binary_logloss: 0.0970685
[25]	valid_0's binary_logloss: 0.0963888
[26]	valid_0's binary_logloss: 0.0959421
[27]	valid_0's binary_logloss: 0.0952086
[28]	valid_0's binary_logloss: 0.0947504
[29]	valid_0's binary_logloss: 0.0941943
[30]	valid_0's binary_logloss: 0.0935908
[31]	valid_0's binary_logloss: 0.0934759
[32]	valid_0's binary_logloss: 0.0934917
[33]	valid_0's binary_logloss: 0.0934774
[34]	valid_0's binary_logloss: 0.0932304
[35]	valid_0's binary_logloss: 0.0929605
[36]	valid_0's binary_logloss: 0.0929299
[37]	valid_0's binary_logloss: 0.0927482
[38]	valid_0's binary_logloss: 0.0926909
[39]	valid_0's binary_logloss: 0.0922755
[40]	valid_0's binary_logloss: 0.0922096
[41]	valid_0's binary_logloss: 0.0922556
[42]	valid_0's binary_logloss: 0.092285
[43]	valid_0's binary_logloss: 0.0922183
[44]	valid_0's binary_logloss: 0.0924878
[45]	valid_0's binary_logloss: 0.0926852
[46]	valid_0's binary_logloss: 0.0926593
[47]	valid_0's binary_logloss: 0.0925947
[48]	valid_0's binary_logloss: 0.0925664
[49]	valid_0's binary_logloss: 0.0925539
[50]	valid_0's binary_logloss: 0.0924439
[51]	valid_0's binary_logloss: 0.0923278
[52]	valid_0's binary_logloss: 0.0922474
[53]	valid_0's binary_logloss: 0.0923416
[54]	valid_0's binary_logloss: 0.0924262
[55]	valid_0's binary_logloss: 0.0924158
[56]	valid_0's binary_logloss: 0.0923859
[57]	valid_0's binary_logloss: 0.092249
[58]	valid_0's binary_logloss: 0.0922159
[59]	valid_0's binary_logloss: 0.091969
[60]	valid_0's binary_logloss: 0.0916696
[61]	valid_0's binary_logloss: 0.0918555
[62]	valid_0's binary_logloss: 0.0920883
[63]	valid_0's binary_logloss: 0.0922647
[64]	valid_0's binary_logloss: 0.0925386
[65]	valid_0's binary_logloss: 0.0922837
[66]	valid_0's binary_logloss: 0.0923475
[67]	valid_0's binary_logloss: 0.0923816
[68]	valid_0's binary_logloss: 0.0923968
[69]	valid_0's binary_logloss: 0.0924329
[70]	valid_0's binary_logloss: 0.0925387
[71]	valid_0's binary_logloss: 0.092713
[72]	valid_0's binary_logloss: 0.0926647
[73]	valid_0's binary_logloss: 0.0928788
[74]	valid_0's binary_logloss: 0.0932072
[75]	valid_0's binary_logloss: 0.0934263
[76]	valid_0's binary_logloss: 0.0933517
[77]	valid_0's binary_logloss: 0.0934263
[78]	valid_0's binary_logloss: 0.0934393
[79]	valid_0's binary_logloss: 0.0935606
[80]	valid_0's binary_logloss: 0.0938841
[81]	valid_0's binary_logloss: 0.0938852
[82]	valid_0's binary_logloss: 0.0937352
[83]	valid_0's binary_logloss: 0.0937287
[84]	valid_0's binary_logloss: 0.0937049
[85]	valid_0's binary_logloss: 0.0938053
[86]	valid_0's binary_logloss: 0.0938102
[87]	valid_0's binary_logloss: 0.0938515

Trening klas:  20%|█▉        | 99/500 [16:39<1:07:34, 10.11s/klasa, klasa=class_99, F1_klasy=0.6158, F1_macro=0.8432, drzewa=60]




Trening klas:  20%|██        | 100/500 [16:39<1:02:07,  9.32s/klasa, klasa=class_99, F1_klasy=0.6158, F1_macro=0.8432, drzewa=60]

[88]	valid_0's binary_logloss: 0.0939347
[89]	valid_0's binary_logloss: 0.0940785
[90]	valid_0's binary_logloss: 0.0942877
[1]	valid_0's binary_logloss: 0.204163
[2]	valid_0's binary_logloss: 0.179682
[3]	valid_0's binary_logloss: 0.16232
[4]	valid_0's binary_logloss: 0.149569
[5]	valid_0's binary_logloss: 0.139253
[6]	valid_0's binary_logloss: 0.130256
[7]	valid_0's binary_logloss: 0.122971
[8]	valid_0's binary_logloss: 0.116461
[9]	valid_0's binary_logloss: 0.111156
[10]	valid_0's binary_logloss: 0.10609
[11]	valid_0's binary_logloss: 0.10139
[12]	valid_0's binary_logloss: 0.097178
[13]	valid_0's binary_logloss: 0.0936629
[14]	valid_0's binary_logloss: 0.0904977
[15]	valid_0's binary_logloss: 0.0876596
[16]	valid_0's binary_logloss: 0.0848255
[17]	valid_0's binary_logloss: 0.0823593
[18]	valid_0's binary_logloss: 0.0802149
[19]	valid_0's binary_logloss: 0.0783424
[20]	valid_0's binary_logloss: 0.0761648
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0745359
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0727298
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.071336
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0699633
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.0690014
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.06778
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.0665833
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.0656671
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.0645158
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.0636585
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.0627925
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.0617044
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.0607637
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.0598493
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.0590686
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.0586319
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.0582133
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.0578648
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.0575964
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.0573109
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.0569769
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.0567109
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.0563897
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.0557813
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.0556683
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.0553861
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.055154
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.0549091
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.0548925
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.0546519
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.0544103
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.0542846
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.054276
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.054231
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.0541879
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.0542165
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.0542106
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.054209
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.0542092
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.0541032
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.0541375
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.0540441
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.0541348
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.0544335
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.054535
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.0546165
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.054714
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.0548667
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.0549488
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.0551125
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.0548463
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.054768
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.0547778
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.0547902
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.0546996
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.0547723
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.0548419
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.0550493
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.0550633
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.0551456
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.0552794
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.0552326
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.0555142
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.0555861
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.0558926
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.0561932
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.0564469
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.0566902
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.0565748
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.056585
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.0568724
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.0570897

Trening klas:  20%|██        | 100/500 [16:43<1:02:07,  9.32s/klasa, klasa=class_100, F1_klasy=0.8932, F1_macro=0.8437, drzewa=62]




Trening klas:  20%|██        | 101/500 [16:43<52:07,  7.84s/klasa, klasa=class_100, F1_klasy=0.8932, F1_macro=0.8437, drzewa=62]

[1]	valid_0's binary_logloss: 0.17845
[2]	valid_0's binary_logloss: 0.157434
[3]	valid_0's binary_logloss: 0.14334
[4]	valid_0's binary_logloss: 0.132349
[5]	valid_0's binary_logloss: 0.124017
[6]	valid_0's binary_logloss: 0.116478
[7]	valid_0's binary_logloss: 0.110593
[8]	valid_0's binary_logloss: 0.105372
[9]	valid_0's binary_logloss: 0.101014
[10]	valid_0's binary_logloss: 0.0966915
[11]	valid_0's binary_logloss: 0.0934052
[12]	valid_0's binary_logloss: 0.0904954
[13]	valid_0's binary_logloss: 0.0880352
[14]	valid_0's binary_logloss: 0.0851792
[15]	valid_0's binary_logloss: 0.0827605
[16]	valid_0's binary_logloss: 0.0801643
[17]	valid_0's binary_logloss: 0.0782421
[18]	valid_0's binary_logloss: 0.0761334
[19]	valid_0's binary_logloss: 0.0742779
[20]	valid_0's binary_logloss: 0.0723647
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0706829
[22]	valid_0's binary_logloss: 0.0691311
[23]	valid_0's binary_logloss: 0.067431
[24]	valid_0's binary_logloss: 0.06621
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.0648648
[26]	valid_0's binary_logloss: 0.0636166
[27]	valid_0's binary_logloss: 0.0624982
[28]	valid_0's binary_logloss: 0.0615435
[29]	valid_0's binary_logloss: 0.0607054
[30]	valid_0's binary_logloss: 0.0597469
[31]	valid_0's binary_logloss: 0.0587512
[32]	valid_0's binary_logloss: 0.0581362
[33]	valid_0's binary_logloss: 0.0574644
[34]	valid_0's binary_logloss: 0.0568331
[35]	valid_0's binary_logloss: 0.0562441
[36]	valid_0's binary_logloss: 0.0555018
[37]	valid_0's binary_logloss: 0.0545175
[38]	valid_0's binary_logloss: 0.0539196
[39]	valid_0's binary_logloss: 0.0529908
[40]	valid_0's binary_logloss: 0.0524848
[41]	valid_0's binary_logloss: 0.0519361
[42]	valid_0's binary_logloss: 0.0515253
[43]	valid_0's binary_logloss: 0.0510988
[44]	valid_0's binary_logloss: 0.0507479
[45]	valid_0's binary_logloss: 0.0503241
[46]	valid_0's binary_logloss: 0.0498678
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.0495119
[48]	valid_0's binary_logloss: 0.0491783
[49]	valid_0's binary_logloss: 0.0488417
[50]	valid_0's binary_logloss: 0.048631
[51]	valid_0's binary_logloss: 0.048246
[52]	valid_0's binary_logloss: 0.0477738
[53]	valid_0's binary_logloss: 0.0474683
[54]	valid_0's binary_logloss: 0.0471675
[55]	valid_0's binary_logloss: 0.046716
[56]	valid_0's binary_logloss: 0.0464829
[57]	valid_0's binary_logloss: 0.046229
[58]	valid_0's binary_logloss: 0.0461973
[59]	valid_0's binary_logloss: 0.0461191
[60]	valid_0's binary_logloss: 0.0459183
[61]	valid_0's binary_logloss: 0.0457483
[62]	valid_0's binary_logloss: 0.0456166
[63]	valid_0's binary_logloss: 0.0453165
[64]	valid_0's binary_logloss: 0.0451527
[65]	valid_0's binary_logloss: 0.0451514
[66]	valid_0's binary_logloss: 0.0449053
[67]	valid_0's binary_logloss: 0.0447388
[68]	valid_0's binary_logloss: 0.0448103
[69]	valid_0's binary_logloss: 0.0445321
[70]	valid_0's binary_logloss: 0.0443836
[71]	valid_0's binary_logloss: 0.0442922
[72]	valid_0's binary_logloss: 0.0442566
[73]	valid_0's binary_logloss: 0.0440914
[74]	valid_0's binary_logloss: 0.0440175
[75]	valid_0's binary_logloss: 0.0437434
[76]	valid_0's binary_logloss: 0.0436351
[77]	valid_0's binary_logloss: 0.0435786
[78]	valid_0's binary_logloss: 0.0434203
[79]	valid_0's binary_logloss: 0.0433986
[80]	valid_0's binary_logloss: 0.0434059
[81]	valid_0's binary_logloss: 0.0431891
[82]	valid_0's binary_logloss: 0.0430901
[83]	valid_0's binary_logloss: 0.0431357
[84]	valid_0's binary_logloss: 0.0431022
[85]	valid_0's binary_logloss: 0.0431441
[86]	valid_0's binary_logloss: 0.0430842
[87]	valid_0's binary_logloss: 0.0430172
[88]	valid_0's binary_logloss: 0.0429817
[89]	valid_0's binary_logloss: 0.0429848
[90]	valid_0's binary_logloss: 0.04284
[91]	valid_0's binary_logloss: 0.0427872
[92]	valid_0's binary_logloss: 0.0427248
[93]	valid_0's binary_logloss: 0.042759
[94]	valid_0's binary_logloss: 0.0425779
[95]	valid_0's binary_logloss: 0.0425586
[96]	valid_0's binary_logloss: 0.0423809
[97]	valid_0's binary_logloss: 0.0426312
[98]	valid_0's binary_logloss: 0.0427209
[99]	valid_0's binary_logloss: 0.0427742
[100]	valid_0's binary_logloss: 0.0428428
[101]	valid_0's binary_logloss: 0.0427924
[102]	valid_0's binary_logloss: 0.0429107
[103]	valid_0's binary_logloss: 0.0428884
[104]	valid_0's binary_logloss: 0.0430454
[105]	valid_0's binary_logloss: 0.0430293
[106]	valid_0's binary_logloss: 0.043045
[107]	valid_0's binary_logloss: 0.0432773
[108]	valid_0's binary_logloss: 0.0434469
[109]	valid_0's binary_logloss: 0.0435443
[110]	valid_0's binary_logloss: 0.0436397
[111]	valid_0's binary_logloss: 0.0436218
[112]	valid_0's binary_logloss: 0.0435071
[113]	valid_0's binary_logloss: 0.0434855
[114]	valid_0's binary_logloss: 0.0435376
[115]	valid_0's binary_logloss: 0.0435483
[116]	valid_0's binary_logloss: 0.0434788
[117]	valid_0's binary_logloss: 0.043449
[118]	valid_0's binary_logloss: 0.0434573
[119]	valid_0's binary_logloss: 0.0435351
[120]	valid_0's binary_logloss: 0.0436246
[121]	valid_0's binary_logloss: 0.0436311
[122]	valid_0's binary_logloss: 0.0436617
[123]	valid_0's binary_logloss: 0.0437734
[124]	valid_0's binary_logloss: 0.0437729
[125]	valid_0's binary_logloss: 0.0437686

Trening klas:  20%|██        | 101/500 [16:51<52:07,  7.84s/klasa, klasa=class_101, F1_klasy=0.8835, F1_macro=0.8440, drzewa=96]




Trening klas:  20%|██        | 102/500 [16:51<50:56,  7.68s/klasa, klasa=class_101, F1_klasy=0.8835, F1_macro=0.8440, drzewa=96]

[126]	valid_0's binary_logloss: 0.0438384
[1]	valid_0's binary_logloss: 0.213365
[2]	valid_0's binary_logloss: 0.192532
[3]	valid_0's binary_logloss: 0.178336
[4]	valid_0's binary_logloss: 0.167148
[5]	valid_0's binary_logloss: 0.158667
[6]	valid_0's binary_logloss: 0.151469
[7]	valid_0's binary_logloss: 0.145317
[8]	valid_0's binary_logloss: 0.139618
[9]	valid_0's binary_logloss: 0.135386
[10]	valid_0's binary_logloss: 0.131104
[11]	valid_0's binary_logloss: 0.127743
[12]	valid_0's binary_logloss: 0.12456
[13]	valid_0's binary_logloss: 0.121542
[14]	valid_0's binary_logloss: 0.118875
[15]	valid_0's binary_logloss: 0.116496
[16]	valid_0's binary_logloss: 0.114788
[17]	valid_0's binary_logloss: 0.113238
[18]	valid_0's binary_logloss: 0.112075
[19]	valid_0's binary_logloss: 0.110572
[20]	valid_0's binary_logloss: 0.10926
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.107819
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.10675
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.10537
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.104409
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.103674
[26]	valid_0's binary_logloss: 0.102994
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.102409
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.101579
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.100975
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.100446
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.0998982
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.0993729
[33]	valid_0's binary_logloss: 0.0988226
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.0986386
[35]	valid_0's binary_logloss: 0.0983322
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.0981926
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.0980773
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.0980933
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.0980972
[40]	valid_0's binary_logloss: 0.0978306
[41]	valid_0's binary_logloss: 0.0979253
[42]	valid_0's binary_logloss: 0.0978642
[43]	valid_0's binary_logloss: 0.0977861
[44]	valid_0's binary_logloss: 0.0980467
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.0979634
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.0978153
[47]	valid_0's binary_logloss: 0.0980366
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.0981096
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.0983336
[50]	valid_0's binary_logloss: 0.0986932
[51]	valid_0's binary_logloss: 0.0986763
[52]	valid_0's binary_logloss: 0.0988815
[53]	valid_0's binary_logloss: 0.0991813
[54]	valid_0's binary_logloss: 0.099427
[55]	valid_0's binary_logloss: 0.0993571
[56]	valid_0's binary_logloss: 0.0996102
[57]	valid_0's binary_logloss: 0.0996692
[58]	valid_0's binary_logloss: 0.0996822
[59]	valid_0's binary_logloss: 0.0994994
[60]	valid_0's binary_logloss: 0.0995521
[61]	valid_0's binary_logloss: 0.0996393
[62]	valid_0's binary_logloss: 0.0999182
[63]	valid_0's binary_logloss: 0.100155
[64]	valid_0's binary_logloss: 0.100395
[65]	valid_0's binary_logloss: 0.100623
[66]	valid_0's binary_logloss: 0.100918
[67]	valid_0's binary_logloss: 0.101397
[68]	valid_0's binary_logloss: 0.101818
[69]	valid_0's binary_logloss: 0.102047
[70]	valid_0's binary_logloss: 0.102227

Trening klas:  20%|██        | 102/500 [16:55<50:56,  7.68s/klasa, klasa=class_102, F1_klasy=0.7498, F1_macro=0.8431, drzewa=43]




Trening klas:  21%|██        | 103/500 [16:55<43:58,  6.65s/klasa, klasa=class_102, F1_klasy=0.7498, F1_macro=0.8431, drzewa=43]

[71]	valid_0's binary_logloss: 0.102469
[72]	valid_0's binary_logloss: 0.102811
[73]	valid_0's binary_logloss: 0.103091
[1]	valid_0's binary_logloss: 0.110488
[2]	valid_0's binary_logloss: 0.0985943
[3]	valid_0's binary_logloss: 0.0900969
[4]	valid_0's binary_logloss: 0.0834505
[5]	valid_0's binary_logloss: 0.0780666
[6]	valid_0's binary_logloss: 0.0729887
[7]	valid_0's binary_logloss: 0.06886
[8]	valid_0's binary_logloss: 0.0650855
[9]	valid_0's binary_logloss: 0.0619061
[10]	valid_0's binary_logloss: 0.0590196
[11]	valid_0's binary_logloss: 0.0563499
[12]	valid_0's binary_logloss: 0.054031
[13]	valid_0's binary_logloss: 0.0518948
[14]	valid_0's binary_logloss: 0.049842
[15]	valid_0's binary_logloss: 0.0480006
[16]	valid_0's binary_logloss: 0.0462265
[17]	valid_0's binary_logloss: 0.0447107
[18]	valid_0's binary_logloss: 0.0432019
[19]	valid_0's binary_logloss: 0.0418753
[20]	valid_0's binary_logloss: 0.0407135
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0395311
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0383767
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.0374518
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0365044
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.0356839
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.034818
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.0337483
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.0327914
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.0319982
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.0314103
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.0308861
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.0303544
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.0299304
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.0294991
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.0290984
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.0286562
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.0284124
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.0278033
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.0275049
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.0269676
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.0266055
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.026305
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.0259403
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.0256522
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.0255012
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.0251454
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.0248379
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.0245371
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.0243239
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.0242009
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.0240887
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.0238572
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.0237502
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.023666
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.0236803
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.023686
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.0234956
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.0235047
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.0232489
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.0230732
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.0231532
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.023208
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.0232196
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.023286
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.0233316
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.0232519
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.0232771
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.0231057
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.0231214
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.0230135
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.022849
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.0226461
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.022516
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.022414
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.0223675
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.0223571
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.022234
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.022257
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.0222535
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.0222494
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.022136
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.0220085
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.0219422
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.0218251
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.0217782
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.0218635
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.0219058
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.0219253
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.0220134
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.0221443
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.0220594
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.022058
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.0220722
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.0220814
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.0221796
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.0221263
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.0220589
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.0221394
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.0221705
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.0221388
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.022199
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.0222673
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.0223706
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.0224565
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.022568
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.0226137
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.0225874
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.0225634
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.0225093
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.0225063
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.0226028
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 0.0226049
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

Trening klas:  21%|██        | 103/500 [16:59<43:58,  6.65s/klasa, klasa=class_103, F1_klasy=0.9095, F1_macro=0.8438, drzewa=85]




Trening klas:  21%|██        | 104/500 [16:59<39:14,  5.95s/klasa, klasa=class_103, F1_klasy=0.9095, F1_macro=0.8438, drzewa=85]

[113]	valid_0's binary_logloss: 0.0227473
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 0.022829
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 0.0228533
[1]	valid_0's binary_logloss: 0.14539
[2]	valid_0's binary_logloss: 0.127493
[3]	valid_0's binary_logloss: 0.114839
[4]	valid_0's binary_logloss: 0.105046
[5]	valid_0's binary_logloss: 0.097165
[6]	valid_0's binary_logloss: 0.090523
[7]	valid_0's binary_logloss: 0.0848762
[8]	valid_0's binary_logloss: 0.0799355
[9]	valid_0's binary_logloss: 0.0756875
[10]	valid_0's binary_logloss: 0.0719111
[11]	valid_0's binary_logloss: 0.0685501
[12]	valid_0's binary_logloss: 0.0655018
[13]	valid_0's binary_logloss: 0.0628145
[14]	valid_0's binary_logloss: 0.0604091
[15]	valid_0's binary_logloss: 0.0581588
[16]	valid_0's binary_logloss: 0.056182
[17]	valid_0's binary_logloss: 0.0543969
[18]	valid_0's binary_logloss: 0.0527091
[19]	valid_0's binary_logloss: 0.0508696
[20]	valid_0's binary_logloss: 0.0495591
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.048146
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0467728
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.045688
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0447264
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.0436358
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.0427938
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.0420341
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.0411757
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.0403923
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.0396744
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.0391828
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.0384635
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.038145
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.0375174
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.0370445
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.0368227
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.0363599
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.0360113
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.0356324
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.035244
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.0351027
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.0350127
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.0349311
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.0347986
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.0347434
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.0345178
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.0343791
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.0342303
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.0342226
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.0341077
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.0338797
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.0337211
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.0336419
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.0335312
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.0334823
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.0335385
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.0335964
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.0336777
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.033796
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.0338504
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.0338828
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.0339424
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.0340757
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.034156
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.0342282
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.034302
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.034368
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.034432
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.0345153
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.0346125
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.0347195
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.0348202
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.0348488
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.0348916
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.0348173
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.0348914
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

Trening klas:  21%|██        | 104/500 [17:02<39:14,  5.95s/klasa, klasa=class_104, F1_klasy=0.9080, F1_macro=0.8444, drzewa=55]




Trening klas:  21%|██        | 105/500 [17:02<33:33,  5.10s/klasa, klasa=class_104, F1_klasy=0.9080, F1_macro=0.8444, drzewa=55]

[77]	valid_0's binary_logloss: 0.0349541
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.035032
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.035129
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.0351506
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.0351198
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.0350763
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.0350934
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.0350225
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.0349746
[1]	valid_0's binary_logloss: 0.114425
[2]	valid_0's binary_logloss: 0.102591
[3]	valid_0's binary_logloss: 0.0946337
[4]	valid_0's binary_logloss: 0.088488
[5]	valid_0's binary_logloss: 0.0837067
[6]	valid_0's binary_logloss: 0.0795208
[7]	valid_0's binary_logloss: 0.0759515
[8]	valid_0's binary_logloss: 0.0728376
[9]	valid_0's binary_logloss: 0.069978
[10]	valid_0's binary_logloss: 0.0674843
[11]	valid_0's binary_logloss: 0.0654942
[12]	valid_0's binary_logloss: 0.0637446
[13]	valid_0's binary_logloss: 0.0622716
[14]	valid_0's binary_logloss: 0.0608078
[15]	valid_0's binary_logloss: 0.05933
[16]	valid_0's binary_logloss: 0.0580845
[17]	valid_0's binary_logloss: 0.0571439
[18]	valid_0's binary_logloss: 0.0561291
[19]	valid_0's binary_logloss: 0.0553092
[20]	valid_0's binary_logloss: 0.0546774
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0541616
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0533653
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.0527566
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0520733
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.051695
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.0512893
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.0508407
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.0504591
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.0502916
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.050066
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.0498767
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.049695
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.0495563
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.0491778
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.0490446
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.0489777
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.0488303
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.0487611
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.0487589
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.0487479
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.0486206
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.0485852
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.0486005
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.0486249
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.0487284
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.048749
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.0489215
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.0490077
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.04912
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.0492847
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.0492787
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.0494189
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.0496796
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.0497694
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.0495983
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.0497344
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.0498893
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.0500844
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.0502262
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.0503583
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.0506322
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.0508425
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.0510333
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.0512003
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.051185
[66]	valid_0's binary_logloss: 0.0513071
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.0514358
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.0515397
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.0516134
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.0516108
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.0517689
[72]	valid_0's binary_logloss: 0.051813

Trening klas:  21%|██        | 105/500 [17:06<33:33,  5.10s/klasa, klasa=class_105, F1_klasy=0.7867, F1_macro=0.8438, drzewa=42]




Trening klas:  21%|██        | 106/500 [17:06<30:49,  4.70s/klasa, klasa=class_105, F1_klasy=0.7867, F1_macro=0.8438, drzewa=42]

[1]	valid_0's binary_logloss: 0.144745
[2]	valid_0's binary_logloss: 0.142528
[3]	valid_0's binary_logloss: 0.145345
[4]	valid_0's binary_logloss: 0.146466
[5]	valid_0's binary_logloss: 0.150185
[6]	valid_0's binary_logloss: 0.154339
[7]	valid_0's binary_logloss: 0.15718
[8]	valid_0's binary_logloss: 0.159895
[9]	valid_0's binary_logloss: 0.16465
[10]	valid_0's binary_logloss: 0.167352
[11]	valid_0's binary_logloss: 0.170756
[12]	valid_0's binary_logloss: 0.173615
[13]	valid_0's binary_logloss: 0.175742
[14]	valid_0's binary_logloss: 0.177729
[15]	valid_0's binary_logloss: 0.180914
[16]	valid_0's binary_logloss: 0.184002
[17]	valid_0's binary_logloss: 0.187628
[18]	valid_0's binary_logloss: 0.189904
[19]	valid_0's binary_logloss: 0.192254
[20]	valid_0's binary_logloss: 0.195864
[21]	valid_0's binary_logloss: 0.1985
[22]	valid_0's binary_logloss: 0.201844
[23]	valid_0's binary_logloss: 0.203898
[24]	valid_0's binary_logloss: 0.206775
[25]	valid_0's binary_logloss: 0.209619
[26]	valid_0's binary_logloss: 0.212048
[27]	valid_0's binary_logloss: 0.213984
[28]	valid_0's binary_logloss: 0.217191
[29]	valid_0's binary_logloss: 0.218146
[30]	valid_0's binary_logloss: 0.220925

Trening klas:  21%|██        | 106/500 [17:10<30:49,  4.70s/klasa, klasa=class_106, F1_klasy=0.0000, F1_macro=0.8359, drzewa=2]




Trening klas:  21%|██▏       | 107/500 [17:10<29:13,  4.46s/klasa, klasa=class_106, F1_klasy=0.0000, F1_macro=0.8359, drzewa=2]

[31]	valid_0's binary_logloss: 0.221836
[32]	valid_0's binary_logloss: 0.224208
[1]	valid_0's binary_logloss: 0.229016
[2]	valid_0's binary_logloss: 0.21938
[3]	valid_0's binary_logloss: 0.210889
[4]	valid_0's binary_logloss: 0.203479
[5]	valid_0's binary_logloss: 0.197169
[6]	valid_0's binary_logloss: 0.192286
[7]	valid_0's binary_logloss: 0.18797
[8]	valid_0's binary_logloss: 0.184559
[9]	valid_0's binary_logloss: 0.181628
[10]	valid_0's binary_logloss: 0.179518
[11]	valid_0's binary_logloss: 0.177548
[12]	valid_0's binary_logloss: 0.17551
[13]	valid_0's binary_logloss: 0.173948
[14]	valid_0's binary_logloss: 0.171626
[15]	valid_0's binary_logloss: 0.169348
[16]	valid_0's binary_logloss: 0.167999
[17]	valid_0's binary_logloss: 0.166408
[18]	valid_0's binary_logloss: 0.164914
[19]	valid_0's binary_logloss: 0.16382
[20]	valid_0's binary_logloss: 0.162822
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.162587
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.16185
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.161326
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.160794
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.160041
[26]	valid_0's binary_logloss: 0.158984
[27]	valid_0's binary_logloss: 0.15813
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.157199
[29]	valid_0's binary_logloss: 0.156361
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.155784
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.155312
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.154712
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.154515
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.154372
[35]	valid_0's binary_logloss: 0.154225
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.153981
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.153529
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.152827
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.152484
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.152703
[41]	valid_0's binary_logloss: 0.152339
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.152241
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.152034
[44]	valid_0's binary_logloss: 0.151625
[45]	valid_0's binary_logloss: 0.151619
[46]	valid_0's binary_logloss: 0.151685
[47]	valid_0's binary_logloss: 0.151832
[48]	valid_0's binary_logloss: 0.15192
[49]	valid_0's binary_logloss: 0.152035
[50]	valid_0's binary_logloss: 0.152267
[51]	valid_0's binary_logloss: 0.152127
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.152008
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.152319
[54]	valid_0's binary_logloss: 0.152391
[55]	valid_0's binary_logloss: 0.152402
[56]	valid_0's binary_logloss: 0.152586
[57]	valid_0's binary_logloss: 0.152925
[58]	valid_0's binary_logloss: 0.153109
[59]	valid_0's binary_logloss: 0.153427
[60]	valid_0's binary_logloss: 0.153699
[61]	valid_0's binary_logloss: 0.153767
[62]	valid_0's binary_logloss: 0.153984
[63]	valid_0's binary_logloss: 0.154061
[64]	valid_0's binary_logloss: 0.1541
[65]	valid_0's binary_logloss: 0.154163
[66]	valid_0's binary_logloss: 0.154403
[67]	valid_0's binary_logloss: 0.154598
[68]	valid_0's binary_logloss: 0.154675
[69]	valid_0's binary_logloss: 0.154791
[70]	valid_0's binary_logloss: 0.154958
[71]	valid_0's binary_logloss: 0.155159
[72]	valid_0's binary_logloss: 0.155507
[73]	valid_0's binary_logloss: 0.155782
[74]	valid_0's binary_logloss: 0.155636
[75]	valid_0's binary_logloss: 0.156245

Trening klas:  21%|██▏       | 107/500 [17:14<29:13,  4.46s/klasa, klasa=class_107, F1_klasy=0.5849, F1_macro=0.8336, drzewa=45]




Trening klas:  22%|██▏       | 108/500 [17:14<29:08,  4.46s/klasa, klasa=class_107, F1_klasy=0.5849, F1_macro=0.8336, drzewa=45]

[1]	valid_0's binary_logloss: 0.134553
[2]	valid_0's binary_logloss: 0.119178
[3]	valid_0's binary_logloss: 0.107677
[4]	valid_0's binary_logloss: 0.0987668
[5]	valid_0's binary_logloss: 0.0915051
[6]	valid_0's binary_logloss: 0.0846894
[7]	valid_0's binary_logloss: 0.0793621
[8]	valid_0's binary_logloss: 0.0746838
[9]	valid_0's binary_logloss: 0.0706168
[10]	valid_0's binary_logloss: 0.0669314
[11]	valid_0's binary_logloss: 0.0636444
[12]	valid_0's binary_logloss: 0.0606533
[13]	valid_0's binary_logloss: 0.0579615
[14]	valid_0's binary_logloss: 0.0554046
[15]	valid_0's binary_logloss: 0.0528571
[16]	valid_0's binary_logloss: 0.0507959
[17]	valid_0's binary_logloss: 0.0489568
[18]	valid_0's binary_logloss: 0.047119
[19]	valid_0's binary_logloss: 0.0454118
[20]	valid_0's binary_logloss: 0.0438212
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0423336
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.040926
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.0396205
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0384215
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.0372877
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.0363265
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.0354887
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.0346137
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.0336897
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.0328923
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.0321694
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.0314597
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.030928
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.0302559
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.0295732
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.0291208
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.0285859
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.0281555
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.0277283
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.0273486
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.0270759
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.0267656
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.0265048
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.0263266
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.0260754
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.0258336
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.0256059
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.0254182
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.0252925
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.0251132
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.0250536
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.0249199
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.0248907
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.0248557
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.0247553
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.0246532
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.024492
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.024464
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.0244352
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.0244168
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.0242957
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.0241615
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.0241494
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.0241407
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.0241365
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.024072
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.0239887
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.0239852
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.024032
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.0241083
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.0240998
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.0241213
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.024075
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.0240765
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.0241071
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.0240441
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.0240152
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.0240639
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.02408
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.0241412
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.0242001
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.0242927
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.0243819
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.0245627
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.0246431
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.0247049
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.0248103
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.0249024
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.0249958
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.0251193
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.0252449
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.025323
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.0254317
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.0255359
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.0256365
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.0256382
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.0257301
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

Trening klas:  22%|██▏       | 108/500 [17:18<29:08,  4.46s/klasa, klasa=class_108, F1_klasy=0.9257, F1_macro=0.8345, drzewa=68]




Trening klas:  22%|██▏       | 109/500 [17:18<27:46,  4.26s/klasa, klasa=class_108, F1_klasy=0.9257, F1_macro=0.8345, drzewa=68]

[98]	valid_0's binary_logloss: 0.0258585
[1]	valid_0's binary_logloss: 0.109123
[2]	valid_0's binary_logloss: 0.102502
[3]	valid_0's binary_logloss: 0.0975531
[4]	valid_0's binary_logloss: 0.0939795
[5]	valid_0's binary_logloss: 0.0911348
[6]	valid_0's binary_logloss: 0.0885625
[7]	valid_0's binary_logloss: 0.0863216
[8]	valid_0's binary_logloss: 0.0841951
[9]	valid_0's binary_logloss: 0.0827796
[10]	valid_0's binary_logloss: 0.0814125
[11]	valid_0's binary_logloss: 0.079874
[12]	valid_0's binary_logloss: 0.0787903
[13]	valid_0's binary_logloss: 0.0774314
[14]	valid_0's binary_logloss: 0.0763073
[15]	valid_0's binary_logloss: 0.0752435
[16]	valid_0's binary_logloss: 0.074297
[17]	valid_0's binary_logloss: 0.0735912
[18]	valid_0's binary_logloss: 0.0727134
[19]	valid_0's binary_logloss: 0.0720318
[20]	valid_0's binary_logloss: 0.0711809
[21]	valid_0's binary_logloss: 0.0705949
[22]	valid_0's binary_logloss: 0.0701699
[23]	valid_0's binary_logloss: 0.0698441
[24]	valid_0's binary_logloss: 0.0693941
[25]	valid_0's binary_logloss: 0.069278
[26]	valid_0's binary_logloss: 0.0688895
[27]	valid_0's binary_logloss: 0.0687807
[28]	valid_0's binary_logloss: 0.068494
[29]	valid_0's binary_logloss: 0.0683344
[30]	valid_0's binary_logloss: 0.0679148
[31]	valid_0's binary_logloss: 0.0676187
[32]	valid_0's binary_logloss: 0.0673325
[33]	valid_0's binary_logloss: 0.0670641
[34]	valid_0's binary_logloss: 0.0667739
[35]	valid_0's binary_logloss: 0.0666009
[36]	valid_0's binary_logloss: 0.0662635
[37]	valid_0's binary_logloss: 0.0661108
[38]	valid_0's binary_logloss: 0.0662003
[39]	valid_0's binary_logloss: 0.0661585
[40]	valid_0's binary_logloss: 0.0660903
[41]	valid_0's binary_logloss: 0.0659583
[42]	valid_0's binary_logloss: 0.0658512
[43]	valid_0's binary_logloss: 0.0657056
[44]	valid_0's binary_logloss: 0.0655539
[45]	valid_0's binary_logloss: 0.0652591
[46]	valid_0's binary_logloss: 0.0654175
[47]	valid_0's binary_logloss: 0.0653564
[48]	valid_0's binary_logloss: 0.0650679
[49]	valid_0's binary_logloss: 0.0649546
[50]	valid_0's binary_logloss: 0.0650213
[51]	valid_0's binary_logloss: 0.0650038
[52]	valid_0's binary_logloss: 0.0650789
[53]	valid_0's binary_logloss: 0.0650631
[54]	valid_0's binary_logloss: 0.0652787
[55]	valid_0's binary_logloss: 0.0653807
[56]	valid_0's binary_logloss: 0.0652388
[57]	valid_0's binary_logloss: 0.06535
[58]	valid_0's binary_logloss: 0.0652555
[59]	valid_0's binary_logloss: 0.0652433
[60]	valid_0's binary_logloss: 0.0651279
[61]	valid_0's binary_logloss: 0.0651412
[62]	valid_0's binary_logloss: 0.0651289
[63]	valid_0's binary_logloss: 0.0652221
[64]	valid_0's binary_logloss: 0.0652882
[65]	valid_0's binary_logloss: 0.0654221
[66]	valid_0's binary_logloss: 0.065522
[67]	valid_0's binary_logloss: 0.0655401
[68]	valid_0's binary_logloss: 0.0655343
[69]	valid_0's binary_logloss: 0.0654422
[70]	valid_0's binary_logloss: 0.0654279
[71]	valid_0's binary_logloss: 0.0655145
[72]	valid_0's binary_logloss: 0.0655755
[73]	valid_0's binary_logloss: 0.0656934
[74]	valid_0's binary_logloss: 0.0657773
[75]	valid_0's binary_logloss: 0.0657382

[76]	valid_0's binary_logloss: 0.0658899
[77]	valid_0's binary_logloss: 0.066048
[78]	valid_0's binary_logloss: 0.0662647
[79]	valid_0's binary_logloss: 0.066496

Trening klas:  22%|██▏       | 109/500 [17:24<27:46,  4.26s/klasa, klasa=class_109, F1_klasy=0.5274, F1_macro=0.8317, drzewa=49]




Trening klas:  22%|██▏       | 110/500 [17:24<30:45,  4.73s/klasa, klasa=class_109, F1_klasy=0.5274, F1_macro=0.8317, drzewa=49]

[1]	valid_0's binary_logloss: 0.117271
[2]	valid_0's binary_logloss: 0.105773
[3]	valid_0's binary_logloss: 0.0973997
[4]	valid_0's binary_logloss: 0.0908166
[5]	valid_0's binary_logloss: 0.0854518
[6]	valid_0's binary_logloss: 0.0810422
[7]	valid_0's binary_logloss: 0.0774574
[8]	valid_0's binary_logloss: 0.0737617
[9]	valid_0's binary_logloss: 0.0706678
[10]	valid_0's binary_logloss: 0.0677474
[11]	valid_0's binary_logloss: 0.0650173
[12]	valid_0's binary_logloss: 0.062716
[13]	valid_0's binary_logloss: 0.0604145
[14]	valid_0's binary_logloss: 0.0582999
[15]	valid_0's binary_logloss: 0.0562335
[16]	valid_0's binary_logloss: 0.0543988
[17]	valid_0's binary_logloss: 0.052697
[18]	valid_0's binary_logloss: 0.0511095
[19]	valid_0's binary_logloss: 0.0496032
[20]	valid_0's binary_logloss: 0.0483242
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0471682
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0460783
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.0450403
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0440456
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.0430312
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.0422305
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.0414787
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.0407425
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.0399608
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.0392817
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.0385909
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.0380014
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.037534
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.0368838
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.036362
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.0360092
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.0355477
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.0351654
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.0348262
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.0344172
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.0340176
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.033711
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.0334266
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.0331488
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.0328897
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.0325473
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.0321402
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.0318525
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.0315601
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.031236
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.0309155
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.0306777
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.0304392
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.0302018
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.029921
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.0297674
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.0296549
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.0294308
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.0294206
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.0293722
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.0291712
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.0289637
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.0288075
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.0287037
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.028645
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.0286371
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.0285837
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.0285413
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.0285313
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.0284999
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.0284792
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.0284877
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.0284417
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.028426
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.0283852
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.0283523
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.0284004
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.0284501
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.0284471
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.028465
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.0286149
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.0286234
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.0285983
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.0286467
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.028697
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.0286176
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.0285246
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.0286082
[89]	valid_0's binary_logloss: 0.0285897
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.0284944
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.0285625
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.0286414
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.0286862
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.0287304
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.0287816
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.0286601
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.028594
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.0285138
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.028505
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.0285315
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.0285624
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.0286516
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.0286202
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.0287009
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.0287872
[106]	valid_0's binary_logloss: 0.0287501

Trening klas:  22%|██▏       | 110/500 [17:30<30:45,  4.73s/klasa, klasa=class_110, F1_klasy=0.8918, F1_macro=0.8322, drzewa=76]




Trening klas:  22%|██▏       | 111/500 [17:30<34:06,  5.26s/klasa, klasa=class_110, F1_klasy=0.8918, F1_macro=0.8322, drzewa=76]

[1]	valid_0's binary_logloss: 0.105114
[2]	valid_0's binary_logloss: 0.0960993
[3]	valid_0's binary_logloss: 0.0894231
[4]	valid_0's binary_logloss: 0.0841665
[5]	valid_0's binary_logloss: 0.0798002
[6]	valid_0's binary_logloss: 0.0765962
[7]	valid_0's binary_logloss: 0.0735926
[8]	valid_0's binary_logloss: 0.0709709
[9]	valid_0's binary_logloss: 0.068849
[10]	valid_0's binary_logloss: 0.066962
[11]	valid_0's binary_logloss: 0.0653218
[12]	valid_0's binary_logloss: 0.063548
[13]	valid_0's binary_logloss: 0.0618463
[14]	valid_0's binary_logloss: 0.060554
[15]	valid_0's binary_logloss: 0.0593291
[16]	valid_0's binary_logloss: 0.0579313
[17]	valid_0's binary_logloss: 0.0569207
[18]	valid_0's binary_logloss: 0.0557703
[19]	valid_0's binary_logloss: 0.0545548
[20]	valid_0's binary_logloss: 0.0536689
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0528838
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0520012
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.0513022
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0505596
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.0498713
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.0496075
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.0490196
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.0485017
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.0481112
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.0475958
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.0470712
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.0466941
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.0462095
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.0458506
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.0453837
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.0452118
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.0447369
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.0445392
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.0441906
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.0439778
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.0437197
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.0434962
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.0433975
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.0432809
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.0431932
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.0430133
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.0429207
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.0429142
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.0427831
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.04273
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.0428905
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.0427139
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.0427965
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.042872
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.042736
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.0426967
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.042728
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.0425821
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.0424775
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.0425863
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.0425826
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.0424962
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.0426769
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.0428318
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.042872
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.0426486
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.0425413
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.0425285
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.0426436
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.0427086
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.0428054
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.0427707
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.0428268
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.0429587
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.0429165
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.0430466
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.043123
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.043441
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.0437043
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.0440601
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.0439248
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.0437531
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.0437558
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.0433639
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

Trening klas:  22%|██▏       | 111/500 [17:35<34:06,  5.26s/klasa, klasa=class_111, F1_klasy=0.7594, F1_macro=0.8316, drzewa=59]




Trening klas:  22%|██▏       | 112/500 [17:35<31:38,  4.89s/klasa, klasa=class_111, F1_klasy=0.7594, F1_macro=0.8316, drzewa=59]

[85]	valid_0's binary_logloss: 0.043256
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.0431835
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.0430957
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.0430097
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.0429501
[1]	valid_0's binary_logloss: 0.066735
[2]	valid_0's binary_logloss: 0.0638954
[3]	valid_0's binary_logloss: 0.0618311
[4]	valid_0's binary_logloss: 0.0598757
[5]	valid_0's binary_logloss: 0.0585429
[6]	valid_0's binary_logloss: 0.0571421
[7]	valid_0's binary_logloss: 0.0557156
[8]	valid_0's binary_logloss: 0.0546577
[9]	valid_0's binary_logloss: 0.0536079
[10]	valid_0's binary_logloss: 0.0523913
[11]	valid_0's binary_logloss: 0.0513855
[12]	valid_0's binary_logloss: 0.0504304
[13]	valid_0's binary_logloss: 0.0495395
[14]	valid_0's binary_logloss: 0.0488522
[15]	valid_0's binary_logloss: 0.0482336
[16]	valid_0's binary_logloss: 0.0473014
[17]	valid_0's binary_logloss: 0.0464618
[18]	valid_0's binary_logloss: 0.0456405
[19]	valid_0's binary_logloss: 0.0449217
[20]	valid_0's binary_logloss: 0.0442115
[21]	valid_0's binary_logloss: 0.0436738
[22]	valid_0's binary_logloss: 0.0430468
[23]	valid_0's binary_logloss: 0.0424876
[24]	valid_0's binary_logloss: 0.0418031
[25]	valid_0's binary_logloss: 0.0414217
[26]	valid_0's binary_logloss: 0.0408005
[27]	valid_0's binary_logloss: 0.0404712
[28]	valid_0's binary_logloss: 0.0401162
[29]	valid_0's binary_logloss: 0.0397352
[30]	valid_0's binary_logloss: 0.0391612
[31]	valid_0's binary_logloss: 0.0388408
[32]	valid_0's binary_logloss: 0.0384909
[33]	valid_0's binary_logloss: 0.0383623
[34]	valid_0's binary_logloss: 0.0378385
[35]	valid_0's binary_logloss: 0.0374682
[36]	valid_0's binary_logloss: 0.0371951
[37]	valid_0's binary_logloss: 0.0368575
[38]	valid_0's binary_logloss: 0.0365485
[39]	valid_0's binary_logloss: 0.0361925
[40]	valid_0's binary_logloss: 0.035954
[41]	valid_0's binary_logloss: 0.0356092
[42]	valid_0's binary_logloss: 0.0353846
[43]	valid_0's binary_logloss: 0.0350183
[44]	valid_0's binary_logloss: 0.0346857
[45]	valid_0's binary_logloss: 0.0346001
[46]	valid_0's binary_logloss: 0.0344131
[47]	valid_0's binary_logloss: 0.0341268
[48]	valid_0's binary_logloss: 0.0339164
[49]	valid_0's binary_logloss: 0.0338253
[50]	valid_0's binary_logloss: 0.0337167
[51]	valid_0's binary_logloss: 0.033613
[52]	valid_0's binary_logloss: 0.033545
[53]	valid_0's binary_logloss: 0.0334491
[54]	valid_0's binary_logloss: 0.0331508
[55]	valid_0's binary_logloss: 0.0329337
[56]	valid_0's binary_logloss: 0.032807
[57]	valid_0's binary_logloss: 0.0328602
[58]	valid_0's binary_logloss: 0.032856
[59]	valid_0's binary_logloss: 0.0329089
[60]	valid_0's binary_logloss: 0.0328894
[61]	valid_0's binary_logloss: 0.0327665
[62]	valid_0's binary_logloss: 0.0325732
[63]	valid_0's binary_logloss: 0.0325466
[64]	valid_0's binary_logloss: 0.0326789
[65]	valid_0's binary_logloss: 0.0324851
[66]	valid_0's binary_logloss: 0.0324569
[67]	valid_0's binary_logloss: 0.0323475
[68]	valid_0's binary_logloss: 0.0322755
[69]	valid_0's binary_logloss: 0.0322212
[70]	valid_0's binary_logloss: 0.0321647
[71]	valid_0's binary_logloss: 0.0321374
[72]	valid_0's binary_logloss: 0.0321539
[73]	valid_0's binary_logloss: 0.0321482
[74]	valid_0's binary_logloss: 0.0321485
[75]	valid_0's binary_logloss: 0.0322197
[76]	valid_0's binary_logloss: 0.0322643
[77]	valid_0's binary_logloss: 0.0323303
[78]	valid_0's binary_logloss: 0.0323401
[79]	valid_0's binary_logloss: 0.0323715
[80]	valid_0's binary_logloss: 0.032349
[81]	valid_0's binary_logloss: 0.0323379
[82]	valid_0's binary_logloss: 0.0322739
[83]	valid_0's binary_logloss: 0.0322967
[84]	valid_0's binary_logloss: 0.0321588
[85]	valid_0's binary_logloss: 0.0321538
[86]	valid_0's binary_logloss: 0.0321237
[87]	valid_0's binary_logloss: 0.0320412
[88]	valid_0's binary_logloss: 0.0320084
[89]	valid_0's binary_logloss: 0.0319153
[90]	valid_0's binary_logloss: 0.0318751
[91]	valid_0's binary_logloss: 0.0318479
[92]	valid_0's binary_logloss: 0.031835
[93]	valid_0's binary_logloss: 0.0317182
[94]	valid_0's binary_logloss: 0.031779
[95]	valid_0's binary_logloss: 0.0318075
[96]	valid_0's binary_logloss: 0.0317674
[97]	valid_0's binary_logloss: 0.0317752
[98]	valid_0's binary_logloss: 0.0317746
[99]	valid_0's binary_logloss: 0.031671
[100]	valid_0's binary_logloss: 0.0315592
[101]	valid_0's binary_logloss: 0.0314298
[102]	valid_0's binary_logloss: 0.031316
[103]	valid_0's binary_logloss: 0.0312471
[104]	valid_0's binary_logloss: 0.0311857
[105]	valid_0's binary_logloss: 0.0311745
[106]	valid_0's binary_logloss: 0.031239
[107]	valid_0's binary_logloss: 0.0313128
[108]	valid_0's binary_logloss: 0.0313491
[109]	valid_0's binary_logloss: 0.0314227
[110]	valid_0's binary_logloss: 0.0315134
[111]	valid_0's binary_logloss: 0.0314846
[112]	valid_0's binary_logloss: 0.0314597
[113]	valid_0's binary_logloss: 0.0314598
[114]	valid_0's binary_logloss: 0.0314328
[115]	valid_0's binary_logloss: 0.0314104
[116]	valid_0's binary_logloss: 0.0315194
[117]	valid_0's binary_logloss: 0.0316483
[118]	valid_0's binary_logloss: 0.0315949
[119]	valid_0's binary_logloss: 0.031668
[120]	valid_0's binary_logloss: 0.031692
[121]	valid_0's binary_logloss: 0.0317556
[122]	valid_0's binary_logloss: 0.031745
[123]	valid_0's binary_logloss: 0.0317863
[124]	valid_0's binary_logloss: 0.031864
[125]	valid_0's binary_logloss: 0.0319966
[126]	valid_0's binary_logloss: 0.031961
[127]	valid_0's binary_logloss: 0.0319172
[128]	valid_0's binary_logloss: 0.0320051
[129]	valid_0's binary_logloss: 0.0319576
[130]	valid_0's binary_logloss: 0.0318832
[131]	valid_0's binary_logloss: 0.0319573
[132]	valid_0's binary_logloss: 0.0319727
[133]	valid_0's binary_logloss: 0.0319205
[134]	valid_0's binary_logloss: 0.0318848

Trening klas:  22%|██▏       | 112/500 [17:45<31:38,  4.89s/klasa, klasa=class_112, F1_klasy=0.5283, F1_macro=0.8289, drzewa=105]




Trening klas:  23%|██▎       | 113/500 [17:45<42:22,  6.57s/klasa, klasa=class_112, F1_klasy=0.5283, F1_macro=0.8289, drzewa=105]

[135]	valid_0's binary_logloss: 0.0319574
[1]	valid_0's binary_logloss: 0.14066
[2]	valid_0's binary_logloss: 0.129707
[3]	valid_0's binary_logloss: 0.122003
[4]	valid_0's binary_logloss: 0.115605
[5]	valid_0's binary_logloss: 0.110435
[6]	valid_0's binary_logloss: 0.106309
[7]	valid_0's binary_logloss: 0.102897
[8]	valid_0's binary_logloss: 0.0995647
[9]	valid_0's binary_logloss: 0.0967909
[10]	valid_0's binary_logloss: 0.0946749
[11]	valid_0's binary_logloss: 0.0926714
[12]	valid_0's binary_logloss: 0.0906607
[13]	valid_0's binary_logloss: 0.0887667
[14]	valid_0's binary_logloss: 0.0871771
[15]	valid_0's binary_logloss: 0.0857554
[16]	valid_0's binary_logloss: 0.0843547
[17]	valid_0's binary_logloss: 0.0830091
[18]	valid_0's binary_logloss: 0.0816561
[19]	valid_0's binary_logloss: 0.0805541
[20]	valid_0's binary_logloss: 0.0795794
[21]	valid_0's binary_logloss: 0.0786449
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0778786
[23]	valid_0's binary_logloss: 0.0771873
[24]	valid_0's binary_logloss: 0.0765805
[25]	valid_0's binary_logloss: 0.0760549
[26]	valid_0's binary_logloss: 0.0753906
[27]	valid_0's binary_logloss: 0.0748128
[28]	valid_0's binary_logloss: 0.0743285
[29]	valid_0's binary_logloss: 0.0735951
[30]	valid_0's binary_logloss: 0.0732398
[31]	valid_0's binary_logloss: 0.0728052
[32]	valid_0's binary_logloss: 0.0725199
[33]	valid_0's binary_logloss: 0.0723197
[34]	valid_0's binary_logloss: 0.0722525
[35]	valid_0's binary_logloss: 0.0720431
[36]	valid_0's binary_logloss: 0.0718302
[37]	valid_0's binary_logloss: 0.0717276
[38]	valid_0's binary_logloss: 0.0715664
[39]	valid_0's binary_logloss: 0.071382
[40]	valid_0's binary_logloss: 0.0712911
[41]	valid_0's binary_logloss: 0.071001
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.0709393
[43]	valid_0's binary_logloss: 0.0708484
[44]	valid_0's binary_logloss: 0.0706279
[45]	valid_0's binary_logloss: 0.0705905
[46]	valid_0's binary_logloss: 0.0705916
[47]	valid_0's binary_logloss: 0.070592
[48]	valid_0's binary_logloss: 0.0706679
[49]	valid_0's binary_logloss: 0.070545
[50]	valid_0's binary_logloss: 0.0706175
[51]	valid_0's binary_logloss: 0.0706328
[52]	valid_0's binary_logloss: 0.0707539
[53]	valid_0's binary_logloss: 0.0707223
[54]	valid_0's binary_logloss: 0.0706501
[55]	valid_0's binary_logloss: 0.070757
[56]	valid_0's binary_logloss: 0.071098
[57]	valid_0's binary_logloss: 0.0714211
[58]	valid_0's binary_logloss: 0.0715987
[59]	valid_0's binary_logloss: 0.0717227
[60]	valid_0's binary_logloss: 0.071878
[61]	valid_0's binary_logloss: 0.0720261
[62]	valid_0's binary_logloss: 0.072149
[63]	valid_0's binary_logloss: 0.0722541
[64]	valid_0's binary_logloss: 0.0726593
[65]	valid_0's binary_logloss: 0.0728453
[66]	valid_0's binary_logloss: 0.0727947
[67]	valid_0's binary_logloss: 0.0729298
[68]	valid_0's binary_logloss: 0.0730483
[69]	valid_0's binary_logloss: 0.073304
[70]	valid_0's binary_logloss: 0.073426
[71]	valid_0's binary_logloss: 0.0734493
[72]	valid_0's binary_logloss: 0.0734504
[73]	valid_0's binary_logloss: 0.0735403
[74]	valid_0's binary_logloss: 0.0736345
[75]	valid_0's binary_logloss: 0.0738251
[76]	valid_0's binary_logloss: 0.0738327
[77]	valid_0's binary_logloss: 0.0737539
[78]	valid_0's binary_logloss: 0.0740005

Trening klas:  23%|██▎       | 113/500 [17:52<42:22,  6.57s/klasa, klasa=class_113, F1_klasy=0.7736, F1_macro=0.8284, drzewa=49]




Trening klas:  23%|██▎       | 114/500 [17:52<43:02,  6.69s/klasa, klasa=class_113, F1_klasy=0.7736, F1_macro=0.8284, drzewa=49]

[79]	valid_0's binary_logloss: 0.0741835
[1]	valid_0's binary_logloss: 0.0887118
[2]	valid_0's binary_logloss: 0.0809207
[3]	valid_0's binary_logloss: 0.0754168
[4]	valid_0's binary_logloss: 0.0711826
[5]	valid_0's binary_logloss: 0.0674105
[6]	valid_0's binary_logloss: 0.0640671
[7]	valid_0's binary_logloss: 0.0611565
[8]	valid_0's binary_logloss: 0.0585893
[9]	valid_0's binary_logloss: 0.0563829
[10]	valid_0's binary_logloss: 0.0543126
[11]	valid_0's binary_logloss: 0.0527379
[12]	valid_0's binary_logloss: 0.0512689
[13]	valid_0's binary_logloss: 0.0498913
[14]	valid_0's binary_logloss: 0.0484195
[15]	valid_0's binary_logloss: 0.0472565
[16]	valid_0's binary_logloss: 0.0458677
[17]	valid_0's binary_logloss: 0.0449052
[18]	valid_0's binary_logloss: 0.0441232
[19]	valid_0's binary_logloss: 0.0432283
[20]	valid_0's binary_logloss: 0.0424476
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0418338
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0411759
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.040443
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0398385
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.0393951
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.0386052
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.037918
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.0374522
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.036934
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.0365527
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.0361714
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.0358252
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.0353541
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.0350268
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.034776
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.0346016
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.0345237
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.034468
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.0344208
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.0344122
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.0342447
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.0340354
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.0337748
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.0336419
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.0334703
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.0333948
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.0332822
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.0330994
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.0328901
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.0328955
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.0328866
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.0327508
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.0326527
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.0326589
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.0325415
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.0325619
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.0324117
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.0323854
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.0323208
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.0324367
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.0325284
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.0324488
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.0323558
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.032506
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.0326721
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.032846
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.0325728
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.0326181
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.0326621
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.0326985
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.0327731
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.0328558
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.0329877
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.033054
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.0329931
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.0329245
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.0329001
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.0329046
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.0329939
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.0330937
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.0332345
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.033362
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.0332731
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.0332009
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

Trening klas:  23%|██▎       | 114/500 [17:57<43:02,  6.69s/klasa, klasa=class_114, F1_klasy=0.7786, F1_macro=0.8280, drzewa=59]




Trening klas:  23%|██▎       | 115/500 [17:57<39:40,  6.18s/klasa, klasa=class_114, F1_klasy=0.7786, F1_macro=0.8280, drzewa=59]

[85]	valid_0's binary_logloss: 0.0331792
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.0332187
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.0332078
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.0332005
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.0332187
[1]	valid_0's binary_logloss: 0.0713418
[2]	valid_0's binary_logloss: 0.0648877
[3]	valid_0's binary_logloss: 0.0604924
[4]	valid_0's binary_logloss: 0.0570086
[5]	valid_0's binary_logloss: 0.0538597
[6]	valid_0's binary_logloss: 0.0512628
[7]	valid_0's binary_logloss: 0.0493043
[8]	valid_0's binary_logloss: 0.0470522
[9]	valid_0's binary_logloss: 0.0450994
[10]	valid_0's binary_logloss: 0.0434621
[11]	valid_0's binary_logloss: 0.0417758
[12]	valid_0's binary_logloss: 0.0402254
[13]	valid_0's binary_logloss: 0.0388647
[14]	valid_0's binary_logloss: 0.0376386
[15]	valid_0's binary_logloss: 0.0366157
[16]	valid_0's binary_logloss: 0.0357997
[17]	valid_0's binary_logloss: 0.0347325
[18]	valid_0's binary_logloss: 0.0337545
[19]	valid_0's binary_logloss: 0.0328632
[20]	valid_0's binary_logloss: 0.0320244
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0312884
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0306374
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.0300364
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0293546
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.0287654
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.028095
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.0273708
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.0267836
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.0262787
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.0257097
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.0246476
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.0238301
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.0229792
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.0222911
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.0215379
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.02102
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.0204925
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.0200039
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.0195322
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.0191696
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.0185773
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.0179762
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.0175088
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.0169474
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.016476
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.0162913
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.0159553
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.0155861
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.015354
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.0151245
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.0148398
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.0147728
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.0147022
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.014564
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.0145117
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.0143948
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.0142474
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.0140154
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.0137301
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.0135247
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.0133119
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.013223
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.0131541
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.0130262
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.0129076
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.0128684
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.0127888
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.0128218
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.0128848
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.0129879
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.0128313
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.0126544
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.0126112
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.0124485
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.012311
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.0121575
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.0119206
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.0118496
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.0117074
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.011598
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.0114956
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.0114434
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.0113671
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.0113078
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.0112664
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.0111495
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.0111879
[88]	valid_0's binary_logloss: 0.0111029
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.0111542
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.0111859
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.0110955
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.011011
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.010874
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.0107869
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.0107214
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.010662
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.0106952
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.0107316
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.0107739
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.0107847
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.0108206
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.0108616
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.0109209
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.0110516
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.0110606
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.010999
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.0109324
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.0109164
[109]	valid_0's binary_logloss: 0.0108414
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.010808
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.0107949
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 0.0108184
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 0.0107526
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 0.0107701
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 0.0108044
[116]	valid_0's binary_logloss: 0.0107391
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[117]	valid_0's binary_logloss: 0.0106265
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[118]	valid_0's binary_logloss: 0.0105648
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[119]	valid_0's binary_logloss: 0.0105256
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[120]	valid_0's binary_logloss: 0.0104789
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[121]	valid_0's binary_logloss: 0.0104638
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[122]	valid_0's binary_logloss: 0.0104611
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[123]	valid_0's binary_logloss: 0.010432
[124]	valid_0's binary_logloss: 0.0104633
[125]	valid_0's binary_logloss: 0.0104836
[126]	valid_0's binary_logloss: 0.0104867
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[127]	valid_0's binary_logloss: 0.0105037
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[128]	valid_0's binary_logloss: 0.0105469
[129]	valid_0's binary_logloss: 0.0105946
[130]	valid_0's binary_logloss: 0.0106305
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[131]	valid_0's binary_logloss: 0.0106592
[132]	valid_0's binary_logloss: 0.0106967
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[133]	valid_0's binary_logloss: 0.0107363
[134]	valid_0's binary_logloss: 0.0107754
[135]	valid_0's binary_logloss: 0.0108148
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[136]	valid_0's binary_logloss: 0.0108866
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[137]	valid_0's binary_logloss: 0.0109034
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[138]	valid_0's binary_logloss: 0.0109746
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[139]	valid_0's binary_logloss: 0.0110257
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[140]	valid_0's binary_logloss: 0.0110742
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[141]	valid_0's binary_logloss: 0.0111047
[142]	valid_0's binary_logloss: 0.0111198
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[143]	valid_0's binary_logloss: 0.0111766
[144]	valid_0's binary_logloss: 0.0112086
[145]	valid_0's binary_logloss: 0.0112306
[146]	valid_0's binary_logloss: 0.0112405
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[147]	valid_0's binary_logloss: 0.01129
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[148]	valid_0's binary_logloss: 0.0112872
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[149]	valid_0's binary_logloss: 0.0113529
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

Trening klas:  23%|██▎       | 115/500 [18:04<39:40,  6.18s/klasa, klasa=class_115, F1_klasy=0.9372, F1_macro=0.8289, drzewa=123]




Trening klas:  23%|██▎       | 116/500 [18:04<41:13,  6.44s/klasa, klasa=class_115, F1_klasy=0.9372, F1_macro=0.8289, drzewa=123]

[150]	valid_0's binary_logloss: 0.0113378
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[151]	valid_0's binary_logloss: 0.0113595
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[152]	valid_0's binary_logloss: 0.0114011
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[153]	valid_0's binary_logloss: 0.0114414
[1]	valid_0's binary_logloss: 0.0747644
[2]	valid_0's binary_logloss: 0.0679543
[3]	valid_0's binary_logloss: 0.0629145
[4]	valid_0's binary_logloss: 0.0590182
[5]	valid_0's binary_logloss: 0.0557572
[6]	valid_0's binary_logloss: 0.052845
[7]	valid_0's binary_logloss: 0.0501688
[8]	valid_0's binary_logloss: 0.0478402
[9]	valid_0's binary_logloss: 0.0457384
[10]	valid_0's binary_logloss: 0.0440372
[11]	valid_0's binary_logloss: 0.0423334
[12]	valid_0's binary_logloss: 0.0406004
[13]	valid_0's binary_logloss: 0.0389595
[14]	valid_0's binary_logloss: 0.0374705
[15]	valid_0's binary_logloss: 0.0361817
[16]	valid_0's binary_logloss: 0.0349519
[17]	valid_0's binary_logloss: 0.0336898
[18]	valid_0's binary_logloss: 0.0326302
[19]	valid_0's binary_logloss: 0.0314297
[20]	valid_0's binary_logloss: 0.0304556
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0293932
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.028536
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.0276956
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0269154
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.026218
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.0256275
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.0252139
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.0247259
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.0242193
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.0236452
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.023301
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.0229846
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.0227187
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.0224513
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.0222034
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.0220587
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.0217447
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.0216161
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.0215996
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.0210928
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.0206542
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.0204922
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.0201205
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.0197945
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.0196603
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.0195185
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.0195744
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.0197223
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.0197961
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.0198994
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.0196906
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.0195735
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.0194736
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.0194062
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.0192341
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.0191123
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.0190979
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.0191354
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.0189135
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.0188399
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.0188959
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.018987
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.0191264
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.0190239
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.0189139
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.0188793
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.0188743
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.0188929
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.0191013
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.0192728
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.019429
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.0195938
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.019749
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.0199032
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.0199547
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.0198258
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.019684
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.0195895
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.0195594
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.0193642
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.0193696
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.0190535
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.0189528
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.0188593
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.0190474
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.0191007
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.0191578
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.0192177
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.0192579
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.0193034

Trening klas:  23%|██▎       | 116/500 [18:08<41:13,  6.44s/klasa, klasa=class_116, F1_klasy=0.8440, F1_macro=0.8290, drzewa=60]




Trening klas:  23%|██▎       | 117/500 [18:08<35:54,  5.63s/klasa, klasa=class_116, F1_klasy=0.8440, F1_macro=0.8290, drzewa=60]

[1]	valid_0's binary_logloss: 0.116495
[2]	valid_0's binary_logloss: 0.10947
[3]	valid_0's binary_logloss: 0.104582
[4]	valid_0's binary_logloss: 0.100681
[5]	valid_0's binary_logloss: 0.0979733
[6]	valid_0's binary_logloss: 0.0959835
[7]	valid_0's binary_logloss: 0.0941179
[8]	valid_0's binary_logloss: 0.0916674
[9]	valid_0's binary_logloss: 0.0900912
[10]	valid_0's binary_logloss: 0.088749
[11]	valid_0's binary_logloss: 0.0872468
[12]	valid_0's binary_logloss: 0.0857136
[13]	valid_0's binary_logloss: 0.0845604
[14]	valid_0's binary_logloss: 0.0833478
[15]	valid_0's binary_logloss: 0.0821049
[16]	valid_0's binary_logloss: 0.0810194
[17]	valid_0's binary_logloss: 0.0800134
[18]	valid_0's binary_logloss: 0.0791761
[19]	valid_0's binary_logloss: 0.0785772
[20]	valid_0's binary_logloss: 0.077862
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0769901
[22]	valid_0's binary_logloss: 0.0759358
[23]	valid_0's binary_logloss: 0.0754075
[24]	valid_0's binary_logloss: 0.0746611
[25]	valid_0's binary_logloss: 0.0741785
[26]	valid_0's binary_logloss: 0.0737699
[27]	valid_0's binary_logloss: 0.0733077
[28]	valid_0's binary_logloss: 0.0729835
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.0725017
[30]	valid_0's binary_logloss: 0.0722564
[31]	valid_0's binary_logloss: 0.0717876
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.0712394
[33]	valid_0's binary_logloss: 0.0710279
[34]	valid_0's binary_logloss: 0.0706236
[35]	valid_0's binary_logloss: 0.0703168
[36]	valid_0's binary_logloss: 0.0698567
[37]	valid_0's binary_logloss: 0.0696234
[38]	valid_0's binary_logloss: 0.06923
[39]	valid_0's binary_logloss: 0.0690103
[40]	valid_0's binary_logloss: 0.0687532
[41]	valid_0's binary_logloss: 0.068677
[42]	valid_0's binary_logloss: 0.0684838
[43]	valid_0's binary_logloss: 0.0681152
[44]	valid_0's binary_logloss: 0.0681596
[45]	valid_0's binary_logloss: 0.0679914
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.0680423
[47]	valid_0's binary_logloss: 0.067865
[48]	valid_0's binary_logloss: 0.0676327
[49]	valid_0's binary_logloss: 0.0675501
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.0674728
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.0673468
[52]	valid_0's binary_logloss: 0.0671945
[53]	valid_0's binary_logloss: 0.0669273
[54]	valid_0's binary_logloss: 0.0669084
[55]	valid_0's binary_logloss: 0.0669191
[56]	valid_0's binary_logloss: 0.0668106
[57]	valid_0's binary_logloss: 0.0667906
[58]	valid_0's binary_logloss: 0.0668046
[59]	valid_0's binary_logloss: 0.0669345
[60]	valid_0's binary_logloss: 0.0670588
[61]	valid_0's binary_logloss: 0.0670091
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.0671457
[63]	valid_0's binary_logloss: 0.0672556
[64]	valid_0's binary_logloss: 0.0672115
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.0671293
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.0671137
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.0673528
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.0675815
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.0678666
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.0679466
[71]	valid_0's binary_logloss: 0.067977
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.0680125
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.0680306
[74]	valid_0's binary_logloss: 0.0681044
[75]	valid_0's binary_logloss: 0.0680744
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.0680139
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.068014
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.0680168
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.0680031
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.0681556
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.0682072
[82]	valid_0's binary_logloss: 0.0681714
[83]	valid_0's binary_logloss: 0.0682139
[84]	valid_0's binary_logloss: 0.0681789
[85]	valid_0's binary_logloss: 0.0683677
[86]	valid_0's binary_logloss: 0.0685988
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

Trening klas:  23%|██▎       | 117/500 [18:13<35:54,  5.63s/klasa, klasa=class_117, F1_klasy=0.5199, F1_macro=0.8264, drzewa=57]




Trening klas:  24%|██▎       | 118/500 [18:13<35:45,  5.62s/klasa, klasa=class_117, F1_klasy=0.5199, F1_macro=0.8264, drzewa=57]

[87]	valid_0's binary_logloss: 0.0688049
[1]	valid_0's binary_logloss: 0.149792
[2]	valid_0's binary_logloss: 0.137039
[3]	valid_0's binary_logloss: 0.127741
[4]	valid_0's binary_logloss: 0.119744
[5]	valid_0's binary_logloss: 0.113236
[6]	valid_0's binary_logloss: 0.107547
[7]	valid_0's binary_logloss: 0.102544
[8]	valid_0's binary_logloss: 0.0987686
[9]	valid_0's binary_logloss: 0.0951839
[10]	valid_0's binary_logloss: 0.0919134
[11]	valid_0's binary_logloss: 0.0893503
[12]	valid_0's binary_logloss: 0.0869104
[13]	valid_0's binary_logloss: 0.0849105
[14]	valid_0's binary_logloss: 0.0824201
[15]	valid_0's binary_logloss: 0.0807608
[16]	valid_0's binary_logloss: 0.0787061
[17]	valid_0's binary_logloss: 0.0768992
[18]	valid_0's binary_logloss: 0.0753068
[19]	valid_0's binary_logloss: 0.0736969
[20]	valid_0's binary_logloss: 0.0723426
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0708946
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.069679
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.0686863
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0677136
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.066659
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.0660937
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.0652793
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.0643191
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.0637673
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.0632944
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.0629451
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.0624484
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.0620238
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.0617075
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.061492
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.0612045
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.060627
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.060189
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.0600564
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.0600602
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.0596569
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.0592043
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.0590971
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.0587343
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.0588462
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.0587037
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.0586016
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.0584978
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.0583376
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.0583222
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.0582772
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.0582575
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.0581654
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.0580546
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.0580615
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.0582553
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.0581953
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.0584231
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.0584832
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.0587892
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.0587303
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.0587973
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.0589906
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.0591188
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.0592123
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.0592042
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.0594814
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.0592971
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.0595843
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.0595602
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.0597341
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.0597137
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.0598216
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.0598442
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.0598885
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.0601088
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.0603678
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.0608132
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.0610764
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.0613149
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.061412
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.0615508
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.0618369
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

Trening klas:  24%|██▎       | 118/500 [18:17<35:45,  5.62s/klasa, klasa=class_118, F1_klasy=0.8417, F1_macro=0.8265, drzewa=54]




Trening klas:  24%|██▍       | 119/500 [18:17<32:46,  5.16s/klasa, klasa=class_118, F1_klasy=0.8417, F1_macro=0.8265, drzewa=54]

[84]	valid_0's binary_logloss: 0.0619545
[1]	valid_0's binary_logloss: 0.0404756
[2]	valid_0's binary_logloss: 0.0392145
[3]	valid_0's binary_logloss: 0.0381724
[4]	valid_0's binary_logloss: 0.0372014
[5]	valid_0's binary_logloss: 0.0364277
[6]	valid_0's binary_logloss: 0.036196
[7]	valid_0's binary_logloss: 0.0354013
[8]	valid_0's binary_logloss: 0.034621
[9]	valid_0's binary_logloss: 0.0336777
[10]	valid_0's binary_logloss: 0.0330379
[11]	valid_0's binary_logloss: 0.0324565
[12]	valid_0's binary_logloss: 0.0319089
[13]	valid_0's binary_logloss: 0.0313211
[14]	valid_0's binary_logloss: 0.0307419
[15]	valid_0's binary_logloss: 0.0302454
[16]	valid_0's binary_logloss: 0.0295991
[17]	valid_0's binary_logloss: 0.0290077
[18]	valid_0's binary_logloss: 0.0284027
[19]	valid_0's binary_logloss: 0.0279131
[20]	valid_0's binary_logloss: 0.0274611
[21]	valid_0's binary_logloss: 0.0269985
[22]	valid_0's binary_logloss: 0.0265427
[23]	valid_0's binary_logloss: 0.0260119
[24]	valid_0's binary_logloss: 0.0255102
[25]	valid_0's binary_logloss: 0.0250708
[26]	valid_0's binary_logloss: 0.0247027
[27]	valid_0's binary_logloss: 0.0243244
[28]	valid_0's binary_logloss: 0.02395
[29]	valid_0's binary_logloss: 0.0235864
[30]	valid_0's binary_logloss: 0.0232832
[31]	valid_0's binary_logloss: 0.0228955
[32]	valid_0's binary_logloss: 0.0225743
[33]	valid_0's binary_logloss: 0.0222768
[34]	valid_0's binary_logloss: 0.0220013
[35]	valid_0's binary_logloss: 0.0216826
[36]	valid_0's binary_logloss: 0.0214884
[37]	valid_0's binary_logloss: 0.0212293
[38]	valid_0's binary_logloss: 0.0210998
[39]	valid_0's binary_logloss: 0.0209872
[40]	valid_0's binary_logloss: 0.0208237
[41]	valid_0's binary_logloss: 0.0206881
[42]	valid_0's binary_logloss: 0.0205941
[43]	valid_0's binary_logloss: 0.0204818
[44]	valid_0's binary_logloss: 0.0203845
[45]	valid_0's binary_logloss: 0.0202682
[46]	valid_0's binary_logloss: 0.0201417
[47]	valid_0's binary_logloss: 0.0200119
[48]	valid_0's binary_logloss: 0.0198234
[49]	valid_0's binary_logloss: 0.0196719
[50]	valid_0's binary_logloss: 0.019609
[51]	valid_0's binary_logloss: 0.0194607
[52]	valid_0's binary_logloss: 0.0192912
[53]	valid_0's binary_logloss: 0.019232
[54]	valid_0's binary_logloss: 0.0190368
[55]	valid_0's binary_logloss: 0.0189346
[56]	valid_0's binary_logloss: 0.0188443
[57]	valid_0's binary_logloss: 0.0187599
[58]	valid_0's binary_logloss: 0.01868
[59]	valid_0's binary_logloss: 0.0185829
[60]	valid_0's binary_logloss: 0.018478
[61]	valid_0's binary_logloss: 0.0183672
[62]	valid_0's binary_logloss: 0.018316
[63]	valid_0's binary_logloss: 0.0183198
[64]	valid_0's binary_logloss: 0.018203
[65]	valid_0's binary_logloss: 0.0181324
[66]	valid_0's binary_logloss: 0.0180413
[67]	valid_0's binary_logloss: 0.01801
[68]	valid_0's binary_logloss: 0.0179919
[69]	valid_0's binary_logloss: 0.0180661
[70]	valid_0's binary_logloss: 0.0179925
[71]	valid_0's binary_logloss: 0.0178164
[72]	valid_0's binary_logloss: 0.0177491
[73]	valid_0's binary_logloss: 0.0176466
[74]	valid_0's binary_logloss: 0.0175448
[75]	valid_0's binary_logloss: 0.0174802
[76]	valid_0's binary_logloss: 0.0173401
[77]	valid_0's binary_logloss: 0.0171818
[78]	valid_0's binary_logloss: 0.0170614
[79]	valid_0's binary_logloss: 0.016997
[80]	valid_0's binary_logloss: 0.016879
[81]	valid_0's binary_logloss: 0.0168502
[82]	valid_0's binary_logloss: 0.0168531
[83]	valid_0's binary_logloss: 0.0169138
[84]	valid_0's binary_logloss: 0.016962
[85]	valid_0's binary_logloss: 0.0169388
[86]	valid_0's binary_logloss: 0.0168643
[87]	valid_0's binary_logloss: 0.0168885
[88]	valid_0's binary_logloss: 0.0168267
[89]	valid_0's binary_logloss: 0.0168139
[90]	valid_0's binary_logloss: 0.0168095
[91]	valid_0's binary_logloss: 0.0168364
[92]	valid_0's binary_logloss: 0.0167793
[93]	valid_0's binary_logloss: 0.0167709
[94]	valid_0's binary_logloss: 0.0167931
[95]	valid_0's binary_logloss: 0.0167693
[96]	valid_0's binary_logloss: 0.0167027
[97]	valid_0's binary_logloss: 0.0166559
[98]	valid_0's binary_logloss: 0.0166765
[99]	valid_0's binary_logloss: 0.0167018
[100]	valid_0's binary_logloss: 0.016642
[101]	valid_0's binary_logloss: 0.0166968
[102]	valid_0's binary_logloss: 0.0166852
[103]	valid_0's binary_logloss: 0.0166887
[104]	valid_0's binary_logloss: 0.0167017
[105]	valid_0's binary_logloss: 0.0166468
[106]	valid_0's binary_logloss: 0.0167413
[107]	valid_0's binary_logloss: 0.0166818
[108]	valid_0's binary_logloss: 0.016703
[109]	valid_0's binary_logloss: 0.0166866
[110]	valid_0's binary_logloss: 0.0166823
[111]	valid_0's binary_logloss: 0.0167304
[112]	valid_0's binary_logloss: 0.0167209
[113]	valid_0's binary_logloss: 0.0167434
[114]	valid_0's binary_logloss: 0.0167458
[115]	valid_0's binary_logloss: 0.0167018
[116]	valid_0's binary_logloss: 0.0167099
[117]	valid_0's binary_logloss: 0.0166992
[118]	valid_0's binary_logloss: 0.016758
[119]	valid_0's binary_logloss: 0.0167582
[120]	valid_0's binary_logloss: 0.0167434
[121]	valid_0's binary_logloss: 0.0167812
[122]	valid_0's binary_logloss: 0.0167941
[123]	valid_0's binary_logloss: 0.0168219
[124]	valid_0's binary_logloss: 0.0167938
[125]	valid_0's binary_logloss: 0.016822
[126]	valid_0's binary_logloss: 0.0168401
[127]	valid_0's binary_logloss: 0.0168842

Trening klas:  24%|██▍       | 119/500 [18:27<32:46,  5.16s/klasa, klasa=class_119, F1_klasy=0.4091, F1_macro=0.8231, drzewa=100]




Trening klas:  24%|██▍       | 120/500 [18:27<40:41,  6.42s/klasa, klasa=class_119, F1_klasy=0.4091, F1_macro=0.8231, drzewa=100]

[128]	valid_0's binary_logloss: 0.0168798
[129]	valid_0's binary_logloss: 0.01691
[130]	valid_0's binary_logloss: 0.0169336
[1]	valid_0's binary_logloss: 0.0850865
[2]	valid_0's binary_logloss: 0.0770975
[3]	valid_0's binary_logloss: 0.0712195
[4]	valid_0's binary_logloss: 0.0668474
[5]	valid_0's binary_logloss: 0.0633641
[6]	valid_0's binary_logloss: 0.0604107
[7]	valid_0's binary_logloss: 0.0574683
[8]	valid_0's binary_logloss: 0.0549408
[9]	valid_0's binary_logloss: 0.0529317
[10]	valid_0's binary_logloss: 0.051196
[11]	valid_0's binary_logloss: 0.0493986
[12]	valid_0's binary_logloss: 0.0477811
[13]	valid_0's binary_logloss: 0.0463153
[14]	valid_0's binary_logloss: 0.045054
[15]	valid_0's binary_logloss: 0.0437932
[16]	valid_0's binary_logloss: 0.0429037
[17]	valid_0's binary_logloss: 0.0419856
[18]	valid_0's binary_logloss: 0.0411596
[19]	valid_0's binary_logloss: 0.0403189
[20]	valid_0's binary_logloss: 0.039716
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0389879
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0383002
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.0375883
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0370634
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.0366201
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.0359312
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.0352942
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.0347624
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.0342886
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.0339186
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.033642
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.0333859
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.0331738
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.0328127
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.0325118
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.0324454
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.0324133
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.0324255
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.0323967
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.0323655
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.0321111
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.0317812
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.0316545
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.0314141
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.0310966
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.031086
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.0310506
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.0310394
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.0310149
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.0310027
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.030896
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.0306512
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.0306697
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.0307208
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.0306092
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.030597
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.0305134
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.0305213
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.0305845
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.0307076
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.0303895
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.0302489
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.0301278
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.0300078
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.0298376
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.029746
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.0296581
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.029595
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.029594
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.0294801
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.0293063
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.0292589
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.0292349
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.0292603
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.0292845
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.0292042
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.0291395
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.0291019
[79]	valid_0's binary_logloss: 0.0290443
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.0290716
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.0292258
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.0294376
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.0295703
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.029696
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.0296601
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.0296257
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.0297558
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.0299221
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.0300555
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.0300813
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.0301876
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.0302399
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.0303253
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.0304501
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.0305055
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.0305654
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.0306886
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.0307882
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.0309396
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.0311016
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.0311277
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.0311215
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.0311398
[104]	valid_0's binary_logloss: 0.0310089
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.0310238
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.0310126
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

Trening klas:  24%|██▍       | 120/500 [18:32<40:41,  6.42s/klasa, klasa=class_120, F1_klasy=0.7967, F1_macro=0.8228, drzewa=79]




Trening klas:  24%|██▍       | 121/500 [18:32<38:54,  6.16s/klasa, klasa=class_120, F1_klasy=0.7967, F1_macro=0.8228, drzewa=79]

[107]	valid_0's binary_logloss: 0.0309615
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.0309481
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.0309222
[1]	valid_0's binary_logloss: 0.135474
[2]	valid_0's binary_logloss: 0.13798
[3]	valid_0's binary_logloss: 0.141655
[4]	valid_0's binary_logloss: 0.145051
[5]	valid_0's binary_logloss: 0.149823
[6]	valid_0's binary_logloss: 0.15342
[7]	valid_0's binary_logloss: 0.156179
[8]	valid_0's binary_logloss: 0.160441
[9]	valid_0's binary_logloss: 0.163383
[10]	valid_0's binary_logloss: 0.165575
[11]	valid_0's binary_logloss: 0.169101
[12]	valid_0's binary_logloss: 0.17178
[13]	valid_0's binary_logloss: 0.175795
[14]	valid_0's binary_logloss: 0.179238
[15]	valid_0's binary_logloss: 0.183192
[16]	valid_0's binary_logloss: 0.187006
[17]	valid_0's binary_logloss: 0.190833
[18]	valid_0's binary_logloss: 0.194797
[19]	valid_0's binary_logloss: 0.198324
[20]	valid_0's binary_logloss: 0.202587
[21]	valid_0's binary_logloss: 0.204595
[22]	valid_0's binary_logloss: 0.208238
[23]	valid_0's binary_logloss: 0.210693
[24]	valid_0's binary_logloss: 0.212328
[25]	valid_0's binary_logloss: 0.212554
[26]	valid_0's binary_logloss: 0.214656
[27]	valid_0's binary_logloss: 0.217294
[28]	valid_0's binary_logloss: 0.219013
[29]	valid_0's binary_logloss: 0.222022
[30]	valid_0's binary_logloss: 0.223752
[31]	valid_0's binary_logloss: 0.22433

Trening klas:  24%|██▍       | 121/500 [18:37<38:54,  6.16s/klasa, klasa=class_121, F1_klasy=0.0000, F1_macro=0.8161, drzewa=1]




Trening klas:  24%|██▍       | 122/500 [18:37<35:17,  5.60s/klasa, klasa=class_121, F1_klasy=0.0000, F1_macro=0.8161, drzewa=1]

[1]	valid_0's binary_logloss: 0.0401243
[2]	valid_0's binary_logloss: 0.0388127
[3]	valid_0's binary_logloss: 0.0378718
[4]	valid_0's binary_logloss: 0.0369541
[5]	valid_0's binary_logloss: 0.0360967
[6]	valid_0's binary_logloss: 0.0357246
[7]	valid_0's binary_logloss: 0.0349817
[8]	valid_0's binary_logloss: 0.0340699
[9]	valid_0's binary_logloss: 0.0333186
[10]	valid_0's binary_logloss: 0.0326389
[11]	valid_0's binary_logloss: 0.0321665
[12]	valid_0's binary_logloss: 0.0316544
[13]	valid_0's binary_logloss: 0.03115
[14]	valid_0's binary_logloss: 0.0304975
[15]	valid_0's binary_logloss: 0.0299322
[16]	valid_0's binary_logloss: 0.0292676
[17]	valid_0's binary_logloss: 0.0286153
[18]	valid_0's binary_logloss: 0.0280947
[19]	valid_0's binary_logloss: 0.027622
[20]	valid_0's binary_logloss: 0.0271445
[21]	valid_0's binary_logloss: 0.0266094
[22]	valid_0's binary_logloss: 0.0261452
[23]	valid_0's binary_logloss: 0.0255655
[24]	valid_0's binary_logloss: 0.0250388
[25]	valid_0's binary_logloss: 0.0245258
[26]	valid_0's binary_logloss: 0.0240893
[27]	valid_0's binary_logloss: 0.0236938
[28]	valid_0's binary_logloss: 0.0233539
[29]	valid_0's binary_logloss: 0.0230598
[30]	valid_0's binary_logloss: 0.0227509
[31]	valid_0's binary_logloss: 0.0223407
[32]	valid_0's binary_logloss: 0.0219868
[33]	valid_0's binary_logloss: 0.021663
[34]	valid_0's binary_logloss: 0.0213231
[35]	valid_0's binary_logloss: 0.0210139
[36]	valid_0's binary_logloss: 0.0208077
[37]	valid_0's binary_logloss: 0.020633
[38]	valid_0's binary_logloss: 0.0203745
[39]	valid_0's binary_logloss: 0.0202825
[40]	valid_0's binary_logloss: 0.0201271
[41]	valid_0's binary_logloss: 0.0199527
[42]	valid_0's binary_logloss: 0.0198343
[43]	valid_0's binary_logloss: 0.0197331
[44]	valid_0's binary_logloss: 0.0196153
[45]	valid_0's binary_logloss: 0.019463
[46]	valid_0's binary_logloss: 0.0193539
[47]	valid_0's binary_logloss: 0.0191723
[48]	valid_0's binary_logloss: 0.0190546
[49]	valid_0's binary_logloss: 0.0189882
[50]	valid_0's binary_logloss: 0.0188862
[51]	valid_0's binary_logloss: 0.0186859
[52]	valid_0's binary_logloss: 0.0184558
[53]	valid_0's binary_logloss: 0.0183555
[54]	valid_0's binary_logloss: 0.0181981
[55]	valid_0's binary_logloss: 0.0180042
[56]	valid_0's binary_logloss: 0.0178969
[57]	valid_0's binary_logloss: 0.017862
[58]	valid_0's binary_logloss: 0.0177928
[59]	valid_0's binary_logloss: 0.0177512
[60]	valid_0's binary_logloss: 0.0175625
[61]	valid_0's binary_logloss: 0.0174449
[62]	valid_0's binary_logloss: 0.0174227
[63]	valid_0's binary_logloss: 0.0173094
[64]	valid_0's binary_logloss: 0.0171726
[65]	valid_0's binary_logloss: 0.0171032
[66]	valid_0's binary_logloss: 0.0170657
[67]	valid_0's binary_logloss: 0.0170037
[68]	valid_0's binary_logloss: 0.0169824
[69]	valid_0's binary_logloss: 0.0169537
[70]	valid_0's binary_logloss: 0.016925
[71]	valid_0's binary_logloss: 0.0168421
[72]	valid_0's binary_logloss: 0.0167578
[73]	valid_0's binary_logloss: 0.0166845
[74]	valid_0's binary_logloss: 0.0165918
[75]	valid_0's binary_logloss: 0.0165502
[76]	valid_0's binary_logloss: 0.016386
[77]	valid_0's binary_logloss: 0.0162486
[78]	valid_0's binary_logloss: 0.01621
[79]	valid_0's binary_logloss: 0.0160922
[80]	valid_0's binary_logloss: 0.0160302
[81]	valid_0's binary_logloss: 0.015991
[82]	valid_0's binary_logloss: 0.0159715
[83]	valid_0's binary_logloss: 0.0159761
[84]	valid_0's binary_logloss: 0.0159612
[85]	valid_0's binary_logloss: 0.0158947
[86]	valid_0's binary_logloss: 0.0158674
[87]	valid_0's binary_logloss: 0.0158703
[88]	valid_0's binary_logloss: 0.0158578
[89]	valid_0's binary_logloss: 0.0157748
[90]	valid_0's binary_logloss: 0.0157978
[91]	valid_0's binary_logloss: 0.0158575
[92]	valid_0's binary_logloss: 0.0158564
[93]	valid_0's binary_logloss: 0.0158773
[94]	valid_0's binary_logloss: 0.0159378
[95]	valid_0's binary_logloss: 0.0159777
[96]	valid_0's binary_logloss: 0.0159651
[97]	valid_0's binary_logloss: 0.0159543
[98]	valid_0's binary_logloss: 0.0159746
[99]	valid_0's binary_logloss: 0.0159398
[100]	valid_0's binary_logloss: 0.0159058
[101]	valid_0's binary_logloss: 0.0158658
[102]	valid_0's binary_logloss: 0.0158532
[103]	valid_0's binary_logloss: 0.0157842
[104]	valid_0's binary_logloss: 0.0157485
[105]	valid_0's binary_logloss: 0.0156932
[106]	valid_0's binary_logloss: 0.0157428
[107]	valid_0's binary_logloss: 0.0157328
[108]	valid_0's binary_logloss: 0.0157974
[109]	valid_0's binary_logloss: 0.0158319
[110]	valid_0's binary_logloss: 0.0158166
[111]	valid_0's binary_logloss: 0.015784
[112]	valid_0's binary_logloss: 0.0157806
[113]	valid_0's binary_logloss: 0.0158182
[114]	valid_0's binary_logloss: 0.0158303
[115]	valid_0's binary_logloss: 0.0158133
[116]	valid_0's binary_logloss: 0.0158992
[117]	valid_0's binary_logloss: 0.0159087
[118]	valid_0's binary_logloss: 0.0159597
[119]	valid_0's binary_logloss: 0.0159106
[120]	valid_0's binary_logloss: 0.0159233
[121]	valid_0's binary_logloss: 0.0159574
[122]	valid_0's binary_logloss: 0.0159651
[123]	valid_0's binary_logloss: 0.0159699
[124]	valid_0's binary_logloss: 0.0159417
[125]	valid_0's binary_logloss: 0.0159438
[126]	valid_0's binary_logloss: 0.01599
[127]	valid_0's binary_logloss: 0.0160472
[128]	valid_0's binary_logloss: 0.0160499
[129]	valid_0's binary_logloss: 0.0160516
[130]	valid_0's binary_logloss: 0.0161308
[131]	valid_0's binary_logloss: 0.0160525
[132]	valid_0's binary_logloss: 0.0160068
[133]	valid_0's binary_logloss: 0.0160371
[134]	valid_0's binary_logloss: 0.0159956

Trening klas:  24%|██▍       | 122/500 [18:47<35:17,  5.60s/klasa, klasa=class_122, F1_klasy=0.3673, F1_macro=0.8125, drzewa=105]




Trening klas:  25%|██▍       | 123/500 [18:47<43:34,  6.94s/klasa, klasa=class_122, F1_klasy=0.3673, F1_macro=0.8125, drzewa=105]

[135]	valid_0's binary_logloss: 0.0160063
[1]	valid_0's binary_logloss: 0.0382935
[2]	valid_0's binary_logloss: 0.0366429
[3]	valid_0's binary_logloss: 0.0350097
[4]	valid_0's binary_logloss: 0.0336173
[5]	valid_0's binary_logloss: 0.0322939
[6]	valid_0's binary_logloss: 0.0312646
[7]	valid_0's binary_logloss: 0.0302196
[8]	valid_0's binary_logloss: 0.0291639
[9]	valid_0's binary_logloss: 0.0280532
[10]	valid_0's binary_logloss: 0.0270627
[11]	valid_0's binary_logloss: 0.0261128
[12]	valid_0's binary_logloss: 0.0251692
[13]	valid_0's binary_logloss: 0.0242874
[14]	valid_0's binary_logloss: 0.023461
[15]	valid_0's binary_logloss: 0.0226806
[16]	valid_0's binary_logloss: 0.0219255
[17]	valid_0's binary_logloss: 0.0211886
[18]	valid_0's binary_logloss: 0.0204694
[19]	valid_0's binary_logloss: 0.0198145
[20]	valid_0's binary_logloss: 0.0191855
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0185659
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0180004
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.0174523
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0169557
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.016481
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.0160187
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.0155876
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.0151771
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.0148022
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.0144295
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.014043
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.0136797
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.0133773
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.0131014
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.0128473
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.0125813
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.0123512
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.0121428
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.011933
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.0116968
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.011485
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.0112866
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.0111269
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.010947
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.0108058
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.0106494
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.0105312
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.0104197
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.0103173
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.0102252
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.0101438
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.0100712
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.00995283
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.00989725
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.00981212
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.00972679
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.00965564
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.00959164
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.00953628
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.00947524
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.00943591
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.00936096
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.00933504
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.00927125
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.00919911
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.00916874
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.00916382
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.00913907
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.00915539
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.00916837
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.00916577
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.00916974
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.00917418
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.0091945
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.00921949
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.0092391
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.00925074
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.00925599
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.0092741
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.00929676
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.00931961
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.00934282
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.00936779
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.00939338
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.00941674
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.0094455
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.00946136
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.00947561
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.00951379
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.00954671
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.00956655
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.0096132
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.00966993
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

Trening klas:  25%|██▍       | 123/500 [18:52<43:34,  6.94s/klasa, klasa=class_123, F1_klasy=0.0000, F1_macro=0.8059, drzewa=68]




Trening klas:  25%|██▍       | 124/500 [18:52<39:47,  6.35s/klasa, klasa=class_123, F1_klasy=0.0000, F1_macro=0.8059, drzewa=68]

[94]	valid_0's binary_logloss: 0.00971986
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.00975535
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.00979648
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.00981737
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.00985213
[1]	valid_0's binary_logloss: 0.0378524
[2]	valid_0's binary_logloss: 0.035534
[3]	valid_0's binary_logloss: 0.0335517
[4]	valid_0's binary_logloss: 0.0318142
[5]	valid_0's binary_logloss: 0.0301606
[6]	valid_0's binary_logloss: 0.0286353
[7]	valid_0's binary_logloss: 0.0272897
[8]	valid_0's binary_logloss: 0.0259489
[9]	valid_0's binary_logloss: 0.0246977
[10]	valid_0's binary_logloss: 0.0235274
[11]	valid_0's binary_logloss: 0.0224745
[12]	valid_0's binary_logloss: 0.0214356
[13]	valid_0's binary_logloss: 0.0204688
[14]	valid_0's binary_logloss: 0.0195567
[15]	valid_0's binary_logloss: 0.0186757
[16]	valid_0's binary_logloss: 0.0178195
[17]	valid_0's binary_logloss: 0.0170379
[18]	valid_0's binary_logloss: 0.0162947
[19]	valid_0's binary_logloss: 0.0155755
[20]	valid_0's binary_logloss: 0.0148938
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0142675
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0136749
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.0130948
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.012575
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.0120444
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.0115536
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.0110979
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.0106729
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.0102974
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.00992352
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.0095755
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.00924835
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.00891251
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.00860014
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.00832517
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.00803436
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.00776456
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.007517
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.00727375
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.00704953
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.00682929
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.00662975
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.00645384
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.00626861
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.00609072
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.0059214
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.00576034
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.00560883
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.00547359
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.00534549
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.00522498
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.00510967
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.00499416
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.00490414
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.00480813
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.00466944
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.00457795
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.00450733
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.00443268
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.00437118
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.0042992
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.0042308
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.00413021
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.00408296
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.00400633
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.00396332
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.00393088
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.00389061
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.00385685
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.00382199
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.00379428
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.00376392
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.00369139
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.00366894
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.00365229
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.00361608
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.00359723
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.0035877
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.003539
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.00353728
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.0035223
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.00351417
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.00348878
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.00348462
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.00347782
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.00345876
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.00345893
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.00346884
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.00347437
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.00347384
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.00349117
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.0034979
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.0035097
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.00350457
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.00351569
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.00352435
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.00351356
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.00349408
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.00350531
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.00350569
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.00351075
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.00350541
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.00350875
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.00351265
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.00350922
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.00353467
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.00355694
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.00353723
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.00351028
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.00353717
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.00354668
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 0.00355767
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 0.00357533
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

Trening klas:  25%|██▍       | 124/500 [18:56<39:47,  6.35s/klasa, klasa=class_124, F1_klasy=0.8889, F1_macro=0.8066, drzewa=86]




Trening klas:  25%|██▌       | 125/500 [18:56<35:23,  5.66s/klasa, klasa=class_124, F1_klasy=0.8889, F1_macro=0.8066, drzewa=86]

[114]	valid_0's binary_logloss: 0.0035877
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 0.00361925
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[116]	valid_0's binary_logloss: 0.00363386
[1]	valid_0's binary_logloss: 0.165725
[2]	valid_0's binary_logloss: 0.156304
[3]	valid_0's binary_logloss: 0.149234
[4]	valid_0's binary_logloss: 0.143261
[5]	valid_0's binary_logloss: 0.13932
[6]	valid_0's binary_logloss: 0.135996
[7]	valid_0's binary_logloss: 0.132944
[8]	valid_0's binary_logloss: 0.130805
[9]	valid_0's binary_logloss: 0.128349
[10]	valid_0's binary_logloss: 0.126288
[11]	valid_0's binary_logloss: 0.124515
[12]	valid_0's binary_logloss: 0.123071
[13]	valid_0's binary_logloss: 0.121455
[14]	valid_0's binary_logloss: 0.119957
[15]	valid_0's binary_logloss: 0.118875
[16]	valid_0's binary_logloss: 0.117477
[17]	valid_0's binary_logloss: 0.116331
[18]	valid_0's binary_logloss: 0.115453
[19]	valid_0's binary_logloss: 0.114588
[20]	valid_0's binary_logloss: 0.113864
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.113193
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.112135
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.111714
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.111298
[25]	valid_0's binary_logloss: 0.110657
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.109852
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.109262
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.108965
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.108502
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.108002
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.107597
[32]	valid_0's binary_logloss: 0.107205
[33]	valid_0's binary_logloss: 0.107297
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.107235
[35]	valid_0's binary_logloss: 0.107294
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.107103
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.107162
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.107231
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.107233
[40]	valid_0's binary_logloss: 0.107319
[41]	valid_0's binary_logloss: 0.107498
[42]	valid_0's binary_logloss: 0.107393
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.107779
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.10806
[45]	valid_0's binary_logloss: 0.108208
[46]	valid_0's binary_logloss: 0.108563
[47]	valid_0's binary_logloss: 0.109014
[48]	valid_0's binary_logloss: 0.108937
[49]	valid_0's binary_logloss: 0.108873
[50]	valid_0's binary_logloss: 0.109436
[51]	valid_0's binary_logloss: 0.109742
[52]	valid_0's binary_logloss: 0.10958
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.109439
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.109352
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.109403
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.109849
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.110244
[58]	valid_0's binary_logloss: 0.110622
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.11068
[60]	valid_0's binary_logloss: 0.110988
[61]	valid_0's binary_logloss: 0.111391
[62]	valid_0's binary_logloss: 0.111961
[63]	valid_0's binary_logloss: 0.112428
[64]	valid_0's binary_logloss: 0.112789
[65]	valid_0's binary_logloss: 0.112983
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.113092

Trening klas:  25%|██▌       | 125/500 [19:00<35:23,  5.66s/klasa, klasa=class_125, F1_klasy=0.6191, F1_macro=0.8051, drzewa=36]




Trening klas:  25%|██▌       | 126/500 [19:00<31:58,  5.13s/klasa, klasa=class_125, F1_klasy=0.6191, F1_macro=0.8051, drzewa=36]

[1]	valid_0's binary_logloss: 0.0909133
[2]	valid_0's binary_logloss: 0.0834562
[3]	valid_0's binary_logloss: 0.0776216
[4]	valid_0's binary_logloss: 0.0727517
[5]	valid_0's binary_logloss: 0.0689797
[6]	valid_0's binary_logloss: 0.0658071
[7]	valid_0's binary_logloss: 0.0631378
[8]	valid_0's binary_logloss: 0.0605486
[9]	valid_0's binary_logloss: 0.0583573
[10]	valid_0's binary_logloss: 0.0566036
[11]	valid_0's binary_logloss: 0.054956
[12]	valid_0's binary_logloss: 0.0534053
[13]	valid_0's binary_logloss: 0.0520867
[14]	valid_0's binary_logloss: 0.0507851
[15]	valid_0's binary_logloss: 0.0496882
[16]	valid_0's binary_logloss: 0.0485864
[17]	valid_0's binary_logloss: 0.0476062
[18]	valid_0's binary_logloss: 0.0467137
[19]	valid_0's binary_logloss: 0.0459218
[20]	valid_0's binary_logloss: 0.0449338
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0442455
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0434647
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.0429541
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0424233
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.041873
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.0414101
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.0407254
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.0404532
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.0401957
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.0398633
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.0394563
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.0391964
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.0388919
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.0386512
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.038242
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.0377603
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.037297
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.0369718
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.0369168
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.0368238
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.0363882
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.0361084
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.0358478
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.0356761
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.035442
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.0351623
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.0349506
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.0347435
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.0346416
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.0344589
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.0345201
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.0345561
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.0345793
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.0343475
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.0344541
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.0343621
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.0342233
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.0340791
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.033883
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.0336967
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.0333742
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.0330611
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.0329964
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.0328437
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.0326491
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.0325992
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.0324744
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.0323261
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.0322579
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.0321278
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.0320191
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.0318405
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.031448
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.0313091
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.0313367
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.0313433
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.0313498
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.0314338
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.0313439
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.0314298
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.0312521
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.0311337
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.0309082
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.0309223
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.0309719
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.0309357
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.0310219
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.0311423
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.0309912
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.0307816
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.0309054
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.0310614
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.0311573
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.0312652
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.031347
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.0313737
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.0313804
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.031452
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.0314237
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.0314643
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.031505
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.0314127
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.031578
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.0313465
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.0312315
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.0311967
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.0312566
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.0312957
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.031222
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.0312426
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.031224
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 0.0311874
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 0.0311016
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 0.0312217
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 0.0311728
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[116]	valid_0's binary_logloss: 0.0311919
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[117]	valid_0's binary_logloss: 0.0313295
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[118]	valid_0's binary_logloss: 0.0312632
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[119]	valid_0's binary_logloss: 0.0313643
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

Trening klas:  25%|██▌       | 126/500 [19:04<31:58,  5.13s/klasa, klasa=class_126, F1_klasy=0.8344, F1_macro=0.8053, drzewa=90]




Trening klas:  25%|██▌       | 127/500 [19:04<30:25,  4.89s/klasa, klasa=class_126, F1_klasy=0.8344, F1_macro=0.8053, drzewa=90]

[120]	valid_0's binary_logloss: 0.0313989
[1]	valid_0's binary_logloss: 0.165725
[2]	valid_0's binary_logloss: 0.156304
[3]	valid_0's binary_logloss: 0.149234
[4]	valid_0's binary_logloss: 0.143261
[5]	valid_0's binary_logloss: 0.13932
[6]	valid_0's binary_logloss: 0.135996
[7]	valid_0's binary_logloss: 0.132944
[8]	valid_0's binary_logloss: 0.130805
[9]	valid_0's binary_logloss: 0.128349
[10]	valid_0's binary_logloss: 0.126288
[11]	valid_0's binary_logloss: 0.124515
[12]	valid_0's binary_logloss: 0.123071
[13]	valid_0's binary_logloss: 0.121455
[14]	valid_0's binary_logloss: 0.119957
[15]	valid_0's binary_logloss: 0.118875
[16]	valid_0's binary_logloss: 0.117477
[17]	valid_0's binary_logloss: 0.116331
[18]	valid_0's binary_logloss: 0.115453
[19]	valid_0's binary_logloss: 0.114588
[20]	valid_0's binary_logloss: 0.113864
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.113193
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.112135
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.111714
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.111298
[25]	valid_0's binary_logloss: 0.110657
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.109852
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.109262
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.108965
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.108502
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.108002
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.107597
[32]	valid_0's binary_logloss: 0.107205
[33]	valid_0's binary_logloss: 0.107297
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.107235
[35]	valid_0's binary_logloss: 0.107294
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.107103
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.107162
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.107231
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.107233
[40]	valid_0's binary_logloss: 0.107319
[41]	valid_0's binary_logloss: 0.107498
[42]	valid_0's binary_logloss: 0.107393
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.107779
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.10806
[45]	valid_0's binary_logloss: 0.108208
[46]	valid_0's binary_logloss: 0.108563
[47]	valid_0's binary_logloss: 0.109014
[48]	valid_0's binary_logloss: 0.108937
[49]	valid_0's binary_logloss: 0.108873
[50]	valid_0's binary_logloss: 0.109436
[51]	valid_0's binary_logloss: 0.109742
[52]	valid_0's binary_logloss: 0.10958
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.109439
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.109352
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.109403
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.109849
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.110244
[58]	valid_0's binary_logloss: 0.110622
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.11068
[60]	valid_0's binary_logloss: 0.110988
[61]	valid_0's binary_logloss: 0.111391
[62]	valid_0's binary_logloss: 0.111961
[63]	valid_0's binary_logloss: 0.112428
[64]	valid_0's binary_logloss: 0.112789
[65]	valid_0's binary_logloss: 0.112983
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.113092

Trening klas:  25%|██▌       | 127/500 [19:08<30:25,  4.89s/klasa, klasa=class_127, F1_klasy=0.6191, F1_macro=0.8039, drzewa=36]




Trening klas:  26%|██▌       | 128/500 [19:08<28:25,  4.58s/klasa, klasa=class_127, F1_klasy=0.6191, F1_macro=0.8039, drzewa=36]

[1]	valid_0's binary_logloss: 0.0725356
[2]	valid_0's binary_logloss: 0.0669587
[3]	valid_0's binary_logloss: 0.0629227
[4]	valid_0's binary_logloss: 0.059746
[5]	valid_0's binary_logloss: 0.056823
[6]	valid_0's binary_logloss: 0.0546593
[7]	valid_0's binary_logloss: 0.0524787
[8]	valid_0's binary_logloss: 0.0504446
[9]	valid_0's binary_logloss: 0.0486855
[10]	valid_0's binary_logloss: 0.0471233
[11]	valid_0's binary_logloss: 0.0457896
[12]	valid_0's binary_logloss: 0.0447475
[13]	valid_0's binary_logloss: 0.0438829
[14]	valid_0's binary_logloss: 0.0432962
[15]	valid_0's binary_logloss: 0.0424812
[16]	valid_0's binary_logloss: 0.04159
[17]	valid_0's binary_logloss: 0.0411492
[18]	valid_0's binary_logloss: 0.0403369
[19]	valid_0's binary_logloss: 0.0395782
[20]	valid_0's binary_logloss: 0.0389281
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0382871
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0379255
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.0375634
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0372346
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.0364887
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.0361959
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.0358505
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.0354022
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.0351181
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.0346344
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.0343538
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.0340642
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.0338371
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.0335559
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.0333751
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.0331631
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.0329389
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.032327
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.0319437
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.031687
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.0315173
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.0310756
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.0308066
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.0306062
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.0303255
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.0298184
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.0293865
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.0290762
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.0289151
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.0289743
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.0285579
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.0281734
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.0281459
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.0276757
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.0273229
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.0275188
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.0275387
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.0275693
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.0276915
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.0278691
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.0279775
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.0280887
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.0281152
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.0278257
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.0280526
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.0276971
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.0275304
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.0272791
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.0271036
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.0269565
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.0269406
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.0269578
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.0268735
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.0269471
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.0269266
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.0270582
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.0270472
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.0271115
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.0272263
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.0272265
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.0274289
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.027515
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.0276882
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.0278524
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.0280057
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.0278663
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.0279277
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.028034
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.0281702
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.0280238
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.0281618
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.0280883
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.0280059
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.0279038
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.0280777
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.028009
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.0279659
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.0279606
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.028003
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.0279967
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.0278977
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.0276323
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

Trening klas:  26%|██▌       | 128/500 [19:12<28:25,  4.58s/klasa, klasa=class_128, F1_klasy=0.7629, F1_macro=0.8035, drzewa=73]




Trening klas:  26%|██▌       | 129/500 [19:12<27:32,  4.46s/klasa, klasa=class_128, F1_klasy=0.7629, F1_macro=0.8035, drzewa=73]

[103]	valid_0's binary_logloss: 0.0275793
[1]	valid_0's binary_logloss: 0.0714603
[2]	valid_0's binary_logloss: 0.0658683
[3]	valid_0's binary_logloss: 0.061861
[4]	valid_0's binary_logloss: 0.0586692
[5]	valid_0's binary_logloss: 0.0557308
[6]	valid_0's binary_logloss: 0.0535519
[7]	valid_0's binary_logloss: 0.0513845
[8]	valid_0's binary_logloss: 0.0493613
[9]	valid_0's binary_logloss: 0.0476123
[10]	valid_0's binary_logloss: 0.0460589
[11]	valid_0's binary_logloss: 0.0447159
[12]	valid_0's binary_logloss: 0.0436589
[13]	valid_0's binary_logloss: 0.0428004
[14]	valid_0's binary_logloss: 0.0421988
[15]	valid_0's binary_logloss: 0.0413687
[16]	valid_0's binary_logloss: 0.0404626
[17]	valid_0's binary_logloss: 0.0400072
[18]	valid_0's binary_logloss: 0.03918
[19]	valid_0's binary_logloss: 0.0384061
[20]	valid_0's binary_logloss: 0.0377411
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.037103
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0367444
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.0363674
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0360238
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.0352974
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.0349888
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.0346277
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.0341814
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.0338817
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.0333825
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.0331036
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.0327983
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.0325563
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.0322764
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.0320969
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.0318861
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.0316625
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.0310357
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.0306673
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.0304138
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.0302285
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.0298029
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.029549
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.0293639
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.0290993
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.0285889
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.0281573
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.0278475
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.0276925
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.0277645
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.027363
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.0269939
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.0269515
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.0264957
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.0261409
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.0263221
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.0263407
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.0263714
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.0264782
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.0266551
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.0267486
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.026845
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.0268807
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.0265763
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.0267883
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.0264183
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.0262445
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.0259785
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.0258002
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.0256512
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.0255932
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.0256104
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.0255257
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.0255961
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.0255715
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.0256883
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.0256624
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.0257119
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.0258293
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.0258361
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.0260384
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.0261221
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.0263056
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.0264827
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.0266511
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.026522
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.0265667
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.0266813
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.0268228
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.0266915
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.0268156
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.026749
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.0266464
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.0265255
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.0267047
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.0266339
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.0265802
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.0265892
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

Trening klas:  26%|██▌       | 129/500 [19:16<27:32,  4.46s/klasa, klasa=class_129, F1_klasy=0.7682, F1_macro=0.8033, drzewa=73]




Trening klas:  26%|██▌       | 130/500 [19:16<26:48,  4.35s/klasa, klasa=class_129, F1_klasy=0.7682, F1_macro=0.8033, drzewa=73]

[99]	valid_0's binary_logloss: 0.0266454
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.0266513
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.0265415
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.0262703
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.0262153
[1]	valid_0's binary_logloss: 0.131783
[2]	valid_0's binary_logloss: 0.122978
[3]	valid_0's binary_logloss: 0.117204
[4]	valid_0's binary_logloss: 0.111845
[5]	valid_0's binary_logloss: 0.107598
[6]	valid_0's binary_logloss: 0.105148
[7]	valid_0's binary_logloss: 0.101994
[8]	valid_0's binary_logloss: 0.0989974
[9]	valid_0's binary_logloss: 0.0961144
[10]	valid_0's binary_logloss: 0.093949
[11]	valid_0's binary_logloss: 0.0919097
[12]	valid_0's binary_logloss: 0.0905204
[13]	valid_0's binary_logloss: 0.0887832
[14]	valid_0's binary_logloss: 0.0872207
[15]	valid_0's binary_logloss: 0.0861265
[16]	valid_0's binary_logloss: 0.0850073
[17]	valid_0's binary_logloss: 0.0837743
[18]	valid_0's binary_logloss: 0.0828653
[19]	valid_0's binary_logloss: 0.0818876
[20]	valid_0's binary_logloss: 0.0810052
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0803197
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0796719
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.0792243
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0785085
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.0780655
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.0772983
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.0768512
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.0762743
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.0757046
[30]	valid_0's binary_logloss: 0.0752512
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.0747858
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.0744195
[33]	valid_0's binary_logloss: 0.0740302
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.073839
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.0735278
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.0732269
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.072982
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.0727381
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.0725835
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.0723665
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.0722389
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.0721287
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.0721005
[44]	valid_0's binary_logloss: 0.0720015
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.0717698
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.0716472
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.0715224
[48]	valid_0's binary_logloss: 0.0715578
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.0714141
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.0712186
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.071001
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.071019
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.070961
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.0709708
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.0709453
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.070914
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.0709211
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.0709688
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.0708998
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.0708823
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.0709162
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.0710277
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.0710004
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.0710117
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.0709976
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.0709658
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.071092
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.0711541
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.0713033
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.0711526
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.0713292
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.0714825
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.0715511
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.0716921
[75]	valid_0's binary_logloss: 0.0719593
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.0721527
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.0722149
[78]	valid_0's binary_logloss: 0.072301
[79]	valid_0's binary_logloss: 0.072331
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.0723724
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.0726046
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.0727165
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.0728142
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.0730574
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.0731441
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.073474
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.0736651
[88]	valid_0's binary_logloss: 0.0738833
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.0739429
[90]	valid_0's binary_logloss: 0.0742153

Trening klas:  26%|██▌       | 130/500 [19:22<26:48,  4.35s/klasa, klasa=class_130, F1_klasy=0.7740, F1_macro=0.8030, drzewa=60]




Trening klas:  26%|██▌       | 131/500 [19:22<29:11,  4.75s/klasa, klasa=class_130, F1_klasy=0.7740, F1_macro=0.8030, drzewa=60]

[1]	valid_0's binary_logloss: 0.131783
[2]	valid_0's binary_logloss: 0.122978
[3]	valid_0's binary_logloss: 0.117204
[4]	valid_0's binary_logloss: 0.111845
[5]	valid_0's binary_logloss: 0.107598
[6]	valid_0's binary_logloss: 0.105148
[7]	valid_0's binary_logloss: 0.101994
[8]	valid_0's binary_logloss: 0.0989974
[9]	valid_0's binary_logloss: 0.0961144
[10]	valid_0's binary_logloss: 0.093949
[11]	valid_0's binary_logloss: 0.0919097
[12]	valid_0's binary_logloss: 0.0905204
[13]	valid_0's binary_logloss: 0.0887832
[14]	valid_0's binary_logloss: 0.0872207
[15]	valid_0's binary_logloss: 0.0861265
[16]	valid_0's binary_logloss: 0.0850073
[17]	valid_0's binary_logloss: 0.0837743
[18]	valid_0's binary_logloss: 0.0828653
[19]	valid_0's binary_logloss: 0.0818876
[20]	valid_0's binary_logloss: 0.0810052
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0803197
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0796719
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.0792243
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0785085
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.0780655
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.0772983
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.0768512
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.0762743
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.0757046
[30]	valid_0's binary_logloss: 0.0752512
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.0747858
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.0744195
[33]	valid_0's binary_logloss: 0.0740302
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.073839
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.0735278
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.0732269
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.072982
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.0727381
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.0725835
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.0723665
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.0722389
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.0721287
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.0721005
[44]	valid_0's binary_logloss: 0.0720015
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.0717698
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.0716472
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.0715224
[48]	valid_0's binary_logloss: 0.0715578
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.0714141
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.0712186
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.071001
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.071019
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.070961
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.0709708
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.0709453
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.070914
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.0709211
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.0709688
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.0708998
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.0708823
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.0709162
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.0710277
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.0710004
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.0710117
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.0709976
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.0709658
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.071092
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.0711541
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.0713033
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.0711526
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.0713292
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.0714825
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.0715511
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.0716921
[75]	valid_0's binary_logloss: 0.0719593
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.0721527
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.0722149
[78]	valid_0's binary_logloss: 0.072301
[79]	valid_0's binary_logloss: 0.072331
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.0723724
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.0726046
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.0727165
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.0728142
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.0730574
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.0731441
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.073474
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.0736651
[88]	valid_0's binary_logloss: 0.0738833

Trening klas:  26%|██▌       | 131/500 [19:27<29:11,  4.75s/klasa, klasa=class_131, F1_klasy=0.7740, F1_macro=0.8028, drzewa=60]




Trening klas:  26%|██▋       | 132/500 [19:27<29:47,  4.86s/klasa, klasa=class_131, F1_klasy=0.7740, F1_macro=0.8028, drzewa=60]

[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.0739429
[90]	valid_0's binary_logloss: 0.0742153
[1]	valid_0's binary_logloss: 0.095686
[2]	valid_0's binary_logloss: 0.0921978
[3]	valid_0's binary_logloss: 0.0902405
[4]	valid_0's binary_logloss: 0.0883394
[5]	valid_0's binary_logloss: 0.0873715
[6]	valid_0's binary_logloss: 0.0864733
[7]	valid_0's binary_logloss: 0.0850746
[8]	valid_0's binary_logloss: 0.0839123
[9]	valid_0's binary_logloss: 0.0831726
[10]	valid_0's binary_logloss: 0.0824178
[11]	valid_0's binary_logloss: 0.0819993
[12]	valid_0's binary_logloss: 0.081497
[13]	valid_0's binary_logloss: 0.0812123
[14]	valid_0's binary_logloss: 0.0808099
[15]	valid_0's binary_logloss: 0.0804287
[16]	valid_0's binary_logloss: 0.0798063
[17]	valid_0's binary_logloss: 0.0793812
[18]	valid_0's binary_logloss: 0.0789807
[19]	valid_0's binary_logloss: 0.0785307
[20]	valid_0's binary_logloss: 0.0782998
[21]	valid_0's binary_logloss: 0.077959
[22]	valid_0's binary_logloss: 0.0778366
[23]	valid_0's binary_logloss: 0.0778207
[24]	valid_0's binary_logloss: 0.077731
[25]	valid_0's binary_logloss: 0.0775161
[26]	valid_0's binary_logloss: 0.0773467
[27]	valid_0's binary_logloss: 0.0770821
[28]	valid_0's binary_logloss: 0.076929
[29]	valid_0's binary_logloss: 0.0768204
[30]	valid_0's binary_logloss: 0.0765407
[31]	valid_0's binary_logloss: 0.076326
[32]	valid_0's binary_logloss: 0.0763259
[33]	valid_0's binary_logloss: 0.0760029
[34]	valid_0's binary_logloss: 0.0758373
[35]	valid_0's binary_logloss: 0.07558
[36]	valid_0's binary_logloss: 0.0755727
[37]	valid_0's binary_logloss: 0.075649
[38]	valid_0's binary_logloss: 0.0755949
[39]	valid_0's binary_logloss: 0.0755758
[40]	valid_0's binary_logloss: 0.0754812
[41]	valid_0's binary_logloss: 0.0749357
[42]	valid_0's binary_logloss: 0.0745226
[43]	valid_0's binary_logloss: 0.0741898
[44]	valid_0's binary_logloss: 0.0741346
[45]	valid_0's binary_logloss: 0.0739296
[46]	valid_0's binary_logloss: 0.0737885
[47]	valid_0's binary_logloss: 0.0736984
[48]	valid_0's binary_logloss: 0.0735362
[49]	valid_0's binary_logloss: 0.0733075
[50]	valid_0's binary_logloss: 0.0733369
[51]	valid_0's binary_logloss: 0.0734371
[52]	valid_0's binary_logloss: 0.0736029
[53]	valid_0's binary_logloss: 0.0736269
[54]	valid_0's binary_logloss: 0.0738591
[55]	valid_0's binary_logloss: 0.074019
[56]	valid_0's binary_logloss: 0.0737985
[57]	valid_0's binary_logloss: 0.0738133
[58]	valid_0's binary_logloss: 0.0737497
[59]	valid_0's binary_logloss: 0.0736911
[60]	valid_0's binary_logloss: 0.073646
[61]	valid_0's binary_logloss: 0.0737128
[62]	valid_0's binary_logloss: 0.0739246
[63]	valid_0's binary_logloss: 0.0740664
[64]	valid_0's binary_logloss: 0.0742579
[65]	valid_0's binary_logloss: 0.0743454
[66]	valid_0's binary_logloss: 0.0742963
[67]	valid_0's binary_logloss: 0.0744683
[68]	valid_0's binary_logloss: 0.0744514
[69]	valid_0's binary_logloss: 0.0742746
[70]	valid_0's binary_logloss: 0.0743578
[71]	valid_0's binary_logloss: 0.0744684
[72]	valid_0's binary_logloss: 0.0746461
[73]	valid_0's binary_logloss: 0.0748444
[74]	valid_0's binary_logloss: 0.0750139
[75]	valid_0's binary_logloss: 0.0750849
[76]	valid_0's binary_logloss: 0.0750221
[77]	valid_0's binary_logloss: 0.0751506

Trening klas:  26%|██▋       | 132/500 [19:33<29:47,  4.86s/klasa, klasa=class_132, F1_klasy=0.3929, F1_macro=0.7997, drzewa=49]




Trening klas:  27%|██▋       | 133/500 [19:33<31:47,  5.20s/klasa, klasa=class_132, F1_klasy=0.3929, F1_macro=0.7997, drzewa=49]

[78]	valid_0's binary_logloss: 0.0749813
[79]	valid_0's binary_logloss: 0.0749273
[1]	valid_0's binary_logloss: 0.0798453
[2]	valid_0's binary_logloss: 0.0737875
[3]	valid_0's binary_logloss: 0.0690227
[4]	valid_0's binary_logloss: 0.0654499
[5]	valid_0's binary_logloss: 0.0623943
[6]	valid_0's binary_logloss: 0.0603674
[7]	valid_0's binary_logloss: 0.0584772
[8]	valid_0's binary_logloss: 0.0564163
[9]	valid_0's binary_logloss: 0.0549057
[10]	valid_0's binary_logloss: 0.0535417
[11]	valid_0's binary_logloss: 0.0522875
[12]	valid_0's binary_logloss: 0.0511638
[13]	valid_0's binary_logloss: 0.0500172
[14]	valid_0's binary_logloss: 0.0489168
[15]	valid_0's binary_logloss: 0.0481796
[16]	valid_0's binary_logloss: 0.0473448
[17]	valid_0's binary_logloss: 0.0466148
[18]	valid_0's binary_logloss: 0.0459564
[19]	valid_0's binary_logloss: 0.0451982
[20]	valid_0's binary_logloss: 0.044691
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0440646
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0436237
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.0432925
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0429863
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.0427513
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.0425627
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.0424403
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.0423433
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.0421679
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.0418552
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.0418323
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.0418081
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.0417869
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.0418373
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.0418457
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.0416061
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.0410536
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.0410685
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.0408024
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.0405922
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.0406297
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.0407034
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.0405336
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.0404465
[45]	valid_0's binary_logloss: 0.0402999
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.0403257
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.0405499
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.0405943
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.040634
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.0407486
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.0403919
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.0399052
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.0397855
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.039639
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.0394244
[56]	valid_0's binary_logloss: 0.0393055
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.039098
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.039117
[59]	valid_0's binary_logloss: 0.0389829
[60]	valid_0's binary_logloss: 0.0389815
[61]	valid_0's binary_logloss: 0.0390595
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.0391652
[63]	valid_0's binary_logloss: 0.0392732
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.0393341
[65]	valid_0's binary_logloss: 0.0393779
[66]	valid_0's binary_logloss: 0.0394031
[67]	valid_0's binary_logloss: 0.0393905
[68]	valid_0's binary_logloss: 0.0393529
[69]	valid_0's binary_logloss: 0.0394179
[70]	valid_0's binary_logloss: 0.0394263
[71]	valid_0's binary_logloss: 0.0395878
[72]	valid_0's binary_logloss: 0.0396073
[73]	valid_0's binary_logloss: 0.039737
[74]	valid_0's binary_logloss: 0.0398413
[75]	valid_0's binary_logloss: 0.0400611
[76]	valid_0's binary_logloss: 0.0399653
[77]	valid_0's binary_logloss: 0.039915
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.0398777
[79]	valid_0's binary_logloss: 0.0399306
[80]	valid_0's binary_logloss: 0.0399336
[81]	valid_0's binary_logloss: 0.0399298
[82]	valid_0's binary_logloss: 0.0399566
[83]	valid_0's binary_logloss: 0.0399272
[84]	valid_0's binary_logloss: 0.0399173
[85]	valid_0's binary_logloss: 0.0398619
[86]	valid_0's binary_logloss: 0.0397689

Trening klas:  27%|██▋       | 133/500 [19:38<31:47,  5.20s/klasa, klasa=class_133, F1_klasy=0.7905, F1_macro=0.7997, drzewa=60]




Trening klas:  27%|██▋       | 134/500 [19:38<31:15,  5.12s/klasa, klasa=class_133, F1_klasy=0.7905, F1_macro=0.7997, drzewa=60]

[87]	valid_0's binary_logloss: 0.0396516
[88]	valid_0's binary_logloss: 0.0396767
[89]	valid_0's binary_logloss: 0.0396538
[90]	valid_0's binary_logloss: 0.0396571
[1]	valid_0's binary_logloss: 0.0295382
[2]	valid_0's binary_logloss: 0.0280152
[3]	valid_0's binary_logloss: 0.0266327
[4]	valid_0's binary_logloss: 0.0255184
[5]	valid_0's binary_logloss: 0.0243502
[6]	valid_0's binary_logloss: 0.0232011
[7]	valid_0's binary_logloss: 0.0221707
[8]	valid_0's binary_logloss: 0.0211786
[9]	valid_0's binary_logloss: 0.0202369
[10]	valid_0's binary_logloss: 0.0193515
[11]	valid_0's binary_logloss: 0.0184613
[12]	valid_0's binary_logloss: 0.0176875
[13]	valid_0's binary_logloss: 0.0169451
[14]	valid_0's binary_logloss: 0.0161916
[15]	valid_0's binary_logloss: 0.0154746
[16]	valid_0's binary_logloss: 0.0147908
[17]	valid_0's binary_logloss: 0.0141896
[18]	valid_0's binary_logloss: 0.0135892
[19]	valid_0's binary_logloss: 0.0130124
[20]	valid_0's binary_logloss: 0.0124837
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0119406
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0114681
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.0110505
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0106395
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.0102368
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.00978889
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.00942983
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.00905056
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.00867252
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.00831299
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.00794669
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.00762951
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.00736872
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.00705152
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.00680655
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.00654026
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.00627853
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.00602403
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.00580225
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.00559123
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.00536654
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.00515588
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.00496434
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.00477679
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.00461351
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.00444821
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.00429029
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.00412894
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.00397727
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.00383101
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.00369643
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.00358835
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.00348692
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.00335673
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.00324285
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.00313155
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.00301229
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.00291976
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.00283061
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.00275171
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.00266549
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.00258894
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.00250416
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.00243426
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.00235988
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.00228344
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.00221963
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.00212991
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.00207207
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.0020072
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.00195297
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.00191766
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.00187734
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.00183864
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.0018059
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.00176836
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.00172371
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.00168651
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.00164776
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.00161264
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.00157712
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.00154632
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.00152453
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.00149762
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.00145369
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.001417
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.00138239
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.00135355
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.00131985
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.00129728
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.00127059
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.00125221
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.00123012
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.00121865
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.00120413
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.00117388
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.00116372
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.00112809
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.00110112
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.00106159
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.0010454
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.00103684
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.00103011
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.00101498
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.000996073
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.000978897
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.00096822
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.000943701
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.000935208
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.000925873
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.000910496
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 0.000909428
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 0.00089697
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 0.000875524
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 0.000866282
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[116]	valid_0's binary_logloss: 0.000856669
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[117]	valid_0's binary_logloss: 0.000849661
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[118]	valid_0's binary_logloss: 0.000847566
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[119]	valid_0's binary_logloss: 0.000844519
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[120]	valid_0's binary_logloss: 0.000851046
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[121]	valid_0's binary_logloss: 0.000849132
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[122]	valid_0's binary_logloss: 0.000844099
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[123]	valid_0's binary_logloss: 0.000833096
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[124]	valid_0's binary_logloss: 0.00082957
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[125]	valid_0's binary_logloss: 0.000833105
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[126]	valid_0's binary_logloss: 0.000816802
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[127]	valid_0's binary_logloss: 0.000813094
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[128]	valid_0's binary_logloss: 0.000808644
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[129]	valid_0's binary_logloss: 0.000808702
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[130]	valid_0's binary_logloss: 0.000803535
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[131]	valid_0's binary_logloss: 0.000801141
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[132]	valid_0's binary_logloss: 0.000791674
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[133]	valid_0's binary_logloss: 0.000777802
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[134]	valid_0's binary_logloss: 0.0007656
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[135]	valid_0's binary_logloss: 0.000762323
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[136]	valid_0's binary_logloss: 0.000762278
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[137]	valid_0's binary_logloss: 0.000759156
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[138]	valid_0's binary_logloss: 0.000759914
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[139]	valid_0's binary_logloss: 0.000755868
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[140]	valid_0's binary_logloss: 0.00075739
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[141]	valid_0's binary_logloss: 0.000748475
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[142]	valid_0's binary_logloss: 0.000744672
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[143]	valid_0's binary_logloss: 0.000735449
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[144]	valid_0's binary_logloss: 0.000743617
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[145]	valid_0's binary_logloss: 0.000738432
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[146]	valid_0's binary_logloss: 0.000751101
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[147]	valid_0's binary_logloss: 0.000752439
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[148]	valid_0's binary_logloss: 0.000740283
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[149]	valid_0's binary_logloss: 0.000744162
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[150]	valid_0's binary_logloss: 0.00075803
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[151]	valid_0's binary_logloss: 0.000752223
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[152]	valid_0's binary_logloss: 0.000755065
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[153]	valid_0's binary_logloss: 0.000752897
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[154]	valid_0's binary_logloss: 0.000747541
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[155]	valid_0's binary_logloss: 0.000749896
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[156]	valid_0's binary_logloss: 0.000753056
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[157]	valid_0's binary_logloss: 0.000754793
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[158]	valid_0's binary_logloss: 0.000755211
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[159]	valid_0's binary_logloss: 0.000758533
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[160]	valid_0's binary_logloss: 0.000765598
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[161]	valid_0's binary_logloss: 0.000757046
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[162]	valid_0's binary_logloss: 0.000762826
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[163]	valid_0's binary_logloss: 0.000758042
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[164]	valid_0's binary_logloss: 0.000759185
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[165]	valid_0's binary_logloss: 0.000763969
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[166]	valid_0's binary_logloss: 0.000762009
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[167]	valid_0's binary_logloss: 0.000757196
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[168]	valid_0's binary_logloss: 0.000749705
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[169]	valid_0's binary_logloss: 0.00075105
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[170]	valid_0's binary_logloss: 0.000752319
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[171]	valid_0's binary_logloss: 0.000748521
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[172]	valid_0's binary_logloss: 0.000745459
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

Trening klas:  27%|██▋       | 134/500 [19:44<31:15,  5.12s/klasa, klasa=class_134, F1_klasy=0.8750, F1_macro=0.8002, drzewa=143]




Trening klas:  27%|██▋       | 135/500 [19:44<33:01,  5.43s/klasa, klasa=class_134, F1_klasy=0.8750, F1_macro=0.8002, drzewa=143]

[173]	valid_0's binary_logloss: 0.000737311
[1]	valid_0's binary_logloss: 0.0905871
[2]	valid_0's binary_logloss: 0.0826813
[3]	valid_0's binary_logloss: 0.0763833
[4]	valid_0's binary_logloss: 0.0710696
[5]	valid_0's binary_logloss: 0.0664892
[6]	valid_0's binary_logloss: 0.0624885
[7]	valid_0's binary_logloss: 0.0589994
[8]	valid_0's binary_logloss: 0.0559277
[9]	valid_0's binary_logloss: 0.0532057
[10]	valid_0's binary_logloss: 0.0507827
[11]	valid_0's binary_logloss: 0.048643
[12]	valid_0's binary_logloss: 0.0467286
[13]	valid_0's binary_logloss: 0.0449604
[14]	valid_0's binary_logloss: 0.0433332
[15]	valid_0's binary_logloss: 0.0418944
[16]	valid_0's binary_logloss: 0.0405866
[17]	valid_0's binary_logloss: 0.0393859
[18]	valid_0's binary_logloss: 0.0382573
[19]	valid_0's binary_logloss: 0.0372915
[20]	valid_0's binary_logloss: 0.0364372
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0356331
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0349019
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.034248
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0336759
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.0331086
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.0325921
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.0321422
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.0317182
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.0313468
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.0310229
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.0306018
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.0303195
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.0300807
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.0298571
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.0296939
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.029459
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.0293805
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.0292313
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.0291988
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.0291947
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.0291949
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.0291933
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.0292343
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.0292939
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.0293561
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.0285823
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.0281964
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.0276218
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.0272822
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.0271303
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.0267162
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.026346
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.0264965
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.0263312
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.0264091
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.0261367
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.0259542
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.025852
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.0257204
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.025632
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.0257969
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.0259702
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.0261442
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.0262821
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.0262348
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.0262035
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.0261298
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.0260884
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.0260784
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.0260662
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.026268
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.0264635
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.0266281
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.0268132
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.0270331
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.027171
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.0271077
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.0271386
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.0271939
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.0272851
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.0273894
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.0273565
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.0274561
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.0275004
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.0275101
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

Trening klas:  27%|██▋       | 135/500 [19:47<33:01,  5.43s/klasa, klasa=class_135, F1_klasy=0.9101, F1_macro=0.8010, drzewa=60]




Trening klas:  27%|██▋       | 136/500 [19:47<28:17,  4.66s/klasa, klasa=class_135, F1_klasy=0.9101, F1_macro=0.8010, drzewa=60]

[86]	valid_0's binary_logloss: 0.0275835
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.0275105
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.0275835
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.0277376
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.0278385
[1]	valid_0's binary_logloss: 0.141465
[2]	valid_0's binary_logloss: 0.138134
[3]	valid_0's binary_logloss: 0.135778
[4]	valid_0's binary_logloss: 0.133729
[5]	valid_0's binary_logloss: 0.132066
[6]	valid_0's binary_logloss: 0.130908
[7]	valid_0's binary_logloss: 0.129383
[8]	valid_0's binary_logloss: 0.12822
[9]	valid_0's binary_logloss: 0.127725
[10]	valid_0's binary_logloss: 0.126416
[11]	valid_0's binary_logloss: 0.124947
[12]	valid_0's binary_logloss: 0.124491
[13]	valid_0's binary_logloss: 0.123808
[14]	valid_0's binary_logloss: 0.123583
[15]	valid_0's binary_logloss: 0.123313
[16]	valid_0's binary_logloss: 0.1226
[17]	valid_0's binary_logloss: 0.121939
[18]	valid_0's binary_logloss: 0.120904
[19]	valid_0's binary_logloss: 0.120277
[20]	valid_0's binary_logloss: 0.119714
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.119107
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.119286
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.119206
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.119151
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.118925
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.119045
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.119255
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.118698
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.118486
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.118503
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.11844
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.11822
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.118273
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.118234
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.117999
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.117804
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.117798
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.117742
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.117575
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.117966
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.117976
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.118213
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.118518
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.118719
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.119211
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.119382
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.119574
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.11965
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.119813
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.119913
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.120136
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.119861
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.119929
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.11999
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.120039
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.120116
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.120256
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.12023
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.120299
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.120422
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.120455
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.120563
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.120759
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.12066

Trening klas:  27%|██▋       | 136/500 [19:51<28:17,  4.66s/klasa, klasa=class_136, F1_klasy=0.5601, F1_macro=0.7993, drzewa=39]




Trening klas:  27%|██▋       | 137/500 [19:51<26:59,  4.46s/klasa, klasa=class_136, F1_klasy=0.5601, F1_macro=0.7993, drzewa=39]

[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.120673
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.120733
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.120799
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.121006
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.120962
[1]	valid_0's binary_logloss: 0.176992
[2]	valid_0's binary_logloss: 0.174922
[3]	valid_0's binary_logloss: 0.17249
[4]	valid_0's binary_logloss: 0.169857
[5]	valid_0's binary_logloss: 0.16799
[6]	valid_0's binary_logloss: 0.166414
[7]	valid_0's binary_logloss: 0.165464
[8]	valid_0's binary_logloss: 0.164641
[9]	valid_0's binary_logloss: 0.162524
[10]	valid_0's binary_logloss: 0.161366
[11]	valid_0's binary_logloss: 0.160678
[12]	valid_0's binary_logloss: 0.159347
[13]	valid_0's binary_logloss: 0.158294
[14]	valid_0's binary_logloss: 0.158022
[15]	valid_0's binary_logloss: 0.156949
[16]	valid_0's binary_logloss: 0.156705
[17]	valid_0's binary_logloss: 0.156384
[18]	valid_0's binary_logloss: 0.155625
[19]	valid_0's binary_logloss: 0.155315
[20]	valid_0's binary_logloss: 0.15474
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.15473
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.154427
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.154216
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.154497
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.153665
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.153336
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.152801
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.151816
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.150945
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.150586
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.150726
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.150778
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.150357
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.149867
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.149495
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.148613
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.148111
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.147123
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.146538
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.146153
[41]	valid_0's binary_logloss: 0.146114
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.146282
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.146395
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.146828
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.146897
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.146374
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.146236
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.146545
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.146771
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.146945
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.146688
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.146875
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.146887
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.146852
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.146734
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.146336
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.146183
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.146099
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.146036
[60]	valid_0's binary_logloss: 0.146052
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.146024
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.146116
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.146092
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.145865
[65]	valid_0's binary_logloss: 0.145712
[66]	valid_0's binary_logloss: 0.145412
[67]	valid_0's binary_logloss: 0.14512
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.144919
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.144804
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.144663
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.144477
[72]	valid_0's binary_logloss: 0.144641
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.144626
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.144625
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.1446
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.144339
[77]	valid_0's binary_logloss: 0.144137
[78]	valid_0's binary_logloss: 0.144223
[79]	valid_0's binary_logloss: 0.144309
[80]	valid_0's binary_logloss: 0.144057
[81]	valid_0's binary_logloss: 0.143923
[82]	valid_0's binary_logloss: 0.144033
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.143809
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.144049
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.143807
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.143772
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.143861
[88]	valid_0's binary_logloss: 0.144
[89]	valid_0's binary_logloss: 0.144284
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.144306
[91]	valid_0's binary_logloss: 0.144428
[92]	valid_0's binary_logloss: 0.144434
[93]	valid_0's binary_logloss: 0.1446
[94]	valid_0's binary_logloss: 0.144906
[95]	valid_0's binary_logloss: 0.145308
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.145625
[97]	valid_0's binary_logloss: 0.145641
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.145827
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.145813
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.145895
[101]	valid_0's binary_logloss: 0.146341
[102]	valid_0's binary_logloss: 0.146397
[103]	valid_0's binary_logloss: 0.146665
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.146941
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.146636
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.146315
[107]	valid_0's binary_logloss: 0.146185
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.145847
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.145461
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.145294
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.145381
[112]	valid_0's binary_logloss: 0.145721
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 0.146031
[114]	valid_0's binary_logloss: 0.146109
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

Trening klas:  27%|██▋       | 137/500 [19:57<26:59,  4.46s/klasa, klasa=class_137, F1_klasy=0.5598, F1_macro=0.7975, drzewa=86]




Trening klas:  28%|██▊       | 138/500 [19:57<29:57,  4.96s/klasa, klasa=class_137, F1_klasy=0.5598, F1_macro=0.7975, drzewa=86]

[115]	valid_0's binary_logloss: 0.146107
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[116]	valid_0's binary_logloss: 0.146254
[1]	valid_0's binary_logloss: 0.176992
[2]	valid_0's binary_logloss: 0.174922
[3]	valid_0's binary_logloss: 0.17249
[4]	valid_0's binary_logloss: 0.169857
[5]	valid_0's binary_logloss: 0.16799
[6]	valid_0's binary_logloss: 0.166414
[7]	valid_0's binary_logloss: 0.165464
[8]	valid_0's binary_logloss: 0.164641
[9]	valid_0's binary_logloss: 0.162524
[10]	valid_0's binary_logloss: 0.161366
[11]	valid_0's binary_logloss: 0.160678
[12]	valid_0's binary_logloss: 0.159347
[13]	valid_0's binary_logloss: 0.158294
[14]	valid_0's binary_logloss: 0.158022
[15]	valid_0's binary_logloss: 0.156949
[16]	valid_0's binary_logloss: 0.156705
[17]	valid_0's binary_logloss: 0.156384
[18]	valid_0's binary_logloss: 0.155625
[19]	valid_0's binary_logloss: 0.155315
[20]	valid_0's binary_logloss: 0.15474
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.15473
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.154427
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.154216
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.154497
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.153665
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.153336
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.152801
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.151816
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.150945
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.150586
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.150726
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.150778
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.150357
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.149867
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.149495
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.148613
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.148111
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.147123
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.146538
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.146153
[41]	valid_0's binary_logloss: 0.146114
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.146282
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.146395
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.146828
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.146897
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.146374
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.146236
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.146545
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.146771
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.146945
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.146688
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.146875
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.146887
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.146852
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.146734
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.146336
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.146183
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.146099
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.146036
[60]	valid_0's binary_logloss: 0.146052
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.146024
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.146116
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.146092
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.145865
[65]	valid_0's binary_logloss: 0.145712
[66]	valid_0's binary_logloss: 0.145412
[67]	valid_0's binary_logloss: 0.14512
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.144919
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.144804
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.144663
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.144477
[72]	valid_0's binary_logloss: 0.144641
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.144626
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.144625
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.1446
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.144339
[77]	valid_0's binary_logloss: 0.144137
[78]	valid_0's binary_logloss: 0.144223
[79]	valid_0's binary_logloss: 0.144309
[80]	valid_0's binary_logloss: 0.144057
[81]	valid_0's binary_logloss: 0.143923
[82]	valid_0's binary_logloss: 0.144033
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.143809
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.144049
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.143807
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.143772
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.143861
[88]	valid_0's binary_logloss: 0.144
[89]	valid_0's binary_logloss: 0.144284
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.144306
[91]	valid_0's binary_logloss: 0.144428
[92]	valid_0's binary_logloss: 0.144434
[93]	valid_0's binary_logloss: 0.1446
[94]	valid_0's binary_logloss: 0.144906
[95]	valid_0's binary_logloss: 0.145308
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.145625
[97]	valid_0's binary_logloss: 0.145641
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.145827
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.145813
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.145895
[101]	valid_0's binary_logloss: 0.146341
[102]	valid_0's binary_logloss: 0.146397
[103]	valid_0's binary_logloss: 0.146665
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.146941
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.146636
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.146315
[107]	valid_0's binary_logloss: 0.146185
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.145847
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.145461
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.145294
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.145381
[112]	valid_0's binary_logloss: 0.145721
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 0.146031
[114]	valid_0's binary_logloss: 0.146109
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 0.146107
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[116]	valid_0's binary_logloss: 0.146254

Trening klas:  28%|██▊       | 138/500 [20:03<29:57,  4.96s/klasa, klasa=class_138, F1_klasy=0.5598, F1_macro=0.7958, drzewa=86]




Trening klas:  28%|██▊       | 139/500 [20:03<31:56,  5.31s/klasa, klasa=class_138, F1_klasy=0.5598, F1_macro=0.7958, drzewa=86]

[1]	valid_0's binary_logloss: 0.043394
[2]	valid_0's binary_logloss: 0.041775
[3]	valid_0's binary_logloss: 0.0401991
[4]	valid_0's binary_logloss: 0.03871
[5]	valid_0's binary_logloss: 0.0372328
[6]	valid_0's binary_logloss: 0.0359068
[7]	valid_0's binary_logloss: 0.0348652
[8]	valid_0's binary_logloss: 0.0339515
[9]	valid_0's binary_logloss: 0.0329632
[10]	valid_0's binary_logloss: 0.0321366
[11]	valid_0's binary_logloss: 0.0311538
[12]	valid_0's binary_logloss: 0.0303831
[13]	valid_0's binary_logloss: 0.0297367
[14]	valid_0's binary_logloss: 0.0289533
[15]	valid_0's binary_logloss: 0.0282597
[16]	valid_0's binary_logloss: 0.0277404
[17]	valid_0's binary_logloss: 0.0271189
[18]	valid_0's binary_logloss: 0.0265462
[19]	valid_0's binary_logloss: 0.026092
[20]	valid_0's binary_logloss: 0.0256948
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0252402
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0248052
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.0244075
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0239764
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.0236347
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.0232915
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.0227643
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.0223579
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.0220568
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.0217364
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.0213613
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.0210867
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.0207588
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.0205439
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.0203141
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.0201067
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.019936
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.0197094
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.0195596
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.01939
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.0191769
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.0190138
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.0188079
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.0186865
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.0185819
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.0185149
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.018464
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.0184529
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.0182833
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.0180883
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.0179223
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.0177738
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.0177626
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.0176173
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.0175251
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.017528
[57]	valid_0's binary_logloss: 0.0173756
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.0172466
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.0172388
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.0171239
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.0170066
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.0169466
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.0168794
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.0168273
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.0167789
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.0166055
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.0166373
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.0165105
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.0164046
[70]	valid_0's binary_logloss: 0.0164457
[71]	valid_0's binary_logloss: 0.0163189
[72]	valid_0's binary_logloss: 0.0163256
[73]	valid_0's binary_logloss: 0.0163158
[74]	valid_0's binary_logloss: 0.0161956
[75]	valid_0's binary_logloss: 0.016084
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.0160296
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.015966
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.015921
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.0159652
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.0159196
[81]	valid_0's binary_logloss: 0.0158345
[82]	valid_0's binary_logloss: 0.0157316
[83]	valid_0's binary_logloss: 0.0156953
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.015679
[85]	valid_0's binary_logloss: 0.0156288
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.0155973
[87]	valid_0's binary_logloss: 0.0156246
[88]	valid_0's binary_logloss: 0.0155905
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.0156428
[90]	valid_0's binary_logloss: 0.0156711
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.0157172
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.0156667
[93]	valid_0's binary_logloss: 0.0156838
[94]	valid_0's binary_logloss: 0.0156928
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.0156657
[96]	valid_0's binary_logloss: 0.0156662
[97]	valid_0's binary_logloss: 0.0156923
[98]	valid_0's binary_logloss: 0.015695
[99]	valid_0's binary_logloss: 0.0157328
[100]	valid_0's binary_logloss: 0.0157665
[101]	valid_0's binary_logloss: 0.0157953
[102]	valid_0's binary_logloss: 0.0158368
[103]	valid_0's binary_logloss: 0.0158867
[104]	valid_0's binary_logloss: 0.0159327
[105]	valid_0's binary_logloss: 0.0159598
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.0159879
[107]	valid_0's binary_logloss: 0.0160138
[108]	valid_0's binary_logloss: 0.0160553
[109]	valid_0's binary_logloss: 0.0159754
[110]	valid_0's binary_logloss: 0.0160098
[111]	valid_0's binary_logloss: 0.0160331
[112]	valid_0's binary_logloss: 0.0160247
[113]	valid_0's binary_logloss: 0.0160177
[114]	valid_0's binary_logloss: 0.0159782
[115]	valid_0's binary_logloss: 0.0159969
[116]	valid_0's binary_logloss: 0.0160046
[117]	valid_0's binary_logloss: 0.01608

Trening klas:  28%|██▊       | 139/500 [20:09<31:56,  5.31s/klasa, klasa=class_139, F1_klasy=0.5526, F1_macro=0.7941, drzewa=88]




Trening klas:  28%|██▊       | 140/500 [20:09<33:21,  5.56s/klasa, klasa=class_139, F1_klasy=0.5526, F1_macro=0.7941, drzewa=88]

[118]	valid_0's binary_logloss: 0.0161015
[1]	valid_0's binary_logloss: 0.137562
[2]	valid_0's binary_logloss: 0.134605
[3]	valid_0's binary_logloss: 0.132581
[4]	valid_0's binary_logloss: 0.130688
[5]	valid_0's binary_logloss: 0.129369
[6]	valid_0's binary_logloss: 0.128477
[7]	valid_0's binary_logloss: 0.127627
[8]	valid_0's binary_logloss: 0.126755
[9]	valid_0's binary_logloss: 0.126314
[10]	valid_0's binary_logloss: 0.12515
[11]	valid_0's binary_logloss: 0.124269
[12]	valid_0's binary_logloss: 0.123717
[13]	valid_0's binary_logloss: 0.122874
[14]	valid_0's binary_logloss: 0.122403
[15]	valid_0's binary_logloss: 0.121676
[16]	valid_0's binary_logloss: 0.120783
[17]	valid_0's binary_logloss: 0.119929
[18]	valid_0's binary_logloss: 0.118808
[19]	valid_0's binary_logloss: 0.118124
[20]	valid_0's binary_logloss: 0.117413
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.116919
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.116685
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.116282
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.115921
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.115565
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.115098
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.114507
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.113892
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.113587
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.113163
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.112736
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.112473
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.111711
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.111679
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.11162
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.11157
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.111406
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.111292
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.111522
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.111689
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.111518
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.111554
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.111535
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.111314
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.111549
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.111375
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.111105
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.111262
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.111192
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.111153
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.110858
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.11076
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.11066
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.110568
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.110529
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.110509
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.110447
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.110407
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.110457
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.110153
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.110412
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.110576
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.110495
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.110558
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.110458
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.11027
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.110013
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.109828
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.109921
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.109767
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.109666
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.109705
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.109618
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.109688
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.10938
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.109324
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.109334
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.109544
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.109565
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.109654
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.10976
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.10965
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.109791
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.109958
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.109921
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.109912
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.110001
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.110233
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.110656
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.110844
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.111021
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.111135
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.111227
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.111435
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.11123
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.111031
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.111143
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.111014
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.111052
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.11085
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.111143
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.111267
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.111432
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.111651
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

Trening klas:  28%|██▊       | 140/500 [20:14<33:21,  5.56s/klasa, klasa=class_140, F1_klasy=0.5831, F1_macro=0.7926, drzewa=76]




Trening klas:  28%|██▊       | 141/500 [20:14<32:36,  5.45s/klasa, klasa=class_140, F1_klasy=0.5831, F1_macro=0.7926, drzewa=76]

[105]	valid_0's binary_logloss: 0.111863
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.112126
[1]	valid_0's binary_logloss: 0.0842527
[2]	valid_0's binary_logloss: 0.0772386
[3]	valid_0's binary_logloss: 0.0716493
[4]	valid_0's binary_logloss: 0.0668008
[5]	valid_0's binary_logloss: 0.0626824
[6]	valid_0's binary_logloss: 0.0590921
[7]	valid_0's binary_logloss: 0.0559039
[8]	valid_0's binary_logloss: 0.0529502
[9]	valid_0's binary_logloss: 0.0504831
[10]	valid_0's binary_logloss: 0.0481997
[11]	valid_0's binary_logloss: 0.0462244
[12]	valid_0's binary_logloss: 0.0444377
[13]	valid_0's binary_logloss: 0.0428269
[14]	valid_0's binary_logloss: 0.0413981
[15]	valid_0's binary_logloss: 0.0402523
[16]	valid_0's binary_logloss: 0.0389835
[17]	valid_0's binary_logloss: 0.0378403
[18]	valid_0's binary_logloss: 0.037176
[19]	valid_0's binary_logloss: 0.036636
[20]	valid_0's binary_logloss: 0.0357543
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0345027
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0337339
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.032719
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0321386
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.03128
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.030689
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.0299079
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.0293646
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.0287547
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.028193
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.0279369
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.027607
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.0274343
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.0269353
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.0264892
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.0263675
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.0258601
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.0254745
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.0252441
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.0251171
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.024964
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.0249265
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.024888
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.0248419
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.0248642
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.0246909
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.0247013
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.0245377
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.0243667
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.0242911
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.0242525
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.0241804
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.0242452
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.0241496
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.0241621
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.0242867
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.0244199
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.0245832
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.0244424
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.0243101
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.0243272
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.0242195
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.0242217
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.0241735
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.0242883
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.0242891
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.0243317
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.0243638
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.0243327
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.0243895
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.0245315
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.0245028
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.0245109
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.0246067
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.0246298
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.0246716
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.0247102
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.0247261
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

Trening klas:  28%|██▊       | 141/500 [20:18<32:36,  5.45s/klasa, klasa=class_141, F1_klasy=0.9224, F1_macro=0.7935, drzewa=54]




Trening klas:  28%|██▊       | 142/500 [20:18<29:02,  4.87s/klasa, klasa=class_141, F1_klasy=0.9224, F1_macro=0.7935, drzewa=54]

[79]	valid_0's binary_logloss: 0.0247162
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.0247819
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.0247252
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.0246776
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.0246833
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.0248076
[1]	valid_0's binary_logloss: 0.0374148
[2]	valid_0's binary_logloss: 0.0360105
[3]	valid_0's binary_logloss: 0.0346927
[4]	valid_0's binary_logloss: 0.0334419
[5]	valid_0's binary_logloss: 0.0323225
[6]	valid_0's binary_logloss: 0.0312085
[7]	valid_0's binary_logloss: 0.0304013
[8]	valid_0's binary_logloss: 0.0295639
[9]	valid_0's binary_logloss: 0.0287586
[10]	valid_0's binary_logloss: 0.0279777
[11]	valid_0's binary_logloss: 0.0274662
[12]	valid_0's binary_logloss: 0.0269011
[13]	valid_0's binary_logloss: 0.0262203
[14]	valid_0's binary_logloss: 0.0257103
[15]	valid_0's binary_logloss: 0.0251521
[16]	valid_0's binary_logloss: 0.0245712
[17]	valid_0's binary_logloss: 0.0240118
[18]	valid_0's binary_logloss: 0.0235854
[19]	valid_0's binary_logloss: 0.0230684
[20]	valid_0's binary_logloss: 0.0225144
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0219789
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0216979
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.0212884
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0209396
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.0206773
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.0203494
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.0199507
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.0196364
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.0193123
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.0190088
[31]	valid_0's binary_logloss: 0.0187701
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.0185353
[33]	valid_0's binary_logloss: 0.0183058
[34]	valid_0's binary_logloss: 0.0181181
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.0178857
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.0177749
[37]	valid_0's binary_logloss: 0.0175983
[38]	valid_0's binary_logloss: 0.017386
[39]	valid_0's binary_logloss: 0.0171822
[40]	valid_0's binary_logloss: 0.0170293
[41]	valid_0's binary_logloss: 0.0169109
[42]	valid_0's binary_logloss: 0.0167891
[43]	valid_0's binary_logloss: 0.016668
[44]	valid_0's binary_logloss: 0.0165234
[45]	valid_0's binary_logloss: 0.0164336
[46]	valid_0's binary_logloss: 0.0163713
[47]	valid_0's binary_logloss: 0.0162074
[48]	valid_0's binary_logloss: 0.0161309
[49]	valid_0's binary_logloss: 0.0160578
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.0159859
[51]	valid_0's binary_logloss: 0.0159903
[52]	valid_0's binary_logloss: 0.0159348
[53]	valid_0's binary_logloss: 0.0159182
[54]	valid_0's binary_logloss: 0.0158764
[55]	valid_0's binary_logloss: 0.01578
[56]	valid_0's binary_logloss: 0.0157678
[57]	valid_0's binary_logloss: 0.0156318
[58]	valid_0's binary_logloss: 0.0154822
[59]	valid_0's binary_logloss: 0.0153344
[60]	valid_0's binary_logloss: 0.0152587
[61]	valid_0's binary_logloss: 0.0152402
[62]	valid_0's binary_logloss: 0.0152455
[63]	valid_0's binary_logloss: 0.0151911
[64]	valid_0's binary_logloss: 0.0151703
[65]	valid_0's binary_logloss: 0.015123
[66]	valid_0's binary_logloss: 0.0150656
[67]	valid_0's binary_logloss: 0.0149923
[68]	valid_0's binary_logloss: 0.014915
[69]	valid_0's binary_logloss: 0.0147998
[70]	valid_0's binary_logloss: 0.0147249
[71]	valid_0's binary_logloss: 0.0146891
[72]	valid_0's binary_logloss: 0.014641
[73]	valid_0's binary_logloss: 0.0146351
[74]	valid_0's binary_logloss: 0.0146598
[75]	valid_0's binary_logloss: 0.0146037
[76]	valid_0's binary_logloss: 0.0145925
[77]	valid_0's binary_logloss: 0.0145865
[78]	valid_0's binary_logloss: 0.0145817
[79]	valid_0's binary_logloss: 0.0146096
[80]	valid_0's binary_logloss: 0.0145539
[81]	valid_0's binary_logloss: 0.0146157
[82]	valid_0's binary_logloss: 0.0145913
[83]	valid_0's binary_logloss: 0.0145381
[84]	valid_0's binary_logloss: 0.0144919
[85]	valid_0's binary_logloss: 0.014418
[86]	valid_0's binary_logloss: 0.0144373
[87]	valid_0's binary_logloss: 0.0143777
[88]	valid_0's binary_logloss: 0.0144018
[89]	valid_0's binary_logloss: 0.0143358
[90]	valid_0's binary_logloss: 0.0143688
[91]	valid_0's binary_logloss: 0.0143944
[92]	valid_0's binary_logloss: 0.0143655
[93]	valid_0's binary_logloss: 0.0143155
[94]	valid_0's binary_logloss: 0.0142654
[95]	valid_0's binary_logloss: 0.0142937
[96]	valid_0's binary_logloss: 0.0143138
[97]	valid_0's binary_logloss: 0.0143427
[98]	valid_0's binary_logloss: 0.0142591
[99]	valid_0's binary_logloss: 0.0142603
[100]	valid_0's binary_logloss: 0.0142614
[101]	valid_0's binary_logloss: 0.014219
[102]	valid_0's binary_logloss: 0.0141865
[103]	valid_0's binary_logloss: 0.0141545
[104]	valid_0's binary_logloss: 0.0141048
[105]	valid_0's binary_logloss: 0.0141195
[106]	valid_0's binary_logloss: 0.014169
[107]	valid_0's binary_logloss: 0.0142079
[108]	valid_0's binary_logloss: 0.0142648
[109]	valid_0's binary_logloss: 0.0143073
[110]	valid_0's binary_logloss: 0.0143821
[111]	valid_0's binary_logloss: 0.0143845
[112]	valid_0's binary_logloss: 0.0144199
[113]	valid_0's binary_logloss: 0.0144435
[114]	valid_0's binary_logloss: 0.0144487
[115]	valid_0's binary_logloss: 0.014406
[116]	valid_0's binary_logloss: 0.0143268
[117]	valid_0's binary_logloss: 0.0142811
[118]	valid_0's binary_logloss: 0.0142413
[119]	valid_0's binary_logloss: 0.0141648
[120]	valid_0's binary_logloss: 0.0142247
[121]	valid_0's binary_logloss: 0.0142458
[122]	valid_0's binary_logloss: 0.0142519
[123]	valid_0's binary_logloss: 0.0142517
[124]	valid_0's binary_logloss: 0.0142913
[125]	valid_0's binary_logloss: 0.0143685
[126]	valid_0's binary_logloss: 0.0144018
[127]	valid_0's binary_logloss: 0.0144206
[128]	valid_0's binary_logloss: 0.0144914
[129]	valid_0's binary_logloss: 0.0144847
[130]	valid_0's binary_logloss: 0.0145157
[131]	valid_0's binary_logloss: 0.0145537
[132]	valid_0's binary_logloss: 0.014572
[133]	valid_0's binary_logloss: 0.0146469
[134]	valid_0's binary_logloss: 0.014707

Trening klas:  28%|██▊       | 142/500 [20:26<29:02,  4.87s/klasa, klasa=class_142, F1_klasy=0.3922, F1_macro=0.7907, drzewa=104]




Trening klas:  29%|██▊       | 143/500 [20:26<34:27,  5.79s/klasa, klasa=class_142, F1_klasy=0.3922, F1_macro=0.7907, drzewa=104]

[1]	valid_0's binary_logloss: 0.0885092
[2]	valid_0's binary_logloss: 0.0833247
[3]	valid_0's binary_logloss: 0.0801831
[4]	valid_0's binary_logloss: 0.0771142
[5]	valid_0's binary_logloss: 0.0747905
[6]	valid_0's binary_logloss: 0.0727894
[7]	valid_0's binary_logloss: 0.0709625
[8]	valid_0's binary_logloss: 0.0694767
[9]	valid_0's binary_logloss: 0.0680657
[10]	valid_0's binary_logloss: 0.0669484
[11]	valid_0's binary_logloss: 0.065707
[12]	valid_0's binary_logloss: 0.064889
[13]	valid_0's binary_logloss: 0.0636651
[14]	valid_0's binary_logloss: 0.0628107
[15]	valid_0's binary_logloss: 0.0617553
[16]	valid_0's binary_logloss: 0.0604794
[17]	valid_0's binary_logloss: 0.0596065
[18]	valid_0's binary_logloss: 0.05902
[19]	valid_0's binary_logloss: 0.0583134
[20]	valid_0's binary_logloss: 0.0574518
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0569501
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.056133
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.0556609
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0548978
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.0543221
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.053625
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.052821
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.0524659
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.0517903
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.0512616
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.0506975
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.0503331
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.0500615
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.0497147
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.0492367
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.0487436
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.0483545
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.0480636
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.047599
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.0471695
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.0466919
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.0463715
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.0461278
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.0460808
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.0459616
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.0456781
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.0452994
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.0450216
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.0446283
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.0443114
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.0441638
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.0438889
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.0437716
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.0439051
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.0439018
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.0437928
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.0437007
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.0435253
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.0435003
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.043469
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.0434924
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.0435482
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.0435474
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.0436554
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.0435768
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.043628
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.0436355
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.0437515
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.043905
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.0438046
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.0436617
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.0436918
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.0435415
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.0437914
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.0440181
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.0441082
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.0442148
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.0443392
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.0444592
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.044704
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.0448741
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.0450753
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.0451536
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.0453562
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.0453605
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.045422
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.0455192
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

Trening klas:  29%|██▊       | 143/500 [20:31<34:27,  5.79s/klasa, klasa=class_143, F1_klasy=0.7105, F1_macro=0.7901, drzewa=60]




Trening klas:  29%|██▉       | 144/500 [20:31<33:33,  5.66s/klasa, klasa=class_143, F1_klasy=0.7105, F1_macro=0.7901, drzewa=60]

[88]	valid_0's binary_logloss: 0.0457341
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.0457191
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.0458314
[1]	valid_0's binary_logloss: 0.0426441
[2]	valid_0's binary_logloss: 0.0393752
[3]	valid_0's binary_logloss: 0.0371841
[4]	valid_0's binary_logloss: 0.0353764
[5]	valid_0's binary_logloss: 0.0336227
[6]	valid_0's binary_logloss: 0.0322298
[7]	valid_0's binary_logloss: 0.0310112
[8]	valid_0's binary_logloss: 0.0299379
[9]	valid_0's binary_logloss: 0.0289476
[10]	valid_0's binary_logloss: 0.0280857
[11]	valid_0's binary_logloss: 0.0272265
[12]	valid_0's binary_logloss: 0.026392
[13]	valid_0's binary_logloss: 0.0256
[14]	valid_0's binary_logloss: 0.024929
[15]	valid_0's binary_logloss: 0.0243353
[16]	valid_0's binary_logloss: 0.0238774
[17]	valid_0's binary_logloss: 0.0233634
[18]	valid_0's binary_logloss: 0.0228735
[19]	valid_0's binary_logloss: 0.0219496
[20]	valid_0's binary_logloss: 0.0212926
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0208346
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0204272
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.0203376
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0200082
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.0196882
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.0196517
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.0196394
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.0197021
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.0187886
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.0179747
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.0172317
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.0165349
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.0159061
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.0156364
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.0154368
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.015481
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.0155013
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.0155664
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.0156529
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.0158071
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.015241
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.0151572
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.0150859
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.0149855
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.0149251
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.0149513
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.0152621
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.0156328
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.0155611
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.0157147
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.0155614
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.015088
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.014663
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.0142313
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.0138474
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.0134167
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.0130015
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.0132642
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.0134696
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.0136735
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.0133186
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.013739
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.0133902
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.0130299
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.0127319
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.0123981
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.0114959
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.0107611
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.01047
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.0101707
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.0102587
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.010272
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.0100589
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.00965579
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.00968197
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.00939615
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.00912188
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.00886337
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.00864298
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.00868303
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.00844498
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.0081054
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.00816596
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.00797062
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.00781677
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.00760467
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.00736828
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.00719446
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.00700783
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.0069256
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.00668052
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.00644254
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.0062449
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.00602675
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.00597464
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.00600876
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.00590169
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.00575534
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.00560589
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.00545304
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.00536249
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.00526214
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.00513791
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.00505171
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.0049872
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.00489008
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.00482394
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.00471233
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.0046305
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.00466171
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.00460268
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 0.00455787
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 0.00450614
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 0.00447422
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 0.00438605
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[116]	valid_0's binary_logloss: 0.00431911
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[117]	valid_0's binary_logloss: 0.00422664
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[118]	valid_0's binary_logloss: 0.00416155
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[119]	valid_0's binary_logloss: 0.00411232
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[120]	valid_0's binary_logloss: 0.0040632
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[121]	valid_0's binary_logloss: 0.00400982
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[122]	valid_0's binary_logloss: 0.00402785
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[123]	valid_0's binary_logloss: 0.00403151
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[124]	valid_0's binary_logloss: 0.00404392
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[125]	valid_0's binary_logloss: 0.00402673
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[126]	valid_0's binary_logloss: 0.00393699
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[127]	valid_0's binary_logloss: 0.00397664
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[128]	valid_0's binary_logloss: 0.00391071
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[129]	valid_0's binary_logloss: 0.00384907
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[130]	valid_0's binary_logloss: 0.00378557
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[131]	valid_0's binary_logloss: 0.00373119
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[132]	valid_0's binary_logloss: 0.0036765
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[133]	valid_0's binary_logloss: 0.00362439
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[134]	valid_0's binary_logloss: 0.00368014
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[135]	valid_0's binary_logloss: 0.00362612
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[136]	valid_0's binary_logloss: 0.00361642
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[137]	valid_0's binary_logloss: 0.00359426
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[138]	valid_0's binary_logloss: 0.00356531
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[139]	valid_0's binary_logloss: 0.00353965
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[140]	valid_0's binary_logloss: 0.00350793
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[141]	valid_0's binary_logloss: 0.0034167
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[142]	valid_0's binary_logloss: 0.00336442
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[143]	valid_0's binary_logloss: 0.0033551
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[144]	valid_0's binary_logloss: 0.00337426
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[145]	valid_0's binary_logloss: 0.00338478
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[146]	valid_0's binary_logloss: 0.00339236
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[147]	valid_0's binary_logloss: 0.00336189
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[148]	valid_0's binary_logloss: 0.00333618
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[149]	valid_0's binary_logloss: 0.00333001
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[150]	valid_0's binary_logloss: 0.00330884
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[151]	valid_0's binary_logloss: 0.00332977
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[152]	valid_0's binary_logloss: 0.00332205
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[153]	valid_0's binary_logloss: 0.00331488
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[154]	valid_0's binary_logloss: 0.00329722
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[155]	valid_0's binary_logloss: 0.00327497
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[156]	valid_0's binary_logloss: 0.00324301
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[157]	valid_0's binary_logloss: 0.00323738
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[158]	valid_0's binary_logloss: 0.00321727
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[159]	valid_0's binary_logloss: 0.00319126
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[160]	valid_0's binary_logloss: 0.00316749
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[161]	valid_0's binary_logloss: 0.00315651
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[162]	valid_0's binary_logloss: 0.00319118
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[163]	valid_0's binary_logloss: 0.00317384
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[164]	valid_0's binary_logloss: 0.0031666
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[165]	valid_0's binary_logloss: 0.00316151
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[166]	valid_0's binary_logloss: 0.00318519
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[167]	valid_0's binary_logloss: 0.00320448
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[168]	valid_0's binary_logloss: 0.00322456
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[169]	valid_0's binary_logloss: 0.0032119
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[170]	valid_0's binary_logloss: 0.00323953
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[171]	valid_0's binary_logloss: 0.00322369
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[172]	valid_0's binary_logloss: 0.00323097
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[173]	valid_0's binary_logloss: 0.00323062
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[174]	valid_0's binary_logloss: 0.00323771
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[175]	valid_0's binary_logloss: 0.00320655
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[176]	valid_0's binary_logloss: 0.00322238
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[177]	valid_0's binary_logloss: 0.00322431
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[178]	valid_0's binary_logloss: 0.00326626
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[179]	valid_0's binary_logloss: 0.00324647
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[180]	valid_0's binary_logloss: 0.00326384
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[181]	valid_0's binary_logloss: 0.00326106

Trening klas:  29%|██▉       | 144/500 [20:36<33:33,  5.66s/klasa, klasa=class_144, F1_klasy=0.9440, F1_macro=0.7912, drzewa=161]




Trening klas:  29%|██▉       | 145/500 [20:36<32:10,  5.44s/klasa, klasa=class_144, F1_klasy=0.9440, F1_macro=0.7912, drzewa=161]

[1]	valid_0's binary_logloss: 0.0646523
[2]	valid_0's binary_logloss: 0.0608562
[3]	valid_0's binary_logloss: 0.0581838
[4]	valid_0's binary_logloss: 0.0560925
[5]	valid_0's binary_logloss: 0.0544245
[6]	valid_0's binary_logloss: 0.0527725
[7]	valid_0's binary_logloss: 0.0514192
[8]	valid_0's binary_logloss: 0.0500824
[9]	valid_0's binary_logloss: 0.0488687
[10]	valid_0's binary_logloss: 0.0477285
[11]	valid_0's binary_logloss: 0.0466115
[12]	valid_0's binary_logloss: 0.0456628
[13]	valid_0's binary_logloss: 0.0447666
[14]	valid_0's binary_logloss: 0.0441007
[15]	valid_0's binary_logloss: 0.0434556
[16]	valid_0's binary_logloss: 0.0427811
[17]	valid_0's binary_logloss: 0.0421238
[18]	valid_0's binary_logloss: 0.0414953
[19]	valid_0's binary_logloss: 0.0407903
[20]	valid_0's binary_logloss: 0.0402915
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0397302
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0390218
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.0385632
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0382314
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.0379182
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.0374667
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.0371325
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.0368947
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.0365561
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.0362429
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.0357675
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.0355878
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.035258
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.034975
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.0345685
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.0343045
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.0342004
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.0339693
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.0335535
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.0333716
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.0331036
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.0328358
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.0326205
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.0325037
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.0324477
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.0324031
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.0322574
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.0322351
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.0321829
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.0321529
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.0319351
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.0316563
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.0315454
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.0313902
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.0311953
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.0310729
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.0308549
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.0307606
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.0305797
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.0304428
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.0303048
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.0302613
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.0303479
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.0303805
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.030317
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.0302055
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.0303267
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.0302889
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.0301307
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.0300229
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.0299263
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.0298122
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.0297528
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.0293909
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.0292287
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.0290058
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.0289798
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.0289837
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.0290121
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.0289557
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.0289946
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.0289549
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.0289066
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.0289519
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.0289796
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.0289433
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.0290618
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.0290887
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.0290734
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.0291203
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.0289606
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.0288511
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.0288066
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.028953
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.029177
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.0290858
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.0291384
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.029234
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.0293665
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.0295633
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.0296094
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.0296598
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.0296918
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.029778
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.0298562
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.0298281
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.0297094
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.0296971
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.0298203
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.029784
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.0298153
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 0.029893
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 0.0298667
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 0.0299402
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 0.0299698
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[116]	valid_0's binary_logloss: 0.0298754
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[117]	valid_0's binary_logloss: 0.0299787
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[118]	valid_0's binary_logloss: 0.0299336
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[119]	valid_0's binary_logloss: 0.0298767
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[120]	valid_0's binary_logloss: 0.0298773
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[121]	valid_0's binary_logloss: 0.0299579

Trening klas:  29%|██▉       | 145/500 [20:42<32:10,  5.44s/klasa, klasa=class_145, F1_klasy=0.6852, F1_macro=0.7905, drzewa=93]




Trening klas:  29%|██▉       | 146/500 [20:42<32:18,  5.48s/klasa, klasa=class_145, F1_klasy=0.6852, F1_macro=0.7905, drzewa=93]

[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[122]	valid_0's binary_logloss: 0.0299357
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[123]	valid_0's binary_logloss: 0.0299153
[1]	valid_0's binary_logloss: 0.134973
[2]	valid_0's binary_logloss: 0.132042
[3]	valid_0's binary_logloss: 0.129428
[4]	valid_0's binary_logloss: 0.127724
[5]	valid_0's binary_logloss: 0.126176
[6]	valid_0's binary_logloss: 0.12505
[7]	valid_0's binary_logloss: 0.124404
[8]	valid_0's binary_logloss: 0.123645
[9]	valid_0's binary_logloss: 0.123233
[10]	valid_0's binary_logloss: 0.122978
[11]	valid_0's binary_logloss: 0.123178
[12]	valid_0's binary_logloss: 0.122761
[13]	valid_0's binary_logloss: 0.122281
[14]	valid_0's binary_logloss: 0.121954
[15]	valid_0's binary_logloss: 0.121949
[16]	valid_0's binary_logloss: 0.121788
[17]	valid_0's binary_logloss: 0.12178
[18]	valid_0's binary_logloss: 0.121541
[19]	valid_0's binary_logloss: 0.121272
[20]	valid_0's binary_logloss: 0.121359
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.121288
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.121288
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.121466
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.12151
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.121775
[26]	valid_0's binary_logloss: 0.12195
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.122015
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.12216
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.122288
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.122658
[31]	valid_0's binary_logloss: 0.122579
[32]	valid_0's binary_logloss: 0.122631
[33]	valid_0's binary_logloss: 0.122953
[34]	valid_0's binary_logloss: 0.123129
[35]	valid_0's binary_logloss: 0.122917
[36]	valid_0's binary_logloss: 0.122314
[37]	valid_0's binary_logloss: 0.122417
[38]	valid_0's binary_logloss: 0.122413
[39]	valid_0's binary_logloss: 0.122079
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.122132
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.122485
[42]	valid_0's binary_logloss: 0.122764
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.123106
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.12354
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.123921
[46]	valid_0's binary_logloss: 0.124142
[47]	valid_0's binary_logloss: 0.124245
[48]	valid_0's binary_logloss: 0.124421

Trening klas:  29%|██▉       | 146/500 [20:45<32:18,  5.48s/klasa, klasa=class_146, F1_klasy=0.5198, F1_macro=0.7886, drzewa=19]




Trening klas:  29%|██▉       | 147/500 [20:45<28:43,  4.88s/klasa, klasa=class_146, F1_klasy=0.5198, F1_macro=0.7886, drzewa=19]

[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.124676
[1]	valid_0's binary_logloss: 0.145782
[2]	valid_0's binary_logloss: 0.142756
[3]	valid_0's binary_logloss: 0.140321
[4]	valid_0's binary_logloss: 0.137932
[5]	valid_0's binary_logloss: 0.135642
[6]	valid_0's binary_logloss: 0.136051
[7]	valid_0's binary_logloss: 0.13459
[8]	valid_0's binary_logloss: 0.133352
[9]	valid_0's binary_logloss: 0.132255
[10]	valid_0's binary_logloss: 0.131318
[11]	valid_0's binary_logloss: 0.129911
[12]	valid_0's binary_logloss: 0.128883
[13]	valid_0's binary_logloss: 0.127828
[14]	valid_0's binary_logloss: 0.126869
[15]	valid_0's binary_logloss: 0.125854
[16]	valid_0's binary_logloss: 0.124772
[17]	valid_0's binary_logloss: 0.123854
[18]	valid_0's binary_logloss: 0.123511
[19]	valid_0's binary_logloss: 0.122851
[20]	valid_0's binary_logloss: 0.122226
[21]	valid_0's binary_logloss: 0.121337
[22]	valid_0's binary_logloss: 0.120405
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.119254
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.118773
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.117929
[26]	valid_0's binary_logloss: 0.117715
[27]	valid_0's binary_logloss: 0.117492
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.11729
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.116948
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.116551
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.116279
[32]	valid_0's binary_logloss: 0.116146
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.116002
[34]	valid_0's binary_logloss: 0.115792
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.115814
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.11564
[37]	valid_0's binary_logloss: 0.115332
[38]	valid_0's binary_logloss: 0.115258
[39]	valid_0's binary_logloss: 0.114839
[40]	valid_0's binary_logloss: 0.114627
[41]	valid_0's binary_logloss: 0.114447
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.114357
[43]	valid_0's binary_logloss: 0.114052
[44]	valid_0's binary_logloss: 0.113958
[45]	valid_0's binary_logloss: 0.114111
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.114419
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.114483
[48]	valid_0's binary_logloss: 0.114179
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.114301
[50]	valid_0's binary_logloss: 0.114075
[51]	valid_0's binary_logloss: 0.113864
[52]	valid_0's binary_logloss: 0.113804
[53]	valid_0's binary_logloss: 0.113574
[54]	valid_0's binary_logloss: 0.113448
[55]	valid_0's binary_logloss: 0.113754
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.114001
[57]	valid_0's binary_logloss: 0.114083
[58]	valid_0's binary_logloss: 0.11416
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.114357
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.114388
[61]	valid_0's binary_logloss: 0.114242
[62]	valid_0's binary_logloss: 0.114279
[63]	valid_0's binary_logloss: 0.114368
[64]	valid_0's binary_logloss: 0.114708
[65]	valid_0's binary_logloss: 0.114572
[66]	valid_0's binary_logloss: 0.114099
[67]	valid_0's binary_logloss: 0.114139
[68]	valid_0's binary_logloss: 0.114204
[69]	valid_0's binary_logloss: 0.114349
[70]	valid_0's binary_logloss: 0.114814
[71]	valid_0's binary_logloss: 0.114993
[72]	valid_0's binary_logloss: 0.114778
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.114663
[74]	valid_0's binary_logloss: 0.114678
[75]	valid_0's binary_logloss: 0.11465
[76]	valid_0's binary_logloss: 0.114645
[77]	valid_0's binary_logloss: 0.114876
[78]	valid_0's binary_logloss: 0.114929
[79]	valid_0's binary_logloss: 0.115314
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.1157
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

Trening klas:  29%|██▉       | 147/500 [20:50<28:43,  4.88s/klasa, klasa=class_147, F1_klasy=0.6092, F1_macro=0.7874, drzewa=54]




Trening klas:  30%|██▉       | 148/500 [20:50<28:56,  4.93s/klasa, klasa=class_147, F1_klasy=0.6092, F1_macro=0.7874, drzewa=54]

[81]	valid_0's binary_logloss: 0.115945
[82]	valid_0's binary_logloss: 0.115948
[83]	valid_0's binary_logloss: 0.116071
[84]	valid_0's binary_logloss: 0.116161
[1]	valid_0's binary_logloss: 0.052858
[2]	valid_0's binary_logloss: 0.0496008
[3]	valid_0's binary_logloss: 0.047108
[4]	valid_0's binary_logloss: 0.0450502
[5]	valid_0's binary_logloss: 0.0433041
[6]	valid_0's binary_logloss: 0.0418536
[7]	valid_0's binary_logloss: 0.0405823
[8]	valid_0's binary_logloss: 0.039258
[9]	valid_0's binary_logloss: 0.0381039
[10]	valid_0's binary_logloss: 0.0371666
[11]	valid_0's binary_logloss: 0.0363236
[12]	valid_0's binary_logloss: 0.0354684
[13]	valid_0's binary_logloss: 0.0346653
[14]	valid_0's binary_logloss: 0.0338369
[15]	valid_0's binary_logloss: 0.0331229
[16]	valid_0's binary_logloss: 0.0323171
[17]	valid_0's binary_logloss: 0.0317042
[18]	valid_0's binary_logloss: 0.0311563
[19]	valid_0's binary_logloss: 0.0307072
[20]	valid_0's binary_logloss: 0.0299976
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0295345
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0291541
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.0285411
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0281176
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.0276935
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.0275362
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.0273958
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.0272666
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.0271062
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.0269265
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.0266061
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.0262293
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.0258315
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.0255895
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.0252864
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.0249502
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.024674
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.0245039
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.0245024
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.0243418
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.0244194
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.0245281
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.0244601
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.024422
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.0243945
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.0244763
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.0244107
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.0241613
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.0240405
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.0239308
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.0238341
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.0237077
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.0235668
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.0235187
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.0234832
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.0234426
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.0233869
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.0233242
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.0232226
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.0233281
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.0232596
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.0232819
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.0231116
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.0231208
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.0230977
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.0228632
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.0228408
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.0228324
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.022828
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.0227254
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.0227183
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.0226263
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.022644
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.0225782
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.022659
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.0225298
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.0224637
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.022338
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.0223214
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.0222961
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.0222771
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.0222958
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.0223835
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.0223622
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.022474
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.0225435
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.0226053
[88]	valid_0's binary_logloss: 0.0224906
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.0225001
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.0225822
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.0225291
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.0225804
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.0225318
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.0225593
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.0225363
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.0226474
[97]	valid_0's binary_logloss: 0.0227604
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.0228707
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.0230225
[100]	valid_0's binary_logloss: 0.0231957
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.0231663
[102]	valid_0's binary_logloss: 0.0231238
[103]	valid_0's binary_logloss: 0.0230781
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.0230383
[105]	valid_0's binary_logloss: 0.0230141
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.023044
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.0230719
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.0230428
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

Trening klas:  30%|██▉       | 148/500 [20:55<28:56,  4.93s/klasa, klasa=class_148, F1_klasy=0.7238, F1_macro=0.7870, drzewa=81]




Trening klas:  30%|██▉       | 149/500 [20:55<29:23,  5.02s/klasa, klasa=class_148, F1_klasy=0.7238, F1_macro=0.7870, drzewa=81]

[109]	valid_0's binary_logloss: 0.0229789
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.0229423
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.0230307
[1]	valid_0's binary_logloss: 0.0380618
[2]	valid_0's binary_logloss: 0.03661
[3]	valid_0's binary_logloss: 0.0352295
[4]	valid_0's binary_logloss: 0.0339875
[5]	valid_0's binary_logloss: 0.0327155
[6]	valid_0's binary_logloss: 0.0316443
[7]	valid_0's binary_logloss: 0.0306934
[8]	valid_0's binary_logloss: 0.0297137
[9]	valid_0's binary_logloss: 0.02887
[10]	valid_0's binary_logloss: 0.0281357
[11]	valid_0's binary_logloss: 0.0273324
[12]	valid_0's binary_logloss: 0.0266994
[13]	valid_0's binary_logloss: 0.0259406
[14]	valid_0's binary_logloss: 0.0253059
[15]	valid_0's binary_logloss: 0.0247229
[16]	valid_0's binary_logloss: 0.0241784
[17]	valid_0's binary_logloss: 0.0236092
[18]	valid_0's binary_logloss: 0.0231513
[19]	valid_0's binary_logloss: 0.0226483
[20]	valid_0's binary_logloss: 0.0222238
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0218081
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.021438
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.0210804
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.020782
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.0203897
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.0199902
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.0196709
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.0192501
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.0189448
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.0185647
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.018314
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.0180316
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.017738
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.0175486
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.0174339
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.0172353
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.0170469
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.0168509
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.0165903
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.0163463
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.0161104
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.0158873
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.0156768
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.0155095
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.0153337
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.0152941
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.0151564
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.0150055
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.0148991
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.0147981
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.0146871
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.0145579
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.0144372
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.0143163
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.0141539
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.0140216
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.0139077
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.0138247
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.0137943
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.0138412
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.0138206
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.0138083
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.0138146
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.0138069
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.0137841
[66]	valid_0's binary_logloss: 0.013751
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.0137101
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.0136245
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.0135981
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.0135049
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.0134256
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.0134231
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.0134667
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.0134811
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.013536
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.0134651
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.0134287
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.0134571
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.0134998
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.0134409
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.0134845
[82]	valid_0's binary_logloss: 0.0134214
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.013414
[84]	valid_0's binary_logloss: 0.013411
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.013381
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.0133935
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.0134434
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.0134127
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.0134947
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.0135359
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.0135866
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.0136475
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.0136599
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.0136893
[95]	valid_0's binary_logloss: 0.0137796
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.0138222
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.0138776
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.0139007
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.0139442
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.0140428
[101]	valid_0's binary_logloss: 0.0140685
[102]	valid_0's binary_logloss: 0.0141501
[103]	valid_0's binary_logloss: 0.0141538
[104]	valid_0's binary_logloss: 0.0141839
[105]	valid_0's binary_logloss: 0.0142308
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.0142544
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.0143243
[108]	valid_0's binary_logloss: 0.0144064
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.0144882
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.0144768
[111]	valid_0's binary_logloss: 0.0145491
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

Trening klas:  30%|██▉       | 149/500 [21:02<29:23,  5.02s/klasa, klasa=class_149, F1_klasy=0.5079, F1_macro=0.7851, drzewa=85]




Trening klas:  30%|███       | 150/500 [21:02<31:33,  5.41s/klasa, klasa=class_149, F1_klasy=0.5079, F1_macro=0.7851, drzewa=85]

[112]	valid_0's binary_logloss: 0.0146252
[113]	valid_0's binary_logloss: 0.0147275
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 0.014804
[115]	valid_0's binary_logloss: 0.0148717
[1]	valid_0's binary_logloss: 0.0474359
[2]	valid_0's binary_logloss: 0.0460505
[3]	valid_0's binary_logloss: 0.044787
[4]	valid_0's binary_logloss: 0.0437098
[5]	valid_0's binary_logloss: 0.0427587
[6]	valid_0's binary_logloss: 0.0417419
[7]	valid_0's binary_logloss: 0.0408407
[8]	valid_0's binary_logloss: 0.0398966
[9]	valid_0's binary_logloss: 0.0391347
[10]	valid_0's binary_logloss: 0.0384353
[11]	valid_0's binary_logloss: 0.0377711
[12]	valid_0's binary_logloss: 0.0371383
[13]	valid_0's binary_logloss: 0.0365416
[14]	valid_0's binary_logloss: 0.0359568
[15]	valid_0's binary_logloss: 0.0355738
[16]	valid_0's binary_logloss: 0.035283
[17]	valid_0's binary_logloss: 0.0347304
[18]	valid_0's binary_logloss: 0.0344444
[19]	valid_0's binary_logloss: 0.0340053
[20]	valid_0's binary_logloss: 0.0338251
[21]	valid_0's binary_logloss: 0.0334683
[22]	valid_0's binary_logloss: 0.0330986
[23]	valid_0's binary_logloss: 0.0327967
[24]	valid_0's binary_logloss: 0.0324259
[25]	valid_0's binary_logloss: 0.0321304
[26]	valid_0's binary_logloss: 0.0317411
[27]	valid_0's binary_logloss: 0.0314057
[28]	valid_0's binary_logloss: 0.0310797
[29]	valid_0's binary_logloss: 0.0307562
[30]	valid_0's binary_logloss: 0.0304725
[31]	valid_0's binary_logloss: 0.0302243
[32]	valid_0's binary_logloss: 0.0300117
[33]	valid_0's binary_logloss: 0.0298787
[34]	valid_0's binary_logloss: 0.0297497
[35]	valid_0's binary_logloss: 0.0295678
[36]	valid_0's binary_logloss: 0.0293405
[37]	valid_0's binary_logloss: 0.0291282
[38]	valid_0's binary_logloss: 0.0288891
[39]	valid_0's binary_logloss: 0.0285559
[40]	valid_0's binary_logloss: 0.0284282
[41]	valid_0's binary_logloss: 0.0281862
[42]	valid_0's binary_logloss: 0.0279422
[43]	valid_0's binary_logloss: 0.0276781
[44]	valid_0's binary_logloss: 0.0274958
[45]	valid_0's binary_logloss: 0.0275588
[46]	valid_0's binary_logloss: 0.0274941
[47]	valid_0's binary_logloss: 0.0272724
[48]	valid_0's binary_logloss: 0.0270733
[49]	valid_0's binary_logloss: 0.0269513
[50]	valid_0's binary_logloss: 0.0268144
[51]	valid_0's binary_logloss: 0.026764
[52]	valid_0's binary_logloss: 0.0265998
[53]	valid_0's binary_logloss: 0.0265374
[54]	valid_0's binary_logloss: 0.0264971
[55]	valid_0's binary_logloss: 0.0263597
[56]	valid_0's binary_logloss: 0.0262448
[57]	valid_0's binary_logloss: 0.0260803
[58]	valid_0's binary_logloss: 0.0259984
[59]	valid_0's binary_logloss: 0.025964
[60]	valid_0's binary_logloss: 0.0258194
[61]	valid_0's binary_logloss: 0.0257631
[62]	valid_0's binary_logloss: 0.0256355
[63]	valid_0's binary_logloss: 0.0257076
[64]	valid_0's binary_logloss: 0.025716
[65]	valid_0's binary_logloss: 0.0256416
[66]	valid_0's binary_logloss: 0.0255183
[67]	valid_0's binary_logloss: 0.0254709
[68]	valid_0's binary_logloss: 0.0254605
[69]	valid_0's binary_logloss: 0.0254482
[70]	valid_0's binary_logloss: 0.0254045
[71]	valid_0's binary_logloss: 0.0253822
[72]	valid_0's binary_logloss: 0.0254238
[73]	valid_0's binary_logloss: 0.0253455
[74]	valid_0's binary_logloss: 0.0254136
[75]	valid_0's binary_logloss: 0.0255173
[76]	valid_0's binary_logloss: 0.0256062
[77]	valid_0's binary_logloss: 0.0256173
[78]	valid_0's binary_logloss: 0.0257127
[79]	valid_0's binary_logloss: 0.0258374
[80]	valid_0's binary_logloss: 0.0259338
[81]	valid_0's binary_logloss: 0.0259192
[82]	valid_0's binary_logloss: 0.0259908
[83]	valid_0's binary_logloss: 0.0260887
[84]	valid_0's binary_logloss: 0.0261195
[85]	valid_0's binary_logloss: 0.0262214
[86]	valid_0's binary_logloss: 0.0261838
[87]	valid_0's binary_logloss: 0.026133
[88]	valid_0's binary_logloss: 0.0261951
[89]	valid_0's binary_logloss: 0.0263065
[90]	valid_0's binary_logloss: 0.0264316
[91]	valid_0's binary_logloss: 0.0264426
[92]	valid_0's binary_logloss: 0.0264172
[93]	valid_0's binary_logloss: 0.0263931
[94]	valid_0's binary_logloss: 0.0264127
[95]	valid_0's binary_logloss: 0.0264131
[96]	valid_0's binary_logloss: 0.0266176
[97]	valid_0's binary_logloss: 0.0266565
[98]	valid_0's binary_logloss: 0.026856
[99]	valid_0's binary_logloss: 0.0269242
[100]	valid_0's binary_logloss: 0.0270205
[101]	valid_0's binary_logloss: 0.0271239
[102]	valid_0's binary_logloss: 0.0272452
[103]	valid_0's binary_logloss: 0.0272428

Trening klas:  30%|███       | 150/500 [21:09<31:33,  5.41s/klasa, klasa=class_150, F1_klasy=0.4681, F1_macro=0.7830, drzewa=73]




Trening klas:  30%|███       | 151/500 [21:09<34:58,  6.01s/klasa, klasa=class_150, F1_klasy=0.4681, F1_macro=0.7830, drzewa=73]

[1]	valid_0's binary_logloss: 0.0627067
[2]	valid_0's binary_logloss: 0.059185
[3]	valid_0's binary_logloss: 0.0565463
[4]	valid_0's binary_logloss: 0.0544967
[5]	valid_0's binary_logloss: 0.0526833
[6]	valid_0's binary_logloss: 0.0511276
[7]	valid_0's binary_logloss: 0.0498987
[8]	valid_0's binary_logloss: 0.0486338
[9]	valid_0's binary_logloss: 0.0473983
[10]	valid_0's binary_logloss: 0.0466234
[11]	valid_0's binary_logloss: 0.0458522
[12]	valid_0's binary_logloss: 0.044959
[13]	valid_0's binary_logloss: 0.0443205
[14]	valid_0's binary_logloss: 0.0436515
[15]	valid_0's binary_logloss: 0.0432985
[16]	valid_0's binary_logloss: 0.0427537
[17]	valid_0's binary_logloss: 0.0422862
[18]	valid_0's binary_logloss: 0.0418859
[19]	valid_0's binary_logloss: 0.041466
[20]	valid_0's binary_logloss: 0.0407953
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0402867
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0397971
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.0393315
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0384832
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.0380258
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.0376483
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.0374039
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.0368857
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.0366642
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.0364146
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.0360014
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.0358232
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.0355187
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.0353202
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.0350267
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.0349925
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.0347643
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.0346915
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.0344462
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.034179
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.0341587
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.0340449
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.0339637
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.0338567
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.0337226
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.0335379
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.0333125
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.0329958
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.0327052
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.0322865
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.0321804
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.0319323
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.0317462
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.0315488
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.0314266
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.0311881
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.0309628
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.0308451
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.0306037
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.0304262
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.0301829
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.0302342
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.0301602
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.0302957
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.0302586
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.0301978
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.0300106
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.0298985
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.0297534
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.0297016
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.0296072
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.029577
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.0294225
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.0294681
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.0295031
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.0293072
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.0292967
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.0293842
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.029476
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.0295014
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.0294675
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.0292941
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.029187
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.028973
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.0290119
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.0289605
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.0289465
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.0288041
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.0288754
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.0288327
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.0287096
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.0286491
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.0285413
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.0283941
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.0284143
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.0283479
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.028279
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.0282527
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.0282187
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.0280819
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.0280475
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.0281202
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.028184
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.0282393
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.0281905
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.0281246
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.0280522
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.02794
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.0277803
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.0277257
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.0277386
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 0.0277232
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 0.0277223
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 0.0276863
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 0.0277224
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[116]	valid_0's binary_logloss: 0.027685
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[117]	valid_0's binary_logloss: 0.0276771
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[118]	valid_0's binary_logloss: 0.0276696
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[119]	valid_0's binary_logloss: 0.0275248
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[120]	valid_0's binary_logloss: 0.0276155
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[121]	valid_0's binary_logloss: 0.0275681
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[122]	valid_0's binary_logloss: 0.0275803
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[123]	valid_0's binary_logloss: 0.0275762
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[124]	valid_0's binary_logloss: 0.0275789
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[125]	valid_0's binary_logloss: 0.027576
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[126]	valid_0's binary_logloss: 0.0276346
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[127]	valid_0's binary_logloss: 0.0275687
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[128]	valid_0's binary_logloss: 0.0275605
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[129]	valid_0's binary_logloss: 0.0275383
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[130]	valid_0's binary_logloss: 0.0275499
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[131]	valid_0's binary_logloss: 0.0275449
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[132]	valid_0's binary_logloss: 0.0276025
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[133]	valid_0's binary_logloss: 0.0276215
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[134]	valid_0's binary_logloss: 0.0277016
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[135]	valid_0's binary_logloss: 0.0276929
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[136]	valid_0's binary_logloss: 0.0276651
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[137]	valid_0's binary_logloss: 0.027558
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[138]	valid_0's binary_logloss: 0.0276185
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[139]	valid_0's binary_logloss: 0.0274971
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[140]	valid_0's binary_logloss: 0.0275897
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[141]	valid_0's binary_logloss: 0.0275503
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[142]	valid_0's binary_logloss: 0.0275503
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[143]	valid_0's binary_logloss: 0.0275225
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[144]	valid_0's binary_logloss: 0.0275563
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[145]	valid_0's binary_logloss: 0.027596
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[146]	valid_0's binary_logloss: 0.0276526
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[147]	valid_0's binary_logloss: 0.0276389
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[148]	valid_0's binary_logloss: 0.0276913
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[149]	valid_0's binary_logloss: 0.0276767
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[150]	valid_0's binary_logloss: 0.027727
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[151]	valid_0's binary_logloss: 0.0277696
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[152]	valid_0's binary_logloss: 0.0278094
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[153]	valid_0's binary_logloss: 0.0278361
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[154]	valid_0's binary_logloss: 0.0279099
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[155]	valid_0's binary_logloss: 0.0279152
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[156]	valid_0's binary_logloss: 0.0279057
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[157]	valid_0's binary_logloss: 0.0278189
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[158]	valid_0's binary_logloss: 0.0277524
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[159]	valid_0's binary_logloss: 0.0276834
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[160]	valid_0's binary_logloss: 0.0277338
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[161]	valid_0's binary_logloss: 0.0278076
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[162]	valid_0's binary_logloss: 0.027841
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[163]	valid_0's binary_logloss: 0.0278668
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[164]	valid_0's binary_logloss: 0.0279247
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[165]	valid_0's binary_logloss: 0.0279944
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[166]	valid_0's binary_logloss: 0.0279663
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[167]	valid_0's binary_logloss: 0.0279555
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[168]	valid_0's binary_logloss: 0.0279486
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

Trening klas:  30%|███       | 151/500 [21:15<34:58,  6.01s/klasa, klasa=class_151, F1_klasy=0.7589, F1_macro=0.7829, drzewa=139]




Trening klas:  30%|███       | 152/500 [21:15<34:49,  6.00s/klasa, klasa=class_151, F1_klasy=0.7589, F1_macro=0.7829, drzewa=139]

[169]	valid_0's binary_logloss: 0.0279505
[1]	valid_0's binary_logloss: 0.119646
[2]	valid_0's binary_logloss: 0.118775
[3]	valid_0's binary_logloss: 0.117451
[4]	valid_0's binary_logloss: 0.116327
[5]	valid_0's binary_logloss: 0.115156
[6]	valid_0's binary_logloss: 0.117264
[7]	valid_0's binary_logloss: 0.116281
[8]	valid_0's binary_logloss: 0.115781
[9]	valid_0's binary_logloss: 0.115103
[10]	valid_0's binary_logloss: 0.114154
[11]	valid_0's binary_logloss: 0.114034
[12]	valid_0's binary_logloss: 0.113323
[13]	valid_0's binary_logloss: 0.113187
[14]	valid_0's binary_logloss: 0.112922
[15]	valid_0's binary_logloss: 0.112766
[16]	valid_0's binary_logloss: 0.112255
[17]	valid_0's binary_logloss: 0.111667
[18]	valid_0's binary_logloss: 0.111365
[19]	valid_0's binary_logloss: 0.111405
[20]	valid_0's binary_logloss: 0.111297
[21]	valid_0's binary_logloss: 0.110945
[22]	valid_0's binary_logloss: 0.110766
[23]	valid_0's binary_logloss: 0.11065
[24]	valid_0's binary_logloss: 0.110366
[25]	valid_0's binary_logloss: 0.109787
[26]	valid_0's binary_logloss: 0.109204
[27]	valid_0's binary_logloss: 0.109134
[28]	valid_0's binary_logloss: 0.108635
[29]	valid_0's binary_logloss: 0.108587
[30]	valid_0's binary_logloss: 0.108267
[31]	valid_0's binary_logloss: 0.107904
[32]	valid_0's binary_logloss: 0.107529
[33]	valid_0's binary_logloss: 0.107602
[34]	valid_0's binary_logloss: 0.107278
[35]	valid_0's binary_logloss: 0.107048
[36]	valid_0's binary_logloss: 0.106624
[37]	valid_0's binary_logloss: 0.10612
[38]	valid_0's binary_logloss: 0.10545
[39]	valid_0's binary_logloss: 0.105226
[40]	valid_0's binary_logloss: 0.105137
[41]	valid_0's binary_logloss: 0.104797
[42]	valid_0's binary_logloss: 0.104382
[43]	valid_0's binary_logloss: 0.104129
[44]	valid_0's binary_logloss: 0.103723
[45]	valid_0's binary_logloss: 0.103587
[46]	valid_0's binary_logloss: 0.103625
[47]	valid_0's binary_logloss: 0.103483
[48]	valid_0's binary_logloss: 0.103512
[49]	valid_0's binary_logloss: 0.103435
[50]	valid_0's binary_logloss: 0.103335
[51]	valid_0's binary_logloss: 0.10326
[52]	valid_0's binary_logloss: 0.102858
[53]	valid_0's binary_logloss: 0.102728
[54]	valid_0's binary_logloss: 0.102755
[55]	valid_0's binary_logloss: 0.102678
[56]	valid_0's binary_logloss: 0.102633
[57]	valid_0's binary_logloss: 0.10255
[58]	valid_0's binary_logloss: 0.102348
[59]	valid_0's binary_logloss: 0.102482
[60]	valid_0's binary_logloss: 0.102529
[61]	valid_0's binary_logloss: 0.10215
[62]	valid_0's binary_logloss: 0.102154
[63]	valid_0's binary_logloss: 0.101884
[64]	valid_0's binary_logloss: 0.101645
[65]	valid_0's binary_logloss: 0.101544
[66]	valid_0's binary_logloss: 0.101571
[67]	valid_0's binary_logloss: 0.101305
[68]	valid_0's binary_logloss: 0.101121
[69]	valid_0's binary_logloss: 0.100977
[70]	valid_0's binary_logloss: 0.100691
[71]	valid_0's binary_logloss: 0.100533
[72]	valid_0's binary_logloss: 0.100499
[73]	valid_0's binary_logloss: 0.100507
[74]	valid_0's binary_logloss: 0.100409
[75]	valid_0's binary_logloss: 0.100551
[76]	valid_0's binary_logloss: 0.100451
[77]	valid_0's binary_logloss: 0.100563
[78]	valid_0's binary_logloss: 0.100713
[79]	valid_0's binary_logloss: 0.10066
[80]	valid_0's binary_logloss: 0.100754
[81]	valid_0's binary_logloss: 0.101064
[82]	valid_0's binary_logloss: 0.101169
[83]	valid_0's binary_logloss: 0.100912
[84]	valid_0's binary_logloss: 0.100981
[85]	valid_0's binary_logloss: 0.100958
[86]	valid_0's binary_logloss: 0.100923
[87]	valid_0's binary_logloss: 0.100968
[88]	valid_0's binary_logloss: 0.101146
[89]	valid_0's binary_logloss: 0.101035
[90]	valid_0's binary_logloss: 0.101205
[91]	valid_0's binary_logloss: 0.101267
[92]	valid_0's binary_logloss: 0.10137
[93]	valid_0's binary_logloss: 0.101603
[94]	valid_0's binary_logloss: 0.101751
[95]	valid_0's binary_logloss: 0.101878
[96]	valid_0's binary_logloss: 0.101956
[97]	valid_0's binary_logloss: 0.101983
[98]	valid_0's binary_logloss: 0.102169
[99]	valid_0's binary_logloss: 0.102246
[100]	valid_0's binary_logloss: 0.102412
[101]	valid_0's binary_logloss: 0.102436
[102]	valid_0's binary_logloss: 0.102411
[103]	valid_0's binary_logloss: 0.102616

Trening klas:  30%|███       | 152/500 [21:22<34:49,  6.00s/klasa, klasa=class_152, F1_klasy=0.3821, F1_macro=0.7803, drzewa=74]




Trening klas:  31%|███       | 153/500 [21:22<36:48,  6.36s/klasa, klasa=class_152, F1_klasy=0.3821, F1_macro=0.7803, drzewa=74]

[104]	valid_0's binary_logloss: 0.102444
[1]	valid_0's binary_logloss: 0.0670733
[2]	valid_0's binary_logloss: 0.0625673
[3]	valid_0's binary_logloss: 0.0586075
[4]	valid_0's binary_logloss: 0.0555425
[5]	valid_0's binary_logloss: 0.0529537
[6]	valid_0's binary_logloss: 0.0508515
[7]	valid_0's binary_logloss: 0.0490681
[8]	valid_0's binary_logloss: 0.0476171
[9]	valid_0's binary_logloss: 0.0462868
[10]	valid_0's binary_logloss: 0.0450918
[11]	valid_0's binary_logloss: 0.04397
[12]	valid_0's binary_logloss: 0.0429127
[13]	valid_0's binary_logloss: 0.0418371
[14]	valid_0's binary_logloss: 0.0406295
[15]	valid_0's binary_logloss: 0.039566
[16]	valid_0's binary_logloss: 0.0388495
[17]	valid_0's binary_logloss: 0.0382107
[18]	valid_0's binary_logloss: 0.037537
[19]	valid_0's binary_logloss: 0.037031
[20]	valid_0's binary_logloss: 0.0364836
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.035872
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0354745
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.0350706
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0346184
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.0344185
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.0340732
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.0336903
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.0333547
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.0329531
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.0327103
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.0326362
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.0325627
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.0323675
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.0322751
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.0323065
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.0322073
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.0319595
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.0319533
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.0318721
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.0318992
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.0315719
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.0313725
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.0314216
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.0313644
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.0310794
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.0311212
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.0309813
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.0308243
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.0308381
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.030869
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.0307802
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.0306987
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.0306764
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.0306726
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.0304618
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.0306682
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.0307156
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.0307761
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.0309607
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.0306057
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.03052
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.0306239
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.0305204
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.0305483
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.0306337
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.030794
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.0305941
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.0306164
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.0307004
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.0306972
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.0307426
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.0307183
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.0307588
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.0308747
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.0308324
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.030921
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.0305866
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.0303838
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.0302745
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.0301363
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.0299799
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.0301103
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.0301629
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.0301234
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.0300761
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.0297722
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.0296642
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.0293547
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.0292489
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.0290774
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.0289054
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.0289061
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.028785
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.0287327
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.0287278
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.0285811
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.0282362
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.0280612
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.0278045
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.0275945
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.0273812
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.0272476
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.0269887
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.0269187
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.026691
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.0265449
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.0264834
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.0265549
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.0264671
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.0265172
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.0263142
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 0.0261764
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 0.0262115
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 0.0262245
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 0.0262473
[116]	valid_0's binary_logloss: 0.0262161
[117]	valid_0's binary_logloss: 0.0261355
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[118]	valid_0's binary_logloss: 0.0260481
[119]	valid_0's binary_logloss: 0.026026
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[120]	valid_0's binary_logloss: 0.0260132
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[121]	valid_0's binary_logloss: 0.0260613
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[122]	valid_0's binary_logloss: 0.0260423
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[123]	valid_0's binary_logloss: 0.0260833
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[124]	valid_0's binary_logloss: 0.0261045
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[125]	valid_0's binary_logloss: 0.026166
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[126]	valid_0's binary_logloss: 0.0262225
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[127]	valid_0's binary_logloss: 0.0261579
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[128]	valid_0's binary_logloss: 0.0262675
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[129]	valid_0's binary_logloss: 0.0262994
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[130]	valid_0's binary_logloss: 0.0264083
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[131]	valid_0's binary_logloss: 0.0265075
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[132]	valid_0's binary_logloss: 0.0265331
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[133]	valid_0's binary_logloss: 0.0266139
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[134]	valid_0's binary_logloss: 0.026718
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[135]	valid_0's binary_logloss: 0.0267492
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[136]	valid_0's binary_logloss: 0.026837
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[137]	valid_0's binary_logloss: 0.0269821
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[138]	valid_0's binary_logloss: 0.027106
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[139]	valid_0's binary_logloss: 0.0271026
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[140]	valid_0's binary_logloss: 0.0271371
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[141]	valid_0's binary_logloss: 0.0272786
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[142]	valid_0's binary_logloss: 0.0273831
[143]	valid_0's binary_logloss: 0.0273993
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[144]	valid_0's binary_logloss: 0.0274599
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[145]	valid_0's binary_logloss: 0.0274842
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[146]	valid_0's binary_logloss: 0.0275302
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[147]	valid_0's binary_logloss: 0.0276207
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[148]	valid_0's binary_logloss: 0.0276405
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[149]	valid_0's binary_logloss: 0.0277096
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[150]	valid_0's binary_logloss: 0.0277328

Trening klas:  31%|███       | 153/500 [21:28<36:48,  6.36s/klasa, klasa=class_153, F1_klasy=0.8584, F1_macro=0.7808, drzewa=120]




Trening klas:  31%|███       | 154/500 [21:28<35:14,  6.11s/klasa, klasa=class_153, F1_klasy=0.8584, F1_macro=0.7808, drzewa=120]

[1]	valid_0's binary_logloss: 0.0588351
[2]	valid_0's binary_logloss: 0.0553383
[3]	valid_0's binary_logloss: 0.053092
[4]	valid_0's binary_logloss: 0.0511031
[5]	valid_0's binary_logloss: 0.0495645
[6]	valid_0's binary_logloss: 0.0477872
[7]	valid_0's binary_logloss: 0.0463452
[8]	valid_0's binary_logloss: 0.0452023
[9]	valid_0's binary_logloss: 0.0442981
[10]	valid_0's binary_logloss: 0.0434148
[11]	valid_0's binary_logloss: 0.0425852
[12]	valid_0's binary_logloss: 0.04174
[13]	valid_0's binary_logloss: 0.0410648
[14]	valid_0's binary_logloss: 0.0403835
[15]	valid_0's binary_logloss: 0.039719
[16]	valid_0's binary_logloss: 0.0390408
[17]	valid_0's binary_logloss: 0.0385462
[18]	valid_0's binary_logloss: 0.037876
[19]	valid_0's binary_logloss: 0.0374605
[20]	valid_0's binary_logloss: 0.0368912
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0365095
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0360312
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.0357112
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0354848
[25]	valid_0's binary_logloss: 0.0352333
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.0347644
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.0344969
[28]	valid_0's binary_logloss: 0.0341895
[29]	valid_0's binary_logloss: 0.033907
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.0337046
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.0336597
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.0334091
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.0331589
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.0330996
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.0328758
[36]	valid_0's binary_logloss: 0.0327759
[37]	valid_0's binary_logloss: 0.0326884
[38]	valid_0's binary_logloss: 0.0326315
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.032517
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.0326171
[41]	valid_0's binary_logloss: 0.0324961
[42]	valid_0's binary_logloss: 0.0324044
[43]	valid_0's binary_logloss: 0.0323874
[44]	valid_0's binary_logloss: 0.0323117
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.0322896
[46]	valid_0's binary_logloss: 0.0322286
[47]	valid_0's binary_logloss: 0.0321505
[48]	valid_0's binary_logloss: 0.0321281
[49]	valid_0's binary_logloss: 0.0320053
[50]	valid_0's binary_logloss: 0.0319609
[51]	valid_0's binary_logloss: 0.0318778
[52]	valid_0's binary_logloss: 0.0318729
[53]	valid_0's binary_logloss: 0.0318674
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.0319356
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.0319589
[56]	valid_0's binary_logloss: 0.0318386
[57]	valid_0's binary_logloss: 0.0317343
[58]	valid_0's binary_logloss: 0.0317556
[59]	valid_0's binary_logloss: 0.0318282
[60]	valid_0's binary_logloss: 0.0318187
[61]	valid_0's binary_logloss: 0.031834
[62]	valid_0's binary_logloss: 0.0317958
[63]	valid_0's binary_logloss: 0.0318941
[64]	valid_0's binary_logloss: 0.0318685
[65]	valid_0's binary_logloss: 0.0318957
[66]	valid_0's binary_logloss: 0.0318551
[67]	valid_0's binary_logloss: 0.0317571
[68]	valid_0's binary_logloss: 0.0318973
[69]	valid_0's binary_logloss: 0.0320313
[70]	valid_0's binary_logloss: 0.0322116
[71]	valid_0's binary_logloss: 0.0321625
[72]	valid_0's binary_logloss: 0.0322015
[73]	valid_0's binary_logloss: 0.0323603
[74]	valid_0's binary_logloss: 0.0323979
[75]	valid_0's binary_logloss: 0.0323577
[76]	valid_0's binary_logloss: 0.0322409
[77]	valid_0's binary_logloss: 0.0322541
[78]	valid_0's binary_logloss: 0.032307
[79]	valid_0's binary_logloss: 0.0324394
[80]	valid_0's binary_logloss: 0.032563
[81]	valid_0's binary_logloss: 0.0327846
[82]	valid_0's binary_logloss: 0.0329774
[83]	valid_0's binary_logloss: 0.0329621
[84]	valid_0's binary_logloss: 0.0329624
[85]	valid_0's binary_logloss: 0.0332225
[86]	valid_0's binary_logloss: 0.0332474
[87]	valid_0's binary_logloss: 0.0332095

Trening klas:  31%|███       | 154/500 [21:34<35:14,  6.11s/klasa, klasa=class_154, F1_klasy=0.6161, F1_macro=0.7797, drzewa=57]




Trening klas:  31%|███       | 155/500 [21:34<34:13,  5.95s/klasa, klasa=class_154, F1_klasy=0.6161, F1_macro=0.7797, drzewa=57]

[1]	valid_0's binary_logloss: 0.0585203
[2]	valid_0's binary_logloss: 0.0554074
[3]	valid_0's binary_logloss: 0.0529751
[4]	valid_0's binary_logloss: 0.0508933
[5]	valid_0's binary_logloss: 0.0487915
[6]	valid_0's binary_logloss: 0.0472622
[7]	valid_0's binary_logloss: 0.045887
[8]	valid_0's binary_logloss: 0.0448618
[9]	valid_0's binary_logloss: 0.0434994
[10]	valid_0's binary_logloss: 0.0423623
[11]	valid_0's binary_logloss: 0.0414071
[12]	valid_0's binary_logloss: 0.0404572
[13]	valid_0's binary_logloss: 0.039701
[14]	valid_0's binary_logloss: 0.0389619
[15]	valid_0's binary_logloss: 0.0382321
[16]	valid_0's binary_logloss: 0.0376463
[17]	valid_0's binary_logloss: 0.0370836
[18]	valid_0's binary_logloss: 0.036591
[19]	valid_0's binary_logloss: 0.0361321
[20]	valid_0's binary_logloss: 0.035797
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0354607
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0349715
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.0345699
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0342394
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.0339546
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.0334116
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.0330665
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.0329177
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.0326988
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.0325249
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.0322787
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.03197
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.0314864
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.0310827
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.0306573
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.0303208
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.0301052
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.0299748
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.0298887
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.0294211
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.0292847
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.0291806
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.0291434
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.0290403
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.0289747
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.0286765
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.0284521
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.0282788
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.0281495
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.028048
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.0277526
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.0274627
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.0274371
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.0271904
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.0270028
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.0269457
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.026748
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.0265993
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.0265058
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.0263957
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.0263084
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.0261548
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.0261031
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.0260464
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.0258206
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.0258052
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.025777
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.0257852
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.0257338
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.0256527
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.0255689
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.0255044
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.0255167
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.0253926
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.0252586
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.0252903
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.0253223
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.0253699
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.0252715
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.0252367
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.0252591
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.0252002
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.0252696
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.025397
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.0254605
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.0254298
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.0252428
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.0251384
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.0249503
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.024715
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.024612
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.0246854
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.0247477
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.0247699
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.0247192
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.0245722
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.0245091
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.0244362
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.0244125
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.0244913
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.0246088
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.0247431
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.0246126
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.0245487
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.0244755
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.0245615
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.0245072
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.0245818
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.0246529
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.0245663
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.0247305
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 0.0246735
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 0.0247079
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 0.0248891
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 0.0249453
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[116]	valid_0's binary_logloss: 0.0251048
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[117]	valid_0's binary_logloss: 0.0251573
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[118]	valid_0's binary_logloss: 0.0252395
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[119]	valid_0's binary_logloss: 0.0252696
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[120]	valid_0's binary_logloss: 0.0254128
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[121]	valid_0's binary_logloss: 0.0255362
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[122]	valid_0's binary_logloss: 0.0255858
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[123]	valid_0's binary_logloss: 0.0255578
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[124]	valid_0's binary_logloss: 0.0255916
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[125]	valid_0's binary_logloss: 0.0256007
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[126]	valid_0's binary_logloss: 0.0254644
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[127]	valid_0's binary_logloss: 0.0254198
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[128]	valid_0's binary_logloss: 0.0253367
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[129]	valid_0's binary_logloss: 0.0251565

Trening klas:  31%|███       | 155/500 [21:38<34:13,  5.95s/klasa, klasa=class_155, F1_klasy=0.7875, F1_macro=0.7798, drzewa=99]




Trening klas:  31%|███       | 156/500 [21:38<30:49,  5.38s/klasa, klasa=class_155, F1_klasy=0.7875, F1_macro=0.7798, drzewa=99]

[1]	valid_0's binary_logloss: 0.0255974
[2]	valid_0's binary_logloss: 0.0245126
[3]	valid_0's binary_logloss: 0.0233824
[4]	valid_0's binary_logloss: 0.0223922
[5]	valid_0's binary_logloss: 0.021495
[6]	valid_0's binary_logloss: 0.0205715
[7]	valid_0's binary_logloss: 0.0196725
[8]	valid_0's binary_logloss: 0.0188764
[9]	valid_0's binary_logloss: 0.0180381
[10]	valid_0's binary_logloss: 0.0172571
[11]	valid_0's binary_logloss: 0.0165775
[12]	valid_0's binary_logloss: 0.0159189
[13]	valid_0's binary_logloss: 0.015338
[14]	valid_0's binary_logloss: 0.0147551
[15]	valid_0's binary_logloss: 0.0142103
[16]	valid_0's binary_logloss: 0.013642
[17]	valid_0's binary_logloss: 0.0131629
[18]	valid_0's binary_logloss: 0.0126407
[19]	valid_0's binary_logloss: 0.0121456
[20]	valid_0's binary_logloss: 0.0116978
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0112609
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0108638
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.0104673
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0100911
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.0097328
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.0094448
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.00917089
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.00893403
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.00869148
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.00844304
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.00819393
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.00794147
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.00770892
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.00748912
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.00728698
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.00713719
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.00698648
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.0068374
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.00668651
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.00650056
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.00632341
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.00616439
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.00601834
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.00588731
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.00575815
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.00566099
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.00553836
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.00541226
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.00529851
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.00521222
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.00512861
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.00502674
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.00498336
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.00494317
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.00486931
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.00478785
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.00469439
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.0046142
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.00458468
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.00452822
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.00450052
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.00447624
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.00445038
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.00437785
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.00436089
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.00431949
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.00430945
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.00427894
[69]	valid_0's binary_logloss: 0.00425543
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.00425087
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.00419131
[72]	valid_0's binary_logloss: 0.00417894
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.00413281
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.00411758
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.00407662
[76]	valid_0's binary_logloss: 0.00404999
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.00405053
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.00404162
[79]	valid_0's binary_logloss: 0.00400179
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.00400749
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.0039918
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.00396159
[83]	valid_0's binary_logloss: 0.00396871
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.00390207
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.00389363
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.00387178
[87]	valid_0's binary_logloss: 0.00386365
[88]	valid_0's binary_logloss: 0.00383887
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.00382317
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.00379502
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.00376504
[92]	valid_0's binary_logloss: 0.00380626
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.00386376
[94]	valid_0's binary_logloss: 0.00390283
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.0039205
[96]	valid_0's binary_logloss: 0.00391931
[97]	valid_0's binary_logloss: 0.00394057
[98]	valid_0's binary_logloss: 0.00395476
[99]	valid_0's binary_logloss: 0.00397036
[100]	valid_0's binary_logloss: 0.0039568
[101]	valid_0's binary_logloss: 0.00395045
[102]	valid_0's binary_logloss: 0.00396874
[103]	valid_0's binary_logloss: 0.00396782
[104]	valid_0's binary_logloss: 0.00399553
[105]	valid_0's binary_logloss: 0.00400808
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.00401267
[107]	valid_0's binary_logloss: 0.00404931
[108]	valid_0's binary_logloss: 0.00407553
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.00409994
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.00413982
[111]	valid_0's binary_logloss: 0.00413303
[112]	valid_0's binary_logloss: 0.00410991
[113]	valid_0's binary_logloss: 0.00410654
[114]	valid_0's binary_logloss: 0.00411519
[115]	valid_0's binary_logloss: 0.00409458
[116]	valid_0's binary_logloss: 0.00409967
[117]	valid_0's binary_logloss: 0.00407648
[118]	valid_0's binary_logloss: 0.00409991
[119]	valid_0's binary_logloss: 0.00406985
[120]	valid_0's binary_logloss: 0.00409214
[121]	valid_0's binary_logloss: 0.00410432

Trening klas:  31%|███       | 156/500 [21:42<30:49,  5.38s/klasa, klasa=class_156, F1_klasy=0.7059, F1_macro=0.7793, drzewa=91]




Trening klas:  31%|███▏      | 157/500 [21:42<29:42,  5.20s/klasa, klasa=class_156, F1_klasy=0.7059, F1_macro=0.7793, drzewa=91]

[1]	valid_0's binary_logloss: 0.0334318
[2]	valid_0's binary_logloss: 0.0311206
[3]	valid_0's binary_logloss: 0.029189
[4]	valid_0's binary_logloss: 0.0275721
[5]	valid_0's binary_logloss: 0.0261622
[6]	valid_0's binary_logloss: 0.024935
[7]	valid_0's binary_logloss: 0.023788
[8]	valid_0's binary_logloss: 0.0227595
[9]	valid_0's binary_logloss: 0.0216491
[10]	valid_0's binary_logloss: 0.0207692
[11]	valid_0's binary_logloss: 0.019804
[12]	valid_0's binary_logloss: 0.0189432
[13]	valid_0's binary_logloss: 0.0181494
[14]	valid_0's binary_logloss: 0.0173767
[15]	valid_0's binary_logloss: 0.0167345
[16]	valid_0's binary_logloss: 0.0160612
[17]	valid_0's binary_logloss: 0.0154435
[18]	valid_0's binary_logloss: 0.0148713
[19]	valid_0's binary_logloss: 0.0143579
[20]	valid_0's binary_logloss: 0.0138476
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.013401
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0129807
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.0125953
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0121558
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.0117
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.0113024
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.0109368
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.0106033
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.010285
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.00994326
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.00954492
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.00926301
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.00896438
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.00869438
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.00844781
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.00823141
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.00804461
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.00783656
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.00765753
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.00742864
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.00718679
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.00700996
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.00679647
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.00661673
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.00644695
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.0063039
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.00612016
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.00600433
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.0058327
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.00575507
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.00555105
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.00535142
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.0051777
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.00501568
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.00484186
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.00474307
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.00462803
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.00452664
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.00442721
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.00432394
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.00425065
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.00421161
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.004157
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.00405403
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.00401467
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.00398533
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.00395157
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.00393114
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.00382991
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.00379745
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.00373346
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.00365542
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.00357823
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.00348468
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.00332512
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.00329838
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.00328804
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.00321432
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.00315248
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.00313258
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.00311221
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.0030836
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.00305674
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.00304811
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.00303199
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.00303722
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.00295829
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.00295406
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.00288244
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.00285997
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.00281478
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.00276009
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.00268849
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.00267635
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.00261589
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.00260582
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.00257555
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.00257666
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.00250355
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.00245081
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.0024032
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.00236084
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.00232125
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.00227812
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.00223656
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.00223714
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.00227283
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.00222141
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.00217886
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.00218294
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.00213877
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 0.00209651
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 0.00205542
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 0.00200654
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 0.00197755
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[116]	valid_0's binary_logloss: 0.00193481
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[117]	valid_0's binary_logloss: 0.00190647
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[118]	valid_0's binary_logloss: 0.00186734
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[119]	valid_0's binary_logloss: 0.00183449
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[120]	valid_0's binary_logloss: 0.00181158
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[121]	valid_0's binary_logloss: 0.00184301
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[122]	valid_0's binary_logloss: 0.00184913
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[123]	valid_0's binary_logloss: 0.00182073
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[124]	valid_0's binary_logloss: 0.00180586
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[125]	valid_0's binary_logloss: 0.00177159
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[126]	valid_0's binary_logloss: 0.00174969
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[127]	valid_0's binary_logloss: 0.00173564
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[128]	valid_0's binary_logloss: 0.00174388
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[129]	valid_0's binary_logloss: 0.00173087
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[130]	valid_0's binary_logloss: 0.00175791
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[131]	valid_0's binary_logloss: 0.00175741
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[132]	valid_0's binary_logloss: 0.00174377
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[133]	valid_0's binary_logloss: 0.0017417
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[134]	valid_0's binary_logloss: 0.00172595
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[135]	valid_0's binary_logloss: 0.00173576
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[136]	valid_0's binary_logloss: 0.00173959
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[137]	valid_0's binary_logloss: 0.00175758
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[138]	valid_0's binary_logloss: 0.00177919
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[139]	valid_0's binary_logloss: 0.00177412
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[140]	valid_0's binary_logloss: 0.00176965
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[141]	valid_0's binary_logloss: 0.00177924
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[142]	valid_0's binary_logloss: 0.00177221
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[143]	valid_0's binary_logloss: 0.00176625
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[144]	valid_0's binary_logloss: 0.00175972
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[145]	valid_0's binary_logloss: 0.00175344
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[146]	valid_0's binary_logloss: 0.00174978
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[147]	valid_0's binary_logloss: 0.0017392
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[148]	valid_0's binary_logloss: 0.00171833
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[149]	valid_0's binary_logloss: 0.00172098
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[150]	valid_0's binary_logloss: 0.00172613
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[151]	valid_0's binary_logloss: 0.00170428
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[152]	valid_0's binary_logloss: 0.00168671
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[153]	valid_0's binary_logloss: 0.00165682
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[154]	valid_0's binary_logloss: 0.0016478
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[155]	valid_0's binary_logloss: 0.00163717
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[156]	valid_0's binary_logloss: 0.00164013
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[157]	valid_0's binary_logloss: 0.00161247
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[158]	valid_0's binary_logloss: 0.0016039
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[159]	valid_0's binary_logloss: 0.00158624
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[160]	valid_0's binary_logloss: 0.00156761
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[161]	valid_0's binary_logloss: 0.0015562
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[162]	valid_0's binary_logloss: 0.00153823
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[163]	valid_0's binary_logloss: 0.00153227
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[164]	valid_0's binary_logloss: 0.00152806
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[165]	valid_0's binary_logloss: 0.0015158
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[166]	valid_0's binary_logloss: 0.00153152
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[167]	valid_0's binary_logloss: 0.00153894
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[168]	valid_0's binary_logloss: 0.00155198
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[169]	valid_0's binary_logloss: 0.001558
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[170]	valid_0's binary_logloss: 0.0015486
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[171]	valid_0's binary_logloss: 0.00155045
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[172]	valid_0's binary_logloss: 0.00156103
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[173]	valid_0's binary_logloss: 0.001563
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[174]	valid_0's binary_logloss: 0.00159142
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[175]	valid_0's binary_logloss: 0.00159426
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[176]	valid_0's binary_logloss: 0.00157375
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[177]	valid_0's binary_logloss: 0.00156425
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[178]	valid_0's binary_logloss: 0.00154204
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[179]	valid_0's binary_logloss: 0.00152181
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[180]	valid_0's binary_logloss: 0.00149771
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[181]	valid_0's binary_logloss: 0.00150132
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[182]	valid_0's binary_logloss: 0.00150753
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[183]	valid_0's binary_logloss: 0.00151948

Trening klas:  31%|███▏      | 157/500 [21:51<29:42,  5.20s/klasa, klasa=class_157, F1_klasy=0.9524, F1_macro=0.7804, drzewa=300]




Trening klas:  32%|███▏      | 158/500 [21:51<35:06,  6.16s/klasa, klasa=class_157, F1_klasy=0.9524, F1_macro=0.7804, drzewa=300]

[296]	valid_0's binary_logloss: 0.00114629
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[297]	valid_0's binary_logloss: 0.00114624
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[298]	valid_0's binary_logloss: 0.00114619
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[299]	valid_0's binary_logloss: 0.00114276
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[300]	valid_0's binary_logloss: 0.00113959
[1]	valid_0's binary_logloss: 0.0750327
[2]	valid_0's binary_logloss: 0.0704484
[3]	valid_0's binary_logloss: 0.0666364
[4]	valid_0's binary_logloss: 0.0633746
[5]	valid_0's binary_logloss: 0.0604728
[6]	valid_0's binary_logloss: 0.0584523
[7]	valid_0's binary_logloss: 0.0561291
[8]	valid_0's binary_logloss: 0.0540704
[9]	valid_0's binary_logloss: 0.0520398
[10]	valid_0's binary_logloss: 0.050315
[11]	valid_0's binary_logloss: 0.048725
[12]	valid_0's binary_logloss: 0.0473242
[13]	valid_0's binary_logloss: 0.0459189
[14]	valid_0's binary_logloss: 0.044624
[15]	valid_0's binary_logloss: 0.0434141
[16]	valid_0's binary_logloss: 0.0423882
[17]	valid_0's binary_logloss: 0.041424
[18]	valid_0's binary_logloss: 0.0405385
[19]	valid_0's binary_logloss: 0.040121
[20]	valid_0's binary_logloss: 0.0393749
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0386148
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0378867
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.0372002
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0366069
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.0362947
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.0357084
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.0351613
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.0345832
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.0340599
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.0336012
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.0331849
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.0327611
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.0324013
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.0321213
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.0318294
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.0316092
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.0313576
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.0311376
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.0309602
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.030752
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.0306139
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.030445
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.0303362
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.0302398
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.0301666
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.0300909
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.0299328
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.029731
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.0295369
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.0293959
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.0292629
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.029155
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.0290291
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.028919
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.0288187
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.0287431
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.0287093
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.0286106
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.0284909
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.0284384
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.0283919
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.0283642
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.0283901
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.0283654
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.0284008
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.0283888
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.0283665
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.0283921
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.0284111
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.0284191
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.0284953
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.0285584
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.0286441
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.0287255
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.0288033
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.0287622
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.0288319
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.0289437
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.0289046
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.0290177
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.029068
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.0290506
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.0291127
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.0291499
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.0291973
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.0294566
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.0295578
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.0297751
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.03002
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

Trening klas:  32%|███▏      | 158/500 [21:55<35:06,  6.16s/klasa, klasa=class_158, F1_klasy=0.8760, F1_macro=0.7810, drzewa=62]




Trening klas:  32%|███▏      | 159/500 [21:55<32:26,  5.71s/klasa, klasa=class_158, F1_klasy=0.8760, F1_macro=0.7810, drzewa=62]

[90]	valid_0's binary_logloss: 0.0302786
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.0304256
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.0304291
[1]	valid_0's binary_logloss: 0.124039
[2]	valid_0's binary_logloss: 0.121536
[3]	valid_0's binary_logloss: 0.119394
[4]	valid_0's binary_logloss: 0.117701
[5]	valid_0's binary_logloss: 0.116298
[6]	valid_0's binary_logloss: 0.115615
[7]	valid_0's binary_logloss: 0.114154
[8]	valid_0's binary_logloss: 0.112858
[9]	valid_0's binary_logloss: 0.111503
[10]	valid_0's binary_logloss: 0.110458
[11]	valid_0's binary_logloss: 0.109375
[12]	valid_0's binary_logloss: 0.108331
[13]	valid_0's binary_logloss: 0.107304
[14]	valid_0's binary_logloss: 0.106967
[15]	valid_0's binary_logloss: 0.106074
[16]	valid_0's binary_logloss: 0.105268
[17]	valid_0's binary_logloss: 0.104786
[18]	valid_0's binary_logloss: 0.103914
[19]	valid_0's binary_logloss: 0.103384
[20]	valid_0's binary_logloss: 0.103196
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.103106
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.102495
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.102518
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.10212
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.101742
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.101407
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.100983
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.100899
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.10056
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.100473
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.100171
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.0996042
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.0994184
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.0993705
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.0993521
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.0992583
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.0991943
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.0992201
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.0991288
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.0992662
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.0991863
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.0991226
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.0991219
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.0989687
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.0987828
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.0989115
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.0988733
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.0988587
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.0990013
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.0987886
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.09873
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.0986788
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.0985398
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.0984188
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.0983747
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.0981626
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.0981515
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.0980225
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.0981585
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.0981207
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.0980079
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.0977875
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.0977271
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.0978042
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.0980639
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.0981451
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.0982874
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.0985637
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.0986324
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.098588
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.098736
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.0986568
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.0987576
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.0987346
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.0989376
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.0990757
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.0990355
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.0990547
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.0990076
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.0992138
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.0992055
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.0993719
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.0995294
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.099601
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.0998327
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.10003
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.100223
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.100394
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

Trening klas:  32%|███▏      | 159/500 [22:00<32:26,  5.71s/klasa, klasa=class_159, F1_klasy=0.6203, F1_macro=0.7800, drzewa=63]




Trening klas:  32%|███▏      | 160/500 [22:00<30:11,  5.33s/klasa, klasa=class_159, F1_klasy=0.6203, F1_macro=0.7800, drzewa=63]

[89]	valid_0's binary_logloss: 0.100696
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.100867
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.101034
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.101189
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.101078
[1]	valid_0's binary_logloss: 0.074747
[2]	valid_0's binary_logloss: 0.0722956
[3]	valid_0's binary_logloss: 0.0702917
[4]	valid_0's binary_logloss: 0.0686406
[5]	valid_0's binary_logloss: 0.0669958
[6]	valid_0's binary_logloss: 0.0655227
[7]	valid_0's binary_logloss: 0.0645888
[8]	valid_0's binary_logloss: 0.0635867
[9]	valid_0's binary_logloss: 0.0628678
[10]	valid_0's binary_logloss: 0.0620098
[11]	valid_0's binary_logloss: 0.0613362
[12]	valid_0's binary_logloss: 0.060745
[13]	valid_0's binary_logloss: 0.0600228
[14]	valid_0's binary_logloss: 0.0597186
[15]	valid_0's binary_logloss: 0.0592275
[16]	valid_0's binary_logloss: 0.0590593
[17]	valid_0's binary_logloss: 0.0588972
[18]	valid_0's binary_logloss: 0.0586386
[19]	valid_0's binary_logloss: 0.0585645
[20]	valid_0's binary_logloss: 0.0582573
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.058144
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0579456
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.058193
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0583667
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.0586236
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.0587388
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.0584341
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.0585461
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.058617
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.0584913
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.0582263
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.0581335
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.0582616
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.0584685
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.0584065
[36]	valid_0's binary_logloss: 0.0582241
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.0582851
[38]	valid_0's binary_logloss: 0.0583216
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.0583477
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.0582076
[41]	valid_0's binary_logloss: 0.0580824
[42]	valid_0's binary_logloss: 0.057825
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.0577809
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.0578987
[45]	valid_0's binary_logloss: 0.0578173
[46]	valid_0's binary_logloss: 0.0578299
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.0579343
[48]	valid_0's binary_logloss: 0.0578472
[49]	valid_0's binary_logloss: 0.0579726
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.0583034
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.0578499
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.0575019
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.0572506
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.056993
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.0566383
[56]	valid_0's binary_logloss: 0.0563767
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.0564482
[58]	valid_0's binary_logloss: 0.0560951
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.0557427
[60]	valid_0's binary_logloss: 0.0555894
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.0557055
[62]	valid_0's binary_logloss: 0.0557206
[63]	valid_0's binary_logloss: 0.0555921
[64]	valid_0's binary_logloss: 0.0556266
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.0558384
[66]	valid_0's binary_logloss: 0.0557336
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.0559637
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.0563399
[69]	valid_0's binary_logloss: 0.0564227
[70]	valid_0's binary_logloss: 0.0565615
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.0566614
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.056705
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.0569139
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.0570975
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.0571032
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.0573344
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.0573762
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.0576303
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.057765
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.0578573
[81]	valid_0's binary_logloss: 0.0576229
[82]	valid_0's binary_logloss: 0.0575617
[83]	valid_0's binary_logloss: 0.0576164
[84]	valid_0's binary_logloss: 0.0575623
[85]	valid_0's binary_logloss: 0.0576759
[86]	valid_0's binary_logloss: 0.0577714
[87]	valid_0's binary_logloss: 0.0577472

Trening klas:  32%|███▏      | 160/500 [22:04<30:11,  5.33s/klasa, klasa=class_160, F1_klasy=0.6969, F1_macro=0.7795, drzewa=60]




Trening klas:  32%|███▏      | 161/500 [22:04<28:15,  5.00s/klasa, klasa=class_160, F1_klasy=0.6969, F1_macro=0.7795, drzewa=60]

[88]	valid_0's binary_logloss: 0.0577314
[89]	valid_0's binary_logloss: 0.0577629
[90]	valid_0's binary_logloss: 0.0577693
[1]	valid_0's binary_logloss: 0.0751331
[2]	valid_0's binary_logloss: 0.0719124
[3]	valid_0's binary_logloss: 0.0693362
[4]	valid_0's binary_logloss: 0.0679253
[5]	valid_0's binary_logloss: 0.0660553
[6]	valid_0's binary_logloss: 0.0645381
[7]	valid_0's binary_logloss: 0.0631712
[8]	valid_0's binary_logloss: 0.0620278
[9]	valid_0's binary_logloss: 0.0611214
[10]	valid_0's binary_logloss: 0.059921
[11]	valid_0's binary_logloss: 0.0589508
[12]	valid_0's binary_logloss: 0.0583265
[13]	valid_0's binary_logloss: 0.0572726
[14]	valid_0's binary_logloss: 0.0561406
[15]	valid_0's binary_logloss: 0.0551808
[16]	valid_0's binary_logloss: 0.0545649
[17]	valid_0's binary_logloss: 0.0537897
[18]	valid_0's binary_logloss: 0.053064
[19]	valid_0's binary_logloss: 0.0526685
[20]	valid_0's binary_logloss: 0.052296
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0519505
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.05131
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.0508777
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0504472
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.0499771
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.049525
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.0491972
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.0489592
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.0486581
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.0483901
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.0482119
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.0478876
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.0477415
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.0473118
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.0470671
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.0468472
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.0466306
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.0463468
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.0462019
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.046118
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.0459728
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.0457807
[43]	valid_0's binary_logloss: 0.0456861
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.0454149
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.0452675
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.0451384
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.0449997
[48]	valid_0's binary_logloss: 0.0448533
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.0447073
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.0445586
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.044454
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.0443077
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.0442335
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.0441269
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.0442307
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.0441797
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.0441506
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.0441694
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.0441821
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.0442202
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.0440674
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.0439921
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.0440187
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.0438894
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.0438832
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.0437859
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.043834
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.0439037
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.0439631
[70]	valid_0's binary_logloss: 0.0438026
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.043883
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.0439163
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.0438874
[74]	valid_0's binary_logloss: 0.0437988
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.0439616
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.0440681
[77]	valid_0's binary_logloss: 0.044105
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.0441915
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.0441901
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.0441793
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.044197
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.0441418
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.0442382
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.0443357
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.0443856
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.0445818
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.0445927
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.0445501
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.0445638
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.0444819
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.0446008
[92]	valid_0's binary_logloss: 0.0447635

Trening klas:  32%|███▏      | 161/500 [22:09<28:15,  5.00s/klasa, klasa=class_161, F1_klasy=0.7626, F1_macro=0.7794, drzewa=66]




Trening klas:  32%|███▏      | 162/500 [22:09<27:37,  4.90s/klasa, klasa=class_161, F1_klasy=0.7626, F1_macro=0.7794, drzewa=66]

[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.0450068
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.0449967
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.045041
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.0451208
[1]	valid_0's binary_logloss: 0.0256021
[2]	valid_0's binary_logloss: 0.0245919
[3]	valid_0's binary_logloss: 0.0236086
[4]	valid_0's binary_logloss: 0.0227005
[5]	valid_0's binary_logloss: 0.0218138
[6]	valid_0's binary_logloss: 0.0212152
[7]	valid_0's binary_logloss: 0.020347
[8]	valid_0's binary_logloss: 0.0195713
[9]	valid_0's binary_logloss: 0.0188579
[10]	valid_0's binary_logloss: 0.0181252
[11]	valid_0's binary_logloss: 0.0173784
[12]	valid_0's binary_logloss: 0.0167277
[13]	valid_0's binary_logloss: 0.0160979
[14]	valid_0's binary_logloss: 0.0154642
[15]	valid_0's binary_logloss: 0.014854
[16]	valid_0's binary_logloss: 0.0143059
[17]	valid_0's binary_logloss: 0.0138177
[18]	valid_0's binary_logloss: 0.0133128
[19]	valid_0's binary_logloss: 0.0128482
[20]	valid_0's binary_logloss: 0.0123789
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0119492
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0115529
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.0111796
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0108076
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.0104707
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.010118
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.0098141
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.00952135
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.00924485
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.00899055
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.00872767
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.00847798
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.00824045
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.00804513
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.00783615
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.00764657
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.00746272
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.00727314
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.00710223
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.00694183
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.00679815
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.00664778
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.00652383
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.0063995
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.00627729
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.00618156
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.00607633
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.00597962
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.00588579
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.00580084
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.00570121
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.0056105
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.00554265
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.00547576
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.00541884
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.00536242
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.00532139
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.00526608
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.005233
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.0051854
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.00515165
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.00510848
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.00508165
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.00504528
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.00502242
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.00499049
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.00496151
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.00493559
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.0049111
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.00488809
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.00485747
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.00485289
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.00484615
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.00484385
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.0048314
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.00482777
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.00482939
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.00482112
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.00482479
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.00481751
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.00482907
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.00483914
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.00485203
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.00485833
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.00484592
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.00486191
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.00486807
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.0048856
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.00489903
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.00490898
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.00492721
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.0049472
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.00496319
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.00498291
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.0049909
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.00499121
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.00501225
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.00503236
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.00505316
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.00507214
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.00508268
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.00509724
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.00512171
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.00513835
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.00515312
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.00517814
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.00520323
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.00521115
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.00523892
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

Trening klas:  32%|███▏      | 162/500 [22:13<27:37,  4.90s/klasa, klasa=class_162, F1_klasy=0.0000, F1_macro=0.7746, drzewa=80]




Trening klas:  33%|███▎      | 163/500 [22:13<26:53,  4.79s/klasa, klasa=class_162, F1_klasy=0.0000, F1_macro=0.7746, drzewa=80]

[110]	valid_0's binary_logloss: 0.00524943
[1]	valid_0's binary_logloss: 0.043565
[2]	valid_0's binary_logloss: 0.0411504
[3]	valid_0's binary_logloss: 0.0391318
[4]	valid_0's binary_logloss: 0.0375105
[5]	valid_0's binary_logloss: 0.0358082
[6]	valid_0's binary_logloss: 0.0343953
[7]	valid_0's binary_logloss: 0.0330981
[8]	valid_0's binary_logloss: 0.0319631
[9]	valid_0's binary_logloss: 0.0308838
[10]	valid_0's binary_logloss: 0.0299755
[11]	valid_0's binary_logloss: 0.0295812
[12]	valid_0's binary_logloss: 0.0293381
[13]	valid_0's binary_logloss: 0.02868
[14]	valid_0's binary_logloss: 0.0289138
[15]	valid_0's binary_logloss: 0.0287727
[16]	valid_0's binary_logloss: 0.0282743
[17]	valid_0's binary_logloss: 0.0277934
[18]	valid_0's binary_logloss: 0.0273747
[19]	valid_0's binary_logloss: 0.0272054
[20]	valid_0's binary_logloss: 0.0269108
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0265911
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0262967
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.0260685
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0259069
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.0253396
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.0246717
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.0239283
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.0234053
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.023302
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.0226544
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.0224852
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.0223272
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.0221317
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.0221443
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.0214437
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.0212245
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.0206955
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.0202311
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.0197897
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.0196247
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.0196734
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.019699
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.0197589
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.0197533
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.0198186
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.0198032
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.0198109
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.0193627
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.0194509
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.0195354
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.0191289
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.0187511
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.0183725
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.0184697
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.0180849
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.0177256
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.0176849
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.0173622
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.0170421
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.016731
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.0165657
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.0163498
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.0164302
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.0163044
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.0160757
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.0161707
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.0158645
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.0155778
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.0154531
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.0151832
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.0150579
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.0151865
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.0149303
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.015035
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.014684
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.014163
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.0139628
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.0136342
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.0132532
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.0129962
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.0126606
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.0125036
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.0122815
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.0120036
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.0117979
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.0115297
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.0113594
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.0111935
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.0109866
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.0108225
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.010709
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.0106055
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.010561
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.0104721
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.0104537
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.0105545
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.0106108
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.010724
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.0108055
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.0107796
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.0106171
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.0105402
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.0104398
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.0104055
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.010373
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.010312
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.0102576
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.0102222
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.0101947
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.0101553
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.0100631
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 0.00997025
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 0.00989907
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 0.00986857
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 0.00982788
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[116]	valid_0's binary_logloss: 0.00978195
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[117]	valid_0's binary_logloss: 0.00975968
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[118]	valid_0's binary_logloss: 0.00971776
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[119]	valid_0's binary_logloss: 0.00970125
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[120]	valid_0's binary_logloss: 0.00966396
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[121]	valid_0's binary_logloss: 0.00968447
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[122]	valid_0's binary_logloss: 0.009632
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[123]	valid_0's binary_logloss: 0.00964781
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[124]	valid_0's binary_logloss: 0.00962992
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[125]	valid_0's binary_logloss: 0.00967866
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[126]	valid_0's binary_logloss: 0.0096353
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[127]	valid_0's binary_logloss: 0.00966984
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[128]	valid_0's binary_logloss: 0.00960828
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[129]	valid_0's binary_logloss: 0.00961415
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[130]	valid_0's binary_logloss: 0.00956263
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[131]	valid_0's binary_logloss: 0.00954609
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[132]	valid_0's binary_logloss: 0.00949897
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[133]	valid_0's binary_logloss: 0.00946436
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[134]	valid_0's binary_logloss: 0.00941881
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[135]	valid_0's binary_logloss: 0.00943018
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[136]	valid_0's binary_logloss: 0.00945475
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[137]	valid_0's binary_logloss: 0.00944862
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[138]	valid_0's binary_logloss: 0.00944907
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[139]	valid_0's binary_logloss: 0.00946182
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[140]	valid_0's binary_logloss: 0.00947563
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[141]	valid_0's binary_logloss: 0.00946778
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[142]	valid_0's binary_logloss: 0.00946997
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[143]	valid_0's binary_logloss: 0.0094852
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[144]	valid_0's binary_logloss: 0.00947034
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[145]	valid_0's binary_logloss: 0.00948515
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[146]	valid_0's binary_logloss: 0.00955233
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[147]	valid_0's binary_logloss: 0.00958133
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[148]	valid_0's binary_logloss: 0.00956173
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[149]	valid_0's binary_logloss: 0.00957702
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[150]	valid_0's binary_logloss: 0.00964801
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[151]	valid_0's binary_logloss: 0.00963027
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[152]	valid_0's binary_logloss: 0.00958639
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[153]	valid_0's binary_logloss: 0.00957818
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[154]	valid_0's binary_logloss: 0.00954657
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[155]	valid_0's binary_logloss: 0.00952945
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[156]	valid_0's binary_logloss: 0.00954382
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[157]	valid_0's binary_logloss: 0.00956715
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[158]	valid_0's binary_logloss: 0.00954189
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[159]	valid_0's binary_logloss: 0.00952141
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[160]	valid_0's binary_logloss: 0.00952872
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[161]	valid_0's binary_logloss: 0.00955182
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[162]	valid_0's binary_logloss: 0.00954208
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[163]	valid_0's binary_logloss: 0.0095378
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[164]	valid_0's binary_logloss: 0.0095797

Trening klas:  33%|███▎      | 163/500 [22:17<26:53,  4.79s/klasa, klasa=class_163, F1_klasy=0.8489, F1_macro=0.7750, drzewa=134]




Trening klas:  33%|███▎      | 164/500 [22:17<25:38,  4.58s/klasa, klasa=class_163, F1_klasy=0.8489, F1_macro=0.7750, drzewa=134]

[1]	valid_0's binary_logloss: 0.0635975
[2]	valid_0's binary_logloss: 0.0620339
[3]	valid_0's binary_logloss: 0.0605377
[4]	valid_0's binary_logloss: 0.0591872
[5]	valid_0's binary_logloss: 0.0582101
[6]	valid_0's binary_logloss: 0.0574647
[7]	valid_0's binary_logloss: 0.0568246
[8]	valid_0's binary_logloss: 0.0563142
[9]	valid_0's binary_logloss: 0.0558662
[10]	valid_0's binary_logloss: 0.0555932
[11]	valid_0's binary_logloss: 0.0552897
[12]	valid_0's binary_logloss: 0.0550404
[13]	valid_0's binary_logloss: 0.0544724
[14]	valid_0's binary_logloss: 0.0543903
[15]	valid_0's binary_logloss: 0.0540406
[16]	valid_0's binary_logloss: 0.0537857
[17]	valid_0's binary_logloss: 0.0536649
[18]	valid_0's binary_logloss: 0.053127
[19]	valid_0's binary_logloss: 0.0533751
[20]	valid_0's binary_logloss: 0.0532094
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0532149
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0530038
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.0526899
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0528881
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.0531334
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.0534642
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.053796
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.0537644
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.0534952
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.053652
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.0537412
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.0540316
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.0544006
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.0546666
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.0546851
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.0549608
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.0552698
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.055602
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.0560442
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.0565372
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.0566653
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.0566158
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.0568138
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.0569034
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.0570925
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.0574887
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.0575835
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.0575195
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.0576618
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.0576604
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.0578317
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.0571192
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.0572802

Trening klas:  33%|███▎      | 164/500 [22:20<25:38,  4.58s/klasa, klasa=class_164, F1_klasy=0.7660, F1_macro=0.7750, drzewa=23]




Trening klas:  33%|███▎      | 165/500 [22:20<22:13,  3.98s/klasa, klasa=class_164, F1_klasy=0.7660, F1_macro=0.7750, drzewa=23]

[1]	valid_0's binary_logloss: 0.0836733
[2]	valid_0's binary_logloss: 0.0808531
[3]	valid_0's binary_logloss: 0.0780213
[4]	valid_0's binary_logloss: 0.0756247
[5]	valid_0's binary_logloss: 0.073829
[6]	valid_0's binary_logloss: 0.0718432
[7]	valid_0's binary_logloss: 0.0701679
[8]	valid_0's binary_logloss: 0.0683043
[9]	valid_0's binary_logloss: 0.0670165
[10]	valid_0's binary_logloss: 0.0655353
[11]	valid_0's binary_logloss: 0.0642593
[12]	valid_0's binary_logloss: 0.0630457
[13]	valid_0's binary_logloss: 0.0618589
[14]	valid_0's binary_logloss: 0.0605144
[15]	valid_0's binary_logloss: 0.0593763
[16]	valid_0's binary_logloss: 0.0583047
[17]	valid_0's binary_logloss: 0.0576795
[18]	valid_0's binary_logloss: 0.057176
[19]	valid_0's binary_logloss: 0.0563862
[20]	valid_0's binary_logloss: 0.0555911
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0547979
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0539816
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.0532767
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0527163
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.0523385
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.0518879
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.0513153
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.0509304
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.0505552
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.050096
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.0496728
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.0494055
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.049026
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.0490195
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.048644
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.0480629
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.0477132
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.0474548
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.0469215
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.046676
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.0463894
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.0459936
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.0456459
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.0455023
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.0450829
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.0450068
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.0448296
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.0445272
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.0440753
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.0439851
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.043779
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.0435323
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.0432881
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.0431919
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.0428908
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.0427162
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.0424659
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.042355
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.0420075
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.0418993
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.0417003
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.0415026
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.0413901
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.0413388
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.0412224
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.0411628
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.0409529
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.0408545
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.0408224
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.0407039
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.0407183
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.0405602
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.0404717
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.0404976
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.0404866
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.0404506
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.0405412
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.0405525
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.0404369
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.0405142
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.0405907
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.0407247
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.0407408
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.0407755
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.0407607
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.0407039
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.0407055
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.0409445
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.0411768
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.0410914
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.0411626
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.0412531
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.0413567
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.0415189
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.0413502
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.0413908
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.0412981
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.0411464
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.041109
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.0411235
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.0413169
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.0414756
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.0417459
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.0419856
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.0421921
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.0423545
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.0423001
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.0423029
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.0423114

Trening klas:  33%|███▎      | 165/500 [22:24<22:13,  3.98s/klasa, klasa=class_165, F1_klasy=0.7089, F1_macro=0.7746, drzewa=79]




Trening klas:  33%|███▎      | 166/500 [22:24<22:02,  3.96s/klasa, klasa=class_165, F1_klasy=0.7089, F1_macro=0.7746, drzewa=79]

[1]	valid_0's binary_logloss: 0.0433891
[2]	valid_0's binary_logloss: 0.04021
[3]	valid_0's binary_logloss: 0.0375323
[4]	valid_0's binary_logloss: 0.035338
[5]	valid_0's binary_logloss: 0.0332964
[6]	valid_0's binary_logloss: 0.0315312
[7]	valid_0's binary_logloss: 0.0299857
[8]	valid_0's binary_logloss: 0.0285866
[9]	valid_0's binary_logloss: 0.0273646
[10]	valid_0's binary_logloss: 0.0261874
[11]	valid_0's binary_logloss: 0.0252079
[12]	valid_0's binary_logloss: 0.0240593
[13]	valid_0's binary_logloss: 0.0230281
[14]	valid_0's binary_logloss: 0.0221359
[15]	valid_0's binary_logloss: 0.0213117
[16]	valid_0's binary_logloss: 0.020434
[17]	valid_0's binary_logloss: 0.0196922
[18]	valid_0's binary_logloss: 0.0190359
[19]	valid_0's binary_logloss: 0.0183952
[20]	valid_0's binary_logloss: 0.0177612
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0172089
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0166356
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.0161589
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0157216
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.0152603
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.014835
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.0144526
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.0141092
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.013803
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.0134692
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.0131591
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.012869
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.0126446
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.0124429
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.0122011
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.0119117
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.0116813
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.0114969
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.0113956
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.0112315
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.011093
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.0109177
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.0107688
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.0106446
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.0105097
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.0103664
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.0102326
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.0101105
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.0100168
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.00993787
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.00982917
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.00976709
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.0097096
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.0096502
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.00959113
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.00956755
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.00955536
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.00956348
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.00956786
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.00959776
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.00956597
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.00953953
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.00955057
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.00953934
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.00950183
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.00942785
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.00942716
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.00941687
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.00939468
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.00939092
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.00936729
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.00935824
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.00935367
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.00937968
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.0094173
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.00943991
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.00943203
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.00934223
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.0092649
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.00922385
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.00921119
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.00911574
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.00909718
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.00909595
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.00908605
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.00902417
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.00901792
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.00893855
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.00892722
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.0088638
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.008893
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.00892648
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.00895493
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.00890295
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.00890336
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.00891527
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.00895709
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.00894805
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.00898727
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.00895899
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.00893653
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.00895123
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.00896034
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.00898358
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.00901798
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.00906526
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.00902456
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.00909864
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.00915045
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.00914863
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.00919966
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 0.00916876
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 0.00920974
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 0.009262
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 0.00929866
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[116]	valid_0's binary_logloss: 0.0093481
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[117]	valid_0's binary_logloss: 0.00938347
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[118]	valid_0's binary_logloss: 0.00944913
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

Trening klas:  33%|███▎      | 166/500 [22:28<22:02,  3.96s/klasa, klasa=class_166, F1_klasy=0.9302, F1_macro=0.7755, drzewa=90]




Trening klas:  33%|███▎      | 167/500 [22:28<22:30,  4.06s/klasa, klasa=class_166, F1_klasy=0.9302, F1_macro=0.7755, drzewa=90]

[119]	valid_0's binary_logloss: 0.00949777
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[120]	valid_0's binary_logloss: 0.00953924
[1]	valid_0's binary_logloss: 0.0232857
[2]	valid_0's binary_logloss: 0.0223152
[3]	valid_0's binary_logloss: 0.021361
[4]	valid_0's binary_logloss: 0.0205069
[5]	valid_0's binary_logloss: 0.0196434
[6]	valid_0's binary_logloss: 0.0188266
[7]	valid_0's binary_logloss: 0.0180478
[8]	valid_0's binary_logloss: 0.0173349
[9]	valid_0's binary_logloss: 0.0166356
[10]	valid_0's binary_logloss: 0.0159766
[11]	valid_0's binary_logloss: 0.015332
[12]	valid_0's binary_logloss: 0.0147449
[13]	valid_0's binary_logloss: 0.0141959
[14]	valid_0's binary_logloss: 0.0136636
[15]	valid_0's binary_logloss: 0.0131488
[16]	valid_0's binary_logloss: 0.0126857
[17]	valid_0's binary_logloss: 0.0122489
[18]	valid_0's binary_logloss: 0.0118008
[19]	valid_0's binary_logloss: 0.0113811
[20]	valid_0's binary_logloss: 0.0109746
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0105771
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0101912
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.00983634
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.00950445
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.00919157
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.00887966
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.00858404
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.00830954
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.00805992
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.00782786
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.00761785
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.00738954
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.00719216
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.00700437
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.00684628
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.00668401
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.00652351
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.00637212
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.00623858
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.00610299
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.00596044
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.00584064
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.0057157
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.00559928
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.00550106
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.00539134
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.00528639
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.00518818
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.00511745
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.00502823
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.00494736
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.00488887
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.00481466
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.00474787
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.00468266
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.0046261
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.00457563
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.00452212
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.00447448
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.00442657
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.00436406
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.00432534
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.00428825
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.00425478
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.00422296
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.00419384
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.00416778
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.00415129
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.004136
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.00411586
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.00409352
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.00407797
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.00406299
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.00404915
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.00404332
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.00403431
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.00402636
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.0040271
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.0040215
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.004024
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.00402486
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.00402394
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.00402381
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.00403019
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.00403035
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.00403858
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.00403988
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.00404835
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.00405132
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.00405482
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.00406487
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.00407817
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.00408922
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.0041105
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.00412501
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.00412992
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.00412122
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.00411488
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.00414826
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.00417897
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.00418596
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.0041934
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.00420183
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.00421027
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.00421941
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.00423009
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.00424132
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.0042571
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.00427582

Trening klas:  33%|███▎      | 167/500 [22:33<22:30,  4.06s/klasa, klasa=class_167, F1_klasy=0.0000, F1_macro=0.7709, drzewa=79]




Trening klas:  34%|███▎      | 168/500 [22:33<23:15,  4.20s/klasa, klasa=class_167, F1_klasy=0.0000, F1_macro=0.7709, drzewa=79]

[1]	valid_0's binary_logloss: 0.0396649
[2]	valid_0's binary_logloss: 0.0375071
[3]	valid_0's binary_logloss: 0.0355319
[4]	valid_0's binary_logloss: 0.0337464
[5]	valid_0's binary_logloss: 0.0321575
[6]	valid_0's binary_logloss: 0.0305543
[7]	valid_0's binary_logloss: 0.0292425
[8]	valid_0's binary_logloss: 0.0279961
[9]	valid_0's binary_logloss: 0.0268181
[10]	valid_0's binary_logloss: 0.0256583
[11]	valid_0's binary_logloss: 0.0246207
[12]	valid_0's binary_logloss: 0.0237712
[13]	valid_0's binary_logloss: 0.0228626
[14]	valid_0's binary_logloss: 0.0219792
[15]	valid_0's binary_logloss: 0.0211692
[16]	valid_0's binary_logloss: 0.0205668
[17]	valid_0's binary_logloss: 0.0200021
[18]	valid_0's binary_logloss: 0.019301
[19]	valid_0's binary_logloss: 0.0187601
[20]	valid_0's binary_logloss: 0.0181743
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0176351
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0172016
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.0166752
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0162603
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.0158742
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.0154521
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.0150315
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.0146658
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.0143203
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.013986
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.0136825
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.0134152
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.0130564
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.0127189
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.0124239
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.0121887
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.011923
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.0116783
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.0114359
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.0112122
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.0110388
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.0108295
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.0106394
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.0104564
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.0102924
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.010183
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.0100425
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.00989969
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.00977058
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.00964671
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.00951348
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.00938741
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.00921963
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.00908887
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.00897295
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.00888329
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.00878696
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.00868879
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.00865103
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.00859976
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.00851083
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.00847042
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.00842699
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.00840542
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.0082868
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.00824669
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.00820884
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.00814078
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.00807778
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.00800641
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.00796749
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.00794632
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.00793838
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.00790213
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.00789021
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.00785057
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.00780934
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.00773937
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.00770459
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.00767655
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.00766387
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.00762345
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.00759436
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.00755086
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.00751035
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.00753031
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.00755635
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.0075156
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.00749258
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.00751486
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.0074887
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.00746281
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.00746795
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.00741313
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.00739076
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.00739777
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.00736357
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.00739792
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.0074008
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.00744887
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.00750413
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.00749343
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.00753531
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.00754118
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.0075285
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.00750681
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.00750087
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.007503
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.00745924
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.00742364
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.00743487
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 0.00743423
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 0.0074364
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 0.0074598
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 0.00747126
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[116]	valid_0's binary_logloss: 0.0075043
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[117]	valid_0's binary_logloss: 0.00747361
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[118]	valid_0's binary_logloss: 0.00749211
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[119]	valid_0's binary_logloss: 0.00749835
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[120]	valid_0's binary_logloss: 0.00752528
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[121]	valid_0's binary_logloss: 0.00751729
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[122]	valid_0's binary_logloss: 0.00753401
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[123]	valid_0's binary_logloss: 0.00753241
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[124]	valid_0's binary_logloss: 0.00753307
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[125]	valid_0's binary_logloss: 0.00754883
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

Trening klas:  34%|███▎      | 168/500 [22:37<23:15,  4.20s/klasa, klasa=class_168, F1_klasy=0.8906, F1_macro=0.7716, drzewa=97]




Trening klas:  34%|███▍      | 169/500 [22:37<22:59,  4.17s/klasa, klasa=class_168, F1_klasy=0.8906, F1_macro=0.7716, drzewa=97]

[126]	valid_0's binary_logloss: 0.00756043
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[127]	valid_0's binary_logloss: 0.00757644
[1]	valid_0's binary_logloss: 0.0749567
[2]	valid_0's binary_logloss: 0.0732588
[3]	valid_0's binary_logloss: 0.071786
[4]	valid_0's binary_logloss: 0.0706476
[5]	valid_0's binary_logloss: 0.0698218
[6]	valid_0's binary_logloss: 0.0694852
[7]	valid_0's binary_logloss: 0.0691438
[8]	valid_0's binary_logloss: 0.0685359
[9]	valid_0's binary_logloss: 0.0678182
[10]	valid_0's binary_logloss: 0.0671905
[11]	valid_0's binary_logloss: 0.066775
[12]	valid_0's binary_logloss: 0.0666361
[13]	valid_0's binary_logloss: 0.0662203
[14]	valid_0's binary_logloss: 0.0659433
[15]	valid_0's binary_logloss: 0.0658142
[16]	valid_0's binary_logloss: 0.065432
[17]	valid_0's binary_logloss: 0.0652234
[18]	valid_0's binary_logloss: 0.0648177
[19]	valid_0's binary_logloss: 0.0647262
[20]	valid_0's binary_logloss: 0.0645381
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0641428
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0640147
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.0639448
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0637332
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.0636184
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.0636976
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.0634441
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.0631167
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.0627853
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.0625177
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.0622964
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.0621242
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.0618681
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.0618371
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.061894
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.0616024
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.061479
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.0614954
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.0616396
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.0617013
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.0619688
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.06209
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.0618238
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.061751
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.0618568
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.0616438
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.0616569
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.0617984
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.0614311
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.0615247
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.0613242
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.0612413
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.0610764
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.0609213
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.0609338
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.0608712
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.060788
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.0607727
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.0603631
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.06025
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.0604002
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.0604095
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.0604419
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.0602659
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.0603445
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.060498
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.0605616
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.0607058
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.0608076
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.0607431
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.0606657
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.0607091
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.0608054
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.0608694
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.0609479
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.0609996
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.0611139
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.0609811
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.061006
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.0609119
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.0607169
[82]	valid_0's binary_logloss: 0.0607135
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.0607248
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.0607734
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.0607
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.0606782
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.0607126

Trening klas:  34%|███▍      | 169/500 [22:41<22:59,  4.17s/klasa, klasa=class_169, F1_klasy=0.5874, F1_macro=0.7705, drzewa=60]




Trening klas:  34%|███▍      | 170/500 [22:41<23:31,  4.28s/klasa, klasa=class_169, F1_klasy=0.5874, F1_macro=0.7705, drzewa=60]

[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.0607593
[89]	valid_0's binary_logloss: 0.0607216
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.0607467
[1]	valid_0's binary_logloss: 0.0745456
[2]	valid_0's binary_logloss: 0.0728601
[3]	valid_0's binary_logloss: 0.0714304
[4]	valid_0's binary_logloss: 0.0703336
[5]	valid_0's binary_logloss: 0.0695279
[6]	valid_0's binary_logloss: 0.0692248
[7]	valid_0's binary_logloss: 0.0688991
[8]	valid_0's binary_logloss: 0.0683079
[9]	valid_0's binary_logloss: 0.0676013
[10]	valid_0's binary_logloss: 0.066979
[11]	valid_0's binary_logloss: 0.0664464
[12]	valid_0's binary_logloss: 0.0660766
[13]	valid_0's binary_logloss: 0.065846
[14]	valid_0's binary_logloss: 0.0656388
[15]	valid_0's binary_logloss: 0.0654894
[16]	valid_0's binary_logloss: 0.065436
[17]	valid_0's binary_logloss: 0.0651253
[18]	valid_0's binary_logloss: 0.0647032
[19]	valid_0's binary_logloss: 0.0645295
[20]	valid_0's binary_logloss: 0.0642326
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0642751
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0641051
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.0636628
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0637455
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.0636271
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.0635994
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.0632669
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.0632013
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.0628139
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.062562
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.0622659
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.0619795
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.0621114
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.0620558
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.0620588
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.062011
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.0618066
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.0618423
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.0618858
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.0618386
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.0619423
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.0622783
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.06239
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.0624511
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.0622353
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.0623604
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.0625682
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.0627787
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.0623416
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.0623541
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.0621159
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.0620471
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.0620006
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.0620656
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.0621366
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.062293
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.0622605
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.0620869
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.0619909
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.0622414
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.0622454
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.062349
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.0626013
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.0626307
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.062673
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.0626924
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

Trening klas:  34%|███▍      | 170/500 [22:45<23:31,  4.28s/klasa, klasa=class_170, F1_klasy=0.5695, F1_macro=0.7693, drzewa=37]




Trening klas:  34%|███▍      | 171/500 [22:45<22:15,  4.06s/klasa, klasa=class_170, F1_klasy=0.5695, F1_macro=0.7693, drzewa=37]

[67]	valid_0's binary_logloss: 0.0627976
[1]	valid_0's binary_logloss: 0.0516536
[2]	valid_0's binary_logloss: 0.0496183
[3]	valid_0's binary_logloss: 0.0477041
[4]	valid_0's binary_logloss: 0.045993
[5]	valid_0's binary_logloss: 0.0444837
[6]	valid_0's binary_logloss: 0.0435612
[7]	valid_0's binary_logloss: 0.0424463
[8]	valid_0's binary_logloss: 0.0414826
[9]	valid_0's binary_logloss: 0.04057
[10]	valid_0's binary_logloss: 0.0396856
[11]	valid_0's binary_logloss: 0.0390261
[12]	valid_0's binary_logloss: 0.038385
[13]	valid_0's binary_logloss: 0.037875
[14]	valid_0's binary_logloss: 0.0374046
[15]	valid_0's binary_logloss: 0.0369998
[16]	valid_0's binary_logloss: 0.0365224
[17]	valid_0's binary_logloss: 0.0361261
[18]	valid_0's binary_logloss: 0.0357818
[19]	valid_0's binary_logloss: 0.0353026
[20]	valid_0's binary_logloss: 0.0350048
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0347523
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0344795
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.0342126
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0339755
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.0338649
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.0336442
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.033449
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.0333483
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.0332433
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.0331662
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.0332607
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.033231
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.033316
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.0332594
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.033201
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.0330658
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.0329663
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.0329161
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.0327732
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.0328539
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.0327005
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.0326238
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.0327057
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.0327768
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.0328021
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.0327558
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.0327806
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.0323894
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.0320544
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.0319464
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.0319868
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.032078
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.0321903
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.0322466
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.0322141
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.032315
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.0322624
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.0323628
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.0326017
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.0327544
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.0325467
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.0320423
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.0316439
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.0313986
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.0313807
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.0314917
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.0314773
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.0315384
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.0314022
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.031516
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.0316321
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.0316599
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.0316288
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.0317377
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.0316863
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.0318185
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.031963
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.0320465
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.0321534
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.0322548
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.0323401
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.0324534
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.0322041
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.0320667
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.0321591
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.0320805
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.0319547
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.0319603
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.0318949
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.0318923
[91]	valid_0's binary_logloss: 0.0319577
[92]	valid_0's binary_logloss: 0.0319232
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

Trening klas:  34%|███▍      | 171/500 [22:49<22:15,  4.06s/klasa, klasa=class_171, F1_klasy=0.8780, F1_macro=0.7700, drzewa=65]




Trening klas:  34%|███▍      | 172/500 [22:49<22:25,  4.10s/klasa, klasa=class_171, F1_klasy=0.8780, F1_macro=0.7700, drzewa=65]

[93]	valid_0's binary_logloss: 0.0318965
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.031984
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.0318365
[1]	valid_0's binary_logloss: 0.0327794
[2]	valid_0's binary_logloss: 0.0305163
[3]	valid_0's binary_logloss: 0.0286189
[4]	valid_0's binary_logloss: 0.0269075
[5]	valid_0's binary_logloss: 0.02541
[6]	valid_0's binary_logloss: 0.0240576
[7]	valid_0's binary_logloss: 0.0228292
[8]	valid_0's binary_logloss: 0.0217013
[9]	valid_0's binary_logloss: 0.0206844
[10]	valid_0's binary_logloss: 0.0197348
[11]	valid_0's binary_logloss: 0.01887
[12]	valid_0's binary_logloss: 0.0180574
[13]	valid_0's binary_logloss: 0.017312
[14]	valid_0's binary_logloss: 0.0165706
[15]	valid_0's binary_logloss: 0.015869
[16]	valid_0's binary_logloss: 0.0150829
[17]	valid_0's binary_logloss: 0.0144877
[18]	valid_0's binary_logloss: 0.0139488
[19]	valid_0's binary_logloss: 0.0134041
[20]	valid_0's binary_logloss: 0.0129557
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0125451
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.012083
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.011631
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0112791
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.0109462
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.0105956
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.0102952
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.0100315
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.00972113
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.00945109
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.00920211
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.009008
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.00876174
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.00853156
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.00831663
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.00804278
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.00788512
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.00762931
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.00750483
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.00725226
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.00714405
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.00704553
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.0068314
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.00664067
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.00645235
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.00631981
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.00623605
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.00609618
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.00594024
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.00588997
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.00572586
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.00563456
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.00549191
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.00533661
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.00522199
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.0051538
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.00505954
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.00498619
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.00491364
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.00487567
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.00482202
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.00477318
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.00472717
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.00468702
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.00469116
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.00466661
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.00464722
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.0046484
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.00466599
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.00468157
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.00460754
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.00462894
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.00456076
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.00448802
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.0045085
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.00450816
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.00450639
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.00451073
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.00452942
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.00453366
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.00449056
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.00445016
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.00441226
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.00442594
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.00440852
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.00436805
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.00431883
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.00430481
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.00427938
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.00428926
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.00429074
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.00430598
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.00429486
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.0042872
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.00429504
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.00432084
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.00436209
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.00437088
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.00441449
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.00442609
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.00444997
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.00446855
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.00448923
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.00451369
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.00452846
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.00452888
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.00458079
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.00461968
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.00460598
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.00465111
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.00468979
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 0.00469893
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 0.00472029
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 0.00472935
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 0.00474632
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[116]	valid_0's binary_logloss: 0.00475597
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[117]	valid_0's binary_logloss: 0.00475903
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[118]	valid_0's binary_logloss: 0.00476289

Trening klas:  34%|███▍      | 172/500 [22:52<22:25,  4.10s/klasa, klasa=class_172, F1_klasy=0.9160, F1_macro=0.7708, drzewa=89]




Trening klas:  35%|███▍      | 173/500 [22:52<20:57,  3.85s/klasa, klasa=class_172, F1_klasy=0.9160, F1_macro=0.7708, drzewa=89]

[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[119]	valid_0's binary_logloss: 0.00475451
[1]	valid_0's binary_logloss: 0.0250101
[2]	valid_0's binary_logloss: 0.02417
[3]	valid_0's binary_logloss: 0.0234278
[4]	valid_0's binary_logloss: 0.0226932
[5]	valid_0's binary_logloss: 0.0219474
[6]	valid_0's binary_logloss: 0.0213183
[7]	valid_0's binary_logloss: 0.0206745
[8]	valid_0's binary_logloss: 0.0201375
[9]	valid_0's binary_logloss: 0.0195995
[10]	valid_0's binary_logloss: 0.0191117
[11]	valid_0's binary_logloss: 0.0186914
[12]	valid_0's binary_logloss: 0.0180921
[13]	valid_0's binary_logloss: 0.0176087
[14]	valid_0's binary_logloss: 0.0172801
[15]	valid_0's binary_logloss: 0.0168742
[16]	valid_0's binary_logloss: 0.01641
[17]	valid_0's binary_logloss: 0.0160265
[18]	valid_0's binary_logloss: 0.0156538
[19]	valid_0's binary_logloss: 0.0153397
[20]	valid_0's binary_logloss: 0.01499
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0146159
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.014291
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.01402
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0137048
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.0134304
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.0132316
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.0130077
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.0128335
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.0126519
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.0124308
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.0122182
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.0120084
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.0118202
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.0116255
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.01145
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.0113049
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.0112374
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.0111491
[39]	valid_0's binary_logloss: 0.0110204
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.0109172
[41]	valid_0's binary_logloss: 0.0107624
[42]	valid_0's binary_logloss: 0.0106323
[43]	valid_0's binary_logloss: 0.0104804
[44]	valid_0's binary_logloss: 0.0103674
[45]	valid_0's binary_logloss: 0.0102733
[46]	valid_0's binary_logloss: 0.0101386
[47]	valid_0's binary_logloss: 0.0100452
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.00996937
[49]	valid_0's binary_logloss: 0.00992942
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.0098665
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.009777
[52]	valid_0's binary_logloss: 0.00967422
[53]	valid_0's binary_logloss: 0.0096166
[54]	valid_0's binary_logloss: 0.0094845
[55]	valid_0's binary_logloss: 0.00943569
[56]	valid_0's binary_logloss: 0.00936654
[57]	valid_0's binary_logloss: 0.00931433
[58]	valid_0's binary_logloss: 0.00930493
[59]	valid_0's binary_logloss: 0.00925211
[60]	valid_0's binary_logloss: 0.00921432
[61]	valid_0's binary_logloss: 0.00914513
[62]	valid_0's binary_logloss: 0.00911908
[63]	valid_0's binary_logloss: 0.00909565
[64]	valid_0's binary_logloss: 0.00904424
[65]	valid_0's binary_logloss: 0.00896338
[66]	valid_0's binary_logloss: 0.00888673
[67]	valid_0's binary_logloss: 0.00883364
[68]	valid_0's binary_logloss: 0.00878463
[69]	valid_0's binary_logloss: 0.00871472
[70]	valid_0's binary_logloss: 0.00866429
[71]	valid_0's binary_logloss: 0.00868799
[72]	valid_0's binary_logloss: 0.00873195
[73]	valid_0's binary_logloss: 0.00874547
[74]	valid_0's binary_logloss: 0.0087233
[75]	valid_0's binary_logloss: 0.00876461
[76]	valid_0's binary_logloss: 0.00878377
[77]	valid_0's binary_logloss: 0.00880731
[78]	valid_0's binary_logloss: 0.00878258
[79]	valid_0's binary_logloss: 0.00881282
[80]	valid_0's binary_logloss: 0.00878334
[81]	valid_0's binary_logloss: 0.00875195
[82]	valid_0's binary_logloss: 0.00874395
[83]	valid_0's binary_logloss: 0.00872253
[84]	valid_0's binary_logloss: 0.00869105
[85]	valid_0's binary_logloss: 0.00868965
[86]	valid_0's binary_logloss: 0.00868691
[87]	valid_0's binary_logloss: 0.00869695
[88]	valid_0's binary_logloss: 0.00870707
[89]	valid_0's binary_logloss: 0.00871072
[90]	valid_0's binary_logloss: 0.00869469
[91]	valid_0's binary_logloss: 0.00871263
[92]	valid_0's binary_logloss: 0.00866952
[93]	valid_0's binary_logloss: 0.00862727
[94]	valid_0's binary_logloss: 0.00859815
[95]	valid_0's binary_logloss: 0.00859052
[96]	valid_0's binary_logloss: 0.00858959
[97]	valid_0's binary_logloss: 0.00858943
[98]	valid_0's binary_logloss: 0.00860959
[99]	valid_0's binary_logloss: 0.008635
[100]	valid_0's binary_logloss: 0.00867133
[101]	valid_0's binary_logloss: 0.00866886
[102]	valid_0's binary_logloss: 0.00863873
[103]	valid_0's binary_logloss: 0.00860623
[104]	valid_0's binary_logloss: 0.00858326
[105]	valid_0's binary_logloss: 0.00858014
[106]	valid_0's binary_logloss: 0.00860661
[107]	valid_0's binary_logloss: 0.00865209
[108]	valid_0's binary_logloss: 0.00870934
[109]	valid_0's binary_logloss: 0.00872361
[110]	valid_0's binary_logloss: 0.00876399
[111]	valid_0's binary_logloss: 0.00877264
[112]	valid_0's binary_logloss: 0.00879757
[113]	valid_0's binary_logloss: 0.00876477
[114]	valid_0's binary_logloss: 0.00878539
[115]	valid_0's binary_logloss: 0.00873295
[116]	valid_0's binary_logloss: 0.00869745
[117]	valid_0's binary_logloss: 0.0087815
[118]	valid_0's binary_logloss: 0.00876271
[119]	valid_0's binary_logloss: 0.00879489
[120]	valid_0's binary_logloss: 0.00882312
[121]	valid_0's binary_logloss: 0.00883591
[122]	valid_0's binary_logloss: 0.00890721
[123]	valid_0's binary_logloss: 0.00896567
[124]	valid_0's binary_logloss: 0.00904152
[125]	valid_0's binary_logloss: 0.00910847
[126]	valid_0's binary_logloss: 0.00916721
[127]	valid_0's binary_logloss: 0.00915674
[128]	valid_0's binary_logloss: 0.00917461
[129]	valid_0's binary_logloss: 0.00918267
[130]	valid_0's binary_logloss: 0.00922725
[131]	valid_0's binary_logloss: 0.00921419
[132]	valid_0's binary_logloss: 0.00922286

Trening klas:  35%|███▍      | 173/500 [23:00<20:57,  3.85s/klasa, klasa=class_173, F1_klasy=0.3704, F1_macro=0.7685, drzewa=105]




Trening klas:  35%|███▍      | 174/500 [23:00<26:43,  4.92s/klasa, klasa=class_173, F1_klasy=0.3704, F1_macro=0.7685, drzewa=105]

[133]	valid_0's binary_logloss: 0.0092272
[134]	valid_0's binary_logloss: 0.00922353
[135]	valid_0's binary_logloss: 0.00921458
[1]	valid_0's binary_logloss: 0.0207281
[2]	valid_0's binary_logloss: 0.019713
[3]	valid_0's binary_logloss: 0.0187389
[4]	valid_0's binary_logloss: 0.0178888
[5]	valid_0's binary_logloss: 0.0170201
[6]	valid_0's binary_logloss: 0.0162268
[7]	valid_0's binary_logloss: 0.0154874
[8]	valid_0's binary_logloss: 0.0147952
[9]	valid_0's binary_logloss: 0.0141272
[10]	valid_0's binary_logloss: 0.0135093
[11]	valid_0's binary_logloss: 0.0129291
[12]	valid_0's binary_logloss: 0.0123345
[13]	valid_0's binary_logloss: 0.0117788
[14]	valid_0's binary_logloss: 0.011279
[15]	valid_0's binary_logloss: 0.0108029
[16]	valid_0's binary_logloss: 0.010354
[17]	valid_0's binary_logloss: 0.00989557
[18]	valid_0's binary_logloss: 0.00949684
[19]	valid_0's binary_logloss: 0.00908699
[20]	valid_0's binary_logloss: 0.00873206
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0083234
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.00794406
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.00764755
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.00732636
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.00705893
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.00677449
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.00650633
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.00623061
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.00597478
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.00574296
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.00552721
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.00531445
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.00509547
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.00491695
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.00475648
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.00458061
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.00439918
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.00425014
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.00408979
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.00391084
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.00377918
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.00363233
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.00350982
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.00339373
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.00328623
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.00316935
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.00308056
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.00297732
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.00290824
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.00282767
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.00274158
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.00266223
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.00259664
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.00252273
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.00244664
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.00237308
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.00230717
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.00224677
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.00219213
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.00215155
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.00211761
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.00207511
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.00202541
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.00199965
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.0019829
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.00195065
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.001916
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.00188649
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.0018615
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.00182588
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.0018052
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.0017949
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.00179026
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.00176247
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.00176171
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.00170915
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.00169332
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.00168334
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.0016647
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.00165335
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.00163667
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.0016269
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.00161926
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.00160212
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.0015944
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.00159747
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.00158073
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.0015699
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.00156786
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.00155754
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.00154593
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.00155341
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.00155124
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.0015518
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.00154198
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.00155188
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.00156479
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.00157543
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.00158378
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.00159018
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.00159254
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.00160612
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.00160841
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.00161004
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.00161982
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.00163594
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.00162425
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.00162575
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.00164254
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.00164566
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.00165151
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 0.00166317
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 0.00166629
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 0.00165081
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 0.0016485
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[116]	valid_0's binary_logloss: 0.00163041
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[117]	valid_0's binary_logloss: 0.00163129
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[118]	valid_0's binary_logloss: 0.0016232
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[119]	valid_0's binary_logloss: 0.00162932
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[120]	valid_0's binary_logloss: 0.00163739
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

Trening klas:  35%|███▍      | 174/500 [23:05<26:43,  4.92s/klasa, klasa=class_174, F1_klasy=0.6000, F1_macro=0.7676, drzewa=95]




Trening klas:  35%|███▌      | 175/500 [23:05<27:15,  5.03s/klasa, klasa=class_174, F1_klasy=0.6000, F1_macro=0.7676, drzewa=95]

[121]	valid_0's binary_logloss: 0.00164948
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[122]	valid_0's binary_logloss: 0.00165853
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[123]	valid_0's binary_logloss: 0.00167398
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[124]	valid_0's binary_logloss: 0.00168436
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[125]	valid_0's binary_logloss: 0.00169789
[1]	valid_0's binary_logloss: 0.022572
[2]	valid_0's binary_logloss: 0.0215771
[3]	valid_0's binary_logloss: 0.0207109
[4]	valid_0's binary_logloss: 0.0198398
[5]	valid_0's binary_logloss: 0.0190002
[6]	valid_0's binary_logloss: 0.0182818
[7]	valid_0's binary_logloss: 0.0175224
[8]	valid_0's binary_logloss: 0.0168397
[9]	valid_0's binary_logloss: 0.0160823
[10]	valid_0's binary_logloss: 0.0154713
[11]	valid_0's binary_logloss: 0.0147726
[12]	valid_0's binary_logloss: 0.0141098
[13]	valid_0's binary_logloss: 0.0134753
[14]	valid_0's binary_logloss: 0.0128694
[15]	valid_0's binary_logloss: 0.0122935
[16]	valid_0's binary_logloss: 0.0117488
[17]	valid_0's binary_logloss: 0.0112315
[18]	valid_0's binary_logloss: 0.0107711
[19]	valid_0's binary_logloss: 0.0103298
[20]	valid_0's binary_logloss: 0.0098989
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.00949997
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.00909488
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.00868696
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.00830657
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.00796236
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.0076658
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.00733245
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.00702102
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.00675202
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.00648156
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.0062342
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.00600886
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.00575797
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.00555897
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.00534457
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.0051849
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.00496604
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.00476317
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.00456394
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.00437321
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.00420807
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.00406878
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.00392285
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.00380893
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.00367989
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.0035479
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.0034216
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.003298
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.00318375
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.0030808
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.00298015
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.00288758
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.0027952
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.00271171
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.00263611
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.00255489
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.00248051
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.00241189
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.00234806
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.00228025
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.00223133
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.00217518
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.00212238
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.00207217
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.00203115
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.00198517
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.00194564
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.00190872
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.00187215
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.00183666
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.00180604
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.00177766
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.00174926
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.00171986
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.00169539
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.00166914
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.00164388
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.00162079
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.00160221
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.00158492
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.00155681
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.00154047
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.00151023
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.00148742
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.00145838
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.0014316
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.00141974
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.00139555
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.00137472
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.00136959
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.00134796
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.00134182
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.00133622
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.00133008
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.00132764
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.00132497
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.00132376
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.00131362
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.00131272
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.00129742
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.00129643
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.00129648
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.00129256
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.0012873
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.00128291
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.00128102
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.0012829
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.00128206
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.00128037
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.00127981
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.00127963
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 0.00127975
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 0.00128031
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 0.00127954
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 0.00128075
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[116]	valid_0's binary_logloss: 0.00127876
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[117]	valid_0's binary_logloss: 0.00127884
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[118]	valid_0's binary_logloss: 0.00127025
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[119]	valid_0's binary_logloss: 0.00127224
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[120]	valid_0's binary_logloss: 0.00126526
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[121]	valid_0's binary_logloss: 0.00126857
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[122]	valid_0's binary_logloss: 0.00127149
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[123]	valid_0's binary_logloss: 0.0012747
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[124]	valid_0's binary_logloss: 0.00126738
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[125]	valid_0's binary_logloss: 0.00126627
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[126]	valid_0's binary_logloss: 0.00126351
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[127]	valid_0's binary_logloss: 0.00126269
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[128]	valid_0's binary_logloss: 0.00126387
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[129]	valid_0's binary_logloss: 0.0012658
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[130]	valid_0's binary_logloss: 0.00126928
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[131]	valid_0's binary_logloss: 0.00126335
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[132]	valid_0's binary_logloss: 0.0012537
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[133]	valid_0's binary_logloss: 0.00124481
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[134]	valid_0's binary_logloss: 0.00127733
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[135]	valid_0's binary_logloss: 0.00127976
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[136]	valid_0's binary_logloss: 0.00128451
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[137]	valid_0's binary_logloss: 0.00128929
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[138]	valid_0's binary_logloss: 0.00129616
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[139]	valid_0's binary_logloss: 0.00130317
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[140]	valid_0's binary_logloss: 0.00131561
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[141]	valid_0's binary_logloss: 0.001321
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[142]	valid_0's binary_logloss: 0.00132708
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[143]	valid_0's binary_logloss: 0.00133096
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[144]	valid_0's binary_logloss: 0.00133639
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[145]	valid_0's binary_logloss: 0.00134209
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[146]	valid_0's binary_logloss: 0.00134415
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[147]	valid_0's binary_logloss: 0.0013437
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[148]	valid_0's binary_logloss: 0.00134615
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[149]	valid_0's binary_logloss: 0.0013484
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[150]	valid_0's binary_logloss: 0.00134052
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[151]	valid_0's binary_logloss: 0.00133576
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[152]	valid_0's binary_logloss: 0.00133446
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[153]	valid_0's binary_logloss: 0.00132684
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[154]	valid_0's binary_logloss: 0.00132263
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[155]	valid_0's binary_logloss: 0.00131474
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[156]	valid_0's binary_logloss: 0.00131739
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[157]	valid_0's binary_logloss: 0.00132314
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[158]	valid_0's binary_logloss: 0.00132586
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[159]	valid_0's binary_logloss: 0.00132986
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[160]	valid_0's binary_logloss: 0.00133495
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[161]	valid_0's binary_logloss: 0.00134451
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[162]	valid_0's binary_logloss: 0.00135384
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[163]	valid_0's binary_logloss: 0.00136255

Trening klas:  35%|███▌      | 175/500 [23:12<27:15,  5.03s/klasa, klasa=class_175, F1_klasy=0.6667, F1_macro=0.7670, drzewa=133]




Trening klas:  35%|███▌      | 176/500 [23:12<30:15,  5.60s/klasa, klasa=class_175, F1_klasy=0.6667, F1_macro=0.7670, drzewa=133]

[1]	valid_0's binary_logloss: 0.0242067
[2]	valid_0's binary_logloss: 0.0232515
[3]	valid_0's binary_logloss: 0.0223305
[4]	valid_0's binary_logloss: 0.0216293
[5]	valid_0's binary_logloss: 0.0208699
[6]	valid_0's binary_logloss: 0.0201831
[7]	valid_0's binary_logloss: 0.019516
[8]	valid_0's binary_logloss: 0.0188714
[9]	valid_0's binary_logloss: 0.0182307
[10]	valid_0's binary_logloss: 0.0176812
[11]	valid_0's binary_logloss: 0.0171657
[12]	valid_0's binary_logloss: 0.0166265
[13]	valid_0's binary_logloss: 0.0161914
[14]	valid_0's binary_logloss: 0.0156604
[15]	valid_0's binary_logloss: 0.015173
[16]	valid_0's binary_logloss: 0.0147859
[17]	valid_0's binary_logloss: 0.0143457
[18]	valid_0's binary_logloss: 0.01399
[19]	valid_0's binary_logloss: 0.0137065
[20]	valid_0's binary_logloss: 0.0134171
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0130811
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.01278
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.0124626
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0122407
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.0119402
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.0117249
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.0115281
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.0113216
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.0111309
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.0109743
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.010766
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.0105626
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.0103685
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.0101959
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.0100309
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.00989655
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.00969354
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.00954303
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.00940506
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.00927766
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.00911642
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.00896719
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.0088153
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.00873499
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.00869366
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.00854028
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.00846337
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.00840684
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.00837566
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.00828418
[51]	valid_0's binary_logloss: 0.00824444
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.00823281
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.00822383
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.00821438
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.00812979
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.0080925
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.00802341
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.00799416
[59]	valid_0's binary_logloss: 0.00790494
[60]	valid_0's binary_logloss: 0.00788675
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.00782908
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.00780067
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.00783827
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.00776238
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.00777327
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.00775618
[67]	valid_0's binary_logloss: 0.00774526
[68]	valid_0's binary_logloss: 0.00772376
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.00772158
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.00775986
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.00772287
[72]	valid_0's binary_logloss: 0.00773055
[73]	valid_0's binary_logloss: 0.00768551
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.00767802
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.00766877
[76]	valid_0's binary_logloss: 0.00764199
[77]	valid_0's binary_logloss: 0.00765603
[78]	valid_0's binary_logloss: 0.00764485
[79]	valid_0's binary_logloss: 0.007625
[80]	valid_0's binary_logloss: 0.00760803
[81]	valid_0's binary_logloss: 0.00760954
[82]	valid_0's binary_logloss: 0.00760048
[83]	valid_0's binary_logloss: 0.00756523
[84]	valid_0's binary_logloss: 0.00760334
[85]	valid_0's binary_logloss: 0.00764709
[86]	valid_0's binary_logloss: 0.00760183
[87]	valid_0's binary_logloss: 0.00759301
[88]	valid_0's binary_logloss: 0.00753144
[89]	valid_0's binary_logloss: 0.00752294
[90]	valid_0's binary_logloss: 0.00755322
[91]	valid_0's binary_logloss: 0.00754176
[92]	valid_0's binary_logloss: 0.00752425
[93]	valid_0's binary_logloss: 0.00746973
[94]	valid_0's binary_logloss: 0.00749757
[95]	valid_0's binary_logloss: 0.00753419
[96]	valid_0's binary_logloss: 0.00761426
[97]	valid_0's binary_logloss: 0.0076396
[98]	valid_0's binary_logloss: 0.00770369
[99]	valid_0's binary_logloss: 0.00770827
[100]	valid_0's binary_logloss: 0.00776137
[101]	valid_0's binary_logloss: 0.00781105
[102]	valid_0's binary_logloss: 0.00784712
[103]	valid_0's binary_logloss: 0.00787232
[104]	valid_0's binary_logloss: 0.00791795
[105]	valid_0's binary_logloss: 0.00790729
[106]	valid_0's binary_logloss: 0.00794041
[107]	valid_0's binary_logloss: 0.00794787
[108]	valid_0's binary_logloss: 0.00797972
[109]	valid_0's binary_logloss: 0.00799566
[110]	valid_0's binary_logloss: 0.00797712
[111]	valid_0's binary_logloss: 0.00798109
[112]	valid_0's binary_logloss: 0.00795094
[113]	valid_0's binary_logloss: 0.00795261
[114]	valid_0's binary_logloss: 0.00799379
[115]	valid_0's binary_logloss: 0.00800283
[116]	valid_0's binary_logloss: 0.00799215
[117]	valid_0's binary_logloss: 0.00801704
[118]	valid_0's binary_logloss: 0.00799528
[119]	valid_0's binary_logloss: 0.00797555
[120]	valid_0's binary_logloss: 0.00797851

Trening klas:  35%|███▌      | 176/500 [23:18<30:15,  5.60s/klasa, klasa=class_176, F1_klasy=0.4286, F1_macro=0.7651, drzewa=93]




Trening klas:  35%|███▌      | 177/500 [23:18<30:40,  5.70s/klasa, klasa=class_176, F1_klasy=0.4286, F1_macro=0.7651, drzewa=93]

[121]	valid_0's binary_logloss: 0.00804341
[122]	valid_0's binary_logloss: 0.00807327
[123]	valid_0's binary_logloss: 0.00812357
[1]	valid_0's binary_logloss: 0.0325862
[2]	valid_0's binary_logloss: 0.0304924
[3]	valid_0's binary_logloss: 0.0285511
[4]	valid_0's binary_logloss: 0.0269978
[5]	valid_0's binary_logloss: 0.0256176
[6]	valid_0's binary_logloss: 0.0244243
[7]	valid_0's binary_logloss: 0.0232511
[8]	valid_0's binary_logloss: 0.0221822
[9]	valid_0's binary_logloss: 0.0212472
[10]	valid_0's binary_logloss: 0.0203429
[11]	valid_0's binary_logloss: 0.019727
[12]	valid_0's binary_logloss: 0.0189522
[13]	valid_0's binary_logloss: 0.0182128
[14]	valid_0's binary_logloss: 0.0175223
[15]	valid_0's binary_logloss: 0.0168519
[16]	valid_0's binary_logloss: 0.0162006
[17]	valid_0's binary_logloss: 0.015577
[18]	valid_0's binary_logloss: 0.0150073
[19]	valid_0's binary_logloss: 0.0144636
[20]	valid_0's binary_logloss: 0.0139807
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0135895
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0131299
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.0127448
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0124193
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.0120544
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.0117374
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.01139
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.0111198
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.0108549
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.0106133
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.0103729
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.0101072
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.00981482
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.00954162
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.00932081
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.00905882
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.00882716
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.00862452
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.00847694
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.00826339
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.00813318
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.00798696
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.00785937
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.0076958
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.00756642
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.0074677
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.00737224
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.00722981
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.00710129
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.00699223
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.00687988
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.00680566
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.00658178
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.00647437
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.0063617
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.00629665
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.00626757
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.00622571
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.00617762
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.00616132
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.00606873
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.00604629
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.00603204
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.00600356
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.00600361
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.00590934
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.00582445
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.00576952
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.00572821
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.00565428
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.00555424
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.00550486
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.00549491
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.00545531
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.00534919
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.00530329
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.00522454
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.0051588
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.00513732
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.00508118
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.00497254
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.00488336
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.00479887
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.00474328
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.00471978
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.00471647
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.00467418
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.00464628
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.00462137
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.00458777
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.0045831
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.00457794
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.00457262
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.00456526
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.0045984
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.00461534
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.00464185
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.00466974
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.00469873
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.00468785
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.00468952
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.00469114
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.00469561
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.00470862
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.00471523
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.00471691
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.00472516
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.00471947
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.00470597
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.00470343
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.00468427
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 0.00469009
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

Trening klas:  35%|███▌      | 177/500 [23:21<30:40,  5.70s/klasa, klasa=class_177, F1_klasy=0.9381, F1_macro=0.7660, drzewa=94]




Trening klas:  36%|███▌      | 178/500 [23:21<26:30,  4.94s/klasa, klasa=class_177, F1_klasy=0.9381, F1_macro=0.7660, drzewa=94]

[113]	valid_0's binary_logloss: 0.00468233
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 0.0046829
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 0.00468749
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[116]	valid_0's binary_logloss: 0.00469784
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[117]	valid_0's binary_logloss: 0.00469634
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[118]	valid_0's binary_logloss: 0.00471451
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[119]	valid_0's binary_logloss: 0.00469631
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[120]	valid_0's binary_logloss: 0.00470809
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[121]	valid_0's binary_logloss: 0.00473811
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[122]	valid_0's binary_logloss: 0.00474288
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[123]	valid_0's binary_logloss: 0.00474055
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[124]	valid_0's binary_logloss: 0.00475717
[1]	valid_0's binary_logloss: 0.0744056
[2]	valid_0's binary_logloss: 0.0719813
[3]	valid_0's binary_logloss: 0.0702535
[4]	valid_0's binary_logloss: 0.0683509
[5]	valid_0's binary_logloss: 0.0663873
[6]	valid_0's binary_logloss: 0.0649889
[7]	valid_0's binary_logloss: 0.0637088
[8]	valid_0's binary_logloss: 0.0626755
[9]	valid_0's binary_logloss: 0.0616241
[10]	valid_0's binary_logloss: 0.0603099
[11]	valid_0's binary_logloss: 0.0594448
[12]	valid_0's binary_logloss: 0.0586576
[13]	valid_0's binary_logloss: 0.0577447
[14]	valid_0's binary_logloss: 0.0567424
[15]	valid_0's binary_logloss: 0.0560834
[16]	valid_0's binary_logloss: 0.0552943
[17]	valid_0's binary_logloss: 0.054841
[18]	valid_0's binary_logloss: 0.054314
[19]	valid_0's binary_logloss: 0.0535398
[20]	valid_0's binary_logloss: 0.0527046
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0520953
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0515783
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.0509866
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0506502
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.0504076
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.0500306
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.04929
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.0487816
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.0483733
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.0480551
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.0478369
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.047503
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.0473829
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.0473498
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.0473671
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.0468148
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.0464475
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.0460986
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.0458761
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.0456936
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.0456272
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.0454751
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.0452738
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.0451979
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.0452825
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.0454235
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.0453504
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.0450003
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.0450905
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.0450652
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.0448462
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.0446629
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.044515
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.0443408
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.043983
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.0437106
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.0434075
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.0432987
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.0432964
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.0431805
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.0430781
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.0427253
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.0424058
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.0423984
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.0423108
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.042054
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.0421019
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.0420139
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.0421129
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.0419829
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.0418624
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.0417634
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.0418052
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.0417241
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.0417255
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.0417318
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.0416245
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.0416015
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.041654
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.0416888
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.0417366
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.0416677
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.0416272
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.041627
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.0416176
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.0415112
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.0413948
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.0414049
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.0413393
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.0412382
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.0413094
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.0413348
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.0413243
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.041315
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.0414497
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.0415218
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.0415219
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.0414198
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.0413184
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.0413262
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.0415543
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.0416792
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.0418758
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.0420798
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.0422484
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.0422813
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.0423618
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.0424533
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.0424663
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.0425411
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.0427246
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 0.0429128
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 0.0432033
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 0.0435022
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 0.0437728
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[116]	valid_0's binary_logloss: 0.0436234
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[117]	valid_0's binary_logloss: 0.0434775
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

Trening klas:  36%|███▌      | 178/500 [23:25<26:30,  4.94s/klasa, klasa=class_178, F1_klasy=0.7143, F1_macro=0.7658, drzewa=90]




Trening klas:  36%|███▌      | 179/500 [23:25<25:24,  4.75s/klasa, klasa=class_178, F1_klasy=0.7143, F1_macro=0.7658, drzewa=90]

[118]	valid_0's binary_logloss: 0.0434418
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[119]	valid_0's binary_logloss: 0.0433399
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[120]	valid_0's binary_logloss: 0.0434403
[1]	valid_0's binary_logloss: 0.0299364
[2]	valid_0's binary_logloss: 0.027889
[3]	valid_0's binary_logloss: 0.0261543
[4]	valid_0's binary_logloss: 0.0246649
[5]	valid_0's binary_logloss: 0.0233338
[6]	valid_0's binary_logloss: 0.0221396
[7]	valid_0's binary_logloss: 0.0210457
[8]	valid_0's binary_logloss: 0.0200475
[9]	valid_0's binary_logloss: 0.0191459
[10]	valid_0's binary_logloss: 0.0183092
[11]	valid_0's binary_logloss: 0.0175467
[12]	valid_0's binary_logloss: 0.0168458
[13]	valid_0's binary_logloss: 0.0162048
[14]	valid_0's binary_logloss: 0.0156062
[15]	valid_0's binary_logloss: 0.0150623
[16]	valid_0's binary_logloss: 0.0145499
[17]	valid_0's binary_logloss: 0.0140858
[18]	valid_0's binary_logloss: 0.0136358
[19]	valid_0's binary_logloss: 0.0132191
[20]	valid_0's binary_logloss: 0.0128582
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0124953
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0121614
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.0118523
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0115771
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.0113184
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.0110763
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.0108662
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.0106743
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.0104975
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.0103285
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.0101688
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.0100334
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.00991662
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.00980199
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.00969152
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.00959903
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.00951008
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.00945079
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.00939113
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.00933561
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.00929637
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.00926273
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.00924399
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.00923036
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.00921323
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.00920333
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.00919622
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.00918996
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.00919485
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.00910194
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.00910608
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.00912113
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.0091464
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.00916296
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.00918077
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.00921136
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.00923729
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.00926469
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.00930048
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.00934871
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.00894734
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.00896826
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.00871521
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.00853686
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.00856802
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.00861804
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.00866896
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.00872512
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.00877963
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.00884188
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.00888058
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.00890431
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.00894701
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.00898967
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.00903527
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.0089408
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.00884144
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.00878763
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.00868201
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.0087171
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.00868739
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.00867694
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.00867944
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.00865618
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.00869438
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.00848715
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.0085637
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.00861932
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.00868443
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.00874884
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.00875976
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.00881367
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.00881969
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.00883202
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.00884181
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.00883385
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.00886011
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.0088168
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.00878985
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.00881011
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.00884209
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.00884752
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.0088714
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.00891829
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.00897065
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.00893316
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.00892415
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.00893781
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.00891406
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.00890895
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.00890321
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 0.008886
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 0.00890973
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 0.00888114
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 0.00891175
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[116]	valid_0's binary_logloss: 0.00897005

Trening klas:  36%|███▌      | 179/500 [23:29<25:24,  4.75s/klasa, klasa=class_179, F1_klasy=0.8618, F1_macro=0.7663, drzewa=86]




Trening klas:  36%|███▌      | 180/500 [23:29<23:20,  4.38s/klasa, klasa=class_179, F1_klasy=0.8618, F1_macro=0.7663, drzewa=86]

[1]	valid_0's binary_logloss: 0.115399
[2]	valid_0's binary_logloss: 0.11438
[3]	valid_0's binary_logloss: 0.11389
[4]	valid_0's binary_logloss: 0.112874
[5]	valid_0's binary_logloss: 0.111982
[6]	valid_0's binary_logloss: 0.11146
[7]	valid_0's binary_logloss: 0.110599
[8]	valid_0's binary_logloss: 0.110072
[9]	valid_0's binary_logloss: 0.109706
[10]	valid_0's binary_logloss: 0.109147
[11]	valid_0's binary_logloss: 0.108469
[12]	valid_0's binary_logloss: 0.107967
[13]	valid_0's binary_logloss: 0.107526
[14]	valid_0's binary_logloss: 0.107389
[15]	valid_0's binary_logloss: 0.107178
[16]	valid_0's binary_logloss: 0.106969
[17]	valid_0's binary_logloss: 0.106503
[18]	valid_0's binary_logloss: 0.106113
[19]	valid_0's binary_logloss: 0.106002
[20]	valid_0's binary_logloss: 0.105876
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.105604
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.105529
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.105507
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.105538
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.105484
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.105423
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.105261
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.105598
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.105199
[30]	valid_0's binary_logloss: 0.105184
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.104783
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.104722
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.104811
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.104956
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.105228
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.105107
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.105403
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.105571
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.105172
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.10515
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.105056
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.105162
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.105243
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.105267
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.105794
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.105797
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.105722
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.105498
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.105833
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.105912
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.105813
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.105628
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.10558
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.105707
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.105792
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.106027
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.105991
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.106208
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

Trening klas:  36%|███▌      | 180/500 [23:33<23:20,  4.38s/klasa, klasa=class_180, F1_klasy=0.3519, F1_macro=0.7640, drzewa=32]




Trening klas:  36%|███▌      | 181/500 [23:33<22:40,  4.27s/klasa, klasa=class_180, F1_klasy=0.3519, F1_macro=0.7640, drzewa=32]

[59]	valid_0's binary_logloss: 0.106185
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.1061
[61]	valid_0's binary_logloss: 0.106504
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.106699
[1]	valid_0's binary_logloss: 0.0305605
[2]	valid_0's binary_logloss: 0.0296635
[3]	valid_0's binary_logloss: 0.0288937
[4]	valid_0's binary_logloss: 0.0281983
[5]	valid_0's binary_logloss: 0.0274474
[6]	valid_0's binary_logloss: 0.0268006
[7]	valid_0's binary_logloss: 0.0261629
[8]	valid_0's binary_logloss: 0.0255986
[9]	valid_0's binary_logloss: 0.0250683
[10]	valid_0's binary_logloss: 0.0246616
[11]	valid_0's binary_logloss: 0.024164
[12]	valid_0's binary_logloss: 0.023717
[13]	valid_0's binary_logloss: 0.0233456
[14]	valid_0's binary_logloss: 0.0230714
[15]	valid_0's binary_logloss: 0.0227238
[16]	valid_0's binary_logloss: 0.0223629
[17]	valid_0's binary_logloss: 0.0220446
[18]	valid_0's binary_logloss: 0.0218586
[19]	valid_0's binary_logloss: 0.021482
[20]	valid_0's binary_logloss: 0.0212513
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0209697
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0206412
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.0204031
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0201532
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.019879
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.019491
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.0192323
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.0188827
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.018669
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.0185409
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.0182629
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.0180783
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.017853
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.017612
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.0174374
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.0172731
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.0171521
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.0171303
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.017041
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.0169705
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.0168607
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.0166749
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.0165008
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.0163437
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.0161824
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.0160046
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.015887
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.0157787
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.0156603
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.0155306
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.0154138
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.0153119
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.0152885
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.0151795
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.0151863
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.0150331
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.0150388
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.0149352
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.0148422
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.0147532
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.0146317
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.0145401
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.0144306
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.0144017
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.0143669
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.0143728
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.0143156
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.0142605
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.0142293
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.0141483
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.0140958
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.0141478
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.0141765
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.0141472
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.0140601
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.0140338
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.013971
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.0139293
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.0138616
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.013852
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.0138006
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.0137484
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.0136669
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.0135899
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.013495
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.0134154
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.0133519
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.0133595
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.0133478
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.0133791
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.0133903
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.0133478
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.0133783
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.0133856
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.0134246
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.013403
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.0133967
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.0133793
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.0133756
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.0134006
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.0134183
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.0134575
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.0134831
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.0134882
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.0135334
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.0135891
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.0135688
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.0135792
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.0136133
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.01365
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.0136603
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 0.0136809
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 0.0136838
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 0.0137242
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 0.0137222
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[116]	valid_0's binary_logloss: 0.0137259
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[117]	valid_0's binary_logloss: 0.0137962
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[118]	valid_0's binary_logloss: 0.0138259
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

Trening klas:  36%|███▌      | 181/500 [23:38<22:40,  4.27s/klasa, klasa=class_181, F1_klasy=0.2273, F1_macro=0.7610, drzewa=92]




Trening klas:  36%|███▋      | 182/500 [23:38<23:58,  4.52s/klasa, klasa=class_181, F1_klasy=0.2273, F1_macro=0.7610, drzewa=92]

[119]	valid_0's binary_logloss: 0.0138144
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[120]	valid_0's binary_logloss: 0.0138065
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[121]	valid_0's binary_logloss: 0.0138529
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[122]	valid_0's binary_logloss: 0.0139142
[1]	valid_0's binary_logloss: 0.0291045
[2]	valid_0's binary_logloss: 0.0269989
[3]	valid_0's binary_logloss: 0.0251868
[4]	valid_0's binary_logloss: 0.0235753
[5]	valid_0's binary_logloss: 0.0221266
[6]	valid_0's binary_logloss: 0.0208043
[7]	valid_0's binary_logloss: 0.0195979
[8]	valid_0's binary_logloss: 0.0184973
[9]	valid_0's binary_logloss: 0.0174806
[10]	valid_0's binary_logloss: 0.016548
[11]	valid_0's binary_logloss: 0.0156944
[12]	valid_0's binary_logloss: 0.0149016
[13]	valid_0's binary_logloss: 0.0141776
[14]	valid_0's binary_logloss: 0.0134811
[15]	valid_0's binary_logloss: 0.0128362
[16]	valid_0's binary_logloss: 0.0121892
[17]	valid_0's binary_logloss: 0.0115834
[18]	valid_0's binary_logloss: 0.0110214
[19]	valid_0's binary_logloss: 0.0104703
[20]	valid_0's binary_logloss: 0.00996445
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.00948602
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.00902653
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.00860055
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.00818845
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.0077992
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.00741673
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.00707694
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.0067335
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.00643105
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.00612727
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.00586428
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.00561649
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.00539991
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.0051786
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.00497563
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.00474704
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.00454112
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.00434696
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.00415122
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.00396531
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.00377622
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.00361667
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.00346737
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.00331981
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.00318602
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.00304731
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.00290977
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.00280118
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.00267252
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.00256661
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.00246343
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.00236686
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.00226179
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.00217576
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.00208018
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.00200407
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.00193962
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.00185678
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.0017782
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.0017249
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.0016758
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.0016305
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.00158884
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.00153446
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.00149825
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.00145036
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.00140554
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.00135273
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.00130796
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.00127058
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.00123575
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.00120339
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.00117341
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.00114571
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.00109727
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.00106712
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.00103607
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.00100694
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.00098208
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.000971148
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.000933518
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.000897625
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.000863393
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.000830706
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.000799571
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.000771869
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.000761119
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.000733977
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.00072713
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.000702945
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.00068078
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.000659721
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.000653733
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.000637713
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.000635516
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.000632861
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.000631164
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.000630401
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.000630549
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.000633568
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.00061746
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.000611944
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.00059384
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.000577768
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.000560981
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.000546027
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.000535558
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.000521888
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.000508744
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.000494454
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.000491771
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 0.000489701
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 0.000488219
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 0.000482237
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 0.000481529
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[116]	valid_0's binary_logloss: 0.000470974
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[117]	valid_0's binary_logloss: 0.000470874
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[118]	valid_0's binary_logloss: 0.000458069
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[119]	valid_0's binary_logloss: 0.000458017
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[120]	valid_0's binary_logloss: 0.000457278
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[121]	valid_0's binary_logloss: 0.000447703
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[122]	valid_0's binary_logloss: 0.000437677
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[123]	valid_0's binary_logloss: 0.00042903
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[124]	valid_0's binary_logloss: 0.000420715
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[125]	valid_0's binary_logloss: 0.000411908
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[126]	valid_0's binary_logloss: 0.000415666
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[127]	valid_0's binary_logloss: 0.000415879
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[128]	valid_0's binary_logloss: 0.000416852
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[129]	valid_0's binary_logloss: 0.000412153
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[130]	valid_0's binary_logloss: 0.00040258
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[131]	valid_0's binary_logloss: 0.000395875
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[132]	valid_0's binary_logloss: 0.000389267
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[133]	valid_0's binary_logloss: 0.000389411
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[134]	valid_0's binary_logloss: 0.000392434
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[135]	valid_0's binary_logloss: 0.000384449
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[136]	valid_0's binary_logloss: 0.000378904
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[137]	valid_0's binary_logloss: 0.000382328
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[138]	valid_0's binary_logloss: 0.000377168
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[139]	valid_0's binary_logloss: 0.000379671
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[140]	valid_0's binary_logloss: 0.000382452
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[141]	valid_0's binary_logloss: 0.000379214
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[142]	valid_0's binary_logloss: 0.000370147
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[143]	valid_0's binary_logloss: 0.000361316
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[144]	valid_0's binary_logloss: 0.000353952
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[145]	valid_0's binary_logloss: 0.000346389
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[146]	valid_0's binary_logloss: 0.000350425
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[147]	valid_0's binary_logloss: 0.000343937
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[148]	valid_0's binary_logloss: 0.000339107
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[149]	valid_0's binary_logloss: 0.000337576
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[150]	valid_0's binary_logloss: 0.000341753
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[151]	valid_0's binary_logloss: 0.000339997
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[152]	valid_0's binary_logloss: 0.000335326
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[153]	valid_0's binary_logloss: 0.000330232
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[154]	valid_0's binary_logloss: 0.000325806
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[155]	valid_0's binary_logloss: 0.000324469
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[156]	valid_0's binary_logloss: 0.000320692
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[157]	valid_0's binary_logloss: 0.000317855
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[158]	valid_0's binary_logloss: 0.000314585
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[159]	valid_0's binary_logloss: 0.000311463
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[160]	valid_0's binary_logloss: 0.000308114
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[161]	valid_0's binary_logloss: 0.000310757
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[162]	valid_0's binary_logloss: 0.000313096
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[163]	valid_0's binary_logloss: 0.000316004
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[164]	valid_0's binary_logloss: 0.000311097
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[165]	valid_0's binary_logloss: 0.000308318
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[166]	valid_0's binary_logloss: 0.000307809
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[167]	valid_0's binary_logloss: 0.000312947
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[168]	valid_0's binary_logloss: 0.000316826
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[169]	valid_0's binary_logloss: 0.000320705
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[170]	valid_0's binary_logloss: 0.000320323
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[171]	valid_0's binary_logloss: 0.000310086
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[172]	valid_0's binary_logloss: 0.000313415
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[173]	valid_0's binary_logloss: 0.000318514
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[174]	valid_0's binary_logloss: 0.000315706
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[175]	valid_0's binary_logloss: 0.000307029
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[176]	valid_0's binary_logloss: 0.000302264
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[177]	valid_0's binary_logloss: 0.000298483
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[178]	valid_0's binary_logloss: 0.000297937
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[179]	valid_0's binary_logloss: 0.000297086

Trening klas:  36%|███▋      | 182/500 [23:42<23:58,  4.52s/klasa, klasa=class_182, F1_klasy=0.9907, F1_macro=0.7623, drzewa=181]




Trening klas:  37%|███▋      | 183/500 [23:42<22:50,  4.32s/klasa, klasa=class_182, F1_klasy=0.9907, F1_macro=0.7623, drzewa=181]

[1]	valid_0's binary_logloss: 0.0950678
[2]	valid_0's binary_logloss: 0.0941657
[3]	valid_0's binary_logloss: 0.0930578
[4]	valid_0's binary_logloss: 0.0916993
[5]	valid_0's binary_logloss: 0.0901902
[6]	valid_0's binary_logloss: 0.0892573
[7]	valid_0's binary_logloss: 0.0878048
[8]	valid_0's binary_logloss: 0.0873239
[9]	valid_0's binary_logloss: 0.0859792
[10]	valid_0's binary_logloss: 0.0854759
[11]	valid_0's binary_logloss: 0.0842837
[12]	valid_0's binary_logloss: 0.0832823
[13]	valid_0's binary_logloss: 0.0823635
[14]	valid_0's binary_logloss: 0.0812338
[15]	valid_0's binary_logloss: 0.080616
[16]	valid_0's binary_logloss: 0.0802468
[17]	valid_0's binary_logloss: 0.0798209
[18]	valid_0's binary_logloss: 0.079425
[19]	valid_0's binary_logloss: 0.079276
[20]	valid_0's binary_logloss: 0.0787647
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0785847
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0780822
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.0777738
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0775578
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.0775848
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.0773193
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.0771495
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.0772283
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.0770078
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.0768443
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.0765587
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.0764195
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.0766709
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.0765885
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.0767581
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.076387
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.0765767
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.0762753
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.0761426
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.0760832
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.0763178
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.0764387
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.0766117
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.0769612
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.0773076
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.0772063
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.0773373
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.0774902
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.0775912
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.0777146
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.0781129
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.0782635
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.0784149
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.0786412
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.0788984
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.0790297
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.0792143
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.0795307
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.07964
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.0797557
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.0798995
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.0801011
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.0799575
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.0796467
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.0799365
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.0802045
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.0803208
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.080616
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.0808261
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

Trening klas:  37%|███▋      | 183/500 [23:45<22:50,  4.32s/klasa, klasa=class_183, F1_klasy=0.6518, F1_macro=0.7617, drzewa=40]




Trening klas:  37%|███▋      | 184/500 [23:45<21:26,  4.07s/klasa, klasa=class_183, F1_klasy=0.6518, F1_macro=0.7617, drzewa=40]

[70]	valid_0's binary_logloss: 0.0811037
[1]	valid_0's binary_logloss: 0.0639482
[2]	valid_0's binary_logloss: 0.0622785
[3]	valid_0's binary_logloss: 0.0606201
[4]	valid_0's binary_logloss: 0.059221
[5]	valid_0's binary_logloss: 0.0574961
[6]	valid_0's binary_logloss: 0.0571985
[7]	valid_0's binary_logloss: 0.0559062
[8]	valid_0's binary_logloss: 0.054969
[9]	valid_0's binary_logloss: 0.0544949
[10]	valid_0's binary_logloss: 0.0535632
[11]	valid_0's binary_logloss: 0.0527268
[12]	valid_0's binary_logloss: 0.0518822
[13]	valid_0's binary_logloss: 0.0511039
[14]	valid_0's binary_logloss: 0.0503478
[15]	valid_0's binary_logloss: 0.0496464
[16]	valid_0's binary_logloss: 0.0490119
[17]	valid_0's binary_logloss: 0.048517
[18]	valid_0's binary_logloss: 0.0479008
[19]	valid_0's binary_logloss: 0.0473068
[20]	valid_0's binary_logloss: 0.0468439
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0464354
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0461203
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.045898
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0456569
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.0454028
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.0448082
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.0441812
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.0438474
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.0436702
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.0431537
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.042903
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.0426854
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.0426144
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.0425917
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.0425828
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.0423936
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.0421473
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.0419403
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.0415084
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.0414234
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.0413036
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.0413399
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.041313
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.0410611
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.0408216
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.0405426
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.0403761
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.0402308
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.0401295
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.0400535
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.0399608
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.0399365
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.0400344
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.0399566
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.0399009
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.039846
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.0397292
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.0397393
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.0395953
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.0392694
[61]	valid_0's binary_logloss: 0.0393134
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.0394142
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.0394735
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.0395791
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.0394895
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.0394539
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.0394004
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.0394479
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.0394809
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.0395432
[71]	valid_0's binary_logloss: 0.0393692
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.0392481
[73]	valid_0's binary_logloss: 0.0391758
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.0392049
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.0391253
[76]	valid_0's binary_logloss: 0.0390749
[77]	valid_0's binary_logloss: 0.039185
[78]	valid_0's binary_logloss: 0.039117
[79]	valid_0's binary_logloss: 0.0390568
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.0389774
[81]	valid_0's binary_logloss: 0.039006
[82]	valid_0's binary_logloss: 0.0390114
[83]	valid_0's binary_logloss: 0.0391858
[84]	valid_0's binary_logloss: 0.0392085
[85]	valid_0's binary_logloss: 0.0392627
[86]	valid_0's binary_logloss: 0.0392912
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.039422
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.0395327
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.0395287
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.039657
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.0396957
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.0398036
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.0398757
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.0398893
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.0399717
[96]	valid_0's binary_logloss: 0.0400847
[97]	valid_0's binary_logloss: 0.0400541
[98]	valid_0's binary_logloss: 0.0399684
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.0399096
[100]	valid_0's binary_logloss: 0.0399
[101]	valid_0's binary_logloss: 0.0398575
[102]	valid_0's binary_logloss: 0.0398949
[103]	valid_0's binary_logloss: 0.040008
[104]	valid_0's binary_logloss: 0.0401824
[105]	valid_0's binary_logloss: 0.0400977
[106]	valid_0's binary_logloss: 0.0401445
[107]	valid_0's binary_logloss: 0.0402677
[108]	valid_0's binary_logloss: 0.0405181
[109]	valid_0's binary_logloss: 0.0407226
[110]	valid_0's binary_logloss: 0.0409475

Trening klas:  37%|███▋      | 184/500 [23:50<21:26,  4.07s/klasa, klasa=class_184, F1_klasy=0.8130, F1_macro=0.7620, drzewa=80]




Trening klas:  37%|███▋      | 185/500 [23:50<23:01,  4.38s/klasa, klasa=class_184, F1_klasy=0.8130, F1_macro=0.7620, drzewa=80]

[1]	valid_0's binary_logloss: 0.0633538
[2]	valid_0's binary_logloss: 0.0616378
[3]	valid_0's binary_logloss: 0.0600073
[4]	valid_0's binary_logloss: 0.0586254
[5]	valid_0's binary_logloss: 0.0568662
[6]	valid_0's binary_logloss: 0.0563099
[7]	valid_0's binary_logloss: 0.0555493
[8]	valid_0's binary_logloss: 0.0546657
[9]	valid_0's binary_logloss: 0.0539303
[10]	valid_0's binary_logloss: 0.0532457
[11]	valid_0's binary_logloss: 0.0526835
[12]	valid_0's binary_logloss: 0.0516904
[13]	valid_0's binary_logloss: 0.0509855
[14]	valid_0's binary_logloss: 0.0502879
[15]	valid_0's binary_logloss: 0.0495478
[16]	valid_0's binary_logloss: 0.0487904
[17]	valid_0's binary_logloss: 0.048087
[18]	valid_0's binary_logloss: 0.0475201
[19]	valid_0's binary_logloss: 0.0469023
[20]	valid_0's binary_logloss: 0.0462432
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0459539
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0455616
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.0453637
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0451369
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.0447824
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.0440539
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.0435837
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.0431447
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.0428475
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.0425439
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.0420219
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.0415111
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.0414092
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.0413643
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.0413373
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.0411733
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.0409254
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.0407026
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.0404895
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.040322
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.0400191
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.0399673
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.0397876
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.0397265
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.0396488
[46]	valid_0's binary_logloss: 0.0394463
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.039246
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.0390984
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.039022
[50]	valid_0's binary_logloss: 0.0388414
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.0386333
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.0385761
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.0386434
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.0385917
[55]	valid_0's binary_logloss: 0.0385921
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.0385752
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.03853
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.0384815
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.0383569
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.0381453
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.0382706
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.0383245
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.0384101
[64]	valid_0's binary_logloss: 0.0385549
[65]	valid_0's binary_logloss: 0.0386484
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.0386299
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.0385121
[68]	valid_0's binary_logloss: 0.038486
[69]	valid_0's binary_logloss: 0.0384643
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.0384674
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.038425
[72]	valid_0's binary_logloss: 0.0384549
[73]	valid_0's binary_logloss: 0.0383619
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.0381489
[75]	valid_0's binary_logloss: 0.0380823
[76]	valid_0's binary_logloss: 0.0380696
[77]	valid_0's binary_logloss: 0.0379838
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.0379
[79]	valid_0's binary_logloss: 0.0379246
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.0378778
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.0377686
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.0377886
[83]	valid_0's binary_logloss: 0.037836
[84]	valid_0's binary_logloss: 0.0378599
[85]	valid_0's binary_logloss: 0.0379912
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.0380199
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.0380574
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.0381789
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.038266
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.0383996
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.0385444
[92]	valid_0's binary_logloss: 0.0386888
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.0387531
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.0388754
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.0391391
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.0391252
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.0392626
[98]	valid_0's binary_logloss: 0.0392348
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.0392241
[100]	valid_0's binary_logloss: 0.0392184
[101]	valid_0's binary_logloss: 0.0392344
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.0393048
[103]	valid_0's binary_logloss: 0.0394602
[104]	valid_0's binary_logloss: 0.0395336
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.0395866
[106]	valid_0's binary_logloss: 0.039596
[107]	valid_0's binary_logloss: 0.0396781
[108]	valid_0's binary_logloss: 0.0397876
[109]	valid_0's binary_logloss: 0.039758
[110]	valid_0's binary_logloss: 0.0398063
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

Trening klas:  37%|███▋      | 185/500 [23:55<23:01,  4.38s/klasa, klasa=class_185, F1_klasy=0.8209, F1_macro=0.7623, drzewa=81]




Trening klas:  37%|███▋      | 186/500 [23:55<23:59,  4.59s/klasa, klasa=class_185, F1_klasy=0.8209, F1_macro=0.7623, drzewa=81]

[111]	valid_0's binary_logloss: 0.0397555
[1]	valid_0's binary_logloss: 0.0227789
[2]	valid_0's binary_logloss: 0.0218393
[3]	valid_0's binary_logloss: 0.0210866
[4]	valid_0's binary_logloss: 0.0203276
[5]	valid_0's binary_logloss: 0.0197656
[6]	valid_0's binary_logloss: 0.0191763
[7]	valid_0's binary_logloss: 0.0186835
[8]	valid_0's binary_logloss: 0.0181154
[9]	valid_0's binary_logloss: 0.0175975
[10]	valid_0's binary_logloss: 0.0171237
[11]	valid_0's binary_logloss: 0.0166687
[12]	valid_0's binary_logloss: 0.0161508
[13]	valid_0's binary_logloss: 0.0157085
[14]	valid_0's binary_logloss: 0.0152296
[15]	valid_0's binary_logloss: 0.0148381
[16]	valid_0's binary_logloss: 0.0144221
[17]	valid_0's binary_logloss: 0.0140045
[18]	valid_0's binary_logloss: 0.0136767
[19]	valid_0's binary_logloss: 0.0134023
[20]	valid_0's binary_logloss: 0.0131436
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0128265
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0125658
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.0122525
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0120241
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.0118214
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.0116003
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.0114196
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.0112131
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.0110719
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.0108441
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.0106233
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.010397
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.01022
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.0100691
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.00991445
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.00979159
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.0096893
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.0095524
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.00944742
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.0093396
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.00921898
[42]	valid_0's binary_logloss: 0.00907275
[43]	valid_0's binary_logloss: 0.00895406
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.00887489
[45]	valid_0's binary_logloss: 0.00873407
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.00862603
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.00856052
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.00847176
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.0084756
[50]	valid_0's binary_logloss: 0.00842405
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.00834798
[52]	valid_0's binary_logloss: 0.00830122
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.00823524
[54]	valid_0's binary_logloss: 0.00817716
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.00815305
[56]	valid_0's binary_logloss: 0.00803713
[57]	valid_0's binary_logloss: 0.00789589
[58]	valid_0's binary_logloss: 0.00776458
[59]	valid_0's binary_logloss: 0.00766215
[60]	valid_0's binary_logloss: 0.00758241
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.00756485
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.00755395
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.00751272
[64]	valid_0's binary_logloss: 0.00746852
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.00745597
[66]	valid_0's binary_logloss: 0.00741232
[67]	valid_0's binary_logloss: 0.00735501
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.00732088
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.00729754
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.007282
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.00729164
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.00728788
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.00731808
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.00726661
[75]	valid_0's binary_logloss: 0.00728758
[76]	valid_0's binary_logloss: 0.00727952
[77]	valid_0's binary_logloss: 0.00723731
[78]	valid_0's binary_logloss: 0.00720798
[79]	valid_0's binary_logloss: 0.00720322
[80]	valid_0's binary_logloss: 0.00721858
[81]	valid_0's binary_logloss: 0.00720967
[82]	valid_0's binary_logloss: 0.00716653
[83]	valid_0's binary_logloss: 0.00715936
[84]	valid_0's binary_logloss: 0.00713701
[85]	valid_0's binary_logloss: 0.00719019
[86]	valid_0's binary_logloss: 0.00720582
[87]	valid_0's binary_logloss: 0.00720307
[88]	valid_0's binary_logloss: 0.00717607
[89]	valid_0's binary_logloss: 0.0071414
[90]	valid_0's binary_logloss: 0.00709484
[91]	valid_0's binary_logloss: 0.00700943
[92]	valid_0's binary_logloss: 0.00697766
[93]	valid_0's binary_logloss: 0.00699415
[94]	valid_0's binary_logloss: 0.00696456
[95]	valid_0's binary_logloss: 0.00701557
[96]	valid_0's binary_logloss: 0.0070328
[97]	valid_0's binary_logloss: 0.00700792
[98]	valid_0's binary_logloss: 0.00700556
[99]	valid_0's binary_logloss: 0.00695893
[100]	valid_0's binary_logloss: 0.00698839
[101]	valid_0's binary_logloss: 0.00701247
[102]	valid_0's binary_logloss: 0.00696552
[103]	valid_0's binary_logloss: 0.00691592
[104]	valid_0's binary_logloss: 0.00691122
[105]	valid_0's binary_logloss: 0.00692636
[106]	valid_0's binary_logloss: 0.00693555
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.00696753
[108]	valid_0's binary_logloss: 0.00699308
[109]	valid_0's binary_logloss: 0.00699825
[110]	valid_0's binary_logloss: 0.00698895
[111]	valid_0's binary_logloss: 0.00698446
[112]	valid_0's binary_logloss: 0.0069513
[113]	valid_0's binary_logloss: 0.006977
[114]	valid_0's binary_logloss: 0.00688654
[115]	valid_0's binary_logloss: 0.00687366
[116]	valid_0's binary_logloss: 0.00688154
[117]	valid_0's binary_logloss: 0.00690297
[118]	valid_0's binary_logloss: 0.00692975
[119]	valid_0's binary_logloss: 0.00692334
[120]	valid_0's binary_logloss: 0.0069552
[121]	valid_0's binary_logloss: 0.00697864
[122]	valid_0's binary_logloss: 0.00693522
[123]	valid_0's binary_logloss: 0.00699368
[124]	valid_0's binary_logloss: 0.00705919
[125]	valid_0's binary_logloss: 0.00709164
[126]	valid_0's binary_logloss: 0.00706468
[127]	valid_0's binary_logloss: 0.00705604
[128]	valid_0's binary_logloss: 0.00709371
[129]	valid_0's binary_logloss: 0.00705355
[130]	valid_0's binary_logloss: 0.007076
[131]	valid_0's binary_logloss: 0.00709625
[132]	valid_0's binary_logloss: 0.00710734
[133]	valid_0's binary_logloss: 0.00716825
[134]	valid_0's binary_logloss: 0.00717251
[135]	valid_0's binary_logloss: 0.00718912
[136]	valid_0's binary_logloss: 0.00721155
[137]	valid_0's binary_logloss: 0.00719411
[138]	valid_0's binary_logloss: 0.0072055
[139]	valid_0's binary_logloss: 0.00722249
[140]	valid_0's binary_logloss: 0.00723291
[141]	valid_0's binary_logloss: 0.0072423
[142]	valid_0's binary_logloss: 0.00722187

Trening klas:  37%|███▋      | 186/500 [24:03<23:59,  4.59s/klasa, klasa=class_186, F1_klasy=0.5714, F1_macro=0.7613, drzewa=115]




Trening klas:  37%|███▋      | 187/500 [24:03<27:49,  5.33s/klasa, klasa=class_186, F1_klasy=0.5714, F1_macro=0.7613, drzewa=115]

[143]	valid_0's binary_logloss: 0.00721412
[144]	valid_0's binary_logloss: 0.00722957
[145]	valid_0's binary_logloss: 0.0072257
[1]	valid_0's binary_logloss: 0.025752
[2]	valid_0's binary_logloss: 0.0250229
[3]	valid_0's binary_logloss: 0.0244067
[4]	valid_0's binary_logloss: 0.0235995
[5]	valid_0's binary_logloss: 0.0228514
[6]	valid_0's binary_logloss: 0.0221504
[7]	valid_0's binary_logloss: 0.0215225
[8]	valid_0's binary_logloss: 0.0210454
[9]	valid_0's binary_logloss: 0.0205174
[10]	valid_0's binary_logloss: 0.020027
[11]	valid_0's binary_logloss: 0.0195394
[12]	valid_0's binary_logloss: 0.0191176
[13]	valid_0's binary_logloss: 0.0187027
[14]	valid_0's binary_logloss: 0.0182559
[15]	valid_0's binary_logloss: 0.0179761
[16]	valid_0's binary_logloss: 0.0176533
[17]	valid_0's binary_logloss: 0.0173739
[18]	valid_0's binary_logloss: 0.0171234
[19]	valid_0's binary_logloss: 0.0168053
[20]	valid_0's binary_logloss: 0.0165624
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0162124
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0159677
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.0155456
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0153484
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.0150236
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.0147376
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.014424
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.014107
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.0139882
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.0138527
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.0136871
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.013526
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.0133514
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.0131172
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.0129294
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.0127638
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.0126496
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.0124451
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.0122884
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.0121555
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.0119997
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.0119025
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.0118567
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.0116859
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.0114994
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.0113671
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.0112725
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.0111769
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.01097
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.0108347
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.0106846
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.0105408
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.010497
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.0104464
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.0104053
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.0102614
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.0101921
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.010132
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.0100906
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.00994669
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.00985793
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.00973642
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.00967482
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.00960882
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.0095176
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.00938945
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.00937368
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.00930317
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.00929967
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.00928616
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.00929232
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.009211
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.00917194
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.00922691
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.00914438
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.00906503
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.00900406
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.00901116
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.00886506
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.00872801
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.00874704
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.00874519
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.00870935
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.00866452
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.00861945
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.00862179
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.00862669
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.00866591
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.00858349
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.00856812
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.00858083
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.0085113
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.00853519
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.00844718
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.00836224
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.00837214
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.00837041
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.00840255
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.00838256
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.00837062
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.00833315
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.00828851
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.00828313
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.008257
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.00824896
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.00820562
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.00818612
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.00817495
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.00817296
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.00817492
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.00817101
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 0.00807735
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 0.00806998
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 0.0080517
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 0.00804461
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[116]	valid_0's binary_logloss: 0.0080025
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[117]	valid_0's binary_logloss: 0.00796821
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[118]	valid_0's binary_logloss: 0.00794521
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[119]	valid_0's binary_logloss: 0.00793099
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[120]	valid_0's binary_logloss: 0.00794928
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[121]	valid_0's binary_logloss: 0.00792577
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[122]	valid_0's binary_logloss: 0.00789421
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[123]	valid_0's binary_logloss: 0.00792054
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[124]	valid_0's binary_logloss: 0.00791186
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[125]	valid_0's binary_logloss: 0.00790192
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[126]	valid_0's binary_logloss: 0.00788193
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[127]	valid_0's binary_logloss: 0.00787798
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[128]	valid_0's binary_logloss: 0.00788914
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[129]	valid_0's binary_logloss: 0.00784723
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[130]	valid_0's binary_logloss: 0.00785479
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[131]	valid_0's binary_logloss: 0.00782178
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[132]	valid_0's binary_logloss: 0.0078086
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[133]	valid_0's binary_logloss: 0.0077744
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[134]	valid_0's binary_logloss: 0.00776791
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[135]	valid_0's binary_logloss: 0.00775073
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[136]	valid_0's binary_logloss: 0.00774121
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[137]	valid_0's binary_logloss: 0.00774723
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[138]	valid_0's binary_logloss: 0.00774339
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[139]	valid_0's binary_logloss: 0.00775647
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[140]	valid_0's binary_logloss: 0.00776994
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[141]	valid_0's binary_logloss: 0.00778874
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[142]	valid_0's binary_logloss: 0.00784778
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[143]	valid_0's binary_logloss: 0.00788586
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[144]	valid_0's binary_logloss: 0.00789216
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[145]	valid_0's binary_logloss: 0.00798639
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[146]	valid_0's binary_logloss: 0.0079652
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[147]	valid_0's binary_logloss: 0.00796853
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[148]	valid_0's binary_logloss: 0.0079485
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[149]	valid_0's binary_logloss: 0.00794013
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[150]	valid_0's binary_logloss: 0.00793566
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[151]	valid_0's binary_logloss: 0.00793892
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[152]	valid_0's binary_logloss: 0.00791458
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[153]	valid_0's binary_logloss: 0.00787851
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[154]	valid_0's binary_logloss: 0.00786033
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[155]	valid_0's binary_logloss: 0.0078762
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[156]	valid_0's binary_logloss: 0.00788527
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[157]	valid_0's binary_logloss: 0.00783002
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[158]	valid_0's binary_logloss: 0.00778982
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[159]	valid_0's binary_logloss: 0.00775497
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[160]	valid_0's binary_logloss: 0.00772756
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[161]	valid_0's binary_logloss: 0.00773578
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[162]	valid_0's binary_logloss: 0.00775369
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[163]	valid_0's binary_logloss: 0.00774897
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[164]	valid_0's binary_logloss: 0.00772078
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[165]	valid_0's binary_logloss: 0.00770165
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[166]	valid_0's binary_logloss: 0.00766536
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[167]	valid_0's binary_logloss: 0.00765617
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[168]	valid_0's binary_logloss: 0.00764985
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[169]	valid_0's binary_logloss: 0.00764139
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[170]	valid_0's binary_logloss: 0.00763929
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[171]	valid_0's binary_logloss: 0.00766929
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[172]	valid_0's binary_logloss: 0.00766956
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[173]	valid_0's binary_logloss: 0.00768443
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[174]	valid_0's binary_logloss: 0.00766604
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[175]	valid_0's binary_logloss: 0.00769408
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[176]	valid_0's binary_logloss: 0.00769141
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[177]	valid_0's binary_logloss: 0.00767752
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[178]	valid_0's binary_logloss: 0.00769336
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[179]	valid_0's binary_logloss: 0.00767845
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[180]	valid_0's binary_logloss: 0.00765642
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[181]	valid_0's binary_logloss: 0.00763558
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[182]	valid_0's binary_logloss: 0.00765075
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

Trening klas:  37%|███▋      | 187/500 [24:11<27:49,  5.33s/klasa, klasa=class_187, F1_klasy=0.5833, F1_macro=0.7603, drzewa=207]




Trening klas:  38%|███▊      | 188/500 [24:11<32:33,  6.26s/klasa, klasa=class_187, F1_klasy=0.5833, F1_macro=0.7603, drzewa=207]

[237]	valid_0's binary_logloss: 0.00786876
[1]	valid_0's binary_logloss: 0.0275639
[2]	valid_0's binary_logloss: 0.0257949
[3]	valid_0's binary_logloss: 0.0242701
[4]	valid_0's binary_logloss: 0.0229509
[5]	valid_0's binary_logloss: 0.0217549
[6]	valid_0's binary_logloss: 0.020684
[7]	valid_0's binary_logloss: 0.0197094
[8]	valid_0's binary_logloss: 0.0188343
[9]	valid_0's binary_logloss: 0.0180219
[10]	valid_0's binary_logloss: 0.0172813
[11]	valid_0's binary_logloss: 0.0165897
[12]	valid_0's binary_logloss: 0.0159518
[13]	valid_0's binary_logloss: 0.015364
[14]	valid_0's binary_logloss: 0.0148231
[15]	valid_0's binary_logloss: 0.0143364
[16]	valid_0's binary_logloss: 0.013886
[17]	valid_0's binary_logloss: 0.0134717
[18]	valid_0's binary_logloss: 0.0130755
[19]	valid_0's binary_logloss: 0.0127089
[20]	valid_0's binary_logloss: 0.0123955
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.012078
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0117858
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.0115161
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0112663
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.0110414
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.0108318
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.0106452
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.0104718
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.0103153
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.0101687
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.0100341
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.00991619
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.00982135
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.00972767
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.00964535
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.00957076
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.00950829
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.00946165
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.00941668
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.00938161
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.00935744
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.00934326
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.00933056
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.0093241
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.00932365
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.00931983
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.00932125
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.00932793
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.00933243
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.00923883
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.00925815
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.00927754
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.00929027
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.0093178
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.00933484
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.00936605
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.0094109
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.0094477
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.00949747
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.00954888
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.0091393
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.00919165
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.0089825
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.00882075
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.0088687
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.00893415
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.0089961
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.00906736
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.00908322
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.00907498
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.00912591
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.00917281
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.00923052
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.00928835
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.00932601
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.00924375
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.00910165
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.00903538
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.00897908
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.00904126
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.00901991
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.00899372
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.0089964
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.0089874
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.00899653
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.00896627
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.00892589
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.00882688
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.00857095
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.00850973
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.00852568
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.00852474
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.0085567
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.00858622
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.00861253
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.00855027
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.00850215
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.00848691
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.00844314
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.00845423
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.00849039
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.00855611
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.00859224
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.00864523
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.00866635
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.00860834
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.00860898
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.00857042
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.00846292
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.00846418
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.00846206
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 0.00849407
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 0.00852942
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 0.00857632
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 0.0086109
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[116]	valid_0's binary_logloss: 0.00856347
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[117]	valid_0's binary_logloss: 0.00860534
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[118]	valid_0's binary_logloss: 0.00863627
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[119]	valid_0's binary_logloss: 0.00865327
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[120]	valid_0's binary_logloss: 0.00865492
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[121]	valid_0's binary_logloss: 0.00865615
[122]	valid_0's binary_logloss: 0.00859488
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[123]	valid_0's binary_logloss: 0.00860333
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[124]	valid_0's binary_logloss: 0.00856564
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[125]	valid_0's binary_logloss: 0.00857282
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[126]	valid_0's binary_logloss: 0.00859291
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[127]	valid_0's binary_logloss: 0.00860164
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

Trening klas:  38%|███▊      | 188/500 [24:15<32:33,  6.26s/klasa, klasa=class_188, F1_klasy=0.8718, F1_macro=0.7609, drzewa=99]




Trening klas:  38%|███▊      | 189/500 [24:15<29:34,  5.70s/klasa, klasa=class_188, F1_klasy=0.8718, F1_macro=0.7609, drzewa=99]

[128]	valid_0's binary_logloss: 0.00862804
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[129]	valid_0's binary_logloss: 0.00865273
[1]	valid_0's binary_logloss: 0.0385366
[2]	valid_0's binary_logloss: 0.037159
[3]	valid_0's binary_logloss: 0.0360177
[4]	valid_0's binary_logloss: 0.0350842
[5]	valid_0's binary_logloss: 0.0341604
[6]	valid_0's binary_logloss: 0.0335437
[7]	valid_0's binary_logloss: 0.0327945
[8]	valid_0's binary_logloss: 0.0322363
[9]	valid_0's binary_logloss: 0.0316461
[10]	valid_0's binary_logloss: 0.0311471
[11]	valid_0's binary_logloss: 0.0305857
[12]	valid_0's binary_logloss: 0.0300942
[13]	valid_0's binary_logloss: 0.0294925
[14]	valid_0's binary_logloss: 0.029094
[15]	valid_0's binary_logloss: 0.0285772
[16]	valid_0's binary_logloss: 0.0282626
[17]	valid_0's binary_logloss: 0.0280253
[18]	valid_0's binary_logloss: 0.0277291
[19]	valid_0's binary_logloss: 0.0274144
[20]	valid_0's binary_logloss: 0.0271632
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0266967
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0262716
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.0259671
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0257593
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.0255923
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.0252
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.0249484
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.0246906
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.0244325
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.02434
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.0240247
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.0240057
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.0237976
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.0236747
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.0234675
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.0233166
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.0232353
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.023252
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.0230219
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.0228589
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.0227076
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.0225844
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.0225378
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.0224481
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.022361
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.0222841
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.0222039
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.0221534
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.0221944
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.0221654
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.0220609
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.0220652
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.0220326
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.0218893
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.0219231
[56]	valid_0's binary_logloss: 0.0219359
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.0219915
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.0220558
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.0220346
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.0221119
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.0220771
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.0220425
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.0220617
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.0220247
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.0218278
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.0218688
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.02181
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.0218921
[69]	valid_0's binary_logloss: 0.0218753
[70]	valid_0's binary_logloss: 0.0219247
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.0218841
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.0219206
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.0219723
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.0219626
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.0220218
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.0220377
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.0220284
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.0219337
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.021882
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.0217672
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.0217092
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.0218166
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.021841
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.021844
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.0218956
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.0219039
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.0219384
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.0219884
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.0220289
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.0221545
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.0221562
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.0221134
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.022196
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.0222321
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.0222949
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.0222952
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.0223245
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.0223313
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.0223477
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.0223007
[101]	valid_0's binary_logloss: 0.0223549
[102]	valid_0's binary_logloss: 0.0223911
[103]	valid_0's binary_logloss: 0.0224905
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.0225351
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.0225579
[106]	valid_0's binary_logloss: 0.0226407
[107]	valid_0's binary_logloss: 0.0227305
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.0227902
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.0228794

Trening klas:  38%|███▊      | 189/500 [24:21<29:34,  5.70s/klasa, klasa=class_189, F1_klasy=0.6923, F1_macro=0.7606, drzewa=81]




Trening klas:  38%|███▊      | 190/500 [24:21<29:04,  5.63s/klasa, klasa=class_189, F1_klasy=0.6923, F1_macro=0.7606, drzewa=81]

[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.0229001
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.0228633
[1]	valid_0's binary_logloss: 0.0769487
[2]	valid_0's binary_logloss: 0.0755704
[3]	valid_0's binary_logloss: 0.0744558
[4]	valid_0's binary_logloss: 0.073594
[5]	valid_0's binary_logloss: 0.0726331
[6]	valid_0's binary_logloss: 0.0719386
[7]	valid_0's binary_logloss: 0.0709467
[8]	valid_0's binary_logloss: 0.0701678
[9]	valid_0's binary_logloss: 0.0694139
[10]	valid_0's binary_logloss: 0.068606
[11]	valid_0's binary_logloss: 0.0683264
[12]	valid_0's binary_logloss: 0.0678325
[13]	valid_0's binary_logloss: 0.0673459
[14]	valid_0's binary_logloss: 0.0670175
[15]	valid_0's binary_logloss: 0.0665276
[16]	valid_0's binary_logloss: 0.0660912
[17]	valid_0's binary_logloss: 0.0656964
[18]	valid_0's binary_logloss: 0.0654949
[19]	valid_0's binary_logloss: 0.0651062
[20]	valid_0's binary_logloss: 0.0648538
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0646054
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0644266
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.0643109
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0641839
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.0639838
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.0638032
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.0637537
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.0636062
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.0635671
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.0634626
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.0634727
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.063479
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.0635238
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.0634205
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.0634017
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.0631999
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.0629604
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.0630091
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.0629119
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.0630905
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.0629802
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.063011
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.0629999
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.063191
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.063324
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.0632206
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.0632078
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.0632902
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.0633162
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.0634256
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.0634915
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.0636273
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.0636946
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.0639309
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.0640633
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.0643121
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.0645223
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.0647051
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.064852
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.0651352
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.0652754
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.0652415
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.0653397
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.0653991
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.0654267
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.0654871
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.0657752
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.0659663
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.0659549

Trening klas:  38%|███▊      | 190/500 [24:25<29:04,  5.63s/klasa, klasa=class_190, F1_klasy=0.5951, F1_macro=0.7597, drzewa=39]




Trening klas:  38%|███▊      | 191/500 [24:25<26:17,  5.11s/klasa, klasa=class_190, F1_klasy=0.5951, F1_macro=0.7597, drzewa=39]

[1]	valid_0's binary_logloss: 0.028413
[2]	valid_0's binary_logloss: 0.0263997
[3]	valid_0's binary_logloss: 0.0246663
[4]	valid_0's binary_logloss: 0.0231038
[5]	valid_0's binary_logloss: 0.0216966
[6]	valid_0's binary_logloss: 0.0204091
[7]	valid_0's binary_logloss: 0.0192211
[8]	valid_0's binary_logloss: 0.0181273
[9]	valid_0's binary_logloss: 0.0171246
[10]	valid_0's binary_logloss: 0.0161933
[11]	valid_0's binary_logloss: 0.0153357
[12]	valid_0's binary_logloss: 0.0145327
[13]	valid_0's binary_logloss: 0.0137715
[14]	valid_0's binary_logloss: 0.0130592
[15]	valid_0's binary_logloss: 0.0123811
[16]	valid_0's binary_logloss: 0.0117553
[17]	valid_0's binary_logloss: 0.011168
[18]	valid_0's binary_logloss: 0.0105922
[19]	valid_0's binary_logloss: 0.0100534
[20]	valid_0's binary_logloss: 0.00954535
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.00906877
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.00861953
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.00819411
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.00779281
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.00740656
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.00705146
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.00672027
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.00639839
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.00610914
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.00582338
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.00554243
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.00526788
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.00501572
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.00477729
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.00454988
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.00434327
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.00415317
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.00397685
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.00379156
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.00363391
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.00345914
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.00329635
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.00313911
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.00300084
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.00287053
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.00274047
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.00262017
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.00250316
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.00239665
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.00229966
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.00221073
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.00212613
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.00204326
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.00196829
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.0018885
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.00180944
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.00172562
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.00165449
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.00158862
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.00152434
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.00146087
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.00139962
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.00134483
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.00129123
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.00123761
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.00118591
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.00113865
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.00109451
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.00105067
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.00100928
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.000962128
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.000916897
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.000874309
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.000833295
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.000794884
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.000762902
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.0007336
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.000704879
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.000677863
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.000652769
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.000624397
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.00059618
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.000569024
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.000543146
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.000520036
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.000502332
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.000481987
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.000465084
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.000449288
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.000435864
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.000418191
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.000401097
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.000384884
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.000367512
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.000350958
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.000337936
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.000322999
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.000308813
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.000295307
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.000282189
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.000274685
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.000266755
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.000259472
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.000252207
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.000246164
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.000238371
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.000230976
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.000227926
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.000219917
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.000218997
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.000215183
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 0.000207638
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 0.00020023
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 0.000193644
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 0.000190823
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[116]	valid_0's binary_logloss: 0.000184457
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[117]	valid_0's binary_logloss: 0.000182369
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[118]	valid_0's binary_logloss: 0.000176264
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[119]	valid_0's binary_logloss: 0.000170699
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[120]	valid_0's binary_logloss: 0.000164267
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[121]	valid_0's binary_logloss: 0.000163819
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[122]	valid_0's binary_logloss: 0.000164483
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[123]	valid_0's binary_logloss: 0.000163887
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[124]	valid_0's binary_logloss: 0.000164737
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[125]	valid_0's binary_logloss: 0.00016554
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[126]	valid_0's binary_logloss: 0.000165768
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[127]	valid_0's binary_logloss: 0.000159946
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[128]	valid_0's binary_logloss: 0.000159819
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[129]	valid_0's binary_logloss: 0.000159576
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[130]	valid_0's binary_logloss: 0.000160615
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[131]	valid_0's binary_logloss: 0.000156489
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[132]	valid_0's binary_logloss: 0.000152896
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[133]	valid_0's binary_logloss: 0.000149451
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[134]	valid_0's binary_logloss: 0.000145325
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[135]	valid_0's binary_logloss: 0.000142665
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[136]	valid_0's binary_logloss: 0.000143155
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[137]	valid_0's binary_logloss: 0.000141984
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[138]	valid_0's binary_logloss: 0.000139043
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[139]	valid_0's binary_logloss: 0.000139707
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[140]	valid_0's binary_logloss: 0.000136929
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[141]	valid_0's binary_logloss: 0.000139334
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[142]	valid_0's binary_logloss: 0.000138348
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[143]	valid_0's binary_logloss: 0.000140688
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[144]	valid_0's binary_logloss: 0.000139714
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[145]	valid_0's binary_logloss: 0.000141555
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[146]	valid_0's binary_logloss: 0.00013821
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[147]	valid_0's binary_logloss: 0.00013465
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[148]	valid_0's binary_logloss: 0.000131174
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[149]	valid_0's binary_logloss: 0.000127838
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[150]	valid_0's binary_logloss: 0.000125183
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[151]	valid_0's binary_logloss: 0.00012721
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[152]	valid_0's binary_logloss: 0.000124263
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[153]	valid_0's binary_logloss: 0.000122732
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[154]	valid_0's binary_logloss: 0.000124935
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[155]	valid_0's binary_logloss: 0.000127275
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[156]	valid_0's binary_logloss: 0.000126881
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[157]	valid_0's binary_logloss: 0.00012468
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[158]	valid_0's binary_logloss: 0.000126277
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[159]	valid_0's binary_logloss: 0.000123849
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[160]	valid_0's binary_logloss: 0.000121744
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[161]	valid_0's binary_logloss: 0.00011938
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[162]	valid_0's binary_logloss: 0.000114915
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[163]	valid_0's binary_logloss: 0.00011258
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[164]	valid_0's binary_logloss: 0.000110363
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[165]	valid_0's binary_logloss: 0.000108237
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[166]	valid_0's binary_logloss: 0.000107605
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[167]	valid_0's binary_logloss: 0.000107854
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[168]	valid_0's binary_logloss: 0.000107082
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[169]	valid_0's binary_logloss: 0.000106839
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[170]	valid_0's binary_logloss: 0.00010472
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[171]	valid_0's binary_logloss: 0.000101654
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[172]	valid_0's binary_logloss: 0.000101545
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[173]	valid_0's binary_logloss: 0.000101479
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[174]	valid_0's binary_logloss: 0.000101423
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[175]	valid_0's binary_logloss: 0.000101415
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[176]	valid_0's binary_logloss: 0.000100818
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[177]	valid_0's binary_logloss: 0.000100535
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[178]	valid_0's binary_logloss: 0.000102997
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[179]	valid_0's binary_logloss: 0.000105097
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[180]	valid_0's binary_logloss: 0.000104517
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[181]	valid_0's binary_logloss: 0.000104148
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[182]	valid_0's binary_logloss: 0.000104619

Trening klas:  38%|███▊      | 191/500 [24:31<26:17,  5.11s/klasa, klasa=class_191, F1_klasy=1.0000, F1_macro=0.7609, drzewa=266]

[288]	valid_0's binary_logloss: 7.14565e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[289]	valid_0's binary_logloss: 7.09257e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[290]	valid_0's binary_logloss: 7.0337e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[291]	valid_0's binary_logloss: 7.03258e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[292]	valid_0's binary_logloss: 7.03067e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[293]	valid_0's binary_logloss: 7.03044e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[294]	valid_0's binary_logloss: 7.02937e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[295]	valid_0's binary_logloss: 7.0556e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[296]	valid_0's binary_logloss: 7.05418e-05

Trening klas:  38%|███▊      | 192/500 [24:31<28:23,  5.53s/klasa, klasa=class_191, F1_klasy=1.0000, F1_macro=0.7609, drzewa=266]

[1]	valid_0's binary_logloss: 0.108613
[2]	valid_0's binary_logloss: 0.111675
[3]	valid_0's binary_logloss: 0.114024
[4]	valid_0's binary_logloss: 0.116045
[5]	valid_0's binary_logloss: 0.117374
[6]	valid_0's binary_logloss: 0.121723
[7]	valid_0's binary_logloss: 0.123512
[8]	valid_0's binary_logloss: 0.125205
[9]	valid_0's binary_logloss: 0.128206
[10]	valid_0's binary_logloss: 0.130207
[11]	valid_0's binary_logloss: 0.131409
[12]	valid_0's binary_logloss: 0.132602
[13]	valid_0's binary_logloss: 0.133975
[14]	valid_0's binary_logloss: 0.135103
[15]	valid_0's binary_logloss: 0.134673
[16]	valid_0's binary_logloss: 0.135439
[17]	valid_0's binary_logloss: 0.136498
[18]	valid_0's binary_logloss: 0.13644
[19]	valid_0's binary_logloss: 0.136312
[20]	valid_0's binary_logloss: 0.137039
[21]	valid_0's binary_logloss: 0.137296
[22]	valid_0's binary_logloss: 0.137409
[23]	valid_0's binary_logloss: 0.136974
[24]	valid_0's binary_logloss: 0.137089
[25]	valid_0's binary_logloss: 0.13695
[26]	valid_0's binary_logloss: 0.137005
[27]	valid_0's binary_logloss: 0.138244
[28]	valid_0's binary_logloss: 0.137839
[29]	valid_0's binary_logloss: 0.138297
[30]	valid_0's binary_logloss: 0.137298

Trening klas:  38%|███▊      | 192/500 [24:36<28:23,  5.53s/klasa, klasa=class_192, F1_klasy=0.0000, F1_macro=0.7570, drzewa=1]




Trening klas:  39%|███▊      | 193/500 [24:36<26:28,  5.17s/klasa, klasa=class_192, F1_klasy=0.0000, F1_macro=0.7570, drzewa=1]

[31]	valid_0's binary_logloss: 0.13678
[1]	valid_0's binary_logloss: 0.0492395
[2]	valid_0's binary_logloss: 0.0466782
[3]	valid_0's binary_logloss: 0.0445102
[4]	valid_0's binary_logloss: 0.0424173
[5]	valid_0's binary_logloss: 0.0406351
[6]	valid_0's binary_logloss: 0.0388028
[7]	valid_0's binary_logloss: 0.0371419
[8]	valid_0's binary_logloss: 0.0356976
[9]	valid_0's binary_logloss: 0.0342832
[10]	valid_0's binary_logloss: 0.0329933
[11]	valid_0's binary_logloss: 0.03193
[12]	valid_0's binary_logloss: 0.0309107
[13]	valid_0's binary_logloss: 0.0298274
[14]	valid_0's binary_logloss: 0.0289494
[15]	valid_0's binary_logloss: 0.0281231
[16]	valid_0's binary_logloss: 0.0272607
[17]	valid_0's binary_logloss: 0.0264864
[18]	valid_0's binary_logloss: 0.0258447
[19]	valid_0's binary_logloss: 0.0252526
[20]	valid_0's binary_logloss: 0.0246341
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0240145
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0234952
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.0230842
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0226507
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.0223158
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.0218917
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.0214568
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.0210728
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.0207364
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.0204541
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.02009
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.0197
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.0193637
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.0190791
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.0188221
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.0186353
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.0185028
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.0183419
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.0181758
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.0180577
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.0180042
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.0178975
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.0178346
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.0178355
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.0177343
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.0176468
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.0175756
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.0175821
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.0175068
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.0174559
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.0173935
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.0172706
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.0173077
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.0173413
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.0173616
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.0173809
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.0172635
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.0172301
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.0172062
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.0172359
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.017291
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.0173692
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.0173927
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.0173958
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.0175961
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.0176012
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.0176119
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.0176806
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.0177114
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.0178858
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.0179565
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.0179533
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.0179819
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.0180116
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.0180602
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.0181653
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.0183069
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.0184295
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.018533
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.0186922
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.0188414
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.0189563
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.0190527
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.0192337
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.0192977
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.0194239
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.0194317

Trening klas:  39%|███▊      | 193/500 [24:40<26:28,  5.17s/klasa, klasa=class_193, F1_klasy=0.8955, F1_macro=0.7577, drzewa=59]




Trening klas:  39%|███▉      | 194/500 [24:40<25:52,  5.07s/klasa, klasa=class_193, F1_klasy=0.8955, F1_macro=0.7577, drzewa=59]

[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.0193869
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.0193726
[1]	valid_0's binary_logloss: 0.0575161
[2]	valid_0's binary_logloss: 0.0566334
[3]	valid_0's binary_logloss: 0.0553131
[4]	valid_0's binary_logloss: 0.0542555
[5]	valid_0's binary_logloss: 0.0532386
[6]	valid_0's binary_logloss: 0.0522645
[7]	valid_0's binary_logloss: 0.0513329
[8]	valid_0's binary_logloss: 0.0502448
[9]	valid_0's binary_logloss: 0.0494007
[10]	valid_0's binary_logloss: 0.0487295
[11]	valid_0's binary_logloss: 0.0497618
[12]	valid_0's binary_logloss: 0.0489529
[13]	valid_0's binary_logloss: 0.0486976
[14]	valid_0's binary_logloss: 0.0485261
[15]	valid_0's binary_logloss: 0.0480159
[16]	valid_0's binary_logloss: 0.0476484
[17]	valid_0's binary_logloss: 0.0470573
[18]	valid_0's binary_logloss: 0.0467297
[19]	valid_0's binary_logloss: 0.0464433
[20]	valid_0's binary_logloss: 0.0461595
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.045822
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0454622
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.0453404
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0450441
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.0446404
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.0443643
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.0442847
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.044231
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.0441042
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.043944
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.0437418
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.0435474
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.0435467
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.0435231
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.0432803
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.0431288
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.0429909
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.0427684
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.0424014
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.0420991
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.0419383
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.0416135
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.0415001
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.0414095
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.0413299
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.0412055
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.0411304
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.041126
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.0412783
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.0413125
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.0411898
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.041172
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.0412321
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.0413894
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.0414632
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.0414507
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.0414635
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.041395
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.0415006
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.0414415
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.0415295
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.0417418
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.0418792
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.0420358
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.0422191
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.0422102
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.0424303
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.0422667
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.0424429
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.0425596
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.042774
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.0428933
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.0429937
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.0431284
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.0432169
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.0433179
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.0432918
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

Trening klas:  39%|███▉      | 194/500 [24:45<25:52,  5.07s/klasa, klasa=class_194, F1_klasy=0.7682, F1_macro=0.7578, drzewa=48]




Trening klas:  39%|███▉      | 195/500 [24:45<24:50,  4.89s/klasa, klasa=class_194, F1_klasy=0.7682, F1_macro=0.7578, drzewa=48]

[78]	valid_0's binary_logloss: 0.0432659
[1]	valid_0's binary_logloss: 0.0910894
[2]	valid_0's binary_logloss: 0.0890917
[3]	valid_0's binary_logloss: 0.0876549
[4]	valid_0's binary_logloss: 0.0860292
[5]	valid_0's binary_logloss: 0.0850528
[6]	valid_0's binary_logloss: 0.0838905
[7]	valid_0's binary_logloss: 0.0827175
[8]	valid_0's binary_logloss: 0.0816076
[9]	valid_0's binary_logloss: 0.0807145
[10]	valid_0's binary_logloss: 0.0799733
[11]	valid_0's binary_logloss: 0.0792643
[12]	valid_0's binary_logloss: 0.0787057
[13]	valid_0's binary_logloss: 0.0779302
[14]	valid_0's binary_logloss: 0.0772672
[15]	valid_0's binary_logloss: 0.0762298
[16]	valid_0's binary_logloss: 0.0757723
[17]	valid_0's binary_logloss: 0.075243
[18]	valid_0's binary_logloss: 0.0746149
[19]	valid_0's binary_logloss: 0.0739756
[20]	valid_0's binary_logloss: 0.0734935
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0729319
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0722779
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.0718698
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0712416
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.070871
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.0702114
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.0697054
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.0693341
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.0690134
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.0688885
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.0685341
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.0680451
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.0677474
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.0674586
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.0670779
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.0670782
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.0669576
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.0667608
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.0665593
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.0663907
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.0661937
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.0660973
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.0657451
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.065732
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.0658459
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.0658251
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.0657825
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.0655283
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.0651581
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.0647297
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.0645805
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.0648411
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.0649205
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.0650422
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.0651121
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.0650303
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.0648272
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.064779
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.0647429
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.0647896
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.06489
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.0648855
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.0651344
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.0652742
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.065639
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.0653931
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.0652871
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.065133
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.0650696
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.0651736
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.0651267
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.0651994
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.0651738
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.0652219
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.0653703
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.065698
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

Trening klas:  39%|███▉      | 195/500 [24:50<24:50,  4.89s/klasa, klasa=class_195, F1_klasy=0.5872, F1_macro=0.7569, drzewa=51]




Trening klas:  39%|███▉      | 196/500 [24:50<24:23,  4.82s/klasa, klasa=class_195, F1_klasy=0.5872, F1_macro=0.7569, drzewa=51]

[77]	valid_0's binary_logloss: 0.0658847
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.0658295
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.065754
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.0659973
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.0657875
[1]	valid_0's binary_logloss: 0.049447
[2]	valid_0's binary_logloss: 0.0480096
[3]	valid_0's binary_logloss: 0.0466572
[4]	valid_0's binary_logloss: 0.0457077
[5]	valid_0's binary_logloss: 0.0446923
[6]	valid_0's binary_logloss: 0.0436413
[7]	valid_0's binary_logloss: 0.0425346
[8]	valid_0's binary_logloss: 0.0415769
[9]	valid_0's binary_logloss: 0.0407365
[10]	valid_0's binary_logloss: 0.0400616
[11]	valid_0's binary_logloss: 0.0395268
[12]	valid_0's binary_logloss: 0.0390403
[13]	valid_0's binary_logloss: 0.0386142
[14]	valid_0's binary_logloss: 0.0381616
[15]	valid_0's binary_logloss: 0.037804
[16]	valid_0's binary_logloss: 0.0372926
[17]	valid_0's binary_logloss: 0.0368726
[18]	valid_0's binary_logloss: 0.0366113
[19]	valid_0's binary_logloss: 0.0362606
[20]	valid_0's binary_logloss: 0.0357876
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.035502
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0352728
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.0349481
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0348005
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.034527
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.0344911
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.0343759
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.034052
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.0338481
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.0337484
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.0334665
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.0332868
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.0328728
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.0325809
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.0322872
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.0321311
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.0320245
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.0318556
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.0317333
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.0316546
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.0314639
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.0312163
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.030917
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.0306945
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.0305678
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.0303285
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.0301555
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.0300909
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.0300489
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.0298935
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.0296927
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.0296889
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.0295961
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.0296021
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.0296637
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.029617
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.0296879
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.0297037
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.0297171
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.0296319
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.0294113
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.0294245
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.0293737
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.0292232
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.0293773
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.0292709
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.0292318
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.0292312
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.0293148
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.0293437
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.0292361
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.0293289
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.0294043
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.0295024
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.0294498
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.0294302
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.0294056
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.0293083
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.0293747
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.0294234
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.0295984
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.0296153
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.0295571
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.0296684
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.0297132
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.029807
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.0298031
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.029842
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.0298496
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.0298324
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.0297936
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.0298181
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.0297443
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

Trening klas:  39%|███▉      | 196/500 [24:54<24:23,  4.82s/klasa, klasa=class_196, F1_klasy=0.6225, F1_macro=0.7562, drzewa=64]




Trening klas:  39%|███▉      | 197/500 [24:54<23:39,  4.69s/klasa, klasa=class_196, F1_klasy=0.6225, F1_macro=0.7562, drzewa=64]

[94]	valid_0's binary_logloss: 0.0297823
[1]	valid_0's binary_logloss: 0.0238442
[2]	valid_0's binary_logloss: 0.022901
[3]	valid_0's binary_logloss: 0.0219217
[4]	valid_0's binary_logloss: 0.0211184
[5]	valid_0's binary_logloss: 0.0203559
[6]	valid_0's binary_logloss: 0.0196503
[7]	valid_0's binary_logloss: 0.0190149
[8]	valid_0's binary_logloss: 0.018431
[9]	valid_0's binary_logloss: 0.0178575
[10]	valid_0's binary_logloss: 0.0173389
[11]	valid_0's binary_logloss: 0.0169543
[12]	valid_0's binary_logloss: 0.0166139
[13]	valid_0's binary_logloss: 0.0162064
[14]	valid_0's binary_logloss: 0.0158205
[15]	valid_0's binary_logloss: 0.0155167
[16]	valid_0's binary_logloss: 0.0152635
[17]	valid_0's binary_logloss: 0.0149873
[18]	valid_0's binary_logloss: 0.0147377
[19]	valid_0's binary_logloss: 0.0145324
[20]	valid_0's binary_logloss: 0.0142468
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0140611
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0139206
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.0137362
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0136035
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.0134185
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.0132814
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.0131642
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.0129068
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.0127346
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.01266
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.0126068
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.0125534
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.0124438
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.0123919
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.0123127
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.0123229
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.0123025
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.0122714
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.012214
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.0121675
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.0121382
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.0120791
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.0120514
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.011992
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.0119467
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.0119092
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.0118392
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.0117308
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.011601
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.0115726
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.0114847
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.0115513
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.0116116
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.0115397
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.0115283
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.0115046
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.011529
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.0115905
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.0115538
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.0115763
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.0114314
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.0112462
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.0111237
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.0110309
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.0109061
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.0109342
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.0107741
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.0107756
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.0107792
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.010817
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.0108296
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.0107038
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.0105939
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.0105606
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.0104824
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.0105156
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.0105219
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.0104917
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.0105242
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.0104109
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.010408
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.0104302
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.0102919
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.0102025
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.0102343
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.0102441
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.0102432
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.0102061
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.01024
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.0103073
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.0103092
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.0102763
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.010319
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.0103082
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.0103342
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.0104033
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.010467
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.0105311
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.0105949
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.0107079
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.0107591
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.0107566
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.0107695
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.0107823
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.010814
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.0107259
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.0107375
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.0106924
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.0107158
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.0107973
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.0107338
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

Trening klas:  39%|███▉      | 197/500 [24:58<23:39,  4.69s/klasa, klasa=class_197, F1_klasy=0.6154, F1_macro=0.7555, drzewa=84]




Trening klas:  40%|███▉      | 198/500 [24:58<23:08,  4.60s/klasa, klasa=class_197, F1_klasy=0.6154, F1_macro=0.7555, drzewa=84]

[112]	valid_0's binary_logloss: 0.010642
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 0.0106044
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 0.0106313
[1]	valid_0's binary_logloss: 0.0263855
[2]	valid_0's binary_logloss: 0.0249617
[3]	valid_0's binary_logloss: 0.0238427
[4]	valid_0's binary_logloss: 0.0228608
[5]	valid_0's binary_logloss: 0.0218457
[6]	valid_0's binary_logloss: 0.0210103
[7]	valid_0's binary_logloss: 0.0201623
[8]	valid_0's binary_logloss: 0.0193854
[9]	valid_0's binary_logloss: 0.0186809
[10]	valid_0's binary_logloss: 0.0180684
[11]	valid_0's binary_logloss: 0.0174809
[12]	valid_0's binary_logloss: 0.0169158
[13]	valid_0's binary_logloss: 0.0164162
[14]	valid_0's binary_logloss: 0.0159672
[15]	valid_0's binary_logloss: 0.0155417
[16]	valid_0's binary_logloss: 0.0151441
[17]	valid_0's binary_logloss: 0.014793
[18]	valid_0's binary_logloss: 0.0144665
[19]	valid_0's binary_logloss: 0.0141577
[20]	valid_0's binary_logloss: 0.0138744
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0135847
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0133389
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.013124
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0129054
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.0127257
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.0125085
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.0123477
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.012208
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.0120542
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.0119221
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.0117991
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.0116181
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.0115217
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.0114557
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.011371
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.0111443
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.011073
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.010868
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.0108114
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.0106763
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.0106672
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.0106676
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.0105946
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.0105967
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.0106149
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.0106023
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.0106119
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.0105945
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.0106001
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.0105983
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.0105859
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.0105732
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.0105696
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.0105477
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.0105609
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.0105224
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.0105044
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.0105104
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.0105111
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.0105347
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.0105679
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.0106236
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.0106425
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.0106822
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.0107324
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.0107836
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.0108354
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.0108848
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.0109101
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.0109718
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.0110367
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.0110676
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.0111401
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.011166
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.0112254
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.0112952
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.0113687
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.011415
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.0114763
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.011535
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

Trening klas:  40%|███▉      | 198/500 [25:02<23:08,  4.60s/klasa, klasa=class_198, F1_klasy=0.7921, F1_macro=0.7557, drzewa=57]




Trening klas:  40%|███▉      | 199/500 [25:02<21:26,  4.28s/klasa, klasa=class_198, F1_klasy=0.7921, F1_macro=0.7557, drzewa=57]

[81]	valid_0's binary_logloss: 0.0115706
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.0116225
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.0116728
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.0116735
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.0117347
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.0118623
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.0119801
[1]	valid_0's binary_logloss: 0.0695444
[2]	valid_0's binary_logloss: 0.0675467
[3]	valid_0's binary_logloss: 0.0662018
[4]	valid_0's binary_logloss: 0.0643846
[5]	valid_0's binary_logloss: 0.0630417
[6]	valid_0's binary_logloss: 0.0618302
[7]	valid_0's binary_logloss: 0.0608937
[8]	valid_0's binary_logloss: 0.06014
[9]	valid_0's binary_logloss: 0.0594358
[10]	valid_0's binary_logloss: 0.0586993
[11]	valid_0's binary_logloss: 0.059779
[12]	valid_0's binary_logloss: 0.0588459
[13]	valid_0's binary_logloss: 0.0579783
[14]	valid_0's binary_logloss: 0.057201
[15]	valid_0's binary_logloss: 0.0563418
[16]	valid_0's binary_logloss: 0.0565144
[17]	valid_0's binary_logloss: 0.0560572
[18]	valid_0's binary_logloss: 0.0553178
[19]	valid_0's binary_logloss: 0.0545434
[20]	valid_0's binary_logloss: 0.0540294
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0537527
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.05303
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.0521972
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.051629
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.0512564
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.0509418
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.0504645
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.0500328
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.049679
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.04938
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.0491876
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.0490465
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.0486979
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.0484283
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.0480806
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.0478611
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.0476269
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.0474661
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.0471441
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.0468069
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.0467293
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.0465357
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.0464851
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.0464709
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.0463533
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.0461885
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.0460862
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.0460498
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.0460128
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.045917
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.0457273
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.0456609
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.045587
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.0455677
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.045375
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.0452951
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.0452164
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.0451116
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.0451136
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.0449656
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.0448769
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.0447634
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.0446086
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.0444982
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.0443689
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.0443107
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.0443495
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.0444527
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.0443092
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.0442655
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.0443443
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.044334
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.0442691
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.0442229
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.0441623
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.0442548
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.0442243
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.0442265
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.044388
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.0441876
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.0440127
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.044053
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.0439249
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.0440251
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.0440025
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.0439491
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.0439505
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.0439044
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.0440889
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.0442223
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.0443736
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.0444731
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.0445266
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.0446114
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.044571
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.0445638
[97]	valid_0's binary_logloss: 0.0446838
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.0446485
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.0447026
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.0447968
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.0447563
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.0448833
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.0450092
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.0449424
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.045072
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.04508
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.0451866
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.0453136
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.0453255
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.0454135
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.0453941
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 0.0453867
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 0.0453182
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 0.0453374
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 0.045323
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[116]	valid_0's binary_logloss: 0.0453879
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

Trening klas:  40%|███▉      | 199/500 [25:08<21:26,  4.28s/klasa, klasa=class_199, F1_klasy=0.7730, F1_macro=0.7558, drzewa=88]




Trening klas:  40%|████      | 200/500 [25:08<23:58,  4.79s/klasa, klasa=class_199, F1_klasy=0.7730, F1_macro=0.7558, drzewa=88]

[117]	valid_0's binary_logloss: 0.045525
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[118]	valid_0's binary_logloss: 0.0455842
[1]	valid_0's binary_logloss: 0.0696736
[2]	valid_0's binary_logloss: 0.0677781
[3]	valid_0's binary_logloss: 0.0664347
[4]	valid_0's binary_logloss: 0.065014
[5]	valid_0's binary_logloss: 0.063739
[6]	valid_0's binary_logloss: 0.0626299
[7]	valid_0's binary_logloss: 0.0616644
[8]	valid_0's binary_logloss: 0.0612145
[9]	valid_0's binary_logloss: 0.0605165
[10]	valid_0's binary_logloss: 0.0597874
[11]	valid_0's binary_logloss: 0.0608858
[12]	valid_0's binary_logloss: 0.0598844
[13]	valid_0's binary_logloss: 0.0589961
[14]	valid_0's binary_logloss: 0.0581851
[15]	valid_0's binary_logloss: 0.0572078
[16]	valid_0's binary_logloss: 0.0573703
[17]	valid_0's binary_logloss: 0.0568094
[18]	valid_0's binary_logloss: 0.0560951
[19]	valid_0's binary_logloss: 0.0554508
[20]	valid_0's binary_logloss: 0.0547881
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0544455
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0537371
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.0528794
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.052356
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.0519914
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.0516
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.051412
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.0509858
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.0505375
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.0502736
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.0499338
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.049719
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.0495763
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.0492909
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.048986
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.0488144
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.0486097
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.0484092
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.0482817
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.0480689
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.0477786
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.0476325
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.0474205
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.047346
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.0472734
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.0471341
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.046989
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.0470183
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.0470054
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.046864
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.0466553
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.0466787
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.0466188
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.0466206
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.0464198
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.0463277
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.0461771
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.0460839
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.0460212
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.0459791
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.0459376
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.0458698
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.0458507
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.0458647
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.0460251
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.0458813
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.0459465
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.0459372
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.0458739
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.0460219
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.0461441
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.0462342
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.0462105
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.0461885
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.0460964
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.0460437
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.04605
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.0461023
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.0462178
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.0462397
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.0462813
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.0464404
[83]	valid_0's binary_logloss: 0.046594
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.0465775
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.0464837
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.0464576
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.0463498
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.0463017
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.0464225
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.0463923
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.0465079
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

Trening klas:  40%|████      | 200/500 [25:13<23:58,  4.79s/klasa, klasa=class_200, F1_klasy=0.7769, F1_macro=0.7559, drzewa=63]




Trening klas:  40%|████      | 201/500 [25:13<24:28,  4.91s/klasa, klasa=class_200, F1_klasy=0.7769, F1_macro=0.7559, drzewa=63]

[92]	valid_0's binary_logloss: 0.0466446
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.0467206
[1]	valid_0's binary_logloss: 0.0326875
[2]	valid_0's binary_logloss: 0.0313817
[3]	valid_0's binary_logloss: 0.030264
[4]	valid_0's binary_logloss: 0.0291456
[5]	valid_0's binary_logloss: 0.0284062
[6]	valid_0's binary_logloss: 0.0275499
[7]	valid_0's binary_logloss: 0.0266834
[8]	valid_0's binary_logloss: 0.025724
[9]	valid_0's binary_logloss: 0.0248757
[10]	valid_0's binary_logloss: 0.0242202
[11]	valid_0's binary_logloss: 0.0236025
[12]	valid_0's binary_logloss: 0.0230173
[13]	valid_0's binary_logloss: 0.0226554
[14]	valid_0's binary_logloss: 0.0220855
[15]	valid_0's binary_logloss: 0.0216199
[16]	valid_0's binary_logloss: 0.0211833
[17]	valid_0's binary_logloss: 0.0209687
[18]	valid_0's binary_logloss: 0.0205743
[19]	valid_0's binary_logloss: 0.020202
[20]	valid_0's binary_logloss: 0.0199116
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0196107
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0193815
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.0191318
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0189101
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.0187703
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.0184845
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.0182694
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.018013
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.0177576
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.0173767
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.0172348
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.0170348
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.0169482
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.0167724
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.0166457
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.0165491
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.0164844
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.0164399
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.0163254
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.0162171
[41]	valid_0's binary_logloss: 0.0161516
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.016084
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.0159643
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.0159407
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.0158207
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.0157737
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.015703
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.0155421
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.0153859
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.0152536
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.0151729
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.0151084
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.014964
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.0148097
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.0147481
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.0147238
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.0147686
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.0146473
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.0146819
[60]	valid_0's binary_logloss: 0.0144952
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.0142092
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.0140525
[63]	valid_0's binary_logloss: 0.0138
[64]	valid_0's binary_logloss: 0.0136554
[65]	valid_0's binary_logloss: 0.013573
[66]	valid_0's binary_logloss: 0.0134435
[67]	valid_0's binary_logloss: 0.0133548
[68]	valid_0's binary_logloss: 0.0132101
[69]	valid_0's binary_logloss: 0.0130561
[70]	valid_0's binary_logloss: 0.0129026
[71]	valid_0's binary_logloss: 0.0129026
[72]	valid_0's binary_logloss: 0.0127817
[73]	valid_0's binary_logloss: 0.0127019
[74]	valid_0's binary_logloss: 0.0126037
[75]	valid_0's binary_logloss: 0.0125643
[76]	valid_0's binary_logloss: 0.0124908
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.0124426
[78]	valid_0's binary_logloss: 0.0123646
[79]	valid_0's binary_logloss: 0.0121671
[80]	valid_0's binary_logloss: 0.0121174
[81]	valid_0's binary_logloss: 0.0121089
[82]	valid_0's binary_logloss: 0.0120557
[83]	valid_0's binary_logloss: 0.011993
[84]	valid_0's binary_logloss: 0.0119593
[85]	valid_0's binary_logloss: 0.01197
[86]	valid_0's binary_logloss: 0.0119055
[87]	valid_0's binary_logloss: 0.0118384
[88]	valid_0's binary_logloss: 0.0118
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.0117355
[90]	valid_0's binary_logloss: 0.0117284
[91]	valid_0's binary_logloss: 0.0116708
[92]	valid_0's binary_logloss: 0.0115962
[93]	valid_0's binary_logloss: 0.011507
[94]	valid_0's binary_logloss: 0.0115166
[95]	valid_0's binary_logloss: 0.0114665
[96]	valid_0's binary_logloss: 0.0113627
[97]	valid_0's binary_logloss: 0.0113928
[98]	valid_0's binary_logloss: 0.0113492
[99]	valid_0's binary_logloss: 0.011326
[100]	valid_0's binary_logloss: 0.0112678
[101]	valid_0's binary_logloss: 0.0112712
[102]	valid_0's binary_logloss: 0.0112663
[103]	valid_0's binary_logloss: 0.0112274
[104]	valid_0's binary_logloss: 0.0112113
[105]	valid_0's binary_logloss: 0.0112442
[106]	valid_0's binary_logloss: 0.0111729
[107]	valid_0's binary_logloss: 0.0111189
[108]	valid_0's binary_logloss: 0.0110497
[109]	valid_0's binary_logloss: 0.0110334
[110]	valid_0's binary_logloss: 0.0109903
[111]	valid_0's binary_logloss: 0.0109566
[112]	valid_0's binary_logloss: 0.0109292
[113]	valid_0's binary_logloss: 0.0109005
[114]	valid_0's binary_logloss: 0.0108588
[115]	valid_0's binary_logloss: 0.0108653
[116]	valid_0's binary_logloss: 0.0108871
[117]	valid_0's binary_logloss: 0.0108777
[118]	valid_0's binary_logloss: 0.0108219
[119]	valid_0's binary_logloss: 0.0107961
[120]	valid_0's binary_logloss: 0.0108317
[121]	valid_0's binary_logloss: 0.0107692
[122]	valid_0's binary_logloss: 0.0107765
[123]	valid_0's binary_logloss: 0.0107643
[124]	valid_0's binary_logloss: 0.0106829
[125]	valid_0's binary_logloss: 0.0106911
[126]	valid_0's binary_logloss: 0.0105903
[127]	valid_0's binary_logloss: 0.010589
[128]	valid_0's binary_logloss: 0.0105914
[129]	valid_0's binary_logloss: 0.010575
[130]	valid_0's binary_logloss: 0.010574
[131]	valid_0's binary_logloss: 0.0105589
[132]	valid_0's binary_logloss: 0.0105461
[133]	valid_0's binary_logloss: 0.0105302
[134]	valid_0's binary_logloss: 0.0105838
[135]	valid_0's binary_logloss: 0.0105549
[136]	valid_0's binary_logloss: 0.0105339
[137]	valid_0's binary_logloss: 0.0104881
[138]	valid_0's binary_logloss: 0.0104405
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[139]	valid_0's binary_logloss: 0.0104421
[140]	valid_0's binary_logloss: 0.0104195
[141]	valid_0's binary_logloss: 0.0104154
[142]	valid_0's binary_logloss: 0.0103338
[143]	valid_0's binary_logloss: 0.0102981
[144]	valid_0's binary_logloss: 0.0102305
[145]	valid_0's binary_logloss: 0.0102627
[146]	valid_0's binary_logloss: 0.0102274
[147]	valid_0's binary_logloss: 0.0102376
[148]	valid_0's binary_logloss: 0.0102226
[149]	valid_0's binary_logloss: 0.0102035
[150]	valid_0's binary_logloss: 0.0101731
[151]	valid_0's binary_logloss: 0.0101858
[152]	valid_0's binary_logloss: 0.0101797
[153]	valid_0's binary_logloss: 0.0101192
[154]	valid_0's binary_logloss: 0.0100884
[155]	valid_0's binary_logloss: 0.0100545
[156]	valid_0's binary_logloss: 0.0100456
[157]	valid_0's binary_logloss: 0.0100291
[158]	valid_0's binary_logloss: 0.00998289
[159]	valid_0's binary_logloss: 0.00999877
[160]	valid_0's binary_logloss: 0.00998562
[161]	valid_0's binary_logloss: 0.0100188
[162]	valid_0's binary_logloss: 0.0100022
[163]	valid_0's binary_logloss: 0.0100165
[164]	valid_0's binary_logloss: 0.0100696
[165]	valid_0's binary_logloss: 0.0100713
[166]	valid_0's binary_logloss: 0.0101236
[167]	valid_0's binary_logloss: 0.0101039
[168]	valid_0's binary_logloss: 0.0101022
[169]	valid_0's binary_logloss: 0.0101372
[170]	valid_0's binary_logloss: 0.0101946
[171]	valid_0's binary_logloss: 0.0102382
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[172]	valid_0's binary_logloss: 0.010231
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[173]	valid_0's binary_logloss: 0.0102793
[174]	valid_0's binary_logloss: 0.0102978
[175]	valid_0's binary_logloss: 0.0102698
[176]	valid_0's binary_logloss: 0.0102898
[177]	valid_0's binary_logloss: 0.0103152
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[178]	valid_0's binary_logloss: 0.0103214
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[179]	valid_0's binary_logloss: 0.0103216
[180]	valid_0's binary_logloss: 0.0103195
[181]	valid_0's binary_logloss: 0.0103618
[182]	valid_0's binary_logloss: 0.0103635
[183]	valid_0's binary_logloss: 0.0103852
[184]	valid_0's binary_logloss: 0.0104004
[185]	valid_0's binary_logloss: 0.0104234
[186]	valid_0's binary_logloss: 0.0104251
[187]	valid_0's binary_logloss: 0.0104227
[188]	valid_0's binary_logloss: 0.0104262

Trening klas:  40%|████      | 201/500 [25:23<24:28,  4.91s/klasa, klasa=class_201, F1_klasy=0.8130, F1_macro=0.7562, drzewa=158]




Trening klas:  40%|████      | 202/500 [25:23<32:29,  6.54s/klasa, klasa=class_201, F1_klasy=0.8130, F1_macro=0.7562, drzewa=158]

[1]	valid_0's binary_logloss: 0.0195684
[2]	valid_0's binary_logloss: 0.0188543
[3]	valid_0's binary_logloss: 0.0182686
[4]	valid_0's binary_logloss: 0.0176249
[5]	valid_0's binary_logloss: 0.0169702
[6]	valid_0's binary_logloss: 0.0164356
[7]	valid_0's binary_logloss: 0.0159
[8]	valid_0's binary_logloss: 0.015389
[9]	valid_0's binary_logloss: 0.0147483
[10]	valid_0's binary_logloss: 0.014237
[11]	valid_0's binary_logloss: 0.0136591
[12]	valid_0's binary_logloss: 0.0131157
[13]	valid_0's binary_logloss: 0.0127212
[14]	valid_0's binary_logloss: 0.0123369
[15]	valid_0's binary_logloss: 0.0118061
[16]	valid_0's binary_logloss: 0.0113886
[17]	valid_0's binary_logloss: 0.0109964
[18]	valid_0's binary_logloss: 0.0105535
[19]	valid_0's binary_logloss: 0.0101981
[20]	valid_0's binary_logloss: 0.00990009
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.00949523
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.00921062
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.00882388
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.00858343
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.00826073
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.00800486
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.00779897
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.0076157
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.00730823
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.00706441
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.00688041
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.00673031
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.0066209
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.00650667
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.00636761
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.0062061
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.00601724
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.00592069
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.00582467
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.0056604
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.00542561
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.00520236
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.00498965
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.00488326
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.00472953
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.00464476
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.00451704
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.00438769
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.00426125
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.0042299
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.00413937
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.00407146
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.00404935
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.00397592
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.00395974
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.00386607
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.00382227
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.00377661
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.00373154
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.00360385
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.00358892
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.00350915
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.0034546
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.00344936
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.00340982
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.00332353
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.00331022
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.00320373
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.00310314
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.00302724
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.00299535
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.00301368
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.00301827
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.00303291
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.00300929
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.00302158
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.00297144
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.00286163
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.0028291
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.00284643
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.00281549
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.00280357
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.00281776
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.0027362
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.00275089
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.002744
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.00270543
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.00272051
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.00268707
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.00268373
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.00263882
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.00259055
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.00253617
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.00250007
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.00246273
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.00242734
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.00236526
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.00230089
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.00223928
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.00218947
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.00215286
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.00212346
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.00209037
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.00206356
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.00203257
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.00200464
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.00196034
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.00191989
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.00189759
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.00187922
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.00183527
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 0.00181539
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 0.0017568
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 0.00171597
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 0.00167138
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[116]	valid_0's binary_logloss: 0.00164213
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[117]	valid_0's binary_logloss: 0.0016427
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[118]	valid_0's binary_logloss: 0.00165215
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[119]	valid_0's binary_logloss: 0.00163671
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[120]	valid_0's binary_logloss: 0.00160409
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[121]	valid_0's binary_logloss: 0.00160464
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[122]	valid_0's binary_logloss: 0.00160948
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[123]	valid_0's binary_logloss: 0.00158157
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[124]	valid_0's binary_logloss: 0.00156679
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[125]	valid_0's binary_logloss: 0.00155453
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[126]	valid_0's binary_logloss: 0.00151777
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[127]	valid_0's binary_logloss: 0.00146036
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[128]	valid_0's binary_logloss: 0.0014387
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[129]	valid_0's binary_logloss: 0.00141355
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[130]	valid_0's binary_logloss: 0.00139279
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[131]	valid_0's binary_logloss: 0.00136618
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[132]	valid_0's binary_logloss: 0.00134942
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[133]	valid_0's binary_logloss: 0.00133147
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[134]	valid_0's binary_logloss: 0.00130302
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[135]	valid_0's binary_logloss: 0.00126127
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[136]	valid_0's binary_logloss: 0.00126497
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[137]	valid_0's binary_logloss: 0.00124932
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[138]	valid_0's binary_logloss: 0.00122413
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[139]	valid_0's binary_logloss: 0.00121524
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[140]	valid_0's binary_logloss: 0.00120761
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[141]	valid_0's binary_logloss: 0.00112306
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[142]	valid_0's binary_logloss: 0.00108157
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[143]	valid_0's binary_logloss: 0.00107271
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[144]	valid_0's binary_logloss: 0.00105231
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[145]	valid_0's binary_logloss: 0.00103488
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[146]	valid_0's binary_logloss: 0.0010144
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[147]	valid_0's binary_logloss: 0.00100312
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[148]	valid_0's binary_logloss: 0.000963621
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[149]	valid_0's binary_logloss: 0.000945681
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[150]	valid_0's binary_logloss: 0.000920076
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[151]	valid_0's binary_logloss: 0.000896067
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[152]	valid_0's binary_logloss: 0.000873028
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[153]	valid_0's binary_logloss: 0.00084949
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[154]	valid_0's binary_logloss: 0.000830551
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[155]	valid_0's binary_logloss: 0.000809532
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[156]	valid_0's binary_logloss: 0.000801888
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[157]	valid_0's binary_logloss: 0.000790501
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[158]	valid_0's binary_logloss: 0.000787827
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[159]	valid_0's binary_logloss: 0.000780776
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[160]	valid_0's binary_logloss: 0.000778045
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[161]	valid_0's binary_logloss: 0.000781623
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[162]	valid_0's binary_logloss: 0.000753475
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[163]	valid_0's binary_logloss: 0.000729587
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[164]	valid_0's binary_logloss: 0.00070316
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[165]	valid_0's binary_logloss: 0.000683712
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[166]	valid_0's binary_logloss: 0.000673274
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[167]	valid_0's binary_logloss: 0.000663193
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[168]	valid_0's binary_logloss: 0.00066405
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[169]	valid_0's binary_logloss: 0.000660212
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[170]	valid_0's binary_logloss: 0.000654628
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[171]	valid_0's binary_logloss: 0.000647206
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[172]	valid_0's binary_logloss: 0.000656823
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[173]	valid_0's binary_logloss: 0.000656556
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[174]	valid_0's binary_logloss: 0.000647636
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[175]	valid_0's binary_logloss: 0.000657803
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[176]	valid_0's binary_logloss: 0.000648489
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[177]	valid_0's binary_logloss: 0.00063291
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[178]	valid_0's binary_logloss: 0.0006222
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[179]	valid_0's binary_logloss: 0.000606722
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[180]	valid_0's binary_logloss: 0.000600679
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[181]	valid_0's binary_logloss: 0.000597427
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[182]	valid_0's binary_logloss: 0.000592093
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[183]	valid_0's binary_logloss: 0.000587731

Trening klas:  40%|████      | 202/500 [25:36<32:29,  6.54s/klasa, klasa=class_202, F1_klasy=0.0000, F1_macro=0.7524, drzewa=265]




Trening klas:  41%|████      | 203/500 [25:36<41:33,  8.40s/klasa, klasa=class_202, F1_klasy=0.0000, F1_macro=0.7524, drzewa=265]

[294]	valid_0's binary_logloss: 0.000413993
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[295]	valid_0's binary_logloss: 0.000413486
[1]	valid_0's binary_logloss: 0.141007
[2]	valid_0's binary_logloss: 0.139445
[3]	valid_0's binary_logloss: 0.137611
[4]	valid_0's binary_logloss: 0.135649
[5]	valid_0's binary_logloss: 0.133693
[6]	valid_0's binary_logloss: 0.132047
[7]	valid_0's binary_logloss: 0.130333
[8]	valid_0's binary_logloss: 0.128804
[9]	valid_0's binary_logloss: 0.127675
[10]	valid_0's binary_logloss: 0.12658
[11]	valid_0's binary_logloss: 0.125637
[12]	valid_0's binary_logloss: 0.124739
[13]	valid_0's binary_logloss: 0.123557
[14]	valid_0's binary_logloss: 0.122031
[15]	valid_0's binary_logloss: 0.120761
[16]	valid_0's binary_logloss: 0.119636
[17]	valid_0's binary_logloss: 0.118634
[18]	valid_0's binary_logloss: 0.117793
[19]	valid_0's binary_logloss: 0.116789
[20]	valid_0's binary_logloss: 0.116093
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.115249
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.114654
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.113807
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.113158
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.112171
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.111697
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.111401
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.110603
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.11008
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.109622
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.109221
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.108707
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.108118
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.107761
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.107394
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.107328
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.107169
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.106586
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.106365
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.106229
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.105908
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.105499
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.105021
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.104856
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.10477
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.104397
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.104195
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.103866
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.103568
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.10325
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.103027
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.102884
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.102666
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.102602
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.102424
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.102242
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.102317
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.102156
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.10197
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.10201
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.10182
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.101648
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.101649
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.10159
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.101509
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.101716
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.101712
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.101789
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.101684
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.101719
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.101605
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.101867
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.101688
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.101793
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.10189
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.10211
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.102176
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.101861
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.101753
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.101632
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.101796
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.102061
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.102183
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.102314
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.10248
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.102669
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.102804
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.102863
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.102802
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.10284
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.103031
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.103276
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.103565
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

Trening klas:  41%|████      | 203/500 [25:42<41:33,  8.40s/klasa, klasa=class_203, F1_klasy=0.4750, F1_macro=0.7511, drzewa=65]




Trening klas:  41%|████      | 204/500 [25:42<37:01,  7.51s/klasa, klasa=class_203, F1_klasy=0.4750, F1_macro=0.7511, drzewa=65]

[94]	valid_0's binary_logloss: 0.103781
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.103591
[1]	valid_0's binary_logloss: 0.0204642
[2]	valid_0's binary_logloss: 0.0196051
[3]	valid_0's binary_logloss: 0.0188017
[4]	valid_0's binary_logloss: 0.0180019
[5]	valid_0's binary_logloss: 0.0172437
[6]	valid_0's binary_logloss: 0.0164939
[7]	valid_0's binary_logloss: 0.0159255
[8]	valid_0's binary_logloss: 0.0153292
[9]	valid_0's binary_logloss: 0.0147356
[10]	valid_0's binary_logloss: 0.0142571
[11]	valid_0's binary_logloss: 0.0137577
[12]	valid_0's binary_logloss: 0.0132949
[13]	valid_0's binary_logloss: 0.012854
[14]	valid_0's binary_logloss: 0.0124092
[15]	valid_0's binary_logloss: 0.0120056
[16]	valid_0's binary_logloss: 0.0115921
[17]	valid_0's binary_logloss: 0.011175
[18]	valid_0's binary_logloss: 0.0107955
[19]	valid_0's binary_logloss: 0.0103946
[20]	valid_0's binary_logloss: 0.0100706
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.00976846
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.00945943
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.00917739
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.00889153
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.00856682
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.00830342
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.00807178
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.00785551
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.00764764
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.00746112
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.00727095
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.00706936
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.00684045
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.00666791
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.00647842
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.00631443
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.00612555
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.00601636
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.0059056
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.00578461
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.00560772
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.00551173
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.00540665
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.0053
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.00521401
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.00511457
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.00503154
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.00493196
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.00484135
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.00474442
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.00466366
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.0045958
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.00454268
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.00448037
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.00442573
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.00434981
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.00427817
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.00422715
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.00417602
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.00416312
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.00411604
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.00406523
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.004018
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.00398252
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.0039154
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.00388816
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.00385552
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.00379372
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.00377481
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.00376689
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.00373234
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.00368697
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.0036737
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.00363636
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.00359857
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.00360395
[77]	valid_0's binary_logloss: 0.0035936
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.00359457
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.00358259
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.00358609
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.00356412
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.00358096
[83]	valid_0's binary_logloss: 0.0035689
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.00354473
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.00355074
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.00351573
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.00354842
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.00350415
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.00346893
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.00348768
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.00345821
[92]	valid_0's binary_logloss: 0.00341925
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.00340165
[94]	valid_0's binary_logloss: 0.00341333
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.00338706
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.00336988
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.00334417
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.00332368
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.00326685
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.00322692
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.00319087
[102]	valid_0's binary_logloss: 0.00317531
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.00315723
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.00318659
[105]	valid_0's binary_logloss: 0.00318872
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.00319327
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.00320414
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.00316465
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.00314596
[110]	valid_0's binary_logloss: 0.00312196
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.00311399
[112]	valid_0's binary_logloss: 0.00309359
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 0.00307825
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 0.00311094
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 0.00308565
[116]	valid_0's binary_logloss: 0.00311224
[117]	valid_0's binary_logloss: 0.00313669
[118]	valid_0's binary_logloss: 0.00316868
[119]	valid_0's binary_logloss: 0.0031803
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[120]	valid_0's binary_logloss: 0.00320842
[121]	valid_0's binary_logloss: 0.0031894
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[122]	valid_0's binary_logloss: 0.00318703
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[123]	valid_0's binary_logloss: 0.00318602
[124]	valid_0's binary_logloss: 0.00322056
[125]	valid_0's binary_logloss: 0.00321782
[126]	valid_0's binary_logloss: 0.00320602
[127]	valid_0's binary_logloss: 0.00323101
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[128]	valid_0's binary_logloss: 0.00326534
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[129]	valid_0's binary_logloss: 0.00326117
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[130]	valid_0's binary_logloss: 0.00326371
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[131]	valid_0's binary_logloss: 0.00326659
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[132]	valid_0's binary_logloss: 0.00326526
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[133]	valid_0's binary_logloss: 0.00328335
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[134]	valid_0's binary_logloss: 0.00329261
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[135]	valid_0's binary_logloss: 0.00331369
[136]	valid_0's binary_logloss: 0.0033083
[137]	valid_0's binary_logloss: 0.00334298
[138]	valid_0's binary_logloss: 0.00334008
[139]	valid_0's binary_logloss: 0.0033674
[140]	valid_0's binary_logloss: 0.00335214
[141]	valid_0's binary_logloss: 0.00332494
[142]	valid_0's binary_logloss: 0.0033418
[143]	valid_0's binary_logloss: 0.00333027

Trening klas:  41%|████      | 204/500 [25:49<37:01,  7.51s/klasa, klasa=class_204, F1_klasy=0.4615, F1_macro=0.7497, drzewa=113]




Trening klas:  41%|████      | 205/500 [25:49<36:41,  7.46s/klasa, klasa=class_204, F1_klasy=0.4615, F1_macro=0.7497, drzewa=113]

[1]	valid_0's binary_logloss: 0.14013
[2]	valid_0's binary_logloss: 0.140261
[3]	valid_0's binary_logloss: 0.141223
[4]	valid_0's binary_logloss: 0.142496
[5]	valid_0's binary_logloss: 0.142165
[6]	valid_0's binary_logloss: 0.145548
[7]	valid_0's binary_logloss: 0.150988
[8]	valid_0's binary_logloss: 0.151365
[9]	valid_0's binary_logloss: 0.152183
[10]	valid_0's binary_logloss: 0.152377
[11]	valid_0's binary_logloss: 0.153211
[12]	valid_0's binary_logloss: 0.153124
[13]	valid_0's binary_logloss: 0.152652
[14]	valid_0's binary_logloss: 0.153141
[15]	valid_0's binary_logloss: 0.153119
[16]	valid_0's binary_logloss: 0.15219
[17]	valid_0's binary_logloss: 0.152549
[18]	valid_0's binary_logloss: 0.152662
[19]	valid_0's binary_logloss: 0.15255
[20]	valid_0's binary_logloss: 0.15195
[21]	valid_0's binary_logloss: 0.150954
[22]	valid_0's binary_logloss: 0.150235
[23]	valid_0's binary_logloss: 0.149044
[24]	valid_0's binary_logloss: 0.147737
[25]	valid_0's binary_logloss: 0.147578
[26]	valid_0's binary_logloss: 0.147922
[27]	valid_0's binary_logloss: 0.148142
[28]	valid_0's binary_logloss: 0.147766
[29]	valid_0's binary_logloss: 0.14817

Trening klas:  41%|████      | 205/500 [25:53<36:41,  7.46s/klasa, klasa=class_205, F1_klasy=0.0000, F1_macro=0.7460, drzewa=1]




Trening klas:  41%|████      | 206/500 [25:53<31:49,  6.49s/klasa, klasa=class_205, F1_klasy=0.0000, F1_macro=0.7460, drzewa=1]

[30]	valid_0's binary_logloss: 0.147572
[31]	valid_0's binary_logloss: 0.147787
[1]	valid_0's binary_logloss: 0.0339059
[2]	valid_0's binary_logloss: 0.0324865
[3]	valid_0's binary_logloss: 0.0310991
[4]	valid_0's binary_logloss: 0.0297494
[5]	valid_0's binary_logloss: 0.0286812
[6]	valid_0's binary_logloss: 0.027547
[7]	valid_0's binary_logloss: 0.0265844
[8]	valid_0's binary_logloss: 0.0258358
[9]	valid_0's binary_logloss: 0.0250408
[10]	valid_0's binary_logloss: 0.0242773
[11]	valid_0's binary_logloss: 0.0235676
[12]	valid_0's binary_logloss: 0.0229292
[13]	valid_0's binary_logloss: 0.0223524
[14]	valid_0's binary_logloss: 0.0218232
[15]	valid_0's binary_logloss: 0.0213461
[16]	valid_0's binary_logloss: 0.0209552
[17]	valid_0's binary_logloss: 0.0205575
[18]	valid_0's binary_logloss: 0.0201897
[19]	valid_0's binary_logloss: 0.0198723
[20]	valid_0's binary_logloss: 0.01958
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0193261
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0190588
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.0188669
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0186687
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.0184951
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.0180991
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.0180027
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.017929
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.0178149
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.0177315
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.017606
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.0174937
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.0174585
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.0172554
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.0171789
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.0170003
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.0168242
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.0167293
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.0166968
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.016719
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.0167446
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.0166072
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.0164501
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.0162663
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.0160586
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.0159267
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.0158191
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.0156788
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.0155896
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.0154177
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.0153766
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.0153722
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.0153521
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.0153556
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.0152783
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.0153339
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.0154109
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.0152295
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.01508
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.0150805
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.0149557
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.015031
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.0150167
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.0150694
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.015007
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.0150468
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.0150405
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.0150172
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.0149515
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.0148471
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.0149404
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.0150162
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.0150134
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.0150854
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.0150301
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.0151149
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.0151158
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.0151256
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.0150036
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.014958
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.0150137
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.0150887
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.0151199
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.0150731
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.0150457
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.0150743
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.0151208
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.0151864
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.0151957
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.0152987
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.0150613
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.015019
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.0146535
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.0146294
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.0146698
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.0146181
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.0145747
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.0145574
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.0144389
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.0144807
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.0144527
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.0144415
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.014542
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.0146227
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.0146889
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.014609
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.014618
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.0145972
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.0145761
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.0144691
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.0143731
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 0.0143462
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 0.0142782
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 0.0141967
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 0.0142051
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[116]	valid_0's binary_logloss: 0.0141523
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[117]	valid_0's binary_logloss: 0.0141688
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[118]	valid_0's binary_logloss: 0.014142
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[119]	valid_0's binary_logloss: 0.0142556
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[120]	valid_0's binary_logloss: 0.0142819
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[121]	valid_0's binary_logloss: 0.0142886
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[122]	valid_0's binary_logloss: 0.0142865
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[123]	valid_0's binary_logloss: 0.0143005
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[124]	valid_0's binary_logloss: 0.0142874
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[125]	valid_0's binary_logloss: 0.0142529
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[126]	valid_0's binary_logloss: 0.0142294
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[127]	valid_0's binary_logloss: 0.0142321
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[128]	valid_0's binary_logloss: 0.0142219
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[129]	valid_0's binary_logloss: 0.0142591
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[130]	valid_0's binary_logloss: 0.0143619
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[131]	valid_0's binary_logloss: 0.0143208
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[132]	valid_0's binary_logloss: 0.0143362
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[133]	valid_0's binary_logloss: 0.0142522
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[134]	valid_0's binary_logloss: 0.0141925
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[135]	valid_0's binary_logloss: 0.0142116
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[136]	valid_0's binary_logloss: 0.0141214
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[137]	valid_0's binary_logloss: 0.0141245
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[138]	valid_0's binary_logloss: 0.014122
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[139]	valid_0's binary_logloss: 0.0141187
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[140]	valid_0's binary_logloss: 0.0141332
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[141]	valid_0's binary_logloss: 0.0141105
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[142]	valid_0's binary_logloss: 0.014097
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[143]	valid_0's binary_logloss: 0.0140979
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[144]	valid_0's binary_logloss: 0.0141476
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[145]	valid_0's binary_logloss: 0.014183
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[146]	valid_0's binary_logloss: 0.0141361
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[147]	valid_0's binary_logloss: 0.014156
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[148]	valid_0's binary_logloss: 0.0141822
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[149]	valid_0's binary_logloss: 0.0141881
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[150]	valid_0's binary_logloss: 0.014207
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[151]	valid_0's binary_logloss: 0.0142282
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[152]	valid_0's binary_logloss: 0.0142818
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[153]	valid_0's binary_logloss: 0.0142433
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[154]	valid_0's binary_logloss: 0.0142355
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[155]	valid_0's binary_logloss: 0.0142656
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[156]	valid_0's binary_logloss: 0.014278
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[157]	valid_0's binary_logloss: 0.0143082
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[158]	valid_0's binary_logloss: 0.0144151
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[159]	valid_0's binary_logloss: 0.0145114
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[160]	valid_0's binary_logloss: 0.0145942
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[161]	valid_0's binary_logloss: 0.0145815
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[162]	valid_0's binary_logloss: 0.0146024
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[163]	valid_0's binary_logloss: 0.0146225
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[164]	valid_0's binary_logloss: 0.0146571
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[165]	valid_0's binary_logloss: 0.0147308
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[166]	valid_0's binary_logloss: 0.014773
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[167]	valid_0's binary_logloss: 0.0148211
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[168]	valid_0's binary_logloss: 0.0148417

Trening klas:  41%|████      | 206/500 [26:01<31:49,  6.49s/klasa, klasa=class_206, F1_klasy=0.8550, F1_macro=0.7466, drzewa=142]




Trening klas:  41%|████▏     | 207/500 [26:01<33:02,  6.77s/klasa, klasa=class_206, F1_klasy=0.8550, F1_macro=0.7466, drzewa=142]

[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[169]	valid_0's binary_logloss: 0.0148936
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[170]	valid_0's binary_logloss: 0.0148773
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[171]	valid_0's binary_logloss: 0.0149099
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[172]	valid_0's binary_logloss: 0.0149285
[1]	valid_0's binary_logloss: 0.110571
[2]	valid_0's binary_logloss: 0.1081
[3]	valid_0's binary_logloss: 0.105975
[4]	valid_0's binary_logloss: 0.104049
[5]	valid_0's binary_logloss: 0.102492
[6]	valid_0's binary_logloss: 0.100226
[7]	valid_0's binary_logloss: 0.0983374
[8]	valid_0's binary_logloss: 0.0968654
[9]	valid_0's binary_logloss: 0.0954928
[10]	valid_0's binary_logloss: 0.0942594
[11]	valid_0's binary_logloss: 0.0932232
[12]	valid_0's binary_logloss: 0.0921387
[13]	valid_0's binary_logloss: 0.0910493
[14]	valid_0's binary_logloss: 0.090308
[15]	valid_0's binary_logloss: 0.0892787
[16]	valid_0's binary_logloss: 0.0881704
[17]	valid_0's binary_logloss: 0.0873131
[18]	valid_0's binary_logloss: 0.0866191
[19]	valid_0's binary_logloss: 0.0857863
[20]	valid_0's binary_logloss: 0.0849364
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0842686
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0833613
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.0829839
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0823096
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.0817838
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.0816259
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.0811822
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.0809519
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.0806147
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.0803298
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.0801078
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.0799236
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.0797333
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.0793594
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.0789912
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.0792008
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.0791354
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.0790552
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.0786877
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.0783969
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.0781278
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.0778911
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.0778681
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.0777221
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.0773931
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.0772979
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.0771813
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.0766984
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.0768076
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.0765904
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.076617
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.0768775
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.0769228
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.0767633
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.076862
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.0765813
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.076395
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.0760848
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.0757696
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.0757701
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.0758647
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.0758958
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.0758316
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.0759221
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.0760268
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.0762271
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.0764119
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.0766335
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.0768741
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.0772146
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.0773514
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.077473
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.0775001
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.0773213
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.0775243
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.0777656
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.0780404
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.0784421
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.0787623
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.0791029
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.0789239
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.0789673
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.0790019
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.0789199
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.0790922
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.0793126
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.079532
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.0796595
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

Trening klas:  41%|████▏     | 207/500 [26:05<33:02,  6.77s/klasa, klasa=class_207, F1_klasy=0.4983, F1_macro=0.7454, drzewa=59]




Trening klas:  42%|████▏     | 208/500 [26:05<29:53,  6.14s/klasa, klasa=class_207, F1_klasy=0.4983, F1_macro=0.7454, drzewa=59]

[89]	valid_0's binary_logloss: 0.0799701
[1]	valid_0's binary_logloss: 0.0342821
[2]	valid_0's binary_logloss: 0.0332125
[3]	valid_0's binary_logloss: 0.0318841
[4]	valid_0's binary_logloss: 0.0304942
[5]	valid_0's binary_logloss: 0.0294465
[6]	valid_0's binary_logloss: 0.0288305
[7]	valid_0's binary_logloss: 0.0281793
[8]	valid_0's binary_logloss: 0.0277133
[9]	valid_0's binary_logloss: 0.0277203
[10]	valid_0's binary_logloss: 0.027135
[11]	valid_0's binary_logloss: 0.0264468
[12]	valid_0's binary_logloss: 0.0261864
[13]	valid_0's binary_logloss: 0.0258439
[14]	valid_0's binary_logloss: 0.0254232
[15]	valid_0's binary_logloss: 0.0251316
[16]	valid_0's binary_logloss: 0.0246487
[17]	valid_0's binary_logloss: 0.0242474
[18]	valid_0's binary_logloss: 0.0238456
[19]	valid_0's binary_logloss: 0.0235381
[20]	valid_0's binary_logloss: 0.0230832
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0229221
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0225624
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.0224632
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0224808
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.0225362
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.022335
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.0221188
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.0219784
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.0218567
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.0217691
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.0213805
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.0209571
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.0204626
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.0204464
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.0202864
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.0201269
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.0200774
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.0200656
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.0200555
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.0200714
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.0194732
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.0191474
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.0190529
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.018525
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.0180607
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.0178013
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.0179038
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.0177213
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.017531
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.017304
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.0171307
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.0172059
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.0171333
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.0170673
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.016827
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.0168382
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.0166375
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.0165001
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.0163633
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.016166
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.0159708
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.0160264
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.0161235
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.0161511
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.0162556
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.0163158
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.0162529
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.0161127
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.0162208
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.016341
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.0161786
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.0161462
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.0162879
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.0163807
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.0164651
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.0164838
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.0165667
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.016668
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.0167401
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.0168954
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.0167611
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.0167322
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.0166661
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.0166623
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.0166759
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.0164945
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.0162625
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.0160616
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.0157817
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.0154801
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.0153923
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.0154508
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.0152939
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.0154195
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.0153675
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.0153318
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.0152699
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.0152251
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.0151812
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.0150448
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.015046
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.0151009
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.0150936
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.015151
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.0150492
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.0149516
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.014835
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.0147786
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.0145807
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.0145189
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.0143947
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 0.0145154
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 0.0144402
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 0.0144617
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 0.0144574
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[116]	valid_0's binary_logloss: 0.0144457
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[117]	valid_0's binary_logloss: 0.0145292
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[118]	valid_0's binary_logloss: 0.0144266
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[119]	valid_0's binary_logloss: 0.0144375
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[120]	valid_0's binary_logloss: 0.0144263
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[121]	valid_0's binary_logloss: 0.0143795
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[122]	valid_0's binary_logloss: 0.0144224
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[123]	valid_0's binary_logloss: 0.0144956
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[124]	valid_0's binary_logloss: 0.0144926
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[125]	valid_0's binary_logloss: 0.0145047
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[126]	valid_0's binary_logloss: 0.0144692
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[127]	valid_0's binary_logloss: 0.0143954
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[128]	valid_0's binary_logloss: 0.0143123
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[129]	valid_0's binary_logloss: 0.014247
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[130]	valid_0's binary_logloss: 0.0141714
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[131]	valid_0's binary_logloss: 0.0139883
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[132]	valid_0's binary_logloss: 0.0138326
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[133]	valid_0's binary_logloss: 0.0138386
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[134]	valid_0's binary_logloss: 0.0137817
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[135]	valid_0's binary_logloss: 0.0138027
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[136]	valid_0's binary_logloss: 0.0137079
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[137]	valid_0's binary_logloss: 0.0136269
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[138]	valid_0's binary_logloss: 0.0135098
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[139]	valid_0's binary_logloss: 0.0134665
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[140]	valid_0's binary_logloss: 0.0133702
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[141]	valid_0's binary_logloss: 0.0133403
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[142]	valid_0's binary_logloss: 0.0132806
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[143]	valid_0's binary_logloss: 0.0132016
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[144]	valid_0's binary_logloss: 0.0131423
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[145]	valid_0's binary_logloss: 0.0131039
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[146]	valid_0's binary_logloss: 0.0131207
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[147]	valid_0's binary_logloss: 0.0131822
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[148]	valid_0's binary_logloss: 0.0131506
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[149]	valid_0's binary_logloss: 0.0131767
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[150]	valid_0's binary_logloss: 0.0131311
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[151]	valid_0's binary_logloss: 0.0130945
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[152]	valid_0's binary_logloss: 0.0130442
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[153]	valid_0's binary_logloss: 0.0130145
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[154]	valid_0's binary_logloss: 0.0130741
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[155]	valid_0's binary_logloss: 0.013032
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[156]	valid_0's binary_logloss: 0.0130767
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[157]	valid_0's binary_logloss: 0.0130511
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[158]	valid_0's binary_logloss: 0.012931
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[159]	valid_0's binary_logloss: 0.0129029
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[160]	valid_0's binary_logloss: 0.0128515
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[161]	valid_0's binary_logloss: 0.012839
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[162]	valid_0's binary_logloss: 0.0128093
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[163]	valid_0's binary_logloss: 0.0128825
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[164]	valid_0's binary_logloss: 0.0129494
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[165]	valid_0's binary_logloss: 0.012958
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[166]	valid_0's binary_logloss: 0.0129674
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[167]	valid_0's binary_logloss: 0.0129938
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[168]	valid_0's binary_logloss: 0.0129934
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[169]	valid_0's binary_logloss: 0.0129815
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[170]	valid_0's binary_logloss: 0.0130228
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[171]	valid_0's binary_logloss: 0.0130019
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[172]	valid_0's binary_logloss: 0.0130327
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[173]	valid_0's binary_logloss: 0.0130003
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[174]	valid_0's binary_logloss: 0.0130285
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[175]	valid_0's binary_logloss: 0.0130285
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[176]	valid_0's binary_logloss: 0.0129957
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[177]	valid_0's binary_logloss: 0.0130104
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[178]	valid_0's binary_logloss: 0.0129747
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[179]	valid_0's binary_logloss: 0.0129373
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[180]	valid_0's binary_logloss: 0.0129174
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[181]	valid_0's binary_logloss: 0.0128436
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[182]	valid_0's binary_logloss: 0.0128542
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[183]	valid_0's binary_logloss: 0.012866
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[184]	valid_0's binary_logloss: 0.0128751

Trening klas:  42%|████▏     | 208/500 [26:13<29:53,  6.14s/klasa, klasa=class_208, F1_klasy=0.8333, F1_macro=0.7458, drzewa=193]




Trening klas:  42%|████▏     | 209/500 [26:13<31:56,  6.59s/klasa, klasa=class_208, F1_klasy=0.8333, F1_macro=0.7458, drzewa=193]

[219]	valid_0's binary_logloss: 0.0130085
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[220]	valid_0's binary_logloss: 0.0130229
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[221]	valid_0's binary_logloss: 0.0130073
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[222]	valid_0's binary_logloss: 0.0130305
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[223]	valid_0's binary_logloss: 0.0130519
[1]	valid_0's binary_logloss: 0.0342821
[2]	valid_0's binary_logloss: 0.0332125
[3]	valid_0's binary_logloss: 0.0318841
[4]	valid_0's binary_logloss: 0.0304942
[5]	valid_0's binary_logloss: 0.0294465
[6]	valid_0's binary_logloss: 0.0288305
[7]	valid_0's binary_logloss: 0.0281793
[8]	valid_0's binary_logloss: 0.0277133
[9]	valid_0's binary_logloss: 0.0277203
[10]	valid_0's binary_logloss: 0.027135
[11]	valid_0's binary_logloss: 0.0264468
[12]	valid_0's binary_logloss: 0.0261864
[13]	valid_0's binary_logloss: 0.0258439
[14]	valid_0's binary_logloss: 0.0254232
[15]	valid_0's binary_logloss: 0.0251316
[16]	valid_0's binary_logloss: 0.0246487
[17]	valid_0's binary_logloss: 0.0242474
[18]	valid_0's binary_logloss: 0.0238456
[19]	valid_0's binary_logloss: 0.0235381
[20]	valid_0's binary_logloss: 0.0230832
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0229221
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0225624
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.0224632
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0224808
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.0225362
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.022335
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.0221188
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.0219784
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.0218567
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.0217691
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.0213805
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.0209571
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.0204626
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.0204464
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.0202864
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.0201269
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.0200774
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.0200656
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.0200555
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.0200714
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.0194732
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.0191474
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.0190529
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.018525
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.0180607
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.0178013
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.0179038
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.0177213
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.017531
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.017304
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.0171307
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.0172059
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.0171333
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.0170673
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.016827
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.0168382
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.0166375
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.0165001
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.0163633
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.016166
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.0159708
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.0160264
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.0161235
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.0161511
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.0162556
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.0163158
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.0162529
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.0161127
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.0162208
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.016341
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.0161786
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.0161462
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.0162879
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.0163807
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.0164651
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.0164838
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.0165667
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.016668
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.0167401
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.0168954
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.0167611
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.0167322
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.0166661
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.0166623
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.0166759
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.0164945
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.0162625
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.0160616
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.0157817
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.0154801
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.0153923
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.0154508
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.0152939
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.0154195
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.0153675
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.0153318
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.0152699
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.0152251
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.0151812
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.0150448
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.015046
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.0151009
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.0150936
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.015151
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.0150492
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.0149516
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.014835
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.0147786
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.0145807
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.0145189
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.0143947
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 0.0145154
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 0.0144402
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 0.0144617
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 0.0144574
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[116]	valid_0's binary_logloss: 0.0144457
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[117]	valid_0's binary_logloss: 0.0145292
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[118]	valid_0's binary_logloss: 0.0144266
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[119]	valid_0's binary_logloss: 0.0144375
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[120]	valid_0's binary_logloss: 0.0144263
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[121]	valid_0's binary_logloss: 0.0143795
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[122]	valid_0's binary_logloss: 0.0144224
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[123]	valid_0's binary_logloss: 0.0144956
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[124]	valid_0's binary_logloss: 0.0144926
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[125]	valid_0's binary_logloss: 0.0145047
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[126]	valid_0's binary_logloss: 0.0144692
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[127]	valid_0's binary_logloss: 0.0143954
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[128]	valid_0's binary_logloss: 0.0143123
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[129]	valid_0's binary_logloss: 0.014247
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[130]	valid_0's binary_logloss: 0.0141714
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[131]	valid_0's binary_logloss: 0.0139883
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[132]	valid_0's binary_logloss: 0.0138326
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[133]	valid_0's binary_logloss: 0.0138386
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[134]	valid_0's binary_logloss: 0.0137817
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[135]	valid_0's binary_logloss: 0.0138027
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[136]	valid_0's binary_logloss: 0.0137079
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[137]	valid_0's binary_logloss: 0.0136269
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[138]	valid_0's binary_logloss: 0.0135098
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[139]	valid_0's binary_logloss: 0.0134665
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[140]	valid_0's binary_logloss: 0.0133702
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[141]	valid_0's binary_logloss: 0.0133403
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[142]	valid_0's binary_logloss: 0.0132806
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[143]	valid_0's binary_logloss: 0.0132016
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[144]	valid_0's binary_logloss: 0.0131423
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[145]	valid_0's binary_logloss: 0.0131039
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[146]	valid_0's binary_logloss: 0.0131207
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[147]	valid_0's binary_logloss: 0.0131822
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[148]	valid_0's binary_logloss: 0.0131506
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[149]	valid_0's binary_logloss: 0.0131767
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[150]	valid_0's binary_logloss: 0.0131311
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[151]	valid_0's binary_logloss: 0.0130945
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[152]	valid_0's binary_logloss: 0.0130442
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[153]	valid_0's binary_logloss: 0.0130145
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[154]	valid_0's binary_logloss: 0.0130741
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[155]	valid_0's binary_logloss: 0.013032
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[156]	valid_0's binary_logloss: 0.0130767
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[157]	valid_0's binary_logloss: 0.0130511
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[158]	valid_0's binary_logloss: 0.012931
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[159]	valid_0's binary_logloss: 0.0129029
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[160]	valid_0's binary_logloss: 0.0128515
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[161]	valid_0's binary_logloss: 0.012839
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[162]	valid_0's binary_logloss: 0.0128093
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[163]	valid_0's binary_logloss: 0.0128825
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[164]	valid_0's binary_logloss: 0.0129494
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[165]	valid_0's binary_logloss: 0.012958
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[166]	valid_0's binary_logloss: 0.0129674
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[167]	valid_0's binary_logloss: 0.0129938
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[168]	valid_0's binary_logloss: 0.0129934
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[169]	valid_0's binary_logloss: 0.0129815
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[170]	valid_0's binary_logloss: 0.0130228
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[171]	valid_0's binary_logloss: 0.0130019
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[172]	valid_0's binary_logloss: 0.0130327
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[173]	valid_0's binary_logloss: 0.0130003
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[174]	valid_0's binary_logloss: 0.0130285
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[175]	valid_0's binary_logloss: 0.0130285
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[176]	valid_0's binary_logloss: 0.0129957
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[177]	valid_0's binary_logloss: 0.0130104
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[178]	valid_0's binary_logloss: 0.0129747
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[179]	valid_0's binary_logloss: 0.0129373
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[180]	valid_0's binary_logloss: 0.0129174

Trening klas:  42%|████▏     | 209/500 [26:20<31:56,  6.59s/klasa, klasa=class_209, F1_klasy=0.8333, F1_macro=0.7462, drzewa=193]




Trening klas:  42%|████▏     | 210/500 [26:21<33:24,  6.91s/klasa, klasa=class_209, F1_klasy=0.8333, F1_macro=0.7462, drzewa=193]

[222]	valid_0's binary_logloss: 0.0130305
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[223]	valid_0's binary_logloss: 0.0130519
[1]	valid_0's binary_logloss: 0.0620624
[2]	valid_0's binary_logloss: 0.0618555
[3]	valid_0's binary_logloss: 0.0614123
[4]	valid_0's binary_logloss: 0.0612803
[5]	valid_0's binary_logloss: 0.0612915
[6]	valid_0's binary_logloss: 0.0616954
[7]	valid_0's binary_logloss: 0.0618274
[8]	valid_0's binary_logloss: 0.061778
[9]	valid_0's binary_logloss: 0.0616993
[10]	valid_0's binary_logloss: 0.0615098
[11]	valid_0's binary_logloss: 0.0612104
[12]	valid_0's binary_logloss: 0.0612797
[13]	valid_0's binary_logloss: 0.0612058
[14]	valid_0's binary_logloss: 0.0610171
[15]	valid_0's binary_logloss: 0.0609534
[16]	valid_0's binary_logloss: 0.0605965
[17]	valid_0's binary_logloss: 0.0604866
[18]	valid_0's binary_logloss: 0.0604047
[19]	valid_0's binary_logloss: 0.0602027
[20]	valid_0's binary_logloss: 0.0601484
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0602323
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.060117
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.059676
[24]	valid_0's binary_logloss: 0.0594616
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.0592385
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.0588089
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.0585103
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.058257
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.0584277
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.058038
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.0579233
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.0581306
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.0581944
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.0582017
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.0578274
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.057732
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.0575532
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.0572657
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.0571941
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.0570627
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.0569966
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.0570936
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.0570431
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.0567883
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.0569101
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.0569278
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.0571726
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.0572921
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.0576036
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.0578994
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.0577208
[52]	valid_0's binary_logloss: 0.0575484
[53]	valid_0's binary_logloss: 0.0569911
[54]	valid_0's binary_logloss: 0.0566107
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.0563843
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.0564834
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.0565091
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.0564042
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.056466
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.056373
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.0561327
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.0560681
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.0562337
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.0561695
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.0559443
[66]	valid_0's binary_logloss: 0.0559254
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.0558726
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.0560647
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.0557502
[70]	valid_0's binary_logloss: 0.0557465
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.0556354
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.0552685
[73]	valid_0's binary_logloss: 0.055046
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.0547375
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.0543601
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.0541661
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.0539302
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.0539182
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.053706
[80]	valid_0's binary_logloss: 0.0534258
[81]	valid_0's binary_logloss: 0.053466
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.05338
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.0532915
[84]	valid_0's binary_logloss: 0.0532854
[85]	valid_0's binary_logloss: 0.0532264
[86]	valid_0's binary_logloss: 0.0530466
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.0528738
[88]	valid_0's binary_logloss: 0.0526683
[89]	valid_0's binary_logloss: 0.052463
[90]	valid_0's binary_logloss: 0.0522654
[91]	valid_0's binary_logloss: 0.0520779
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.0519922
[93]	valid_0's binary_logloss: 0.0520087
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.0521267
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.0520491
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.0521366
[97]	valid_0's binary_logloss: 0.0521409
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.0522813
[99]	valid_0's binary_logloss: 0.0523813
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.0524467
[101]	valid_0's binary_logloss: 0.052461
[102]	valid_0's binary_logloss: 0.0523768
[103]	valid_0's binary_logloss: 0.0523876
[104]	valid_0's binary_logloss: 0.0523592
[105]	valid_0's binary_logloss: 0.0520983
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.0520796
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.0520282
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.0520704
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.0521441
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.0520766
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.052207
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 0.0522229
[113]	valid_0's binary_logloss: 0.052352
[114]	valid_0's binary_logloss: 0.0526494
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 0.0528038
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[116]	valid_0's binary_logloss: 0.0529496
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[117]	valid_0's binary_logloss: 0.0530922
[118]	valid_0's binary_logloss: 0.0531404
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[119]	valid_0's binary_logloss: 0.0530936
[120]	valid_0's binary_logloss: 0.0531243
[121]	valid_0's binary_logloss: 0.0531219

Trening klas:  42%|████▏     | 210/500 [26:27<33:24,  6.91s/klasa, klasa=class_210, F1_klasy=0.5619, F1_macro=0.7453, drzewa=92]




Trening klas:  42%|████▏     | 211/500 [26:27<32:16,  6.70s/klasa, klasa=class_210, F1_klasy=0.5619, F1_macro=0.7453, drzewa=92]

[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[122]	valid_0's binary_logloss: 0.0530198
[1]	valid_0's binary_logloss: 0.0243377
[2]	valid_0's binary_logloss: 0.022809
[3]	valid_0's binary_logloss: 0.0214372
[4]	valid_0's binary_logloss: 0.0202248
[5]	valid_0's binary_logloss: 0.0190466
[6]	valid_0's binary_logloss: 0.0179664
[7]	valid_0's binary_logloss: 0.0170186
[8]	valid_0's binary_logloss: 0.0160976
[9]	valid_0's binary_logloss: 0.01525
[10]	valid_0's binary_logloss: 0.0144653
[11]	valid_0's binary_logloss: 0.0137401
[12]	valid_0's binary_logloss: 0.0130348
[13]	valid_0's binary_logloss: 0.0123934
[14]	valid_0's binary_logloss: 0.0117742
[15]	valid_0's binary_logloss: 0.0112429
[16]	valid_0's binary_logloss: 0.0107039
[17]	valid_0's binary_logloss: 0.0101932
[18]	valid_0's binary_logloss: 0.00971576
[19]	valid_0's binary_logloss: 0.00925435
[20]	valid_0's binary_logloss: 0.00881957
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.00842865
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0080563
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.00767649
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.00730868
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.0070012
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.00670885
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.00641412
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.00614015
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.00587003
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.00562349
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.00538261
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.00513529
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.0049043
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.00468723
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.00447926
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.00429312
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.00411957
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.00394427
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.00377758
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.00363498
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.00346453
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.00329533
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.00314363
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.00299521
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.00285262
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.00275621
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.00264524
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.00253662
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.00246533
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.00235836
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.00226671
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.00217575
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.00208513
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.00199247
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.00191583
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.00184033
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.00176445
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.00169053
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.00161591
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.00155141
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.00148966
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.00142684
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.00136013
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.00130811
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.00125682
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.00120847
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.00116535
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.00112493
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.00108911
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.00105691
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.00102666
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.000996994
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.000964757
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.000937342
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.000909302
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.000886649
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.000852415
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.000813775
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.000777416
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.00074699
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.000723102
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.000704566
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.000678117
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.000661827
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.000650831
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.000621669
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.000594779
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.000572494
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.000547169
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.000521113
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.000501359
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.000493424
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.000476216
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.000459153
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.000443007
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.000427862
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.000417337
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.00041426
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.000397162
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.000389765
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.000370684
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.000352628
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.000335439
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.000318805
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.000303014
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.000292895
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.000283429
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.00027485
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.000265638
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.000257322
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.000257729
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 0.000247747
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 0.000237893
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 0.000228202
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 0.000222059
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[116]	valid_0's binary_logloss: 0.000221695
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[117]	valid_0's binary_logloss: 0.000218843
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[118]	valid_0's binary_logloss: 0.000217662
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[119]	valid_0's binary_logloss: 0.000212107
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[120]	valid_0's binary_logloss: 0.000211013
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[121]	valid_0's binary_logloss: 0.000211169
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[122]	valid_0's binary_logloss: 0.000204188
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[123]	valid_0's binary_logloss: 0.000202789
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[124]	valid_0's binary_logloss: 0.000202491
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[125]	valid_0's binary_logloss: 0.000194423
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[126]	valid_0's binary_logloss: 0.000188586
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[127]	valid_0's binary_logloss: 0.000183154
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[128]	valid_0's binary_logloss: 0.000176166
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[129]	valid_0's binary_logloss: 0.000171613
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[130]	valid_0's binary_logloss: 0.000165307
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[131]	valid_0's binary_logloss: 0.000165581
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[132]	valid_0's binary_logloss: 0.000164272
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[133]	valid_0's binary_logloss: 0.000160849
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[134]	valid_0's binary_logloss: 0.000157844
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[135]	valid_0's binary_logloss: 0.00015761
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[136]	valid_0's binary_logloss: 0.0001522
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[137]	valid_0's binary_logloss: 0.0001496
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[138]	valid_0's binary_logloss: 0.000145119
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[139]	valid_0's binary_logloss: 0.000140852
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[140]	valid_0's binary_logloss: 0.000136771
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[141]	valid_0's binary_logloss: 0.000139025
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[142]	valid_0's binary_logloss: 0.000141355
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[143]	valid_0's binary_logloss: 0.00014206
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[144]	valid_0's binary_logloss: 0.000144129
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[145]	valid_0's binary_logloss: 0.000143575
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[146]	valid_0's binary_logloss: 0.000139592
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[147]	valid_0's binary_logloss: 0.000139142
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[148]	valid_0's binary_logloss: 0.00014114
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[149]	valid_0's binary_logloss: 0.000136604
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[150]	valid_0's binary_logloss: 0.000136104
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[151]	valid_0's binary_logloss: 0.000137964
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[152]	valid_0's binary_logloss: 0.00014097
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[153]	valid_0's binary_logloss: 0.000144042
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[154]	valid_0's binary_logloss: 0.000146273
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[155]	valid_0's binary_logloss: 0.000148648
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[156]	valid_0's binary_logloss: 0.000146778
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[157]	valid_0's binary_logloss: 0.000143911
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[158]	valid_0's binary_logloss: 0.000142122
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[159]	valid_0's binary_logloss: 0.00014258
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[160]	valid_0's binary_logloss: 0.000142558
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[161]	valid_0's binary_logloss: 0.000145285
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[162]	valid_0's binary_logloss: 0.000143015
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[163]	valid_0's binary_logloss: 0.000139676
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[164]	valid_0's binary_logloss: 0.000138247
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[165]	valid_0's binary_logloss: 0.00013849
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[166]	valid_0's binary_logloss: 0.000137554
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[167]	valid_0's binary_logloss: 0.000136693
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[168]	valid_0's binary_logloss: 0.000132959
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[169]	valid_0's binary_logloss: 0.00013099
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[170]	valid_0's binary_logloss: 0.000130483
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[171]	valid_0's binary_logloss: 0.000133007
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[172]	valid_0's binary_logloss: 0.000135739
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[173]	valid_0's binary_logloss: 0.000137964
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[174]	valid_0's binary_logloss: 0.000141426
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[175]	valid_0's binary_logloss: 0.000145155
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[176]	valid_0's binary_logloss: 0.000144842
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[177]	valid_0's binary_logloss: 0.000143079
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[178]	valid_0's binary_logloss: 0.000145278
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[179]	valid_0's binary_logloss: 0.000143314
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[180]	valid_0's binary_logloss: 0.000141954
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[181]	valid_0's binary_logloss: 0.000139987

Trening klas:  42%|████▏     | 211/500 [26:32<32:16,  6.70s/klasa, klasa=class_211, F1_klasy=1.0000, F1_macro=0.7465, drzewa=194]




Trening klas:  42%|████▏     | 212/500 [26:32<29:48,  6.21s/klasa, klasa=class_211, F1_klasy=1.0000, F1_macro=0.7465, drzewa=194]

[217]	valid_0's binary_logloss: 0.000117071
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[218]	valid_0's binary_logloss: 0.000118942
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[219]	valid_0's binary_logloss: 0.000120476
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[220]	valid_0's binary_logloss: 0.000120469
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[221]	valid_0's binary_logloss: 0.000120246
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[222]	valid_0's binary_logloss: 0.00012007
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[223]	valid_0's binary_logloss: 0.00011989
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[224]	valid_0's binary_logloss: 0.000119588
[1]	valid_0's binary_logloss: 0.0325846
[2]	valid_0's binary_logloss: 0.0316604
[3]	valid_0's binary_logloss: 0.0308587
[4]	valid_0's binary_logloss: 0.0300337
[5]	valid_0's binary_logloss: 0.0292964
[6]	valid_0's binary_logloss: 0.0287622
[7]	valid_0's binary_logloss: 0.0281635
[8]	valid_0's binary_logloss: 0.0276258
[9]	valid_0's binary_logloss: 0.0270509
[10]	valid_0's binary_logloss: 0.0265044
[11]	valid_0's binary_logloss: 0.0260284
[12]	valid_0's binary_logloss: 0.0254191
[13]	valid_0's binary_logloss: 0.0250055
[14]	valid_0's binary_logloss: 0.0245817
[15]	valid_0's binary_logloss: 0.0241869
[16]	valid_0's binary_logloss: 0.0239017
[17]	valid_0's binary_logloss: 0.0235547
[18]	valid_0's binary_logloss: 0.0232631
[19]	valid_0's binary_logloss: 0.0230111
[20]	valid_0's binary_logloss: 0.0227284
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0225622
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0223264
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.0220899
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0218972
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.0217392
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.0215806
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.0214375
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.0212726
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.0211249
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.0210234
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.0208973
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.020794
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.0206965
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.0205682
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.0204766
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.0203638
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.0202799
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.0202461
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.0202108
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.0201624
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.0201207
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.0200946
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.0200374
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.0200358
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.0200679
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.0200752
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.0200721
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.0200693
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.0200958
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.0200932
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.0200958
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.0201141
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.020111
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.0201028
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.020134
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.0200185
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.0199387
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.0199345
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.0199474
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.0199303
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.0199547
[62]	valid_0's binary_logloss: 0.0199564
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.0199606
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.0199237
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.0199163
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.0199309
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.019941
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.0199567
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.019972
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.0199318
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.0199225
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.0199599
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.0199634
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.0199951
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.0200109
[76]	valid_0's binary_logloss: 0.0199838
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.0200116
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.020061
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.0201232
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.020196
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.0202582
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.0202508
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.020254
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.0203156
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.0203348
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.020372
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.0204608
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.0204287
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.0204876
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.0204947
[91]	valid_0's binary_logloss: 0.0205449
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.0205798
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.0206079
[94]	valid_0's binary_logloss: 0.0206202

Trening klas:  42%|████▏     | 212/500 [26:38<29:48,  6.21s/klasa, klasa=class_212, F1_klasy=0.6301, F1_macro=0.7460, drzewa=65]




Trening klas:  43%|████▎     | 213/500 [26:38<29:05,  6.08s/klasa, klasa=class_212, F1_klasy=0.6301, F1_macro=0.7460, drzewa=65]

[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.0206505
[1]	valid_0's binary_logloss: 0.0158148
[2]	valid_0's binary_logloss: 0.0150911
[3]	valid_0's binary_logloss: 0.0144125
[4]	valid_0's binary_logloss: 0.0137678
[5]	valid_0's binary_logloss: 0.013153
[6]	valid_0's binary_logloss: 0.0125107
[7]	valid_0's binary_logloss: 0.0119011
[8]	valid_0's binary_logloss: 0.0113207
[9]	valid_0's binary_logloss: 0.0107679
[10]	valid_0's binary_logloss: 0.0102631
[11]	valid_0's binary_logloss: 0.00977017
[12]	valid_0's binary_logloss: 0.00930294
[13]	valid_0's binary_logloss: 0.00887346
[14]	valid_0's binary_logloss: 0.00846625
[15]	valid_0's binary_logloss: 0.00806123
[16]	valid_0's binary_logloss: 0.00769409
[17]	valid_0's binary_logloss: 0.0073478
[18]	valid_0's binary_logloss: 0.00700217
[19]	valid_0's binary_logloss: 0.00669247
[20]	valid_0's binary_logloss: 0.00637958
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.00607384
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.00578213
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.00550532
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.00524417
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.00499292
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.00475937
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.00453316
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.00431945
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.00411458
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.00391997
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.00373736
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.00356766
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.00340283
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.00324744
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.00309453
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.00295168
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.00281308
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.0026803
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.00256003
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.00244207
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.00232841
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.00222099
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.00211981
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.00202523
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.00192913
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.00184099
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.00175999
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.00168097
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.00160309
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.00153288
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.00146555
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.00140284
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.00134039
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.00128447
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.00122704
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.00117278
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.0011224
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.00107008
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.00102517
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.000980284
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.000940844
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.000901471
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.000864156
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.000828632
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.000794146
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.000757939
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.000725083
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.000696637
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.000664436
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.000639134
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.000610394
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.000582418
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.000554604
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.000532034
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.000507155
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.000485117
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.000463582
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.000445219
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.000425735
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.000406664
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.000390939
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.000374392
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.000357898
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.000342906
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.000326929
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.000313565
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.000299819
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.000291478
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.000282438
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.000270229
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.000258898
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.000246785
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.000238427
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.000229762
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.000221294
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.000210306
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.00020218
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.000194507
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.000185213
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.000177855
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.000170452
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.000163332
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.000155493
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.000146638
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.000141716
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.000137439
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.000132829
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.0001271
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.000121367
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.000117485
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.00011461
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 0.000111604
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 0.000107924
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 0.000104536
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 0.000102862
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[116]	valid_0's binary_logloss: 9.88975e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[117]	valid_0's binary_logloss: 9.5534e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[118]	valid_0's binary_logloss: 9.21429e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[119]	valid_0's binary_logloss: 8.84835e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[120]	valid_0's binary_logloss: 8.51403e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[121]	valid_0's binary_logloss: 8.35409e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[122]	valid_0's binary_logloss: 8.27526e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[123]	valid_0's binary_logloss: 8.07957e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[124]	valid_0's binary_logloss: 7.96894e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[125]	valid_0's binary_logloss: 7.84096e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[126]	valid_0's binary_logloss: 7.60886e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[127]	valid_0's binary_logloss: 7.38366e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[128]	valid_0's binary_logloss: 7.16051e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[129]	valid_0's binary_logloss: 7.00208e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[130]	valid_0's binary_logloss: 6.7697e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[131]	valid_0's binary_logloss: 6.60442e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[132]	valid_0's binary_logloss: 6.3883e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[133]	valid_0's binary_logloss: 6.22806e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[134]	valid_0's binary_logloss: 6.05026e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[135]	valid_0's binary_logloss: 5.79972e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[136]	valid_0's binary_logloss: 5.63363e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[137]	valid_0's binary_logloss: 5.45663e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[138]	valid_0's binary_logloss: 5.32384e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[139]	valid_0's binary_logloss: 5.22619e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[140]	valid_0's binary_logloss: 5.07932e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[141]	valid_0's binary_logloss: 4.88866e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[142]	valid_0's binary_logloss: 4.80524e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[143]	valid_0's binary_logloss: 4.62949e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[144]	valid_0's binary_logloss: 4.49346e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[145]	valid_0's binary_logloss: 4.39695e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[146]	valid_0's binary_logloss: 4.23699e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[147]	valid_0's binary_logloss: 4.00844e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[148]	valid_0's binary_logloss: 3.85481e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[149]	valid_0's binary_logloss: 3.71653e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[150]	valid_0's binary_logloss: 3.61089e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[151]	valid_0's binary_logloss: 3.48104e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[152]	valid_0's binary_logloss: 3.36254e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[153]	valid_0's binary_logloss: 3.25125e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[154]	valid_0's binary_logloss: 3.17466e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[155]	valid_0's binary_logloss: 3.08419e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[156]	valid_0's binary_logloss: 3.02145e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[157]	valid_0's binary_logloss: 2.95669e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[158]	valid_0's binary_logloss: 2.93855e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[159]	valid_0's binary_logloss: 2.84661e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[160]	valid_0's binary_logloss: 2.76813e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[161]	valid_0's binary_logloss: 2.71243e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[162]	valid_0's binary_logloss: 2.65746e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[163]	valid_0's binary_logloss: 2.63741e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[164]	valid_0's binary_logloss: 2.59077e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[165]	valid_0's binary_logloss: 2.57498e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[166]	valid_0's binary_logloss: 2.48036e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[167]	valid_0's binary_logloss: 2.39214e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[168]	valid_0's binary_logloss: 2.31229e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[169]	valid_0's binary_logloss: 2.23556e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[170]	valid_0's binary_logloss: 2.16449e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[171]	valid_0's binary_logloss: 2.15093e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[172]	valid_0's binary_logloss: 2.1416e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[173]	valid_0's binary_logloss: 2.12886e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[174]	valid_0's binary_logloss: 2.10284e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[175]	valid_0's binary_logloss: 2.06771e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[176]	valid_0's binary_logloss: 2.04971e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[177]	valid_0's binary_logloss: 2.03729e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[178]	valid_0's binary_logloss: 2.03576e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[179]	valid_0's binary_logloss: 1.98973e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[180]	valid_0's binary_logloss: 1.9805e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[181]	valid_0's binary_logloss: 1.907e-05

Trening klas:  43%|████▎     | 213/500 [26:47<29:05,  6.08s/klasa, klasa=class_213, F1_klasy=0.0000, F1_macro=0.7425, drzewa=295]




Trening klas:  43%|████▎     | 214/500 [26:47<33:05,  6.94s/klasa, klasa=class_213, F1_klasy=0.0000, F1_macro=0.7425, drzewa=295]

[295]	valid_0's binary_logloss: 7.1017e-06
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[296]	valid_0's binary_logloss: 7.10586e-06
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[297]	valid_0's binary_logloss: 7.10401e-06
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[298]	valid_0's binary_logloss: 7.15159e-06
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[299]	valid_0's binary_logloss: 7.20064e-06
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[300]	valid_0's binary_logloss: 7.26172e-06
[1]	valid_0's binary_logloss: 0.01644
[2]	valid_0's binary_logloss: 0.0157626
[3]	valid_0's binary_logloss: 0.015107
[4]	valid_0's binary_logloss: 0.0144581
[5]	valid_0's binary_logloss: 0.0138523
[6]	valid_0's binary_logloss: 0.0133068
[7]	valid_0's binary_logloss: 0.0127075
[8]	valid_0's binary_logloss: 0.0121654
[9]	valid_0's binary_logloss: 0.0116388
[10]	valid_0's binary_logloss: 0.011159
[11]	valid_0's binary_logloss: 0.0106586
[12]	valid_0's binary_logloss: 0.0102313
[13]	valid_0's binary_logloss: 0.00979187
[14]	valid_0's binary_logloss: 0.00935975
[15]	valid_0's binary_logloss: 0.00899604
[16]	valid_0's binary_logloss: 0.00861853
[17]	valid_0's binary_logloss: 0.00827344
[18]	valid_0's binary_logloss: 0.00791892
[19]	valid_0's binary_logloss: 0.00758664
[20]	valid_0's binary_logloss: 0.00728677
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.00697451
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.00669181
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.00640749
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.00613741
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.00589877
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.0056646
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.00545502
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.00528847
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.00509859
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.00491028
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.00471609
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.00455624
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.00440883
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.00425274
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.00411308
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.00397833
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.00385013
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.00372062
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.00360046
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.0034929
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.00336287
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.00323308
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.00312324
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.00300264
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.00291051
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.00282765
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.0027431
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.00265988
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.00256542
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.00251155
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.00244954
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.00237296
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.0023115
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.00225064
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.00219681
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.00213266
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.00206064
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.00201265
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.00194476
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.00189418
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.00184823
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.00179309
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.00173739
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.00168407
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.0016295
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.00160196
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.00157764
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.00155565
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.00152371
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.0015051
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.00148583
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.00144741
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.00143105
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.00141634
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.00140548
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.00138625
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.00136574
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.00134499
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.00132914
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.00132166
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.00130295
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.00128559
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.00127286
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.00125783
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.0012444
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.0012382
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.00123429
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.00123194
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.00122871
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.00122351
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.00122364
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.00122465
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.00122036
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.00121787
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.00122099
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.00122279
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.00122094
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.00121075
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.00121057
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.00121956
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.00120316
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.00120318
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.00120446
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.00120946
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.00121272
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.00120358
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.00121036
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.0012176
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.00122601
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.00123358
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.00123177
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 0.00123655
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 0.00124393
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 0.00124298
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 0.00124371
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[116]	valid_0's binary_logloss: 0.001253
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[117]	valid_0's binary_logloss: 0.00126234
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[118]	valid_0's binary_logloss: 0.00126243
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[119]	valid_0's binary_logloss: 0.00126031
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[120]	valid_0's binary_logloss: 0.00125603
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[121]	valid_0's binary_logloss: 0.00124044
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[122]	valid_0's binary_logloss: 0.00122359
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[123]	valid_0's binary_logloss: 0.00121578
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[124]	valid_0's binary_logloss: 0.00120121
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[125]	valid_0's binary_logloss: 0.00119966
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[126]	valid_0's binary_logloss: 0.00119676
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[127]	valid_0's binary_logloss: 0.00119743
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[128]	valid_0's binary_logloss: 0.00119524
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[129]	valid_0's binary_logloss: 0.001189
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[130]	valid_0's binary_logloss: 0.001188
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[131]	valid_0's binary_logloss: 0.00118924
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[132]	valid_0's binary_logloss: 0.00119486
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[133]	valid_0's binary_logloss: 0.00120279
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[134]	valid_0's binary_logloss: 0.00120239
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[135]	valid_0's binary_logloss: 0.00121185
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[136]	valid_0's binary_logloss: 0.00121566
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[137]	valid_0's binary_logloss: 0.00121324
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[138]	valid_0's binary_logloss: 0.00120991
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[139]	valid_0's binary_logloss: 0.0012117
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[140]	valid_0's binary_logloss: 0.00120573
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[141]	valid_0's binary_logloss: 0.00120408
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[142]	valid_0's binary_logloss: 0.00121296
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[143]	valid_0's binary_logloss: 0.00121563
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[144]	valid_0's binary_logloss: 0.00121798
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[145]	valid_0's binary_logloss: 0.00122361
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[146]	valid_0's binary_logloss: 0.00123246
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[147]	valid_0's binary_logloss: 0.0012303
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[148]	valid_0's binary_logloss: 0.00123142
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[149]	valid_0's binary_logloss: 0.00123302
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[150]	valid_0's binary_logloss: 0.00123025
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[151]	valid_0's binary_logloss: 0.0012264
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[152]	valid_0's binary_logloss: 0.00121545
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[153]	valid_0's binary_logloss: 0.00122178
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[154]	valid_0's binary_logloss: 0.00122645
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[155]	valid_0's binary_logloss: 0.00123464
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[156]	valid_0's binary_logloss: 0.0012344
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[157]	valid_0's binary_logloss: 0.0012343
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[158]	valid_0's binary_logloss: 0.00123428
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[159]	valid_0's binary_logloss: 0.00122968
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[160]	valid_0's binary_logloss: 0.00123167

Trening klas:  43%|████▎     | 214/500 [26:53<33:05,  6.94s/klasa, klasa=class_214, F1_klasy=0.0000, F1_macro=0.7390, drzewa=130]




Trening klas:  43%|████▎     | 215/500 [26:53<31:56,  6.72s/klasa, klasa=class_214, F1_klasy=0.0000, F1_macro=0.7390, drzewa=130]

[1]	valid_0's binary_logloss: 0.033341
[2]	valid_0's binary_logloss: 0.0326153
[3]	valid_0's binary_logloss: 0.0317837
[4]	valid_0's binary_logloss: 0.0313694
[5]	valid_0's binary_logloss: 0.0310028
[6]	valid_0's binary_logloss: 0.0305129
[7]	valid_0's binary_logloss: 0.0300378
[8]	valid_0's binary_logloss: 0.0294677
[9]	valid_0's binary_logloss: 0.0288285
[10]	valid_0's binary_logloss: 0.0284532
[11]	valid_0's binary_logloss: 0.0279639
[12]	valid_0's binary_logloss: 0.0274797
[13]	valid_0's binary_logloss: 0.027087
[14]	valid_0's binary_logloss: 0.0268136
[15]	valid_0's binary_logloss: 0.0265583
[16]	valid_0's binary_logloss: 0.0263079
[17]	valid_0's binary_logloss: 0.0260358
[18]	valid_0's binary_logloss: 0.0257502
[19]	valid_0's binary_logloss: 0.0255748
[20]	valid_0's binary_logloss: 0.0253878
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0251496
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0248494
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.0245593
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0242912
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.0240707
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.0239159
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.0237999
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.0236683
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.0234653
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.0232095
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.0230801
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.0228556
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.0227931
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.0226677
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.0226613
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.0225524
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.0224357
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.0223396
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.0222721
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.0221471
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.0220057
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.0218933
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.0217748
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.0216969
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.0215993
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.0215777
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.0216061
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.0215893
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.0215327
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.0215901
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.0214852
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.0214052
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.0213547
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.0213612
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.0213266
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.0212432
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.021313
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.0212794
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.0212953
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.0211687
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.0210508
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.0210354
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.0210338
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.0209568
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.0209394
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.020972
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.0211023
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.0211914
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.0212185
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.0213108
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.0213339
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.0213993
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.021358
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.0213944
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.021427
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.0213775
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.0214296
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.0214832
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.0215575
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.0215665
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.0215785
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.0215923
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.0216527
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.0216709
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.0217518
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.0218242
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.0218452
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.0218867
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.0219375
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.0219484
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.0220472
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

Trening klas:  43%|████▎     | 215/500 [26:57<31:56,  6.72s/klasa, klasa=class_215, F1_klasy=0.5432, F1_macro=0.7381, drzewa=65]




Trening klas:  43%|████▎     | 216/500 [26:57<28:54,  6.11s/klasa, klasa=class_215, F1_klasy=0.5432, F1_macro=0.7381, drzewa=65]

[92]	valid_0's binary_logloss: 0.0221138
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.0221256
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.0221924
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.0222949
[1]	valid_0's binary_logloss: 0.146164
[2]	valid_0's binary_logloss: 0.142649
[3]	valid_0's binary_logloss: 0.138574
[4]	valid_0's binary_logloss: 0.134531
[5]	valid_0's binary_logloss: 0.130925
[6]	valid_0's binary_logloss: 0.127889
[7]	valid_0's binary_logloss: 0.125523
[8]	valid_0's binary_logloss: 0.123294
[9]	valid_0's binary_logloss: 0.121127
[10]	valid_0's binary_logloss: 0.119089
[11]	valid_0's binary_logloss: 0.117145
[12]	valid_0's binary_logloss: 0.115498
[13]	valid_0's binary_logloss: 0.113837
[14]	valid_0's binary_logloss: 0.111976
[15]	valid_0's binary_logloss: 0.110769
[16]	valid_0's binary_logloss: 0.109336
[17]	valid_0's binary_logloss: 0.107904
[18]	valid_0's binary_logloss: 0.106905
[19]	valid_0's binary_logloss: 0.106154
[20]	valid_0's binary_logloss: 0.10495
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.103904
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.102813
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.102049
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.101316
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.100717
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.100232
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.0996624
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.0991578
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.098784
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.098431
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.0978139
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.0975215
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.0970112
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.0964431
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.0962252
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.0961799
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.0961058
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.0957754
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.0953373
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.095123
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.0950097
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.0948283
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.0943837
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.0938284
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.0935348
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.093108
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.0927125
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.0925135
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.0922856
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.0919993
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.0918178
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.0916554
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.091606
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.0913467
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.0911658
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.0910176
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.0906794
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.0904909
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.0902403
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.0898445
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.089679
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.0897343
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.0893908
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.0893887
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.0895575
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.0895128
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.0893612
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.0892509
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.0892018
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.0891396
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.0891582
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.0893604
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.0894466
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.0895187
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.0895289
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.0895486
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.0896741
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.0897846
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.0899886
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.0900578
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.0901484
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.0903673
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.0904012
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.0905807
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.0907689
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.0908613
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.0909201
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.0910333
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.0909454
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.091108
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.0913054
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.0914767
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.0914086
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.0915333
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.0917626
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

Trening klas:  43%|████▎     | 216/500 [27:02<28:54,  6.11s/klasa, klasa=class_216, F1_klasy=0.5312, F1_macro=0.7372, drzewa=70]




Trening klas:  43%|████▎     | 217/500 [27:02<27:19,  5.79s/klasa, klasa=class_216, F1_klasy=0.5312, F1_macro=0.7372, drzewa=70]

[96]	valid_0's binary_logloss: 0.0918909
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.0920454
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.0920313
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.0919846
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.0920164
[1]	valid_0's binary_logloss: 0.0297879
[2]	valid_0's binary_logloss: 0.028929
[3]	valid_0's binary_logloss: 0.0282072
[4]	valid_0's binary_logloss: 0.027531
[5]	valid_0's binary_logloss: 0.026948
[6]	valid_0's binary_logloss: 0.0264447
[7]	valid_0's binary_logloss: 0.0258528
[8]	valid_0's binary_logloss: 0.0253604
[9]	valid_0's binary_logloss: 0.0248205
[10]	valid_0's binary_logloss: 0.0243087
[11]	valid_0's binary_logloss: 0.0236834
[12]	valid_0's binary_logloss: 0.0233192
[13]	valid_0's binary_logloss: 0.022788
[14]	valid_0's binary_logloss: 0.0224344
[15]	valid_0's binary_logloss: 0.0220447
[16]	valid_0's binary_logloss: 0.0216378
[17]	valid_0's binary_logloss: 0.0212695
[18]	valid_0's binary_logloss: 0.0209231
[19]	valid_0's binary_logloss: 0.020543
[20]	valid_0's binary_logloss: 0.0202678
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0200325
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0198194
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.0196209
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0194589
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.0192736
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.0190966
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.018881
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.0186849
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.0185297
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.0183867
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.0182632
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.0181294
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.0180147
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.0179436
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.0178726
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.0177297
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.0176195
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.0175264
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.017435
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.0174071
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.0174033
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.0173953
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.0173666
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.0173433
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.0173323
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.0172836
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.017258
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.017252
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.0172404
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.0172265
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.0172454
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.017296
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.0173081
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.0173423
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.0173457
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.0173299
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.0172429
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.0172344
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.0172335
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.0172486
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.0171952
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.0171835
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.0171857
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.017197
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.0172708
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.017276
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.0171933
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.0171832
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.0171535
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.0171794
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.0171879
[72]	valid_0's binary_logloss: 0.0172511
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.0172549
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.0172835
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.017338
[76]	valid_0's binary_logloss: 0.0173337
[77]	valid_0's binary_logloss: 0.0173272
[78]	valid_0's binary_logloss: 0.0174089
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.0174541
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.0174769
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.0174962
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.0174569
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.0174365
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.0175021
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.017524
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.0175431
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.0175707
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.0175562
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.017586
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.0176131
[91]	valid_0's binary_logloss: 0.017703
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.0176696
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.0177215
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.0177204
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.0177495
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.0177557
[97]	valid_0's binary_logloss: 0.0178026
[98]	valid_0's binary_logloss: 0.0178326
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

Trening klas:  43%|████▎     | 217/500 [27:09<27:19,  5.79s/klasa, klasa=class_217, F1_klasy=0.6364, F1_macro=0.7367, drzewa=69]




Trening klas:  44%|████▎     | 218/500 [27:09<27:37,  5.88s/klasa, klasa=class_217, F1_klasy=0.6364, F1_macro=0.7367, drzewa=69]

[99]	valid_0's binary_logloss: 0.0179067
[1]	valid_0's binary_logloss: 0.0365227
[2]	valid_0's binary_logloss: 0.0358697
[3]	valid_0's binary_logloss: 0.0350818
[4]	valid_0's binary_logloss: 0.0346919
[5]	valid_0's binary_logloss: 0.0343972
[6]	valid_0's binary_logloss: 0.0342127
[7]	valid_0's binary_logloss: 0.0339473
[8]	valid_0's binary_logloss: 0.0336593
[9]	valid_0's binary_logloss: 0.033561
[10]	valid_0's binary_logloss: 0.0333039
[11]	valid_0's binary_logloss: 0.0332136
[12]	valid_0's binary_logloss: 0.0331172
[13]	valid_0's binary_logloss: 0.0330078
[14]	valid_0's binary_logloss: 0.0328073
[15]	valid_0's binary_logloss: 0.0327209
[16]	valid_0's binary_logloss: 0.0325807
[17]	valid_0's binary_logloss: 0.0325534
[18]	valid_0's binary_logloss: 0.032616
[19]	valid_0's binary_logloss: 0.032557
[20]	valid_0's binary_logloss: 0.0325662
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0323216
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0321342
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.032179
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0320824
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.0319044
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.0318608
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.0315722
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.0313786
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.0309558
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.0305106
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.030402
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.0303913
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.0300568
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.0297946
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.0295255
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.0296939
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.0293407
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.0290474
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.0288305
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.028694
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.0287288
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.0288834
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.0287028
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.0285266
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.0285231
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.0282815
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.0283939
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.0280128
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.0279058
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.0277431
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.027387
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.0273334
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.0272538
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.0271105
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.0269198
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.0267045
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.0264964
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.0263526
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.0262429
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.0262036
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.026312
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.0262913
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.0262099
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.0260873
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.0261077
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.0260074
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.0259488
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.0258288
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.0259265
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.0259304
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.0260595
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.026086
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.0260578
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.0260427
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.0260221
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.0259646
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.0259362
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.0258438
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.0259384
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.0259381
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.0259004
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.0260176
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.0258934
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.0258008
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.0257663
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.0256907
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.0255489
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.0255701
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.0255296
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.025513
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.0253587
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.025255
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.025258
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.0252478
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.0252152
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.025089
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.02493
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.0248181
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.0247303
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.0246599
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.024747
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.0248161
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.024784
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.0248255
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.0247174
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.02472
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.0246297
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.0246026
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.0245824
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.0246168
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.0246339
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 0.0245814
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 0.0245688
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 0.0245681
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 0.024574
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[116]	valid_0's binary_logloss: 0.0246868
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[117]	valid_0's binary_logloss: 0.0248078
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[118]	valid_0's binary_logloss: 0.0249286
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[119]	valid_0's binary_logloss: 0.0250826
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[120]	valid_0's binary_logloss: 0.0252635
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[121]	valid_0's binary_logloss: 0.025242
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[122]	valid_0's binary_logloss: 0.0251251
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[123]	valid_0's binary_logloss: 0.0250119
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[124]	valid_0's binary_logloss: 0.0250085
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[125]	valid_0's binary_logloss: 0.0249554
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[126]	valid_0's binary_logloss: 0.0249081
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[127]	valid_0's binary_logloss: 0.0249072
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[128]	valid_0's binary_logloss: 0.024931
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[129]	valid_0's binary_logloss: 0.0250505
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[130]	valid_0's binary_logloss: 0.0250527
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[131]	valid_0's binary_logloss: 0.0251129
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[132]	valid_0's binary_logloss: 0.0251433
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[133]	valid_0's binary_logloss: 0.025163
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[134]	valid_0's binary_logloss: 0.0252201
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[135]	valid_0's binary_logloss: 0.0252241
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[136]	valid_0's binary_logloss: 0.0253059
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[137]	valid_0's binary_logloss: 0.0252849
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[138]	valid_0's binary_logloss: 0.0252455
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[139]	valid_0's binary_logloss: 0.0253533
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[140]	valid_0's binary_logloss: 0.0254085
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[141]	valid_0's binary_logloss: 0.0254183

Trening klas:  44%|████▎     | 218/500 [27:14<27:37,  5.88s/klasa, klasa=class_218, F1_klasy=0.8194, F1_macro=0.7371, drzewa=114]




Trening klas:  44%|████▍     | 219/500 [27:14<27:12,  5.81s/klasa, klasa=class_218, F1_klasy=0.8194, F1_macro=0.7371, drzewa=114]

[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[142]	valid_0's binary_logloss: 0.025459
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[143]	valid_0's binary_logloss: 0.0254813
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[144]	valid_0's binary_logloss: 0.0255045
[1]	valid_0's binary_logloss: 0.110359
[2]	valid_0's binary_logloss: 0.109447
[3]	valid_0's binary_logloss: 0.108768
[4]	valid_0's binary_logloss: 0.108066
[5]	valid_0's binary_logloss: 0.107126
[6]	valid_0's binary_logloss: 0.106065
[7]	valid_0's binary_logloss: 0.105854
[8]	valid_0's binary_logloss: 0.105201
[9]	valid_0's binary_logloss: 0.104081
[10]	valid_0's binary_logloss: 0.103165
[11]	valid_0's binary_logloss: 0.103961
[12]	valid_0's binary_logloss: 0.103365
[13]	valid_0's binary_logloss: 0.102685
[14]	valid_0's binary_logloss: 0.102077
[15]	valid_0's binary_logloss: 0.101821
[16]	valid_0's binary_logloss: 0.100972
[17]	valid_0's binary_logloss: 0.100666
[18]	valid_0's binary_logloss: 0.0999623
[19]	valid_0's binary_logloss: 0.0992566
[20]	valid_0's binary_logloss: 0.0985191
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0979603
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0971859
[23]	valid_0's binary_logloss: 0.0969704
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0965533
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.0960562
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.0958755
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.0956846
[28]	valid_0's binary_logloss: 0.0953126
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.0951329
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.0950188
[31]	valid_0's binary_logloss: 0.0944527
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.0943919
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.0941535
[34]	valid_0's binary_logloss: 0.0940079
[35]	valid_0's binary_logloss: 0.0937786
[36]	valid_0's binary_logloss: 0.0938331
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.0935762
[38]	valid_0's binary_logloss: 0.0934229
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.0931801
[40]	valid_0's binary_logloss: 0.0930528
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.0928311
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.0927076
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.0927462
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.0926344
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.0925438
[46]	valid_0's binary_logloss: 0.0924621
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.0920007
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.0918385
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.0915462
[50]	valid_0's binary_logloss: 0.0914245
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.0914647
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.0911584
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.0911547
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.0913315
[55]	valid_0's binary_logloss: 0.0914468
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.0914274
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.0913649
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.0914189
[59]	valid_0's binary_logloss: 0.0914152
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.0915364
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.0915409
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.091409
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.0913687
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.0913731
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.0916228
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.0916301
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.0918581
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.091934
[69]	valid_0's binary_logloss: 0.0920173
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.092057
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.0919932
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.0919254
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.0919059
[74]	valid_0's binary_logloss: 0.0918423
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.0917604
[76]	valid_0's binary_logloss: 0.0918839
[77]	valid_0's binary_logloss: 0.092141
[78]	valid_0's binary_logloss: 0.0922839
[79]	valid_0's binary_logloss: 0.0927214
[80]	valid_0's binary_logloss: 0.0930108
[81]	valid_0's binary_logloss: 0.0933455
[82]	valid_0's binary_logloss: 0.0935965
[83]	valid_0's binary_logloss: 0.0939957

Trening klas:  44%|████▍     | 219/500 [27:20<27:12,  5.81s/klasa, klasa=class_219, F1_klasy=0.3917, F1_macro=0.7355, drzewa=53]




Trening klas:  44%|████▍     | 220/500 [27:20<26:45,  5.73s/klasa, klasa=class_219, F1_klasy=0.3917, F1_macro=0.7355, drzewa=53]

[1]	valid_0's binary_logloss: 0.0264461
[2]	valid_0's binary_logloss: 0.0253349
[3]	valid_0's binary_logloss: 0.0243711
[4]	valid_0's binary_logloss: 0.023637
[5]	valid_0's binary_logloss: 0.0228014
[6]	valid_0's binary_logloss: 0.0221107
[7]	valid_0's binary_logloss: 0.0213622
[8]	valid_0's binary_logloss: 0.0206245
[9]	valid_0's binary_logloss: 0.0199294
[10]	valid_0's binary_logloss: 0.0193804
[11]	valid_0's binary_logloss: 0.0187717
[12]	valid_0's binary_logloss: 0.0182695
[13]	valid_0's binary_logloss: 0.0177676
[14]	valid_0's binary_logloss: 0.0173938
[15]	valid_0's binary_logloss: 0.0169372
[16]	valid_0's binary_logloss: 0.0164931
[17]	valid_0's binary_logloss: 0.0160755
[18]	valid_0's binary_logloss: 0.015686
[19]	valid_0's binary_logloss: 0.0152734
[20]	valid_0's binary_logloss: 0.0150109
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0147832
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0145564
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.014322
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.014103
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.0138912
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.0137277
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.0135183
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.0133629
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.0131998
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.0130703
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.0128771
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.0126969
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.0126368
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.0125945
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.0125181
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.0124081
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.012254
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.0121015
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.0119322
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.0118288
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.0116801
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.0115894
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.011461
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.0114613
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.0114391
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.0113613
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.011277
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.0111888
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.0111604
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.0111119
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.0110442
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.0109555
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.0109595
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.0109169
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.0108564
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.0108644
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.0108241
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.0108399
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.0107894
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.0106751
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.0106295
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.0105835
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.0105214
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.0104187
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.0104354
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.0104801
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.01046
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.0104533
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.0104654
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.0103707
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.0103759
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.0103869
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.0103537
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.0103355
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.0103787
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.0103869
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.010504
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.0105376
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.0105135
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.0105092
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.0105547
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.0105229
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.01056
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.0105063
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.0105288
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.0105682
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.0105767
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.0105669
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.0106057
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.0106383
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.0105938
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.0106003
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.0105658
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.0105689
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.0105615
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.0105541
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.0105696
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.0106149
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.0106489
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.0106002
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.010666
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

Trening klas:  44%|████▍     | 220/500 [27:24<26:45,  5.73s/klasa, klasa=class_220, F1_klasy=0.7551, F1_macro=0.7356, drzewa=74]




Trening klas:  44%|████▍     | 221/500 [27:24<25:01,  5.38s/klasa, klasa=class_220, F1_klasy=0.7551, F1_macro=0.7356, drzewa=74]

[102]	valid_0's binary_logloss: 0.010729
[103]	valid_0's binary_logloss: 0.0107627
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.0107717
[1]	valid_0's binary_logloss: 0.0246032
[2]	valid_0's binary_logloss: 0.0233768
[3]	valid_0's binary_logloss: 0.0222617
[4]	valid_0's binary_logloss: 0.0212308
[5]	valid_0's binary_logloss: 0.0202615
[6]	valid_0's binary_logloss: 0.0194053
[7]	valid_0's binary_logloss: 0.0185229
[8]	valid_0's binary_logloss: 0.0177594
[9]	valid_0's binary_logloss: 0.0170549
[10]	valid_0's binary_logloss: 0.0165136
[11]	valid_0's binary_logloss: 0.0159802
[12]	valid_0's binary_logloss: 0.0153733
[13]	valid_0's binary_logloss: 0.0148064
[14]	valid_0's binary_logloss: 0.0142489
[15]	valid_0's binary_logloss: 0.0137335
[16]	valid_0's binary_logloss: 0.0131911
[17]	valid_0's binary_logloss: 0.0126114
[18]	valid_0's binary_logloss: 0.0120769
[19]	valid_0's binary_logloss: 0.0115596
[20]	valid_0's binary_logloss: 0.0110862
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0106278
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0101932
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.00979327
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0094077
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.00908862
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.00887489
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.00857018
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.00831837
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.00811964
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.00782497
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.00757778
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.00728919
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.00705477
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.00678027
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.00658752
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.00636842
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.00622396
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.00605436
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.00590216
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.00571921
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.00556701
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.00542697
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.00525644
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.00513903
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.0050386
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.00488473
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.00475238
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.00459995
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.00445405
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.00434497
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.004235
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.00413126
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.0040537
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.00391299
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.00384396
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.00370185
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.00360361
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.00349793
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.00340604
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.0033598
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.00326983
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.00321796
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.0031703
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.00313305
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.00302372
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.00297208
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.0028829
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.00285011
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.00275726
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.00268463
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.00264072
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.00257505
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.00251301
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.0024722
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.00243492
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.00239477
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.00236583
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.00233648
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.00232313
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.00230996
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.00230163
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.00229769
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.00230726
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.00227458
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.0022887
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.00228098
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.00228001
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.002258
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.00221096
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.00223347
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.00221436
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.00214749
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.00209727
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.00208225
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.00205542
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.00207422
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.00209173
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.00211124
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.00213256
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.00215318
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.0021261
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.00210967
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.00210705
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.0021054
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.00207164
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.00206715
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.00207419
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.00209144
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.00208891
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.00208593
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.0020531
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 0.00202178
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 0.00199066
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 0.00197277
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 0.00196571
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[116]	valid_0's binary_logloss: 0.00192596
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[117]	valid_0's binary_logloss: 0.00192408
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[118]	valid_0's binary_logloss: 0.00189835
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[119]	valid_0's binary_logloss: 0.00189035
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[120]	valid_0's binary_logloss: 0.00187369
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[121]	valid_0's binary_logloss: 0.00189194
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[122]	valid_0's binary_logloss: 0.00188419
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[123]	valid_0's binary_logloss: 0.00186442
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[124]	valid_0's binary_logloss: 0.00187435
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[125]	valid_0's binary_logloss: 0.0018763
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[126]	valid_0's binary_logloss: 0.00185394
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[127]	valid_0's binary_logloss: 0.00186007
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[128]	valid_0's binary_logloss: 0.00186819
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[129]	valid_0's binary_logloss: 0.00187862
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[130]	valid_0's binary_logloss: 0.00187641
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[131]	valid_0's binary_logloss: 0.00187075
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[132]	valid_0's binary_logloss: 0.00186412
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[133]	valid_0's binary_logloss: 0.00182704
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[134]	valid_0's binary_logloss: 0.00182083
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[135]	valid_0's binary_logloss: 0.00181258
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[136]	valid_0's binary_logloss: 0.0018042
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[137]	valid_0's binary_logloss: 0.00178759
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[138]	valid_0's binary_logloss: 0.0017798
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[139]	valid_0's binary_logloss: 0.00174813
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[140]	valid_0's binary_logloss: 0.00171556
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[141]	valid_0's binary_logloss: 0.00169822
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[142]	valid_0's binary_logloss: 0.00167747
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[143]	valid_0's binary_logloss: 0.00167414
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[144]	valid_0's binary_logloss: 0.0016538
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[145]	valid_0's binary_logloss: 0.0016434
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[146]	valid_0's binary_logloss: 0.00160887
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[147]	valid_0's binary_logloss: 0.00159152
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[148]	valid_0's binary_logloss: 0.00159141
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[149]	valid_0's binary_logloss: 0.00158644
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[150]	valid_0's binary_logloss: 0.00159198
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[151]	valid_0's binary_logloss: 0.00157232
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[152]	valid_0's binary_logloss: 0.00158483
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[153]	valid_0's binary_logloss: 0.00156873
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[154]	valid_0's binary_logloss: 0.00156295
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[155]	valid_0's binary_logloss: 0.0015567
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[156]	valid_0's binary_logloss: 0.00157841
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[157]	valid_0's binary_logloss: 0.00156723
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[158]	valid_0's binary_logloss: 0.00155964
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[159]	valid_0's binary_logloss: 0.00156207
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[160]	valid_0's binary_logloss: 0.00154742
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[161]	valid_0's binary_logloss: 0.00156894
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[162]	valid_0's binary_logloss: 0.00157284
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[163]	valid_0's binary_logloss: 0.00159063
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[164]	valid_0's binary_logloss: 0.00161513
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[165]	valid_0's binary_logloss: 0.00159756
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[166]	valid_0's binary_logloss: 0.00159557
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[167]	valid_0's binary_logloss: 0.00160951
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[168]	valid_0's binary_logloss: 0.00163375
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[169]	valid_0's binary_logloss: 0.00164716
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[170]	valid_0's binary_logloss: 0.00166461
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[171]	valid_0's binary_logloss: 0.00166236
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[172]	valid_0's binary_logloss: 0.00165836
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[173]	valid_0's binary_logloss: 0.00164626
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[174]	valid_0's binary_logloss: 0.00164214
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[175]	valid_0's binary_logloss: 0.0016286
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[176]	valid_0's binary_logloss: 0.00163166
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[177]	valid_0's binary_logloss: 0.00163835
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[178]	valid_0's binary_logloss: 0.00165231
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[179]	valid_0's binary_logloss: 0.00165402
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[180]	valid_0's binary_logloss: 0.0016381
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[181]	valid_0's binary_logloss: 0.00159327
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

Trening klas:  44%|████▍     | 221/500 [27:29<25:01,  5.38s/klasa, klasa=class_221, F1_klasy=0.9333, F1_macro=0.7365, drzewa=160]




Trening klas:  44%|████▍     | 222/500 [27:29<24:11,  5.22s/klasa, klasa=class_221, F1_klasy=0.9333, F1_macro=0.7365, drzewa=160]

[189]	valid_0's binary_logloss: 0.00155722
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[190]	valid_0's binary_logloss: 0.00154832
[1]	valid_0's binary_logloss: 0.051804
[2]	valid_0's binary_logloss: 0.0511203
[3]	valid_0's binary_logloss: 0.0503636
[4]	valid_0's binary_logloss: 0.0494798
[5]	valid_0's binary_logloss: 0.0490392
[6]	valid_0's binary_logloss: 0.0498116
[7]	valid_0's binary_logloss: 0.0494689
[8]	valid_0's binary_logloss: 0.0492738
[9]	valid_0's binary_logloss: 0.048591
[10]	valid_0's binary_logloss: 0.0483805
[11]	valid_0's binary_logloss: 0.0479791
[12]	valid_0's binary_logloss: 0.0476319
[13]	valid_0's binary_logloss: 0.0474649
[14]	valid_0's binary_logloss: 0.0471672
[15]	valid_0's binary_logloss: 0.0469132
[16]	valid_0's binary_logloss: 0.0466005
[17]	valid_0's binary_logloss: 0.0463313
[18]	valid_0's binary_logloss: 0.0461364
[19]	valid_0's binary_logloss: 0.0461085
[20]	valid_0's binary_logloss: 0.045956
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0457366
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0455465
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.045441
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0449394
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.0448172
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.0446759
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.0446003
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.0443213
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.0441005
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.0438218
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.043525
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.0433968
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.0433942
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.0433574
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.0432701
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.0432051
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.0433054
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.0433281
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.0433194
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.0434542
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.0434875
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.04346
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.0432756
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.043289
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.0430716
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.0431306
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.0430347
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.042991
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.0429774
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.0430267
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.042798
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.0428434
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.0428143
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.0430156
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.0430999
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.0432357
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.0432919
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.0432404
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.0434138
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.0434168
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.0432371
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.0433036
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.0429822
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.0430881
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.0430669
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.0432178
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.0432983
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.0433388
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.0434583
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.043341
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.0431715
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.0431471
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.043197
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.0432978
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.0430436
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.0431576
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.0431249
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.0431226
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

Trening klas:  44%|████▍     | 222/500 [27:33<24:11,  5.22s/klasa, klasa=class_222, F1_klasy=0.4505, F1_macro=0.7352, drzewa=51]




Trening klas:  45%|████▍     | 223/500 [27:33<22:28,  4.87s/klasa, klasa=class_222, F1_klasy=0.4505, F1_macro=0.7352, drzewa=51]

[79]	valid_0's binary_logloss: 0.0431655
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.0430543
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.0429718
[1]	valid_0's binary_logloss: 0.420302
[2]	valid_0's binary_logloss: 0.331116
[3]	valid_0's binary_logloss: 0.302725
[4]	valid_0's binary_logloss: 0.277888
[5]	valid_0's binary_logloss: 0.258578
[6]	valid_0's binary_logloss: 0.241139
[7]	valid_0's binary_logloss: 0.227807
[8]	valid_0's binary_logloss: 0.218486
[9]	valid_0's binary_logloss: 0.210869
[10]	valid_0's binary_logloss: 0.201382
[11]	valid_0's binary_logloss: 0.193525
[12]	valid_0's binary_logloss: 0.186535
[13]	valid_0's binary_logloss: 0.181331
[14]	valid_0's binary_logloss: 0.175392
[15]	valid_0's binary_logloss: 0.170967
[16]	valid_0's binary_logloss: 0.165141
[17]	valid_0's binary_logloss: 0.160368
[18]	valid_0's binary_logloss: 0.155935
[19]	valid_0's binary_logloss: 0.152044
[20]	valid_0's binary_logloss: 0.14829
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.145414
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.142713
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.140366
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.137514
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.134867
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.132494
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.130518
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.128513
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.126887
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.124948
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.12302
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.12119
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.119464
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.11808
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.117147
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.116125
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.115222
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.113779
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.11301
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.111883
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.110546
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.109341
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.108397
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.107205
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.106606
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.105702
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.105116
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.104533
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.103528
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.103095
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.102277
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.101637
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.100963
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.100409
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.0996207
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.0990201
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.0985865
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.0980984
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.0976691
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.0972487
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.0967492
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.0963855
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.0958552
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.0953965
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.0949494
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.0945542
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.0941364
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.094012
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.0936547
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.0931925
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.0927364
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.0923568
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.0920096
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.0919131
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.0915532
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.0913328
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.091265
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.0912297
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.0911687
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.0910247
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.0907368
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.0905291
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.0903759
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.090299
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.090263
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.0900269
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.0897789
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.0895843
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.089684
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.0895553
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.0895493
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.0894346
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.0892062
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.0891669
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.0889701
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.088869
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.0886466
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.0885172
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.0884586
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.088172
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.0880839
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.0880082
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.0879668
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.0880549
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.0881388
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.0880714
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.088085
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.0882126
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.0882483
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.0881435
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.0883117
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 0.0883702
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 0.0883182
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 0.0883857
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 0.0882566
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[116]	valid_0's binary_logloss: 0.0881905
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[117]	valid_0's binary_logloss: 0.0882143
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[118]	valid_0's binary_logloss: 0.0882695
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[119]	valid_0's binary_logloss: 0.0881976
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[120]	valid_0's binary_logloss: 0.0881403
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[121]	valid_0's binary_logloss: 0.0881063
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[122]	valid_0's binary_logloss: 0.0880843
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[123]	valid_0's binary_logloss: 0.0881248
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[124]	valid_0's binary_logloss: 0.088146
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[125]	valid_0's binary_logloss: 0.0881184
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

Trening klas:  45%|████▍     | 223/500 [27:38<22:28,  4.87s/klasa, klasa=class_223, F1_klasy=0.7152, F1_macro=0.7351, drzewa=103]




Trening klas:  45%|████▍     | 224/500 [27:38<21:52,  4.75s/klasa, klasa=class_223, F1_klasy=0.7152, F1_macro=0.7351, drzewa=103]

[126]	valid_0's binary_logloss: 0.0880954
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[127]	valid_0's binary_logloss: 0.0880054
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[128]	valid_0's binary_logloss: 0.0880339
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[129]	valid_0's binary_logloss: 0.0880006
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[130]	valid_0's binary_logloss: 0.08812
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[131]	valid_0's binary_logloss: 0.0880967
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[132]	valid_0's binary_logloss: 0.0882477
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[133]	valid_0's binary_logloss: 0.0882433
[1]	valid_0's binary_logloss: 0.0327061
[2]	valid_0's binary_logloss: 0.0321692
[3]	valid_0's binary_logloss: 0.0313234
[4]	valid_0's binary_logloss: 0.0306422
[5]	valid_0's binary_logloss: 0.0299126
[6]	valid_0's binary_logloss: 0.0302698
[7]	valid_0's binary_logloss: 0.0306024
[8]	valid_0's binary_logloss: 0.030157
[9]	valid_0's binary_logloss: 0.0296802
[10]	valid_0's binary_logloss: 0.0297778
[11]	valid_0's binary_logloss: 0.0291804
[12]	valid_0's binary_logloss: 0.0287599
[13]	valid_0's binary_logloss: 0.0282237
[14]	valid_0's binary_logloss: 0.0277257
[15]	valid_0's binary_logloss: 0.0271618
[16]	valid_0's binary_logloss: 0.0267653
[17]	valid_0's binary_logloss: 0.0261536
[18]	valid_0's binary_logloss: 0.0255557
[19]	valid_0's binary_logloss: 0.0254224
[20]	valid_0's binary_logloss: 0.0249575
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0245411
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0240534
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.0236117
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0234664
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.0230962
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.0227855
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.0225749
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.0223113
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.0219289
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.0216932
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.0214515
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.0214302
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.0212344
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.0209612
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.0205564
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.0202489
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.0200793
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.0199157
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.0196965
[40]	valid_0's binary_logloss: 0.0195184
[41]	valid_0's binary_logloss: 0.0191855
[42]	valid_0's binary_logloss: 0.019028
[43]	valid_0's binary_logloss: 0.0188355
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.0186591
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.0184915
[46]	valid_0's binary_logloss: 0.0182605
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.0181009
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.0179302
[49]	valid_0's binary_logloss: 0.0176946
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.0174315
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.0172157
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.0171028
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.0170069
[54]	valid_0's binary_logloss: 0.0169168
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.0167334
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.0165241
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.0163367
[58]	valid_0's binary_logloss: 0.0161286
[59]	valid_0's binary_logloss: 0.0160217
[60]	valid_0's binary_logloss: 0.0159087
[61]	valid_0's binary_logloss: 0.015784
[62]	valid_0's binary_logloss: 0.01573
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.0156011
[64]	valid_0's binary_logloss: 0.0154627
[65]	valid_0's binary_logloss: 0.015309
[66]	valid_0's binary_logloss: 0.0151841
[67]	valid_0's binary_logloss: 0.0150358
[68]	valid_0's binary_logloss: 0.0148975
[69]	valid_0's binary_logloss: 0.0148117
[70]	valid_0's binary_logloss: 0.0146869
[71]	valid_0's binary_logloss: 0.0145095
[72]	valid_0's binary_logloss: 0.0144285
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.0143735
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.0143392
[75]	valid_0's binary_logloss: 0.014284
[76]	valid_0's binary_logloss: 0.0142738
[77]	valid_0's binary_logloss: 0.0142649
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.0142228
[79]	valid_0's binary_logloss: 0.0141697
[80]	valid_0's binary_logloss: 0.0142305
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.0141189
[82]	valid_0's binary_logloss: 0.0140447
[83]	valid_0's binary_logloss: 0.0139741
[84]	valid_0's binary_logloss: 0.0139745
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.013945
[86]	valid_0's binary_logloss: 0.0139578
[87]	valid_0's binary_logloss: 0.0139151
[88]	valid_0's binary_logloss: 0.0139034
[89]	valid_0's binary_logloss: 0.0138866
[90]	valid_0's binary_logloss: 0.0138611
[91]	valid_0's binary_logloss: 0.0138275
[92]	valid_0's binary_logloss: 0.0138448
[93]	valid_0's binary_logloss: 0.0138327
[94]	valid_0's binary_logloss: 0.013827
[95]	valid_0's binary_logloss: 0.0138275
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.0137755
[97]	valid_0's binary_logloss: 0.0136569
[98]	valid_0's binary_logloss: 0.0135854
[99]	valid_0's binary_logloss: 0.0136
[100]	valid_0's binary_logloss: 0.0135842
[101]	valid_0's binary_logloss: 0.0135529
[102]	valid_0's binary_logloss: 0.0135744
[103]	valid_0's binary_logloss: 0.0136008
[104]	valid_0's binary_logloss: 0.0136268
[105]	valid_0's binary_logloss: 0.0136717
[106]	valid_0's binary_logloss: 0.0136802
[107]	valid_0's binary_logloss: 0.0136616
[108]	valid_0's binary_logloss: 0.0136769
[109]	valid_0's binary_logloss: 0.0137134
[110]	valid_0's binary_logloss: 0.0137262
[111]	valid_0's binary_logloss: 0.013788
[112]	valid_0's binary_logloss: 0.0138248
[113]	valid_0's binary_logloss: 0.0138139
[114]	valid_0's binary_logloss: 0.0138647
[115]	valid_0's binary_logloss: 0.0138803
[116]	valid_0's binary_logloss: 0.0138759
[117]	valid_0's binary_logloss: 0.0139144
[118]	valid_0's binary_logloss: 0.0139783
[119]	valid_0's binary_logloss: 0.0139578
[120]	valid_0's binary_logloss: 0.0140001
[121]	valid_0's binary_logloss: 0.0140199
[122]	valid_0's binary_logloss: 0.0140294
[123]	valid_0's binary_logloss: 0.0140473
[124]	valid_0's binary_logloss: 0.0140569
[125]	valid_0's binary_logloss: 0.0140532
[126]	valid_0's binary_logloss: 0.0140491
[127]	valid_0's binary_logloss: 0.0140639
[128]	valid_0's binary_logloss: 0.0140363
[129]	valid_0's binary_logloss: 0.0140022
[130]	valid_0's binary_logloss: 0.013948

Trening klas:  45%|████▍     | 224/500 [27:45<21:52,  4.75s/klasa, klasa=class_224, F1_klasy=0.5000, F1_macro=0.7341, drzewa=101]




Trening klas:  45%|████▌     | 225/500 [27:45<25:21,  5.53s/klasa, klasa=class_224, F1_klasy=0.5000, F1_macro=0.7341, drzewa=101]

[131]	valid_0's binary_logloss: 0.013909
[1]	valid_0's binary_logloss: 0.126147
[2]	valid_0's binary_logloss: 0.127401
[3]	valid_0's binary_logloss: 0.129698
[4]	valid_0's binary_logloss: 0.131454
[5]	valid_0's binary_logloss: 0.132232
[6]	valid_0's binary_logloss: 0.136826
[7]	valid_0's binary_logloss: 0.137534
[8]	valid_0's binary_logloss: 0.139059
[9]	valid_0's binary_logloss: 0.140418
[10]	valid_0's binary_logloss: 0.140967
[11]	valid_0's binary_logloss: 0.142178
[12]	valid_0's binary_logloss: 0.142451
[13]	valid_0's binary_logloss: 0.142915
[14]	valid_0's binary_logloss: 0.143128
[15]	valid_0's binary_logloss: 0.143965
[16]	valid_0's binary_logloss: 0.144252
[17]	valid_0's binary_logloss: 0.143808
[18]	valid_0's binary_logloss: 0.143125
[19]	valid_0's binary_logloss: 0.142509
[20]	valid_0's binary_logloss: 0.142137
[21]	valid_0's binary_logloss: 0.141694
[22]	valid_0's binary_logloss: 0.14051
[23]	valid_0's binary_logloss: 0.140749
[24]	valid_0's binary_logloss: 0.140034
[25]	valid_0's binary_logloss: 0.138719
[26]	valid_0's binary_logloss: 0.137595
[27]	valid_0's binary_logloss: 0.137262

[28]	valid_0's binary_logloss: 0.137167
[29]	valid_0's binary_logloss: 0.13672
[30]	valid_0's binary_logloss: 0.136575
[31]	valid_0's binary_logloss: 0.136042

Trening klas:  45%|████▌     | 225/500 [27:49<25:21,  5.53s/klasa, klasa=class_225, F1_klasy=0.0000, F1_macro=0.7308, drzewa=1]




Trening klas:  45%|████▌     | 226/500 [27:49<23:10,  5.07s/klasa, klasa=class_225, F1_klasy=0.0000, F1_macro=0.7308, drzewa=1]

[1]	valid_0's binary_logloss: 0.0452427
[2]	valid_0's binary_logloss: 0.0444356
[3]	valid_0's binary_logloss: 0.0438372
[4]	valid_0's binary_logloss: 0.0433899
[5]	valid_0's binary_logloss: 0.0429668
[6]	valid_0's binary_logloss: 0.042247
[7]	valid_0's binary_logloss: 0.0414431
[8]	valid_0's binary_logloss: 0.0404151
[9]	valid_0's binary_logloss: 0.0396672
[10]	valid_0's binary_logloss: 0.0390161
[11]	valid_0's binary_logloss: 0.038558
[12]	valid_0's binary_logloss: 0.0380806
[13]	valid_0's binary_logloss: 0.0378937
[14]	valid_0's binary_logloss: 0.0374727
[15]	valid_0's binary_logloss: 0.036912
[16]	valid_0's binary_logloss: 0.0368284
[17]	valid_0's binary_logloss: 0.0367091
[18]	valid_0's binary_logloss: 0.0366328
[19]	valid_0's binary_logloss: 0.0365212
[20]	valid_0's binary_logloss: 0.0365246
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0360893
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0358079
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.0356756
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0355157
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.0351628
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.0347212
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.0344683
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.03439
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.0341346
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.0340491
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.0339119
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.0337129
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.0335255
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.0333896
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.0334832
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.0336481
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.0337602
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.0336512
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.0336101
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.033658
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.0333057
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.0329078
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.0325251
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.0322833
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.0320806
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.0318121
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.0315751
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.0312707
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.0311114
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.0308257
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.0308776
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.0308387
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.0306524
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.0304833
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.0303929
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.0305434
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.0303694
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.0304886
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.0305892
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.0307363
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.0307512
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.0308186
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.0308104
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.0308744
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.0306704
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.030597
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.0305702
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.030499
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.0304404
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.0302186
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.0301735
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.030197
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.0300909
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.0299695
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.0297425
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.0298865
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.0298513
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.0298437
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.0297307
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.0296914
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.0296165
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.0295716
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.0295278
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.0293872
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.0291975
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.0290793
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.0291568
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.0290783
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.0290618
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.0290342
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.0288516
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.0287883
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.0286577
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.0284859
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.028303
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.0279391
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.0277924
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.02755
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.0274991
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.0274184
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.0274301
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.0273127
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.0273394
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.0273645
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.0273238
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.0271408
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.027068
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.0269731
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.0268234
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.0266854
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.0266035
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 0.0266024
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 0.0264042
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 0.026379
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 0.0263296
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[116]	valid_0's binary_logloss: 0.026108
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[117]	valid_0's binary_logloss: 0.02616
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[118]	valid_0's binary_logloss: 0.0262859
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[119]	valid_0's binary_logloss: 0.0263151
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[120]	valid_0's binary_logloss: 0.0264816
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[121]	valid_0's binary_logloss: 0.0265244
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[122]	valid_0's binary_logloss: 0.0266066
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[123]	valid_0's binary_logloss: 0.0265599
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[124]	valid_0's binary_logloss: 0.0265607
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[125]	valid_0's binary_logloss: 0.0265639
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[126]	valid_0's binary_logloss: 0.0265006
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[127]	valid_0's binary_logloss: 0.0264054
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[128]	valid_0's binary_logloss: 0.0263819
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[129]	valid_0's binary_logloss: 0.0262653
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[130]	valid_0's binary_logloss: 0.0262404
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[131]	valid_0's binary_logloss: 0.0263657
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[132]	valid_0's binary_logloss: 0.0264299
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[133]	valid_0's binary_logloss: 0.0264839
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[134]	valid_0's binary_logloss: 0.0265598
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[135]	valid_0's binary_logloss: 0.0266364
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[136]	valid_0's binary_logloss: 0.0267261
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[137]	valid_0's binary_logloss: 0.0267003
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[138]	valid_0's binary_logloss: 0.02675
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[139]	valid_0's binary_logloss: 0.0268492
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[140]	valid_0's binary_logloss: 0.0268449
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[141]	valid_0's binary_logloss: 0.0268786
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[142]	valid_0's binary_logloss: 0.0269072
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[143]	valid_0's binary_logloss: 0.0269994
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[144]	valid_0's binary_logloss: 0.0270609
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[145]	valid_0's binary_logloss: 0.0270942
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

Trening klas:  45%|████▌     | 226/500 [27:55<23:10,  5.07s/klasa, klasa=class_226, F1_klasy=0.7857, F1_macro=0.7311, drzewa=116]




Trening klas:  45%|████▌     | 227/500 [27:55<23:48,  5.23s/klasa, klasa=class_226, F1_klasy=0.7857, F1_macro=0.7311, drzewa=116]

[146]	valid_0's binary_logloss: 0.0271992
[1]	valid_0's binary_logloss: 0.0321883
[2]	valid_0's binary_logloss: 0.0312666
[3]	valid_0's binary_logloss: 0.0306183
[4]	valid_0's binary_logloss: 0.030045
[5]	valid_0's binary_logloss: 0.0293725
[6]	valid_0's binary_logloss: 0.0287923
[7]	valid_0's binary_logloss: 0.0281673
[8]	valid_0's binary_logloss: 0.0275549
[9]	valid_0's binary_logloss: 0.0270412
[10]	valid_0's binary_logloss: 0.0265255
[11]	valid_0's binary_logloss: 0.0261213
[12]	valid_0's binary_logloss: 0.0257405
[13]	valid_0's binary_logloss: 0.0253256
[14]	valid_0's binary_logloss: 0.0250162
[15]	valid_0's binary_logloss: 0.0245689
[16]	valid_0's binary_logloss: 0.0242243
[17]	valid_0's binary_logloss: 0.0238908
[18]	valid_0's binary_logloss: 0.023578
[19]	valid_0's binary_logloss: 0.0232361
[20]	valid_0's binary_logloss: 0.0229461
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0228161
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0226177
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.0224324
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0222409
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.0220309
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.0219091
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.0217536
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.0216638
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.0215504
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.0213918
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.0212722
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.0211467
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.0211124
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.021079
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.0210795
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.0210139
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.0209897
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.0209904
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.0209448
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.0208802
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.0208477
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.0206238
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.0205553
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.0204942
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.0204863
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.0203601
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.0203206
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.0201924
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.0200918
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.0200493
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.0200663
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.0200906
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.0201186
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.020165
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.0202141
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.0202235
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.020196
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.0202049
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.0201948
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.020288
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.0202052
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.020115
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.0200777
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.0201994
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.0202442
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.0202873
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.0203213
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.0203995
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.0204281
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.0204926
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.0204211
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.0204083
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.0201967
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.0202046
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.0202269
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.0202258
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.0202808
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.0202575
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.0201675
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

Trening klas:  45%|████▌     | 227/500 [27:59<23:48,  5.23s/klasa, klasa=class_227, F1_klasy=0.6393, F1_macro=0.7307, drzewa=50]




Trening klas:  46%|████▌     | 228/500 [27:59<22:19,  4.92s/klasa, klasa=class_227, F1_klasy=0.6393, F1_macro=0.7307, drzewa=50]

[80]	valid_0's binary_logloss: 0.020211
[1]	valid_0's binary_logloss: 0.0454926
[2]	valid_0's binary_logloss: 0.0451771
[3]	valid_0's binary_logloss: 0.0445277
[4]	valid_0's binary_logloss: 0.0440241
[5]	valid_0's binary_logloss: 0.0439019
[6]	valid_0's binary_logloss: 0.0436632
[7]	valid_0's binary_logloss: 0.0430664
[8]	valid_0's binary_logloss: 0.0424193
[9]	valid_0's binary_logloss: 0.0419235
[10]	valid_0's binary_logloss: 0.0414864
[11]	valid_0's binary_logloss: 0.0405925
[12]	valid_0's binary_logloss: 0.0406647
[13]	valid_0's binary_logloss: 0.0403778
[14]	valid_0's binary_logloss: 0.039839
[15]	valid_0's binary_logloss: 0.0394366
[16]	valid_0's binary_logloss: 0.038928
[17]	valid_0's binary_logloss: 0.0383996
[18]	valid_0's binary_logloss: 0.0381224
[19]	valid_0's binary_logloss: 0.0378089
[20]	valid_0's binary_logloss: 0.0375131
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0372388
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0370933
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.0366104
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0362067
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.0360245
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.0357301
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.0354169
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.0352446
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.0350525
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.0349011
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.0347982
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.0344652
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.0342773
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.0338453
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.0333885
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.0330401
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.0327215
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.0324131
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.0324025
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.0322024
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.0320765
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.0319927
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.0318969
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.031834
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.0319024
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.0317025
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.0315146
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.0313723
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.0312402
[50]	valid_0's binary_logloss: 0.0310022
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.0309692
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.030859
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.0307352
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.030705
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.0306553
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.0306868
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.0305949
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.0305204
[59]	valid_0's binary_logloss: 0.0304355
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.0301906
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.0301852
[62]	valid_0's binary_logloss: 0.030166
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.0300722
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.0300739
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.0300803
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.0300069
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.0298312
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.0298795
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.0300061
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.0300707
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.0300914
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.0300193
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.0300235
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.0300265
[75]	valid_0's binary_logloss: 0.0300411
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.0300179
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.030122
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.0300982
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.0301315
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.030217
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.0301551
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.0301631
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.0301864
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.0302289
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.0302483
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.0303109
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.0303327
[88]	valid_0's binary_logloss: 0.0304295
[89]	valid_0's binary_logloss: 0.0305178
[90]	valid_0's binary_logloss: 0.0306747
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.0308343
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.030808
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.0308436
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.0309832
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.0310593
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.031175

Trening klas:  46%|████▌     | 228/500 [28:04<22:19,  4.92s/klasa, klasa=class_228, F1_klasy=0.5085, F1_macro=0.7297, drzewa=67]




Trening klas:  46%|████▌     | 229/500 [28:04<22:36,  5.00s/klasa, klasa=class_228, F1_klasy=0.5085, F1_macro=0.7297, drzewa=67]

[97]	valid_0's binary_logloss: 0.0313115
[1]	valid_0's binary_logloss: 0.031409
[2]	valid_0's binary_logloss: 0.0308141
[3]	valid_0's binary_logloss: 0.0303441
[4]	valid_0's binary_logloss: 0.0297159
[5]	valid_0's binary_logloss: 0.0291231
[6]	valid_0's binary_logloss: 0.0300783
[7]	valid_0's binary_logloss: 0.029886
[8]	valid_0's binary_logloss: 0.0292676
[9]	valid_0's binary_logloss: 0.0290767
[10]	valid_0's binary_logloss: 0.0289969
[11]	valid_0's binary_logloss: 0.0299386
[12]	valid_0's binary_logloss: 0.0296813
[13]	valid_0's binary_logloss: 0.0293165
[14]	valid_0's binary_logloss: 0.0289107
[15]	valid_0's binary_logloss: 0.0286614
[16]	valid_0's binary_logloss: 0.0283724
[17]	valid_0's binary_logloss: 0.0281544
[18]	valid_0's binary_logloss: 0.0278537
[19]	valid_0's binary_logloss: 0.0275816
[20]	valid_0's binary_logloss: 0.0273816
[21]	valid_0's binary_logloss: 0.0270438
[22]	valid_0's binary_logloss: 0.0268242
[23]	valid_0's binary_logloss: 0.026559
[24]	valid_0's binary_logloss: 0.0263573
[25]	valid_0's binary_logloss: 0.0262082
[26]	valid_0's binary_logloss: 0.026018
[27]	valid_0's binary_logloss: 0.0259664
[28]	valid_0's binary_logloss: 0.0258345
[29]	valid_0's binary_logloss: 0.0257398
[30]	valid_0's binary_logloss: 0.0255491
[31]	valid_0's binary_logloss: 0.0252477
[32]	valid_0's binary_logloss: 0.0250732
[33]	valid_0's binary_logloss: 0.0249152
[34]	valid_0's binary_logloss: 0.0247985
[35]	valid_0's binary_logloss: 0.0246606
[36]	valid_0's binary_logloss: 0.0245355
[37]	valid_0's binary_logloss: 0.0244132
[38]	valid_0's binary_logloss: 0.0242723
[39]	valid_0's binary_logloss: 0.0240712
[40]	valid_0's binary_logloss: 0.0238842
[41]	valid_0's binary_logloss: 0.0237194
[42]	valid_0's binary_logloss: 0.0236306
[43]	valid_0's binary_logloss: 0.0234695
[44]	valid_0's binary_logloss: 0.0232884
[45]	valid_0's binary_logloss: 0.0232132
[46]	valid_0's binary_logloss: 0.0231719
[47]	valid_0's binary_logloss: 0.023111
[48]	valid_0's binary_logloss: 0.0230261
[49]	valid_0's binary_logloss: 0.0229613
[50]	valid_0's binary_logloss: 0.0228647
[51]	valid_0's binary_logloss: 0.02263
[52]	valid_0's binary_logloss: 0.0224714
[53]	valid_0's binary_logloss: 0.0221372
[54]	valid_0's binary_logloss: 0.021995
[55]	valid_0's binary_logloss: 0.021937
[56]	valid_0's binary_logloss: 0.0218839
[57]	valid_0's binary_logloss: 0.0218575
[58]	valid_0's binary_logloss: 0.0218973
[59]	valid_0's binary_logloss: 0.0219932
[60]	valid_0's binary_logloss: 0.0221046
[61]	valid_0's binary_logloss: 0.0221605
[62]	valid_0's binary_logloss: 0.022208
[63]	valid_0's binary_logloss: 0.0221686
[64]	valid_0's binary_logloss: 0.022076
[65]	valid_0's binary_logloss: 0.0221592
[66]	valid_0's binary_logloss: 0.0221123
[67]	valid_0's binary_logloss: 0.0221229
[68]	valid_0's binary_logloss: 0.0221567
[69]	valid_0's binary_logloss: 0.0220901
[70]	valid_0's binary_logloss: 0.0220989
[71]	valid_0's binary_logloss: 0.0221141
[72]	valid_0's binary_logloss: 0.0220304
[73]	valid_0's binary_logloss: 0.0220996
[74]	valid_0's binary_logloss: 0.022147
[75]	valid_0's binary_logloss: 0.0221163
[76]	valid_0's binary_logloss: 0.0219033
[77]	valid_0's binary_logloss: 0.0218223
[78]	valid_0's binary_logloss: 0.0218062
[79]	valid_0's binary_logloss: 0.021661
[80]	valid_0's binary_logloss: 0.0216192
[81]	valid_0's binary_logloss: 0.0214772
[82]	valid_0's binary_logloss: 0.0214422
[83]	valid_0's binary_logloss: 0.021356
[84]	valid_0's binary_logloss: 0.0212958
[85]	valid_0's binary_logloss: 0.0213715
[86]	valid_0's binary_logloss: 0.021345
[87]	valid_0's binary_logloss: 0.0213538
[88]	valid_0's binary_logloss: 0.0213429
[89]	valid_0's binary_logloss: 0.021334
[90]	valid_0's binary_logloss: 0.0213989
[91]	valid_0's binary_logloss: 0.0214368
[92]	valid_0's binary_logloss: 0.0214687
[93]	valid_0's binary_logloss: 0.0215679
[94]	valid_0's binary_logloss: 0.0215743
[95]	valid_0's binary_logloss: 0.0215824
[96]	valid_0's binary_logloss: 0.021611
[97]	valid_0's binary_logloss: 0.0215325
[98]	valid_0's binary_logloss: 0.0216021
[99]	valid_0's binary_logloss: 0.0216421
[100]	valid_0's binary_logloss: 0.0216115
[101]	valid_0's binary_logloss: 0.0215511
[102]	valid_0's binary_logloss: 0.0214602
[103]	valid_0's binary_logloss: 0.0215341
[104]	valid_0's binary_logloss: 0.021567
[105]	valid_0's binary_logloss: 0.0215144
[106]	valid_0's binary_logloss: 0.0214893
[107]	valid_0's binary_logloss: 0.0215132
[108]	valid_0's binary_logloss: 0.0216287
[109]	valid_0's binary_logloss: 0.0216953
[110]	valid_0's binary_logloss: 0.0217178
[111]	valid_0's binary_logloss: 0.0218036
[112]	valid_0's binary_logloss: 0.0217615
[113]	valid_0's binary_logloss: 0.0218507
[114]	valid_0's binary_logloss: 0.0219169

Trening klas:  46%|████▌     | 229/500 [28:12<22:36,  5.00s/klasa, klasa=class_229, F1_klasy=0.4854, F1_macro=0.7286, drzewa=84]




Trening klas:  46%|████▌     | 230/500 [28:12<26:59,  6.00s/klasa, klasa=class_229, F1_klasy=0.4854, F1_macro=0.7286, drzewa=84]

[1]	valid_0's binary_logloss: 0.0438199
[2]	valid_0's binary_logloss: 0.0431925
[3]	valid_0's binary_logloss: 0.0427604
[4]	valid_0's binary_logloss: 0.0422013
[5]	valid_0's binary_logloss: 0.0416606
[6]	valid_0's binary_logloss: 0.0409225
[7]	valid_0's binary_logloss: 0.0404047
[8]	valid_0's binary_logloss: 0.039756
[9]	valid_0's binary_logloss: 0.0390893
[10]	valid_0's binary_logloss: 0.0386779
[11]	valid_0's binary_logloss: 0.0377371
[12]	valid_0's binary_logloss: 0.0374065
[13]	valid_0's binary_logloss: 0.0369989
[14]	valid_0's binary_logloss: 0.0368301
[15]	valid_0's binary_logloss: 0.036405
[16]	valid_0's binary_logloss: 0.0361447
[17]	valid_0's binary_logloss: 0.0353007
[18]	valid_0's binary_logloss: 0.0349668
[19]	valid_0's binary_logloss: 0.0347222
[20]	valid_0's binary_logloss: 0.0342418
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0339745
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0334852
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.0327977
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0323005
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.0315613
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.0313514
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.0310697
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.0309593
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.0308345
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.0304536
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.0302817
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.0301769
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.0298454
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.0297392
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.029254
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.0289639
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.0288292
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.0285287
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.0284181
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.0280214
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.0279344
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.0275689
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.0275001
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.027413
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.0273297
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.0269871
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.0265182
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.0262163
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.0258113
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.0253752
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.0255007
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.0254595
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.0253099
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.0251156
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.0251437
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.0250341
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.0250597
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.0248143
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.0246455
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.0245553
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.0243902
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.0244361
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.0243748
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.0242684
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.0243052
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.0241238
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.0240944
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.0238034
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.0235146
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.0232527
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.023191
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.0231333
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.0230519
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.0230998
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.0230728
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.022718
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.0226391
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.0224918
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.0223105
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.022207
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.0221545
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.0221887
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.0222871
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.0222017
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.022172
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.0221993
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.0221813
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.0221226
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.0221518
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.0221764
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.0222305
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.0221302
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.0220213
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.0219712
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.0218554
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.0218477
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.0218356
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.021786
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.0217787
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.021893
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.0217216
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.0217872
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.0216901
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.0216937
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.0217317
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.0217404
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.0217026
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.0216108
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.0216511
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.0217309
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.0217926
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 0.021789
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 0.0217953
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 0.0217758
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 0.0217678
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[116]	valid_0's binary_logloss: 0.0217625
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[117]	valid_0's binary_logloss: 0.021722
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[118]	valid_0's binary_logloss: 0.0217745
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[119]	valid_0's binary_logloss: 0.0218245
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[120]	valid_0's binary_logloss: 0.021791
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[121]	valid_0's binary_logloss: 0.0219066
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[122]	valid_0's binary_logloss: 0.0218313
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[123]	valid_0's binary_logloss: 0.0218621
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[124]	valid_0's binary_logloss: 0.0218517
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[125]	valid_0's binary_logloss: 0.0219355
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[126]	valid_0's binary_logloss: 0.021811
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[127]	valid_0's binary_logloss: 0.0217252
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[128]	valid_0's binary_logloss: 0.0217381
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[129]	valid_0's binary_logloss: 0.0216747
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[130]	valid_0's binary_logloss: 0.0217032
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[131]	valid_0's binary_logloss: 0.0218226
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[132]	valid_0's binary_logloss: 0.0218766
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[133]	valid_0's binary_logloss: 0.0219387
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[134]	valid_0's binary_logloss: 0.0219794
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[135]	valid_0's binary_logloss: 0.0221121
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[136]	valid_0's binary_logloss: 0.0221796
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[137]	valid_0's binary_logloss: 0.0222085
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[138]	valid_0's binary_logloss: 0.0222203

Trening klas:  46%|████▌     | 230/500 [28:17<26:59,  6.00s/klasa, klasa=class_230, F1_klasy=0.7168, F1_macro=0.7286, drzewa=108]




Trening klas:  46%|████▌     | 231/500 [28:17<25:11,  5.62s/klasa, klasa=class_230, F1_klasy=0.7168, F1_macro=0.7286, drzewa=108]

[1]	valid_0's binary_logloss: 0.123534
[2]	valid_0's binary_logloss: 0.120654
[3]	valid_0's binary_logloss: 0.118567
[4]	valid_0's binary_logloss: 0.115917
[5]	valid_0's binary_logloss: 0.113662
[6]	valid_0's binary_logloss: 0.111299
[7]	valid_0's binary_logloss: 0.109272
[8]	valid_0's binary_logloss: 0.10778
[9]	valid_0's binary_logloss: 0.105589
[10]	valid_0's binary_logloss: 0.103939
[11]	valid_0's binary_logloss: 0.103572
[12]	valid_0's binary_logloss: 0.102716
[13]	valid_0's binary_logloss: 0.102001
[14]	valid_0's binary_logloss: 0.101004
[15]	valid_0's binary_logloss: 0.100052
[16]	valid_0's binary_logloss: 0.0988714
[17]	valid_0's binary_logloss: 0.098066
[18]	valid_0's binary_logloss: 0.0969104
[19]	valid_0's binary_logloss: 0.0961475
[20]	valid_0's binary_logloss: 0.0954898
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0940863
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0931024
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.0923692
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0913899
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.090666
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.0896305
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.0890853
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.0883768
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.0881967
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.0879884
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.0873827
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.0868426
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.0865983
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.0858937
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.0856688
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.0854554
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.0850868
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.0846713
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.0844822
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.0843777
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.0839475
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.0834994
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.0829898
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.0826501
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.0823671
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.0817853
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.0814196
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.0811086
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.0808603
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.0803827
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.0798789
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.0795398
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.0791611
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.0789873
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.078813
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.0785984
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.0783341
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.078391
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.0782785
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.0780674
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.0782687
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.0781584
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.0780513
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.0779536
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.0779587
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.0779643
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.0779625
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.077923
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.0777086
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.0776628
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.077571
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.0775214
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.07753
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.0774891
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.0775217
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.0774084
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.0774503
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.0774499
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.0776546
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.0780446
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.0778951
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.0779015
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.077757
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.0777873
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.0778186
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.0777672
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.0776689
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.0776966
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.0776806
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.0776637
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.07755
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.0776466
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.0776245
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.0775307
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.077621
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.0775768
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.0773537
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.0771706
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.0770943
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.0769602
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.0769901
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.0771564
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.0771232
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.0771319
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.0773127
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.0774455
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.0773988
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.0772265
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.0771929
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.077032
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.077078
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 0.0769192
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 0.0768224
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 0.0769716
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 0.076967
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[116]	valid_0's binary_logloss: 0.0769323
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[117]	valid_0's binary_logloss: 0.0770124
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[118]	valid_0's binary_logloss: 0.0769385
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[119]	valid_0's binary_logloss: 0.0769035
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[120]	valid_0's binary_logloss: 0.0768666
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[121]	valid_0's binary_logloss: 0.076827
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[122]	valid_0's binary_logloss: 0.077024
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[123]	valid_0's binary_logloss: 0.0771181
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[124]	valid_0's binary_logloss: 0.0771242
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[125]	valid_0's binary_logloss: 0.0770441
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[126]	valid_0's binary_logloss: 0.0770476
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[127]	valid_0's binary_logloss: 0.0768634
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[128]	valid_0's binary_logloss: 0.0768153
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[129]	valid_0's binary_logloss: 0.0766377
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[130]	valid_0's binary_logloss: 0.0765616
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[131]	valid_0's binary_logloss: 0.0764571
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[132]	valid_0's binary_logloss: 0.0764673
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[133]	valid_0's binary_logloss: 0.0765198
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[134]	valid_0's binary_logloss: 0.076318
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[135]	valid_0's binary_logloss: 0.0762113
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[136]	valid_0's binary_logloss: 0.0761258
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[137]	valid_0's binary_logloss: 0.0758327
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[138]	valid_0's binary_logloss: 0.0756173
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[139]	valid_0's binary_logloss: 0.0755861
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[140]	valid_0's binary_logloss: 0.0755562
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[141]	valid_0's binary_logloss: 0.0757107
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[142]	valid_0's binary_logloss: 0.0757543
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[143]	valid_0's binary_logloss: 0.0757102
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[144]	valid_0's binary_logloss: 0.0758178
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[145]	valid_0's binary_logloss: 0.0757892
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[146]	valid_0's binary_logloss: 0.0756745
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[147]	valid_0's binary_logloss: 0.075644
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[148]	valid_0's binary_logloss: 0.0754269
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[149]	valid_0's binary_logloss: 0.0753351
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[150]	valid_0's binary_logloss: 0.0752132
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[151]	valid_0's binary_logloss: 0.0751443
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[152]	valid_0's binary_logloss: 0.0752066
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[153]	valid_0's binary_logloss: 0.0751315
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[154]	valid_0's binary_logloss: 0.0750277
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[155]	valid_0's binary_logloss: 0.0749559
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[156]	valid_0's binary_logloss: 0.0748562
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[157]	valid_0's binary_logloss: 0.074844
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[158]	valid_0's binary_logloss: 0.074803
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[159]	valid_0's binary_logloss: 0.0746839
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[160]	valid_0's binary_logloss: 0.0746114
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[161]	valid_0's binary_logloss: 0.0744199
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[162]	valid_0's binary_logloss: 0.0742741
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[163]	valid_0's binary_logloss: 0.0742368
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[164]	valid_0's binary_logloss: 0.0742223
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[165]	valid_0's binary_logloss: 0.0740405
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[166]	valid_0's binary_logloss: 0.074034
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[167]	valid_0's binary_logloss: 0.0739542
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[168]	valid_0's binary_logloss: 0.0738894
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[169]	valid_0's binary_logloss: 0.073878
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[170]	valid_0's binary_logloss: 0.073925
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[171]	valid_0's binary_logloss: 0.0739635
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[172]	valid_0's binary_logloss: 0.0739614
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[173]	valid_0's binary_logloss: 0.0739857
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[174]	valid_0's binary_logloss: 0.0739514
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[175]	valid_0's binary_logloss: 0.0737487
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[176]	valid_0's binary_logloss: 0.0736225
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[177]	valid_0's binary_logloss: 0.0734735
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[178]	valid_0's binary_logloss: 0.073458
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[179]	valid_0's binary_logloss: 0.073337
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[180]	valid_0's binary_logloss: 0.0733973
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[181]	valid_0's binary_logloss: 0.0733435
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[182]	valid_0's binary_logloss: 0.0732934
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[183]	valid_0's binary_logloss: 0.0732672
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[184]	valid_0's binary_logloss: 0.0732487
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[185]	valid_0's binary_logloss: 0.0732223

Trening klas:  46%|████▌     | 231/500 [28:26<25:11,  5.62s/klasa, klasa=class_231, F1_klasy=0.5533, F1_macro=0.7278, drzewa=186]




Trening klas:  46%|████▋     | 232/500 [28:26<30:08,  6.75s/klasa, klasa=class_231, F1_klasy=0.5533, F1_macro=0.7278, drzewa=186]

[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[214]	valid_0's binary_logloss: 0.0748515
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[215]	valid_0's binary_logloss: 0.074962
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[216]	valid_0's binary_logloss: 0.075038
[1]	valid_0's binary_logloss: 0.0251962
[2]	valid_0's binary_logloss: 0.0243564
[3]	valid_0's binary_logloss: 0.0236371
[4]	valid_0's binary_logloss: 0.022816
[5]	valid_0's binary_logloss: 0.0220585
[6]	valid_0's binary_logloss: 0.0214228
[7]	valid_0's binary_logloss: 0.0208153
[8]	valid_0's binary_logloss: 0.0202653
[9]	valid_0's binary_logloss: 0.0196426
[10]	valid_0's binary_logloss: 0.0191997
[11]	valid_0's binary_logloss: 0.0186917
[12]	valid_0's binary_logloss: 0.0182051
[13]	valid_0's binary_logloss: 0.0177655
[14]	valid_0's binary_logloss: 0.017355
[15]	valid_0's binary_logloss: 0.0169772
[16]	valid_0's binary_logloss: 0.0165904
[17]	valid_0's binary_logloss: 0.0162484
[18]	valid_0's binary_logloss: 0.0159478
[19]	valid_0's binary_logloss: 0.0156681
[20]	valid_0's binary_logloss: 0.0153948
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0150907
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0149269
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.014687
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0144663
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.0142629
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.0141645
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.0140475
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.0139774
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.013839
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.013783
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.0137006
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.0136533
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.0136182
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.013593
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.0135785
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.013499
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.0131821
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.0129468
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.0128116
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.0126759
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.0125893
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.012538
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.0124833
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.0124383
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.0124056
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.012367
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.012404
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.0124941
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.0125096
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.0124947
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.0124723
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.0124623
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.0124537
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.0124628
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.0124658
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.0124763
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.0124793
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.0124948
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.0124166
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.012439
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.0124968
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.0125632
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.0126313
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.0127045
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.012771
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.0128068
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.012876
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.0129207
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

Trening klas:  46%|████▋     | 232/500 [28:30<30:08,  6.75s/klasa, klasa=class_232, F1_klasy=0.9211, F1_macro=0.7287, drzewa=46]




Trening klas:  47%|████▋     | 233/500 [28:30<25:19,  5.69s/klasa, klasa=class_232, F1_klasy=0.9211, F1_macro=0.7287, drzewa=46]

[69]	valid_0's binary_logloss: 0.0129725
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.0130377
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.0130776
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.0131079
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.0131385
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.0131906
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.013153
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.0131684
[1]	valid_0's binary_logloss: 0.190861
[2]	valid_0's binary_logloss: 0.182404
[3]	valid_0's binary_logloss: 0.175919
[4]	valid_0's binary_logloss: 0.169303
[5]	valid_0's binary_logloss: 0.164816
[6]	valid_0's binary_logloss: 0.16382
[7]	valid_0's binary_logloss: 0.159547
[8]	valid_0's binary_logloss: 0.154727
[9]	valid_0's binary_logloss: 0.150885
[10]	valid_0's binary_logloss: 0.14702
[11]	valid_0's binary_logloss: 0.144111
[12]	valid_0's binary_logloss: 0.142104
[13]	valid_0's binary_logloss: 0.139518
[14]	valid_0's binary_logloss: 0.137373
[15]	valid_0's binary_logloss: 0.134175
[16]	valid_0's binary_logloss: 0.131942
[17]	valid_0's binary_logloss: 0.129607
[18]	valid_0's binary_logloss: 0.127475
[19]	valid_0's binary_logloss: 0.125212
[20]	valid_0's binary_logloss: 0.12384
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.121837
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.120257
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.119137
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.117604
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.116477
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.114661
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.113314
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.111674
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.109978
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.10848
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.107423
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.106251
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.105619
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.104761
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.104044
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.102935
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.102169
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.101211
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.100828
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.0997699
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.0989106
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.0984889
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.0979905
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.097323
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.0968454
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.096771
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.0966507
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.0963504
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.0962059
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.0958551
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.0953178
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.0948411
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.0945901
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.0945457
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.0942432
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.0933787
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.0929415
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.092793
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.0925707
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.0921085
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.0921116
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.0916789
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.0914034
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.0913254
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.091306
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.0906123
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.0903267
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.0902572
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.0901332
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.0901198
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.0899134
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.0896584
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.0892673
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.0887373
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.0884767
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.0883281
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.0880711
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.0877296
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.0874226
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.0872166
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.0868662
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.0866274
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.0863159
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.0859986
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.0858202
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.0855546
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.0853667
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.0853962
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.0853061
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.0850763
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.0850609
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.0849883
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.0851071
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.085246
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.0849798
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.0847205
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.0844295
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.0840982
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.083827
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.0835502
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.0834705
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.0832613
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.0832041
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.083057
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.0828389
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.0828813
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.0828233
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.0826888
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.0826234
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.0827847
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.0829424
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 0.0829749
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 0.0829577
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 0.0829455
[115]	valid_0's binary_logloss: 0.0829853
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[116]	valid_0's binary_logloss: 0.0830372
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[117]	valid_0's binary_logloss: 0.08299
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[118]	valid_0's binary_logloss: 0.0830632
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[119]	valid_0's binary_logloss: 0.0831856
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[120]	valid_0's binary_logloss: 0.0832095
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[121]	valid_0's binary_logloss: 0.0832601
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[122]	valid_0's binary_logloss: 0.0831716
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[123]	valid_0's binary_logloss: 0.0832623
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[124]	valid_0's binary_logloss: 0.0830907
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[125]	valid_0's binary_logloss: 0.0828671
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[126]	valid_0's binary_logloss: 0.0827948
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[127]	valid_0's binary_logloss: 0.0827809
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[128]	valid_0's binary_logloss: 0.0826665
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[129]	valid_0's binary_logloss: 0.0823565
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[130]	valid_0's binary_logloss: 0.0823714
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[131]	valid_0's binary_logloss: 0.082374
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[132]	valid_0's binary_logloss: 0.0824155
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[133]	valid_0's binary_logloss: 0.0823555
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[134]	valid_0's binary_logloss: 0.0822982
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[135]	valid_0's binary_logloss: 0.0822369
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[136]	valid_0's binary_logloss: 0.0820988
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[137]	valid_0's binary_logloss: 0.0821336
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[138]	valid_0's binary_logloss: 0.0818723
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[139]	valid_0's binary_logloss: 0.0817296
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[140]	valid_0's binary_logloss: 0.0816199
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[141]	valid_0's binary_logloss: 0.081622
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[142]	valid_0's binary_logloss: 0.0816077
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[143]	valid_0's binary_logloss: 0.0817287
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[144]	valid_0's binary_logloss: 0.0817868
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[145]	valid_0's binary_logloss: 0.0817815
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[146]	valid_0's binary_logloss: 0.0817025
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[147]	valid_0's binary_logloss: 0.0815911
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[148]	valid_0's binary_logloss: 0.0814373
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[149]	valid_0's binary_logloss: 0.0812915
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[150]	valid_0's binary_logloss: 0.081232
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[151]	valid_0's binary_logloss: 0.0812999
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[152]	valid_0's binary_logloss: 0.0814194
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[153]	valid_0's binary_logloss: 0.0814087
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[154]	valid_0's binary_logloss: 0.0813799
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[155]	valid_0's binary_logloss: 0.0814546
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[156]	valid_0's binary_logloss: 0.0816747
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[157]	valid_0's binary_logloss: 0.0817416
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[158]	valid_0's binary_logloss: 0.0817567
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[159]	valid_0's binary_logloss: 0.0816628
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[160]	valid_0's binary_logloss: 0.0816847
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[161]	valid_0's binary_logloss: 0.0815214
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[162]	valid_0's binary_logloss: 0.0814595
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[163]	valid_0's binary_logloss: 0.0813246
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[164]	valid_0's binary_logloss: 0.0812614
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[165]	valid_0's binary_logloss: 0.0810817
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[166]	valid_0's binary_logloss: 0.0811327
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[167]	valid_0's binary_logloss: 0.0812566
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[168]	valid_0's binary_logloss: 0.0814431
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[169]	valid_0's binary_logloss: 0.0816278
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[170]	valid_0's binary_logloss: 0.0815522
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[171]	valid_0's binary_logloss: 0.0818338
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[172]	valid_0's binary_logloss: 0.0820371
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[173]	valid_0's binary_logloss: 0.0824005
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[174]	valid_0's binary_logloss: 0.0824608
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[175]	valid_0's binary_logloss: 0.0825315
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[176]	valid_0's binary_logloss: 0.0825571
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[177]	valid_0's binary_logloss: 0.0825724
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[178]	valid_0's binary_logloss: 0.0825103

Trening klas:  47%|████▋     | 233/500 [28:39<25:19,  5.69s/klasa, klasa=class_233, F1_klasy=0.5510, F1_macro=0.7279, drzewa=165]




Trening klas:  47%|████▋     | 234/500 [28:39<30:31,  6.89s/klasa, klasa=class_233, F1_klasy=0.5510, F1_macro=0.7279, drzewa=165]

[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[193]	valid_0's binary_logloss: 0.0825158
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[194]	valid_0's binary_logloss: 0.0824736
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[195]	valid_0's binary_logloss: 0.0823566
[1]	valid_0's binary_logloss: 0.190861
[2]	valid_0's binary_logloss: 0.182404
[3]	valid_0's binary_logloss: 0.175919
[4]	valid_0's binary_logloss: 0.169303
[5]	valid_0's binary_logloss: 0.164816
[6]	valid_0's binary_logloss: 0.16382
[7]	valid_0's binary_logloss: 0.159547
[8]	valid_0's binary_logloss: 0.154727
[9]	valid_0's binary_logloss: 0.150885
[10]	valid_0's binary_logloss: 0.14702
[11]	valid_0's binary_logloss: 0.144111
[12]	valid_0's binary_logloss: 0.142104
[13]	valid_0's binary_logloss: 0.139518
[14]	valid_0's binary_logloss: 0.137373
[15]	valid_0's binary_logloss: 0.134175
[16]	valid_0's binary_logloss: 0.131942
[17]	valid_0's binary_logloss: 0.129607
[18]	valid_0's binary_logloss: 0.127475
[19]	valid_0's binary_logloss: 0.125212
[20]	valid_0's binary_logloss: 0.12384
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.121837
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.120257
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.119137
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.117604
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.116477
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.114661
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.113314
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.111674
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.109978
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.10848
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.107423
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.106251
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.105619
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.104761
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.104044
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.102935
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.102169
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.101211
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.100828
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.0997699
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.0989106
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.0984889
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.0979905
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.097323
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.0968454
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.096771
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.0966507
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.0963504
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.0962059
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.0958551
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.0953178
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.0948411
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.0945901
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.0945457
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.0942432
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.0933787
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.0929415
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.092793
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.0925707
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.0921085
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.0921116
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.0916789
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.0914034
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.0913254
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.091306
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.0906123
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.0903267
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.0902572
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.0901332
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.0901198
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.0899134
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.0896584
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.0892673
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.0887373
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.0884767
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.0883281
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.0880711
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.0877296
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.0874226
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.0872166
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.0868662
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.0866274
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.0863159
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.0859986
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.0858202
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.0855546
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.0853667
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.0853962
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.0853061
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.0850763
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.0850609
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.0849883
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.0851071
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.085246
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.0849798
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.0847205
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.0844295
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.0840982
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.083827
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.0835502
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.0834705
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.0832613
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.0832041
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.083057
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.0828389
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.0828813
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.0828233
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.0826888
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.0826234
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.0827847
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.0829424
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 0.0829749
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 0.0829577
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 0.0829455
[115]	valid_0's binary_logloss: 0.0829853
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[116]	valid_0's binary_logloss: 0.0830372
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[117]	valid_0's binary_logloss: 0.08299
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[118]	valid_0's binary_logloss: 0.0830632
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[119]	valid_0's binary_logloss: 0.0831856
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[120]	valid_0's binary_logloss: 0.0832095
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[121]	valid_0's binary_logloss: 0.0832601
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[122]	valid_0's binary_logloss: 0.0831716
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[123]	valid_0's binary_logloss: 0.0832623
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[124]	valid_0's binary_logloss: 0.0830907
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[125]	valid_0's binary_logloss: 0.0828671
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[126]	valid_0's binary_logloss: 0.0827948
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[127]	valid_0's binary_logloss: 0.0827809
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[128]	valid_0's binary_logloss: 0.0826665
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[129]	valid_0's binary_logloss: 0.0823565
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[130]	valid_0's binary_logloss: 0.0823714
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[131]	valid_0's binary_logloss: 0.082374
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[132]	valid_0's binary_logloss: 0.0824155
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[133]	valid_0's binary_logloss: 0.0823555
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[134]	valid_0's binary_logloss: 0.0822982
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[135]	valid_0's binary_logloss: 0.0822369
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[136]	valid_0's binary_logloss: 0.0820988
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[137]	valid_0's binary_logloss: 0.0821336
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[138]	valid_0's binary_logloss: 0.0818723
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[139]	valid_0's binary_logloss: 0.0817296
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[140]	valid_0's binary_logloss: 0.0816199
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[141]	valid_0's binary_logloss: 0.081622
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[142]	valid_0's binary_logloss: 0.0816077
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[143]	valid_0's binary_logloss: 0.0817287
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[144]	valid_0's binary_logloss: 0.0817868
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[145]	valid_0's binary_logloss: 0.0817815
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[146]	valid_0's binary_logloss: 0.0817025
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[147]	valid_0's binary_logloss: 0.0815911
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[148]	valid_0's binary_logloss: 0.0814373
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[149]	valid_0's binary_logloss: 0.0812915
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[150]	valid_0's binary_logloss: 0.081232
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[151]	valid_0's binary_logloss: 0.0812999
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[152]	valid_0's binary_logloss: 0.0814194
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[153]	valid_0's binary_logloss: 0.0814087
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[154]	valid_0's binary_logloss: 0.0813799
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[155]	valid_0's binary_logloss: 0.0814546
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[156]	valid_0's binary_logloss: 0.0816747
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[157]	valid_0's binary_logloss: 0.0817416
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[158]	valid_0's binary_logloss: 0.0817567
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[159]	valid_0's binary_logloss: 0.0816628
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[160]	valid_0's binary_logloss: 0.0816847
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[161]	valid_0's binary_logloss: 0.0815214
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[162]	valid_0's binary_logloss: 0.0814595
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[163]	valid_0's binary_logloss: 0.0813246
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[164]	valid_0's binary_logloss: 0.0812614
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[165]	valid_0's binary_logloss: 0.0810817
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[166]	valid_0's binary_logloss: 0.0811327
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[167]	valid_0's binary_logloss: 0.0812566
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[168]	valid_0's binary_logloss: 0.0814431
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[169]	valid_0's binary_logloss: 0.0816278
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[170]	valid_0's binary_logloss: 0.0815522
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[171]	valid_0's binary_logloss: 0.0818338
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[172]	valid_0's binary_logloss: 0.0820371
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[173]	valid_0's binary_logloss: 0.0824005
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[174]	valid_0's binary_logloss: 0.0824608
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[175]	valid_0's binary_logloss: 0.0825315
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[176]	valid_0's binary_logloss: 0.0825571
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[177]	valid_0's binary_logloss: 0.0825724
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[178]	valid_0's binary_logloss: 0.0825103
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[179]	valid_0's binary_logloss: 0.0825883
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[180]	valid_0's binary_logloss: 0.082542
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[181]	valid_0's binary_logloss: 0.0824406
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[182]	valid_0's binary_logloss: 0.0823724
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

Trening klas:  47%|████▋     | 234/500 [28:49<30:31,  6.89s/klasa, klasa=class_234, F1_klasy=0.5510, F1_macro=0.7272, drzewa=165]




Trening klas:  47%|████▋     | 235/500 [28:49<34:04,  7.71s/klasa, klasa=class_234, F1_klasy=0.5510, F1_macro=0.7272, drzewa=165]

[1]	valid_0's binary_logloss: 0.115694
[2]	valid_0's binary_logloss: 0.112437
[3]	valid_0's binary_logloss: 0.108603
[4]	valid_0's binary_logloss: 0.106336
[5]	valid_0's binary_logloss: 0.103158
[6]	valid_0's binary_logloss: 0.101132
[7]	valid_0's binary_logloss: 0.0986618
[8]	valid_0's binary_logloss: 0.0964102
[9]	valid_0's binary_logloss: 0.0942069
[10]	valid_0's binary_logloss: 0.0922977
[11]	valid_0's binary_logloss: 0.0905609
[12]	valid_0's binary_logloss: 0.089277
[13]	valid_0's binary_logloss: 0.0878326
[14]	valid_0's binary_logloss: 0.0864778
[15]	valid_0's binary_logloss: 0.08532
[16]	valid_0's binary_logloss: 0.083981
[17]	valid_0's binary_logloss: 0.0829507
[18]	valid_0's binary_logloss: 0.0820363
[19]	valid_0's binary_logloss: 0.080961
[20]	valid_0's binary_logloss: 0.0800221
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.079211
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0785173
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.0778716
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0772514
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.0767916
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.0763098
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.0757579
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.0751451
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.074848
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.0744571
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.0740014
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.0736491
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.073393
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.0731213
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.0725622
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.0723471
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.0721192
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.0719291
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.0716356
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.0710409
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.0711368
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.0707635
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.0706109
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.0703705
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.0700342
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.0697097
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.069731
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.0695106
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.0696278
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.0694681
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.0695034
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.0696323
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.0697921
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.0697355
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.0697025
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.069917
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.0700195
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.0699037
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.0698432
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.0700709
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.0697462
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.0699349
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.0701407
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.0701403
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.0701854
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.0703113
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.070402
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.0704736
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.0707111
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.0709201
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.0710018
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.0712725
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.0714761
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.071582
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.0716211
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.0715006
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.0716882
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

Trening klas:  47%|████▋     | 235/500 [28:53<34:04,  7.71s/klasa, klasa=class_235, F1_klasy=0.5000, F1_macro=0.7262, drzewa=50]




Trening klas:  47%|████▋     | 236/500 [28:53<28:53,  6.56s/klasa, klasa=class_235, F1_klasy=0.5000, F1_macro=0.7262, drzewa=50]

[78]	valid_0's binary_logloss: 0.0715877
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.0717224
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.0718673
[1]	valid_0's binary_logloss: 0.189651
[2]	valid_0's binary_logloss: 0.181835
[3]	valid_0's binary_logloss: 0.175469
[4]	valid_0's binary_logloss: 0.168735
[5]	valid_0's binary_logloss: 0.163315
[6]	valid_0's binary_logloss: 0.16293
[7]	valid_0's binary_logloss: 0.158351
[8]	valid_0's binary_logloss: 0.153709
[9]	valid_0's binary_logloss: 0.149718
[10]	valid_0's binary_logloss: 0.145873
[11]	valid_0's binary_logloss: 0.141987
[12]	valid_0's binary_logloss: 0.138816
[13]	valid_0's binary_logloss: 0.135369
[14]	valid_0's binary_logloss: 0.133108
[15]	valid_0's binary_logloss: 0.130483
[16]	valid_0's binary_logloss: 0.129183
[17]	valid_0's binary_logloss: 0.126937
[18]	valid_0's binary_logloss: 0.125213
[19]	valid_0's binary_logloss: 0.123565
[20]	valid_0's binary_logloss: 0.122047
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.119938
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.118351
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.116734
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.115288
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.11371
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.112304
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.11105
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.109542
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.108352
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.107149
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.10612
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.104943
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.10381
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.102922
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.101741
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.100948
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.100303
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.0997282
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.098911
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.0983766
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.0973916
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.0969722
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.0963878
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.0956416
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.095306
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.0945771
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.0939894
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.0934968
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.0932217
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.0930103
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.0924773
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.0919323
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.091666
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.0911466
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.0909651
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.0910778
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.0909637
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.0907033
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.0906024
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.0902262
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.0902954
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.0901256
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.0900709
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.0897556
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.0894735
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.0893631
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.0889038
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.0887733
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.0885841
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.088664
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.0888283
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.0890284
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.089175
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.0893699
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.0895476
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.0897637
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.0899052
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.0897022
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.0898608
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.0900504
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.0903149
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.0903668
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.0904914
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.0904467
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.0906318
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.0906242
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.0907336
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.0907442
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.0908001
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.091015
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.0912582
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.0912406
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.0911895
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.0915087
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.0916402
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.0917643
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

Trening klas:  47%|████▋     | 236/500 [28:59<28:53,  6.56s/klasa, klasa=class_236, F1_klasy=0.4000, F1_macro=0.7248, drzewa=69]




Trening klas:  47%|████▋     | 237/500 [28:59<28:08,  6.42s/klasa, klasa=class_236, F1_klasy=0.4000, F1_macro=0.7248, drzewa=69]

[97]	valid_0's binary_logloss: 0.0920336
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.0923547
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.0923782
[1]	valid_0's binary_logloss: 0.0245663
[2]	valid_0's binary_logloss: 0.0240063
[3]	valid_0's binary_logloss: 0.0234058
[4]	valid_0's binary_logloss: 0.0228542
[5]	valid_0's binary_logloss: 0.0222092
[6]	valid_0's binary_logloss: 0.0217136
[7]	valid_0's binary_logloss: 0.0212216
[8]	valid_0's binary_logloss: 0.0207124
[9]	valid_0's binary_logloss: 0.0201475
[10]	valid_0's binary_logloss: 0.0196978
[11]	valid_0's binary_logloss: 0.0193157
[12]	valid_0's binary_logloss: 0.0188464
[13]	valid_0's binary_logloss: 0.0186706
[14]	valid_0's binary_logloss: 0.0181533
[15]	valid_0's binary_logloss: 0.0176583
[16]	valid_0's binary_logloss: 0.0171221
[17]	valid_0's binary_logloss: 0.0167949
[18]	valid_0's binary_logloss: 0.0163682
[19]	valid_0's binary_logloss: 0.016071
[20]	valid_0's binary_logloss: 0.0157112
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0153805
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.015008
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.0146856
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0144523
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.0143025
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.0139094
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.0135937
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.0132402
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.0129403
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.0125984
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.0123506
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.012092
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.0117922
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.0116093
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.0114165
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.0111867
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.0110019
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.0108006
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.0106917
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.0105884
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.0104739
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.0103151
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.0101964
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.0100954
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.00999974
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.00983973
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.00968853
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.00958425
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.0094337
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.00929114
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.00916202
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.00911342
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.00905737
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.00891122
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.00881951
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.00875573
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.00863567
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.00853894
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.00841097
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.00839127
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.00828037
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.00818142
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.00811202
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.00802471
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.00793863
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.00791731
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.00790721
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.00788819
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.00780319
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.00773698
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.00767367
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.00764563
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.00758751
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.00752137
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.00751095
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.00744183
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.00738663
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.0073364
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.00726696
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.00727156
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.00725856
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.00718058
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.00718913
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.00712169
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.00709068
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.00707183
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.00704614
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.00694331
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.00690496
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.00686989
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.0068229
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.00674507
[93]	valid_0's binary_logloss: 0.00670534
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.00669891
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.00664425
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.00660275
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.00658674
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.00654751
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.00654834
[100]	valid_0's binary_logloss: 0.00652878
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.00649058
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.00647742
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.00643895
[104]	valid_0's binary_logloss: 0.00640366
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.00637932
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.00636156
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.00633519
[108]	valid_0's binary_logloss: 0.00633158
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.00632849
[110]	valid_0's binary_logloss: 0.00635688
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.00632666
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 0.0062698
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 0.00625073
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 0.00621346
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 0.00621933
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[116]	valid_0's binary_logloss: 0.00623801
[117]	valid_0's binary_logloss: 0.00626002
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[118]	valid_0's binary_logloss: 0.00625936
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[119]	valid_0's binary_logloss: 0.00626095
[120]	valid_0's binary_logloss: 0.00627814
[121]	valid_0's binary_logloss: 0.00627097
[122]	valid_0's binary_logloss: 0.00630785
[123]	valid_0's binary_logloss: 0.00630331
[124]	valid_0's binary_logloss: 0.00629972
[125]	valid_0's binary_logloss: 0.00630035
[126]	valid_0's binary_logloss: 0.00630181
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[127]	valid_0's binary_logloss: 0.00632973
[128]	valid_0's binary_logloss: 0.00633943
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[129]	valid_0's binary_logloss: 0.00635985
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[130]	valid_0's binary_logloss: 0.00636596
[131]	valid_0's binary_logloss: 0.00634024
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[132]	valid_0's binary_logloss: 0.00631539
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[133]	valid_0's binary_logloss: 0.00631057
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[134]	valid_0's binary_logloss: 0.00628842
[135]	valid_0's binary_logloss: 0.00627361
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[136]	valid_0's binary_logloss: 0.00626485
[137]	valid_0's binary_logloss: 0.00624818
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[138]	valid_0's binary_logloss: 0.00623598
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[139]	valid_0's binary_logloss: 0.00621508
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[140]	valid_0's binary_logloss: 0.0062051
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[141]	valid_0's binary_logloss: 0.00619113
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[142]	valid_0's binary_logloss: 0.00619141
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[143]	valid_0's binary_logloss: 0.00619739
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[144]	valid_0's binary_logloss: 0.00621574
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[145]	valid_0's binary_logloss: 0.00620587
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[146]	valid_0's binary_logloss: 0.00622614
[147]	valid_0's binary_logloss: 0.00623476
[148]	valid_0's binary_logloss: 0.00624567
[149]	valid_0's binary_logloss: 0.00625532
[150]	valid_0's binary_logloss: 0.00626326
[151]	valid_0's binary_logloss: 0.00625362
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[152]	valid_0's binary_logloss: 0.00624005
[153]	valid_0's binary_logloss: 0.00622572
[154]	valid_0's binary_logloss: 0.00624646
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[155]	valid_0's binary_logloss: 0.0062741
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[156]	valid_0's binary_logloss: 0.00625586
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[157]	valid_0's binary_logloss: 0.00626726
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[158]	valid_0's binary_logloss: 0.00627385
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[159]	valid_0's binary_logloss: 0.00627625
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[160]	valid_0's binary_logloss: 0.00628963
[161]	valid_0's binary_logloss: 0.00627689
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[162]	valid_0's binary_logloss: 0.00628458
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[163]	valid_0's binary_logloss: 0.00628629
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[164]	valid_0's binary_logloss: 0.00628203
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[165]	valid_0's binary_logloss: 0.00627021
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[166]	valid_0's binary_logloss: 0.0062643
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[167]	valid_0's binary_logloss: 0.0062796
[168]	valid_0's binary_logloss: 0.00629583
[169]	valid_0's binary_logloss: 0.00630892
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[170]	valid_0's binary_logloss: 0.00632513
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[171]	valid_0's binary_logloss: 0.00636092

Trening klas:  47%|████▋     | 237/500 [29:08<28:08,  6.42s/klasa, klasa=class_237, F1_klasy=0.7451, F1_macro=0.7249, drzewa=141]




Trening klas:  48%|████▊     | 238/500 [29:08<31:20,  7.18s/klasa, klasa=class_237, F1_klasy=0.7451, F1_macro=0.7249, drzewa=141]

[1]	valid_0's binary_logloss: 0.0349928
[2]	valid_0's binary_logloss: 0.0339992
[3]	valid_0's binary_logloss: 0.0330772
[4]	valid_0's binary_logloss: 0.0323547
[5]	valid_0's binary_logloss: 0.0317785
[6]	valid_0's binary_logloss: 0.0310693
[7]	valid_0's binary_logloss: 0.0305022
[8]	valid_0's binary_logloss: 0.0300137
[9]	valid_0's binary_logloss: 0.0295564
[10]	valid_0's binary_logloss: 0.0291041
[11]	valid_0's binary_logloss: 0.0286407
[12]	valid_0's binary_logloss: 0.0284725
[13]	valid_0's binary_logloss: 0.0281458
[14]	valid_0's binary_logloss: 0.0277656
[15]	valid_0's binary_logloss: 0.0275415
[16]	valid_0's binary_logloss: 0.0271833
[17]	valid_0's binary_logloss: 0.0269463
[18]	valid_0's binary_logloss: 0.0265497
[19]	valid_0's binary_logloss: 0.0262571
[20]	valid_0's binary_logloss: 0.0260292
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0255907
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0252013
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.024787
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0245378
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.0243451
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.0242145
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.0239982
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.0239459
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.0237785
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.0235668
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.0234379
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.0233298
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.0230873
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.0229331
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.0229259
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.0228754
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.0227398
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.0225295
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.0223998
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.0223109
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.0222395
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.0220712
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.0220205
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.0219376
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.0216855
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.0215705
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.0214182
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.021368
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.0211294
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.0209887
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.0208381
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.0207846
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.0207425
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.0205753
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.020514
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.020369
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.0203097
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.0202906
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.0201759
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.0201811
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.0201266
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.0201
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.0199759
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.0200195
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.019938
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.0197635
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.0195789
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.0193716
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.0192616
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.0192138
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.0191971
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.0192357
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.0191522
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.019145
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.0192527
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.0191097
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.0190856
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.0190873
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.0190625
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.0189389
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.0188275
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.0187611
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.0187189
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.0186663
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.0186673
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.0185832
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.0184799
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.0184968
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.0184763
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.0185654
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.0184473
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.0184171
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.0183734
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.0184179
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.0183491
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.0183602
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.0183798
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.0183898
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.01844
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.0184434
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.0183602
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.0183346
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.0182714
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.0182385
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.0182066
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.0181284
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.0181027
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.0180404
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.0180131
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.0179916
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.0180718
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 0.018053
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 0.018042
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 0.0180697
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 0.0180729
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[116]	valid_0's binary_logloss: 0.0181632
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[117]	valid_0's binary_logloss: 0.0181906
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[118]	valid_0's binary_logloss: 0.0182346
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[119]	valid_0's binary_logloss: 0.0181884
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[120]	valid_0's binary_logloss: 0.0182401
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[121]	valid_0's binary_logloss: 0.0183345
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[122]	valid_0's binary_logloss: 0.0183975
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[123]	valid_0's binary_logloss: 0.0184317
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[124]	valid_0's binary_logloss: 0.0184933
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[125]	valid_0's binary_logloss: 0.0185051
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[126]	valid_0's binary_logloss: 0.0185252
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[127]	valid_0's binary_logloss: 0.0185767
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[128]	valid_0's binary_logloss: 0.0186035
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[129]	valid_0's binary_logloss: 0.0186039
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[130]	valid_0's binary_logloss: 0.018594
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[131]	valid_0's binary_logloss: 0.018602
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[132]	valid_0's binary_logloss: 0.0185833
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[133]	valid_0's binary_logloss: 0.0185701
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[134]	valid_0's binary_logloss: 0.0185465
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[135]	valid_0's binary_logloss: 0.0184872
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[136]	valid_0's binary_logloss: 0.018489
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[137]	valid_0's binary_logloss: 0.0185054
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[138]	valid_0's binary_logloss: 0.0186178
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[139]	valid_0's binary_logloss: 0.0186926
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[140]	valid_0's binary_logloss: 0.0188484

Trening klas:  48%|████▊     | 238/500 [29:13<31:20,  7.18s/klasa, klasa=class_238, F1_klasy=0.6891, F1_macro=0.7248, drzewa=110]




Trening klas:  48%|████▊     | 239/500 [29:13<28:20,  6.52s/klasa, klasa=class_238, F1_klasy=0.6891, F1_macro=0.7248, drzewa=110]

[1]	valid_0's binary_logloss: 0.0291031
[2]	valid_0's binary_logloss: 0.0286524
[3]	valid_0's binary_logloss: 0.0283909
[4]	valid_0's binary_logloss: 0.0276341
[5]	valid_0's binary_logloss: 0.0272469
[6]	valid_0's binary_logloss: 0.0273088
[7]	valid_0's binary_logloss: 0.026918
[8]	valid_0's binary_logloss: 0.0266542
[9]	valid_0's binary_logloss: 0.0264589
[10]	valid_0's binary_logloss: 0.0264597
[11]	valid_0's binary_logloss: 0.0270632
[12]	valid_0's binary_logloss: 0.0272287
[13]	valid_0's binary_logloss: 0.0270563
[14]	valid_0's binary_logloss: 0.0268296
[15]	valid_0's binary_logloss: 0.0266308
[16]	valid_0's binary_logloss: 0.026358
[17]	valid_0's binary_logloss: 0.0262429
[18]	valid_0's binary_logloss: 0.0261063
[19]	valid_0's binary_logloss: 0.0259532
[20]	valid_0's binary_logloss: 0.0257178
[21]	valid_0's binary_logloss: 0.025452
[22]	valid_0's binary_logloss: 0.0251327
[23]	valid_0's binary_logloss: 0.0249529
[24]	valid_0's binary_logloss: 0.024653
[25]	valid_0's binary_logloss: 0.0243693
[26]	valid_0's binary_logloss: 0.024234
[27]	valid_0's binary_logloss: 0.0240635
[28]	valid_0's binary_logloss: 0.0240629
[29]	valid_0's binary_logloss: 0.0238623
[30]	valid_0's binary_logloss: 0.0237424
[31]	valid_0's binary_logloss: 0.0234614
[32]	valid_0's binary_logloss: 0.0234475
[33]	valid_0's binary_logloss: 0.0233779
[34]	valid_0's binary_logloss: 0.0233462
[35]	valid_0's binary_logloss: 0.0231294
[36]	valid_0's binary_logloss: 0.0231106
[37]	valid_0's binary_logloss: 0.0229279
[38]	valid_0's binary_logloss: 0.0226346
[39]	valid_0's binary_logloss: 0.0225225
[40]	valid_0's binary_logloss: 0.0222888
[41]	valid_0's binary_logloss: 0.0222833
[42]	valid_0's binary_logloss: 0.0220873
[43]	valid_0's binary_logloss: 0.0219345
[44]	valid_0's binary_logloss: 0.0217581
[45]	valid_0's binary_logloss: 0.0217513
[46]	valid_0's binary_logloss: 0.0217061
[47]	valid_0's binary_logloss: 0.0216023
[48]	valid_0's binary_logloss: 0.021538
[49]	valid_0's binary_logloss: 0.0215681
[50]	valid_0's binary_logloss: 0.0214365
[51]	valid_0's binary_logloss: 0.0215316
[52]	valid_0's binary_logloss: 0.0213898
[53]	valid_0's binary_logloss: 0.0213651
[54]	valid_0's binary_logloss: 0.021253
[55]	valid_0's binary_logloss: 0.0211481
[56]	valid_0's binary_logloss: 0.021054
[57]	valid_0's binary_logloss: 0.020933
[58]	valid_0's binary_logloss: 0.0209997
[59]	valid_0's binary_logloss: 0.0209102
[60]	valid_0's binary_logloss: 0.0209459
[61]	valid_0's binary_logloss: 0.0209489
[62]	valid_0's binary_logloss: 0.0209037
[63]	valid_0's binary_logloss: 0.0209341
[64]	valid_0's binary_logloss: 0.020871
[65]	valid_0's binary_logloss: 0.0208196
[66]	valid_0's binary_logloss: 0.0206275
[67]	valid_0's binary_logloss: 0.0206014
[68]	valid_0's binary_logloss: 0.0206707
[69]	valid_0's binary_logloss: 0.0207817
[70]	valid_0's binary_logloss: 0.0206439
[71]	valid_0's binary_logloss: 0.0206042
[72]	valid_0's binary_logloss: 0.0205789
[73]	valid_0's binary_logloss: 0.0205521
[74]	valid_0's binary_logloss: 0.0203988
[75]	valid_0's binary_logloss: 0.0204056
[76]	valid_0's binary_logloss: 0.0204065
[77]	valid_0's binary_logloss: 0.0203135
[78]	valid_0's binary_logloss: 0.0202904
[79]	valid_0's binary_logloss: 0.0201778
[80]	valid_0's binary_logloss: 0.0200797
[81]	valid_0's binary_logloss: 0.019896
[82]	valid_0's binary_logloss: 0.0198071
[83]	valid_0's binary_logloss: 0.0197664
[84]	valid_0's binary_logloss: 0.0197307
[85]	valid_0's binary_logloss: 0.0195412
[86]	valid_0's binary_logloss: 0.0195444
[87]	valid_0's binary_logloss: 0.0195005
[88]	valid_0's binary_logloss: 0.0194951
[89]	valid_0's binary_logloss: 0.0194937
[90]	valid_0's binary_logloss: 0.0194709
[91]	valid_0's binary_logloss: 0.0195462
[92]	valid_0's binary_logloss: 0.0194298
[93]	valid_0's binary_logloss: 0.0193669
[94]	valid_0's binary_logloss: 0.0193766
[95]	valid_0's binary_logloss: 0.0192972
[96]	valid_0's binary_logloss: 0.0192565
[97]	valid_0's binary_logloss: 0.0192408
[98]	valid_0's binary_logloss: 0.0192846
[99]	valid_0's binary_logloss: 0.0193308
[100]	valid_0's binary_logloss: 0.0194168
[101]	valid_0's binary_logloss: 0.0193199
[102]	valid_0's binary_logloss: 0.0192956
[103]	valid_0's binary_logloss: 0.0191812
[104]	valid_0's binary_logloss: 0.0190921
[105]	valid_0's binary_logloss: 0.0190405
[106]	valid_0's binary_logloss: 0.0190188
[107]	valid_0's binary_logloss: 0.0190894
[108]	valid_0's binary_logloss: 0.0190748
[109]	valid_0's binary_logloss: 0.0190727
[110]	valid_0's binary_logloss: 0.0190765
[111]	valid_0's binary_logloss: 0.0191796
[112]	valid_0's binary_logloss: 0.0192203
[113]	valid_0's binary_logloss: 0.019208
[114]	valid_0's binary_logloss: 0.0192062
[115]	valid_0's binary_logloss: 0.0190951
[116]	valid_0's binary_logloss: 0.0190402
[117]	valid_0's binary_logloss: 0.0190202
[118]	valid_0's binary_logloss: 0.0190581
[119]	valid_0's binary_logloss: 0.0190071
[120]	valid_0's binary_logloss: 0.0190344
[121]	valid_0's binary_logloss: 0.0190877
[122]	valid_0's binary_logloss: 0.0191637
[123]	valid_0's binary_logloss: 0.0192952
[124]	valid_0's binary_logloss: 0.0192773
[125]	valid_0's binary_logloss: 0.0192929
[126]	valid_0's binary_logloss: 0.0193282
[127]	valid_0's binary_logloss: 0.019304
[128]	valid_0's binary_logloss: 0.0193047
[129]	valid_0's binary_logloss: 0.0193675
[130]	valid_0's binary_logloss: 0.0194297
[131]	valid_0's binary_logloss: 0.019482
[132]	valid_0's binary_logloss: 0.0194868
[133]	valid_0's binary_logloss: 0.0195556
[134]	valid_0's binary_logloss: 0.0196581
[135]	valid_0's binary_logloss: 0.0196246
[136]	valid_0's binary_logloss: 0.019638
[137]	valid_0's binary_logloss: 0.0196289
[138]	valid_0's binary_logloss: 0.0196282
[139]	valid_0's binary_logloss: 0.0197011
[140]	valid_0's binary_logloss: 0.0197456
[141]	valid_0's binary_logloss: 0.0197086
[142]	valid_0's binary_logloss: 0.0196001
[143]	valid_0's binary_logloss: 0.0195976
[144]	valid_0's binary_logloss: 0.0195723
[145]	valid_0's binary_logloss: 0.0195214
[146]	valid_0's binary_logloss: 0.0195077
[147]	valid_0's binary_logloss: 0.0194809

Trening klas:  48%|████▊     | 239/500 [29:24<28:20,  6.52s/klasa, klasa=class_239, F1_klasy=0.5161, F1_macro=0.7239, drzewa=119]

[148]	valid_0's binary_logloss: 0.0196284
[149]	valid_0's binary_logloss: 0.0197596

Trening klas:  48%|████▊     | 240/500 [29:24<34:04,  7.87s/klasa, klasa=class_239, F1_klasy=0.5161, F1_macro=0.7239, drzewa=119]

[1]	valid_0's binary_logloss: 0.166742
[2]	valid_0's binary_logloss: 0.161561
[3]	valid_0's binary_logloss: 0.155054
[4]	valid_0's binary_logloss: 0.151827
[5]	valid_0's binary_logloss: 0.148351
[6]	valid_0's binary_logloss: 0.145068
[7]	valid_0's binary_logloss: 0.142353
[8]	valid_0's binary_logloss: 0.140573
[9]	valid_0's binary_logloss: 0.138196
[10]	valid_0's binary_logloss: 0.136632
[11]	valid_0's binary_logloss: 0.134449
[12]	valid_0's binary_logloss: 0.132482
[13]	valid_0's binary_logloss: 0.129843
[14]	valid_0's binary_logloss: 0.127794
[15]	valid_0's binary_logloss: 0.126231
[16]	valid_0's binary_logloss: 0.124938
[17]	valid_0's binary_logloss: 0.123011
[18]	valid_0's binary_logloss: 0.122307
[19]	valid_0's binary_logloss: 0.120988
[20]	valid_0's binary_logloss: 0.119432
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.117971
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.116826
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.115589
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.114528
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.113758
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.112848
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.112395
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.111779
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.111513
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.111269
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.110579
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.110036
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.109416
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.109238
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.108803
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.108495
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.1078
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.10752
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.107224
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.106987
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.106402
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.10615
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.105881
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.105625
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.105434
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.105184
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.10496
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.10493
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.104787
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.10477
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.104828
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.104861
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.104896
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.104903
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.104844
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.104724
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.104652
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.104561
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.104745
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.104652
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.104679
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.10471
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.104671
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.105028
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.104784
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.104549
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.104669
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.104421
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.104186
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.104223
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.104027
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.103513
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.103175
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.102903
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.102949
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.103087
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.102972
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.103008
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.103136
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.103177
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.102932
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.102909
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.102879
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.102829
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.103031
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.10281
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.102565
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.102393
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.102573
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.102473
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.102439
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.102553
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.102487
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.102691
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.10288
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.102593
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.102341
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.102188
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.102039
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.101923
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.101812
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.101828
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.101928
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.102002
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.102141
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.102441
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.102701
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.102815
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.103122
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.103406
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.103527
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 0.103638
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 0.103654
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 0.103664
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 0.103815
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[116]	valid_0's binary_logloss: 0.103882
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[117]	valid_0's binary_logloss: 0.103908
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[118]	valid_0's binary_logloss: 0.103998
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[119]	valid_0's binary_logloss: 0.104157
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[120]	valid_0's binary_logloss: 0.104377
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[121]	valid_0's binary_logloss: 0.104425
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[122]	valid_0's binary_logloss: 0.104581
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[123]	valid_0's binary_logloss: 0.10461
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[124]	valid_0's binary_logloss: 0.104651
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[125]	valid_0's binary_logloss: 0.104846
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[126]	valid_0's binary_logloss: 0.104628
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[127]	valid_0's binary_logloss: 0.10448
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[128]	valid_0's binary_logloss: 0.104633
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[129]	valid_0's binary_logloss: 0.104416

Trening klas:  48%|████▊     | 240/500 [29:30<34:04,  7.87s/klasa, klasa=class_240, F1_klasy=0.3896, F1_macro=0.7225, drzewa=101]




Trening klas:  48%|████▊     | 241/500 [29:30<31:10,  7.22s/klasa, klasa=class_240, F1_klasy=0.3896, F1_macro=0.7225, drzewa=101]

[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[130]	valid_0's binary_logloss: 0.104642
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[131]	valid_0's binary_logloss: 0.10456
[1]	valid_0's binary_logloss: 0.0151647
[2]	valid_0's binary_logloss: 0.0144077
[3]	valid_0's binary_logloss: 0.013692
[4]	valid_0's binary_logloss: 0.01301
[5]	valid_0's binary_logloss: 0.0123648
[6]	valid_0's binary_logloss: 0.0118227
[7]	valid_0's binary_logloss: 0.0112691
[8]	valid_0's binary_logloss: 0.010714
[9]	valid_0's binary_logloss: 0.0102157
[10]	valid_0's binary_logloss: 0.0097082
[11]	valid_0's binary_logloss: 0.0092562
[12]	valid_0's binary_logloss: 0.0088616
[13]	valid_0's binary_logloss: 0.00842595
[14]	valid_0's binary_logloss: 0.00800711
[15]	valid_0's binary_logloss: 0.00766746
[16]	valid_0's binary_logloss: 0.00735221
[17]	valid_0's binary_logloss: 0.00705503
[18]	valid_0's binary_logloss: 0.00680999
[19]	valid_0's binary_logloss: 0.00654427
[20]	valid_0's binary_logloss: 0.00629361
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.00601836
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.00575734
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.00550378
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.00529603
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.00503583
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.00477656
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.00453159
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.0043671
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.00414652
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.00397551
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.00377419
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.00358128
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.00340032
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.00323077
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.00306581
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.00295111
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.00282966
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.00271229
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.00259042
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.00248943
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.00238181
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.002283
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.00219799
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.00211815
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.00204229
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.0019715
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.00190541
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.00184245
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.00177073
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.00171661
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.00166206
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.00160847
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.00156898
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.00151752
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.00146595
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.0013763
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.00131052
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.00124336
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.00118214
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.00112791
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.00108924
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.0010476
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.00100105
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.000966784
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.000926852
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.000901532
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.000855066
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.00082769
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.000784864
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.000757263
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.000724053
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.000691135
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.000666427
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.000636131
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.000607562
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.00058568
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.000557371
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.000539199
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.000512798
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.000488225
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.000471253
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.000455554
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.000435083
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.000416805
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.000401359
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.000383982
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.000367553
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.000352039
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.000337376
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.000321774
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.000308414
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.000295832
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.00028389
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.000272342
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.000261684
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.000251965
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.000242194
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.000233407
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.000221416
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.000211875
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.000201542
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.000192348
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.000185003
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.000176916
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.000168551
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.000161448
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.000155137
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.000149226
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.000143347
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.000137616
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.000129372
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 0.000123819
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 0.000119352
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 0.000114447
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 0.000110628
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[116]	valid_0's binary_logloss: 0.000107745
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[117]	valid_0's binary_logloss: 0.000103426
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[118]	valid_0's binary_logloss: 9.81273e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[119]	valid_0's binary_logloss: 9.51208e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[120]	valid_0's binary_logloss: 9.32213e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[121]	valid_0's binary_logloss: 8.96647e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[122]	valid_0's binary_logloss: 8.68142e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[123]	valid_0's binary_logloss: 8.44596e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[124]	valid_0's binary_logloss: 8.22733e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[125]	valid_0's binary_logloss: 7.93047e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[126]	valid_0's binary_logloss: 7.62842e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[127]	valid_0's binary_logloss: 7.34203e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[128]	valid_0's binary_logloss: 7.13366e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[129]	valid_0's binary_logloss: 6.93738e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[130]	valid_0's binary_logloss: 6.6485e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[131]	valid_0's binary_logloss: 6.47213e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[132]	valid_0's binary_logloss: 6.24462e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[133]	valid_0's binary_logloss: 6.07702e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[134]	valid_0's binary_logloss: 5.90416e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[135]	valid_0's binary_logloss: 5.73512e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[136]	valid_0's binary_logloss: 5.61821e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[137]	valid_0's binary_logloss: 5.50557e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[138]	valid_0's binary_logloss: 5.41444e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[139]	valid_0's binary_logloss: 5.28033e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[140]	valid_0's binary_logloss: 5.15818e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[141]	valid_0's binary_logloss: 4.95334e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[142]	valid_0's binary_logloss: 4.746e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[143]	valid_0's binary_logloss: 4.567e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[144]	valid_0's binary_logloss: 4.38255e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[145]	valid_0's binary_logloss: 4.21685e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[146]	valid_0's binary_logloss: 4.19315e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[147]	valid_0's binary_logloss: 4.1315e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[148]	valid_0's binary_logloss: 4.08643e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[149]	valid_0's binary_logloss: 4.00839e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[150]	valid_0's binary_logloss: 3.9096e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[151]	valid_0's binary_logloss: 3.76977e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[152]	valid_0's binary_logloss: 3.63357e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[153]	valid_0's binary_logloss: 3.51936e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[154]	valid_0's binary_logloss: 3.41372e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[155]	valid_0's binary_logloss: 3.3003e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[156]	valid_0's binary_logloss: 3.20479e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[157]	valid_0's binary_logloss: 3.12199e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[158]	valid_0's binary_logloss: 3.07883e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[159]	valid_0's binary_logloss: 2.99506e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[160]	valid_0's binary_logloss: 2.92966e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[161]	valid_0's binary_logloss: 2.8839e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[162]	valid_0's binary_logloss: 2.85317e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[163]	valid_0's binary_logloss: 2.82146e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[164]	valid_0's binary_logloss: 2.79693e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[165]	valid_0's binary_logloss: 2.75026e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[166]	valid_0's binary_logloss: 2.69875e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[167]	valid_0's binary_logloss: 2.63652e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[168]	valid_0's binary_logloss: 2.57724e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[169]	valid_0's binary_logloss: 2.55314e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[170]	valid_0's binary_logloss: 2.525e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[171]	valid_0's binary_logloss: 2.49757e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[172]	valid_0's binary_logloss: 2.46369e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[173]	valid_0's binary_logloss: 2.46071e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[174]	valid_0's binary_logloss: 2.43788e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[175]	valid_0's binary_logloss: 2.39113e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[176]	valid_0's binary_logloss: 2.37367e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[177]	valid_0's binary_logloss: 2.34611e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[178]	valid_0's binary_logloss: 2.32e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[179]	valid_0's binary_logloss: 2.29132e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[180]	valid_0's binary_logloss: 2.26812e-05

[292]	valid_0's binary_logloss: 7.8376e-06
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[293]	valid_0's binary_logloss: 7.8279e-06
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[294]	valid_0's binary_logloss: 7.83877e-06
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[295]	valid_0's binary_logloss: 7.82959e-06
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[296]	valid_0's binary_logloss: 7.8469e-06
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[297]	valid_0's binary_logloss: 7.85113e-06
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[298]	valid_0's binary_logloss: 7.85381e-06
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[299]	valid_0's binary_logloss: 7.88162e-06
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[300]	valid_0's binary_logloss: 7.91191e-06

Trening klas:  48%|████▊     | 241/500 [29:36<31:10,  7.22s/klasa, klasa=class_241, F1_klasy=1.0000, F1_macro=0.7236, drzewa=293]




Trening klas:  48%|████▊     | 242/500 [29:36<30:18,  7.05s/klasa, klasa=class_241, F1_klasy=1.0000, F1_macro=0.7236, drzewa=293]

[1]	valid_0's binary_logloss: 0.0181527
[2]	valid_0's binary_logloss: 0.0176526
[3]	valid_0's binary_logloss: 0.0171196
[4]	valid_0's binary_logloss: 0.0164484
[5]	valid_0's binary_logloss: 0.0158173
[6]	valid_0's binary_logloss: 0.0151895
[7]	valid_0's binary_logloss: 0.0146467
[8]	valid_0's binary_logloss: 0.0141393
[9]	valid_0's binary_logloss: 0.0136123
[10]	valid_0's binary_logloss: 0.0131507
[11]	valid_0's binary_logloss: 0.012883
[12]	valid_0's binary_logloss: 0.0125022
[13]	valid_0's binary_logloss: 0.012259
[14]	valid_0's binary_logloss: 0.0119352
[15]	valid_0's binary_logloss: 0.0117151
[16]	valid_0's binary_logloss: 0.0112131
[17]	valid_0's binary_logloss: 0.0109343
[18]	valid_0's binary_logloss: 0.0105433
[19]	valid_0's binary_logloss: 0.0102815
[20]	valid_0's binary_logloss: 0.010022
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.00982146
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.00958787
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.00933515
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.00908068
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.00883048
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.00854276
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.0083318
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.00807729
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.00789811
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.00772804
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.00757587
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.00746384
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.00723759
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.00713728
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.00704806
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.00690394
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.00667795
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.00647676
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.00635289
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.00624243
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.00603877
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.00585673
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.00567205
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.00552199
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.00539341
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.00525574
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.0051857
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.00505696
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.00498767
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.00491654
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.00473886
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.00470472
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.00457037
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.00446953
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.00432585
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.00422532
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.00414973
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.00411209
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.00403501
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.00401824
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.00400868
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.0040078
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.00399886
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.00388886
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.00390599
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.00388664
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.00386086
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.00380725
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.00374973
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.00372907
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.00377243
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.00371282
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.00373663
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.00376002
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.00368965
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.00364552
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.00360191
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.00352709
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.00344447
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.0033765
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.00332889
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.00329667
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.00323792
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.00318668
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.00312057
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.00310624
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.00308536
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.00305025
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.00299264
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.00295537
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.00294231
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.00289665
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.00284946
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.00282711
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.00282067
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.00284283
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.00284065
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.00283909
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.00281788
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.00277546
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.00271719
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.00267823
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.00263791
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.00261761
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.00256635
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.00256467
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.00257844
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.0025719
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.00255803
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.00254626
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.00254248
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 0.00253519
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 0.00256348
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 0.00257775
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 0.00258674
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[116]	valid_0's binary_logloss: 0.00256463
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[117]	valid_0's binary_logloss: 0.00254204
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[118]	valid_0's binary_logloss: 0.002529
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[119]	valid_0's binary_logloss: 0.00250128
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[120]	valid_0's binary_logloss: 0.00248605
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[121]	valid_0's binary_logloss: 0.0024367
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[122]	valid_0's binary_logloss: 0.00245569
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[123]	valid_0's binary_logloss: 0.00240816
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[124]	valid_0's binary_logloss: 0.00236124
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[125]	valid_0's binary_logloss: 0.00232582
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[126]	valid_0's binary_logloss: 0.00231022
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[127]	valid_0's binary_logloss: 0.00230824
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[128]	valid_0's binary_logloss: 0.00231348
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[129]	valid_0's binary_logloss: 0.0022981
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[130]	valid_0's binary_logloss: 0.0023049
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[131]	valid_0's binary_logloss: 0.0023242
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[132]	valid_0's binary_logloss: 0.00234736
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[133]	valid_0's binary_logloss: 0.00236919
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[134]	valid_0's binary_logloss: 0.00239534
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[135]	valid_0's binary_logloss: 0.00239578
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[136]	valid_0's binary_logloss: 0.00237716
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[137]	valid_0's binary_logloss: 0.00239006
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[138]	valid_0's binary_logloss: 0.00238849
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[139]	valid_0's binary_logloss: 0.0023875
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[140]	valid_0's binary_logloss: 0.0023753
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[141]	valid_0's binary_logloss: 0.00238635
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[142]	valid_0's binary_logloss: 0.00238481
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[143]	valid_0's binary_logloss: 0.00238397
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[144]	valid_0's binary_logloss: 0.00237034
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[145]	valid_0's binary_logloss: 0.00239433
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[146]	valid_0's binary_logloss: 0.00241933
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[147]	valid_0's binary_logloss: 0.00241679
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[148]	valid_0's binary_logloss: 0.00244161
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[149]	valid_0's binary_logloss: 0.00247518
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[150]	valid_0's binary_logloss: 0.00250021
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

Trening klas:  48%|████▊     | 242/500 [29:41<30:18,  7.05s/klasa, klasa=class_242, F1_klasy=0.6667, F1_macro=0.7234, drzewa=129]




Trening klas:  49%|████▊     | 243/500 [29:41<26:47,  6.26s/klasa, klasa=class_242, F1_klasy=0.6667, F1_macro=0.7234, drzewa=129]

[151]	valid_0's binary_logloss: 0.00250388
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[152]	valid_0's binary_logloss: 0.0025118
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[153]	valid_0's binary_logloss: 0.00250219
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[154]	valid_0's binary_logloss: 0.002514
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[155]	valid_0's binary_logloss: 0.00252319
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[156]	valid_0's binary_logloss: 0.002485
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[157]	valid_0's binary_logloss: 0.00246052
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[158]	valid_0's binary_logloss: 0.00244487
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[159]	valid_0's binary_logloss: 0.0024214
[1]	valid_0's binary_logloss: 0.0513874
[2]	valid_0's binary_logloss: 0.0506112
[3]	valid_0's binary_logloss: 0.0499207
[4]	valid_0's binary_logloss: 0.0490935
[5]	valid_0's binary_logloss: 0.048398
[6]	valid_0's binary_logloss: 0.0503896
[7]	valid_0's binary_logloss: 0.0498615
[8]	valid_0's binary_logloss: 0.0492341
[9]	valid_0's binary_logloss: 0.0486522
[10]	valid_0's binary_logloss: 0.0479671
[11]	valid_0's binary_logloss: 0.0476322
[12]	valid_0's binary_logloss: 0.0470479
[13]	valid_0's binary_logloss: 0.0464162
[14]	valid_0's binary_logloss: 0.0459878
[15]	valid_0's binary_logloss: 0.0456075
[16]	valid_0's binary_logloss: 0.0451571
[17]	valid_0's binary_logloss: 0.0447804
[18]	valid_0's binary_logloss: 0.0443838
[19]	valid_0's binary_logloss: 0.0440267
[20]	valid_0's binary_logloss: 0.0437741
[21]	valid_0's binary_logloss: 0.0433825
[22]	valid_0's binary_logloss: 0.0431409
[23]	valid_0's binary_logloss: 0.0429092
[24]	valid_0's binary_logloss: 0.04252
[25]	valid_0's binary_logloss: 0.0422166
[26]	valid_0's binary_logloss: 0.0418272
[27]	valid_0's binary_logloss: 0.0413692
[28]	valid_0's binary_logloss: 0.0411512
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.0408886
[30]	valid_0's binary_logloss: 0.0407509
[31]	valid_0's binary_logloss: 0.0404692
[32]	valid_0's binary_logloss: 0.0400904
[33]	valid_0's binary_logloss: 0.0396568
[34]	valid_0's binary_logloss: 0.0394233
[35]	valid_0's binary_logloss: 0.0392677
[36]	valid_0's binary_logloss: 0.0390181
[37]	valid_0's binary_logloss: 0.0384036
[38]	valid_0's binary_logloss: 0.0379361
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.037701
[40]	valid_0's binary_logloss: 0.0374655
[41]	valid_0's binary_logloss: 0.037146
[42]	valid_0's binary_logloss: 0.0368956
[43]	valid_0's binary_logloss: 0.0367735
[44]	valid_0's binary_logloss: 0.0364804
[45]	valid_0's binary_logloss: 0.03631
[46]	valid_0's binary_logloss: 0.0361491
[47]	valid_0's binary_logloss: 0.035925
[48]	valid_0's binary_logloss: 0.0357864
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.0356108
[50]	valid_0's binary_logloss: 0.0355449
[51]	valid_0's binary_logloss: 0.0352175
[52]	valid_0's binary_logloss: 0.0350401
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.0349516
[54]	valid_0's binary_logloss: 0.034773
[55]	valid_0's binary_logloss: 0.0347528
[56]	valid_0's binary_logloss: 0.0346926
[57]	valid_0's binary_logloss: 0.0345356
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.0343421
[59]	valid_0's binary_logloss: 0.034276
[60]	valid_0's binary_logloss: 0.0340615
[61]	valid_0's binary_logloss: 0.0340412
[62]	valid_0's binary_logloss: 0.0340131
[63]	valid_0's binary_logloss: 0.0340559
[64]	valid_0's binary_logloss: 0.0339831
[65]	valid_0's binary_logloss: 0.0340701
[66]	valid_0's binary_logloss: 0.0339568
[67]	valid_0's binary_logloss: 0.0338245
[68]	valid_0's binary_logloss: 0.0337161
[69]	valid_0's binary_logloss: 0.0337583
[70]	valid_0's binary_logloss: 0.0337122
[71]	valid_0's binary_logloss: 0.033687
[72]	valid_0's binary_logloss: 0.0337163
[73]	valid_0's binary_logloss: 0.0337365
[74]	valid_0's binary_logloss: 0.0337499
[75]	valid_0's binary_logloss: 0.0337998
[76]	valid_0's binary_logloss: 0.0337985
[77]	valid_0's binary_logloss: 0.033759
[78]	valid_0's binary_logloss: 0.0336718
[79]	valid_0's binary_logloss: 0.0336328
[80]	valid_0's binary_logloss: 0.0335531
[81]	valid_0's binary_logloss: 0.0334939
[82]	valid_0's binary_logloss: 0.0334255
[83]	valid_0's binary_logloss: 0.0335103
[84]	valid_0's binary_logloss: 0.0334448
[85]	valid_0's binary_logloss: 0.0335082
[86]	valid_0's binary_logloss: 0.0334558
[87]	valid_0's binary_logloss: 0.0334363
[88]	valid_0's binary_logloss: 0.0335288
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.0335406
[90]	valid_0's binary_logloss: 0.0334471
[91]	valid_0's binary_logloss: 0.0334552
[92]	valid_0's binary_logloss: 0.0335032
[93]	valid_0's binary_logloss: 0.0335071
[94]	valid_0's binary_logloss: 0.0335021
[95]	valid_0's binary_logloss: 0.0334609
[96]	valid_0's binary_logloss: 0.0334823
[97]	valid_0's binary_logloss: 0.0336043
[98]	valid_0's binary_logloss: 0.0336198
[99]	valid_0's binary_logloss: 0.0337926
[100]	valid_0's binary_logloss: 0.0338441
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.0340086
[102]	valid_0's binary_logloss: 0.0339859
[103]	valid_0's binary_logloss: 0.0340583
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.0341588
[105]	valid_0's binary_logloss: 0.0342518
[106]	valid_0's binary_logloss: 0.0343022
[107]	valid_0's binary_logloss: 0.0344076
[108]	valid_0's binary_logloss: 0.034508
[109]	valid_0's binary_logloss: 0.0344412
[110]	valid_0's binary_logloss: 0.034563
[111]	valid_0's binary_logloss: 0.034567

Trening klas:  49%|████▊     | 243/500 [29:48<26:47,  6.26s/klasa, klasa=class_243, F1_klasy=0.4667, F1_macro=0.7224, drzewa=82]




Trening klas:  49%|████▉     | 244/500 [29:48<28:16,  6.63s/klasa, klasa=class_243, F1_klasy=0.4667, F1_macro=0.7224, drzewa=82]

[112]	valid_0's binary_logloss: 0.0345912
[1]	valid_0's binary_logloss: 0.0140091
[2]	valid_0's binary_logloss: 0.0133207
[3]	valid_0's binary_logloss: 0.0126695
[4]	valid_0's binary_logloss: 0.0120531
[5]	valid_0's binary_logloss: 0.0114737
[6]	valid_0's binary_logloss: 0.0109224
[7]	valid_0's binary_logloss: 0.0103976
[8]	valid_0's binary_logloss: 0.00990357
[9]	valid_0's binary_logloss: 0.00943128
[10]	valid_0's binary_logloss: 0.00898369
[11]	valid_0's binary_logloss: 0.00855944
[12]	valid_0's binary_logloss: 0.0081596
[13]	valid_0's binary_logloss: 0.00778571
[14]	valid_0's binary_logloss: 0.00742465
[15]	valid_0's binary_logloss: 0.00708216
[16]	valid_0's binary_logloss: 0.00676572
[17]	valid_0's binary_logloss: 0.00645937
[18]	valid_0's binary_logloss: 0.00616743
[19]	valid_0's binary_logloss: 0.00589078
[20]	valid_0's binary_logloss: 0.00562869
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.00540504
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.00516604
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.00493968
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.00471531
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.00450991
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.00431565
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.00413154
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.00395741
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.00379255
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.00363642
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.00348947
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.00335074
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.00321984
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.00309641
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.00297985
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.002858
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.00270154
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.00259386
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.00245439
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.00232552
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.00224013
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.00215733
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.00207469
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.00200058
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.00192076
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.00185076
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.0017875
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.00172396
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.00166596
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.00160626
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.00154924
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.00150525
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.00145338
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.00138577
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.00134134
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.00127853
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.00121733
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.00116819
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.00112475
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.00107045
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.00103156
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.000999147
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.000968758
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.000940304
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.000906579
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.000857008
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.000816168
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.000776113
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.000741561
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.000706358
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.000679806
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.000654248
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.000630068
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.000607535
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.000585867
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.000564401
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.000540908
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.00051512
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.000490815
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.000472824
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.000448156
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.000432375
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.000408738
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.000394946
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.000382845
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.000362074
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.000343179
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.00032931
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.000312656
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.000295826
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.000280859
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.000267258
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.00025439
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.000241974
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.000230297
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.000219437
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.000208839
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.000198598
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.000188978
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.000179935
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.000171554
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.000163494
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.000155931
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.000148809
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.000142001
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.000136688
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.000131779
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.00012682
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.000122469
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.000118451
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.000113832
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 0.000109843
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 0.000105496
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 0.000103535
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 9.92554e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[116]	valid_0's binary_logloss: 9.52681e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[117]	valid_0's binary_logloss: 9.16676e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[118]	valid_0's binary_logloss: 8.83804e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[119]	valid_0's binary_logloss: 8.45645e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[120]	valid_0's binary_logloss: 8.16865e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[121]	valid_0's binary_logloss: 7.92081e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[122]	valid_0's binary_logloss: 7.68114e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[123]	valid_0's binary_logloss: 7.47986e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[124]	valid_0's binary_logloss: 7.25937e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[125]	valid_0's binary_logloss: 7.03789e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[126]	valid_0's binary_logloss: 6.77981e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[127]	valid_0's binary_logloss: 6.53712e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[128]	valid_0's binary_logloss: 6.29906e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[129]	valid_0's binary_logloss: 5.99287e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[130]	valid_0's binary_logloss: 5.75536e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[131]	valid_0's binary_logloss: 5.50178e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[132]	valid_0's binary_logloss: 5.28267e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[133]	valid_0's binary_logloss: 5.13118e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[134]	valid_0's binary_logloss: 4.89279e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[135]	valid_0's binary_logloss: 4.70262e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[136]	valid_0's binary_logloss: 4.53802e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[137]	valid_0's binary_logloss: 4.37885e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[138]	valid_0's binary_logloss: 4.24032e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[139]	valid_0's binary_logloss: 4.09419e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[140]	valid_0's binary_logloss: 3.96552e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[141]	valid_0's binary_logloss: 3.80345e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[142]	valid_0's binary_logloss: 3.64645e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[143]	valid_0's binary_logloss: 3.50771e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[144]	valid_0's binary_logloss: 3.379e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[145]	valid_0's binary_logloss: 3.25095e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[146]	valid_0's binary_logloss: 3.1577e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[147]	valid_0's binary_logloss: 3.07825e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[148]	valid_0's binary_logloss: 3.03164e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[149]	valid_0's binary_logloss: 2.96509e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[150]	valid_0's binary_logloss: 2.855e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[151]	valid_0's binary_logloss: 2.79896e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[152]	valid_0's binary_logloss: 2.72055e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[153]	valid_0's binary_logloss: 2.65108e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[154]	valid_0's binary_logloss: 2.60479e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[155]	valid_0's binary_logloss: 2.56082e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[156]	valid_0's binary_logloss: 2.48529e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[157]	valid_0's binary_logloss: 2.41836e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[158]	valid_0's binary_logloss: 2.3505e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[159]	valid_0's binary_logloss: 2.2855e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[160]	valid_0's binary_logloss: 2.22622e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[161]	valid_0's binary_logloss: 2.16878e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[162]	valid_0's binary_logloss: 2.16336e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[163]	valid_0's binary_logloss: 2.15804e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[164]	valid_0's binary_logloss: 2.10586e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[165]	valid_0's binary_logloss: 2.11119e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[166]	valid_0's binary_logloss: 2.09823e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[167]	valid_0's binary_logloss: 2.04842e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[168]	valid_0's binary_logloss: 2.04039e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[169]	valid_0's binary_logloss: 2.05082e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[170]	valid_0's binary_logloss: 2.0462e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[171]	valid_0's binary_logloss: 2.05498e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[172]	valid_0's binary_logloss: 2.01073e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[173]	valid_0's binary_logloss: 2.0028e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[174]	valid_0's binary_logloss: 1.98447e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[175]	valid_0's binary_logloss: 1.94338e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[176]	valid_0's binary_logloss: 1.9166e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[177]	valid_0's binary_logloss: 1.8638e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[178]	valid_0's binary_logloss: 1.82522e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[179]	valid_0's binary_logloss: 1.77655e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[180]	valid_0's binary_logloss: 1.73082e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[181]	valid_0's binary_logloss: 1.71178e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

Trening klas:  49%|████▉     | 244/500 [29:54<28:16,  6.63s/klasa, klasa=class_244, F1_klasy=1.0000, F1_macro=0.7235, drzewa=300]




Trening klas:  49%|████▉     | 245/500 [29:54<27:44,  6.53s/klasa, klasa=class_244, F1_klasy=1.0000, F1_macro=0.7235, drzewa=300]

[296]	valid_0's binary_logloss: 7.12828e-06
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[297]	valid_0's binary_logloss: 7.11376e-06
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[298]	valid_0's binary_logloss: 7.08267e-06
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[299]	valid_0's binary_logloss: 7.05646e-06
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[300]	valid_0's binary_logloss: 7.03668e-06
[1]	valid_0's binary_logloss: 0.212222
[2]	valid_0's binary_logloss: 0.201377
[3]	valid_0's binary_logloss: 0.191477
[4]	valid_0's binary_logloss: 0.182768
[5]	valid_0's binary_logloss: 0.175667
[6]	valid_0's binary_logloss: 0.172109
[7]	valid_0's binary_logloss: 0.165387
[8]	valid_0's binary_logloss: 0.158924
[9]	valid_0's binary_logloss: 0.154072
[10]	valid_0's binary_logloss: 0.149265
[11]	valid_0's binary_logloss: 0.144436
[12]	valid_0's binary_logloss: 0.140505
[13]	valid_0's binary_logloss: 0.13649
[14]	valid_0's binary_logloss: 0.133153
[15]	valid_0's binary_logloss: 0.129991
[16]	valid_0's binary_logloss: 0.126683
[17]	valid_0's binary_logloss: 0.12365
[18]	valid_0's binary_logloss: 0.120847
[19]	valid_0's binary_logloss: 0.118349
[20]	valid_0's binary_logloss: 0.116019
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.113804
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.11209
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.110317
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.108669
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.107119
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.105612
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.104291
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.103119
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.10199
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.100895
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.0994803
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.0982116
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.0971547
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.0961772
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.095308
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.0946998
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.0941483
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.0935415
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.0927771
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.092133
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.0915957
[42]	valid_0's binary_logloss: 0.090842
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.0903758
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.0898505
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.0894481
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.0889365
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.0886351
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.0883401
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.0880656
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.0876944
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.0872172
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.0867943
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.0864429
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.0863325
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.0860167
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.0855025
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.085122
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.0847126
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.0844521
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.0841477
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.0839287
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.0838881
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.0837962
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.0836391
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.0836309
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.0835671
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.0834944
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.0834512
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.0832424
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.0831901
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.0832159
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.08327
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.0832869
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.0834036
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.0833569
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.0832834
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.0834437
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.0833972
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.0834497
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.0835262
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.0834395
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.083543
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.0837224
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.0837028
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.0838286
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.0838255
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.0838645
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.0837842
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.0837289
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.0837715
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.0838327
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.0840007
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.0841453
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.0842836
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.0844076
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.0847248
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.0849419
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.0850864
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.0853175
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.0854936

Trening klas:  49%|████▉     | 245/500 [30:01<27:44,  6.53s/klasa, klasa=class_245, F1_klasy=0.5371, F1_macro=0.7227, drzewa=70]




Trening klas:  49%|████▉     | 246/500 [30:01<27:53,  6.59s/klasa, klasa=class_245, F1_klasy=0.5371, F1_macro=0.7227, drzewa=70]

[1]	valid_0's binary_logloss: 0.0140091
[2]	valid_0's binary_logloss: 0.0133207
[3]	valid_0's binary_logloss: 0.0126695
[4]	valid_0's binary_logloss: 0.0120531
[5]	valid_0's binary_logloss: 0.0114737
[6]	valid_0's binary_logloss: 0.0109224
[7]	valid_0's binary_logloss: 0.0103976
[8]	valid_0's binary_logloss: 0.00990357
[9]	valid_0's binary_logloss: 0.00943128
[10]	valid_0's binary_logloss: 0.00898369
[11]	valid_0's binary_logloss: 0.00855944
[12]	valid_0's binary_logloss: 0.0081596
[13]	valid_0's binary_logloss: 0.00778571
[14]	valid_0's binary_logloss: 0.00742465
[15]	valid_0's binary_logloss: 0.00708216
[16]	valid_0's binary_logloss: 0.00676572
[17]	valid_0's binary_logloss: 0.00645937
[18]	valid_0's binary_logloss: 0.00616743
[19]	valid_0's binary_logloss: 0.00589078
[20]	valid_0's binary_logloss: 0.00562869
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.00540504
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.00516604
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.00493968
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.00471531
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.00450991
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.00431565
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.00413154
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.00395741
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.00379255
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.00363642
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.00348947
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.00335074
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.00321984
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.00309641
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.00297985
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.002858
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.00270154
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.00259386
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.00245439
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.00232552
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.00224013
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.00215733
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.00207469
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.00200058
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.00192076
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.00185076
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.0017875
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.00172396
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.00166596
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.00160626
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.00154924
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.00150525
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.00145338
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.00138577
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.00134134
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.00127853
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.00121733
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.00116819
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.00112475
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.00107045
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.00103156
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.000999147
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.000968758
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.000940304
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.000906579
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.000857008
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.000816168
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.000776113
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.000741561
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.000706358
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.000679806
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.000654248
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.000630068
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.000607535
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.000585867
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.000564401
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.000540908
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.00051512
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.000490815
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.000472824
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.000448156
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.000432375
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.000408738
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.000394946
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.000382845
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.000362074
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.000343179
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.00032931
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.000312656
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.000295826
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.000280859
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.000267258
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.00025439
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.000241974
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.000230297
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.000219437
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.000208839
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.000198598
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.000188978
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.000179935
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.000171554
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.000163494
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.000155931
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.000148809
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.000142001
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.000136688
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.000131779
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.00012682
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.000122469
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.000118451
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.000113832
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 0.000109843
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 0.000105496
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 0.000103535
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 9.92554e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[116]	valid_0's binary_logloss: 9.52681e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[117]	valid_0's binary_logloss: 9.16676e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[118]	valid_0's binary_logloss: 8.83804e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[119]	valid_0's binary_logloss: 8.45645e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[120]	valid_0's binary_logloss: 8.16865e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[121]	valid_0's binary_logloss: 7.92081e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[122]	valid_0's binary_logloss: 7.68114e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[123]	valid_0's binary_logloss: 7.47986e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[124]	valid_0's binary_logloss: 7.25937e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[125]	valid_0's binary_logloss: 7.03789e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[126]	valid_0's binary_logloss: 6.77981e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[127]	valid_0's binary_logloss: 6.53712e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[128]	valid_0's binary_logloss: 6.29906e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[129]	valid_0's binary_logloss: 5.99287e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[130]	valid_0's binary_logloss: 5.75536e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[131]	valid_0's binary_logloss: 5.50178e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[132]	valid_0's binary_logloss: 5.28267e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[133]	valid_0's binary_logloss: 5.13118e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[134]	valid_0's binary_logloss: 4.89279e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[135]	valid_0's binary_logloss: 4.70262e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[136]	valid_0's binary_logloss: 4.53802e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[137]	valid_0's binary_logloss: 4.37885e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[138]	valid_0's binary_logloss: 4.24032e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[139]	valid_0's binary_logloss: 4.09419e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[140]	valid_0's binary_logloss: 3.96552e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[141]	valid_0's binary_logloss: 3.80345e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[142]	valid_0's binary_logloss: 3.64645e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[143]	valid_0's binary_logloss: 3.50771e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[144]	valid_0's binary_logloss: 3.379e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[145]	valid_0's binary_logloss: 3.25095e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[146]	valid_0's binary_logloss: 3.1577e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[147]	valid_0's binary_logloss: 3.07825e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[148]	valid_0's binary_logloss: 3.03164e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[149]	valid_0's binary_logloss: 2.96509e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[150]	valid_0's binary_logloss: 2.855e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[151]	valid_0's binary_logloss: 2.79896e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[152]	valid_0's binary_logloss: 2.72055e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[153]	valid_0's binary_logloss: 2.65108e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[154]	valid_0's binary_logloss: 2.60479e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[155]	valid_0's binary_logloss: 2.56082e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[156]	valid_0's binary_logloss: 2.48529e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[157]	valid_0's binary_logloss: 2.41836e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[158]	valid_0's binary_logloss: 2.3505e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[159]	valid_0's binary_logloss: 2.2855e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[160]	valid_0's binary_logloss: 2.22622e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[161]	valid_0's binary_logloss: 2.16878e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[162]	valid_0's binary_logloss: 2.16336e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[163]	valid_0's binary_logloss: 2.15804e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[164]	valid_0's binary_logloss: 2.10586e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[165]	valid_0's binary_logloss: 2.11119e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[166]	valid_0's binary_logloss: 2.09823e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[167]	valid_0's binary_logloss: 2.04842e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[168]	valid_0's binary_logloss: 2.04039e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[169]	valid_0's binary_logloss: 2.05082e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[170]	valid_0's binary_logloss: 2.0462e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[171]	valid_0's binary_logloss: 2.05498e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[172]	valid_0's binary_logloss: 2.01073e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[173]	valid_0's binary_logloss: 2.0028e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[174]	valid_0's binary_logloss: 1.98447e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[175]	valid_0's binary_logloss: 1.94338e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[176]	valid_0's binary_logloss: 1.9166e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[177]	valid_0's binary_logloss: 1.8638e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[178]	valid_0's binary_logloss: 1.82522e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[179]	valid_0's binary_logloss: 1.77655e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[180]	valid_0's binary_logloss: 1.73082e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[181]	valid_0's binary_logloss: 1.71178e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[182]	valid_0's binary_logloss: 1.69371e-05

Trening klas:  49%|████▉     | 246/500 [30:07<27:53,  6.59s/klasa, klasa=class_246, F1_klasy=1.0000, F1_macro=0.7239, drzewa=300]

[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[292]	valid_0's binary_logloss: 7.21964e-06
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[293]	valid_0's binary_logloss: 7.20809e-06
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[294]	valid_0's binary_logloss: 7.16608e-06
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[295]	valid_0's binary_logloss: 7.15522e-06
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[296]	valid_0's binary_logloss: 7.12828e-06
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[297]	valid_0's binary_logloss: 7.11376e-06
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[298]	valid_0's binary_logloss: 7.08267e-06
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[299]	valid_0's binary_logloss: 7.05646e-06
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[300]	valid_0's binary_logloss: 7.03668e-06

Trening klas:  49%|████▉     | 247/500 [30:07<27:05,  6.42s/klasa, klasa=class_246, F1_klasy=1.0000, F1_macro=0.7239, drzewa=300]

[1]	valid_0's binary_logloss: 0.0152799
[2]	valid_0's binary_logloss: 0.0145659
[3]	valid_0's binary_logloss: 0.013935
[4]	valid_0's binary_logloss: 0.0132971
[5]	valid_0's binary_logloss: 0.0126515
[6]	valid_0's binary_logloss: 0.012066
[7]	valid_0's binary_logloss: 0.0115092
[8]	valid_0's binary_logloss: 0.0109898
[9]	valid_0's binary_logloss: 0.0104902
[10]	valid_0's binary_logloss: 0.010013
[11]	valid_0's binary_logloss: 0.00953056
[12]	valid_0's binary_logloss: 0.00907615
[13]	valid_0's binary_logloss: 0.00864014
[14]	valid_0's binary_logloss: 0.00823545
[15]	valid_0's binary_logloss: 0.00784189
[16]	valid_0's binary_logloss: 0.0074699
[17]	valid_0's binary_logloss: 0.00710943
[18]	valid_0's binary_logloss: 0.00678832
[19]	valid_0's binary_logloss: 0.00648374
[20]	valid_0's binary_logloss: 0.00617234
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.00588396
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.00560677
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.00534418
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.00509298
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.00487227
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.00463607
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.0044169
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.00422083
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.00402718
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.00383534
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.00365364
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.00350138
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.00333462
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.00318036
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.00302853
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.0029011
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.00276531
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.00263222
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.00252329
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.00240605
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.00230938
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.00219798
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.00210772
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.00202322
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.00193436
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.00184264
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.00177321
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.00167853
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.00159467
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.0015258
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.00147017
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.00141771
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.00136106
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.00130566
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.00126037
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.0012088
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.00115311
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.0010992
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.00104893
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.000998366
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.0009486
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.000909574
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.000878509
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.000837164
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.000797288
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.000759228
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.000723594
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.000692038
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.000659789
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.000628242
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.000604195
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.00057543
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.000552981
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.000531791
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.000507618
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.000483233
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.000463813
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.000446509
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.000429259
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.000408759
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.000390924
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.000377179
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.000360857
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.00034896
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.000331945
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.000317456
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.000304874
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.000295771
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.00028402
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.00027823
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.000265431
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.000253523
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.000242085
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.000235229
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.000228671
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.00021797
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.000206687
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.000197963
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.000190148
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.000182946
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.000176775
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.000169173
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.000165076
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.00015855
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.000155191
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.00015167
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.000145483
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.000139303
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.000136635
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.000131173
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.000125471
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 0.000123825
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 0.000122518
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 0.000118084
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 0.000117085
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[116]	valid_0's binary_logloss: 0.000116643
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[117]	valid_0's binary_logloss: 0.000115786
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[118]	valid_0's binary_logloss: 0.000110377
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[119]	valid_0's binary_logloss: 0.000105669
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[120]	valid_0's binary_logloss: 0.000100855
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[121]	valid_0's binary_logloss: 0.000100279
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[122]	valid_0's binary_logloss: 0.000100591
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[123]	valid_0's binary_logloss: 0.000100318
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[124]	valid_0's binary_logloss: 9.69356e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[125]	valid_0's binary_logloss: 9.28529e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[126]	valid_0's binary_logloss: 9.18286e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[127]	valid_0's binary_logloss: 8.97909e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[128]	valid_0's binary_logloss: 9.02715e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[129]	valid_0's binary_logloss: 8.77077e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[130]	valid_0's binary_logloss: 8.76953e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[131]	valid_0's binary_logloss: 8.70665e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[132]	valid_0's binary_logloss: 8.78678e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[133]	valid_0's binary_logloss: 8.46284e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[134]	valid_0's binary_logloss: 8.53952e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[135]	valid_0's binary_logloss: 8.56739e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[136]	valid_0's binary_logloss: 8.38945e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[137]	valid_0's binary_logloss: 8.46587e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[138]	valid_0's binary_logloss: 8.21175e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[139]	valid_0's binary_logloss: 8.28504e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[140]	valid_0's binary_logloss: 8.1788e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[141]	valid_0's binary_logloss: 7.9669e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[142]	valid_0's binary_logloss: 7.8391e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[143]	valid_0's binary_logloss: 7.93089e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[144]	valid_0's binary_logloss: 8.09573e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[145]	valid_0's binary_logloss: 8.02145e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[146]	valid_0's binary_logloss: 8.10858e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[147]	valid_0's binary_logloss: 7.88807e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[148]	valid_0's binary_logloss: 7.50847e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[149]	valid_0's binary_logloss: 7.16341e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[150]	valid_0's binary_logloss: 7.21565e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[151]	valid_0's binary_logloss: 7.28635e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[152]	valid_0's binary_logloss: 7.25211e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[153]	valid_0's binary_logloss: 7.32897e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[154]	valid_0's binary_logloss: 7.18639e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[155]	valid_0's binary_logloss: 7.2296e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[156]	valid_0's binary_logloss: 6.993e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[157]	valid_0's binary_logloss: 7.08624e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[158]	valid_0's binary_logloss: 6.89639e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[159]	valid_0's binary_logloss: 6.98256e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[160]	valid_0's binary_logloss: 6.84324e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[161]	valid_0's binary_logloss: 7.00256e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[162]	valid_0's binary_logloss: 7.11775e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[163]	valid_0's binary_logloss: 7.25067e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[164]	valid_0's binary_logloss: 7.43585e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[165]	valid_0's binary_logloss: 7.54632e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[166]	valid_0's binary_logloss: 7.53781e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[167]	valid_0's binary_logloss: 7.68963e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[168]	valid_0's binary_logloss: 7.67959e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[169]	valid_0's binary_logloss: 7.65211e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[170]	valid_0's binary_logloss: 7.83491e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[171]	valid_0's binary_logloss: 8.02624e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[172]	valid_0's binary_logloss: 8.16181e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[173]	valid_0's binary_logloss: 8.31771e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[174]	valid_0's binary_logloss: 8.29999e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[175]	valid_0's binary_logloss: 8.37658e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[176]	valid_0's binary_logloss: 8.59436e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[177]	valid_0's binary_logloss: 8.56984e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[178]	valid_0's binary_logloss: 8.81641e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[179]	valid_0's binary_logloss: 9.06729e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[180]	valid_0's binary_logloss: 8.88816e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[181]	valid_0's binary_logloss: 8.74945e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[182]	valid_0's binary_logloss: 8.5121e-05

Trening klas:  49%|████▉     | 247/500 [30:15<27:05,  6.42s/klasa, klasa=class_247, F1_klasy=1.0000, F1_macro=0.7250, drzewa=191]




Trening klas:  50%|████▉     | 248/500 [30:15<28:06,  6.69s/klasa, klasa=class_247, F1_klasy=1.0000, F1_macro=0.7250, drzewa=191]

[218]	valid_0's binary_logloss: 7.35867e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[219]	valid_0's binary_logloss: 7.2627e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[220]	valid_0's binary_logloss: 7.2501e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[221]	valid_0's binary_logloss: 7.45963e-05
[1]	valid_0's binary_logloss: 0.0787116
[2]	valid_0's binary_logloss: 0.0754932
[3]	valid_0's binary_logloss: 0.0730843
[4]	valid_0's binary_logloss: 0.0710723
[5]	valid_0's binary_logloss: 0.069425
[6]	valid_0's binary_logloss: 0.067251
[7]	valid_0's binary_logloss: 0.0655806
[8]	valid_0's binary_logloss: 0.0643188
[9]	valid_0's binary_logloss: 0.0630982
[10]	valid_0's binary_logloss: 0.0620737
[11]	valid_0's binary_logloss: 0.0607738
[12]	valid_0's binary_logloss: 0.0599744
[13]	valid_0's binary_logloss: 0.0586909
[14]	valid_0's binary_logloss: 0.0580548
[15]	valid_0's binary_logloss: 0.0571276
[16]	valid_0's binary_logloss: 0.0558749
[17]	valid_0's binary_logloss: 0.0553205
[18]	valid_0's binary_logloss: 0.0549391
[19]	valid_0's binary_logloss: 0.0545759
[20]	valid_0's binary_logloss: 0.0542697
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0539393
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.053707
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.0533934
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0530624
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.0526987
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.0524542
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.0523405
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.0516952
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.0511264
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.0512482
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.050763
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.0504892
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.0502216
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.050003
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.0499964
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.0495765
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.0493537
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.0491283
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.0490527
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.0490608
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.0488652
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.0489418
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.0489416
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.049054
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.0493475
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.0493288
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.0490274
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.0489563
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.0486993
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.0488326
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.0485277
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.0484348
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.0484555
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.0486582
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.0485386
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.0485066
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.0484826
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.0484764
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.0485507
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.0484389
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.0482551
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.0481969
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.048397
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.0485666
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.0484646
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.0485315
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.0485874
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.0486556
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.0488636
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.0490464
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.0492093
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.0494306
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.0494531
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.049624
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.0499224
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.0498444
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.049932
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.0500718
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.0502699
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.0504003
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.0505614
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.0506096
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.0507165
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.0507808
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.0507775
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.050778
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.0507961
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

Trening klas:  50%|████▉     | 248/500 [30:19<28:06,  6.69s/klasa, klasa=class_248, F1_klasy=0.6740, F1_macro=0.7248, drzewa=62]




Trening klas:  50%|████▉     | 249/500 [30:19<24:36,  5.88s/klasa, klasa=class_248, F1_klasy=0.6740, F1_macro=0.7248, drzewa=62]

[88]	valid_0's binary_logloss: 0.0510394
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.0512849
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.05127
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.0514794
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.0517043
[1]	valid_0's binary_logloss: 0.182114
[2]	valid_0's binary_logloss: 0.180143
[3]	valid_0's binary_logloss: 0.177041
[4]	valid_0's binary_logloss: 0.175755
[5]	valid_0's binary_logloss: 0.173613
[6]	valid_0's binary_logloss: 0.182445
[7]	valid_0's binary_logloss: 0.181539
[8]	valid_0's binary_logloss: 0.180291
[9]	valid_0's binary_logloss: 0.178944
[10]	valid_0's binary_logloss: 0.176832
[11]	valid_0's binary_logloss: 0.176093
[12]	valid_0's binary_logloss: 0.174518
[13]	valid_0's binary_logloss: 0.172986
[14]	valid_0's binary_logloss: 0.170363
[15]	valid_0's binary_logloss: 0.168638
[16]	valid_0's binary_logloss: 0.166568
[17]	valid_0's binary_logloss: 0.164899
[18]	valid_0's binary_logloss: 0.164472
[19]	valid_0's binary_logloss: 0.163492
[20]	valid_0's binary_logloss: 0.161744
[21]	valid_0's binary_logloss: 0.159499
[22]	valid_0's binary_logloss: 0.157205
[23]	valid_0's binary_logloss: 0.155365
[24]	valid_0's binary_logloss: 0.153071
[25]	valid_0's binary_logloss: 0.151841
[26]	valid_0's binary_logloss: 0.150573
[27]	valid_0's binary_logloss: 0.148161
[28]	valid_0's binary_logloss: 0.14676
[29]	valid_0's binary_logloss: 0.144915
[30]	valid_0's binary_logloss: 0.143781
[31]	valid_0's binary_logloss: 0.142108
[32]	valid_0's binary_logloss: 0.140481
[33]	valid_0's binary_logloss: 0.138886
[34]	valid_0's binary_logloss: 0.137215
[35]	valid_0's binary_logloss: 0.135918
[36]	valid_0's binary_logloss: 0.135599
[37]	valid_0's binary_logloss: 0.134693
[38]	valid_0's binary_logloss: 0.133644
[39]	valid_0's binary_logloss: 0.133144
[40]	valid_0's binary_logloss: 0.132056
[41]	valid_0's binary_logloss: 0.130891
[42]	valid_0's binary_logloss: 0.1299
[43]	valid_0's binary_logloss: 0.12896
[44]	valid_0's binary_logloss: 0.128171
[45]	valid_0's binary_logloss: 0.127141
[46]	valid_0's binary_logloss: 0.125846
[47]	valid_0's binary_logloss: 0.1248
[48]	valid_0's binary_logloss: 0.123417
[49]	valid_0's binary_logloss: 0.122777
[50]	valid_0's binary_logloss: 0.121669
[51]	valid_0's binary_logloss: 0.120521
[52]	valid_0's binary_logloss: 0.119604
[53]	valid_0's binary_logloss: 0.11864
[54]	valid_0's binary_logloss: 0.117555
[55]	valid_0's binary_logloss: 0.116641
[56]	valid_0's binary_logloss: 0.115725
[57]	valid_0's binary_logloss: 0.114852
[58]	valid_0's binary_logloss: 0.113714
[59]	valid_0's binary_logloss: 0.112862
[60]	valid_0's binary_logloss: 0.11149
[61]	valid_0's binary_logloss: 0.110638
[62]	valid_0's binary_logloss: 0.109655
[63]	valid_0's binary_logloss: 0.108389
[64]	valid_0's binary_logloss: 0.107444
[65]	valid_0's binary_logloss: 0.107096
[66]	valid_0's binary_logloss: 0.107019
[67]	valid_0's binary_logloss: 0.10666
[68]	valid_0's binary_logloss: 0.105947
[69]	valid_0's binary_logloss: 0.105605
[70]	valid_0's binary_logloss: 0.105394
[71]	valid_0's binary_logloss: 0.104625
[72]	valid_0's binary_logloss: 0.103913
[73]	valid_0's binary_logloss: 0.103285
[74]	valid_0's binary_logloss: 0.102538
[75]	valid_0's binary_logloss: 0.101451
[76]	valid_0's binary_logloss: 0.100711
[77]	valid_0's binary_logloss: 0.10021
[78]	valid_0's binary_logloss: 0.0994329
[79]	valid_0's binary_logloss: 0.0985266
[80]	valid_0's binary_logloss: 0.0978416
[81]	valid_0's binary_logloss: 0.0978989
[82]	valid_0's binary_logloss: 0.097164
[83]	valid_0's binary_logloss: 0.0967042
[84]	valid_0's binary_logloss: 0.0963947
[85]	valid_0's binary_logloss: 0.095846
[86]	valid_0's binary_logloss: 0.0952636
[87]	valid_0's binary_logloss: 0.0947837
[88]	valid_0's binary_logloss: 0.0940203
[89]	valid_0's binary_logloss: 0.0934199
[90]	valid_0's binary_logloss: 0.092917
[91]	valid_0's binary_logloss: 0.0924289
[92]	valid_0's binary_logloss: 0.0916859
[93]	valid_0's binary_logloss: 0.0913685
[94]	valid_0's binary_logloss: 0.0910424
[95]	valid_0's binary_logloss: 0.0907907
[96]	valid_0's binary_logloss: 0.0908296
[97]	valid_0's binary_logloss: 0.0907538
[98]	valid_0's binary_logloss: 0.0905448
[99]	valid_0's binary_logloss: 0.0905755
[100]	valid_0's binary_logloss: 0.0905005
[101]	valid_0's binary_logloss: 0.0906062
[102]	valid_0's binary_logloss: 0.0906544
[103]	valid_0's binary_logloss: 0.090855
[104]	valid_0's binary_logloss: 0.0908838
[105]	valid_0's binary_logloss: 0.0909964
[106]	valid_0's binary_logloss: 0.0910146
[107]	valid_0's binary_logloss: 0.091077
[108]	valid_0's binary_logloss: 0.0911611
[109]	valid_0's binary_logloss: 0.0909475
[110]	valid_0's binary_logloss: 0.0907735
[111]	valid_0's binary_logloss: 0.090714
[112]	valid_0's binary_logloss: 0.090604
[113]	valid_0's binary_logloss: 0.0903609
[114]	valid_0's binary_logloss: 0.0903031
[115]	valid_0's binary_logloss: 0.0902922
[116]	valid_0's binary_logloss: 0.0900673
[117]	valid_0's binary_logloss: 0.0899364
[118]	valid_0's binary_logloss: 0.0899914
[119]	valid_0's binary_logloss: 0.0899984
[120]	valid_0's binary_logloss: 0.0902811
[121]	valid_0's binary_logloss: 0.0902077
[122]	valid_0's binary_logloss: 0.0903548
[123]	valid_0's binary_logloss: 0.0902881
[124]	valid_0's binary_logloss: 0.0902084
[125]	valid_0's binary_logloss: 0.0902415
[126]	valid_0's binary_logloss: 0.0903634
[127]	valid_0's binary_logloss: 0.0903993
[128]	valid_0's binary_logloss: 0.0904704
[129]	valid_0's binary_logloss: 0.0907856
[130]	valid_0's binary_logloss: 0.0904816
[131]	valid_0's binary_logloss: 0.0906379
[132]	valid_0's binary_logloss: 0.0907767
[133]	valid_0's binary_logloss: 0.0906305
[134]	valid_0's binary_logloss: 0.0907235
[135]	valid_0's binary_logloss: 0.0908311
[136]	valid_0's binary_logloss: 0.0909248
[137]	valid_0's binary_logloss: 0.0910003
[138]	valid_0's binary_logloss: 0.0910184
[139]	valid_0's binary_logloss: 0.0908856
[140]	valid_0's binary_logloss: 0.0908013
[141]	valid_0's binary_logloss: 0.090759
[142]	valid_0's binary_logloss: 0.0909324
[143]	valid_0's binary_logloss: 0.0909914
[144]	valid_0's binary_logloss: 0.0912346
[145]	valid_0's binary_logloss: 0.0911031
[146]	valid_0's binary_logloss: 0.0906263
[147]	valid_0's binary_logloss: 0.0902053

Trening klas:  50%|████▉     | 249/500 [30:30<24:36,  5.88s/klasa, klasa=class_249, F1_klasy=0.1545, F1_macro=0.7225, drzewa=117]




Trening klas:  50%|█████     | 250/500 [30:30<31:23,  7.53s/klasa, klasa=class_249, F1_klasy=0.1545, F1_macro=0.7225, drzewa=117]

[1]	valid_0's binary_logloss: 0.0171255
[2]	valid_0's binary_logloss: 0.0163691
[3]	valid_0's binary_logloss: 0.0156691
[4]	valid_0's binary_logloss: 0.015049
[5]	valid_0's binary_logloss: 0.0144389
[6]	valid_0's binary_logloss: 0.0138957
[7]	valid_0's binary_logloss: 0.0133894
[8]	valid_0's binary_logloss: 0.0129193
[9]	valid_0's binary_logloss: 0.0124689
[10]	valid_0's binary_logloss: 0.0120424
[11]	valid_0's binary_logloss: 0.0116669
[12]	valid_0's binary_logloss: 0.0112552
[13]	valid_0's binary_logloss: 0.0107167
[14]	valid_0's binary_logloss: 0.0103882
[15]	valid_0's binary_logloss: 0.0100495
[16]	valid_0's binary_logloss: 0.00976257
[17]	valid_0's binary_logloss: 0.00946784
[18]	valid_0's binary_logloss: 0.00919735
[19]	valid_0's binary_logloss: 0.00897208
[20]	valid_0's binary_logloss: 0.00872291
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.00849877
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.00827991
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.00807425
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.00787591
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.00769692
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.00753908
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.00737106
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.00720845
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.00706256
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.00689826
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.00678641
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.00664782
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.00658024
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.00646868
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.00635556
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.00627779
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.00620789
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.0061368
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.0060722
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.00602401
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.00596541
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.00592077
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.00588754
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.00584563
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.0058243
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.00579424
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.00575264
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.00565121
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.00562302
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.00559473
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.00559402
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.00560668
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.00560972
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.00562577
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.00561179
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.00538838
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.00522895
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.00520383
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.00518885
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.0051343
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.00515974
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.00517816
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.00512881
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.00512991
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.00514226
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.00512716
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.00511714
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.00514758
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.00515417
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.00520718
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.00515076
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.0050372
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.00506242
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.00499975
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.00499909
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.00495257
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.00488688
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.00490819
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.0049001
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.0048835
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.00487852
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.00487773
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.00486935
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.00486708
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.0048942
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.00489136
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.0049095
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.004937
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.00490152
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.00486987
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.00478079
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.00475603
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.00473798
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.0047375
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.00474175
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.00475419
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.00469952
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.00470849
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.00467927
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.0046579
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.00467031
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.00466088
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.00464998
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.00467258
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.00467175
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.00465003
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.00461977
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.00460051
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.0045827
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.00455466
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.00459056
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 0.00458527
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 0.0045844
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 0.00455695
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 0.00455781
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[116]	valid_0's binary_logloss: 0.00458287
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[117]	valid_0's binary_logloss: 0.00459849
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[118]	valid_0's binary_logloss: 0.00463649
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[119]	valid_0's binary_logloss: 0.00463001
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[120]	valid_0's binary_logloss: 0.00464552
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[121]	valid_0's binary_logloss: 0.00464699
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[122]	valid_0's binary_logloss: 0.00468549
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[123]	valid_0's binary_logloss: 0.00468843
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[124]	valid_0's binary_logloss: 0.0047397
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[125]	valid_0's binary_logloss: 0.00478055
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[126]	valid_0's binary_logloss: 0.0048124
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[127]	valid_0's binary_logloss: 0.00483496
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[128]	valid_0's binary_logloss: 0.00486871
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[129]	valid_0's binary_logloss: 0.00489727
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[130]	valid_0's binary_logloss: 0.00493601
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[131]	valid_0's binary_logloss: 0.00490299
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[132]	valid_0's binary_logloss: 0.00485472
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[133]	valid_0's binary_logloss: 0.00484834
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[134]	valid_0's binary_logloss: 0.00486087
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[135]	valid_0's binary_logloss: 0.00487806
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[136]	valid_0's binary_logloss: 0.00488528
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[137]	valid_0's binary_logloss: 0.00490434
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

Trening klas:  50%|█████     | 250/500 [30:35<31:23,  7.53s/klasa, klasa=class_250, F1_klasy=0.7451, F1_macro=0.7226, drzewa=110]




Trening klas:  50%|█████     | 251/500 [30:35<27:44,  6.69s/klasa, klasa=class_250, F1_klasy=0.7451, F1_macro=0.7226, drzewa=110]

[138]	valid_0's binary_logloss: 0.00493732
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[139]	valid_0's binary_logloss: 0.0049683
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[140]	valid_0's binary_logloss: 0.00501475
[1]	valid_0's binary_logloss: 0.0230268
[2]	valid_0's binary_logloss: 0.0224428
[3]	valid_0's binary_logloss: 0.0218934
[4]	valid_0's binary_logloss: 0.0212884
[5]	valid_0's binary_logloss: 0.0206951
[6]	valid_0's binary_logloss: 0.020214
[7]	valid_0's binary_logloss: 0.0198867
[8]	valid_0's binary_logloss: 0.0196202
[9]	valid_0's binary_logloss: 0.0190662
[10]	valid_0's binary_logloss: 0.0186513
[11]	valid_0's binary_logloss: 0.018274
[12]	valid_0's binary_logloss: 0.0183687
[13]	valid_0's binary_logloss: 0.0179279
[14]	valid_0's binary_logloss: 0.0176351
[15]	valid_0's binary_logloss: 0.01728
[16]	valid_0's binary_logloss: 0.0167957
[17]	valid_0's binary_logloss: 0.0163886
[18]	valid_0's binary_logloss: 0.0159825
[19]	valid_0's binary_logloss: 0.0156076
[20]	valid_0's binary_logloss: 0.0153132
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.015115
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0148259
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.0146484
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0145592
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.0144514
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.0142184
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.0140396
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.0137288
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.0135461
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.0134525
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.0132287
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.0130309
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.012886
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.0128246
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.0126542
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.0124868
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.0123369
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.0121387
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.0119573
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.0118509
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.0116438
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.01148
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.0113154
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.011144
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.0109973
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.0108523
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.0107467
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.0106502
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.0105588
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.0104869
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.0102901
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.0101963
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.0101453
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.0100758
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.0100383
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.00998332
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.00979483
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.00967418
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.00957992
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.00950408
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.00940947
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.00933017
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.00925078
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.00918928
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.00918334
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.00914651
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.00911803
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.00908257
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.00907775
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.00908562
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.00905013
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.00902841
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.00899617
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.00890814
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.00880756
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.00879732
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.00879073
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.00878207
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.00877413
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.00872257
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.00870958
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.00869819
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.00865825
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.00862543
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.0086093
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.00856075
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.00852575
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.00852822
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.00848892
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.00846445
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.00848405
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.00850688
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.00852168
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.00854275
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.00854657
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.00855369
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.00853936
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.00854767
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.00853929
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.00861058
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.00863996
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.00859948
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.00864762
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.00868249
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.00873019
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.00866054
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.00859562
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.00853528
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.00847565
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.00851012
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.00844537
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 0.00839536
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 0.00837693
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 0.00833651
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 0.00830535
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[116]	valid_0's binary_logloss: 0.00827957
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[117]	valid_0's binary_logloss: 0.00824094
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[118]	valid_0's binary_logloss: 0.0082383
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[119]	valid_0's binary_logloss: 0.00827096
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[120]	valid_0's binary_logloss: 0.00824946
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[121]	valid_0's binary_logloss: 0.00827655
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[122]	valid_0's binary_logloss: 0.00832708
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[123]	valid_0's binary_logloss: 0.0083673
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[124]	valid_0's binary_logloss: 0.00838343
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[125]	valid_0's binary_logloss: 0.0084226
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[126]	valid_0's binary_logloss: 0.0084547
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[127]	valid_0's binary_logloss: 0.00847965
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[128]	valid_0's binary_logloss: 0.00851623
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[129]	valid_0's binary_logloss: 0.00854075
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[130]	valid_0's binary_logloss: 0.00855254
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[131]	valid_0's binary_logloss: 0.00856322
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[132]	valid_0's binary_logloss: 0.00846715
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[133]	valid_0's binary_logloss: 0.00844138
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[134]	valid_0's binary_logloss: 0.00845379
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[135]	valid_0's binary_logloss: 0.00843059
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[136]	valid_0's binary_logloss: 0.00845957
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[137]	valid_0's binary_logloss: 0.00847868
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[138]	valid_0's binary_logloss: 0.00845099
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[139]	valid_0's binary_logloss: 0.00842559
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[140]	valid_0's binary_logloss: 0.00838288
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[141]	valid_0's binary_logloss: 0.00842576
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[142]	valid_0's binary_logloss: 0.00835941
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[143]	valid_0's binary_logloss: 0.00838706
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

Trening klas:  50%|█████     | 251/500 [30:38<27:44,  6.69s/klasa, klasa=class_251, F1_klasy=0.8750, F1_macro=0.7232, drzewa=118]




Trening klas:  50%|█████     | 252/500 [30:38<24:01,  5.81s/klasa, klasa=class_251, F1_klasy=0.8750, F1_macro=0.7232, drzewa=118]

[144]	valid_0's binary_logloss: 0.00832953
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[145]	valid_0's binary_logloss: 0.00836752
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[146]	valid_0's binary_logloss: 0.0083476
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[147]	valid_0's binary_logloss: 0.00831413
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[148]	valid_0's binary_logloss: 0.00831774
[1]	valid_0's binary_logloss: 0.0230268
[2]	valid_0's binary_logloss: 0.0224428
[3]	valid_0's binary_logloss: 0.0218934
[4]	valid_0's binary_logloss: 0.0212884
[5]	valid_0's binary_logloss: 0.0206951
[6]	valid_0's binary_logloss: 0.020214
[7]	valid_0's binary_logloss: 0.0198867
[8]	valid_0's binary_logloss: 0.0196202
[9]	valid_0's binary_logloss: 0.0190662
[10]	valid_0's binary_logloss: 0.0186513
[11]	valid_0's binary_logloss: 0.018274
[12]	valid_0's binary_logloss: 0.0183687
[13]	valid_0's binary_logloss: 0.0179279
[14]	valid_0's binary_logloss: 0.0176351
[15]	valid_0's binary_logloss: 0.01728
[16]	valid_0's binary_logloss: 0.0167957
[17]	valid_0's binary_logloss: 0.0163886
[18]	valid_0's binary_logloss: 0.0159825
[19]	valid_0's binary_logloss: 0.0156076
[20]	valid_0's binary_logloss: 0.0153132
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.015115
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0148259
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.0146484
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0145592
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.0144514
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.0142184
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.0140396
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.0137288
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.0135461
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.0134525
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.0132287
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.0130309
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.012886
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.0128246
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.0126542
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.0124868
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.0123369
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.0121387
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.0119573
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.0118509
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.0116438
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.01148
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.0113154
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.011144
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.0109973
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.0108523
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.0107467
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.0106502
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.0105588
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.0104869
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.0102901
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.0101963
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.0101453
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.0100758
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.0100383
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.00998332
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.00979483
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.00967418
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.00957992
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.00950408
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.00940947
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.00933017
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.00925078
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.00918928
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.00918334
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.00914651
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.00911803
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.00908257
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.00907775
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.00908562
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.00905013
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.00902841
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.00899617
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.00890814
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.00880756
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.00879732
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.00879073
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.00878207
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.00877413
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.00872257
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.00870958
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.00869819
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.00865825
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.00862543
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.0086093
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.00856075
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.00852575
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.00852822
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.00848892
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.00846445
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.00848405
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.00850688
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.00852168
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.00854275
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.00854657
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.00855369
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.00853936
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.00854767
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.00853929
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.00861058
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.00863996
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.00859948
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.00864762
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.00868249
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.00873019
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.00866054
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.00859562
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.00853528
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.00847565
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.00851012
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.00844537
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 0.00839536
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 0.00837693
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 0.00833651
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 0.00830535
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[116]	valid_0's binary_logloss: 0.00827957
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[117]	valid_0's binary_logloss: 0.00824094
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[118]	valid_0's binary_logloss: 0.0082383
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[119]	valid_0's binary_logloss: 0.00827096
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[120]	valid_0's binary_logloss: 0.00824946
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[121]	valid_0's binary_logloss: 0.00827655
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[122]	valid_0's binary_logloss: 0.00832708
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[123]	valid_0's binary_logloss: 0.0083673
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[124]	valid_0's binary_logloss: 0.00838343
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[125]	valid_0's binary_logloss: 0.0084226
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[126]	valid_0's binary_logloss: 0.0084547
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[127]	valid_0's binary_logloss: 0.00847965
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[128]	valid_0's binary_logloss: 0.00851623
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[129]	valid_0's binary_logloss: 0.00854075
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[130]	valid_0's binary_logloss: 0.00855254
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[131]	valid_0's binary_logloss: 0.00856322
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[132]	valid_0's binary_logloss: 0.00846715
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[133]	valid_0's binary_logloss: 0.00844138
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[134]	valid_0's binary_logloss: 0.00845379
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[135]	valid_0's binary_logloss: 0.00843059
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[136]	valid_0's binary_logloss: 0.00845957
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[137]	valid_0's binary_logloss: 0.00847868
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[138]	valid_0's binary_logloss: 0.00845099
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[139]	valid_0's binary_logloss: 0.00842559
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[140]	valid_0's binary_logloss: 0.00838288
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[141]	valid_0's binary_logloss: 0.00842576
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[142]	valid_0's binary_logloss: 0.00835941
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[143]	valid_0's binary_logloss: 0.00838706
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

Trening klas:  50%|█████     | 252/500 [30:42<24:01,  5.81s/klasa, klasa=class_252, F1_klasy=0.8750, F1_macro=0.7238, drzewa=118]




Trening klas:  51%|█████     | 253/500 [30:42<21:17,  5.17s/klasa, klasa=class_252, F1_klasy=0.8750, F1_macro=0.7238, drzewa=118]

[144]	valid_0's binary_logloss: 0.00832953
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[145]	valid_0's binary_logloss: 0.00836752
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[146]	valid_0's binary_logloss: 0.0083476
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[147]	valid_0's binary_logloss: 0.00831413
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[148]	valid_0's binary_logloss: 0.00831774
[1]	valid_0's binary_logloss: 0.0164189
[2]	valid_0's binary_logloss: 0.0158227
[3]	valid_0's binary_logloss: 0.0152671
[4]	valid_0's binary_logloss: 0.0147235
[5]	valid_0's binary_logloss: 0.0143061
[6]	valid_0's binary_logloss: 0.0139634
[7]	valid_0's binary_logloss: 0.0136028
[8]	valid_0's binary_logloss: 0.0132048
[9]	valid_0's binary_logloss: 0.0128629
[10]	valid_0's binary_logloss: 0.0125336
[11]	valid_0's binary_logloss: 0.0122044
[12]	valid_0's binary_logloss: 0.0119252
[13]	valid_0's binary_logloss: 0.0116476
[14]	valid_0's binary_logloss: 0.011353
[15]	valid_0's binary_logloss: 0.0111292
[16]	valid_0's binary_logloss: 0.010875
[17]	valid_0's binary_logloss: 0.0104693
[18]	valid_0's binary_logloss: 0.0103165
[19]	valid_0's binary_logloss: 0.0101208
[20]	valid_0's binary_logloss: 0.00971544
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.00953819
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.00935843
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.00918579
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.00897877
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.00877488
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.00864112
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.00855035
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.00837402
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.00827573
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.00802913
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.00791499
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.00777275
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.00751723
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.00723699
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.0070186
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.00692266
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.00683761
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.0067587
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.00669939
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.00664982
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.00657009
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.00649395
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.00643969
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.00625688
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.00615053
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.0060981
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.00605064
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.00600951
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.005979
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.00592457
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.00584248
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.00578627
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.00573619
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.00566225
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.00558745
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.00548026
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.00544439
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.00528608
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.0051667
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.00502367
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.0049958
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.0048814
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.00488057
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.00485768
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.00484569
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.00472197
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.00460889
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.00450776
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.00448738
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.00440836
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.00442476
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.00443916
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.00445472
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.00435298
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.00436607
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.00436922
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.00428184
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.0041992
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.00416154
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.00409445
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.00404286
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.00407933
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.00401171
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.00402319
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.00400816
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.0039391
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.00396558
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.00396538
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.00398617
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.00401717
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.00395203
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.0038969
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.0038418
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.00377843
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.00374041
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.00375578
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.003794
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.00382263
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.00381643
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.00385675
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.00384613
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.00389421
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.00390412
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.00394821
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.00396201
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.00397437
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.00398543
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.00400045
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.00398871
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.00401385
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.00401873
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 0.00405809
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 0.0040878
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 0.00412885
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 0.00415316
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[116]	valid_0's binary_logloss: 0.00418042
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[117]	valid_0's binary_logloss: 0.0042044
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[118]	valid_0's binary_logloss: 0.0042243
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[119]	valid_0's binary_logloss: 0.00425552
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[120]	valid_0's binary_logloss: 0.00424491
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[121]	valid_0's binary_logloss: 0.00421413
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[122]	valid_0's binary_logloss: 0.00425666
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[123]	valid_0's binary_logloss: 0.00431042
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[124]	valid_0's binary_logloss: 0.00433825
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

Trening klas:  51%|█████     | 253/500 [30:47<21:17,  5.17s/klasa, klasa=class_253, F1_klasy=0.7568, F1_macro=0.7239, drzewa=95]




Trening klas:  51%|█████     | 254/500 [30:47<21:00,  5.12s/klasa, klasa=class_253, F1_klasy=0.7568, F1_macro=0.7239, drzewa=95]

[125]	valid_0's binary_logloss: 0.0043903
[1]	valid_0's binary_logloss: 0.0754596
[2]	valid_0's binary_logloss: 0.0732605
[3]	valid_0's binary_logloss: 0.0709982
[4]	valid_0's binary_logloss: 0.0689958
[5]	valid_0's binary_logloss: 0.0670671
[6]	valid_0's binary_logloss: 0.0660739
[7]	valid_0's binary_logloss: 0.0645148
[8]	valid_0's binary_logloss: 0.0630058
[9]	valid_0's binary_logloss: 0.0614915
[10]	valid_0's binary_logloss: 0.0601949
[11]	valid_0's binary_logloss: 0.0588761
[12]	valid_0's binary_logloss: 0.0576441
[13]	valid_0's binary_logloss: 0.0567306
[14]	valid_0's binary_logloss: 0.0558765
[15]	valid_0's binary_logloss: 0.0551959
[16]	valid_0's binary_logloss: 0.0544552
[17]	valid_0's binary_logloss: 0.0536652
[18]	valid_0's binary_logloss: 0.053157
[19]	valid_0's binary_logloss: 0.0527439
[20]	valid_0's binary_logloss: 0.0520951
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0517859
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0513185
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.0508975
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0504808
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.0502159
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.0499443
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.0497306
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.0492603
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.0489035
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.0487534
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.0485332
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.0483139
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.0481887
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.0480239
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.0479033
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.0477182
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.0475816
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.0471773
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.046956
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.0469426
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.0468595
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.0468624
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.0468864
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.0468288
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.0466155
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.0465531
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.046445
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.0463115
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.0462148
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.0461589
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.0462062
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.0461919
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.0463023
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.046255
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.0461448
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.0462345
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.0463218
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.0462776
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.0463697
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.0464552
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.0463829
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.0463054
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.0462585
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.0461502
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.0462367
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.0462039
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.0463242
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.0461998
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.0461716
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.0462654
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.0463727
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.0463922
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.0465704
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.0466356
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.0466283
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.0465998
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.046562
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.0466478
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.0468067
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.0467662
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.0468593
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.0470749
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.047132
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.0473612
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.0475395

Trening klas:  51%|█████     | 254/500 [30:52<21:00,  5.12s/klasa, klasa=class_254, F1_klasy=0.6255, F1_macro=0.7235, drzewa=55]




Trening klas:  51%|█████     | 255/500 [30:52<20:30,  5.02s/klasa, klasa=class_254, F1_klasy=0.6255, F1_macro=0.7235, drzewa=55]

[1]	valid_0's binary_logloss: 0.0348254
[2]	valid_0's binary_logloss: 0.0339002
[3]	valid_0's binary_logloss: 0.0332482
[4]	valid_0's binary_logloss: 0.0322036
[5]	valid_0's binary_logloss: 0.0314882
[6]	valid_0's binary_logloss: 0.0306948
[7]	valid_0's binary_logloss: 0.0300105
[8]	valid_0's binary_logloss: 0.0293782
[9]	valid_0's binary_logloss: 0.0285632
[10]	valid_0's binary_logloss: 0.027883
[11]	valid_0's binary_logloss: 0.0273049
[12]	valid_0's binary_logloss: 0.0267256
[13]	valid_0's binary_logloss: 0.0261581
[14]	valid_0's binary_logloss: 0.0256814
[15]	valid_0's binary_logloss: 0.0252074
[16]	valid_0's binary_logloss: 0.0247549
[17]	valid_0's binary_logloss: 0.0243278
[18]	valid_0's binary_logloss: 0.0238624
[19]	valid_0's binary_logloss: 0.023432
[20]	valid_0's binary_logloss: 0.0229943
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0226722
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0223655
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.0221157
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0218762
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.0217261
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.0214774
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.0211499
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.020953
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.0207911
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.0205498
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.0203287
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.0200164
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.0197683
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.0195611
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.0192868
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.019188
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.0190088
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.0189088
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.0188456
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.0186731
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.0185169
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.0183739
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.0182656
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.0181482
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.018091
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.0180573
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.0180154
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.0179412
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.0178866
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.0178064
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.0177633
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.0177626
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.0176367
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.0176101
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.0175399
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.0174425
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.0173572
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.0172815
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.0172543
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.0172178
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.017141
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.0170418
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.0169713
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.0169161
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.0169234
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.0169015
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.0168907
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.0168643
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.0168242
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.0168017
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.0167718
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.0167683
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.0167388
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.0167133
[75]	valid_0's binary_logloss: 0.0167704
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.0167325
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.0167261
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.0167533
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.0167418
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.0167373
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.0167524
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.016717
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.0166987
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.0167471
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.0167567
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.0167619
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.0167349
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.0167603
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.0167581
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.0167556
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.0168121
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.0167806
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.0167975
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.0168676
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.0169367
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.0169782
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.0170452
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.0170819
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.0171446
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.0170741
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.0171645
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.0172838
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.0173245
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.017387
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.0174839
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.017534
[107]	valid_0's binary_logloss: 0.0176226
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.0176706
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.0177474
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.0177798
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.01793
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 0.0179624
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

Trening klas:  51%|█████     | 255/500 [30:58<20:30,  5.02s/klasa, klasa=class_255, F1_klasy=0.4262, F1_macro=0.7224, drzewa=83]




Trening klas:  51%|█████     | 256/500 [30:58<21:26,  5.27s/klasa, klasa=class_255, F1_klasy=0.4262, F1_macro=0.7224, drzewa=83]

[113]	valid_0's binary_logloss: 0.0180235
[1]	valid_0's binary_logloss: 0.014599
[2]	valid_0's binary_logloss: 0.0139299
[3]	valid_0's binary_logloss: 0.0132735
[4]	valid_0's binary_logloss: 0.0126735
[5]	valid_0's binary_logloss: 0.0120918
[6]	valid_0's binary_logloss: 0.0115693
[7]	valid_0's binary_logloss: 0.011076
[8]	valid_0's binary_logloss: 0.0105317
[9]	valid_0's binary_logloss: 0.0100399
[10]	valid_0's binary_logloss: 0.00955131
[11]	valid_0's binary_logloss: 0.00911833
[12]	valid_0's binary_logloss: 0.0087137
[13]	valid_0's binary_logloss: 0.0083275
[14]	valid_0's binary_logloss: 0.007954
[15]	valid_0's binary_logloss: 0.00757799
[16]	valid_0's binary_logloss: 0.0072138
[17]	valid_0's binary_logloss: 0.00688396
[18]	valid_0's binary_logloss: 0.00654303
[19]	valid_0's binary_logloss: 0.00622624
[20]	valid_0's binary_logloss: 0.00592864
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.00564289
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.00536858
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.00511277
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.00487951
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.00464096
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.0044254
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.00420886
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.00400203
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.00380848
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.00364114
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.00347951
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.00332475
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.00317908
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.00304425
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.00291335
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.00279652
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.00266039
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.00253349
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.00242895
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.00231166
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.00220391
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.00210173
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.00199682
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.00190154
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.00180971
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.0017309
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.00165101
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.00157228
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.00149565
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.00142251
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.00135222
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.00129062
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.00122933
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.00117241
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.00111557
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.00106108
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.001011
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.000963112
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.000918299
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.000873677
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.000838968
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.000797842
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.000764983
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.000728053
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.000694316
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.000662049
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.00063827
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.000608353
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.000584946
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.000558665
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.000531535
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.000504555
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.000479346
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.000455825
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.000433684
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.000413992
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.000394339
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.000374604
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.000358097
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.00034061
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.000324483
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.000309065
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.000296216
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.000284345
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.000272484
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.000258505
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.000246486
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.000234666
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.000224393
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.000213928
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.000204792
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.000195817
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.000187918
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.000179688
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.000174444
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.000168054
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.000160487
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.000154753
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.000147395
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.000142993
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.000137433
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.000131505
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.0001273
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.000124767
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.000120196
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.000114358
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.000108498
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.0001033
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 9.87126e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 9.48838e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 9.08077e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 8.82993e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 8.48811e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 8.16268e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 7.88538e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[116]	valid_0's binary_logloss: 7.58618e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[117]	valid_0's binary_logloss: 7.38547e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[118]	valid_0's binary_logloss: 7.12426e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[119]	valid_0's binary_logloss: 6.76227e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[120]	valid_0's binary_logloss: 6.49757e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[121]	valid_0's binary_logloss: 6.33469e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[122]	valid_0's binary_logloss: 6.07918e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[123]	valid_0's binary_logloss: 5.91985e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[124]	valid_0's binary_logloss: 5.71819e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[125]	valid_0's binary_logloss: 5.59441e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[126]	valid_0's binary_logloss: 5.4065e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[127]	valid_0's binary_logloss: 5.23867e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[128]	valid_0's binary_logloss: 5.07859e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[129]	valid_0's binary_logloss: 4.91137e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[130]	valid_0's binary_logloss: 4.63041e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[131]	valid_0's binary_logloss: 4.5783e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[132]	valid_0's binary_logloss: 4.40376e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[133]	valid_0's binary_logloss: 4.22732e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[134]	valid_0's binary_logloss: 4.07534e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[135]	valid_0's binary_logloss: 3.92725e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[136]	valid_0's binary_logloss: 3.74613e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[137]	valid_0's binary_logloss: 3.58722e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[138]	valid_0's binary_logloss: 3.438e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[139]	valid_0's binary_logloss: 3.30044e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[140]	valid_0's binary_logloss: 3.19023e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[141]	valid_0's binary_logloss: 3.14002e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[142]	valid_0's binary_logloss: 3.05842e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[143]	valid_0's binary_logloss: 3.00525e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[144]	valid_0's binary_logloss: 2.91801e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[145]	valid_0's binary_logloss: 2.83283e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[146]	valid_0's binary_logloss: 2.75575e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[147]	valid_0's binary_logloss: 2.65664e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[148]	valid_0's binary_logloss: 2.5737e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[149]	valid_0's binary_logloss: 2.47536e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[150]	valid_0's binary_logloss: 2.41442e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[151]	valid_0's binary_logloss: 2.34962e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[152]	valid_0's binary_logloss: 2.2941e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[153]	valid_0's binary_logloss: 2.23902e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[154]	valid_0's binary_logloss: 2.1787e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[155]	valid_0's binary_logloss: 2.1335e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[156]	valid_0's binary_logloss: 2.05418e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[157]	valid_0's binary_logloss: 1.98268e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[158]	valid_0's binary_logloss: 1.9447e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[159]	valid_0's binary_logloss: 1.88426e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[160]	valid_0's binary_logloss: 1.83825e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[161]	valid_0's binary_logloss: 1.78921e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[162]	valid_0's binary_logloss: 1.72645e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[163]	valid_0's binary_logloss: 1.68534e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[164]	valid_0's binary_logloss: 1.66456e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[165]	valid_0's binary_logloss: 1.65621e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[166]	valid_0's binary_logloss: 1.64735e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[167]	valid_0's binary_logloss: 1.64037e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[168]	valid_0's binary_logloss: 1.6109e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[169]	valid_0's binary_logloss: 1.60421e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[170]	valid_0's binary_logloss: 1.61447e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[171]	valid_0's binary_logloss: 1.5705e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[172]	valid_0's binary_logloss: 1.55967e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[173]	valid_0's binary_logloss: 1.55726e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[174]	valid_0's binary_logloss: 1.52609e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[175]	valid_0's binary_logloss: 1.52637e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[176]	valid_0's binary_logloss: 1.53033e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[177]	valid_0's binary_logloss: 1.49426e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[178]	valid_0's binary_logloss: 1.45613e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[179]	valid_0's binary_logloss: 1.44672e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[180]	valid_0's binary_logloss: 1.44192e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[181]	valid_0's binary_logloss: 1.404e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[182]	valid_0's binary_logloss: 1.37055e-05

Trening klas:  51%|█████     | 256/500 [31:08<21:26,  5.27s/klasa, klasa=class_256, F1_klasy=0.0000, F1_macro=0.7195, drzewa=285]




Trening klas:  51%|█████▏    | 257/500 [31:08<27:05,  6.69s/klasa, klasa=class_256, F1_klasy=0.0000, F1_macro=0.7195, drzewa=285]

[1]	valid_0's binary_logloss: 0.0180212
[2]	valid_0's binary_logloss: 0.0174482
[3]	valid_0's binary_logloss: 0.0169287
[4]	valid_0's binary_logloss: 0.0164571
[5]	valid_0's binary_logloss: 0.0160289
[6]	valid_0's binary_logloss: 0.0156456
[7]	valid_0's binary_logloss: 0.015291
[8]	valid_0's binary_logloss: 0.0148983
[9]	valid_0's binary_logloss: 0.0145848
[10]	valid_0's binary_logloss: 0.0143203
[11]	valid_0's binary_logloss: 0.0139819
[12]	valid_0's binary_logloss: 0.0136599
[13]	valid_0's binary_logloss: 0.0134633
[14]	valid_0's binary_logloss: 0.0132399
[15]	valid_0's binary_logloss: 0.0130692
[16]	valid_0's binary_logloss: 0.0128731
[17]	valid_0's binary_logloss: 0.0126987
[18]	valid_0's binary_logloss: 0.0125439
[19]	valid_0's binary_logloss: 0.0124063
[20]	valid_0's binary_logloss: 0.0123258
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0122617
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0122082
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.0121131
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0120519
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.0119884
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.0119352
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.0118948
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.0118648
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.0115989
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.0115478
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.011558
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.0115909
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.0116418
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.0116638
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.0116949
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.0117299
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.0117762
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.0118304
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.011892
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.0119469
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.0119913
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.0120407
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.0121037
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.0121652
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.0120152
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.0120795
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.0121479
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.0122187
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.0122944
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.0120578
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.0121426
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.0122015
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.012285
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.0122489
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.0123373
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

Trening klas:  51%|█████▏    | 257/500 [31:11<27:05,  6.69s/klasa, klasa=class_257, F1_klasy=0.7455, F1_macro=0.7196, drzewa=30]




Trening klas:  52%|█████▏    | 258/500 [31:11<22:36,  5.61s/klasa, klasa=class_257, F1_klasy=0.7455, F1_macro=0.7196, drzewa=30]

[56]	valid_0's binary_logloss: 0.0124244
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.0124526
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.0125028
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.0125916
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.0124617
[1]	valid_0's binary_logloss: 0.090636
[2]	valid_0's binary_logloss: 0.0865447
[3]	valid_0's binary_logloss: 0.0830652
[4]	valid_0's binary_logloss: 0.0795402
[5]	valid_0's binary_logloss: 0.0769833
[6]	valid_0's binary_logloss: 0.0777389
[7]	valid_0's binary_logloss: 0.0773767
[8]	valid_0's binary_logloss: 0.0755753
[9]	valid_0's binary_logloss: 0.0735264
[10]	valid_0's binary_logloss: 0.0719589
[11]	valid_0's binary_logloss: 0.0708255
[12]	valid_0's binary_logloss: 0.0695849
[13]	valid_0's binary_logloss: 0.0683361
[14]	valid_0's binary_logloss: 0.0672686
[15]	valid_0's binary_logloss: 0.0661435
[16]	valid_0's binary_logloss: 0.0651155
[17]	valid_0's binary_logloss: 0.0641203
[18]	valid_0's binary_logloss: 0.0626941
[19]	valid_0's binary_logloss: 0.0615328
[20]	valid_0's binary_logloss: 0.0606443
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0598395
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0591154
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.0584043
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0575285
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.0570328
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.0563698
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.0556755
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.0551564
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.0545036
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.0537922
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.0534341
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.053087
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.0527648
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.0524303
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.0520472
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.0517489
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.0513327
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.0509705
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.0505411
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.0502959
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.0499677
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.0495894
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.0492446
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.0488732
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.0485725
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.0483055
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.0480368
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.0477799
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.0476229
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.0474628
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.0473216
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.0470731
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.0468726
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.0467787
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.0465345
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.0464483
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.0463701
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.0462016
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.0461046
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.046079
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.045886
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.0458662
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.0457586
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.0456515
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.0456337
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.0456595
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.0456276
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.0455631
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.0455441
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.0454678
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.0453258
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.0452436
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.0450486
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.045127
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.0450389
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.0450612
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.0451527
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.0452006
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.0452278
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.0453117
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.0453445
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.045329
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.0452156
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.0452875
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.0452457
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.0452401
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.0453399
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.0453023
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.045284
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.0451866
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.045196
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.0452117
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.0452211
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.0452386
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.045315
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.0452829
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.0453461
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.0454252
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.0455288
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

Trening klas:  52%|█████▏    | 258/500 [31:16<22:36,  5.61s/klasa, klasa=class_258, F1_klasy=0.6939, F1_macro=0.7195, drzewa=75]




Trening klas:  52%|█████▏    | 259/500 [31:16<22:32,  5.61s/klasa, klasa=class_258, F1_klasy=0.6939, F1_macro=0.7195, drzewa=75]

[100]	valid_0's binary_logloss: 0.0455569
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.0456354
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.0457182
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.0457353
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.0458798
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.0458305
[1]	valid_0's binary_logloss: 0.0685447
[2]	valid_0's binary_logloss: 0.0670588
[3]	valid_0's binary_logloss: 0.0655254
[4]	valid_0's binary_logloss: 0.0641319
[5]	valid_0's binary_logloss: 0.0627596
[6]	valid_0's binary_logloss: 0.0614325
[7]	valid_0's binary_logloss: 0.0601977
[8]	valid_0's binary_logloss: 0.0592952
[9]	valid_0's binary_logloss: 0.0583479
[10]	valid_0's binary_logloss: 0.0574075
[11]	valid_0's binary_logloss: 0.0564216
[12]	valid_0's binary_logloss: 0.0557182
[13]	valid_0's binary_logloss: 0.0551347
[14]	valid_0's binary_logloss: 0.054386
[15]	valid_0's binary_logloss: 0.0537517
[16]	valid_0's binary_logloss: 0.0532699
[17]	valid_0's binary_logloss: 0.0529373
[18]	valid_0's binary_logloss: 0.0524425
[19]	valid_0's binary_logloss: 0.0519792
[20]	valid_0's binary_logloss: 0.0513916
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0508508
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0504515
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.0501089
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0496165
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.0492421
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.0489057
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.0485433
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.047997
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.047753
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.0473698
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.0470152
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.0466309
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.0462814
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.0460005
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.0457934
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.0455554
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.0453541
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.0450912
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.044957
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.0446747
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.0443998
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.0440976
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.0438128
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.0434218
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.0430964
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.042985
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.0429964
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.0427936
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.0427146
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.0425382
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.0424651
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.0423481
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.0422435
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.042217
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.0421114
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.0421363
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.0421001
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.0420781
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.0418264
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.0418396
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.041922
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.0419732
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.042109
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.0422729
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.0422242
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.0423102
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.0423587
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.0423444
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.0424038
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.0426413
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.0426926
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.0428035
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.0428632
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.0428851
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.0427029
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.0426521
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.0427186
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.0426859
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.0427884
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.0428466
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.0428384
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.042652
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.0426859
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.0426219
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.0423664

Trening klas:  52%|█████▏    | 259/500 [31:21<22:32,  5.61s/klasa, klasa=class_259, F1_klasy=0.4643, F1_macro=0.7186, drzewa=59]




Trening klas:  52%|█████▏    | 260/500 [31:21<21:39,  5.41s/klasa, klasa=class_259, F1_klasy=0.4643, F1_macro=0.7186, drzewa=59]

[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.0422299
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.042149
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.0422232
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.0421411
[1]	valid_0's binary_logloss: 0.0519499
[2]	valid_0's binary_logloss: 0.0492234
[3]	valid_0's binary_logloss: 0.0468571
[4]	valid_0's binary_logloss: 0.0448085
[5]	valid_0's binary_logloss: 0.0430667
[6]	valid_0's binary_logloss: 0.042284
[7]	valid_0's binary_logloss: 0.0406685
[8]	valid_0's binary_logloss: 0.0390485
[9]	valid_0's binary_logloss: 0.0378007
[10]	valid_0's binary_logloss: 0.0365471
[11]	valid_0's binary_logloss: 0.0354047
[12]	valid_0's binary_logloss: 0.0344913
[13]	valid_0's binary_logloss: 0.0337164
[14]	valid_0's binary_logloss: 0.0329196
[15]	valid_0's binary_logloss: 0.0321945
[16]	valid_0's binary_logloss: 0.0313851
[17]	valid_0's binary_logloss: 0.0307235
[18]	valid_0's binary_logloss: 0.0300707
[19]	valid_0's binary_logloss: 0.0295613
[20]	valid_0's binary_logloss: 0.0290594
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0286887
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0283423
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.0279376
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0274316
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.027144
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.0266532
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.0262357
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.0257908
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.0255421
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.0251321
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.0247659
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.0245906
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.0241832
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.0240587
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.0239027
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.0237482
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.0233605
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.0232246
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.022794
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.0224905
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.0219257
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.0214861
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.0212972
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.0209597
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.0209257
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.0208541
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.0208385
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.0206457
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.0203881
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.0201235
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.0199029
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.0197655
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.0197051
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.019715
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.0196724
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.019398
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.0191329
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.0190315
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.0191101
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.0191425
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.0191311
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.0190953
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.0190695
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.0191222
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.0192288
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.0191513
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.0192571
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.0192231
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.0191569
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.0191194
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.0189267
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.0187191
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.0185644
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.018361
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.0181644
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.0181829
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.0181912
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.0181563
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.0179881
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.0178518
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.017848
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.0178296
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.0177904
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.0178511
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.0178187
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.0178993
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.0178222
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.0178907
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.0179644
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.0178358
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.0178512
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.0178537
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.0178543
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.0179163
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.0178298
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.0177203
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.0176468
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.0176641
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.0177607
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.0178411
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.0178261
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.0178475
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.0178573
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.0179044
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.0179421
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.0179912
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.0177805
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.0177961
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.0178228
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.0177457
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.0177412
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 0.0178536
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 0.017973
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 0.0180691
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 0.0180149
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[116]	valid_0's binary_logloss: 0.0179569
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[117]	valid_0's binary_logloss: 0.0179019
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[118]	valid_0's binary_logloss: 0.0176194
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[119]	valid_0's binary_logloss: 0.0176756
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[120]	valid_0's binary_logloss: 0.0176056
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[121]	valid_0's binary_logloss: 0.0176033
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[122]	valid_0's binary_logloss: 0.0175181
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[123]	valid_0's binary_logloss: 0.0174115
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[124]	valid_0's binary_logloss: 0.0173141
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[125]	valid_0's binary_logloss: 0.0173627
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[126]	valid_0's binary_logloss: 0.0173511
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[127]	valid_0's binary_logloss: 0.017428
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[128]	valid_0's binary_logloss: 0.0174006
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[129]	valid_0's binary_logloss: 0.0173431
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[130]	valid_0's binary_logloss: 0.0173177
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[131]	valid_0's binary_logloss: 0.0172753
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[132]	valid_0's binary_logloss: 0.0173246
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[133]	valid_0's binary_logloss: 0.0173812
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[134]	valid_0's binary_logloss: 0.0173853
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[135]	valid_0's binary_logloss: 0.0174092
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[136]	valid_0's binary_logloss: 0.0173582
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[137]	valid_0's binary_logloss: 0.0173608
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[138]	valid_0's binary_logloss: 0.0173399
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[139]	valid_0's binary_logloss: 0.0172756
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[140]	valid_0's binary_logloss: 0.0172582
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[141]	valid_0's binary_logloss: 0.0172913
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[142]	valid_0's binary_logloss: 0.0172988
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[143]	valid_0's binary_logloss: 0.0173325
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[144]	valid_0's binary_logloss: 0.0173258
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[145]	valid_0's binary_logloss: 0.0173207
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[146]	valid_0's binary_logloss: 0.0173206
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[147]	valid_0's binary_logloss: 0.0173077
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[148]	valid_0's binary_logloss: 0.0172914
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[149]	valid_0's binary_logloss: 0.017344
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[150]	valid_0's binary_logloss: 0.0173793
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[151]	valid_0's binary_logloss: 0.0173647
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[152]	valid_0's binary_logloss: 0.017348
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[153]	valid_0's binary_logloss: 0.0173638
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[154]	valid_0's binary_logloss: 0.0173727
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[155]	valid_0's binary_logloss: 0.0173464
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[156]	valid_0's binary_logloss: 0.0173475
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[157]	valid_0's binary_logloss: 0.0173811
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[158]	valid_0's binary_logloss: 0.0174072
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[159]	valid_0's binary_logloss: 0.0175059
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[160]	valid_0's binary_logloss: 0.0175575
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[161]	valid_0's binary_logloss: 0.0174738
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[162]	valid_0's binary_logloss: 0.0174362
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[163]	valid_0's binary_logloss: 0.0174138
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[164]	valid_0's binary_logloss: 0.0174461
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[165]	valid_0's binary_logloss: 0.0175592
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[166]	valid_0's binary_logloss: 0.0176125
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[167]	valid_0's binary_logloss: 0.0176493
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[168]	valid_0's binary_logloss: 0.0176541
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[169]	valid_0's binary_logloss: 0.0176712
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

Trening klas:  52%|█████▏    | 260/500 [31:28<21:39,  5.41s/klasa, klasa=class_260, F1_klasy=0.8019, F1_macro=0.7189, drzewa=140]




Trening klas:  52%|█████▏    | 261/500 [31:28<23:11,  5.82s/klasa, klasa=class_260, F1_klasy=0.8019, F1_macro=0.7189, drzewa=140]

[170]	valid_0's binary_logloss: 0.0176126
[1]	valid_0's binary_logloss: 0.0174149
[2]	valid_0's binary_logloss: 0.0167096
[3]	valid_0's binary_logloss: 0.0160323
[4]	valid_0's binary_logloss: 0.0155007
[5]	valid_0's binary_logloss: 0.0150152
[6]	valid_0's binary_logloss: 0.0144644
[7]	valid_0's binary_logloss: 0.0140484
[8]	valid_0's binary_logloss: 0.0135687
[9]	valid_0's binary_logloss: 0.0131215
[10]	valid_0's binary_logloss: 0.0127066
[11]	valid_0's binary_logloss: 0.0123225
[12]	valid_0's binary_logloss: 0.0120538
[13]	valid_0's binary_logloss: 0.0118105
[14]	valid_0's binary_logloss: 0.01159
[15]	valid_0's binary_logloss: 0.0112925
[16]	valid_0's binary_logloss: 0.01112
[17]	valid_0's binary_logloss: 0.0108643
[18]	valid_0's binary_logloss: 0.0106273
[19]	valid_0's binary_logloss: 0.0104075
[20]	valid_0's binary_logloss: 0.0102019
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0100242
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.00985204
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.00968494
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.00953935
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.00940412
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.00927437
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.00915725
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.00905061
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.00896308
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.00888269
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.00880063
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.00872696
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.0086354
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.00857639
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.00850163
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.00843815
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.00840071
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.00840302
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.00841135
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.00833983
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.00831383
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.00829707
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.00829277
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.00818958
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.00818387
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.00819118
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.00819738
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.0082068
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.00822199
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.00823715
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.00806217
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.00796539
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.00787135
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.00777927
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.00779305
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.00779565
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.00778564
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.00778722
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.00780953
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.00781108
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.00776608
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.00772823
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.00766339
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.00764067
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.00762283
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.0074929
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.00750141
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.0074803
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.00748811
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.00731169
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.00733887
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.00733665
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.00736944
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.00738911
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.00729657
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.00726836
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.00727538
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.00728179
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.00723877
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.00726863
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.00727902
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.00731474
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.0072913
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.00734645
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.00737813
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.00736978
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.0073743
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.00741182
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.00743612
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.0074753
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.00746557
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.00741532
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.00741236
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.00744861
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.00748732
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.00748148
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.00748543
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.00751943
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.00752403
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.00762609
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.00767801
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.00774818
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.00779511
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.00784943
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.00787437
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.00792375
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

Trening klas:  52%|█████▏    | 261/500 [31:32<23:11,  5.82s/klasa, klasa=class_261, F1_klasy=0.9028, F1_macro=0.7196, drzewa=79]




Trening klas:  52%|█████▏    | 262/500 [31:32<20:48,  5.24s/klasa, klasa=class_261, F1_klasy=0.9028, F1_macro=0.7196, drzewa=79]

[107]	valid_0's binary_logloss: 0.00794821
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.00797905
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.00799386
[1]	valid_0's binary_logloss: 0.0271743
[2]	valid_0's binary_logloss: 0.0266049
[3]	valid_0's binary_logloss: 0.0260995
[4]	valid_0's binary_logloss: 0.0255915
[5]	valid_0's binary_logloss: 0.0251487
[6]	valid_0's binary_logloss: 0.0248799
[7]	valid_0's binary_logloss: 0.0245694
[8]	valid_0's binary_logloss: 0.0242017
[9]	valid_0's binary_logloss: 0.023893
[10]	valid_0's binary_logloss: 0.0235059
[11]	valid_0's binary_logloss: 0.0233014
[12]	valid_0's binary_logloss: 0.0230035
[13]	valid_0's binary_logloss: 0.0227191
[14]	valid_0's binary_logloss: 0.0225669
[15]	valid_0's binary_logloss: 0.0222619
[16]	valid_0's binary_logloss: 0.0220364
[17]	valid_0's binary_logloss: 0.0216511
[18]	valid_0's binary_logloss: 0.0213364
[19]	valid_0's binary_logloss: 0.021198
[20]	valid_0's binary_logloss: 0.021011
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0207854
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0206124
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.0205029
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0204137
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.020174
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.0200431
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.0199136
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.0198964
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.0199147
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.0198465
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.0197956
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.019696
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.0196032
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.0195179
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.0195299
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.0194223
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.0193568
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.0191747
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.0191332
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.0191372
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.0191339
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.0191432
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.0190408
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.0190205
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.0190873
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.0189219
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.0187634
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.0186216
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.0186612
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.0186458
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.0186138
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.0186521
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.0186169
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.0186046
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.0185228
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.018311
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.018246
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.0180271
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.0178334
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.0176989
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.0177053
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.0177691
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.0177031
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.017547
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.0175598
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.0176052
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.0175869
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.0176365
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.0177255
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.0177327
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.0176691
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.0177195
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.0177707
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.017748
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.0177415
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.0176764
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.0177097
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.0177407
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.0177694
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.0178195
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.017801
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.0178169
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.0178771
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.0178415
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.0178714
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.017927
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.0179415
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.017938
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.0180492
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.0180962
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.0181392
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.0181326
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.0181323
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

Trening klas:  52%|█████▏    | 262/500 [31:36<20:48,  5.24s/klasa, klasa=class_262, F1_klasy=0.6711, F1_macro=0.7194, drzewa=64]




Trening klas:  53%|█████▎    | 263/500 [31:36<19:40,  4.98s/klasa, klasa=class_262, F1_klasy=0.6711, F1_macro=0.7194, drzewa=64]

[94]	valid_0's binary_logloss: 0.0182719
[1]	valid_0's binary_logloss: 0.0519101
[2]	valid_0's binary_logloss: 0.0504954
[3]	valid_0's binary_logloss: 0.0491037
[4]	valid_0's binary_logloss: 0.0479765
[5]	valid_0's binary_logloss: 0.046836
[6]	valid_0's binary_logloss: 0.0463382
[7]	valid_0's binary_logloss: 0.0452605
[8]	valid_0's binary_logloss: 0.0446337
[9]	valid_0's binary_logloss: 0.0439022
[10]	valid_0's binary_logloss: 0.0429111
[11]	valid_0's binary_logloss: 0.0420343
[12]	valid_0's binary_logloss: 0.0409561
[13]	valid_0's binary_logloss: 0.0401037
[14]	valid_0's binary_logloss: 0.0392244
[15]	valid_0's binary_logloss: 0.0385326
[16]	valid_0's binary_logloss: 0.0378868
[17]	valid_0's binary_logloss: 0.0372827
[18]	valid_0's binary_logloss: 0.0367304
[19]	valid_0's binary_logloss: 0.036235
[20]	valid_0's binary_logloss: 0.0357272
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0353168
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0348876
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.0345802
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0342643
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.0341282
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.0339265
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.0333984
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.0330801
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.0327834
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.0324492
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.0323352
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.0322635
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.0319755
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.0316602
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.0313907
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.0311517
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.0308938
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.0306893
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.0304897
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.0302459
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.0300543
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.0297687
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.0295877
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.029529
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.0293402
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.029229
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.0291922
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.0291318
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.0290285
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.029072
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.0289683
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.0288014
[53]	valid_0's binary_logloss: 0.0287655
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.0286268
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.0285843
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.028543
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.0285378
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.0285474
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.0286469
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.0286547
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.0284864
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.028456
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.0282778
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.0282136
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.0281186
[66]	valid_0's binary_logloss: 0.0281685
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.0281641
[68]	valid_0's binary_logloss: 0.0282416
[69]	valid_0's binary_logloss: 0.0283345
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.0283914
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.0284307
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.0284821
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.0285532
[74]	valid_0's binary_logloss: 0.0286631
[75]	valid_0's binary_logloss: 0.0287092
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.0287738
[77]	valid_0's binary_logloss: 0.0288264
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.0288468
[79]	valid_0's binary_logloss: 0.028819
[80]	valid_0's binary_logloss: 0.0288874
[81]	valid_0's binary_logloss: 0.028932
[82]	valid_0's binary_logloss: 0.0288887
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.0289625
[84]	valid_0's binary_logloss: 0.0289042
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.0288527
[86]	valid_0's binary_logloss: 0.0288729
[87]	valid_0's binary_logloss: 0.0288894
[88]	valid_0's binary_logloss: 0.0288998
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.0289274
[90]	valid_0's binary_logloss: 0.0289641
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.0290253
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.0290926
[93]	valid_0's binary_logloss: 0.0291441
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.0292319
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

Trening klas:  53%|█████▎    | 263/500 [31:43<19:40,  4.98s/klasa, klasa=class_263, F1_klasy=0.7514, F1_macro=0.7195, drzewa=65]




Trening klas:  53%|█████▎    | 264/500 [31:43<21:22,  5.43s/klasa, klasa=class_263, F1_klasy=0.7514, F1_macro=0.7195, drzewa=65]

[95]	valid_0's binary_logloss: 0.0293434
[1]	valid_0's binary_logloss: 0.0537452
[2]	valid_0's binary_logloss: 0.052889
[3]	valid_0's binary_logloss: 0.0521233
[4]	valid_0's binary_logloss: 0.0512672
[5]	valid_0's binary_logloss: 0.0506631
[6]	valid_0's binary_logloss: 0.0499483
[7]	valid_0's binary_logloss: 0.048961
[8]	valid_0's binary_logloss: 0.0482936
[9]	valid_0's binary_logloss: 0.0477495
[10]	valid_0's binary_logloss: 0.0469827
[11]	valid_0's binary_logloss: 0.0474631
[12]	valid_0's binary_logloss: 0.0471848
[13]	valid_0's binary_logloss: 0.0466213
[14]	valid_0's binary_logloss: 0.046047
[15]	valid_0's binary_logloss: 0.0457791
[16]	valid_0's binary_logloss: 0.0455209
[17]	valid_0's binary_logloss: 0.0451499
[18]	valid_0's binary_logloss: 0.0449094
[19]	valid_0's binary_logloss: 0.0446725
[20]	valid_0's binary_logloss: 0.0444391
[21]	valid_0's binary_logloss: 0.0441024
[22]	valid_0's binary_logloss: 0.0437919
[23]	valid_0's binary_logloss: 0.043498
[24]	valid_0's binary_logloss: 0.0432178
[25]	valid_0's binary_logloss: 0.0428348
[26]	valid_0's binary_logloss: 0.0426054
[27]	valid_0's binary_logloss: 0.0421182
[28]	valid_0's binary_logloss: 0.0418837
[29]	valid_0's binary_logloss: 0.0416581
[30]	valid_0's binary_logloss: 0.041257
[31]	valid_0's binary_logloss: 0.0408918
[32]	valid_0's binary_logloss: 0.0405008
[33]	valid_0's binary_logloss: 0.040182
[34]	valid_0's binary_logloss: 0.0398959
[35]	valid_0's binary_logloss: 0.0395912
[36]	valid_0's binary_logloss: 0.0395181
[37]	valid_0's binary_logloss: 0.0394204
[38]	valid_0's binary_logloss: 0.0391733
[39]	valid_0's binary_logloss: 0.0390018
[40]	valid_0's binary_logloss: 0.0390113
[41]	valid_0's binary_logloss: 0.0388041
[42]	valid_0's binary_logloss: 0.0386794
[43]	valid_0's binary_logloss: 0.038538
[44]	valid_0's binary_logloss: 0.0383292
[45]	valid_0's binary_logloss: 0.0381241
[46]	valid_0's binary_logloss: 0.0381847
[47]	valid_0's binary_logloss: 0.0383585
[48]	valid_0's binary_logloss: 0.038275
[49]	valid_0's binary_logloss: 0.0383976
[50]	valid_0's binary_logloss: 0.0381991
[51]	valid_0's binary_logloss: 0.0380262
[52]	valid_0's binary_logloss: 0.0379245
[53]	valid_0's binary_logloss: 0.0378565
[54]	valid_0's binary_logloss: 0.0377556
[55]	valid_0's binary_logloss: 0.0376797
[56]	valid_0's binary_logloss: 0.0376697
[57]	valid_0's binary_logloss: 0.0375396
[58]	valid_0's binary_logloss: 0.0373513
[59]	valid_0's binary_logloss: 0.0373476
[60]	valid_0's binary_logloss: 0.0371902
[61]	valid_0's binary_logloss: 0.0372754
[62]	valid_0's binary_logloss: 0.0372294
[63]	valid_0's binary_logloss: 0.0372597
[64]	valid_0's binary_logloss: 0.0372739
[65]	valid_0's binary_logloss: 0.0372525
[66]	valid_0's binary_logloss: 0.03734
[67]	valid_0's binary_logloss: 0.0373125
[68]	valid_0's binary_logloss: 0.0373235
[69]	valid_0's binary_logloss: 0.0373894
[70]	valid_0's binary_logloss: 0.0374493
[71]	valid_0's binary_logloss: 0.0374561
[72]	valid_0's binary_logloss: 0.0374529
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.0375073
[74]	valid_0's binary_logloss: 0.0375039
[75]	valid_0's binary_logloss: 0.0375501
[76]	valid_0's binary_logloss: 0.0375831
[77]	valid_0's binary_logloss: 0.037534
[78]	valid_0's binary_logloss: 0.0376089
[79]	valid_0's binary_logloss: 0.0375993
[80]	valid_0's binary_logloss: 0.0378202
[81]	valid_0's binary_logloss: 0.0378837
[82]	valid_0's binary_logloss: 0.0380041
[83]	valid_0's binary_logloss: 0.0380185
[84]	valid_0's binary_logloss: 0.0380301
[85]	valid_0's binary_logloss: 0.0380261
[86]	valid_0's binary_logloss: 0.0379753
[87]	valid_0's binary_logloss: 0.0380695
[88]	valid_0's binary_logloss: 0.0380365
[89]	valid_0's binary_logloss: 0.0380874
[90]	valid_0's binary_logloss: 0.0381128

Trening klas:  53%|█████▎    | 264/500 [31:49<21:22,  5.43s/klasa, klasa=class_264, F1_klasy=0.3566, F1_macro=0.7182, drzewa=60]




Trening klas:  53%|█████▎    | 265/500 [31:49<21:59,  5.61s/klasa, klasa=class_264, F1_klasy=0.3566, F1_macro=0.7182, drzewa=60]

[1]	valid_0's binary_logloss: 0.0147716
[2]	valid_0's binary_logloss: 0.0142536
[3]	valid_0's binary_logloss: 0.0137472
[4]	valid_0's binary_logloss: 0.0132894
[5]	valid_0's binary_logloss: 0.0128201
[6]	valid_0's binary_logloss: 0.0123593
[7]	valid_0's binary_logloss: 0.0119543
[8]	valid_0's binary_logloss: 0.0115552
[9]	valid_0's binary_logloss: 0.011188
[10]	valid_0's binary_logloss: 0.0108679
[11]	valid_0's binary_logloss: 0.0105658
[12]	valid_0's binary_logloss: 0.0102658
[13]	valid_0's binary_logloss: 0.0100132
[14]	valid_0's binary_logloss: 0.00978562
[15]	valid_0's binary_logloss: 0.00952811
[16]	valid_0's binary_logloss: 0.00929493
[17]	valid_0's binary_logloss: 0.0091089
[18]	valid_0's binary_logloss: 0.00893035
[19]	valid_0's binary_logloss: 0.00876947
[20]	valid_0's binary_logloss: 0.00861482
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0084417
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.00829719
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.00811161
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.00795686
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.00778943
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.00768074
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.00755806
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.00744361
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.00734084
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.00726721
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.00720679
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.00713314
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.00708305
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.00696196
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.00691806
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.00684447
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.00674366
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.00667097
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.00661588
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.0065708
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.00652314
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.00647275
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.00645227
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.00642299
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.0063932
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.00633302
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.00629605
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.00626837
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.00616222
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.00612174
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.00613689
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.00611866
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.00609494
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.00606812
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.00602369
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.00603573
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.00606766
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.00606426
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.00601233
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.00601783
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.00602082
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.00594419
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.00586667
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.00582933
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.0058
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.00573761
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.00570338
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.00571687
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.00568147
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.0056775
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.00563822
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.0056342
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.00559879
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.00553573
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.0054903
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.00548357
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.00537784
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.00536517
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.00534187
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.00532103
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.0053425
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.00537744
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.00539468
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.00538403
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.00539701
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.00539403
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.00538199
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.00537286
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.00539943
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.00540333
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.0053822
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.00535755
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.00529824
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.00530122
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.00529441
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.00529031
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.005266
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.00519105
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.00518187
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.00514099
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.0051325
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.00509659
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.00509267
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.00509438
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.00509186
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.00506223
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.00505733
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.00503743
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.00501187
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.00500825
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.00500503
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 0.00497491
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 0.00497003
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 0.00497383
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 0.00494697
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[116]	valid_0's binary_logloss: 0.00494943
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[117]	valid_0's binary_logloss: 0.00496753
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[118]	valid_0's binary_logloss: 0.00497312
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[119]	valid_0's binary_logloss: 0.00498141
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[120]	valid_0's binary_logloss: 0.00498107
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[121]	valid_0's binary_logloss: 0.00500129
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[122]	valid_0's binary_logloss: 0.00502194
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[123]	valid_0's binary_logloss: 0.0050547
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[124]	valid_0's binary_logloss: 0.00507125
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[125]	valid_0's binary_logloss: 0.00506979
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[126]	valid_0's binary_logloss: 0.00507432
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[127]	valid_0's binary_logloss: 0.00510903
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[128]	valid_0's binary_logloss: 0.0051428
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[129]	valid_0's binary_logloss: 0.00519922
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[130]	valid_0's binary_logloss: 0.00520657
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[131]	valid_0's binary_logloss: 0.00524035
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[132]	valid_0's binary_logloss: 0.00526674
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[133]	valid_0's binary_logloss: 0.00529405
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[134]	valid_0's binary_logloss: 0.00530189
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[135]	valid_0's binary_logloss: 0.00534444
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[136]	valid_0's binary_logloss: 0.00535684
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[137]	valid_0's binary_logloss: 0.00542298
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[138]	valid_0's binary_logloss: 0.0054814
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[139]	valid_0's binary_logloss: 0.00554971
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[140]	valid_0's binary_logloss: 0.00561723
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[141]	valid_0's binary_logloss: 0.0056388
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[142]	valid_0's binary_logloss: 0.00569747
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[143]	valid_0's binary_logloss: 0.00572401
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

Trening klas:  53%|█████▎    | 265/500 [31:54<21:59,  5.61s/klasa, klasa=class_265, F1_klasy=0.6818, F1_macro=0.7180, drzewa=115]




Trening klas:  53%|█████▎    | 266/500 [31:54<21:08,  5.42s/klasa, klasa=class_265, F1_klasy=0.6818, F1_macro=0.7180, drzewa=115]

[144]	valid_0's binary_logloss: 0.00577599
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[145]	valid_0's binary_logloss: 0.00580457
[1]	valid_0's binary_logloss: 0.0211424
[2]	valid_0's binary_logloss: 0.0199633
[3]	valid_0's binary_logloss: 0.0189148
[4]	valid_0's binary_logloss: 0.0179732
[5]	valid_0's binary_logloss: 0.0170978
[6]	valid_0's binary_logloss: 0.0165468
[7]	valid_0's binary_logloss: 0.0157848
[8]	valid_0's binary_logloss: 0.0150829
[9]	valid_0's binary_logloss: 0.0145453
[10]	valid_0's binary_logloss: 0.0139329
[11]	valid_0's binary_logloss: 0.013357
[12]	valid_0's binary_logloss: 0.0127892
[13]	valid_0's binary_logloss: 0.0122796
[14]	valid_0's binary_logloss: 0.011796
[15]	valid_0's binary_logloss: 0.0113405
[16]	valid_0's binary_logloss: 0.0108874
[17]	valid_0's binary_logloss: 0.012299
[18]	valid_0's binary_logloss: 0.0118673
[19]	valid_0's binary_logloss: 0.0114695
[20]	valid_0's binary_logloss: 0.0110849
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0107236
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0103779
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.0100503
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.00973855
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.00945457
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.00918201
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.00901344
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.00879721
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.00859896
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.00837042
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.00815449
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.00794705
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.00774954
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.00756199
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.00738502
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.00720855
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.00704397
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.00690669
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.0067697
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.00662205
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.00649269
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.00636339
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.00625236
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.00613305
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.00602129
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.00590699
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.00579917
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.00569726
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.00560303
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.00551261
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.00542997
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.00535187
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.00529504
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.00523063
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.00515936
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.00511051
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.00505681
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.00496679
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.00487794
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.00484606
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.00475082
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.00464793
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.00458521
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.0045214
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.00446555
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.00441838
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.00437545
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.00433903
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.00429199
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.00422898
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.00419099
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.00418487
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.00419344
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.00416951
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.00413439
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.00410839
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.00408984
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.00406658
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.0040486
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.00404438
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.00403149
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.00401799
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.00399758
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.0040013
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.00397501
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.00402671
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.004009
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.00396055
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.00391137
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.0039199
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.00390975
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.0038767
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.00388438
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.00383486
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.00382354
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.00382654
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.00381749
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.00381404
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.00383225
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.00384323
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.00385236
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.00385031
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.00386873
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.00386297
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.00386178
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.00385003
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.00385969
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.00387631
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.00384118
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.0038571
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.00386166
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 0.00383402
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 0.00380336
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 0.00379545
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 0.00379361
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[116]	valid_0's binary_logloss: 0.00380038
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[117]	valid_0's binary_logloss: 0.0037922
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[118]	valid_0's binary_logloss: 0.00379983
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[119]	valid_0's binary_logloss: 0.00377956
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[120]	valid_0's binary_logloss: 0.00376288
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[121]	valid_0's binary_logloss: 0.00376602
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[122]	valid_0's binary_logloss: 0.00375918
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[123]	valid_0's binary_logloss: 0.00375183
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[124]	valid_0's binary_logloss: 0.00375029
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[125]	valid_0's binary_logloss: 0.00375345
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[126]	valid_0's binary_logloss: 0.00375747
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[127]	valid_0's binary_logloss: 0.00375216
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[128]	valid_0's binary_logloss: 0.0037573
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[129]	valid_0's binary_logloss: 0.00377306
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[130]	valid_0's binary_logloss: 0.00378595
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[131]	valid_0's binary_logloss: 0.0037778
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[132]	valid_0's binary_logloss: 0.00376458
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[133]	valid_0's binary_logloss: 0.00374905
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[134]	valid_0's binary_logloss: 0.00374258
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[135]	valid_0's binary_logloss: 0.00373839
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[136]	valid_0's binary_logloss: 0.00374669
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[137]	valid_0's binary_logloss: 0.00375512
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[138]	valid_0's binary_logloss: 0.00375271
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[139]	valid_0's binary_logloss: 0.00375113
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[140]	valid_0's binary_logloss: 0.00376219
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[141]	valid_0's binary_logloss: 0.0037819
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[142]	valid_0's binary_logloss: 0.00378691
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[143]	valid_0's binary_logloss: 0.00378642
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[144]	valid_0's binary_logloss: 0.00379171
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[145]	valid_0's binary_logloss: 0.00378776
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[146]	valid_0's binary_logloss: 0.00378193
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[147]	valid_0's binary_logloss: 0.00377561
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[148]	valid_0's binary_logloss: 0.0037699
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[149]	valid_0's binary_logloss: 0.00377207
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[150]	valid_0's binary_logloss: 0.00376727
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[151]	valid_0's binary_logloss: 0.0037656
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[152]	valid_0's binary_logloss: 0.00376661
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[153]	valid_0's binary_logloss: 0.0037638
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[154]	valid_0's binary_logloss: 0.00376139
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[155]	valid_0's binary_logloss: 0.00375258
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[156]	valid_0's binary_logloss: 0.0037554
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[157]	valid_0's binary_logloss: 0.00375335
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[158]	valid_0's binary_logloss: 0.00373191
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[159]	valid_0's binary_logloss: 0.00373552
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[160]	valid_0's binary_logloss: 0.00372939
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[161]	valid_0's binary_logloss: 0.00373416
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[162]	valid_0's binary_logloss: 0.00373893
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[163]	valid_0's binary_logloss: 0.00374132
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[164]	valid_0's binary_logloss: 0.0037344
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[165]	valid_0's binary_logloss: 0.00373695
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[166]	valid_0's binary_logloss: 0.00373511
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[167]	valid_0's binary_logloss: 0.00374478
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[168]	valid_0's binary_logloss: 0.00375399
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[169]	valid_0's binary_logloss: 0.00376372
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[170]	valid_0's binary_logloss: 0.00377722
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[171]	valid_0's binary_logloss: 0.00378719
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[172]	valid_0's binary_logloss: 0.00379979
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[173]	valid_0's binary_logloss: 0.00381039
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[174]	valid_0's binary_logloss: 0.00382075
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[175]	valid_0's binary_logloss: 0.00382792
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[176]	valid_0's binary_logloss: 0.00382854
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[177]	valid_0's binary_logloss: 0.00382793
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[178]	valid_0's binary_logloss: 0.00384128
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[179]	valid_0's binary_logloss: 0.00384747
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[180]	valid_0's binary_logloss: 0.00386427
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[181]	valid_0's binary_logloss: 0.00386247
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[182]	valid_0's binary_logloss: 0.00386076

Trening klas:  53%|█████▎    | 266/500 [31:59<21:08,  5.42s/klasa, klasa=class_266, F1_klasy=0.9811, F1_macro=0.7190, drzewa=160]




Trening klas:  53%|█████▎    | 267/500 [31:59<21:04,  5.43s/klasa, klasa=class_266, F1_klasy=0.9811, F1_macro=0.7190, drzewa=160]

[189]	valid_0's binary_logloss: 0.00386703
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[190]	valid_0's binary_logloss: 0.00386182
[1]	valid_0's binary_logloss: 0.0234532
[2]	valid_0's binary_logloss: 0.0228341
[3]	valid_0's binary_logloss: 0.0222592
[4]	valid_0's binary_logloss: 0.0216263
[5]	valid_0's binary_logloss: 0.0211284
[6]	valid_0's binary_logloss: 0.0208891
[7]	valid_0's binary_logloss: 0.0201691
[8]	valid_0's binary_logloss: 0.0196415
[9]	valid_0's binary_logloss: 0.0191402
[10]	valid_0's binary_logloss: 0.018666
[11]	valid_0's binary_logloss: 0.0182154
[12]	valid_0's binary_logloss: 0.0176942
[13]	valid_0's binary_logloss: 0.0172058
[14]	valid_0's binary_logloss: 0.0168074
[15]	valid_0's binary_logloss: 0.0164291
[16]	valid_0's binary_logloss: 0.0160479
[17]	valid_0's binary_logloss: 0.0156641
[18]	valid_0's binary_logloss: 0.01537
[19]	valid_0's binary_logloss: 0.015067
[20]	valid_0's binary_logloss: 0.014742
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0146764
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0144509
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.0141877
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0141384
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.0139929
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.0137915
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.0136045
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.0133898
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.0132804
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.0131384
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.0129804
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.0128116
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.0126702
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.0125105
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.0123579
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.012234
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.0120945
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.0119622
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.0118429
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.0117212
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.0116116
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.0115073
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.0112848
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.0111888
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.0110345
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.0109874
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.0109419
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.0108981
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.0108566
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.0108144
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.0106955
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.0105786
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.0105021
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.0104248
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.0103278
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.0101854
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.0100381
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.00991659
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.00979976
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.00975685
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.00969999
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.00958554
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.00957922
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.00957444
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.00947905
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.00945053
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.00942761
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.00939987
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.00917985
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.00902439
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.00879813
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.00874843
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.00857805
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.0084629
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.00840634
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.00837446
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.008311
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.00826955
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.00825716
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.00821859
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.00832163
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.00829621
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.0082956
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.00845254
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.00845281
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.00850738
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.00861321
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.00863994
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.00862906
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.00871125
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.00874335
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.00874713
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.00874574
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.00876121
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.00871795
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.00878079
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.00886614
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.00891746
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.00896232
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.00907091
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.00908724
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.00910408
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.00913109
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.00915911
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.00922527
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.00921985
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.00920478
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.00924848
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.00929477
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.00929328

Trening klas:  53%|█████▎    | 267/500 [32:03<21:04,  5.43s/klasa, klasa=class_267, F1_klasy=0.8160, F1_macro=0.7194, drzewa=80]




Trening klas:  54%|█████▎    | 268/500 [32:03<19:07,  4.95s/klasa, klasa=class_267, F1_klasy=0.8160, F1_macro=0.7194, drzewa=80]

[1]	valid_0's binary_logloss: 0.0415157
[2]	valid_0's binary_logloss: 0.0405917
[3]	valid_0's binary_logloss: 0.0393357
[4]	valid_0's binary_logloss: 0.0382677
[5]	valid_0's binary_logloss: 0.0371769
[6]	valid_0's binary_logloss: 0.0364698
[7]	valid_0's binary_logloss: 0.0356766
[8]	valid_0's binary_logloss: 0.0349077
[9]	valid_0's binary_logloss: 0.0342305
[10]	valid_0's binary_logloss: 0.0335048
[11]	valid_0's binary_logloss: 0.0329442
[12]	valid_0's binary_logloss: 0.0324866
[13]	valid_0's binary_logloss: 0.0321091
[14]	valid_0's binary_logloss: 0.0315197
[15]	valid_0's binary_logloss: 0.0311416
[16]	valid_0's binary_logloss: 0.0308412
[17]	valid_0's binary_logloss: 0.030219
[18]	valid_0's binary_logloss: 0.0297002
[19]	valid_0's binary_logloss: 0.02917
[20]	valid_0's binary_logloss: 0.0286987
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0283059
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0279048
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.0275808
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0273247
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.0270321
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.0267826
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.026439
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.026009
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.0256437
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.0254525
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.0251423
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.0250215
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.0248948
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.0247957
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.0247303
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.024626
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.0244673
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.0243561
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.0243157
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.0242671
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.0241796
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.0241236
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.0238359
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.0236043
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.0234785
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.0232705
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.0230869
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.0230348
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.0227841
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.0226979
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.0226365
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.022605
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.0225482
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.0225776
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.0224312
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.0224378
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.0225081
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.0224952
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.0224735
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.0224657
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.0224569
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.0225064
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.0225174
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.0225585
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.0226032
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.0226771
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.0227032
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.0227189
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.0227069
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.0227244
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.0227448
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.0227887
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.0228618
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.0227955
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.02271
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.0227243
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.0228174
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.0228878
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.0228
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.0228293
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.0227638
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.0227631
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.0228025
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

Trening klas:  54%|█████▎    | 268/500 [32:08<19:07,  4.95s/klasa, klasa=class_268, F1_klasy=0.6341, F1_macro=0.7190, drzewa=55]




Trening klas:  54%|█████▍    | 269/500 [32:08<18:36,  4.83s/klasa, klasa=class_268, F1_klasy=0.6341, F1_macro=0.7190, drzewa=55]

[84]	valid_0's binary_logloss: 0.0227255
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.0227252
[1]	valid_0's binary_logloss: 0.0444946
[2]	valid_0's binary_logloss: 0.0435587
[3]	valid_0's binary_logloss: 0.0423133
[4]	valid_0's binary_logloss: 0.0415666
[5]	valid_0's binary_logloss: 0.0406553
[6]	valid_0's binary_logloss: 0.0413111
[7]	valid_0's binary_logloss: 0.0407708
[8]	valid_0's binary_logloss: 0.0402464
[9]	valid_0's binary_logloss: 0.0395564
[10]	valid_0's binary_logloss: 0.0391096
[11]	valid_0's binary_logloss: 0.0389617
[12]	valid_0's binary_logloss: 0.0385654
[13]	valid_0's binary_logloss: 0.0373849
[14]	valid_0's binary_logloss: 0.0370797
[15]	valid_0's binary_logloss: 0.0365118
[16]	valid_0's binary_logloss: 0.0361033
[17]	valid_0's binary_logloss: 0.0352685
[18]	valid_0's binary_logloss: 0.034896
[19]	valid_0's binary_logloss: 0.033978
[20]	valid_0's binary_logloss: 0.0335446
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0332552
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0327125
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.0321723
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0319396
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.0313829
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.0309818
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.0306858
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.030494
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.0300159
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.0298405
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.0294372
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.0291764
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.0290151
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.0289039
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.0286123
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.028319
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.0279589
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.0276233
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.0273061
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.0268826
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.0266987
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.0265818
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.0263904
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.0262517
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.0261517
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.0258518
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.0255588
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.0252508
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.025011
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.0249962
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.0249694
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.0248645
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.0247922
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.024685
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.0245743
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.0243908
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.0242594
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.0240633
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.0240251
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.0239101
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.0236924
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.0237161
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.0236195
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.0235177
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.0234377
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.0232876
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.0232018
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.0229983
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.0226556
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.0224548
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.022484
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.0224841
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.0225431
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.0225045
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.0224368
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.0224873
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.0224469
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.0224003
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.0223667
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.0223899
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.0224112
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.0225023
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.0224707
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.0224892
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.0223917
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.0223884
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.022415
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.02237
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.0223353
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.0223457
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.0221806
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.0221456
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.0220857
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.0218866
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.0218464
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.0216431
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.0215913
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.0214863
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.0213586
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.0213435
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.0212872
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.0212817
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.0213043
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.0213423
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.0213666
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.0213621
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.0213709
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.0214444
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.0215288
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.0216203
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.0217167
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 0.0216913
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 0.0217637
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 0.0218299
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 0.0219876
[116]	valid_0's binary_logloss: 0.0219721
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[117]	valid_0's binary_logloss: 0.0219448
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[118]	valid_0's binary_logloss: 0.0219505
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[119]	valid_0's binary_logloss: 0.0218719
[120]	valid_0's binary_logloss: 0.021821
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[121]	valid_0's binary_logloss: 0.0218158
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[122]	valid_0's binary_logloss: 0.0218337
[123]	valid_0's binary_logloss: 0.0218484
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[124]	valid_0's binary_logloss: 0.0219309
[125]	valid_0's binary_logloss: 0.0218877
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[126]	valid_0's binary_logloss: 0.0218691
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[127]	valid_0's binary_logloss: 0.021841
[128]	valid_0's binary_logloss: 0.0218872
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[129]	valid_0's binary_logloss: 0.0218601
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[130]	valid_0's binary_logloss: 0.0217777
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[131]	valid_0's binary_logloss: 0.0218029
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

Trening klas:  54%|█████▍    | 269/500 [32:14<18:36,  4.83s/klasa, klasa=class_269, F1_klasy=0.6752, F1_macro=0.7189, drzewa=102]




Trening klas:  54%|█████▍    | 270/500 [32:14<20:37,  5.38s/klasa, klasa=class_269, F1_klasy=0.6752, F1_macro=0.7189, drzewa=102]

[132]	valid_0's binary_logloss: 0.0218228
[1]	valid_0's binary_logloss: 0.029602
[2]	valid_0's binary_logloss: 0.0283891
[3]	valid_0's binary_logloss: 0.0273136
[4]	valid_0's binary_logloss: 0.0263252
[5]	valid_0's binary_logloss: 0.0254278
[6]	valid_0's binary_logloss: 0.024707
[7]	valid_0's binary_logloss: 0.0240038
[8]	valid_0's binary_logloss: 0.0232378
[9]	valid_0's binary_logloss: 0.0226147
[10]	valid_0's binary_logloss: 0.0218366
[11]	valid_0's binary_logloss: 0.0211415
[12]	valid_0's binary_logloss: 0.0203791
[13]	valid_0's binary_logloss: 0.0199227
[14]	valid_0's binary_logloss: 0.0193395
[15]	valid_0's binary_logloss: 0.0189382
[16]	valid_0's binary_logloss: 0.0184498
[17]	valid_0's binary_logloss: 0.0178938
[18]	valid_0's binary_logloss: 0.0174823
[19]	valid_0's binary_logloss: 0.0171612
[20]	valid_0's binary_logloss: 0.0167249
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0164763
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0162712
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.0160025
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0157867
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.0155895
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.0152286
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.0149057
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.014611
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.0143275
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.0141078
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.0138165
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.0135699
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.0134937
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.0132579
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.0129883
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.0128147
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.0126497
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.0125088
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.0123361
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.0122026
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.012113
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.0120057
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.0119279
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.0118417
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.011771
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.0117283
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.0116513
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.0115895
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.011558
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.0114168
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.0113715
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.0113504
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.0112594
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.0111752
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.0110847
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.010942
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.0109108
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.0108937
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.0108781
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.0108385
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.0107898
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.0107627
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.0107336
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.0107208
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.0107488
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.0107102
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.0106938
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.0107127
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.0106231
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.0106133
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.0104965
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.0104844
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.0104861
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.0104767
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.0103972
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.0103675
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.0103738
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.0103703
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.0103509
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.0103891
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.0103837
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.010394
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.0104011
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.0104489
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.0104776
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.0103787
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.0104142
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.0104528
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.0104718
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.0105092
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.0105218
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.0104907
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.0104661
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.0104607
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.0104402
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.0104654
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.0104684
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.0105166
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.0105465
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.0105987
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.0105667
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.0105561
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.0105041
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.0105353
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.0105128
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.0104889
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.0104776
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.0104308
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.0104089

Trening klas:  54%|█████▍    | 270/500 [32:18<20:37,  5.38s/klasa, klasa=class_270, F1_klasy=0.8571, F1_macro=0.7194, drzewa=79]




Trening klas:  54%|█████▍    | 271/500 [32:18<18:22,  4.81s/klasa, klasa=class_270, F1_klasy=0.8571, F1_macro=0.7194, drzewa=79]

[1]	valid_0's binary_logloss: 0.0284885
[2]	valid_0's binary_logloss: 0.0278437
[3]	valid_0's binary_logloss: 0.0272438
[4]	valid_0's binary_logloss: 0.0265558
[5]	valid_0's binary_logloss: 0.0261372
[6]	valid_0's binary_logloss: 0.0313373
[7]	valid_0's binary_logloss: 0.0308329
[8]	valid_0's binary_logloss: 0.0302515
[9]	valid_0's binary_logloss: 0.0296888
[10]	valid_0's binary_logloss: 0.0292142
[11]	valid_0's binary_logloss: 0.0327418
[12]	valid_0's binary_logloss: 0.032252
[13]	valid_0's binary_logloss: 0.0317631
[14]	valid_0's binary_logloss: 0.0314625
[15]	valid_0's binary_logloss: 0.0310489
[16]	valid_0's binary_logloss: 0.0304825
[17]	valid_0's binary_logloss: 0.0302112
[18]	valid_0's binary_logloss: 0.029824
[19]	valid_0's binary_logloss: 0.0293744
[20]	valid_0's binary_logloss: 0.0289405
[21]	valid_0's binary_logloss: 0.0285186
[22]	valid_0's binary_logloss: 0.0280424
[23]	valid_0's binary_logloss: 0.0276475
[24]	valid_0's binary_logloss: 0.0273358
[25]	valid_0's binary_logloss: 0.0269132
[26]	valid_0's binary_logloss: 0.0265103
[27]	valid_0's binary_logloss: 0.0261997
[28]	valid_0's binary_logloss: 0.026033
[29]	valid_0's binary_logloss: 0.0257882
[30]	valid_0's binary_logloss: 0.0256963
[31]	valid_0's binary_logloss: 0.0255583
[32]	valid_0's binary_logloss: 0.0252557
[33]	valid_0's binary_logloss: 0.0250322
[34]	valid_0's binary_logloss: 0.0248377
[35]	valid_0's binary_logloss: 0.0244894
[36]	valid_0's binary_logloss: 0.0241989
[37]	valid_0's binary_logloss: 0.0240408
[38]	valid_0's binary_logloss: 0.0239247
[39]	valid_0's binary_logloss: 0.0238171
[40]	valid_0's binary_logloss: 0.0236026
[41]	valid_0's binary_logloss: 0.0234823
[42]	valid_0's binary_logloss: 0.023289
[43]	valid_0's binary_logloss: 0.0230746
[44]	valid_0's binary_logloss: 0.0229221
[45]	valid_0's binary_logloss: 0.0226847
[46]	valid_0's binary_logloss: 0.0225036
[47]	valid_0's binary_logloss: 0.0222943
[48]	valid_0's binary_logloss: 0.0220825
[49]	valid_0's binary_logloss: 0.0218001
[50]	valid_0's binary_logloss: 0.0216667
[51]	valid_0's binary_logloss: 0.0215213
[52]	valid_0's binary_logloss: 0.0213424
[53]	valid_0's binary_logloss: 0.0212696
[54]	valid_0's binary_logloss: 0.021144
[55]	valid_0's binary_logloss: 0.0209546
[56]	valid_0's binary_logloss: 0.0208438
[57]	valid_0's binary_logloss: 0.0206834
[58]	valid_0's binary_logloss: 0.0206977
[59]	valid_0's binary_logloss: 0.0204377
[60]	valid_0's binary_logloss: 0.0203406
[61]	valid_0's binary_logloss: 0.0203151
[62]	valid_0's binary_logloss: 0.0200923
[63]	valid_0's binary_logloss: 0.0200268
[64]	valid_0's binary_logloss: 0.0200456
[65]	valid_0's binary_logloss: 0.0199968
[66]	valid_0's binary_logloss: 0.019736
[67]	valid_0's binary_logloss: 0.0195924
[68]	valid_0's binary_logloss: 0.0194509
[69]	valid_0's binary_logloss: 0.0193247
[70]	valid_0's binary_logloss: 0.019257
[71]	valid_0's binary_logloss: 0.0192999
[72]	valid_0's binary_logloss: 0.0192213
[73]	valid_0's binary_logloss: 0.0192139
[74]	valid_0's binary_logloss: 0.0191742
[75]	valid_0's binary_logloss: 0.0190789
[76]	valid_0's binary_logloss: 0.0190454
[77]	valid_0's binary_logloss: 0.0189888
[78]	valid_0's binary_logloss: 0.0188292
[79]	valid_0's binary_logloss: 0.0187924
[80]	valid_0's binary_logloss: 0.018775
[81]	valid_0's binary_logloss: 0.0186232
[82]	valid_0's binary_logloss: 0.0185548
[83]	valid_0's binary_logloss: 0.0183471
[84]	valid_0's binary_logloss: 0.0183069
[85]	valid_0's binary_logloss: 0.0182774
[86]	valid_0's binary_logloss: 0.0182183
[87]	valid_0's binary_logloss: 0.0181364
[88]	valid_0's binary_logloss: 0.0180829
[89]	valid_0's binary_logloss: 0.018123
[90]	valid_0's binary_logloss: 0.0180973
[91]	valid_0's binary_logloss: 0.018213
[92]	valid_0's binary_logloss: 0.0182441
[93]	valid_0's binary_logloss: 0.0182363
[94]	valid_0's binary_logloss: 0.0182058
[95]	valid_0's binary_logloss: 0.0182068
[96]	valid_0's binary_logloss: 0.0182704
[97]	valid_0's binary_logloss: 0.0184032
[98]	valid_0's binary_logloss: 0.0184161
[99]	valid_0's binary_logloss: 0.0183302
[100]	valid_0's binary_logloss: 0.0183238
[101]	valid_0's binary_logloss: 0.0183201
[102]	valid_0's binary_logloss: 0.018245
[103]	valid_0's binary_logloss: 0.0182916
[104]	valid_0's binary_logloss: 0.0182882
[105]	valid_0's binary_logloss: 0.0183076
[106]	valid_0's binary_logloss: 0.0181976
[107]	valid_0's binary_logloss: 0.0182193
[108]	valid_0's binary_logloss: 0.0181666
[109]	valid_0's binary_logloss: 0.0181269
[110]	valid_0's binary_logloss: 0.0180914
[111]	valid_0's binary_logloss: 0.0179156
[112]	valid_0's binary_logloss: 0.0179335
[113]	valid_0's binary_logloss: 0.0176587
[114]	valid_0's binary_logloss: 0.0176427
[115]	valid_0's binary_logloss: 0.017502
[116]	valid_0's binary_logloss: 0.0175135
[117]	valid_0's binary_logloss: 0.0175915
[118]	valid_0's binary_logloss: 0.0175931
[119]	valid_0's binary_logloss: 0.0176056
[120]	valid_0's binary_logloss: 0.0176459
[121]	valid_0's binary_logloss: 0.0177492
[122]	valid_0's binary_logloss: 0.0176807
[123]	valid_0's binary_logloss: 0.0176787
[124]	valid_0's binary_logloss: 0.0174525
[125]	valid_0's binary_logloss: 0.0172561
[126]	valid_0's binary_logloss: 0.017315
[127]	valid_0's binary_logloss: 0.0174107
[128]	valid_0's binary_logloss: 0.017421
[129]	valid_0's binary_logloss: 0.0174627
[130]	valid_0's binary_logloss: 0.0175554
[131]	valid_0's binary_logloss: 0.0175967
[132]	valid_0's binary_logloss: 0.0175181
[133]	valid_0's binary_logloss: 0.0174319
[134]	valid_0's binary_logloss: 0.0173604
[135]	valid_0's binary_logloss: 0.0173588
[136]	valid_0's binary_logloss: 0.0172701
[137]	valid_0's binary_logloss: 0.0173743
[138]	valid_0's binary_logloss: 0.0173789
[139]	valid_0's binary_logloss: 0.0174489
[140]	valid_0's binary_logloss: 0.0175744
[141]	valid_0's binary_logloss: 0.0174938
[142]	valid_0's binary_logloss: 0.0174988
[143]	valid_0's binary_logloss: 0.0174122
[144]	valid_0's binary_logloss: 0.0173475
[145]	valid_0's binary_logloss: 0.0173702
[146]	valid_0's binary_logloss: 0.0173088
[147]	valid_0's binary_logloss: 0.0173172
[148]	valid_0's binary_logloss: 0.017474
[149]	valid_0's binary_logloss: 0.0174471
[150]	valid_0's binary_logloss: 0.0174127
[151]	valid_0's binary_logloss: 0.0175195
[152]	valid_0's binary_logloss: 0.0176243
[153]	valid_0's binary_logloss: 0.0176549
[154]	valid_0's binary_logloss: 0.0175904

Trening klas:  54%|█████▍    | 271/500 [32:30<18:22,  4.81s/klasa, klasa=class_271, F1_klasy=0.5275, F1_macro=0.7187, drzewa=125]




Trening klas:  54%|█████▍    | 272/500 [32:30<26:12,  6.90s/klasa, klasa=class_271, F1_klasy=0.5275, F1_macro=0.7187, drzewa=125]

[155]	valid_0's binary_logloss: 0.0175827
[1]	valid_0's binary_logloss: 0.0530038
[2]	valid_0's binary_logloss: 0.0515784
[3]	valid_0's binary_logloss: 0.0500394
[4]	valid_0's binary_logloss: 0.0490362
[5]	valid_0's binary_logloss: 0.048386
[6]	valid_0's binary_logloss: 0.0467404
[7]	valid_0's binary_logloss: 0.0453917
[8]	valid_0's binary_logloss: 0.0438434
[9]	valid_0's binary_logloss: 0.0425199
[10]	valid_0's binary_logloss: 0.041167
[11]	valid_0's binary_logloss: 0.0398703
[12]	valid_0's binary_logloss: 0.0392516
[13]	valid_0's binary_logloss: 0.0383185
[14]	valid_0's binary_logloss: 0.0373538
[15]	valid_0's binary_logloss: 0.0368783
[16]	valid_0's binary_logloss: 0.0361018
[17]	valid_0's binary_logloss: 0.0353514
[18]	valid_0's binary_logloss: 0.0344641
[19]	valid_0's binary_logloss: 0.0337525
[20]	valid_0's binary_logloss: 0.033318
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0328979
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0320887
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.0315095
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0309299
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.0304467
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.0300072
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.0295703
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.0293731
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.0289999
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.0285421
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.0282554
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.0278982
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.027379
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.0272076
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.026842
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.0262685
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.0258487
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.0254561
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.025047
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.024655
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.0243184
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.023855
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.0235459
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.0233015
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.0230731
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.0228319
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.0226498
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.0225702
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.0223779
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.0220735
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.0218531
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.0216405
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.02153
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.0212179
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.0210153
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.0208164
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.020702
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.0206922
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.0205947
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.0205087
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.0204907
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.0204104
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.0203779
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.0203366
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.0202871
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.0201243
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.0200152
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.0198716
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.0197181
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.0195754
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.0194847
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.0194825
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.0193513
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.0193507
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.019271
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.0191909
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.0190308
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.0189558
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.0188764
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.0189468
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.0188896
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.0188531
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.0188315
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.0187466
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.0187442
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.018784
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.0187977
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.0187663
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.0187533
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.0187632
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.0187933
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.018818
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.0188211
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.0188737
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.0189302
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.0188498
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.018796
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.0187572
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.0186844
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.0186525
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.0185944
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.0185917
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.0185649
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.0186036
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.018533
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.0185249
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.0184973
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.0184654
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.0184277
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.0184208
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.0183752
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 0.0183942
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 0.0183815
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 0.0183004
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 0.0183723
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[116]	valid_0's binary_logloss: 0.0184235
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[117]	valid_0's binary_logloss: 0.0184733
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[118]	valid_0's binary_logloss: 0.0184513
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[119]	valid_0's binary_logloss: 0.0184574
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[120]	valid_0's binary_logloss: 0.0185689
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[121]	valid_0's binary_logloss: 0.018563
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[122]	valid_0's binary_logloss: 0.0186244
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[123]	valid_0's binary_logloss: 0.018614
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[124]	valid_0's binary_logloss: 0.0187013
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[125]	valid_0's binary_logloss: 0.0187237
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[126]	valid_0's binary_logloss: 0.0188203
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[127]	valid_0's binary_logloss: 0.01882
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[128]	valid_0's binary_logloss: 0.0188655
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[129]	valid_0's binary_logloss: 0.0189139
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[130]	valid_0's binary_logloss: 0.0189626
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[131]	valid_0's binary_logloss: 0.0190034
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[132]	valid_0's binary_logloss: 0.0190947
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[133]	valid_0's binary_logloss: 0.0191645
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[134]	valid_0's binary_logloss: 0.0192788
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[135]	valid_0's binary_logloss: 0.0193771
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[136]	valid_0's binary_logloss: 0.0192783
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[137]	valid_0's binary_logloss: 0.019327
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[138]	valid_0's binary_logloss: 0.0192679
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[139]	valid_0's binary_logloss: 0.0193492
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[140]	valid_0's binary_logloss: 0.0193352
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[141]	valid_0's binary_logloss: 0.0193531
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[142]	valid_0's binary_logloss: 0.019392
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[143]	valid_0's binary_logloss: 0.0193824
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[144]	valid_0's binary_logloss: 0.0194129

Trening klas:  54%|█████▍    | 272/500 [32:34<26:12,  6.90s/klasa, klasa=class_272, F1_klasy=0.1250, F1_macro=0.7165, drzewa=114]




Trening klas:  55%|█████▍    | 273/500 [32:34<23:03,  6.10s/klasa, klasa=class_272, F1_klasy=0.1250, F1_macro=0.7165, drzewa=114]

[1]	valid_0's binary_logloss: 0.0670949
[2]	valid_0's binary_logloss: 0.0627134
[3]	valid_0's binary_logloss: 0.0593439
[4]	valid_0's binary_logloss: 0.0565189
[5]	valid_0's binary_logloss: 0.0541102
[6]	valid_0's binary_logloss: 0.0519582
[7]	valid_0's binary_logloss: 0.0499649
[8]	valid_0's binary_logloss: 0.047997
[9]	valid_0's binary_logloss: 0.0463445
[10]	valid_0's binary_logloss: 0.0448173
[11]	valid_0's binary_logloss: 0.0437367
[12]	valid_0's binary_logloss: 0.0428093
[13]	valid_0's binary_logloss: 0.0414453
[14]	valid_0's binary_logloss: 0.040204
[15]	valid_0's binary_logloss: 0.0390247
[16]	valid_0's binary_logloss: 0.0379011
[17]	valid_0's binary_logloss: 0.0369329
[18]	valid_0's binary_logloss: 0.0359661
[19]	valid_0's binary_logloss: 0.0351983
[20]	valid_0's binary_logloss: 0.0344885
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.033635
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0331055
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.0324108
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0315749
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.0308761
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.0303541
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.0299718
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.0294901
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.028978
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.0285801
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.0281348
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.0276469
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.0272848
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.026819
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.0264082
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.0261031
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.0256858
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.0254451
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.0251132
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.0249135
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.0245869
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.0243886
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.0240226
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.0238977
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.0236278
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.0234084
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.0232586
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.0231196
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.023
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.0228412
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.0226467
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.022588
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.0225196
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.0223646
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.0222167
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.0220997
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.0217799
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.021649
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.02151
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.0213668
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.0212842
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.021239
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.0211968
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.0210137
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.0209965
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.0208755
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.0206509
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.0206241
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.0204415
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.020385
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.0203629
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.0202469
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.0201175
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.0200471
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.0199844
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.0199777
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.0198844
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.0198335
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.0196701
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.0196285
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.0195767
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.0195184
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.0195362
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.0194876
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.0195128
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.0195034
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.0194767
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.0194846
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.0195396
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.0194864
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.0194777
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.0195522
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.0194915
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.0194748
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.019488
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.019395
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.0192861
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.0192405
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.019148
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.0191166
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.0191249
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.019111
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.0190218
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.0189052
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.0188377
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.0187803
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.0186858
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.0186216
[109]	valid_0's binary_logloss: 0.018566
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.0185724
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.0185651
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 0.0185918
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 0.0186555
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 0.0186741
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 0.0186585
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[116]	valid_0's binary_logloss: 0.0186141
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[117]	valid_0's binary_logloss: 0.0186163
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[118]	valid_0's binary_logloss: 0.0186225
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[119]	valid_0's binary_logloss: 0.0186302
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[120]	valid_0's binary_logloss: 0.0185562
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[121]	valid_0's binary_logloss: 0.0185659
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[122]	valid_0's binary_logloss: 0.0184965
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[123]	valid_0's binary_logloss: 0.0185181
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[124]	valid_0's binary_logloss: 0.0185499
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[125]	valid_0's binary_logloss: 0.0185482
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[126]	valid_0's binary_logloss: 0.0185513
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[127]	valid_0's binary_logloss: 0.0185119
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[128]	valid_0's binary_logloss: 0.0184754
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[129]	valid_0's binary_logloss: 0.0184243
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[130]	valid_0's binary_logloss: 0.0184018
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[131]	valid_0's binary_logloss: 0.0183799
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[132]	valid_0's binary_logloss: 0.0184146
[133]	valid_0's binary_logloss: 0.0184124
[134]	valid_0's binary_logloss: 0.018505
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[135]	valid_0's binary_logloss: 0.018516
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[136]	valid_0's binary_logloss: 0.0185179
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[137]	valid_0's binary_logloss: 0.0184841
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[138]	valid_0's binary_logloss: 0.018473
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[139]	valid_0's binary_logloss: 0.0184665
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[140]	valid_0's binary_logloss: 0.018471
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[141]	valid_0's binary_logloss: 0.0184753
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[142]	valid_0's binary_logloss: 0.0184577
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[143]	valid_0's binary_logloss: 0.0184532
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[144]	valid_0's binary_logloss: 0.0184401
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[145]	valid_0's binary_logloss: 0.0184595
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[146]	valid_0's binary_logloss: 0.0184317
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[147]	valid_0's binary_logloss: 0.0184055
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[148]	valid_0's binary_logloss: 0.0184141
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[149]	valid_0's binary_logloss: 0.0184657
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[150]	valid_0's binary_logloss: 0.0184817
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[151]	valid_0's binary_logloss: 0.0184621
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[152]	valid_0's binary_logloss: 0.0184774
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[153]	valid_0's binary_logloss: 0.018475
[154]	valid_0's binary_logloss: 0.0185212
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[155]	valid_0's binary_logloss: 0.0185771
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[156]	valid_0's binary_logloss: 0.0185441
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[157]	valid_0's binary_logloss: 0.0185079
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[158]	valid_0's binary_logloss: 0.0184279
[159]	valid_0's binary_logloss: 0.0184566
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[160]	valid_0's binary_logloss: 0.0184361

Trening klas:  55%|█████▍    | 273/500 [32:42<23:03,  6.10s/klasa, klasa=class_273, F1_klasy=0.7226, F1_macro=0.7165, drzewa=131]




Trening klas:  55%|█████▍    | 274/500 [32:42<25:15,  6.71s/klasa, klasa=class_273, F1_klasy=0.7226, F1_macro=0.7165, drzewa=131]

[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[161]	valid_0's binary_logloss: 0.0184375
[1]	valid_0's binary_logloss: 0.0269236
[2]	valid_0's binary_logloss: 0.0266834
[3]	valid_0's binary_logloss: 0.026564
[4]	valid_0's binary_logloss: 0.0263984
[5]	valid_0's binary_logloss: 0.0261578
[6]	valid_0's binary_logloss: 0.0284736
[7]	valid_0's binary_logloss: 0.0284647
[8]	valid_0's binary_logloss: 0.0281947
[9]	valid_0's binary_logloss: 0.0279224
[10]	valid_0's binary_logloss: 0.0276369
[11]	valid_0's binary_logloss: 0.0315874
[12]	valid_0's binary_logloss: 0.0314886
[13]	valid_0's binary_logloss: 0.0311709
[14]	valid_0's binary_logloss: 0.030829
[15]	valid_0's binary_logloss: 0.0304564
[16]	valid_0's binary_logloss: 0.030139
[17]	valid_0's binary_logloss: 0.0298073
[18]	valid_0's binary_logloss: 0.0294475
[19]	valid_0's binary_logloss: 0.0291703
[20]	valid_0's binary_logloss: 0.0288299
[21]	valid_0's binary_logloss: 0.0283751
[22]	valid_0's binary_logloss: 0.0278779
[23]	valid_0's binary_logloss: 0.027558
[24]	valid_0's binary_logloss: 0.0272484
[25]	valid_0's binary_logloss: 0.0268965
[26]	valid_0's binary_logloss: 0.0266605
[27]	valid_0's binary_logloss: 0.0264804
[28]	valid_0's binary_logloss: 0.0261456
[29]	valid_0's binary_logloss: 0.0260031
[30]	valid_0's binary_logloss: 0.0257404
[31]	valid_0's binary_logloss: 0.0254555
[32]	valid_0's binary_logloss: 0.0252361
[33]	valid_0's binary_logloss: 0.0249681
[34]	valid_0's binary_logloss: 0.0247946
[35]	valid_0's binary_logloss: 0.0246843
[36]	valid_0's binary_logloss: 0.0246277
[37]	valid_0's binary_logloss: 0.0244413
[38]	valid_0's binary_logloss: 0.0240929
[39]	valid_0's binary_logloss: 0.0238268
[40]	valid_0's binary_logloss: 0.0234735
[41]	valid_0's binary_logloss: 0.0233745
[42]	valid_0's binary_logloss: 0.0230925
[43]	valid_0's binary_logloss: 0.0229794
[44]	valid_0's binary_logloss: 0.0229377
[45]	valid_0's binary_logloss: 0.022801
[46]	valid_0's binary_logloss: 0.0225784
[47]	valid_0's binary_logloss: 0.0224545
[48]	valid_0's binary_logloss: 0.0224062
[49]	valid_0's binary_logloss: 0.0222217
[50]	valid_0's binary_logloss: 0.0221271
[51]	valid_0's binary_logloss: 0.0218999
[52]	valid_0's binary_logloss: 0.0216942
[53]	valid_0's binary_logloss: 0.0216023
[54]	valid_0's binary_logloss: 0.0214643
[55]	valid_0's binary_logloss: 0.021277
[56]	valid_0's binary_logloss: 0.0211364
[57]	valid_0's binary_logloss: 0.0209434
[58]	valid_0's binary_logloss: 0.0208461
[59]	valid_0's binary_logloss: 0.0206595
[60]	valid_0's binary_logloss: 0.0205757
[61]	valid_0's binary_logloss: 0.0206051
[62]	valid_0's binary_logloss: 0.0206476
[63]	valid_0's binary_logloss: 0.0205859
[64]	valid_0's binary_logloss: 0.0205823
[65]	valid_0's binary_logloss: 0.0205061
[66]	valid_0's binary_logloss: 0.0204279
[67]	valid_0's binary_logloss: 0.0203289
[68]	valid_0's binary_logloss: 0.0201538
[69]	valid_0's binary_logloss: 0.0200777
[70]	valid_0's binary_logloss: 0.0200125
[71]	valid_0's binary_logloss: 0.0197101
[72]	valid_0's binary_logloss: 0.0196469
[73]	valid_0's binary_logloss: 0.0196923
[74]	valid_0's binary_logloss: 0.0196784
[75]	valid_0's binary_logloss: 0.019589
[76]	valid_0's binary_logloss: 0.0195316
[77]	valid_0's binary_logloss: 0.0193384
[78]	valid_0's binary_logloss: 0.0193477
[79]	valid_0's binary_logloss: 0.0191901
[80]	valid_0's binary_logloss: 0.0191125
[81]	valid_0's binary_logloss: 0.0190301
[82]	valid_0's binary_logloss: 0.0188428
[83]	valid_0's binary_logloss: 0.018801
[84]	valid_0's binary_logloss: 0.0187061
[85]	valid_0's binary_logloss: 0.0186514
[86]	valid_0's binary_logloss: 0.0185415
[87]	valid_0's binary_logloss: 0.018472
[88]	valid_0's binary_logloss: 0.0184983
[89]	valid_0's binary_logloss: 0.0184099
[90]	valid_0's binary_logloss: 0.0183471
[91]	valid_0's binary_logloss: 0.0182218
[92]	valid_0's binary_logloss: 0.018325
[93]	valid_0's binary_logloss: 0.0182535
[94]	valid_0's binary_logloss: 0.0182132
[95]	valid_0's binary_logloss: 0.0182533
[96]	valid_0's binary_logloss: 0.0182277
[97]	valid_0's binary_logloss: 0.0182407
[98]	valid_0's binary_logloss: 0.0182421
[99]	valid_0's binary_logloss: 0.0181079
[100]	valid_0's binary_logloss: 0.018085
[101]	valid_0's binary_logloss: 0.0181122
[102]	valid_0's binary_logloss: 0.0181337
[103]	valid_0's binary_logloss: 0.0180767
[104]	valid_0's binary_logloss: 0.0180496
[105]	valid_0's binary_logloss: 0.0180459
[106]	valid_0's binary_logloss: 0.0180735
[107]	valid_0's binary_logloss: 0.018053
[108]	valid_0's binary_logloss: 0.0179811
[109]	valid_0's binary_logloss: 0.0179005
[110]	valid_0's binary_logloss: 0.0179102
[111]	valid_0's binary_logloss: 0.0178806
[112]	valid_0's binary_logloss: 0.0176268
[113]	valid_0's binary_logloss: 0.0175182
[114]	valid_0's binary_logloss: 0.017509
[115]	valid_0's binary_logloss: 0.0175866
[116]	valid_0's binary_logloss: 0.0176011
[117]	valid_0's binary_logloss: 0.0176903
[118]	valid_0's binary_logloss: 0.0177304
[119]	valid_0's binary_logloss: 0.0177296
[120]	valid_0's binary_logloss: 0.0177747
[121]	valid_0's binary_logloss: 0.0176812
[122]	valid_0's binary_logloss: 0.0176457
[123]	valid_0's binary_logloss: 0.0175963
[124]	valid_0's binary_logloss: 0.0175093
[125]	valid_0's binary_logloss: 0.0175199
[126]	valid_0's binary_logloss: 0.0174669
[127]	valid_0's binary_logloss: 0.0175059
[128]	valid_0's binary_logloss: 0.0176055
[129]	valid_0's binary_logloss: 0.0176942
[130]	valid_0's binary_logloss: 0.0176883
[131]	valid_0's binary_logloss: 0.0176121
[132]	valid_0's binary_logloss: 0.0176128
[133]	valid_0's binary_logloss: 0.0175789
[134]	valid_0's binary_logloss: 0.0175149
[135]	valid_0's binary_logloss: 0.0173862
[136]	valid_0's binary_logloss: 0.0174366
[137]	valid_0's binary_logloss: 0.0174233
[138]	valid_0's binary_logloss: 0.0174583
[139]	valid_0's binary_logloss: 0.0174585
[140]	valid_0's binary_logloss: 0.0174992
[141]	valid_0's binary_logloss: 0.0175146
[142]	valid_0's binary_logloss: 0.0174956
[143]	valid_0's binary_logloss: 0.0173865
[144]	valid_0's binary_logloss: 0.0172961
[145]	valid_0's binary_logloss: 0.0171282
[146]	valid_0's binary_logloss: 0.0171977
[147]	valid_0's binary_logloss: 0.0172748
[148]	valid_0's binary_logloss: 0.0173956
[149]	valid_0's binary_logloss: 0.0173554
[150]	valid_0's binary_logloss: 0.0174238
[151]	valid_0's binary_logloss: 0.0174423
[152]	valid_0's binary_logloss: 0.0173527
[153]	valid_0's binary_logloss: 0.0174081
[154]	valid_0's binary_logloss: 0.0174386
[155]	valid_0's binary_logloss: 0.017438
[156]	valid_0's binary_logloss: 0.0173685
[157]	valid_0's binary_logloss: 0.0172479
[158]	valid_0's binary_logloss: 0.0171123
[159]	valid_0's binary_logloss: 0.0169955
[160]	valid_0's binary_logloss: 0.0169609
[161]	valid_0's binary_logloss: 0.016929
[162]	valid_0's binary_logloss: 0.0169854
[163]	valid_0's binary_logloss: 0.0169631
[164]	valid_0's binary_logloss: 0.0170373
[165]	valid_0's binary_logloss: 0.0171131
[166]	valid_0's binary_logloss: 0.017146
[167]	valid_0's binary_logloss: 0.0172013
[168]	valid_0's binary_logloss: 0.0172994
[169]	valid_0's binary_logloss: 0.0172554
[170]	valid_0's binary_logloss: 0.0172089
[171]	valid_0's binary_logloss: 0.0172489
[172]	valid_0's binary_logloss: 0.0173284
[173]	valid_0's binary_logloss: 0.0174281
[174]	valid_0's binary_logloss: 0.0174654
[175]	valid_0's binary_logloss: 0.0176316
[176]	valid_0's binary_logloss: 0.0177637
[177]	valid_0's binary_logloss: 0.0178248
[178]	valid_0's binary_logloss: 0.017824
[179]	valid_0's binary_logloss: 0.0178832
[180]	valid_0's binary_logloss: 0.0178334
[181]	valid_0's binary_logloss: 0.0179574
[182]	valid_0's binary_logloss: 0.0180041
[183]	valid_0's binary_logloss: 0.0179981
[184]	valid_0's binary_logloss: 0.0180452
[185]	valid_0's binary_logloss: 0.0181831
[186]	valid_0's binary_logloss: 0.0181934
[187]	valid_0's binary_logloss: 0.018237
[188]	valid_0's binary_logloss: 0.0182355
[189]	valid_0's binary_logloss: 0.0184138
[190]	valid_0's binary_logloss: 0.0184064

Trening klas:  55%|█████▍    | 274/500 [32:57<25:15,  6.71s/klasa, klasa=class_274, F1_klasy=0.4941, F1_macro=0.7157, drzewa=161]




Trening klas:  55%|█████▌    | 275/500 [32:57<33:54,  9.04s/klasa, klasa=class_274, F1_klasy=0.4941, F1_macro=0.7157, drzewa=161]

[191]	valid_0's binary_logloss: 0.0182098
[1]	valid_0's binary_logloss: 0.0181705
[2]	valid_0's binary_logloss: 0.0175132
[3]	valid_0's binary_logloss: 0.0169123
[4]	valid_0's binary_logloss: 0.0163678
[5]	valid_0's binary_logloss: 0.0158027
[6]	valid_0's binary_logloss: 0.0160857
[7]	valid_0's binary_logloss: 0.0155628
[8]	valid_0's binary_logloss: 0.0150706
[9]	valid_0's binary_logloss: 0.014499
[10]	valid_0's binary_logloss: 0.0139759
[11]	valid_0's binary_logloss: 0.013563
[12]	valid_0's binary_logloss: 0.0131758
[13]	valid_0's binary_logloss: 0.0127879
[14]	valid_0's binary_logloss: 0.0123877
[15]	valid_0's binary_logloss: 0.012008
[16]	valid_0's binary_logloss: 0.0116621
[17]	valid_0's binary_logloss: 0.0113589
[18]	valid_0's binary_logloss: 0.0111102
[19]	valid_0's binary_logloss: 0.0108304
[20]	valid_0's binary_logloss: 0.010576
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0102626
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.00997245
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.00969217
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.00946909
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.00923435
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.00899867
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.00874224
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.00854562
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.00833166
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.00816543
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.00799016
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.00781364
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.00764212
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.00744842
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.00729732
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.00712643
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.0070246
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.00691442
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.00680094
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.00667829
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.00654266
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.00643574
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.00629632
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.00620395
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.00608683
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.00595699
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.0058351
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.00571775
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.0056138
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.0055522
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.00551236
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.00541931
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.00539844
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.00537253
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.00534774
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.00528978
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.00521905
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.00515004
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.00506894
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.00501972
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.00497556
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.00495294
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.00494435
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.00494081
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.00490991
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.00488485
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.00486336
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.0048362
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.00479862
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.0048148
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.0047819
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.00476997
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.00475093
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.00473951
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.00471218
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.00468576
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.00466123
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.00465209
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.0046506
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.00463353
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.00462535
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.00461272
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.00457325
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.00458223
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.00456428
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.00457011
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.00458626
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.00458584
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.00458546
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.00458149
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.00455702
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.0045374
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.00453807
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.00452174
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.00451129
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.00452906
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.00453237
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.00453498
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.00453956
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.00453976
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.00455265
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.00457703
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.00457976
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.00459575
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.00460312
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.00458065
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.00456777
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.00460276
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.00461166
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.00461468
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.00460687
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 0.00460132
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 0.00459748
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 0.00458512
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 0.00459055
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[116]	valid_0's binary_logloss: 0.00455293
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[117]	valid_0's binary_logloss: 0.00452631
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[118]	valid_0's binary_logloss: 0.00448998
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[119]	valid_0's binary_logloss: 0.0044506
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[120]	valid_0's binary_logloss: 0.00445968
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[121]	valid_0's binary_logloss: 0.00449517
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[122]	valid_0's binary_logloss: 0.00451985
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[123]	valid_0's binary_logloss: 0.00454948
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[124]	valid_0's binary_logloss: 0.00457096
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[125]	valid_0's binary_logloss: 0.00458371
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[126]	valid_0's binary_logloss: 0.00458419
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[127]	valid_0's binary_logloss: 0.00458572
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[128]	valid_0's binary_logloss: 0.00458141
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[129]	valid_0's binary_logloss: 0.00458073
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[130]	valid_0's binary_logloss: 0.00457815
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[131]	valid_0's binary_logloss: 0.00455484
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[132]	valid_0's binary_logloss: 0.00454955
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[133]	valid_0's binary_logloss: 0.00455746
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[134]	valid_0's binary_logloss: 0.00454836
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[135]	valid_0's binary_logloss: 0.00453831
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[136]	valid_0's binary_logloss: 0.0045324
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[137]	valid_0's binary_logloss: 0.00452779
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[138]	valid_0's binary_logloss: 0.0045606
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[139]	valid_0's binary_logloss: 0.00457411
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[140]	valid_0's binary_logloss: 0.00458639
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[141]	valid_0's binary_logloss: 0.0046109
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[142]	valid_0's binary_logloss: 0.00463304
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[143]	valid_0's binary_logloss: 0.00464049
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[144]	valid_0's binary_logloss: 0.0046377
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[145]	valid_0's binary_logloss: 0.00463314
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[146]	valid_0's binary_logloss: 0.0046508
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[147]	valid_0's binary_logloss: 0.00462051
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

Trening klas:  55%|█████▌    | 275/500 [33:03<33:54,  9.04s/klasa, klasa=class_275, F1_klasy=0.5000, F1_macro=0.7149, drzewa=119]




Trening klas:  55%|█████▌    | 276/500 [33:03<30:43,  8.23s/klasa, klasa=class_275, F1_klasy=0.5000, F1_macro=0.7149, drzewa=119]

[148]	valid_0's binary_logloss: 0.00461862
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[149]	valid_0's binary_logloss: 0.00461666
[1]	valid_0's binary_logloss: 0.0889292
[2]	valid_0's binary_logloss: 0.0873776
[3]	valid_0's binary_logloss: 0.0865778
[4]	valid_0's binary_logloss: 0.0856708
[5]	valid_0's binary_logloss: 0.084694
[6]	valid_0's binary_logloss: 0.0822594
[7]	valid_0's binary_logloss: 0.079997
[8]	valid_0's binary_logloss: 0.078472
[9]	valid_0's binary_logloss: 0.0768362
[10]	valid_0's binary_logloss: 0.076033
[11]	valid_0's binary_logloss: 0.0748579
[12]	valid_0's binary_logloss: 0.0747476
[13]	valid_0's binary_logloss: 0.07394
[14]	valid_0's binary_logloss: 0.0736998
[15]	valid_0's binary_logloss: 0.0728637
[16]	valid_0's binary_logloss: 0.0717832
[17]	valid_0's binary_logloss: 0.0709311
[18]	valid_0's binary_logloss: 0.0702316
[19]	valid_0's binary_logloss: 0.0695659
[20]	valid_0's binary_logloss: 0.0696573
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0698454
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0698095
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.0688977
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0685109
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.0678342
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.0673871
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.0664163
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.0659235
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.0655129
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.064413
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.0638475
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.0634287
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.0630616
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.0623832
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.062178
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.061762
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.0615296
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.0608912
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.060959
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.0599106
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.0599034
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.0589522
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.0590306
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.059118
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.0585199
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.0578445
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.0571139
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.0566328
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.0561813
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.0558044
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.0556207
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.0551986
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.0550208
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.0547978
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.0547234
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.054354
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.053796
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.0532966
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.052843
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.052508
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.0521665
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.0522688
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.0518976
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.0520508
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.051968
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.051655
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.0512128
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.0511722
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.0507061
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.0505664
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.050578
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.0505799
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.0505042
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.0506032
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.0506384
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.0504381
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.0503475
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.0500664
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.049995
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.0498401
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.0496762
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.0495888
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.0495637
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.0493081
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.0491598
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.0490629
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.049182
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.0493127
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.0495377
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.0497529
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.049803
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.0498
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.0498307
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.0499119
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.0499416
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.0499087
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.0498711
[98]	valid_0's binary_logloss: 0.0498947
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.0497968
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.049909
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.0500881
[102]	valid_0's binary_logloss: 0.0502789
[103]	valid_0's binary_logloss: 0.0504058
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.0505923
[105]	valid_0's binary_logloss: 0.0506694
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.0506744
[107]	valid_0's binary_logloss: 0.0507182
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.0507197
[109]	valid_0's binary_logloss: 0.050834
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.0509054
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.0505923
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 0.0505124
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 0.0506763
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

Trening klas:  55%|█████▌    | 276/500 [33:10<30:43,  8.23s/klasa, klasa=class_276, F1_klasy=0.4330, F1_macro=0.7139, drzewa=86]




Trening klas:  55%|█████▌    | 277/500 [33:10<28:57,  7.79s/klasa, klasa=class_276, F1_klasy=0.4330, F1_macro=0.7139, drzewa=86]

[114]	valid_0's binary_logloss: 0.0508037
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 0.0507939
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[116]	valid_0's binary_logloss: 0.0507861
[1]	valid_0's binary_logloss: 0.0177494
[2]	valid_0's binary_logloss: 0.017304
[3]	valid_0's binary_logloss: 0.0167943
[4]	valid_0's binary_logloss: 0.0163305
[5]	valid_0's binary_logloss: 0.0159029
[6]	valid_0's binary_logloss: 0.0155644
[7]	valid_0's binary_logloss: 0.0152424
[8]	valid_0's binary_logloss: 0.0149456
[9]	valid_0's binary_logloss: 0.0146776
[10]	valid_0's binary_logloss: 0.0144537
[11]	valid_0's binary_logloss: 0.0141405
[12]	valid_0's binary_logloss: 0.0135067
[13]	valid_0's binary_logloss: 0.0131626
[14]	valid_0's binary_logloss: 0.0126734
[15]	valid_0's binary_logloss: 0.0122117
[16]	valid_0's binary_logloss: 0.0117856
[17]	valid_0's binary_logloss: 0.0112954
[18]	valid_0's binary_logloss: 0.0110392
[19]	valid_0's binary_logloss: 0.0108296
[20]	valid_0's binary_logloss: 0.0103881
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0101823
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.00965407
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.00928035
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.00891479
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.00849145
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.00808928
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.00770271
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.00756762
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.00738906
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.00725352
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.00701383
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.00678753
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.00657649
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.00637491
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.00619289
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.00612464
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.00592885
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.00584014
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.00565951
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.00546775
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.00531043
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.00516556
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.00510994
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.00498001
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.00499519
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.00492727
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.00485935
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.00466351
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.00451393
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.00440418
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.0042294
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.00411855
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.00404362
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.00393078
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.0038038
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.00375615
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.00367164
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.0035369
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.00342977
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.0033115
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.00321177
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.00315288
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.00305304
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.00293539
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.00285931
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.00275525
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.00267138
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.00259013
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.0025547
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.00247867
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.00241995
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.00234546
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.00229335
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.00225056
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.00219956
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.00214401
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.00211539
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.00209254
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.00205645
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.00204856
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.0020233
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.00197406
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.00193876
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.00192276
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.0019104
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.00188579
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.00186215
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.00180628
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.0017987
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.00181082
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.00180855
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.00178537
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.00177271
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.00172205
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.00171472
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.00168998
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.00165618
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.00164565
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.00161314
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.00159442
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.00159985
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.00156669
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.00156401
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.00155526
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.00155852
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.00154259
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.00154712
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.00153021
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.00153143
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.00152662
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.001493
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 0.0014902
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 0.001507
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 0.00149809
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 0.00149294
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[116]	valid_0's binary_logloss: 0.00148318
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[117]	valid_0's binary_logloss: 0.00147928
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[118]	valid_0's binary_logloss: 0.00145002
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[119]	valid_0's binary_logloss: 0.00143807
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[120]	valid_0's binary_logloss: 0.00141319
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[121]	valid_0's binary_logloss: 0.00142254
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[122]	valid_0's binary_logloss: 0.00140908
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[123]	valid_0's binary_logloss: 0.00142697
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[124]	valid_0's binary_logloss: 0.00144436
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[125]	valid_0's binary_logloss: 0.00141994
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[126]	valid_0's binary_logloss: 0.00141877
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[127]	valid_0's binary_logloss: 0.00142754
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[128]	valid_0's binary_logloss: 0.00140436
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[129]	valid_0's binary_logloss: 0.00142193
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[130]	valid_0's binary_logloss: 0.00142318
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[131]	valid_0's binary_logloss: 0.001398
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[132]	valid_0's binary_logloss: 0.0013748
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[133]	valid_0's binary_logloss: 0.00136196
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[134]	valid_0's binary_logloss: 0.00135592
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[135]	valid_0's binary_logloss: 0.00134553
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[136]	valid_0's binary_logloss: 0.00135874
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[137]	valid_0's binary_logloss: 0.00137594
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[138]	valid_0's binary_logloss: 0.0013857
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[139]	valid_0's binary_logloss: 0.00139455
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[140]	valid_0's binary_logloss: 0.00137492
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[141]	valid_0's binary_logloss: 0.00137334
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[142]	valid_0's binary_logloss: 0.0013708
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[143]	valid_0's binary_logloss: 0.00137047
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[144]	valid_0's binary_logloss: 0.00138157
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[145]	valid_0's binary_logloss: 0.00137368
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[146]	valid_0's binary_logloss: 0.00135382
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[147]	valid_0's binary_logloss: 0.00134442
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[148]	valid_0's binary_logloss: 0.00133573
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[149]	valid_0's binary_logloss: 0.00131592
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[150]	valid_0's binary_logloss: 0.00129281
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[151]	valid_0's binary_logloss: 0.00128965
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[152]	valid_0's binary_logloss: 0.00126524
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[153]	valid_0's binary_logloss: 0.00125938
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[154]	valid_0's binary_logloss: 0.00124932
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[155]	valid_0's binary_logloss: 0.00124489
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[156]	valid_0's binary_logloss: 0.00123824
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[157]	valid_0's binary_logloss: 0.00123696
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[158]	valid_0's binary_logloss: 0.00124889
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[159]	valid_0's binary_logloss: 0.00125664
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[160]	valid_0's binary_logloss: 0.00125967
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[161]	valid_0's binary_logloss: 0.00125024
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[162]	valid_0's binary_logloss: 0.00126085
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[163]	valid_0's binary_logloss: 0.00127278
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[164]	valid_0's binary_logloss: 0.0012724
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[165]	valid_0's binary_logloss: 0.00125608
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[166]	valid_0's binary_logloss: 0.00124637
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[167]	valid_0's binary_logloss: 0.00123747
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[168]	valid_0's binary_logloss: 0.00122759
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[169]	valid_0's binary_logloss: 0.00120647
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[170]	valid_0's binary_logloss: 0.00119525
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[171]	valid_0's binary_logloss: 0.0012109
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[172]	valid_0's binary_logloss: 0.00120981
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[173]	valid_0's binary_logloss: 0.00121046
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[174]	valid_0's binary_logloss: 0.00121304
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[175]	valid_0's binary_logloss: 0.0012262
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[176]	valid_0's binary_logloss: 0.00121708
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[177]	valid_0's binary_logloss: 0.00121519
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[178]	valid_0's binary_logloss: 0.00121506
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[179]	valid_0's binary_logloss: 0.00120869
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[180]	valid_0's binary_logloss: 0.00120471
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[181]	valid_0's binary_logloss: 0.00120728

Trening klas:  55%|█████▌    | 277/500 [33:17<28:57,  7.79s/klasa, klasa=class_277, F1_klasy=0.8571, F1_macro=0.7144, drzewa=241]




Trening klas:  56%|█████▌    | 278/500 [33:17<28:39,  7.75s/klasa, klasa=class_277, F1_klasy=0.8571, F1_macro=0.7144, drzewa=241]

[1]	valid_0's binary_logloss: 0.278288
[2]	valid_0's binary_logloss: 0.265691
[3]	valid_0's binary_logloss: 0.255695
[4]	valid_0's binary_logloss: 0.246265
[5]	valid_0's binary_logloss: 0.237992
[6]	valid_0's binary_logloss: 0.241009
[7]	valid_0's binary_logloss: 0.232447
[8]	valid_0's binary_logloss: 0.227019
[9]	valid_0's binary_logloss: 0.220595
[10]	valid_0's binary_logloss: 0.21576
[11]	valid_0's binary_logloss: 0.209754
[12]	valid_0's binary_logloss: 0.204038
[13]	valid_0's binary_logloss: 0.199049
[14]	valid_0's binary_logloss: 0.193957
[15]	valid_0's binary_logloss: 0.189516
[16]	valid_0's binary_logloss: 0.184904
[17]	valid_0's binary_logloss: 0.18051
[18]	valid_0's binary_logloss: 0.175517
[19]	valid_0's binary_logloss: 0.171574
[20]	valid_0's binary_logloss: 0.167132
[21]	valid_0's binary_logloss: 0.162995
[22]	valid_0's binary_logloss: 0.159741
[23]	valid_0's binary_logloss: 0.15619
[24]	valid_0's binary_logloss: 0.15341
[25]	valid_0's binary_logloss: 0.150423
[26]	valid_0's binary_logloss: 0.147681
[27]	valid_0's binary_logloss: 0.145481
[28]	valid_0's binary_logloss: 0.143172
[29]	valid_0's binary_logloss: 0.141449
[30]	valid_0's binary_logloss: 0.139209
[31]	valid_0's binary_logloss: 0.137393
[32]	valid_0's binary_logloss: 0.135788
[33]	valid_0's binary_logloss: 0.133691
[34]	valid_0's binary_logloss: 0.132091
[35]	valid_0's binary_logloss: 0.130323
[36]	valid_0's binary_logloss: 0.128485
[37]	valid_0's binary_logloss: 0.127001
[38]	valid_0's binary_logloss: 0.126115
[39]	valid_0's binary_logloss: 0.124868
[40]	valid_0's binary_logloss: 0.123128
[41]	valid_0's binary_logloss: 0.122022
[42]	valid_0's binary_logloss: 0.120531
[43]	valid_0's binary_logloss: 0.119093
[44]	valid_0's binary_logloss: 0.117727
[45]	valid_0's binary_logloss: 0.116342
[46]	valid_0's binary_logloss: 0.114425
[47]	valid_0's binary_logloss: 0.112949
[48]	valid_0's binary_logloss: 0.111823
[49]	valid_0's binary_logloss: 0.110818
[50]	valid_0's binary_logloss: 0.109989
[51]	valid_0's binary_logloss: 0.109373
[52]	valid_0's binary_logloss: 0.108487
[53]	valid_0's binary_logloss: 0.107781
[54]	valid_0's binary_logloss: 0.106788
[55]	valid_0's binary_logloss: 0.106006
[56]	valid_0's binary_logloss: 0.104885
[57]	valid_0's binary_logloss: 0.103995
[58]	valid_0's binary_logloss: 0.102816
[59]	valid_0's binary_logloss: 0.102011
[60]	valid_0's binary_logloss: 0.101156
[61]	valid_0's binary_logloss: 0.100472
[62]	valid_0's binary_logloss: 0.0998259
[63]	valid_0's binary_logloss: 0.0991306
[64]	valid_0's binary_logloss: 0.0987772
[65]	valid_0's binary_logloss: 0.0979931
[66]	valid_0's binary_logloss: 0.0971205
[67]	valid_0's binary_logloss: 0.0965609
[68]	valid_0's binary_logloss: 0.0964348
[69]	valid_0's binary_logloss: 0.0960669
[70]	valid_0's binary_logloss: 0.0957901
[71]	valid_0's binary_logloss: 0.0953346
[72]	valid_0's binary_logloss: 0.0948834
[73]	valid_0's binary_logloss: 0.0943667
[74]	valid_0's binary_logloss: 0.0937473
[75]	valid_0's binary_logloss: 0.0929883
[76]	valid_0's binary_logloss: 0.0925201
[77]	valid_0's binary_logloss: 0.0917026
[78]	valid_0's binary_logloss: 0.0913277
[79]	valid_0's binary_logloss: 0.0907937
[80]	valid_0's binary_logloss: 0.0903846
[81]	valid_0's binary_logloss: 0.0902261
[82]	valid_0's binary_logloss: 0.0898133
[83]	valid_0's binary_logloss: 0.0896685
[84]	valid_0's binary_logloss: 0.0894906
[85]	valid_0's binary_logloss: 0.0890236
[86]	valid_0's binary_logloss: 0.0883042
[87]	valid_0's binary_logloss: 0.0879796
[88]	valid_0's binary_logloss: 0.0873737
[89]	valid_0's binary_logloss: 0.0868014
[90]	valid_0's binary_logloss: 0.0862068
[91]	valid_0's binary_logloss: 0.0857422
[92]	valid_0's binary_logloss: 0.0850024
[93]	valid_0's binary_logloss: 0.0847252
[94]	valid_0's binary_logloss: 0.0843691
[95]	valid_0's binary_logloss: 0.0840543
[96]	valid_0's binary_logloss: 0.0837772
[97]	valid_0's binary_logloss: 0.0835866
[98]	valid_0's binary_logloss: 0.0831946
[99]	valid_0's binary_logloss: 0.0833723
[100]	valid_0's binary_logloss: 0.0834511
[101]	valid_0's binary_logloss: 0.0832252
[102]	valid_0's binary_logloss: 0.0831124
[103]	valid_0's binary_logloss: 0.0829452
[104]	valid_0's binary_logloss: 0.0827672
[105]	valid_0's binary_logloss: 0.0827462
[106]	valid_0's binary_logloss: 0.0827081
[107]	valid_0's binary_logloss: 0.0826911
[108]	valid_0's binary_logloss: 0.0827595
[109]	valid_0's binary_logloss: 0.0828644
[110]	valid_0's binary_logloss: 0.082852
[111]	valid_0's binary_logloss: 0.0826397
[112]	valid_0's binary_logloss: 0.0825406
[113]	valid_0's binary_logloss: 0.0825554
[114]	valid_0's binary_logloss: 0.0822397
[115]	valid_0's binary_logloss: 0.082084
[116]	valid_0's binary_logloss: 0.0820497
[117]	valid_0's binary_logloss: 0.0818253
[118]	valid_0's binary_logloss: 0.0818218
[119]	valid_0's binary_logloss: 0.0817776
[120]	valid_0's binary_logloss: 0.0818613
[121]	valid_0's binary_logloss: 0.0815727
[122]	valid_0's binary_logloss: 0.081893
[123]	valid_0's binary_logloss: 0.0816273
[124]	valid_0's binary_logloss: 0.0814558
[125]	valid_0's binary_logloss: 0.08094
[126]	valid_0's binary_logloss: 0.0810588
[127]	valid_0's binary_logloss: 0.0812588
[128]	valid_0's binary_logloss: 0.0812008
[129]	valid_0's binary_logloss: 0.0814123
[130]	valid_0's binary_logloss: 0.0814977
[131]	valid_0's binary_logloss: 0.0816619
[132]	valid_0's binary_logloss: 0.0816229
[133]	valid_0's binary_logloss: 0.0815517
[134]	valid_0's binary_logloss: 0.0815803
[135]	valid_0's binary_logloss: 0.0814631
[136]	valid_0's binary_logloss: 0.0817863
[137]	valid_0's binary_logloss: 0.0819911
[138]	valid_0's binary_logloss: 0.0824598
[139]	valid_0's binary_logloss: 0.0826776
[140]	valid_0's binary_logloss: 0.0827433
[141]	valid_0's binary_logloss: 0.0826317
[142]	valid_0's binary_logloss: 0.0827586
[143]	valid_0's binary_logloss: 0.082858
[144]	valid_0's binary_logloss: 0.0829721
[145]	valid_0's binary_logloss: 0.0832337
[146]	valid_0's binary_logloss: 0.0832246
[147]	valid_0's binary_logloss: 0.0831737
[148]	valid_0's binary_logloss: 0.0829291
[149]	valid_0's binary_logloss: 0.0830749
[150]	valid_0's binary_logloss: 0.0832752
[151]	valid_0's binary_logloss: 0.0836321
[152]	valid_0's binary_logloss: 0.0837667
[153]	valid_0's binary_logloss: 0.0839701
[154]	valid_0's binary_logloss: 0.0840795
[155]	valid_0's binary_logloss: 0.0841549

Trening klas:  56%|█████▌    | 278/500 [33:29<28:39,  7.75s/klasa, klasa=class_278, F1_klasy=0.1128, F1_macro=0.7123, drzewa=125]




Trening klas:  56%|█████▌    | 279/500 [33:29<33:08,  9.00s/klasa, klasa=class_278, F1_klasy=0.1128, F1_macro=0.7123, drzewa=125]

[1]	valid_0's binary_logloss: 0.111844
[2]	valid_0's binary_logloss: 0.107081
[3]	valid_0's binary_logloss: 0.102337
[4]	valid_0's binary_logloss: 0.0989774
[5]	valid_0's binary_logloss: 0.0968873
[6]	valid_0's binary_logloss: 0.0938198
[7]	valid_0's binary_logloss: 0.0908725
[8]	valid_0's binary_logloss: 0.0886263
[9]	valid_0's binary_logloss: 0.0865328
[10]	valid_0's binary_logloss: 0.0840129
[11]	valid_0's binary_logloss: 0.0815882
[12]	valid_0's binary_logloss: 0.0795896
[13]	valid_0's binary_logloss: 0.0774076
[14]	valid_0's binary_logloss: 0.0754284
[15]	valid_0's binary_logloss: 0.073816
[16]	valid_0's binary_logloss: 0.0723018
[17]	valid_0's binary_logloss: 0.0710136
[18]	valid_0's binary_logloss: 0.0697024
[19]	valid_0's binary_logloss: 0.0684679
[20]	valid_0's binary_logloss: 0.0673757
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0659503
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0646162
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.0637016
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0627144
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.0615755
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.0611018
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.0603389
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.0594001
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.0586912
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.0578824
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.0573768
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.0565621
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.055751
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.055279
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.054623
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.0541173
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.0535718
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.0531012
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.0526271
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.0521659
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.0519793
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.0515819
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.0511829
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.050784
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.0504416
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.0501259
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.0497461
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.0494406
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.049096
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.0487663
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.0483914
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.0480077
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.0476527
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.0473579
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.0471103
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.0469378
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.0466966
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.0465653
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.0465132
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.0464114
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.0460804
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.0459608
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.04582
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.045735
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.045619
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.0453385
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.0452139
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.0450794
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.0449825
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.0448472
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.0449131
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.0449113
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.0449139
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.0448468
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.0449036
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.0449357
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.0447937
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.0448712
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.0448526
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.0446676
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.044508
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.0444606
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.044507
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.044522
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.0444266
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.0443247
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.0442388
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.044374
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.0444924
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.0443989
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.0444099
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.0444605
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.044393
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.0443386
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.0443545
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.0443058
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.0442767
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.0443032
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.0443623
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.0445157
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.0446461
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.044769
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.0448564
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.0449492
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.0449209
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.0448836
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.0449473
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.0451295
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.045163
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.0452456
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.0453171
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 0.0453741
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

Trening klas:  56%|█████▌    | 279/500 [33:35<33:08,  9.00s/klasa, klasa=class_279, F1_klasy=0.5333, F1_macro=0.7117, drzewa=87]




Trening klas:  56%|█████▌    | 280/500 [33:35<29:27,  8.03s/klasa, klasa=class_279, F1_klasy=0.5333, F1_macro=0.7117, drzewa=87]

[113]	valid_0's binary_logloss: 0.0453877
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 0.0454831
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 0.0455853
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[116]	valid_0's binary_logloss: 0.0456135
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[117]	valid_0's binary_logloss: 0.0456882
[1]	valid_0's binary_logloss: 0.757602
[2]	valid_0's binary_logloss: 0.543735
[3]	valid_0's binary_logloss: 0.513984
[4]	valid_0's binary_logloss: 0.488292
[5]	valid_0's binary_logloss: 0.474114
[6]	valid_0's binary_logloss: 0.460037
[7]	valid_0's binary_logloss: 0.445564
[8]	valid_0's binary_logloss: 0.432437
[9]	valid_0's binary_logloss: 0.42159
[10]	valid_0's binary_logloss: 0.412662
[11]	valid_0's binary_logloss: 0.403811
[12]	valid_0's binary_logloss: 0.395691
[13]	valid_0's binary_logloss: 0.388381
[14]	valid_0's binary_logloss: 0.380368
[15]	valid_0's binary_logloss: 0.373706
[16]	valid_0's binary_logloss: 0.36736
[17]	valid_0's binary_logloss: 0.36059
[18]	valid_0's binary_logloss: 0.354717
[19]	valid_0's binary_logloss: 0.34914
[20]	valid_0's binary_logloss: 0.343579
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.338336
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.333108
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.32808
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.323396
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.318769
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.314584
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.310807
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.306915
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.303129
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.299552
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.296042
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.292781
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.289504
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.286547
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.283417
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.280303
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.276941
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.273957
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.271257
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.268699
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.265843
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.263124
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.260616
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.257842
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.255414
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.252771
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.25051
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.247982
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.245445
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.243177
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.240937
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.238947
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.237098
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.235034
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.232927
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.230342
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.227783
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.225506
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.223052
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.221039
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.218882
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.216805
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.215055
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.213433
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.212016
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.210588
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.209069
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.20751
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.206114
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.20477
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.203801
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.202818
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.201565
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.20011
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.198952
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.197643
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.196325
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.195321
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.194061
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.193118
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.192266
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.191161
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.190101
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.18908
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.188181
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.187049
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.186492
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.185806
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.184854
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.183954
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.183357
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.182647
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.182081
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.181471
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.180757
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.18016
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.179243
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.178679
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.178029
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.177481
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.176913
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.1763
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.175807
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.175352
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.175075
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.1744
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.173934
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.173537
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.173065
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.172445
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.17203
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 0.171718
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 0.171456
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 0.171167
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 0.170785
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[116]	valid_0's binary_logloss: 0.170217
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[117]	valid_0's binary_logloss: 0.169608
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[118]	valid_0's binary_logloss: 0.169174
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[119]	valid_0's binary_logloss: 0.168713
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[120]	valid_0's binary_logloss: 0.168102
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[121]	valid_0's binary_logloss: 0.16772
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[122]	valid_0's binary_logloss: 0.167434
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[123]	valid_0's binary_logloss: 0.16717
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[124]	valid_0's binary_logloss: 0.166814
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[125]	valid_0's binary_logloss: 0.166336
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[126]	valid_0's binary_logloss: 0.166062
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[127]	valid_0's binary_logloss: 0.165409
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[128]	valid_0's binary_logloss: 0.164975
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[129]	valid_0's binary_logloss: 0.164386
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[130]	valid_0's binary_logloss: 0.163901
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[131]	valid_0's binary_logloss: 0.163447
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[132]	valid_0's binary_logloss: 0.163231
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[133]	valid_0's binary_logloss: 0.162768
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[134]	valid_0's binary_logloss: 0.162379
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[135]	valid_0's binary_logloss: 0.162088
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[136]	valid_0's binary_logloss: 0.16208
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[137]	valid_0's binary_logloss: 0.162198
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[138]	valid_0's binary_logloss: 0.162114
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[139]	valid_0's binary_logloss: 0.161991
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[140]	valid_0's binary_logloss: 0.161845
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[141]	valid_0's binary_logloss: 0.161934
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[142]	valid_0's binary_logloss: 0.16196
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[143]	valid_0's binary_logloss: 0.161866
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[144]	valid_0's binary_logloss: 0.161734
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[145]	valid_0's binary_logloss: 0.161605
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[146]	valid_0's binary_logloss: 0.161373
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[147]	valid_0's binary_logloss: 0.161218
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[148]	valid_0's binary_logloss: 0.161038
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[149]	valid_0's binary_logloss: 0.160967
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[150]	valid_0's binary_logloss: 0.160855
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[151]	valid_0's binary_logloss: 0.160901
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[152]	valid_0's binary_logloss: 0.160843
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[153]	valid_0's binary_logloss: 0.160707
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[154]	valid_0's binary_logloss: 0.160644
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[155]	valid_0's binary_logloss: 0.160555
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[156]	valid_0's binary_logloss: 0.160333
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[157]	valid_0's binary_logloss: 0.160087
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[158]	valid_0's binary_logloss: 0.159882
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[159]	valid_0's binary_logloss: 0.159619
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[160]	valid_0's binary_logloss: 0.159392
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[161]	valid_0's binary_logloss: 0.159375
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[162]	valid_0's binary_logloss: 0.159347
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[163]	valid_0's binary_logloss: 0.159254
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[164]	valid_0's binary_logloss: 0.159
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[165]	valid_0's binary_logloss: 0.158889
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[166]	valid_0's binary_logloss: 0.158752
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[167]	valid_0's binary_logloss: 0.158662
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[168]	valid_0's binary_logloss: 0.158514
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[169]	valid_0's binary_logloss: 0.158462
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[170]	valid_0's binary_logloss: 0.158315
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[171]	valid_0's binary_logloss: 0.158285
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[172]	valid_0's binary_logloss: 0.158321
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[173]	valid_0's binary_logloss: 0.158315
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[174]	valid_0's binary_logloss: 0.158178
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[175]	valid_0's binary_logloss: 0.157969
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[176]	valid_0's binary_logloss: 0.157821
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[177]	valid_0's binary_logloss: 0.157755
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[178]	valid_0's binary_logloss: 0.157621
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[179]	valid_0's binary_logloss: 0.157548
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[180]	valid_0's binary_logloss: 0.157598
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[181]	valid_0's binary_logloss: 0.15774
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[182]	valid_0's binary_logloss: 0.15778

Trening klas:  56%|█████▌    | 280/500 [33:44<29:27,  8.03s/klasa, klasa=class_280, F1_klasy=0.2667, F1_macro=0.7101, drzewa=215]




Trening klas:  56%|█████▌    | 281/500 [33:44<30:32,  8.37s/klasa, klasa=class_280, F1_klasy=0.2667, F1_macro=0.7101, drzewa=215]

[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[242]	valid_0's binary_logloss: 0.157279
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[243]	valid_0's binary_logloss: 0.157355
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[244]	valid_0's binary_logloss: 0.157383
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[245]	valid_0's binary_logloss: 0.157623
[1]	valid_0's binary_logloss: 0.213218
[2]	valid_0's binary_logloss: 0.18831
[3]	valid_0's binary_logloss: 0.175508
[4]	valid_0's binary_logloss: 0.165851
[5]	valid_0's binary_logloss: 0.158843
[6]	valid_0's binary_logloss: 0.152304
[7]	valid_0's binary_logloss: 0.145983
[8]	valid_0's binary_logloss: 0.141466
[9]	valid_0's binary_logloss: 0.137686
[10]	valid_0's binary_logloss: 0.134248
[11]	valid_0's binary_logloss: 0.129589
[12]	valid_0's binary_logloss: 0.125331
[13]	valid_0's binary_logloss: 0.121493
[14]	valid_0's binary_logloss: 0.118421
[15]	valid_0's binary_logloss: 0.115325
[16]	valid_0's binary_logloss: 0.11292
[17]	valid_0's binary_logloss: 0.110689
[18]	valid_0's binary_logloss: 0.108524
[19]	valid_0's binary_logloss: 0.106522
[20]	valid_0's binary_logloss: 0.104964
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.103313
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.102333
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.100759
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0993074
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.0978798
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.0966032
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.0953912
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.0939684
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.0929267
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.0920247
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.091273
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.0904823
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.0895699
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.0884778
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.0876562
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.0867368
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.0857584
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.0850389
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.0840696
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.0831609
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.082647
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.0821864
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.0814335
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.0809811
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.0802791
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.0795186
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.07903
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.0783772
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.0776644
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.0769604
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.0762563
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.0757274
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.0750322
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.0748553
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.0741608
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.0739097
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.0735325
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.0731651
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.0726158
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.0724076
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.0721938
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.0720181
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.0718617
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.0717553
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.0716445
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.0712544
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.0707914
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.0703324
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.0698779
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.0695165
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.0693259
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.069148
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.0690627
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.0688617
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.068933
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.0688758
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.0688341
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.0685046
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.0685417
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.0685102
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.0686028
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.0684901
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.0683826
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.0684475
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.0685355
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.0684458
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.0684458
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.0679962
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.0676314
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.0677597
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.0676392
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.0676833
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.0676713
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.0678152
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.0677771
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.067677
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.0676682
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.0675663
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.0674581
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.0672844
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.0671823
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.0670447
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.0669158
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.0668942
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.0667189
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.0667419
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.0667184
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.066805
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.0667954
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.0668707
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.066744
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 0.0666325
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 0.0666718
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 0.066535
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 0.0665428
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[116]	valid_0's binary_logloss: 0.0666276
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[117]	valid_0's binary_logloss: 0.0664806
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[118]	valid_0's binary_logloss: 0.0665207
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[119]	valid_0's binary_logloss: 0.0665407
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[120]	valid_0's binary_logloss: 0.066465
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[121]	valid_0's binary_logloss: 0.0664721
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[122]	valid_0's binary_logloss: 0.0665282
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[123]	valid_0's binary_logloss: 0.0665141
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[124]	valid_0's binary_logloss: 0.0665567
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[125]	valid_0's binary_logloss: 0.0664986
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[126]	valid_0's binary_logloss: 0.0665421
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[127]	valid_0's binary_logloss: 0.0665689
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[128]	valid_0's binary_logloss: 0.0665602
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[129]	valid_0's binary_logloss: 0.0664821
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[130]	valid_0's binary_logloss: 0.0664934
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[131]	valid_0's binary_logloss: 0.066546
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[132]	valid_0's binary_logloss: 0.0666435
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[133]	valid_0's binary_logloss: 0.0665967
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[134]	valid_0's binary_logloss: 0.0666469
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[135]	valid_0's binary_logloss: 0.0667668
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[136]	valid_0's binary_logloss: 0.0666331
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[137]	valid_0's binary_logloss: 0.0666928
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[138]	valid_0's binary_logloss: 0.0665291
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[139]	valid_0's binary_logloss: 0.066556
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[140]	valid_0's binary_logloss: 0.0665253
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[141]	valid_0's binary_logloss: 0.0664978
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[142]	valid_0's binary_logloss: 0.0664816
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[143]	valid_0's binary_logloss: 0.0664458
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[144]	valid_0's binary_logloss: 0.0664057
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[145]	valid_0's binary_logloss: 0.0662151
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[146]	valid_0's binary_logloss: 0.0661847
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[147]	valid_0's binary_logloss: 0.0662167
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[148]	valid_0's binary_logloss: 0.0661935
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[149]	valid_0's binary_logloss: 0.0661899
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[150]	valid_0's binary_logloss: 0.0661966
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[151]	valid_0's binary_logloss: 0.0662098
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[152]	valid_0's binary_logloss: 0.0662296
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[153]	valid_0's binary_logloss: 0.0662236
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[154]	valid_0's binary_logloss: 0.0664017
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[155]	valid_0's binary_logloss: 0.0662122
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[156]	valid_0's binary_logloss: 0.0662199
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[157]	valid_0's binary_logloss: 0.0661353
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[158]	valid_0's binary_logloss: 0.0660804
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[159]	valid_0's binary_logloss: 0.0660689
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[160]	valid_0's binary_logloss: 0.066033
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[161]	valid_0's binary_logloss: 0.0660264
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[162]	valid_0's binary_logloss: 0.0659985
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[163]	valid_0's binary_logloss: 0.0659057
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[164]	valid_0's binary_logloss: 0.0658376
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[165]	valid_0's binary_logloss: 0.0656767
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[166]	valid_0's binary_logloss: 0.0657388
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[167]	valid_0's binary_logloss: 0.06585
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[168]	valid_0's binary_logloss: 0.0658462
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[169]	valid_0's binary_logloss: 0.0658297
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[170]	valid_0's binary_logloss: 0.0658109
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[171]	valid_0's binary_logloss: 0.0656518
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[172]	valid_0's binary_logloss: 0.0655238
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[173]	valid_0's binary_logloss: 0.065432
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[174]	valid_0's binary_logloss: 0.0653283
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[175]	valid_0's binary_logloss: 0.0653022
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[176]	valid_0's binary_logloss: 0.0652382
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[177]	valid_0's binary_logloss: 0.0651919
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[178]	valid_0's binary_logloss: 0.0650286
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[179]	valid_0's binary_logloss: 0.0648794
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[180]	valid_0's binary_logloss: 0.0648309
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[181]	valid_0's binary_logloss: 0.064773

Trening klas:  56%|█████▌    | 281/500 [33:53<30:32,  8.37s/klasa, klasa=class_281, F1_klasy=0.5200, F1_macro=0.7094, drzewa=230]




Trening klas:  56%|█████▋    | 282/500 [33:53<30:58,  8.53s/klasa, klasa=class_281, F1_klasy=0.5200, F1_macro=0.7094, drzewa=230]

[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[257]	valid_0's binary_logloss: 0.0651019
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[258]	valid_0's binary_logloss: 0.0651713
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[259]	valid_0's binary_logloss: 0.0652306
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[260]	valid_0's binary_logloss: 0.0652707
[1]	valid_0's binary_logloss: 0.051975
[2]	valid_0's binary_logloss: 0.0492285
[3]	valid_0's binary_logloss: 0.0471017
[4]	valid_0's binary_logloss: 0.0451471
[5]	valid_0's binary_logloss: 0.043648
[6]	valid_0's binary_logloss: 0.0423552
[7]	valid_0's binary_logloss: 0.0409862
[8]	valid_0's binary_logloss: 0.0398626
[9]	valid_0's binary_logloss: 0.0389303
[10]	valid_0's binary_logloss: 0.0382406
[11]	valid_0's binary_logloss: 0.0371781
[12]	valid_0's binary_logloss: 0.0360352
[13]	valid_0's binary_logloss: 0.0353761
[14]	valid_0's binary_logloss: 0.0344215
[15]	valid_0's binary_logloss: 0.0337022
[16]	valid_0's binary_logloss: 0.0329616
[17]	valid_0's binary_logloss: 0.032491
[18]	valid_0's binary_logloss: 0.032153
[19]	valid_0's binary_logloss: 0.031479
[20]	valid_0's binary_logloss: 0.0308541
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0306495
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0302871
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.0301199
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0299264
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.0296625
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.0291908
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.0288436
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.0285483
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.0284384
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.0282255
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.0278924
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.0276377
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.0273356
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.0271661
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.0269694
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.0267215
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.026806
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.0266504
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.0264884
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.026407
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.0263311
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.0263123
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.0262363
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.0262916
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.0261816
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.0260827
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.0259803
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.0256602
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.0256027
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.0255863
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.0254618
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.0254783
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.025354
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.025321
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.0252634
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.0252993
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.0250382
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.0248575
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.0249917
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.0248281
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.0249305
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.0249794
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.0250965
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.0250372
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.025133
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.0250949
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.0250054
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.0248796
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.0248119
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.0246473
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.0247917
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.0248835
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.0249506
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.0249048
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.0249761
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.0250258
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.0251065
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.0251085
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.0252155
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.025255
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.0251988
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.0251254
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.0252428
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.0251715
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.0251865
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.0252908
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.0254706
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.0255223
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.0255766
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.0255958
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.0256526
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.0257146
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.0256374
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.0255629
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.0255241
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.0255008
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.0254968
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

Trening klas:  56%|█████▋    | 282/500 [33:57<30:58,  8.53s/klasa, klasa=class_282, F1_klasy=0.7516, F1_macro=0.7095, drzewa=70]




Trening klas:  57%|█████▋    | 283/500 [33:57<25:45,  7.12s/klasa, klasa=class_282, F1_klasy=0.7516, F1_macro=0.7095, drzewa=70]

[98]	valid_0's binary_logloss: 0.0255435
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.0255456
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.0255649
[1]	valid_0's binary_logloss: 0.0639458
[2]	valid_0's binary_logloss: 0.0603897
[3]	valid_0's binary_logloss: 0.0578815
[4]	valid_0's binary_logloss: 0.055637
[5]	valid_0's binary_logloss: 0.0532971
[6]	valid_0's binary_logloss: 0.0514199
[7]	valid_0's binary_logloss: 0.0500352
[8]	valid_0's binary_logloss: 0.0487745
[9]	valid_0's binary_logloss: 0.0477375
[10]	valid_0's binary_logloss: 0.046172
[11]	valid_0's binary_logloss: 0.0454803
[12]	valid_0's binary_logloss: 0.0449346
[13]	valid_0's binary_logloss: 0.0444663
[14]	valid_0's binary_logloss: 0.0441369
[15]	valid_0's binary_logloss: 0.0434189
[16]	valid_0's binary_logloss: 0.0425944
[17]	valid_0's binary_logloss: 0.0420458
[18]	valid_0's binary_logloss: 0.0415146
[19]	valid_0's binary_logloss: 0.0413294
[20]	valid_0's binary_logloss: 0.0406441
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0405019
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0400808
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.039315
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0390084
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.0385054
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.0383661
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.0380232
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.0374728
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.037461
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.0375208
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.0372808
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.0368783
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.0368553
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.0367537
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.0367134
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.0364264
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.0361393
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.0359233
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.0357044
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.0355071
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.0355368
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.0354739
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.035469
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.0354426
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.0355791
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.0353181
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.0354152
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.0351984
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.034768
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.0348714
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.0346474
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.0349533
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.0345905
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.0345658
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.0344449
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.0343698
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.0342082
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.0341964
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.034134
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.0339163
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.0338753
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.0338568
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.0338216
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.0337742
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.0339379
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.0336693
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.0335023
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.033409
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.0332902
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.0332505
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.0330959
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.0332146
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.0329711
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.0329087
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.0327514
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.0326242
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.0325675
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.032381
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.032164
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.0321002
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.0322672
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.0323633
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.0324535
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.0323067
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.0323658
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.0323105
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.0323358
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.032295
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.0320875
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.0321767
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.0323531
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.0324868
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.032517
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.0323094
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.0323398
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.0323378
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.0323961
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.0322132
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.032141
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.0320453
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.0319477
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.0317714
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.0315004
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.0313364
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.0311502
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.031064
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.0309416
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.0307768
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.0306725
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.0305145
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.0304105
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 0.0303467
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 0.0303988
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 0.0305048
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 0.0305594
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[116]	valid_0's binary_logloss: 0.030634
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[117]	valid_0's binary_logloss: 0.0305464
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[118]	valid_0's binary_logloss: 0.0304301
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[119]	valid_0's binary_logloss: 0.0303211
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[120]	valid_0's binary_logloss: 0.0304168
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[121]	valid_0's binary_logloss: 0.0303218
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[122]	valid_0's binary_logloss: 0.0301339
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[123]	valid_0's binary_logloss: 0.0300016
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[124]	valid_0's binary_logloss: 0.0300221
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[125]	valid_0's binary_logloss: 0.0298821
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[126]	valid_0's binary_logloss: 0.0297431
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[127]	valid_0's binary_logloss: 0.0298748
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[128]	valid_0's binary_logloss: 0.0296776
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[129]	valid_0's binary_logloss: 0.0297864
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[130]	valid_0's binary_logloss: 0.0299858
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[131]	valid_0's binary_logloss: 0.0297884
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[132]	valid_0's binary_logloss: 0.0296929
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[133]	valid_0's binary_logloss: 0.0294877
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[134]	valid_0's binary_logloss: 0.0296046
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[135]	valid_0's binary_logloss: 0.0295431
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[136]	valid_0's binary_logloss: 0.0295702
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[137]	valid_0's binary_logloss: 0.0295129
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[138]	valid_0's binary_logloss: 0.0294573
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[139]	valid_0's binary_logloss: 0.0295634
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[140]	valid_0's binary_logloss: 0.0295933
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[141]	valid_0's binary_logloss: 0.0295364
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[142]	valid_0's binary_logloss: 0.0295854
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[143]	valid_0's binary_logloss: 0.0295444
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[144]	valid_0's binary_logloss: 0.0295939
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[145]	valid_0's binary_logloss: 0.0296105
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[146]	valid_0's binary_logloss: 0.0298077
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[147]	valid_0's binary_logloss: 0.0298922
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[148]	valid_0's binary_logloss: 0.0298299
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[149]	valid_0's binary_logloss: 0.0299191
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[150]	valid_0's binary_logloss: 0.0299932
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[151]	valid_0's binary_logloss: 0.0299495
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[152]	valid_0's binary_logloss: 0.0299054
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[153]	valid_0's binary_logloss: 0.0298643
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[154]	valid_0's binary_logloss: 0.0297006
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[155]	valid_0's binary_logloss: 0.0295477
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[156]	valid_0's binary_logloss: 0.0296053
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[157]	valid_0's binary_logloss: 0.0296601
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[158]	valid_0's binary_logloss: 0.0295732
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[159]	valid_0's binary_logloss: 0.0296171
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[160]	valid_0's binary_logloss: 0.0296652
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[161]	valid_0's binary_logloss: 0.0296388
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[162]	valid_0's binary_logloss: 0.0296103
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[163]	valid_0's binary_logloss: 0.0295559
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[164]	valid_0's binary_logloss: 0.0295298
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[165]	valid_0's binary_logloss: 0.0294915
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[166]	valid_0's binary_logloss: 0.0294492
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[167]	valid_0's binary_logloss: 0.0293833
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[168]	valid_0's binary_logloss: 0.0293389
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[169]	valid_0's binary_logloss: 0.0293063
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[170]	valid_0's binary_logloss: 0.0292324
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[171]	valid_0's binary_logloss: 0.0292574
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[172]	valid_0's binary_logloss: 0.0293317
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[173]	valid_0's binary_logloss: 0.0293702
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[174]	valid_0's binary_logloss: 0.0293746
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[175]	valid_0's binary_logloss: 0.0294076
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[176]	valid_0's binary_logloss: 0.0294159
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[177]	valid_0's binary_logloss: 0.0294759
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[178]	valid_0's binary_logloss: 0.0294467
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[179]	valid_0's binary_logloss: 0.0293681
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[180]	valid_0's binary_logloss: 0.0293513
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[181]	valid_0's binary_logloss: 0.0293767
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[182]	valid_0's binary_logloss: 0.0291702

Trening klas:  57%|█████▋    | 283/500 [34:05<25:45,  7.12s/klasa, klasa=class_283, F1_klasy=0.7374, F1_macro=0.7096, drzewa=295]




Trening klas:  57%|█████▋    | 284/500 [34:05<27:16,  7.58s/klasa, klasa=class_283, F1_klasy=0.7374, F1_macro=0.7096, drzewa=295]

[1]	valid_0's binary_logloss: 0.0457021
[2]	valid_0's binary_logloss: 0.0440735
[3]	valid_0's binary_logloss: 0.042464
[4]	valid_0's binary_logloss: 0.0411728
[5]	valid_0's binary_logloss: 0.0399434
[6]	valid_0's binary_logloss: 0.0388557
[7]	valid_0's binary_logloss: 0.0376205
[8]	valid_0's binary_logloss: 0.0366581
[9]	valid_0's binary_logloss: 0.0355801
[10]	valid_0's binary_logloss: 0.0348151
[11]	valid_0's binary_logloss: 0.0338617
[12]	valid_0's binary_logloss: 0.0329644
[13]	valid_0's binary_logloss: 0.0322354
[14]	valid_0's binary_logloss: 0.0315116
[15]	valid_0's binary_logloss: 0.0307563
[16]	valid_0's binary_logloss: 0.0299832
[17]	valid_0's binary_logloss: 0.0293126
[18]	valid_0's binary_logloss: 0.0288215
[19]	valid_0's binary_logloss: 0.0282872
[20]	valid_0's binary_logloss: 0.0278276
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0274184
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0269676
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.0266543
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0263888
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.0260396
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.0257542
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.025516
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.0251604
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.024898
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.0246634
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.024412
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.0241697
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.0239642
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.0237692
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.0236094
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.0234665
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.0233025
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.0231211
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.0230149
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.023
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.0226158
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.0223152
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.0221166
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.0218706
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.0216755
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.0216362
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.0216043
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.0215235
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.021497
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.0214752
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.0215043
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.0215109
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.021505
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.0214331
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.0213526
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.0213227
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.0211406
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.0210577
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.0210411
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.0209657
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.0209242
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.0208958
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.0209169
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.0209761
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.0209753
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.0208761
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.0207538
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.0206462
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.0205965
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.0205498
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.0206359
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.0206661
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.0207263
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.0207455
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.0208432
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.0208223
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.0208132
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.0207846
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.0208322
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.0208844
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.0208868
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.0208631
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.0207971
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.0208259
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.0208123
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.0209006
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.0209428
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.0209723
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.0210082
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.0210049
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.0210326
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.021057
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.0210825
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.021126
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.0211687
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.0211514
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

Trening klas:  57%|█████▋    | 284/500 [34:11<27:16,  7.58s/klasa, klasa=class_284, F1_klasy=0.6491, F1_macro=0.7094, drzewa=70]




Trening klas:  57%|█████▋    | 285/500 [34:11<24:41,  6.89s/klasa, klasa=class_284, F1_klasy=0.6491, F1_macro=0.7094, drzewa=70]

[97]	valid_0's binary_logloss: 0.0211167
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.0211685
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.0212017
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.0212971
[1]	valid_0's binary_logloss: 0.0163534
[2]	valid_0's binary_logloss: 0.0155556
[3]	valid_0's binary_logloss: 0.0148065
[4]	valid_0's binary_logloss: 0.0140915
[5]	valid_0's binary_logloss: 0.013413
[6]	valid_0's binary_logloss: 0.0127848
[7]	valid_0's binary_logloss: 0.0124844
[8]	valid_0's binary_logloss: 0.0121883
[9]	valid_0's binary_logloss: 0.0116312
[10]	valid_0's binary_logloss: 0.0110974
[11]	valid_0's binary_logloss: 0.0106469
[12]	valid_0's binary_logloss: 0.0102436
[13]	valid_0's binary_logloss: 0.00979922
[14]	valid_0's binary_logloss: 0.00947436
[15]	valid_0's binary_logloss: 0.00918815
[16]	valid_0's binary_logloss: 0.00875108
[17]	valid_0's binary_logloss: 0.0083432
[18]	valid_0's binary_logloss: 0.00795055
[19]	valid_0's binary_logloss: 0.00780246
[20]	valid_0's binary_logloss: 0.00744675
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0071148
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.00679941
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.00648925
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.00622055
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.00593745
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.00584182
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.0057589
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.00565701
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.00557063
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.00532318
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.00509228
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.00484114
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.00462948
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.00442896
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.0042533
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.00407276
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.00390279
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.00374162
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.00358468
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.00343632
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.00329241
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.003167
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.00304714
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.00297103
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.00285701
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.00271939
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.00259302
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.00248299
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.00238939
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.00227606
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.00216602
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.00206283
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.00196595
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.00189314
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.00182439
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.00176027
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.00169936
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.00164318
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.00159054
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.0015202
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.00147164
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.00140541
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.0013626
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.00132209
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.00128402
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.00122866
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.00118026
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.00112876
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.00108117
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.00103329
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.0010038
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.000976087
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.00094972
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.000925702
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.000902518
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.000866637
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.000848472
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.000814254
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.000799018
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.000783319
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.000765193
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.000748364
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.000732796
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.000704817
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.000691121
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.000665423
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.000651293
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.000641505
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.000631019
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.00062049
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.000614959
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.000610341
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.000605631
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.000602045
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.000599009
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.000597028
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.000594568
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.000592647
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.000591568
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.000590721
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.000571051
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.0005627
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.000557863
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.0005529
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.000553083
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.000535154
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.000531399
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.000528649
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.000526366
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.000509877
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.000494092
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 0.000479259
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 0.000465115
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 0.000462398
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 0.000448881
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[116]	valid_0's binary_logloss: 0.000438304
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[117]	valid_0's binary_logloss: 0.000428061
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[118]	valid_0's binary_logloss: 0.000421451
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[119]	valid_0's binary_logloss: 0.000414146
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[120]	valid_0's binary_logloss: 0.000417762
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[121]	valid_0's binary_logloss: 0.000405523
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[122]	valid_0's binary_logloss: 0.000393912
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[123]	valid_0's binary_logloss: 0.000382895
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[124]	valid_0's binary_logloss: 0.000386969
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[125]	valid_0's binary_logloss: 0.000376552
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[126]	valid_0's binary_logloss: 0.00038013
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[127]	valid_0's binary_logloss: 0.000384048
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[128]	valid_0's binary_logloss: 0.000374162
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[129]	valid_0's binary_logloss: 0.000364708
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[130]	valid_0's binary_logloss: 0.000368863
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[131]	valid_0's binary_logloss: 0.000373426
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[132]	valid_0's binary_logloss: 0.000378086
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[133]	valid_0's binary_logloss: 0.000370789
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[134]	valid_0's binary_logloss: 0.000363538
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[135]	valid_0's binary_logloss: 0.000359324
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[136]	valid_0's binary_logloss: 0.000350214
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[137]	valid_0's binary_logloss: 0.000341488
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[138]	valid_0's binary_logloss: 0.000332359
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[139]	valid_0's binary_logloss: 0.000323318
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[140]	valid_0's binary_logloss: 0.000327898
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[141]	valid_0's binary_logloss: 0.000332006
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[142]	valid_0's binary_logloss: 0.000336226
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[143]	valid_0's binary_logloss: 0.000328939
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[144]	valid_0's binary_logloss: 0.000333596
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[145]	valid_0's binary_logloss: 0.000337869
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[146]	valid_0's binary_logloss: 0.000329944
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[147]	valid_0's binary_logloss: 0.000322017
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[148]	valid_0's binary_logloss: 0.000325331
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[149]	valid_0's binary_logloss: 0.00031774
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[150]	valid_0's binary_logloss: 0.000321021
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[151]	valid_0's binary_logloss: 0.000320416
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[152]	valid_0's binary_logloss: 0.000324269
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[153]	valid_0's binary_logloss: 0.000328284
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[154]	valid_0's binary_logloss: 0.000333154
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[155]	valid_0's binary_logloss: 0.000337289
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[156]	valid_0's binary_logloss: 0.000341769
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[157]	valid_0's binary_logloss: 0.000346298
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[158]	valid_0's binary_logloss: 0.000350498
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[159]	valid_0's binary_logloss: 0.00034554
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[160]	valid_0's binary_logloss: 0.000349698
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[161]	valid_0's binary_logloss: 0.000342805
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[162]	valid_0's binary_logloss: 0.000336023
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[163]	valid_0's binary_logloss: 0.000329444
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[164]	valid_0's binary_logloss: 0.000323167
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[165]	valid_0's binary_logloss: 0.000316839
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[166]	valid_0's binary_logloss: 0.000320786
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[167]	valid_0's binary_logloss: 0.000324693
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[168]	valid_0's binary_logloss: 0.000328563
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[169]	valid_0's binary_logloss: 0.000332415
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[170]	valid_0's binary_logloss: 0.000336199
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[171]	valid_0's binary_logloss: 0.000331094
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[172]	valid_0's binary_logloss: 0.000326133
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[173]	valid_0's binary_logloss: 0.00032126
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[174]	valid_0's binary_logloss: 0.000324792
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[175]	valid_0's binary_logloss: 0.00032011
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[176]	valid_0's binary_logloss: 0.000325741
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[177]	valid_0's binary_logloss: 0.000331505
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[178]	valid_0's binary_logloss: 0.000337254
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[179]	valid_0's binary_logloss: 0.000343103

Trening klas:  57%|█████▋    | 285/500 [34:16<24:41,  6.89s/klasa, klasa=class_285, F1_klasy=0.9231, F1_macro=0.7102, drzewa=165]




Trening klas:  57%|█████▋    | 286/500 [34:16<23:16,  6.53s/klasa, klasa=class_285, F1_klasy=0.9231, F1_macro=0.7102, drzewa=165]

[1]	valid_0's binary_logloss: 0.0927213
[2]	valid_0's binary_logloss: 0.086623
[3]	valid_0's binary_logloss: 0.0815908
[4]	valid_0's binary_logloss: 0.0777186
[5]	valid_0's binary_logloss: 0.074158
[6]	valid_0's binary_logloss: 0.0717442
[7]	valid_0's binary_logloss: 0.0693771
[8]	valid_0's binary_logloss: 0.0671507
[9]	valid_0's binary_logloss: 0.0650577
[10]	valid_0's binary_logloss: 0.0629699
[11]	valid_0's binary_logloss: 0.0607584
[12]	valid_0's binary_logloss: 0.0589537
[13]	valid_0's binary_logloss: 0.0572124
[14]	valid_0's binary_logloss: 0.0554879
[15]	valid_0's binary_logloss: 0.0539501
[16]	valid_0's binary_logloss: 0.0523193
[17]	valid_0's binary_logloss: 0.0507107
[18]	valid_0's binary_logloss: 0.0491737
[19]	valid_0's binary_logloss: 0.0479423
[20]	valid_0's binary_logloss: 0.0465087
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0451875
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0439751
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.0428392
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0415955
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.0404908
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.0395443
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.0387838
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.0379066
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.0370519
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.0364645
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.0356541
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.034914
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.0342523
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.0336546
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.0331148
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.0323945
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.0318115
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.0313542
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.0307817
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.0301503
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.0296054
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.0290406
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.0285658
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.028086
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.0276001
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.0271833
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.0267558
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.02648
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.0261926
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.0259172
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.0257329
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.0253583
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.0250539
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.0248101
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.0245275
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.0242966
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.0239908
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.0236868
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.0234598
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.0232048
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.0230101
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.0227592
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.0225139
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.0223932
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.0222307
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.0220933
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.0219275
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.0217219
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.0215757
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.0215279
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.0213469
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.0211574
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.0209654
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.0208287
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.0206089
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.0205118
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.0204428
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.0203126
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.0202617
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.0202264
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.0202122
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.0201595
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.0201037
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.0200573
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.0200412
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.0200163
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.0199492
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.01986
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.019813
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.0198238
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.0198076
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.0198445
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.0198749
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.0199274
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.0199863
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.0198485
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.01975
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.0197703
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.0197242
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.0197271
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.0198002
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.0198931
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.0198889
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.0199172
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.0199725
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.0199227
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.01987
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.0198942
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.0199195
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.0199208
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.0198774
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 0.0198276
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 0.0197811
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 0.0197223
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 0.0196581
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[116]	valid_0's binary_logloss: 0.0196221
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[117]	valid_0's binary_logloss: 0.0196277
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[118]	valid_0's binary_logloss: 0.0196776
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[119]	valid_0's binary_logloss: 0.0196977
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[120]	valid_0's binary_logloss: 0.0197098
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[121]	valid_0's binary_logloss: 0.0197445
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[122]	valid_0's binary_logloss: 0.0197951
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[123]	valid_0's binary_logloss: 0.0197986
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[124]	valid_0's binary_logloss: 0.0198461
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[125]	valid_0's binary_logloss: 0.0198851
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[126]	valid_0's binary_logloss: 0.019898
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[127]	valid_0's binary_logloss: 0.0199183
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[128]	valid_0's binary_logloss: 0.0199622
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[129]	valid_0's binary_logloss: 0.0200124
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[130]	valid_0's binary_logloss: 0.020005
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[131]	valid_0's binary_logloss: 0.0199792
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[132]	valid_0's binary_logloss: 0.0200178
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[133]	valid_0's binary_logloss: 0.0200317
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[134]	valid_0's binary_logloss: 0.0200554
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[135]	valid_0's binary_logloss: 0.0200824
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[136]	valid_0's binary_logloss: 0.0201308
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[137]	valid_0's binary_logloss: 0.0202006
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[138]	valid_0's binary_logloss: 0.020229
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[139]	valid_0's binary_logloss: 0.0202653
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[140]	valid_0's binary_logloss: 0.0202971
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[141]	valid_0's binary_logloss: 0.0203401
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[142]	valid_0's binary_logloss: 0.020383
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[143]	valid_0's binary_logloss: 0.0203359
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[144]	valid_0's binary_logloss: 0.0203452
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

Trening klas:  57%|█████▋    | 286/500 [34:22<23:16,  6.53s/klasa, klasa=class_286, F1_klasy=0.6847, F1_macro=0.7101, drzewa=116]




Trening klas:  57%|█████▋    | 287/500 [34:22<22:28,  6.33s/klasa, klasa=class_286, F1_klasy=0.6847, F1_macro=0.7101, drzewa=116]

[145]	valid_0's binary_logloss: 0.0204292
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[146]	valid_0's binary_logloss: 0.0203708
[1]	valid_0's binary_logloss: 0.299727
[2]	valid_0's binary_logloss: 0.170475
[3]	valid_0's binary_logloss: 0.156421
[4]	valid_0's binary_logloss: 0.148611
[5]	valid_0's binary_logloss: 0.143378
[6]	valid_0's binary_logloss: 0.15306
[7]	valid_0's binary_logloss: 0.147179
[8]	valid_0's binary_logloss: 0.143183
[9]	valid_0's binary_logloss: 0.136838
[10]	valid_0's binary_logloss: 0.133186
[11]	valid_0's binary_logloss: 0.129429
[12]	valid_0's binary_logloss: 0.126322
[13]	valid_0's binary_logloss: 0.12372
[14]	valid_0's binary_logloss: 0.121004
[15]	valid_0's binary_logloss: 0.118227
[16]	valid_0's binary_logloss: 0.115764
[17]	valid_0's binary_logloss: 0.113829
[18]	valid_0's binary_logloss: 0.112043
[19]	valid_0's binary_logloss: 0.110319
[20]	valid_0's binary_logloss: 0.108691
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.107149
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.105643
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.104433
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.103137
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.101931
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.100793
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.0997033
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.098616
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.0975149
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.0966818
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.0958006
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.0949798
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.0943551
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.0936676
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.0930991
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.0919114
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.0910931
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.0903257
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.0892084
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.0885404
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.0878607
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.0872531
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.0863347
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.0854832
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.0848291
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.0840823
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.0833434
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.0829372
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.0822886
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.0819658
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.0815325
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.0811178
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.0808422
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.0804103
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.0800852
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.0795131
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.0790529
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.0786213
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.0783626
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.0779798
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.0773947
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.0771293
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.076685
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.0764935
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.0759459
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.0755564
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.0749437
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.0745109
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.07409
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.0735955
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.0735631
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.0733468
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.0731302
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.0729579
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.0727002
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.072391
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.0721457
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.0720242
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.0719358
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.0719399
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.0718719
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.0717554
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.0713327
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.0711898
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.0709436
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.0707414
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.0704635
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.07011
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.0698465
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.069527
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.0693892
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.0690797
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.0689318
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.0689448
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.0687341
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.0685811
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.0683957
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.0682694
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.0681332
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.0681512
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.0677862
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.067589
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.0674361
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.0668635
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.0665523
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.0668219
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.0669831
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.0668377
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.0669312
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.0670491
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.0668537
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 0.0666809
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 0.0666895
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 0.0665323
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 0.066523
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[116]	valid_0's binary_logloss: 0.0663236
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[117]	valid_0's binary_logloss: 0.0662818
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[118]	valid_0's binary_logloss: 0.0662436
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[119]	valid_0's binary_logloss: 0.0661918
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[120]	valid_0's binary_logloss: 0.0662268
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[121]	valid_0's binary_logloss: 0.0661123
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[122]	valid_0's binary_logloss: 0.0660198
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[123]	valid_0's binary_logloss: 0.0659213
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[124]	valid_0's binary_logloss: 0.0659148
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[125]	valid_0's binary_logloss: 0.066047
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[126]	valid_0's binary_logloss: 0.066022
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[127]	valid_0's binary_logloss: 0.0659715
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[128]	valid_0's binary_logloss: 0.0658813
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[129]	valid_0's binary_logloss: 0.065885
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[130]	valid_0's binary_logloss: 0.0660088
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[131]	valid_0's binary_logloss: 0.0658875
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[132]	valid_0's binary_logloss: 0.0659321
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[133]	valid_0's binary_logloss: 0.0658411
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[134]	valid_0's binary_logloss: 0.0658742
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[135]	valid_0's binary_logloss: 0.0659816
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[136]	valid_0's binary_logloss: 0.0661416
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[137]	valid_0's binary_logloss: 0.0661733
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[138]	valid_0's binary_logloss: 0.0663432
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[139]	valid_0's binary_logloss: 0.0662651
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[140]	valid_0's binary_logloss: 0.06626
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[141]	valid_0's binary_logloss: 0.0661848
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[142]	valid_0's binary_logloss: 0.0661908
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[143]	valid_0's binary_logloss: 0.0661226
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[144]	valid_0's binary_logloss: 0.0662301
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[145]	valid_0's binary_logloss: 0.0663331
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[146]	valid_0's binary_logloss: 0.0659789
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[147]	valid_0's binary_logloss: 0.0657131
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[148]	valid_0's binary_logloss: 0.0656454
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[149]	valid_0's binary_logloss: 0.0653805
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[150]	valid_0's binary_logloss: 0.0653276
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[151]	valid_0's binary_logloss: 0.0655315
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[152]	valid_0's binary_logloss: 0.0655547
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[153]	valid_0's binary_logloss: 0.0656361
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[154]	valid_0's binary_logloss: 0.0658523
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[155]	valid_0's binary_logloss: 0.0660357
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[156]	valid_0's binary_logloss: 0.0662029
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[157]	valid_0's binary_logloss: 0.0663984
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[158]	valid_0's binary_logloss: 0.0665809
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[159]	valid_0's binary_logloss: 0.0668
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[160]	valid_0's binary_logloss: 0.0668781
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[161]	valid_0's binary_logloss: 0.0670055
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[162]	valid_0's binary_logloss: 0.0669154
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[163]	valid_0's binary_logloss: 0.067097
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[164]	valid_0's binary_logloss: 0.0671471
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[165]	valid_0's binary_logloss: 0.0670779
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[166]	valid_0's binary_logloss: 0.0666492
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[167]	valid_0's binary_logloss: 0.0663613
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[168]	valid_0's binary_logloss: 0.0660551
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[169]	valid_0's binary_logloss: 0.0658654
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[170]	valid_0's binary_logloss: 0.0657391
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[171]	valid_0's binary_logloss: 0.0657185
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[172]	valid_0's binary_logloss: 0.0656959
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[173]	valid_0's binary_logloss: 0.0656967
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[174]	valid_0's binary_logloss: 0.0657421
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[175]	valid_0's binary_logloss: 0.0658011
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[176]	valid_0's binary_logloss: 0.0657919
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[177]	valid_0's binary_logloss: 0.0657093
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[178]	valid_0's binary_logloss: 0.0658144
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[179]	valid_0's binary_logloss: 0.0658279
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

Trening klas:  57%|█████▋    | 287/500 [34:29<22:28,  6.33s/klasa, klasa=class_287, F1_klasy=0.6849, F1_macro=0.7100, drzewa=150]




Trening klas:  58%|█████▊    | 288/500 [34:29<22:41,  6.42s/klasa, klasa=class_287, F1_klasy=0.6849, F1_macro=0.7100, drzewa=150]

[180]	valid_0's binary_logloss: 0.0658962
[1]	valid_0's binary_logloss: 0.030244
[2]	valid_0's binary_logloss: 0.0293357
[3]	valid_0's binary_logloss: 0.0285544
[4]	valid_0's binary_logloss: 0.0273838
[5]	valid_0's binary_logloss: 0.0267389
[6]	valid_0's binary_logloss: 0.0256149
[7]	valid_0's binary_logloss: 0.0246058
[8]	valid_0's binary_logloss: 0.023721
[9]	valid_0's binary_logloss: 0.0227791
[10]	valid_0's binary_logloss: 0.0221998
[11]	valid_0's binary_logloss: 0.021567
[12]	valid_0's binary_logloss: 0.0211115
[13]	valid_0's binary_logloss: 0.0204888
[14]	valid_0's binary_logloss: 0.0198936
[15]	valid_0's binary_logloss: 0.019317
[16]	valid_0's binary_logloss: 0.0185927
[17]	valid_0's binary_logloss: 0.0181433
[18]	valid_0's binary_logloss: 0.0177784
[19]	valid_0's binary_logloss: 0.0172328
[20]	valid_0's binary_logloss: 0.0169071
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0164708
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0161676
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.0158896
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.015815
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.0157519
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.0153643
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.0151121
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.0146739
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.0144911
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.0142953
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.0141239
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.0139303
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.0136673
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.0133478
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.0130156
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.0129553
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.0129644
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.012867
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.0128002
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.0127017
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.0124158
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.0121043
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.0118999
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.0117053
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.0115077
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.0114625
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.0113402
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.0111199
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.011081
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.0110076
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.0109624
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.0108512
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.0107805
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.0106739
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.0106583
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.0105685
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.0103229
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.0102297
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.0101301
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.00996276
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.00973557
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.00960815
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.00945046
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.00929536
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.00914452
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.00900726
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.00887778
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.00881645
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.00876783
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.0086165
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.00862056
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.00848253
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.00850444
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.00842714
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.00845822
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.00831612
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.00823973
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.00810921
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.00804394
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.00799425
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.00795381
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.00788156
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.0078173
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.00767971
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.00760567
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.00751692
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.00743354
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.00736414
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.00729539
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.00723206
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.00716563
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.00710105
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.00710457
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.00705779
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.00707525
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.00712234
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.00702429
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.00696125
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.00700586
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.00704244
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.00705744
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.00704453
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.00705764
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.00701474
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.0069886
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.0069036
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.00685965
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.00683617
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.00678973
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.0067624
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.00676476
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 0.00680918
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 0.00683351
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 0.00682977
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 0.00682892
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[116]	valid_0's binary_logloss: 0.00678179
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[117]	valid_0's binary_logloss: 0.00681809
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[118]	valid_0's binary_logloss: 0.00682505
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[119]	valid_0's binary_logloss: 0.00684398
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[120]	valid_0's binary_logloss: 0.00685248
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[121]	valid_0's binary_logloss: 0.0068809
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[122]	valid_0's binary_logloss: 0.00688616
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[123]	valid_0's binary_logloss: 0.00688431
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[124]	valid_0's binary_logloss: 0.00688095
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[125]	valid_0's binary_logloss: 0.00686483
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[126]	valid_0's binary_logloss: 0.00685966
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[127]	valid_0's binary_logloss: 0.00679582
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[128]	valid_0's binary_logloss: 0.00681777
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[129]	valid_0's binary_logloss: 0.00683097
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[130]	valid_0's binary_logloss: 0.00685197
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[131]	valid_0's binary_logloss: 0.00684341
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[132]	valid_0's binary_logloss: 0.00682904
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[133]	valid_0's binary_logloss: 0.00681721
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[134]	valid_0's binary_logloss: 0.00679663
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[135]	valid_0's binary_logloss: 0.00679326
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[136]	valid_0's binary_logloss: 0.00679596
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[137]	valid_0's binary_logloss: 0.00678901
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[138]	valid_0's binary_logloss: 0.00678209
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[139]	valid_0's binary_logloss: 0.0067707
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

Trening klas:  58%|█████▊    | 288/500 [34:35<22:41,  6.42s/klasa, klasa=class_288, F1_klasy=0.6111, F1_macro=0.7097, drzewa=110]




Trening klas:  58%|█████▊    | 289/500 [34:35<21:42,  6.17s/klasa, klasa=class_288, F1_klasy=0.6111, F1_macro=0.7097, drzewa=110]

[140]	valid_0's binary_logloss: 0.00679555
[1]	valid_0's binary_logloss: 0.045298
[2]	valid_0's binary_logloss: 0.0426411
[3]	valid_0's binary_logloss: 0.0399755
[4]	valid_0's binary_logloss: 0.037253
[5]	valid_0's binary_logloss: 0.0356183
[6]	valid_0's binary_logloss: 0.0340445
[7]	valid_0's binary_logloss: 0.03245
[8]	valid_0's binary_logloss: 0.0309337
[9]	valid_0's binary_logloss: 0.0295588
[10]	valid_0's binary_logloss: 0.0285726
[11]	valid_0's binary_logloss: 0.0274895
[12]	valid_0's binary_logloss: 0.0265006
[13]	valid_0's binary_logloss: 0.0256672
[14]	valid_0's binary_logloss: 0.0248309
[15]	valid_0's binary_logloss: 0.0240874
[16]	valid_0's binary_logloss: 0.0233054
[17]	valid_0's binary_logloss: 0.0226261
[18]	valid_0's binary_logloss: 0.0219471
[19]	valid_0's binary_logloss: 0.0212341
[20]	valid_0's binary_logloss: 0.0205662
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0202197
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0196862
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.0192766
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0190019
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.0185484
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.018171
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.0178284
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.0174928
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.017252
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.0169198
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.0166358
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.0164429
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.0161104
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.0159184
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.0157448
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.0156277
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.0155018
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.0153669
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.0152527
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.0151343
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.0150032
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.0148244
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.0147076
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.0146042
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.0145341
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.0144856
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.0144372
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.0142085
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.0139392
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.0137061
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.0135427
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.0134671
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.0133392
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.0131677
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.0129887
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.0128892
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.0128187
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.0127575
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.0126737
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.0126582
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.0126076
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.0125882
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.012527
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.0124446
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.01239
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.0123451
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.0123491
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.0123564
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.0123717
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.0122744
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.012255
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.0121441
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.0121239
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.0120811
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.0120439
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.0119898
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.0119787
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.0119716
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.0118836
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.0118553
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.0117731
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.0117414
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.0117077
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.0116706
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.0116682
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.0116086
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.0116579
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.0116862
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.011748
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.011782
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.0117612
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.0117915
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.0117642
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.0117898
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.0117978
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.0117487
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.0117291
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.0117278
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.0116918
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.0116556
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.0116808
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.0117086
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.0117245
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.011783
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.0117801
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.0117391
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.0116713
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.0116302
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.0115883
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.0115182
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.0115663
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 0.0116045
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 0.0116453
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 0.01166
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 0.011687
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[116]	valid_0's binary_logloss: 0.0116665
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[117]	valid_0's binary_logloss: 0.0116625
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[118]	valid_0's binary_logloss: 0.0116312
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[119]	valid_0's binary_logloss: 0.0116601
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[120]	valid_0's binary_logloss: 0.0117188
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[121]	valid_0's binary_logloss: 0.0116376
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[122]	valid_0's binary_logloss: 0.0116771
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[123]	valid_0's binary_logloss: 0.0116896
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[124]	valid_0's binary_logloss: 0.0116766
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[125]	valid_0's binary_logloss: 0.0116548
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[126]	valid_0's binary_logloss: 0.0116888
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[127]	valid_0's binary_logloss: 0.0117312
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[128]	valid_0's binary_logloss: 0.0117886
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[129]	valid_0's binary_logloss: 0.0118353
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[130]	valid_0's binary_logloss: 0.0118401
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[131]	valid_0's binary_logloss: 0.0118575
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[132]	valid_0's binary_logloss: 0.0118838
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[133]	valid_0's binary_logloss: 0.0118674
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[134]	valid_0's binary_logloss: 0.0118536
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[135]	valid_0's binary_logloss: 0.0118269
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[136]	valid_0's binary_logloss: 0.0118371
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[137]	valid_0's binary_logloss: 0.0118401
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[138]	valid_0's binary_logloss: 0.0118249
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

Trening klas:  58%|█████▊    | 289/500 [34:39<21:42,  6.17s/klasa, klasa=class_289, F1_klasy=0.8000, F1_macro=0.7100, drzewa=110]




Trening klas:  58%|█████▊    | 290/500 [34:39<20:16,  5.79s/klasa, klasa=class_289, F1_klasy=0.8000, F1_macro=0.7100, drzewa=110]

[139]	valid_0's binary_logloss: 0.0118038
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[140]	valid_0's binary_logloss: 0.0117771
[1]	valid_0's binary_logloss: 0.0113604
[2]	valid_0's binary_logloss: 0.0109215
[3]	valid_0's binary_logloss: 0.0103721
[4]	valid_0's binary_logloss: 0.00993162
[5]	valid_0's binary_logloss: 0.00945781
[6]	valid_0's binary_logloss: 0.00899085
[7]	valid_0's binary_logloss: 0.00867051
[8]	valid_0's binary_logloss: 0.00824646
[9]	valid_0's binary_logloss: 0.00796323
[10]	valid_0's binary_logloss: 0.00765015
[11]	valid_0's binary_logloss: 0.00731528
[12]	valid_0's binary_logloss: 0.00701739
[13]	valid_0's binary_logloss: 0.00674624
[14]	valid_0's binary_logloss: 0.00642579
[15]	valid_0's binary_logloss: 0.00617473
[16]	valid_0's binary_logloss: 0.00595328
[17]	valid_0's binary_logloss: 0.0056765
[18]	valid_0's binary_logloss: 0.00544199
[19]	valid_0's binary_logloss: 0.00518254
[20]	valid_0's binary_logloss: 0.00495941
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.00475193
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.00456338
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.00433985
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.00412592
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.00392686
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.00375193
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.0035867
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.00343833
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.00329976
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.00315453
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.00301797
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.00288684
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.00274562
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.00261089
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.00248034
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.00235938
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.00224494
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.00213649
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.00203404
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.00193578
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.00184878
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.00176091
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.00168148
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.00161809
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.00155494
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.00148359
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.00142586
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.00137154
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.00132242
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.00127401
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.00123544
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.00118024
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.00114121
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.0011131
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.00106153
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.00101626
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.000973612
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.000931496
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.000894758
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.000858683
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.000819847
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.000787448
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.000756611
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.000728094
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.000695227
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.000663389
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.000634296
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.000606826
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.000586243
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.00056197
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.000537154
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.00051371
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.000489668
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.000465322
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.000445376
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.000423895
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.000403581
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.000384299
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.000366007
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.000348497
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.000331814
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.000316078
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.000301942
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.000286
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.000271764
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.000261379
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.000249792
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.000238718
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.000228353
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.000218501
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.000209386
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.000201214
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.000193466
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.000184819
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.000177918
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.000168855
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.000159951
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.000151894
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.000145029
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.000137984
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.000132304
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.000127101
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.000122383
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.000116833
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.000111778
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.000107227
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.000103032
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 9.89901e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 9.50115e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 9.17094e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 9.00308e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 8.85684e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 8.55369e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 8.20629e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 7.89669e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[116]	valid_0's binary_logloss: 7.63011e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[117]	valid_0's binary_logloss: 7.36476e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[118]	valid_0's binary_logloss: 7.10334e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[119]	valid_0's binary_logloss: 6.86422e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[120]	valid_0's binary_logloss: 6.62385e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[121]	valid_0's binary_logloss: 6.408e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[122]	valid_0's binary_logloss: 6.20844e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[123]	valid_0's binary_logloss: 6.00996e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[124]	valid_0's binary_logloss: 5.83259e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[125]	valid_0's binary_logloss: 5.60262e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[126]	valid_0's binary_logloss: 5.4217e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[127]	valid_0's binary_logloss: 5.25143e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[128]	valid_0's binary_logloss: 5.11227e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[129]	valid_0's binary_logloss: 4.97361e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[130]	valid_0's binary_logloss: 4.828e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[131]	valid_0's binary_logloss: 4.69556e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[132]	valid_0's binary_logloss: 4.58299e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[133]	valid_0's binary_logloss: 4.48065e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[134]	valid_0's binary_logloss: 4.36237e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[135]	valid_0's binary_logloss: 4.23238e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[136]	valid_0's binary_logloss: 4.10167e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[137]	valid_0's binary_logloss: 3.97412e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[138]	valid_0's binary_logloss: 3.85807e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[139]	valid_0's binary_logloss: 3.71632e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[140]	valid_0's binary_logloss: 3.61305e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[141]	valid_0's binary_logloss: 3.49782e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[142]	valid_0's binary_logloss: 3.40833e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[143]	valid_0's binary_logloss: 3.3236e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[144]	valid_0's binary_logloss: 3.24307e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[145]	valid_0's binary_logloss: 3.16516e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[146]	valid_0's binary_logloss: 3.0806e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[147]	valid_0's binary_logloss: 2.99697e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[148]	valid_0's binary_logloss: 2.91841e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[149]	valid_0's binary_logloss: 2.84985e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[150]	valid_0's binary_logloss: 2.7792e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[151]	valid_0's binary_logloss: 2.69695e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[152]	valid_0's binary_logloss: 2.62183e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[153]	valid_0's binary_logloss: 2.54685e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[154]	valid_0's binary_logloss: 2.47552e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[155]	valid_0's binary_logloss: 2.42467e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[156]	valid_0's binary_logloss: 2.37878e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[157]	valid_0's binary_logloss: 2.33356e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[158]	valid_0's binary_logloss: 2.2961e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[159]	valid_0's binary_logloss: 2.26334e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[160]	valid_0's binary_logloss: 2.24774e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[161]	valid_0's binary_logloss: 2.20655e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[162]	valid_0's binary_logloss: 2.14831e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[163]	valid_0's binary_logloss: 2.10326e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[164]	valid_0's binary_logloss: 2.04986e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[165]	valid_0's binary_logloss: 1.99887e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[166]	valid_0's binary_logloss: 1.96091e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[167]	valid_0's binary_logloss: 1.9211e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[168]	valid_0's binary_logloss: 1.88389e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[169]	valid_0's binary_logloss: 1.85115e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[170]	valid_0's binary_logloss: 1.81646e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[171]	valid_0's binary_logloss: 1.80553e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[172]	valid_0's binary_logloss: 1.80328e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[173]	valid_0's binary_logloss: 1.79663e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[174]	valid_0's binary_logloss: 1.79658e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[175]	valid_0's binary_logloss: 1.79348e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[176]	valid_0's binary_logloss: 1.75604e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[177]	valid_0's binary_logloss: 1.73874e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[178]	valid_0's binary_logloss: 1.73087e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[179]	valid_0's binary_logloss: 1.69681e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[180]	valid_0's binary_logloss: 1.68154e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

Trening klas:  58%|█████▊    | 290/500 [34:45<20:16,  5.79s/klasa, klasa=class_290, F1_klasy=1.0000, F1_macro=0.7110, drzewa=300]




Trening klas:  58%|█████▊    | 291/500 [34:45<20:21,  5.84s/klasa, klasa=class_290, F1_klasy=1.0000, F1_macro=0.7110, drzewa=300]

[295]	valid_0's binary_logloss: 7.29532e-06
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[296]	valid_0's binary_logloss: 7.2461e-06
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[297]	valid_0's binary_logloss: 7.1835e-06
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[298]	valid_0's binary_logloss: 7.15868e-06
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[299]	valid_0's binary_logloss: 7.1135e-06
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[300]	valid_0's binary_logloss: 7.07272e-06
[1]	valid_0's binary_logloss: 0.0328365
[2]	valid_0's binary_logloss: 0.0317661
[3]	valid_0's binary_logloss: 0.0307146
[4]	valid_0's binary_logloss: 0.0297483
[5]	valid_0's binary_logloss: 0.0287746
[6]	valid_0's binary_logloss: 0.028105
[7]	valid_0's binary_logloss: 0.0274978
[8]	valid_0's binary_logloss: 0.026919
[9]	valid_0's binary_logloss: 0.0263773
[10]	valid_0's binary_logloss: 0.0259904
[11]	valid_0's binary_logloss: 0.0255348
[12]	valid_0's binary_logloss: 0.0251555
[13]	valid_0's binary_logloss: 0.0247461
[14]	valid_0's binary_logloss: 0.0244181
[15]	valid_0's binary_logloss: 0.0241572
[16]	valid_0's binary_logloss: 0.0239567
[17]	valid_0's binary_logloss: 0.0237389
[18]	valid_0's binary_logloss: 0.0234919
[19]	valid_0's binary_logloss: 0.0232377
[20]	valid_0's binary_logloss: 0.0230664
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0229308
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0228188
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.0227046
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0227312
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.0226867
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.0225486
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.0223879
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.0222422
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.0222097
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.0220657
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.0219193
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.0218133
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.0215991
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.021523
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.0214978
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.0215315
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.021433
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.0214017
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.0213811
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.0214434
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.0214739
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.0214953
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.0215669
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.0215944
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.0216119
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.0216909
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.0217683
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.0218196
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.0219022
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.0219196
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.0219328
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.0219674
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.0218242
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.0217929
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.0217574
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.0217165
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.0218024
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.0218226
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.0219
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.0220273
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.0220458
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.0221181
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.0220248
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.022182
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.0222456
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.0222213
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.0222048
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.0222063
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.022249

Trening klas:  58%|█████▊    | 291/500 [34:50<20:21,  5.84s/klasa, klasa=class_291, F1_klasy=0.6719, F1_macro=0.7108, drzewa=39]




Trening klas:  58%|█████▊    | 292/500 [34:50<18:42,  5.40s/klasa, klasa=class_291, F1_klasy=0.6719, F1_macro=0.7108, drzewa=39]

[1]	valid_0's binary_logloss: 0.0340739
[2]	valid_0's binary_logloss: 0.0332799
[3]	valid_0's binary_logloss: 0.0325421
[4]	valid_0's binary_logloss: 0.0321172
[5]	valid_0's binary_logloss: 0.0315888
[6]	valid_0's binary_logloss: 0.0321346
[7]	valid_0's binary_logloss: 0.0316989
[8]	valid_0's binary_logloss: 0.0312362
[9]	valid_0's binary_logloss: 0.0308296
[10]	valid_0's binary_logloss: 0.0303504
[11]	valid_0's binary_logloss: 0.0360994
[12]	valid_0's binary_logloss: 0.0349038
[13]	valid_0's binary_logloss: 0.0344754
[14]	valid_0's binary_logloss: 0.0338619
[15]	valid_0's binary_logloss: 0.0333591
[16]	valid_0's binary_logloss: 0.0327133
[17]	valid_0's binary_logloss: 0.0322675
[18]	valid_0's binary_logloss: 0.0318882
[19]	valid_0's binary_logloss: 0.0315216
[20]	valid_0's binary_logloss: 0.0311872
[21]	valid_0's binary_logloss: 0.0306513
[22]	valid_0's binary_logloss: 0.030205
[23]	valid_0's binary_logloss: 0.0297807
[24]	valid_0's binary_logloss: 0.0295196
[25]	valid_0's binary_logloss: 0.0291022
[26]	valid_0's binary_logloss: 0.0288736
[27]	valid_0's binary_logloss: 0.0286357
[28]	valid_0's binary_logloss: 0.0284373
[29]	valid_0's binary_logloss: 0.0282942
[30]	valid_0's binary_logloss: 0.028138
[31]	valid_0's binary_logloss: 0.0278782
[32]	valid_0's binary_logloss: 0.0275949
[33]	valid_0's binary_logloss: 0.0273635
[34]	valid_0's binary_logloss: 0.0272347
[35]	valid_0's binary_logloss: 0.0270604
[36]	valid_0's binary_logloss: 0.0269938
[37]	valid_0's binary_logloss: 0.0267727
[38]	valid_0's binary_logloss: 0.0265159
[39]	valid_0's binary_logloss: 0.026305
[40]	valid_0's binary_logloss: 0.0259942
[41]	valid_0's binary_logloss: 0.0258628
[42]	valid_0's binary_logloss: 0.0256494
[43]	valid_0's binary_logloss: 0.0254926
[44]	valid_0's binary_logloss: 0.0253285
[45]	valid_0's binary_logloss: 0.0251631
[46]	valid_0's binary_logloss: 0.0248841
[47]	valid_0's binary_logloss: 0.0247114
[48]	valid_0's binary_logloss: 0.0244985
[49]	valid_0's binary_logloss: 0.0243594
[50]	valid_0's binary_logloss: 0.0240378
[51]	valid_0's binary_logloss: 0.0238218
[52]	valid_0's binary_logloss: 0.0236746
[53]	valid_0's binary_logloss: 0.0233875
[54]	valid_0's binary_logloss: 0.0232265
[55]	valid_0's binary_logloss: 0.0230617
[56]	valid_0's binary_logloss: 0.0229917
[57]	valid_0's binary_logloss: 0.0228912
[58]	valid_0's binary_logloss: 0.0228051
[59]	valid_0's binary_logloss: 0.0227161
[60]	valid_0's binary_logloss: 0.0226833
[61]	valid_0's binary_logloss: 0.0226516
[62]	valid_0's binary_logloss: 0.0226222
[63]	valid_0's binary_logloss: 0.0224021
[64]	valid_0's binary_logloss: 0.0222985
[65]	valid_0's binary_logloss: 0.0222223
[66]	valid_0's binary_logloss: 0.0221681
[67]	valid_0's binary_logloss: 0.0220464
[68]	valid_0's binary_logloss: 0.0219596
[69]	valid_0's binary_logloss: 0.0219862
[70]	valid_0's binary_logloss: 0.0218669
[71]	valid_0's binary_logloss: 0.0218189
[72]	valid_0's binary_logloss: 0.021663
[73]	valid_0's binary_logloss: 0.0215324
[74]	valid_0's binary_logloss: 0.0213675
[75]	valid_0's binary_logloss: 0.0212453
[76]	valid_0's binary_logloss: 0.0212874
[77]	valid_0's binary_logloss: 0.021288
[78]	valid_0's binary_logloss: 0.0214015
[79]	valid_0's binary_logloss: 0.0213694
[80]	valid_0's binary_logloss: 0.0214175
[81]	valid_0's binary_logloss: 0.0212579
[82]	valid_0's binary_logloss: 0.0211325
[83]	valid_0's binary_logloss: 0.0210315
[84]	valid_0's binary_logloss: 0.0210907
[85]	valid_0's binary_logloss: 0.0209791
[86]	valid_0's binary_logloss: 0.0209364
[87]	valid_0's binary_logloss: 0.0209232
[88]	valid_0's binary_logloss: 0.0209012
[89]	valid_0's binary_logloss: 0.0209022
[90]	valid_0's binary_logloss: 0.0208522
[91]	valid_0's binary_logloss: 0.0207538
[92]	valid_0's binary_logloss: 0.0207277
[93]	valid_0's binary_logloss: 0.0207209
[94]	valid_0's binary_logloss: 0.0207016
[95]	valid_0's binary_logloss: 0.0206241
[96]	valid_0's binary_logloss: 0.0207361
[97]	valid_0's binary_logloss: 0.0206566
[98]	valid_0's binary_logloss: 0.0206138
[99]	valid_0's binary_logloss: 0.0205384
[100]	valid_0's binary_logloss: 0.0205265
[101]	valid_0's binary_logloss: 0.0204504
[102]	valid_0's binary_logloss: 0.0203744
[103]	valid_0's binary_logloss: 0.0202738
[104]	valid_0's binary_logloss: 0.0203062
[105]	valid_0's binary_logloss: 0.0203487
[106]	valid_0's binary_logloss: 0.0203183
[107]	valid_0's binary_logloss: 0.0202054
[108]	valid_0's binary_logloss: 0.0201595
[109]	valid_0's binary_logloss: 0.0202894
[110]	valid_0's binary_logloss: 0.0203444
[111]	valid_0's binary_logloss: 0.0203722
[112]	valid_0's binary_logloss: 0.0203996
[113]	valid_0's binary_logloss: 0.0204486
[114]	valid_0's binary_logloss: 0.0204774
[115]	valid_0's binary_logloss: 0.0204862
[116]	valid_0's binary_logloss: 0.0205355
[117]	valid_0's binary_logloss: 0.0206893
[118]	valid_0's binary_logloss: 0.0208139
[119]	valid_0's binary_logloss: 0.0208266
[120]	valid_0's binary_logloss: 0.0209643
[121]	valid_0's binary_logloss: 0.0208429
[122]	valid_0's binary_logloss: 0.0207182
[123]	valid_0's binary_logloss: 0.0206502
[124]	valid_0's binary_logloss: 0.0205775
[125]	valid_0's binary_logloss: 0.0205504
[126]	valid_0's binary_logloss: 0.0205607
[127]	valid_0's binary_logloss: 0.020599
[128]	valid_0's binary_logloss: 0.0205894
[129]	valid_0's binary_logloss: 0.0205852
[130]	valid_0's binary_logloss: 0.0205687
[131]	valid_0's binary_logloss: 0.0205333
[132]	valid_0's binary_logloss: 0.0205233
[133]	valid_0's binary_logloss: 0.0205165
[134]	valid_0's binary_logloss: 0.0206156
[135]	valid_0's binary_logloss: 0.0207058
[136]	valid_0's binary_logloss: 0.0206923
[137]	valid_0's binary_logloss: 0.020732
[138]	valid_0's binary_logloss: 0.0206649

Trening klas:  58%|█████▊    | 292/500 [35:00<18:42,  5.40s/klasa, klasa=class_292, F1_klasy=0.5217, F1_macro=0.7102, drzewa=108]




Trening klas:  59%|█████▊    | 293/500 [35:00<23:20,  6.77s/klasa, klasa=class_292, F1_klasy=0.5217, F1_macro=0.7102, drzewa=108]

[1]	valid_0's binary_logloss: 0.0335893
[2]	valid_0's binary_logloss: 0.0325303
[3]	valid_0's binary_logloss: 0.0317077
[4]	valid_0's binary_logloss: 0.0306717
[5]	valid_0's binary_logloss: 0.0298152
[6]	valid_0's binary_logloss: 0.029133
[7]	valid_0's binary_logloss: 0.0285592
[8]	valid_0's binary_logloss: 0.0280257
[9]	valid_0's binary_logloss: 0.0275572
[10]	valid_0's binary_logloss: 0.0271306
[11]	valid_0's binary_logloss: 0.026793
[12]	valid_0's binary_logloss: 0.0263616
[13]	valid_0's binary_logloss: 0.0260594
[14]	valid_0's binary_logloss: 0.0254638
[15]	valid_0's binary_logloss: 0.0251546
[16]	valid_0's binary_logloss: 0.0249381
[17]	valid_0's binary_logloss: 0.0246469
[18]	valid_0's binary_logloss: 0.0244308
[19]	valid_0's binary_logloss: 0.0241855
[20]	valid_0's binary_logloss: 0.0240003
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0238235
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0237671
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.0237104
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0234841
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.0232011
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.0230703
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.022907
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.0227682
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.0226345
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.022494
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.0224373
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.0224257
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.0223533
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.0223245
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.0223501
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.0223284
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.0223544
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.0223759
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.0224156
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.0224137
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.0224862
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.0225394
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.0225802
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.0225956
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.0226403
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.0227028
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.0227189
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.0226783
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.0225702
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.0225134
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.0224867
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.0224367
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.0220717
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.0220479
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.0219936
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.0219737
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.0219106
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.0219109
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.0219336
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.0219546
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.0219986
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.0220671
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.0221545
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.0221997
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.0223732
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.0222017
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.0220758
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.0219202
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.021907
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.0218966
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.0219592
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.0220343
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.0220642
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.0220622
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.0221026
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.0221127
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.0220405
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.0220132
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.0220683
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.0221842
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.0222795
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.0222229
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.0221787
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.022142
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.0221904
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.0222206
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.0222728
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.0222984
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.0223352
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.0224937
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.022553
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.0225193
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.0226209
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.0226581
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.0227613
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.0227658
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.0227894
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.0228307
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.0228759
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.0228985

Trening klas:  59%|█████▊    | 293/500 [35:05<23:20,  6.77s/klasa, klasa=class_293, F1_klasy=0.6885, F1_macro=0.7101, drzewa=70]




Trening klas:  59%|█████▉    | 294/500 [35:05<21:42,  6.32s/klasa, klasa=class_293, F1_klasy=0.6885, F1_macro=0.7101, drzewa=70]

[1]	valid_0's binary_logloss: 0.146858
[2]	valid_0's binary_logloss: 0.0931778
[3]	valid_0's binary_logloss: 0.0828109
[4]	valid_0's binary_logloss: 0.0769658
[5]	valid_0's binary_logloss: 0.0736262
[6]	valid_0's binary_logloss: 0.243216
[7]	valid_0's binary_logloss: 0.233462
[8]	valid_0's binary_logloss: 0.22693
[9]	valid_0's binary_logloss: 0.220188
[10]	valid_0's binary_logloss: 0.215408
[11]	valid_0's binary_logloss: 0.424424
[12]	valid_0's binary_logloss: 0.418475
[13]	valid_0's binary_logloss: 0.413361
[14]	valid_0's binary_logloss: 0.4085
[15]	valid_0's binary_logloss: 0.397301
[16]	valid_0's binary_logloss: 0.43938
[17]	valid_0's binary_logloss: 0.43289
[18]	valid_0's binary_logloss: 0.428281
[19]	valid_0's binary_logloss: 0.413304
[20]	valid_0's binary_logloss: 0.405154
[21]	valid_0's binary_logloss: 0.391677
[22]	valid_0's binary_logloss: 0.375025
[23]	valid_0's binary_logloss: 0.360242
[24]	valid_0's binary_logloss: 0.343949
[25]	valid_0's binary_logloss: 0.338906
[26]	valid_0's binary_logloss: 0.333535
[27]	valid_0's binary_logloss: 0.326283
[28]	valid_0's binary_logloss: 0.320578
[29]	valid_0's binary_logloss: 0.309741
[30]	valid_0's binary_logloss: 0.306614
[31]	valid_0's binary_logloss: 0.302453
[32]	valid_0's binary_logloss: 0.297972
[33]	valid_0's binary_logloss: 0.293035
[34]	valid_0's binary_logloss: 0.289965

Trening klas:  59%|█████▉    | 294/500 [35:09<21:42,  6.32s/klasa, klasa=class_294, F1_klasy=0.0261, F1_macro=0.7078, drzewa=5]




Trening klas:  59%|█████▉    | 295/500 [35:09<19:28,  5.70s/klasa, klasa=class_294, F1_klasy=0.0261, F1_macro=0.7078, drzewa=5]

[35]	valid_0's binary_logloss: 0.287187
[1]	valid_0's binary_logloss: 0.0175379
[2]	valid_0's binary_logloss: 0.016769
[3]	valid_0's binary_logloss: 0.0161262
[4]	valid_0's binary_logloss: 0.0155413
[5]	valid_0's binary_logloss: 0.0149256
[6]	valid_0's binary_logloss: 0.0155095
[7]	valid_0's binary_logloss: 0.0150867
[8]	valid_0's binary_logloss: 0.0146056
[9]	valid_0's binary_logloss: 0.0141987
[10]	valid_0's binary_logloss: 0.0136743
[11]	valid_0's binary_logloss: 0.0131915
[12]	valid_0's binary_logloss: 0.0126809
[13]	valid_0's binary_logloss: 0.0122169
[14]	valid_0's binary_logloss: 0.0118998
[15]	valid_0's binary_logloss: 0.0116082
[16]	valid_0's binary_logloss: 0.0113561
[17]	valid_0's binary_logloss: 0.0110935
[18]	valid_0's binary_logloss: 0.0108599
[19]	valid_0's binary_logloss: 0.0105311
[20]	valid_0's binary_logloss: 0.0103024
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0100524
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.00987579
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.00966738
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.00931158
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.00910472
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.00891415
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.00872351
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.00859905
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.00830656
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.00803631
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.00791078
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.00773914
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.00760299
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.00747251
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.00735719
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.00727983
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.00723742
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.00714529
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.00709837
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.00705282
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.00686776
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.00669619
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.00653819
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.00638424
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.00623623
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.00621776
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.00621267
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.00617353
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.00613321
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.00610427
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.00607722
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.0060463
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.00604804
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.00603793
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.00594317
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.00584143
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.00577423
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.00567935
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.00557832
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.00556234
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.00547162
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.0053917
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.00535738
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.0052975
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.00521002
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.00520073
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.00515909
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.00516285
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.00515416
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.00513967
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.0051493
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.00517503
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.00520548
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.00516022
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.00516291
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.00518007
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.00510663
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.00504753
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.00503601
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.00503413
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.00495836
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.00496379
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.00497249
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.00498048
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.00500474
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.00499069
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.00499584
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.00500416
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.00502655
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.00504541
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.004993
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.00499903
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.00502079
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.0050003
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.00500281
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.00498142
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.00493847
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.00500864
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.00502011
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.0050322
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.00501277
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.00498806
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.00502052
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.00496959
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.0049475
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.00487763
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.00487758
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.00480392
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.00483391
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.00484778
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.0048406
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 0.00484648
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 0.00487565
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 0.00489469
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 0.00488967
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[116]	valid_0's binary_logloss: 0.00488994
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[117]	valid_0's binary_logloss: 0.00490599
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[118]	valid_0's binary_logloss: 0.00493298
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[119]	valid_0's binary_logloss: 0.00494582
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[120]	valid_0's binary_logloss: 0.00495794
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[121]	valid_0's binary_logloss: 0.00498569
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[122]	valid_0's binary_logloss: 0.00496826
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[123]	valid_0's binary_logloss: 0.00495495
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[124]	valid_0's binary_logloss: 0.00494684
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[125]	valid_0's binary_logloss: 0.0049395
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[126]	valid_0's binary_logloss: 0.00493684
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[127]	valid_0's binary_logloss: 0.00492869
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[128]	valid_0's binary_logloss: 0.00490398
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[129]	valid_0's binary_logloss: 0.00488341
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[130]	valid_0's binary_logloss: 0.004945
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[131]	valid_0's binary_logloss: 0.0049501
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[132]	valid_0's binary_logloss: 0.0049804
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[133]	valid_0's binary_logloss: 0.00499742
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[134]	valid_0's binary_logloss: 0.00501094
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[135]	valid_0's binary_logloss: 0.00502451
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[136]	valid_0's binary_logloss: 0.00500399
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

Trening klas:  59%|█████▉    | 295/500 [35:15<19:28,  5.70s/klasa, klasa=class_295, F1_klasy=0.6471, F1_macro=0.7076, drzewa=108]




Trening klas:  59%|█████▉    | 296/500 [35:15<19:09,  5.64s/klasa, klasa=class_295, F1_klasy=0.6471, F1_macro=0.7076, drzewa=108]

[137]	valid_0's binary_logloss: 0.0050487
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[138]	valid_0's binary_logloss: 0.00506883
[1]	valid_0's binary_logloss: 0.0350555
[2]	valid_0's binary_logloss: 0.0326485
[3]	valid_0's binary_logloss: 0.0307898
[4]	valid_0's binary_logloss: 0.0292441
[5]	valid_0's binary_logloss: 0.0280241
[6]	valid_0's binary_logloss: 0.0271305
[7]	valid_0's binary_logloss: 0.0262405
[8]	valid_0's binary_logloss: 0.0253974
[9]	valid_0's binary_logloss: 0.0247143
[10]	valid_0's binary_logloss: 0.0240623
[11]	valid_0's binary_logloss: 0.0234065
[12]	valid_0's binary_logloss: 0.02295
[13]	valid_0's binary_logloss: 0.0225516
[14]	valid_0's binary_logloss: 0.022179
[15]	valid_0's binary_logloss: 0.0219161
[16]	valid_0's binary_logloss: 0.0216464
[17]	valid_0's binary_logloss: 0.0214287
[18]	valid_0's binary_logloss: 0.0211221
[19]	valid_0's binary_logloss: 0.0206028
[20]	valid_0's binary_logloss: 0.0204025
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0201744
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0198602
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.0195456
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0191937
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.0188866
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.0187341
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.0185821
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.018333
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.0181843
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.0180652
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.0178847
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.0177359
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.0176177
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.0175661
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.0173598
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.0170978
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.016866
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.0165539
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.0164033
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.0161574
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.0160012
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.015701
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.0154981
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.0152785
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.0150596
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.0149467
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.0148441
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.0147512
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.014671
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.0145459
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.0144048
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.0143122
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.0141966
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.0141827
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.0140686
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.0140283
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.0139117
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.013772
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.0136749
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.0136582
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.0136247
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.0135339
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.0135835
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.0136332
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.0136562
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.0136057
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.0135615
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.0135605
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.0134867
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.0135013
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.0134489
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.0133882
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.0134811
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.0134885
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.0135356
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.0136021
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.0135959
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.0135177
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.0134743
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.0134114
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.0134551
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.0134899
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.0134421
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.0134829
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.0135412
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.0135207
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.0135494
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.013503
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.0135424
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.0135175
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.0134653
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.0134865
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.0134505
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.0133943
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.0134297
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.0133359
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.0133337
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.0133311
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.013381
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.0133932
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.0134158
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.0134779
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.013402
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.013387
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.0133439
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.0134579
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.0135695
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.0135555
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.0136069
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.0135764
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.0136957
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 0.0137587
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 0.0138716
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 0.0139811
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 0.0140112
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[116]	valid_0's binary_logloss: 0.0141115
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[117]	valid_0's binary_logloss: 0.0141844
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[118]	valid_0's binary_logloss: 0.0141904
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[119]	valid_0's binary_logloss: 0.014276
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[120]	valid_0's binary_logloss: 0.0143174
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[121]	valid_0's binary_logloss: 0.0143436
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[122]	valid_0's binary_logloss: 0.0144011
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[123]	valid_0's binary_logloss: 0.0143819
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[124]	valid_0's binary_logloss: 0.0144154
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[125]	valid_0's binary_logloss: 0.0144766
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[126]	valid_0's binary_logloss: 0.0145636
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[127]	valid_0's binary_logloss: 0.0145254
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[128]	valid_0's binary_logloss: 0.0146059

Trening klas:  59%|█████▉    | 296/500 [35:19<19:09,  5.64s/klasa, klasa=class_296, F1_klasy=0.6667, F1_macro=0.7075, drzewa=98]




Trening klas:  59%|█████▉    | 297/500 [35:19<18:06,  5.35s/klasa, klasa=class_296, F1_klasy=0.6667, F1_macro=0.7075, drzewa=98]

[1]	valid_0's binary_logloss: 0.015264
[2]	valid_0's binary_logloss: 0.0147508
[3]	valid_0's binary_logloss: 0.0142508
[4]	valid_0's binary_logloss: 0.0138173
[5]	valid_0's binary_logloss: 0.013331
[6]	valid_0's binary_logloss: 0.0135869
[7]	valid_0's binary_logloss: 0.0131628
[8]	valid_0's binary_logloss: 0.0127696
[9]	valid_0's binary_logloss: 0.0123662
[10]	valid_0's binary_logloss: 0.0120481
[11]	valid_0's binary_logloss: 0.0115817
[12]	valid_0's binary_logloss: 0.0112307
[13]	valid_0's binary_logloss: 0.0109153
[14]	valid_0's binary_logloss: 0.010432
[15]	valid_0's binary_logloss: 0.0100146
[16]	valid_0's binary_logloss: 0.00979997
[17]	valid_0's binary_logloss: 0.00959654
[18]	valid_0's binary_logloss: 0.00926198
[19]	valid_0's binary_logloss: 0.00904458
[20]	valid_0's binary_logloss: 0.00890406
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.00869351
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.00840624
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.00819525
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.00800896
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.00766502
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.007506
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.00719213
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.00710155
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.00692457
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.00668532
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.00655864
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.0064704
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.00636808
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.00628604
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.00615725
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.0060904
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.0060306
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.00597268
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.00590728
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.00589216
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.00574003
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.00555334
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.00539273
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.00525255
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.00519682
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.00515487
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.00511727
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.00509015
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.00507918
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.00505916
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.00500858
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.00498728
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.00500548
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.00502584
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.00488672
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.00477317
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.00476895
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.00477965
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.00476784
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.00476859
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.00476472
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.00463357
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.00466346
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.00454681
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.00443766
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.00434511
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.00424718
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.00416223
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.00408507
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.00399689
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.00400244
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.00401377
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.00404315
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.0040629
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.00405778
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.0040413
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.00400151
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.00396227
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.00394743
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.00395135
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.00395839
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.00397326
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.00399962
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.00399152
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.00398324
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.00397681
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.00399349
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.00398125
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.00397709
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.00398425
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.00394623
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.00400195
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.00404866
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.0040835
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.0040557
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.00407639
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.0040727
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.00407536
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.00410992
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.00409999
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.00413595
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.0041568
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.00420555
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.0042485
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.004296
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.0043209
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.0043547
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.00441719
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.00446852
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.00450191
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.0044815
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 0.00444395
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 0.00443619
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 0.00447319
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 0.00450655
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[116]	valid_0's binary_logloss: 0.00455246
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[117]	valid_0's binary_logloss: 0.00457249
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[118]	valid_0's binary_logloss: 0.00460344
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

Trening klas:  59%|█████▉    | 297/500 [35:24<18:06,  5.35s/klasa, klasa=class_297, F1_klasy=0.6875, F1_macro=0.7074, drzewa=91]




Trening klas:  60%|█████▉    | 298/500 [35:24<17:18,  5.14s/klasa, klasa=class_297, F1_klasy=0.6875, F1_macro=0.7074, drzewa=91]

[119]	valid_0's binary_logloss: 0.00463397
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[120]	valid_0's binary_logloss: 0.00463134
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[121]	valid_0's binary_logloss: 0.00464223
[1]	valid_0's binary_logloss: 0.011354
[2]	valid_0's binary_logloss: 0.0108344
[3]	valid_0's binary_logloss: 0.0103928
[4]	valid_0's binary_logloss: 0.0100125
[5]	valid_0's binary_logloss: 0.00963652
[6]	valid_0's binary_logloss: 0.00944975
[7]	valid_0's binary_logloss: 0.00907131
[8]	valid_0's binary_logloss: 0.0087184
[9]	valid_0's binary_logloss: 0.00838583
[10]	valid_0's binary_logloss: 0.00803554
[11]	valid_0's binary_logloss: 0.00771862
[12]	valid_0's binary_logloss: 0.0074163
[13]	valid_0's binary_logloss: 0.00713425
[14]	valid_0's binary_logloss: 0.00686667
[15]	valid_0's binary_logloss: 0.00663509
[16]	valid_0's binary_logloss: 0.00635601
[17]	valid_0's binary_logloss: 0.00609529
[18]	valid_0's binary_logloss: 0.00585932
[19]	valid_0's binary_logloss: 0.00562806
[20]	valid_0's binary_logloss: 0.00542001
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.00525315
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.00508313
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.00492049
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.00477737
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.00464443
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.00448561
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.00433569
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.00417671
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.00402496
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.00388021
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.0037631
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.00367951
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.00357783
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.00347733
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.00336244
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.00328893
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.00322701
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.00315802
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.00307122
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.0029829
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.00289503
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.00282736
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.00277667
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.00269889
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.00265484
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.0026109
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.00256357
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.00251826
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.00247155
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.00243044
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.00239924
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.00234465
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.00230487
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.00227227
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.0022365
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.00218491
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.00210145
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.00202366
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.00196573
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.0019457
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.00189734
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.00187824
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.00184961
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.00180954
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.00177017
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.00174883
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.00171314
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.00169399
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.00165972
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.00163981
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.00162686
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.00160093
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.00159007
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.00156651
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.00154727
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.0015358
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.00150979
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.00148427
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.00146106
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.00145043
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.00142645
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.00141784
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.00141073
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.00140711
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.00140275
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.00139916
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.00138283
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.00136534
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.00134725
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.00133918
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.00130306
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.00127033
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.00124199
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.00121433
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.00119717
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.00118119
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.00116589
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.00115174
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.00114404
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.00114497
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.00115068
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.00114158
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.0011303
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.00111708
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.00110642
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.00109855
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.00109179
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.00107937
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.00107886
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.0010895
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.00108108
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 0.00106997
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 0.00106673
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 0.00106979
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 0.00106869
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[116]	valid_0's binary_logloss: 0.00106388
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[117]	valid_0's binary_logloss: 0.00106421
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[118]	valid_0's binary_logloss: 0.00105483
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[119]	valid_0's binary_logloss: 0.00103637
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[120]	valid_0's binary_logloss: 0.00102622
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[121]	valid_0's binary_logloss: 0.00101774
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[122]	valid_0's binary_logloss: 0.00102134
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[123]	valid_0's binary_logloss: 0.00101343
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[124]	valid_0's binary_logloss: 0.00100949
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[125]	valid_0's binary_logloss: 0.00100761
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[126]	valid_0's binary_logloss: 0.000989871
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[127]	valid_0's binary_logloss: 0.000980903
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[128]	valid_0's binary_logloss: 0.000982682
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[129]	valid_0's binary_logloss: 0.000982407
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[130]	valid_0's binary_logloss: 0.000982369
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[131]	valid_0's binary_logloss: 0.000985371
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[132]	valid_0's binary_logloss: 0.000971275
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[133]	valid_0's binary_logloss: 0.000967093
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[134]	valid_0's binary_logloss: 0.000954344
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[135]	valid_0's binary_logloss: 0.000956239
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[136]	valid_0's binary_logloss: 0.000943931
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[137]	valid_0's binary_logloss: 0.000941036
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[138]	valid_0's binary_logloss: 0.000927983
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[139]	valid_0's binary_logloss: 0.000913822
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[140]	valid_0's binary_logloss: 0.000911402
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[141]	valid_0's binary_logloss: 0.000903514
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[142]	valid_0's binary_logloss: 0.000887709
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[143]	valid_0's binary_logloss: 0.000888304
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[144]	valid_0's binary_logloss: 0.000881071
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[145]	valid_0's binary_logloss: 0.000874258
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[146]	valid_0's binary_logloss: 0.000882861
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[147]	valid_0's binary_logloss: 0.000885429
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[148]	valid_0's binary_logloss: 0.000892993
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[149]	valid_0's binary_logloss: 0.000890942
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[150]	valid_0's binary_logloss: 0.000888177
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[151]	valid_0's binary_logloss: 0.000888991
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[152]	valid_0's binary_logloss: 0.000897692
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[153]	valid_0's binary_logloss: 0.000901813
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[154]	valid_0's binary_logloss: 0.000907246
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[155]	valid_0's binary_logloss: 0.000908227
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[156]	valid_0's binary_logloss: 0.00090801
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[157]	valid_0's binary_logloss: 0.000908227
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[158]	valid_0's binary_logloss: 0.000912199
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[159]	valid_0's binary_logloss: 0.000905089
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[160]	valid_0's binary_logloss: 0.000905795
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[161]	valid_0's binary_logloss: 0.000897114
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[162]	valid_0's binary_logloss: 0.000890776
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[163]	valid_0's binary_logloss: 0.000886659
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[164]	valid_0's binary_logloss: 0.000882972
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[165]	valid_0's binary_logloss: 0.000883391
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[166]	valid_0's binary_logloss: 0.000888406
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[167]	valid_0's binary_logloss: 0.000889597
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[168]	valid_0's binary_logloss: 0.000894898
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[169]	valid_0's binary_logloss: 0.000901072
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[170]	valid_0's binary_logloss: 0.000908645
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[171]	valid_0's binary_logloss: 0.000913945
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[172]	valid_0's binary_logloss: 0.000919245
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[173]	valid_0's binary_logloss: 0.000913883
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[174]	valid_0's binary_logloss: 0.000902972

Trening klas:  60%|█████▉    | 298/500 [35:29<17:18,  5.14s/klasa, klasa=class_298, F1_klasy=0.8750, F1_macro=0.7079, drzewa=145]




Trening klas:  60%|█████▉    | 299/500 [35:29<17:02,  5.08s/klasa, klasa=class_298, F1_klasy=0.8750, F1_macro=0.7079, drzewa=145]

[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[175]	valid_0's binary_logloss: 0.000903612
[1]	valid_0's binary_logloss: 0.0144294
[2]	valid_0's binary_logloss: 0.0141948
[3]	valid_0's binary_logloss: 0.0139783
[4]	valid_0's binary_logloss: 0.0137707
[5]	valid_0's binary_logloss: 0.0135788
[6]	valid_0's binary_logloss: 0.0134163
[7]	valid_0's binary_logloss: 0.0132317
[8]	valid_0's binary_logloss: 0.0130911
[9]	valid_0's binary_logloss: 0.0129333
[10]	valid_0's binary_logloss: 0.0127872
[11]	valid_0's binary_logloss: 0.0125799
[12]	valid_0's binary_logloss: 0.0124879
[13]	valid_0's binary_logloss: 0.0123248
[14]	valid_0's binary_logloss: 0.0121889
[15]	valid_0's binary_logloss: 0.0120736
[16]	valid_0's binary_logloss: 0.0119745
[17]	valid_0's binary_logloss: 0.0118308
[18]	valid_0's binary_logloss: 0.0116722
[19]	valid_0's binary_logloss: 0.0116318
[20]	valid_0's binary_logloss: 0.0115579
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0115458
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0115154
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.0114977
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0113507
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.0112348
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.011242
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.0112466
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.0110017
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.0109895
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.0108528
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.0108406
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.0108263
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.0107876
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.0107933
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.0108033
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.0107692
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.010787
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.0107842
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.0108024
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.0107993
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.0107047
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.0106661
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.0106277
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.0106606
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.0104803
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.0105373
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.0101808
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.010226
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.0102707
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.0101857
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.00998166
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.0098046
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.00987484
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.00976119
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.00982152
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.00978356
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.0097959
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.0098217
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.00987155
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.00989986
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.00994668
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.00998246
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.0100182
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.00998134
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.0099414
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.00971383
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.00965775
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.00961132
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.00953122
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.00954375
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.0095615
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.00961418
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.0096138
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.00961338
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.00967409
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.00954263
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.00940844
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.00930302
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.0092121
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.0091365
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.00913073
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.00915319
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.00917941
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.00923084
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.00925304
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.00929111
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.00931295
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.00931407
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.00935828
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.00935646
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.00940528
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.0094491
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.0094759
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.0095297
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.00958063
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.00965051
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.0096565
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.00972861
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.00977239
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.0098162
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.00987604
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.00995154
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.00994978
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.00998469
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.0100264
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.0100405
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.0100649
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.0100375
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.0100338
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.00999914
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

Trening klas:  60%|█████▉    | 299/500 [35:33<17:02,  5.08s/klasa, klasa=class_299, F1_klasy=0.8844, F1_macro=0.7085, drzewa=81]




Trening klas:  60%|██████    | 300/500 [35:33<15:32,  4.66s/klasa, klasa=class_299, F1_klasy=0.8844, F1_macro=0.7085, drzewa=81]

[111]	valid_0's binary_logloss: 0.0100318
[1]	valid_0's binary_logloss: 0.0112723
[2]	valid_0's binary_logloss: 0.0107258
[3]	valid_0's binary_logloss: 0.010241
[4]	valid_0's binary_logloss: 0.00975171
[5]	valid_0's binary_logloss: 0.0092749
[6]	valid_0's binary_logloss: 0.0101849
[7]	valid_0's binary_logloss: 0.00965691
[8]	valid_0's binary_logloss: 0.00915524
[9]	valid_0's binary_logloss: 0.00868345
[10]	valid_0's binary_logloss: 0.00824959
[11]	valid_0's binary_logloss: 0.00784751
[12]	valid_0's binary_logloss: 0.0074687
[13]	valid_0's binary_logloss: 0.00708737
[14]	valid_0's binary_logloss: 0.00672686
[15]	valid_0's binary_logloss: 0.00638688
[16]	valid_0's binary_logloss: 0.00609629
[17]	valid_0's binary_logloss: 0.00581508
[18]	valid_0's binary_logloss: 0.00556281
[19]	valid_0's binary_logloss: 0.00529948
[20]	valid_0's binary_logloss: 0.00506816
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.00483666
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.00463167
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.00443931
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.00425918
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.00408153
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.0038973
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.0037183
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.00354191
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.00338671
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.00323806
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.00308618
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.00296097
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.00282806
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.00269555
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.00256862
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.00245226
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.00233647
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.00224264
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.00213868
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.00203731
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.00195962
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.00188657
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.00181724
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.00173454
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.00165591
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.00157409
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.00149914
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.001428
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.00136047
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.00127916
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.00121917
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.0011629
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.00110832
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.00105732
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.00100821
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.000959799
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.000913761
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.000870534
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.000830144
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.000791688
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.000766747
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.000731059
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.000696813
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.000664916
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.000634519
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.000604952
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.000576863
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.000550293
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.000523462
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.000499695
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.000475162
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.000454635
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.000432615
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.000412057
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.000392561
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.000376118
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.000359766
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.00034209
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.000328172
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.000313448
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.000299436
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.000285919
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.000271739
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.000260504
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.000249364
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.000238008
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.000227711
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.000218092
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.000208783
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.000200052
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.000191605
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.000182774
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.000174274
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.000165832
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.000158457
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.000149336
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.000141867
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.00013481
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.000128202
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.000122108
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.000116289
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.000113041
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.000108166
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.000103451
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 9.86926e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 9.53103e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 9.26868e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 9.07728e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 8.86183e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 8.48988e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 8.29279e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 8.1424e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 7.96825e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 7.62724e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 7.32091e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[116]	valid_0's binary_logloss: 7.04701e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[117]	valid_0's binary_logloss: 6.69493e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[118]	valid_0's binary_logloss: 6.33452e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[119]	valid_0's binary_logloss: 6.01856e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[120]	valid_0's binary_logloss: 5.74314e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[121]	valid_0's binary_logloss: 5.47481e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[122]	valid_0's binary_logloss: 5.17155e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[123]	valid_0's binary_logloss: 4.90741e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[124]	valid_0's binary_logloss: 4.6988e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[125]	valid_0's binary_logloss: 4.47427e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[126]	valid_0's binary_logloss: 4.22816e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[127]	valid_0's binary_logloss: 3.99867e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[128]	valid_0's binary_logloss: 3.77303e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[129]	valid_0's binary_logloss: 3.5829e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[130]	valid_0's binary_logloss: 3.40278e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[131]	valid_0's binary_logloss: 3.35822e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[132]	valid_0's binary_logloss: 3.26145e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[133]	valid_0's binary_logloss: 3.22351e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[134]	valid_0's binary_logloss: 3.17449e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[135]	valid_0's binary_logloss: 3.08894e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[136]	valid_0's binary_logloss: 2.93928e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[137]	valid_0's binary_logloss: 2.79697e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[138]	valid_0's binary_logloss: 2.69467e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[139]	valid_0's binary_logloss: 2.57866e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[140]	valid_0's binary_logloss: 2.50067e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[141]	valid_0's binary_logloss: 2.46355e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[142]	valid_0's binary_logloss: 2.40606e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[143]	valid_0's binary_logloss: 2.33938e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[144]	valid_0's binary_logloss: 2.30128e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[145]	valid_0's binary_logloss: 2.22656e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[146]	valid_0's binary_logloss: 2.14712e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[147]	valid_0's binary_logloss: 2.069e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[148]	valid_0's binary_logloss: 1.98747e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[149]	valid_0's binary_logloss: 1.88327e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[150]	valid_0's binary_logloss: 1.80211e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[151]	valid_0's binary_logloss: 1.75546e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[152]	valid_0's binary_logloss: 1.68325e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[153]	valid_0's binary_logloss: 1.63937e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[154]	valid_0's binary_logloss: 1.63035e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[155]	valid_0's binary_logloss: 1.58749e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[156]	valid_0's binary_logloss: 1.52533e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[157]	valid_0's binary_logloss: 1.47262e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[158]	valid_0's binary_logloss: 1.42561e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[159]	valid_0's binary_logloss: 1.37542e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[160]	valid_0's binary_logloss: 1.32275e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[161]	valid_0's binary_logloss: 1.27338e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[162]	valid_0's binary_logloss: 1.234e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[163]	valid_0's binary_logloss: 1.21673e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[164]	valid_0's binary_logloss: 1.19224e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[165]	valid_0's binary_logloss: 1.1513e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[166]	valid_0's binary_logloss: 1.11105e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[167]	valid_0's binary_logloss: 1.10306e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[168]	valid_0's binary_logloss: 1.08458e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[169]	valid_0's binary_logloss: 1.06502e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[170]	valid_0's binary_logloss: 1.03854e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[171]	valid_0's binary_logloss: 9.99249e-06
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[172]	valid_0's binary_logloss: 9.34338e-06
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[173]	valid_0's binary_logloss: 8.83356e-06
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[174]	valid_0's binary_logloss: 8.53046e-06
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[175]	valid_0's binary_logloss: 8.14462e-06
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[176]	valid_0's binary_logloss: 7.98348e-06
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[177]	valid_0's binary_logloss: 7.79988e-06
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[178]	valid_0's binary_logloss: 7.74992e-06
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[179]	valid_0's binary_logloss: 7.6394e-06
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[180]	valid_0's binary_logloss: 7.56055e-06
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[181]	valid_0's binary_logloss: 7.4303e-06
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

Trening klas:  60%|██████    | 300/500 [35:41<15:32,  4.66s/klasa, klasa=class_300, F1_klasy=0.0000, F1_macro=0.7062, drzewa=300]




Trening klas:  60%|██████    | 301/500 [35:41<19:26,  5.86s/klasa, klasa=class_300, F1_klasy=0.0000, F1_macro=0.7062, drzewa=300]

[294]	valid_0's binary_logloss: 2.48787e-06
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[295]	valid_0's binary_logloss: 2.45995e-06
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[296]	valid_0's binary_logloss: 2.4598e-06
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[297]	valid_0's binary_logloss: 2.43739e-06
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[298]	valid_0's binary_logloss: 2.43538e-06
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[299]	valid_0's binary_logloss: 2.41497e-06
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[300]	valid_0's binary_logloss: 2.3972e-06
[1]	valid_0's binary_logloss: 0.0150154
[2]	valid_0's binary_logloss: 0.0140825
[3]	valid_0's binary_logloss: 0.0135003
[4]	valid_0's binary_logloss: 0.013041
[5]	valid_0's binary_logloss: 0.0126861
[6]	valid_0's binary_logloss: 0.0123671
[7]	valid_0's binary_logloss: 0.0120801
[8]	valid_0's binary_logloss: 0.0118232
[9]	valid_0's binary_logloss: 0.0115933
[10]	valid_0's binary_logloss: 0.0113946
[11]	valid_0's binary_logloss: 0.0112065
[12]	valid_0's binary_logloss: 0.0110268
[13]	valid_0's binary_logloss: 0.01087
[14]	valid_0's binary_logloss: 0.0107258
[15]	valid_0's binary_logloss: 0.0105887
[16]	valid_0's binary_logloss: 0.0104769
[17]	valid_0's binary_logloss: 0.0103755
[18]	valid_0's binary_logloss: 0.0102856
[19]	valid_0's binary_logloss: 0.0101937
[20]	valid_0's binary_logloss: 0.0101114
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0100488
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.00990916
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.00983348
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.00971423
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.00967869
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.00960017
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.00953236
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.00949362
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.00947734
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.00939361
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.009359
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.00915752
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.00910671
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.00909533
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.00909175
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.00910384
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.00908375
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.00906984
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.00893506
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.00891662
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.00894054
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.00891413
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.00885613
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.0088572
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.0087768
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.00879272
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.00882656
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.00885797
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.00888285
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.00890357
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.00892759
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.00897906
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.00903288
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.00904298
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.00908612
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.00909216
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.00913525
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.00916895
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.0091388
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.00910936
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.00915519
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.0091985
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.00920941
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.00920954
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.0092061
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.00925758
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.00931173
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.00935963
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.00933936
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.00936282
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.00941083
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.00946119
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.00950579
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.00953951
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.00951428

Trening klas:  60%|██████    | 301/500 [35:45<19:26,  5.86s/klasa, klasa=class_301, F1_klasy=0.9212, F1_macro=0.7069, drzewa=45]




Trening klas:  60%|██████    | 302/500 [35:45<16:49,  5.10s/klasa, klasa=class_301, F1_klasy=0.9212, F1_macro=0.7069, drzewa=45]

[1]	valid_0's binary_logloss: 0.0234302
[2]	valid_0's binary_logloss: 0.0228057
[3]	valid_0's binary_logloss: 0.0221183
[4]	valid_0's binary_logloss: 0.0213822
[5]	valid_0's binary_logloss: 0.0207383
[6]	valid_0's binary_logloss: 0.0209934
[7]	valid_0's binary_logloss: 0.0204546
[8]	valid_0's binary_logloss: 0.0198952
[9]	valid_0's binary_logloss: 0.0193116
[10]	valid_0's binary_logloss: 0.0188203
[11]	valid_0's binary_logloss: 0.0182807
[12]	valid_0's binary_logloss: 0.0177916
[13]	valid_0's binary_logloss: 0.0172907
[14]	valid_0's binary_logloss: 0.0169137
[15]	valid_0's binary_logloss: 0.0164485
[16]	valid_0's binary_logloss: 0.0160766
[17]	valid_0's binary_logloss: 0.015635
[18]	valid_0's binary_logloss: 0.0150443
[19]	valid_0's binary_logloss: 0.0147178
[20]	valid_0's binary_logloss: 0.0144618
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0141122
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.013705
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.0134859
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0133157
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.012939
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.0126767
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.0124994
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.0122907
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.0121371
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.0118718
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.0115677
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.0112069
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.0109821
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.0107947
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.0105182
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.0103328
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.0100643
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.00988168
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.0097567
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.00955539
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.00937933
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.00918812
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.00907218
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.00898078
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.00885895
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.00877232
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.00870062
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.00867609
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.00860613
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.00856508
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.00841224
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.0083486
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.00822092
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.00813007
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.00802782
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.00791152
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.00778778
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.00767342
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.00755253
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.00741567
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.0074121
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.00728567
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.00721376
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.00710728
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.00706743
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.00697269
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.00695547
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.00684606
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.00680002
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.00672648
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.00665101
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.00658287
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.00649145
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.00643171
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.006365
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.00626502
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.00622935
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.00618746
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.00613642
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.00605961
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.00600088
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.00594224
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.00589606
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.00583265
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.00579593
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.00577446
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.005716
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.0056956
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.0056815
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.00565712
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.00571462
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.00565444
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.00567278
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.00565147
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.00559422
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.00558503
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.00560375
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.00561126
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.00560994
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.00562831
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.00562286
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.00563759
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.00563643
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.0056048
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.00558461
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.00558587
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.00560326
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.00560707
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.00562308
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.0056128
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.00565171
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 0.00564869
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 0.00562773
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 0.0056378
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 0.00566701
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[116]	valid_0's binary_logloss: 0.00569162
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[117]	valid_0's binary_logloss: 0.00570315
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[118]	valid_0's binary_logloss: 0.00571568
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[119]	valid_0's binary_logloss: 0.00569894
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[120]	valid_0's binary_logloss: 0.00571119
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[121]	valid_0's binary_logloss: 0.00569251
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[122]	valid_0's binary_logloss: 0.00566417
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[123]	valid_0's binary_logloss: 0.00566488
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[124]	valid_0's binary_logloss: 0.0056579
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[125]	valid_0's binary_logloss: 0.00564796
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[126]	valid_0's binary_logloss: 0.00563677
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[127]	valid_0's binary_logloss: 0.00563888
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[128]	valid_0's binary_logloss: 0.00564967
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[129]	valid_0's binary_logloss: 0.00565153
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[130]	valid_0's binary_logloss: 0.00567256
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[131]	valid_0's binary_logloss: 0.00563401
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[132]	valid_0's binary_logloss: 0.00565697
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[133]	valid_0's binary_logloss: 0.00568951
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[134]	valid_0's binary_logloss: 0.00567773
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[135]	valid_0's binary_logloss: 0.00568506

Trening klas:  60%|██████    | 302/500 [35:51<16:49,  5.10s/klasa, klasa=class_302, F1_klasy=0.0000, F1_macro=0.7046, drzewa=105]




Trening klas:  61%|██████    | 303/500 [35:51<18:21,  5.59s/klasa, klasa=class_302, F1_klasy=0.0000, F1_macro=0.7046, drzewa=105]

[1]	valid_0's binary_logloss: 0.0335665
[2]	valid_0's binary_logloss: 0.0302359
[3]	valid_0's binary_logloss: 0.0282147
[4]	valid_0's binary_logloss: 0.0262636
[5]	valid_0's binary_logloss: 0.024601
[6]	valid_0's binary_logloss: 0.0254937
[7]	valid_0's binary_logloss: 0.0242157
[8]	valid_0's binary_logloss: 0.0230842
[9]	valid_0's binary_logloss: 0.0221296
[10]	valid_0's binary_logloss: 0.0210817
[11]	valid_0's binary_logloss: 0.0202086
[12]	valid_0's binary_logloss: 0.0194746
[13]	valid_0's binary_logloss: 0.0186702
[14]	valid_0's binary_logloss: 0.0178275
[15]	valid_0's binary_logloss: 0.0171755
[16]	valid_0's binary_logloss: 0.016472
[17]	valid_0's binary_logloss: 0.0158175
[18]	valid_0's binary_logloss: 0.01514
[19]	valid_0's binary_logloss: 0.0146199
[20]	valid_0's binary_logloss: 0.0140941
[21]	valid_0's binary_logloss: 0.0135524
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0130842
[23]	valid_0's binary_logloss: 0.0126242
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0121641
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.0117818
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.0114649
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.0110568
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.0107148
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.0104343
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.0101061
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.0097172
[32]	valid_0's binary_logloss: 0.00938913
[33]	valid_0's binary_logloss: 0.00896482
[34]	valid_0's binary_logloss: 0.00868774
[35]	valid_0's binary_logloss: 0.00836418
[36]	valid_0's binary_logloss: 0.00812548
[37]	valid_0's binary_logloss: 0.00791787
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.00773599
[39]	valid_0's binary_logloss: 0.00756885
[40]	valid_0's binary_logloss: 0.00737305
[41]	valid_0's binary_logloss: 0.00718752
[42]	valid_0's binary_logloss: 0.00702527
[43]	valid_0's binary_logloss: 0.00685094
[44]	valid_0's binary_logloss: 0.00663557
[45]	valid_0's binary_logloss: 0.00650118
[46]	valid_0's binary_logloss: 0.00638612
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.00625951
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.00612181
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.00605265
[50]	valid_0's binary_logloss: 0.00598071
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.00589613
[52]	valid_0's binary_logloss: 0.00580138
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.00578266
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.00567791
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.00556183
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.00545434
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.00533884
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.00524327
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.00511539
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.00501476
[61]	valid_0's binary_logloss: 0.00494235
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.00483934
[63]	valid_0's binary_logloss: 0.00479267
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.00476051
[65]	valid_0's binary_logloss: 0.00473235
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.00472687
[67]	valid_0's binary_logloss: 0.00471425
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.0046986
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.00465159
[70]	valid_0's binary_logloss: 0.00463908
[71]	valid_0's binary_logloss: 0.00460611
[72]	valid_0's binary_logloss: 0.00459098
[73]	valid_0's binary_logloss: 0.00453433
[74]	valid_0's binary_logloss: 0.00447954
[75]	valid_0's binary_logloss: 0.00443665
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.00441318
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.00441197
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.00437713
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.00437833
[80]	valid_0's binary_logloss: 0.00439302
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.00432668
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.00425562
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.00419583
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.0041487
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.00408374
[86]	valid_0's binary_logloss: 0.00403088
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.00398026
[88]	valid_0's binary_logloss: 0.00395697
[89]	valid_0's binary_logloss: 0.00395624
[90]	valid_0's binary_logloss: 0.00389811
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.00386413
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.00386561
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.00383639
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.00379267
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.00378747
[96]	valid_0's binary_logloss: 0.00382002
[97]	valid_0's binary_logloss: 0.00380795
[98]	valid_0's binary_logloss: 0.00380993
[99]	valid_0's binary_logloss: 0.00383021
[100]	valid_0's binary_logloss: 0.00386864
[101]	valid_0's binary_logloss: 0.00383637
[102]	valid_0's binary_logloss: 0.0038233
[103]	valid_0's binary_logloss: 0.00382117
[104]	valid_0's binary_logloss: 0.00381588
[105]	valid_0's binary_logloss: 0.00376078
[106]	valid_0's binary_logloss: 0.00373809
[107]	valid_0's binary_logloss: 0.00370016
[108]	valid_0's binary_logloss: 0.00370191
[109]	valid_0's binary_logloss: 0.00369855
[110]	valid_0's binary_logloss: 0.00368755
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.00367892
[112]	valid_0's binary_logloss: 0.0036751
[113]	valid_0's binary_logloss: 0.00368963
[114]	valid_0's binary_logloss: 0.00369504
[115]	valid_0's binary_logloss: 0.00371512
[116]	valid_0's binary_logloss: 0.00372659
[117]	valid_0's binary_logloss: 0.0037707
[118]	valid_0's binary_logloss: 0.00374672
[119]	valid_0's binary_logloss: 0.00373459
[120]	valid_0's binary_logloss: 0.00371205
[121]	valid_0's binary_logloss: 0.00368093
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[122]	valid_0's binary_logloss: 0.00364552
[123]	valid_0's binary_logloss: 0.00364226
[124]	valid_0's binary_logloss: 0.00361723
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[125]	valid_0's binary_logloss: 0.00358763
[126]	valid_0's binary_logloss: 0.00357878
[127]	valid_0's binary_logloss: 0.00354336
[128]	valid_0's binary_logloss: 0.00350808
[129]	valid_0's binary_logloss: 0.00353042
[130]	valid_0's binary_logloss: 0.0035162
[131]	valid_0's binary_logloss: 0.00350626
[132]	valid_0's binary_logloss: 0.0035253
[133]	valid_0's binary_logloss: 0.00353768
[134]	valid_0's binary_logloss: 0.0035179
[135]	valid_0's binary_logloss: 0.00348618
[136]	valid_0's binary_logloss: 0.00345031
[137]	valid_0's binary_logloss: 0.00339628
[138]	valid_0's binary_logloss: 0.00339136
[139]	valid_0's binary_logloss: 0.00337015
[140]	valid_0's binary_logloss: 0.00333757
[141]	valid_0's binary_logloss: 0.00335894
[142]	valid_0's binary_logloss: 0.00334548
[143]	valid_0's binary_logloss: 0.00335479
[144]	valid_0's binary_logloss: 0.00335661
[145]	valid_0's binary_logloss: 0.00335239
[146]	valid_0's binary_logloss: 0.00334227
[147]	valid_0's binary_logloss: 0.00335027
[148]	valid_0's binary_logloss: 0.00333036
[149]	valid_0's binary_logloss: 0.0033365
[150]	valid_0's binary_logloss: 0.00331549
[151]	valid_0's binary_logloss: 0.00332313
[152]	valid_0's binary_logloss: 0.00332545
[153]	valid_0's binary_logloss: 0.00331771
[154]	valid_0's binary_logloss: 0.00331656
[155]	valid_0's binary_logloss: 0.00331873
[156]	valid_0's binary_logloss: 0.00331902
[157]	valid_0's binary_logloss: 0.00330571
[158]	valid_0's binary_logloss: 0.00331262
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[159]	valid_0's binary_logloss: 0.00330413
[160]	valid_0's binary_logloss: 0.00331656
[161]	valid_0's binary_logloss: 0.00332377
[162]	valid_0's binary_logloss: 0.00330392
[163]	valid_0's binary_logloss: 0.00329673
[164]	valid_0's binary_logloss: 0.00326639
[165]	valid_0's binary_logloss: 0.00326391
[166]	valid_0's binary_logloss: 0.00327535
[167]	valid_0's binary_logloss: 0.00328868
[168]	valid_0's binary_logloss: 0.00330474
[169]	valid_0's binary_logloss: 0.00332158
[170]	valid_0's binary_logloss: 0.00332071
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[171]	valid_0's binary_logloss: 0.00331281
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[172]	valid_0's binary_logloss: 0.00330896
[173]	valid_0's binary_logloss: 0.0033026
[174]	valid_0's binary_logloss: 0.00329347
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[175]	valid_0's binary_logloss: 0.00327914
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[176]	valid_0's binary_logloss: 0.00329032
[177]	valid_0's binary_logloss: 0.0032915
[178]	valid_0's binary_logloss: 0.00329461
[179]	valid_0's binary_logloss: 0.00328894
[180]	valid_0's binary_logloss: 0.003301
[181]	valid_0's binary_logloss: 0.00331869
[182]	valid_0's binary_logloss: 0.00333632
[183]	valid_0's binary_logloss: 0.00335719
[184]	valid_0's binary_logloss: 0.00337658
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[185]	valid_0's binary_logloss: 0.00338909
[186]	valid_0's binary_logloss: 0.00338086
[187]	valid_0's binary_logloss: 0.00338643
[188]	valid_0's binary_logloss: 0.00337182
[189]	valid_0's binary_logloss: 0.00337424
[190]	valid_0's binary_logloss: 0.00334502
[191]	valid_0's binary_logloss: 0.0033611
[192]	valid_0's binary_logloss: 0.00336276
[193]	valid_0's binary_logloss: 0.00333393
[194]	valid_0's binary_logloss: 0.00333679
[195]	valid_0's binary_logloss: 0.00334497

Trening klas:  61%|██████    | 303/500 [36:02<18:21,  5.59s/klasa, klasa=class_303, F1_klasy=0.4615, F1_macro=0.7038, drzewa=165]




Trening klas:  61%|██████    | 304/500 [36:02<22:46,  6.97s/klasa, klasa=class_303, F1_klasy=0.4615, F1_macro=0.7038, drzewa=165]

[1]	valid_0's binary_logloss: 0.0121626
[2]	valid_0's binary_logloss: 0.0119261
[3]	valid_0's binary_logloss: 0.0117117
[4]	valid_0's binary_logloss: 0.0115257
[5]	valid_0's binary_logloss: 0.0113314
[6]	valid_0's binary_logloss: 0.0111433
[7]	valid_0's binary_logloss: 0.0109871
[8]	valid_0's binary_logloss: 0.0108586
[9]	valid_0's binary_logloss: 0.0107435
[10]	valid_0's binary_logloss: 0.0106015
[11]	valid_0's binary_logloss: 0.0104704
[12]	valid_0's binary_logloss: 0.0103497
[13]	valid_0's binary_logloss: 0.0102637
[14]	valid_0's binary_logloss: 0.0101603
[15]	valid_0's binary_logloss: 0.01007
[16]	valid_0's binary_logloss: 0.0100083
[17]	valid_0's binary_logloss: 0.00993073
[18]	valid_0's binary_logloss: 0.00986458
[19]	valid_0's binary_logloss: 0.00981348
[20]	valid_0's binary_logloss: 0.0097598
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.00973243
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.00964488
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.00962558
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.00955766
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.0095283
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.0094745
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.00943526
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.00939379
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.00935906
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.00933742
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.00929077
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.00928274
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.00927212
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.00928158
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.00927786
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.00927482
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.00928011
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.0092384
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.00916641
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.00912303
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.00913274
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.00910053
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.00912141
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.00912969
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.00913599
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.00908751
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.0091078
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.00906765
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.00909756
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.00911443
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.00914902
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.00919907
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.00925739
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.00930063
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.00934127
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.00932225
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.00936345
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.00941688
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.00945755
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.00949948
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.00952916
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.00957376
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.00963968
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.00968593
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.00971838
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.00979931
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.00988388
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.00996333
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.0100218
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.0100182
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.0100864
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.0100939
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.0101551
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.0101268
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

Trening klas:  61%|██████    | 304/500 [36:05<22:46,  6.97s/klasa, klasa=class_304, F1_klasy=0.9212, F1_macro=0.7045, drzewa=48]




Trening klas:  61%|██████    | 305/500 [36:05<19:08,  5.89s/klasa, klasa=class_304, F1_klasy=0.9212, F1_macro=0.7045, drzewa=48]

[75]	valid_0's binary_logloss: 0.0101326
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.0101766
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.0102426
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.0102688
[1]	valid_0's binary_logloss: 0.110202
[2]	valid_0's binary_logloss: 0.0877518
[3]	valid_0's binary_logloss: 0.0818624
[4]	valid_0's binary_logloss: 0.0774433
[5]	valid_0's binary_logloss: 0.0731031
[6]	valid_0's binary_logloss: 0.0672605
[7]	valid_0's binary_logloss: 0.0635838
[8]	valid_0's binary_logloss: 0.0603527
[9]	valid_0's binary_logloss: 0.0576773
[10]	valid_0's binary_logloss: 0.0557746
[11]	valid_0's binary_logloss: 0.0536486
[12]	valid_0's binary_logloss: 0.0515372
[13]	valid_0's binary_logloss: 0.0498364
[14]	valid_0's binary_logloss: 0.0482918
[15]	valid_0's binary_logloss: 0.0469893
[16]	valid_0's binary_logloss: 0.0456376
[17]	valid_0's binary_logloss: 0.0443914
[18]	valid_0's binary_logloss: 0.0433553
[19]	valid_0's binary_logloss: 0.0421841
[20]	valid_0's binary_logloss: 0.0413399
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0402203
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0392548
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.0384781
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0375217
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.036857
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.0361061
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.0356007
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.03494
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.0344673
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.0341514
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.0335833
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.0330803
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.0326201
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.0322263
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.0318515
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.0314013
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.031028
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.0307091
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.0303393
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.0298916
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.0296617
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.0294829
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.0293378
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.0291464
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.028907
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.028857
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.0288565
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.0286964
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.0284623
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.0284975
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.028314
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.0281599
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.0279227
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.0277051
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.0275465
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.0275504
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.0275981
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.0274383
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.0274615
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.0273993
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.0272765
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.0270378
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.026881
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.0267399
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.0265837
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.0265075
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.0264188
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.0262517
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.0261857
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.026035
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.025882
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.0257348
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.0257149
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.0255695
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.025542
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.0252018
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.024971
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.0249711
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.0248425
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.0248155
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.0246594
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.0245346
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.0245008
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.0244856
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.0244728
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.0244078
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.024282
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.0242847
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.0243119
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.024333
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.0243776
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.0244157
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.0245505
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.0246191
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.0247081
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.0246589
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.0245905
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.0245273
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.0245306
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.0245059
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.0244644
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.0244697
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.0244589
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.0244578
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.0244769
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.0244172
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.0243949
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.0243564
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.0243489
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.0243352
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.0243473
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

Trening klas:  61%|██████    | 305/500 [36:10<19:08,  5.89s/klasa, klasa=class_305, F1_klasy=0.7544, F1_macro=0.7046, drzewa=87]




Trening klas:  61%|██████    | 306/500 [36:10<18:04,  5.59s/klasa, klasa=class_305, F1_klasy=0.7544, F1_macro=0.7046, drzewa=87]

[112]	valid_0's binary_logloss: 0.024333
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 0.0243274
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 0.024412
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 0.0244276
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[116]	valid_0's binary_logloss: 0.02446
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[117]	valid_0's binary_logloss: 0.0244808
[1]	valid_0's binary_logloss: 0.102366
[2]	valid_0's binary_logloss: 0.0943923
[3]	valid_0's binary_logloss: 0.089289
[4]	valid_0's binary_logloss: 0.084895
[5]	valid_0's binary_logloss: 0.081123
[6]	valid_0's binary_logloss: 0.0779721
[7]	valid_0's binary_logloss: 0.0751068
[8]	valid_0's binary_logloss: 0.0728463
[9]	valid_0's binary_logloss: 0.0703222
[10]	valid_0's binary_logloss: 0.0680402
[11]	valid_0's binary_logloss: 0.0655849
[12]	valid_0's binary_logloss: 0.0634664
[13]	valid_0's binary_logloss: 0.0614022
[14]	valid_0's binary_logloss: 0.0598902
[15]	valid_0's binary_logloss: 0.0581807
[16]	valid_0's binary_logloss: 0.0569192
[17]	valid_0's binary_logloss: 0.0555501
[18]	valid_0's binary_logloss: 0.0542647
[19]	valid_0's binary_logloss: 0.0531794
[20]	valid_0's binary_logloss: 0.052049
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.051028
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0501191
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.0493529
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0484297
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.0476271
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.0467071
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.0458399
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.0451405
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.0442602
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.0433252
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.0429479
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.0425903
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.0420427
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.0415909
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.0411473
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.0407613
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.0404709
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.0403232
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.0399576
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.0396055
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.0393768
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.0390319
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.0386913
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.0382748
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.037913
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.037692
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.0377039
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.0375137
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.0374139
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.0371933
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.0371013
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.0369159
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.0367617
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.0365908
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.0363406
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.0362398
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.0360355
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.0359149
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.0357931
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.0355517
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.035494
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.0352761
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.0352448
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.0351936
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.0350226
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.0348655
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.0348173
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.0347842
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.0347369
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.0347097
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.0346448
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.0346616
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.0345341
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.0344094
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.0345287
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.0345277
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.0344963
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.0345139
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.0344608
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.034326
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.0342046
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.0342527
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.0341645
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.0341965
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.0341974
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.0341381
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.0341955
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.0342177
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.0342106
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.0342001
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.0342304
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.0342354
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.0342922
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.0342907
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.0342779
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.0343364
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.0342993
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.034301
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.0343769
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.0343869
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.0344348
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.0344887
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.0345024
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.0345913
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.0346294
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.034638
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.0346577
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.0346988
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.0347013
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.0347364
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.0347463
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 0.0347478
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 0.0347403
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 0.0347796
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 0.0348041
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[116]	valid_0's binary_logloss: 0.0348882

Trening klas:  61%|██████    | 306/500 [36:16<18:04,  5.59s/klasa, klasa=class_306, F1_klasy=0.4567, F1_macro=0.7038, drzewa=86]




Trening klas:  61%|██████▏   | 307/500 [36:16<18:05,  5.63s/klasa, klasa=class_306, F1_klasy=0.4567, F1_macro=0.7038, drzewa=86]

[1]	valid_0's binary_logloss: 0.0207184
[2]	valid_0's binary_logloss: 0.0196745
[3]	valid_0's binary_logloss: 0.0187131
[4]	valid_0's binary_logloss: 0.0178216
[5]	valid_0's binary_logloss: 0.0170686
[6]	valid_0's binary_logloss: 0.0163674
[7]	valid_0's binary_logloss: 0.0155973
[8]	valid_0's binary_logloss: 0.0150583
[9]	valid_0's binary_logloss: 0.0144755
[10]	valid_0's binary_logloss: 0.0139346
[11]	valid_0's binary_logloss: 0.0133493
[12]	valid_0's binary_logloss: 0.0127517
[13]	valid_0's binary_logloss: 0.0121965
[14]	valid_0's binary_logloss: 0.0116777
[15]	valid_0's binary_logloss: 0.0112081
[16]	valid_0's binary_logloss: 0.0107449
[17]	valid_0's binary_logloss: 0.0102944
[18]	valid_0's binary_logloss: 0.00986388
[19]	valid_0's binary_logloss: 0.00945717
[20]	valid_0's binary_logloss: 0.00910097
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.00881059
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.00851518
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.00823507
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.007973
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.00770288
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.00743733
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.00722026
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.00701226
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.00674924
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.00651809
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.0062886
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.0060717
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.00588196
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.00571822
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.00555047
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.00537546
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.00520909
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.00505407
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.00489753
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.00475307
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.00463914
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.00452017
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.00442087
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.00429058
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.00419055
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.00411015
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.00401288
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.00393048
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.00384517
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.00376744
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.0036796
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.00359966
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.00352414
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.00345681
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.00337658
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.00328445
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.00319797
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.00311359
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.00303447
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.00295763
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.00289805
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.00283498
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.0027841
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.00272292
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.00264078
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.00259941
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.00253277
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.00249952
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.00242591
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.00237992
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.00233518
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.00231835
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.00228253
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.00227807
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.00224493
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.00218927
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.00216373
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.00211042
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.00207184
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.00202537
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.00201261
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.00195581
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.0019141
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.00188287
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.00186636
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.00185722
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.00184885
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.00184245
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.00183296
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.00183794
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.00183015
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.00182675
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.00181316
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.00179592
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.00176889
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.00176905
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.00175693
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.00176017
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.00175288
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.00174858
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.00173323
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.00171801
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.00172089
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.00170185
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.00169303
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.00168787
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.00168388
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.00168259
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.00165737
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.00165793
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.00164546
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 0.00162111
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 0.00155148
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 0.00155759
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 0.00154145
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[116]	valid_0's binary_logloss: 0.00153782
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[117]	valid_0's binary_logloss: 0.00152531
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[118]	valid_0's binary_logloss: 0.00152069
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[119]	valid_0's binary_logloss: 0.00153432
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[120]	valid_0's binary_logloss: 0.0015321
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[121]	valid_0's binary_logloss: 0.00152811
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[122]	valid_0's binary_logloss: 0.00152626
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[123]	valid_0's binary_logloss: 0.00154223
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[124]	valid_0's binary_logloss: 0.00153119
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[125]	valid_0's binary_logloss: 0.00152941
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[126]	valid_0's binary_logloss: 0.00153676
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[127]	valid_0's binary_logloss: 0.00154228
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[128]	valid_0's binary_logloss: 0.0015487
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[129]	valid_0's binary_logloss: 0.00155661
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[130]	valid_0's binary_logloss: 0.00155172
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[131]	valid_0's binary_logloss: 0.00153978
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[132]	valid_0's binary_logloss: 0.00151133
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[133]	valid_0's binary_logloss: 0.00149933
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[134]	valid_0's binary_logloss: 0.00150637
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[135]	valid_0's binary_logloss: 0.00149974
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[136]	valid_0's binary_logloss: 0.00151413
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[137]	valid_0's binary_logloss: 0.00151894
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[138]	valid_0's binary_logloss: 0.00152538
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[139]	valid_0's binary_logloss: 0.00151757
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[140]	valid_0's binary_logloss: 0.00151618
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[141]	valid_0's binary_logloss: 0.00151751
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[142]	valid_0's binary_logloss: 0.00151527
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[143]	valid_0's binary_logloss: 0.00151866
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[144]	valid_0's binary_logloss: 0.00153013
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[145]	valid_0's binary_logloss: 0.00152557
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[146]	valid_0's binary_logloss: 0.00151864
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[147]	valid_0's binary_logloss: 0.00151824
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[148]	valid_0's binary_logloss: 0.00151436
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[149]	valid_0's binary_logloss: 0.00150215
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[150]	valid_0's binary_logloss: 0.00151083
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[151]	valid_0's binary_logloss: 0.00150194
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[152]	valid_0's binary_logloss: 0.00150462
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[153]	valid_0's binary_logloss: 0.00150629
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[154]	valid_0's binary_logloss: 0.00151336
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[155]	valid_0's binary_logloss: 0.00149674
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[156]	valid_0's binary_logloss: 0.00150292
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[157]	valid_0's binary_logloss: 0.00150691
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[158]	valid_0's binary_logloss: 0.00150328
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[159]	valid_0's binary_logloss: 0.00151434
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[160]	valid_0's binary_logloss: 0.00151316
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[161]	valid_0's binary_logloss: 0.00151121
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[162]	valid_0's binary_logloss: 0.0014959
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[163]	valid_0's binary_logloss: 0.00147535
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[164]	valid_0's binary_logloss: 0.00146308
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[165]	valid_0's binary_logloss: 0.00145059
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[166]	valid_0's binary_logloss: 0.00145919
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[167]	valid_0's binary_logloss: 0.00145997
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[168]	valid_0's binary_logloss: 0.00147038
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[169]	valid_0's binary_logloss: 0.00146422
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[170]	valid_0's binary_logloss: 0.00147101
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[171]	valid_0's binary_logloss: 0.00147746
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[172]	valid_0's binary_logloss: 0.0014712
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[173]	valid_0's binary_logloss: 0.00146003
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[174]	valid_0's binary_logloss: 0.00147357
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[175]	valid_0's binary_logloss: 0.00147184
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[176]	valid_0's binary_logloss: 0.00146979
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[177]	valid_0's binary_logloss: 0.00147344
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[178]	valid_0's binary_logloss: 0.00145414
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[179]	valid_0's binary_logloss: 0.00146864
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[180]	valid_0's binary_logloss: 0.00146903
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[181]	valid_0's binary_logloss: 0.00145673
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[182]	valid_0's binary_logloss: 0.00146321
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[183]	valid_0's binary_logloss: 0.00146564

Trening klas:  61%|██████▏   | 307/500 [36:23<18:05,  5.63s/klasa, klasa=class_307, F1_klasy=0.8235, F1_macro=0.7042, drzewa=165]




Trening klas:  62%|██████▏   | 308/500 [36:23<19:26,  6.07s/klasa, klasa=class_307, F1_klasy=0.8235, F1_macro=0.7042, drzewa=165]

[194]	valid_0's binary_logloss: 0.00153261
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[195]	valid_0's binary_logloss: 0.00152867
[1]	valid_0's binary_logloss: 0.0359655
[2]	valid_0's binary_logloss: 0.0345249
[3]	valid_0's binary_logloss: 0.0333906
[4]	valid_0's binary_logloss: 0.032271
[5]	valid_0's binary_logloss: 0.0312889
[6]	valid_0's binary_logloss: 0.0314896
[7]	valid_0's binary_logloss: 0.0305518
[8]	valid_0's binary_logloss: 0.0297136
[9]	valid_0's binary_logloss: 0.0288932
[10]	valid_0's binary_logloss: 0.0281019
[11]	valid_0's binary_logloss: 0.0273947
[12]	valid_0's binary_logloss: 0.0266915
[13]	valid_0's binary_logloss: 0.0260846
[14]	valid_0's binary_logloss: 0.0256121
[15]	valid_0's binary_logloss: 0.025018
[16]	valid_0's binary_logloss: 0.0245153
[17]	valid_0's binary_logloss: 0.0241068
[18]	valid_0's binary_logloss: 0.0238169
[19]	valid_0's binary_logloss: 0.0232924
[20]	valid_0's binary_logloss: 0.0229014
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.022554
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0221351
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.0218881
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0215124
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.0212146
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.0209995
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.0207862
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.0205803
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.0204254
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.0201503
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.0199713
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.0197823
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.0195623
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.0193913
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.0192046
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.0190283
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.0188464
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.0187176
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.0185791
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.0184211
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.0182351
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.0180125
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.0178158
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.0176677
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.0174971
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.0172451
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.0172017
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.0170918
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.0168651
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.0167113
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.0166317
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.0165285
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.0164666
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.0163847
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.0163117
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.0162551
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.0161663
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.0160967
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.0159804
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.0159088
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.0158409
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.0157885
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.0157098
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.015681
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.0156291
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.0156195
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.0154974
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.0155233
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.0154683
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.0154412
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.0154312
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.0153781
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.015358
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.0152838
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.0152099
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.0152312
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.0152017
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.0152198
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.0152662
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.0152955
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.0153009
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.0153233
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.0153892
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.0153501
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.0152435
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.0152559
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.0151972
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.0151617
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.0151419
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.015134
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.0151021
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.0150616
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.0149829
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.0148736
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.0148307
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.0148201
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.0148154
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.0147389
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.0147393
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.014714
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.014769
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.0148126
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.0147997
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.0147779
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.0148423
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.0148365
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.0148263
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.0148553
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.0148125
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.0147484
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.0146976
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 0.0146031
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 0.0145943
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 0.0145542
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 0.0145131
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[116]	valid_0's binary_logloss: 0.0144152
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[117]	valid_0's binary_logloss: 0.0143569
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[118]	valid_0's binary_logloss: 0.0143539
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[119]	valid_0's binary_logloss: 0.0143058
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[120]	valid_0's binary_logloss: 0.0142874
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[121]	valid_0's binary_logloss: 0.0142749
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[122]	valid_0's binary_logloss: 0.0143109
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[123]	valid_0's binary_logloss: 0.0143062
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[124]	valid_0's binary_logloss: 0.0143187
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[125]	valid_0's binary_logloss: 0.0143101
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[126]	valid_0's binary_logloss: 0.0142629
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[127]	valid_0's binary_logloss: 0.0142562
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[128]	valid_0's binary_logloss: 0.0142157
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[129]	valid_0's binary_logloss: 0.0142289
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[130]	valid_0's binary_logloss: 0.0142432
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[131]	valid_0's binary_logloss: 0.0142505
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[132]	valid_0's binary_logloss: 0.0142635
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[133]	valid_0's binary_logloss: 0.014318
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[134]	valid_0's binary_logloss: 0.0142638
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[135]	valid_0's binary_logloss: 0.0142774
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[136]	valid_0's binary_logloss: 0.0143117
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[137]	valid_0's binary_logloss: 0.0142949
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[138]	valid_0's binary_logloss: 0.0142876
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[139]	valid_0's binary_logloss: 0.0142684
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[140]	valid_0's binary_logloss: 0.0143053
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[141]	valid_0's binary_logloss: 0.0143333
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[142]	valid_0's binary_logloss: 0.0143574
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[143]	valid_0's binary_logloss: 0.014316
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[144]	valid_0's binary_logloss: 0.0143393
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[145]	valid_0's binary_logloss: 0.0143224
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[146]	valid_0's binary_logloss: 0.0143297
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[147]	valid_0's binary_logloss: 0.0142999
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[148]	valid_0's binary_logloss: 0.0142856
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[149]	valid_0's binary_logloss: 0.0142815
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[150]	valid_0's binary_logloss: 0.0142777
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[151]	valid_0's binary_logloss: 0.014302
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[152]	valid_0's binary_logloss: 0.0143344
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[153]	valid_0's binary_logloss: 0.0143621
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[154]	valid_0's binary_logloss: 0.0143352
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[155]	valid_0's binary_logloss: 0.0143134
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

Trening klas:  62%|██████▏   | 308/500 [36:29<19:26,  6.07s/klasa, klasa=class_308, F1_klasy=0.6500, F1_macro=0.7040, drzewa=128]




Trening klas:  62%|██████▏   | 309/500 [36:29<19:20,  6.08s/klasa, klasa=class_308, F1_klasy=0.6500, F1_macro=0.7040, drzewa=128]

[156]	valid_0's binary_logloss: 0.0143049
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[157]	valid_0's binary_logloss: 0.0142736
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[158]	valid_0's binary_logloss: 0.0142493
[1]	valid_0's binary_logloss: 0.00919353
[2]	valid_0's binary_logloss: 0.00874926
[3]	valid_0's binary_logloss: 0.00832048
[4]	valid_0's binary_logloss: 0.0079197
[5]	valid_0's binary_logloss: 0.0075387
[6]	valid_0's binary_logloss: 0.00718611
[7]	valid_0's binary_logloss: 0.00684476
[8]	valid_0's binary_logloss: 0.00651846
[9]	valid_0's binary_logloss: 0.00620821
[10]	valid_0's binary_logloss: 0.00591941
[11]	valid_0's binary_logloss: 0.00563412
[12]	valid_0's binary_logloss: 0.00537499
[13]	valid_0's binary_logloss: 0.00512103
[14]	valid_0's binary_logloss: 0.00487358
[15]	valid_0's binary_logloss: 0.00464684
[16]	valid_0's binary_logloss: 0.00442604
[17]	valid_0's binary_logloss: 0.00422041
[18]	valid_0's binary_logloss: 0.00402662
[19]	valid_0's binary_logloss: 0.00384305
[20]	valid_0's binary_logloss: 0.00367226
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.00351408
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.00335595
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.00320504
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.00306244
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.0029225
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.0027932
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.00266988
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.00255211
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.00244194
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.00232606
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.00221516
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.00211758
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.0020142
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.0019174
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.00182861
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.00173938
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.00165462
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.00157409
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.00149741
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.00143211
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.00136994
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.00131132
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.00125666
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.00120478
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.00115851
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.00111297
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.00106981
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.00102127
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.000984142
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.000948583
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.000907158
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.000867588
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.000838224
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.000803232
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.000769265
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.00074414
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.000720932
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.000699173
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.000678785
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.000660231
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.000642642
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.000626338
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.000611423
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.00059748
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.000584682
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.000573157
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.00056263
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.000552676
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.000537143
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.000517017
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.00050938
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.000502445
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.000496249
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.000490467
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.000485494
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.000480939
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.000477093
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.000473684
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.000470662
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.000468258
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.000453539
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.000439411
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.000426224
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.0004258
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.000413389
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.000405089
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.000393157
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.00038429
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.000372524
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.000364436
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.000363985
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.000363582
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.000363528
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.000363694
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.000363875
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.000358712
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.000350449
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.000351082
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.000356114
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.000348204
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.000339381
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.00034538
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.000336927
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.000329208
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.000320676
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.000325038
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.00032937
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.000321107
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.000326596
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.000320228
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.000313221
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 0.000318283
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 0.000319356
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 0.000324326
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 0.000329298
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[116]	valid_0's binary_logloss: 0.000322191
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[117]	valid_0's binary_logloss: 0.000314873
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[118]	valid_0's binary_logloss: 0.000307745
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[119]	valid_0's binary_logloss: 0.000300545
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[120]	valid_0's binary_logloss: 0.000293319
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[121]	valid_0's binary_logloss: 0.00029702
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[122]	valid_0's binary_logloss: 0.000302465
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[123]	valid_0's binary_logloss: 0.000308084
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[124]	valid_0's binary_logloss: 0.000313771
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[125]	valid_0's binary_logloss: 0.000318216
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[126]	valid_0's binary_logloss: 0.000317486
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[127]	valid_0's binary_logloss: 0.000316772
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[128]	valid_0's binary_logloss: 0.000318148
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[129]	valid_0's binary_logloss: 0.00032362
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[130]	valid_0's binary_logloss: 0.000324938
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[131]	valid_0's binary_logloss: 0.000321641
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[132]	valid_0's binary_logloss: 0.000327
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[133]	valid_0's binary_logloss: 0.000333684
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[134]	valid_0's binary_logloss: 0.000330664
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[135]	valid_0's binary_logloss: 0.000336376
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[136]	valid_0's binary_logloss: 0.000329042
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[137]	valid_0's binary_logloss: 0.000321814
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[138]	valid_0's binary_logloss: 0.000323613
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[139]	valid_0's binary_logloss: 0.000316491
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[140]	valid_0's binary_logloss: 0.000309283
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[141]	valid_0's binary_logloss: 0.000309987
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[142]	valid_0's binary_logloss: 0.000303643
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[143]	valid_0's binary_logloss: 0.000297152
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[144]	valid_0's binary_logloss: 0.000291426
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[145]	valid_0's binary_logloss: 0.000285019
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[146]	valid_0's binary_logloss: 0.000284542
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[147]	valid_0's binary_logloss: 0.000290976
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[148]	valid_0's binary_logloss: 0.00029678
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[149]	valid_0's binary_logloss: 0.000302718
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[150]	valid_0's binary_logloss: 0.000308712
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[151]	valid_0's binary_logloss: 0.000308293
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[152]	valid_0's binary_logloss: 0.000314251
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[153]	valid_0's binary_logloss: 0.0003202
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[154]	valid_0's binary_logloss: 0.000326046
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[155]	valid_0's binary_logloss: 0.000320042
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[156]	valid_0's binary_logloss: 0.000326758
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[157]	valid_0's binary_logloss: 0.000333577
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[158]	valid_0's binary_logloss: 0.000340273
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[159]	valid_0's binary_logloss: 0.000346263
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[160]	valid_0's binary_logloss: 0.000353067
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[161]	valid_0's binary_logloss: 0.00035976
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[162]	valid_0's binary_logloss: 0.000366203
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[163]	valid_0's binary_logloss: 0.000372233
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[164]	valid_0's binary_logloss: 0.000366095
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[165]	valid_0's binary_logloss: 0.000373454
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[166]	valid_0's binary_logloss: 0.00037688
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[167]	valid_0's binary_logloss: 0.000380289
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[168]	valid_0's binary_logloss: 0.000383634
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[169]	valid_0's binary_logloss: 0.000383446
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[170]	valid_0's binary_logloss: 0.000386614
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[171]	valid_0's binary_logloss: 0.000389863
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[172]	valid_0's binary_logloss: 0.000385922
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[173]	valid_0's binary_logloss: 0.000384379
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[174]	valid_0's binary_logloss: 0.000391909
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

Trening klas:  62%|██████▏   | 309/500 [36:35<19:20,  6.08s/klasa, klasa=class_309, F1_klasy=0.0000, F1_macro=0.7018, drzewa=146]




Trening klas:  62%|██████▏   | 310/500 [36:35<19:16,  6.09s/klasa, klasa=class_309, F1_klasy=0.0000, F1_macro=0.7018, drzewa=146]

[175]	valid_0's binary_logloss: 0.00039175
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[176]	valid_0's binary_logloss: 0.0003986
[1]	valid_0's binary_logloss: 0.146193
[2]	valid_0's binary_logloss: 0.132856
[3]	valid_0's binary_logloss: 0.125362
[4]	valid_0's binary_logloss: 0.119691
[5]	valid_0's binary_logloss: 0.115779
[6]	valid_0's binary_logloss: 0.111923
[7]	valid_0's binary_logloss: 0.109041
[8]	valid_0's binary_logloss: 0.105942
[9]	valid_0's binary_logloss: 0.103262
[10]	valid_0's binary_logloss: 0.100715
[11]	valid_0's binary_logloss: 0.0987871
[12]	valid_0's binary_logloss: 0.0962693
[13]	valid_0's binary_logloss: 0.0945754
[14]	valid_0's binary_logloss: 0.0921027
[15]	valid_0's binary_logloss: 0.0907161
[16]	valid_0's binary_logloss: 0.0899591
[17]	valid_0's binary_logloss: 0.0885828
[18]	valid_0's binary_logloss: 0.0869755
[19]	valid_0's binary_logloss: 0.0854754
[20]	valid_0's binary_logloss: 0.0841687
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0831677
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0817082
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.0804182
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0790332
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.0780226
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.0775056
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.0770106
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.0765473
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.0761329
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.0756795
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.074804
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.0739748
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.0732136
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.0726912
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.072246
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.0715844
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.0710371
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.0705991
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.070382
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.0698813
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.0695927
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.0690404
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.0688113
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.0684554
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.068177
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.0679629
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.0674796
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.0672653
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.0671458
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.0671089
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.0668771
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.0668577
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.0667785
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.0664903
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.0663535
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.0663006
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.0661694
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.0660797
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.0660724
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.0660304
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.0660541
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.0659395
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.0658126
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.0657286
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.0657039
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.0653212
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.0652417
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.0650472
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.0648314
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.064786
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.0646239
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.0647293
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.0647826
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.0648681
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.0648409
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.0647722
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.06482
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.0645363
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.064486
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.0643513
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.064097
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.0641261
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.0639089
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.0637118
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.0635639
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.0637087
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.0636283
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.0636899
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.0636735
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.0637007
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.0635523
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.063462
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.063191
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.0630391
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.0629702
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.0629002
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.0628119
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.0627628
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.0627529
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.0627307
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.0626496
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.0625549
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.0623573
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.0621872
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.0620924
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.0620834
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.0621214
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.0620579
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.061996
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.0619578
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.0620624
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 0.0621282
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 0.0622028
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 0.0621315
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 0.0619094
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[116]	valid_0's binary_logloss: 0.0618461
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[117]	valid_0's binary_logloss: 0.0616155
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[118]	valid_0's binary_logloss: 0.0615799
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[119]	valid_0's binary_logloss: 0.0615678
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[120]	valid_0's binary_logloss: 0.0615591
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[121]	valid_0's binary_logloss: 0.0616115
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[122]	valid_0's binary_logloss: 0.0615471
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[123]	valid_0's binary_logloss: 0.0617187
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[124]	valid_0's binary_logloss: 0.0618013
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[125]	valid_0's binary_logloss: 0.0618526
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[126]	valid_0's binary_logloss: 0.0617571
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[127]	valid_0's binary_logloss: 0.0616793
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[128]	valid_0's binary_logloss: 0.061589
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[129]	valid_0's binary_logloss: 0.0615281
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[130]	valid_0's binary_logloss: 0.0615072
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[131]	valid_0's binary_logloss: 0.061421
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[132]	valid_0's binary_logloss: 0.0613862
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[133]	valid_0's binary_logloss: 0.0611747
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[134]	valid_0's binary_logloss: 0.0610811
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[135]	valid_0's binary_logloss: 0.0609152
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[136]	valid_0's binary_logloss: 0.0606897
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[137]	valid_0's binary_logloss: 0.0606709
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[138]	valid_0's binary_logloss: 0.0605
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[139]	valid_0's binary_logloss: 0.0606457
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[140]	valid_0's binary_logloss: 0.0607107
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[141]	valid_0's binary_logloss: 0.060726
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[142]	valid_0's binary_logloss: 0.0607561
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[143]	valid_0's binary_logloss: 0.0607493
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[144]	valid_0's binary_logloss: 0.0607139
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[145]	valid_0's binary_logloss: 0.0608196
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[146]	valid_0's binary_logloss: 0.0609316
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[147]	valid_0's binary_logloss: 0.0608941
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[148]	valid_0's binary_logloss: 0.0609351
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[149]	valid_0's binary_logloss: 0.060969
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[150]	valid_0's binary_logloss: 0.0610406
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[151]	valid_0's binary_logloss: 0.0610439
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[152]	valid_0's binary_logloss: 0.0610153
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[153]	valid_0's binary_logloss: 0.0611529
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[154]	valid_0's binary_logloss: 0.0611711
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[155]	valid_0's binary_logloss: 0.0612277
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[156]	valid_0's binary_logloss: 0.061263
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[157]	valid_0's binary_logloss: 0.0613413
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[158]	valid_0's binary_logloss: 0.0613982
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[159]	valid_0's binary_logloss: 0.0615155
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[160]	valid_0's binary_logloss: 0.061547
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[161]	valid_0's binary_logloss: 0.0615885
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[162]	valid_0's binary_logloss: 0.0614487
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[163]	valid_0's binary_logloss: 0.0614791
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[164]	valid_0's binary_logloss: 0.0614795
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[165]	valid_0's binary_logloss: 0.0615554
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

Trening klas:  62%|██████▏   | 310/500 [36:42<19:16,  6.09s/klasa, klasa=class_310, F1_klasy=0.4569, F1_macro=0.7010, drzewa=138]




Trening klas:  62%|██████▏   | 311/500 [36:42<19:58,  6.34s/klasa, klasa=class_310, F1_klasy=0.4569, F1_macro=0.7010, drzewa=138]

[166]	valid_0's binary_logloss: 0.0616011
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[167]	valid_0's binary_logloss: 0.0616609
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[168]	valid_0's binary_logloss: 0.0617108
[1]	valid_0's binary_logloss: 0.703435
[2]	valid_0's binary_logloss: 0.429551
[3]	valid_0's binary_logloss: 0.396534
[4]	valid_0's binary_logloss: 0.373588
[5]	valid_0's binary_logloss: 0.35553
[6]	valid_0's binary_logloss: 0.33899
[7]	valid_0's binary_logloss: 0.324116
[8]	valid_0's binary_logloss: 0.310762
[9]	valid_0's binary_logloss: 0.298037
[10]	valid_0's binary_logloss: 0.288061
[11]	valid_0's binary_logloss: 0.278338
[12]	valid_0's binary_logloss: 0.269403
[13]	valid_0's binary_logloss: 0.261391
[14]	valid_0's binary_logloss: 0.253812
[15]	valid_0's binary_logloss: 0.246806
[16]	valid_0's binary_logloss: 0.240335
[17]	valid_0's binary_logloss: 0.234009
[18]	valid_0's binary_logloss: 0.228054
[19]	valid_0's binary_logloss: 0.222725
[20]	valid_0's binary_logloss: 0.217209
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.214005
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.20884
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.204016
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.199642
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.195437
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.191361
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.187321
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.183749
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.179994
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.176557
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.173442
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.170141
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.167405
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.164646
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.162139
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.159241
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.156692
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.153858
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.151061
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.148649
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.146284
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.143794
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.141326
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.138931
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.136584
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.134395
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.132456
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.130418
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.128695
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.127038
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.125151
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.123337
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.121763
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.119879
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.118389
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.116479
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.114932
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.113453
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.112153
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.11061
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.109173
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.107751
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.106473
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.105031
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.103768
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.102423
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.101079
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.0998054
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.0985059
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.0974696
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.0965834
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.0957453
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.0947804
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.093835
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.0930877
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.0923735
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.0914951
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.0906903
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.0899382
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.0891204
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.0883411
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.0875035
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.0867333
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.0859243
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.0853673
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.0847332
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.0840259
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.0835345
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.0829185
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.082421
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.0818573
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.0813151
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.0809535
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.0805177
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.0802711
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.0796901
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.0791359
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.078782
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.0783185
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.0777922
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.0774844
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.0770454
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.0767982
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.0764525
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.0762165
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.0758677
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.0754757
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.0751438
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.0748717
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.0745407
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.0743864
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 0.0741003
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 0.073798
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 0.073634
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 0.0734746
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[116]	valid_0's binary_logloss: 0.0733021
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[117]	valid_0's binary_logloss: 0.0732444
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[118]	valid_0's binary_logloss: 0.0730335
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[119]	valid_0's binary_logloss: 0.0728213
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[120]	valid_0's binary_logloss: 0.0726573
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[121]	valid_0's binary_logloss: 0.072382
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[122]	valid_0's binary_logloss: 0.0722173
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[123]	valid_0's binary_logloss: 0.071999
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[124]	valid_0's binary_logloss: 0.0717735
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[125]	valid_0's binary_logloss: 0.071523
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[126]	valid_0's binary_logloss: 0.0715158
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[127]	valid_0's binary_logloss: 0.0713477
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[128]	valid_0's binary_logloss: 0.0713756
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[129]	valid_0's binary_logloss: 0.0711683
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[130]	valid_0's binary_logloss: 0.071166
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[131]	valid_0's binary_logloss: 0.0710433
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[132]	valid_0's binary_logloss: 0.0709372
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[133]	valid_0's binary_logloss: 0.0708027
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[134]	valid_0's binary_logloss: 0.0707839
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[135]	valid_0's binary_logloss: 0.0706973
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[136]	valid_0's binary_logloss: 0.0705877
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[137]	valid_0's binary_logloss: 0.0705292
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[138]	valid_0's binary_logloss: 0.0705398
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[139]	valid_0's binary_logloss: 0.0705209
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[140]	valid_0's binary_logloss: 0.0704926
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[141]	valid_0's binary_logloss: 0.070356
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[142]	valid_0's binary_logloss: 0.0702009
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[143]	valid_0's binary_logloss: 0.0699778
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[144]	valid_0's binary_logloss: 0.0696885
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[145]	valid_0's binary_logloss: 0.0694226
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[146]	valid_0's binary_logloss: 0.0693529
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[147]	valid_0's binary_logloss: 0.069422
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[148]	valid_0's binary_logloss: 0.0694031
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[149]	valid_0's binary_logloss: 0.0693391
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[150]	valid_0's binary_logloss: 0.0692889
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[151]	valid_0's binary_logloss: 0.0692109
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[152]	valid_0's binary_logloss: 0.0691114
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[153]	valid_0's binary_logloss: 0.0690012
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[154]	valid_0's binary_logloss: 0.0689503
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[155]	valid_0's binary_logloss: 0.0689227
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[156]	valid_0's binary_logloss: 0.0689088
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[157]	valid_0's binary_logloss: 0.0687644
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[158]	valid_0's binary_logloss: 0.0688205
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[159]	valid_0's binary_logloss: 0.0689594
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[160]	valid_0's binary_logloss: 0.0688856
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[161]	valid_0's binary_logloss: 0.0688285
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[162]	valid_0's binary_logloss: 0.0688896
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[163]	valid_0's binary_logloss: 0.0689407
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[164]	valid_0's binary_logloss: 0.0690072
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[165]	valid_0's binary_logloss: 0.069109
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[166]	valid_0's binary_logloss: 0.0690159
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[167]	valid_0's binary_logloss: 0.0689132
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[168]	valid_0's binary_logloss: 0.0689282
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[169]	valid_0's binary_logloss: 0.0688965
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[170]	valid_0's binary_logloss: 0.0689342
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[171]	valid_0's binary_logloss: 0.0689991
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[172]	valid_0's binary_logloss: 0.0690742
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[173]	valid_0's binary_logloss: 0.0692151
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[174]	valid_0's binary_logloss: 0.0693295
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[175]	valid_0's binary_logloss: 0.069463
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[176]	valid_0's binary_logloss: 0.0695271
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[177]	valid_0's binary_logloss: 0.0695335
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[178]	valid_0's binary_logloss: 0.0694675
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[179]	valid_0's binary_logloss: 0.0695019
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[180]	valid_0's binary_logloss: 0.0695212
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[181]	valid_0's binary_logloss: 0.0694202
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[182]	valid_0's binary_logloss: 0.0694371
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[183]	valid_0's binary_logloss: 0.0694194

Trening klas:  62%|██████▏   | 311/500 [36:51<19:58,  6.34s/klasa, klasa=class_311, F1_klasy=0.5387, F1_macro=0.7005, drzewa=157]




Trening klas:  62%|██████▏   | 312/500 [36:51<22:48,  7.28s/klasa, klasa=class_311, F1_klasy=0.5387, F1_macro=0.7005, drzewa=157]

[186]	valid_0's binary_logloss: 0.0692853
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[187]	valid_0's binary_logloss: 0.0692154
[1]	valid_0's binary_logloss: 0.0554567
[2]	valid_0's binary_logloss: 0.0506233
[3]	valid_0's binary_logloss: 0.0434662
[4]	valid_0's binary_logloss: 0.0406852
[5]	valid_0's binary_logloss: 0.0387223
[6]	valid_0's binary_logloss: 0.0373476
[7]	valid_0's binary_logloss: 0.0357943
[8]	valid_0's binary_logloss: 0.034155
[9]	valid_0's binary_logloss: 0.0330948
[10]	valid_0's binary_logloss: 0.0322306
[11]	valid_0's binary_logloss: 0.031303
[12]	valid_0's binary_logloss: 0.0304618
[13]	valid_0's binary_logloss: 0.0292597
[14]	valid_0's binary_logloss: 0.0286835
[15]	valid_0's binary_logloss: 0.0282235
[16]	valid_0's binary_logloss: 0.0278377
[17]	valid_0's binary_logloss: 0.0275942
[18]	valid_0's binary_logloss: 0.0273133
[19]	valid_0's binary_logloss: 0.0265766
[20]	valid_0's binary_logloss: 0.0264375
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0261831
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0259803
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.0257396
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0255199
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.0253373
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.0248946
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.0247381
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.0243605
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.0242459
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.0238962
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.0236017
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.0233467
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.0232307
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.0231417
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.0228755
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.0222049
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.0219403
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.0213745
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.0212145
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.0208212
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.0206315
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.0203404
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.0201469
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.0199268
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.0198533
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.0195513
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.0190262
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.0187966
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.0186132
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.0184856
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.0181019
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.0179451
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.0175625
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.0173126
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.0171582
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.0169744
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.0168267
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.016767
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.0167816
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.0167711
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.0164974
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.0162326
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.0159928
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.0157408
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.0154632
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.0153127
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.0152154
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.0150516
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.0149207
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.0148045
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.0147177
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.0146413
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.0145812
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.0144344
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.0142507
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.0142072
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.0142276
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.0142305
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.0142256
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.0141866
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.0140686
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.0140279
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.0139796
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.0139477
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.0138896
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.0138569
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.0138444
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.0137648
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.0137519
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.0137369
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.0136545
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.0135905
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.0135485
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.0136091
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.01351
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.013427
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.0133335
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.0132954
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.0132749
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.013289
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.0132224
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.0131942
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.0132438
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.0132556
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.0132638
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.013279
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.0133379
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.0133288
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.0133783
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.0133575
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.0133917
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 0.0134499
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 0.0134713
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 0.0135068
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 0.0135239
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[116]	valid_0's binary_logloss: 0.0132037
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[117]	valid_0's binary_logloss: 0.0136664
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[118]	valid_0's binary_logloss: 0.0134981
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[119]	valid_0's binary_logloss: 0.0135121
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[120]	valid_0's binary_logloss: 0.0134392
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[121]	valid_0's binary_logloss: 0.0134555
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[122]	valid_0's binary_logloss: 0.0134532
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[123]	valid_0's binary_logloss: 0.0134257
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[124]	valid_0's binary_logloss: 0.0134025
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[125]	valid_0's binary_logloss: 0.0133753
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[126]	valid_0's binary_logloss: 0.0133592
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[127]	valid_0's binary_logloss: 0.0133358
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[128]	valid_0's binary_logloss: 0.0132894
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

Trening klas:  62%|██████▏   | 312/500 [36:57<22:48,  7.28s/klasa, klasa=class_312, F1_klasy=0.7607, F1_macro=0.7007, drzewa=102]




Trening klas:  63%|██████▎   | 313/500 [36:57<20:53,  6.70s/klasa, klasa=class_312, F1_klasy=0.7607, F1_macro=0.7007, drzewa=102]

[129]	valid_0's binary_logloss: 0.0133239
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[130]	valid_0's binary_logloss: 0.0133713
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[131]	valid_0's binary_logloss: 0.013405
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[132]	valid_0's binary_logloss: 0.0133961
[1]	valid_0's binary_logloss: 0.0997683
[2]	valid_0's binary_logloss: 0.0935108
[3]	valid_0's binary_logloss: 0.0890788
[4]	valid_0's binary_logloss: 0.0850494
[5]	valid_0's binary_logloss: 0.08105
[6]	valid_0's binary_logloss: 0.0790605
[7]	valid_0's binary_logloss: 0.0755866
[8]	valid_0's binary_logloss: 0.0723803
[9]	valid_0's binary_logloss: 0.0695982
[10]	valid_0's binary_logloss: 0.0673844
[11]	valid_0's binary_logloss: 0.0653358
[12]	valid_0's binary_logloss: 0.0636628
[13]	valid_0's binary_logloss: 0.0619642
[14]	valid_0's binary_logloss: 0.0602921
[15]	valid_0's binary_logloss: 0.0588626
[16]	valid_0's binary_logloss: 0.0575087
[17]	valid_0's binary_logloss: 0.055989
[18]	valid_0's binary_logloss: 0.0547315
[19]	valid_0's binary_logloss: 0.0536303
[20]	valid_0's binary_logloss: 0.0524043
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0513209
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.050225
[23]	valid_0's binary_logloss: 0.0490484
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0483081
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.0474866
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.0466927
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.0457492
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.0450875
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.0444105
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.043575
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.0430011
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.0423585
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.0418435
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.0413871
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.0409754
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.040694
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.0403249
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.0399801
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.0396818
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.0393689
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.0390256
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.038751
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.0385354
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.0383285
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.0380912
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.0379149
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.0376876
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.0375465
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.0373802
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.0372509
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.0370598
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.0368441
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.036692
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.0365928
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.0363563
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.0361988
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.0362086
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.036119
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.0360158
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.0360221
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.0360361
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.036074
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.0361146
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.0361674
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.0362227
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.0363169
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.0368178
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.0369269
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.0371387
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.0374948
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.0374798
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.0375212
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.0375568
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.0375431
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.0375824
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.0376888
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.0377767
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.0378715
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.0380138
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.0381458
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.0382901
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.038451
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.0386313
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.0387482
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.0389544
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.0391291
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

Trening klas:  63%|██████▎   | 313/500 [37:03<20:53,  6.70s/klasa, klasa=class_313, F1_klasy=0.2667, F1_macro=0.6993, drzewa=59]




Trening klas:  63%|██████▎   | 314/500 [37:03<20:35,  6.64s/klasa, klasa=class_313, F1_klasy=0.2667, F1_macro=0.6993, drzewa=59]

[87]	valid_0's binary_logloss: 0.0392962
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.0394474
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.0395284
[1]	valid_0's binary_logloss: 0.0602176
[2]	valid_0's binary_logloss: 0.0569227
[3]	valid_0's binary_logloss: 0.0545131
[4]	valid_0's binary_logloss: 0.0522252
[5]	valid_0's binary_logloss: 0.0501808
[6]	valid_0's binary_logloss: 0.0480632
[7]	valid_0's binary_logloss: 0.0460586
[8]	valid_0's binary_logloss: 0.0444634
[9]	valid_0's binary_logloss: 0.0427854
[10]	valid_0's binary_logloss: 0.0414902
[11]	valid_0's binary_logloss: 0.0403077
[12]	valid_0's binary_logloss: 0.0391385
[13]	valid_0's binary_logloss: 0.0378436
[14]	valid_0's binary_logloss: 0.0365499
[15]	valid_0's binary_logloss: 0.0356426
[16]	valid_0's binary_logloss: 0.0345455
[17]	valid_0's binary_logloss: 0.0336406
[18]	valid_0's binary_logloss: 0.0326641
[19]	valid_0's binary_logloss: 0.0318468
[20]	valid_0's binary_logloss: 0.0311105
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0302451
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0293906
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.0287299
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0281164
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.0274398
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.0268874
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.0263672
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.0258863
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.0253685
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.0248528
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.0245173
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.0241366
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.0237988
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.0234446
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.0231536
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.0227943
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.0224484
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.0221693
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.0218892
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.0216675
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.0213534
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.0211138
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.0209477
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.0207004
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.0205305
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.0203339
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.0201255
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.0199454
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.0197347
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.0196157
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.0195012
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.0194022
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.0193577
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.0192583
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.0192146
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.0191107
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.0191338
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.0189968
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.019009
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.019045
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.018962
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.018846
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.0187563
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.0187604
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.0186468
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.0185835
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.0185293
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.0184712
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.0184134
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.0183462
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.0183282
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.0182869
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.0182448
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.0181596
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.0181213
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.0182376
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.0182388
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.0182476
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.0182693
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.0182852
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.0183488
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.0184184
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.0183822
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.0183637
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.0184054
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.0183576
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.0183228
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.0182927
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.0182363
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.0182187
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.0181906
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.0181476
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.0181316
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.0180927
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.0180689
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.0180957
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.0180919
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.0180531
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.0180812
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.0181202
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.0182269
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.0182464
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.0182793
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.0183373
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.0183046
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.0182743
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.0182606
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.0183121
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.0183083
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.018312
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.0183816
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 0.0184874
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 0.0185217
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 0.0185457
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 0.0184907
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[116]	valid_0's binary_logloss: 0.0185603
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[117]	valid_0's binary_logloss: 0.0186043
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[118]	valid_0's binary_logloss: 0.0186591
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[119]	valid_0's binary_logloss: 0.0187116
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[120]	valid_0's binary_logloss: 0.0187032
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[121]	valid_0's binary_logloss: 0.0187366
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[122]	valid_0's binary_logloss: 0.0187711
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[123]	valid_0's binary_logloss: 0.0187959
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[124]	valid_0's binary_logloss: 0.0188239
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[125]	valid_0's binary_logloss: 0.0189079
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[126]	valid_0's binary_logloss: 0.0189766
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[127]	valid_0's binary_logloss: 0.0190019
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

Trening klas:  63%|██████▎   | 314/500 [37:11<20:35,  6.64s/klasa, klasa=class_314, F1_klasy=0.2745, F1_macro=0.6979, drzewa=98]




Trening klas:  63%|██████▎   | 315/500 [37:11<21:10,  6.87s/klasa, klasa=class_314, F1_klasy=0.2745, F1_macro=0.6979, drzewa=98]

[128]	valid_0's binary_logloss: 0.0190142
[1]	valid_0's binary_logloss: 0.206725
[2]	valid_0's binary_logloss: 0.143219
[3]	valid_0's binary_logloss: 0.129674
[4]	valid_0's binary_logloss: 0.120719
[5]	valid_0's binary_logloss: 0.112514
[6]	valid_0's binary_logloss: 0.105775
[7]	valid_0's binary_logloss: 0.100656
[8]	valid_0's binary_logloss: 0.0951559
[9]	valid_0's binary_logloss: 0.0906912
[10]	valid_0's binary_logloss: 0.0870335
[11]	valid_0's binary_logloss: 0.0833951
[12]	valid_0's binary_logloss: 0.0800616
[13]	valid_0's binary_logloss: 0.0773245
[14]	valid_0's binary_logloss: 0.0746429
[15]	valid_0's binary_logloss: 0.0721134
[16]	valid_0's binary_logloss: 0.0698441
[17]	valid_0's binary_logloss: 0.0677187
[18]	valid_0's binary_logloss: 0.0657159
[19]	valid_0's binary_logloss: 0.0639385
[20]	valid_0's binary_logloss: 0.0623529
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0606025
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.058812
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.057397
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0561408
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.0547207
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.0535265
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.0524122
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.0512405
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.0503306
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.0492156
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.0485137
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.0475633
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.0467986
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.0458633
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.0449939
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.0441625
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.0432789
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.042457
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.0418714
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.0412541
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.040686
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.0402359
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.0398928
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.0394222
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.0389755
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.0383549
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.0377171
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.0372634
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.0368008
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.0362379
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.0357951
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.0354979
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.0350842
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.0346779
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.0343219
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.0340299
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.0336991
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.0334415
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.0331059
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.0328865
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.0326014
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.0323186
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.0320229
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.0318447
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.0316138
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.0313517
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.031155
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.0309191
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.0307134
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.0305669
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.0304535
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.030323
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.0300946
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.029942
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.0297872
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.029706
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.0296076
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.0294084
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.0294171
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.0292985
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.0291565
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.0290742
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.0289371
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.0288484
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.0288182
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.0287513
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.0286872
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.0285441
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.0283341
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.0282354
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.0282007
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.0281693
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.028163
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.0280908
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.027996
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.0279775
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.0278835
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.0278382
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.0278196
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.0278723
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.0278621
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.0277703
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.0277148
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.0276892
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.027666
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.0276447
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.027687
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.02771
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.0277892
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.0278256
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.0278106
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 0.0277971
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 0.0277181
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 0.0276632
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 0.0276901
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[116]	valid_0's binary_logloss: 0.0276819
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[117]	valid_0's binary_logloss: 0.027725
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[118]	valid_0's binary_logloss: 0.0277096
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[119]	valid_0's binary_logloss: 0.0277182
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[120]	valid_0's binary_logloss: 0.0276896
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[121]	valid_0's binary_logloss: 0.0275447
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[122]	valid_0's binary_logloss: 0.0275049
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[123]	valid_0's binary_logloss: 0.0275078
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[124]	valid_0's binary_logloss: 0.0274508
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[125]	valid_0's binary_logloss: 0.0273603
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[126]	valid_0's binary_logloss: 0.0273487
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[127]	valid_0's binary_logloss: 0.0273921
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[128]	valid_0's binary_logloss: 0.0273932
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[129]	valid_0's binary_logloss: 0.0274685
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[130]	valid_0's binary_logloss: 0.0274756
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[131]	valid_0's binary_logloss: 0.0274482
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[132]	valid_0's binary_logloss: 0.0274752
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[133]	valid_0's binary_logloss: 0.027548
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[134]	valid_0's binary_logloss: 0.0275537
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[135]	valid_0's binary_logloss: 0.0276063
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[136]	valid_0's binary_logloss: 0.0276184
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[137]	valid_0's binary_logloss: 0.0275981
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[138]	valid_0's binary_logloss: 0.027639
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[139]	valid_0's binary_logloss: 0.0276788
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[140]	valid_0's binary_logloss: 0.02773
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[141]	valid_0's binary_logloss: 0.0277314
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[142]	valid_0's binary_logloss: 0.0277934
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[143]	valid_0's binary_logloss: 0.0278851
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[144]	valid_0's binary_logloss: 0.0279682
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[145]	valid_0's binary_logloss: 0.0280199
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[146]	valid_0's binary_logloss: 0.0281002
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[147]	valid_0's binary_logloss: 0.0281562
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[148]	valid_0's binary_logloss: 0.0281969
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[149]	valid_0's binary_logloss: 0.0282227
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[150]	valid_0's binary_logloss: 0.0282773
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[151]	valid_0's binary_logloss: 0.0283167
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[152]	valid_0's binary_logloss: 0.0284407
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[153]	valid_0's binary_logloss: 0.0285409
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[154]	valid_0's binary_logloss: 0.0285916
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[155]	valid_0's binary_logloss: 0.028689
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[156]	valid_0's binary_logloss: 0.0286742

Trening klas:  63%|██████▎   | 315/500 [37:18<21:10,  6.87s/klasa, klasa=class_315, F1_klasy=0.6421, F1_macro=0.6977, drzewa=126]




Trening klas:  63%|██████▎   | 316/500 [37:18<21:33,  7.03s/klasa, klasa=class_315, F1_klasy=0.6421, F1_macro=0.6977, drzewa=126]

[1]	valid_0's binary_logloss: 0.0108661
[2]	valid_0's binary_logloss: 0.0103866
[3]	valid_0's binary_logloss: 0.00988174
[4]	valid_0's binary_logloss: 0.00934653
[5]	valid_0's binary_logloss: 0.00886249
[6]	valid_0's binary_logloss: 0.00844315
[7]	valid_0's binary_logloss: 0.00803808
[8]	valid_0's binary_logloss: 0.00765209
[9]	valid_0's binary_logloss: 0.00728601
[10]	valid_0's binary_logloss: 0.00694046
[11]	valid_0's binary_logloss: 0.00660746
[12]	valid_0's binary_logloss: 0.00629257
[13]	valid_0's binary_logloss: 0.00599488
[14]	valid_0's binary_logloss: 0.00571787
[15]	valid_0's binary_logloss: 0.0054451
[16]	valid_0's binary_logloss: 0.00518365
[17]	valid_0's binary_logloss: 0.00493466
[18]	valid_0's binary_logloss: 0.00469817
[19]	valid_0's binary_logloss: 0.004472
[20]	valid_0's binary_logloss: 0.00425371
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.00404948
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.00385219
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.0036645
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.00348618
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.00331708
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.00315352
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.00299656
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.00285973
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.00271452
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.00257711
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.00244887
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.00232723
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.0022116
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.0021018
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.00199887
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.00190163
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.00181026
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.00172239
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.00163521
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.00155171
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.00147579
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.0014037
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.00133509
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.00127032
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.00120625
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.00114742
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.00109153
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.00103835
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.00098791
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.000939784
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.000894132
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.000850602
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.000809656
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.000768171
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.000728566
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.00069339
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.000660533
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.000628847
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.000596879
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.00056778
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.000540551
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.000514589
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.000488307
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.000463451
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.00044
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.000418251
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.000397196
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.000377617
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.000360256
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.000342137
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.000324987
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.000308669
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.000293332
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.000278797
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.000265488
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.000252554
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.000240923
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.000229824
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.000218699
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.000208091
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.000198579
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.000189933
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.000181387
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.00017329
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.000165153
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.000157371
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.000149956
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.000143214
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.00013734
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.000131232
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.000126076
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.000121349
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.000116502
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.000111901
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.000107295
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.000102486
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 9.8296e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 9.42392e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 9.01936e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 8.65369e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 8.37644e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 8.11628e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 7.87642e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 7.6034e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 7.33761e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 7.06514e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 6.74979e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 6.53517e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 6.32502e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 6.10631e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 5.90869e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 5.65261e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 5.42204e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 5.17019e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 4.98677e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[116]	valid_0's binary_logloss: 4.84258e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[117]	valid_0's binary_logloss: 4.73431e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[118]	valid_0's binary_logloss: 4.57589e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[119]	valid_0's binary_logloss: 4.41221e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[120]	valid_0's binary_logloss: 4.30618e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[121]	valid_0's binary_logloss: 4.18205e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[122]	valid_0's binary_logloss: 4.05712e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[123]	valid_0's binary_logloss: 3.9404e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[124]	valid_0's binary_logloss: 3.80615e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[125]	valid_0's binary_logloss: 3.71645e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[126]	valid_0's binary_logloss: 3.61687e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[127]	valid_0's binary_logloss: 3.49739e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[128]	valid_0's binary_logloss: 3.34659e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[129]	valid_0's binary_logloss: 3.23763e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[130]	valid_0's binary_logloss: 3.12443e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[131]	valid_0's binary_logloss: 3.03267e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[132]	valid_0's binary_logloss: 2.95749e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[133]	valid_0's binary_logloss: 2.87338e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[134]	valid_0's binary_logloss: 2.79783e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[135]	valid_0's binary_logloss: 2.69261e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[136]	valid_0's binary_logloss: 2.58478e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[137]	valid_0's binary_logloss: 2.48512e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[138]	valid_0's binary_logloss: 2.40449e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[139]	valid_0's binary_logloss: 2.33939e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[140]	valid_0's binary_logloss: 2.20787e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[141]	valid_0's binary_logloss: 2.14289e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[142]	valid_0's binary_logloss: 2.08304e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[143]	valid_0's binary_logloss: 2.01686e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[144]	valid_0's binary_logloss: 1.97347e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[145]	valid_0's binary_logloss: 1.92939e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[146]	valid_0's binary_logloss: 1.88815e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[147]	valid_0's binary_logloss: 1.83275e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[148]	valid_0's binary_logloss: 1.79836e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[149]	valid_0's binary_logloss: 1.74619e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[150]	valid_0's binary_logloss: 1.69538e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[151]	valid_0's binary_logloss: 1.64237e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[152]	valid_0's binary_logloss: 1.58892e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[153]	valid_0's binary_logloss: 1.54468e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[154]	valid_0's binary_logloss: 1.49864e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[155]	valid_0's binary_logloss: 1.45687e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[156]	valid_0's binary_logloss: 1.43358e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[157]	valid_0's binary_logloss: 1.38711e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[158]	valid_0's binary_logloss: 1.37239e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[159]	valid_0's binary_logloss: 1.3482e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[160]	valid_0's binary_logloss: 1.33535e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[161]	valid_0's binary_logloss: 1.3043e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[162]	valid_0's binary_logloss: 1.27918e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[163]	valid_0's binary_logloss: 1.26525e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[164]	valid_0's binary_logloss: 1.24406e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[165]	valid_0's binary_logloss: 1.22508e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[166]	valid_0's binary_logloss: 1.21535e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[167]	valid_0's binary_logloss: 1.20194e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[168]	valid_0's binary_logloss: 1.19206e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[169]	valid_0's binary_logloss: 1.19191e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[170]	valid_0's binary_logloss: 1.19038e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[171]	valid_0's binary_logloss: 1.17357e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[172]	valid_0's binary_logloss: 1.16862e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[173]	valid_0's binary_logloss: 1.1624e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[174]	valid_0's binary_logloss: 1.12611e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[175]	valid_0's binary_logloss: 1.1068e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[176]	valid_0's binary_logloss: 1.07873e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[177]	valid_0's binary_logloss: 1.03893e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[178]	valid_0's binary_logloss: 1.02617e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[179]	valid_0's binary_logloss: 1.01529e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[180]	valid_0's binary_logloss: 9.94196e-06
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[181]	valid_0's binary_logloss: 9.54915e-06
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[182]	valid_0's binary_logloss: 9.17225e-06

Trening klas:  63%|██████▎   | 316/500 [37:32<21:33,  7.03s/klasa, klasa=class_316, F1_klasy=0.0000, F1_macro=0.6955, drzewa=300]




Trening klas:  63%|██████▎   | 317/500 [37:32<27:43,  9.09s/klasa, klasa=class_316, F1_klasy=0.0000, F1_macro=0.6955, drzewa=300]

[1]	valid_0's binary_logloss: 0.0173983
[2]	valid_0's binary_logloss: 0.016834
[3]	valid_0's binary_logloss: 0.0163641
[4]	valid_0's binary_logloss: 0.0159691
[5]	valid_0's binary_logloss: 0.0154704
[6]	valid_0's binary_logloss: 0.0148175
[7]	valid_0's binary_logloss: 0.0143378
[8]	valid_0's binary_logloss: 0.0137988
[9]	valid_0's binary_logloss: 0.0132844
[10]	valid_0's binary_logloss: 0.0130488
[11]	valid_0's binary_logloss: 0.012613
[12]	valid_0's binary_logloss: 0.012118
[13]	valid_0's binary_logloss: 0.0116059
[14]	valid_0's binary_logloss: 0.0111342
[15]	valid_0's binary_logloss: 0.0108044
[16]	valid_0's binary_logloss: 0.010569
[17]	valid_0's binary_logloss: 0.010173
[18]	valid_0's binary_logloss: 0.0100006
[19]	valid_0's binary_logloss: 0.00975652
[20]	valid_0's binary_logloss: 0.00962885
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.00937338
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0091119
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.00883858
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0085997
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.00832773
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.00827091
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.00820861
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.00793447
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.00788015
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.00784384
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.00758966
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.00737316
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.00704466
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.00683986
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.00659422
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.00629072
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.00603736
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.00600171
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.00583951
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.00568976
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.005626
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.00555882
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.00550084
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.00526656
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.00521481
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.00517978
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.00518811
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.00514755
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.00511616
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.00509191
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.00489597
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.00481878
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.00470096
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.0046238
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.00444702
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.00437446
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.00430861
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.00424598
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.0041066
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.00405267
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.00392697
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.00380726
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.00375179
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.0036419
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.00353707
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.00345228
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.00346321
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.00339143
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.00339827
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.00330995
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.00324252
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.00316549
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.00308998
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.00302212
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.00294394
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.00286293
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.00282779
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.00275537
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.00267078
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.00267023
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.00271569
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.0027267
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.00274016
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.00271276
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.00271575
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.00266098
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.00261
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.00255965
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.0025119
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.00246669
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.00243734
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.00239933
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.00239765
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.00239658
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.00240965
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.00242293
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.00238351
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.0023558
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.00236978
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.00233467
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.00230033
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.0022687
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.00223871
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.00221312
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.00218974
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.00221302
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.00221589
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.00218693
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.00221158
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.00223774
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.00217833
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 0.00215133
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 0.00217085
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 0.00211872
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 0.00206733
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[116]	valid_0's binary_logloss: 0.0020905
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[117]	valid_0's binary_logloss: 0.00209808
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[118]	valid_0's binary_logloss: 0.00212104
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[119]	valid_0's binary_logloss: 0.00214606
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[120]	valid_0's binary_logloss: 0.00217347
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[121]	valid_0's binary_logloss: 0.00214812
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[122]	valid_0's binary_logloss: 0.00213343
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[123]	valid_0's binary_logloss: 0.00211967
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[124]	valid_0's binary_logloss: 0.00210606
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[125]	valid_0's binary_logloss: 0.00212681
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[126]	valid_0's binary_logloss: 0.00214575
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[127]	valid_0's binary_logloss: 0.00212358
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[128]	valid_0's binary_logloss: 0.00215584
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[129]	valid_0's binary_logloss: 0.00217634
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[130]	valid_0's binary_logloss: 0.00220944
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[131]	valid_0's binary_logloss: 0.00225011
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[132]	valid_0's binary_logloss: 0.00229011
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[133]	valid_0's binary_logloss: 0.00233251
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[134]	valid_0's binary_logloss: 0.00234412
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[135]	valid_0's binary_logloss: 0.00238401
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[136]	valid_0's binary_logloss: 0.0024088
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[137]	valid_0's binary_logloss: 0.00242795
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[138]	valid_0's binary_logloss: 0.00246256
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[139]	valid_0's binary_logloss: 0.00247828
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[140]	valid_0's binary_logloss: 0.00250648
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[141]	valid_0's binary_logloss: 0.00249736
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

Trening klas:  63%|██████▎   | 317/500 [37:36<27:43,  9.09s/klasa, klasa=class_317, F1_klasy=0.5556, F1_macro=0.6951, drzewa=115]




Trening klas:  64%|██████▎   | 318/500 [37:36<23:21,  7.70s/klasa, klasa=class_317, F1_klasy=0.5556, F1_macro=0.6951, drzewa=115]

[142]	valid_0's binary_logloss: 0.00248535
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[143]	valid_0's binary_logloss: 0.00246049
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[144]	valid_0's binary_logloss: 0.00243643
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[145]	valid_0's binary_logloss: 0.00244621
[1]	valid_0's binary_logloss: 0.027045
[2]	valid_0's binary_logloss: 0.0245946
[3]	valid_0's binary_logloss: 0.0227895
[4]	valid_0's binary_logloss: 0.021608
[5]	valid_0's binary_logloss: 0.0205434
[6]	valid_0's binary_logloss: 0.0195453
[7]	valid_0's binary_logloss: 0.0186351
[8]	valid_0's binary_logloss: 0.0177856
[9]	valid_0's binary_logloss: 0.0170813
[10]	valid_0's binary_logloss: 0.0164417
[11]	valid_0's binary_logloss: 0.0156885
[12]	valid_0's binary_logloss: 0.0150895
[13]	valid_0's binary_logloss: 0.0144166
[14]	valid_0's binary_logloss: 0.0140985
[15]	valid_0's binary_logloss: 0.0136275
[16]	valid_0's binary_logloss: 0.0132057
[17]	valid_0's binary_logloss: 0.0128483
[18]	valid_0's binary_logloss: 0.0124233
[19]	valid_0's binary_logloss: 0.0120125
[20]	valid_0's binary_logloss: 0.0115441
[21]	valid_0's binary_logloss: 0.0111941
[22]	valid_0's binary_logloss: 0.0108011
[23]	valid_0's binary_logloss: 0.0104641
[24]	valid_0's binary_logloss: 0.0101526
[25]	valid_0's binary_logloss: 0.00983532
[26]	valid_0's binary_logloss: 0.00950236
[27]	valid_0's binary_logloss: 0.00922805
[28]	valid_0's binary_logloss: 0.00904187
[29]	valid_0's binary_logloss: 0.00883403
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.00860654
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.00840242
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.00829272
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.00818159
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.00805641
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.00787077
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.00772689
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.00760092
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.00749075
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.00741305
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.00731751
[41]	valid_0's binary_logloss: 0.00716654
[42]	valid_0's binary_logloss: 0.00699913
[43]	valid_0's binary_logloss: 0.00686351
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.00674768
[45]	valid_0's binary_logloss: 0.00666704
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.00652862
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.0064177
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.00633478
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.00624983
[50]	valid_0's binary_logloss: 0.00617672
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.00619232
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.00616108
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.00616439
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.00612381
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.00610546
[56]	valid_0's binary_logloss: 0.00602312
[57]	valid_0's binary_logloss: 0.00591604
[58]	valid_0's binary_logloss: 0.00583233
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.00577914
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.00573793
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.00567062
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.00561732
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.00556084
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.00552947
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.00547638
[66]	valid_0's binary_logloss: 0.00538131
[67]	valid_0's binary_logloss: 0.0052961
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.00523491
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.0051786
[70]	valid_0's binary_logloss: 0.00508595
[71]	valid_0's binary_logloss: 0.00501955
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.0049909
[73]	valid_0's binary_logloss: 0.00493692
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.00489883
[75]	valid_0's binary_logloss: 0.00482379
[76]	valid_0's binary_logloss: 0.00480576
[77]	valid_0's binary_logloss: 0.00473176
[78]	valid_0's binary_logloss: 0.00473289
[79]	valid_0's binary_logloss: 0.00472005
[80]	valid_0's binary_logloss: 0.00469263
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.00467618
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.00462618
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.00460871
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.00456644
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.0045639
[86]	valid_0's binary_logloss: 0.00455378
[87]	valid_0's binary_logloss: 0.00455989
[88]	valid_0's binary_logloss: 0.00453013
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.00453342
[90]	valid_0's binary_logloss: 0.00452708
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.0045307
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.00451454
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.00449482
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.00451756
[95]	valid_0's binary_logloss: 0.00448345
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.00443392
[97]	valid_0's binary_logloss: 0.00443524
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.00441842
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.00441337
[100]	valid_0's binary_logloss: 0.00439113
[101]	valid_0's binary_logloss: 0.00436895
[102]	valid_0's binary_logloss: 0.00432785
[103]	valid_0's binary_logloss: 0.00432063
[104]	valid_0's binary_logloss: 0.0043363
[105]	valid_0's binary_logloss: 0.00434282
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.00430328
[107]	valid_0's binary_logloss: 0.0042662
[108]	valid_0's binary_logloss: 0.00425939
[109]	valid_0's binary_logloss: 0.00425413
[110]	valid_0's binary_logloss: 0.00422739
[111]	valid_0's binary_logloss: 0.00424021
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 0.00424642
[113]	valid_0's binary_logloss: 0.00421159
[114]	valid_0's binary_logloss: 0.00420463
[115]	valid_0's binary_logloss: 0.00417855
[116]	valid_0's binary_logloss: 0.00417012
[117]	valid_0's binary_logloss: 0.0041586
[118]	valid_0's binary_logloss: 0.00420681
[119]	valid_0's binary_logloss: 0.0041938
[120]	valid_0's binary_logloss: 0.00417512
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[121]	valid_0's binary_logloss: 0.00417114
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[122]	valid_0's binary_logloss: 0.00416959
[123]	valid_0's binary_logloss: 0.00413967
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[124]	valid_0's binary_logloss: 0.00414895
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[125]	valid_0's binary_logloss: 0.00411144
[126]	valid_0's binary_logloss: 0.00410043
[127]	valid_0's binary_logloss: 0.00410976
[128]	valid_0's binary_logloss: 0.00411109
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[129]	valid_0's binary_logloss: 0.00410349
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[130]	valid_0's binary_logloss: 0.00410251
[131]	valid_0's binary_logloss: 0.00409199
[132]	valid_0's binary_logloss: 0.00408959
[133]	valid_0's binary_logloss: 0.00409677
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[134]	valid_0's binary_logloss: 0.00411046
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[135]	valid_0's binary_logloss: 0.00413098
[136]	valid_0's binary_logloss: 0.00413597
[137]	valid_0's binary_logloss: 0.00413229
[138]	valid_0's binary_logloss: 0.00412345
[139]	valid_0's binary_logloss: 0.00412865
[140]	valid_0's binary_logloss: 0.00414
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[141]	valid_0's binary_logloss: 0.00413971
[142]	valid_0's binary_logloss: 0.00412718
[143]	valid_0's binary_logloss: 0.00410726
[144]	valid_0's binary_logloss: 0.00410768
[145]	valid_0's binary_logloss: 0.00412207
[146]	valid_0's binary_logloss: 0.00411668
[147]	valid_0's binary_logloss: 0.00410068
[148]	valid_0's binary_logloss: 0.0040855
[149]	valid_0's binary_logloss: 0.00410396
[150]	valid_0's binary_logloss: 0.00409514
[151]	valid_0's binary_logloss: 0.00407794
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[152]	valid_0's binary_logloss: 0.00406392
[153]	valid_0's binary_logloss: 0.00406148
[154]	valid_0's binary_logloss: 0.00406897
[155]	valid_0's binary_logloss: 0.00407053
[156]	valid_0's binary_logloss: 0.0040494
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[157]	valid_0's binary_logloss: 0.00401838
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[158]	valid_0's binary_logloss: 0.00399919
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[159]	valid_0's binary_logloss: 0.0039676
[160]	valid_0's binary_logloss: 0.00395044
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[161]	valid_0's binary_logloss: 0.00395828
[162]	valid_0's binary_logloss: 0.00394792
[163]	valid_0's binary_logloss: 0.00394328
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[164]	valid_0's binary_logloss: 0.00397338
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[165]	valid_0's binary_logloss: 0.00399402
[166]	valid_0's binary_logloss: 0.00399283
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[167]	valid_0's binary_logloss: 0.00398735
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[168]	valid_0's binary_logloss: 0.00398362
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[169]	valid_0's binary_logloss: 0.00398444
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[170]	valid_0's binary_logloss: 0.00399665
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[171]	valid_0's binary_logloss: 0.00401054
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[172]	valid_0's binary_logloss: 0.00400414
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[173]	valid_0's binary_logloss: 0.00399533
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[174]	valid_0's binary_logloss: 0.00399263
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[175]	valid_0's binary_logloss: 0.00398001
[176]	valid_0's binary_logloss: 0.0039519
[177]	valid_0's binary_logloss: 0.00393232
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[178]	valid_0's binary_logloss: 0.00392611
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[179]	valid_0's binary_logloss: 0.00392023
[180]	valid_0's binary_logloss: 0.00390674
[181]	valid_0's binary_logloss: 0.00388871
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[182]	valid_0's binary_logloss: 0.00388434
[183]	valid_0's binary_logloss: 0.00387851
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[184]	valid_0's binary_logloss: 0.00386502
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[185]	valid_0's binary_logloss: 0.00387839
[186]	valid_0's binary_logloss: 0.00389822
[187]	valid_0's binary_logloss: 0.00390173
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[188]	valid_0's binary_logloss: 0.00390374
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[189]	valid_0's binary_logloss: 0.00391483
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[190]	valid_0's binary_logloss: 0.00391804
[191]	valid_0's binary_logloss: 0.00393099
[192]	valid_0's binary_logloss: 0.00391517
[193]	valid_0's binary_logloss: 0.00392473
[194]	valid_0's binary_logloss: 0.00391019
[195]	valid_0's binary_logloss: 0.00390186
[196]	valid_0's binary_logloss: 0.00390648
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[197]	valid_0's binary_logloss: 0.00388244
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[198]	valid_0's binary_logloss: 0.00389332
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[199]	valid_0's binary_logloss: 0.00389859
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[200]	valid_0's binary_logloss: 0.00391067
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[201]	valid_0's binary_logloss: 0.00392269
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[202]	valid_0's binary_logloss: 0.00391924
[203]	valid_0's binary_logloss: 0.00392545
[204]	valid_0's binary_logloss: 0.00392825
[205]	valid_0's binary_logloss: 0.00392865
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[206]	valid_0's binary_logloss: 0.00391439
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[207]	valid_0's binary_logloss: 0.00391096
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[208]	valid_0's binary_logloss: 0.00389811
[209]	valid_0's binary_logloss: 0.00389346
[210]	valid_0's binary_logloss: 0.00388643
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[211]	valid_0's binary_logloss: 0.00388111
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[212]	valid_0's binary_logloss: 0.00388108
[213]	valid_0's binary_logloss: 0.00388279

Trening klas:  64%|██████▎   | 318/500 [37:48<23:21,  7.70s/klasa, klasa=class_318, F1_klasy=0.4286, F1_macro=0.6943, drzewa=184]




Trening klas:  64%|██████▍   | 319/500 [37:48<27:15,  9.03s/klasa, klasa=class_318, F1_klasy=0.4286, F1_macro=0.6943, drzewa=184]

[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[214]	valid_0's binary_logloss: 0.00388315
[1]	valid_0's binary_logloss: 0.0456197
[2]	valid_0's binary_logloss: 0.0434157
[3]	valid_0's binary_logloss: 0.0420688
[4]	valid_0's binary_logloss: 0.0407972
[5]	valid_0's binary_logloss: 0.0395359
[6]	valid_0's binary_logloss: 0.0463053
[7]	valid_0's binary_logloss: 0.0458034
[8]	valid_0's binary_logloss: 0.0455784
[9]	valid_0's binary_logloss: 0.0452914
[10]	valid_0's binary_logloss: 0.0450337
[11]	valid_0's binary_logloss: 0.0446794
[12]	valid_0's binary_logloss: 0.0435606
[13]	valid_0's binary_logloss: 0.0426673
[14]	valid_0's binary_logloss: 0.0422074
[15]	valid_0's binary_logloss: 0.0416928
[16]	valid_0's binary_logloss: 0.040897
[17]	valid_0's binary_logloss: 0.0404317
[18]	valid_0's binary_logloss: 0.0401171
[19]	valid_0's binary_logloss: 0.0396831
[20]	valid_0's binary_logloss: 0.0392459
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0387676
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0384796
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.0382001
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0378782
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.0376454
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.0372904
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.0368167
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.0364203
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.036124
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.035809
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.0354865
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.0353105
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.0348955
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.0345702
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.0344651
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.0342458
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.0341763
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.0339696
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.0338236
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.0338307
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.0336154
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.0334095
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.0332447
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.033101
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.0329765
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.0328652
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.0327398
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.0325294
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.0322585
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.0321118
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.032043
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.0318904
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.0317264
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.0315218
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.0314669
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.0312778
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.0311133
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.0309827
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.0308364
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.0307121
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.030676
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.0305426
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.0304723
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.0303712
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.0303061
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.0302043
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.0300846
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.0299704
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.0298849
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.0298147
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.0296903
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.0295755
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.0295
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.0294184
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.0292903
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.0291976
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.0291491
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.029155
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.0290884
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.0290169
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.0290925
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.0290861
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.0290648
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.0291361
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.0291799
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.0291998
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.0292411
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.0292707
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.0292477
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.0292614
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.0292726
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.0292875
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.0293338
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.0293415
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.0293359
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.0293863
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.0294206
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.0295137
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.0295138
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.0294969
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.0295964
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.0296624
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.0296942
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.0296858
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.02969
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.0296935
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.0297082
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.029797
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

Trening klas:  64%|██████▍   | 319/500 [37:52<27:15,  9.03s/klasa, klasa=class_319, F1_klasy=0.6839, F1_macro=0.6942, drzewa=80]




Trening klas:  64%|██████▍   | 320/500 [37:52<22:29,  7.50s/klasa, klasa=class_319, F1_klasy=0.6839, F1_macro=0.6942, drzewa=80]

[109]	valid_0's binary_logloss: 0.0298284
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.0299325
[1]	valid_0's binary_logloss: 0.20245
[2]	valid_0's binary_logloss: 0.140711
[3]	valid_0's binary_logloss: 0.132308
[4]	valid_0's binary_logloss: 0.123948
[5]	valid_0's binary_logloss: 0.117263
[6]	valid_0's binary_logloss: 0.109997
[7]	valid_0's binary_logloss: 0.104304
[8]	valid_0's binary_logloss: 0.0990595
[9]	valid_0's binary_logloss: 0.0951938
[10]	valid_0's binary_logloss: 0.0918973
[11]	valid_0's binary_logloss: 0.0885271
[12]	valid_0's binary_logloss: 0.0855607
[13]	valid_0's binary_logloss: 0.0829334
[14]	valid_0's binary_logloss: 0.0806342
[15]	valid_0's binary_logloss: 0.0779635
[16]	valid_0's binary_logloss: 0.0756608
[17]	valid_0's binary_logloss: 0.0739805
[18]	valid_0's binary_logloss: 0.0721189
[19]	valid_0's binary_logloss: 0.0704455
[20]	valid_0's binary_logloss: 0.0689038
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0669058
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0652678
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.0634015
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0619763
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.0605399
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.0592758
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.0582714
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.057154
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.0562713
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.0551975
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.0543147
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.0534461
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.0525499
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.0516721
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.0508898
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.0501035
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.0490889
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.0483196
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.0475826
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.0468155
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.0462276
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.0454529
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.0448782
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.0442774
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.0437269
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.0430459
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.0423099
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.0416742
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.0412122
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.0407883
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.0402044
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.039629
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.0391303
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.0386961
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.0380733
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.0375743
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.0371682
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.0367896
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.0363657
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.0359256
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.0356722
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.0349285
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.0347513
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.0343362
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.0342555
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.0337841
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.0333618
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.0329536
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.0326428
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.032375
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.0321525
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.0320066
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.0317469
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.0315656
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.0313237
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.0310313
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.0308818
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.0307177
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.0306445
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.0304799
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.030223
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.0301132
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.0298787
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.0298009
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.0296306
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.0295061
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.0292941
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.0291938
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.0289712
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.0287868
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.0286939
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.0285762
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.0284211
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.0283263
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.0282418
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.0281086
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.028049
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.0279745
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.0278815
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.0278019
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.0277213
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.0275933
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.0274625
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.0273631
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.0272598
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.0271594
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.0270721
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.0270781
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.0270535
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.0269886
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.0269922
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 0.0269983
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 0.0269733
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 0.0269492
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 0.026961
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[116]	valid_0's binary_logloss: 0.0269038
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[117]	valid_0's binary_logloss: 0.0267913
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[118]	valid_0's binary_logloss: 0.0266923
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[119]	valid_0's binary_logloss: 0.0266938
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[120]	valid_0's binary_logloss: 0.0266055
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[121]	valid_0's binary_logloss: 0.0266027
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[122]	valid_0's binary_logloss: 0.0265087
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[123]	valid_0's binary_logloss: 0.0264347
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[124]	valid_0's binary_logloss: 0.0263363
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[125]	valid_0's binary_logloss: 0.026307
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[126]	valid_0's binary_logloss: 0.0262508
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[127]	valid_0's binary_logloss: 0.0261956
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[128]	valid_0's binary_logloss: 0.0262913
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[129]	valid_0's binary_logloss: 0.0263923
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[130]	valid_0's binary_logloss: 0.0263916
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[131]	valid_0's binary_logloss: 0.0263894
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[132]	valid_0's binary_logloss: 0.0263258
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[133]	valid_0's binary_logloss: 0.0262344
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[134]	valid_0's binary_logloss: 0.0261082
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[135]	valid_0's binary_logloss: 0.02604
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[136]	valid_0's binary_logloss: 0.0260453
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[137]	valid_0's binary_logloss: 0.0260456
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[138]	valid_0's binary_logloss: 0.0260871
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[139]	valid_0's binary_logloss: 0.0260513
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[140]	valid_0's binary_logloss: 0.0261113
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[141]	valid_0's binary_logloss: 0.026201
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[142]	valid_0's binary_logloss: 0.0262487
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[143]	valid_0's binary_logloss: 0.0262776
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[144]	valid_0's binary_logloss: 0.0263213
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[145]	valid_0's binary_logloss: 0.0263932
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[146]	valid_0's binary_logloss: 0.0264583
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[147]	valid_0's binary_logloss: 0.0265254
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[148]	valid_0's binary_logloss: 0.0265418
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[149]	valid_0's binary_logloss: 0.0265455
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[150]	valid_0's binary_logloss: 0.0265278
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[151]	valid_0's binary_logloss: 0.0265856
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[152]	valid_0's binary_logloss: 0.0265822
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[153]	valid_0's binary_logloss: 0.0265968
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[154]	valid_0's binary_logloss: 0.0265803
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[155]	valid_0's binary_logloss: 0.0265703
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[156]	valid_0's binary_logloss: 0.0265807
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[157]	valid_0's binary_logloss: 0.0265735
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[158]	valid_0's binary_logloss: 0.0266267
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[159]	valid_0's binary_logloss: 0.0266711
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[160]	valid_0's binary_logloss: 0.0266215
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[161]	valid_0's binary_logloss: 0.0266351
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[162]	valid_0's binary_logloss: 0.0266581
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[163]	valid_0's binary_logloss: 0.0266693
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[164]	valid_0's binary_logloss: 0.0266419
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[165]	valid_0's binary_logloss: 0.0266809

Trening klas:  64%|██████▍   | 320/500 [38:00<22:29,  7.50s/klasa, klasa=class_320, F1_klasy=0.6495, F1_macro=0.6941, drzewa=135]




Trening klas:  64%|██████▍   | 321/500 [38:00<22:34,  7.57s/klasa, klasa=class_320, F1_klasy=0.6495, F1_macro=0.6941, drzewa=135]

[1]	valid_0's binary_logloss: 0.10572
[2]	valid_0's binary_logloss: 0.0920424
[3]	valid_0's binary_logloss: 0.0863641
[4]	valid_0's binary_logloss: 0.0829878
[5]	valid_0's binary_logloss: 0.0802171
[6]	valid_0's binary_logloss: 0.0767845
[7]	valid_0's binary_logloss: 0.0743487
[8]	valid_0's binary_logloss: 0.0730748
[9]	valid_0's binary_logloss: 0.07206
[10]	valid_0's binary_logloss: 0.0699811
[11]	valid_0's binary_logloss: 0.0675637
[12]	valid_0's binary_logloss: 0.06585
[13]	valid_0's binary_logloss: 0.0637764
[14]	valid_0's binary_logloss: 0.0620248
[15]	valid_0's binary_logloss: 0.0606739
[16]	valid_0's binary_logloss: 0.0591312
[17]	valid_0's binary_logloss: 0.0585892
[18]	valid_0's binary_logloss: 0.0572419
[19]	valid_0's binary_logloss: 0.0560098
[20]	valid_0's binary_logloss: 0.0548588
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0537369
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0527277
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.0518034
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0509174
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.0497939
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.0492763
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.0487756
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.0483163
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.0478226
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.0473859
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.0464917
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.0459166
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.0453731
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.0433957
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.0433283
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.042468
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.04243
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.041818
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.0412972
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.0406931
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.0402316
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.0399539
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.0397084
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.0394303
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.0391648
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.0386867
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.0384622
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.0380783
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.0375967
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.0372154
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.0369667
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.0367464
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.0365124
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.0361908
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.0360445
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.0358503
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.0356708
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.0357512
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.0355751
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.0354072
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.0352777
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.0351526
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.0350986
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.0350144
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.0349687
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.0348758
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.0347985
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.0347505
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.0346958
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.0344646
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.0344082
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.0342712
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.0340846
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.033884
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.0337884
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.0337483
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.0337192
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.0337548
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.0337454
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.0338179
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.0337975
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.0338089
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.0338718
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.0339231
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.0339152
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.0339973
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.034057
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.0341882
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.0343336
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.0343978
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.0344885
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.0345971
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.0347132
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.0348445
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.034849
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.034885
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.0348692
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.0348613
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.0348611
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.0349502
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.0349429
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.0350114
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.0350818
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.03522
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.0352882
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.0351653
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

Trening klas:  64%|██████▍   | 321/500 [38:05<22:34,  7.57s/klasa, klasa=class_321, F1_klasy=0.7129, F1_macro=0.6942, drzewa=77]




Trening klas:  64%|██████▍   | 322/500 [38:05<19:44,  6.65s/klasa, klasa=class_321, F1_klasy=0.7129, F1_macro=0.6942, drzewa=77]

[107]	valid_0's binary_logloss: 0.0352056
[1]	valid_0's binary_logloss: 0.0296009
[2]	valid_0's binary_logloss: 0.0281438
[3]	valid_0's binary_logloss: 0.0269721
[4]	valid_0's binary_logloss: 0.0253767
[5]	valid_0's binary_logloss: 0.0246384
[6]	valid_0's binary_logloss: 0.0233046
[7]	valid_0's binary_logloss: 0.0226522
[8]	valid_0's binary_logloss: 0.0215584
[9]	valid_0's binary_logloss: 0.0211538
[10]	valid_0's binary_logloss: 0.0207355
[11]	valid_0's binary_logloss: 0.0196356
[12]	valid_0's binary_logloss: 0.0188884
[13]	valid_0's binary_logloss: 0.0180892
[14]	valid_0's binary_logloss: 0.0173307
[15]	valid_0's binary_logloss: 0.0170243
[16]	valid_0's binary_logloss: 0.0164833
[17]	valid_0's binary_logloss: 0.0157838
[18]	valid_0's binary_logloss: 0.015394
[19]	valid_0's binary_logloss: 0.0148788
[20]	valid_0's binary_logloss: 0.0144165
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0139963
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0136317
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.0132249
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0129464
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.0126812
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.0125165
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.0122526
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.0120929
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.0119151
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.0116149
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.011514
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.0112527
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.0110044
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.0108839
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.0108082
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.0106985
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.0105631
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.0104421
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.0103662
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.0102847
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.0102163
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.0101286
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.0100597
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.00996957
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.00982926
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.00969135
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.00957884
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.00946403
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.00935812
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.0092066
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.00907037
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.00908675
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.00896554
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.00893383
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.00884674
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.00875062
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.00865202
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.00855756
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.0084489
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.00836775
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.00824794
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.00816968
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.00810144
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.00808251
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.00803574
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.00799885
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.00795238
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.00794629
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.00787859
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.00785875
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.0078937
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.00790514
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.00795185
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.00800453
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.00803212
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.00806759
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.0080343
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.00809092
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.00809189
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.00813287
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.00816392
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.00822276
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.00828149
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.00831724
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.00833883
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.00835152
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.00835972
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.00839937
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.00843745
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.00839396
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.00836105
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.00835518
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.00832734
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.00831346
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.00830496
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.00836311
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.00833466
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.00834319

Trening klas:  64%|██████▍   | 322/500 [38:09<19:44,  6.65s/klasa, klasa=class_322, F1_klasy=0.6486, F1_macro=0.6940, drzewa=70]




Trening klas:  65%|██████▍   | 323/500 [38:09<17:25,  5.91s/klasa, klasa=class_322, F1_klasy=0.6486, F1_macro=0.6940, drzewa=70]

[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.00831514
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.00834273
[1]	valid_0's binary_logloss: 0.0862768
[2]	valid_0's binary_logloss: 0.0805984
[3]	valid_0's binary_logloss: 0.0759189
[4]	valid_0's binary_logloss: 0.0722529
[5]	valid_0's binary_logloss: 0.0691352
[6]	valid_0's binary_logloss: 0.0717839
[7]	valid_0's binary_logloss: 0.0692368
[8]	valid_0's binary_logloss: 0.0666714
[9]	valid_0's binary_logloss: 0.0642482
[10]	valid_0's binary_logloss: 0.0620696
[11]	valid_0's binary_logloss: 0.0598177
[12]	valid_0's binary_logloss: 0.0577859
[13]	valid_0's binary_logloss: 0.0559289
[14]	valid_0's binary_logloss: 0.0542835
[15]	valid_0's binary_logloss: 0.0526685
[16]	valid_0's binary_logloss: 0.0511638
[17]	valid_0's binary_logloss: 0.0499957
[18]	valid_0's binary_logloss: 0.0487337
[19]	valid_0's binary_logloss: 0.0474894
[20]	valid_0's binary_logloss: 0.0463561
[21]	valid_0's binary_logloss: 0.0451774
[22]	valid_0's binary_logloss: 0.0442156
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.0433198
[24]	valid_0's binary_logloss: 0.0424525
[25]	valid_0's binary_logloss: 0.0415072
[26]	valid_0's binary_logloss: 0.0407156
[27]	valid_0's binary_logloss: 0.0400543
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.0393726
[29]	valid_0's binary_logloss: 0.0386501
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.0379224
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.0372462
[32]	valid_0's binary_logloss: 0.0366423
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.0361693
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.0356462
[35]	valid_0's binary_logloss: 0.0351029
[36]	valid_0's binary_logloss: 0.0345019
[37]	valid_0's binary_logloss: 0.0338778
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.0334909
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.0331513
[40]	valid_0's binary_logloss: 0.0327087
[41]	valid_0's binary_logloss: 0.0322528
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.0318487
[43]	valid_0's binary_logloss: 0.0314827
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.0311564
[45]	valid_0's binary_logloss: 0.0309155
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.0305299
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.0301439
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.0298338
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.0295623
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.0292588
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.0290352
[52]	valid_0's binary_logloss: 0.0287709
[53]	valid_0's binary_logloss: 0.0285182
[54]	valid_0's binary_logloss: 0.0282529
[55]	valid_0's binary_logloss: 0.0280828
[56]	valid_0's binary_logloss: 0.0279854
[57]	valid_0's binary_logloss: 0.0278179
[58]	valid_0's binary_logloss: 0.0275786
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.0273926
[60]	valid_0's binary_logloss: 0.0273088
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.027266
[62]	valid_0's binary_logloss: 0.0272331
[63]	valid_0's binary_logloss: 0.0271238
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.0271355
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.0269868
[66]	valid_0's binary_logloss: 0.0269546
[67]	valid_0's binary_logloss: 0.0268224
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.0267345
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.0267155
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.0266801
[71]	valid_0's binary_logloss: 0.0266026
[72]	valid_0's binary_logloss: 0.0265723
[73]	valid_0's binary_logloss: 0.0264815
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.0264963
[75]	valid_0's binary_logloss: 0.0265282
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.0263998
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.0262959
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.0261714
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.0260797
[80]	valid_0's binary_logloss: 0.0260052
[81]	valid_0's binary_logloss: 0.0259008
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.0257576
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.0257061
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.0256884
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.0256609
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.0256478
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.0256689
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.0256928
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.0256656
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.0256957
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.0256671
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.0256645
[93]	valid_0's binary_logloss: 0.0255815
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.0255691
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.0255747
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.0255899
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.0255615
[98]	valid_0's binary_logloss: 0.0255712
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.0255846
[100]	valid_0's binary_logloss: 0.025618
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.0255798
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.0255525
[103]	valid_0's binary_logloss: 0.0255538
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.0255817
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.0256646
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.0256925
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.0257066
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.0256243
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.025558
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.0255703
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.0255658
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 0.0255981
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 0.025617
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 0.0256044
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 0.0256164
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[116]	valid_0's binary_logloss: 0.0256232
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[117]	valid_0's binary_logloss: 0.0255865
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[118]	valid_0's binary_logloss: 0.0255039
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[119]	valid_0's binary_logloss: 0.0254988
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[120]	valid_0's binary_logloss: 0.0254297
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[121]	valid_0's binary_logloss: 0.0255094
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[122]	valid_0's binary_logloss: 0.0255458
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[123]	valid_0's binary_logloss: 0.0255964
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[124]	valid_0's binary_logloss: 0.0256641
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[125]	valid_0's binary_logloss: 0.0257331
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[126]	valid_0's binary_logloss: 0.0257349
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[127]	valid_0's binary_logloss: 0.0257436
[128]	valid_0's binary_logloss: 0.0257047
[129]	valid_0's binary_logloss: 0.0257581
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[130]	valid_0's binary_logloss: 0.0257272
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[131]	valid_0's binary_logloss: 0.0256852
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[132]	valid_0's binary_logloss: 0.0256631
[133]	valid_0's binary_logloss: 0.0257372
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[134]	valid_0's binary_logloss: 0.0257905
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[135]	valid_0's binary_logloss: 0.0257406
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[136]	valid_0's binary_logloss: 0.0257731
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[137]	valid_0's binary_logloss: 0.0258058
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[138]	valid_0's binary_logloss: 0.0258136
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[139]	valid_0's binary_logloss: 0.0258172
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[140]	valid_0's binary_logloss: 0.0258447
[141]	valid_0's binary_logloss: 0.0258739
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[142]	valid_0's binary_logloss: 0.0259288
[143]	valid_0's binary_logloss: 0.0259796
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[144]	valid_0's binary_logloss: 0.0259843
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[145]	valid_0's binary_logloss: 0.0260356
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[146]	valid_0's binary_logloss: 0.0260478
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[147]	valid_0's binary_logloss: 0.0260315
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[148]	valid_0's binary_logloss: 0.0260477
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[149]	valid_0's binary_logloss: 0.0260159
[150]	valid_0's binary_logloss: 0.0259991

Trening klas:  65%|██████▍   | 323/500 [38:18<17:25,  5.91s/klasa, klasa=class_323, F1_klasy=0.5063, F1_macro=0.6934, drzewa=120]




Trening klas:  65%|██████▍   | 324/500 [38:18<20:21,  6.94s/klasa, klasa=class_323, F1_klasy=0.5063, F1_macro=0.6934, drzewa=120]

[1]	valid_0's binary_logloss: 0.0560047
[2]	valid_0's binary_logloss: 0.0494
[3]	valid_0's binary_logloss: 0.0460476
[4]	valid_0's binary_logloss: 0.0449745
[5]	valid_0's binary_logloss: 0.0417863
[6]	valid_0's binary_logloss: 0.0415542
[7]	valid_0's binary_logloss: 0.0401676
[8]	valid_0's binary_logloss: 0.0384422
[9]	valid_0's binary_logloss: 0.036889
[10]	valid_0's binary_logloss: 0.0358376
[11]	valid_0's binary_logloss: 0.0348188
[12]	valid_0's binary_logloss: 0.0336571
[13]	valid_0's binary_logloss: 0.0328088
[14]	valid_0's binary_logloss: 0.0317939
[15]	valid_0's binary_logloss: 0.0312306
[16]	valid_0's binary_logloss: 0.0303715
[17]	valid_0's binary_logloss: 0.0295651
[18]	valid_0's binary_logloss: 0.02889
[19]	valid_0's binary_logloss: 0.0281993
[20]	valid_0's binary_logloss: 0.0275988
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0269329
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0263914
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.0259221
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0255005
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.0250055
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.0245745
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.0241959
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.0236995
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.0233601
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.0230508
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.0227679
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.022504
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.0222088
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.0218753
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.0216788
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.0215373
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.021271
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.0211554
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.0210284
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.0207845
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.0206674
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.0204669
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.0203381
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.0202363
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.0201518
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.0200021
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.0198742
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.0198331
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.0197686
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.0196675
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.0195662
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.0194709
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.019398
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.0193753
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.0193737
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.0193672
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.0193227
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.0192854
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.01926
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.0192434
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.019199
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.019134
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.0191048
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.019052
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.0190461
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.0190559
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.0190689
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.019146
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.0190674
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.0190423
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.0190037
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.0189739
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.0189805
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.0190172
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.0190597
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.0189956
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.0189959
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.0190645
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.019107
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.0191015
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.0191008
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.0191199
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.0191374
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.0191665
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.0192025
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.0192974
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.0193786
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.0194778
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.019421
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.019451
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.0195323
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.0195756
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.0195876
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.0196258
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.0196956
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.0197721
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.0198184
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.019753
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

Trening klas:  65%|██████▍   | 324/500 [38:22<20:21,  6.94s/klasa, klasa=class_324, F1_klasy=0.6852, F1_macro=0.6934, drzewa=72]




Trening klas:  65%|██████▌   | 325/500 [38:22<17:24,  5.97s/klasa, klasa=class_324, F1_klasy=0.6852, F1_macro=0.6934, drzewa=72]

[99]	valid_0's binary_logloss: 0.0197577
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.0198109
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.0199231
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.0200274
[1]	valid_0's binary_logloss: 0.090431
[2]	valid_0's binary_logloss: 0.0745788
[3]	valid_0's binary_logloss: 0.0658152
[4]	valid_0's binary_logloss: 0.0601915
[5]	valid_0's binary_logloss: 0.0563547
[6]	valid_0's binary_logloss: 0.0525788
[7]	valid_0's binary_logloss: 0.0497836
[8]	valid_0's binary_logloss: 0.0476986
[9]	valid_0's binary_logloss: 0.0457185
[10]	valid_0's binary_logloss: 0.0435547
[11]	valid_0's binary_logloss: 0.0417935
[12]	valid_0's binary_logloss: 0.0400807
[13]	valid_0's binary_logloss: 0.0385394
[14]	valid_0's binary_logloss: 0.0371265
[15]	valid_0's binary_logloss: 0.035709
[16]	valid_0's binary_logloss: 0.0344552
[17]	valid_0's binary_logloss: 0.0333136
[18]	valid_0's binary_logloss: 0.0323173
[19]	valid_0's binary_logloss: 0.0314387
[20]	valid_0's binary_logloss: 0.0305121
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0298398
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0290743
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.0283656
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0277561
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.0271917
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.0267813
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.0261913
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.0256796
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.0252516
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.024706
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.0242697
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.0237814
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.0234743
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.0230633
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.0227868
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.0224269
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.0221158
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.0218298
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.021574
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.0213897
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.0212658
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.0210888
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.020986
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.0207924
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.0206875
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.0204918
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.0204248
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.0203262
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.0202591
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.0201042
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.0199403
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.0198671
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.0198377
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.0197723
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.0197236
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.019544
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.0194676
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.0194149
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.0193431
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.0193169
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.0192254
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.0191737
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.0191651
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.0191668
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.0191707
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.019046
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.0190446
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.0189886
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.0190744
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.0190556
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.0189952
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.0189481
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.019
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.0190302
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.0190825
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.0191512
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.0191722
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.019265
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.0193556
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.0194325
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.0194921
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.0195147
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.0195755
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.0195988
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.019666
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.0196747
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.0197649
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.0197351
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.0197575
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.0197803
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.0197952
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.019834
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.0198787
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.0199352
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.0200012
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.0200268
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.0200177
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.0200528
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.0201066
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.0200977
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.0202008
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

Trening klas:  65%|██████▌   | 325/500 [38:26<17:24,  5.97s/klasa, klasa=class_325, F1_klasy=0.6496, F1_macro=0.6933, drzewa=72]




Trening klas:  65%|██████▌   | 326/500 [38:26<15:56,  5.50s/klasa, klasa=class_325, F1_klasy=0.6496, F1_macro=0.6933, drzewa=72]

[102]	valid_0's binary_logloss: 0.0202807
[1]	valid_0's binary_logloss: 0.0111019
[2]	valid_0's binary_logloss: 0.0105824
[3]	valid_0's binary_logloss: 0.0101535
[4]	valid_0's binary_logloss: 0.00975174
[5]	valid_0's binary_logloss: 0.00940869
[6]	valid_0's binary_logloss: 0.00986489
[7]	valid_0's binary_logloss: 0.00954974
[8]	valid_0's binary_logloss: 0.00922504
[9]	valid_0's binary_logloss: 0.00894805
[10]	valid_0's binary_logloss: 0.00856162
[11]	valid_0's binary_logloss: 0.00831702
[12]	valid_0's binary_logloss: 0.00804873
[13]	valid_0's binary_logloss: 0.00782896
[14]	valid_0's binary_logloss: 0.0075743
[15]	valid_0's binary_logloss: 0.00735137
[16]	valid_0's binary_logloss: 0.00710845
[17]	valid_0's binary_logloss: 0.0068915
[18]	valid_0's binary_logloss: 0.00665474
[19]	valid_0's binary_logloss: 0.00642853
[20]	valid_0's binary_logloss: 0.00621552
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.00606895
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.00587825
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.00569805
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.00552868
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.00538389
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.00519794
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.0050844
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.00495426
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.00480862
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.00470054
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.00456801
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.00445954
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.00434896
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.00422704
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.00411943
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.00403315
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.0039742
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.00385205
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.00375239
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.00365071
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.00358012
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.00353536
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.0034727
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.00341178
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.00336286
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.00327863
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.00321479
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.00310041
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.0030559
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.00297679
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.00293313
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.00291066
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.00287974
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.00285169
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.00280214
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.00276952
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.00271368
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.00267196
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.00263037
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.00259079
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.00257909
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.00254986
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.00253122
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.00252537
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.00250491
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.00243589
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.00238778
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.00235683
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.00234157
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.00230988
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.00226627
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.00220953
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.00215324
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.00215273
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.00213793
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.00211716
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.00210962
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.00209451
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.00207301
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.0020666
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.00206212
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.00205811
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.00202973
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.00202435
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.0020308
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.00202994
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.0020241
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.00200442
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.001999
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.00198007
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.00193204
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.00190539
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.00186891
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.00183566
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.00179903
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.00179798
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.00177005
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.00175063
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.001736
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.00173263
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.00171272
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.00172577
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.00170206
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.00167116
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.00166915
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.00165571
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.00165675
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.00162572
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.00162159
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.00160831
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.00160666
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 0.00161594
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 0.00161876
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 0.00160908
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 0.00161391
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[116]	valid_0's binary_logloss: 0.00161915
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[117]	valid_0's binary_logloss: 0.00160966
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[118]	valid_0's binary_logloss: 0.00162145
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[119]	valid_0's binary_logloss: 0.00161976
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[120]	valid_0's binary_logloss: 0.00161768
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[121]	valid_0's binary_logloss: 0.001617
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[122]	valid_0's binary_logloss: 0.00160953
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[123]	valid_0's binary_logloss: 0.00157144
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[124]	valid_0's binary_logloss: 0.00156897
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[125]	valid_0's binary_logloss: 0.00153534
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[126]	valid_0's binary_logloss: 0.00155518
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[127]	valid_0's binary_logloss: 0.00156371
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[128]	valid_0's binary_logloss: 0.00155496
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[129]	valid_0's binary_logloss: 0.00155364
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[130]	valid_0's binary_logloss: 0.00155313
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[131]	valid_0's binary_logloss: 0.00155492
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[132]	valid_0's binary_logloss: 0.00155638
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[133]	valid_0's binary_logloss: 0.00154928
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[134]	valid_0's binary_logloss: 0.00154573
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[135]	valid_0's binary_logloss: 0.0015523
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[136]	valid_0's binary_logloss: 0.00154894
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[137]	valid_0's binary_logloss: 0.00155458
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[138]	valid_0's binary_logloss: 0.00156402
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[139]	valid_0's binary_logloss: 0.00157128
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[140]	valid_0's binary_logloss: 0.0015791
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[141]	valid_0's binary_logloss: 0.0015501
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[142]	valid_0's binary_logloss: 0.00155434
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[143]	valid_0's binary_logloss: 0.00156114
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[144]	valid_0's binary_logloss: 0.00155619
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[145]	valid_0's binary_logloss: 0.0015671
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[146]	valid_0's binary_logloss: 0.00155781
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[147]	valid_0's binary_logloss: 0.00158176
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[148]	valid_0's binary_logloss: 0.00157834
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

Trening klas:  65%|██████▌   | 326/500 [38:32<15:56,  5.50s/klasa, klasa=class_326, F1_klasy=0.3333, F1_macro=0.6922, drzewa=125]




Trening klas:  65%|██████▌   | 327/500 [38:32<15:48,  5.48s/klasa, klasa=class_326, F1_klasy=0.3333, F1_macro=0.6922, drzewa=125]

[149]	valid_0's binary_logloss: 0.00157984
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[150]	valid_0's binary_logloss: 0.0015781
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[151]	valid_0's binary_logloss: 0.00156932
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[152]	valid_0's binary_logloss: 0.00156306
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[153]	valid_0's binary_logloss: 0.00156684
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[154]	valid_0's binary_logloss: 0.00157392
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[155]	valid_0's binary_logloss: 0.00157749
[1]	valid_0's binary_logloss: 0.332535
[2]	valid_0's binary_logloss: 0.282527
[3]	valid_0's binary_logloss: 0.265082
[4]	valid_0's binary_logloss: 0.253096
[5]	valid_0's binary_logloss: 0.243622
[6]	valid_0's binary_logloss: 0.320944
[7]	valid_0's binary_logloss: 0.30605
[8]	valid_0's binary_logloss: 0.291146
[9]	valid_0's binary_logloss: 0.282186
[10]	valid_0's binary_logloss: 0.274337
[11]	valid_0's binary_logloss: 0.266737
[12]	valid_0's binary_logloss: 0.259807
[13]	valid_0's binary_logloss: 0.250819
[14]	valid_0's binary_logloss: 0.244675
[15]	valid_0's binary_logloss: 0.238776
[16]	valid_0's binary_logloss: 0.23358
[17]	valid_0's binary_logloss: 0.228897
[18]	valid_0's binary_logloss: 0.224443
[19]	valid_0's binary_logloss: 0.220071
[20]	valid_0's binary_logloss: 0.216268
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.211745
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.208281
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.204493
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.20145
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.198439
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.19504
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.191842
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.188898
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.185258
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.182411
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.179633
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.17695
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.174434
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.1721
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.169543
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.167291
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.165048
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.162842
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.160694
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.158351
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.156214
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.154489
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.152774
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.150871
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.149217
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.147921
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.146058
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.144549
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.142852
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.141231
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.139564
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.138334
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.136967
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.135627
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.134449
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.132909
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.131732
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.130381
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.129082
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.127895
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.126699
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.125745
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.124841
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.123828
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.123081
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.122257
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.121387
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.120349
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.119454
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.118692
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.11779
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.116908
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.116099
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.115315
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.114671
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.113765
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.113053
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.112379
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.11166
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.11108
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.110491
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.110089
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.10974
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.109354
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.108846
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.108167
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.107487
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.106811
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.106205
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.105683
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.105158
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.104846
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.104354
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.10402
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.103682
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.103143
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.102795
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.102335
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.101864
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.101342
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.100767
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.100238
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.0998166
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.0993752
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.0988623
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.0983583
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.0979844
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.0975146
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.0971484
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.0967825
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.0964241
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 0.0961391
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 0.0959816
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 0.0957352
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 0.0955469
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[116]	valid_0's binary_logloss: 0.0953149
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[117]	valid_0's binary_logloss: 0.0950334
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[118]	valid_0's binary_logloss: 0.0947256
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[119]	valid_0's binary_logloss: 0.0945858
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[120]	valid_0's binary_logloss: 0.0944313
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[121]	valid_0's binary_logloss: 0.0942207
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[122]	valid_0's binary_logloss: 0.0940074
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[123]	valid_0's binary_logloss: 0.09377
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[124]	valid_0's binary_logloss: 0.0935891
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[125]	valid_0's binary_logloss: 0.0934906
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[126]	valid_0's binary_logloss: 0.093022
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[127]	valid_0's binary_logloss: 0.0927041
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[128]	valid_0's binary_logloss: 0.0923201
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[129]	valid_0's binary_logloss: 0.0920836
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[130]	valid_0's binary_logloss: 0.0917716
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[131]	valid_0's binary_logloss: 0.0916293
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[132]	valid_0's binary_logloss: 0.091442
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[133]	valid_0's binary_logloss: 0.091215
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[134]	valid_0's binary_logloss: 0.0910719
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[135]	valid_0's binary_logloss: 0.0908261
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[136]	valid_0's binary_logloss: 0.0905679
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[137]	valid_0's binary_logloss: 0.0902635
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[138]	valid_0's binary_logloss: 0.0901541
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[139]	valid_0's binary_logloss: 0.0898463
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[140]	valid_0's binary_logloss: 0.0896657
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[141]	valid_0's binary_logloss: 0.0895161
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[142]	valid_0's binary_logloss: 0.0894211
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[143]	valid_0's binary_logloss: 0.0893267
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[144]	valid_0's binary_logloss: 0.0893795
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[145]	valid_0's binary_logloss: 0.0893722
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[146]	valid_0's binary_logloss: 0.0893162
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[147]	valid_0's binary_logloss: 0.0891786
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[148]	valid_0's binary_logloss: 0.0891583
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[149]	valid_0's binary_logloss: 0.0891763
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[150]	valid_0's binary_logloss: 0.0891456
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[151]	valid_0's binary_logloss: 0.0891629
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[152]	valid_0's binary_logloss: 0.0891023
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[153]	valid_0's binary_logloss: 0.0890662
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[154]	valid_0's binary_logloss: 0.0890761
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[155]	valid_0's binary_logloss: 0.0889954
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[156]	valid_0's binary_logloss: 0.0889306
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[157]	valid_0's binary_logloss: 0.0889432
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[158]	valid_0's binary_logloss: 0.0888159
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[159]	valid_0's binary_logloss: 0.0887881
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[160]	valid_0's binary_logloss: 0.0886509
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[161]	valid_0's binary_logloss: 0.0886533
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[162]	valid_0's binary_logloss: 0.0887255
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[163]	valid_0's binary_logloss: 0.0886325
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[164]	valid_0's binary_logloss: 0.0887881
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[165]	valid_0's binary_logloss: 0.0888624
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[166]	valid_0's binary_logloss: 0.0889211
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[167]	valid_0's binary_logloss: 0.0890482
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[168]	valid_0's binary_logloss: 0.0891604
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[169]	valid_0's binary_logloss: 0.0891753
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[170]	valid_0's binary_logloss: 0.089125
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[171]	valid_0's binary_logloss: 0.0890643
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[172]	valid_0's binary_logloss: 0.0889195
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[173]	valid_0's binary_logloss: 0.0888646
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[174]	valid_0's binary_logloss: 0.0888627
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[175]	valid_0's binary_logloss: 0.088854
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[176]	valid_0's binary_logloss: 0.0889544
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[177]	valid_0's binary_logloss: 0.0890541
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[178]	valid_0's binary_logloss: 0.0890318
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[179]	valid_0's binary_logloss: 0.0890913

Trening klas:  65%|██████▌   | 327/500 [38:39<15:48,  5.48s/klasa, klasa=class_327, F1_klasy=0.4955, F1_macro=0.6916, drzewa=163]




Trening klas:  66%|██████▌   | 328/500 [38:39<17:16,  6.03s/klasa, klasa=class_327, F1_klasy=0.4955, F1_macro=0.6916, drzewa=163]

[1]	valid_0's binary_logloss: 0.509225
[2]	valid_0's binary_logloss: 0.279948
[3]	valid_0's binary_logloss: 0.273856
[4]	valid_0's binary_logloss: 0.264976
[5]	valid_0's binary_logloss: 0.25839
[6]	valid_0's binary_logloss: 0.392174
[7]	valid_0's binary_logloss: 0.38545
[8]	valid_0's binary_logloss: 0.382878
[9]	valid_0's binary_logloss: 0.378957
[10]	valid_0's binary_logloss: 0.376271
[11]	valid_0's binary_logloss: 0.37579
[12]	valid_0's binary_logloss: 0.372994
[13]	valid_0's binary_logloss: 0.371417
[14]	valid_0's binary_logloss: 0.370495
[15]	valid_0's binary_logloss: 0.36981
[16]	valid_0's binary_logloss: 0.369212
[17]	valid_0's binary_logloss: 0.36689
[18]	valid_0's binary_logloss: 0.365902
[19]	valid_0's binary_logloss: 0.364397
[20]	valid_0's binary_logloss: 0.36317
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.362651
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.361483
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.360271
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.359919
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.358917
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.358137
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.356944
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.356253
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.355569
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.354863
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.353618
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

Trening klas:  66%|██████▌   | 328/500 [38:42<17:16,  6.03s/klasa, klasa=class_328, F1_klasy=0.3210, F1_macro=0.6904, drzewa=5]




Trening klas:  66%|██████▌   | 329/500 [38:42<14:55,  5.24s/klasa, klasa=class_328, F1_klasy=0.3210, F1_macro=0.6904, drzewa=5]

[32]	valid_0's binary_logloss: 0.351098
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.349744
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.348962
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.348613
[1]	valid_0's binary_logloss: 0.442022
[2]	valid_0's binary_logloss: 0.343831
[3]	valid_0's binary_logloss: 0.3108
[4]	valid_0's binary_logloss: 0.279779
[5]	valid_0's binary_logloss: 0.263407
[6]	valid_0's binary_logloss: 0.275579
[7]	valid_0's binary_logloss: 0.25977
[8]	valid_0's binary_logloss: 0.248804
[9]	valid_0's binary_logloss: 0.242096
[10]	valid_0's binary_logloss: 0.235796
[11]	valid_0's binary_logloss: 0.23464
[12]	valid_0's binary_logloss: 0.228752
[13]	valid_0's binary_logloss: 0.223816
[14]	valid_0's binary_logloss: 0.219392
[15]	valid_0's binary_logloss: 0.21466
[16]	valid_0's binary_logloss: 0.211287
[17]	valid_0's binary_logloss: 0.207868
[18]	valid_0's binary_logloss: 0.203796
[19]	valid_0's binary_logloss: 0.201282
[20]	valid_0's binary_logloss: 0.198735
[21]	valid_0's binary_logloss: 0.195896
[22]	valid_0's binary_logloss: 0.191707
[23]	valid_0's binary_logloss: 0.188921
[24]	valid_0's binary_logloss: 0.185356
[25]	valid_0's binary_logloss: 0.182489
[26]	valid_0's binary_logloss: 0.18081
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.178403
[28]	valid_0's binary_logloss: 0.175627
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.17406
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.17212
[31]	valid_0's binary_logloss: 0.169934
[32]	valid_0's binary_logloss: 0.167516
[33]	valid_0's binary_logloss: 0.165543
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.1642
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.162841
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.161105
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.159668
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.158114
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.156634
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.155368
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.153528
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.151826
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.150034
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.148778
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.147558
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.1462
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.144993
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.144128
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.143114
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.14203
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.141131
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.140091
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.138955
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.137999
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.137367
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.136124
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.134946
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.13378
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.132589
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.131747
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.131188
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.130412
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.129676
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.129098
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.128548
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.127598
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.126966
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.12631
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.125553
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.125033
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.124098
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.123536
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.122644
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.122161
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.121336
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.120973
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.120385
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.119635
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.119052
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.118814
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.118166
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.117643
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.117186
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.116592
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.116372
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.115779
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.115171
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.114676
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.114177
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.113846
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.113439
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.113187
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.112709
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.112556
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.112049
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.111681
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.111618
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.11143
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.111322
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.111062
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.110652
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.110358
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.110081
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.109827
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.10964
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.109269
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.109073
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.108884
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.108762
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.108586
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.108248
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 0.108074
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 0.10786
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 0.107596
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 0.107199
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[116]	valid_0's binary_logloss: 0.107094
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[117]	valid_0's binary_logloss: 0.106841
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[118]	valid_0's binary_logloss: 0.106639
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[119]	valid_0's binary_logloss: 0.106417
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[120]	valid_0's binary_logloss: 0.106303
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[121]	valid_0's binary_logloss: 0.106199
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[122]	valid_0's binary_logloss: 0.106125
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[123]	valid_0's binary_logloss: 0.105936
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[124]	valid_0's binary_logloss: 0.105673
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[125]	valid_0's binary_logloss: 0.105518
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[126]	valid_0's binary_logloss: 0.105299
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[127]	valid_0's binary_logloss: 0.105081
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[128]	valid_0's binary_logloss: 0.104882
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[129]	valid_0's binary_logloss: 0.104667
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[130]	valid_0's binary_logloss: 0.104563
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[131]	valid_0's binary_logloss: 0.104223
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[132]	valid_0's binary_logloss: 0.103954
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[133]	valid_0's binary_logloss: 0.103904
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[134]	valid_0's binary_logloss: 0.10374
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[135]	valid_0's binary_logloss: 0.103678
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[136]	valid_0's binary_logloss: 0.103601
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[137]	valid_0's binary_logloss: 0.103601
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[138]	valid_0's binary_logloss: 0.103599
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[139]	valid_0's binary_logloss: 0.103449
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[140]	valid_0's binary_logloss: 0.103386
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[141]	valid_0's binary_logloss: 0.103266
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[142]	valid_0's binary_logloss: 0.103175
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[143]	valid_0's binary_logloss: 0.103115
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[144]	valid_0's binary_logloss: 0.103109
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[145]	valid_0's binary_logloss: 0.103052
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[146]	valid_0's binary_logloss: 0.102881
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[147]	valid_0's binary_logloss: 0.102729
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[148]	valid_0's binary_logloss: 0.102547
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[149]	valid_0's binary_logloss: 0.102446
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[150]	valid_0's binary_logloss: 0.102344
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[151]	valid_0's binary_logloss: 0.102333
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[152]	valid_0's binary_logloss: 0.102297
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[153]	valid_0's binary_logloss: 0.102165
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[154]	valid_0's binary_logloss: 0.102063
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[155]	valid_0's binary_logloss: 0.101916
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[156]	valid_0's binary_logloss: 0.101776
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[157]	valid_0's binary_logloss: 0.101721
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[158]	valid_0's binary_logloss: 0.10165
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[159]	valid_0's binary_logloss: 0.101694
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[160]	valid_0's binary_logloss: 0.101788
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[161]	valid_0's binary_logloss: 0.10172
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[162]	valid_0's binary_logloss: 0.101621
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[163]	valid_0's binary_logloss: 0.101558
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[164]	valid_0's binary_logloss: 0.10154
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[165]	valid_0's binary_logloss: 0.101528
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[166]	valid_0's binary_logloss: 0.10144
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[167]	valid_0's binary_logloss: 0.101374
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[168]	valid_0's binary_logloss: 0.101287
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[169]	valid_0's binary_logloss: 0.101169
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[170]	valid_0's binary_logloss: 0.101101
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[171]	valid_0's binary_logloss: 0.100896
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[172]	valid_0's binary_logloss: 0.100866
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[173]	valid_0's binary_logloss: 0.100836
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[174]	valid_0's binary_logloss: 0.100649
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[175]	valid_0's binary_logloss: 0.100567
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[176]	valid_0's binary_logloss: 0.100553
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[177]	valid_0's binary_logloss: 0.100525
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[178]	valid_0's binary_logloss: 0.100512
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[179]	valid_0's binary_logloss: 0.100532
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[180]	valid_0's binary_logloss: 0.100548
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[181]	valid_0's binary_logloss: 0.100292
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[182]	valid_0's binary_logloss: 0.100065
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[183]	valid_0's binary_logloss: 0.100054
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[184]	valid_0's binary_logloss: 0.0999287
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[185]	valid_0's binary_logloss: 0.0998909
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[186]	valid_0's binary_logloss: 0.0998525
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[187]	valid_0's binary_logloss: 0.0998824
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[188]	valid_0's binary_logloss: 0.0998658
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[189]	valid_0's binary_logloss: 0.0999307

Trening klas:  66%|██████▌   | 329/500 [38:56<14:55,  5.24s/klasa, klasa=class_329, F1_klasy=0.4587, F1_macro=0.6897, drzewa=300]




Trening klas:  66%|██████▌   | 330/500 [38:56<22:01,  7.77s/klasa, klasa=class_329, F1_klasy=0.4587, F1_macro=0.6897, drzewa=300]

[1]	valid_0's binary_logloss: 0.0132324
[2]	valid_0's binary_logloss: 0.0127962
[3]	valid_0's binary_logloss: 0.0124072
[4]	valid_0's binary_logloss: 0.0118832
[5]	valid_0's binary_logloss: 0.0113609
[6]	valid_0's binary_logloss: 0.0109244
[7]	valid_0's binary_logloss: 0.0104759
[8]	valid_0's binary_logloss: 0.0100381
[9]	valid_0's binary_logloss: 0.00962456
[10]	valid_0's binary_logloss: 0.00927051
[11]	valid_0's binary_logloss: 0.0088771
[12]	valid_0's binary_logloss: 0.0084746
[13]	valid_0's binary_logloss: 0.00818262
[14]	valid_0's binary_logloss: 0.00788967
[15]	valid_0's binary_logloss: 0.00760863
[16]	valid_0's binary_logloss: 0.00730979
[17]	valid_0's binary_logloss: 0.00698539
[18]	valid_0's binary_logloss: 0.00672958
[19]	valid_0's binary_logloss: 0.00647859
[20]	valid_0's binary_logloss: 0.00624371
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0059794
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0057352
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.00549675
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0053153
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.00510497
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.00490027
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.00473675
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.00457608
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.0043905
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.0042331
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.00407285
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.00392598
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.00379344
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.00366413
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.00353715
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.00342329
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.00331397
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.00321174
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.00311702
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.00302401
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.00292394
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.00282048
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.00274317
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.00266174
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.00259943
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.00251535
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.00244965
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.00238691
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.00232511
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.00227734
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.00222253
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.00217418
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.0021272
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.00208205
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.00203325
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.00198798
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.0019425
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.00190105
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.00186301
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.00182675
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.00178015
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.0017446
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.00169557
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.00167704
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.00162963
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.00160027
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.00155836
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.00153251
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.00151064
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.00148822
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.0014611
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.00143792
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.00141905
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.00137878
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.00136151
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.00135868
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.00135766
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.00135822
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.00134787
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.00134907
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.00132126
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.00131258
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.0012988
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.00128495
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.00127217
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.00125255
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.00122904
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.00121271
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.00122046
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.00122169
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.00121442
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.00120946
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.00121328
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.00122813
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.00120872
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.00118956
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.00116956
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.00115203
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.00114504
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.00113823
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.00113545
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.00113579
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.00111505
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.00109996
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.00109965
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.00109402
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.00108763
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.00107889
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.0010717
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.00106636
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.00106941
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 0.00106978
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 0.00107311
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 0.00107594
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 0.00108705
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[116]	valid_0's binary_logloss: 0.00109025
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[117]	valid_0's binary_logloss: 0.00109388
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[118]	valid_0's binary_logloss: 0.00109569
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[119]	valid_0's binary_logloss: 0.00108356
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[120]	valid_0's binary_logloss: 0.0010868
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[121]	valid_0's binary_logloss: 0.00108365
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[122]	valid_0's binary_logloss: 0.00109511
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[123]	valid_0's binary_logloss: 0.00109322
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[124]	valid_0's binary_logloss: 0.00110691
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[125]	valid_0's binary_logloss: 0.00111825
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[126]	valid_0's binary_logloss: 0.00112013
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[127]	valid_0's binary_logloss: 0.00111888
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[128]	valid_0's binary_logloss: 0.00110047
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[129]	valid_0's binary_logloss: 0.00116392
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[130]	valid_0's binary_logloss: 0.00115036
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[131]	valid_0's binary_logloss: 0.00113904
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[132]	valid_0's binary_logloss: 0.00115014
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[133]	valid_0's binary_logloss: 0.00115698
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

Trening klas:  66%|██████▌   | 330/500 [39:00<22:01,  7.77s/klasa, klasa=class_330, F1_klasy=0.0000, F1_macro=0.6877, drzewa=110]




Trening klas:  66%|██████▌   | 331/500 [39:00<18:56,  6.73s/klasa, klasa=class_330, F1_klasy=0.0000, F1_macro=0.6877, drzewa=110]

[134]	valid_0's binary_logloss: 0.00115156
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[135]	valid_0's binary_logloss: 0.00114118
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[136]	valid_0's binary_logloss: 0.00119686
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[137]	valid_0's binary_logloss: 0.00120951
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[138]	valid_0's binary_logloss: 0.00126475
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[139]	valid_0's binary_logloss: 0.00126674
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[140]	valid_0's binary_logloss: 0.00127492
[1]	valid_0's binary_logloss: 0.35058
[2]	valid_0's binary_logloss: 0.236971
[3]	valid_0's binary_logloss: 0.22797
[4]	valid_0's binary_logloss: 0.218487
[5]	valid_0's binary_logloss: 0.212406
[6]	valid_0's binary_logloss: 0.205891
[7]	valid_0's binary_logloss: 0.201207
[8]	valid_0's binary_logloss: 0.196797
[9]	valid_0's binary_logloss: 0.193412
[10]	valid_0's binary_logloss: 0.19001
[11]	valid_0's binary_logloss: 0.187354
[12]	valid_0's binary_logloss: 0.184288
[13]	valid_0's binary_logloss: 0.181885
[14]	valid_0's binary_logloss: 0.179548
[15]	valid_0's binary_logloss: 0.177367
[16]	valid_0's binary_logloss: 0.17555
[17]	valid_0's binary_logloss: 0.173725
[18]	valid_0's binary_logloss: 0.171619
[19]	valid_0's binary_logloss: 0.169769
[20]	valid_0's binary_logloss: 0.168201
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.166486
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.164551
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.162919
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.161405
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.160014
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.158622
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.156998
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.155639
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.154267
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.152972
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.151709
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.150689
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.149547
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.148414
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.147309
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.146196
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.144846
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.143658
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.142433
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.14125
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.140294
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.139329
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.138255
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.137448
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.136483
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.135623
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.134699
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.13382
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.132843
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.132026
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.131223
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.130383
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.129499
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.128743
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.127854
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.126899
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.125996
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.125081
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.124466
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.123845
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.123259
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.122609
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.121993
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.121248
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.120606
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.119795
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.119452
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.118864
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.118309
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.117483
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.117026
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.116495
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.115826
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.115287
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.114682
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.114154
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.113447
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.112966
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.11241
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.112005
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.111686
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.111497
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.11127
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.110933
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.110557
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.110259
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.109942
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.109643
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.10941
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.109247
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.108908
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.108717
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.108415
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.108125
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.107843
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.107596
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.107388
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.107113
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.106827
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.106554
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.106224
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.10587
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.105532
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.105412
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.105063
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.10496
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.104849
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.104857
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.104745
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.104763
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.104632
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 0.104207
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 0.10403
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 0.103947
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 0.103845
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[116]	valid_0's binary_logloss: 0.103635
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[117]	valid_0's binary_logloss: 0.103473
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[118]	valid_0's binary_logloss: 0.103367
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[119]	valid_0's binary_logloss: 0.103299
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[120]	valid_0's binary_logloss: 0.103135
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[121]	valid_0's binary_logloss: 0.103009
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[122]	valid_0's binary_logloss: 0.102878
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[123]	valid_0's binary_logloss: 0.102741
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[124]	valid_0's binary_logloss: 0.102645
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[125]	valid_0's binary_logloss: 0.102492
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[126]	valid_0's binary_logloss: 0.102402
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[127]	valid_0's binary_logloss: 0.10232
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[128]	valid_0's binary_logloss: 0.102266
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[129]	valid_0's binary_logloss: 0.102206
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[130]	valid_0's binary_logloss: 0.102058
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[131]	valid_0's binary_logloss: 0.102131
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[132]	valid_0's binary_logloss: 0.102165
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[133]	valid_0's binary_logloss: 0.102133
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[134]	valid_0's binary_logloss: 0.102162
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[135]	valid_0's binary_logloss: 0.102264
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[136]	valid_0's binary_logloss: 0.102287
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[137]	valid_0's binary_logloss: 0.10218
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[138]	valid_0's binary_logloss: 0.102123
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[139]	valid_0's binary_logloss: 0.102019
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[140]	valid_0's binary_logloss: 0.101867
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[141]	valid_0's binary_logloss: 0.101943
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[142]	valid_0's binary_logloss: 0.101982
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[143]	valid_0's binary_logloss: 0.102012
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[144]	valid_0's binary_logloss: 0.102086
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[145]	valid_0's binary_logloss: 0.102093
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[146]	valid_0's binary_logloss: 0.102088
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[147]	valid_0's binary_logloss: 0.101887
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[148]	valid_0's binary_logloss: 0.10195
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[149]	valid_0's binary_logloss: 0.101746
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[150]	valid_0's binary_logloss: 0.101666
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[151]	valid_0's binary_logloss: 0.101584
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[152]	valid_0's binary_logloss: 0.101513
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[153]	valid_0's binary_logloss: 0.101455
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[154]	valid_0's binary_logloss: 0.101517
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[155]	valid_0's binary_logloss: 0.101575
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[156]	valid_0's binary_logloss: 0.101662
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[157]	valid_0's binary_logloss: 0.101751
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[158]	valid_0's binary_logloss: 0.101858
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[159]	valid_0's binary_logloss: 0.101826
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[160]	valid_0's binary_logloss: 0.101855
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[161]	valid_0's binary_logloss: 0.101822
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[162]	valid_0's binary_logloss: 0.101864
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[163]	valid_0's binary_logloss: 0.101883
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[164]	valid_0's binary_logloss: 0.101894
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[165]	valid_0's binary_logloss: 0.101826
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[166]	valid_0's binary_logloss: 0.101876
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[167]	valid_0's binary_logloss: 0.101854
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[168]	valid_0's binary_logloss: 0.101818
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[169]	valid_0's binary_logloss: 0.101852
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[170]	valid_0's binary_logloss: 0.101791
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[171]	valid_0's binary_logloss: 0.10176
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[172]	valid_0's binary_logloss: 0.101713
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[173]	valid_0's binary_logloss: 0.101624
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[174]	valid_0's binary_logloss: 0.101595
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[175]	valid_0's binary_logloss: 0.101498
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[176]	valid_0's binary_logloss: 0.10145
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[177]	valid_0's binary_logloss: 0.1014
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[178]	valid_0's binary_logloss: 0.101415
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[179]	valid_0's binary_logloss: 0.101444
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

Trening klas:  66%|██████▌   | 331/500 [39:10<18:56,  6.73s/klasa, klasa=class_331, F1_klasy=0.4907, F1_macro=0.6871, drzewa=300]




Trening klas:  66%|██████▋   | 332/500 [39:10<21:25,  7.65s/klasa, klasa=class_331, F1_klasy=0.4907, F1_macro=0.6871, drzewa=300]

[1]	valid_0's binary_logloss: 0.080079
[2]	valid_0's binary_logloss: 0.0737935
[3]	valid_0's binary_logloss: 0.0695758
[4]	valid_0's binary_logloss: 0.0657771
[5]	valid_0's binary_logloss: 0.0624175
[6]	valid_0's binary_logloss: 0.0599229
[7]	valid_0's binary_logloss: 0.0579045
[8]	valid_0's binary_logloss: 0.0561105
[9]	valid_0's binary_logloss: 0.0544675
[10]	valid_0's binary_logloss: 0.0526432
[11]	valid_0's binary_logloss: 0.0550894
[12]	valid_0's binary_logloss: 0.0538369
[13]	valid_0's binary_logloss: 0.0528285
[14]	valid_0's binary_logloss: 0.0518425
[15]	valid_0's binary_logloss: 0.0507549
[16]	valid_0's binary_logloss: 0.0497782
[17]	valid_0's binary_logloss: 0.0490194
[18]	valid_0's binary_logloss: 0.0476888
[19]	valid_0's binary_logloss: 0.0466658
[20]	valid_0's binary_logloss: 0.0458693
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0447086
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0436974
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.0428763
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0421259
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.0413237
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.0404702
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.0398091
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.0390357
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.0383173
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.0377176
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.0370577
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.0364467
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.035788
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.0353605
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.0348417
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.0343594
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.0340926
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.0339062
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.0335586
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.0333898
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.0329596
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.0327184
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.0323961
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.0321235
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.0318308
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.0316428
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.0314217
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.0312137
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.0310077
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.0307254
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.0305468
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.0303024
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.0302218
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.0302027
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.030016
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.0300067
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.0298467
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.0296877
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.0296451
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.0294979
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.0293426
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.0292109
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.0291187
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.0290001
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.0288934
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.0288186
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.0287288
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.0286246
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.0284837
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.0283574
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.0282886
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.0281812
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.0280864
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.0280137
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.0279851
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.0279387
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.0278928
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.0279129
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.0278184
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.0277603
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.0276569
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.0276346
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.0275425
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.0275334
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.0274093
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.0273223
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.0272963
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.0272175
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.0272549
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.0270941
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.0269794
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.0269523
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.0269603
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.026848
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.0267891
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.026725
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.0266736
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.0266228
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.026573
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.0265385
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.0265215
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.0265333
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.0265444
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.0266239
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.0265953
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.0266091
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.0265801
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.0265903
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.0266122
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.0265899
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.0266185
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 0.0266392
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 0.0265963
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 0.0266129
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 0.0266055
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[116]	valid_0's binary_logloss: 0.0265555
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[117]	valid_0's binary_logloss: 0.0264989
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[118]	valid_0's binary_logloss: 0.0264849
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[119]	valid_0's binary_logloss: 0.0265134
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[120]	valid_0's binary_logloss: 0.0264602
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[121]	valid_0's binary_logloss: 0.0263845
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[122]	valid_0's binary_logloss: 0.0263228
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[123]	valid_0's binary_logloss: 0.0262661
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[124]	valid_0's binary_logloss: 0.0262675
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[125]	valid_0's binary_logloss: 0.0262237
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[126]	valid_0's binary_logloss: 0.0262004
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[127]	valid_0's binary_logloss: 0.0261906
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[128]	valid_0's binary_logloss: 0.0261759
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[129]	valid_0's binary_logloss: 0.0261469
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[130]	valid_0's binary_logloss: 0.0261101
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[131]	valid_0's binary_logloss: 0.0261336
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[132]	valid_0's binary_logloss: 0.0261571
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[133]	valid_0's binary_logloss: 0.0261898
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[134]	valid_0's binary_logloss: 0.0261635
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[135]	valid_0's binary_logloss: 0.0261505
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[136]	valid_0's binary_logloss: 0.0261802
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[137]	valid_0's binary_logloss: 0.0261984
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[138]	valid_0's binary_logloss: 0.0262379
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[139]	valid_0's binary_logloss: 0.0263008
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[140]	valid_0's binary_logloss: 0.0262675
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[141]	valid_0's binary_logloss: 0.0262588
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[142]	valid_0's binary_logloss: 0.0262439
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[143]	valid_0's binary_logloss: 0.0262645
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[144]	valid_0's binary_logloss: 0.0262848
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[145]	valid_0's binary_logloss: 0.0263185
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[146]	valid_0's binary_logloss: 0.0263476
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[147]	valid_0's binary_logloss: 0.0263827
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[148]	valid_0's binary_logloss: 0.0264156
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[149]	valid_0's binary_logloss: 0.0263837
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[150]	valid_0's binary_logloss: 0.0263814
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[151]	valid_0's binary_logloss: 0.0264101
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[152]	valid_0's binary_logloss: 0.0264466
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[153]	valid_0's binary_logloss: 0.0264549
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[154]	valid_0's binary_logloss: 0.0264836
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[155]	valid_0's binary_logloss: 0.0265055
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[156]	valid_0's binary_logloss: 0.0265151
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[157]	valid_0's binary_logloss: 0.0265138
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[158]	valid_0's binary_logloss: 0.0265346
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

Trening klas:  66%|██████▋   | 332/500 [39:18<21:25,  7.65s/klasa, klasa=class_332, F1_klasy=0.5634, F1_macro=0.6867, drzewa=130]




Trening klas:  67%|██████▋   | 333/500 [39:18<21:16,  7.65s/klasa, klasa=class_332, F1_klasy=0.5634, F1_macro=0.6867, drzewa=130]

[159]	valid_0's binary_logloss: 0.0265348
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[160]	valid_0's binary_logloss: 0.0265739
[1]	valid_0's binary_logloss: 0.0229435
[2]	valid_0's binary_logloss: 0.0218605
[3]	valid_0's binary_logloss: 0.0208506
[4]	valid_0's binary_logloss: 0.0199867
[5]	valid_0's binary_logloss: 0.0190987
[6]	valid_0's binary_logloss: 0.0232932
[7]	valid_0's binary_logloss: 0.0223877
[8]	valid_0's binary_logloss: 0.0215304
[9]	valid_0's binary_logloss: 0.0207488
[10]	valid_0's binary_logloss: 0.0200256
[11]	valid_0's binary_logloss: 0.0193087
[12]	valid_0's binary_logloss: 0.0186363
[13]	valid_0's binary_logloss: 0.0180145
[14]	valid_0's binary_logloss: 0.0174435
[15]	valid_0's binary_logloss: 0.0168048
[16]	valid_0's binary_logloss: 0.0162532
[17]	valid_0's binary_logloss: 0.0157584
[18]	valid_0's binary_logloss: 0.0152205
[19]	valid_0's binary_logloss: 0.0147428
[20]	valid_0's binary_logloss: 0.0143539
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0138493
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.013364
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.0128927
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.012414
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.0119585
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.0115453
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.0111768
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.0108483
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.0105215
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.0102275
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.00987126
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.00954458
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.00925169
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.00897336
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.00872442
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.00846417
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.00820194
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.00796731
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.00774234
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.00751884
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.00730036
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.00710319
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.00690974
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.00670285
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.00652934
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.00637753
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.00622061
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.00607114
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.00594738
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.00580791
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.00566814
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.00553928
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.00540457
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.00528555
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.00518529
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.00506026
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.00497574
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.00488927
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.0048246
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.00475568
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.00465593
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.00458084
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.00450408
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.00445126
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.00441383
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.00436024
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.00429821
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.00425141
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.00421714
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.00418043
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.00411986
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.00407153
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.00402655
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.0039608
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.00391111
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.00387082
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.00382288
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.00378071
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.00373201
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.00370366
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.00368204
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.00363997
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.00361374
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.00358207
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.00357247
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.00353569
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.00350162
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.00345778
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.00343982
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.00339211
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.00337112
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.00334969
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.00334403
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.00333929
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.00334287
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.0033086
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.00326891
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.00323747
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.00319864
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.00316284
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.00315231
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.00312631
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.00310237
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.00306818
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.00305973
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.00305271
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.00304425
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.00303881
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.00300755
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.00298086
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.0029812
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 0.00296811
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 0.00297359
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 0.0029722
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 0.00297226
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[116]	valid_0's binary_logloss: 0.0029631
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[117]	valid_0's binary_logloss: 0.00294325
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[118]	valid_0's binary_logloss: 0.00294563
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[119]	valid_0's binary_logloss: 0.00294684
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[120]	valid_0's binary_logloss: 0.00292996
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[121]	valid_0's binary_logloss: 0.00292427
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[122]	valid_0's binary_logloss: 0.00291941
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[123]	valid_0's binary_logloss: 0.00290919
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[124]	valid_0's binary_logloss: 0.0029005
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[125]	valid_0's binary_logloss: 0.00289821
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[126]	valid_0's binary_logloss: 0.00288985
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[127]	valid_0's binary_logloss: 0.00287534
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[128]	valid_0's binary_logloss: 0.00286621
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[129]	valid_0's binary_logloss: 0.00285659
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[130]	valid_0's binary_logloss: 0.00284361
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[131]	valid_0's binary_logloss: 0.00283236
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[132]	valid_0's binary_logloss: 0.00282494
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[133]	valid_0's binary_logloss: 0.00281985
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[134]	valid_0's binary_logloss: 0.00282455
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[135]	valid_0's binary_logloss: 0.00281927
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[136]	valid_0's binary_logloss: 0.00280587
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[137]	valid_0's binary_logloss: 0.00280939
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[138]	valid_0's binary_logloss: 0.00279591
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[139]	valid_0's binary_logloss: 0.002791
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[140]	valid_0's binary_logloss: 0.00277859
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[141]	valid_0's binary_logloss: 0.00278358
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[142]	valid_0's binary_logloss: 0.00279045
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[143]	valid_0's binary_logloss: 0.00278929
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[144]	valid_0's binary_logloss: 0.00278928
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[145]	valid_0's binary_logloss: 0.00278712
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[146]	valid_0's binary_logloss: 0.00278308
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[147]	valid_0's binary_logloss: 0.00278821
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[148]	valid_0's binary_logloss: 0.00279987
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[149]	valid_0's binary_logloss: 0.00280493
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[150]	valid_0's binary_logloss: 0.00282282
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[151]	valid_0's binary_logloss: 0.00282047
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[152]	valid_0's binary_logloss: 0.00282313
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[153]	valid_0's binary_logloss: 0.00282469
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[154]	valid_0's binary_logloss: 0.00282734
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[155]	valid_0's binary_logloss: 0.00283102
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[156]	valid_0's binary_logloss: 0.00283538
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[157]	valid_0's binary_logloss: 0.00283963
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[158]	valid_0's binary_logloss: 0.00283737
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[159]	valid_0's binary_logloss: 0.00283665
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[160]	valid_0's binary_logloss: 0.00283697
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[161]	valid_0's binary_logloss: 0.00283297
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[162]	valid_0's binary_logloss: 0.00284716
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[163]	valid_0's binary_logloss: 0.00285591
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[164]	valid_0's binary_logloss: 0.0028574
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

Trening klas:  67%|██████▋   | 333/500 [39:25<21:16,  7.65s/klasa, klasa=class_333, F1_klasy=0.0000, F1_macro=0.6846, drzewa=140]




Trening klas:  67%|██████▋   | 334/500 [39:25<21:05,  7.62s/klasa, klasa=class_333, F1_klasy=0.0000, F1_macro=0.6846, drzewa=140]

[165]	valid_0's binary_logloss: 0.00286719
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[166]	valid_0's binary_logloss: 0.00286084
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[167]	valid_0's binary_logloss: 0.00285214
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[168]	valid_0's binary_logloss: 0.00285249
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[169]	valid_0's binary_logloss: 0.00285838
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[170]	valid_0's binary_logloss: 0.00285564
[1]	valid_0's binary_logloss: 0.143391
[2]	valid_0's binary_logloss: 0.0984486
[3]	valid_0's binary_logloss: 0.0926128
[4]	valid_0's binary_logloss: 0.0873087
[5]	valid_0's binary_logloss: 0.082854
[6]	valid_0's binary_logloss: 0.0798829
[7]	valid_0's binary_logloss: 0.0776844
[8]	valid_0's binary_logloss: 0.0755324
[9]	valid_0's binary_logloss: 0.0733687
[10]	valid_0's binary_logloss: 0.0715583
[11]	valid_0's binary_logloss: 0.0700583
[12]	valid_0's binary_logloss: 0.0687135
[13]	valid_0's binary_logloss: 0.0672013
[14]	valid_0's binary_logloss: 0.0658692
[15]	valid_0's binary_logloss: 0.0647467
[16]	valid_0's binary_logloss: 0.0633338
[17]	valid_0's binary_logloss: 0.062259
[18]	valid_0's binary_logloss: 0.0614173
[19]	valid_0's binary_logloss: 0.0602591
[20]	valid_0's binary_logloss: 0.0587886
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0578972
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0572662
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.0563512
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0553411
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.0544923
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.0534557
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.0526956
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.0515575
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.0508012
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.0498687
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.0489566
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.0483898
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.0476262
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.0470458
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.0463743
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.0458431
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.0452773
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.0447372
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.0443462
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.0437796
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.0434709
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.0433713
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.0429704
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.0423731
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.0418972
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.0415198
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.0412215
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.0409135
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.0405573
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.0402241
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.0398345
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.0395173
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.0392389
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.0387919
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.0383665
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.0380369
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.037642
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.037287
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.0370555
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.0367556
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.0365268
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.036254
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.0360595
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.0357919
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.0355294
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.0352676
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.035066
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.0349048
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.0346603
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.0345256
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.0343867
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.034154
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.0337929
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.0336532
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.0335157
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.0335741
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.0335903
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.0333915
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.0332428
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.0329723
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.0329143
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.0327585
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.0326669
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.0325202
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.0324937
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.0323139
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.0321928
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.0320445
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.0318365
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.0316071
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.0316192
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.0314974
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.0313485
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.0312507
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.0310882
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.0309792
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.0308972
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.0308761
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.0307386
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.0306701
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.0305275
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.0304817
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.0303656
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.0302258
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.0301795
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.0300502
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.0299212
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.0298462
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.0297701
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.0296105
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.0294735
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 0.0293155
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 0.0292546
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 0.029172
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 0.0290905
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[116]	valid_0's binary_logloss: 0.0290395
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[117]	valid_0's binary_logloss: 0.0290602
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[118]	valid_0's binary_logloss: 0.0289777
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[119]	valid_0's binary_logloss: 0.0288855
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[120]	valid_0's binary_logloss: 0.0289089
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[121]	valid_0's binary_logloss: 0.028844
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[122]	valid_0's binary_logloss: 0.0288403
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[123]	valid_0's binary_logloss: 0.0288564
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[124]	valid_0's binary_logloss: 0.0288561
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[125]	valid_0's binary_logloss: 0.0288473
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[126]	valid_0's binary_logloss: 0.0289234
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[127]	valid_0's binary_logloss: 0.0289595
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[128]	valid_0's binary_logloss: 0.0290241
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[129]	valid_0's binary_logloss: 0.0290672
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[130]	valid_0's binary_logloss: 0.0291017
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[131]	valid_0's binary_logloss: 0.029048
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[132]	valid_0's binary_logloss: 0.0289849
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[133]	valid_0's binary_logloss: 0.0289636
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[134]	valid_0's binary_logloss: 0.0288959
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[135]	valid_0's binary_logloss: 0.0288482
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[136]	valid_0's binary_logloss: 0.0288199
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[137]	valid_0's binary_logloss: 0.0288032
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[138]	valid_0's binary_logloss: 0.0288163
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[139]	valid_0's binary_logloss: 0.028869
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[140]	valid_0's binary_logloss: 0.0287702
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[141]	valid_0's binary_logloss: 0.0287656
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[142]	valid_0's binary_logloss: 0.0287103
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[143]	valid_0's binary_logloss: 0.0286651
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[144]	valid_0's binary_logloss: 0.0286103
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[145]	valid_0's binary_logloss: 0.0286238
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[146]	valid_0's binary_logloss: 0.0285769
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[147]	valid_0's binary_logloss: 0.0285479
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[148]	valid_0's binary_logloss: 0.0285492
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[149]	valid_0's binary_logloss: 0.0284948
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[150]	valid_0's binary_logloss: 0.0284423
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[151]	valid_0's binary_logloss: 0.0284203
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[152]	valid_0's binary_logloss: 0.0283607
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[153]	valid_0's binary_logloss: 0.0283017
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[154]	valid_0's binary_logloss: 0.028226
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[155]	valid_0's binary_logloss: 0.0282256
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[156]	valid_0's binary_logloss: 0.0281849
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[157]	valid_0's binary_logloss: 0.0278675
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[158]	valid_0's binary_logloss: 0.0278433
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[159]	valid_0's binary_logloss: 0.0276915
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[160]	valid_0's binary_logloss: 0.0275956
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[161]	valid_0's binary_logloss: 0.0275595
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[162]	valid_0's binary_logloss: 0.0275359
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[163]	valid_0's binary_logloss: 0.0275029
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[164]	valid_0's binary_logloss: 0.0274449
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[165]	valid_0's binary_logloss: 0.027389
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[166]	valid_0's binary_logloss: 0.0274139
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[167]	valid_0's binary_logloss: 0.0273844
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[168]	valid_0's binary_logloss: 0.027345
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[169]	valid_0's binary_logloss: 0.0272394
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[170]	valid_0's binary_logloss: 0.0271457
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[171]	valid_0's binary_logloss: 0.0271168
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[172]	valid_0's binary_logloss: 0.027036
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[173]	valid_0's binary_logloss: 0.0269832
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[174]	valid_0's binary_logloss: 0.0269492
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[175]	valid_0's binary_logloss: 0.0270153
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[176]	valid_0's binary_logloss: 0.0269534
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[177]	valid_0's binary_logloss: 0.0269293
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[178]	valid_0's binary_logloss: 0.0268961
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[179]	valid_0's binary_logloss: 0.0268547

Trening klas:  67%|██████▋   | 334/500 [39:34<21:05,  7.62s/klasa, klasa=class_334, F1_klasy=0.7538, F1_macro=0.6848, drzewa=240]




Trening klas:  67%|██████▋   | 335/500 [39:34<21:57,  7.98s/klasa, klasa=class_334, F1_klasy=0.7538, F1_macro=0.6848, drzewa=240]

[263]	valid_0's binary_logloss: 0.0262212
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[264]	valid_0's binary_logloss: 0.0262452
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[265]	valid_0's binary_logloss: 0.0263095
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[266]	valid_0's binary_logloss: 0.0263379
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[267]	valid_0's binary_logloss: 0.0263524
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[268]	valid_0's binary_logloss: 0.0263095
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[269]	valid_0's binary_logloss: 0.0263634
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[270]	valid_0's binary_logloss: 0.0263849
[1]	valid_0's binary_logloss: 0.531064
[2]	valid_0's binary_logloss: 0.411034
[3]	valid_0's binary_logloss: 0.394044
[4]	valid_0's binary_logloss: 0.38071
[5]	valid_0's binary_logloss: 0.36677
[6]	valid_0's binary_logloss: 0.354062
[7]	valid_0's binary_logloss: 0.342457
[8]	valid_0's binary_logloss: 0.331854
[9]	valid_0's binary_logloss: 0.323274
[10]	valid_0's binary_logloss: 0.31439
[11]	valid_0's binary_logloss: 0.305862
[12]	valid_0's binary_logloss: 0.297872
[13]	valid_0's binary_logloss: 0.291198
[14]	valid_0's binary_logloss: 0.285195
[15]	valid_0's binary_logloss: 0.27964
[16]	valid_0's binary_logloss: 0.273287
[17]	valid_0's binary_logloss: 0.26775
[18]	valid_0's binary_logloss: 0.262231
[19]	valid_0's binary_logloss: 0.257042
[20]	valid_0's binary_logloss: 0.252011
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.247667
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.243457
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.239296
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.235057
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.2313
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.226923
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.223074
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.219179
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.215293
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.211757
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.208462
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.204966
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.201425
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.19835
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.195857
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.193668
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.191145
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.188785
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.186496
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.184396
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.182182
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.180228
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.178209
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.176154
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.174039
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.171414
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.168954
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.166587
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.164267
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.16201
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.16009
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.158003
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.156094
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.154278
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.152388
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.150807
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.149063
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.147436
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.146071
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.144441
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.142897
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.141445
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.139958
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.138554
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.137123
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.135984
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.134812
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.133678
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.132656
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.131405
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.129914
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.128831
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.127738
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.126711
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.125693
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.124859
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.124135
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.123235
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.122444
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.121882
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.120989
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.120298
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.11953
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.118661
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.117821
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.117177
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.116245
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.115665
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.115053
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.114288
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.113795
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.113374
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.112944
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.112578
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.112083
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.111456
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.110894
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.11053
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.110017
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.109483
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.108811
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.108397
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.107837
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.107177
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.106783
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.106515
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.10639
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.106148
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.105987
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.105789
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.105329
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 0.10489
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 0.104427
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 0.103973
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 0.103799
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[116]	valid_0's binary_logloss: 0.103511
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[117]	valid_0's binary_logloss: 0.1033
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[118]	valid_0's binary_logloss: 0.103123
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[119]	valid_0's binary_logloss: 0.102866
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[120]	valid_0's binary_logloss: 0.102648
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[121]	valid_0's binary_logloss: 0.102336
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[122]	valid_0's binary_logloss: 0.101985
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[123]	valid_0's binary_logloss: 0.101711
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[124]	valid_0's binary_logloss: 0.101448
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[125]	valid_0's binary_logloss: 0.10121
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[126]	valid_0's binary_logloss: 0.10111
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[127]	valid_0's binary_logloss: 0.101008
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[128]	valid_0's binary_logloss: 0.100879
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[129]	valid_0's binary_logloss: 0.100779
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[130]	valid_0's binary_logloss: 0.100516
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[131]	valid_0's binary_logloss: 0.100497
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[132]	valid_0's binary_logloss: 0.100343
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[133]	valid_0's binary_logloss: 0.100215
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[134]	valid_0's binary_logloss: 0.100121
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[135]	valid_0's binary_logloss: 0.100003
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[136]	valid_0's binary_logloss: 0.0999081
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[137]	valid_0's binary_logloss: 0.0998042
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[138]	valid_0's binary_logloss: 0.0995939
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[139]	valid_0's binary_logloss: 0.0993948
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[140]	valid_0's binary_logloss: 0.0992451
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[141]	valid_0's binary_logloss: 0.0990039
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[142]	valid_0's binary_logloss: 0.0988165
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[143]	valid_0's binary_logloss: 0.0985603
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[144]	valid_0's binary_logloss: 0.0983225
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[145]	valid_0's binary_logloss: 0.0982337
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[146]	valid_0's binary_logloss: 0.0980217
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[147]	valid_0's binary_logloss: 0.0980316
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[148]	valid_0's binary_logloss: 0.0977712
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[149]	valid_0's binary_logloss: 0.0977492
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[150]	valid_0's binary_logloss: 0.097662
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[151]	valid_0's binary_logloss: 0.0976247
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[152]	valid_0's binary_logloss: 0.0976624
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[153]	valid_0's binary_logloss: 0.0977414
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[154]	valid_0's binary_logloss: 0.097778
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[155]	valid_0's binary_logloss: 0.0976681
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[156]	valid_0's binary_logloss: 0.0975239
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[157]	valid_0's binary_logloss: 0.0973915
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[158]	valid_0's binary_logloss: 0.0972733
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[159]	valid_0's binary_logloss: 0.0971607
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[160]	valid_0's binary_logloss: 0.0971452
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[161]	valid_0's binary_logloss: 0.0970846
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[162]	valid_0's binary_logloss: 0.0970413
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[163]	valid_0's binary_logloss: 0.0970098
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[164]	valid_0's binary_logloss: 0.0969979
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[165]	valid_0's binary_logloss: 0.0968657
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[166]	valid_0's binary_logloss: 0.0966446
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[167]	valid_0's binary_logloss: 0.0965279
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[168]	valid_0's binary_logloss: 0.0964259
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[169]	valid_0's binary_logloss: 0.0963271
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[170]	valid_0's binary_logloss: 0.0963038
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[171]	valid_0's binary_logloss: 0.0963227
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[172]	valid_0's binary_logloss: 0.0963633
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[173]	valid_0's binary_logloss: 0.0963739
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[174]	valid_0's binary_logloss: 0.0964493
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[175]	valid_0's binary_logloss: 0.0964649
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[176]	valid_0's binary_logloss: 0.096306
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[177]	valid_0's binary_logloss: 0.0961573
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[178]	valid_0's binary_logloss: 0.0960695
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

Trening klas:  67%|██████▋   | 335/500 [39:43<21:57,  7.98s/klasa, klasa=class_335, F1_klasy=0.3226, F1_macro=0.6838, drzewa=195]




Trening klas:  67%|██████▋   | 336/500 [39:43<22:21,  8.18s/klasa, klasa=class_335, F1_klasy=0.3226, F1_macro=0.6838, drzewa=195]

[221]	valid_0's binary_logloss: 0.0958097
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[222]	valid_0's binary_logloss: 0.0958147
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[223]	valid_0's binary_logloss: 0.0957837
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[224]	valid_0's binary_logloss: 0.0957572
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[225]	valid_0's binary_logloss: 0.0957292
[1]	valid_0's binary_logloss: 0.145024
[2]	valid_0's binary_logloss: 0.065763
[3]	valid_0's binary_logloss: 0.0610739
[4]	valid_0's binary_logloss: 0.0582661
[5]	valid_0's binary_logloss: 0.0561463
[6]	valid_0's binary_logloss: 0.0538797
[7]	valid_0's binary_logloss: 0.0525786
[8]	valid_0's binary_logloss: 0.0510397
[9]	valid_0's binary_logloss: 0.0500957
[10]	valid_0's binary_logloss: 0.0493051
[11]	valid_0's binary_logloss: 0.0480306
[12]	valid_0's binary_logloss: 0.0468366
[13]	valid_0's binary_logloss: 0.0458341
[14]	valid_0's binary_logloss: 0.0450015
[15]	valid_0's binary_logloss: 0.044082
[16]	valid_0's binary_logloss: 0.0431262
[17]	valid_0's binary_logloss: 0.0424366
[18]	valid_0's binary_logloss: 0.0417167
[19]	valid_0's binary_logloss: 0.041017
[20]	valid_0's binary_logloss: 0.0403753
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0398984
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0393856
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.0390367
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0386761
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.0382974
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.0381204
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.0377614
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.0375267
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.0373803
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.0372322
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.0368651
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.0363116
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.0358928
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.0354675
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.0350916
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.034818
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.0345331
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.0342666
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.0339633
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.0336887
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.0332552
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.0330355
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.0327554
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.0324065
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.0322803
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.0321185
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.0320142
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.031889
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.031753
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.0316866
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.0314533
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.0312341
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.0311083
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.0309616
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.0308041
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.0308226
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.0307364
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.030626
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.0305757
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.0305543
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.0302955
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.0301629
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.0298255
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.0295671
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.0292777
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.0292069
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.0291647
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.0290055
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.0290003
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.0289773
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.0289408
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.0288461
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.0287301
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.028608
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.02849
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.0282661
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.0280953
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.02798
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.0278111
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.0276696
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.0275876
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.0275762
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.0275082
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.0274595
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.0274194
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.0274115
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.0273795
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.0273085
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.0272308
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.0271794
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.027148
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.0271211
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.0270842
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.0271167
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.0271757
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.0271827
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.0272492
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.027297
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.0273426
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.0273774
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.0273677
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.0273873
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.0274152
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.0274461
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.0274721
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.0274592
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.0275036
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.0275435
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.0275557
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.0276066
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.0276345
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 0.0276388
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 0.0276066
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 0.0276659
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 0.0276482
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[116]	valid_0's binary_logloss: 0.0275698
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[117]	valid_0's binary_logloss: 0.0274621
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[118]	valid_0's binary_logloss: 0.0273916
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[119]	valid_0's binary_logloss: 0.027323
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[120]	valid_0's binary_logloss: 0.0272931
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[121]	valid_0's binary_logloss: 0.0272709
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[122]	valid_0's binary_logloss: 0.0272608
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[123]	valid_0's binary_logloss: 0.0272291

Trening klas:  67%|██████▋   | 336/500 [39:48<22:21,  8.18s/klasa, klasa=class_336, F1_klasy=0.7679, F1_macro=0.6840, drzewa=93]




Trening klas:  67%|██████▋   | 337/500 [39:48<19:55,  7.33s/klasa, klasa=class_336, F1_klasy=0.7679, F1_macro=0.6840, drzewa=93]

[1]	valid_0's binary_logloss: 0.0180534
[2]	valid_0's binary_logloss: 0.0169941
[3]	valid_0's binary_logloss: 0.0161955
[4]	valid_0's binary_logloss: 0.0154021
[5]	valid_0's binary_logloss: 0.0148756
[6]	valid_0's binary_logloss: 0.0142181
[7]	valid_0's binary_logloss: 0.0134754
[8]	valid_0's binary_logloss: 0.012776
[9]	valid_0's binary_logloss: 0.0121092
[10]	valid_0's binary_logloss: 0.011653
[11]	valid_0's binary_logloss: 0.0111607
[12]	valid_0's binary_logloss: 0.0107386
[13]	valid_0's binary_logloss: 0.0102936
[14]	valid_0's binary_logloss: 0.00999411
[15]	valid_0's binary_logloss: 0.00968307
[16]	valid_0's binary_logloss: 0.0092924
[17]	valid_0's binary_logloss: 0.00896342
[18]	valid_0's binary_logloss: 0.0086608
[19]	valid_0's binary_logloss: 0.00837899
[20]	valid_0's binary_logloss: 0.00811214
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.00783107
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.00760197
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.00739579
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.00718925
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.00698929
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.00680153
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.0065739
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.00642141
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.00624871
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.00608002
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.00593204
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.0057444
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.0056192
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.00547925
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.00535208
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.00520009
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.00511777
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.00491611
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.00480601
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.00464607
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.00454436
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.00444055
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.00436043
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.00426905
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.00416729
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.0041012
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.00403968
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.00396883
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.00389627
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.00381434
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.00373408
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.00367699
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.00363919
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.00356743
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.00354708
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.00353068
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.00346967
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.00345749
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.00342938
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.00340401
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.00333405
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.00327639
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.00321382
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.00316946
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.00312628
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.0030678
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.00302644
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.00298269
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.0029447
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.00291035
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.00287513
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.00285076
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.0028546
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.00280893
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.00280085
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.00279997
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.00281527
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.00281686
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.00278572
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.00276586
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.00274596
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.00271967
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.00270242
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.0026691
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.00264985
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.00264067
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.00263507
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.00262375
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.00260478
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.00256988
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.0025451
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.00252496
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.00250924
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.0024794
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.00246239
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.00244194
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.00244122
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.00243276
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.00242151
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.00242639
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.00241978
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.00240455
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.0024042
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.00240632
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.00240611
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.00240756
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.00240263
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.00240734
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.00240648
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.0024
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.00239475
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 0.00237956
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 0.00237992
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 0.00236935
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 0.00236499
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[116]	valid_0's binary_logloss: 0.00235905
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[117]	valid_0's binary_logloss: 0.00236409
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[118]	valid_0's binary_logloss: 0.00233834
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[119]	valid_0's binary_logloss: 0.00234373
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[120]	valid_0's binary_logloss: 0.00233658
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[121]	valid_0's binary_logloss: 0.00234829
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[122]	valid_0's binary_logloss: 0.00235577
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[123]	valid_0's binary_logloss: 0.00235552
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[124]	valid_0's binary_logloss: 0.00235659
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[125]	valid_0's binary_logloss: 0.0023697
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[126]	valid_0's binary_logloss: 0.00239619
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[127]	valid_0's binary_logloss: 0.00242315
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[128]	valid_0's binary_logloss: 0.00244379
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[129]	valid_0's binary_logloss: 0.002449
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[130]	valid_0's binary_logloss: 0.00244864
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[131]	valid_0's binary_logloss: 0.00246007
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[132]	valid_0's binary_logloss: 0.00248355
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[133]	valid_0's binary_logloss: 0.00250155
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[134]	valid_0's binary_logloss: 0.00252582
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[135]	valid_0's binary_logloss: 0.00254583
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[136]	valid_0's binary_logloss: 0.00251308
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[137]	valid_0's binary_logloss: 0.00252434
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[138]	valid_0's binary_logloss: 0.0025009
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[139]	valid_0's binary_logloss: 0.00248531
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[140]	valid_0's binary_logloss: 0.00248068
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[141]	valid_0's binary_logloss: 0.00247671
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[142]	valid_0's binary_logloss: 0.00247766
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[143]	valid_0's binary_logloss: 0.00248299
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[144]	valid_0's binary_logloss: 0.00247505
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[145]	valid_0's binary_logloss: 0.00247996
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[146]	valid_0's binary_logloss: 0.00248881
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[147]	valid_0's binary_logloss: 0.00249755
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[148]	valid_0's binary_logloss: 0.00249999
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[149]	valid_0's binary_logloss: 0.00250611
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[150]	valid_0's binary_logloss: 0.00250772

Trening klas:  67%|██████▋   | 337/500 [39:56<19:55,  7.33s/klasa, klasa=class_337, F1_klasy=0.6667, F1_macro=0.6840, drzewa=120]




Trening klas:  68%|██████▊   | 338/500 [39:56<20:01,  7.42s/klasa, klasa=class_337, F1_klasy=0.6667, F1_macro=0.6840, drzewa=120]

[1]	valid_0's binary_logloss: 0.229591
[2]	valid_0's binary_logloss: 0.146437
[3]	valid_0's binary_logloss: 0.141072
[4]	valid_0's binary_logloss: 0.134923
[5]	valid_0's binary_logloss: 0.131048
[6]	valid_0's binary_logloss: 0.126717
[7]	valid_0's binary_logloss: 0.121037
[8]	valid_0's binary_logloss: 0.116686
[9]	valid_0's binary_logloss: 0.11267
[10]	valid_0's binary_logloss: 0.10906
[11]	valid_0's binary_logloss: 0.10562
[12]	valid_0's binary_logloss: 0.102156
[13]	valid_0's binary_logloss: 0.0984705
[14]	valid_0's binary_logloss: 0.0955711
[15]	valid_0's binary_logloss: 0.0930285
[16]	valid_0's binary_logloss: 0.0905805
[17]	valid_0's binary_logloss: 0.0883486
[18]	valid_0's binary_logloss: 0.0864491
[19]	valid_0's binary_logloss: 0.0846732
[20]	valid_0's binary_logloss: 0.082176
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0802712
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0786499
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.0771837
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0757118
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.074289
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.0727356
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.0716834
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.0700659
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.0687536
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.0677211
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.06682
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.0659775
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.0651996
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.0643985
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.0635608
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.0626762
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.0618734
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.060817
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.0600568
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.0593107
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.0583767
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.0575599
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.0567045
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.0558385
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.0548576
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.0541757
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.0534886
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.0528019
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.0522754
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.0514135
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.0506958
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.0500323
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.0493876
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.0487367
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.0481438
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.0475114
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.0468743
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.0462748
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.0457261
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.0453054
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.0446238
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.044116
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.0433931
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.0428399
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.0421683
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.0416797
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.0411841
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.0408714
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.0405949
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.0402322
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.0398048
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.039403
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.0390442
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.0387208
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.0382864
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.0380095
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.0376634
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.0372264
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.0368553
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.0365178
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.0362878
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.0360553
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.0356415
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.0353796
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.0349757
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.0347826
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.0345814
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.034364
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.034232
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.0340122
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.0336732
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.0334274
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.0332259
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.0328696
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.0325786
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.0321508
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.0317945
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.0316394
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.031343
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.0310918
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.030828
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.0306103
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.0303434
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.0301446
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.0299711
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.0299509
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.0299606
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.0299266
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.0299116
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.0298193
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.0296489
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 0.0294422
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 0.0292877
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 0.0291469
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 0.0289006
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[116]	valid_0's binary_logloss: 0.0288228
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[117]	valid_0's binary_logloss: 0.0285918
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[118]	valid_0's binary_logloss: 0.0285226
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[119]	valid_0's binary_logloss: 0.0283386
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[120]	valid_0's binary_logloss: 0.0282138
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[121]	valid_0's binary_logloss: 0.0281508
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[122]	valid_0's binary_logloss: 0.0281715
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[123]	valid_0's binary_logloss: 0.028157
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[124]	valid_0's binary_logloss: 0.0281655
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[125]	valid_0's binary_logloss: 0.0281203
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[126]	valid_0's binary_logloss: 0.0280064
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[127]	valid_0's binary_logloss: 0.0278431
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[128]	valid_0's binary_logloss: 0.027732
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[129]	valid_0's binary_logloss: 0.0275965
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[130]	valid_0's binary_logloss: 0.0274594
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[131]	valid_0's binary_logloss: 0.0272974
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[132]	valid_0's binary_logloss: 0.0272431
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[133]	valid_0's binary_logloss: 0.0270584
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[134]	valid_0's binary_logloss: 0.0270161
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[135]	valid_0's binary_logloss: 0.0269554
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[136]	valid_0's binary_logloss: 0.0267823
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[137]	valid_0's binary_logloss: 0.0266387
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[138]	valid_0's binary_logloss: 0.0265059
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[139]	valid_0's binary_logloss: 0.0264058
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[140]	valid_0's binary_logloss: 0.0262657
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[141]	valid_0's binary_logloss: 0.026232
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[142]	valid_0's binary_logloss: 0.0262054
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[143]	valid_0's binary_logloss: 0.0261722
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[144]	valid_0's binary_logloss: 0.0261782
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[145]	valid_0's binary_logloss: 0.0261437
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[146]	valid_0's binary_logloss: 0.0261623
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[147]	valid_0's binary_logloss: 0.0262346
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[148]	valid_0's binary_logloss: 0.0262757
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[149]	valid_0's binary_logloss: 0.02633
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[150]	valid_0's binary_logloss: 0.0264209
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[151]	valid_0's binary_logloss: 0.026365
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[152]	valid_0's binary_logloss: 0.0262709
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[153]	valid_0's binary_logloss: 0.0261889
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[154]	valid_0's binary_logloss: 0.0260399
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[155]	valid_0's binary_logloss: 0.0260037
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[156]	valid_0's binary_logloss: 0.0259281
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[157]	valid_0's binary_logloss: 0.0258537
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[158]	valid_0's binary_logloss: 0.0259506
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[159]	valid_0's binary_logloss: 0.0258953
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[160]	valid_0's binary_logloss: 0.0259268
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[161]	valid_0's binary_logloss: 0.0259467
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[162]	valid_0's binary_logloss: 0.0259494
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[163]	valid_0's binary_logloss: 0.0259148
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[164]	valid_0's binary_logloss: 0.0258864
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[165]	valid_0's binary_logloss: 0.0258264
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[166]	valid_0's binary_logloss: 0.0257407
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[167]	valid_0's binary_logloss: 0.0257733
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[168]	valid_0's binary_logloss: 0.0257676
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[169]	valid_0's binary_logloss: 0.0258086
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[170]	valid_0's binary_logloss: 0.0256975
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[171]	valid_0's binary_logloss: 0.0256012
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[172]	valid_0's binary_logloss: 0.025563
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[173]	valid_0's binary_logloss: 0.0255068
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[174]	valid_0's binary_logloss: 0.0255591
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[175]	valid_0's binary_logloss: 0.0255878
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[176]	valid_0's binary_logloss: 0.025558
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[177]	valid_0's binary_logloss: 0.025603
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[178]	valid_0's binary_logloss: 0.0256676
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[179]	valid_0's binary_logloss: 0.0256832
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[180]	valid_0's binary_logloss: 0.0257091
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[181]	valid_0's binary_logloss: 0.025787
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[182]	valid_0's binary_logloss: 0.0258278
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[183]	valid_0's binary_logloss: 0.0259023
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[184]	valid_0's binary_logloss: 0.0259765
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

Trening klas:  68%|██████▊   | 338/500 [40:04<20:01,  7.42s/klasa, klasa=class_338, F1_klasy=0.7558, F1_macro=0.6842, drzewa=283]




Trening klas:  68%|██████▊   | 339/500 [40:04<20:11,  7.52s/klasa, klasa=class_338, F1_klasy=0.7558, F1_macro=0.6842, drzewa=283]

[294]	valid_0's binary_logloss: 0.0236869
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[295]	valid_0's binary_logloss: 0.0236832
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[296]	valid_0's binary_logloss: 0.0236634
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[297]	valid_0's binary_logloss: 0.0236371
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[298]	valid_0's binary_logloss: 0.023632
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[299]	valid_0's binary_logloss: 0.0236123
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[300]	valid_0's binary_logloss: 0.023609
[1]	valid_0's binary_logloss: 0.0107657
[2]	valid_0's binary_logloss: 0.010212
[3]	valid_0's binary_logloss: 0.00973784
[4]	valid_0's binary_logloss: 0.00928179
[5]	valid_0's binary_logloss: 0.00886649
[6]	valid_0's binary_logloss: 0.00851003
[7]	valid_0's binary_logloss: 0.00811015
[8]	valid_0's binary_logloss: 0.007761
[9]	valid_0's binary_logloss: 0.00738056
[10]	valid_0's binary_logloss: 0.00706699
[11]	valid_0's binary_logloss: 0.00679493
[12]	valid_0's binary_logloss: 0.00651851
[13]	valid_0's binary_logloss: 0.00624044
[14]	valid_0's binary_logloss: 0.00598889
[15]	valid_0's binary_logloss: 0.00574744
[16]	valid_0's binary_logloss: 0.00551377
[17]	valid_0's binary_logloss: 0.00529237
[18]	valid_0's binary_logloss: 0.0050742
[19]	valid_0's binary_logloss: 0.00486734
[20]	valid_0's binary_logloss: 0.00465224
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.00446997
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.00431431
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.00413916
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.00398335
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.00384604
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.00371815
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.00359931
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.00348304
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.0033863
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.00326267
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.00315278
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.00304804
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.0029481
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.00285156
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.00278389
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.00270603
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.00263781
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.00256361
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.0024967
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.00242344
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.002352
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.00227685
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.00221596
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.00215189
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.00210873
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.00205601
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.0020105
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.00196504
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.0019387
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.00188494
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.00185824
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.00181938
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.00177954
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.00175544
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.0017393
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.00171477
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.00168611
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.00167367
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.00165777
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.00164562
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.00163822
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.00162429
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.0016162
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.00160005
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.00159435
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.00157567
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.00156801
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.00155335
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.00155003
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.00153438
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.00151317
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.00151174
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.00150737
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.00150329
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.0015008
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.00150054
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.00150355
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.00148343
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.00146912
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.00145091
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.00144645
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.0014479
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.00145945
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.00147459
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.00146093
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.00145484
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.00144971
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.00146303
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.00147622
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.0014742
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.00147738
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.00148924
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.00148251
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.00148649
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.00149234
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.00147538
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.00150128
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.00149153
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.00146983
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.00145301
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.00145896
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.0014608
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.00146366
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.00146693
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.00147622
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

[106]	valid_0's binary_logloss: 0.0014766
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.00148188
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.00148732
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.00149135
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.00150263
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.0015166

Trening klas:  68%|██████▊   | 339/500 [40:10<20:11,  7.52s/klasa, klasa=class_339, F1_klasy=0.5714, F1_macro=0.6838, drzewa=81]




Trening klas:  68%|██████▊   | 340/500 [40:10<18:52,  7.08s/klasa, klasa=class_339, F1_klasy=0.5714, F1_macro=0.6838, drzewa=81]

[1]	valid_0's binary_logloss: 0.293886
[2]	valid_0's binary_logloss: 0.18663
[3]	valid_0's binary_logloss: 0.169922
[4]	valid_0's binary_logloss: 0.156279
[5]	valid_0's binary_logloss: 0.146112
[6]	valid_0's binary_logloss: 0.161686
[7]	valid_0's binary_logloss: 0.153695
[8]	valid_0's binary_logloss: 0.146928
[9]	valid_0's binary_logloss: 0.141266
[10]	valid_0's binary_logloss: 0.136345
[11]	valid_0's binary_logloss: 0.131499
[12]	valid_0's binary_logloss: 0.126114
[13]	valid_0's binary_logloss: 0.121912
[14]	valid_0's binary_logloss: 0.11863
[15]	valid_0's binary_logloss: 0.1147
[16]	valid_0's binary_logloss: 0.11168
[17]	valid_0's binary_logloss: 0.108477
[18]	valid_0's binary_logloss: 0.10586
[19]	valid_0's binary_logloss: 0.102954
[20]	valid_0's binary_logloss: 0.100473
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0979136
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0957341
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.0934848
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0916445
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.0898551
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.088513
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.0869735
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.0853169
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.0841238
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.0827864
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.0813835
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.0798655
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.0785583
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.0770802
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.0758648
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.0747332
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.0736599
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.0728351
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.0717469
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.0709091
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.069534
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.0684208
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.0673748
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.0665001
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.0656638
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.0649405
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.0641252
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.0634278
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.0628742
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.0621105
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.0615495
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.0606993
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.0599417
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.0592436
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.0586485
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.0581102
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.0576478
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.0571864
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.0568316
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.0564942
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.0560269
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.055569
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.0551823
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.0548333
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.05446
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.054128
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.0537199
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.0534447
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.0530807
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.0527447
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.0526356
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.0525074
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.052316
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.0521931
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.0520577
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.051733
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.0514154
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.0512529
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.0511224
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.050951
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.0510757
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.0510281
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.0509849
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.0509976
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.0509451
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.0508772
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.05095
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.0508645
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.050782
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.0507639
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.0507466
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.0507161
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.0506381
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.0507215
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.050733
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.0507017
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.0507415
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.0507913
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.0507405
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.0507157
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.050665
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.050671
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.0505655
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.0504619
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.0503847
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.0503249
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.0502698
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.050218
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.0502295
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.0501398
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.0499469
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 0.0498651
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 0.0497216
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 0.0495673
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 0.049684
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[116]	valid_0's binary_logloss: 0.049524
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[117]	valid_0's binary_logloss: 0.0493882
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[118]	valid_0's binary_logloss: 0.0492032
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[119]	valid_0's binary_logloss: 0.0490558
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[120]	valid_0's binary_logloss: 0.0488875
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[121]	valid_0's binary_logloss: 0.0487962
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[122]	valid_0's binary_logloss: 0.0487228
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[123]	valid_0's binary_logloss: 0.0486501
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[124]	valid_0's binary_logloss: 0.0485067
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[125]	valid_0's binary_logloss: 0.0483448
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[126]	valid_0's binary_logloss: 0.0482537
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[127]	valid_0's binary_logloss: 0.0481905
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[128]	valid_0's binary_logloss: 0.0480908
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[129]	valid_0's binary_logloss: 0.0479785
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[130]	valid_0's binary_logloss: 0.047994
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[131]	valid_0's binary_logloss: 0.0479135
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[132]	valid_0's binary_logloss: 0.0478707
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[133]	valid_0's binary_logloss: 0.0478981
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[134]	valid_0's binary_logloss: 0.0478869
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[135]	valid_0's binary_logloss: 0.0479325
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[136]	valid_0's binary_logloss: 0.0480524
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[137]	valid_0's binary_logloss: 0.0481342
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[138]	valid_0's binary_logloss: 0.0480192
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[139]	valid_0's binary_logloss: 0.048189
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[140]	valid_0's binary_logloss: 0.0482758
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[141]	valid_0's binary_logloss: 0.0483172
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[142]	valid_0's binary_logloss: 0.048387
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[143]	valid_0's binary_logloss: 0.0483907
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[144]	valid_0's binary_logloss: 0.0483523
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[145]	valid_0's binary_logloss: 0.0483693
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[146]	valid_0's binary_logloss: 0.0483685
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[147]	valid_0's binary_logloss: 0.0483822
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[148]	valid_0's binary_logloss: 0.04837
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[149]	valid_0's binary_logloss: 0.0484046
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[150]	valid_0's binary_logloss: 0.0483204
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[151]	valid_0's binary_logloss: 0.0483163
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[152]	valid_0's binary_logloss: 0.0483742
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[153]	valid_0's binary_logloss: 0.0483584
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[154]	valid_0's binary_logloss: 0.0483671
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[155]	valid_0's binary_logloss: 0.0483924
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[156]	valid_0's binary_logloss: 0.0484657
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[157]	valid_0's binary_logloss: 0.0486007
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[158]	valid_0's binary_logloss: 0.048624
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[159]	valid_0's binary_logloss: 0.0487815
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[160]	valid_0's binary_logloss: 0.0487939
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[161]	valid_0's binary_logloss: 0.048823
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[162]	valid_0's binary_logloss: 0.0488727

Trening klas:  68%|██████▊   | 340/500 [40:16<18:52,  7.08s/klasa, klasa=class_340, F1_klasy=0.4076, F1_macro=0.6830, drzewa=132]




Trening klas:  68%|██████▊   | 341/500 [40:16<18:09,  6.85s/klasa, klasa=class_340, F1_klasy=0.4076, F1_macro=0.6830, drzewa=132]

[1]	valid_0's binary_logloss: 0.112644
[2]	valid_0's binary_logloss: 0.103867
[3]	valid_0's binary_logloss: 0.0984581
[4]	valid_0's binary_logloss: 0.0933099
[5]	valid_0's binary_logloss: 0.0895129
[6]	valid_0's binary_logloss: 0.0935552
[7]	valid_0's binary_logloss: 0.0907391
[8]	valid_0's binary_logloss: 0.0879842
[9]	valid_0's binary_logloss: 0.0858086
[10]	valid_0's binary_logloss: 0.0830204
[11]	valid_0's binary_logloss: 0.0800682
[12]	valid_0's binary_logloss: 0.0784213
[13]	valid_0's binary_logloss: 0.0769931
[14]	valid_0's binary_logloss: 0.0756053
[15]	valid_0's binary_logloss: 0.0742167
[16]	valid_0's binary_logloss: 0.072512
[17]	valid_0's binary_logloss: 0.0712474
[18]	valid_0's binary_logloss: 0.0699168
[19]	valid_0's binary_logloss: 0.0684944
[20]	valid_0's binary_logloss: 0.0670192
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0655248
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0641855
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.0633028
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0622175
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.0611453
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.0598424
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.0585297
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.0574042
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.0564295
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.05517
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.0542448
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.0532492
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.0522916
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.0513697
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.0505079
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.0498457
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.0492523
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.048479
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.0478205
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.0472694
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.0467844
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.0461152
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.0456258
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.0451265
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.0446695
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.0442049
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.0437568
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.0434577
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.0429908
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.0426163
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.0422537
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.0417166
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.0412219
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.0409215
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.040538
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.0402974
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.0400269
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.0397709
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.0394133
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.0391837
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.0388348
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.0386318
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.0384344
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.0381255
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.0379123
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.0376863
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.0375231
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.0373063
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.0371049
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.0369286
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.0367164
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.0366594
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.0364663
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.0364431
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.0363742
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.0362496
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.0362116
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.036319
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.0362987
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.0361996
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.0360264
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.036135
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.0360677
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.0360261
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.0360163
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.0358917
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.0358198
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.0357858
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.0357307
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.0356474
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.0355329
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.0354349
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.0353402
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.0351439
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.0350689
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.0349503
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.0349323
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.0349066
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.0348278
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.034786
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.034761
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.0347613
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.0347219
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.0347488
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.0347589
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.0346717
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.0346687
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.0346291
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.0346533
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.034703
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.0346983
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 0.034646
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 0.0346272
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 0.0345516
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 0.0346256
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[116]	valid_0's binary_logloss: 0.0346353
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[117]	valid_0's binary_logloss: 0.0346675
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[118]	valid_0's binary_logloss: 0.0347305
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[119]	valid_0's binary_logloss: 0.0347217
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[120]	valid_0's binary_logloss: 0.0347661
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[121]	valid_0's binary_logloss: 0.0348283
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[122]	valid_0's binary_logloss: 0.034771
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[123]	valid_0's binary_logloss: 0.0346998
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[124]	valid_0's binary_logloss: 0.0346764
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[125]	valid_0's binary_logloss: 0.0348007
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[126]	valid_0's binary_logloss: 0.0349076
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[127]	valid_0's binary_logloss: 0.0350041
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[128]	valid_0's binary_logloss: 0.034968
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[129]	valid_0's binary_logloss: 0.0349955
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[130]	valid_0's binary_logloss: 0.0349234
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[131]	valid_0's binary_logloss: 0.0348937
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[132]	valid_0's binary_logloss: 0.0349451
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[133]	valid_0's binary_logloss: 0.0349063
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[134]	valid_0's binary_logloss: 0.0348814
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[135]	valid_0's binary_logloss: 0.0350127
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[136]	valid_0's binary_logloss: 0.0350512
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[137]	valid_0's binary_logloss: 0.0351216
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[138]	valid_0's binary_logloss: 0.0351365
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[139]	valid_0's binary_logloss: 0.0351496
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

Trening klas:  68%|██████▊   | 341/500 [40:23<18:09,  6.85s/klasa, klasa=class_341, F1_klasy=0.2970, F1_macro=0.6819, drzewa=114]




Trening klas:  68%|██████▊   | 342/500 [40:23<17:56,  6.81s/klasa, klasa=class_341, F1_klasy=0.2970, F1_macro=0.6819, drzewa=114]

[140]	valid_0's binary_logloss: 0.0351761
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[141]	valid_0's binary_logloss: 0.035254
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[142]	valid_0's binary_logloss: 0.0352862
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[143]	valid_0's binary_logloss: 0.0353714
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[144]	valid_0's binary_logloss: 0.0353667
[1]	valid_0's binary_logloss: 0.25073
[2]	valid_0's binary_logloss: 0.21219
[3]	valid_0's binary_logloss: 0.196457
[4]	valid_0's binary_logloss: 0.186425
[5]	valid_0's binary_logloss: 0.173907
[6]	valid_0's binary_logloss: 0.168399
[7]	valid_0's binary_logloss: 0.161656
[8]	valid_0's binary_logloss: 0.155718
[9]	valid_0's binary_logloss: 0.15122
[10]	valid_0's binary_logloss: 0.146603
[11]	valid_0's binary_logloss: 0.141299
[12]	valid_0's binary_logloss: 0.136808
[13]	valid_0's binary_logloss: 0.132668
[14]	valid_0's binary_logloss: 0.128924
[15]	valid_0's binary_logloss: 0.126261
[16]	valid_0's binary_logloss: 0.123132
[17]	valid_0's binary_logloss: 0.120618
[18]	valid_0's binary_logloss: 0.117652
[19]	valid_0's binary_logloss: 0.115597
[20]	valid_0's binary_logloss: 0.113184
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.110559
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.108193
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.105859
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.10357
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.101631
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.0996409
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.0979332
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.0967962
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.0953699
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.0940626
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.0927824
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.0914907
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.0901111
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.0886794
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.0875446
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.0861901
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.0852071
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.0840183
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.0831326
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.0821955
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.081073
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.0799321
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.0790431
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.0782263
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.0774746
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.0765639
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.075941
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.0749022
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.0738895
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.073195
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.0728173
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.0723525
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.0718956
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.0715912
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.0711903
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.0708462
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.0706328
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.0702963
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.0699416
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.0694984
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.0692152
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.0688045
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.0686376
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.0684799
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.0682643
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.0679391
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.0675301
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.0673267
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.0668696
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.0665038
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.0662315
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.066078
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.0658194
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.0654258
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.0651656
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.0652659
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.0651326
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.064902
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.0644634
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.0643244
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.0641296
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.0638493
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.0636305
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.0634368
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.0632824
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.0630945
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.0630752
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.0628547
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.0627849
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.0627242
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.0626396
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.0625197
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.0624907
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.0623665
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.0622217
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.0621107
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.0620154
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.0619616
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.0619411
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.0619465
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.061788
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.0616812
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.0615862
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.0615386
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.0614464
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.0613088
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.0612138
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.0611164
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.0611099
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.0610791
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.0608566
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 0.0606769
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 0.0605442
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 0.0604636
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 0.0603014
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[116]	valid_0's binary_logloss: 0.0601857
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[117]	valid_0's binary_logloss: 0.0600632
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[118]	valid_0's binary_logloss: 0.0601602
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[119]	valid_0's binary_logloss: 0.0601434
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[120]	valid_0's binary_logloss: 0.0601516
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[121]	valid_0's binary_logloss: 0.0602131
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[122]	valid_0's binary_logloss: 0.0601005
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[123]	valid_0's binary_logloss: 0.0600326
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[124]	valid_0's binary_logloss: 0.0599116
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[125]	valid_0's binary_logloss: 0.0598879
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[126]	valid_0's binary_logloss: 0.0598545
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[127]	valid_0's binary_logloss: 0.0598351
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[128]	valid_0's binary_logloss: 0.0598559
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[129]	valid_0's binary_logloss: 0.0598286
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[130]	valid_0's binary_logloss: 0.0598672
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[131]	valid_0's binary_logloss: 0.0598363
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[132]	valid_0's binary_logloss: 0.059872
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[133]	valid_0's binary_logloss: 0.0599103
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[134]	valid_0's binary_logloss: 0.0599334
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[135]	valid_0's binary_logloss: 0.0599119
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[136]	valid_0's binary_logloss: 0.0600216
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[137]	valid_0's binary_logloss: 0.06016
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[138]	valid_0's binary_logloss: 0.0602954
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[139]	valid_0's binary_logloss: 0.0604562
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[140]	valid_0's binary_logloss: 0.0605586
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[141]	valid_0's binary_logloss: 0.0606215
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[142]	valid_0's binary_logloss: 0.060606
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[143]	valid_0's binary_logloss: 0.0606548
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[144]	valid_0's binary_logloss: 0.0607
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[145]	valid_0's binary_logloss: 0.0606836
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[146]	valid_0's binary_logloss: 0.0606642
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[147]	valid_0's binary_logloss: 0.0606946
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[148]	valid_0's binary_logloss: 0.0607874
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[149]	valid_0's binary_logloss: 0.0608545
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[150]	valid_0's binary_logloss: 0.0609092
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[151]	valid_0's binary_logloss: 0.0608968
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[152]	valid_0's binary_logloss: 0.0609466
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[153]	valid_0's binary_logloss: 0.0609902
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[154]	valid_0's binary_logloss: 0.0610369
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[155]	valid_0's binary_logloss: 0.0610549
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[156]	valid_0's binary_logloss: 0.0609182
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[157]	valid_0's binary_logloss: 0.060849
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[158]	valid_0's binary_logloss: 0.0608509
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[159]	valid_0's binary_logloss: 0.0608533

Trening klas:  68%|██████▊   | 342/500 [40:30<17:56,  6.81s/klasa, klasa=class_342, F1_klasy=0.3881, F1_macro=0.6811, drzewa=129]




Trening klas:  69%|██████▊   | 343/500 [40:30<18:05,  6.91s/klasa, klasa=class_342, F1_klasy=0.3881, F1_macro=0.6811, drzewa=129]

[1]	valid_0's binary_logloss: 0.149019
[2]	valid_0's binary_logloss: 0.139721
[3]	valid_0's binary_logloss: 0.131559
[4]	valid_0's binary_logloss: 0.125719
[5]	valid_0's binary_logloss: 0.11987
[6]	valid_0's binary_logloss: 0.146649
[7]	valid_0's binary_logloss: 0.140092
[8]	valid_0's binary_logloss: 0.133977
[9]	valid_0's binary_logloss: 0.12829
[10]	valid_0's binary_logloss: 0.123912
[11]	valid_0's binary_logloss: 0.119167
[12]	valid_0's binary_logloss: 0.11473
[13]	valid_0's binary_logloss: 0.110736
[14]	valid_0's binary_logloss: 0.10716
[15]	valid_0's binary_logloss: 0.103899
[16]	valid_0's binary_logloss: 0.100984
[17]	valid_0's binary_logloss: 0.0983425
[18]	valid_0's binary_logloss: 0.0960062
[19]	valid_0's binary_logloss: 0.0937422
[20]	valid_0's binary_logloss: 0.0913922
[21]	valid_0's binary_logloss: 0.0889518
[22]	valid_0's binary_logloss: 0.0865355
[23]	valid_0's binary_logloss: 0.0842269
[24]	valid_0's binary_logloss: 0.0821907
[25]	valid_0's binary_logloss: 0.0804941
[26]	valid_0's binary_logloss: 0.0787228
[27]	valid_0's binary_logloss: 0.0770641
[28]	valid_0's binary_logloss: 0.0756027
[29]	valid_0's binary_logloss: 0.074352
[30]	valid_0's binary_logloss: 0.0731046
[31]	valid_0's binary_logloss: 0.0717532
[32]	valid_0's binary_logloss: 0.0705932
[33]	valid_0's binary_logloss: 0.0693002
[34]	valid_0's binary_logloss: 0.0683271
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.0672765
[36]	valid_0's binary_logloss: 0.0662622
[37]	valid_0's binary_logloss: 0.065309
[38]	valid_0's binary_logloss: 0.0644416
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.0636034
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.0627844
[41]	valid_0's binary_logloss: 0.0620581
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.0613942
[43]	valid_0's binary_logloss: 0.0608475
[44]	valid_0's binary_logloss: 0.0603156
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.059768
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.0592144
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.0587495
[48]	valid_0's binary_logloss: 0.0582779
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.0578358
[50]	valid_0's binary_logloss: 0.0574614
[51]	valid_0's binary_logloss: 0.0570545
[52]	valid_0's binary_logloss: 0.0566861
[53]	valid_0's binary_logloss: 0.0562413
[54]	valid_0's binary_logloss: 0.0559884
[55]	valid_0's binary_logloss: 0.0557281
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.0553635
[57]	valid_0's binary_logloss: 0.0550318
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.0547972
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.0544434
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.0542236
[61]	valid_0's binary_logloss: 0.0539936
[62]	valid_0's binary_logloss: 0.0537378
[63]	valid_0's binary_logloss: 0.0535078
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.0533354
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.0530985
[66]	valid_0's binary_logloss: 0.0529553
[67]	valid_0's binary_logloss: 0.0528246
[68]	valid_0's binary_logloss: 0.052628
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.0524896
[70]	valid_0's binary_logloss: 0.0522855
[71]	valid_0's binary_logloss: 0.052265
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.0521441
[73]	valid_0's binary_logloss: 0.0521264
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.0521323
[75]	valid_0's binary_logloss: 0.052056
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.052017
[77]	valid_0's binary_logloss: 0.0519967
[78]	valid_0's binary_logloss: 0.0519658
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.0519454
[80]	valid_0's binary_logloss: 0.0519421
[81]	valid_0's binary_logloss: 0.0518939
[82]	valid_0's binary_logloss: 0.0518953
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.0518954
[84]	valid_0's binary_logloss: 0.0519003
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.0518792
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.0518849
[87]	valid_0's binary_logloss: 0.0519575
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.0520052
[89]	valid_0's binary_logloss: 0.0520551
[90]	valid_0's binary_logloss: 0.0521521
[91]	valid_0's binary_logloss: 0.0521501
[92]	valid_0's binary_logloss: 0.0522111
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.0522183
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.0522281
[95]	valid_0's binary_logloss: 0.0522696
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.0522991
[97]	valid_0's binary_logloss: 0.0523271
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.0523526
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.0523469
[100]	valid_0's binary_logloss: 0.0523389
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.052333
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.0524321
[103]	valid_0's binary_logloss: 0.0525098
[104]	valid_0's binary_logloss: 0.0526208
[105]	valid_0's binary_logloss: 0.0526128
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.0526631
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.0527008
[108]	valid_0's binary_logloss: 0.0526968
[109]	valid_0's binary_logloss: 0.0527472
[110]	valid_0's binary_logloss: 0.0528503
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.0528494
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 0.0528059
[113]	valid_0's binary_logloss: 0.0527845
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 0.052788

Trening klas:  69%|██████▊   | 343/500 [40:38<18:05,  6.91s/klasa, klasa=class_343, F1_klasy=0.1493, F1_macro=0.6795, drzewa=85]




Trening klas:  69%|██████▉   | 344/500 [40:38<19:07,  7.36s/klasa, klasa=class_343, F1_klasy=0.1493, F1_macro=0.6795, drzewa=85]

[115]	valid_0's binary_logloss: 0.0527987
[1]	valid_0's binary_logloss: 0.100306
[2]	valid_0's binary_logloss: 0.0877238
[3]	valid_0's binary_logloss: 0.0760058
[4]	valid_0's binary_logloss: 0.0693733
[5]	valid_0's binary_logloss: 0.0641886
[6]	valid_0's binary_logloss: 0.0713017
[7]	valid_0's binary_logloss: 0.0689465
[8]	valid_0's binary_logloss: 0.0658449
[9]	valid_0's binary_logloss: 0.0632509
[10]	valid_0's binary_logloss: 0.0607285
[11]	valid_0's binary_logloss: 0.0584571
[12]	valid_0's binary_logloss: 0.0564784
[13]	valid_0's binary_logloss: 0.0549517
[14]	valid_0's binary_logloss: 0.0531315
[15]	valid_0's binary_logloss: 0.0515505
[16]	valid_0's binary_logloss: 0.050488
[17]	valid_0's binary_logloss: 0.0489972
[18]	valid_0's binary_logloss: 0.0478403
[19]	valid_0's binary_logloss: 0.0463806
[20]	valid_0's binary_logloss: 0.0452186
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0435548
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0423715
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.0413397
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0406574
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.0395546
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.0386683
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.037873
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.036683
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.0359293
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.0350361
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.0343337
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.0338457
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.0332911
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.032699
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.0321845
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.031638
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.0311503
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.0307635
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.0302851
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.0299751
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.0295222
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.0291569
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.0287275
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.0284224
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.028108
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.0277796
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.0275493
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.0272745
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.0270957
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.0268085
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.026606
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.0263415
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.0261299
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.0258588
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.0256134
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.0253418
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.0251546
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.0249421
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.0247738
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.0246089
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.0244488
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.0243411
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.0241858
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.0240185
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.0238909
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.0237464
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.0235975
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.0234874
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.0233559
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.0232672
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.0232455
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.0230959
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.0229779
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.0229244
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.0228731
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.0228062
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.0227984
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.0227548
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.0227667
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.0227475
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.0225978
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.0224747
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.0223447
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.022228
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.0221163
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.022067
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.0220827
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.0220402
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.0220166
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.0220361
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.0219642
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.021905
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.0218728
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.0218493
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.0218441
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.0218125
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.0218046
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.0217509
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.0217398
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.0217347
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.0217964
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.0217102
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.0217557
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.0218146
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.0217796
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.0217587
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.0218258
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.0218101
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.0217575
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.0218433
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.0218274
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 0.0218143
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 0.0218235
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 0.0218581
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 0.021911
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[116]	valid_0's binary_logloss: 0.021943
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[117]	valid_0's binary_logloss: 0.0219168
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[118]	valid_0's binary_logloss: 0.0219242
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[119]	valid_0's binary_logloss: 0.021854
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[120]	valid_0's binary_logloss: 0.0218315
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[121]	valid_0's binary_logloss: 0.0218407
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[122]	valid_0's binary_logloss: 0.0218545
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[123]	valid_0's binary_logloss: 0.0218762
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[124]	valid_0's binary_logloss: 0.0218811
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[125]	valid_0's binary_logloss: 0.0218669
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[126]	valid_0's binary_logloss: 0.021861
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[127]	valid_0's binary_logloss: 0.0218743
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[128]	valid_0's binary_logloss: 0.0218586
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[129]	valid_0's binary_logloss: 0.0218441
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[130]	valid_0's binary_logloss: 0.0218439
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[131]	valid_0's binary_logloss: 0.021883
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[132]	valid_0's binary_logloss: 0.0218624

Trening klas:  69%|██████▉   | 344/500 [40:44<19:07,  7.36s/klasa, klasa=class_344, F1_klasy=0.6667, F1_macro=0.6795, drzewa=102]




Trening klas:  69%|██████▉   | 345/500 [40:44<18:00,  6.97s/klasa, klasa=class_344, F1_klasy=0.6667, F1_macro=0.6795, drzewa=102]

[1]	valid_0's binary_logloss: 0.0186705
[2]	valid_0's binary_logloss: 0.0167626
[3]	valid_0's binary_logloss: 0.0152738
[4]	valid_0's binary_logloss: 0.0140909
[5]	valid_0's binary_logloss: 0.0131187
[6]	valid_0's binary_logloss: 0.0122501
[7]	valid_0's binary_logloss: 0.0115015
[8]	valid_0's binary_logloss: 0.0108287
[9]	valid_0's binary_logloss: 0.0102336
[10]	valid_0's binary_logloss: 0.00970985
[11]	valid_0's binary_logloss: 0.00927595
[12]	valid_0's binary_logloss: 0.01095
[13]	valid_0's binary_logloss: 0.0104791
[14]	valid_0's binary_logloss: 0.0100346
[15]	valid_0's binary_logloss: 0.00963194
[16]	valid_0's binary_logloss: 0.00919115
[17]	valid_0's binary_logloss: 0.00887663
[18]	valid_0's binary_logloss: 0.0086025
[19]	valid_0's binary_logloss: 0.00829707
[20]	valid_0's binary_logloss: 0.00798323
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.00783747
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.00761197
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.00740965
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.00722436
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.00703975
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.0068225
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.00662219
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.00641077
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.00620972
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.00602302
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.00576728
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.00552452
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.00531356
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.00511437
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.0048998
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.00470396
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.00456199
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.00443163
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.00426032
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.00410996
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.00393812
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.00382274
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.00371159
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.00358836
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.00347555
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.00340221
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.00334291
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.00329844
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.00326846
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.00320484
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.00311702
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.00306082
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.00297365
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.00286495
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.0027876
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.00276078
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.00273206
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.00269532
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.00267456
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.0026488
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.00260326
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.00250557
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.00243865
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.0023726
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.00231304
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.00226863
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.00226203
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.00224917
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.00222633
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.00220912
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.00217963
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.00213193
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.00208319
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.00204976
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.00204059
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.00202506
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.00201245
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.00199106
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.00197736
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.00196387
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.00194149
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.00192221
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.00189717
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.00186513
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.00183649
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.00173974
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.00165554
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.00166079
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.00160058
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.00160254
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.00159093
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.00156313
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.0015322
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.00152863
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.0015225
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.00151513
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.00151949
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.00148868
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.00148438
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.00148927
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.00145821
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.00147027
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.00147295
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.00144981
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.00145461
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.00141009
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.00140819
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.00141777
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.00139172
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.00135592
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.00135922
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 0.00136176
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 0.00134575
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 0.00134642
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 0.00135765
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[116]	valid_0's binary_logloss: 0.00133758
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[117]	valid_0's binary_logloss: 0.00133522
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[118]	valid_0's binary_logloss: 0.00131473
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[119]	valid_0's binary_logloss: 0.00130773
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[120]	valid_0's binary_logloss: 0.00130636
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[121]	valid_0's binary_logloss: 0.00126065
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[122]	valid_0's binary_logloss: 0.00123798
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[123]	valid_0's binary_logloss: 0.00123081
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[124]	valid_0's binary_logloss: 0.00122198
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[125]	valid_0's binary_logloss: 0.00120906
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[126]	valid_0's binary_logloss: 0.00120152
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[127]	valid_0's binary_logloss: 0.00118124
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[128]	valid_0's binary_logloss: 0.00117389
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[129]	valid_0's binary_logloss: 0.00116526
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[130]	valid_0's binary_logloss: 0.00115475
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[131]	valid_0's binary_logloss: 0.0011583
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[132]	valid_0's binary_logloss: 0.0011468
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[133]	valid_0's binary_logloss: 0.00114206
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[134]	valid_0's binary_logloss: 0.0011553
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[135]	valid_0's binary_logloss: 0.00115886
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[136]	valid_0's binary_logloss: 0.00117262
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[137]	valid_0's binary_logloss: 0.00118658
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[138]	valid_0's binary_logloss: 0.00119705
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[139]	valid_0's binary_logloss: 0.00120353
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[140]	valid_0's binary_logloss: 0.0012101
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[141]	valid_0's binary_logloss: 0.001174
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[142]	valid_0's binary_logloss: 0.0011556
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[143]	valid_0's binary_logloss: 0.00113682
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[144]	valid_0's binary_logloss: 0.00112457
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[145]	valid_0's binary_logloss: 0.00111353
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[146]	valid_0's binary_logloss: 0.00111821
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[147]	valid_0's binary_logloss: 0.00110683
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[148]	valid_0's binary_logloss: 0.00110637
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[149]	valid_0's binary_logloss: 0.00110544
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[150]	valid_0's binary_logloss: 0.00110375
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[151]	valid_0's binary_logloss: 0.0011157
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[152]	valid_0's binary_logloss: 0.00111759
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[153]	valid_0's binary_logloss: 0.00111546
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[154]	valid_0's binary_logloss: 0.00112095
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[155]	valid_0's binary_logloss: 0.00112072
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[156]	valid_0's binary_logloss: 0.00111839
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[157]	valid_0's binary_logloss: 0.00111674
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[158]	valid_0's binary_logloss: 0.00112617
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[159]	valid_0's binary_logloss: 0.00112565
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[160]	valid_0's binary_logloss: 0.0011345
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[161]	valid_0's binary_logloss: 0.0011345
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[162]	valid_0's binary_logloss: 0.00113009
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[163]	valid_0's binary_logloss: 0.00113816
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[164]	valid_0's binary_logloss: 0.00115152
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[165]	valid_0's binary_logloss: 0.00116593
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[166]	valid_0's binary_logloss: 0.0011298
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[167]	valid_0's binary_logloss: 0.00108037
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[168]	valid_0's binary_logloss: 0.0010454
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[169]	valid_0's binary_logloss: 0.00105374
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[170]	valid_0's binary_logloss: 0.00105625
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[171]	valid_0's binary_logloss: 0.00106345
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[172]	valid_0's binary_logloss: 0.00106626
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[173]	valid_0's binary_logloss: 0.00106733
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[174]	valid_0's binary_logloss: 0.0010745
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[175]	valid_0's binary_logloss: 0.00107876
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[176]	valid_0's binary_logloss: 0.00100958
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[177]	valid_0's binary_logloss: 0.00101125
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[178]	valid_0's binary_logloss: 0.000989956
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[179]	valid_0's binary_logloss: 0.000977872
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[180]	valid_0's binary_logloss: 0.000975172
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[181]	valid_0's binary_logloss: 0.000983551
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[182]	valid_0's binary_logloss: 0.000976076
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[183]	valid_0's binary_logloss: 0.00096741

Trening klas:  69%|██████▉   | 345/500 [40:54<18:00,  6.97s/klasa, klasa=class_345, F1_klasy=0.8889, F1_macro=0.6801, drzewa=192]




Trening klas:  69%|██████▉   | 346/500 [40:54<19:40,  7.67s/klasa, klasa=class_345, F1_klasy=0.8889, F1_macro=0.6801, drzewa=192]

[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[221]	valid_0's binary_logloss: 0.00112198
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[222]	valid_0's binary_logloss: 0.00111386
[1]	valid_0's binary_logloss: 0.0114482
[2]	valid_0's binary_logloss: 0.011195
[3]	valid_0's binary_logloss: 0.0109914
[4]	valid_0's binary_logloss: 0.010716
[5]	valid_0's binary_logloss: 0.0104012
[6]	valid_0's binary_logloss: 0.0101869
[7]	valid_0's binary_logloss: 0.0100953
[8]	valid_0's binary_logloss: 0.00987421
[9]	valid_0's binary_logloss: 0.00966377
[10]	valid_0's binary_logloss: 0.00947963
[11]	valid_0's binary_logloss: 0.00930707
[12]	valid_0's binary_logloss: 0.00913246
[13]	valid_0's binary_logloss: 0.00897921
[14]	valid_0's binary_logloss: 0.00882802
[15]	valid_0's binary_logloss: 0.00863472
[16]	valid_0's binary_logloss: 0.00856625
[17]	valid_0's binary_logloss: 0.00851158
[18]	valid_0's binary_logloss: 0.0083267
[19]	valid_0's binary_logloss: 0.00828383
[20]	valid_0's binary_logloss: 0.00822625
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.00809206
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.00798278
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.00788726
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.00776448
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.00767111
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.00760023
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.00756201
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.00749338
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.00744099
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.00743286
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.0073666
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.00735139
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.00733503
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.00730382
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.00725703
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.00726678
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.00716759
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.00719334
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.00720572
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.00719847
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.00720411
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.00724137
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.00722359
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.00724619
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.00727042
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.00722254
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.00718079
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.00713752
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.00710641
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.007072
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.0070859
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.00706944
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.00704109
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.00704829
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.00705424
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.0070971
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.00710903
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.00711265
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.00714957
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.00714257
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.00717424
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.0071836
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.00719772
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.00721711
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.00725163
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.00724301
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.00725064
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.00729114
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.00739895
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.00741647
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.00744502
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.00743242
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.00742053
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.0074623
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.00751772
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.00757001
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.00754192
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.00753092
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.00752018
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.00751343
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.00757893
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.00759014
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.00758814

Trening klas:  69%|██████▉   | 346/500 [40:58<19:40,  7.67s/klasa, klasa=class_346, F1_klasy=0.5000, F1_macro=0.6796, drzewa=53]




Trening klas:  69%|██████▉   | 347/500 [40:58<16:44,  6.56s/klasa, klasa=class_346, F1_klasy=0.5000, F1_macro=0.6796, drzewa=53]

[1]	valid_0's binary_logloss: 0.012816
[2]	valid_0's binary_logloss: 0.0120706
[3]	valid_0's binary_logloss: 0.0114037
[4]	valid_0's binary_logloss: 0.0107557
[5]	valid_0's binary_logloss: 0.0101493
[6]	valid_0's binary_logloss: 0.0119204
[7]	valid_0's binary_logloss: 0.0113352
[8]	valid_0's binary_logloss: 0.0107736
[9]	valid_0's binary_logloss: 0.0102778
[10]	valid_0's binary_logloss: 0.00979946
[11]	valid_0's binary_logloss: 0.00935394
[12]	valid_0's binary_logloss: 0.00892344
[13]	valid_0's binary_logloss: 0.008539
[14]	valid_0's binary_logloss: 0.00817531
[15]	valid_0's binary_logloss: 0.00780944
[16]	valid_0's binary_logloss: 0.00749641
[17]	valid_0's binary_logloss: 0.00720613
[18]	valid_0's binary_logloss: 0.00688367
[19]	valid_0's binary_logloss: 0.00658137
[20]	valid_0's binary_logloss: 0.00628884
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.00600801
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.00574048
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.00548508
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.00523187
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.005006
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.00478159
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.00456629
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.00435937
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.00416231
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.00397665
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.00386263
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.00369169
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.00352746
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.00336913
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.0032192
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.00307727
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.00294245
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.00281117
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.00268556
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.00256749
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.00244785
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.00229882
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.00220098
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.00210192
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.00200761
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.0019151
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.00182702
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.00174284
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.00166324
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.00158693
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.00151533
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.00144782
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.00140057
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.0013384
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.00131541
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.00125719
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.00120206
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.00114868
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.00109746
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.00104609
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.00101989
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.000984659
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.000952563
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.000920864
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.000882071
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.000842658
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.000803466
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.000765892
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.000730171
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.000696246
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.000673819
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.000644587
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.00061337
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.000586856
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.000557908
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.000533248
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.000509044
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.00048826
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.000466717
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.000445949
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.000426188
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.000408639
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.000390639
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.000373612
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.000357212
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.000343461
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.000331547
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.000318805
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.000304933
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.000293895
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.000281584
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.000275231
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.000262871
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.00025152
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.000244033
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.000236058
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.00022675
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.000217844
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.000209517
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.000201223
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.000193514
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.000185753
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.000178997
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.000171938
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.000165247
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.000159277
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.000153336
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.000149208
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.000148032
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.000147088
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.000142773
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 0.000136964
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 0.000132986
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 0.000130426
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 0.000125118
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[116]	valid_0's binary_logloss: 0.00012221
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[117]	valid_0's binary_logloss: 0.000122442
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[118]	valid_0's binary_logloss: 0.000123013
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[119]	valid_0's binary_logloss: 0.000120681
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[120]	valid_0's binary_logloss: 0.000118453
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[121]	valid_0's binary_logloss: 0.000113895
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[122]	valid_0's binary_logloss: 0.000109549
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[123]	valid_0's binary_logloss: 0.000105407
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[124]	valid_0's binary_logloss: 0.000101458
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[125]	valid_0's binary_logloss: 9.76938e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[126]	valid_0's binary_logloss: 9.34842e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[127]	valid_0's binary_logloss: 8.97172e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[128]	valid_0's binary_logloss: 8.58041e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[129]	valid_0's binary_logloss: 8.22221e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[130]	valid_0's binary_logloss: 7.91944e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[131]	valid_0's binary_logloss: 7.69702e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[132]	valid_0's binary_logloss: 7.48441e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[133]	valid_0's binary_logloss: 7.2827e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[134]	valid_0's binary_logloss: 7.09247e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[135]	valid_0's binary_logloss: 6.90909e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[136]	valid_0's binary_logloss: 6.69623e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[137]	valid_0's binary_logloss: 6.49407e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[138]	valid_0's binary_logloss: 6.30745e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[139]	valid_0's binary_logloss: 6.10452e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[140]	valid_0's binary_logloss: 5.94923e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[141]	valid_0's binary_logloss: 5.95883e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[142]	valid_0's binary_logloss: 5.8384e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[143]	valid_0's binary_logloss: 5.93662e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[144]	valid_0's binary_logloss: 6.03782e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[145]	valid_0's binary_logloss: 6.14927e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[146]	valid_0's binary_logloss: 6.14611e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[147]	valid_0's binary_logloss: 5.91279e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[148]	valid_0's binary_logloss: 5.70713e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[149]	valid_0's binary_logloss: 5.68608e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[150]	valid_0's binary_logloss: 5.73053e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[151]	valid_0's binary_logloss: 5.53446e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[152]	valid_0's binary_logloss: 5.36569e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[153]	valid_0's binary_logloss: 5.21515e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[154]	valid_0's binary_logloss: 5.05505e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[155]	valid_0's binary_logloss: 4.88565e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[156]	valid_0's binary_logloss: 4.78147e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[157]	valid_0's binary_logloss: 4.67102e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[158]	valid_0's binary_logloss: 4.48758e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[159]	valid_0's binary_logloss: 4.40316e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[160]	valid_0's binary_logloss: 4.31829e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[161]	valid_0's binary_logloss: 4.21302e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[162]	valid_0's binary_logloss: 4.19074e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[163]	valid_0's binary_logloss: 4.15467e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[164]	valid_0's binary_logloss: 4.13126e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[165]	valid_0's binary_logloss: 4.04251e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[166]	valid_0's binary_logloss: 3.90897e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[167]	valid_0's binary_logloss: 3.78123e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[168]	valid_0's binary_logloss: 3.74399e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[169]	valid_0's binary_logloss: 3.76773e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[170]	valid_0's binary_logloss: 3.6483e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[171]	valid_0's binary_logloss: 3.53459e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[172]	valid_0's binary_logloss: 3.45853e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[173]	valid_0's binary_logloss: 3.35013e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[174]	valid_0's binary_logloss: 3.32982e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[175]	valid_0's binary_logloss: 3.22823e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[176]	valid_0's binary_logloss: 3.20177e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[177]	valid_0's binary_logloss: 3.16196e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[178]	valid_0's binary_logloss: 3.13362e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[179]	valid_0's binary_logloss: 3.04338e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[180]	valid_0's binary_logloss: 3.01529e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[181]	valid_0's binary_logloss: 3.03568e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[182]	valid_0's binary_logloss: 3.00814e-05

Trening klas:  69%|██████▉   | 347/500 [41:06<16:44,  6.56s/klasa, klasa=class_347, F1_klasy=0.0000, F1_macro=0.6776, drzewa=300]




Trening klas:  70%|██████▉   | 348/500 [41:06<18:07,  7.16s/klasa, klasa=class_347, F1_klasy=0.0000, F1_macro=0.6776, drzewa=300]

[300]	valid_0's binary_logloss: 9.72726e-06
[1]	valid_0's binary_logloss: 0.291989
[2]	valid_0's binary_logloss: 0.190315
[3]	valid_0's binary_logloss: 0.184326
[4]	valid_0's binary_logloss: 0.17991
[5]	valid_0's binary_logloss: 0.175651
[6]	valid_0's binary_logloss: 0.291065
[7]	valid_0's binary_logloss: 0.280679
[8]	valid_0's binary_logloss: 0.276319
[9]	valid_0's binary_logloss: 0.272934
[10]	valid_0's binary_logloss: 0.27016
[11]	valid_0's binary_logloss: 0.268043
[12]	valid_0's binary_logloss: 0.266584
[13]	valid_0's binary_logloss: 0.265292
[14]	valid_0's binary_logloss: 0.263865
[15]	valid_0's binary_logloss: 0.261141
[16]	valid_0's binary_logloss: 0.259923
[17]	valid_0's binary_logloss: 0.258605
[18]	valid_0's binary_logloss: 0.257008
[19]	valid_0's binary_logloss: 0.255945
[20]	valid_0's binary_logloss: 0.254659
[21]	valid_0's binary_logloss: 0.253558
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.252391
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.251382
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.249979
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.248921
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.247937
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.247121
[28]	valid_0's binary_logloss: 0.246146
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.245165
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.244207
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

Trening klas:  70%|██████▉   | 348/500 [41:09<18:07,  7.16s/klasa, klasa=class_348, F1_klasy=0.4258, F1_macro=0.6769, drzewa=5]




Trening klas:  70%|██████▉   | 349/500 [41:09<14:56,  5.93s/klasa, klasa=class_348, F1_klasy=0.4258, F1_macro=0.6769, drzewa=5]

[31]	valid_0's binary_logloss: 0.243134
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.242494
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.241626
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.240809
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.240125
[1]	valid_0's binary_logloss: 0.0190712
[2]	valid_0's binary_logloss: 0.0181979
[3]	valid_0's binary_logloss: 0.0170104
[4]	valid_0's binary_logloss: 0.0161179
[5]	valid_0's binary_logloss: 0.0153606
[6]	valid_0's binary_logloss: 0.01528
[7]	valid_0's binary_logloss: 0.0146515
[8]	valid_0's binary_logloss: 0.0141347
[9]	valid_0's binary_logloss: 0.0136599
[10]	valid_0's binary_logloss: 0.0132649
[11]	valid_0's binary_logloss: 0.0128847
[12]	valid_0's binary_logloss: 0.0125982
[13]	valid_0's binary_logloss: 0.0122432
[14]	valid_0's binary_logloss: 0.0119808
[15]	valid_0's binary_logloss: 0.0116778
[16]	valid_0's binary_logloss: 0.0114547
[17]	valid_0's binary_logloss: 0.0111849
[18]	valid_0's binary_logloss: 0.0109532
[19]	valid_0's binary_logloss: 0.0106812
[20]	valid_0's binary_logloss: 0.0104432
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0104601
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0102671
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.0100975
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.00992599
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.00972451
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.0095592
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.00929259
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.00913572
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.00899595
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.00887244
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.00872987
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.00861547
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.00849415
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.00838043
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.00826243
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.00813052
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.00788086
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.0076872
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.00756973
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.00736433
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.00730442
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.00724913
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.00718322
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.00711573
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.00704968
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.00700313
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.00698162
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.00695065
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.00692369
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.00690139
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.00684712
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.00681531
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.00673174
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.00669209
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.00656828
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.00645918
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.00630048
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.00620414
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.00612186
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.00610645
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.00607003
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.00600617
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.00601762
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.00598821
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.00596379
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.00595704
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.00593582
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.00590789
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.00584468
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.00574993
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.00568065
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.00562946
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.0055635
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.00549561
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.00542639
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.00532463
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.0052916
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.00527975
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.00524284
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.00519404
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.00518285
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.00510306
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.00507916
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.00496561
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.00495945
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.00492443
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.0048895
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.0048559
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.00481477
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.00478847
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.00477694
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.00477292
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.00473387
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.00472273
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.00471061
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.00469888
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.00472402
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.00474672
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.00477104
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.004795
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.00480929
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.00474876
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.00473757
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.00476741
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.00476683
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.00477842
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.00474075
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.00472898
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.00471956
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.00471321
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.00473376
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 0.0047801
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 0.0048278
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 0.00484811
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 0.00487849
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[116]	valid_0's binary_logloss: 0.00488975
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[117]	valid_0's binary_logloss: 0.0049263
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[118]	valid_0's binary_logloss: 0.00490254
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[119]	valid_0's binary_logloss: 0.00487943
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

Trening klas:  70%|██████▉   | 349/500 [41:13<14:56,  5.93s/klasa, klasa=class_349, F1_klasy=0.7907, F1_macro=0.6772, drzewa=96]




Trening klas:  70%|███████   | 350/500 [41:13<13:27,  5.39s/klasa, klasa=class_349, F1_klasy=0.7907, F1_macro=0.6772, drzewa=96]

[120]	valid_0's binary_logloss: 0.00491663
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[121]	valid_0's binary_logloss: 0.00487175
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[122]	valid_0's binary_logloss: 0.00482759
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[123]	valid_0's binary_logloss: 0.00481924
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[124]	valid_0's binary_logloss: 0.00480191
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[125]	valid_0's binary_logloss: 0.00475914
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[126]	valid_0's binary_logloss: 0.00475343
[1]	valid_0's binary_logloss: 0.284206
[2]	valid_0's binary_logloss: 0.124861
[3]	valid_0's binary_logloss: 0.12191
[4]	valid_0's binary_logloss: 0.119724
[5]	valid_0's binary_logloss: 0.118102
[6]	valid_0's binary_logloss: 0.114666
[7]	valid_0's binary_logloss: 0.11265
[8]	valid_0's binary_logloss: 0.111727
[9]	valid_0's binary_logloss: 0.11089
[10]	valid_0's binary_logloss: 0.110274
[11]	valid_0's binary_logloss: 0.109304
[12]	valid_0's binary_logloss: 0.108676
[13]	valid_0's binary_logloss: 0.107953
[14]	valid_0's binary_logloss: 0.107562
[15]	valid_0's binary_logloss: 0.10709
[16]	valid_0's binary_logloss: 0.106531
[17]	valid_0's binary_logloss: 0.106007
[18]	valid_0's binary_logloss: 0.1055
[19]	valid_0's binary_logloss: 0.105002
[20]	valid_0's binary_logloss: 0.104529
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.104201
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.103881
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.103622
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.103374
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.1031
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.102731
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.102494
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.102289
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.10198
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.101891
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.10178
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.101505
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.101423
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.101401
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.101321
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.101268
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.101153
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.101079
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.100941
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.100871
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.100718
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.1006
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.10033
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.100199
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.100027
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.0999315
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.0997559
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.0996106
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.0994794
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.0993781
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.0992065
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.0990671
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.0989868
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.0988824
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.0987055
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.0985156
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.0984124
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.0982604
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.0980907
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.0980704
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.0980805
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.0979378
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.0979138
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.0979607
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.0979948
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.097911
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.0978938
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.0976277
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.0974275
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.0972027
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.0971035
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.0970948
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.0970494
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.0970827
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.0968761
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.0967285
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.0966965
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.0966096
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.0965379
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.096457
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.0964771
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.0964564
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.0964374
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.0965579
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.0966063
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.0964913
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.0962774
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.0962051
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.0961658
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.0960838
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.0960197
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.0959796
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.095862
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.0958597
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.0957957
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.0958684
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.0959416
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.0960283
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.0960808
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.0961079
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.0960437
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.0959596
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.0958992
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.095852
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.0958093
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.0958128
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.0958233
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.095855
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.0958724
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.0959021
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.095876
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 0.095886
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 0.0959015
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 0.0959737
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 0.0959831
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[116]	valid_0's binary_logloss: 0.0959404
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[117]	valid_0's binary_logloss: 0.0959358
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[118]	valid_0's binary_logloss: 0.0960214
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[119]	valid_0's binary_logloss: 0.0960317
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[120]	valid_0's binary_logloss: 0.0959611
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[121]	valid_0's binary_logloss: 0.0959542
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

Trening klas:  70%|███████   | 350/500 [41:18<13:27,  5.39s/klasa, klasa=class_350, F1_klasy=0.5923, F1_macro=0.6770, drzewa=95]




Trening klas:  70%|███████   | 351/500 [41:18<12:40,  5.10s/klasa, klasa=class_350, F1_klasy=0.5923, F1_macro=0.6770, drzewa=95]

[122]	valid_0's binary_logloss: 0.095898
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[123]	valid_0's binary_logloss: 0.095803
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[124]	valid_0's binary_logloss: 0.0958828
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[125]	valid_0's binary_logloss: 0.0958174
[1]	valid_0's binary_logloss: 0.021131
[2]	valid_0's binary_logloss: 0.0194561
[3]	valid_0's binary_logloss: 0.0177726
[4]	valid_0's binary_logloss: 0.0168271
[5]	valid_0's binary_logloss: 0.0157999
[6]	valid_0's binary_logloss: 0.0149272
[7]	valid_0's binary_logloss: 0.0141277
[8]	valid_0's binary_logloss: 0.0132127
[9]	valid_0's binary_logloss: 0.0124012
[10]	valid_0's binary_logloss: 0.011659
[11]	valid_0's binary_logloss: 0.0109604
[12]	valid_0's binary_logloss: 0.0103221
[13]	valid_0's binary_logloss: 0.00972197
[14]	valid_0's binary_logloss: 0.00916675
[15]	valid_0's binary_logloss: 0.00865811
[16]	valid_0's binary_logloss: 0.00820558
[17]	valid_0's binary_logloss: 0.0077942
[18]	valid_0's binary_logloss: 0.00737651
[19]	valid_0's binary_logloss: 0.00698695
[20]	valid_0's binary_logloss: 0.0066208
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.00629605
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.00597997
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.00567483
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.00538978
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.00511665
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.00487012
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.00464154
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.00441146
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.00419243
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.00399411
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.003793
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.00361641
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.00343263
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.0032622
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.0031079
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.00297465
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.00283754
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.00273697
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.00262294
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.00249804
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.0023799
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.00226655
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.00215948
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.00205846
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.00196168
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.00188256
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.00179615
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.00172149
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.00164333
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.00157985
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.00150607
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.00143643
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.00137053
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.0013064
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.00124543
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.00119567
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.00116489
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.00113029
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.0010783
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.00102823
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.000977587
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.000928938
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.00088362
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.000839718
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.000798637
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.000763531
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.000728915
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.000701116
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.000670661
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.000640646
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.000611554
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.00058441
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.000558194
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.000533624
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.000509988
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.000496395
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.000478892
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.000459356
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.000441073
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.0004292
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.000409698
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.00039228
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.000374973
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.000359532
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.000345228
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.000329333
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.00031413
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.000299752
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.000286101
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.000273179
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.000263422
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.000254372
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.000245785
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.000237826
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.000231859
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.000227512
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.000222783
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.000216832
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.00021076
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.000206987
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.000202183
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.000194877
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.000187621
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.000181869
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.000176925
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.000170521
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.00016498
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.000159806
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.00015496
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.000153039
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.000147334
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 0.000145905
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 0.000142228
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 0.000139853
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 0.000135327
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[116]	valid_0's binary_logloss: 0.000131964
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[117]	valid_0's binary_logloss: 0.000130071
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[118]	valid_0's binary_logloss: 0.000127075
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[119]	valid_0's binary_logloss: 0.000125252
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[120]	valid_0's binary_logloss: 0.00012422
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[121]	valid_0's binary_logloss: 0.000119944
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[122]	valid_0's binary_logloss: 0.000117079
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[123]	valid_0's binary_logloss: 0.00011428
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[124]	valid_0's binary_logloss: 0.000111163
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[125]	valid_0's binary_logloss: 0.000107449
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[126]	valid_0's binary_logloss: 0.000104599
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[127]	valid_0's binary_logloss: 0.000101657
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[128]	valid_0's binary_logloss: 9.93005e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[129]	valid_0's binary_logloss: 9.71259e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[130]	valid_0's binary_logloss: 9.39564e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[131]	valid_0's binary_logloss: 9.29145e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[132]	valid_0's binary_logloss: 9.12957e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[133]	valid_0's binary_logloss: 9.07594e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[134]	valid_0's binary_logloss: 8.8744e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[135]	valid_0's binary_logloss: 8.75008e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[136]	valid_0's binary_logloss: 8.68203e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[137]	valid_0's binary_logloss: 8.46746e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[138]	valid_0's binary_logloss: 8.19534e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[139]	valid_0's binary_logloss: 7.96724e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[140]	valid_0's binary_logloss: 7.82181e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[141]	valid_0's binary_logloss: 7.61134e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[142]	valid_0's binary_logloss: 7.43234e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[143]	valid_0's binary_logloss: 7.24093e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[144]	valid_0's binary_logloss: 7.05845e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[145]	valid_0's binary_logloss: 6.88703e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[146]	valid_0's binary_logloss: 6.89758e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[147]	valid_0's binary_logloss: 6.73754e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[148]	valid_0's binary_logloss: 6.6264e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[149]	valid_0's binary_logloss: 6.57759e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[150]	valid_0's binary_logloss: 6.46612e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[151]	valid_0's binary_logloss: 6.37272e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[152]	valid_0's binary_logloss: 6.30049e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[153]	valid_0's binary_logloss: 6.22723e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[154]	valid_0's binary_logloss: 6.1559e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[155]	valid_0's binary_logloss: 6.07897e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[156]	valid_0's binary_logloss: 5.95546e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[157]	valid_0's binary_logloss: 5.96123e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[158]	valid_0's binary_logloss: 5.99111e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[159]	valid_0's binary_logloss: 5.84241e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[160]	valid_0's binary_logloss: 5.86579e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[161]	valid_0's binary_logloss: 5.65778e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[162]	valid_0's binary_logloss: 5.49613e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[163]	valid_0's binary_logloss: 5.34356e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[164]	valid_0's binary_logloss: 5.19249e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[165]	valid_0's binary_logloss: 5.01092e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[166]	valid_0's binary_logloss: 4.99504e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[167]	valid_0's binary_logloss: 4.98466e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[168]	valid_0's binary_logloss: 4.86616e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[169]	valid_0's binary_logloss: 4.86783e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[170]	valid_0's binary_logloss: 4.8813e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[171]	valid_0's binary_logloss: 4.82107e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[172]	valid_0's binary_logloss: 4.7735e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[173]	valid_0's binary_logloss: 4.72449e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[174]	valid_0's binary_logloss: 4.66849e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[175]	valid_0's binary_logloss: 4.55777e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[176]	valid_0's binary_logloss: 4.5148e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[177]	valid_0's binary_logloss: 4.43231e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[178]	valid_0's binary_logloss: 4.38646e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[179]	valid_0's binary_logloss: 4.34895e-05

Trening klas:  70%|███████   | 351/500 [41:25<12:40,  5.10s/klasa, klasa=class_351, F1_klasy=0.0000, F1_macro=0.6750, drzewa=300]




Trening klas:  70%|███████   | 352/500 [41:25<14:00,  5.68s/klasa, klasa=class_351, F1_klasy=0.0000, F1_macro=0.6750, drzewa=300]

[299]	valid_0's binary_logloss: 1.30446e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[300]	valid_0's binary_logloss: 1.30172e-05
[1]	valid_0's binary_logloss: 0.0146681
[2]	valid_0's binary_logloss: 0.0130557
[3]	valid_0's binary_logloss: 0.0118807
[4]	valid_0's binary_logloss: 0.0109902
[5]	valid_0's binary_logloss: 0.0103147
[6]	valid_0's binary_logloss: 0.0109561
[7]	valid_0's binary_logloss: 0.0103096
[8]	valid_0's binary_logloss: 0.00974741
[9]	valid_0's binary_logloss: 0.0092317
[10]	valid_0's binary_logloss: 0.00874064
[11]	valid_0's binary_logloss: 0.00827167
[12]	valid_0's binary_logloss: 0.00784964
[13]	valid_0's binary_logloss: 0.00745629
[14]	valid_0's binary_logloss: 0.00708985
[15]	valid_0's binary_logloss: 0.00676473
[16]	valid_0's binary_logloss: 0.00643888
[17]	valid_0's binary_logloss: 0.00612253
[18]	valid_0's binary_logloss: 0.00581928
[19]	valid_0's binary_logloss: 0.00553365
[20]	valid_0's binary_logloss: 0.00525426
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.00499597
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0047496
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.00451644
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.00429677
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.00408913
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.00389452
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.00370233
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.00352143
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.00334972
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.00318867
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.00306545
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.00291404
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.00277716
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.00264638
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.00251661
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.00239007
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.00227043
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.00216112
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.00205365
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.00195184
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.00185569
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.00176207
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.00167513
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.00159125
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.00151289
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.00144225
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.00137673
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.00130583
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.00123908
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.00117634
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.00111921
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.00106475
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.00101331
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.000964446
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.000915841
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.000870533
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.000828452
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.00078771
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.000750053
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.000713441
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.000677616
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.000648165
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.000620103
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.000590254
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.000562246
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.000538832
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.00051571
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.0004927
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.000473506
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.00045477
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.000432563
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.000411447
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.000392814
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.000375914
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.00035911
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.000341834
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.000325541
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.000310212
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.000295704
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.000281533
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.000268456
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.000254733
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.00024201
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.000231501
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.000220571
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.000210648
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.00020137
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.000193526
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.000185501
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.000177382
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.000169719
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.000164577
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.000157559
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.000149419
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.000144417
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.000140048
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.000134174
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.00012953
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.00012469
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.000119623
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.000115148
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.000110045
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.000106215
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.000102124
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 9.77303e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 9.29266e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 9.00938e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 8.56984e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 8.22969e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 7.94166e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 7.69372e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 7.38874e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 7.04098e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 6.86162e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 6.70192e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[116]	valid_0's binary_logloss: 6.59904e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[117]	valid_0's binary_logloss: 6.47504e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[118]	valid_0's binary_logloss: 6.3737e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[119]	valid_0's binary_logloss: 6.26654e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[120]	valid_0's binary_logloss: 6.15994e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[121]	valid_0's binary_logloss: 5.9879e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[122]	valid_0's binary_logloss: 5.77895e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[123]	valid_0's binary_logloss: 5.69822e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[124]	valid_0's binary_logloss: 5.49926e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[125]	valid_0's binary_logloss: 5.38207e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[126]	valid_0's binary_logloss: 5.20227e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[127]	valid_0's binary_logloss: 5.10742e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[128]	valid_0's binary_logloss: 4.96748e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[129]	valid_0's binary_logloss: 4.81081e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[130]	valid_0's binary_logloss: 4.66345e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[131]	valid_0's binary_logloss: 4.4765e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[132]	valid_0's binary_logloss: 4.31004e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[133]	valid_0's binary_logloss: 4.20854e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[134]	valid_0's binary_logloss: 4.0665e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[135]	valid_0's binary_logloss: 3.92916e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[136]	valid_0's binary_logloss: 3.87736e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[137]	valid_0's binary_logloss: 3.84834e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[138]	valid_0's binary_logloss: 3.79113e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[139]	valid_0's binary_logloss: 3.77326e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[140]	valid_0's binary_logloss: 3.74111e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[141]	valid_0's binary_logloss: 3.64911e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[142]	valid_0's binary_logloss: 3.54943e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[143]	valid_0's binary_logloss: 3.48485e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[144]	valid_0's binary_logloss: 3.40262e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[145]	valid_0's binary_logloss: 3.35581e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[146]	valid_0's binary_logloss: 3.25201e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[147]	valid_0's binary_logloss: 3.16241e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[148]	valid_0's binary_logloss: 3.07915e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[149]	valid_0's binary_logloss: 3.03664e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[150]	valid_0's binary_logloss: 2.97685e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[151]	valid_0's binary_logloss: 2.86965e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[152]	valid_0's binary_logloss: 2.76998e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[153]	valid_0's binary_logloss: 2.67335e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[154]	valid_0's binary_logloss: 2.58597e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[155]	valid_0's binary_logloss: 2.50163e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[156]	valid_0's binary_logloss: 2.43345e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[157]	valid_0's binary_logloss: 2.38057e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[158]	valid_0's binary_logloss: 2.32219e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[159]	valid_0's binary_logloss: 2.28683e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[160]	valid_0's binary_logloss: 2.2349e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[161]	valid_0's binary_logloss: 2.18427e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[162]	valid_0's binary_logloss: 2.1514e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[163]	valid_0's binary_logloss: 2.10554e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[164]	valid_0's binary_logloss: 2.08059e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[165]	valid_0's binary_logloss: 2.04217e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[166]	valid_0's binary_logloss: 2.03017e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[167]	valid_0's binary_logloss: 2.02208e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[168]	valid_0's binary_logloss: 2.01608e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[169]	valid_0's binary_logloss: 2.006e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[170]	valid_0's binary_logloss: 2.00208e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[171]	valid_0's binary_logloss: 1.97909e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[172]	valid_0's binary_logloss: 1.95662e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[173]	valid_0's binary_logloss: 1.94188e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[174]	valid_0's binary_logloss: 1.92522e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[175]	valid_0's binary_logloss: 1.89774e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[176]	valid_0's binary_logloss: 1.86551e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[177]	valid_0's binary_logloss: 1.85632e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[178]	valid_0's binary_logloss: 1.81266e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[179]	valid_0's binary_logloss: 1.79357e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[180]	valid_0's binary_logloss: 1.76968e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

[294]	valid_0's binary_logloss: 7.74792e-06
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[295]	valid_0's binary_logloss: 7.77895e-06
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[296]	valid_0's binary_logloss: 7.77962e-06
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[297]	valid_0's binary_logloss: 7.86354e-06
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[298]	valid_0's binary_logloss: 7.82477e-06
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[299]	valid_0's binary_logloss: 7.78708e-06
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[300]	valid_0's binary_logloss: 7.73993e-06

Trening klas:  70%|███████   | 352/500 [41:34<14:00,  5.68s/klasa, klasa=class_352, F1_klasy=0.0000, F1_macro=0.6731, drzewa=300]




Trening klas:  71%|███████   | 353/500 [41:34<16:30,  6.74s/klasa, klasa=class_352, F1_klasy=0.0000, F1_macro=0.6731, drzewa=300]

[1]	valid_0's binary_logloss: 0.0305872
[2]	valid_0's binary_logloss: 0.0279602
[3]	valid_0's binary_logloss: 0.0258629
[4]	valid_0's binary_logloss: 0.023751
[5]	valid_0's binary_logloss: 0.0221052
[6]	valid_0's binary_logloss: 0.0221931
[7]	valid_0's binary_logloss: 0.0207109
[8]	valid_0's binary_logloss: 0.0194639
[9]	valid_0's binary_logloss: 0.018266
[10]	valid_0's binary_logloss: 0.0172096
[11]	valid_0's binary_logloss: 0.0162448
[12]	valid_0's binary_logloss: 0.0154074
[13]	valid_0's binary_logloss: 0.0146327
[14]	valid_0's binary_logloss: 0.0138771
[15]	valid_0's binary_logloss: 0.0131523
[16]	valid_0's binary_logloss: 0.0125204
[17]	valid_0's binary_logloss: 0.011877
[18]	valid_0's binary_logloss: 0.0113548
[19]	valid_0's binary_logloss: 0.0108564
[20]	valid_0's binary_logloss: 0.0103601
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.00989381
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.00947745
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.00911891
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.00874517
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.00838148
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.00802278
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.0076669
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.0073414
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.00703038
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.00670623
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.00643792
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.00617943
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.00592497
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.00575721
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.00553721
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.0053226
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.00509131
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.00490323
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.00471709
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.00453937
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.00434763
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.00416506
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.00400955
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.00384315
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.00368273
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.00354066
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.00342342
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.00331289
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.00321404
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.00309322
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.0029741
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.00287464
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.00278684
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.00269964
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.00259975
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.0025286
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.00245666
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.00237155
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.00231646
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.00225975
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.00220423
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.00213259
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.00206508
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.00199982
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.00195802
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.00190731
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.00186068
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.00181575
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.00177409
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.00173678
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.00168994
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.00163263
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.00159099
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.00153733
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.00151312
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.00147945
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.00144811
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.00141899
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.00139306
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.00135215
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.00132775
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.00129455
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.00126102
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.00124016
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.00121608
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.00119273
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.00117829
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.00116582
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.00115569
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.00114532
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.00112613
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.00111559
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.00110654
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.00109879
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.00109769
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.0010966
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.00108254
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.00107559
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.0010529
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.00104854
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.00103947
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.0010301
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.0010218
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.00101968
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.00099371
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.000973027
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.000951416
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.000932883
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.000914539
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.000902382
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.000885408
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 0.000858292
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 0.000837476
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 0.000817455
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 0.000798314
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[116]	valid_0's binary_logloss: 0.000796012
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[117]	valid_0's binary_logloss: 0.000786669
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[118]	valid_0's binary_logloss: 0.000787453
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[119]	valid_0's binary_logloss: 0.000794108
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[120]	valid_0's binary_logloss: 0.000796423
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[121]	valid_0's binary_logloss: 0.0007981
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[122]	valid_0's binary_logloss: 0.000801429
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[123]	valid_0's binary_logloss: 0.000802706
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[124]	valid_0's binary_logloss: 0.000805647
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[125]	valid_0's binary_logloss: 0.000805542
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[126]	valid_0's binary_logloss: 0.000796381
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[127]	valid_0's binary_logloss: 0.00079337
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[128]	valid_0's binary_logloss: 0.000773377
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[129]	valid_0's binary_logloss: 0.000768666
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[130]	valid_0's binary_logloss: 0.000757102
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[131]	valid_0's binary_logloss: 0.000748371
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[132]	valid_0's binary_logloss: 0.000745667
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[133]	valid_0's binary_logloss: 0.000747742
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[134]	valid_0's binary_logloss: 0.00074694
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[135]	valid_0's binary_logloss: 0.000748178
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[136]	valid_0's binary_logloss: 0.000742765
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[137]	valid_0's binary_logloss: 0.000737956
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[138]	valid_0's binary_logloss: 0.000727144
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[139]	valid_0's binary_logloss: 0.000716671
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[140]	valid_0's binary_logloss: 0.000723265
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[141]	valid_0's binary_logloss: 0.000719723
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[142]	valid_0's binary_logloss: 0.000711473
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[143]	valid_0's binary_logloss: 0.000703438
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[144]	valid_0's binary_logloss: 0.00070453
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[145]	valid_0's binary_logloss: 0.00069701
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[146]	valid_0's binary_logloss: 0.000690656
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[147]	valid_0's binary_logloss: 0.000684716
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[148]	valid_0's binary_logloss: 0.000678898
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[149]	valid_0's binary_logloss: 0.000669421
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[150]	valid_0's binary_logloss: 0.000664685
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[151]	valid_0's binary_logloss: 0.000650713
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[152]	valid_0's binary_logloss: 0.000636982
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[153]	valid_0's binary_logloss: 0.000624449
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[154]	valid_0's binary_logloss: 0.000610883
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[155]	valid_0's binary_logloss: 0.000598801
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[156]	valid_0's binary_logloss: 0.000593502
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[157]	valid_0's binary_logloss: 0.000592137
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[158]	valid_0's binary_logloss: 0.000585656
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[159]	valid_0's binary_logloss: 0.000590986
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[160]	valid_0's binary_logloss: 0.000587363
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[161]	valid_0's binary_logloss: 0.00059012
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[162]	valid_0's binary_logloss: 0.000581859
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[163]	valid_0's binary_logloss: 0.000574098
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[164]	valid_0's binary_logloss: 0.000576405
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[165]	valid_0's binary_logloss: 0.000578732
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[166]	valid_0's binary_logloss: 0.000570283
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[167]	valid_0's binary_logloss: 0.00056142
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[168]	valid_0's binary_logloss: 0.000551293
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[169]	valid_0's binary_logloss: 0.000542404
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[170]	valid_0's binary_logloss: 0.000533473
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[171]	valid_0's binary_logloss: 0.000525042
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[172]	valid_0's binary_logloss: 0.000515169
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[173]	valid_0's binary_logloss: 0.000503353
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[174]	valid_0's binary_logloss: 0.000494839
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[175]	valid_0's binary_logloss: 0.000484596
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[176]	valid_0's binary_logloss: 0.000478087
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[177]	valid_0's binary_logloss: 0.000477362
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[178]	valid_0's binary_logloss: 0.000477723
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[179]	valid_0's binary_logloss: 0.000475274
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[180]	valid_0's binary_logloss: 0.000474911
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[181]	valid_0's binary_logloss: 0.000471831
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[182]	valid_0's binary_logloss: 0.000466933
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

Trening klas:  71%|███████   | 353/500 [41:39<16:30,  6.74s/klasa, klasa=class_353, F1_klasy=0.9730, F1_macro=0.6740, drzewa=300]




Trening klas:  71%|███████   | 354/500 [41:39<15:21,  6.31s/klasa, klasa=class_353, F1_klasy=0.9730, F1_macro=0.6740, drzewa=300]

[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[294]	valid_0's binary_logloss: 0.000298909
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[295]	valid_0's binary_logloss: 0.000297145
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[296]	valid_0's binary_logloss: 0.000295956
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[297]	valid_0's binary_logloss: 0.000295281
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[298]	valid_0's binary_logloss: 0.000294272
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[299]	valid_0's binary_logloss: 0.000293488
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[300]	valid_0's binary_logloss: 0.000293166
[1]	valid_0's binary_logloss: 0.0357296
[2]	valid_0's binary_logloss: 0.0342718
[3]	valid_0's binary_logloss: 0.0331937
[4]	valid_0's binary_logloss: 0.0320843
[5]	valid_0's binary_logloss: 0.0310699
[6]	valid_0's binary_logloss: 0.0295836
[7]	valid_0's binary_logloss: 0.028145
[8]	valid_0's binary_logloss: 0.0273412
[9]	valid_0's binary_logloss: 0.026462
[10]	valid_0's binary_logloss: 0.0258343
[11]	valid_0's binary_logloss: 0.025225
[12]	valid_0's binary_logloss: 0.0246945
[13]	valid_0's binary_logloss: 0.0241624
[14]	valid_0's binary_logloss: 0.0236555
[15]	valid_0's binary_logloss: 0.0231942
[16]	valid_0's binary_logloss: 0.0228255
[17]	valid_0's binary_logloss: 0.0224663
[18]	valid_0's binary_logloss: 0.0221595
[19]	valid_0's binary_logloss: 0.0218783
[20]	valid_0's binary_logloss: 0.0215782
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0213947
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0212028
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.0209583
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.020846
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.0206893
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.0204279
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.0202846
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.0200746
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.0198378
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.0196478
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.0195252
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.0193484
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.0192219
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.0190999
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.0190109
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.0189599
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.0188157
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.0188185
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.0187348
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.0186688
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.0185135
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.0184835
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.0183893
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.0182323
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.0180192
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.0179155
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.0177474
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.017683
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.0176297
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.0176021
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.0174929
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.0174443
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.01738
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.0173129
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.0172413
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.0171997
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.0171095
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.0169564
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.0168215
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.0166986
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.0166312
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.0166194
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.0165892
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.0165731
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.0166603
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.016647
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.0166303
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.0165008
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.0165034
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.0164798
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.0164803
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.0165081
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.0165141
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.016502
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.0165197
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.0165298
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.0164224
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.0164283
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.0164764
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.0164525
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.016547
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.0165171
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.0165869
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.0166432
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.0166812
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.016733
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.0167751
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.0168595
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.01685
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.0168814
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.0169361
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.0169281
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.0169138
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.0169627
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.0169914
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.0169718
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.0169417
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.0169897
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.0169984
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.0170112
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.0170051
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.0170434
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.0170421
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.0171009
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.0170976
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.0171121

Trening klas:  71%|███████   | 354/500 [41:44<15:21,  6.31s/klasa, klasa=class_354, F1_klasy=0.5373, F1_macro=0.6736, drzewa=77]




Trening klas:  71%|███████   | 355/500 [41:44<14:09,  5.86s/klasa, klasa=class_354, F1_klasy=0.5373, F1_macro=0.6736, drzewa=77]

[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.017119
[1]	valid_0's binary_logloss: 0.0144349
[2]	valid_0's binary_logloss: 0.0135361
[3]	valid_0's binary_logloss: 0.0127243
[4]	valid_0's binary_logloss: 0.0120998
[5]	valid_0's binary_logloss: 0.011511
[6]	valid_0's binary_logloss: 0.0110092
[7]	valid_0's binary_logloss: 0.0104875
[8]	valid_0's binary_logloss: 0.0100439
[9]	valid_0's binary_logloss: 0.00965427
[10]	valid_0's binary_logloss: 0.00927435
[11]	valid_0's binary_logloss: 0.0089604
[12]	valid_0's binary_logloss: 0.00863152
[13]	valid_0's binary_logloss: 0.00835387
[14]	valid_0's binary_logloss: 0.00808604
[15]	valid_0's binary_logloss: 0.0078277
[16]	valid_0's binary_logloss: 0.00755594
[17]	valid_0's binary_logloss: 0.00730344
[18]	valid_0's binary_logloss: 0.00704802
[19]	valid_0's binary_logloss: 0.00680469
[20]	valid_0's binary_logloss: 0.00661094
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.00643018
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.00625485
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.00604133
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.00588696
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.00574862
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.00563442
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.00549399
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.00536043
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.00525012
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.00514704
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.00503586
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.0049316
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.00482259
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.00473072
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.0046362
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.00429555
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.00421288
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.0041845
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.00420783
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.00415919
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.004039
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.0039175
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.00386663
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.00381557
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.00372193
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.00371498
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.00368387
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.00365697
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.00365691
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.00364078
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.00363573
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.00361659
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.00358325
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.00355486
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.00351122
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.00350496
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.00348056
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.00347946
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.00342716
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.00338277
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.00335122
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.00335874
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.00333103
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.00328184
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.00325995
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.00327135
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.00328858
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.0032596
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.00327842
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.00330411
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.00331256
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.00332408
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.00335266
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.00336423
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.00337904
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.00341553
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.00344438
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.00347602
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.00350781
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.00354623
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.00358245
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.00358666
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.00363429
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.00363254
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.00362503
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.00366968
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.00371303
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.00370513
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.00374955
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.00377735
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.0038023
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

Trening klas:  71%|███████   | 355/500 [41:48<14:09,  5.86s/klasa, klasa=class_355, F1_klasy=0.7742, F1_macro=0.6739, drzewa=68]




Trening klas:  71%|███████   | 356/500 [41:48<12:27,  5.19s/klasa, klasa=class_355, F1_klasy=0.7742, F1_macro=0.6739, drzewa=68]

[92]	valid_0's binary_logloss: 0.0038319
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.0038715
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.00389614
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.00392129
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.00396853
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.004016
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.00406381
[1]	valid_0's binary_logloss: 0.0987233
[2]	valid_0's binary_logloss: 0.0541397
[3]	valid_0's binary_logloss: 0.0525389
[4]	valid_0's binary_logloss: 0.0516319
[5]	valid_0's binary_logloss: 0.0504757
[6]	valid_0's binary_logloss: 0.0629331
[7]	valid_0's binary_logloss: 0.0613667
[8]	valid_0's binary_logloss: 0.0601253
[9]	valid_0's binary_logloss: 0.0593197
[10]	valid_0's binary_logloss: 0.0581628
[11]	valid_0's binary_logloss: 0.057884
[12]	valid_0's binary_logloss: 0.0575243
[13]	valid_0's binary_logloss: 0.0571321
[14]	valid_0's binary_logloss: 0.056461
[15]	valid_0's binary_logloss: 0.0559652
[16]	valid_0's binary_logloss: 0.0551516
[17]	valid_0's binary_logloss: 0.054656
[18]	valid_0's binary_logloss: 0.05381
[19]	valid_0's binary_logloss: 0.0535478
[20]	valid_0's binary_logloss: 0.0528084
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.052558
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0523214
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.052103
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0518431
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.0514884
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.0513451
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.0512082
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.0509913
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.0507652
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.0504112
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.0499425
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.0497702
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.0495713
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.0494547
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.0490481
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.0487938
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.0486335
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.0484857
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.0482297
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.0479502
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.0479356
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.047764
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.0475304
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.047429
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.0472548
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.0471055
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.0468223
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.0465667
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.0464298
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.0462316
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.0459866
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.0457546
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.0455918
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.0454308
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.0452914
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.0451948
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.0451118
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.0449558
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.0448763
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.0446554
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.0445089
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.0443375
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.0441963
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.0440581
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.0439171
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.0438551
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.0438986
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.0438521
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.0439257
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.0439325
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.0437188
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.0435663
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.0433832
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.0432298
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.0431202
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.043074
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.0429989
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.0429574
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.0427923
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.042748
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.0426795
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.0427016
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.0426583
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.0425943
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.0425831
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.0425454
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.0425315
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.0424959
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.0424316
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.0424057
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.0422989
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.0422025
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.0421553
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.04212
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.0420347
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.0420236
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.0419929
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.0419349
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.0419131
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.041859
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.0419165
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.0419004
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.0417603
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.0416166
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.0415109
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.0414558
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.0414362
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.0414213
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.0413908
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.0413855
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.0412644
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 0.0410525
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 0.0410025
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 0.040994
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 0.0409403
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[116]	valid_0's binary_logloss: 0.0410104
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[117]	valid_0's binary_logloss: 0.0410133
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[118]	valid_0's binary_logloss: 0.0409762
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[119]	valid_0's binary_logloss: 0.0408851
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[120]	valid_0's binary_logloss: 0.0408201
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[121]	valid_0's binary_logloss: 0.0408379
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[122]	valid_0's binary_logloss: 0.0408678
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[123]	valid_0's binary_logloss: 0.0408398
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[124]	valid_0's binary_logloss: 0.0408759
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[125]	valid_0's binary_logloss: 0.0408437
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[126]	valid_0's binary_logloss: 0.0407247
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[127]	valid_0's binary_logloss: 0.0407015
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[128]	valid_0's binary_logloss: 0.0406618
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[129]	valid_0's binary_logloss: 0.040559
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[130]	valid_0's binary_logloss: 0.0405255
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[131]	valid_0's binary_logloss: 0.0404877
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[132]	valid_0's binary_logloss: 0.040469
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[133]	valid_0's binary_logloss: 0.040456
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[134]	valid_0's binary_logloss: 0.0404251
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[135]	valid_0's binary_logloss: 0.0403889
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[136]	valid_0's binary_logloss: 0.0403764
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[137]	valid_0's binary_logloss: 0.0403452
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[138]	valid_0's binary_logloss: 0.0403561
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[139]	valid_0's binary_logloss: 0.0403309
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[140]	valid_0's binary_logloss: 0.0402858
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[141]	valid_0's binary_logloss: 0.04018
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[142]	valid_0's binary_logloss: 0.0400771
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[143]	valid_0's binary_logloss: 0.0400082
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[144]	valid_0's binary_logloss: 0.0398588
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[145]	valid_0's binary_logloss: 0.0397488
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[146]	valid_0's binary_logloss: 0.0397318
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[147]	valid_0's binary_logloss: 0.0397454
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[148]	valid_0's binary_logloss: 0.0397432
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[149]	valid_0's binary_logloss: 0.0397649
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[150]	valid_0's binary_logloss: 0.0397536
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[151]	valid_0's binary_logloss: 0.0397732
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[152]	valid_0's binary_logloss: 0.0399868
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[153]	valid_0's binary_logloss: 0.040177
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[154]	valid_0's binary_logloss: 0.0402856
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[155]	valid_0's binary_logloss: 0.0402485
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[156]	valid_0's binary_logloss: 0.0402714
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[157]	valid_0's binary_logloss: 0.0402532
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[158]	valid_0's binary_logloss: 0.0401977
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[159]	valid_0's binary_logloss: 0.040172
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[160]	valid_0's binary_logloss: 0.0401396
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[161]	valid_0's binary_logloss: 0.0402195
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[162]	valid_0's binary_logloss: 0.0402276
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[163]	valid_0's binary_logloss: 0.0402382
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[164]	valid_0's binary_logloss: 0.0402521
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[165]	valid_0's binary_logloss: 0.0403368
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[166]	valid_0's binary_logloss: 0.0403497
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[167]	valid_0's binary_logloss: 0.0403
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[168]	valid_0's binary_logloss: 0.0402516
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[169]	valid_0's binary_logloss: 0.0402255
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[170]	valid_0's binary_logloss: 0.0401952
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[171]	valid_0's binary_logloss: 0.0401216
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[172]	valid_0's binary_logloss: 0.040046
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[173]	valid_0's binary_logloss: 0.0399471
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[174]	valid_0's binary_logloss: 0.0399344
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

Trening klas:  71%|███████   | 356/500 [41:54<12:27,  5.19s/klasa, klasa=class_356, F1_klasy=0.7860, F1_macro=0.6742, drzewa=146]




Trening klas:  71%|███████▏  | 357/500 [41:54<13:05,  5.49s/klasa, klasa=class_356, F1_klasy=0.7860, F1_macro=0.6742, drzewa=146]

[175]	valid_0's binary_logloss: 0.039842
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[176]	valid_0's binary_logloss: 0.0398468
[1]	valid_0's binary_logloss: 0.0191455
[2]	valid_0's binary_logloss: 0.0164803
[3]	valid_0's binary_logloss: 0.014829
[4]	valid_0's binary_logloss: 0.0136341
[5]	valid_0's binary_logloss: 0.0127177
[6]	valid_0's binary_logloss: 0.0118428
[7]	valid_0's binary_logloss: 0.0110966
[8]	valid_0's binary_logloss: 0.010445
[9]	valid_0's binary_logloss: 0.00986716
[10]	valid_0's binary_logloss: 0.00931897
[11]	valid_0's binary_logloss: 0.00981107
[12]	valid_0's binary_logloss: 0.00934214
[13]	valid_0's binary_logloss: 0.00889476
[14]	valid_0's binary_logloss: 0.00847867
[15]	valid_0's binary_logloss: 0.00810053
[16]	valid_0's binary_logloss: 0.00775263
[17]	valid_0's binary_logloss: 0.00744161
[18]	valid_0's binary_logloss: 0.0071336
[19]	valid_0's binary_logloss: 0.00685892
[20]	valid_0's binary_logloss: 0.00660168
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.00633892
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.00610538
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.00588776
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.00568273
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.00549604
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.00531208
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.00513841
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.0049493
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.00474203
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.00459941
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.00448757
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.00435938
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.00423188
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.00403926
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.00392395
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.00381211
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.00364865
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.00353563
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.00345095
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.0033718
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.00328839
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.00321782
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.0030784
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.00299852
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.00292351
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.00288355
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.00284871
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.00278431
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.00274062
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.00268738
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.00265217
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.00261982
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.00254489
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.00249054
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.00224438
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.0022196
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.0021951
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.00214854
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.00212311
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.00210668
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.00195069
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.00183156
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.00173657
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.00165999
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.00159661
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.00158454
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.00156767
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.0015725
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.00156736
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.00153979
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.00148678
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.00143188
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.00139762
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.00137592
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.00133695
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.00133843
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.00133731
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.00133718
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.00133919
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.00134087
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.0013317
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.00133379
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.00134529
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.00135077
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.00134936
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.0012518
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.00123781
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.00117798
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.00113238
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.00107833
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.00106138
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.001033
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.00100297
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.000994692
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.000978738
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.000976595
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.000973618
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.000968612
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.000953119
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.000958882
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.000966243
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.000958372
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.000960863
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.000959094
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.000958281
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.000952221
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.000956879
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.000949485
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.000939339
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.000923495
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.000914337
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 0.000912975
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 0.000902112
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 0.000898734
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 0.00090398
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[116]	valid_0's binary_logloss: 0.000909542
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[117]	valid_0's binary_logloss: 0.000915075
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[118]	valid_0's binary_logloss: 0.000921408
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[119]	valid_0's binary_logloss: 0.000911453
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[120]	valid_0's binary_logloss: 0.000913611
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[121]	valid_0's binary_logloss: 0.000886794
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[122]	valid_0's binary_logloss: 0.000886219
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[123]	valid_0's binary_logloss: 0.000894154
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[124]	valid_0's binary_logloss: 0.000901784
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[125]	valid_0's binary_logloss: 0.000910128
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[126]	valid_0's binary_logloss: 0.00091657
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[127]	valid_0's binary_logloss: 0.000918302
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[128]	valid_0's binary_logloss: 0.000920423
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[129]	valid_0's binary_logloss: 0.000926495
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[130]	valid_0's binary_logloss: 0.000923709
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[131]	valid_0's binary_logloss: 0.000921676
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[132]	valid_0's binary_logloss: 0.00092048
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[133]	valid_0's binary_logloss: 0.000919922
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[134]	valid_0's binary_logloss: 0.000910526
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[135]	valid_0's binary_logloss: 0.000921234
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[136]	valid_0's binary_logloss: 0.000923138
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[137]	valid_0's binary_logloss: 0.000926469
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[138]	valid_0's binary_logloss: 0.0009384
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[139]	valid_0's binary_logloss: 0.000941779
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[140]	valid_0's binary_logloss: 0.000945013
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[141]	valid_0's binary_logloss: 0.00093035
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[142]	valid_0's binary_logloss: 0.000927907
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[143]	valid_0's binary_logloss: 0.000922276
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[144]	valid_0's binary_logloss: 0.000924277
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[145]	valid_0's binary_logloss: 0.000920862
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[146]	valid_0's binary_logloss: 0.000928508
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[147]	valid_0's binary_logloss: 0.000932386
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

Trening klas:  71%|███████▏  | 357/500 [42:00<13:05,  5.49s/klasa, klasa=class_357, F1_klasy=0.8889, F1_macro=0.6748, drzewa=122]




Trening klas:  72%|███████▏  | 358/500 [42:00<13:15,  5.60s/klasa, klasa=class_357, F1_klasy=0.8889, F1_macro=0.6748, drzewa=122]

[148]	valid_0's binary_logloss: 0.00092948
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[149]	valid_0's binary_logloss: 0.000938307
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[150]	valid_0's binary_logloss: 0.000941996
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[151]	valid_0's binary_logloss: 0.000950223
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[152]	valid_0's binary_logloss: 0.000948351
[1]	valid_0's binary_logloss: 0.0998011
[2]	valid_0's binary_logloss: 0.0791917
[3]	valid_0's binary_logloss: 0.0682733
[4]	valid_0's binary_logloss: 0.0614045
[5]	valid_0's binary_logloss: 0.057716
[6]	valid_0's binary_logloss: 0.0540324
[7]	valid_0's binary_logloss: 0.0506775
[8]	valid_0's binary_logloss: 0.0479074
[9]	valid_0's binary_logloss: 0.0452942
[10]	valid_0's binary_logloss: 0.043568
[11]	valid_0's binary_logloss: 0.0418605
[12]	valid_0's binary_logloss: 0.0402378
[13]	valid_0's binary_logloss: 0.0388034
[14]	valid_0's binary_logloss: 0.037272
[15]	valid_0's binary_logloss: 0.0362415
[16]	valid_0's binary_logloss: 0.0349854
[17]	valid_0's binary_logloss: 0.0338972
[18]	valid_0's binary_logloss: 0.0328477
[19]	valid_0's binary_logloss: 0.0319549
[20]	valid_0's binary_logloss: 0.0309928
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0301169
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0294808
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.0286536
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.027884
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.0271776
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.0265458
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.026104
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.0256185
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.0249237
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.0243778
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.0237858
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.0233179
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.0227359
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.0222394
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.0217686
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.0213816
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.0210358
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.0206964
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.0204147
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.020122
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.019822
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.0195589
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.0192922
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.0190463
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.018799
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.0185459
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.0183522
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.0181792
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.0180085
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.0178267
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.0176636
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.0175066
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.0173894
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.0172985
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.0171881
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.0170414
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.0168501
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.0166812
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.0165332
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.0163888
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.0162613
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.0161205
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.0160333
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.0159703
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.0159195
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.0157634
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.0156687
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.0155984
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.0154927
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.0153888
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.0152481
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.0151191
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.0150026
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.0148952
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.0148356
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.0148146
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.0147809
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.0147235
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.0146869
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.0146422
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.014626
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.0146218
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.0146091
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.0146183
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.0146388
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.0146156
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.0146002
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.0145912
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.0145567
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.0145655
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.0144657
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.0144653
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.014456
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.0143744
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.0142956
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.0142322
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.014159
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.0141172
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.0140825
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.014035
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.0140306
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.014045
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.0141022
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.0140719
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.0140478
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.0140348
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.0140393
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.0140396
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.0140476
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.0141002
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.0141112
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 0.014126
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 0.0141296
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 0.014167
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 0.0141713
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[116]	valid_0's binary_logloss: 0.0141117
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[117]	valid_0's binary_logloss: 0.0140433
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[118]	valid_0's binary_logloss: 0.0139931
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[119]	valid_0's binary_logloss: 0.0139572
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[120]	valid_0's binary_logloss: 0.0138946
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[121]	valid_0's binary_logloss: 0.013915
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[122]	valid_0's binary_logloss: 0.0139352
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[123]	valid_0's binary_logloss: 0.0139139
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[124]	valid_0's binary_logloss: 0.0138986
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[125]	valid_0's binary_logloss: 0.0138709
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[126]	valid_0's binary_logloss: 0.0138446
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[127]	valid_0's binary_logloss: 0.0138377
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[128]	valid_0's binary_logloss: 0.0138114
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[129]	valid_0's binary_logloss: 0.01383
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[130]	valid_0's binary_logloss: 0.013829
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[131]	valid_0's binary_logloss: 0.0138541
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[132]	valid_0's binary_logloss: 0.0138856
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[133]	valid_0's binary_logloss: 0.0139018
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[134]	valid_0's binary_logloss: 0.01389
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[135]	valid_0's binary_logloss: 0.0138652
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[136]	valid_0's binary_logloss: 0.013825
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[137]	valid_0's binary_logloss: 0.0137907
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[138]	valid_0's binary_logloss: 0.0137583
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[139]	valid_0's binary_logloss: 0.0137169
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[140]	valid_0's binary_logloss: 0.0136954
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[141]	valid_0's binary_logloss: 0.0137057
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[142]	valid_0's binary_logloss: 0.0136746
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[143]	valid_0's binary_logloss: 0.0136697
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[144]	valid_0's binary_logloss: 0.0136602
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[145]	valid_0's binary_logloss: 0.0136572
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[146]	valid_0's binary_logloss: 0.0136826
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[147]	valid_0's binary_logloss: 0.0137048
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[148]	valid_0's binary_logloss: 0.0137199
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[149]	valid_0's binary_logloss: 0.0137405
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[150]	valid_0's binary_logloss: 0.0137805
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[151]	valid_0's binary_logloss: 0.0137306
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[152]	valid_0's binary_logloss: 0.0136716
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[153]	valid_0's binary_logloss: 0.013628
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[154]	valid_0's binary_logloss: 0.0135731
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[155]	valid_0's binary_logloss: 0.0135541
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[156]	valid_0's binary_logloss: 0.0135841
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[157]	valid_0's binary_logloss: 0.0136231
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[158]	valid_0's binary_logloss: 0.0136523
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[159]	valid_0's binary_logloss: 0.0136532
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[160]	valid_0's binary_logloss: 0.0136767
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[161]	valid_0's binary_logloss: 0.0136806
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[162]	valid_0's binary_logloss: 0.0136635
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[163]	valid_0's binary_logloss: 0.0136307
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[164]	valid_0's binary_logloss: 0.0136178
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[165]	valid_0's binary_logloss: 0.0135758
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[166]	valid_0's binary_logloss: 0.0136069
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[167]	valid_0's binary_logloss: 0.0136405
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[168]	valid_0's binary_logloss: 0.0136466
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[169]	valid_0's binary_logloss: 0.0136726
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[170]	valid_0's binary_logloss: 0.0136743
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[171]	valid_0's binary_logloss: 0.0136453
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[172]	valid_0's binary_logloss: 0.013658
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[173]	valid_0's binary_logloss: 0.0136456
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[174]	valid_0's binary_logloss: 0.0136195
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[175]	valid_0's binary_logloss: 0.013632
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[176]	valid_0's binary_logloss: 0.0136469
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[177]	valid_0's binary_logloss: 0.0136589
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[178]	valid_0's binary_logloss: 0.013669
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[179]	valid_0's binary_logloss: 0.0136867
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[180]	valid_0's binary_logloss: 0.0136618

Trening klas:  72%|███████▏  | 358/500 [42:06<13:15,  5.60s/klasa, klasa=class_358, F1_klasy=0.5806, F1_macro=0.6745, drzewa=155]




Trening klas:  72%|███████▏  | 359/500 [42:06<13:16,  5.65s/klasa, klasa=class_358, F1_klasy=0.5806, F1_macro=0.6745, drzewa=155]

[185]	valid_0's binary_logloss: 0.0137185
[1]	valid_0's binary_logloss: 0.444466
[2]	valid_0's binary_logloss: 0.261282
[3]	valid_0's binary_logloss: 0.638798
[4]	valid_0's binary_logloss: 0.715818
[5]	valid_0's binary_logloss: 0.725501
[6]	valid_0's binary_logloss: 0.964073
[7]	valid_0's binary_logloss: 0.966554
[8]	valid_0's binary_logloss: 0.969596
[9]	valid_0's binary_logloss: 0.972949
[10]	valid_0's binary_logloss: 0.976801
[11]	valid_0's binary_logloss: 0.978151
[12]	valid_0's binary_logloss: 0.98193
[13]	valid_0's binary_logloss: 0.982746
[14]	valid_0's binary_logloss: 0.983563
[15]	valid_0's binary_logloss: 0.985649
[16]	valid_0's binary_logloss: 0.987422
[17]	valid_0's binary_logloss: 0.987335
[18]	valid_0's binary_logloss: 0.984788
[19]	valid_0's binary_logloss: 0.983035
[20]	valid_0's binary_logloss: 0.985626
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.988434
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.988223
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.991029
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.993217
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.991674
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 1.08985
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

Trening klas:  72%|███████▏  | 359/500 [42:08<13:16,  5.65s/klasa, klasa=class_359, F1_klasy=0.2118, F1_macro=0.6732, drzewa=2]




Trening klas:  72%|███████▏  | 360/500 [42:08<10:55,  4.68s/klasa, klasa=class_359, F1_klasy=0.2118, F1_macro=0.6732, drzewa=2]

[27]	valid_0's binary_logloss: 1.09044
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 1.09219
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 1.09253
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 1.09313
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 1.09297
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 1.09694
[1]	valid_0's binary_logloss: 0.0272802
[2]	valid_0's binary_logloss: 0.0240697
[3]	valid_0's binary_logloss: 0.02248
[4]	valid_0's binary_logloss: 0.0212872
[5]	valid_0's binary_logloss: 0.020253
[6]	valid_0's binary_logloss: 0.0193693
[7]	valid_0's binary_logloss: 0.0186284
[8]	valid_0's binary_logloss: 0.0180404
[9]	valid_0's binary_logloss: 0.017537
[10]	valid_0's binary_logloss: 0.0170861
[11]	valid_0's binary_logloss: 0.0165497
[12]	valid_0's binary_logloss: 0.0161605
[13]	valid_0's binary_logloss: 0.0155971
[14]	valid_0's binary_logloss: 0.015194
[15]	valid_0's binary_logloss: 0.0145725
[16]	valid_0's binary_logloss: 0.0143213
[17]	valid_0's binary_logloss: 0.0140703
[18]	valid_0's binary_logloss: 0.0138471
[19]	valid_0's binary_logloss: 0.013636
[20]	valid_0's binary_logloss: 0.0134525
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0132847
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0131154
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.0129593
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0128254
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.0126971
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.0124981
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.0121847
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.0119601
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.0115949
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.011517
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.0114454
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.0113814
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.011331
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.011283
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.011164
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.0109573
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.0107715
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.0106276
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.0105907
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.010445
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.0104403
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.0103835
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.0103808
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.0103691
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.0103302
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.010268
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.0102537
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.0101869
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.0101139
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.0100647
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.00998959
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.00991118
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.00983943
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.00976809
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.00963909
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.00964958
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.00965459
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.00960294
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.00961467
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.00958033
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.00958
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.00950058
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.00944039
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.00937709
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.0093162
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.00931226
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.00923174
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.00916476
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.00909954
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.00902844
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.00900328
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.00898773
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.00896368
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.00894342
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.0089246
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.00895716
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.00898107
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.00901486
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.00903521
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.00906518
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.00908023
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.00906783
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.00908687
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.00910457
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.00912873
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.00910949
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.00918871
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.00927628
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.00925783
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.00924502
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.00922646
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.00922117
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.00925014
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.00921317
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.0092
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.00919966
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.00923005
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.00928369
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.00935751
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.00939883
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.00940939
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.00949577
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.00951617
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.00950166
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

Trening klas:  72%|███████▏  | 360/500 [42:12<10:55,  4.68s/klasa, klasa=class_360, F1_klasy=0.7143, F1_macro=0.6734, drzewa=75]




Trening klas:  72%|███████▏  | 361/500 [42:12<10:15,  4.43s/klasa, klasa=class_360, F1_klasy=0.7143, F1_macro=0.6734, drzewa=75]

[105]	valid_0's binary_logloss: 0.00949103
[1]	valid_0's binary_logloss: 1.11148
[2]	valid_0's binary_logloss: 0.874464
[3]	valid_0's binary_logloss: 1.05894
[4]	valid_0's binary_logloss: 1.02892
[5]	valid_0's binary_logloss: 0.99158
[6]	valid_0's binary_logloss: 0.969275
[7]	valid_0's binary_logloss: 0.949807
[8]	valid_0's binary_logloss: 0.940528
[9]	valid_0's binary_logloss: 0.929507
[10]	valid_0's binary_logloss: 0.91959
[11]	valid_0's binary_logloss: 0.898683
[12]	valid_0's binary_logloss: 0.892063
[13]	valid_0's binary_logloss: 0.883605
[14]	valid_0's binary_logloss: 0.876042
[15]	valid_0's binary_logloss: 0.865997
[16]	valid_0's binary_logloss: 0.859768
[17]	valid_0's binary_logloss: 0.852436
[18]	valid_0's binary_logloss: 0.847396
[19]	valid_0's binary_logloss: 0.843583
[20]	valid_0's binary_logloss: 0.843572
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.839184
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.832421
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.8277
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.823825
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.818488
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.818892
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.813956
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.809232
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.810179
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.804609
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 1.25667
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 1.25075
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 1.24691
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 1.24788
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 1.24103
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 1.22249
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 1.20148
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 1.18478
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 1.30202
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 1.28206
[41]	valid_0's binary_logloss: 1.2723
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 1.26133
[43]	valid_0's binary_logloss: 1.25677
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 1.24349
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 1.23994
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 1.22426
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 1.21558
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 1.20285
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 1.18723
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 1.1734
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 1.16083
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 1.1473
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 1.14134
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 1.13269
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 1.12655
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 1.16387
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 1.16123
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 1.15651
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 1.1537
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

Trening klas:  72%|███████▏  | 361/500 [42:16<10:15,  4.43s/klasa, klasa=class_361, F1_klasy=0.2934, F1_macro=0.6723, drzewa=30]




Trening klas:  72%|███████▏  | 362/500 [42:16<09:49,  4.27s/klasa, klasa=class_361, F1_klasy=0.2934, F1_macro=0.6723, drzewa=30]

[60]	valid_0's binary_logloss: 1.14476
[1]	valid_0's binary_logloss: 0.450041
[2]	valid_0's binary_logloss: 0.201265
[3]	valid_0's binary_logloss: 0.220255
[4]	valid_0's binary_logloss: 0.219103
[5]	valid_0's binary_logloss: 0.218636
[6]	valid_0's binary_logloss: 0.263272
[7]	valid_0's binary_logloss: 0.258389
[8]	valid_0's binary_logloss: 0.257861
[9]	valid_0's binary_logloss: 0.25738
[10]	valid_0's binary_logloss: 0.256183
[11]	valid_0's binary_logloss: 0.250382
[12]	valid_0's binary_logloss: 0.243402
[13]	valid_0's binary_logloss: 0.241405
[14]	valid_0's binary_logloss: 0.239716
[15]	valid_0's binary_logloss: 0.238092
[16]	valid_0's binary_logloss: 0.237422
[17]	valid_0's binary_logloss: 0.236583
[18]	valid_0's binary_logloss: 0.236107
[19]	valid_0's binary_logloss: 0.235817
[20]	valid_0's binary_logloss: 0.235518
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.235215
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.234832
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.234642
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.234534
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.234361
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.234091
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.233814
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.233629
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.233501
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.233314
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.233013
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.23256

Trening klas:  72%|███████▏  | 362/500 [42:18<09:49,  4.27s/klasa, klasa=class_362, F1_klasy=0.4854, F1_macro=0.6718, drzewa=2]




Trening klas:  73%|███████▎  | 363/500 [42:18<08:22,  3.67s/klasa, klasa=class_362, F1_klasy=0.4854, F1_macro=0.6718, drzewa=2]

[1]	valid_0's binary_logloss: 0.462019
[2]	valid_0's binary_logloss: 0.277082
[3]	valid_0's binary_logloss: 0.261962
[4]	valid_0's binary_logloss: 0.250298
[5]	valid_0's binary_logloss: 0.240153
[6]	valid_0's binary_logloss: 0.229102
[7]	valid_0's binary_logloss: 0.219016
[8]	valid_0's binary_logloss: 0.210977
[9]	valid_0's binary_logloss: 0.20335
[10]	valid_0's binary_logloss: 0.197375
[11]	valid_0's binary_logloss: 0.191341
[12]	valid_0's binary_logloss: 0.186141
[13]	valid_0's binary_logloss: 0.180823
[14]	valid_0's binary_logloss: 0.176318
[15]	valid_0's binary_logloss: 0.172198
[16]	valid_0's binary_logloss: 0.168124
[17]	valid_0's binary_logloss: 0.16392
[18]	valid_0's binary_logloss: 0.16019
[19]	valid_0's binary_logloss: 0.15695
[20]	valid_0's binary_logloss: 0.153558
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.149889
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.14682
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.144282
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.14171
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.1396
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.137
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.134266
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.131652
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.12922
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.12694
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.125023
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.123259
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.121339
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.119631
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.117713
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.115652
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.113841
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.112071
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.110489
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.108891
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.10753
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.106377
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.105184
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.103668
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.101682
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.10017
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.0986637
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.0973555
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.095984
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.0947993
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.0937312
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.0930309
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.0917047
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.090898
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.0901736
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.0891735
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.0882134
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.0867813
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.0852628
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.0843218
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.0836096
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.0829835
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.0822302
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.0815526
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.0809291
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.0800416
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.079349
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.0785669
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.0778362
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.077155
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.0763786
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.0757642
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.0752549
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.0749032
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.0743634
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.0740696
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.0735261
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.073263
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.0720585
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.071587
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.0713945
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.0710479
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.0707641
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.0703368
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.0701863
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.0698448
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.068899
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.0683971
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.0679721
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.0677989
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.0674387
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.0670682
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.0667927
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.0664784
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.0663248
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.066404
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.066276
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.0661342
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.0658926
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.0657267
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.0656295
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.0654216
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.0652971
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.0651839
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.0649873
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.065001
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.0648761
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.0648744
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.0647776
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.0647566
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.0643664
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 0.0640134
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 0.0637385
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 0.0636615
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 0.0635479
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[116]	valid_0's binary_logloss: 0.0631542
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[117]	valid_0's binary_logloss: 0.0628515
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[118]	valid_0's binary_logloss: 0.0626801
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[119]	valid_0's binary_logloss: 0.0624781
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[120]	valid_0's binary_logloss: 0.0622337
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[121]	valid_0's binary_logloss: 0.0619007
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[122]	valid_0's binary_logloss: 0.0615641
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[123]	valid_0's binary_logloss: 0.0612472
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[124]	valid_0's binary_logloss: 0.0609415
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[125]	valid_0's binary_logloss: 0.0607168
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[126]	valid_0's binary_logloss: 0.060674
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[127]	valid_0's binary_logloss: 0.0604478
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[128]	valid_0's binary_logloss: 0.0604359
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[129]	valid_0's binary_logloss: 0.0604464
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[130]	valid_0's binary_logloss: 0.0604564
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[131]	valid_0's binary_logloss: 0.0604095
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[132]	valid_0's binary_logloss: 0.0602668
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[133]	valid_0's binary_logloss: 0.0601537
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[134]	valid_0's binary_logloss: 0.0599727
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[135]	valid_0's binary_logloss: 0.0599314
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[136]	valid_0's binary_logloss: 0.0598531
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[137]	valid_0's binary_logloss: 0.0599123
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[138]	valid_0's binary_logloss: 0.0598746
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[139]	valid_0's binary_logloss: 0.059869
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[140]	valid_0's binary_logloss: 0.0597791
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[141]	valid_0's binary_logloss: 0.0596973
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[142]	valid_0's binary_logloss: 0.0598521
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[143]	valid_0's binary_logloss: 0.0598426
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[144]	valid_0's binary_logloss: 0.0599223
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[145]	valid_0's binary_logloss: 0.0599488
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[146]	valid_0's binary_logloss: 0.059901
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[147]	valid_0's binary_logloss: 0.0600163
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[148]	valid_0's binary_logloss: 0.0600724
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[149]	valid_0's binary_logloss: 0.0600806
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[150]	valid_0's binary_logloss: 0.0601285
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[151]	valid_0's binary_logloss: 0.0601133
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[152]	valid_0's binary_logloss: 0.0600735
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[153]	valid_0's binary_logloss: 0.0600756
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[154]	valid_0's binary_logloss: 0.0602067
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[155]	valid_0's binary_logloss: 0.0602769
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[156]	valid_0's binary_logloss: 0.0602374
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[157]	valid_0's binary_logloss: 0.0603368
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[158]	valid_0's binary_logloss: 0.0604421
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[159]	valid_0's binary_logloss: 0.0605005
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[160]	valid_0's binary_logloss: 0.0606122
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[161]	valid_0's binary_logloss: 0.0605087
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[162]	valid_0's binary_logloss: 0.0605749
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[163]	valid_0's binary_logloss: 0.0607076
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[164]	valid_0's binary_logloss: 0.0606566
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[165]	valid_0's binary_logloss: 0.0606657
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[166]	valid_0's binary_logloss: 0.060721
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[167]	valid_0's binary_logloss: 0.0607604
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[168]	valid_0's binary_logloss: 0.0607835
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[169]	valid_0's binary_logloss: 0.0606993
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[170]	valid_0's binary_logloss: 0.0607
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[171]	valid_0's binary_logloss: 0.0607371

Trening klas:  73%|███████▎  | 363/500 [42:25<08:22,  3.67s/klasa, klasa=class_363, F1_klasy=0.5153, F1_macro=0.6714, drzewa=141]




Trening klas:  73%|███████▎  | 364/500 [42:25<10:40,  4.71s/klasa, klasa=class_363, F1_klasy=0.5153, F1_macro=0.6714, drzewa=141]

[1]	valid_0's binary_logloss: 0.148386
[2]	valid_0's binary_logloss: 0.138377
[3]	valid_0's binary_logloss: 0.299315
[4]	valid_0's binary_logloss: 0.296386
[5]	valid_0's binary_logloss: 0.294237
[6]	valid_0's binary_logloss: 0.655927
[7]	valid_0's binary_logloss: 0.617996
[8]	valid_0's binary_logloss: 0.567909
[9]	valid_0's binary_logloss: 0.52581
[10]	valid_0's binary_logloss: 0.521885
[11]	valid_0's binary_logloss: 0.521223
[12]	valid_0's binary_logloss: 0.514595
[13]	valid_0's binary_logloss: 0.513062
[14]	valid_0's binary_logloss: 0.509036
[15]	valid_0's binary_logloss: 0.507272
[16]	valid_0's binary_logloss: 0.504917
[17]	valid_0's binary_logloss: 0.484907
[18]	valid_0's binary_logloss: 0.482145
[19]	valid_0's binary_logloss: 0.479576
[20]	valid_0's binary_logloss: 0.477709
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.470783
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.466762
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.463721
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.459911
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.457301
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.454716
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.45179
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.448483
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

Trening klas:  73%|███████▎  | 364/500 [42:28<10:40,  4.71s/klasa, klasa=class_364, F1_klasy=0.3488, F1_macro=0.6705, drzewa=2]




Trening klas:  73%|███████▎  | 365/500 [42:28<09:39,  4.29s/klasa, klasa=class_364, F1_klasy=0.3488, F1_macro=0.6705, drzewa=2]

[29]	valid_0's binary_logloss: 0.44483
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.443174
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.439819
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.436443
[1]	valid_0's binary_logloss: 0.00932989
[2]	valid_0's binary_logloss: 0.00884637
[3]	valid_0's binary_logloss: 0.00838058
[4]	valid_0's binary_logloss: 0.00794156
[5]	valid_0's binary_logloss: 0.00751493
[6]	valid_0's binary_logloss: 0.00711085
[7]	valid_0's binary_logloss: 0.00673309
[8]	valid_0's binary_logloss: 0.00640171
[9]	valid_0's binary_logloss: 0.00607766
[10]	valid_0's binary_logloss: 0.00579076
[11]	valid_0's binary_logloss: 0.00550011
[12]	valid_0's binary_logloss: 0.00521033
[13]	valid_0's binary_logloss: 0.00495632
[14]	valid_0's binary_logloss: 0.00473014
[15]	valid_0's binary_logloss: 0.00450129
[16]	valid_0's binary_logloss: 0.0043098
[17]	valid_0's binary_logloss: 0.00411677
[18]	valid_0's binary_logloss: 0.00391468
[19]	valid_0's binary_logloss: 0.00372669
[20]	valid_0's binary_logloss: 0.00354809
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.00337158
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.00320975
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.00305149
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.00290209
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.00276427
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.00262809
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.00250147
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.00238456
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.00226689
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.00215183
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.0020495
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.00194941
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.0018536
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.00175958
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.00167022
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.00159468
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.0015152
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.00144382
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.00137936
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.00131026
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.0012468
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.00119464
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.00113795
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.00109102
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.00103798
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.000987561
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.000941141
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.000897126
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.00085565
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.000818398
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.000780465
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.000743491
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.000712138
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.000682647
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.000654665
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.000626929
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.000601685
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.000576602
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.000552821
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.000532474
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.00051092
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.000486183
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.000468127
[64]	valid_0's binary_logloss: 0.000451473
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.000434165
[66]	valid_0's binary_logloss: 0.000412468
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.000407274
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.00039506
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.000378223
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.000360867
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.000351498
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.000347559
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.000343833
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.00033737
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.000335962
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.00033329
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.000318937
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.000305424
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.000295583
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.000285952
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.000278561
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.0002797
[83]	valid_0's binary_logloss: 0.000272861
[84]	valid_0's binary_logloss: 0.00026655
[85]	valid_0's binary_logloss: 0.000261911
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.000252857
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.000242975
[88]	valid_0's binary_logloss: 0.00024501
[89]	valid_0's binary_logloss: 0.00023723
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.000229093
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.0002289
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.000234249
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.00022502
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.000216893
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.000222616
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.000223166
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.000227102
[98]	valid_0's binary_logloss: 0.0002299
[99]	valid_0's binary_logloss: 0.000232087
[100]	valid_0's binary_logloss: 0.000234589
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.000233427
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.000230683
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.000232686
[104]	valid_0's binary_logloss: 0.000235316
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.00023067
[106]	valid_0's binary_logloss: 0.000225524
[107]	valid_0's binary_logloss: 0.000234668
[108]	valid_0's binary_logloss: 0.000232632
[109]	valid_0's binary_logloss: 0.000236006
[110]	valid_0's binary_logloss: 0.000229782
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.000224457
[112]	valid_0's binary_logloss: 0.000228233
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 0.000233354
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 0.000235996
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 0.000240209
[116]	valid_0's binary_logloss: 0.000244584
[117]	valid_0's binary_logloss: 0.000248763
[118]	valid_0's binary_logloss: 0.000242546
[119]	valid_0's binary_logloss: 0.0002359
[120]	valid_0's binary_logloss: 0.000230638
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[121]	valid_0's binary_logloss: 0.000227279
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[122]	valid_0's binary_logloss: 0.000233717
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[123]	valid_0's binary_logloss: 0.00023026
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

Trening klas:  73%|███████▎  | 365/500 [42:34<09:39,  4.29s/klasa, klasa=class_365, F1_klasy=0.6667, F1_macro=0.6705, drzewa=94]




Trening klas:  73%|███████▎  | 366/500 [42:34<10:11,  4.57s/klasa, klasa=class_365, F1_klasy=0.6667, F1_macro=0.6705, drzewa=94]

[124]	valid_0's binary_logloss: 0.000250047
[1]	valid_0's binary_logloss: 0.0086152
[2]	valid_0's binary_logloss: 0.00780745
[3]	valid_0's binary_logloss: 0.00730798
[4]	valid_0's binary_logloss: 0.00683312
[5]	valid_0's binary_logloss: 0.00641735
[6]	valid_0's binary_logloss: 0.00604233
[7]	valid_0's binary_logloss: 0.00570018
[8]	valid_0's binary_logloss: 0.00538491
[9]	valid_0's binary_logloss: 0.00509244
[10]	valid_0's binary_logloss: 0.00481982
[11]	valid_0's binary_logloss: 0.00456635
[12]	valid_0's binary_logloss: 0.00432526
[13]	valid_0's binary_logloss: 0.00410168
[14]	valid_0's binary_logloss: 0.00389101
[15]	valid_0's binary_logloss: 0.0036889
[16]	valid_0's binary_logloss: 0.00349806
[17]	valid_0's binary_logloss: 0.0033181
[18]	valid_0's binary_logloss: 0.00315061
[19]	valid_0's binary_logloss: 0.00298954
[20]	valid_0's binary_logloss: 0.00283421
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0026903
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0025542
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.0024254
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.00230347
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.00218966
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.00208131
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.00197851
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.00188096
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.00178828
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.00169889
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.00161436
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.00154008
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.00147148
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.00139868
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.00132954
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.00126353
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.0012078
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.00114799
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.0010918
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.00103593
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.000984618
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.000935937
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.000887854
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.000842311
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.00079917
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.000758394
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.000719391
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.000684772
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.000651569
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.000618435
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.000586711
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.000565737
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.000545743
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.000517609
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.000490987
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.000465623
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.000441634
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.000418942
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.000404767
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.000388812
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.00036882
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.000349903
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.000332
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.000315057
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.000298703
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.000283349
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.000273808
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.000259707
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.000246378
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.000236326
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.000227749
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.000220218
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.000208994
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.000201728
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.00019147
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.000181326
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.000171769
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.00016276
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.000154267
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.000149524
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.000144533
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.000137051
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.000132654
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.000128708
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.00012399
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.000119576
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.000114041
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.000110308
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.000106885
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.000103811
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 9.8883e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 9.3847e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 9.0112e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 8.55703e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 8.21041e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 7.78399e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 7.41131e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 7.05899e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 6.74801e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 6.46687e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 6.1712e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 5.98754e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 5.71983e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 5.46883e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 5.24405e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 5.04239e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 4.85073e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 4.64312e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 4.43709e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 4.36295e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 4.27111e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 4.08752e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 3.93946e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 3.72929e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 3.58107e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[116]	valid_0's binary_logloss: 3.46771e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[117]	valid_0's binary_logloss: 3.39004e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[118]	valid_0's binary_logloss: 3.33161e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[119]	valid_0's binary_logloss: 3.25427e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[120]	valid_0's binary_logloss: 3.15448e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[121]	valid_0's binary_logloss: 3.0221e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[122]	valid_0's binary_logloss: 2.89067e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[123]	valid_0's binary_logloss: 2.79098e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[124]	valid_0's binary_logloss: 2.67481e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[125]	valid_0's binary_logloss: 2.56825e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[126]	valid_0's binary_logloss: 2.44721e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[127]	valid_0's binary_logloss: 2.33272e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[128]	valid_0's binary_logloss: 2.23401e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[129]	valid_0's binary_logloss: 2.12822e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[130]	valid_0's binary_logloss: 2.03273e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[131]	valid_0's binary_logloss: 2.02159e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[132]	valid_0's binary_logloss: 1.96827e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[133]	valid_0's binary_logloss: 1.94176e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[134]	valid_0's binary_logloss: 1.86691e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[135]	valid_0's binary_logloss: 1.809e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[136]	valid_0's binary_logloss: 1.79988e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[137]	valid_0's binary_logloss: 1.79425e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[138]	valid_0's binary_logloss: 1.79072e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[139]	valid_0's binary_logloss: 1.77047e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[140]	valid_0's binary_logloss: 1.74646e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[141]	valid_0's binary_logloss: 1.67385e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[142]	valid_0's binary_logloss: 1.63429e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[143]	valid_0's binary_logloss: 1.56623e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[144]	valid_0's binary_logloss: 1.50406e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[145]	valid_0's binary_logloss: 1.44716e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[146]	valid_0's binary_logloss: 1.38877e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[147]	valid_0's binary_logloss: 1.36972e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[148]	valid_0's binary_logloss: 1.35735e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[149]	valid_0's binary_logloss: 1.34495e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[150]	valid_0's binary_logloss: 1.33926e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[151]	valid_0's binary_logloss: 1.28389e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[152]	valid_0's binary_logloss: 1.23483e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[153]	valid_0's binary_logloss: 1.20043e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[154]	valid_0's binary_logloss: 1.15216e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[155]	valid_0's binary_logloss: 1.10645e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[156]	valid_0's binary_logloss: 1.06602e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[157]	valid_0's binary_logloss: 1.03249e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[158]	valid_0's binary_logloss: 1.00971e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[159]	valid_0's binary_logloss: 9.708e-06
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[160]	valid_0's binary_logloss: 9.38199e-06
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[161]	valid_0's binary_logloss: 9.10878e-06
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[162]	valid_0's binary_logloss: 9.18802e-06
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[163]	valid_0's binary_logloss: 8.91556e-06
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[164]	valid_0's binary_logloss: 8.67632e-06
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[165]	valid_0's binary_logloss: 8.58061e-06
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[166]	valid_0's binary_logloss: 8.43278e-06
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[167]	valid_0's binary_logloss: 8.48662e-06
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[168]	valid_0's binary_logloss: 8.21768e-06
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[169]	valid_0's binary_logloss: 8.33473e-06
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[170]	valid_0's binary_logloss: 8.06896e-06
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[171]	valid_0's binary_logloss: 8.20684e-06
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[172]	valid_0's binary_logloss: 8.36932e-06
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[173]	valid_0's binary_logloss: 8.45464e-06
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[174]	valid_0's binary_logloss: 8.55663e-06
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[175]	valid_0's binary_logloss: 8.72567e-06
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[176]	valid_0's binary_logloss: 8.54686e-06
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[177]	valid_0's binary_logloss: 8.64326e-06
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[178]	valid_0's binary_logloss: 8.42671e-06
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[179]	valid_0's binary_logloss: 8.42371e-06
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[180]	valid_0's binary_logloss: 8.22804e-06
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[181]	valid_0's binary_logloss: 8.32065e-06
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

Trening klas:  73%|███████▎  | 366/500 [42:39<10:11,  4.57s/klasa, klasa=class_366, F1_klasy=0.0000, F1_macro=0.6686, drzewa=265]




Trening klas:  73%|███████▎  | 367/500 [42:39<10:50,  4.89s/klasa, klasa=class_366, F1_klasy=0.0000, F1_macro=0.6686, drzewa=265]

[1]	valid_0's binary_logloss: 0.0214529
[2]	valid_0's binary_logloss: 0.0199564
[3]	valid_0's binary_logloss: 0.0187015
[4]	valid_0's binary_logloss: 0.0172818
[5]	valid_0's binary_logloss: 0.0160506
[6]	valid_0's binary_logloss: 0.0149475
[7]	valid_0's binary_logloss: 0.0141294
[8]	valid_0's binary_logloss: 0.0132469
[9]	valid_0's binary_logloss: 0.0124565
[10]	valid_0's binary_logloss: 0.011787
[11]	valid_0's binary_logloss: 0.0112108
[12]	valid_0's binary_logloss: 0.0106642
[13]	valid_0's binary_logloss: 0.0101536
[14]	valid_0's binary_logloss: 0.00964253
[15]	valid_0's binary_logloss: 0.00917967
[16]	valid_0's binary_logloss: 0.00873877
[17]	valid_0's binary_logloss: 0.00832052
[18]	valid_0's binary_logloss: 0.00791794
[19]	valid_0's binary_logloss: 0.00753543
[20]	valid_0's binary_logloss: 0.00717346
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0068267
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.00649474
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.00618232
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.00589932
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.00561001
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.00534541
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.00508692
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.00484145
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.00461572
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.00438249
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.00416431
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.00395778
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.00376151
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.00357603
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.00340239
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.00323728
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.00308111
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.00293937
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.00280561
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.0026574
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.00252286
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.00241374
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.00231092
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.00220005
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.00210368
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.00200549
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.0019292
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.00184501
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.00176939
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.00168845
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.00162342
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.00155134
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.00148374
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.00140651
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.00134823
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.00128368
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.00122296
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.001168
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.00111189
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.00106867
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.00101261
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.000967759
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.000922296
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.000886768
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.000850376
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.000815328
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.000776862
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.000746027
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.000717229
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.000683974
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.000650703
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.000621725
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.000591591
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.000561781
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.000541164
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.000517464
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.000492745
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.000468652
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.00044648
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.000425123
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.000406321
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.000395057
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.000376779
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.000362186
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.000345543
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.000329644
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.00031736
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.000304175
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.000292359
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.000282906
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.000273916
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.000264322
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.000255107
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.000245779
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.000237053
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.000230192
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.000222585
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.000213311
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.000204795
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.000196464
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.000188492
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.000181221
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.000175088
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.00016909
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.000165202
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.00015976
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.000153877
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.000148612
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.000142554
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.000137931
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.000133061
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 0.000128235
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 0.000124161
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 0.000119673
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 0.000116193
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[116]	valid_0's binary_logloss: 0.000112297
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[117]	valid_0's binary_logloss: 0.000107816
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[118]	valid_0's binary_logloss: 0.000103479
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[119]	valid_0's binary_logloss: 9.97088e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[120]	valid_0's binary_logloss: 9.7261e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[121]	valid_0's binary_logloss: 9.40215e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[122]	valid_0's binary_logloss: 9.08188e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[123]	valid_0's binary_logloss: 8.86094e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[124]	valid_0's binary_logloss: 8.56798e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[125]	valid_0's binary_logloss: 8.33589e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[126]	valid_0's binary_logloss: 8.07976e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[127]	valid_0's binary_logloss: 7.96285e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[128]	valid_0's binary_logloss: 7.72422e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[129]	valid_0's binary_logloss: 7.49961e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[130]	valid_0's binary_logloss: 7.44773e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[131]	valid_0's binary_logloss: 7.33034e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[132]	valid_0's binary_logloss: 7.22597e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[133]	valid_0's binary_logloss: 7.07629e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[134]	valid_0's binary_logloss: 6.8796e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[135]	valid_0's binary_logloss: 6.8134e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[136]	valid_0's binary_logloss: 6.69169e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[137]	valid_0's binary_logloss: 6.52493e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[138]	valid_0's binary_logloss: 6.36984e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[139]	valid_0's binary_logloss: 6.21323e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[140]	valid_0's binary_logloss: 6.01544e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[141]	valid_0's binary_logloss: 5.91819e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[142]	valid_0's binary_logloss: 5.83523e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[143]	valid_0's binary_logloss: 5.73457e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[144]	valid_0's binary_logloss: 5.65569e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[145]	valid_0's binary_logloss: 5.57499e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[146]	valid_0's binary_logloss: 5.43996e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[147]	valid_0's binary_logloss: 5.31434e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[148]	valid_0's binary_logloss: 5.18415e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[149]	valid_0's binary_logloss: 5.06889e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[150]	valid_0's binary_logloss: 4.96287e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[151]	valid_0's binary_logloss: 4.85905e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[152]	valid_0's binary_logloss: 4.73752e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[153]	valid_0's binary_logloss: 4.6454e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[154]	valid_0's binary_logloss: 4.52861e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[155]	valid_0's binary_logloss: 4.4462e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[156]	valid_0's binary_logloss: 4.36071e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[157]	valid_0's binary_logloss: 4.28433e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[158]	valid_0's binary_logloss: 4.23153e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[159]	valid_0's binary_logloss: 4.15255e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[160]	valid_0's binary_logloss: 4.09922e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[161]	valid_0's binary_logloss: 4.04323e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[162]	valid_0's binary_logloss: 3.96636e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[163]	valid_0's binary_logloss: 3.92498e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[164]	valid_0's binary_logloss: 3.88623e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[165]	valid_0's binary_logloss: 3.83387e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[166]	valid_0's binary_logloss: 3.84511e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[167]	valid_0's binary_logloss: 3.79024e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[168]	valid_0's binary_logloss: 3.77667e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[169]	valid_0's binary_logloss: 3.70464e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[170]	valid_0's binary_logloss: 3.63621e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[171]	valid_0's binary_logloss: 3.5675e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[172]	valid_0's binary_logloss: 3.55016e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[173]	valid_0's binary_logloss: 3.528e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[174]	valid_0's binary_logloss: 3.47747e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[175]	valid_0's binary_logloss: 3.43205e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[176]	valid_0's binary_logloss: 3.42575e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[177]	valid_0's binary_logloss: 3.40276e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[178]	valid_0's binary_logloss: 3.37544e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[179]	valid_0's binary_logloss: 3.33825e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[180]	valid_0's binary_logloss: 3.31731e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[181]	valid_0's binary_logloss: 3.33197e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[182]	valid_0's binary_logloss: 3.29569e-05

Trening klas:  73%|███████▎  | 367/500 [42:48<10:50,  4.89s/klasa, klasa=class_367, F1_klasy=0.0000, F1_macro=0.6668, drzewa=289]




Trening klas:  74%|███████▎  | 368/500 [42:48<13:17,  6.04s/klasa, klasa=class_367, F1_klasy=0.0000, F1_macro=0.6668, drzewa=289]

[295]	valid_0's binary_logloss: 2.17147e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[296]	valid_0's binary_logloss: 2.16378e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[297]	valid_0's binary_logloss: 2.22013e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[298]	valid_0's binary_logloss: 2.21628e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[299]	valid_0's binary_logloss: 2.19789e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[300]	valid_0's binary_logloss: 2.25344e-05
[1]	valid_0's binary_logloss: 0.0114038
[2]	valid_0's binary_logloss: 0.0105907
[3]	valid_0's binary_logloss: 0.0102049
[4]	valid_0's binary_logloss: 0.00963741
[5]	valid_0's binary_logloss: 0.00910354
[6]	valid_0's binary_logloss: 0.00856362
[7]	valid_0's binary_logloss: 0.00808227
[8]	valid_0's binary_logloss: 0.00764295
[9]	valid_0's binary_logloss: 0.00723944
[10]	valid_0's binary_logloss: 0.00690448
[11]	valid_0's binary_logloss: 0.00664136
[12]	valid_0's binary_logloss: 0.00630439
[13]	valid_0's binary_logloss: 0.0060008
[14]	valid_0's binary_logloss: 0.00570434
[15]	valid_0's binary_logloss: 0.00542518
[16]	valid_0's binary_logloss: 0.00517457
[17]	valid_0's binary_logloss: 0.00493741
[18]	valid_0's binary_logloss: 0.00470908
[19]	valid_0's binary_logloss: 0.00450058
[20]	valid_0's binary_logloss: 0.00432794
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.00413564
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.00395657
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.00380358
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.00364107
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.00350004
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.00335966
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.00322187
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.0030917
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.00297823
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.00286192
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.00274962
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.00264392
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.00254414
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.00245267
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.00236554
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.00228628
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.00221137
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.00213923
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.0020702
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.00200487
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.00193746
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.00187871
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.00182126
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.00176868
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.00171936
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.00167424
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.001629
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.0015864
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.00154628
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.00150872
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.00147392
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.00144064
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.00140957
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.00138052
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.00135353
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.00132316
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.00129848
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.00127508
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.00125341
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.00123445
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.00121582
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.0011971
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.00118088
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.0011653
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.00115091
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.00113853
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.00112495
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.00111447
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.00109495
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.0010858
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.00107681
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.00106849
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.00106124
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.0010548
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.00104849
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.00104424
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.00103631
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.00103169
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.00102865
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.0010261
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.00102412
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.00101474
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.00101353
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.00101218
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.00101148
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.00100956
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.00100807
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.000994693
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.000981458
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.000968914
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.000970098
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.000971657
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.000972983
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.000975428
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.00097851
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.000967817
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.000971275
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.000974973
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.000978721
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.000982701
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.000985956
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.000988733
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.000978292
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.000968521
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.000968734
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.000958768
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.000949301
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.000939959
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.000930996
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.00092229
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.00092598
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 0.000925079
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 0.000915342
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 0.000908952
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 0.000904011
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[116]	valid_0's binary_logloss: 0.000909003
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[117]	valid_0's binary_logloss: 0.000913141
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[118]	valid_0's binary_logloss: 0.000909247
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[119]	valid_0's binary_logloss: 0.000913172
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[120]	valid_0's binary_logloss: 0.00090694
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[121]	valid_0's binary_logloss: 0.000905946
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[122]	valid_0's binary_logloss: 0.000911488
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[123]	valid_0's binary_logloss: 0.00091644
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[124]	valid_0's binary_logloss: 0.000922142
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[125]	valid_0's binary_logloss: 0.000923532
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[126]	valid_0's binary_logloss: 0.000919035
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[127]	valid_0's binary_logloss: 0.000914656
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[128]	valid_0's binary_logloss: 0.000910143
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[129]	valid_0's binary_logloss: 0.000916097
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[130]	valid_0's binary_logloss: 0.000911547
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[131]	valid_0's binary_logloss: 0.000900183
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[132]	valid_0's binary_logloss: 0.000889063
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[133]	valid_0's binary_logloss: 0.000882673
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[134]	valid_0's binary_logloss: 0.000876427
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[135]	valid_0's binary_logloss: 0.00087032
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[136]	valid_0's binary_logloss: 0.000876475
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[137]	valid_0's binary_logloss: 0.000882537
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[138]	valid_0's binary_logloss: 0.000888823
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[139]	valid_0's binary_logloss: 0.000879337
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[140]	valid_0's binary_logloss: 0.000878292
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[141]	valid_0's binary_logloss: 0.000884615
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[142]	valid_0's binary_logloss: 0.000891162
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[143]	valid_0's binary_logloss: 0.000897703
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[144]	valid_0's binary_logloss: 0.000904278
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[145]	valid_0's binary_logloss: 0.000910738
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[146]	valid_0's binary_logloss: 0.000902744
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[147]	valid_0's binary_logloss: 0.000894986
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[148]	valid_0's binary_logloss: 0.000891902
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[149]	valid_0's binary_logloss: 0.000891254
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[150]	valid_0's binary_logloss: 0.000897247
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[151]	valid_0's binary_logloss: 0.000902989
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[152]	valid_0's binary_logloss: 0.000896243
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[153]	valid_0's binary_logloss: 0.000890939
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[154]	valid_0's binary_logloss: 0.000883922
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[155]	valid_0's binary_logloss: 0.000883428
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[156]	valid_0's binary_logloss: 0.000873945
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[157]	valid_0's binary_logloss: 0.000864675
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[158]	valid_0's binary_logloss: 0.000868876
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[159]	valid_0's binary_logloss: 0.000859952
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[160]	valid_0's binary_logloss: 0.0008513
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[161]	valid_0's binary_logloss: 0.000852129
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[162]	valid_0's binary_logloss: 0.000844576
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[163]	valid_0's binary_logloss: 0.000837157
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[164]	valid_0's binary_logloss: 0.000836713
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[165]	valid_0's binary_logloss: 0.00084111
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[166]	valid_0's binary_logloss: 0.000839708
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[167]	valid_0's binary_logloss: 0.000845536
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[168]	valid_0's binary_logloss: 0.000844275
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[169]	valid_0's binary_logloss: 0.000843073
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[170]	valid_0's binary_logloss: 0.000850229
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[171]	valid_0's binary_logloss: 0.000850078
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[172]	valid_0's binary_logloss: 0.000845266
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[173]	valid_0's binary_logloss: 0.000839997
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[174]	valid_0's binary_logloss: 0.000835381
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[175]	valid_0's binary_logloss: 0.000830909
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[176]	valid_0's binary_logloss: 0.000837735
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[177]	valid_0's binary_logloss: 0.000844455

Trening klas:  74%|███████▎  | 368/500 [42:56<13:17,  6.04s/klasa, klasa=class_368, F1_klasy=0.6667, F1_macro=0.6668, drzewa=216]




Trening klas:  74%|███████▍  | 369/500 [42:56<14:28,  6.63s/klasa, klasa=class_368, F1_klasy=0.6667, F1_macro=0.6668, drzewa=216]

[1]	valid_0's binary_logloss: 0.073226
[2]	valid_0's binary_logloss: 0.0480122
[3]	valid_0's binary_logloss: 0.044054
[4]	valid_0's binary_logloss: 0.0411714
[5]	valid_0's binary_logloss: 0.0390438
[6]	valid_0's binary_logloss: 0.0406254
[7]	valid_0's binary_logloss: 0.0388794
[8]	valid_0's binary_logloss: 0.0372049
[9]	valid_0's binary_logloss: 0.0357212
[10]	valid_0's binary_logloss: 0.0344382
[11]	valid_0's binary_logloss: 0.033223
[12]	valid_0's binary_logloss: 0.0320444
[13]	valid_0's binary_logloss: 0.0309525
[14]	valid_0's binary_logloss: 0.0299999
[15]	valid_0's binary_logloss: 0.0290912
[16]	valid_0's binary_logloss: 0.0284135
[17]	valid_0's binary_logloss: 0.0277398
[18]	valid_0's binary_logloss: 0.0270748
[19]	valid_0's binary_logloss: 0.0264693
[20]	valid_0's binary_logloss: 0.0258208
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0252767
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.024761
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.0243405
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0238858
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.023496
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.0231049
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.0226747
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.0222633
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.0219285
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.0215025
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.0211605
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.0208466
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.0206099
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.0202734
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.0200053
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.0197041
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.0193944
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.0191187
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.0188595
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.0186682
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.0183871
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.0182228
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.0180147
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.0178326
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.0176452
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.0173602
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.0170167
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.0168184
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.016628
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.0164557
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.0162593
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.0160398
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.0158722
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.0157554
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.0156002
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.0154857
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.0153742
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.0152395
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.0151118
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.0149692
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.0148463
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.0146443
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.0144921
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.0144276
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.0142633
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.0140838
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.0138985
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.0137568
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.0136186
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.013534
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.0133469
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.013108
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.0129878
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.0128729
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.0128613
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.0128399
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.0127417
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.0126336
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.0125292
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.0124166
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.0124199
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.0123266
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.0123291
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.0122489
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.012121
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.0120547
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.0119437
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.0118828
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.0117809
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.0116709
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.0116131
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.0114989
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.0114214
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.0113307
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.0112581
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.011171
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.0110977
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.0110471
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.0109947
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.0109357
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.0108768
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.0107458
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.0106306
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.0105345
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.0104213
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.0104375
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.0104481
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.0104832
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.0104489
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.0104297
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.0103851
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 0.0103432
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 0.0102951
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 0.0102519
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 0.0102485
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[116]	valid_0's binary_logloss: 0.0102783
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[117]	valid_0's binary_logloss: 0.0103103
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[118]	valid_0's binary_logloss: 0.0102523
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[119]	valid_0's binary_logloss: 0.0102089
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[120]	valid_0's binary_logloss: 0.0102612
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[121]	valid_0's binary_logloss: 0.0102274
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[122]	valid_0's binary_logloss: 0.0102002
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[123]	valid_0's binary_logloss: 0.0101486
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[124]	valid_0's binary_logloss: 0.0100886
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[125]	valid_0's binary_logloss: 0.0100592
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[126]	valid_0's binary_logloss: 0.0100427
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[127]	valid_0's binary_logloss: 0.00997652
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[128]	valid_0's binary_logloss: 0.00997038
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[129]	valid_0's binary_logloss: 0.00996101
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[130]	valid_0's binary_logloss: 0.00995295
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[131]	valid_0's binary_logloss: 0.0099048
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[132]	valid_0's binary_logloss: 0.00989733
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[133]	valid_0's binary_logloss: 0.00985572
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[134]	valid_0's binary_logloss: 0.00984509
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[135]	valid_0's binary_logloss: 0.00980898
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[136]	valid_0's binary_logloss: 0.0097692
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[137]	valid_0's binary_logloss: 0.00973774
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[138]	valid_0's binary_logloss: 0.00971083
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[139]	valid_0's binary_logloss: 0.00969814
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[140]	valid_0's binary_logloss: 0.00966374
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[141]	valid_0's binary_logloss: 0.00962515
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[142]	valid_0's binary_logloss: 0.00958462
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[143]	valid_0's binary_logloss: 0.00955621
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[144]	valid_0's binary_logloss: 0.00953482
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[145]	valid_0's binary_logloss: 0.00950573
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[146]	valid_0's binary_logloss: 0.00946169
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[147]	valid_0's binary_logloss: 0.00942804
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[148]	valid_0's binary_logloss: 0.00939217
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[149]	valid_0's binary_logloss: 0.00934195
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[150]	valid_0's binary_logloss: 0.00930714
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[151]	valid_0's binary_logloss: 0.00929983
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[152]	valid_0's binary_logloss: 0.00927893
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[153]	valid_0's binary_logloss: 0.00924654
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[154]	valid_0's binary_logloss: 0.0092394
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[155]	valid_0's binary_logloss: 0.00921841
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[156]	valid_0's binary_logloss: 0.00918042
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[157]	valid_0's binary_logloss: 0.00916735
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[158]	valid_0's binary_logloss: 0.00915614
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[159]	valid_0's binary_logloss: 0.00913938
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[160]	valid_0's binary_logloss: 0.00914838
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[161]	valid_0's binary_logloss: 0.00913262
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[162]	valid_0's binary_logloss: 0.00911063
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[163]	valid_0's binary_logloss: 0.00908791
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[164]	valid_0's binary_logloss: 0.0090666
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[165]	valid_0's binary_logloss: 0.00904233
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[166]	valid_0's binary_logloss: 0.00900318
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[167]	valid_0's binary_logloss: 0.00898968
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[168]	valid_0's binary_logloss: 0.00894436
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[169]	valid_0's binary_logloss: 0.00889153
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[170]	valid_0's binary_logloss: 0.00884468
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[171]	valid_0's binary_logloss: 0.00883725
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[172]	valid_0's binary_logloss: 0.00881814
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[173]	valid_0's binary_logloss: 0.00880176
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[174]	valid_0's binary_logloss: 0.00879279
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[175]	valid_0's binary_logloss: 0.00879185
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[176]	valid_0's binary_logloss: 0.00878695
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[177]	valid_0's binary_logloss: 0.00878035
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[178]	valid_0's binary_logloss: 0.00876565
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[179]	valid_0's binary_logloss: 0.00876481
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[180]	valid_0's binary_logloss: 0.00875532
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[181]	valid_0's binary_logloss: 0.00874497
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[182]	valid_0's binary_logloss: 0.0087473
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[183]	valid_0's binary_logloss: 0.00873936
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[184]	valid_0's binary_logloss: 0.00874793

Trening klas:  74%|███████▍  | 369/500 [43:04<14:28,  6.63s/klasa, klasa=class_369, F1_klasy=0.7619, F1_macro=0.6671, drzewa=291]




Trening klas:  74%|███████▍  | 370/500 [43:04<15:33,  7.18s/klasa, klasa=class_369, F1_klasy=0.7619, F1_macro=0.6671, drzewa=291]

[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[300]	valid_0's binary_logloss: 0.00831943
[1]	valid_0's binary_logloss: 0.0261024
[2]	valid_0's binary_logloss: 0.0237211
[3]	valid_0's binary_logloss: 0.022239
[4]	valid_0's binary_logloss: 0.0207615
[5]	valid_0's binary_logloss: 0.0197991
[6]	valid_0's binary_logloss: 0.0190751
[7]	valid_0's binary_logloss: 0.0181779
[8]	valid_0's binary_logloss: 0.0175544
[9]	valid_0's binary_logloss: 0.0168974
[10]	valid_0's binary_logloss: 0.0162795
[11]	valid_0's binary_logloss: 0.0156484
[12]	valid_0's binary_logloss: 0.0150575
[13]	valid_0's binary_logloss: 0.0144915
[14]	valid_0's binary_logloss: 0.0139323
[15]	valid_0's binary_logloss: 0.0133049
[16]	valid_0's binary_logloss: 0.0127904
[17]	valid_0's binary_logloss: 0.0123825
[18]	valid_0's binary_logloss: 0.0119427
[19]	valid_0's binary_logloss: 0.0115509
[20]	valid_0's binary_logloss: 0.0111499
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0107972
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0105
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.010196
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.00986608
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.00958051
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.00927751
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.00898486
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.00873975
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.00849563
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.00827694
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.00805934
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.00783806
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.00764942
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.00744554
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.00728147
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.00710481
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.00693595
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.00680682
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.00664478
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.00647356
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.00634412
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.00621256
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.00607712
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.00595261
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.00585904
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.00575668
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.0056745
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.00557051
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.00550268
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.00541868
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.00533954
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.00527346
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.00521114
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.00513995
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.00508353
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.00505186
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.00500583
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.00496526
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.00493483
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.00490663
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.00484897
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.00483458
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.00480995
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.00473504
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.00470588
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.00465187
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.00459929
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.00455206
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.00450719
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.00447444
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.00444271
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.00440964
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.00438587
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.00438236
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.00439535
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.0043741
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.00434701
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.00431847
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.00430201
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.00428785
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.00429759
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.00431514
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.00431842
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.00432623
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.00433661
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.00433878
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.00434586
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.004361
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.00437828
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.00437035
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.00436805
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.00435861
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.00436833
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.00436767
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.00436965
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.00435206
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.00435624
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.00434817
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.00434252
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.00434255
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.00435781
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.00436459
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.0043787
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.00438337
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.00438264
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.00435864
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.0043571
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

Trening klas:  74%|███████▍  | 370/500 [43:09<15:33,  7.18s/klasa, klasa=class_370, F1_klasy=0.6250, F1_macro=0.6670, drzewa=80]




Trening klas:  74%|███████▍  | 371/500 [43:09<13:33,  6.31s/klasa, klasa=class_370, F1_klasy=0.6250, F1_macro=0.6670, drzewa=80]

[108]	valid_0's binary_logloss: 0.00433845
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.00435605
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.00434158
[1]	valid_0's binary_logloss: 0.673027
[2]	valid_0's binary_logloss: 0.333701
[3]	valid_0's binary_logloss: 0.321059
[4]	valid_0's binary_logloss: 0.303629
[5]	valid_0's binary_logloss: 0.292481
[6]	valid_0's binary_logloss: 0.286131
[7]	valid_0's binary_logloss: 0.277331
[8]	valid_0's binary_logloss: 0.272353
[9]	valid_0's binary_logloss: 0.267697
[10]	valid_0's binary_logloss: 0.263628
[11]	valid_0's binary_logloss: 0.259718
[12]	valid_0's binary_logloss: 0.25626
[13]	valid_0's binary_logloss: 0.252973
[14]	valid_0's binary_logloss: 0.249846
[15]	valid_0's binary_logloss: 0.246795
[16]	valid_0's binary_logloss: 0.243545
[17]	valid_0's binary_logloss: 0.240563
[18]	valid_0's binary_logloss: 0.237749
[19]	valid_0's binary_logloss: 0.23485
[20]	valid_0's binary_logloss: 0.232283
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.229471
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.226818
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.224246
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.22197
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.219775
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.217841
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.215852
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.2139
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.212092
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.21028
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.208132
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.206351
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.204406
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.202642
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.201006
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.199614
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.198165
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.196831
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.195385
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.193982
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.192478
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.191307
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.189913
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.18845
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.187209
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.186014
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.185153
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.183528
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.182544
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.181555
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.181025
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.180337
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.179239
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.178231
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.177032
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.176367
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.175273
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.174498
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.17356
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.172659
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.171589
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.170856
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.170135
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.169224
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.168307
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.167234
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.166105
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.165041
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.163886
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.162741
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.161807
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.160936
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.160132
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.15911
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.158314
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.15771
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.157267
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.156621
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.156058
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.155663
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.155059
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.154507
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.153906
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.153255
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.152637
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.151749
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.151127
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.150563
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.150135
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.149315
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.148786
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.148294
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.147918
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.147398
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.14713
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.146731
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.146144
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.145593
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.145276
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.144772
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.144286
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.143952
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.143622
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.143283
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.142909
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.142671
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.142492
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.142103
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.141822
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.141675
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.141378
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 0.141018
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 0.140558
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 0.140183
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 0.140043
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[116]	valid_0's binary_logloss: 0.139748
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[117]	valid_0's binary_logloss: 0.139493
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[118]	valid_0's binary_logloss: 0.139263
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[119]	valid_0's binary_logloss: 0.138931
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[120]	valid_0's binary_logloss: 0.138563
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[121]	valid_0's binary_logloss: 0.138353
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[122]	valid_0's binary_logloss: 0.138028
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[123]	valid_0's binary_logloss: 0.137782
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[124]	valid_0's binary_logloss: 0.137632
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[125]	valid_0's binary_logloss: 0.137306
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[126]	valid_0's binary_logloss: 0.137167
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[127]	valid_0's binary_logloss: 0.136623
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[128]	valid_0's binary_logloss: 0.136503
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[129]	valid_0's binary_logloss: 0.136368
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[130]	valid_0's binary_logloss: 0.136181
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[131]	valid_0's binary_logloss: 0.136148
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[132]	valid_0's binary_logloss: 0.136097
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[133]	valid_0's binary_logloss: 0.135944
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[134]	valid_0's binary_logloss: 0.135896
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[135]	valid_0's binary_logloss: 0.13588
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[136]	valid_0's binary_logloss: 0.135475
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[137]	valid_0's binary_logloss: 0.13513
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[138]	valid_0's binary_logloss: 0.134638
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[139]	valid_0's binary_logloss: 0.134314
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[140]	valid_0's binary_logloss: 0.13384
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[141]	valid_0's binary_logloss: 0.133597
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[142]	valid_0's binary_logloss: 0.133343
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[143]	valid_0's binary_logloss: 0.133108
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[144]	valid_0's binary_logloss: 0.13292
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[145]	valid_0's binary_logloss: 0.132836
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[146]	valid_0's binary_logloss: 0.13257
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[147]	valid_0's binary_logloss: 0.132303
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[148]	valid_0's binary_logloss: 0.132042
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[149]	valid_0's binary_logloss: 0.132069
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[150]	valid_0's binary_logloss: 0.131817
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[151]	valid_0's binary_logloss: 0.131808
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[152]	valid_0's binary_logloss: 0.131776
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[153]	valid_0's binary_logloss: 0.131846
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[154]	valid_0's binary_logloss: 0.131509
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[155]	valid_0's binary_logloss: 0.131579
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[156]	valid_0's binary_logloss: 0.131184
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[157]	valid_0's binary_logloss: 0.131016
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[158]	valid_0's binary_logloss: 0.130638
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[159]	valid_0's binary_logloss: 0.130525
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[160]	valid_0's binary_logloss: 0.130173
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[161]	valid_0's binary_logloss: 0.130088
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[162]	valid_0's binary_logloss: 0.130068
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[163]	valid_0's binary_logloss: 0.129992
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[164]	valid_0's binary_logloss: 0.129939
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[165]	valid_0's binary_logloss: 0.129899
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[166]	valid_0's binary_logloss: 0.129616
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[167]	valid_0's binary_logloss: 0.129518
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[168]	valid_0's binary_logloss: 0.129375
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[169]	valid_0's binary_logloss: 0.129274
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[170]	valid_0's binary_logloss: 0.129205
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[171]	valid_0's binary_logloss: 0.128968
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[172]	valid_0's binary_logloss: 0.128739
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[173]	valid_0's binary_logloss: 0.128511
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[174]	valid_0's binary_logloss: 0.128309
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[175]	valid_0's binary_logloss: 0.128028
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[176]	valid_0's binary_logloss: 0.128
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[177]	valid_0's binary_logloss: 0.127833
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[178]	valid_0's binary_logloss: 0.127667
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[179]	valid_0's binary_logloss: 0.127533
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[180]	valid_0's binary_logloss: 0.12751
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[181]	valid_0's binary_logloss: 0.127447
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[182]	valid_0's binary_logloss: 0.127417
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[183]	valid_0's binary_logloss: 0.127369
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[184]	valid_0's binary_logloss: 0.127433

Trening klas:  74%|███████▍  | 371/500 [43:15<13:33,  6.31s/klasa, klasa=class_371, F1_klasy=0.2489, F1_macro=0.6658, drzewa=245]




Trening klas:  74%|███████▍  | 372/500 [43:15<13:28,  6.32s/klasa, klasa=class_371, F1_klasy=0.2489, F1_macro=0.6658, drzewa=245]

[1]	valid_0's binary_logloss: 0.0107816
[2]	valid_0's binary_logloss: 0.0100283
[3]	valid_0's binary_logloss: 0.00954402
[4]	valid_0's binary_logloss: 0.00906011
[5]	valid_0's binary_logloss: 0.00868787
[6]	valid_0's binary_logloss: 0.00825618
[7]	valid_0's binary_logloss: 0.00787526
[8]	valid_0's binary_logloss: 0.00753383
[9]	valid_0's binary_logloss: 0.00726267
[10]	valid_0's binary_logloss: 0.00698639
[11]	valid_0's binary_logloss: 0.00670703
[12]	valid_0's binary_logloss: 0.00643625
[13]	valid_0's binary_logloss: 0.00618423
[14]	valid_0's binary_logloss: 0.0059531
[15]	valid_0's binary_logloss: 0.00571553
[16]	valid_0's binary_logloss: 0.00547799
[17]	valid_0's binary_logloss: 0.00527699
[18]	valid_0's binary_logloss: 0.00509797
[19]	valid_0's binary_logloss: 0.00489261
[20]	valid_0's binary_logloss: 0.00472672
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.00455224
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.00442051
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.00429512
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.00415991
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.00403683
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.00391553
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.00381007
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.00371922
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.00359489
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.00347111
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.00338054
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.00331358
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.00322756
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.0031687
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.00312042
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.00305248
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.00300109
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.0029363
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.00285569
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.00282045
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.00275899
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.00272202
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.00266613
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.00263649
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.00260571
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.00255378
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.00248961
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.00248251
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.0024381
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.00240904
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.00238999
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.00238023
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.00233826
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.00229601
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.00227364
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.00224263
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.00222851
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.00221526
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.00219725
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.00217272
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.00217118
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.00215676
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.00211283
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.00211257
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.00207942
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.00205539
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.0020314
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.00200935
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.00197095
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.00195589
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.00192296
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.00189839
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.00187921
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.00184856
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.00186078
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.00182348
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.00180527
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.00175713
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.00174537
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.00174217
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.00175596
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.00173587
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.00175057
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.00176549
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.00177815
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.00176211
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.00175869
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.00175568
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.00175563
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.00175969
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.00174917
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.00174212
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.00169814
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.00168728
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.0016653
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.00166635
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.00167767
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.0016936
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.00167976
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.00169581
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.00167096
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.00165381
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.00166446
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.00165457
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.00164757
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.00164517
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.00164247
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.00164882
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.00164217
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.00164934
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.00163226
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 0.00163858
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 0.00164841
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 0.00166329
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 0.00166981
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[116]	valid_0's binary_logloss: 0.00166046
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[117]	valid_0's binary_logloss: 0.00166181
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[118]	valid_0's binary_logloss: 0.00165331
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[119]	valid_0's binary_logloss: 0.00165174
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[120]	valid_0's binary_logloss: 0.00164156
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[121]	valid_0's binary_logloss: 0.00164087
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[122]	valid_0's binary_logloss: 0.00164975
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[123]	valid_0's binary_logloss: 0.0016575
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[124]	valid_0's binary_logloss: 0.00166156
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[125]	valid_0's binary_logloss: 0.00166041
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[126]	valid_0's binary_logloss: 0.00167115
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[127]	valid_0's binary_logloss: 0.00168763
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[128]	valid_0's binary_logloss: 0.00169952
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[129]	valid_0's binary_logloss: 0.00171093
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[130]	valid_0's binary_logloss: 0.00172036
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[131]	valid_0's binary_logloss: 0.00170872
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[132]	valid_0's binary_logloss: 0.00169559
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[133]	valid_0's binary_logloss: 0.0016955
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[134]	valid_0's binary_logloss: 0.00170396
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[135]	valid_0's binary_logloss: 0.0017009
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[136]	valid_0's binary_logloss: 0.0017016
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[137]	valid_0's binary_logloss: 0.00170048
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[138]	valid_0's binary_logloss: 0.00169813
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[139]	valid_0's binary_logloss: 0.00171243
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[140]	valid_0's binary_logloss: 0.00173092
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

Trening klas:  74%|███████▍  | 372/500 [43:21<13:28,  6.32s/klasa, klasa=class_372, F1_klasy=0.5714, F1_macro=0.6656, drzewa=111]




Trening klas:  75%|███████▍  | 373/500 [43:21<13:05,  6.19s/klasa, klasa=class_372, F1_klasy=0.5714, F1_macro=0.6656, drzewa=111]

[141]	valid_0's binary_logloss: 0.00173792
[1]	valid_0's binary_logloss: 0.0939478
[2]	valid_0's binary_logloss: 0.0635125
[3]	valid_0's binary_logloss: 0.0592514
[4]	valid_0's binary_logloss: 0.0554885
[5]	valid_0's binary_logloss: 0.0528397
[6]	valid_0's binary_logloss: 0.0514063
[7]	valid_0's binary_logloss: 0.0496662
[8]	valid_0's binary_logloss: 0.0477786
[9]	valid_0's binary_logloss: 0.0459961
[10]	valid_0's binary_logloss: 0.0444805
[11]	valid_0's binary_logloss: 0.0428957
[12]	valid_0's binary_logloss: 0.0416211
[13]	valid_0's binary_logloss: 0.0405684
[14]	valid_0's binary_logloss: 0.0393349
[15]	valid_0's binary_logloss: 0.0384019
[16]	valid_0's binary_logloss: 0.0373871
[17]	valid_0's binary_logloss: 0.036567
[18]	valid_0's binary_logloss: 0.0358025
[19]	valid_0's binary_logloss: 0.0350212
[20]	valid_0's binary_logloss: 0.0342693
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0335804
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0329187
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.032268
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0316007
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.0310162
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.0304313
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.0299254
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.0293994
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.0288578
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.0283375
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.0278749
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.0274242
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.0270582
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.0267345
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.0263758
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.025952
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.025532
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.0251364
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.0247676
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.0244162
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.0241268
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.0238497
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.023659
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.0234205
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.0231919
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.0229836
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.0228131
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.0225722
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.0223018
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.0219986
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.0217494
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.0216044
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.0214304
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.021269
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.0211245
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.0209357
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.0208718
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.0207838
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.0207281
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.0206519
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.0205242
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.0204207
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.02036
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.0203053
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.0202061
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.020169
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.0201191
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.0199963
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.0198831
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.019879
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.0196966
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.0195725
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.0195022
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.019366
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.0192865
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.0192117
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.0191552
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.0191195
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.0190963
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.0190785
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.0190842
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.01908
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.0190814
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.0191293
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.0191336
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.0191535
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.0191603
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.0190401
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.0189176
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.0188218
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.0188052
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.0187756
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.0187502
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.018793
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.0187691
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.0187561
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.0187619
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.0187403
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.0187937
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.018782
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.0187733
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.0187855
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.0188173
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.018891
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.0188977
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.0189075
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.0189395
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.0189856
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.0190389
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.01903
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.0190233
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 0.0189843
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 0.0190063
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 0.0189663
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 0.0189757
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[116]	valid_0's binary_logloss: 0.0189899
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[117]	valid_0's binary_logloss: 0.018995
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[118]	valid_0's binary_logloss: 0.0190155
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[119]	valid_0's binary_logloss: 0.0190525
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[120]	valid_0's binary_logloss: 0.0190629
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[121]	valid_0's binary_logloss: 0.0191039
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[122]	valid_0's binary_logloss: 0.0190995
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[123]	valid_0's binary_logloss: 0.0191467
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[124]	valid_0's binary_logloss: 0.0191867
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[125]	valid_0's binary_logloss: 0.0192327
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

Trening klas:  75%|███████▍  | 373/500 [43:27<13:05,  6.19s/klasa, klasa=class_373, F1_klasy=0.5556, F1_macro=0.6653, drzewa=98]




Trening klas:  75%|███████▍  | 374/500 [43:27<12:52,  6.13s/klasa, klasa=class_373, F1_klasy=0.5556, F1_macro=0.6653, drzewa=98]

[126]	valid_0's binary_logloss: 0.0192571
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[127]	valid_0's binary_logloss: 0.0192854
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[128]	valid_0's binary_logloss: 0.019286
[1]	valid_0's binary_logloss: 0.257445
[2]	valid_0's binary_logloss: 0.18688
[3]	valid_0's binary_logloss: 0.173206
[4]	valid_0's binary_logloss: 0.163233
[5]	valid_0's binary_logloss: 0.156439
[6]	valid_0's binary_logloss: 0.157487
[7]	valid_0's binary_logloss: 0.152514
[8]	valid_0's binary_logloss: 0.14783
[9]	valid_0's binary_logloss: 0.143627
[10]	valid_0's binary_logloss: 0.139864
[11]	valid_0's binary_logloss: 0.1367
[12]	valid_0's binary_logloss: 0.132664
[13]	valid_0's binary_logloss: 0.129184
[14]	valid_0's binary_logloss: 0.126197
[15]	valid_0's binary_logloss: 0.123401
[16]	valid_0's binary_logloss: 0.121062
[17]	valid_0's binary_logloss: 0.119237
[18]	valid_0's binary_logloss: 0.117156
[19]	valid_0's binary_logloss: 0.115076
[20]	valid_0's binary_logloss: 0.11338
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.111254
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.109382
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.107536
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.105786
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.104107
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.102509
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.10109
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.0998586
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.0983744
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.0968803
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.0956514
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.0945674
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.0934353
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.0924496
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.0914796
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.0905334
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.0895153
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.0885007
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.0875494
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.0866849
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.0857602
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.0848981
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.0842508
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.0834963
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.0827593
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.0821698
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.0817696
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.0811825
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.0806543
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.0799549
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.0793243
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.0787415
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.0782285
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.0776858
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.0771955
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.0767877
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.0763586
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.0758604
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.0754956
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.0749924
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.0746799
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.0741847
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.0738187
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.0734047
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.0729458
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.0727622
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.0723068
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.071776
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.0714162
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.0709634
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.0707014
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.0704807
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.0701648
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.0699374
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.0697704
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.0697233
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.0696443
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.0692298
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.0689878
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.0687253
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.0684751
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.0682523
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.0680892
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.0679468
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.0677394
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.0675721
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.067355
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.0672356
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.0670145
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.066893
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.0667297
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.066496
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.0662971
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.0660452
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.06588
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.0657039
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.0656835
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.0656051
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.0655695
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.0654196
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.0652402
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.0651171
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.065041
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.0649905
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.0649388
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.0647388
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.0646377
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.0646015
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.0644409
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.0643755
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.0642071
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 0.0641195
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 0.0639872
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 0.063912
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 0.0638477
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[116]	valid_0's binary_logloss: 0.063857
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[117]	valid_0's binary_logloss: 0.0639091
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[118]	valid_0's binary_logloss: 0.0639253
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[119]	valid_0's binary_logloss: 0.063946
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[120]	valid_0's binary_logloss: 0.0638971
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[121]	valid_0's binary_logloss: 0.0638323
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[122]	valid_0's binary_logloss: 0.0637657
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[123]	valid_0's binary_logloss: 0.0637455
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[124]	valid_0's binary_logloss: 0.0637446
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[125]	valid_0's binary_logloss: 0.0637537
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[126]	valid_0's binary_logloss: 0.0637584
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[127]	valid_0's binary_logloss: 0.0636771
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[128]	valid_0's binary_logloss: 0.0636846
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[129]	valid_0's binary_logloss: 0.0636152
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[130]	valid_0's binary_logloss: 0.063519
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[131]	valid_0's binary_logloss: 0.0635931
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[132]	valid_0's binary_logloss: 0.0636335
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[133]	valid_0's binary_logloss: 0.0636916
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[134]	valid_0's binary_logloss: 0.063695
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[135]	valid_0's binary_logloss: 0.0637126
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[136]	valid_0's binary_logloss: 0.0636284
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[137]	valid_0's binary_logloss: 0.0636971
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[138]	valid_0's binary_logloss: 0.0636797
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[139]	valid_0's binary_logloss: 0.0636449
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[140]	valid_0's binary_logloss: 0.0635254
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[141]	valid_0's binary_logloss: 0.0634844
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[142]	valid_0's binary_logloss: 0.0636188
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[143]	valid_0's binary_logloss: 0.0636838
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[144]	valid_0's binary_logloss: 0.0637583
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[145]	valid_0's binary_logloss: 0.0638479
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[146]	valid_0's binary_logloss: 0.0639008
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[147]	valid_0's binary_logloss: 0.0638941
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[148]	valid_0's binary_logloss: 0.0638807
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[149]	valid_0's binary_logloss: 0.0639238
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[150]	valid_0's binary_logloss: 0.0639243
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[151]	valid_0's binary_logloss: 0.0639732
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[152]	valid_0's binary_logloss: 0.0640498
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[153]	valid_0's binary_logloss: 0.0641104
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[154]	valid_0's binary_logloss: 0.0641498
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[155]	valid_0's binary_logloss: 0.0642244
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[156]	valid_0's binary_logloss: 0.0642283
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[157]	valid_0's binary_logloss: 0.0642521
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[158]	valid_0's binary_logloss: 0.0643152
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[159]	valid_0's binary_logloss: 0.0643762
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[160]	valid_0's binary_logloss: 0.0644325
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[161]	valid_0's binary_logloss: 0.0644406
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[162]	valid_0's binary_logloss: 0.0644494
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[163]	valid_0's binary_logloss: 0.0644769
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[164]	valid_0's binary_logloss: 0.0644928
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[165]	valid_0's binary_logloss: 0.0645458
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[166]	valid_0's binary_logloss: 0.0646335
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[167]	valid_0's binary_logloss: 0.0646895
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[168]	valid_0's binary_logloss: 0.0647503
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[169]	valid_0's binary_logloss: 0.0648066
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[170]	valid_0's binary_logloss: 0.0648713
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[171]	valid_0's binary_logloss: 0.0647367

Trening klas:  75%|███████▍  | 374/500 [43:36<12:52,  6.13s/klasa, klasa=class_374, F1_klasy=0.2979, F1_macro=0.6643, drzewa=141]




Trening klas:  75%|███████▌  | 375/500 [43:36<14:38,  7.03s/klasa, klasa=class_374, F1_klasy=0.2979, F1_macro=0.6643, drzewa=141]

[1]	valid_0's binary_logloss: 0.00782881
[2]	valid_0's binary_logloss: 0.00741165
[3]	valid_0's binary_logloss: 0.00704152
[4]	valid_0's binary_logloss: 0.00670307
[5]	valid_0's binary_logloss: 0.00638435
[6]	valid_0's binary_logloss: 0.00609231
[7]	valid_0's binary_logloss: 0.00581759
[8]	valid_0's binary_logloss: 0.005562
[9]	valid_0's binary_logloss: 0.00532388
[10]	valid_0's binary_logloss: 0.00510069
[11]	valid_0's binary_logloss: 0.0335157
[12]	valid_0's binary_logloss: 0.0332657
[13]	valid_0's binary_logloss: 0.0330289
[14]	valid_0's binary_logloss: 0.0327985
[15]	valid_0's binary_logloss: 0.0325871
[16]	valid_0's binary_logloss: 0.0323778
[17]	valid_0's binary_logloss: 0.032178
[18]	valid_0's binary_logloss: 0.031989
[19]	valid_0's binary_logloss: 0.031804
[20]	valid_0's binary_logloss: 0.03162
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0314454
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0312759
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.031118
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0309606
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.0308079
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.0306583
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.0305136
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.030372
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.030233
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.0301071
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.0299801
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.0298496
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.0297244
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.0296035
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.029488
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.0293789
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

Trening klas:  75%|███████▌  | 375/500 [43:39<14:38,  7.03s/klasa, klasa=class_375, F1_klasy=0.0000, F1_macro=0.6625, drzewa=10]




Trening klas:  75%|███████▌  | 376/500 [43:39<12:11,  5.90s/klasa, klasa=class_375, F1_klasy=0.0000, F1_macro=0.6625, drzewa=10]

[37]	valid_0's binary_logloss: 0.0292908
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.0291868
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.0290851
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.0289864
[1]	valid_0's binary_logloss: 0.0650562
[2]	valid_0's binary_logloss: 0.0603626
[3]	valid_0's binary_logloss: 0.0583579
[4]	valid_0's binary_logloss: 0.0562779
[5]	valid_0's binary_logloss: 0.0542479
[6]	valid_0's binary_logloss: 0.0525693
[7]	valid_0's binary_logloss: 0.0517285
[8]	valid_0's binary_logloss: 0.0505325
[9]	valid_0's binary_logloss: 0.0496861
[10]	valid_0's binary_logloss: 0.0489189
[11]	valid_0's binary_logloss: 0.0463066
[12]	valid_0's binary_logloss: 0.0457976
[13]	valid_0's binary_logloss: 0.0451045
[14]	valid_0's binary_logloss: 0.0446616
[15]	valid_0's binary_logloss: 0.0441499
[16]	valid_0's binary_logloss: 0.0434039
[17]	valid_0's binary_logloss: 0.0426059
[18]	valid_0's binary_logloss: 0.0421385
[19]	valid_0's binary_logloss: 0.0414025
[20]	valid_0's binary_logloss: 0.0408442
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0406016
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0401567
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.0397897
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0393952
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.0390919
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.0381939
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.0377369
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.0374087
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.0371755
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.0368296
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.0365401
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.0361661
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.0359193
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.0355636
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.0352004
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.0348997
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.0345591
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.0342689
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.0339734
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.0337433
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.0335899
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.0333232
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.033111
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.0328859
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.0326659
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.0323422
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.0322148
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.0320007
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.0317746
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.0315602
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.0313871
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.0312087
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.0310249
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.0307346
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.0306704
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.0303916
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.0301169
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.0300493
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.0300017
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.0297598
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.0297072
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.0295682
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.0294121
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.0293575
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.0291647
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.0291293
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.0289785
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.0288437
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.0286936
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.028526
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.0284134
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.0283719
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.0283513
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.0283429
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.0283212
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.0283079
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.0283999
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.0281652
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.0280631
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.028038
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.0278578
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.0276334
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.0274447
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.0272909
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.0271323
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.027095
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.0270127
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.026969
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.0270115
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.026877
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.0267838
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.0267033
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.0265883
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.0265277
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.0264594
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.0264324
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.0264579
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.0264512
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.0264443
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.0264461
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.0262851
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.0261996
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.0261231
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.0260605
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.0259969
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.0260144
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.0259724
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.0260367
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.0259168
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.0259929
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.0259191
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 0.0258785
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 0.0258417
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 0.025771
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 0.0257314
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[116]	valid_0's binary_logloss: 0.0256636
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[117]	valid_0's binary_logloss: 0.0255582
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[118]	valid_0's binary_logloss: 0.0254395
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[119]	valid_0's binary_logloss: 0.0253068
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[120]	valid_0's binary_logloss: 0.0251718
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[121]	valid_0's binary_logloss: 0.025149
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[122]	valid_0's binary_logloss: 0.0251291
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[123]	valid_0's binary_logloss: 0.0250654
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[124]	valid_0's binary_logloss: 0.0250563
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[125]	valid_0's binary_logloss: 0.0250906
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[126]	valid_0's binary_logloss: 0.0250179
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[127]	valid_0's binary_logloss: 0.0249942
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[128]	valid_0's binary_logloss: 0.0249484
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[129]	valid_0's binary_logloss: 0.0248481
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[130]	valid_0's binary_logloss: 0.0248201
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[131]	valid_0's binary_logloss: 0.0247772
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[132]	valid_0's binary_logloss: 0.0246667
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[133]	valid_0's binary_logloss: 0.0246235
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[134]	valid_0's binary_logloss: 0.0244919
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[135]	valid_0's binary_logloss: 0.0243882
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[136]	valid_0's binary_logloss: 0.0243086
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[137]	valid_0's binary_logloss: 0.0242876
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[138]	valid_0's binary_logloss: 0.0243121
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[139]	valid_0's binary_logloss: 0.0243086
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[140]	valid_0's binary_logloss: 0.0242108
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[141]	valid_0's binary_logloss: 0.0241813
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[142]	valid_0's binary_logloss: 0.0242361
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[143]	valid_0's binary_logloss: 0.02424
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[144]	valid_0's binary_logloss: 0.024255
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[145]	valid_0's binary_logloss: 0.0243268
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[146]	valid_0's binary_logloss: 0.0243143
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[147]	valid_0's binary_logloss: 0.0243157
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[148]	valid_0's binary_logloss: 0.0243227
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[149]	valid_0's binary_logloss: 0.024326
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[150]	valid_0's binary_logloss: 0.0242743
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[151]	valid_0's binary_logloss: 0.0242914
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[152]	valid_0's binary_logloss: 0.0242863
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[153]	valid_0's binary_logloss: 0.0243044
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[154]	valid_0's binary_logloss: 0.0243074
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[155]	valid_0's binary_logloss: 0.0242772
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[156]	valid_0's binary_logloss: 0.0242522
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[157]	valid_0's binary_logloss: 0.0241762
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[158]	valid_0's binary_logloss: 0.0241434
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[159]	valid_0's binary_logloss: 0.0240829
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[160]	valid_0's binary_logloss: 0.024014
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[161]	valid_0's binary_logloss: 0.0240226
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[162]	valid_0's binary_logloss: 0.0240271
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[163]	valid_0's binary_logloss: 0.0239927
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[164]	valid_0's binary_logloss: 0.0240267
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[165]	valid_0's binary_logloss: 0.0240146
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[166]	valid_0's binary_logloss: 0.0239883
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[167]	valid_0's binary_logloss: 0.0239475
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[168]	valid_0's binary_logloss: 0.0238866
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[169]	valid_0's binary_logloss: 0.0238266
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[170]	valid_0's binary_logloss: 0.0238049
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[171]	valid_0's binary_logloss: 0.0237665
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[172]	valid_0's binary_logloss: 0.0237328
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[173]	valid_0's binary_logloss: 0.0236789
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[174]	valid_0's binary_logloss: 0.0236481
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[175]	valid_0's binary_logloss: 0.02361
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[176]	valid_0's binary_logloss: 0.0235989
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[177]	valid_0's binary_logloss: 0.0236024
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[178]	valid_0's binary_logloss: 0.0235878
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[179]	valid_0's binary_logloss: 0.0235066
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[180]	valid_0's binary_logloss: 0.0234133
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[181]	valid_0's binary_logloss: 0.0234436

Trening klas:  75%|███████▌  | 376/500 [43:47<12:11,  5.90s/klasa, klasa=class_376, F1_klasy=0.6486, F1_macro=0.6625, drzewa=245]




Trening klas:  75%|███████▌  | 377/500 [43:47<13:14,  6.46s/klasa, klasa=class_376, F1_klasy=0.6486, F1_macro=0.6625, drzewa=245]

[275]	valid_0's binary_logloss: 0.0226605
[1]	valid_0's binary_logloss: 0.430186
[2]	valid_0's binary_logloss: 0.211115
[3]	valid_0's binary_logloss: 0.19759
[4]	valid_0's binary_logloss: 0.189934
[5]	valid_0's binary_logloss: 0.18232
[6]	valid_0's binary_logloss: 0.174175
[7]	valid_0's binary_logloss: 0.167992
[8]	valid_0's binary_logloss: 0.160889
[9]	valid_0's binary_logloss: 0.155667
[10]	valid_0's binary_logloss: 0.151166
[11]	valid_0's binary_logloss: 0.146807
[12]	valid_0's binary_logloss: 0.141926
[13]	valid_0's binary_logloss: 0.138424
[14]	valid_0's binary_logloss: 0.134926
[15]	valid_0's binary_logloss: 0.131067
[16]	valid_0's binary_logloss: 0.128321
[17]	valid_0's binary_logloss: 0.125017
[18]	valid_0's binary_logloss: 0.122133
[19]	valid_0's binary_logloss: 0.119462
[20]	valid_0's binary_logloss: 0.117007
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.114787
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.1119
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.109422
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.107588
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.105437
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.102987
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.100938
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.0986479
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.0965058
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.094733
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.0928058
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.0910968
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.0896714
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.0883047
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.0869148
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.085115
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.0830358
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.0815817
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.080095
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.0786611
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.0775425
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.0766663
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.0757848
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.0747915
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.073907
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.0727892
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.0718216
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.0708029
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.0697368
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.0686903
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.0679306
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.0670934
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.0663851
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.065548
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.0646963
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.064145
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.0628339
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.0620494
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.0609278
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.0601705
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.0595305
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.0589062
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.0583072
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.057671
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.0571616
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.0563673
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.0555639
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.0547998
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.0541485
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.0534731
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.0529116
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.0521081
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.0515079
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.0511117
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.0504383
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.05006
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.0493884
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.0490006
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.0482045
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.0477021
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.0473146
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.047201
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.0470547
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.0467518
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.0464895
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.0460326
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.0455469
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.0450848
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.0446628
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.0443339
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.0443043
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.0439867
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.0437623
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.0434355
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.0432564
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.0432299
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.0430651
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.0430016
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.0428759
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.0427539
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.0427414
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.0426398
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.0424739
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.0423499
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.042166
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.0420107
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.0418567
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.0416514
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.041403
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.0413193
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.0409753
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 0.0406983
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 0.0404724
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 0.0403846
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 0.0402579
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[116]	valid_0's binary_logloss: 0.0401492
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[117]	valid_0's binary_logloss: 0.0399882
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[118]	valid_0's binary_logloss: 0.0399872
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[119]	valid_0's binary_logloss: 0.0398761
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[120]	valid_0's binary_logloss: 0.0398467
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[121]	valid_0's binary_logloss: 0.039786
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[122]	valid_0's binary_logloss: 0.039519
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[123]	valid_0's binary_logloss: 0.0393415
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[124]	valid_0's binary_logloss: 0.0391214
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[125]	valid_0's binary_logloss: 0.0389552
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[126]	valid_0's binary_logloss: 0.0389451
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[127]	valid_0's binary_logloss: 0.0389634
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[128]	valid_0's binary_logloss: 0.0389784
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[129]	valid_0's binary_logloss: 0.0389606
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[130]	valid_0's binary_logloss: 0.0390167
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[131]	valid_0's binary_logloss: 0.0387896
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[132]	valid_0's binary_logloss: 0.0384863
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[133]	valid_0's binary_logloss: 0.0382884
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[134]	valid_0's binary_logloss: 0.0383146
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[135]	valid_0's binary_logloss: 0.0382487
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[136]	valid_0's binary_logloss: 0.0382021
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[137]	valid_0's binary_logloss: 0.0383629
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[138]	valid_0's binary_logloss: 0.0379367
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[139]	valid_0's binary_logloss: 0.0377686
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[140]	valid_0's binary_logloss: 0.0376369
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[141]	valid_0's binary_logloss: 0.037632
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[142]	valid_0's binary_logloss: 0.0376404
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[143]	valid_0's binary_logloss: 0.0376714
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[144]	valid_0's binary_logloss: 0.0377235
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[145]	valid_0's binary_logloss: 0.037705
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[146]	valid_0's binary_logloss: 0.0377369
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[147]	valid_0's binary_logloss: 0.0377806
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[148]	valid_0's binary_logloss: 0.0378507
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[149]	valid_0's binary_logloss: 0.037865
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[150]	valid_0's binary_logloss: 0.037885
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[151]	valid_0's binary_logloss: 0.0377862
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[152]	valid_0's binary_logloss: 0.0376727
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[153]	valid_0's binary_logloss: 0.0375611
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[154]	valid_0's binary_logloss: 0.0375181
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[155]	valid_0's binary_logloss: 0.0374594
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[156]	valid_0's binary_logloss: 0.0373394
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[157]	valid_0's binary_logloss: 0.0373569
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[158]	valid_0's binary_logloss: 0.0372985
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[159]	valid_0's binary_logloss: 0.0372715
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[160]	valid_0's binary_logloss: 0.0372663
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[161]	valid_0's binary_logloss: 0.0371129
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[162]	valid_0's binary_logloss: 0.0371024
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[163]	valid_0's binary_logloss: 0.0370401
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[164]	valid_0's binary_logloss: 0.0370014
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[165]	valid_0's binary_logloss: 0.0370059
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[166]	valid_0's binary_logloss: 0.0369744
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[167]	valid_0's binary_logloss: 0.0369531
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[168]	valid_0's binary_logloss: 0.0368838
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[169]	valid_0's binary_logloss: 0.0368402
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[170]	valid_0's binary_logloss: 0.0368637
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[171]	valid_0's binary_logloss: 0.0368719
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[172]	valid_0's binary_logloss: 0.0368037
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[173]	valid_0's binary_logloss: 0.036928
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[174]	valid_0's binary_logloss: 0.0368426
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[175]	valid_0's binary_logloss: 0.0368716
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[176]	valid_0's binary_logloss: 0.0366899
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[177]	valid_0's binary_logloss: 0.0365998
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[178]	valid_0's binary_logloss: 0.0364806
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[179]	valid_0's binary_logloss: 0.0364248
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[180]	valid_0's binary_logloss: 0.0362969
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[181]	valid_0's binary_logloss: 0.0362944
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[182]	valid_0's binary_logloss: 0.0363256
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[183]	valid_0's binary_logloss: 0.0362751
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[184]	valid_0's binary_logloss: 0.0361965
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

Trening klas:  75%|███████▌  | 377/500 [43:55<13:14,  6.46s/klasa, klasa=class_377, F1_klasy=0.6212, F1_macro=0.6624, drzewa=194]




Trening klas:  76%|███████▌  | 378/500 [43:55<14:15,  7.01s/klasa, klasa=class_377, F1_klasy=0.6212, F1_macro=0.6624, drzewa=194]

[220]	valid_0's binary_logloss: 0.0362759
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[221]	valid_0's binary_logloss: 0.0362637
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[222]	valid_0's binary_logloss: 0.0363464
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[223]	valid_0's binary_logloss: 0.0362614
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[224]	valid_0's binary_logloss: 0.0363346
[1]	valid_0's binary_logloss: 0.0236181
[2]	valid_0's binary_logloss: 0.0211476
[3]	valid_0's binary_logloss: 0.0195978
[4]	valid_0's binary_logloss: 0.0182466
[5]	valid_0's binary_logloss: 0.0169413
[6]	valid_0's binary_logloss: 0.0163845
[7]	valid_0's binary_logloss: 0.0154353
[8]	valid_0's binary_logloss: 0.0145388
[9]	valid_0's binary_logloss: 0.0138996
[10]	valid_0's binary_logloss: 0.0131441
[11]	valid_0's binary_logloss: 0.0124729
[12]	valid_0's binary_logloss: 0.0119283
[13]	valid_0's binary_logloss: 0.0114432
[14]	valid_0's binary_logloss: 0.0109871
[15]	valid_0's binary_logloss: 0.0105216
[16]	valid_0's binary_logloss: 0.0101747
[17]	valid_0's binary_logloss: 0.00975762
[18]	valid_0's binary_logloss: 0.00938746
[19]	valid_0's binary_logloss: 0.00904782
[20]	valid_0's binary_logloss: 0.00873934
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.00840744
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.00815514
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.00789231
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.00760417
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.00732115
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.00704835
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.00676483
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.00657154
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.00638205
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.00617065
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.005964
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.00575634
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.00562263
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.00543168
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.00525435
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.00509636
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.00498547
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.00487196
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.00474319
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.00460989
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.0044924
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.00437744
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.0042389
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.00414934
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.00403964
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.00393011
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.00385847
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.00374771
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.00364775
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.00355419
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.00347206
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.003389
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.00334058
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.00325884
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.00319809
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.00313175
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.00306369
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.00300468
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.00294873
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.00287753
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.00281386
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.00276016
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.00271656
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.0026743
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.00264522
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.00260623
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.002548
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.0025066
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.00247285
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.00241151
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.00236009
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.00230877
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.00227954
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.0022579
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.00224363
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.00224412
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.002231
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.0022127
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.00222597
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.00220434
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.00216751
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.0021277
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.0020771
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.0020472
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.00203384
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.0020189
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.00201379
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.00198168
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.001977
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.00197278
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.00196554
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.00194413
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.00193406
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.0019282
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.00191176
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.00189798
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.00188569
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.0018709
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.00186001
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.00183927
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.00184408
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.00183996
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.00184034
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.00183933
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.00184718
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.00183966
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.00183678
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.00183075
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.00183948
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.00184463
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.00184363
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 0.00185403
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 0.00186412
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 0.00187127
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 0.00187918
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[116]	valid_0's binary_logloss: 0.00186324
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[117]	valid_0's binary_logloss: 0.00185996
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[118]	valid_0's binary_logloss: 0.00186238
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[119]	valid_0's binary_logloss: 0.00184188
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[120]	valid_0's binary_logloss: 0.00185196
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[121]	valid_0's binary_logloss: 0.00183967
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[122]	valid_0's binary_logloss: 0.00183151
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[123]	valid_0's binary_logloss: 0.00183367
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[124]	valid_0's binary_logloss: 0.00184314
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[125]	valid_0's binary_logloss: 0.00185293
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[126]	valid_0's binary_logloss: 0.00184524
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[127]	valid_0's binary_logloss: 0.00184238
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[128]	valid_0's binary_logloss: 0.00185803
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[129]	valid_0's binary_logloss: 0.00185807
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[130]	valid_0's binary_logloss: 0.00188368
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[131]	valid_0's binary_logloss: 0.00188808
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[132]	valid_0's binary_logloss: 0.00189215
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[133]	valid_0's binary_logloss: 0.00189532
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[134]	valid_0's binary_logloss: 0.00190246
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[135]	valid_0's binary_logloss: 0.00190848

Trening klas:  76%|███████▌  | 378/500 [44:03<14:15,  7.01s/klasa, klasa=class_378, F1_klasy=0.6667, F1_macro=0.6624, drzewa=108]




Trening klas:  76%|███████▌  | 379/500 [44:03<14:14,  7.06s/klasa, klasa=class_378, F1_klasy=0.6667, F1_macro=0.6624, drzewa=108]

[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[136]	valid_0's binary_logloss: 0.00190909
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[137]	valid_0's binary_logloss: 0.00192609
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[138]	valid_0's binary_logloss: 0.00194122
[1]	valid_0's binary_logloss: 0.262956
[2]	valid_0's binary_logloss: 0.131686
[3]	valid_0's binary_logloss: 0.126314
[4]	valid_0's binary_logloss: 0.113954
[5]	valid_0's binary_logloss: 0.10798
[6]	valid_0's binary_logloss: 0.105675
[7]	valid_0's binary_logloss: 0.103303
[8]	valid_0's binary_logloss: 0.0992199
[9]	valid_0's binary_logloss: 0.0964338
[10]	valid_0's binary_logloss: 0.0941462
[11]	valid_0's binary_logloss: 0.0906834
[12]	valid_0's binary_logloss: 0.0868916
[13]	valid_0's binary_logloss: 0.0840298
[14]	valid_0's binary_logloss: 0.0823201
[15]	valid_0's binary_logloss: 0.080096
[16]	valid_0's binary_logloss: 0.0782212
[17]	valid_0's binary_logloss: 0.0759511
[18]	valid_0's binary_logloss: 0.0743102
[19]	valid_0's binary_logloss: 0.0720295
[20]	valid_0's binary_logloss: 0.0705787
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0690129
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0674133
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.0658955
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0644013
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.0630181
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.0614535
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.0600091
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.0589694
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.0576508
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.0562392
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.0552031
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.0539216
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.0534169
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.0527139
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.0523099
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.0514422
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.0506353
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.0499679
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.0494386
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.0486129
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.0477092
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.0467784
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.0460326
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.0452526
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.0445741
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.043895
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.0433296
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.0426055
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.0419173
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.0414633
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.0408192
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.0402402
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.0395959
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.0389175
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.0382496
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.0377504
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.0370441
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.0365478
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.0360616
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.0355639
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.0350582
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.0346082
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.0341707
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.0335738
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.032985
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.0324501
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.0319501
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.0314661
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.0309851
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.0305483
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.0301154
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.0296774
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.0292682
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.0287463
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.0283484
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.0278698
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.027475
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.0271112
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.0267255
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.0263903
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.0260805
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.0258929
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.0255411
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.025263
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.0249734
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.024674
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.0245043
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.0241886
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.0238868
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.023646
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.0233443
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.0231518
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.0229643
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.0227286
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.0224935
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.0222085
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.0220922
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.0219444
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.0217141
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.0214797
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.0212917
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.0210758
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.0208165
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.0205941
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.0204266
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.020295
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.02024
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.0201458
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.0200571
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.0199515
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.0197391
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 0.0195241
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 0.019347
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 0.0191409
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 0.018967
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[116]	valid_0's binary_logloss: 0.0188694
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[117]	valid_0's binary_logloss: 0.0187704
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[118]	valid_0's binary_logloss: 0.0187218
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[119]	valid_0's binary_logloss: 0.0186716
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[120]	valid_0's binary_logloss: 0.0185686
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[121]	valid_0's binary_logloss: 0.0185494
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[122]	valid_0's binary_logloss: 0.018477
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[123]	valid_0's binary_logloss: 0.0183888
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[124]	valid_0's binary_logloss: 0.0183062
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[125]	valid_0's binary_logloss: 0.018276
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[126]	valid_0's binary_logloss: 0.0182132
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[127]	valid_0's binary_logloss: 0.0181295
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[128]	valid_0's binary_logloss: 0.0180399
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[129]	valid_0's binary_logloss: 0.0179724
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[130]	valid_0's binary_logloss: 0.0179156
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[131]	valid_0's binary_logloss: 0.0178093
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[132]	valid_0's binary_logloss: 0.0178775
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[133]	valid_0's binary_logloss: 0.0177921
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[134]	valid_0's binary_logloss: 0.0178444
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[135]	valid_0's binary_logloss: 0.0177409
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[136]	valid_0's binary_logloss: 0.0176092
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[137]	valid_0's binary_logloss: 0.0174746
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[138]	valid_0's binary_logloss: 0.0173494
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[139]	valid_0's binary_logloss: 0.0172434
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[140]	valid_0's binary_logloss: 0.0170958
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[141]	valid_0's binary_logloss: 0.0170836
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[142]	valid_0's binary_logloss: 0.0170699
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[143]	valid_0's binary_logloss: 0.0170421
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[144]	valid_0's binary_logloss: 0.0170397
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[145]	valid_0's binary_logloss: 0.0169861
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[146]	valid_0's binary_logloss: 0.0169706
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[147]	valid_0's binary_logloss: 0.0169617
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[148]	valid_0's binary_logloss: 0.0169355
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[149]	valid_0's binary_logloss: 0.0168817
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[150]	valid_0's binary_logloss: 0.0167615
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[151]	valid_0's binary_logloss: 0.0166516
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[152]	valid_0's binary_logloss: 0.0166122
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[153]	valid_0's binary_logloss: 0.0165719
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[154]	valid_0's binary_logloss: 0.0164856
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[155]	valid_0's binary_logloss: 0.0164828
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[156]	valid_0's binary_logloss: 0.0164181
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[157]	valid_0's binary_logloss: 0.0163941
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[158]	valid_0's binary_logloss: 0.0163882
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[159]	valid_0's binary_logloss: 0.0163348
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[160]	valid_0's binary_logloss: 0.0162835
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[161]	valid_0's binary_logloss: 0.0162736
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[162]	valid_0's binary_logloss: 0.0162606
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[163]	valid_0's binary_logloss: 0.0162494
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[164]	valid_0's binary_logloss: 0.0161971
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[165]	valid_0's binary_logloss: 0.01615
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[166]	valid_0's binary_logloss: 0.0161509
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[167]	valid_0's binary_logloss: 0.0161868
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[168]	valid_0's binary_logloss: 0.0162328
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[169]	valid_0's binary_logloss: 0.0162183
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[170]	valid_0's binary_logloss: 0.0161883
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[171]	valid_0's binary_logloss: 0.0161038
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[172]	valid_0's binary_logloss: 0.0160809
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[173]	valid_0's binary_logloss: 0.0160247
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[174]	valid_0's binary_logloss: 0.0159843
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[175]	valid_0's binary_logloss: 0.0159135
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[176]	valid_0's binary_logloss: 0.0158836
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[177]	valid_0's binary_logloss: 0.0158537
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[178]	valid_0's binary_logloss: 0.0158463
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[179]	valid_0's binary_logloss: 0.0158144
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[180]	valid_0's binary_logloss: 0.0158098
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[181]	valid_0's binary_logloss: 0.015869
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

Trening klas:  76%|███████▌  | 379/500 [44:11<14:14,  7.06s/klasa, klasa=class_379, F1_klasy=0.7812, F1_macro=0.6627, drzewa=284]




Trening klas:  76%|███████▌  | 380/500 [44:11<14:39,  7.33s/klasa, klasa=class_379, F1_klasy=0.7812, F1_macro=0.6627, drzewa=284]

[299]	valid_0's binary_logloss: 0.0153432
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[300]	valid_0's binary_logloss: 0.0153627
[1]	valid_0's binary_logloss: 0.105186
[2]	valid_0's binary_logloss: 0.0714626
[3]	valid_0's binary_logloss: 0.0647181
[4]	valid_0's binary_logloss: 0.0604999
[5]	valid_0's binary_logloss: 0.0571817
[6]	valid_0's binary_logloss: 0.133716
[7]	valid_0's binary_logloss: 0.100302
[8]	valid_0's binary_logloss: 0.0932025
[9]	valid_0's binary_logloss: 0.0873197
[10]	valid_0's binary_logloss: 0.0824245
[11]	valid_0's binary_logloss: 0.0799326
[12]	valid_0's binary_logloss: 0.0776617
[13]	valid_0's binary_logloss: 0.0757038
[14]	valid_0's binary_logloss: 0.0735216
[15]	valid_0's binary_logloss: 0.0717424
[16]	valid_0's binary_logloss: 0.070144
[17]	valid_0's binary_logloss: 0.06811
[18]	valid_0's binary_logloss: 0.0650242
[19]	valid_0's binary_logloss: 0.0625295
[20]	valid_0's binary_logloss: 0.0608431
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0594408
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0581195
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.0567329
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.055511
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.0543154
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.052527
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.0509146
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.0493864
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.0480945
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.0467731
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.0457578
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.0451054
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.0444711
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.043907
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.0433392
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.0427556
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.0421728
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.0416001
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.0407203
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.0399352
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.0390504
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.0381535
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.0372638
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.036378
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.0355244
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.0352744
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.0347878
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.0341314
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.0336075
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.0331985
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.0326022
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.0322358
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.0317062
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.0311471
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.0306547
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.0301218
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.0296817
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.0291626
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.0288476
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.0284233
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.0278623
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.0273349
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.026813
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.0262702
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.0258348
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.0254579
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.0250954
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.024731
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.0246821
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.0245119
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.0240837
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.0237532
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.0233675
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.0231773
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.0228753
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.0225367
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.0223726
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.022049
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.0216887
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.0213737
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.0210676
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.0208162
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.0205472
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.0203147
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.0201243
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.019902
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.0198806
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.0196739
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.0194495
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.0191928
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.0190637
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.018868
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.018711
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.0186035
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.0185111
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.0185504
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.0185806
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.018574
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.0183879
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.0183285
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.0181007
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.0178559
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.0178609
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.0176327
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.0175404
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.0174485
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.0173751
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.017259
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.0172908
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.0171683
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.0171145
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 0.0170087
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 0.0169476
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 0.0167756
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 0.0166339
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[116]	valid_0's binary_logloss: 0.0166762
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[117]	valid_0's binary_logloss: 0.0166413
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[118]	valid_0's binary_logloss: 0.0165812
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[119]	valid_0's binary_logloss: 0.0165599
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[120]	valid_0's binary_logloss: 0.0164544
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[121]	valid_0's binary_logloss: 0.0165028
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[122]	valid_0's binary_logloss: 0.01648
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[123]	valid_0's binary_logloss: 0.0164425
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[124]	valid_0's binary_logloss: 0.0164214
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[125]	valid_0's binary_logloss: 0.0163495
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[126]	valid_0's binary_logloss: 0.0162984
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[127]	valid_0's binary_logloss: 0.016186
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[128]	valid_0's binary_logloss: 0.0160921
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[129]	valid_0's binary_logloss: 0.0160202
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[130]	valid_0's binary_logloss: 0.0159773
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[131]	valid_0's binary_logloss: 0.0158698
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[132]	valid_0's binary_logloss: 0.0158246
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[133]	valid_0's binary_logloss: 0.0158252
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[134]	valid_0's binary_logloss: 0.0157818
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[135]	valid_0's binary_logloss: 0.0157434
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[136]	valid_0's binary_logloss: 0.0158324
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[137]	valid_0's binary_logloss: 0.0159194
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[138]	valid_0's binary_logloss: 0.0159525
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[139]	valid_0's binary_logloss: 0.0159818
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[140]	valid_0's binary_logloss: 0.0160567
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[141]	valid_0's binary_logloss: 0.0160342
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[142]	valid_0's binary_logloss: 0.0159828
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[143]	valid_0's binary_logloss: 0.0159517
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[144]	valid_0's binary_logloss: 0.0159446
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[145]	valid_0's binary_logloss: 0.01587
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[146]	valid_0's binary_logloss: 0.0158361
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[147]	valid_0's binary_logloss: 0.0157489
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[148]	valid_0's binary_logloss: 0.0157137
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[149]	valid_0's binary_logloss: 0.0156732
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[150]	valid_0's binary_logloss: 0.0156362
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[151]	valid_0's binary_logloss: 0.0156029
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[152]	valid_0's binary_logloss: 0.0154921
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[153]	valid_0's binary_logloss: 0.0154277
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[154]	valid_0's binary_logloss: 0.0153449
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[155]	valid_0's binary_logloss: 0.0152626
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[156]	valid_0's binary_logloss: 0.0152354
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[157]	valid_0's binary_logloss: 0.0152214
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[158]	valid_0's binary_logloss: 0.0151959
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[159]	valid_0's binary_logloss: 0.0151795
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[160]	valid_0's binary_logloss: 0.0151511
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[161]	valid_0's binary_logloss: 0.0151533
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[162]	valid_0's binary_logloss: 0.0151608
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[163]	valid_0's binary_logloss: 0.0151612
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[164]	valid_0's binary_logloss: 0.0151556
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[165]	valid_0's binary_logloss: 0.0151536
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[166]	valid_0's binary_logloss: 0.0151474
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[167]	valid_0's binary_logloss: 0.0150412
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[168]	valid_0's binary_logloss: 0.0149365
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[169]	valid_0's binary_logloss: 0.0149474
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[170]	valid_0's binary_logloss: 0.0148242
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[171]	valid_0's binary_logloss: 0.0148113
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[172]	valid_0's binary_logloss: 0.0148541
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[173]	valid_0's binary_logloss: 0.0148881
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[174]	valid_0's binary_logloss: 0.0149024
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[175]	valid_0's binary_logloss: 0.0149368
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[176]	valid_0's binary_logloss: 0.0148987
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[177]	valid_0's binary_logloss: 0.0148808
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[178]	valid_0's binary_logloss: 0.0148523
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[179]	valid_0's binary_logloss: 0.0148194
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[180]	valid_0's binary_logloss: 0.0148364
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[181]	valid_0's binary_logloss: 0.0147828
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[182]	valid_0's binary_logloss: 0.0147132
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[183]	valid_0's binary_logloss: 0.0146633

Trening klas:  76%|███████▌  | 380/500 [44:21<14:39,  7.33s/klasa, klasa=class_380, F1_klasy=0.6076, F1_macro=0.6626, drzewa=243]




Trening klas:  76%|███████▌  | 381/500 [44:21<16:28,  8.31s/klasa, klasa=class_380, F1_klasy=0.6076, F1_macro=0.6626, drzewa=243]

[273]	valid_0's binary_logloss: 0.0135312
[1]	valid_0's binary_logloss: 0.0248654
[2]	valid_0's binary_logloss: 0.0226616
[3]	valid_0's binary_logloss: 0.0206859
[4]	valid_0's binary_logloss: 0.0194586
[5]	valid_0's binary_logloss: 0.0184016
[6]	valid_0's binary_logloss: 0.0175932
[7]	valid_0's binary_logloss: 0.0168446
[8]	valid_0's binary_logloss: 0.0162799
[9]	valid_0's binary_logloss: 0.0157267
[10]	valid_0's binary_logloss: 0.0152315
[11]	valid_0's binary_logloss: 0.0146255
[12]	valid_0's binary_logloss: 0.014155
[13]	valid_0's binary_logloss: 0.0136925
[14]	valid_0's binary_logloss: 0.01329
[15]	valid_0's binary_logloss: 0.0128702
[16]	valid_0's binary_logloss: 0.0124657
[17]	valid_0's binary_logloss: 0.012131
[18]	valid_0's binary_logloss: 0.0117892
[19]	valid_0's binary_logloss: 0.0114896
[20]	valid_0's binary_logloss: 0.0111462
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0108481
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0105658
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.0103051
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0100595
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.00983143
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.00962596
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.00942035
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.00922283
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.00903533
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.00888917
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.0087393
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.00863877
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.00850306
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.00838098
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.00824765
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.00810082
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.00796537
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.00785366
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.00773371
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.00761561
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.0075382
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.00743361
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.00736289
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.00731803
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.00723867
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.0071837
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.00711648
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.00709092
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.00705821
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.00702566
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.00698769
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.0069251
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.00688699
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.00684976
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.00681804
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.00678873
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.00676937
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.0067556
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.00674247
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.00670895
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.00667632
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.00666079
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.00665271
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.00662655
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.00659807
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.00657497
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.0065568
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.00654457
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.00653802
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.00653473
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.00652668
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.0065237
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.00653076
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.00650831
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.0065239
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.00653289
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.00654226
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.00655895
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.00657496
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.00659246
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.00661143
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.00662973
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.00664712
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.00667957
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.00671135
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.00672246
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.00672548
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.00671726
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.00672117
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.00672909
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.00674391
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.00676462
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.00675978
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.00677676
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.0067715
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.00680524
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.00680276
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.00680188
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.00680145
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

Trening klas:  76%|███████▌  | 381/500 [44:25<16:28,  8.31s/klasa, klasa=class_381, F1_klasy=0.5000, F1_macro=0.6622, drzewa=74]




Trening klas:  76%|███████▋  | 382/500 [44:25<13:49,  7.03s/klasa, klasa=class_381, F1_klasy=0.5000, F1_macro=0.6622, drzewa=74]

[100]	valid_0's binary_logloss: 0.00684159
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.0068582
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.00689313
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.00688389
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.00688325
[1]	valid_0's binary_logloss: 0.258966
[2]	valid_0's binary_logloss: 0.183422
[3]	valid_0's binary_logloss: 0.1683
[4]	valid_0's binary_logloss: 0.159679
[5]	valid_0's binary_logloss: 0.151331
[6]	valid_0's binary_logloss: 0.154559
[7]	valid_0's binary_logloss: 0.150026
[8]	valid_0's binary_logloss: 0.146286
[9]	valid_0's binary_logloss: 0.142535
[10]	valid_0's binary_logloss: 0.138769
[11]	valid_0's binary_logloss: 0.135834
[12]	valid_0's binary_logloss: 0.132504
[13]	valid_0's binary_logloss: 0.129449
[14]	valid_0's binary_logloss: 0.126655
[15]	valid_0's binary_logloss: 0.12405
[16]	valid_0's binary_logloss: 0.121963
[17]	valid_0's binary_logloss: 0.120252
[18]	valid_0's binary_logloss: 0.118045
[19]	valid_0's binary_logloss: 0.115927
[20]	valid_0's binary_logloss: 0.114059
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.112187
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.110247
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.108447
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.106692
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.105156
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.103692
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.102164
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.101058
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.0998736
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.0987791
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.0974678
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.0960185
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.0945424
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.0935182
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.0924546
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.0914996
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.0904265
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.0896325
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.0888254
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.0879047
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.0870789
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.0861057
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.0852277
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.0844998
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.0837951
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.0830985
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.0826155
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.0818808
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.081189
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.0805644
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.079944
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.0793382
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.078676
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.0780333
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.077351
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.0769017
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.0764233
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.0758488
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.07527
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.0747711
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.074202
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.073808
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.0733324
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.0728579
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.0723958
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.0720311
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.0716114
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.0711418
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.0707683
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.0704422
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.0700625
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.0697114
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.0693584
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.0689673
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.0686697
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.0684528
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.0683191
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.0681249
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.0679254
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.0678033
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.067501
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.0673001
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.0670633
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.0667966
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.0665999
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.0664116
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.066173
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.0658996
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.0656803
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.0654924
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.0654595
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.0653789
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.0652973
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.0651417
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.065026
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.0649617
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.0648565
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.0647714
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.0647169
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.0645747
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.0645338
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.0644022
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.064258
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.064181
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.0641277
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.0639908
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.0639176
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.0637906
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.0637214
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.0636777
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.063451
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 0.0633371
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 0.0632524
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 0.0631823
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 0.0631148
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[116]	valid_0's binary_logloss: 0.0629886
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[117]	valid_0's binary_logloss: 0.0628785
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[118]	valid_0's binary_logloss: 0.0627155
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[119]	valid_0's binary_logloss: 0.0626163
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[120]	valid_0's binary_logloss: 0.0625586
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[121]	valid_0's binary_logloss: 0.0625966
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[122]	valid_0's binary_logloss: 0.0626269
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[123]	valid_0's binary_logloss: 0.0626006
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[124]	valid_0's binary_logloss: 0.0625774
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[125]	valid_0's binary_logloss: 0.0625799
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[126]	valid_0's binary_logloss: 0.0625321
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[127]	valid_0's binary_logloss: 0.0625111
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[128]	valid_0's binary_logloss: 0.0625137
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[129]	valid_0's binary_logloss: 0.0624872
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[130]	valid_0's binary_logloss: 0.0624627
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[131]	valid_0's binary_logloss: 0.0624383
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[132]	valid_0's binary_logloss: 0.0624541
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[133]	valid_0's binary_logloss: 0.0624198
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[134]	valid_0's binary_logloss: 0.0623549
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[135]	valid_0's binary_logloss: 0.0623531
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[136]	valid_0's binary_logloss: 0.0621472
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[137]	valid_0's binary_logloss: 0.0622267
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[138]	valid_0's binary_logloss: 0.0621494
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[139]	valid_0's binary_logloss: 0.0622018
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[140]	valid_0's binary_logloss: 0.0621299
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[141]	valid_0's binary_logloss: 0.0622072
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[142]	valid_0's binary_logloss: 0.0621595
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[143]	valid_0's binary_logloss: 0.0622204
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[144]	valid_0's binary_logloss: 0.0622092
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[145]	valid_0's binary_logloss: 0.0622389
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[146]	valid_0's binary_logloss: 0.0623145
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[147]	valid_0's binary_logloss: 0.0622595
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[148]	valid_0's binary_logloss: 0.0623274
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[149]	valid_0's binary_logloss: 0.0623582
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[150]	valid_0's binary_logloss: 0.0623481
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[151]	valid_0's binary_logloss: 0.0624021
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[152]	valid_0's binary_logloss: 0.0624178
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[153]	valid_0's binary_logloss: 0.0623926
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[154]	valid_0's binary_logloss: 0.0624306
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[155]	valid_0's binary_logloss: 0.0624089
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[156]	valid_0's binary_logloss: 0.0622803
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[157]	valid_0's binary_logloss: 0.0621782
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[158]	valid_0's binary_logloss: 0.0621092
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[159]	valid_0's binary_logloss: 0.0620763
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[160]	valid_0's binary_logloss: 0.0621065
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[161]	valid_0's binary_logloss: 0.0620856
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[162]	valid_0's binary_logloss: 0.0620875
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[163]	valid_0's binary_logloss: 0.0621597
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[164]	valid_0's binary_logloss: 0.0622224
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[165]	valid_0's binary_logloss: 0.0622529
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[166]	valid_0's binary_logloss: 0.0622864
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[167]	valid_0's binary_logloss: 0.0622881
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[168]	valid_0's binary_logloss: 0.0623146
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[169]	valid_0's binary_logloss: 0.0623488
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[170]	valid_0's binary_logloss: 0.062389
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[171]	valid_0's binary_logloss: 0.0623554
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[172]	valid_0's binary_logloss: 0.0622571
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[173]	valid_0's binary_logloss: 0.0622282
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[174]	valid_0's binary_logloss: 0.0622803
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[175]	valid_0's binary_logloss: 0.0623084
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[176]	valid_0's binary_logloss: 0.0623049
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[177]	valid_0's binary_logloss: 0.0622517
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[178]	valid_0's binary_logloss: 0.0622876
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[179]	valid_0's binary_logloss: 0.0623331
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[180]	valid_0's binary_logloss: 0.0623711
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

Trening klas:  76%|███████▋  | 382/500 [44:35<13:49,  7.03s/klasa, klasa=class_382, F1_klasy=0.3077, F1_macro=0.6612, drzewa=159]




Trening klas:  77%|███████▋  | 383/500 [44:35<15:27,  7.93s/klasa, klasa=class_382, F1_klasy=0.3077, F1_macro=0.6612, drzewa=159]

[187]	valid_0's binary_logloss: 0.062221
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[188]	valid_0's binary_logloss: 0.0622202
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[189]	valid_0's binary_logloss: 0.0621972
[1]	valid_0's binary_logloss: 0.0620586
[2]	valid_0's binary_logloss: 0.0574272
[3]	valid_0's binary_logloss: 0.0528225
[4]	valid_0's binary_logloss: 0.0491164
[5]	valid_0's binary_logloss: 0.0465006
[6]	valid_0's binary_logloss: 0.0476864
[7]	valid_0's binary_logloss: 0.0458975
[8]	valid_0's binary_logloss: 0.0442097
[9]	valid_0's binary_logloss: 0.0425453
[10]	valid_0's binary_logloss: 0.0411377
[11]	valid_0's binary_logloss: 0.0420605
[12]	valid_0's binary_logloss: 0.0407625
[13]	valid_0's binary_logloss: 0.0395472
[14]	valid_0's binary_logloss: 0.0384586
[15]	valid_0's binary_logloss: 0.0373342
[16]	valid_0's binary_logloss: 0.0362563
[17]	valid_0's binary_logloss: 0.0353001
[18]	valid_0's binary_logloss: 0.0345166
[19]	valid_0's binary_logloss: 0.0337705
[20]	valid_0's binary_logloss: 0.0331122
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0322797
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0315012
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.0307332
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0300322
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.0293755
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.0287972
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.0282365
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.027605
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.0271049
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.0265041
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.0260581
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.025606
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.0251975
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.0247817
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.0244024
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.0240404
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.0236678
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.0233762
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.022999
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.0227299
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.0223817
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.0220373
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.0217689
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.0214988
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.0212531
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.0210567
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.0208038
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.0205583
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.020343
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.0201189
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.0199866
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.0198583
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.0197854
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.0197137
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.0195475
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.0194155
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.0192384
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.0190452
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.0188871
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.0187577
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.018604
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.0184907
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.0183966
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.0182891
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.0181848
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.0180488
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.0179273
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.0178144
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.0177165
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.0176661
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.0175911
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.0175126
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.0174429
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.017378
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.0173119
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.0172196
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.0170995
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.0169988
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.0169087
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.016899
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.0168706
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.0168072
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.0167344
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.0166749
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.01663
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.0165894
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.0165304
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.0164629
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.016454
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.0164217
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.0164004
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.0164008
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.0163842
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.0163639
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.0163448
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.0163345
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.0162674
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.0162503
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.0162306
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.0161542
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.0161486
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.0161551
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.0161251
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.0161245
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.0161037
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.0160755
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.0161046
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.0161285
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.0161538
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.0161749
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.016186
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 0.0162158
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 0.0162325
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 0.016257
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 0.0162807
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[116]	valid_0's binary_logloss: 0.0163005
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[117]	valid_0's binary_logloss: 0.0163307
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[118]	valid_0's binary_logloss: 0.0163434
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[119]	valid_0's binary_logloss: 0.0163832
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[120]	valid_0's binary_logloss: 0.016425
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[121]	valid_0's binary_logloss: 0.0163892
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[122]	valid_0's binary_logloss: 0.0163421
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[123]	valid_0's binary_logloss: 0.0163423
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[124]	valid_0's binary_logloss: 0.0162966
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[125]	valid_0's binary_logloss: 0.0162829
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[126]	valid_0's binary_logloss: 0.0163062
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[127]	valid_0's binary_logloss: 0.0163364
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[128]	valid_0's binary_logloss: 0.0163559
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[129]	valid_0's binary_logloss: 0.0163474
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[130]	valid_0's binary_logloss: 0.0163567
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[131]	valid_0's binary_logloss: 0.0163446
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[132]	valid_0's binary_logloss: 0.0163304
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[133]	valid_0's binary_logloss: 0.0163516
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

Trening klas:  77%|███████▋  | 383/500 [44:42<15:27,  7.93s/klasa, klasa=class_383, F1_klasy=0.2857, F1_macro=0.6603, drzewa=106]




Trening klas:  77%|███████▋  | 384/500 [44:42<14:53,  7.70s/klasa, klasa=class_383, F1_klasy=0.2857, F1_macro=0.6603, drzewa=106]

[134]	valid_0's binary_logloss: 0.0163498
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[135]	valid_0's binary_logloss: 0.016339
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[136]	valid_0's binary_logloss: 0.01637
[1]	valid_0's binary_logloss: 0.0791945
[2]	valid_0's binary_logloss: 0.0681863
[3]	valid_0's binary_logloss: 0.0602984
[4]	valid_0's binary_logloss: 0.0567173
[5]	valid_0's binary_logloss: 0.0529187
[6]	valid_0's binary_logloss: 0.0497091
[7]	valid_0's binary_logloss: 0.0469736
[8]	valid_0's binary_logloss: 0.0445485
[9]	valid_0's binary_logloss: 0.0420735
[10]	valid_0's binary_logloss: 0.0400954
[11]	valid_0's binary_logloss: 0.0382569
[12]	valid_0's binary_logloss: 0.0363074
[13]	valid_0's binary_logloss: 0.0348867
[14]	valid_0's binary_logloss: 0.0332371
[15]	valid_0's binary_logloss: 0.0319514
[16]	valid_0's binary_logloss: 0.0308376
[17]	valid_0's binary_logloss: 0.0295363
[18]	valid_0's binary_logloss: 0.0283229
[19]	valid_0's binary_logloss: 0.0272414
[20]	valid_0's binary_logloss: 0.0260716
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0251631
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0242827
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.0234918
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0225846
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.0218231
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.0211514
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.0203678
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.0196798
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.0190393
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.0184182
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.0178076
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.0172421
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.0166902
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.0162104
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.0157131
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.0152119
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.0147419
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.0143729
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.0139699
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.0135457
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.0132594
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.0129447
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.0126475
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.0123525
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.0120608
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.0117613
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.0114709
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.0113113
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.011052
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.0108358
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.0106229
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.0103694
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.0100806
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.00989271
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.00964382
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.00946847
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.00926484
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.00908216
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.00887717
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.00869981
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.00846928
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.00831431
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.00815324
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.00795838
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.00777532
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.00763065
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.00742954
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.00734246
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.00724886
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.00719136
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.00706434
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.00696434
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.00684068
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.0067062
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.00664823
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.0065481
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.00645593
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.00633774
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.00621013
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.00609861
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.00599219
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.00591573
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.00581579
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.00571737
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.00567586
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.00557501
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.00547417
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.00541299
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.00533802
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.00525998
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.00523831
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.00525628
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.00526501
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.00520225
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.00522733
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.00525104
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.00528138
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.00531874
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.00529045
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.00527587
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.00520201
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.00513569
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.00510198
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.00505015
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.00500353
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.00495135
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.0048778
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.00484763
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.00480609
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.004752
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.00470379
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 0.00464509
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 0.00463542
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 0.00460771
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 0.00457613
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[116]	valid_0's binary_logloss: 0.00454787
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[117]	valid_0's binary_logloss: 0.00450451
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[118]	valid_0's binary_logloss: 0.00446187
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[119]	valid_0's binary_logloss: 0.00441514
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[120]	valid_0's binary_logloss: 0.00438182
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[121]	valid_0's binary_logloss: 0.00435826
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[122]	valid_0's binary_logloss: 0.00432564
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[123]	valid_0's binary_logloss: 0.00430035
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[124]	valid_0's binary_logloss: 0.00427476
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[125]	valid_0's binary_logloss: 0.00425475
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[126]	valid_0's binary_logloss: 0.00424215
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[127]	valid_0's binary_logloss: 0.00423731
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[128]	valid_0's binary_logloss: 0.00422299
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[129]	valid_0's binary_logloss: 0.00421845
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[130]	valid_0's binary_logloss: 0.0042332
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[131]	valid_0's binary_logloss: 0.00423778
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[132]	valid_0's binary_logloss: 0.00422291
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[133]	valid_0's binary_logloss: 0.00422201
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[134]	valid_0's binary_logloss: 0.00422849
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[135]	valid_0's binary_logloss: 0.0042044
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[136]	valid_0's binary_logloss: 0.00419936
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[137]	valid_0's binary_logloss: 0.00419624
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[138]	valid_0's binary_logloss: 0.00412684
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[139]	valid_0's binary_logloss: 0.00414194
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[140]	valid_0's binary_logloss: 0.00414573
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[141]	valid_0's binary_logloss: 0.00413046
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[142]	valid_0's binary_logloss: 0.00407848
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[143]	valid_0's binary_logloss: 0.00406782
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[144]	valid_0's binary_logloss: 0.00404795
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[145]	valid_0's binary_logloss: 0.00402219
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[146]	valid_0's binary_logloss: 0.00398478
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[147]	valid_0's binary_logloss: 0.00400081
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[148]	valid_0's binary_logloss: 0.00399167
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[149]	valid_0's binary_logloss: 0.00402598
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[150]	valid_0's binary_logloss: 0.00403737
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[151]	valid_0's binary_logloss: 0.00395854
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[152]	valid_0's binary_logloss: 0.00391099
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[153]	valid_0's binary_logloss: 0.00385882
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[154]	valid_0's binary_logloss: 0.00379629
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[155]	valid_0's binary_logloss: 0.00374424
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[156]	valid_0's binary_logloss: 0.00376474
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[157]	valid_0's binary_logloss: 0.00380119
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[158]	valid_0's binary_logloss: 0.00381532
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[159]	valid_0's binary_logloss: 0.00383659
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[160]	valid_0's binary_logloss: 0.00385656
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[161]	valid_0's binary_logloss: 0.00383885
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[162]	valid_0's binary_logloss: 0.00382142
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[163]	valid_0's binary_logloss: 0.00379792
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[164]	valid_0's binary_logloss: 0.00376116
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[165]	valid_0's binary_logloss: 0.00373886
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[166]	valid_0's binary_logloss: 0.00371139
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[167]	valid_0's binary_logloss: 0.00370584
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[168]	valid_0's binary_logloss: 0.00371453
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[169]	valid_0's binary_logloss: 0.00370914
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[170]	valid_0's binary_logloss: 0.00371973
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[171]	valid_0's binary_logloss: 0.00372442
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[172]	valid_0's binary_logloss: 0.00373584
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[173]	valid_0's binary_logloss: 0.00374423
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[174]	valid_0's binary_logloss: 0.00376043
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[175]	valid_0's binary_logloss: 0.00377278
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[176]	valid_0's binary_logloss: 0.00379513
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[177]	valid_0's binary_logloss: 0.0037901
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[178]	valid_0's binary_logloss: 0.0037965
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[179]	valid_0's binary_logloss: 0.0038147
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[180]	valid_0's binary_logloss: 0.00382167
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[181]	valid_0's binary_logloss: 0.00382399

Trening klas:  77%|███████▋  | 384/500 [44:52<14:53,  7.70s/klasa, klasa=class_384, F1_klasy=0.0000, F1_macro=0.6585, drzewa=167]




Trening klas:  77%|███████▋  | 385/500 [44:52<15:57,  8.33s/klasa, klasa=class_384, F1_klasy=0.0000, F1_macro=0.6585, drzewa=167]

[195]	valid_0's binary_logloss: 0.00379587
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[196]	valid_0's binary_logloss: 0.00381317
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[197]	valid_0's binary_logloss: 0.00379476
[1]	valid_0's binary_logloss: 0.374733
[2]	valid_0's binary_logloss: 0.351985
[3]	valid_0's binary_logloss: 0.656482
[4]	valid_0's binary_logloss: 0.651843
[5]	valid_0's binary_logloss: 1.35293
[6]	valid_0's binary_logloss: 1.6172
[7]	valid_0's binary_logloss: 1.5655
[8]	valid_0's binary_logloss: 1.53139
[9]	valid_0's binary_logloss: 1.51227
[10]	valid_0's binary_logloss: 1.49367
[11]	valid_0's binary_logloss: 1.51697
[12]	valid_0's binary_logloss: 1.489
[13]	valid_0's binary_logloss: 1.46377
[14]	valid_0's binary_logloss: 1.46202
[15]	valid_0's binary_logloss: 1.46105
[16]	valid_0's binary_logloss: 1.45606
[17]	valid_0's binary_logloss: 1.45652
[18]	valid_0's binary_logloss: 1.45098
[19]	valid_0's binary_logloss: 1.45389
[20]	valid_0's binary_logloss: 1.44912
[21]	valid_0's binary_logloss: 1.47411
[22]	valid_0's binary_logloss: 1.47293
[23]	valid_0's binary_logloss: 1.46794
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 1.4699
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 1.47107
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 1.4733
[27]	valid_0's binary_logloss: 1.47567
[28]	valid_0's binary_logloss: 1.47538
[29]	valid_0's binary_logloss: 1.47397
[30]	valid_0's binary_logloss: 1.47864
[31]	valid_0's binary_logloss: 1.47746

Trening klas:  77%|███████▋  | 385/500 [44:56<15:57,  8.33s/klasa, klasa=class_385, F1_klasy=0.3497, F1_macro=0.6577, drzewa=2]




Trening klas:  77%|███████▋  | 386/500 [44:56<12:58,  6.83s/klasa, klasa=class_385, F1_klasy=0.3497, F1_macro=0.6577, drzewa=2]

[32]	valid_0's binary_logloss: 1.47252
[1]	valid_0's binary_logloss: 0.0163613
[2]	valid_0's binary_logloss: 0.0153621
[3]	valid_0's binary_logloss: 0.0144021
[4]	valid_0's binary_logloss: 0.013714
[5]	valid_0's binary_logloss: 0.012964
[6]	valid_0's binary_logloss: 0.0129729
[7]	valid_0's binary_logloss: 0.0122732
[8]	valid_0's binary_logloss: 0.0116489
[9]	valid_0's binary_logloss: 0.0110275
[10]	valid_0's binary_logloss: 0.0104643
[11]	valid_0's binary_logloss: 0.0140776
[12]	valid_0's binary_logloss: 0.0136234
[13]	valid_0's binary_logloss: 0.0132074
[14]	valid_0's binary_logloss: 0.0127774
[15]	valid_0's binary_logloss: 0.012367
[16]	valid_0's binary_logloss: 0.0121062
[17]	valid_0's binary_logloss: 0.0116949
[18]	valid_0's binary_logloss: 0.0114389
[19]	valid_0's binary_logloss: 0.0110568
[20]	valid_0's binary_logloss: 0.0108325
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0105115
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0101905
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.00987786
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.00958126
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.00930992
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.00903663
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.00878134
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.00854264
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.00842223
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.00818778
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.00797912
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.00776719
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.00756754
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.00737978
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.00720631
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.00703455
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.00687006
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.00671405
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.00657041
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.00642058
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.00627915
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.00613034
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.00601626
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.00589275
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.00577447
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.00566443
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.00556005
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.00546071
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.00536527
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.00526757
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.00518711
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.0050923
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.00500929
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.00493374
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.00484905
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.00477828
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.00470962
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.00463442
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.00456245
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.00449795
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.00442798
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.00436381
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.00430246
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.00424475
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.00418574
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.00413731
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.00408701
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.0040424
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.0040037
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.00395676
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.00390541
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.00385593
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.00380832
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.00376384
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.00371948
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.00367984
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.00364781
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.00361036
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.00358048
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.00355093
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.00351931
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.0034899
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.0034565
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.00342761
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.00339694
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.00336635
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.00334853
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.00334176
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.00331372
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.0032879
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.00326561
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.00324176
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.00321786
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.00319693
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.00317418
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.00317742
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.00316133
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.00314014
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.003126
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.00311134
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.00308529
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.00305985
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.0030351
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.00302586
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.00300692
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.00301142
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.00299204
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.00297349
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.00295513
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.00293712
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.00293182
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 0.00291413
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 0.00290957
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 0.00290507
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 0.00290064
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[116]	valid_0's binary_logloss: 0.00288277
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[117]	valid_0's binary_logloss: 0.00286552
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[118]	valid_0's binary_logloss: 0.00284868
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[119]	valid_0's binary_logloss: 0.0028336
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[120]	valid_0's binary_logloss: 0.00281735
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[121]	valid_0's binary_logloss: 0.00282888
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[122]	valid_0's binary_logloss: 0.00284047
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[123]	valid_0's binary_logloss: 0.00285215
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[124]	valid_0's binary_logloss: 0.00284559
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[125]	valid_0's binary_logloss: 0.00285741
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[126]	valid_0's binary_logloss: 0.00284199
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[127]	valid_0's binary_logloss: 0.00283143
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[128]	valid_0's binary_logloss: 0.00281624
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[129]	valid_0's binary_logloss: 0.00280225
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[130]	valid_0's binary_logloss: 0.00278791
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[131]	valid_0's binary_logloss: 0.00277218
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[132]	valid_0's binary_logloss: 0.002758
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[133]	valid_0's binary_logloss: 0.00274291
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[134]	valid_0's binary_logloss: 0.00272764
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[135]	valid_0's binary_logloss: 0.00271313
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[136]	valid_0's binary_logloss: 0.00270004
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[137]	valid_0's binary_logloss: 0.00270734
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[138]	valid_0's binary_logloss: 0.00269477
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[139]	valid_0's binary_logloss: 0.00270125
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[140]	valid_0's binary_logloss: 0.00268911
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[141]	valid_0's binary_logloss: 0.00267702
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[142]	valid_0's binary_logloss: 0.00266526
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[143]	valid_0's binary_logloss: 0.00265374
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[144]	valid_0's binary_logloss: 0.00265006
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[145]	valid_0's binary_logloss: 0.00263898
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[146]	valid_0's binary_logloss: 0.00263171
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[147]	valid_0's binary_logloss: 0.00261986
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[148]	valid_0's binary_logloss: 0.00260812
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[149]	valid_0's binary_logloss: 0.0025966
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[150]	valid_0's binary_logloss: 0.00258538
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[151]	valid_0's binary_logloss: 0.00257933
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[152]	valid_0's binary_logloss: 0.00257345
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[153]	valid_0's binary_logloss: 0.00257259
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[154]	valid_0's binary_logloss: 0.00256126
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[155]	valid_0's binary_logloss: 0.00255642
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[156]	valid_0's binary_logloss: 0.00255407
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[157]	valid_0's binary_logloss: 0.00255108
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[158]	valid_0's binary_logloss: 0.00254886
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[159]	valid_0's binary_logloss: 0.00254669
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[160]	valid_0's binary_logloss: 0.00254261
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[161]	valid_0's binary_logloss: 0.00253662
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[162]	valid_0's binary_logloss: 0.0025301
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[163]	valid_0's binary_logloss: 0.00252925
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[164]	valid_0's binary_logloss: 0.00252363
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[165]	valid_0's binary_logloss: 0.00251652
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[166]	valid_0's binary_logloss: 0.00251602
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[167]	valid_0's binary_logloss: 0.0025155
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[168]	valid_0's binary_logloss: 0.00251503
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[169]	valid_0's binary_logloss: 0.00251093
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[170]	valid_0's binary_logloss: 0.00251047
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[171]	valid_0's binary_logloss: 0.00251606
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[172]	valid_0's binary_logloss: 0.00252156
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[173]	valid_0's binary_logloss: 0.00252085
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[174]	valid_0's binary_logloss: 0.00251952
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[175]	valid_0's binary_logloss: 0.00251887
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[176]	valid_0's binary_logloss: 0.00252161
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[177]	valid_0's binary_logloss: 0.00252415
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[178]	valid_0's binary_logloss: 0.00251701
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[179]	valid_0's binary_logloss: 0.0025109
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[180]	valid_0's binary_logloss: 0.00250444
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[181]	valid_0's binary_logloss: 0.0025042
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[182]	valid_0's binary_logloss: 0.00250404
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[183]	valid_0's binary_logloss: 0.00250383

Trening klas:  77%|███████▋  | 386/500 [45:04<12:58,  6.83s/klasa, klasa=class_386, F1_klasy=0.0000, F1_macro=0.6560, drzewa=300]




Trening klas:  77%|███████▋  | 387/500 [45:04<13:43,  7.29s/klasa, klasa=class_386, F1_klasy=0.0000, F1_macro=0.6560, drzewa=300]

[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[295]	valid_0's binary_logloss: 0.00240935
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[296]	valid_0's binary_logloss: 0.0024093
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[297]	valid_0's binary_logloss: 0.00240927
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[298]	valid_0's binary_logloss: 0.00240923
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[299]	valid_0's binary_logloss: 0.0024092
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[300]	valid_0's binary_logloss: 0.00240917
[1]	valid_0's binary_logloss: 1.09203
[2]	valid_0's binary_logloss: 0.530343
[3]	valid_0's binary_logloss: 0.576245
[4]	valid_0's binary_logloss: 0.55711
[5]	valid_0's binary_logloss: 0.546459
[6]	valid_0's binary_logloss: 0.540016
[7]	valid_0's binary_logloss: 0.536541
[8]	valid_0's binary_logloss: 0.533468
[9]	valid_0's binary_logloss: 0.531131
[10]	valid_0's binary_logloss: 0.529366
[11]	valid_0's binary_logloss: 0.515068
[12]	valid_0's binary_logloss: 0.510032
[13]	valid_0's binary_logloss: 0.503042
[14]	valid_0's binary_logloss: 0.498635
[15]	valid_0's binary_logloss: 0.499076
[16]	valid_0's binary_logloss: 0.495542
[17]	valid_0's binary_logloss: 0.498219
[18]	valid_0's binary_logloss: 0.497666
[19]	valid_0's binary_logloss: 0.50227
[20]	valid_0's binary_logloss: 0.501818
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.500155
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.497507
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.491596
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.487418
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.488176
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.484252
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.481608
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.47901
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.478707
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.477139
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.476814
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.478681
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.476415
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.476527
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.475724
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.47459
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.472508
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.470911
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.474162
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.476203
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.47761
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.478241
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.479556
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.482821
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.482961
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.481695
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.480931
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.480422
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.479793
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.478348
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.477606
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.477691
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.479876
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.479181
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.478379
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.47744
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.477127
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.47727
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.475754
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.475265
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.474904
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.476009
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.479264
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.480548
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.480274
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

Trening klas:  77%|███████▋  | 387/500 [45:08<13:43,  7.29s/klasa, klasa=class_387, F1_klasy=0.1390, F1_macro=0.6547, drzewa=38]




Trening klas:  78%|███████▊  | 388/500 [45:08<11:59,  6.42s/klasa, klasa=class_387, F1_klasy=0.1390, F1_macro=0.6547, drzewa=38]

[66]	valid_0's binary_logloss: 0.479752
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.480193
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.478861
[1]	valid_0's binary_logloss: 0.0873535
[2]	valid_0's binary_logloss: 0.0765313
[3]	valid_0's binary_logloss: 0.0698844
[4]	valid_0's binary_logloss: 0.065274
[5]	valid_0's binary_logloss: 0.0605495
[6]	valid_0's binary_logloss: 0.0651582
[7]	valid_0's binary_logloss: 0.0618758
[8]	valid_0's binary_logloss: 0.0593001
[9]	valid_0's binary_logloss: 0.0569374
[10]	valid_0's binary_logloss: 0.0545871
[11]	valid_0's binary_logloss: 0.0522781
[12]	valid_0's binary_logloss: 0.049654
[13]	valid_0's binary_logloss: 0.0478513
[14]	valid_0's binary_logloss: 0.046092
[15]	valid_0's binary_logloss: 0.0440681
[16]	valid_0's binary_logloss: 0.042381
[17]	valid_0's binary_logloss: 0.040809
[18]	valid_0's binary_logloss: 0.0395852
[19]	valid_0's binary_logloss: 0.0382868
[20]	valid_0's binary_logloss: 0.037037
[21]	valid_0's binary_logloss: 0.0358654
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0346706
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.0336653
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0326551
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.0317167
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.0308092
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.029959
[28]	valid_0's binary_logloss: 0.0289719
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.0281326
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.0274019
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.026642
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.025989
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.0253109
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.0246174
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.0240344
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.0236025
[37]	valid_0's binary_logloss: 0.0230534
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.0226717
[39]	valid_0's binary_logloss: 0.0220831
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.0217033
[41]	valid_0's binary_logloss: 0.0212555
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.0209187
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.0205637
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.0202735
[45]	valid_0's binary_logloss: 0.0198772
[46]	valid_0's binary_logloss: 0.0194941
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.0191238
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.0188743
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.0185786
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.0182739
[51]	valid_0's binary_logloss: 0.0179003
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.0175793
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.0172623
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.0170436
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.0169167
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.0167583
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.0164558
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.0162693
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.0160914
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.0158948
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.0156317
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.0154873
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.0152817
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.015071
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.0149111
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.0146927
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.0145349
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.014333
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.0141837
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.0140456
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.0138955
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.0137524
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.0135559
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.0133223
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.0132085
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.0130809
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.0129584
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.0128799
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.0127201
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.0126032
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.0124602
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.0123592
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.0122747
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.0121213
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.0120297
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.0118619
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.0116665
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.0115275
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.0114613
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.0113299
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.0112119
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.0111329
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.0110376
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.0109148
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.0108633
[96]	valid_0's binary_logloss: 0.01074
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.0106595
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.010593
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.0105063
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.0104298
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.0104091
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.0103512
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.0102747
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.0101998
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.0101901
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.0101611
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.0100751
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.00997987
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.00992993
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.00987494
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.00987363
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 0.00993251
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 0.00994518
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 0.00997452
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 0.0100165
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[116]	valid_0's binary_logloss: 0.0100396
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[117]	valid_0's binary_logloss: 0.0100105
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[118]	valid_0's binary_logloss: 0.00996389
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[119]	valid_0's binary_logloss: 0.00998837
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[120]	valid_0's binary_logloss: 0.0100086
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[121]	valid_0's binary_logloss: 0.00997917
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[122]	valid_0's binary_logloss: 0.00997419
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[123]	valid_0's binary_logloss: 0.00995423
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[124]	valid_0's binary_logloss: 0.009902
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[125]	valid_0's binary_logloss: 0.00989915
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[126]	valid_0's binary_logloss: 0.0098736
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[127]	valid_0's binary_logloss: 0.00983255
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[128]	valid_0's binary_logloss: 0.00983072
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[129]	valid_0's binary_logloss: 0.00983997
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[130]	valid_0's binary_logloss: 0.00986565
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[131]	valid_0's binary_logloss: 0.00986833
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[132]	valid_0's binary_logloss: 0.00988064
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[133]	valid_0's binary_logloss: 0.00988162
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[134]	valid_0's binary_logloss: 0.009896
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[135]	valid_0's binary_logloss: 0.00986503
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[136]	valid_0's binary_logloss: 0.00988433
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[137]	valid_0's binary_logloss: 0.00980047
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[138]	valid_0's binary_logloss: 0.00980273
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[139]	valid_0's binary_logloss: 0.00980564
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[140]	valid_0's binary_logloss: 0.00972131
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[141]	valid_0's binary_logloss: 0.00971574
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[142]	valid_0's binary_logloss: 0.00967769
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[143]	valid_0's binary_logloss: 0.00968689
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[144]	valid_0's binary_logloss: 0.00967936
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[145]	valid_0's binary_logloss: 0.00966321
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[146]	valid_0's binary_logloss: 0.0096838
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[147]	valid_0's binary_logloss: 0.00967542
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[148]	valid_0's binary_logloss: 0.00969275
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[149]	valid_0's binary_logloss: 0.00968952
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[150]	valid_0's binary_logloss: 0.00969419
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[151]	valid_0's binary_logloss: 0.00968554
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[152]	valid_0's binary_logloss: 0.00966846
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[153]	valid_0's binary_logloss: 0.00963584
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[154]	valid_0's binary_logloss: 0.0096278
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[155]	valid_0's binary_logloss: 0.00963049
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[156]	valid_0's binary_logloss: 0.00958509
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[157]	valid_0's binary_logloss: 0.00959484
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[158]	valid_0's binary_logloss: 0.00959052
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[159]	valid_0's binary_logloss: 0.00956625
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[160]	valid_0's binary_logloss: 0.00951914
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[161]	valid_0's binary_logloss: 0.00954532
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[162]	valid_0's binary_logloss: 0.00953391
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[163]	valid_0's binary_logloss: 0.00952777
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[164]	valid_0's binary_logloss: 0.00958923
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[165]	valid_0's binary_logloss: 0.00966518
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[166]	valid_0's binary_logloss: 0.00964429
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[167]	valid_0's binary_logloss: 0.00967484
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[168]	valid_0's binary_logloss: 0.00967503
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[169]	valid_0's binary_logloss: 0.00970099
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[170]	valid_0's binary_logloss: 0.00968693
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[171]	valid_0's binary_logloss: 0.00971456
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[172]	valid_0's binary_logloss: 0.00972744
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[173]	valid_0's binary_logloss: 0.00975871
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[174]	valid_0's binary_logloss: 0.00979142
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[175]	valid_0's binary_logloss: 0.00978217
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[176]	valid_0's binary_logloss: 0.00979101
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[177]	valid_0's binary_logloss: 0.00977162
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[178]	valid_0's binary_logloss: 0.00979734
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[179]	valid_0's binary_logloss: 0.00981348
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[180]	valid_0's binary_logloss: 0.00977753
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[181]	valid_0's binary_logloss: 0.00976618
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[182]	valid_0's binary_logloss: 0.00977647
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[183]	valid_0's binary_logloss: 0.00980186
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[184]	valid_0's binary_logloss: 0.00985627
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[185]	valid_0's binary_logloss: 0.00986659
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[186]	valid_0's binary_logloss: 0.00983051
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[187]	valid_0's binary_logloss: 0.00983462
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

Trening klas:  78%|███████▊  | 388/500 [45:19<11:59,  6.42s/klasa, klasa=class_388, F1_klasy=0.2400, F1_macro=0.6536, drzewa=160]




Trening klas:  78%|███████▊  | 389/500 [45:19<14:28,  7.82s/klasa, klasa=class_388, F1_klasy=0.2400, F1_macro=0.6536, drzewa=160]

[190]	valid_0's binary_logloss: 0.00977423
[1]	valid_0's binary_logloss: 0.0842274
[2]	valid_0's binary_logloss: 0.060125
[3]	valid_0's binary_logloss: 0.0498389
[4]	valid_0's binary_logloss: 0.0454456
[5]	valid_0's binary_logloss: 0.0422564
[6]	valid_0's binary_logloss: 0.0397273
[7]	valid_0's binary_logloss: 0.0375182
[8]	valid_0's binary_logloss: 0.0356126
[9]	valid_0's binary_logloss: 0.034157
[10]	valid_0's binary_logloss: 0.0326834
[11]	valid_0's binary_logloss: 0.0312836
[12]	valid_0's binary_logloss: 0.0301097
[13]	valid_0's binary_logloss: 0.0292513
[14]	valid_0's binary_logloss: 0.0282263
[15]	valid_0's binary_logloss: 0.0273232
[16]	valid_0's binary_logloss: 0.0267074
[17]	valid_0's binary_logloss: 0.026024
[18]	valid_0's binary_logloss: 0.0253336
[19]	valid_0's binary_logloss: 0.0246906
[20]	valid_0's binary_logloss: 0.0242045
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0234206
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0228789
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.0221377
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0215963
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.0210478
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.0205351
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.020022
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.0196073
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.0191979
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.0187207
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.01833
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.0179867
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.0176634
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.0174018
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.0171004
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.0168262
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.0165258
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.0162352
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.0160038
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.0158247
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.0155881
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.0153715
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.0151709
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.0149023
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.0147071
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.0144984
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.014312
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.0141442
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.0139728
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.0138007
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.0137627
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.0137247
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.0136129
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.013528
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.0134414
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.0132936
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.0131303
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.0130261
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.0129442
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.0128558
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.0127839
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.0127252
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.0126711
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.0126305
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.0125764
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.0124952
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.0124029
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.0123157
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.0122351
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.0122441
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.0121997
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.0121801
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.0121966
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.0121913
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.0121553
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.0121189
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.0120757
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.0120238
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.0119538
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.0119302
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.0119835
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.0119892
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.0120479
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.0121087
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.0121712
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.0121686
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.0121882
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.01221
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.0122109
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.012215
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.0122368
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.0122511
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.0122667
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.0123221
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.0123371
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.0123622
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.0123686
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.0124001
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.0124053
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.0123971
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

Trening klas:  78%|███████▊  | 389/500 [45:24<14:28,  7.82s/klasa, klasa=class_389, F1_klasy=0.8421, F1_macro=0.6541, drzewa=80]




Trening klas:  78%|███████▊  | 390/500 [45:24<12:26,  6.79s/klasa, klasa=class_389, F1_klasy=0.8421, F1_macro=0.6541, drzewa=80]

[101]	valid_0's binary_logloss: 0.0123755
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.0123601
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.0123451
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.0123207
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.012306
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.0123097
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.0122746
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.0122458
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.0122416
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.0122534
[1]	valid_0's binary_logloss: 0.0664172
[2]	valid_0's binary_logloss: 0.0533652
[3]	valid_0's binary_logloss: 0.0467297
[4]	valid_0's binary_logloss: 0.0424074
[5]	valid_0's binary_logloss: 0.0387298
[6]	valid_0's binary_logloss: 0.0358786
[7]	valid_0's binary_logloss: 0.0335347
[8]	valid_0's binary_logloss: 0.0314057
[9]	valid_0's binary_logloss: 0.0294983
[10]	valid_0's binary_logloss: 0.0278419
[11]	valid_0's binary_logloss: 0.0268225
[12]	valid_0's binary_logloss: 0.0257571
[13]	valid_0's binary_logloss: 0.0247059
[14]	valid_0's binary_logloss: 0.0236252
[15]	valid_0's binary_logloss: 0.0225877
[16]	valid_0's binary_logloss: 0.0217692
[17]	valid_0's binary_logloss: 0.0210431
[18]	valid_0's binary_logloss: 0.0203722
[19]	valid_0's binary_logloss: 0.0196422
[20]	valid_0's binary_logloss: 0.0190263
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0184298
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0177575
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.0173363
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.016879
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.0163039
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.0158719
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.0154672
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.0149872
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.0145244
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.0141773
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.013691
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.0132919
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.0130286
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.0126746
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.0123232
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.0119464
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.0115865
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.0112082
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.0108866
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.0105704
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.0102765
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.0100119
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.00976045
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.00954903
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.00932927
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.00909618
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.00890279
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.00871425
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.00849328
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.00833999
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.00818
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.00803244
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.00788095
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.00772886
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.00760895
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.00748814
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.0073219
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.00721471
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.00706188
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.0069415
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.00677435
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.00665484
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.00653436
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.00645076
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.00632039
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.00625468
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.00619138
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.00612737
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.00606437
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.00600596
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.00594006
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.00587468
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.00586344
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.00579693
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.00574945
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.00568686
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.00562812
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.00558247
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.00554531
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.00549484
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.00550252
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.00551479
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.00553516
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.00549127
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.00544558
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.00543913
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.00545144
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.00544789
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.00547234
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.00548662
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.00545278
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.00541601
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.00538037
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.00535451
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.00534024
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.00530764
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.00529764
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.00529309
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.00528172
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.00527275
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.00524798
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.00525974
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.00525391
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.00521473
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.00521475
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.0051808
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.00516625
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.00513166
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.00510589
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.00508098
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.00505891
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 0.00504274
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 0.00506521
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 0.00506636
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 0.00505588
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[116]	valid_0's binary_logloss: 0.0050662
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[117]	valid_0's binary_logloss: 0.00507293
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[118]	valid_0's binary_logloss: 0.00506864
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[119]	valid_0's binary_logloss: 0.00506725
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[120]	valid_0's binary_logloss: 0.00504169
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[121]	valid_0's binary_logloss: 0.0050461
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[122]	valid_0's binary_logloss: 0.00502113
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[123]	valid_0's binary_logloss: 0.00500605
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[124]	valid_0's binary_logloss: 0.00501803
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[125]	valid_0's binary_logloss: 0.00505266
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[126]	valid_0's binary_logloss: 0.00504899
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[127]	valid_0's binary_logloss: 0.0050188
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[128]	valid_0's binary_logloss: 0.00500513
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[129]	valid_0's binary_logloss: 0.00498479
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[130]	valid_0's binary_logloss: 0.00500549
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[131]	valid_0's binary_logloss: 0.0050291
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[132]	valid_0's binary_logloss: 0.00503225
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[133]	valid_0's binary_logloss: 0.00503615
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[134]	valid_0's binary_logloss: 0.00504329
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[135]	valid_0's binary_logloss: 0.00506785
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[136]	valid_0's binary_logloss: 0.00506839
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[137]	valid_0's binary_logloss: 0.00507715
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[138]	valid_0's binary_logloss: 0.00510057
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[139]	valid_0's binary_logloss: 0.00511033
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[140]	valid_0's binary_logloss: 0.00514438
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[141]	valid_0's binary_logloss: 0.00517062
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[142]	valid_0's binary_logloss: 0.00520304
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[143]	valid_0's binary_logloss: 0.00523877
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[144]	valid_0's binary_logloss: 0.00525706
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[145]	valid_0's binary_logloss: 0.00527235
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[146]	valid_0's binary_logloss: 0.00528233
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[147]	valid_0's binary_logloss: 0.00530665
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[148]	valid_0's binary_logloss: 0.00533023
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[149]	valid_0's binary_logloss: 0.00532409
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[150]	valid_0's binary_logloss: 0.0053391
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[151]	valid_0's binary_logloss: 0.00532284
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[152]	valid_0's binary_logloss: 0.00533753
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[153]	valid_0's binary_logloss: 0.00535461
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

Trening klas:  78%|███████▊  | 390/500 [45:29<12:26,  6.79s/klasa, klasa=class_390, F1_klasy=0.1667, F1_macro=0.6529, drzewa=129]




Trening klas:  78%|███████▊  | 391/500 [45:29<11:40,  6.43s/klasa, klasa=class_390, F1_klasy=0.1667, F1_macro=0.6529, drzewa=129]

[154]	valid_0's binary_logloss: 0.00537179
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[155]	valid_0's binary_logloss: 0.00535787
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[156]	valid_0's binary_logloss: 0.00534544
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[157]	valid_0's binary_logloss: 0.00535597
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[158]	valid_0's binary_logloss: 0.0053514
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[159]	valid_0's binary_logloss: 0.00536107
[1]	valid_0's binary_logloss: 0.390472
[2]	valid_0's binary_logloss: 0.327774
[3]	valid_0's binary_logloss: 0.98733
[4]	valid_0's binary_logloss: 0.999282
[5]	valid_0's binary_logloss: 1.22792
[6]	valid_0's binary_logloss: 1.29927
[7]	valid_0's binary_logloss: 1.58357
[8]	valid_0's binary_logloss: 1.67893
[9]	valid_0's binary_logloss: 1.68442
[10]	valid_0's binary_logloss: 1.68975
[11]	valid_0's binary_logloss: 1.70409
[12]	valid_0's binary_logloss: 1.71535
[13]	valid_0's binary_logloss: 1.7147
[14]	valid_0's binary_logloss: 1.71344
[15]	valid_0's binary_logloss: 1.71225
[16]	valid_0's binary_logloss: 1.71633
[17]	valid_0's binary_logloss: 1.70665
[18]	valid_0's binary_logloss: 1.70283
[19]	valid_0's binary_logloss: 1.68486
[20]	valid_0's binary_logloss: 1.6766
[21]	valid_0's binary_logloss: 2.3074
[22]	valid_0's binary_logloss: 2.28925
[23]	valid_0's binary_logloss: 2.26951
[24]	valid_0's binary_logloss: 2.26098
[25]	valid_0's binary_logloss: 2.24912
[26]	valid_0's binary_logloss: 2.21706
[27]	valid_0's binary_logloss: 2.19049
[28]	valid_0's binary_logloss: 2.13481
[29]	valid_0's binary_logloss: 2.11379

Trening klas:  78%|███████▊  | 391/500 [45:32<11:40,  6.43s/klasa, klasa=class_391, F1_klasy=0.3708, F1_macro=0.6522, drzewa=2]




Trening klas:  78%|███████▊  | 392/500 [45:32<09:46,  5.43s/klasa, klasa=class_391, F1_klasy=0.3708, F1_macro=0.6522, drzewa=2]

[30]	valid_0's binary_logloss: 2.10952
[31]	valid_0's binary_logloss: 2.14698
[32]	valid_0's binary_logloss: 2.13667
[1]	valid_0's binary_logloss: 0.106848
[2]	valid_0's binary_logloss: 0.0438734
[3]	valid_0's binary_logloss: 0.0390031
[4]	valid_0's binary_logloss: 0.0374525
[5]	valid_0's binary_logloss: 0.035925
[6]	valid_0's binary_logloss: 0.0349053
[7]	valid_0's binary_logloss: 0.0337295
[8]	valid_0's binary_logloss: 0.0326548
[9]	valid_0's binary_logloss: 0.0318873
[10]	valid_0's binary_logloss: 0.0308232
[11]	valid_0's binary_logloss: 0.029968
[12]	valid_0's binary_logloss: 0.0285285
[13]	valid_0's binary_logloss: 0.0277427
[14]	valid_0's binary_logloss: 0.0269878
[15]	valid_0's binary_logloss: 0.0262407
[16]	valid_0's binary_logloss: 0.0255853
[17]	valid_0's binary_logloss: 0.0248182
[18]	valid_0's binary_logloss: 0.0240946
[19]	valid_0's binary_logloss: 0.0236492
[20]	valid_0's binary_logloss: 0.0232464
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0228213
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0223798
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.0219291
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0214155
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.0209624
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.0206985
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.0202554
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.0198954
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.0195064
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.019192
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.0188912
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.0185972
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.0183024
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.0179273
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.0176158
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.0173103
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.0170618
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.0168345
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.0165893
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.0164028
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.0161484
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.0159188
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.0156996
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.0154712
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.0153012
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.0151298
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.0149892
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.0148328
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.014632
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.0144853
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.014325
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.0141559
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.0140431
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.0139613
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.0138583
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.013767
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.0136744
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.0135383
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.0134712
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.0133664
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.0133586
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.013263
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.0132305
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.0131484
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.0130717
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.0129704
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.0129179
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.0129108
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.0128783
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.0127585
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.0127399
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.0127562
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.0127719
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.012777
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.0127436
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.0126055
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.0124956
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.012387
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.0123551
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.012276
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.0122277
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.0121408
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.0120805
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.0120293
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.0119952
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.0118425
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.0117784
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.0117834
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.0117525
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.0117385
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.0117452
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.0116808
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.0116173
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.0115696
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.0115235
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.0115015
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.0114781
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.0114584
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.01144
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.011413
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.0113724
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.0113108
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.0112506
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.0112177
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.011207
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.0111644
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.0111438
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.0111034
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.0110773
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.0110586
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.0109871
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 0.0109373
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 0.0109174
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 0.010871
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 0.0108826
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[116]	valid_0's binary_logloss: 0.0108587
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[117]	valid_0's binary_logloss: 0.010861
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[118]	valid_0's binary_logloss: 0.0108785
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[119]	valid_0's binary_logloss: 0.0108427
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[120]	valid_0's binary_logloss: 0.0108305
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[121]	valid_0's binary_logloss: 0.0107864
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[122]	valid_0's binary_logloss: 0.0107433
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[123]	valid_0's binary_logloss: 0.0107088
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[124]	valid_0's binary_logloss: 0.0106882
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[125]	valid_0's binary_logloss: 0.0106539
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[126]	valid_0's binary_logloss: 0.0106283
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[127]	valid_0's binary_logloss: 0.0105937
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[128]	valid_0's binary_logloss: 0.0105628
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[129]	valid_0's binary_logloss: 0.010544
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[130]	valid_0's binary_logloss: 0.01051
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[131]	valid_0's binary_logloss: 0.0104921
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[132]	valid_0's binary_logloss: 0.0104743
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[133]	valid_0's binary_logloss: 0.0104829
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[134]	valid_0's binary_logloss: 0.0104556
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[135]	valid_0's binary_logloss: 0.0105007
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[136]	valid_0's binary_logloss: 0.0104695
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[137]	valid_0's binary_logloss: 0.0104474
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[138]	valid_0's binary_logloss: 0.0104294
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[139]	valid_0's binary_logloss: 0.0104219
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[140]	valid_0's binary_logloss: 0.0104269
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[141]	valid_0's binary_logloss: 0.0103855
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[142]	valid_0's binary_logloss: 0.0103647
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[143]	valid_0's binary_logloss: 0.0103519
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[144]	valid_0's binary_logloss: 0.0103271
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[145]	valid_0's binary_logloss: 0.010316
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[146]	valid_0's binary_logloss: 0.0102547
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[147]	valid_0's binary_logloss: 0.0102057
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[148]	valid_0's binary_logloss: 0.0101465
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[149]	valid_0's binary_logloss: 0.0101011
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[150]	valid_0's binary_logloss: 0.0100594
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[151]	valid_0's binary_logloss: 0.00999232
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[152]	valid_0's binary_logloss: 0.0100165
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[153]	valid_0's binary_logloss: 0.0100475
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[154]	valid_0's binary_logloss: 0.0100363
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[155]	valid_0's binary_logloss: 0.0100803
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[156]	valid_0's binary_logloss: 0.0100676
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[157]	valid_0's binary_logloss: 0.010068
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[158]	valid_0's binary_logloss: 0.0100771
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[159]	valid_0's binary_logloss: 0.0100656
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[160]	valid_0's binary_logloss: 0.0100699
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[161]	valid_0's binary_logloss: 0.0100537
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[162]	valid_0's binary_logloss: 0.0100533
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[163]	valid_0's binary_logloss: 0.0100535
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[164]	valid_0's binary_logloss: 0.0100281
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[165]	valid_0's binary_logloss: 0.00998562
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[166]	valid_0's binary_logloss: 0.00997437
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[167]	valid_0's binary_logloss: 0.00993478
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[168]	valid_0's binary_logloss: 0.00991563
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[169]	valid_0's binary_logloss: 0.00990816
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[170]	valid_0's binary_logloss: 0.00990191
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[171]	valid_0's binary_logloss: 0.00993999
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[172]	valid_0's binary_logloss: 0.00992436
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[173]	valid_0's binary_logloss: 0.00993172
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[174]	valid_0's binary_logloss: 0.00991849
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[175]	valid_0's binary_logloss: 0.00991996
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[176]	valid_0's binary_logloss: 0.00989095
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[177]	valid_0's binary_logloss: 0.00985084
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[178]	valid_0's binary_logloss: 0.009822
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[179]	valid_0's binary_logloss: 0.00980039
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[180]	valid_0's binary_logloss: 0.00978957
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[181]	valid_0's binary_logloss: 0.00976355
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[182]	valid_0's binary_logloss: 0.00975065
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[183]	valid_0's binary_logloss: 0.00974122
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

Trening klas:  78%|███████▊  | 392/500 [45:40<09:46,  5.43s/klasa, klasa=class_392, F1_klasy=0.8108, F1_macro=0.6526, drzewa=260]

[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[281]	valid_0's binary_logloss: 0.00944042
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[282]	valid_0's binary_logloss: 0.00943266
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[283]	valid_0's binary_logloss: 0.00943411
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[284]	valid_0's binary_logloss: 0.00943387
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[285]	valid_0's binary_logloss: 0.00941569
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[286]	valid_0's binary_logloss: 0.00941784
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[287]	valid_0's binary_logloss: 0.00941135
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[288]	valid_0's binary_logloss: 0.00940506
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[289]	valid_0's binary_logloss: 0.00940018
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[290]	valid_0's binary_logloss: 0.00940676

Trening klas:  79%|███████▊  | 393/500 [45:40<10:53,  6.10s/klasa, klasa=class_392, F1_klasy=0.8108, F1_macro=0.6526, drzewa=260]

[1]	valid_0's binary_logloss: 0.0477736
[2]	valid_0's binary_logloss: 0.0396696
[3]	valid_0's binary_logloss: 0.0357933
[4]	valid_0's binary_logloss: 0.0333959
[5]	valid_0's binary_logloss: 0.0313154
[6]	valid_0's binary_logloss: 0.0670399
[7]	valid_0's binary_logloss: 0.0611239
[8]	valid_0's binary_logloss: 0.0570754
[9]	valid_0's binary_logloss: 0.0536268
[10]	valid_0's binary_logloss: 0.0505148
[11]	valid_0's binary_logloss: 0.0479093
[12]	valid_0's binary_logloss: 0.0453294
[13]	valid_0's binary_logloss: 0.0432337
[14]	valid_0's binary_logloss: 0.041348
[15]	valid_0's binary_logloss: 0.0395784
[16]	valid_0's binary_logloss: 0.0376713
[17]	valid_0's binary_logloss: 0.0359575
[18]	valid_0's binary_logloss: 0.0344424
[19]	valid_0's binary_logloss: 0.0331513
[20]	valid_0's binary_logloss: 0.0318367
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0305068
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0291766
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.0280528
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0268732
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.0259676
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.0251038
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.024404
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.0235904
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.0228433
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.0221723
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.0216148
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.0210681
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.0205699
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.0199391
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.0194955
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.0189897
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.0184817
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.0180072
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.0175585
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.0171077
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.0166973
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.0163153
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.0159739
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.0157374
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.0155009
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.0152167
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.0149235
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.0146892
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.0144496
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.0141786
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.0140436
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.0138675
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.0136661
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.0134516
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.013295
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.0130983
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.0128625
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.0127334
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.0126086
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.0124933
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.0123747
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.0122284
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.0121083
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.0119484
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.0118352
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.0117674
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.0116833
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.0115784
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.0114915
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.011427
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.0112895
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.0112073
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.0111273
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.0110489
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.0109716
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.0109092
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.0108399
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.0107848
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.0107613
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.010699
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.0106607
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.0106471
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.0106162
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.010547
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.0105135
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.0104859
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.0104499
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.0104251
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.0103802
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.0103262
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.0103081
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.0102972
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.0102858
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.0102936
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.0103046
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.0102891
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.0102792
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.0102532
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.0102538
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.0102349
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.0102149
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.0101976
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.0101685
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.0101799
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.010197
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.0102034
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.0102172
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.0102488
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.0102578
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.0102811
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.0102805
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 0.010275
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 0.0102587
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 0.0102456
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 0.0102536
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[116]	valid_0's binary_logloss: 0.0102638
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[117]	valid_0's binary_logloss: 0.0102905
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[118]	valid_0's binary_logloss: 0.0103363
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[119]	valid_0's binary_logloss: 0.0103229
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[120]	valid_0's binary_logloss: 0.0103411
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[121]	valid_0's binary_logloss: 0.0103447
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[122]	valid_0's binary_logloss: 0.0103524
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[123]	valid_0's binary_logloss: 0.0103692
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[124]	valid_0's binary_logloss: 0.0103645
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[125]	valid_0's binary_logloss: 0.010359
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[126]	valid_0's binary_logloss: 0.0103432
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[127]	valid_0's binary_logloss: 0.0103255
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[128]	valid_0's binary_logloss: 0.0103219
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[129]	valid_0's binary_logloss: 0.0103017
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

Trening klas:  79%|███████▊  | 393/500 [45:47<10:53,  6.10s/klasa, klasa=class_393, F1_klasy=0.4167, F1_macro=0.6520, drzewa=103]




Trening klas:  79%|███████▉  | 394/500 [45:47<11:04,  6.27s/klasa, klasa=class_393, F1_klasy=0.4167, F1_macro=0.6520, drzewa=103]

[130]	valid_0's binary_logloss: 0.0103188
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[131]	valid_0's binary_logloss: 0.010378
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[132]	valid_0's binary_logloss: 0.0103743
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[133]	valid_0's binary_logloss: 0.0103834
[1]	valid_0's binary_logloss: 0.820252
[2]	valid_0's binary_logloss: 0.496615
[3]	valid_0's binary_logloss: 1.28981
[4]	valid_0's binary_logloss: 1.28303
[5]	valid_0's binary_logloss: 1.28208
[6]	valid_0's binary_logloss: 1.28067
[7]	valid_0's binary_logloss: 1.27731
[8]	valid_0's binary_logloss: 1.28067
[9]	valid_0's binary_logloss: 1.27991
[10]	valid_0's binary_logloss: 1.27926
[11]	valid_0's binary_logloss: 1.27874
[12]	valid_0's binary_logloss: 1.27797
[13]	valid_0's binary_logloss: 1.27757
[14]	valid_0's binary_logloss: 1.2771
[15]	valid_0's binary_logloss: 1.27619
[16]	valid_0's binary_logloss: 1.28007
[17]	valid_0's binary_logloss: 1.29649
[18]	valid_0's binary_logloss: 1.29617
[19]	valid_0's binary_logloss: 1.29578
[20]	valid_0's binary_logloss: 1.29551
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 1.29522
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 1.29498
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 1.29473
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 1.29448
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 1.29425
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 1.29406
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 1.29388
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 1.29308
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 1.2929
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 1.29273
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 1.29256
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 1.29239

Trening klas:  79%|███████▉  | 394/500 [45:49<11:04,  6.27s/klasa, klasa=class_394, F1_klasy=0.0492, F1_macro=0.6504, drzewa=2]




Trening klas:  79%|███████▉  | 395/500 [45:49<08:59,  5.14s/klasa, klasa=class_394, F1_klasy=0.0492, F1_macro=0.6504, drzewa=2]

[1]	valid_0's binary_logloss: 0.125716
[2]	valid_0's binary_logloss: 0.0888177
[3]	valid_0's binary_logloss: 0.0809752
[4]	valid_0's binary_logloss: 0.0740496
[5]	valid_0's binary_logloss: 0.0693353
[6]	valid_0's binary_logloss: 0.0653851
[7]	valid_0's binary_logloss: 0.0618907
[8]	valid_0's binary_logloss: 0.0590656
[9]	valid_0's binary_logloss: 0.0567174
[10]	valid_0's binary_logloss: 0.0542794
[11]	valid_0's binary_logloss: 0.0521671
[12]	valid_0's binary_logloss: 0.0503504
[13]	valid_0's binary_logloss: 0.0485059
[14]	valid_0's binary_logloss: 0.0463686
[15]	valid_0's binary_logloss: 0.0446764
[16]	valid_0's binary_logloss: 0.0430977
[17]	valid_0's binary_logloss: 0.0415571
[18]	valid_0's binary_logloss: 0.0400887
[19]	valid_0's binary_logloss: 0.038868
[20]	valid_0's binary_logloss: 0.037514
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0364808
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0355362
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.0346031
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0336809
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.0328603
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.0319075
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.0311354
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.0302903
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.0294358
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.0287247
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.0279679
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.027214
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.0265203
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.0258601
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.0252421
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.0245812
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.02396
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.0234357
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.0230044
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.0224554
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.0220373
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.0215126
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.0210596
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.0206217
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.020149
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.0197933
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.0194294
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.0191039
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.0187545
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.0183897
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.0181861
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.0179744
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.0177848
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.0175778
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.0173356
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.0170702
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.0168409
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.0166283
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.0164822
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.0162827
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.0158993
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.0155493
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.0152951
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.0150717
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.0147669
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.0145908
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.0144604
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.0143233
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.0141873
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.0140726
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.0139256
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.0137838
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.0136555
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.0135144
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.0134285
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.0133488
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.0132184
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.0131193
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.013063
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.0129795
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.0128142
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.0126774
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.0125802
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.0124577
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.0123485
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.0122956
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.0122164
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.0121648
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.0121647
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.0121836
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.0120461
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.0120021
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.011988
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.0119552
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.0119599
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.0119667
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.0119771
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.0119764
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.0119672
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.0119818
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.011986
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.0119988
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.0119773
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.0119665
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.0119398
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.0119646
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.0119739
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.0120145
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.0120112
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.0120343
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.0120032
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 0.0119687
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 0.0120232
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 0.0120987
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 0.0121744
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[116]	valid_0's binary_logloss: 0.0121899
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[117]	valid_0's binary_logloss: 0.0121925
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[118]	valid_0's binary_logloss: 0.0122219
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[119]	valid_0's binary_logloss: 0.0122397
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[120]	valid_0's binary_logloss: 0.0122737
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[121]	valid_0's binary_logloss: 0.0123172
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[122]	valid_0's binary_logloss: 0.0123359
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[123]	valid_0's binary_logloss: 0.0123747
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[124]	valid_0's binary_logloss: 0.0124093
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[125]	valid_0's binary_logloss: 0.012443
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[126]	valid_0's binary_logloss: 0.012499
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[127]	valid_0's binary_logloss: 0.0125573
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[128]	valid_0's binary_logloss: 0.0125954

Trening klas:  79%|███████▉  | 395/500 [45:53<08:59,  5.14s/klasa, klasa=class_395, F1_klasy=0.6197, F1_macro=0.6504, drzewa=105]




Trening klas:  79%|███████▉  | 396/500 [45:53<08:25,  4.86s/klasa, klasa=class_395, F1_klasy=0.6197, F1_macro=0.6504, drzewa=105]

[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[129]	valid_0's binary_logloss: 0.0125796
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[130]	valid_0's binary_logloss: 0.0126097
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[131]	valid_0's binary_logloss: 0.0126127
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[132]	valid_0's binary_logloss: 0.0126929
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[133]	valid_0's binary_logloss: 0.0127254
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[134]	valid_0's binary_logloss: 0.0126996
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[135]	valid_0's binary_logloss: 0.0126948
[1]	valid_0's binary_logloss: 0.0100071
[2]	valid_0's binary_logloss: 0.00963426
[3]	valid_0's binary_logloss: 0.00933113
[4]	valid_0's binary_logloss: 0.00906338
[5]	valid_0's binary_logloss: 0.00883253
[6]	valid_0's binary_logloss: 0.0166695
[7]	valid_0's binary_logloss: 0.0160624
[8]	valid_0's binary_logloss: 0.0148322
[9]	valid_0's binary_logloss: 0.0139098
[10]	valid_0's binary_logloss: 0.0131974
[11]	valid_0's binary_logloss: 0.013383
[12]	valid_0's binary_logloss: 0.0128528
[13]	valid_0's binary_logloss: 0.0126034
[14]	valid_0's binary_logloss: 0.0121221
[15]	valid_0's binary_logloss: 0.0116882
[16]	valid_0's binary_logloss: 0.0113087
[17]	valid_0's binary_logloss: 0.0109759
[18]	valid_0's binary_logloss: 0.010709
[19]	valid_0's binary_logloss: 0.0104794
[20]	valid_0's binary_logloss: 0.0102181
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.00995847
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.00970828
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.00948133
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.00926734
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.00906609
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.008886
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.00871089
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.0085502
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.00837561
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.00823826
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.00813542
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.00802627
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.00793231
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.00784472
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.00774397
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.00762813
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.00752713
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.00742963
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.00733517
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.00726144
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.00718703
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.00711608
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.00704917
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.00698953
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.00693818
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.00690568
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.00687654
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.00684188
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.00680195
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.00676473
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.006731
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.00669965
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.00667061
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.006644
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.00662101
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.00659069
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.00656947
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.00655154
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.00653432
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.00651903
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.00652361
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.00652742
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.00653249
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.00652964
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.00653965
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.00653609
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.00653309
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.00653077
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.00653059
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.00653006
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.00653074
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.00653214
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.006541
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.0065585
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.00656925
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.00657587
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.00659412
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.0066134
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.00663475
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.00664435
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.00666619
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.00667474
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.00669769
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.00672074
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.00674426
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.00672785
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.00673967
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.00675173
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.00677119
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.00678378

Trening klas:  79%|███████▉  | 396/500 [45:57<08:25,  4.86s/klasa, klasa=class_396, F1_klasy=0.2857, F1_macro=0.6494, drzewa=60]




Trening klas:  79%|███████▉  | 397/500 [45:57<07:33,  4.40s/klasa, klasa=class_396, F1_klasy=0.2857, F1_macro=0.6494, drzewa=60]

[1]	valid_0's binary_logloss: 0.158288
[2]	valid_0's binary_logloss: 0.097352
[3]	valid_0's binary_logloss: 0.087664
[4]	valid_0's binary_logloss: 0.0815988
[5]	valid_0's binary_logloss: 0.0766883
[6]	valid_0's binary_logloss: 0.0728956
[7]	valid_0's binary_logloss: 0.0691284
[8]	valid_0's binary_logloss: 0.0663275
[9]	valid_0's binary_logloss: 0.0639647
[10]	valid_0's binary_logloss: 0.0616516
[11]	valid_0's binary_logloss: 0.059618
[12]	valid_0's binary_logloss: 0.0578892
[13]	valid_0's binary_logloss: 0.0563402
[14]	valid_0's binary_logloss: 0.0550398
[15]	valid_0's binary_logloss: 0.0538104
[16]	valid_0's binary_logloss: 0.0522936
[17]	valid_0's binary_logloss: 0.0511641
[18]	valid_0's binary_logloss: 0.0499717
[19]	valid_0's binary_logloss: 0.0486025
[20]	valid_0's binary_logloss: 0.0474249
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0463896
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0455378
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.0446708
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0439474
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.0432657
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.0422979
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.041516
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.0407659
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.0400151
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.0393518
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.0387221
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.038181
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.037688
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.0372371
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.036721
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.0363033
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.0358693
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.0353554
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.0349203
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.0345654
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.0341391
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.0338773
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.0334774
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.033077
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.0327358
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.0324392
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.0322117
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.0318128
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.0314598
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.0311847
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.0307848
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.0305287
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.0302477
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.0299295
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.0296522
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.0293597
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.0292355
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.0290271
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.0288777
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.0286619
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.0285402
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.0283187
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.0280825
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.0278557
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.0275935
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.0275074
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.027317
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.0272349
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.0271611
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.0270588
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.026983
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.0267715
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.0266382
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.0265368
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.0264136
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.0262949
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.0261782
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.0260357
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.0259547
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.0258591
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.0257545
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.0256022
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.0254758
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.0254844
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.0253812
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.0252907
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.0251725
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.0250646
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.0249531
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.0249324
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.0248035
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.0247252
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.0246146
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.0245621
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.0245312
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.0244625
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.0244221
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.0243734
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.0243476
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.0243629
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.0243458
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.024384
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.0243649
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.0243538
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.0243437
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.0242853
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.0242252
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.0241962
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.0241498
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.0241052
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.0240851
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 0.0240568
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 0.024053
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 0.0240399
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 0.0240196
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[116]	valid_0's binary_logloss: 0.0240652
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[117]	valid_0's binary_logloss: 0.0240304
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[118]	valid_0's binary_logloss: 0.0239913
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[119]	valid_0's binary_logloss: 0.023987
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[120]	valid_0's binary_logloss: 0.0240035
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[121]	valid_0's binary_logloss: 0.0240367
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[122]	valid_0's binary_logloss: 0.0240424
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[123]	valid_0's binary_logloss: 0.0239915
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[124]	valid_0's binary_logloss: 0.0240339
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[125]	valid_0's binary_logloss: 0.0239958
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[126]	valid_0's binary_logloss: 0.0239671
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[127]	valid_0's binary_logloss: 0.0239336
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[128]	valid_0's binary_logloss: 0.0238579
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[129]	valid_0's binary_logloss: 0.0238507
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[130]	valid_0's binary_logloss: 0.0237983
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[131]	valid_0's binary_logloss: 0.0237948
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[132]	valid_0's binary_logloss: 0.0237961
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[133]	valid_0's binary_logloss: 0.0237669
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[134]	valid_0's binary_logloss: 0.0237485
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[135]	valid_0's binary_logloss: 0.023721
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[136]	valid_0's binary_logloss: 0.0237044
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[137]	valid_0's binary_logloss: 0.0237277
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[138]	valid_0's binary_logloss: 0.0237799
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[139]	valid_0's binary_logloss: 0.023747
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[140]	valid_0's binary_logloss: 0.0237498
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[141]	valid_0's binary_logloss: 0.023736
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[142]	valid_0's binary_logloss: 0.023758
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[143]	valid_0's binary_logloss: 0.0237888
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[144]	valid_0's binary_logloss: 0.0237483
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[145]	valid_0's binary_logloss: 0.0237731
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[146]	valid_0's binary_logloss: 0.0237706
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[147]	valid_0's binary_logloss: 0.0237684
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[148]	valid_0's binary_logloss: 0.02373
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[149]	valid_0's binary_logloss: 0.0236948
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[150]	valid_0's binary_logloss: 0.0236643
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[151]	valid_0's binary_logloss: 0.0236431
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[152]	valid_0's binary_logloss: 0.023605
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[153]	valid_0's binary_logloss: 0.0235597
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[154]	valid_0's binary_logloss: 0.023481
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[155]	valid_0's binary_logloss: 0.0234252
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[156]	valid_0's binary_logloss: 0.0233987
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[157]	valid_0's binary_logloss: 0.0234121
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[158]	valid_0's binary_logloss: 0.0233934
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[159]	valid_0's binary_logloss: 0.0234041
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[160]	valid_0's binary_logloss: 0.0234077
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[161]	valid_0's binary_logloss: 0.0234348
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[162]	valid_0's binary_logloss: 0.0234671
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[163]	valid_0's binary_logloss: 0.0234822
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[164]	valid_0's binary_logloss: 0.0235165
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[165]	valid_0's binary_logloss: 0.0235327
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[166]	valid_0's binary_logloss: 0.0235481
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[167]	valid_0's binary_logloss: 0.0235087
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[168]	valid_0's binary_logloss: 0.023495
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[169]	valid_0's binary_logloss: 0.023463
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[170]	valid_0's binary_logloss: 0.0234234
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[171]	valid_0's binary_logloss: 0.0234475
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[172]	valid_0's binary_logloss: 0.0234755
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[173]	valid_0's binary_logloss: 0.0234792
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[174]	valid_0's binary_logloss: 0.02346
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[175]	valid_0's binary_logloss: 0.0234866
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[176]	valid_0's binary_logloss: 0.0234567
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[177]	valid_0's binary_logloss: 0.0234375
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[178]	valid_0's binary_logloss: 0.0234364
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[179]	valid_0's binary_logloss: 0.0234346
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[180]	valid_0's binary_logloss: 0.0234405
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[181]	valid_0's binary_logloss: 0.0234303
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[182]	valid_0's binary_logloss: 0.0234606
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[183]	valid_0's binary_logloss: 0.0234671
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[184]	valid_0's binary_logloss: 0.023457
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

Trening klas:  79%|███████▉  | 397/500 [46:04<07:33,  4.40s/klasa, klasa=class_397, F1_klasy=0.6667, F1_macro=0.6495, drzewa=158]




Trening klas:  80%|███████▉  | 398/500 [46:04<08:40,  5.10s/klasa, klasa=class_397, F1_klasy=0.6667, F1_macro=0.6495, drzewa=158]

[185]	valid_0's binary_logloss: 0.0234455
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[186]	valid_0's binary_logloss: 0.0234252
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[187]	valid_0's binary_logloss: 0.0234185
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[188]	valid_0's binary_logloss: 0.0234031
[1]	valid_0's binary_logloss: 0.251316
[2]	valid_0's binary_logloss: 0.161189
[3]	valid_0's binary_logloss: 0.144271
[4]	valid_0's binary_logloss: 0.135849
[5]	valid_0's binary_logloss: 0.127992
[6]	valid_0's binary_logloss: 0.12264
[7]	valid_0's binary_logloss: 0.112719
[8]	valid_0's binary_logloss: 0.108006
[9]	valid_0's binary_logloss: 0.105386
[10]	valid_0's binary_logloss: 0.102941
[11]	valid_0's binary_logloss: 0.101105
[12]	valid_0's binary_logloss: 0.0994244
[13]	valid_0's binary_logloss: 0.0981666
[14]	valid_0's binary_logloss: 0.0968291
[15]	valid_0's binary_logloss: 0.095593
[16]	valid_0's binary_logloss: 0.0919526
[17]	valid_0's binary_logloss: 0.0896709
[18]	valid_0's binary_logloss: 0.0838289
[19]	valid_0's binary_logloss: 0.0809427
[20]	valid_0's binary_logloss: 0.0790346
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0784828
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0771275
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.0756215
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0746219
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.0737345
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.0716469
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.0708107
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.0685134
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.0674412
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.0663423
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.0653789
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.0644665
[33]	valid_0's binary_logloss: 0.0636348
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.0624322
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.0617952
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.0611228
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.0605645
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.0598996
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.0595286
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.0593015
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.0577817
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.0569507
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.0563629
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.0557867
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.0552881
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.0545565
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.054266
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.0536653
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.0533616
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.0530143
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.0527181
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.052505
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.0519442
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.051739
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.0517707
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.0509913
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.0503675
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.0502145
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.0501374
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.0493586
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.0483909
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.0473365
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.0463021
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.0454731
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.0445761
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.0442054
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.0441324
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.0437617
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.0434711
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.0432757
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.0431755
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.0428575
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.0427475
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.0427011
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.0422904
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.042072
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.0417783
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.0414268
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.0411234
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.0406662
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.0406574
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.0405553
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.0407175
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.0406649
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.040634
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.0403594
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.0398882
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.0395099
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.0392963
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.0389787
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.0389784
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.0388881
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.0388552
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.0388498
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.0387883
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.0388198
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.0389346
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.0391029
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.0388724
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.0389368
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.0390168
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.0390583
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.0392848
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.0393673
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.0395713
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.0394683
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.039573
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.0394646
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.0392997
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.0390433
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.0389681
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 0.0391109
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 0.038818
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 0.038856
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 0.0390196
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[116]	valid_0's binary_logloss: 0.038596
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[117]	valid_0's binary_logloss: 0.0386749
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[118]	valid_0's binary_logloss: 0.0386328
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[119]	valid_0's binary_logloss: 0.0386258
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[120]	valid_0's binary_logloss: 0.0384974
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[121]	valid_0's binary_logloss: 0.0386553
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[122]	valid_0's binary_logloss: 0.0387952
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[123]	valid_0's binary_logloss: 0.0389385
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[124]	valid_0's binary_logloss: 0.0390567
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[125]	valid_0's binary_logloss: 0.0390357
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[126]	valid_0's binary_logloss: 0.038847
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[127]	valid_0's binary_logloss: 0.0385411
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[128]	valid_0's binary_logloss: 0.0381298
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[129]	valid_0's binary_logloss: 0.0378877
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[130]	valid_0's binary_logloss: 0.0374624
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[131]	valid_0's binary_logloss: 0.0372723
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[132]	valid_0's binary_logloss: 0.0370673
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[133]	valid_0's binary_logloss: 0.0369097
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[134]	valid_0's binary_logloss: 0.0367496
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[135]	valid_0's binary_logloss: 0.036574
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[136]	valid_0's binary_logloss: 0.0367198
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[137]	valid_0's binary_logloss: 0.0366465
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[138]	valid_0's binary_logloss: 0.036698
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[139]	valid_0's binary_logloss: 0.0368157
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[140]	valid_0's binary_logloss: 0.0369333
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[141]	valid_0's binary_logloss: 0.0370367
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[142]	valid_0's binary_logloss: 0.0371868
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[143]	valid_0's binary_logloss: 0.0372643
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[144]	valid_0's binary_logloss: 0.0372274
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[145]	valid_0's binary_logloss: 0.0373243
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[146]	valid_0's binary_logloss: 0.0372102
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[147]	valid_0's binary_logloss: 0.0373426
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[148]	valid_0's binary_logloss: 0.0371846
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[149]	valid_0's binary_logloss: 0.0371298
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[150]	valid_0's binary_logloss: 0.0370817
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[151]	valid_0's binary_logloss: 0.0368948
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[152]	valid_0's binary_logloss: 0.0367007
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[153]	valid_0's binary_logloss: 0.0365403
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[154]	valid_0's binary_logloss: 0.0362898
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[155]	valid_0's binary_logloss: 0.0360452
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[156]	valid_0's binary_logloss: 0.036067
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[157]	valid_0's binary_logloss: 0.0360024
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[158]	valid_0's binary_logloss: 0.0358585
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[159]	valid_0's binary_logloss: 0.0356968
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[160]	valid_0's binary_logloss: 0.0356007
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[161]	valid_0's binary_logloss: 0.035521
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[162]	valid_0's binary_logloss: 0.0355831
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[163]	valid_0's binary_logloss: 0.0355406
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[164]	valid_0's binary_logloss: 0.0355044
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[165]	valid_0's binary_logloss: 0.0355452
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[166]	valid_0's binary_logloss: 0.0352269
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[167]	valid_0's binary_logloss: 0.0348634
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[168]	valid_0's binary_logloss: 0.0346699
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[169]	valid_0's binary_logloss: 0.0343593
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[170]	valid_0's binary_logloss: 0.0339496
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[171]	valid_0's binary_logloss: 0.0338409
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[172]	valid_0's binary_logloss: 0.0336486
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[173]	valid_0's binary_logloss: 0.0335889
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[174]	valid_0's binary_logloss: 0.0334159
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[175]	valid_0's binary_logloss: 0.033328
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[176]	valid_0's binary_logloss: 0.0332782
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[177]	valid_0's binary_logloss: 0.0330795
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[178]	valid_0's binary_logloss: 0.0329735
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[179]	valid_0's binary_logloss: 0.0328353
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[180]	valid_0's binary_logloss: 0.032825
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[181]	valid_0's binary_logloss: 0.0328029
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[182]	valid_0's binary_logloss: 0.0328124

Trening klas:  80%|███████▉  | 398/500 [46:13<08:40,  5.10s/klasa, klasa=class_398, F1_klasy=0.4818, F1_macro=0.6491, drzewa=245]




Trening klas:  80%|███████▉  | 399/500 [46:13<10:54,  6.48s/klasa, klasa=class_398, F1_klasy=0.4818, F1_macro=0.6491, drzewa=245]

[273]	valid_0's binary_logloss: 0.0322444
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[274]	valid_0's binary_logloss: 0.0323397
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[275]	valid_0's binary_logloss: 0.0324042
[1]	valid_0's binary_logloss: 0.026017
[2]	valid_0's binary_logloss: 0.0162238
[3]	valid_0's binary_logloss: 0.0148393
[4]	valid_0's binary_logloss: 0.0136624
[5]	valid_0's binary_logloss: 0.0128036
[6]	valid_0's binary_logloss: 0.0121145
[7]	valid_0's binary_logloss: 0.011458
[8]	valid_0's binary_logloss: 0.0108769
[9]	valid_0's binary_logloss: 0.0103534
[10]	valid_0's binary_logloss: 0.00988483
[11]	valid_0's binary_logloss: 0.00946658
[12]	valid_0's binary_logloss: 0.00907856
[13]	valid_0's binary_logloss: 0.0087153
[14]	valid_0's binary_logloss: 0.00840044
[15]	valid_0's binary_logloss: 0.00811117
[16]	valid_0's binary_logloss: 0.00782508
[17]	valid_0's binary_logloss: 0.00755083
[18]	valid_0's binary_logloss: 0.00730167
[19]	valid_0's binary_logloss: 0.00705956
[20]	valid_0's binary_logloss: 0.00683786
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.00664078
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.00646214
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.00630072
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.00613711
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.00598565
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.00582632
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.00569526
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.00555404
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.00542161
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.00529729
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.0051836
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.00507147
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.00496616
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.00485002
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.00475556
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.00467876
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.00460048
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.00452948
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.00446793
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.00441114
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.00433284
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.00427805
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.00420302
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.00415203
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.00410477
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.00404864
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.00399645
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.00396656
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.00391493
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.00386805
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.00383436
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.00380483
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.00377709
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.00374314
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.0037207
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.0036794
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.00366131
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.00364381
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.00363303
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.00361636
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.00356673
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.00353375
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.00350823
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.00349525
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.00348524
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.00347918
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.00347981
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.00347454
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.00347028
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.00345082
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.00344741
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.00344831
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.00343313
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.00343372
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.00342953
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.00342506
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.00342169
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.00341872
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.00341004
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.00340373
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.00341189
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.00342186
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.00343306
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.00344417
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.00345378
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.00346319
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.00347666
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.00348736
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.00349176
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.00350594
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.00352343
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.00351158
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.00351405
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.00352619
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.00352511
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.00353683
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.00354582
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.00355801
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.00356934
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.00358091
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.00358455
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.00358884
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.00359352
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.0035995
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.00360441
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.00361988
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.00361965
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.00363595
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.0036524
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.00366179

Trening klas:  80%|███████▉  | 399/500 [46:17<10:54,  6.48s/klasa, klasa=class_399, F1_klasy=0.8571, F1_macro=0.6496, drzewa=80]




Trening klas:  80%|████████  | 400/500 [46:17<09:15,  5.56s/klasa, klasa=class_399, F1_klasy=0.8571, F1_macro=0.6496, drzewa=80]

[1]	valid_0's binary_logloss: 0.126551
[2]	valid_0's binary_logloss: 0.071081
[3]	valid_0's binary_logloss: 0.0678327
[4]	valid_0's binary_logloss: 0.0651487
[5]	valid_0's binary_logloss: 0.0630319
[6]	valid_0's binary_logloss: 0.107533
[7]	valid_0's binary_logloss: 0.104
[8]	valid_0's binary_logloss: 0.0976958
[9]	valid_0's binary_logloss: 0.0937155
[10]	valid_0's binary_logloss: 0.0910365
[11]	valid_0's binary_logloss: 0.086995
[12]	valid_0's binary_logloss: 0.0827948
[13]	valid_0's binary_logloss: 0.0787297
[14]	valid_0's binary_logloss: 0.0749872
[15]	valid_0's binary_logloss: 0.0720409
[16]	valid_0's binary_logloss: 0.0689062
[17]	valid_0's binary_logloss: 0.0671078
[18]	valid_0's binary_logloss: 0.0653077
[19]	valid_0's binary_logloss: 0.0635544
[20]	valid_0's binary_logloss: 0.0615173
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0602293
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0587722
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.0572451
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0563361
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.0556682
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.0541364
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.0530872
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.0519233
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.050517
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.0494768
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.0483243
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.0472811
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.0461489
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.0450495
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.0442588
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.0434396
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.0427147
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.0418324
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.0410768
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.0404278
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.0392682
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.0381553
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.0370401
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.0355695
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.0345319
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.0339584
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.0334712
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.0329735
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.0323785
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.0311871
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.0305997
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.0299458
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.0291891
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.0286733
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.0281991
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.0279212
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.0275034
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.0271479
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.0268464
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.0265635
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.0260044
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.025691
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.0252844
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.0250471
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.024705
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.0244091
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.0241083
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.0237999
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.0235717
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.0232122
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.022801
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.0223735
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.0219612
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.0215728
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.0212955
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.0209836
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.0207242
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.0205423
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.0202852
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.0200399
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.0198632
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.0196286
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.0193846
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.0191471
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.0189161
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.0186824
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.0184416
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.0181974
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.0179531
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.017752
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.0176138
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.017352
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.0171542
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.0168892
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.0166469
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.0163861
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.0162749
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.0160647
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.0158888
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.015677
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.015533
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.0154067
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.0152669
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.0151479
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.0149225
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.0148279
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.0147773
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.0146924
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.0146178
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.0145414
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.0144586
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 0.014367
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 0.0143377
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 0.0142271
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 0.0140019
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[116]	valid_0's binary_logloss: 0.0138252
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[117]	valid_0's binary_logloss: 0.0136573
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[118]	valid_0's binary_logloss: 0.0135043
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[119]	valid_0's binary_logloss: 0.0134058
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[120]	valid_0's binary_logloss: 0.0132851
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[121]	valid_0's binary_logloss: 0.0131598
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[122]	valid_0's binary_logloss: 0.0131188
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[123]	valid_0's binary_logloss: 0.0130335
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[124]	valid_0's binary_logloss: 0.0129416
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[125]	valid_0's binary_logloss: 0.0128599
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[126]	valid_0's binary_logloss: 0.0128544
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[127]	valid_0's binary_logloss: 0.0128289
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[128]	valid_0's binary_logloss: 0.0127872
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[129]	valid_0's binary_logloss: 0.0128376
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[130]	valid_0's binary_logloss: 0.0127714
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[131]	valid_0's binary_logloss: 0.0126954
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[132]	valid_0's binary_logloss: 0.0125649
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[133]	valid_0's binary_logloss: 0.0124381
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[134]	valid_0's binary_logloss: 0.0123268
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[135]	valid_0's binary_logloss: 0.0122945
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[136]	valid_0's binary_logloss: 0.012182
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[137]	valid_0's binary_logloss: 0.0121
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[138]	valid_0's binary_logloss: 0.0120336
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[139]	valid_0's binary_logloss: 0.0119776
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[140]	valid_0's binary_logloss: 0.0118723
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[141]	valid_0's binary_logloss: 0.011837
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[142]	valid_0's binary_logloss: 0.0118128
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[143]	valid_0's binary_logloss: 0.0117748
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[144]	valid_0's binary_logloss: 0.0117364
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[145]	valid_0's binary_logloss: 0.0117227
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[146]	valid_0's binary_logloss: 0.0116252
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[147]	valid_0's binary_logloss: 0.0115856
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[148]	valid_0's binary_logloss: 0.01154
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[149]	valid_0's binary_logloss: 0.0115316
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[150]	valid_0's binary_logloss: 0.0114854
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[151]	valid_0's binary_logloss: 0.0114738
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[152]	valid_0's binary_logloss: 0.0114255
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[153]	valid_0's binary_logloss: 0.0113854
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[154]	valid_0's binary_logloss: 0.0113437
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[155]	valid_0's binary_logloss: 0.0113006
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[156]	valid_0's binary_logloss: 0.011265
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[157]	valid_0's binary_logloss: 0.0112483
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[158]	valid_0's binary_logloss: 0.0112036
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[159]	valid_0's binary_logloss: 0.0112079
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[160]	valid_0's binary_logloss: 0.0111545
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[161]	valid_0's binary_logloss: 0.0111341
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[162]	valid_0's binary_logloss: 0.0111167
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[163]	valid_0's binary_logloss: 0.0110921
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[164]	valid_0's binary_logloss: 0.011064
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[165]	valid_0's binary_logloss: 0.0110337
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[166]	valid_0's binary_logloss: 0.0109619
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[167]	valid_0's binary_logloss: 0.0108923
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[168]	valid_0's binary_logloss: 0.0108488
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[169]	valid_0's binary_logloss: 0.0107784
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[170]	valid_0's binary_logloss: 0.0107089
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[171]	valid_0's binary_logloss: 0.0106482
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[172]	valid_0's binary_logloss: 0.0106161
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[173]	valid_0's binary_logloss: 0.0105808
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[174]	valid_0's binary_logloss: 0.0105292
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[175]	valid_0's binary_logloss: 0.0104924
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[176]	valid_0's binary_logloss: 0.0104652
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[177]	valid_0's binary_logloss: 0.0104381
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[178]	valid_0's binary_logloss: 0.0104331
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[179]	valid_0's binary_logloss: 0.010428
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[180]	valid_0's binary_logloss: 0.0104166
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[181]	valid_0's binary_logloss: 0.0103833
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[182]	valid_0's binary_logloss: 0.0103492
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[183]	valid_0's binary_logloss: 0.0103083
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[184]	valid_0's binary_logloss: 0.0102782
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

Trening klas:  80%|████████  | 400/500 [46:23<09:15,  5.56s/klasa, klasa=class_400, F1_klasy=0.7895, F1_macro=0.6499, drzewa=297]




Trening klas:  80%|████████  | 401/500 [46:23<09:33,  5.80s/klasa, klasa=class_400, F1_klasy=0.7895, F1_macro=0.6499, drzewa=297]

[300]	valid_0's binary_logloss: 0.00929617
[1]	valid_0's binary_logloss: 0.324343
[2]	valid_0's binary_logloss: 0.253849
[3]	valid_0's binary_logloss: 0.238421
[4]	valid_0's binary_logloss: 0.227406
[5]	valid_0's binary_logloss: 0.219574
[6]	valid_0's binary_logloss: 0.339009
[7]	valid_0's binary_logloss: 0.283369
[8]	valid_0's binary_logloss: 0.271163
[9]	valid_0's binary_logloss: 0.259533
[10]	valid_0's binary_logloss: 0.24829
[11]	valid_0's binary_logloss: 0.25
[12]	valid_0's binary_logloss: 0.239304
[13]	valid_0's binary_logloss: 0.232669
[14]	valid_0's binary_logloss: 0.227131
[15]	valid_0's binary_logloss: 0.221859
[16]	valid_0's binary_logloss: 0.220511
[17]	valid_0's binary_logloss: 0.214474
[18]	valid_0's binary_logloss: 0.209418
[19]	valid_0's binary_logloss: 0.204733
[20]	valid_0's binary_logloss: 0.200154
[21]	valid_0's binary_logloss: 0.196465
[22]	valid_0's binary_logloss: 0.192267
[23]	valid_0's binary_logloss: 0.188216
[24]	valid_0's binary_logloss: 0.184444
[25]	valid_0's binary_logloss: 0.180873
[26]	valid_0's binary_logloss: 0.177402
[27]	valid_0's binary_logloss: 0.17374
[28]	valid_0's binary_logloss: 0.170036
[29]	valid_0's binary_logloss: 0.166702
[30]	valid_0's binary_logloss: 0.163466
[31]	valid_0's binary_logloss: 0.160605
[32]	valid_0's binary_logloss: 0.158247
[33]	valid_0's binary_logloss: 0.155772
[34]	valid_0's binary_logloss: 0.153336
[35]	valid_0's binary_logloss: 0.151031
[36]	valid_0's binary_logloss: 0.148998
[37]	valid_0's binary_logloss: 0.147211
[38]	valid_0's binary_logloss: 0.14537
[39]	valid_0's binary_logloss: 0.143473
[40]	valid_0's binary_logloss: 0.14177
[41]	valid_0's binary_logloss: 0.139686
[42]	valid_0's binary_logloss: 0.138013
[43]	valid_0's binary_logloss: 0.136204
[44]	valid_0's binary_logloss: 0.134469
[45]	valid_0's binary_logloss: 0.132974
[46]	valid_0's binary_logloss: 0.131205
[47]	valid_0's binary_logloss: 0.129551
[48]	valid_0's binary_logloss: 0.127882
[49]	valid_0's binary_logloss: 0.126674
[50]	valid_0's binary_logloss: 0.125446
[51]	valid_0's binary_logloss: 0.124112
[52]	valid_0's binary_logloss: 0.122938
[53]	valid_0's binary_logloss: 0.12173
[54]	valid_0's binary_logloss: 0.120989
[55]	valid_0's binary_logloss: 0.119898
[56]	valid_0's binary_logloss: 0.118863
[57]	valid_0's binary_logloss: 0.118026
[58]	valid_0's binary_logloss: 0.116893
[59]	valid_0's binary_logloss: 0.116033
[60]	valid_0's binary_logloss: 0.115125
[61]	valid_0's binary_logloss: 0.114025
[62]	valid_0's binary_logloss: 0.113113
[63]	valid_0's binary_logloss: 0.112106
[64]	valid_0's binary_logloss: 0.111105
[65]	valid_0's binary_logloss: 0.110123
[66]	valid_0's binary_logloss: 0.109355
[67]	valid_0's binary_logloss: 0.108727
[68]	valid_0's binary_logloss: 0.10805
[69]	valid_0's binary_logloss: 0.107635
[70]	valid_0's binary_logloss: 0.106845
[71]	valid_0's binary_logloss: 0.106326
[72]	valid_0's binary_logloss: 0.105595
[73]	valid_0's binary_logloss: 0.104882
[74]	valid_0's binary_logloss: 0.10408
[75]	valid_0's binary_logloss: 0.103498
[76]	valid_0's binary_logloss: 0.102892
[77]	valid_0's binary_logloss: 0.102258
[78]	valid_0's binary_logloss: 0.101626
[79]	valid_0's binary_logloss: 0.10103
[80]	valid_0's binary_logloss: 0.100579
[81]	valid_0's binary_logloss: 0.100166
[82]	valid_0's binary_logloss: 0.099731
[83]	valid_0's binary_logloss: 0.0989543
[84]	valid_0's binary_logloss: 0.098429
[85]	valid_0's binary_logloss: 0.0978172
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.0975024
[87]	valid_0's binary_logloss: 0.0970904
[88]	valid_0's binary_logloss: 0.0966859
[89]	valid_0's binary_logloss: 0.0962013
[90]	valid_0's binary_logloss: 0.0957116
[91]	valid_0's binary_logloss: 0.0951178
[92]	valid_0's binary_logloss: 0.0947421
[93]	valid_0's binary_logloss: 0.0942874
[94]	valid_0's binary_logloss: 0.0938494
[95]	valid_0's binary_logloss: 0.0933205
[96]	valid_0's binary_logloss: 0.093069
[97]	valid_0's binary_logloss: 0.0928501
[98]	valid_0's binary_logloss: 0.0927821
[99]	valid_0's binary_logloss: 0.0924265
[100]	valid_0's binary_logloss: 0.0922332
[101]	valid_0's binary_logloss: 0.0920223
[102]	valid_0's binary_logloss: 0.0917487
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.0914922
[104]	valid_0's binary_logloss: 0.0911632
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.0910254
[106]	valid_0's binary_logloss: 0.0907821
[107]	valid_0's binary_logloss: 0.0905345
[108]	valid_0's binary_logloss: 0.0903287
[109]	valid_0's binary_logloss: 0.0901151
[110]	valid_0's binary_logloss: 0.0899928
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.089794
[112]	valid_0's binary_logloss: 0.0895694
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 0.0894555
[114]	valid_0's binary_logloss: 0.0892841
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 0.0890843
[116]	valid_0's binary_logloss: 0.0887529
[117]	valid_0's binary_logloss: 0.0885829
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[118]	valid_0's binary_logloss: 0.0883453
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[119]	valid_0's binary_logloss: 0.088049
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[120]	valid_0's binary_logloss: 0.087872
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[121]	valid_0's binary_logloss: 0.087814
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[122]	valid_0's binary_logloss: 0.0878481
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[123]	valid_0's binary_logloss: 0.0878077
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[124]	valid_0's binary_logloss: 0.0877268
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[125]	valid_0's binary_logloss: 0.0876404
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[126]	valid_0's binary_logloss: 0.0874172
[127]	valid_0's binary_logloss: 0.0872198
[128]	valid_0's binary_logloss: 0.0872394
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[129]	valid_0's binary_logloss: 0.0871008
[130]	valid_0's binary_logloss: 0.0870479
[131]	valid_0's binary_logloss: 0.0869337
[132]	valid_0's binary_logloss: 0.0866618
[133]	valid_0's binary_logloss: 0.0864478
[134]	valid_0's binary_logloss: 0.0863316
[135]	valid_0's binary_logloss: 0.0862274
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[136]	valid_0's binary_logloss: 0.086154
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[137]	valid_0's binary_logloss: 0.0860607
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[138]	valid_0's binary_logloss: 0.0858886
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[139]	valid_0's binary_logloss: 0.0857464
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[140]	valid_0's binary_logloss: 0.0856666
[141]	valid_0's binary_logloss: 0.0855409
[142]	valid_0's binary_logloss: 0.085644
[143]	valid_0's binary_logloss: 0.0852654
[144]	valid_0's binary_logloss: 0.0852809
[145]	valid_0's binary_logloss: 0.0850173
[146]	valid_0's binary_logloss: 0.084886
[147]	valid_0's binary_logloss: 0.0846409
[148]	valid_0's binary_logloss: 0.0846484
[149]	valid_0's binary_logloss: 0.0847701
[150]	valid_0's binary_logloss: 0.0846234
[151]	valid_0's binary_logloss: 0.0844654
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[152]	valid_0's binary_logloss: 0.0843629
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[153]	valid_0's binary_logloss: 0.0842893
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[154]	valid_0's binary_logloss: 0.0842266
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[155]	valid_0's binary_logloss: 0.0841721
[156]	valid_0's binary_logloss: 0.0841065
[157]	valid_0's binary_logloss: 0.084178
[158]	valid_0's binary_logloss: 0.084027
[159]	valid_0's binary_logloss: 0.0838968
[160]	valid_0's binary_logloss: 0.0837906
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[161]	valid_0's binary_logloss: 0.083667
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[162]	valid_0's binary_logloss: 0.083525
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[163]	valid_0's binary_logloss: 0.0834321
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[164]	valid_0's binary_logloss: 0.0833321
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[165]	valid_0's binary_logloss: 0.0832286
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[166]	valid_0's binary_logloss: 0.0831038
[167]	valid_0's binary_logloss: 0.0830844
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[168]	valid_0's binary_logloss: 0.0830655
[169]	valid_0's binary_logloss: 0.0830371
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[170]	valid_0's binary_logloss: 0.0830998
[171]	valid_0's binary_logloss: 0.0831464
[172]	valid_0's binary_logloss: 0.0831636
[173]	valid_0's binary_logloss: 0.0831689
[174]	valid_0's binary_logloss: 0.0831885
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[175]	valid_0's binary_logloss: 0.0831548
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[176]	valid_0's binary_logloss: 0.0831324
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[177]	valid_0's binary_logloss: 0.0830791
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[178]	valid_0's binary_logloss: 0.0830321
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[179]	valid_0's binary_logloss: 0.083118
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[180]	valid_0's binary_logloss: 0.0832303
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[181]	valid_0's binary_logloss: 0.0831349
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[182]	valid_0's binary_logloss: 0.0831086
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[183]	valid_0's binary_logloss: 0.0831396
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[184]	valid_0's binary_logloss: 0.0831037
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[185]	valid_0's binary_logloss: 0.0829667
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[186]	valid_0's binary_logloss: 0.083102
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[187]	valid_0's binary_logloss: 0.0831393
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[188]	valid_0's binary_logloss: 0.0831323
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[189]	valid_0's binary_logloss: 0.0832197
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[190]	valid_0's binary_logloss: 0.0832153
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[191]	valid_0's binary_logloss: 0.0833829
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[192]	valid_0's binary_logloss: 0.0831889
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[193]	valid_0's binary_logloss: 0.0830332
[194]	valid_0's binary_logloss: 0.0830359
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[195]	valid_0's binary_logloss: 0.0829706
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[196]	valid_0's binary_logloss: 0.0829644
[197]	valid_0's binary_logloss: 0.0828946
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[198]	valid_0's binary_logloss: 0.0829036
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[199]	valid_0's binary_logloss: 0.082917
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[200]	valid_0's binary_logloss: 0.0828004
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[201]	valid_0's binary_logloss: 0.0827945
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[202]	valid_0's binary_logloss: 0.0827229
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[203]	valid_0's binary_logloss: 0.0826814
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[204]	valid_0's binary_logloss: 0.0825672
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[205]	valid_0's binary_logloss: 0.0825867
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[206]	valid_0's binary_logloss: 0.082452
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[207]	valid_0's binary_logloss: 0.0823731
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[208]	valid_0's binary_logloss: 0.0823688
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[209]	valid_0's binary_logloss: 0.0822843
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[210]	valid_0's binary_logloss: 0.0822225
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[211]	valid_0's binary_logloss: 0.0821127
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[212]	valid_0's binary_logloss: 0.0820816
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[213]	valid_0's binary_logloss: 0.0820872
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[214]	valid_0's binary_logloss: 0.0820309
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[215]	valid_0's binary_logloss: 0.0819248
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[216]	valid_0's binary_logloss: 0.0818877
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[217]	valid_0's binary_logloss: 0.0819898
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[218]	valid_0's binary_logloss: 0.0820647
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[219]	valid_0's binary_logloss: 0.082136
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[220]	valid_0's binary_logloss: 0.0821938
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[221]	valid_0's binary_logloss: 0.0820869
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[222]	valid_0's binary_logloss: 0.0820687
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[223]	valid_0's binary_logloss: 0.0820764
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[224]	valid_0's binary_logloss: 0.0820607
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[225]	valid_0's binary_logloss: 0.0820423
[226]	valid_0's binary_logloss: 0.0819132
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[227]	valid_0's binary_logloss: 0.081839
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[228]	valid_0's binary_logloss: 0.081769
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[229]	valid_0's binary_logloss: 0.0818518
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[230]	valid_0's binary_logloss: 0.0819239
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[231]	valid_0's binary_logloss: 0.0819643
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[232]	valid_0's binary_logloss: 0.0820521
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[233]	valid_0's binary_logloss: 0.0819815
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[234]	valid_0's binary_logloss: 0.0818684
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[235]	valid_0's binary_logloss: 0.0818618
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[236]	valid_0's binary_logloss: 0.0817669
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[237]	valid_0's binary_logloss: 0.0816744
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[238]	valid_0's binary_logloss: 0.0815742
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[239]	valid_0's binary_logloss: 0.0815664
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[240]	valid_0's binary_logloss: 0.0815744
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[241]	valid_0's binary_logloss: 0.0816373
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[242]	valid_0's binary_logloss: 0.0817382
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[243]	valid_0's binary_logloss: 0.0818626
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[244]	valid_0's binary_logloss: 0.0817263
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[245]	valid_0's binary_logloss: 0.0815751
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[246]	valid_0's binary_logloss: 0.0815611
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[247]	valid_0's binary_logloss: 0.0816553
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[248]	valid_0's binary_logloss: 0.0817341
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[249]	valid_0's binary_logloss: 0.081832
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[250]	valid_0's binary_logloss: 0.0817604
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[251]	valid_0's binary_logloss: 0.0816659
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[252]	valid_0's binary_logloss: 0.0817176
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[253]	valid_0's binary_logloss: 0.0817392
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[254]	valid_0's binary_logloss: 0.0816954
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[255]	valid_0's binary_logloss: 0.0816083
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[256]	valid_0's binary_logloss: 0.0814044
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[257]	valid_0's binary_logloss: 0.0814398
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[258]	valid_0's binary_logloss: 0.0815397
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[259]	valid_0's binary_logloss: 0.0815488
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[260]	valid_0's binary_logloss: 0.0814186
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[261]	valid_0's binary_logloss: 0.0814412
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[262]	valid_0's binary_logloss: 0.0815545
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[263]	valid_0's binary_logloss: 0.0816391
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[264]	valid_0's binary_logloss: 0.081764
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

Trening klas:  80%|████████  | 401/500 [46:39<09:33,  5.80s/klasa, klasa=class_401, F1_klasy=0.1200, F1_macro=0.6486, drzewa=256]




Trening klas:  80%|████████  | 402/500 [46:39<14:37,  8.95s/klasa, klasa=class_401, F1_klasy=0.1200, F1_macro=0.6486, drzewa=256]

[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[285]	valid_0's binary_logloss: 0.0820997
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[286]	valid_0's binary_logloss: 0.081969
[1]	valid_0's binary_logloss: 0.311295
[2]	valid_0's binary_logloss: 0.275776
[3]	valid_0's binary_logloss: 0.249145
[4]	valid_0's binary_logloss: 0.23017
[5]	valid_0's binary_logloss: 0.215684
[6]	valid_0's binary_logloss: 0.260408
[7]	valid_0's binary_logloss: 0.234323
[8]	valid_0's binary_logloss: 0.220618
[9]	valid_0's binary_logloss: 0.208923
[10]	valid_0's binary_logloss: 0.199034
[11]	valid_0's binary_logloss: 0.190008
[12]	valid_0's binary_logloss: 0.182602
[13]	valid_0's binary_logloss: 0.173646
[14]	valid_0's binary_logloss: 0.165653
[15]	valid_0's binary_logloss: 0.159234
[16]	valid_0's binary_logloss: 0.173342
[17]	valid_0's binary_logloss: 0.16759
[18]	valid_0's binary_logloss: 0.163002
[19]	valid_0's binary_logloss: 0.159256
[20]	valid_0's binary_logloss: 0.154998
[21]	valid_0's binary_logloss: 0.151524
[22]	valid_0's binary_logloss: 0.148049
[23]	valid_0's binary_logloss: 0.144054
[24]	valid_0's binary_logloss: 0.139805
[25]	valid_0's binary_logloss: 0.135978
[26]	valid_0's binary_logloss: 0.12906
[27]	valid_0's binary_logloss: 0.125729
[28]	valid_0's binary_logloss: 0.122721
[29]	valid_0's binary_logloss: 0.119793
[30]	valid_0's binary_logloss: 0.116329
[31]	valid_0's binary_logloss: 0.114218
[32]	valid_0's binary_logloss: 0.112409
[33]	valid_0's binary_logloss: 0.110558
[34]	valid_0's binary_logloss: 0.109161
[35]	valid_0's binary_logloss: 0.107587
[36]	valid_0's binary_logloss: 0.106141
[37]	valid_0's binary_logloss: 0.104867
[38]	valid_0's binary_logloss: 0.103304
[39]	valid_0's binary_logloss: 0.10227
[40]	valid_0's binary_logloss: 0.100977
[41]	valid_0's binary_logloss: 0.0992071
[42]	valid_0's binary_logloss: 0.0978871
[43]	valid_0's binary_logloss: 0.0963457
[44]	valid_0's binary_logloss: 0.0951646
[45]	valid_0's binary_logloss: 0.093957
[46]	valid_0's binary_logloss: 0.0931721
[47]	valid_0's binary_logloss: 0.0923158
[48]	valid_0's binary_logloss: 0.0915721
[49]	valid_0's binary_logloss: 0.0907924
[50]	valid_0's binary_logloss: 0.0903201
[51]	valid_0's binary_logloss: 0.0894877
[52]	valid_0's binary_logloss: 0.0887805
[53]	valid_0's binary_logloss: 0.088126
[54]	valid_0's binary_logloss: 0.0874195
[55]	valid_0's binary_logloss: 0.0867695
[56]	valid_0's binary_logloss: 0.0859071
[57]	valid_0's binary_logloss: 0.0850486
[58]	valid_0's binary_logloss: 0.0842605
[59]	valid_0's binary_logloss: 0.0835387
[60]	valid_0's binary_logloss: 0.08293
[61]	valid_0's binary_logloss: 0.0824152
[62]	valid_0's binary_logloss: 0.0821595
[63]	valid_0's binary_logloss: 0.0817763
[64]	valid_0's binary_logloss: 0.0810098
[65]	valid_0's binary_logloss: 0.0806243
[66]	valid_0's binary_logloss: 0.0802107
[67]	valid_0's binary_logloss: 0.0797477
[68]	valid_0's binary_logloss: 0.0793621
[69]	valid_0's binary_logloss: 0.0790177
[70]	valid_0's binary_logloss: 0.0787123
[71]	valid_0's binary_logloss: 0.078414
[72]	valid_0's binary_logloss: 0.0781665
[73]	valid_0's binary_logloss: 0.0778258
[74]	valid_0's binary_logloss: 0.0774115
[75]	valid_0's binary_logloss: 0.0771286
[76]	valid_0's binary_logloss: 0.0769154
[77]	valid_0's binary_logloss: 0.0768405
[78]	valid_0's binary_logloss: 0.076594
[79]	valid_0's binary_logloss: 0.0761931
[80]	valid_0's binary_logloss: 0.0761075
[81]	valid_0's binary_logloss: 0.0757986
[82]	valid_0's binary_logloss: 0.0757191
[83]	valid_0's binary_logloss: 0.0755625
[84]	valid_0's binary_logloss: 0.0753426
[85]	valid_0's binary_logloss: 0.075273
[86]	valid_0's binary_logloss: 0.0751671
[87]	valid_0's binary_logloss: 0.0750496
[88]	valid_0's binary_logloss: 0.0749137
[89]	valid_0's binary_logloss: 0.0748784
[90]	valid_0's binary_logloss: 0.0747942
[91]	valid_0's binary_logloss: 0.0746666
[92]	valid_0's binary_logloss: 0.0745887
[93]	valid_0's binary_logloss: 0.0744065
[94]	valid_0's binary_logloss: 0.0742722
[95]	valid_0's binary_logloss: 0.0741918
[96]	valid_0's binary_logloss: 0.0740599
[97]	valid_0's binary_logloss: 0.073886
[98]	valid_0's binary_logloss: 0.0736986
[99]	valid_0's binary_logloss: 0.0736245
[100]	valid_0's binary_logloss: 0.0735171
[101]	valid_0's binary_logloss: 0.0735864
[102]	valid_0's binary_logloss: 0.0736333
[103]	valid_0's binary_logloss: 0.0735748
[104]	valid_0's binary_logloss: 0.0735395
[105]	valid_0's binary_logloss: 0.0735089
[106]	valid_0's binary_logloss: 0.0734413
[107]	valid_0's binary_logloss: 0.0734211
[108]	valid_0's binary_logloss: 0.0733632
[109]	valid_0's binary_logloss: 0.0732125
[110]	valid_0's binary_logloss: 0.0731752
[111]	valid_0's binary_logloss: 0.0732086
[112]	valid_0's binary_logloss: 0.0732429
[113]	valid_0's binary_logloss: 0.0732048
[114]	valid_0's binary_logloss: 0.0732112
[115]	valid_0's binary_logloss: 0.0730881
[116]	valid_0's binary_logloss: 0.0731233
[117]	valid_0's binary_logloss: 0.0731293
[118]	valid_0's binary_logloss: 0.0731865
[119]	valid_0's binary_logloss: 0.0731055
[120]	valid_0's binary_logloss: 0.073048
[121]	valid_0's binary_logloss: 0.0730073
[122]	valid_0's binary_logloss: 0.0729791
[123]	valid_0's binary_logloss: 0.0729491
[124]	valid_0's binary_logloss: 0.0728973
[125]	valid_0's binary_logloss: 0.0728888
[126]	valid_0's binary_logloss: 0.0729103
[127]	valid_0's binary_logloss: 0.0728672
[128]	valid_0's binary_logloss: 0.0727714
[129]	valid_0's binary_logloss: 0.0727589
[130]	valid_0's binary_logloss: 0.072758
[131]	valid_0's binary_logloss: 0.0725933
[132]	valid_0's binary_logloss: 0.072591
[133]	valid_0's binary_logloss: 0.0725478
[134]	valid_0's binary_logloss: 0.0724478
[135]	valid_0's binary_logloss: 0.0723366
[136]	valid_0's binary_logloss: 0.072375
[137]	valid_0's binary_logloss: 0.0723388
[138]	valid_0's binary_logloss: 0.07238
[139]	valid_0's binary_logloss: 0.0724104
[140]	valid_0's binary_logloss: 0.0724467
[141]	valid_0's binary_logloss: 0.0725027
[142]	valid_0's binary_logloss: 0.0724972
[143]	valid_0's binary_logloss: 0.0725619
[144]	valid_0's binary_logloss: 0.0726305
[145]	valid_0's binary_logloss: 0.0725876
[146]	valid_0's binary_logloss: 0.0725229
[147]	valid_0's binary_logloss: 0.0724925
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[148]	valid_0's binary_logloss: 0.072466
[149]	valid_0's binary_logloss: 0.0724291
[150]	valid_0's binary_logloss: 0.0723349
[151]	valid_0's binary_logloss: 0.0722554
[152]	valid_0's binary_logloss: 0.0722122
[153]	valid_0's binary_logloss: 0.0721974
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[154]	valid_0's binary_logloss: 0.0721836
[155]	valid_0's binary_logloss: 0.0722815
[156]	valid_0's binary_logloss: 0.0722347
[157]	valid_0's binary_logloss: 0.0721664
[158]	valid_0's binary_logloss: 0.0722637
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[159]	valid_0's binary_logloss: 0.0722436
[160]	valid_0's binary_logloss: 0.0722872
[161]	valid_0's binary_logloss: 0.0722401
[162]	valid_0's binary_logloss: 0.07225
[163]	valid_0's binary_logloss: 0.0721994
[164]	valid_0's binary_logloss: 0.0721367
[165]	valid_0's binary_logloss: 0.0721148
[166]	valid_0's binary_logloss: 0.072131
[167]	valid_0's binary_logloss: 0.0720474
[168]	valid_0's binary_logloss: 0.0720987
[169]	valid_0's binary_logloss: 0.0720648
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[170]	valid_0's binary_logloss: 0.0721263
[171]	valid_0's binary_logloss: 0.0721996
[172]	valid_0's binary_logloss: 0.0722271
[173]	valid_0's binary_logloss: 0.0722609
[174]	valid_0's binary_logloss: 0.072297
[175]	valid_0's binary_logloss: 0.0724396
[176]	valid_0's binary_logloss: 0.0726173
[177]	valid_0's binary_logloss: 0.0725824
[178]	valid_0's binary_logloss: 0.0725444
[179]	valid_0's binary_logloss: 0.0725373
[180]	valid_0's binary_logloss: 0.0725173
[181]	valid_0's binary_logloss: 0.0727316
[182]	valid_0's binary_logloss: 0.0728103
[183]	valid_0's binary_logloss: 0.0729211
[184]	valid_0's binary_logloss: 0.073055
[185]	valid_0's binary_logloss: 0.073129
[186]	valid_0's binary_logloss: 0.0732589
[187]	valid_0's binary_logloss: 0.0732638
[188]	valid_0's binary_logloss: 0.0733225
[189]	valid_0's binary_logloss: 0.0732821
[190]	valid_0's binary_logloss: 0.0732646
[191]	valid_0's binary_logloss: 0.073335
[192]	valid_0's binary_logloss: 0.0733933
[193]	valid_0's binary_logloss: 0.0734188
[194]	valid_0's binary_logloss: 0.0735172
[195]	valid_0's binary_logloss: 0.0736969

Trening klas:  80%|████████  | 402/500 [46:53<14:37,  8.95s/klasa, klasa=class_402, F1_klasy=0.0426, F1_macro=0.6471, drzewa=167]




Trening klas:  81%|████████  | 403/500 [46:53<16:34, 10.25s/klasa, klasa=class_402, F1_klasy=0.0426, F1_macro=0.6471, drzewa=167]

[196]	valid_0's binary_logloss: 0.0737286
[197]	valid_0's binary_logloss: 0.0737498
[1]	valid_0's binary_logloss: 0.673225
[2]	valid_0's binary_logloss: 0.601484
[3]	valid_0's binary_logloss: 0.58213
[4]	valid_0's binary_logloss: 0.578465
[5]	valid_0's binary_logloss: 0.572009
[6]	valid_0's binary_logloss: 0.600788
[7]	valid_0's binary_logloss: 0.596871
[8]	valid_0's binary_logloss: 0.597566
[9]	valid_0's binary_logloss: 0.599618
[10]	valid_0's binary_logloss: 0.598363
[11]	valid_0's binary_logloss: 0.597417
[12]	valid_0's binary_logloss: 0.597046
[13]	valid_0's binary_logloss: 0.599062
[14]	valid_0's binary_logloss: 0.599976
[15]	valid_0's binary_logloss: 0.597583
[16]	valid_0's binary_logloss: 0.596681
[17]	valid_0's binary_logloss: 0.599102
[18]	valid_0's binary_logloss: 0.596686
[19]	valid_0's binary_logloss: 0.594672
[20]	valid_0's binary_logloss: 0.593195
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.598547
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.599412
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.59684
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.598434
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.600155
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.598992
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.598304
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.598866
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

Trening klas:  81%|████████  | 403/500 [46:56<16:34, 10.25s/klasa, klasa=class_403, F1_klasy=0.5382, F1_macro=0.6468, drzewa=5]




Trening klas:  81%|████████  | 404/500 [46:56<12:58,  8.11s/klasa, klasa=class_403, F1_klasy=0.5382, F1_macro=0.6468, drzewa=5]

[29]	valid_0's binary_logloss: 0.59579
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.595302
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.749694
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.746173
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.738231
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.727158
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.721548
[1]	valid_0's binary_logloss: 0.0854768
[2]	valid_0's binary_logloss: 0.0584166
[3]	valid_0's binary_logloss: 0.0553952
[4]	valid_0's binary_logloss: 0.0542522
[5]	valid_0's binary_logloss: 0.0532099
[6]	valid_0's binary_logloss: 0.0522057
[7]	valid_0's binary_logloss: 0.0501438
[8]	valid_0's binary_logloss: 0.0494534
[9]	valid_0's binary_logloss: 0.0491938
[10]	valid_0's binary_logloss: 0.0488571
[11]	valid_0's binary_logloss: 0.0560643
[12]	valid_0's binary_logloss: 0.053627
[13]	valid_0's binary_logloss: 0.051525
[14]	valid_0's binary_logloss: 0.0493979
[15]	valid_0's binary_logloss: 0.048029
[16]	valid_0's binary_logloss: 0.0465782
[17]	valid_0's binary_logloss: 0.0456803
[18]	valid_0's binary_logloss: 0.0447027
[19]	valid_0's binary_logloss: 0.0438811
[20]	valid_0's binary_logloss: 0.0430602
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0421701
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0412586
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.040582
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0400774
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.0387249
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.038109
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.0374576
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.0370316
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.0364895
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.0359965
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.0355974
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.0349865
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.0344588
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.0340171
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.033456
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.032914
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.0324192
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.0319285
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.0314535
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.0310301
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.0309014
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.0305603
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.0301242
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.0297795
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.0293357
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.0290156
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.0289562
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.0286618
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.0286433
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.028386
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.0280912
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.0276826
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.0274993
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.0270752
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.0271641
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.0271861
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.0272099
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.0272666
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.0271961
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.0271794
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.0272208
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.0270732
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.02699
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.0266858
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.0266505
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.0268109
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.026927
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.026677
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.0264905
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.0266764
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.0266242
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.0265013
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.0264734
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.0264397
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.0263391
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.0261915
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.0258462
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.0255886
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.0253192
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.0253423
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.0251211
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.0250244
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.0248464
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.0247427
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.0246395
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.0243894
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.0241728
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.0239507
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.0236742
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.0234385
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.0234373
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.0233114
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.0231811
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.0230365
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.0229408
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.0230214
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.023008
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.0230321
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.0230771
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.0231555
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.0230639
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.0231473
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.0233331
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.0233118
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.023264
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.0230974
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.0230051
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.0229328
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.0229052
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.0230153
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.0229592
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 0.0227416
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 0.0225357
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 0.0224776
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 0.0224292
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[116]	valid_0's binary_logloss: 0.022534
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[117]	valid_0's binary_logloss: 0.0225839
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[118]	valid_0's binary_logloss: 0.0225189
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[119]	valid_0's binary_logloss: 0.0224381
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[120]	valid_0's binary_logloss: 0.0223466
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[121]	valid_0's binary_logloss: 0.0223233
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[122]	valid_0's binary_logloss: 0.0222342
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[123]	valid_0's binary_logloss: 0.0222052
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[124]	valid_0's binary_logloss: 0.0221476
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[125]	valid_0's binary_logloss: 0.0220674
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[126]	valid_0's binary_logloss: 0.0221859
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[127]	valid_0's binary_logloss: 0.0222067
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[128]	valid_0's binary_logloss: 0.0220726
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[129]	valid_0's binary_logloss: 0.0220802
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[130]	valid_0's binary_logloss: 0.0221058
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[131]	valid_0's binary_logloss: 0.0219803
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[132]	valid_0's binary_logloss: 0.0219208
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[133]	valid_0's binary_logloss: 0.0218509
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[134]	valid_0's binary_logloss: 0.021819
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[135]	valid_0's binary_logloss: 0.0217466
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[136]	valid_0's binary_logloss: 0.0218784
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[137]	valid_0's binary_logloss: 0.0218701
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[138]	valid_0's binary_logloss: 0.0220089
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[139]	valid_0's binary_logloss: 0.0221156
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[140]	valid_0's binary_logloss: 0.0222149
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[141]	valid_0's binary_logloss: 0.0223328
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[142]	valid_0's binary_logloss: 0.0223578
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[143]	valid_0's binary_logloss: 0.0224902
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[144]	valid_0's binary_logloss: 0.0224972
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[145]	valid_0's binary_logloss: 0.0226077
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[146]	valid_0's binary_logloss: 0.0225994
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[147]	valid_0's binary_logloss: 0.0225989
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[148]	valid_0's binary_logloss: 0.0226274
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[149]	valid_0's binary_logloss: 0.0225856
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[150]	valid_0's binary_logloss: 0.0226188
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[151]	valid_0's binary_logloss: 0.0227269
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[152]	valid_0's binary_logloss: 0.0226771
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[153]	valid_0's binary_logloss: 0.0226308
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[154]	valid_0's binary_logloss: 0.0225991
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[155]	valid_0's binary_logloss: 0.0225671
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[156]	valid_0's binary_logloss: 0.0225783
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[157]	valid_0's binary_logloss: 0.0225349
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[158]	valid_0's binary_logloss: 0.0225026
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[159]	valid_0's binary_logloss: 0.0224664
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[160]	valid_0's binary_logloss: 0.0225018

Trening klas:  81%|████████  | 404/500 [47:01<12:58,  8.11s/klasa, klasa=class_404, F1_klasy=0.5385, F1_macro=0.6466, drzewa=135]




Trening klas:  81%|████████  | 405/500 [47:01<11:29,  7.26s/klasa, klasa=class_404, F1_klasy=0.5385, F1_macro=0.6466, drzewa=135]

[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[161]	valid_0's binary_logloss: 0.0224523
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[162]	valid_0's binary_logloss: 0.0223875
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[163]	valid_0's binary_logloss: 0.0223407
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[164]	valid_0's binary_logloss: 0.0222694
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[165]	valid_0's binary_logloss: 0.0221143
[1]	valid_0's binary_logloss: 0.438859
[2]	valid_0's binary_logloss: 0.242904
[3]	valid_0's binary_logloss: 0.503985
[4]	valid_0's binary_logloss: 0.49742
[5]	valid_0's binary_logloss: 0.495427
[6]	valid_0's binary_logloss: 0.5356
[7]	valid_0's binary_logloss: 0.534027
[8]	valid_0's binary_logloss: 0.532766
[9]	valid_0's binary_logloss: 0.53081
[10]	valid_0's binary_logloss: 0.528347
[11]	valid_0's binary_logloss: 0.675369
[12]	valid_0's binary_logloss: 0.66927
[13]	valid_0's binary_logloss: 0.666069
[14]	valid_0's binary_logloss: 0.665749
[15]	valid_0's binary_logloss: 0.66554
[16]	valid_0's binary_logloss: 0.795677
[17]	valid_0's binary_logloss: 0.788346
[18]	valid_0's binary_logloss: 0.786835
[19]	valid_0's binary_logloss: 0.781778
[20]	valid_0's binary_logloss: 0.781658
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.781607
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.781645
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.778654
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.779992
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.779975
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.777687
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.774157

Trening klas:  81%|████████  | 405/500 [47:04<11:29,  7.26s/klasa, klasa=class_405, F1_klasy=0.3495, F1_macro=0.6458, drzewa=2]

[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.766738
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.766482
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.764211
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.760908
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.753539

Trening klas:  81%|████████  | 406/500 [47:04<09:24,  6.01s/klasa, klasa=class_405, F1_klasy=0.3495, F1_macro=0.6458, drzewa=2]

[1]	valid_0's binary_logloss: 0.193399
[2]	valid_0's binary_logloss: 0.087749
[3]	valid_0's binary_logloss: 0.0788425
[4]	valid_0's binary_logloss: 0.0722698
[5]	valid_0's binary_logloss: 0.0669753
[6]	valid_0's binary_logloss: 0.0624534
[7]	valid_0's binary_logloss: 0.0584443
[8]	valid_0's binary_logloss: 0.0554982
[9]	valid_0's binary_logloss: 0.0528631
[10]	valid_0's binary_logloss: 0.0505781
[11]	valid_0's binary_logloss: 0.0488924
[12]	valid_0's binary_logloss: 0.047148
[13]	valid_0's binary_logloss: 0.0458015
[14]	valid_0's binary_logloss: 0.0445418
[15]	valid_0's binary_logloss: 0.0433191
[16]	valid_0's binary_logloss: 0.0420562
[17]	valid_0's binary_logloss: 0.0409659
[18]	valid_0's binary_logloss: 0.0397506
[19]	valid_0's binary_logloss: 0.0384444
[20]	valid_0's binary_logloss: 0.0372974
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0363513
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0354304
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.0344786
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0337006
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.0329459
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.0322553
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.031666
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.0310816
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.030575
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.0300656
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.0296062
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.0291561
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.0287469
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.0282969
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.0278887
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.0275155
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.0271045
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.0267377
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.026335
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.0260127
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.0256243
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.0251974
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.0249496
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.0247276
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.0244228
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.0242227
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.0240379
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.0238772
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.0236962
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.0234861
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.0233191
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.023128
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.0228889
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.0226858
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.0225574
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.0223795
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.0221757
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.0220488
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.0218848
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.0216979
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.02151
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.0213343
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.0211361
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.0209938
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.0208749
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.0207408
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.0206206
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.0205502
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.0204304
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.0203772
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.0202711
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.0202238
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.0201394
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.020073
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.0199717
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.0199591
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.0198678
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.0198058
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.0197415
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.0197356
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.0196895
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.0196515
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.0196199
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.0195427
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.0195226
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.0194169
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.0193666
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.019358
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.0193221
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.0192685
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.0191949
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.0192062
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.0192215
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.019255
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.0192733
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.0192705
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.0192531
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.0192562
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.0192696
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.0192413
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.0191768
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.0191294
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.0190714
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.0190846
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.0190301
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.018957
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.0189372
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.0189322
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.0189041
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.0189078
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.0189073
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 0.0189581
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 0.0189834
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 0.0190033
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 0.0190228
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[116]	valid_0's binary_logloss: 0.0190471
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[117]	valid_0's binary_logloss: 0.0190846
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[118]	valid_0's binary_logloss: 0.0191013
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[119]	valid_0's binary_logloss: 0.0191464
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[120]	valid_0's binary_logloss: 0.0191835
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[121]	valid_0's binary_logloss: 0.0192228
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[122]	valid_0's binary_logloss: 0.0192114
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[123]	valid_0's binary_logloss: 0.0191943
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[124]	valid_0's binary_logloss: 0.0192005
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[125]	valid_0's binary_logloss: 0.019166
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[126]	valid_0's binary_logloss: 0.0191562
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[127]	valid_0's binary_logloss: 0.0191552
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[128]	valid_0's binary_logloss: 0.0191105
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[129]	valid_0's binary_logloss: 0.0191048
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[130]	valid_0's binary_logloss: 0.0190902
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[131]	valid_0's binary_logloss: 0.0191086
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[132]	valid_0's binary_logloss: 0.0191323
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[133]	valid_0's binary_logloss: 0.0191285
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

Trening klas:  81%|████████  | 406/500 [47:10<09:24,  6.01s/klasa, klasa=class_406, F1_klasy=0.5758, F1_macro=0.6457, drzewa=109]




Trening klas:  81%|████████▏ | 407/500 [47:10<09:03,  5.84s/klasa, klasa=class_406, F1_klasy=0.5758, F1_macro=0.6457, drzewa=109]

[134]	valid_0's binary_logloss: 0.0191068
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[135]	valid_0's binary_logloss: 0.0190835
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[136]	valid_0's binary_logloss: 0.0190633
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[137]	valid_0's binary_logloss: 0.0190321
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[138]	valid_0's binary_logloss: 0.0190212
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[139]	valid_0's binary_logloss: 0.0189978
[1]	valid_0's binary_logloss: 0.163526
[2]	valid_0's binary_logloss: 0.163725
[3]	valid_0's binary_logloss: 0.311661
[4]	valid_0's binary_logloss: 0.308474
[5]	valid_0's binary_logloss: 0.308069
[6]	valid_0's binary_logloss: 0.306508
[7]	valid_0's binary_logloss: 0.299316
[8]	valid_0's binary_logloss: 0.29092
[9]	valid_0's binary_logloss: 0.288631
[10]	valid_0's binary_logloss: 0.281073
[11]	valid_0's binary_logloss: 0.269726
[12]	valid_0's binary_logloss: 0.263056
[13]	valid_0's binary_logloss: 0.249089
[14]	valid_0's binary_logloss: 0.246616
[15]	valid_0's binary_logloss: 0.245405
[16]	valid_0's binary_logloss: 0.2447
[17]	valid_0's binary_logloss: 0.244228
[18]	valid_0's binary_logloss: 0.242875
[19]	valid_0's binary_logloss: 0.242681
[20]	valid_0's binary_logloss: 0.242549
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.241785
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.241444
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.241182
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.240805
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

Trening klas:  81%|████████▏ | 407/500 [47:12<09:03,  5.84s/klasa, klasa=class_407, F1_klasy=0.6141, F1_macro=0.6456, drzewa=1]




Trening klas:  82%|████████▏ | 408/500 [47:12<07:21,  4.80s/klasa, klasa=class_407, F1_klasy=0.6141, F1_macro=0.6456, drzewa=1]

[25]	valid_0's binary_logloss: 0.240512
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.239518
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.23922
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.238898
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.238765
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.238625
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.238535
[1]	valid_0's binary_logloss: 0.353562
[2]	valid_0's binary_logloss: 0.299551
[3]	valid_0's binary_logloss: 0.273324
[4]	valid_0's binary_logloss: 0.253997
[5]	valid_0's binary_logloss: 0.239026
[6]	valid_0's binary_logloss: 0.316647
[7]	valid_0's binary_logloss: 0.292454
[8]	valid_0's binary_logloss: 0.276491
[9]	valid_0's binary_logloss: 0.263311
[10]	valid_0's binary_logloss: 0.252457
[11]	valid_0's binary_logloss: 0.242222
[12]	valid_0's binary_logloss: 0.233725
[13]	valid_0's binary_logloss: 0.226536
[14]	valid_0's binary_logloss: 0.219923
[15]	valid_0's binary_logloss: 0.213977
[16]	valid_0's binary_logloss: 0.20743
[17]	valid_0's binary_logloss: 0.201763
[18]	valid_0's binary_logloss: 0.196999
[19]	valid_0's binary_logloss: 0.192702
[20]	valid_0's binary_logloss: 0.188499
[21]	valid_0's binary_logloss: 0.184152
[22]	valid_0's binary_logloss: 0.179547
[23]	valid_0's binary_logloss: 0.175682
[24]	valid_0's binary_logloss: 0.172401
[25]	valid_0's binary_logloss: 0.169254
[26]	valid_0's binary_logloss: 0.16586
[27]	valid_0's binary_logloss: 0.162682
[28]	valid_0's binary_logloss: 0.159236
[29]	valid_0's binary_logloss: 0.156132
[30]	valid_0's binary_logloss: 0.153462
[31]	valid_0's binary_logloss: 0.151427
[32]	valid_0's binary_logloss: 0.149617
[33]	valid_0's binary_logloss: 0.147504
[34]	valid_0's binary_logloss: 0.145891
[35]	valid_0's binary_logloss: 0.14406
[36]	valid_0's binary_logloss: 0.141524
[37]	valid_0's binary_logloss: 0.139555
[38]	valid_0's binary_logloss: 0.137945
[39]	valid_0's binary_logloss: 0.136251
[40]	valid_0's binary_logloss: 0.13403
[41]	valid_0's binary_logloss: 0.131917
[42]	valid_0's binary_logloss: 0.13001
[43]	valid_0's binary_logloss: 0.128728
[44]	valid_0's binary_logloss: 0.12699
[45]	valid_0's binary_logloss: 0.125038
[46]	valid_0's binary_logloss: 0.123559
[47]	valid_0's binary_logloss: 0.12248
[48]	valid_0's binary_logloss: 0.121437
[49]	valid_0's binary_logloss: 0.120505
[50]	valid_0's binary_logloss: 0.11974
[51]	valid_0's binary_logloss: 0.118946
[52]	valid_0's binary_logloss: 0.118116
[53]	valid_0's binary_logloss: 0.117492
[54]	valid_0's binary_logloss: 0.116581
[55]	valid_0's binary_logloss: 0.115579
[56]	valid_0's binary_logloss: 0.114639
[57]	valid_0's binary_logloss: 0.113627
[58]	valid_0's binary_logloss: 0.112726
[59]	valid_0's binary_logloss: 0.1119
[60]	valid_0's binary_logloss: 0.110999
[61]	valid_0's binary_logloss: 0.110501
[62]	valid_0's binary_logloss: 0.110132
[63]	valid_0's binary_logloss: 0.109601
[64]	valid_0's binary_logloss: 0.108827
[65]	valid_0's binary_logloss: 0.108366
[66]	valid_0's binary_logloss: 0.106227
[67]	valid_0's binary_logloss: 0.104901
[68]	valid_0's binary_logloss: 0.103894
[69]	valid_0's binary_logloss: 0.103089
[70]	valid_0's binary_logloss: 0.101933
[71]	valid_0's binary_logloss: 0.10157
[72]	valid_0's binary_logloss: 0.100981
[73]	valid_0's binary_logloss: 0.100319
[74]	valid_0's binary_logloss: 0.100088
[75]	valid_0's binary_logloss: 0.0996566
[76]	valid_0's binary_logloss: 0.0994373
[77]	valid_0's binary_logloss: 0.0991955
[78]	valid_0's binary_logloss: 0.0985418
[79]	valid_0's binary_logloss: 0.0979267
[80]	valid_0's binary_logloss: 0.0974248
[81]	valid_0's binary_logloss: 0.0970837
[82]	valid_0's binary_logloss: 0.0967815
[83]	valid_0's binary_logloss: 0.0962845
[84]	valid_0's binary_logloss: 0.0959072
[85]	valid_0's binary_logloss: 0.0954673
[86]	valid_0's binary_logloss: 0.0951284
[87]	valid_0's binary_logloss: 0.0948484
[88]	valid_0's binary_logloss: 0.0944744
[89]	valid_0's binary_logloss: 0.0942238
[90]	valid_0's binary_logloss: 0.0940359
[91]	valid_0's binary_logloss: 0.0938458
[92]	valid_0's binary_logloss: 0.0938555
[93]	valid_0's binary_logloss: 0.093771
[94]	valid_0's binary_logloss: 0.093708
[95]	valid_0's binary_logloss: 0.0937404
[96]	valid_0's binary_logloss: 0.0930729
[97]	valid_0's binary_logloss: 0.09289
[98]	valid_0's binary_logloss: 0.092561
[99]	valid_0's binary_logloss: 0.0921219
[100]	valid_0's binary_logloss: 0.0920483
[101]	valid_0's binary_logloss: 0.0918473
[102]	valid_0's binary_logloss: 0.0918023
[103]	valid_0's binary_logloss: 0.0916816
[104]	valid_0's binary_logloss: 0.0916622
[105]	valid_0's binary_logloss: 0.0916666
[106]	valid_0's binary_logloss: 0.0914855
[107]	valid_0's binary_logloss: 0.0913841
[108]	valid_0's binary_logloss: 0.0911258
[109]	valid_0's binary_logloss: 0.0910848
[110]	valid_0's binary_logloss: 0.0909478
[111]	valid_0's binary_logloss: 0.091008
[112]	valid_0's binary_logloss: 0.0909105
[113]	valid_0's binary_logloss: 0.0909893
[114]	valid_0's binary_logloss: 0.0910212
[115]	valid_0's binary_logloss: 0.0909053
[116]	valid_0's binary_logloss: 0.0910208
[117]	valid_0's binary_logloss: 0.0906406
[118]	valid_0's binary_logloss: 0.0902391
[119]	valid_0's binary_logloss: 0.0899752
[120]	valid_0's binary_logloss: 0.0897459
[121]	valid_0's binary_logloss: 0.0898399
[122]	valid_0's binary_logloss: 0.0898664
[123]	valid_0's binary_logloss: 0.0897861
[124]	valid_0's binary_logloss: 0.0898024
[125]	valid_0's binary_logloss: 0.0897329
[126]	valid_0's binary_logloss: 0.0888279
[127]	valid_0's binary_logloss: 0.0882035
[128]	valid_0's binary_logloss: 0.0880337
[129]	valid_0's binary_logloss: 0.0876906
[130]	valid_0's binary_logloss: 0.087459
[131]	valid_0's binary_logloss: 0.0866576
[132]	valid_0's binary_logloss: 0.0865913
[133]	valid_0's binary_logloss: 0.0864619
[134]	valid_0's binary_logloss: 0.0861918
[135]	valid_0's binary_logloss: 0.0861389
[136]	valid_0's binary_logloss: 0.0860537
[137]	valid_0's binary_logloss: 0.0859863
[138]	valid_0's binary_logloss: 0.0859366
[139]	valid_0's binary_logloss: 0.0859486
[140]	valid_0's binary_logloss: 0.0860235
[141]	valid_0's binary_logloss: 0.0858195
[142]	valid_0's binary_logloss: 0.085879
[143]	valid_0's binary_logloss: 0.085818
[144]	valid_0's binary_logloss: 0.085729
[145]	valid_0's binary_logloss: 0.0857605
[146]	valid_0's binary_logloss: 0.0854806
[147]	valid_0's binary_logloss: 0.0854073
[148]	valid_0's binary_logloss: 0.0851606
[149]	valid_0's binary_logloss: 0.0849824
[150]	valid_0's binary_logloss: 0.0848322
[151]	valid_0's binary_logloss: 0.0843396
[152]	valid_0's binary_logloss: 0.084277
[153]	valid_0's binary_logloss: 0.0840298
[154]	valid_0's binary_logloss: 0.0835962
[155]	valid_0's binary_logloss: 0.0836786
[156]	valid_0's binary_logloss: 0.08354
[157]	valid_0's binary_logloss: 0.08351
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[158]	valid_0's binary_logloss: 0.0836283
[159]	valid_0's binary_logloss: 0.0836928
[160]	valid_0's binary_logloss: 0.0837314
[161]	valid_0's binary_logloss: 0.0833346
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[162]	valid_0's binary_logloss: 0.0831091
[163]	valid_0's binary_logloss: 0.083071
[164]	valid_0's binary_logloss: 0.0830113
[165]	valid_0's binary_logloss: 0.0830902
[166]	valid_0's binary_logloss: 0.083216
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[167]	valid_0's binary_logloss: 0.0833225
[168]	valid_0's binary_logloss: 0.0834406
[169]	valid_0's binary_logloss: 0.0835299
[170]	valid_0's binary_logloss: 0.0836873
[171]	valid_0's binary_logloss: 0.0836702
[172]	valid_0's binary_logloss: 0.083687
[173]	valid_0's binary_logloss: 0.083756
[174]	valid_0's binary_logloss: 0.0836998
[175]	valid_0's binary_logloss: 0.0836984
[176]	valid_0's binary_logloss: 0.0837215
[177]	valid_0's binary_logloss: 0.0838074
[178]	valid_0's binary_logloss: 0.0836664
[179]	valid_0's binary_logloss: 0.083748
[180]	valid_0's binary_logloss: 0.0838423
[181]	valid_0's binary_logloss: 0.0839069
[182]	valid_0's binary_logloss: 0.0841994
[183]	valid_0's binary_logloss: 0.0841957
[184]	valid_0's binary_logloss: 0.0843302
[185]	valid_0's binary_logloss: 0.0843026
[186]	valid_0's binary_logloss: 0.0841
[187]	valid_0's binary_logloss: 0.083947
[188]	valid_0's binary_logloss: 0.0840159
[189]	valid_0's binary_logloss: 0.0840198
[190]	valid_0's binary_logloss: 0.0841341
[191]	valid_0's binary_logloss: 0.083806
[192]	valid_0's binary_logloss: 0.0832764
[193]	valid_0's binary_logloss: 0.0830208
[194]	valid_0's binary_logloss: 0.0830584

Trening klas:  82%|████████▏ | 408/500 [47:27<07:21,  4.80s/klasa, klasa=class_408, F1_klasy=0.0645, F1_macro=0.6442, drzewa=164]




Trening klas:  82%|████████▏ | 409/500 [47:27<12:02,  7.94s/klasa, klasa=class_408, F1_klasy=0.0645, F1_macro=0.6442, drzewa=164]

[1]	valid_0's binary_logloss: 0.0277546
[2]	valid_0's binary_logloss: 0.0263293
[3]	valid_0's binary_logloss: 0.0256106
[4]	valid_0's binary_logloss: 0.0251018
[5]	valid_0's binary_logloss: 0.0244504
[6]	valid_0's binary_logloss: 0.0386301
[7]	valid_0's binary_logloss: 0.0339069
[8]	valid_0's binary_logloss: 0.0317873
[9]	valid_0's binary_logloss: 0.0294051
[10]	valid_0's binary_logloss: 0.0279162
[11]	valid_0's binary_logloss: 0.027135
[12]	valid_0's binary_logloss: 0.0258439
[13]	valid_0's binary_logloss: 0.0250174
[14]	valid_0's binary_logloss: 0.0245702
[15]	valid_0's binary_logloss: 0.0237716
[16]	valid_0's binary_logloss: 0.0228708
[17]	valid_0's binary_logloss: 0.0220415
[18]	valid_0's binary_logloss: 0.0214273
[19]	valid_0's binary_logloss: 0.0208465
[20]	valid_0's binary_logloss: 0.0202644
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.019836
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0195604
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.0192377
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0187907
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.018505
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.0182297
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.0179794
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.0178292
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.0174589
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.0172421
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.0169229
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.0166296
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.0164094
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.016284
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.0160687
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.01587
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.0156738
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.0155215
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.015381
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.0152473
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.0148786
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.014706
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.014475
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.0143499
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.0141966
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.0140588
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.013965
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.0137896
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.0136643
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.0134573
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.0134112
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.0134195
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.0133468
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.0131557
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.0131098
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.0130364
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.0127911
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.0125504
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.0124688
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.0124489
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.0123081
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.0122229
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.0120052
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.0118779
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.0116598
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.0115732
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.0114958
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.0115201
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.0115536
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.0114654
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.011479
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.01145
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.011422
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.0113686
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.0112889
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.0113365
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.0112473
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.0113128
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.0113472
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.0113393
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.0114394
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.0115205
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.0115018
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.0113984
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.0114278
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.0114376
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.0114797
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.0115068
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.0115264
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.0115153
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.011466
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.0114128
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.0113794
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.0112712
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.0112014
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.0111574
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.0110369
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.0109579
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.0108791
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.0108214
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.0106026
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.0104037
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.0103143
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.0103409
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.0103737
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.0104473
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.0105144
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.0105632
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.0105948
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.0106704
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.0107003
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 0.0107337
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 0.0107639
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 0.0108479
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 0.010842
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[116]	valid_0's binary_logloss: 0.0107776
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[117]	valid_0's binary_logloss: 0.0107778
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[118]	valid_0's binary_logloss: 0.0107764
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[119]	valid_0's binary_logloss: 0.0107233
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[120]	valid_0's binary_logloss: 0.0107596
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[121]	valid_0's binary_logloss: 0.0107205
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[122]	valid_0's binary_logloss: 0.0105841
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[123]	valid_0's binary_logloss: 0.0104492
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[124]	valid_0's binary_logloss: 0.0104448
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[125]	valid_0's binary_logloss: 0.0103873
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[126]	valid_0's binary_logloss: 0.0104032
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[127]	valid_0's binary_logloss: 0.0103933
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[128]	valid_0's binary_logloss: 0.0103227
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[129]	valid_0's binary_logloss: 0.010297
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[130]	valid_0's binary_logloss: 0.0103179
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[131]	valid_0's binary_logloss: 0.0103175
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[132]	valid_0's binary_logloss: 0.0102891
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[133]	valid_0's binary_logloss: 0.010334
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[134]	valid_0's binary_logloss: 0.0103316
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[135]	valid_0's binary_logloss: 0.010212
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[136]	valid_0's binary_logloss: 0.0102355
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[137]	valid_0's binary_logloss: 0.0103127
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[138]	valid_0's binary_logloss: 0.010283
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[139]	valid_0's binary_logloss: 0.0102208
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[140]	valid_0's binary_logloss: 0.0102594
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[141]	valid_0's binary_logloss: 0.0102371
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[142]	valid_0's binary_logloss: 0.0102483
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[143]	valid_0's binary_logloss: 0.0103335
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[144]	valid_0's binary_logloss: 0.0103294
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[145]	valid_0's binary_logloss: 0.0103283
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[146]	valid_0's binary_logloss: 0.0103582
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[147]	valid_0's binary_logloss: 0.010414
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[148]	valid_0's binary_logloss: 0.0104772
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[149]	valid_0's binary_logloss: 0.0105065
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[150]	valid_0's binary_logloss: 0.0105825
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[151]	valid_0's binary_logloss: 0.0104657
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[152]	valid_0's binary_logloss: 0.0105041
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[153]	valid_0's binary_logloss: 0.0104853
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[154]	valid_0's binary_logloss: 0.0104631
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[155]	valid_0's binary_logloss: 0.0104353
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[156]	valid_0's binary_logloss: 0.0104994
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[157]	valid_0's binary_logloss: 0.01057
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[158]	valid_0's binary_logloss: 0.0106004
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[159]	valid_0's binary_logloss: 0.0106676
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[160]	valid_0's binary_logloss: 0.010694
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[161]	valid_0's binary_logloss: 0.0105626
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[162]	valid_0's binary_logloss: 0.0104083
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[163]	valid_0's binary_logloss: 0.0104742
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

Trening klas:  82%|████████▏ | 409/500 [47:34<12:02,  7.94s/klasa, klasa=class_409, F1_klasy=0.5818, F1_macro=0.6440, drzewa=135]




Trening klas:  82%|████████▏ | 410/500 [47:34<11:20,  7.56s/klasa, klasa=class_409, F1_klasy=0.5818, F1_macro=0.6440, drzewa=135]

[164]	valid_0's binary_logloss: 0.0105122
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[165]	valid_0's binary_logloss: 0.0105515
[1]	valid_0's binary_logloss: 0.0951886
[2]	valid_0's binary_logloss: 0.0606959
[3]	valid_0's binary_logloss: 0.0555352
[4]	valid_0's binary_logloss: 0.051771
[5]	valid_0's binary_logloss: 0.0487471
[6]	valid_0's binary_logloss: 0.0499823
[7]	valid_0's binary_logloss: 0.0475593
[8]	valid_0's binary_logloss: 0.0445649
[9]	valid_0's binary_logloss: 0.0425447
[10]	valid_0's binary_logloss: 0.0411018
[11]	valid_0's binary_logloss: 0.0779346
[12]	valid_0's binary_logloss: 0.0568138
[13]	valid_0's binary_logloss: 0.0536224
[14]	valid_0's binary_logloss: 0.0507246
[15]	valid_0's binary_logloss: 0.0483626
[16]	valid_0's binary_logloss: 0.0467213
[17]	valid_0's binary_logloss: 0.0448914
[18]	valid_0's binary_logloss: 0.0433716
[19]	valid_0's binary_logloss: 0.0421702
[20]	valid_0's binary_logloss: 0.040601
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0393233
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0382236
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.0371163
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0360011
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.0349848
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.0339923
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.0331192
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.0322745
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.0316543
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.0308814
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.0301345
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.029524
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.0287059
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.0280363
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.027425
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.0269283
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.0263395
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.0257836
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.0251989
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.0246547
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.024161
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.0236393
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.0231954
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.0227248
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.0222826
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.0218094
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.0213457
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.0209747
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.0206142
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.0201833
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.0196813
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.0192628
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.0189163
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.0185559
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.0182124
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.0179648
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.0176476
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.0174129
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.0171839
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.0169902
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.0167102
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.0164427
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.0162284
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.0159733
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.0157509
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.0156507
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.015447
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.0152876
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.0151793
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.0150832
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.014909
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.0146934
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.0144895
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.014275
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.0140692
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.0139117
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.0137594
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.0136526
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.0135368
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.0134441
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.0133214
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.0131556
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.0130353
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.0129515
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.0128521
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.012724
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.012622
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.012481
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.0123539
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.0122427
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.0121269
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.0120677
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.0120389
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.0119619
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.0119312
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.0118775
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.0117411
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.0117468
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.0116847
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.0115799
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.0115199
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.0114529
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.0113987
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.0113175
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.0112789
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.0112487
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.0111725
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.0110812
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.0110474
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.0109932
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.0109376
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 0.0108751
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 0.0107996
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 0.0107302
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 0.0107228
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[116]	valid_0's binary_logloss: 0.0106688
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[117]	valid_0's binary_logloss: 0.0106062
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[118]	valid_0's binary_logloss: 0.0106219
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[119]	valid_0's binary_logloss: 0.0105735
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[120]	valid_0's binary_logloss: 0.0105685
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[121]	valid_0's binary_logloss: 0.0104995
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[122]	valid_0's binary_logloss: 0.0104366
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[123]	valid_0's binary_logloss: 0.0104375
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[124]	valid_0's binary_logloss: 0.0103702
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[125]	valid_0's binary_logloss: 0.0102751
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[126]	valid_0's binary_logloss: 0.010267
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[127]	valid_0's binary_logloss: 0.0102583
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[128]	valid_0's binary_logloss: 0.0102748
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[129]	valid_0's binary_logloss: 0.0102304
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[130]	valid_0's binary_logloss: 0.0102281
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[131]	valid_0's binary_logloss: 0.010193
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[132]	valid_0's binary_logloss: 0.0101942
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[133]	valid_0's binary_logloss: 0.010141
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[134]	valid_0's binary_logloss: 0.0101145
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[135]	valid_0's binary_logloss: 0.0100889
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[136]	valid_0's binary_logloss: 0.0100874
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[137]	valid_0's binary_logloss: 0.0100566
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[138]	valid_0's binary_logloss: 0.0100518
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[139]	valid_0's binary_logloss: 0.0100464
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[140]	valid_0's binary_logloss: 0.0100327
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[141]	valid_0's binary_logloss: 0.0100571
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[142]	valid_0's binary_logloss: 0.0100553
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[143]	valid_0's binary_logloss: 0.0100774
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[144]	valid_0's binary_logloss: 0.0100603
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[145]	valid_0's binary_logloss: 0.0100509
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[146]	valid_0's binary_logloss: 0.010054
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[147]	valid_0's binary_logloss: 0.010076
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[148]	valid_0's binary_logloss: 0.010111
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[149]	valid_0's binary_logloss: 0.0101265
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[150]	valid_0's binary_logloss: 0.0101199
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[151]	valid_0's binary_logloss: 0.0100949
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[152]	valid_0's binary_logloss: 0.0100803
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[153]	valid_0's binary_logloss: 0.0100574
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[154]	valid_0's binary_logloss: 0.010032
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[155]	valid_0's binary_logloss: 0.0100218
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[156]	valid_0's binary_logloss: 0.0100258
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[157]	valid_0's binary_logloss: 0.0100336
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[158]	valid_0's binary_logloss: 0.0100456
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[159]	valid_0's binary_logloss: 0.0100445
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[160]	valid_0's binary_logloss: 0.0100338
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[161]	valid_0's binary_logloss: 0.0100235
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[162]	valid_0's binary_logloss: 0.0100066
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[163]	valid_0's binary_logloss: 0.00998169
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[164]	valid_0's binary_logloss: 0.00996649
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[165]	valid_0's binary_logloss: 0.00996154
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[166]	valid_0's binary_logloss: 0.00991764
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[167]	valid_0's binary_logloss: 0.00990185
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[168]	valid_0's binary_logloss: 0.00988607
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[169]	valid_0's binary_logloss: 0.00985577
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[170]	valid_0's binary_logloss: 0.00985363
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[171]	valid_0's binary_logloss: 0.00985959
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[172]	valid_0's binary_logloss: 0.00983711
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[173]	valid_0's binary_logloss: 0.00981139
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[174]	valid_0's binary_logloss: 0.00978535
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[175]	valid_0's binary_logloss: 0.00975924
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[176]	valid_0's binary_logloss: 0.00975755
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[177]	valid_0's binary_logloss: 0.00976186
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[178]	valid_0's binary_logloss: 0.00976235
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[179]	valid_0's binary_logloss: 0.00975866
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[180]	valid_0's binary_logloss: 0.00976477
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[181]	valid_0's binary_logloss: 0.00976307
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[182]	valid_0's binary_logloss: 0.00972614
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[183]	valid_0's binary_logloss: 0.00972432

Trening klas:  82%|████████▏ | 410/500 [47:43<11:20,  7.56s/klasa, klasa=class_410, F1_klasy=0.5714, F1_macro=0.6438, drzewa=256]




Trening klas:  82%|████████▏ | 411/500 [47:43<11:48,  7.96s/klasa, klasa=class_410, F1_klasy=0.5714, F1_macro=0.6438, drzewa=256]

[1]	valid_0's binary_logloss: 0.0194043
[2]	valid_0's binary_logloss: 0.0168438
[3]	valid_0's binary_logloss: 0.0151162
[4]	valid_0's binary_logloss: 0.0136473
[5]	valid_0's binary_logloss: 0.0124805
[6]	valid_0's binary_logloss: 0.0115104
[7]	valid_0's binary_logloss: 0.0107906
[8]	valid_0's binary_logloss: 0.0100677
[9]	valid_0's binary_logloss: 0.00966525
[10]	valid_0's binary_logloss: 0.00925946
[11]	valid_0's binary_logloss: 0.00883474
[12]	valid_0's binary_logloss: 0.0084615
[13]	valid_0's binary_logloss: 0.00808339
[14]	valid_0's binary_logloss: 0.00778723
[15]	valid_0's binary_logloss: 0.00745331
[16]	valid_0's binary_logloss: 0.00710228
[17]	valid_0's binary_logloss: 0.00677462
[18]	valid_0's binary_logloss: 0.00646327
[19]	valid_0's binary_logloss: 0.00616153
[20]	valid_0's binary_logloss: 0.00587475
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0056126
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.00534537
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.00511959
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.00489522
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.00467263
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.00448477
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.0042827
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.00409332
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.00391261
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.00373873
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.00358046
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.0034301
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.00328574
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.00314624
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.00301121
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.00288275
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.00276531
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.00265307
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.00254018
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.00243102
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.00232782
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.00222697
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.00213058
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.00203772
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.00194903
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.00186368
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.00178229
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.00170432
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.00162989
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.00155898
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.00149093
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.00143079
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.00136921
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.00131542
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.00125827
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.00120303
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.00114924
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.00109788
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.00104988
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.00100312
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.000958341
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.000916684
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.000876947
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.000839048
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.000807239
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.000771944
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.000738151
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.000705942
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.000675342
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.000646215
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.000617929
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.000592019
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.000566272
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.000541648
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.00051817
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.000497804
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.000478648
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.0004605
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.000443315
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.000427051
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.000412041
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.000397579
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.000382821
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.000367827
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.00035537
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.000342745
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.000328221
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.000315841
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.00030285
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.000292837
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.000282163
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.000274086
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.000264251
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.000256504
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.000247281
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.000237405
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.0002299
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.000221718
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.000213031
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.000208684
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.000197869
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.000189369
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.000185688
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.000179063
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.000173028
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.000168915
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.00016252
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.000159211
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.00015624
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.000153701
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.000147994
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 0.000142731
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 0.000137125
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 0.000132569
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 0.000127961
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[116]	valid_0's binary_logloss: 0.000124128
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[117]	valid_0's binary_logloss: 0.000120238
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[118]	valid_0's binary_logloss: 0.000116601
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[119]	valid_0's binary_logloss: 0.000110206
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[120]	valid_0's binary_logloss: 0.000105923
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[121]	valid_0's binary_logloss: 0.0001021
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[122]	valid_0's binary_logloss: 9.82479e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[123]	valid_0's binary_logloss: 9.45681e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[124]	valid_0's binary_logloss: 9.20966e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[125]	valid_0's binary_logloss: 8.85281e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[126]	valid_0's binary_logloss: 8.55027e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[127]	valid_0's binary_logloss: 8.37609e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[128]	valid_0's binary_logloss: 8.1248e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[129]	valid_0's binary_logloss: 7.90101e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[130]	valid_0's binary_logloss: 7.68668e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[131]	valid_0's binary_logloss: 7.50238e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[132]	valid_0's binary_logloss: 7.25194e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[133]	valid_0's binary_logloss: 7.02376e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[134]	valid_0's binary_logloss: 6.86265e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[135]	valid_0's binary_logloss: 6.62803e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[136]	valid_0's binary_logloss: 6.53639e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[137]	valid_0's binary_logloss: 6.43442e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[138]	valid_0's binary_logloss: 6.34375e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[139]	valid_0's binary_logloss: 6.22228e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[140]	valid_0's binary_logloss: 5.98488e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[141]	valid_0's binary_logloss: 5.87976e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[142]	valid_0's binary_logloss: 5.79551e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[143]	valid_0's binary_logloss: 5.6998e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[144]	valid_0's binary_logloss: 5.5763e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[145]	valid_0's binary_logloss: 5.49293e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[146]	valid_0's binary_logloss: 5.29969e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[147]	valid_0's binary_logloss: 5.11649e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[148]	valid_0's binary_logloss: 4.94414e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[149]	valid_0's binary_logloss: 4.79374e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[150]	valid_0's binary_logloss: 4.74158e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[151]	valid_0's binary_logloss: 4.63813e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[152]	valid_0's binary_logloss: 4.54866e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[153]	valid_0's binary_logloss: 4.46408e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[154]	valid_0's binary_logloss: 4.38409e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[155]	valid_0's binary_logloss: 4.30692e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[156]	valid_0's binary_logloss: 4.15522e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[157]	valid_0's binary_logloss: 4.04586e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[158]	valid_0's binary_logloss: 3.93645e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[159]	valid_0's binary_logloss: 3.82625e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[160]	valid_0's binary_logloss: 3.75166e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[161]	valid_0's binary_logloss: 3.72253e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[162]	valid_0's binary_logloss: 3.69629e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[163]	valid_0's binary_logloss: 3.65377e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[164]	valid_0's binary_logloss: 3.63018e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[165]	valid_0's binary_logloss: 3.53472e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[166]	valid_0's binary_logloss: 3.4783e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[167]	valid_0's binary_logloss: 3.45111e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[168]	valid_0's binary_logloss: 3.3862e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[169]	valid_0's binary_logloss: 3.36275e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[170]	valid_0's binary_logloss: 3.38372e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[171]	valid_0's binary_logloss: 3.38604e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[172]	valid_0's binary_logloss: 3.39018e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[173]	valid_0's binary_logloss: 3.38979e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[174]	valid_0's binary_logloss: 3.37429e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[175]	valid_0's binary_logloss: 3.35558e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[176]	valid_0's binary_logloss: 3.32099e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[177]	valid_0's binary_logloss: 3.28086e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[178]	valid_0's binary_logloss: 3.24281e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[179]	valid_0's binary_logloss: 3.20694e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[180]	valid_0's binary_logloss: 3.1323e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[181]	valid_0's binary_logloss: 3.05498e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[182]	valid_0's binary_logloss: 3.01945e-05

Trening klas:  82%|████████▏ | 411/500 [47:49<11:48,  7.96s/klasa, klasa=class_411, F1_klasy=0.0000, F1_macro=0.6423, drzewa=300]




Trening klas:  82%|████████▏ | 412/500 [47:49<11:02,  7.53s/klasa, klasa=class_411, F1_klasy=0.0000, F1_macro=0.6423, drzewa=300]

[1]	valid_0's binary_logloss: 0.0325669
[2]	valid_0's binary_logloss: 0.0298977
[3]	valid_0's binary_logloss: 0.0287663
[4]	valid_0's binary_logloss: 0.027742
[5]	valid_0's binary_logloss: 0.0271991
[6]	valid_0's binary_logloss: 0.0265383
[7]	valid_0's binary_logloss: 0.0262826
[8]	valid_0's binary_logloss: 0.0255795
[9]	valid_0's binary_logloss: 0.0249801
[10]	valid_0's binary_logloss: 0.0247677
[11]	valid_0's binary_logloss: 0.024107
[12]	valid_0's binary_logloss: 0.0237736
[13]	valid_0's binary_logloss: 0.0236007
[14]	valid_0's binary_logloss: 0.023353
[15]	valid_0's binary_logloss: 0.0232059
[16]	valid_0's binary_logloss: 0.0230706
[17]	valid_0's binary_logloss: 0.0228148
[18]	valid_0's binary_logloss: 0.0226223
[19]	valid_0's binary_logloss: 0.0224528
[20]	valid_0's binary_logloss: 0.0222539
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0220104
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0218706
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.0216973
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0215928
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.0214991
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.0213435
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.021236
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.0211852
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.0210589
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.0209391
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.0208605
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.020788
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.0207106
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.0206998
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.0206436
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.0205549
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.0205816
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.0205917
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.0205067
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.0205068
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.0205097
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.0204706
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.0204628
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.0205072
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.0204881
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.0204395
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.0204722
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.0204984
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.0205003
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.0204603
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.020456
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.0204774
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.0205206
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.0205447
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.0205909
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.0206234
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.0206478
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.020703
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.0207573
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.0207338
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.0207335
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.0207429
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.0207519
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.0207582
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.0207753
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.0207741
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.0208178
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.0207999
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.0207672
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.0207761
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.0208057
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.0208443
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.0208861
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.0209088
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.0209507
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.0209688

Trening klas:  82%|████████▏ | 412/500 [47:54<11:02,  7.53s/klasa, klasa=class_412, F1_klasy=0.5667, F1_macro=0.6421, drzewa=46]




Trening klas:  83%|████████▎ | 413/500 [47:54<09:40,  6.67s/klasa, klasa=class_412, F1_klasy=0.5667, F1_macro=0.6421, drzewa=46]

[1]	valid_0's binary_logloss: 0.279542
[2]	valid_0's binary_logloss: 0.0858664
[3]	valid_0's binary_logloss: 0.0793183
[4]	valid_0's binary_logloss: 0.0783219
[5]	valid_0's binary_logloss: 0.0767436
[6]	valid_0's binary_logloss: 0.377448
[7]	valid_0's binary_logloss: 0.376396
[8]	valid_0's binary_logloss: 0.374686
[9]	valid_0's binary_logloss: 0.373016
[10]	valid_0's binary_logloss: 0.371694
[11]	valid_0's binary_logloss: 0.374357
[12]	valid_0's binary_logloss: 0.366215
[13]	valid_0's binary_logloss: 0.357635
[14]	valid_0's binary_logloss: 0.34801
[15]	valid_0's binary_logloss: 0.338339
[16]	valid_0's binary_logloss: 0.334439
[17]	valid_0's binary_logloss: 0.332519
[18]	valid_0's binary_logloss: 0.330703
[19]	valid_0's binary_logloss: 0.328773
[20]	valid_0's binary_logloss: 0.327618
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.325276
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.322374
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.319029
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.318261
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.31617
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.376979
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.376221
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.375148
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.374623
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.373653
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.372668
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.371763
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

Trening klas:  83%|████████▎ | 413/500 [47:58<09:40,  6.67s/klasa, klasa=class_413, F1_klasy=0.4713, F1_macro=0.6417, drzewa=5]




Trening klas:  83%|████████▎ | 414/500 [47:58<08:18,  5.80s/klasa, klasa=class_413, F1_klasy=0.4713, F1_macro=0.6417, drzewa=5]

[33]	valid_0's binary_logloss: 0.371086
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.370305
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.369493
[1]	valid_0's binary_logloss: 1.12687
[2]	valid_0's binary_logloss: 0.644419
[3]	valid_0's binary_logloss: 0.711944
[4]	valid_0's binary_logloss: 0.682515
[5]	valid_0's binary_logloss: 0.669899
[6]	valid_0's binary_logloss: 0.837001
[7]	valid_0's binary_logloss: 0.828677
[8]	valid_0's binary_logloss: 0.8274
[9]	valid_0's binary_logloss: 0.82169
[10]	valid_0's binary_logloss: 0.817808
[11]	valid_0's binary_logloss: 0.846372
[12]	valid_0's binary_logloss: 0.839015
[13]	valid_0's binary_logloss: 0.820191
[14]	valid_0's binary_logloss: 0.801969
[15]	valid_0's binary_logloss: 0.792006
[16]	valid_0's binary_logloss: 0.782904
[17]	valid_0's binary_logloss: 0.774109
[18]	valid_0's binary_logloss: 0.767444
[19]	valid_0's binary_logloss: 0.764193
[20]	valid_0's binary_logloss: 0.761399
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.759274
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.756511
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.75212
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.749952
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.748733
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.746449
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.739378
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.738106
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.737778
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.737618
[31]	valid_0's binary_logloss: 0.757163

Trening klas:  83%|████████▎ | 414/500 [48:01<08:18,  5.80s/klasa, klasa=class_414, F1_klasy=0.2629, F1_macro=0.6408, drzewa=2]




Trening klas:  83%|████████▎ | 415/500 [48:01<07:12,  5.08s/klasa, klasa=class_414, F1_klasy=0.2629, F1_macro=0.6408, drzewa=2]

[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.754743
[1]	valid_0's binary_logloss: 0.0548631
[2]	valid_0's binary_logloss: 0.0422448
[3]	valid_0's binary_logloss: 0.0400148
[4]	valid_0's binary_logloss: 0.0379106
[5]	valid_0's binary_logloss: 0.0361362
[6]	valid_0's binary_logloss: 0.0981477
[7]	valid_0's binary_logloss: 0.0787475
[8]	valid_0's binary_logloss: 0.072267
[9]	valid_0's binary_logloss: 0.0699665
[10]	valid_0's binary_logloss: 0.065783
[11]	valid_0's binary_logloss: 0.0626454
[12]	valid_0's binary_logloss: 0.0601463
[13]	valid_0's binary_logloss: 0.0574135
[14]	valid_0's binary_logloss: 0.0552628
[15]	valid_0's binary_logloss: 0.0533523
[16]	valid_0's binary_logloss: 0.0515868
[17]	valid_0's binary_logloss: 0.0497264
[18]	valid_0's binary_logloss: 0.0481559
[19]	valid_0's binary_logloss: 0.0466978
[20]	valid_0's binary_logloss: 0.0452319
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0438943
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0424194
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.0410208
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0397085
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.0385363
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.0377797
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.0371176
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.0363359
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.0354184
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.0344917
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.0335747
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.0326984
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.0318889
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.0310991
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.0303265
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.0296475
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.0289175
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.0282753
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.0276782
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.0271451
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.0264979
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.0259662
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.0254086
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.0249417
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.0246799
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.0243515
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.0238953
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.023459
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.0230431
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.0226861
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.0222222
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.0217361
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.0213008
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.0208801
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.0204729
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.0202746
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.0200091
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.01972
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.0194984
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.01926
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.0189198
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.0186328
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.0184578
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.0181818
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.0179009
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.017579
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.017286
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.016971
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.0166968
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.0164285
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.0161793
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.0160219
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.0158902
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.0156278
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.0154237
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.0154064
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.0153758
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.0152706
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.0152436
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.0151429
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.0149395
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.0147471
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.0145577
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.0143657
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.0142035
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.0141393
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.0140266
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.0139184
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.0138512
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.0136759
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.0136342
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.0134799
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.0134266
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.0132824
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.0132296
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.0131665
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.0130662
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.0130127
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.0129693
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.0128666
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.012741
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.0126051
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.0124735
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.0124118
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.0122881
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.0122296
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.0121555
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.012114
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.012064
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.0120512
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.0120297
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 0.0120036
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 0.0119771
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 0.0118693
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 0.0117679
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[116]	valid_0's binary_logloss: 0.0117413
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[117]	valid_0's binary_logloss: 0.011744
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[118]	valid_0's binary_logloss: 0.011732
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[119]	valid_0's binary_logloss: 0.0116986
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[120]	valid_0's binary_logloss: 0.0116661
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[121]	valid_0's binary_logloss: 0.0116607
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[122]	valid_0's binary_logloss: 0.0115654
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[123]	valid_0's binary_logloss: 0.0114797
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[124]	valid_0's binary_logloss: 0.011471
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[125]	valid_0's binary_logloss: 0.0114458
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[126]	valid_0's binary_logloss: 0.0112511
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[127]	valid_0's binary_logloss: 0.0110835
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[128]	valid_0's binary_logloss: 0.0109308
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[129]	valid_0's binary_logloss: 0.0107931
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[130]	valid_0's binary_logloss: 0.0106903
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[131]	valid_0's binary_logloss: 0.0107002
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[132]	valid_0's binary_logloss: 0.0106992
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[133]	valid_0's binary_logloss: 0.0107141
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[134]	valid_0's binary_logloss: 0.01073
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[135]	valid_0's binary_logloss: 0.0107126
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[136]	valid_0's binary_logloss: 0.0107221
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[137]	valid_0's binary_logloss: 0.0107466
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[138]	valid_0's binary_logloss: 0.0107803
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[139]	valid_0's binary_logloss: 0.0107907
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[140]	valid_0's binary_logloss: 0.0108246
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[141]	valid_0's binary_logloss: 0.0108562
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[142]	valid_0's binary_logloss: 0.0108772
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[143]	valid_0's binary_logloss: 0.0108973
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[144]	valid_0's binary_logloss: 0.0109186
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[145]	valid_0's binary_logloss: 0.0109417
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[146]	valid_0's binary_logloss: 0.0108982
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[147]	valid_0's binary_logloss: 0.0109135
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[148]	valid_0's binary_logloss: 0.0108678
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[149]	valid_0's binary_logloss: 0.0109024
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[150]	valid_0's binary_logloss: 0.0109292
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[151]	valid_0's binary_logloss: 0.0109728
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[152]	valid_0's binary_logloss: 0.0110158
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[153]	valid_0's binary_logloss: 0.011061
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[154]	valid_0's binary_logloss: 0.0111045
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[155]	valid_0's binary_logloss: 0.0111486
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[156]	valid_0's binary_logloss: 0.0111377
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[157]	valid_0's binary_logloss: 0.01114
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[158]	valid_0's binary_logloss: 0.0111171
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[159]	valid_0's binary_logloss: 0.0111194
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[160]	valid_0's binary_logloss: 0.0111456

Trening klas:  83%|████████▎ | 415/500 [48:06<07:12,  5.08s/klasa, klasa=class_415, F1_klasy=0.7273, F1_macro=0.6410, drzewa=130]




Trening klas:  83%|████████▎ | 416/500 [48:06<07:11,  5.14s/klasa, klasa=class_415, F1_klasy=0.7273, F1_macro=0.6410, drzewa=130]

[1]	valid_0's binary_logloss: 0.0234099
[2]	valid_0's binary_logloss: 0.0148739
[3]	valid_0's binary_logloss: 0.0131426
[4]	valid_0's binary_logloss: 0.0118651
[5]	valid_0's binary_logloss: 0.010844
[6]	valid_0's binary_logloss: 0.00998715
[7]	valid_0's binary_logloss: 0.00929464
[8]	valid_0's binary_logloss: 0.0086432
[9]	valid_0's binary_logloss: 0.00810095
[10]	valid_0's binary_logloss: 0.0075763
[11]	valid_0's binary_logloss: 0.00710017
[12]	valid_0's binary_logloss: 0.00668148
[13]	valid_0's binary_logloss: 0.00637361
[14]	valid_0's binary_logloss: 0.00608465
[15]	valid_0's binary_logloss: 0.00573447
[16]	valid_0's binary_logloss: 0.0054342
[17]	valid_0's binary_logloss: 0.00517951
[18]	valid_0's binary_logloss: 0.00489458
[19]	valid_0's binary_logloss: 0.00462851
[20]	valid_0's binary_logloss: 0.00441762
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.00417898
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.00398092
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.00379475
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.00359868
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.00341336
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.00325375
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.00310381
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.00296386
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.00283139
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.0027128
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.00257698
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.00245479
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.00235016
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.00224409
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.00215335
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.00205295
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.00195741
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.00188332
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.00179972
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.00171649
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.00163613
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.00155942
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.00148638
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.00141743
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.00135131
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.00128895
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.00122907
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.00117209
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.00113321
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.00108031
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.00103091
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.000982991
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.000952139
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.000907353
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.000879963
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.000838641
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.000799288
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.000761811
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.00072612
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.000692132
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.000661079
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.000631503
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.000602446
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.000575856
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.000549423
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.000523828
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.000499467
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.000476276
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.000454199
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.000433183
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.000413239
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.000394231
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.000376136
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.000358501
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.000342127
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.000326501
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.000311626
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.000297106
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.000283626
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.00027082
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.000264545
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.00025885
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.000246983
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.000235692
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.000226191
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.000216248
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.000206768
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.000197454
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.00018887
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.000180426
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.000172382
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.000164731
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.000157454
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.000150533
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.000143942
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.000137679
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.000132749
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.000127028
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.000122596
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.000118438
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.000113433
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.000108666
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.000105061
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.000100883
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 9.673e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 9.27823e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 8.90259e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 8.77209e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 8.51996e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 8.18275e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 7.9594e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 7.74677e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 7.54436e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 7.27728e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 7.0934e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[116]	valid_0's binary_logloss: 6.90311e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[117]	valid_0's binary_logloss: 6.64095e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[118]	valid_0's binary_logloss: 6.47028e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[119]	valid_0's binary_logloss: 6.23109e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[120]	valid_0's binary_logloss: 6.07755e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[121]	valid_0's binary_logloss: 5.85783e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[122]	valid_0's binary_logloss: 5.64856e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[123]	valid_0's binary_logloss: 5.50034e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[124]	valid_0's binary_logloss: 5.30831e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[125]	valid_0's binary_logloss: 5.17418e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[126]	valid_0's binary_logloss: 5.07476e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[127]	valid_0's binary_logloss: 4.97654e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[128]	valid_0's binary_logloss: 4.88255e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[129]	valid_0's binary_logloss: 4.72091e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[130]	valid_0's binary_logloss: 4.63697e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[131]	valid_0's binary_logloss: 4.50472e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[132]	valid_0's binary_logloss: 4.45027e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[133]	valid_0's binary_logloss: 4.386e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[134]	valid_0's binary_logloss: 4.26531e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[135]	valid_0's binary_logloss: 4.19614e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[136]	valid_0's binary_logloss: 4.14207e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[137]	valid_0's binary_logloss: 4.09071e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[138]	valid_0's binary_logloss: 3.96431e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[139]	valid_0's binary_logloss: 3.91645e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[140]	valid_0's binary_logloss: 3.87423e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[141]	valid_0's binary_logloss: 3.76233e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[142]	valid_0's binary_logloss: 3.65547e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[143]	valid_0's binary_logloss: 3.55338e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[144]	valid_0's binary_logloss: 3.45584e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[145]	valid_0's binary_logloss: 3.42268e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[146]	valid_0's binary_logloss: 3.39174e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[147]	valid_0's binary_logloss: 3.36196e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[148]	valid_0's binary_logloss: 3.33376e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[149]	valid_0's binary_logloss: 3.30593e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[150]	valid_0's binary_logloss: 3.27969e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[151]	valid_0's binary_logloss: 3.23607e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[152]	valid_0's binary_logloss: 3.22817e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[153]	valid_0's binary_logloss: 3.192e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[154]	valid_0's binary_logloss: 3.18725e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[155]	valid_0's binary_logloss: 3.18461e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[156]	valid_0's binary_logloss: 3.15516e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[157]	valid_0's binary_logloss: 3.13371e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[158]	valid_0's binary_logloss: 3.11361e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[159]	valid_0's binary_logloss: 3.09485e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[160]	valid_0's binary_logloss: 3.06993e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[161]	valid_0's binary_logloss: 3.04221e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[162]	valid_0's binary_logloss: 3.01516e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[163]	valid_0's binary_logloss: 3.01802e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[164]	valid_0's binary_logloss: 3.02278e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[165]	valid_0's binary_logloss: 2.99756e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[166]	valid_0's binary_logloss: 2.936e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[167]	valid_0's binary_logloss: 2.9242e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[168]	valid_0's binary_logloss: 2.91326e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[169]	valid_0's binary_logloss: 2.90315e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[170]	valid_0's binary_logloss: 2.88955e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[171]	valid_0's binary_logloss: 2.89628e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[172]	valid_0's binary_logloss: 2.90326e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[173]	valid_0's binary_logloss: 2.88334e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[174]	valid_0's binary_logloss: 2.86334e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[175]	valid_0's binary_logloss: 2.83949e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[176]	valid_0's binary_logloss: 2.78605e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[177]	valid_0's binary_logloss: 2.73473e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[178]	valid_0's binary_logloss: 2.72557e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[179]	valid_0's binary_logloss: 2.6771e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[180]	valid_0's binary_logloss: 2.63052e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[181]	valid_0's binary_logloss: 2.61529e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[182]	valid_0's binary_logloss: 2.60935e-05

Trening klas:  83%|████████▎ | 416/500 [48:12<07:11,  5.14s/klasa, klasa=class_416, F1_klasy=0.0000, F1_macro=0.6394, drzewa=299]




Trening klas:  83%|████████▎ | 417/500 [48:12<07:07,  5.15s/klasa, klasa=class_416, F1_klasy=0.0000, F1_macro=0.6394, drzewa=299]

[299]	valid_0's binary_logloss: 1.85153e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[300]	valid_0's binary_logloss: 1.84768e-05
[1]	valid_0's binary_logloss: 0.038378
[2]	valid_0's binary_logloss: 0.0330563
[3]	valid_0's binary_logloss: 0.0295337
[4]	valid_0's binary_logloss: 0.027308
[5]	valid_0's binary_logloss: 0.0256243
[6]	valid_0's binary_logloss: 0.0244294
[7]	valid_0's binary_logloss: 0.0235801
[8]	valid_0's binary_logloss: 0.0226868
[9]	valid_0's binary_logloss: 0.0216841
[10]	valid_0's binary_logloss: 0.0209054
[11]	valid_0's binary_logloss: 0.0202247
[12]	valid_0's binary_logloss: 0.0195586
[13]	valid_0's binary_logloss: 0.0189699
[14]	valid_0's binary_logloss: 0.0184166
[15]	valid_0's binary_logloss: 0.0179313
[16]	valid_0's binary_logloss: 0.0173938
[17]	valid_0's binary_logloss: 0.016824
[18]	valid_0's binary_logloss: 0.0164858
[19]	valid_0's binary_logloss: 0.0161948
[20]	valid_0's binary_logloss: 0.0158384
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0155264
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0151928
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.0149738
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0146894
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.0144628
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.0142592
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.0140359
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.0138069
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.0135626
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.0134019
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.0131909
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.0130027
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.0128173
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.0126944
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.0125545
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.0122949
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.0120694
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.0119172
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.0117066
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.0115206
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.0114125
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.0112989
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.0111691
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.0110418
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.0109141
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.0107213
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.0105835
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.0104402
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.0103175
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.0102299
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.0100874
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.00997292
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.00989497
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.00980478
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.00968294
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.00963629
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.00956271
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.00950354
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.00944313
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.00937985
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.00931962
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.00922999
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.0092161
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.00916133
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.00910873
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.00905686
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.00901886
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.00898609
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.00890699
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.00887759
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.00887311
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.00887648
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.00888407
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.00888998
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.00890003
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.00876853
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.00871713
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.00859809
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.008565
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.00846994
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.00847964
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.00849096
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.00849767
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.00850401
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.0085125
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.00849089
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.00847397
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.00845684
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.00842065
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.0083981
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.0083946
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.00838814
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.00839393
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.00836992
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.00838916
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.00837948
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.00840473
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.00841167
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.00843275
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.00844751
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.00842522
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.00843709
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.00842547
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.00842464
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.00846995
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.00846515
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.00847806
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.00848562
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.00844292
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.00840797
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.00839473
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 0.00837754
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 0.00834582
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 0.00833546
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 0.00829761
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[116]	valid_0's binary_logloss: 0.00831094
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[117]	valid_0's binary_logloss: 0.00831355
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[118]	valid_0's binary_logloss: 0.00831942
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[119]	valid_0's binary_logloss: 0.00832573
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[120]	valid_0's binary_logloss: 0.0082849
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[121]	valid_0's binary_logloss: 0.00827933
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[122]	valid_0's binary_logloss: 0.00824892
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[123]	valid_0's binary_logloss: 0.00824025
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[124]	valid_0's binary_logloss: 0.0082182
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[125]	valid_0's binary_logloss: 0.00822084
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[126]	valid_0's binary_logloss: 0.00824258
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[127]	valid_0's binary_logloss: 0.00823745
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[128]	valid_0's binary_logloss: 0.00823288
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[129]	valid_0's binary_logloss: 0.00827407
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[130]	valid_0's binary_logloss: 0.00832407
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[131]	valid_0's binary_logloss: 0.00832948
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[132]	valid_0's binary_logloss: 0.00837792
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[133]	valid_0's binary_logloss: 0.00841888
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[134]	valid_0's binary_logloss: 0.00843846
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[135]	valid_0's binary_logloss: 0.0084853
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[136]	valid_0's binary_logloss: 0.00849924
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[137]	valid_0's binary_logloss: 0.00850232
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[138]	valid_0's binary_logloss: 0.0084839
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[139]	valid_0's binary_logloss: 0.00847422
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[140]	valid_0's binary_logloss: 0.00846498
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[141]	valid_0's binary_logloss: 0.00843249
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[142]	valid_0's binary_logloss: 0.00841248
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[143]	valid_0's binary_logloss: 0.00841777
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[144]	valid_0's binary_logloss: 0.00842751
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[145]	valid_0's binary_logloss: 0.00843042
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[146]	valid_0's binary_logloss: 0.00840742
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[147]	valid_0's binary_logloss: 0.00839255
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[148]	valid_0's binary_logloss: 0.00840666
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[149]	valid_0's binary_logloss: 0.00841447
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[150]	valid_0's binary_logloss: 0.0084345
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

Trening klas:  83%|████████▎ | 417/500 [48:19<07:07,  5.15s/klasa, klasa=class_417, F1_klasy=0.8077, F1_macro=0.6398, drzewa=124]




Trening klas:  84%|████████▎ | 418/500 [48:19<07:58,  5.84s/klasa, klasa=class_417, F1_klasy=0.8077, F1_macro=0.6398, drzewa=124]

[151]	valid_0's binary_logloss: 0.0084438
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[152]	valid_0's binary_logloss: 0.00846058
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[153]	valid_0's binary_logloss: 0.00848059
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[154]	valid_0's binary_logloss: 0.00848642
[1]	valid_0's binary_logloss: 0.102641
[2]	valid_0's binary_logloss: 0.0593365
[3]	valid_0's binary_logloss: 0.0546677
[4]	valid_0's binary_logloss: 0.0514742
[5]	valid_0's binary_logloss: 0.0477081
[6]	valid_0's binary_logloss: 0.0452807
[7]	valid_0's binary_logloss: 0.0429521
[8]	valid_0's binary_logloss: 0.0404185
[9]	valid_0's binary_logloss: 0.0390488
[10]	valid_0's binary_logloss: 0.037063
[11]	valid_0's binary_logloss: 0.0357543
[12]	valid_0's binary_logloss: 0.0345165
[13]	valid_0's binary_logloss: 0.0333111
[14]	valid_0's binary_logloss: 0.0322894
[15]	valid_0's binary_logloss: 0.0313858
[16]	valid_0's binary_logloss: 0.0302742
[17]	valid_0's binary_logloss: 0.0293563
[18]	valid_0's binary_logloss: 0.0285856
[19]	valid_0's binary_logloss: 0.0278731
[20]	valid_0's binary_logloss: 0.0271781
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0264918
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0258582
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.02533
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0247771
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.0241471
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.0236619
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.0231809
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.0228068
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.022318
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.0218201
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.0214413
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.0210978
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.0207716
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.0204546
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.0201543
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.0198153
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.0195102
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.0192203
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.0188737
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.0185734
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.0182404
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.0179188
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.0176567
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.0173923
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.0171057
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.0168822
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.0166635
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.016413
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.0161794
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.0159599
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.0157881
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.0156789
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.0155376
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.0153915
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.0152343
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.0151658
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.0150608
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.0148565
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.0147385
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.0146109
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.014456
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.0142509
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.0141102
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.0140234
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.0139623
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.0138663
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.0137675
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.0136949
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.0136128
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.0135592
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.0134279
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.0133381
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.0132648
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.0131477
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.0130503
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.0129579
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.0128867
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.0128284
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.0127347
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.0126899
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.0126102
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.012535
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.012463
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.0124857
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.0124213
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.0123561
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.012278
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.0122393
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.0121736
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.0121132
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.012106
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.0120998
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.0120659
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.0120004
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.011942
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.0118948
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.0118219
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.0117844
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.0117346
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.0117069
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.0116779
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.0116783
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.0116373
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.0116149
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.0115753
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.0115004
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.0114331
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.0114336
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.0113459
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.0113084
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.011283
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 0.0112109
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 0.0111766
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 0.0111472
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 0.0110864
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[116]	valid_0's binary_logloss: 0.0110772
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[117]	valid_0's binary_logloss: 0.0110548
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[118]	valid_0's binary_logloss: 0.0110477
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[119]	valid_0's binary_logloss: 0.0110471
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[120]	valid_0's binary_logloss: 0.011023
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[121]	valid_0's binary_logloss: 0.0109866
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[122]	valid_0's binary_logloss: 0.010957
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[123]	valid_0's binary_logloss: 0.0109303
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[124]	valid_0's binary_logloss: 0.0108781
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[125]	valid_0's binary_logloss: 0.0108436
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[126]	valid_0's binary_logloss: 0.010826
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[127]	valid_0's binary_logloss: 0.01081
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[128]	valid_0's binary_logloss: 0.0107954
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[129]	valid_0's binary_logloss: 0.0108167
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[130]	valid_0's binary_logloss: 0.0108361
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[131]	valid_0's binary_logloss: 0.01085
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[132]	valid_0's binary_logloss: 0.0108754
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[133]	valid_0's binary_logloss: 0.0108459
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[134]	valid_0's binary_logloss: 0.0108776
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[135]	valid_0's binary_logloss: 0.0108726
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[136]	valid_0's binary_logloss: 0.0108553
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[137]	valid_0's binary_logloss: 0.0108733
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[138]	valid_0's binary_logloss: 0.0108533
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[139]	valid_0's binary_logloss: 0.0108334
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[140]	valid_0's binary_logloss: 0.0108131
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[141]	valid_0's binary_logloss: 0.010825
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[142]	valid_0's binary_logloss: 0.0108394
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[143]	valid_0's binary_logloss: 0.0108561
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[144]	valid_0's binary_logloss: 0.0108753
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[145]	valid_0's binary_logloss: 0.010893
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[146]	valid_0's binary_logloss: 0.0109044
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[147]	valid_0's binary_logloss: 0.0108828
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[148]	valid_0's binary_logloss: 0.010906
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[149]	valid_0's binary_logloss: 0.0108748
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[150]	valid_0's binary_logloss: 0.0108513
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[151]	valid_0's binary_logloss: 0.0108672
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

Trening klas:  84%|████████▎ | 418/500 [48:24<07:58,  5.84s/klasa, klasa=class_418, F1_klasy=0.7671, F1_macro=0.6401, drzewa=128]




Trening klas:  84%|████████▍ | 419/500 [48:24<07:30,  5.56s/klasa, klasa=class_418, F1_klasy=0.7671, F1_macro=0.6401, drzewa=128]

[152]	valid_0's binary_logloss: 0.0108694
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[153]	valid_0's binary_logloss: 0.0108775
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[154]	valid_0's binary_logloss: 0.0108772
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[155]	valid_0's binary_logloss: 0.0108698
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[156]	valid_0's binary_logloss: 0.0108234
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[157]	valid_0's binary_logloss: 0.0108501
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[158]	valid_0's binary_logloss: 0.0108526
[1]	valid_0's binary_logloss: 0.231119
[2]	valid_0's binary_logloss: 0.182634
[3]	valid_0's binary_logloss: 0.168597
[4]	valid_0's binary_logloss: 0.159474
[5]	valid_0's binary_logloss: 0.152725
[6]	valid_0's binary_logloss: 0.144589
[7]	valid_0's binary_logloss: 0.138297
[8]	valid_0's binary_logloss: 0.133004
[9]	valid_0's binary_logloss: 0.128477
[10]	valid_0's binary_logloss: 0.124625
[11]	valid_0's binary_logloss: 0.121376
[12]	valid_0's binary_logloss: 0.118439
[13]	valid_0's binary_logloss: 0.115658
[14]	valid_0's binary_logloss: 0.113057
[15]	valid_0's binary_logloss: 0.110478
[16]	valid_0's binary_logloss: 0.10815
[17]	valid_0's binary_logloss: 0.106194
[18]	valid_0's binary_logloss: 0.104398
[19]	valid_0's binary_logloss: 0.102219
[20]	valid_0's binary_logloss: 0.100218
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0984546
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0963175
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.0943895
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0923992
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.0907447
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.089301
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.087611
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.0859392
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.084539
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.0829719
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.0815214
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.0801632
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.0787434
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.0772808
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.0759658
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.0748525
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.0738017
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.0728407
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.0718279
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.070781
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.0698361
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.0687142
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.0677418
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.0667776
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.0657182
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.0649406
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.0639745
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.0632183
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.0624011
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.061626
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.0608534
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.0601381
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.0595623
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.0587824
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.0582403
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.0576363
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.0570535
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.0565184
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.0559286
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.0552479
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.0546801
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.0540093
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.0533172
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.0526207
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.0519806
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.0515405
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.0510775
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.0505572
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.0499897
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.0495198
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.0490175
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.0484117
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.04791
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.0474449
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.0470337
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.0465136
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.0460296
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.04559
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.0451118
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.0446866
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.0443617
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.043996
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.0435733
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.0431069
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.0428561
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.0424276
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.0418916
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.0415382
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.0410624
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.040696
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.0403305
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.0399739
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.039614
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.039335
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.0391103
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.0388592
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.0385449
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.0382237
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.0378966
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.0376623
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.0374371
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.0372508
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.0369008
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.0367078
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.0364314
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.0360889
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.0358824
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.0357564
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.0355106
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.0353256
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.0352118
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 0.0350911
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 0.035025
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 0.0348175
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 0.0347609
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[116]	valid_0's binary_logloss: 0.0345492
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[117]	valid_0's binary_logloss: 0.0344078
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[118]	valid_0's binary_logloss: 0.0342431
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[119]	valid_0's binary_logloss: 0.0340508
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[120]	valid_0's binary_logloss: 0.0339538
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[121]	valid_0's binary_logloss: 0.0338615
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[122]	valid_0's binary_logloss: 0.0338309
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[123]	valid_0's binary_logloss: 0.0337709
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[124]	valid_0's binary_logloss: 0.0336431
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[125]	valid_0's binary_logloss: 0.0335152
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[126]	valid_0's binary_logloss: 0.0333898
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[127]	valid_0's binary_logloss: 0.0333376
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[128]	valid_0's binary_logloss: 0.0332928
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[129]	valid_0's binary_logloss: 0.0331666
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[130]	valid_0's binary_logloss: 0.0331684
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[131]	valid_0's binary_logloss: 0.0330626
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[132]	valid_0's binary_logloss: 0.0329938
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[133]	valid_0's binary_logloss: 0.0328759
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[134]	valid_0's binary_logloss: 0.0328055
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[135]	valid_0's binary_logloss: 0.0327292
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[136]	valid_0's binary_logloss: 0.0325945
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[137]	valid_0's binary_logloss: 0.0324459
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[138]	valid_0's binary_logloss: 0.0323155
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[139]	valid_0's binary_logloss: 0.0322863
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[140]	valid_0's binary_logloss: 0.0321919
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[141]	valid_0's binary_logloss: 0.0320323
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[142]	valid_0's binary_logloss: 0.0318688
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[143]	valid_0's binary_logloss: 0.0317197
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[144]	valid_0's binary_logloss: 0.0315777
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[145]	valid_0's binary_logloss: 0.0314379
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[146]	valid_0's binary_logloss: 0.0314311
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[147]	valid_0's binary_logloss: 0.0314274
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[148]	valid_0's binary_logloss: 0.0314162
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[149]	valid_0's binary_logloss: 0.0313633
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[150]	valid_0's binary_logloss: 0.0313409
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[151]	valid_0's binary_logloss: 0.0313204
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[152]	valid_0's binary_logloss: 0.031327
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[153]	valid_0's binary_logloss: 0.0313141
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[154]	valid_0's binary_logloss: 0.0313049
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[155]	valid_0's binary_logloss: 0.031301
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[156]	valid_0's binary_logloss: 0.0312748
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[157]	valid_0's binary_logloss: 0.0312331
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[158]	valid_0's binary_logloss: 0.0311846
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[159]	valid_0's binary_logloss: 0.0311638
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[160]	valid_0's binary_logloss: 0.0311869
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[161]	valid_0's binary_logloss: 0.0310889
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[162]	valid_0's binary_logloss: 0.0310525
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[163]	valid_0's binary_logloss: 0.0310232
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[164]	valid_0's binary_logloss: 0.0310022
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[165]	valid_0's binary_logloss: 0.0309624
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[166]	valid_0's binary_logloss: 0.0310161
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[167]	valid_0's binary_logloss: 0.0309439
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[168]	valid_0's binary_logloss: 0.0309706
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[169]	valid_0's binary_logloss: 0.0308402
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[170]	valid_0's binary_logloss: 0.0307501
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[171]	valid_0's binary_logloss: 0.0306978
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[172]	valid_0's binary_logloss: 0.0306408
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[173]	valid_0's binary_logloss: 0.0305963
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[174]	valid_0's binary_logloss: 0.0305862
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[175]	valid_0's binary_logloss: 0.030536
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[176]	valid_0's binary_logloss: 0.030521
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[177]	valid_0's binary_logloss: 0.0304972
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[178]	valid_0's binary_logloss: 0.0304507
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

Trening klas:  84%|████████▍ | 419/500 [48:32<07:30,  5.56s/klasa, klasa=class_419, F1_klasy=0.4948, F1_macro=0.6398, drzewa=281]




Trening klas:  84%|████████▍ | 420/500 [48:32<08:21,  6.27s/klasa, klasa=class_419, F1_klasy=0.4948, F1_macro=0.6398, drzewa=281]

[1]	valid_0's binary_logloss: 0.0234099
[2]	valid_0's binary_logloss: 0.0148739
[3]	valid_0's binary_logloss: 0.0131426
[4]	valid_0's binary_logloss: 0.0118651
[5]	valid_0's binary_logloss: 0.010844
[6]	valid_0's binary_logloss: 0.00998715
[7]	valid_0's binary_logloss: 0.00929464
[8]	valid_0's binary_logloss: 0.0086432
[9]	valid_0's binary_logloss: 0.00810095
[10]	valid_0's binary_logloss: 0.0075763
[11]	valid_0's binary_logloss: 0.00710017
[12]	valid_0's binary_logloss: 0.00668148
[13]	valid_0's binary_logloss: 0.00637361
[14]	valid_0's binary_logloss: 0.00608465
[15]	valid_0's binary_logloss: 0.00573447
[16]	valid_0's binary_logloss: 0.0054342
[17]	valid_0's binary_logloss: 0.00517951
[18]	valid_0's binary_logloss: 0.00489458
[19]	valid_0's binary_logloss: 0.00462851
[20]	valid_0's binary_logloss: 0.00441762
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.00417898
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.00398092
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.00379475
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.00359868
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.00341336
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.00325375
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.00310381
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.00296386
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.00283139
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.0027128
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.00257698
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.00245479
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.00235016
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.00224409
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.00215335
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.00205295
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.00195741
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.00188332
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.00179972
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.00171649
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.00163613
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.00155942
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.00148638
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.00141743
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.00135131
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.00128895
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.00122907
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.00117209
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.00113321
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.00108031
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.00103091
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.000982991
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.000952139
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.000907353
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.000879963
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.000838641
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.000799288
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.000761811
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.00072612
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.000692132
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.000661079
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.000631503
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.000602446
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.000575856
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.000549423
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.000523828
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.000499467
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.000476276
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.000454199
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.000433183
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.000413239
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.000394231
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.000376136
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.000358501
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.000342127
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.000326501
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.000311626
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.000297106
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.000283626
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.00027082
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.000264545
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.00025885
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.000246983
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.000235692
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.000226191
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.000216248
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.000206768
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.000197454
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.00018887
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.000180426
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.000172382
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.000164731
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.000157454
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.000150533
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.000143942
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.000137679
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.000132749
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.000127028
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.000122596
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.000118438
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.000113433
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.000108666
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.000105061
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.000100883
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 9.673e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 9.27823e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 8.90259e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 8.77209e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 8.51996e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 8.18275e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 7.9594e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 7.74677e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 7.54436e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 7.27728e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 7.0934e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[116]	valid_0's binary_logloss: 6.90311e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[117]	valid_0's binary_logloss: 6.64095e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[118]	valid_0's binary_logloss: 6.47028e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[119]	valid_0's binary_logloss: 6.23109e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[120]	valid_0's binary_logloss: 6.07755e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[121]	valid_0's binary_logloss: 5.85783e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[122]	valid_0's binary_logloss: 5.64856e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[123]	valid_0's binary_logloss: 5.50034e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[124]	valid_0's binary_logloss: 5.30831e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[125]	valid_0's binary_logloss: 5.17418e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[126]	valid_0's binary_logloss: 5.07476e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[127]	valid_0's binary_logloss: 4.97654e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[128]	valid_0's binary_logloss: 4.88255e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[129]	valid_0's binary_logloss: 4.72091e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[130]	valid_0's binary_logloss: 4.63697e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[131]	valid_0's binary_logloss: 4.50472e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[132]	valid_0's binary_logloss: 4.45027e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[133]	valid_0's binary_logloss: 4.386e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[134]	valid_0's binary_logloss: 4.26531e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[135]	valid_0's binary_logloss: 4.19614e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[136]	valid_0's binary_logloss: 4.14207e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[137]	valid_0's binary_logloss: 4.09071e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[138]	valid_0's binary_logloss: 3.96431e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[139]	valid_0's binary_logloss: 3.91645e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[140]	valid_0's binary_logloss: 3.87423e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[141]	valid_0's binary_logloss: 3.76233e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[142]	valid_0's binary_logloss: 3.65547e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[143]	valid_0's binary_logloss: 3.55338e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[144]	valid_0's binary_logloss: 3.45584e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[145]	valid_0's binary_logloss: 3.42268e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[146]	valid_0's binary_logloss: 3.39174e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[147]	valid_0's binary_logloss: 3.36196e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[148]	valid_0's binary_logloss: 3.33376e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[149]	valid_0's binary_logloss: 3.30593e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[150]	valid_0's binary_logloss: 3.27969e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[151]	valid_0's binary_logloss: 3.23607e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[152]	valid_0's binary_logloss: 3.22817e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[153]	valid_0's binary_logloss: 3.192e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[154]	valid_0's binary_logloss: 3.18725e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[155]	valid_0's binary_logloss: 3.18461e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[156]	valid_0's binary_logloss: 3.15516e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[157]	valid_0's binary_logloss: 3.13371e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[158]	valid_0's binary_logloss: 3.11361e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[159]	valid_0's binary_logloss: 3.09485e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[160]	valid_0's binary_logloss: 3.06993e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[161]	valid_0's binary_logloss: 3.04221e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[162]	valid_0's binary_logloss: 3.01516e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[163]	valid_0's binary_logloss: 3.01802e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[164]	valid_0's binary_logloss: 3.02278e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[165]	valid_0's binary_logloss: 2.99756e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[166]	valid_0's binary_logloss: 2.936e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[167]	valid_0's binary_logloss: 2.9242e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[168]	valid_0's binary_logloss: 2.91326e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[169]	valid_0's binary_logloss: 2.90315e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[170]	valid_0's binary_logloss: 2.88955e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[171]	valid_0's binary_logloss: 2.89628e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[172]	valid_0's binary_logloss: 2.90326e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[173]	valid_0's binary_logloss: 2.88334e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[174]	valid_0's binary_logloss: 2.86334e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[175]	valid_0's binary_logloss: 2.83949e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[176]	valid_0's binary_logloss: 2.78605e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[177]	valid_0's binary_logloss: 2.73473e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[178]	valid_0's binary_logloss: 2.72557e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[179]	valid_0's binary_logloss: 2.6771e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[180]	valid_0's binary_logloss: 2.63052e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[181]	valid_0's binary_logloss: 2.61529e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[182]	valid_0's binary_logloss: 2.60935e-05

Trening klas:  84%|████████▍ | 420/500 [48:38<08:21,  6.27s/klasa, klasa=class_420, F1_klasy=0.0000, F1_macro=0.6383, drzewa=299]




Trening klas:  84%|████████▍ | 421/500 [48:38<08:11,  6.22s/klasa, klasa=class_420, F1_klasy=0.0000, F1_macro=0.6383, drzewa=299]

[289]	valid_0's binary_logloss: 1.86751e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[290]	valid_0's binary_logloss: 1.86693e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[291]	valid_0's binary_logloss: 1.86693e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[292]	valid_0's binary_logloss: 1.86567e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[293]	valid_0's binary_logloss: 1.86446e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[294]	valid_0's binary_logloss: 1.86328e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[295]	valid_0's binary_logloss: 1.86214e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[296]	valid_0's binary_logloss: 1.86103e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[297]	valid_0's binary_logloss: 1.85691e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[298]	valid_0's binary_logloss: 1.8555e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[299]	valid_0's binary_logloss: 1.85153e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[300]	valid_0's binary_logloss: 1.84768e-05
[1]	valid_0's binary_logloss: 0.0313371
[2]	valid_0's binary_logloss: 0.0201831
[3]	valid_0's binary_logloss: 0.0187209
[4]	valid_0's binary_logloss: 0.0174637
[5]	valid_0's binary_logloss: 0.0164363
[6]	valid_0's binary_logloss: 0.0155044
[7]	valid_0's binary_logloss: 0.0146809
[8]	valid_0's binary_logloss: 0.0139743
[9]	valid_0's binary_logloss: 0.0133506
[10]	valid_0's binary_logloss: 0.0127423
[11]	valid_0's binary_logloss: 0.0122157
[12]	valid_0's binary_logloss: 0.0117055
[13]	valid_0's binary_logloss: 0.0112351
[14]	valid_0's binary_logloss: 0.0108309
[15]	valid_0's binary_logloss: 0.0104036
[16]	valid_0's binary_logloss: 0.00998817
[17]	valid_0's binary_logloss: 0.00956264
[18]	valid_0's binary_logloss: 0.00918576
[19]	valid_0's binary_logloss: 0.00881006
[20]	valid_0's binary_logloss: 0.00844586
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.00809509
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.00771957
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.00749115
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.00724648
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.00696659
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.00671877
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.00644511
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.00618536
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.00593563
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.00569839
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.00549484
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.00529539
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.00511075
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.00492811
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.00475202
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.00456279
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.00439004
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.0042152
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.00404307
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.0038838
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.00373049
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.00358487
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.00345716
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.00332144
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.00319013
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.00306919
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.00295263
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.00283414
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.0027205
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.0026103
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.00253933
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.00247282
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.00237998
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.00232045
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.00223157
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.00218231
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.00209453
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.00200959
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.00192731
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.00185713
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.00178215
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.00171409
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.00165472
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.00159554
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.00153463
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.00147197
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.00142054
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.0013648
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.0013093
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.00126472
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.00121998
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.00118331
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.00114171
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.0011134
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.00107002
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.00103722
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.000994445
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.000953901
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.000914654
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.000877149
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.000842838
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.000810113
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.000778928
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.000746575
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.000720131
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.000690195
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.000665224
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.000637927
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.000611332
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.000600983
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.000579288
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.000573554
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.000553413
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.000534335
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.000532084
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.000526688
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.000519022
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.000508791
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.000507903
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.00050788
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.000495243
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.000476911
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.000472748
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.000461909
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.000459214
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.000450004
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.000441379
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.000436077
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.000428401
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.000414154
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.000416427
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 0.000417656
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 0.00042083
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 0.00041981
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 0.000420786
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[116]	valid_0's binary_logloss: 0.000413807
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[117]	valid_0's binary_logloss: 0.000405946
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[118]	valid_0's binary_logloss: 0.000405908
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[119]	valid_0's binary_logloss: 0.000398718
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[120]	valid_0's binary_logloss: 0.000383402
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[121]	valid_0's binary_logloss: 0.000386923
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[122]	valid_0's binary_logloss: 0.000392147
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[123]	valid_0's binary_logloss: 0.000388868
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[124]	valid_0's binary_logloss: 0.000385066
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[125]	valid_0's binary_logloss: 0.000385915
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[126]	valid_0's binary_logloss: 0.000386527
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[127]	valid_0's binary_logloss: 0.000386768
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[128]	valid_0's binary_logloss: 0.000374181
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[129]	valid_0's binary_logloss: 0.000368382
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[130]	valid_0's binary_logloss: 0.000363245
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[131]	valid_0's binary_logloss: 0.000361125
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[132]	valid_0's binary_logloss: 0.000359328
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[133]	valid_0's binary_logloss: 0.000358041
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[134]	valid_0's binary_logloss: 0.000365151
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[135]	valid_0's binary_logloss: 0.000363685
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[136]	valid_0's binary_logloss: 0.000364895
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[137]	valid_0's binary_logloss: 0.000367509
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[138]	valid_0's binary_logloss: 0.000358356
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[139]	valid_0's binary_logloss: 0.000361149
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[140]	valid_0's binary_logloss: 0.000363823
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[141]	valid_0's binary_logloss: 0.000363819
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[142]	valid_0's binary_logloss: 0.000353497
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[143]	valid_0's binary_logloss: 0.000352568
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[144]	valid_0's binary_logloss: 0.000352629
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[145]	valid_0's binary_logloss: 0.000352886
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[146]	valid_0's binary_logloss: 0.000348737
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[147]	valid_0's binary_logloss: 0.000335613
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[148]	valid_0's binary_logloss: 0.000323333
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[149]	valid_0's binary_logloss: 0.000319895
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[150]	valid_0's binary_logloss: 0.000316109
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[151]	valid_0's binary_logloss: 0.000321682
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[152]	valid_0's binary_logloss: 0.000327845
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[153]	valid_0's binary_logloss: 0.000333359
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[154]	valid_0's binary_logloss: 0.00033938
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[155]	valid_0's binary_logloss: 0.000346232
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[156]	valid_0's binary_logloss: 0.000348861
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[157]	valid_0's binary_logloss: 0.000346903
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[158]	valid_0's binary_logloss: 0.000344349
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[159]	valid_0's binary_logloss: 0.00033278
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[160]	valid_0's binary_logloss: 0.000331608
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[161]	valid_0's binary_logloss: 0.000336223
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[162]	valid_0's binary_logloss: 0.000324819
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[163]	valid_0's binary_logloss: 0.000327694
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[164]	valid_0's binary_logloss: 0.000330305
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[165]	valid_0's binary_logloss: 0.000319654
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[166]	valid_0's binary_logloss: 0.000323352
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[167]	valid_0's binary_logloss: 0.000326683
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[168]	valid_0's binary_logloss: 0.000329112
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[169]	valid_0's binary_logloss: 0.000332475
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[170]	valid_0's binary_logloss: 0.000335575

Trening klas:  84%|████████▍ | 421/500 [48:43<08:11,  6.22s/klasa, klasa=class_421, F1_klasy=1.0000, F1_macro=0.6391, drzewa=150]




Trening klas:  84%|████████▍ | 422/500 [48:43<07:43,  5.94s/klasa, klasa=class_421, F1_klasy=1.0000, F1_macro=0.6391, drzewa=150]

[179]	valid_0's binary_logloss: 0.000336632
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[180]	valid_0's binary_logloss: 0.000335494
[1]	valid_0's binary_logloss: 0.230307
[2]	valid_0's binary_logloss: 0.181814
[3]	valid_0's binary_logloss: 0.167768
[4]	valid_0's binary_logloss: 0.158638
[5]	valid_0's binary_logloss: 0.151882
[6]	valid_0's binary_logloss: 0.143738
[7]	valid_0's binary_logloss: 0.137438
[8]	valid_0's binary_logloss: 0.132138
[9]	valid_0's binary_logloss: 0.127604
[10]	valid_0's binary_logloss: 0.123744
[11]	valid_0's binary_logloss: 0.120488
[12]	valid_0's binary_logloss: 0.117543
[13]	valid_0's binary_logloss: 0.114755
[14]	valid_0's binary_logloss: 0.112146
[15]	valid_0's binary_logloss: 0.10956
[16]	valid_0's binary_logloss: 0.107225
[17]	valid_0's binary_logloss: 0.105262
[18]	valid_0's binary_logloss: 0.103457
[19]	valid_0's binary_logloss: 0.101271
[20]	valid_0's binary_logloss: 0.0992628
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0974921
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0953477
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.0934122
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0914144
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.0897522
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.0882981
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.0866006
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.0849213
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.0835138
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.0819392
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.0804778
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.0791135
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.0776862
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.0762162
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.0748955
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.0737748
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.0727145
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.0717449
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.0707238
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.0696688
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.0687155
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.0675863
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.0666055
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.065633
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.0645654
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.0637798
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.062806
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.0620418
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.0612167
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.0604336
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.0596529
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.0589297
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.0583456
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.0575577
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.0570077
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.0563956
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.0558047
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.0552615
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.0546638
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.0539747
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.0533992
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.0527209
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.052021
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.0513167
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.0506689
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.0502209
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.04975
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.0492224
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.0486474
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.0481698
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.0476598
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.0470464
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.0465374
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.0460651
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.0456467
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.0451192
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.0446279
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.044181
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.0436956
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.0432634
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.042931
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.0425579
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.0421277
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.0416538
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.0413956
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.0409595
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.0404162
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.0400569
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.0395737
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.0392
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.0388274
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.0384636
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.0380967
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.0378108
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.0375792
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.0373209
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.0369993
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.0366709
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.0363368
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.0360956
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.0358636
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.0356709
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.0353214
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.035122
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.0348386
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.0344897
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.0342769
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.0341445
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.0338919
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.0337008
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.03358
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 0.0334593
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 0.0333864
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 0.0331722
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 0.0331089
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[116]	valid_0's binary_logloss: 0.0328915
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[117]	valid_0's binary_logloss: 0.0327454
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[118]	valid_0's binary_logloss: 0.0325743
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[119]	valid_0's binary_logloss: 0.0323819
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[120]	valid_0's binary_logloss: 0.0322804
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[121]	valid_0's binary_logloss: 0.0321826
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[122]	valid_0's binary_logloss: 0.0321468
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[123]	valid_0's binary_logloss: 0.0320816
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[124]	valid_0's binary_logloss: 0.0319498
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[125]	valid_0's binary_logloss: 0.0318219
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[126]	valid_0's binary_logloss: 0.0316903
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[127]	valid_0's binary_logloss: 0.0316326
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[128]	valid_0's binary_logloss: 0.0315823
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[129]	valid_0's binary_logloss: 0.0314501
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[130]	valid_0's binary_logloss: 0.0314517
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[131]	valid_0's binary_logloss: 0.0313449
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[132]	valid_0's binary_logloss: 0.0312711
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[133]	valid_0's binary_logloss: 0.0311516
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[134]	valid_0's binary_logloss: 0.0310799
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[135]	valid_0's binary_logloss: 0.0309977
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[136]	valid_0's binary_logloss: 0.0308577
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[137]	valid_0's binary_logloss: 0.0307045
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[138]	valid_0's binary_logloss: 0.0305686
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[139]	valid_0's binary_logloss: 0.0305337
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[140]	valid_0's binary_logloss: 0.0304393
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[141]	valid_0's binary_logloss: 0.0302742
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[142]	valid_0's binary_logloss: 0.0301054
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[143]	valid_0's binary_logloss: 0.029951
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[144]	valid_0's binary_logloss: 0.0298037
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[145]	valid_0's binary_logloss: 0.0296588
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[146]	valid_0's binary_logloss: 0.0296468
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[147]	valid_0's binary_logloss: 0.029638
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[148]	valid_0's binary_logloss: 0.0296217
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[149]	valid_0's binary_logloss: 0.0295639
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[150]	valid_0's binary_logloss: 0.0295358
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[151]	valid_0's binary_logloss: 0.0295097
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[152]	valid_0's binary_logloss: 0.0295136
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[153]	valid_0's binary_logloss: 0.0294955
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[154]	valid_0's binary_logloss: 0.0294809
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[155]	valid_0's binary_logloss: 0.0294746
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[156]	valid_0's binary_logloss: 0.0294459
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[157]	valid_0's binary_logloss: 0.0294001
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[158]	valid_0's binary_logloss: 0.0293493
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[159]	valid_0's binary_logloss: 0.0293262
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[160]	valid_0's binary_logloss: 0.029347
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[161]	valid_0's binary_logloss: 0.029245
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[162]	valid_0's binary_logloss: 0.0292051
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[163]	valid_0's binary_logloss: 0.0291725
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[164]	valid_0's binary_logloss: 0.0291514
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[165]	valid_0's binary_logloss: 0.0291078
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[166]	valid_0's binary_logloss: 0.0291588
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[167]	valid_0's binary_logloss: 0.0290867
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[168]	valid_0's binary_logloss: 0.0291133
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[169]	valid_0's binary_logloss: 0.028978
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[170]	valid_0's binary_logloss: 0.0288878
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[171]	valid_0's binary_logloss: 0.0288308
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[172]	valid_0's binary_logloss: 0.0287687
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[173]	valid_0's binary_logloss: 0.0287197
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[174]	valid_0's binary_logloss: 0.0287052
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[175]	valid_0's binary_logloss: 0.0286502
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[176]	valid_0's binary_logloss: 0.0286352
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[177]	valid_0's binary_logloss: 0.0286114
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[178]	valid_0's binary_logloss: 0.0285649
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[179]	valid_0's binary_logloss: 0.0285476
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[180]	valid_0's binary_logloss: 0.0285336
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[181]	valid_0's binary_logloss: 0.0285289
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[182]	valid_0's binary_logloss: 0.0285181
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[183]	valid_0's binary_logloss: 0.0284995

Trening klas:  84%|████████▍ | 422/500 [48:52<07:43,  5.94s/klasa, klasa=class_422, F1_klasy=0.5000, F1_macro=0.6388, drzewa=281]




Trening klas:  85%|████████▍ | 423/500 [48:52<08:44,  6.81s/klasa, klasa=class_422, F1_klasy=0.5000, F1_macro=0.6388, drzewa=281]

[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[292]	valid_0's binary_logloss: 0.0273478
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[293]	valid_0's binary_logloss: 0.0273478
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[294]	valid_0's binary_logloss: 0.0273478
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[295]	valid_0's binary_logloss: 0.0273478
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[296]	valid_0's binary_logloss: 0.0273478
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[297]	valid_0's binary_logloss: 0.0273478
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[298]	valid_0's binary_logloss: 0.0273478
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[299]	valid_0's binary_logloss: 0.0273478
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[300]	valid_0's binary_logloss: 0.0273478
[1]	valid_0's binary_logloss: 0.00613798
[2]	valid_0's binary_logloss: 0.00570237
[3]	valid_0's binary_logloss: 0.00538823
[4]	valid_0's binary_logloss: 0.0051024
[5]	valid_0's binary_logloss: 0.00483841
[6]	valid_0's binary_logloss: 0.00459337
[7]	valid_0's binary_logloss: 0.00435661
[8]	valid_0's binary_logloss: 0.0041434
[9]	valid_0's binary_logloss: 0.0039424
[10]	valid_0's binary_logloss: 0.00374421
[11]	valid_0's binary_logloss: 0.00355844
[12]	valid_0's binary_logloss: 0.00338148
[13]	valid_0's binary_logloss: 0.00321548
[14]	valid_0's binary_logloss: 0.003056
[15]	valid_0's binary_logloss: 0.00290526
[16]	valid_0's binary_logloss: 0.00276247
[17]	valid_0's binary_logloss: 0.00262661
[18]	valid_0's binary_logloss: 0.00249857
[19]	valid_0's binary_logloss: 0.00237712
[20]	valid_0's binary_logloss: 0.0022577
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.00214542
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.00204051
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.00193756
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.00184194
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.00175104
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.0016651
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.00157946
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.00150258
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.00142946
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.00135909
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.00129392
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.0012318
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.00117311
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.00111322
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.00106002
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.00100661
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.000955695
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.000907092
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.000862232
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.000817764
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.000777084
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.000737306
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.000700739
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.000665092
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.000632639
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.00060069
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.00056958
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.000540296
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.000512523
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.000487965
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.000463766
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.000440237
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.000418545
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.000399191
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.000380401
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.000362748
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.000345991
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.000330118
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.000313532
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.000299219
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.000284723
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.000270995
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.000257851
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.000245481
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.000233669
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.000222591
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.000211821
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.000201661
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.000191979
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.000182937
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.000175138
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.000167066
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.000159726
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.000152252
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.000145717
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.000138775
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.000132251
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.000126236
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.000120356
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.000114987
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.000109397
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.000104045
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 9.90004e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 9.42425e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 8.98083e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 8.56466e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 8.20375e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 7.87469e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 7.51399e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 7.21943e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 6.90834e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 6.61577e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 6.31452e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 6.05767e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 5.79269e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 5.54364e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 5.30724e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 5.0892e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 4.8758e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 4.67322e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 4.51772e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 4.32464e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 4.17598e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 4.03347e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 3.91772e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 3.77255e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 3.64623e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 3.52904e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 3.39384e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 3.27951e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 3.1653e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 3.05177e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 2.92081e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 2.83095e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 2.74723e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[116]	valid_0's binary_logloss: 2.67207e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[117]	valid_0's binary_logloss: 2.5807e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[118]	valid_0's binary_logloss: 2.49483e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[119]	valid_0's binary_logloss: 2.432e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[120]	valid_0's binary_logloss: 2.37601e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[121]	valid_0's binary_logloss: 2.28828e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[122]	valid_0's binary_logloss: 2.20049e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[123]	valid_0's binary_logloss: 2.13715e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[124]	valid_0's binary_logloss: 2.10076e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[125]	valid_0's binary_logloss: 2.02415e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[126]	valid_0's binary_logloss: 1.97826e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[127]	valid_0's binary_logloss: 1.9212e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[128]	valid_0's binary_logloss: 1.87925e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[129]	valid_0's binary_logloss: 1.81266e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[130]	valid_0's binary_logloss: 1.75873e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[131]	valid_0's binary_logloss: 1.69552e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[132]	valid_0's binary_logloss: 1.65396e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[133]	valid_0's binary_logloss: 1.61357e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[134]	valid_0's binary_logloss: 1.5523e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[135]	valid_0's binary_logloss: 1.50719e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[136]	valid_0's binary_logloss: 1.48095e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[137]	valid_0's binary_logloss: 1.43392e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[138]	valid_0's binary_logloss: 1.39902e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[139]	valid_0's binary_logloss: 1.36598e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[140]	valid_0's binary_logloss: 1.33083e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[141]	valid_0's binary_logloss: 1.31087e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[142]	valid_0's binary_logloss: 1.28995e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[143]	valid_0's binary_logloss: 1.27837e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[144]	valid_0's binary_logloss: 1.25948e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[145]	valid_0's binary_logloss: 1.23697e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[146]	valid_0's binary_logloss: 1.20224e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[147]	valid_0's binary_logloss: 1.16748e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[148]	valid_0's binary_logloss: 1.13031e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[149]	valid_0's binary_logloss: 1.09608e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[150]	valid_0's binary_logloss: 1.06317e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[151]	valid_0's binary_logloss: 1.0481e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[152]	valid_0's binary_logloss: 1.0317e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[153]	valid_0's binary_logloss: 1.01855e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[154]	valid_0's binary_logloss: 1.0083e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[155]	valid_0's binary_logloss: 9.95799e-06
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[156]	valid_0's binary_logloss: 9.73113e-06
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[157]	valid_0's binary_logloss: 9.51441e-06
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[158]	valid_0's binary_logloss: 9.35245e-06
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[159]	valid_0's binary_logloss: 9.27709e-06
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[160]	valid_0's binary_logloss: 9.13928e-06
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[161]	valid_0's binary_logloss: 9.09527e-06
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[162]	valid_0's binary_logloss: 8.97874e-06
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[163]	valid_0's binary_logloss: 8.82821e-06
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[164]	valid_0's binary_logloss: 8.67278e-06
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[165]	valid_0's binary_logloss: 8.53954e-06
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

Trening klas:  85%|████████▍ | 423/500 [49:00<08:44,  6.81s/klasa, klasa=class_423, F1_klasy=0.0000, F1_macro=0.6373, drzewa=300]




Trening klas:  85%|████████▍ | 424/500 [49:00<09:03,  7.15s/klasa, klasa=class_423, F1_klasy=0.0000, F1_macro=0.6373, drzewa=300]

[293]	valid_0's binary_logloss: 2.2624e-06
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[294]	valid_0's binary_logloss: 2.26049e-06
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[295]	valid_0's binary_logloss: 2.25102e-06
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[296]	valid_0's binary_logloss: 2.22897e-06
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[297]	valid_0's binary_logloss: 2.20449e-06
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[298]	valid_0's binary_logloss: 2.20212e-06
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[299]	valid_0's binary_logloss: 2.20225e-06
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[300]	valid_0's binary_logloss: 2.19053e-06
[1]	valid_0's binary_logloss: 0.21955
[2]	valid_0's binary_logloss: 0.124258
[3]	valid_0's binary_logloss: 0.11706
[4]	valid_0's binary_logloss: 0.11183
[5]	valid_0's binary_logloss: 0.108425
[6]	valid_0's binary_logloss: 0.105277
[7]	valid_0's binary_logloss: 0.10208
[8]	valid_0's binary_logloss: 0.0995095
[9]	valid_0's binary_logloss: 0.097079
[10]	valid_0's binary_logloss: 0.0942456
[11]	valid_0's binary_logloss: 0.0922251
[12]	valid_0's binary_logloss: 0.0902699
[13]	valid_0's binary_logloss: 0.0885003
[14]	valid_0's binary_logloss: 0.0866967
[15]	valid_0's binary_logloss: 0.0851281
[16]	valid_0's binary_logloss: 0.0834215
[17]	valid_0's binary_logloss: 0.0818874
[18]	valid_0's binary_logloss: 0.0803032
[19]	valid_0's binary_logloss: 0.0786379
[20]	valid_0's binary_logloss: 0.0772642
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0757847
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0741671
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.0726594
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0712308
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.0698453
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.0685455
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.0668447
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.0656422
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.0637631
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.0624779
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.0613357
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.0594558
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.0586427
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.0577306
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.0567606
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.0557313
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.0547987
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.0539217
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.0530615
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.0521481
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.0511161
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.0502625
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.0494377
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.0486711
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.0477531
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.0469698
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.0461797
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.0453588
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.0446359
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.0439334
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.0433088
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.0426788
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.0420163
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.0414892
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.0409247
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.0401778
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.0395427
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.0388289
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.0382774
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.0376
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.0370266
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.0364687
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.0358968
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.0352858
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.0347415
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.0341411
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.0335332
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.0330379
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.0324888
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.0319693
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.031486
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.0310268
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.0306111
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.030287
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.0298692
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.029527
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.0292114
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.0288274
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.0284807
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.028198
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.0277642
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.0273561
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.0269371
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.0265165
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.0261292
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.0258731
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.0255925
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.0253146
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.0250496
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.0246876
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.0244054
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.0241255
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.0238071
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.023527
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.0232771
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.0230419
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.0227953
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.0225457
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.02231
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.0221334
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.0220188
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.0217743
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.0215692
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.0214687
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.0213751
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.0211511
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.0209706
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.0207749
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.0206088
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.0204853
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.0203449
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 0.0202234
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 0.0201151
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 0.0200881
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 0.020082
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[116]	valid_0's binary_logloss: 0.0200102
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[117]	valid_0's binary_logloss: 0.0198124
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[118]	valid_0's binary_logloss: 0.0196802
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[119]	valid_0's binary_logloss: 0.0195997
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[120]	valid_0's binary_logloss: 0.0195262
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[121]	valid_0's binary_logloss: 0.0194329
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[122]	valid_0's binary_logloss: 0.0193517
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[123]	valid_0's binary_logloss: 0.0192462
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[124]	valid_0's binary_logloss: 0.019147
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[125]	valid_0's binary_logloss: 0.0190723
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[126]	valid_0's binary_logloss: 0.0189364
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[127]	valid_0's binary_logloss: 0.0188708
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[128]	valid_0's binary_logloss: 0.0187549
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[129]	valid_0's binary_logloss: 0.0186283
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[130]	valid_0's binary_logloss: 0.0185339
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[131]	valid_0's binary_logloss: 0.0184561
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[132]	valid_0's binary_logloss: 0.0184108
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[133]	valid_0's binary_logloss: 0.0183648
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[134]	valid_0's binary_logloss: 0.0183133
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[135]	valid_0's binary_logloss: 0.0182662
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[136]	valid_0's binary_logloss: 0.0182449
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[137]	valid_0's binary_logloss: 0.0182049
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[138]	valid_0's binary_logloss: 0.0181432
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[139]	valid_0's binary_logloss: 0.0180836
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[140]	valid_0's binary_logloss: 0.0180427
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[141]	valid_0's binary_logloss: 0.0179871
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[142]	valid_0's binary_logloss: 0.0179403
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[143]	valid_0's binary_logloss: 0.0178705
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[144]	valid_0's binary_logloss: 0.0178243
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[145]	valid_0's binary_logloss: 0.0177702
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[146]	valid_0's binary_logloss: 0.0177326
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[147]	valid_0's binary_logloss: 0.0177089
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[148]	valid_0's binary_logloss: 0.0176795
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[149]	valid_0's binary_logloss: 0.0176505
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[150]	valid_0's binary_logloss: 0.0176126
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[151]	valid_0's binary_logloss: 0.0175589
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[152]	valid_0's binary_logloss: 0.0175026
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[153]	valid_0's binary_logloss: 0.0174916
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[154]	valid_0's binary_logloss: 0.0174845
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[155]	valid_0's binary_logloss: 0.0174602
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[156]	valid_0's binary_logloss: 0.0174825
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[157]	valid_0's binary_logloss: 0.0174461
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[158]	valid_0's binary_logloss: 0.0175051
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[159]	valid_0's binary_logloss: 0.0174964
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[160]	valid_0's binary_logloss: 0.0175044
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[161]	valid_0's binary_logloss: 0.0174692
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[162]	valid_0's binary_logloss: 0.0174286
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[163]	valid_0's binary_logloss: 0.0173984
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[164]	valid_0's binary_logloss: 0.0173812
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[165]	valid_0's binary_logloss: 0.0173353
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[166]	valid_0's binary_logloss: 0.0173138
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[167]	valid_0's binary_logloss: 0.0173384
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[168]	valid_0's binary_logloss: 0.0173531
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[169]	valid_0's binary_logloss: 0.0173842
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[170]	valid_0's binary_logloss: 0.0173848
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[171]	valid_0's binary_logloss: 0.0173913
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[172]	valid_0's binary_logloss: 0.0173385
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[173]	valid_0's binary_logloss: 0.0173017
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[174]	valid_0's binary_logloss: 0.0172753
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[175]	valid_0's binary_logloss: 0.017281
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[176]	valid_0's binary_logloss: 0.0172768
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[177]	valid_0's binary_logloss: 0.017282

Trening klas:  85%|████████▍ | 424/500 [49:10<09:03,  7.15s/klasa, klasa=class_424, F1_klasy=0.5172, F1_macro=0.6370, drzewa=300]




Trening klas:  85%|████████▌ | 425/500 [49:10<09:58,  7.98s/klasa, klasa=class_424, F1_klasy=0.5172, F1_macro=0.6370, drzewa=300]

[1]	valid_0's binary_logloss: 0.0550171
[2]	valid_0's binary_logloss: 0.0263057
[3]	valid_0's binary_logloss: 0.0242765
[4]	valid_0's binary_logloss: 0.0230144
[5]	valid_0's binary_logloss: 0.0215746
[6]	valid_0's binary_logloss: 0.0693254
[7]	valid_0's binary_logloss: 0.0527616
[8]	valid_0's binary_logloss: 0.0489683
[9]	valid_0's binary_logloss: 0.0457269
[10]	valid_0's binary_logloss: 0.0416536
[11]	valid_0's binary_logloss: 0.0383451
[12]	valid_0's binary_logloss: 0.0355861
[13]	valid_0's binary_logloss: 0.0335528
[14]	valid_0's binary_logloss: 0.0316415
[15]	valid_0's binary_logloss: 0.0302233
[16]	valid_0's binary_logloss: 0.0289385
[17]	valid_0's binary_logloss: 0.0278284
[18]	valid_0's binary_logloss: 0.0265312
[19]	valid_0's binary_logloss: 0.0253281
[20]	valid_0's binary_logloss: 0.024211
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0233863
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.022407
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.0216779
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0208172
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.0200328
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.0193941
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.018714
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.0180433
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.0174972
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.0168996
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.0163319
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.0158028
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.0152214
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.0147326
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.0143211
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.0138878
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.0134979
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.0131231
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.0127605
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.0124179
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.0120425
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.0117384
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.0113876
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.0110566
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.0107729
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.0104754
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.010216
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.00995984
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.00972163
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.00949491
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.00926147
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.00902941
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.00880483
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.00860736
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.00842331
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.00822844
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.00803684
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.00784264
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.00765532
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.00750727
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.00735286
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.00718678
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.00703556
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.0068771
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.00674406
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.00659542
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.00645429
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.00633385
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.00621842
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.0060945
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.00598799
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.00586463
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.00575824
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.00563938
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.00553762
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.0054647
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.00536956
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.0052723
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.0051683
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.00506043
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.00498833
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.00492928
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.00485716
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.0047956
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.00472601
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.00467476
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.00463009
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.00458062
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.00453359
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.00448905
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.00444367
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.00438801
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.00436927
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.00433893
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.00428924
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.00426584
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.00422823
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.0041903
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.00416195
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.00412696
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.00409123
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.00407214
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.00406777
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.00405717
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.0040552
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.00403941
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.00403158
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.00402123
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.00400199
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.0039851
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.00397762
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 0.00397332
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 0.00396363
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 0.00394858
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 0.00394423
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[116]	valid_0's binary_logloss: 0.00392322
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[117]	valid_0's binary_logloss: 0.00390048
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[118]	valid_0's binary_logloss: 0.00389001
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[119]	valid_0's binary_logloss: 0.00386459
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[120]	valid_0's binary_logloss: 0.00385505
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[121]	valid_0's binary_logloss: 0.00382536
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[122]	valid_0's binary_logloss: 0.00379835
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[123]	valid_0's binary_logloss: 0.00377588
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[124]	valid_0's binary_logloss: 0.00377274
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[125]	valid_0's binary_logloss: 0.00376786
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[126]	valid_0's binary_logloss: 0.00373723
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[127]	valid_0's binary_logloss: 0.00370406
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[128]	valid_0's binary_logloss: 0.0036753
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[129]	valid_0's binary_logloss: 0.00367168
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[130]	valid_0's binary_logloss: 0.00367903
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[131]	valid_0's binary_logloss: 0.00365177
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[132]	valid_0's binary_logloss: 0.00363235
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[133]	valid_0's binary_logloss: 0.00360552
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[134]	valid_0's binary_logloss: 0.00358831
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[135]	valid_0's binary_logloss: 0.00357205
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[136]	valid_0's binary_logloss: 0.00356583
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[137]	valid_0's binary_logloss: 0.00355741
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[138]	valid_0's binary_logloss: 0.00355131
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[139]	valid_0's binary_logloss: 0.00355152
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[140]	valid_0's binary_logloss: 0.00352625
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[141]	valid_0's binary_logloss: 0.00352318
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[142]	valid_0's binary_logloss: 0.00351569
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[143]	valid_0's binary_logloss: 0.00350775
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[144]	valid_0's binary_logloss: 0.00350093
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[145]	valid_0's binary_logloss: 0.00348907
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[146]	valid_0's binary_logloss: 0.00347596
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[147]	valid_0's binary_logloss: 0.00347125
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[148]	valid_0's binary_logloss: 0.00344727
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[149]	valid_0's binary_logloss: 0.00343758
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[150]	valid_0's binary_logloss: 0.00342317
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[151]	valid_0's binary_logloss: 0.00343185
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[152]	valid_0's binary_logloss: 0.00343626
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[153]	valid_0's binary_logloss: 0.00342781
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[154]	valid_0's binary_logloss: 0.0034316
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[155]	valid_0's binary_logloss: 0.00342504
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[156]	valid_0's binary_logloss: 0.00342681
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[157]	valid_0's binary_logloss: 0.00343029
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[158]	valid_0's binary_logloss: 0.00343669
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[159]	valid_0's binary_logloss: 0.00342551
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[160]	valid_0's binary_logloss: 0.00341514
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[161]	valid_0's binary_logloss: 0.00342539
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[162]	valid_0's binary_logloss: 0.00342958
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[163]	valid_0's binary_logloss: 0.00341487
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[164]	valid_0's binary_logloss: 0.00341092
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[165]	valid_0's binary_logloss: 0.00339722
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[166]	valid_0's binary_logloss: 0.00339813
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[167]	valid_0's binary_logloss: 0.00338858
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[168]	valid_0's binary_logloss: 0.00338964
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[169]	valid_0's binary_logloss: 0.00337904
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[170]	valid_0's binary_logloss: 0.00337795
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[171]	valid_0's binary_logloss: 0.00338432
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[172]	valid_0's binary_logloss: 0.00339209
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[173]	valid_0's binary_logloss: 0.00339615
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[174]	valid_0's binary_logloss: 0.00340343
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[175]	valid_0's binary_logloss: 0.00340933
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[176]	valid_0's binary_logloss: 0.00340811
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[177]	valid_0's binary_logloss: 0.00339805
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[178]	valid_0's binary_logloss: 0.00339633
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[179]	valid_0's binary_logloss: 0.00340016
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[180]	valid_0's binary_logloss: 0.00339571
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[181]	valid_0's binary_logloss: 0.0033957
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[182]	valid_0's binary_logloss: 0.00339808
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[183]	valid_0's binary_logloss: 0.00339511
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

Trening klas:  85%|████████▌ | 425/500 [49:15<09:58,  7.98s/klasa, klasa=class_425, F1_klasy=0.9333, F1_macro=0.6377, drzewa=205]




Trening klas:  85%|████████▌ | 426/500 [49:15<08:53,  7.21s/klasa, klasa=class_425, F1_klasy=0.9333, F1_macro=0.6377, drzewa=205]

[230]	valid_0's binary_logloss: 0.00325064
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[231]	valid_0's binary_logloss: 0.00324749
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[232]	valid_0's binary_logloss: 0.00324407
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[233]	valid_0's binary_logloss: 0.00324324
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[234]	valid_0's binary_logloss: 0.00324645
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[235]	valid_0's binary_logloss: 0.00324646
[1]	valid_0's binary_logloss: 0.337298
[2]	valid_0's binary_logloss: 0.258066
[3]	valid_0's binary_logloss: 0.488396
[4]	valid_0's binary_logloss: 0.488235
[5]	valid_0's binary_logloss: 0.495271
[6]	valid_0's binary_logloss: 0.503623
[7]	valid_0's binary_logloss: 0.50935
[8]	valid_0's binary_logloss: 0.508561
[9]	valid_0's binary_logloss: 0.507353
[10]	valid_0's binary_logloss: 0.514696
[11]	valid_0's binary_logloss: 0.577862
[12]	valid_0's binary_logloss: 0.578832
[13]	valid_0's binary_logloss: 0.578101
[14]	valid_0's binary_logloss: 0.580586
[15]	valid_0's binary_logloss: 0.580927
[16]	valid_0's binary_logloss: 0.653257
[17]	valid_0's binary_logloss: 0.665658
[18]	valid_0's binary_logloss: 0.670628
[19]	valid_0's binary_logloss: 0.67492
[20]	valid_0's binary_logloss: 0.676657
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.677488
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.678354
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.679855
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.680119
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.6797
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.849851
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.851188
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.854052
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.856025
[30]	valid_0's binary_logloss: 0.857073
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.858516
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.858663

Trening klas:  85%|████████▌ | 426/500 [49:19<08:53,  7.21s/klasa, klasa=class_426, F1_klasy=0.3704, F1_macro=0.6371, drzewa=2]




Trening klas:  85%|████████▌ | 427/500 [49:19<07:21,  6.05s/klasa, klasa=class_426, F1_klasy=0.3704, F1_macro=0.6371, drzewa=2]

[1]	valid_0's binary_logloss: 0.101204
[2]	valid_0's binary_logloss: 0.0825034
[3]	valid_0's binary_logloss: 0.0714843
[4]	valid_0's binary_logloss: 0.0664633
[5]	valid_0's binary_logloss: 0.0634793
[6]	valid_0's binary_logloss: 0.0601869
[7]	valid_0's binary_logloss: 0.0582721
[8]	valid_0's binary_logloss: 0.0570021
[9]	valid_0's binary_logloss: 0.0556276
[10]	valid_0's binary_logloss: 0.0542178
[11]	valid_0's binary_logloss: 0.053416
[12]	valid_0's binary_logloss: 0.0520674
[13]	valid_0's binary_logloss: 0.0513621
[14]	valid_0's binary_logloss: 0.0507053
[15]	valid_0's binary_logloss: 0.0500233
[16]	valid_0's binary_logloss: 0.0494827
[17]	valid_0's binary_logloss: 0.0488807
[18]	valid_0's binary_logloss: 0.0480299
[19]	valid_0's binary_logloss: 0.0473092
[20]	valid_0's binary_logloss: 0.0466659
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0462058
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.045702
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.0453607
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0449869
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.0444493
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.0440564
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.043599
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.0432156
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.0427793
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.0424138
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.042025
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.0416417
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.0412907
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.041009
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.0406718
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.0403207
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.0398964
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.0396244
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.0393514
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.0390928
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.0387873
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.0385231
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.0382028
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.0378869
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.0375767
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.0372862
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.0370264
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.0367488
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.0365113
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.0362292
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.0359839
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.0358254
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.0356796
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.0354785
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.0353409
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.0351462
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.0349601
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.0347131
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.0345369
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.034388
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.0341354
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.0338567
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.0336443
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.0334414
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.0332078
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.0330366
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.0328735
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.0327011
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.0325568
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.0322757
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.0319737
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.031794
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.0314505
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.0311941
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.0309198
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.0307748
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.0306336
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.0304739
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.0302635
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.0301164
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.0299532
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.0297518
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.0295595
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.0293079
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.0291021
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.0289666
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.028806
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.0286537
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.0285307
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.0284095
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.028182
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.027991
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.0277891
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.0276049
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.0273955
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.0272444
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.0270632
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.0269104
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.0268174
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.026657
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.0265369
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.0263917
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.0263464
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.0262216
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.0261551
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.0260801
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.0259493
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.0258492
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.0257827
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.0256941
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.0255758
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 0.0254339
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 0.0253273
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 0.0252215
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 0.0251256
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[116]	valid_0's binary_logloss: 0.0250596
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[117]	valid_0's binary_logloss: 0.0249975
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[118]	valid_0's binary_logloss: 0.0249427
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[119]	valid_0's binary_logloss: 0.0248633
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[120]	valid_0's binary_logloss: 0.0247839
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[121]	valid_0's binary_logloss: 0.0248285
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[122]	valid_0's binary_logloss: 0.0247824
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[123]	valid_0's binary_logloss: 0.0247239
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[124]	valid_0's binary_logloss: 0.024692
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[125]	valid_0's binary_logloss: 0.0246898
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[126]	valid_0's binary_logloss: 0.0245957
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[127]	valid_0's binary_logloss: 0.0245064
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[128]	valid_0's binary_logloss: 0.0244097
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[129]	valid_0's binary_logloss: 0.0243153
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[130]	valid_0's binary_logloss: 0.0242317
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[131]	valid_0's binary_logloss: 0.0241401
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[132]	valid_0's binary_logloss: 0.024057
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[133]	valid_0's binary_logloss: 0.0239758
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[134]	valid_0's binary_logloss: 0.0238782
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[135]	valid_0's binary_logloss: 0.0238032
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[136]	valid_0's binary_logloss: 0.023663
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[137]	valid_0's binary_logloss: 0.0235192
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[138]	valid_0's binary_logloss: 0.0234047
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[139]	valid_0's binary_logloss: 0.0232793
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[140]	valid_0's binary_logloss: 0.023171
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[141]	valid_0's binary_logloss: 0.0231152
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[142]	valid_0's binary_logloss: 0.0230644
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[143]	valid_0's binary_logloss: 0.023033
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[144]	valid_0's binary_logloss: 0.0230611
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[145]	valid_0's binary_logloss: 0.0230704
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[146]	valid_0's binary_logloss: 0.0230203
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[147]	valid_0's binary_logloss: 0.0229604
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[148]	valid_0's binary_logloss: 0.0229332
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[149]	valid_0's binary_logloss: 0.022879
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[150]	valid_0's binary_logloss: 0.0228308
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[151]	valid_0's binary_logloss: 0.022801
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[152]	valid_0's binary_logloss: 0.0227888
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[153]	valid_0's binary_logloss: 0.0227279
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[154]	valid_0's binary_logloss: 0.0226883
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[155]	valid_0's binary_logloss: 0.0226267
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[156]	valid_0's binary_logloss: 0.0225778
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[157]	valid_0's binary_logloss: 0.0225226
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[158]	valid_0's binary_logloss: 0.0224806
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[159]	valid_0's binary_logloss: 0.0224357
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[160]	valid_0's binary_logloss: 0.0223881
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[161]	valid_0's binary_logloss: 0.0223272
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[162]	valid_0's binary_logloss: 0.0222515
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[163]	valid_0's binary_logloss: 0.022198
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[164]	valid_0's binary_logloss: 0.0221643
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[165]	valid_0's binary_logloss: 0.02211
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[166]	valid_0's binary_logloss: 0.0220727
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[167]	valid_0's binary_logloss: 0.0220288
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[168]	valid_0's binary_logloss: 0.0219872
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[169]	valid_0's binary_logloss: 0.0219797
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[170]	valid_0's binary_logloss: 0.0219407
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[171]	valid_0's binary_logloss: 0.0219095
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[172]	valid_0's binary_logloss: 0.0219135
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[173]	valid_0's binary_logloss: 0.0219332
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[174]	valid_0's binary_logloss: 0.0218967
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[175]	valid_0's binary_logloss: 0.0218657
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[176]	valid_0's binary_logloss: 0.0218738
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[177]	valid_0's binary_logloss: 0.021812
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[178]	valid_0's binary_logloss: 0.0217455
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[179]	valid_0's binary_logloss: 0.0217544
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[180]	valid_0's binary_logloss: 0.02169
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[181]	valid_0's binary_logloss: 0.0216815
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[182]	valid_0's binary_logloss: 0.0216961
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[183]	valid_0's binary_logloss: 0.0217069
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[184]	valid_0's binary_logloss: 0.0216863
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

Trening klas:  85%|████████▌ | 427/500 [49:26<07:21,  6.05s/klasa, klasa=class_427, F1_klasy=0.7255, F1_macro=0.6373, drzewa=295]




Trening klas:  86%|████████▌ | 428/500 [49:26<07:37,  6.36s/klasa, klasa=class_427, F1_klasy=0.7255, F1_macro=0.6373, drzewa=295]

[300]	valid_0's binary_logloss: 0.0208853
[1]	valid_0's binary_logloss: 0.0448299
[2]	valid_0's binary_logloss: 0.0411436
[3]	valid_0's binary_logloss: 0.039003
[4]	valid_0's binary_logloss: 0.0361479
[5]	valid_0's binary_logloss: 0.0351047
[6]	valid_0's binary_logloss: 0.0337706
[7]	valid_0's binary_logloss: 0.032788
[8]	valid_0's binary_logloss: 0.0320246
[9]	valid_0's binary_logloss: 0.0314516
[10]	valid_0's binary_logloss: 0.0307555
[11]	valid_0's binary_logloss: 0.03049
[12]	valid_0's binary_logloss: 0.0301885
[13]	valid_0's binary_logloss: 0.0298171
[14]	valid_0's binary_logloss: 0.029639
[15]	valid_0's binary_logloss: 0.0292739
[16]	valid_0's binary_logloss: 0.029124
[17]	valid_0's binary_logloss: 0.0289504
[18]	valid_0's binary_logloss: 0.0288462
[19]	valid_0's binary_logloss: 0.0287021
[20]	valid_0's binary_logloss: 0.0285679
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0283423
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0281326
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.0280304
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0278541
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.0277233
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.0272951
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.0271613
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.0270658
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.0266199
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.0265351
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.0262652
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.0259528
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.0258528
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.0256438
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.0254574
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.0254556
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.0254144
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.0252862
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.0251757
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.0251246
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.0251407
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.0251537
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.0251435
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.025147
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.025196
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.0251373
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.0249116
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.0247799
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.0246401
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.024479
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.0245265
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.0245812
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.0245979
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.0245122
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.0244863
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.0244551
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.0244891
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.0244786
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.0244347
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.0244136
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.0244749
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.024544
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.0246132
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.0246612
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.0247348
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.0247533
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.0248112
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.0248438
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.0248518
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.0248941
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.0248069
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.0246073
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.0245076
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.0244516
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.0243118
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.0243527
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.0244345
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.0242815
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.0243671
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.0244344
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.0245063
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.0246331
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.0247241
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.0248389
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.0249493
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.0249822
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.0249603
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.0249769
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.02494
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.0249094
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.024916
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.0249141
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.024973
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.0249776
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.0250376
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.025078
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.0251218
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.0251149
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.0251079
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.0250759
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.0250362
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.0249413
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.0248755
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.024789
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

Trening klas:  86%|████████▌ | 428/500 [49:31<07:37,  6.36s/klasa, klasa=class_428, F1_klasy=0.7414, F1_macro=0.6375, drzewa=78]




Trening klas:  86%|████████▌ | 429/500 [49:31<07:05,  6.00s/klasa, klasa=class_428, F1_klasy=0.7414, F1_macro=0.6375, drzewa=78]

[105]	valid_0's binary_logloss: 0.0247465
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.0248592
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.0249381
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.0250512
[1]	valid_0's binary_logloss: 0.309474
[2]	valid_0's binary_logloss: 0.159267
[3]	valid_0's binary_logloss: 0.151514
[4]	valid_0's binary_logloss: 0.147379
[5]	valid_0's binary_logloss: 0.140315
[6]	valid_0's binary_logloss: 0.137245
[7]	valid_0's binary_logloss: 0.13575
[8]	valid_0's binary_logloss: 0.133913
[9]	valid_0's binary_logloss: 0.131954
[10]	valid_0's binary_logloss: 0.129807
[11]	valid_0's binary_logloss: 0.128502
[12]	valid_0's binary_logloss: 0.127314
[13]	valid_0's binary_logloss: 0.125976
[14]	valid_0's binary_logloss: 0.124573
[15]	valid_0's binary_logloss: 0.123
[16]	valid_0's binary_logloss: 0.121597
[17]	valid_0's binary_logloss: 0.120865
[18]	valid_0's binary_logloss: 0.119709
[19]	valid_0's binary_logloss: 0.118694
[20]	valid_0's binary_logloss: 0.117529
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.116421
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.115398
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.114435
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.113614
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.112762
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.111852
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.111036
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.110066
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.109075
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.108176
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.107362
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.106437
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.105721
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.104806
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.104113
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.103352
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.102594
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.101873
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.101122
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.100677
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.100141
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.0995144
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.0989416
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.098429
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.097725
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.0970407
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.0963455
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.0956601
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.0950746
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.0944977
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.0938566
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.0931782
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.0925821
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.0919965
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.0913466
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.0907348
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.0902172
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.0896176
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.0890958
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.0884919
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.0878817
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.0873049
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.086843
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.0862965
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.0858087
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.0853052
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.0848295
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.0842748
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.0838455
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.0833404
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.0828958
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.082535
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.0820899
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.0816916
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.0813754
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.0809181
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.0805177
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.0801033
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.079684
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.0791976
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.0788793
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.0785366
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.0781908
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.0778251
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.0774501
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.0770096
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.076643
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.0762184
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.0757918
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.0753871
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.0750785
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.0747899
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.0744929
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.0741678
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.0738738
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.0734956
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.0731676
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.0728543
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.0726948
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.0722811
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.071844
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.0716598
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.0712696
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.0709084
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.0705675
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.070226
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.0699435
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.0696627
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.0693696
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.0690753
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.0689509
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 0.0686772
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 0.0685201
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 0.0683752
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 0.0682889
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[116]	valid_0's binary_logloss: 0.068097
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[117]	valid_0's binary_logloss: 0.0678395
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[118]	valid_0's binary_logloss: 0.0676059
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[119]	valid_0's binary_logloss: 0.0674232
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[120]	valid_0's binary_logloss: 0.0672555
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[121]	valid_0's binary_logloss: 0.0672391
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[122]	valid_0's binary_logloss: 0.0670849
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[123]	valid_0's binary_logloss: 0.066896
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[124]	valid_0's binary_logloss: 0.0667294
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[125]	valid_0's binary_logloss: 0.0665865
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[126]	valid_0's binary_logloss: 0.0663001
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[127]	valid_0's binary_logloss: 0.0660961
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[128]	valid_0's binary_logloss: 0.0657999
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[129]	valid_0's binary_logloss: 0.0656231
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[130]	valid_0's binary_logloss: 0.0654297
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[131]	valid_0's binary_logloss: 0.0653536
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[132]	valid_0's binary_logloss: 0.0652997
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[133]	valid_0's binary_logloss: 0.0651829
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[134]	valid_0's binary_logloss: 0.0651004
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[135]	valid_0's binary_logloss: 0.0649951
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[136]	valid_0's binary_logloss: 0.0647391
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[137]	valid_0's binary_logloss: 0.0644807
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[138]	valid_0's binary_logloss: 0.0642567
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[139]	valid_0's binary_logloss: 0.0640261
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[140]	valid_0's binary_logloss: 0.0638197
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[141]	valid_0's binary_logloss: 0.0637523
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[142]	valid_0's binary_logloss: 0.0636967
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[143]	valid_0's binary_logloss: 0.0635243
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[144]	valid_0's binary_logloss: 0.0633487
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[145]	valid_0's binary_logloss: 0.0632591
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[146]	valid_0's binary_logloss: 0.0632118
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[147]	valid_0's binary_logloss: 0.0631027
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[148]	valid_0's binary_logloss: 0.0629835
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[149]	valid_0's binary_logloss: 0.0628871
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[150]	valid_0's binary_logloss: 0.0628277
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[151]	valid_0's binary_logloss: 0.0627611
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[152]	valid_0's binary_logloss: 0.0626904
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[153]	valid_0's binary_logloss: 0.0625987
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[154]	valid_0's binary_logloss: 0.0625497
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[155]	valid_0's binary_logloss: 0.0625124
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[156]	valid_0's binary_logloss: 0.0625131
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[157]	valid_0's binary_logloss: 0.0625419
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[158]	valid_0's binary_logloss: 0.0625242
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[159]	valid_0's binary_logloss: 0.0624872
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[160]	valid_0's binary_logloss: 0.0624367
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[161]	valid_0's binary_logloss: 0.06237
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[162]	valid_0's binary_logloss: 0.0622457
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[163]	valid_0's binary_logloss: 0.0621283
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[164]	valid_0's binary_logloss: 0.0620566
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[165]	valid_0's binary_logloss: 0.0619812
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[166]	valid_0's binary_logloss: 0.0618316
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[167]	valid_0's binary_logloss: 0.0617441
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[168]	valid_0's binary_logloss: 0.0617536
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[169]	valid_0's binary_logloss: 0.0616355
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[170]	valid_0's binary_logloss: 0.0615243
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[171]	valid_0's binary_logloss: 0.0614474
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[172]	valid_0's binary_logloss: 0.0614236
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[173]	valid_0's binary_logloss: 0.0614103
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[174]	valid_0's binary_logloss: 0.0613936
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[175]	valid_0's binary_logloss: 0.0613232
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[176]	valid_0's binary_logloss: 0.061316
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[177]	valid_0's binary_logloss: 0.0613734
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[178]	valid_0's binary_logloss: 0.0613896
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[179]	valid_0's binary_logloss: 0.0614164
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[180]	valid_0's binary_logloss: 0.0614311
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[181]	valid_0's binary_logloss: 0.0612903
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

Trening klas:  86%|████████▌ | 429/500 [49:42<07:05,  6.00s/klasa, klasa=class_429, F1_klasy=0.4286, F1_macro=0.6371, drzewa=297]




Trening klas:  86%|████████▌ | 430/500 [49:42<08:43,  7.48s/klasa, klasa=class_429, F1_klasy=0.4286, F1_macro=0.6371, drzewa=297]

[300]	valid_0's binary_logloss: 0.0578646
[1]	valid_0's binary_logloss: 0.185142
[2]	valid_0's binary_logloss: 0.0698104
[3]	valid_0's binary_logloss: 0.0634984
[4]	valid_0's binary_logloss: 0.0604041
[5]	valid_0's binary_logloss: 0.0573135
[6]	valid_0's binary_logloss: 0.0536972
[7]	valid_0's binary_logloss: 0.0517458
[8]	valid_0's binary_logloss: 0.0497944
[9]	valid_0's binary_logloss: 0.0481761
[10]	valid_0's binary_logloss: 0.0466212
[11]	valid_0's binary_logloss: 0.0455209
[12]	valid_0's binary_logloss: 0.0445198
[13]	valid_0's binary_logloss: 0.0434509
[14]	valid_0's binary_logloss: 0.0424956
[15]	valid_0's binary_logloss: 0.0418423
[16]	valid_0's binary_logloss: 0.0412282
[17]	valid_0's binary_logloss: 0.0406926
[18]	valid_0's binary_logloss: 0.0401662
[19]	valid_0's binary_logloss: 0.0395881
[20]	valid_0's binary_logloss: 0.0391486
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0385761
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0379566
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.0374796
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0370354
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.0365002
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.0360574
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.0356326
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.0352086
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.0348598
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.034465
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.0340643
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.0336147
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.0331744
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.0327103
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.0323812
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.0318663
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.0314703
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.0310356
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.030673
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.0303077
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.0299778
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.0296746
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.0294104
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.0291496
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.0288177
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.0284884
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.0282517
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.0278702
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.0275964
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.0273343
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.0270349
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.0267684
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.0265
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.0262737
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.0260445
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.0258826
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.025645
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.0255183
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.0253499
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.0251894
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.0250438
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.0248729
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.0246856
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.0244678
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.0242537
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.024054
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.0238986
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.0238086
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.0236549
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.0234473
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.0233103
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.023187
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.0230748
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.0229897
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.0228111
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.0226343
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.0224671
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.0223864
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.0222696
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.0221655
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.0220197
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.0219271
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.0218069
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.0216947
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.0216447
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.0215837
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.0215307
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.0214936
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.0214196
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.0212655
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.0211871
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.0211029
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.0210217
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.0209532
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.0209249
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.0209347
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.0209131
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.0208685
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.0208108
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.0207487
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.020662
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.0205924
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.0205605
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.0205238
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.0204762
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.0203912
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.0203297
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.0202793
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.0201804
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.0201588
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.0201495
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 0.0200968
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 0.0200441
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 0.0199985
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 0.019974
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[116]	valid_0's binary_logloss: 0.0198841
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[117]	valid_0's binary_logloss: 0.0198574
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[118]	valid_0's binary_logloss: 0.0198652
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[119]	valid_0's binary_logloss: 0.0198686
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[120]	valid_0's binary_logloss: 0.0198788
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[121]	valid_0's binary_logloss: 0.0198623
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[122]	valid_0's binary_logloss: 0.0198061
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[123]	valid_0's binary_logloss: 0.0197955
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[124]	valid_0's binary_logloss: 0.0197478
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[125]	valid_0's binary_logloss: 0.0197474
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[126]	valid_0's binary_logloss: 0.0197202
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[127]	valid_0's binary_logloss: 0.0196957
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[128]	valid_0's binary_logloss: 0.0197045
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[129]	valid_0's binary_logloss: 0.0197228
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[130]	valid_0's binary_logloss: 0.0197445
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[131]	valid_0's binary_logloss: 0.0197323
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[132]	valid_0's binary_logloss: 0.019719
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[133]	valid_0's binary_logloss: 0.019709
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[134]	valid_0's binary_logloss: 0.0196875
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[135]	valid_0's binary_logloss: 0.0196991
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[136]	valid_0's binary_logloss: 0.0197047
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[137]	valid_0's binary_logloss: 0.019708
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[138]	valid_0's binary_logloss: 0.0196892
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[139]	valid_0's binary_logloss: 0.0196758
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[140]	valid_0's binary_logloss: 0.0196703
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[141]	valid_0's binary_logloss: 0.0196963
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[142]	valid_0's binary_logloss: 0.0197074
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[143]	valid_0's binary_logloss: 0.0197505
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[144]	valid_0's binary_logloss: 0.0197796
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[145]	valid_0's binary_logloss: 0.0197566
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[146]	valid_0's binary_logloss: 0.019751
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[147]	valid_0's binary_logloss: 0.0197353
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[148]	valid_0's binary_logloss: 0.0197404
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[149]	valid_0's binary_logloss: 0.0197321
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[150]	valid_0's binary_logloss: 0.0196811
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[151]	valid_0's binary_logloss: 0.019686
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[152]	valid_0's binary_logloss: 0.0196264
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[153]	valid_0's binary_logloss: 0.0195943
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[154]	valid_0's binary_logloss: 0.0196114
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[155]	valid_0's binary_logloss: 0.0196156
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[156]	valid_0's binary_logloss: 0.0195701
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[157]	valid_0's binary_logloss: 0.0195843
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[158]	valid_0's binary_logloss: 0.0195572
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[159]	valid_0's binary_logloss: 0.019554
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[160]	valid_0's binary_logloss: 0.0195614
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[161]	valid_0's binary_logloss: 0.0195538
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[162]	valid_0's binary_logloss: 0.0195394
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[163]	valid_0's binary_logloss: 0.01952
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[164]	valid_0's binary_logloss: 0.0195045
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[165]	valid_0's binary_logloss: 0.0195001
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[166]	valid_0's binary_logloss: 0.0195162
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[167]	valid_0's binary_logloss: 0.0195447
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[168]	valid_0's binary_logloss: 0.0195154
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[169]	valid_0's binary_logloss: 0.0195079
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[170]	valid_0's binary_logloss: 0.0195119
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[171]	valid_0's binary_logloss: 0.0195452
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[172]	valid_0's binary_logloss: 0.019585
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[173]	valid_0's binary_logloss: 0.0196002
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[174]	valid_0's binary_logloss: 0.01962
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[175]	valid_0's binary_logloss: 0.0196037
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[176]	valid_0's binary_logloss: 0.0196004
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[177]	valid_0's binary_logloss: 0.0195946
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[178]	valid_0's binary_logloss: 0.0195712
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[179]	valid_0's binary_logloss: 0.019556
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[180]	valid_0's binary_logloss: 0.019548
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[181]	valid_0's binary_logloss: 0.0195106
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[182]	valid_0's binary_logloss: 0.0195244
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[183]	valid_0's binary_logloss: 0.0195194
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[184]	valid_0's binary_logloss: 0.0195229

Trening klas:  86%|████████▌ | 430/500 [49:49<08:43,  7.48s/klasa, klasa=class_430, F1_klasy=0.4746, F1_macro=0.6367, drzewa=189]




Trening klas:  86%|████████▌ | 431/500 [49:49<08:31,  7.41s/klasa, klasa=class_430, F1_klasy=0.4746, F1_macro=0.6367, drzewa=189]

[216]	valid_0's binary_logloss: 0.0196949
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[217]	valid_0's binary_logloss: 0.0197228
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[218]	valid_0's binary_logloss: 0.019724
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[219]	valid_0's binary_logloss: 0.0197247
[1]	valid_0's binary_logloss: 0.0113736
[2]	valid_0's binary_logloss: 0.00750979
[3]	valid_0's binary_logloss: 0.00697663
[4]	valid_0's binary_logloss: 0.00656327
[5]	valid_0's binary_logloss: 0.00616972
[6]	valid_0's binary_logloss: 0.00601674
[7]	valid_0's binary_logloss: 0.00606371
[8]	valid_0's binary_logloss: 0.0060619
[9]	valid_0's binary_logloss: 0.00576684
[10]	valid_0's binary_logloss: 0.00574081
[11]	valid_0's binary_logloss: 0.00548986
[12]	valid_0's binary_logloss: 0.00525203
[13]	valid_0's binary_logloss: 0.00502552
[14]	valid_0's binary_logloss: 0.00481252
[15]	valid_0's binary_logloss: 0.00460439
[16]	valid_0's binary_logloss: 0.00442074
[17]	valid_0's binary_logloss: 0.00422706
[18]	valid_0's binary_logloss: 0.00406471
[19]	valid_0's binary_logloss: 0.00389129
[20]	valid_0's binary_logloss: 0.00369141
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.00354301
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.00336091
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.00319088
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0030516
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.00291441
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.00281065
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.00268798
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.00258469
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.00248311
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.00238788
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.0022846
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.00218803
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.00208708
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.00201227
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.00194162
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.00188559
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.00182396
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.00176124
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.00170436
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.00165168
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.00159726
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.00154622
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.00149025
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.00144865
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.00141002
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.00135963
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.00131283
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.00127559
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.0012411
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.00119732
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.00116873
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.0011256
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.00108572
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.00106886
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.00104997
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.0010334
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.00101818
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.00100475
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.000992226
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.000980749
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.000971678
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.000954902
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.000939255
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.000924654
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.000909921
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.000884633
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.000860458
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.000835485
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.000812224
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.000789984
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.00077062
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.000761831
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.000758864
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.000756576
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.000749337
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.000735399
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.000734144
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.00072035
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.000706912
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.000694176
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.000678765
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.000664021
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.00064998
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.000635085
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.000622233
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.000608709
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.000596943
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.000593596
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.000584196
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.000578683
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.000576001
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.000564804
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.000559303
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.000551276
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.000544394
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.000546321
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.000536481
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.000527584
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.00051836
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.000509447
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.000506448
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.000503675
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.000492859
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.000488463
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.000480207
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.000472748
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.00047613
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.000479719
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.000482059
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.000474934
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.000472628
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 0.000463202
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 0.000467236
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 0.000471055
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 0.00046207
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[116]	valid_0's binary_logloss: 0.000458156
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[117]	valid_0's binary_logloss: 0.000454224
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[118]	valid_0's binary_logloss: 0.000445514
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[119]	valid_0's binary_logloss: 0.000441897
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[120]	valid_0's binary_logloss: 0.000444081
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[121]	valid_0's binary_logloss: 0.000449014
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[122]	valid_0's binary_logloss: 0.000454236
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[123]	valid_0's binary_logloss: 0.000459349
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[124]	valid_0's binary_logloss: 0.000464561
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[125]	valid_0's binary_logloss: 0.000469643
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[126]	valid_0's binary_logloss: 0.00046193
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[127]	valid_0's binary_logloss: 0.00045447
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[128]	valid_0's binary_logloss: 0.000458772
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[129]	valid_0's binary_logloss: 0.000451796
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[130]	valid_0's binary_logloss: 0.000443647
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[131]	valid_0's binary_logloss: 0.000442599
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[132]	valid_0's binary_logloss: 0.000441716
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[133]	valid_0's binary_logloss: 0.000440839
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[134]	valid_0's binary_logloss: 0.000440069
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[135]	valid_0's binary_logloss: 0.000439033
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[136]	valid_0's binary_logloss: 0.00043769
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[137]	valid_0's binary_logloss: 0.000436419
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[138]	valid_0's binary_logloss: 0.000428644
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[139]	valid_0's binary_logloss: 0.000421119
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[140]	valid_0's binary_logloss: 0.000413769
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[141]	valid_0's binary_logloss: 0.000411626
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[142]	valid_0's binary_logloss: 0.000409562
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[143]	valid_0's binary_logloss: 0.000407563
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[144]	valid_0's binary_logloss: 0.000405458
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[145]	valid_0's binary_logloss: 0.000408748
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[146]	valid_0's binary_logloss: 0.000407749
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[147]	valid_0's binary_logloss: 0.00040691
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[148]	valid_0's binary_logloss: 0.000406554
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[149]	valid_0's binary_logloss: 0.000410115
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[150]	valid_0's binary_logloss: 0.0004098
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[151]	valid_0's binary_logloss: 0.00040373
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[152]	valid_0's binary_logloss: 0.000397765
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[153]	valid_0's binary_logloss: 0.00039181
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[154]	valid_0's binary_logloss: 0.000385944
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[155]	valid_0's binary_logloss: 0.000380004
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[156]	valid_0's binary_logloss: 0.000379298
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[157]	valid_0's binary_logloss: 0.000378663
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[158]	valid_0's binary_logloss: 0.000378099
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[159]	valid_0's binary_logloss: 0.000377554
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[160]	valid_0's binary_logloss: 0.000377005
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[161]	valid_0's binary_logloss: 0.000372274
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[162]	valid_0's binary_logloss: 0.000366372
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[163]	valid_0's binary_logloss: 0.000360613
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[164]	valid_0's binary_logloss: 0.000362805
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[165]	valid_0's binary_logloss: 0.000357276
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[166]	valid_0's binary_logloss: 0.000355127
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[167]	valid_0's binary_logloss: 0.000357405
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[168]	valid_0's binary_logloss: 0.000359639
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[169]	valid_0's binary_logloss: 0.000361849
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[170]	valid_0's binary_logloss: 0.000357572
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[171]	valid_0's binary_logloss: 0.000359483
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[172]	valid_0's binary_logloss: 0.000359184
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[173]	valid_0's binary_logloss: 0.000356055
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[174]	valid_0's binary_logloss: 0.000351571
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[175]	valid_0's binary_logloss: 0.000347311
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[176]	valid_0's binary_logloss: 0.000343732
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[177]	valid_0's binary_logloss: 0.000340244
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[178]	valid_0's binary_logloss: 0.000338925
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

Trening klas:  86%|████████▌ | 431/500 [49:55<08:31,  7.41s/klasa, klasa=class_431, F1_klasy=0.9333, F1_macro=0.6374, drzewa=211]




Trening klas:  86%|████████▋ | 432/500 [49:55<08:01,  7.08s/klasa, klasa=class_431, F1_klasy=0.9333, F1_macro=0.6374, drzewa=211]

[238]	valid_0's binary_logloss: 0.00032622
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[239]	valid_0's binary_logloss: 0.000326166
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[240]	valid_0's binary_logloss: 0.000326112
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[241]	valid_0's binary_logloss: 0.000326912
[1]	valid_0's binary_logloss: 0.393186
[2]	valid_0's binary_logloss: 0.263447
[3]	valid_0's binary_logloss: 0.249838
[4]	valid_0's binary_logloss: 0.236838
[5]	valid_0's binary_logloss: 0.227666
[6]	valid_0's binary_logloss: 0.222686
[7]	valid_0's binary_logloss: 0.213967
[8]	valid_0's binary_logloss: 0.20955
[9]	valid_0's binary_logloss: 0.20549
[10]	valid_0's binary_logloss: 0.202075
[11]	valid_0's binary_logloss: 0.199331
[12]	valid_0's binary_logloss: 0.196762
[13]	valid_0's binary_logloss: 0.19474
[14]	valid_0's binary_logloss: 0.192092
[15]	valid_0's binary_logloss: 0.189725
[16]	valid_0's binary_logloss: 0.187186
[17]	valid_0's binary_logloss: 0.184157
[18]	valid_0's binary_logloss: 0.181416
[19]	valid_0's binary_logloss: 0.17868
[20]	valid_0's binary_logloss: 0.176645
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.174976
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.173365
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.171853
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.170201
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.168499
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.16693
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.165598
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.164248
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.162939
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.161661
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.160274
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.158894
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.157629
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.156508
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.155309
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.154304
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.153136
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.152163
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.150877
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.149825
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.148593
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.147563
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.146699
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.145673
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.14448
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.143473
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.142449
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.141481
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.140485
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.139519
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.138652
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.137834
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.137176
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.136396
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.135413
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.134488
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.133575
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.132583
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.131637
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.130802
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.129939
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.129024
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.12836
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.127416
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.126451
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.125602
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.12475
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.123879
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.123216
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.1225
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.121713
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.121013
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.120345
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.119532
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.119125
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.118573
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.117796
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.117309
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.116813
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.116006
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.115363
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.114756
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.114025
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.113474
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.112837
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.112152
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.111484
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.111082
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.110475
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.109823
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.109221
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.108553
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.10805
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.10754
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.106996
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.106596
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.106188
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.105969
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.105579
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.105079
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.104535
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.104129
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.103568
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.103016
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.102478
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.101965
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.101376
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.100863
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.100337
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.0998197
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.0995585
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 0.0990562
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 0.0987226
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 0.0983066
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 0.0980133
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[116]	valid_0's binary_logloss: 0.0976851
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[117]	valid_0's binary_logloss: 0.0973259
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[118]	valid_0's binary_logloss: 0.0971324
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[119]	valid_0's binary_logloss: 0.0970091
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[120]	valid_0's binary_logloss: 0.0967266
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[121]	valid_0's binary_logloss: 0.0964035
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[122]	valid_0's binary_logloss: 0.0960267
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[123]	valid_0's binary_logloss: 0.0956678
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[124]	valid_0's binary_logloss: 0.0953173
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[125]	valid_0's binary_logloss: 0.0949552
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[126]	valid_0's binary_logloss: 0.0944698
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[127]	valid_0's binary_logloss: 0.0940873
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[128]	valid_0's binary_logloss: 0.0934985
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[129]	valid_0's binary_logloss: 0.0931633
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[130]	valid_0's binary_logloss: 0.0928823
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[131]	valid_0's binary_logloss: 0.092496
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[132]	valid_0's binary_logloss: 0.092161
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[133]	valid_0's binary_logloss: 0.0919386
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[134]	valid_0's binary_logloss: 0.0916025
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[135]	valid_0's binary_logloss: 0.091238
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[136]	valid_0's binary_logloss: 0.0910181
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[137]	valid_0's binary_logloss: 0.0908266
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[138]	valid_0's binary_logloss: 0.0905549
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[139]	valid_0's binary_logloss: 0.0903788
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[140]	valid_0's binary_logloss: 0.0901431
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[141]	valid_0's binary_logloss: 0.0899177
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[142]	valid_0's binary_logloss: 0.0895918
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[143]	valid_0's binary_logloss: 0.0892376
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[144]	valid_0's binary_logloss: 0.0889313
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[145]	valid_0's binary_logloss: 0.0886281
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[146]	valid_0's binary_logloss: 0.088346
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[147]	valid_0's binary_logloss: 0.0879479
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[148]	valid_0's binary_logloss: 0.0876927
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[149]	valid_0's binary_logloss: 0.0875077
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[150]	valid_0's binary_logloss: 0.0872082
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[151]	valid_0's binary_logloss: 0.0871092
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[152]	valid_0's binary_logloss: 0.0868886
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[153]	valid_0's binary_logloss: 0.0866864
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[154]	valid_0's binary_logloss: 0.0865126
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[155]	valid_0's binary_logloss: 0.0864437
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[156]	valid_0's binary_logloss: 0.0862929
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[157]	valid_0's binary_logloss: 0.0861375
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[158]	valid_0's binary_logloss: 0.0859975
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[159]	valid_0's binary_logloss: 0.0858133
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[160]	valid_0's binary_logloss: 0.0856805
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[161]	valid_0's binary_logloss: 0.0854976
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[162]	valid_0's binary_logloss: 0.0853328
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[163]	valid_0's binary_logloss: 0.0851987
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[164]	valid_0's binary_logloss: 0.0850829
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[165]	valid_0's binary_logloss: 0.0849704
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[166]	valid_0's binary_logloss: 0.0848833
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[167]	valid_0's binary_logloss: 0.0847913
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[168]	valid_0's binary_logloss: 0.0847211
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[169]	valid_0's binary_logloss: 0.0845799
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[170]	valid_0's binary_logloss: 0.0844237
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[171]	valid_0's binary_logloss: 0.084326
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[172]	valid_0's binary_logloss: 0.0842583
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[173]	valid_0's binary_logloss: 0.084194
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[174]	valid_0's binary_logloss: 0.084106
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[175]	valid_0's binary_logloss: 0.0840383
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[176]	valid_0's binary_logloss: 0.0838455
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[177]	valid_0's binary_logloss: 0.083843
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[178]	valid_0's binary_logloss: 0.083697
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[179]	valid_0's binary_logloss: 0.0835368
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[180]	valid_0's binary_logloss: 0.0834125
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[181]	valid_0's binary_logloss: 0.0832123
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[182]	valid_0's binary_logloss: 0.0830139

Trening klas:  86%|████████▋ | 432/500 [50:05<08:01,  7.08s/klasa, klasa=class_432, F1_klasy=0.2822, F1_macro=0.6365, drzewa=300]




Trening klas:  87%|████████▋ | 433/500 [50:05<08:35,  7.69s/klasa, klasa=class_432, F1_klasy=0.2822, F1_macro=0.6365, drzewa=300]

[1]	valid_0's binary_logloss: 0.120613
[2]	valid_0's binary_logloss: 0.0798849
[3]	valid_0's binary_logloss: 0.0186025
[4]	valid_0's binary_logloss: 0.0174219
[5]	valid_0's binary_logloss: 0.0163311
[6]	valid_0's binary_logloss: 0.0152359
[7]	valid_0's binary_logloss: 0.0145315
[8]	valid_0's binary_logloss: 0.0139815
[9]	valid_0's binary_logloss: 0.013604
[10]	valid_0's binary_logloss: 0.0132322
[11]	valid_0's binary_logloss: 0.0127817
[12]	valid_0's binary_logloss: 0.0121799
[13]	valid_0's binary_logloss: 0.0117717
[14]	valid_0's binary_logloss: 0.0112605
[15]	valid_0's binary_logloss: 0.010873
[16]	valid_0's binary_logloss: 0.0104296
[17]	valid_0's binary_logloss: 0.0101124
[18]	valid_0's binary_logloss: 0.00974135
[19]	valid_0's binary_logloss: 0.00945464
[20]	valid_0's binary_logloss: 0.00913462
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.00880075
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.00847441
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.00816757
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0078787
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.00760775
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.00734666
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.00710132
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.00687056
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.00665343
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.00645004
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.00628038
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.0061173
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.00597865
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.00581979
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.00567606
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.00555979
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.00544877
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.00531156
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.00521075
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.00511482
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.0050547
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.00496912
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.00491125
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.0048452
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.00474983
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.00463265
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.00453383
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.0044394
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.00434918
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.00424955
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.00418349
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.00412313
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.00405642
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.00400165
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.00394741
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.0038944
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.0038714
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.00385019
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.00383379
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.00381808
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.00378094
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.00373655
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.00369705
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.00366536
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.00363464
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.00358222
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.00352631
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.00349143
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.00344233
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.00341116
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.00337148
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.00332061
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.00327325
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.00323923
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.00320403
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.00316827
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.00313432
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.00310212
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.00307158
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.00304263
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.00303023
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.00298287
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.00297263
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.00296336
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.00295572
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.00294896
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.00294301
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.0029375
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.00293302
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.00289975
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.00286036
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.0028222
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.00278523
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.00274941
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.00271472
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.00268314
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.0026525
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.00262276
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.00259394
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.00256392
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.00256092
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.00254394
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.00253026
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.00252244
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.0025069
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.00249333
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.00247934
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.0024809
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.00248285
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.00248516
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.00248641
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 0.00246982
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 0.00246634
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 0.00246309
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 0.00245989
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[116]	valid_0's binary_logloss: 0.00245184
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[117]	valid_0's binary_logloss: 0.00244445
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[118]	valid_0's binary_logloss: 0.00243753
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[119]	valid_0's binary_logloss: 0.00243166
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[120]	valid_0's binary_logloss: 0.00242561
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[121]	valid_0's binary_logloss: 0.00242007
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[122]	valid_0's binary_logloss: 0.00241112
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[123]	valid_0's binary_logloss: 0.00240247
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[124]	valid_0's binary_logloss: 0.00239415
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[125]	valid_0's binary_logloss: 0.00238979
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[126]	valid_0's binary_logloss: 0.00239337
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[127]	valid_0's binary_logloss: 0.0023984
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[128]	valid_0's binary_logloss: 0.00238082
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[129]	valid_0's binary_logloss: 0.00238547
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[130]	valid_0's binary_logloss: 0.00236859
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[131]	valid_0's binary_logloss: 0.00236502
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[132]	valid_0's binary_logloss: 0.00236172
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[133]	valid_0's binary_logloss: 0.00235867
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[134]	valid_0's binary_logloss: 0.00235587
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[135]	valid_0's binary_logloss: 0.0023533
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[136]	valid_0's binary_logloss: 0.00234564
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[137]	valid_0's binary_logloss: 0.00234342
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[138]	valid_0's binary_logloss: 0.00233612
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[139]	valid_0's binary_logloss: 0.00233408
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[140]	valid_0's binary_logloss: 0.00232713
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[141]	valid_0's binary_logloss: 0.00232466
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[142]	valid_0's binary_logloss: 0.00231502
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[143]	valid_0's binary_logloss: 0.00230571
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[144]	valid_0's binary_logloss: 0.00229665
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[145]	valid_0's binary_logloss: 0.00228786
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[146]	valid_0's binary_logloss: 0.00227615
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[147]	valid_0's binary_logloss: 0.00226477
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[148]	valid_0's binary_logloss: 0.00225371
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[149]	valid_0's binary_logloss: 0.00224298
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[150]	valid_0's binary_logloss: 0.0022468
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[151]	valid_0's binary_logloss: 0.00224105
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[152]	valid_0's binary_logloss: 0.00223562
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[153]	valid_0's binary_logloss: 0.00223034
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[154]	valid_0's binary_logloss: 0.00222503
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[155]	valid_0's binary_logloss: 0.00222864
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[156]	valid_0's binary_logloss: 0.00223237
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[157]	valid_0's binary_logloss: 0.00223605
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[158]	valid_0's binary_logloss: 0.00223626
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[159]	valid_0's binary_logloss: 0.00224385
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[160]	valid_0's binary_logloss: 0.00224739
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[161]	valid_0's binary_logloss: 0.00224084
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[162]	valid_0's binary_logloss: 0.00223451
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[163]	valid_0's binary_logloss: 0.00222918
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[164]	valid_0's binary_logloss: 0.00222323
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[165]	valid_0's binary_logloss: 0.00221828
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[166]	valid_0's binary_logloss: 0.00222151
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[167]	valid_0's binary_logloss: 0.00221179
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[168]	valid_0's binary_logloss: 0.00220232
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[169]	valid_0's binary_logloss: 0.00220543
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[170]	valid_0's binary_logloss: 0.00220237
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[171]	valid_0's binary_logloss: 0.00219752
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[172]	valid_0's binary_logloss: 0.00219737
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[173]	valid_0's binary_logloss: 0.00219726
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[174]	valid_0's binary_logloss: 0.00219645
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[175]	valid_0's binary_logloss: 0.00219643
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[176]	valid_0's binary_logloss: 0.0021991
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[177]	valid_0's binary_logloss: 0.00219592
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[178]	valid_0's binary_logloss: 0.00219851
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[179]	valid_0's binary_logloss: 0.00219056
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[180]	valid_0's binary_logloss: 0.00218274
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[181]	valid_0's binary_logloss: 0.00218227
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[182]	valid_0's binary_logloss: 0.00218827
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[183]	valid_0's binary_logloss: 0.00219133

Trening klas:  87%|████████▋ | 433/500 [50:09<08:35,  7.69s/klasa, klasa=class_433, F1_klasy=0.9691, F1_macro=0.6373, drzewa=181]




Trening klas:  87%|████████▋ | 434/500 [50:09<07:33,  6.87s/klasa, klasa=class_433, F1_klasy=0.9691, F1_macro=0.6373, drzewa=181]

[1]	valid_0's binary_logloss: 0.278319
[2]	valid_0's binary_logloss: 0.178525
[3]	valid_0's binary_logloss: 0.172446
[4]	valid_0's binary_logloss: 0.162269
[5]	valid_0's binary_logloss: 0.153595
[6]	valid_0's binary_logloss: 0.304784
[7]	valid_0's binary_logloss: 0.299808
[8]	valid_0's binary_logloss: 0.296582
[9]	valid_0's binary_logloss: 0.293398
[10]	valid_0's binary_logloss: 0.289469
[11]	valid_0's binary_logloss: 0.286282
[12]	valid_0's binary_logloss: 0.284165
[13]	valid_0's binary_logloss: 0.280912
[14]	valid_0's binary_logloss: 0.278276
[15]	valid_0's binary_logloss: 0.275454
[16]	valid_0's binary_logloss: 0.272913
[17]	valid_0's binary_logloss: 0.270321
[18]	valid_0's binary_logloss: 0.267483
[19]	valid_0's binary_logloss: 0.265495
[20]	valid_0's binary_logloss: 0.264002
[21]	valid_0's binary_logloss: 0.261726
[22]	valid_0's binary_logloss: 0.259973
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.257888
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.253945
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.241021
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.237069
[27]	valid_0's binary_logloss: 0.234072
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.231641
[29]	valid_0's binary_logloss: 0.229055
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.226019
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.223678
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.221756

Trening klas:  87%|████████▋ | 434/500 [50:14<07:33,  6.87s/klasa, klasa=class_434, F1_klasy=0.1145, F1_macro=0.6361, drzewa=5]




Trening klas:  87%|████████▋ | 435/500 [50:14<06:32,  6.04s/klasa, klasa=class_434, F1_klasy=0.1145, F1_macro=0.6361, drzewa=5]

[33]	valid_0's binary_logloss: 0.219974
[34]	valid_0's binary_logloss: 0.21872
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.217017
[1]	valid_0's binary_logloss: 0.0773059
[2]	valid_0's binary_logloss: 0.0571359
[3]	valid_0's binary_logloss: 0.0544699
[4]	valid_0's binary_logloss: 0.0529995
[5]	valid_0's binary_logloss: 0.0516975
[6]	valid_0's binary_logloss: 0.0742495
[7]	valid_0's binary_logloss: 0.07153
[8]	valid_0's binary_logloss: 0.0692794
[9]	valid_0's binary_logloss: 0.0681858
[10]	valid_0's binary_logloss: 0.0652256
[11]	valid_0's binary_logloss: 0.0615203
[12]	valid_0's binary_logloss: 0.0594943
[13]	valid_0's binary_logloss: 0.0586581
[14]	valid_0's binary_logloss: 0.0573972
[15]	valid_0's binary_logloss: 0.0563296
[16]	valid_0's binary_logloss: 0.0555237
[17]	valid_0's binary_logloss: 0.0546901
[18]	valid_0's binary_logloss: 0.0537367
[19]	valid_0's binary_logloss: 0.0530004
[20]	valid_0's binary_logloss: 0.0524002
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0516247
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.050901
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.0502704
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0496882
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.0490256
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.0483351
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.0478476
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.0472504
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.0465637
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.0459739
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.0454311
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.0448945
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.044402
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.0439549
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.0434816
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.0429961
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.0425905
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.0421375
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.0417137
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.0412794
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.0408598
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.0404314
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.0400146
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.0395839
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.0391882
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.0388209
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.0384737
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.0381372
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.0377149
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.0373692
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.0371304
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.0368802
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.0365596
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.0362487
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.0359503
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.0356326
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.0352583
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.0349108
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.0346238
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.0343324
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.0340301
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.0337139
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.0333706
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.0330327
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.032802
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.0326098
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.0324153
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.0322179
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.0320262
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.0317971
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.0315887
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.0314001
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.0312035
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.0309893
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.030804
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.0305608
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.0303001
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.0300546
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.0298191
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.0296096
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.0294164
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.0292107
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.0290191
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.028825
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.0286515
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.0284717
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.0282913
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.0280854
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.0279143
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.0277594
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.0275164
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.0273527
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.0271961
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.0270164
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.0269282
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.0267496
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.0265809
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.0264071
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.0262504
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.0260767
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.0259381
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.0258316
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.0257296
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.0256799
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.0256056
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.0255349
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.0254053
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.0252918
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.0252222
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.0251555
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.0249892
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 0.024823
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 0.02465
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 0.0244834
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 0.0243335
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[116]	valid_0's binary_logloss: 0.0241945
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[117]	valid_0's binary_logloss: 0.0240992
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[118]	valid_0's binary_logloss: 0.0240311
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[119]	valid_0's binary_logloss: 0.0239982
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[120]	valid_0's binary_logloss: 0.0239213
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[121]	valid_0's binary_logloss: 0.0239101
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[122]	valid_0's binary_logloss: 0.0238493
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[123]	valid_0's binary_logloss: 0.0237973
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[124]	valid_0's binary_logloss: 0.0237169
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[125]	valid_0's binary_logloss: 0.0236517
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[126]	valid_0's binary_logloss: 0.023563
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[127]	valid_0's binary_logloss: 0.0235077
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[128]	valid_0's binary_logloss: 0.0234218
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[129]	valid_0's binary_logloss: 0.0233673
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[130]	valid_0's binary_logloss: 0.02333
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[131]	valid_0's binary_logloss: 0.0232919
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[132]	valid_0's binary_logloss: 0.023248
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[133]	valid_0's binary_logloss: 0.0232019
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[134]	valid_0's binary_logloss: 0.023082
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[135]	valid_0's binary_logloss: 0.0230415
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[136]	valid_0's binary_logloss: 0.0230508
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[137]	valid_0's binary_logloss: 0.0230739
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[138]	valid_0's binary_logloss: 0.0230572
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[139]	valid_0's binary_logloss: 0.0230516
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[140]	valid_0's binary_logloss: 0.0230131
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[141]	valid_0's binary_logloss: 0.0229478
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[142]	valid_0's binary_logloss: 0.0228706
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[143]	valid_0's binary_logloss: 0.0228124
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[144]	valid_0's binary_logloss: 0.0227504
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[145]	valid_0's binary_logloss: 0.0227091
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[146]	valid_0's binary_logloss: 0.0226788
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[147]	valid_0's binary_logloss: 0.0226214
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[148]	valid_0's binary_logloss: 0.0225879
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[149]	valid_0's binary_logloss: 0.0225399
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[150]	valid_0's binary_logloss: 0.0225428
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[151]	valid_0's binary_logloss: 0.022495
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[152]	valid_0's binary_logloss: 0.0224558
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[153]	valid_0's binary_logloss: 0.0224189
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[154]	valid_0's binary_logloss: 0.0223805
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[155]	valid_0's binary_logloss: 0.0223303
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[156]	valid_0's binary_logloss: 0.0222436
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[157]	valid_0's binary_logloss: 0.0221839
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[158]	valid_0's binary_logloss: 0.0221449
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[159]	valid_0's binary_logloss: 0.0220973
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[160]	valid_0's binary_logloss: 0.0220519
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[161]	valid_0's binary_logloss: 0.0219743
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[162]	valid_0's binary_logloss: 0.0219194
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[163]	valid_0's binary_logloss: 0.0218567
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[164]	valid_0's binary_logloss: 0.021827
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[165]	valid_0's binary_logloss: 0.0217889
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[166]	valid_0's binary_logloss: 0.0217406
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[167]	valid_0's binary_logloss: 0.0217168
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[168]	valid_0's binary_logloss: 0.0216598
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[169]	valid_0's binary_logloss: 0.0216121
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[170]	valid_0's binary_logloss: 0.0215614
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[171]	valid_0's binary_logloss: 0.0215487
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[172]	valid_0's binary_logloss: 0.0215423
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[173]	valid_0's binary_logloss: 0.0215223
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[174]	valid_0's binary_logloss: 0.0215266
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[175]	valid_0's binary_logloss: 0.0215199
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[176]	valid_0's binary_logloss: 0.0215131
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[177]	valid_0's binary_logloss: 0.0214973
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[178]	valid_0's binary_logloss: 0.0215101
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[179]	valid_0's binary_logloss: 0.0215226
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[180]	valid_0's binary_logloss: 0.0215193
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[181]	valid_0's binary_logloss: 0.0215231
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[182]	valid_0's binary_logloss: 0.0214888
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[183]	valid_0's binary_logloss: 0.0214754

Trening klas:  87%|████████▋ | 435/500 [50:24<06:32,  6.04s/klasa, klasa=class_435, F1_klasy=0.5789, F1_macro=0.6360, drzewa=300]




Trening klas:  87%|████████▋ | 436/500 [50:24<07:48,  7.32s/klasa, klasa=class_435, F1_klasy=0.5789, F1_macro=0.6360, drzewa=300]

[297]	valid_0's binary_logloss: 0.0198078
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[298]	valid_0's binary_logloss: 0.0198023
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[299]	valid_0's binary_logloss: 0.0198016
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[300]	valid_0's binary_logloss: 0.0197978
[1]	valid_0's binary_logloss: 0.313496
[2]	valid_0's binary_logloss: 0.141278
[3]	valid_0's binary_logloss: 0.173386
[4]	valid_0's binary_logloss: 0.169962
[5]	valid_0's binary_logloss: 0.166518
[6]	valid_0's binary_logloss: 0.162489
[7]	valid_0's binary_logloss: 0.160479
[8]	valid_0's binary_logloss: 0.157967
[9]	valid_0's binary_logloss: 0.156024
[10]	valid_0's binary_logloss: 0.154247
[11]	valid_0's binary_logloss: 0.153142
[12]	valid_0's binary_logloss: 0.151543
[13]	valid_0's binary_logloss: 0.150406
[14]	valid_0's binary_logloss: 0.149032
[15]	valid_0's binary_logloss: 0.147755
[16]	valid_0's binary_logloss: 0.146444
[17]	valid_0's binary_logloss: 0.145526
[18]	valid_0's binary_logloss: 0.144963
[19]	valid_0's binary_logloss: 0.144123
[20]	valid_0's binary_logloss: 0.143379
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.14273
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.141995
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.141244
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.140325
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.139628
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.139145
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.138642
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.138048
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.137538
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.137113
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.136892
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.136745
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.136843
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.136732
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.13623
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.136035
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.135827
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.135891
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.135386
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.135564
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.135376
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.134985
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.134727
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.134046
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.133959
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.133748
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.133523
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.133315
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.133054
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.132865
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.132338
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.132034
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.131747
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.131494
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.131188
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.130898
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.130577
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.130271
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.129985
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.129718
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.129435
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.129168
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.128895
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.128696
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.128419
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.12818
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.127958
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.12771
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.127723
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.127608
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.127399
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.127311
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.127106
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.12687
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.12671
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.126484
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.126295
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.126134
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.125962
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.125786
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.125619
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.125333
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.125213
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.125077
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.124947
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.12479
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.124521
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.124308
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.1241
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.124007
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.123741
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.123492
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.123267
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.123084
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.122929
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.122873
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.122808
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.122783
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.122634
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.122509
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.122214
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.122135
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.121962
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.12184
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.121661
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.121636
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.121552
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.12148
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.121345
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.121211
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.121047
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 0.12089
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 0.120676
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 0.120449
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 0.120293
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[116]	valid_0's binary_logloss: 0.120235
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[117]	valid_0's binary_logloss: 0.120126
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[118]	valid_0's binary_logloss: 0.120106
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[119]	valid_0's binary_logloss: 0.120048
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[120]	valid_0's binary_logloss: 0.120072
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[121]	valid_0's binary_logloss: 0.120012
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[122]	valid_0's binary_logloss: 0.11995
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[123]	valid_0's binary_logloss: 0.119861
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[124]	valid_0's binary_logloss: 0.119799
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[125]	valid_0's binary_logloss: 0.119702
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[126]	valid_0's binary_logloss: 0.11957
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[127]	valid_0's binary_logloss: 0.119453
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[128]	valid_0's binary_logloss: 0.119313
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[129]	valid_0's binary_logloss: 0.119216
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[130]	valid_0's binary_logloss: 0.119112
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[131]	valid_0's binary_logloss: 0.119066
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[132]	valid_0's binary_logloss: 0.118971
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[133]	valid_0's binary_logloss: 0.118941
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[134]	valid_0's binary_logloss: 0.118886
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[135]	valid_0's binary_logloss: 0.118904
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[136]	valid_0's binary_logloss: 0.118791
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[137]	valid_0's binary_logloss: 0.118683
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[138]	valid_0's binary_logloss: 0.11858
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[139]	valid_0's binary_logloss: 0.118517
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[140]	valid_0's binary_logloss: 0.118411
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[141]	valid_0's binary_logloss: 0.118375
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[142]	valid_0's binary_logloss: 0.11828
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[143]	valid_0's binary_logloss: 0.118189
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[144]	valid_0's binary_logloss: 0.118102
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[145]	valid_0's binary_logloss: 0.118001
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[146]	valid_0's binary_logloss: 0.117932
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[147]	valid_0's binary_logloss: 0.117886
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[148]	valid_0's binary_logloss: 0.117851
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[149]	valid_0's binary_logloss: 0.117813
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[150]	valid_0's binary_logloss: 0.11777
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[151]	valid_0's binary_logloss: 0.117726
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[152]	valid_0's binary_logloss: 0.117717
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[153]	valid_0's binary_logloss: 0.117654
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[154]	valid_0's binary_logloss: 0.117619
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[155]	valid_0's binary_logloss: 0.117594
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[156]	valid_0's binary_logloss: 0.11746
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[157]	valid_0's binary_logloss: 0.117344
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[158]	valid_0's binary_logloss: 0.117268
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[159]	valid_0's binary_logloss: 0.117172
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[160]	valid_0's binary_logloss: 0.117126
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[161]	valid_0's binary_logloss: 0.11713
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[162]	valid_0's binary_logloss: 0.117098
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[163]	valid_0's binary_logloss: 0.117063
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[164]	valid_0's binary_logloss: 0.117033
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[165]	valid_0's binary_logloss: 0.117007
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[166]	valid_0's binary_logloss: 0.1169
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[167]	valid_0's binary_logloss: 0.11684
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[168]	valid_0's binary_logloss: 0.116747
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[169]	valid_0's binary_logloss: 0.116738
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[170]	valid_0's binary_logloss: 0.116707
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[171]	valid_0's binary_logloss: 0.116671
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[172]	valid_0's binary_logloss: 0.116577
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[173]	valid_0's binary_logloss: 0.11649
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[174]	valid_0's binary_logloss: 0.116492
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[175]	valid_0's binary_logloss: 0.116459
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[176]	valid_0's binary_logloss: 0.116353
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[177]	valid_0's binary_logloss: 0.116252
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[178]	valid_0's binary_logloss: 0.116165
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[179]	valid_0's binary_logloss: 0.11607
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[180]	valid_0's binary_logloss: 0.115987
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[181]	valid_0's binary_logloss: 0.115952
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[182]	valid_0's binary_logloss: 0.115922
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[183]	valid_0's binary_logloss: 0.115891

Trening klas:  87%|████████▋ | 436/500 [50:33<07:48,  7.32s/klasa, klasa=class_436, F1_klasy=0.4868, F1_macro=0.6356, drzewa=300]




Trening klas:  87%|████████▋ | 437/500 [50:33<08:24,  8.00s/klasa, klasa=class_436, F1_klasy=0.4868, F1_macro=0.6356, drzewa=300]

[298]	valid_0's binary_logloss: 0.114183
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[299]	valid_0's binary_logloss: 0.114155
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[300]	valid_0's binary_logloss: 0.114144
[1]	valid_0's binary_logloss: 0.0174501
[2]	valid_0's binary_logloss: 0.0118084
[3]	valid_0's binary_logloss: 0.0112259
[4]	valid_0's binary_logloss: 0.0104529
[5]	valid_0's binary_logloss: 0.00971188
[6]	valid_0's binary_logloss: 0.00907893
[7]	valid_0's binary_logloss: 0.00866232
[8]	valid_0's binary_logloss: 0.00833778
[9]	valid_0's binary_logloss: 0.00807552
[10]	valid_0's binary_logloss: 0.00775658
[11]	valid_0's binary_logloss: 0.00742083
[12]	valid_0's binary_logloss: 0.00704221
[13]	valid_0's binary_logloss: 0.0067037
[14]	valid_0's binary_logloss: 0.00654329
[15]	valid_0's binary_logloss: 0.0062223
[16]	valid_0's binary_logloss: 0.00597219
[17]	valid_0's binary_logloss: 0.00575204
[18]	valid_0's binary_logloss: 0.00556693
[19]	valid_0's binary_logloss: 0.0053564
[20]	valid_0's binary_logloss: 0.00516426
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.00503503
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.00488017
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.00479032
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.00468009
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.00457349
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.00442924
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.00432111
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.0041922
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.00409532
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.00396863
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.00389759
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.00381687
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.00374692
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.00368071
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.00362637
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.0035415
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.00348288
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.00341306
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.00333096
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.00325644
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.00320841
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.00316434
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.00311936
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.0030677
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.00302864
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.00298197
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.00293336
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.00290988
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.00287538
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.00285255
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.00281972
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.00278978
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.00276105
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.00273506
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.00270421
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.00270337
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.00269495
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.00267602
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.00266329
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.00266498
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.00263911
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.00261329
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.00259282
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.00258459
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.00256374
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.00254882
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.00253003
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.0025095
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.00249116
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.0024814
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.00246934
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.00245667
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.00245065
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.00243378
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.00240783
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.00239828
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.00238864
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.00238979
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.0023876
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.00239625
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.00238154
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.00236601
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.00236033
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.00234531
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.00233858
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.00232137
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.00230574
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.00229791
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.00229267
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.00228742
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.0022803
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.00227736
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.00228013
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.002292
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.00228913
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.00228784
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.00228417
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.00227906
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.00226977
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.00226144
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.00225468
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.00225618
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.00225702
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.0022438
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.00224035
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.00224371
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.00223143
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.00223573
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.00222404
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.00221285
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.00221227
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 0.00221928
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 0.0022235
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 0.00222971
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 0.0022417
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[116]	valid_0's binary_logloss: 0.00224137
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[117]	valid_0's binary_logloss: 0.00224173
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[118]	valid_0's binary_logloss: 0.00224431
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[119]	valid_0's binary_logloss: 0.00224982
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[120]	valid_0's binary_logloss: 0.00224652
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[121]	valid_0's binary_logloss: 0.00224651
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[122]	valid_0's binary_logloss: 0.00224466
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[123]	valid_0's binary_logloss: 0.00224627
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[124]	valid_0's binary_logloss: 0.00224417
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[125]	valid_0's binary_logloss: 0.00223783
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[126]	valid_0's binary_logloss: 0.00223575
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[127]	valid_0's binary_logloss: 0.0022462
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[128]	valid_0's binary_logloss: 0.00224937
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[129]	valid_0's binary_logloss: 0.00225022
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[130]	valid_0's binary_logloss: 0.00225142
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[131]	valid_0's binary_logloss: 0.00223894
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[132]	valid_0's binary_logloss: 0.00223877
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[133]	valid_0's binary_logloss: 0.0022342
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[134]	valid_0's binary_logloss: 0.00222844
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[135]	valid_0's binary_logloss: 0.00222421
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[136]	valid_0's binary_logloss: 0.00222497
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[137]	valid_0's binary_logloss: 0.00223266
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[138]	valid_0's binary_logloss: 0.0022428
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

Trening klas:  87%|████████▋ | 437/500 [50:40<08:24,  8.00s/klasa, klasa=class_437, F1_klasy=0.8889, F1_macro=0.6362, drzewa=111]




Trening klas:  88%|████████▊ | 438/500 [50:40<07:52,  7.62s/klasa, klasa=class_437, F1_klasy=0.8889, F1_macro=0.6362, drzewa=111]

[139]	valid_0's binary_logloss: 0.00223908
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[140]	valid_0's binary_logloss: 0.00223523
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[141]	valid_0's binary_logloss: 0.00223984
[1]	valid_0's binary_logloss: 0.0878493
[2]	valid_0's binary_logloss: 0.0730527
[3]	valid_0's binary_logloss: 0.0684527
[4]	valid_0's binary_logloss: 0.0646091
[5]	valid_0's binary_logloss: 0.060843
[6]	valid_0's binary_logloss: 0.105932
[7]	valid_0's binary_logloss: 0.0969646
[8]	valid_0's binary_logloss: 0.0906918
[9]	valid_0's binary_logloss: 0.0863465
[10]	valid_0's binary_logloss: 0.0833052
[11]	valid_0's binary_logloss: 0.0798714
[12]	valid_0's binary_logloss: 0.0767402
[13]	valid_0's binary_logloss: 0.0741153
[14]	valid_0's binary_logloss: 0.0721209
[15]	valid_0's binary_logloss: 0.0695665
[16]	valid_0's binary_logloss: 0.0680538
[17]	valid_0's binary_logloss: 0.066436
[18]	valid_0's binary_logloss: 0.0648209
[19]	valid_0's binary_logloss: 0.0634569
[20]	valid_0's binary_logloss: 0.062259
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0608987
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0596206
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.0583705
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0571985
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.0559664
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.0548941
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.0539519
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.0530931
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.0520742
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.0512565
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.0503129
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.0493136
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.0485261
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.0478319
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.0468873
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.0461071
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.0453928
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.0448579
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.044066
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.0435672
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.042759
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.0419947
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.0414641
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.0407824
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.0401037
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.0394409
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.0387904
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.0382081
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.0376518
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.0371433
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.0365623
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.0361247
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.0356373
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.0351156
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.0346275
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.034154
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.0336389
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.0331491
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.0327814
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.0324045
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.0319626
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.0315114
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.0311053
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.0306723
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.0302647
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.0300754
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.0298332
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.0293699
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.0291229
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.0289696
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.0286282
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.0283537
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.0280317
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.0276747
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.0273153
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.0269811
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.0266268
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.0263688
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.0260381
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.0257393
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.0254689
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.0252063
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.02506
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.0249446
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.0248269
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.0246297
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.0242996
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.0240485
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.0237833
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.0236244
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.0233714
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.0230898
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.0229301
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.0226833
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.0224543
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.0223217
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.0221702
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.0220227
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.021902
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.0217782
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.0216569
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.0214808
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.0213395
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.0212191
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.0210563
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.0210357
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.0209667
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.0208825
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.0208611
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.020807
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.020746
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 0.0206803
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 0.0205258
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 0.0203289
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 0.0201938
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[116]	valid_0's binary_logloss: 0.0200045
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[117]	valid_0's binary_logloss: 0.0198546
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[118]	valid_0's binary_logloss: 0.0197199
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[119]	valid_0's binary_logloss: 0.0195845
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[120]	valid_0's binary_logloss: 0.019479
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[121]	valid_0's binary_logloss: 0.0193729
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[122]	valid_0's binary_logloss: 0.0192543
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[123]	valid_0's binary_logloss: 0.0192277
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[124]	valid_0's binary_logloss: 0.0190741
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[125]	valid_0's binary_logloss: 0.0191144
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[126]	valid_0's binary_logloss: 0.0189327
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[127]	valid_0's binary_logloss: 0.0188222
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[128]	valid_0's binary_logloss: 0.0186725
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[129]	valid_0's binary_logloss: 0.0185603
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[130]	valid_0's binary_logloss: 0.0184404
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[131]	valid_0's binary_logloss: 0.0183623
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[132]	valid_0's binary_logloss: 0.0182895
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[133]	valid_0's binary_logloss: 0.0182385
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[134]	valid_0's binary_logloss: 0.0182171
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[135]	valid_0's binary_logloss: 0.0181964
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[136]	valid_0's binary_logloss: 0.0180867
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[137]	valid_0's binary_logloss: 0.0179905
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[138]	valid_0's binary_logloss: 0.0178649
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[139]	valid_0's binary_logloss: 0.0177481
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[140]	valid_0's binary_logloss: 0.0176348
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[141]	valid_0's binary_logloss: 0.0175728
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[142]	valid_0's binary_logloss: 0.0174477
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[143]	valid_0's binary_logloss: 0.017383
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[144]	valid_0's binary_logloss: 0.0172779
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[145]	valid_0's binary_logloss: 0.0172186
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[146]	valid_0's binary_logloss: 0.0171493
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[147]	valid_0's binary_logloss: 0.017026
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[148]	valid_0's binary_logloss: 0.0170101
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[149]	valid_0's binary_logloss: 0.0168897
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[150]	valid_0's binary_logloss: 0.0168226
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[151]	valid_0's binary_logloss: 0.0166726
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[152]	valid_0's binary_logloss: 0.0165114
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[153]	valid_0's binary_logloss: 0.0163698
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[154]	valid_0's binary_logloss: 0.0162973
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[155]	valid_0's binary_logloss: 0.0162087
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[156]	valid_0's binary_logloss: 0.0162157
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[157]	valid_0's binary_logloss: 0.016143
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[158]	valid_0's binary_logloss: 0.0160649
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[159]	valid_0's binary_logloss: 0.0159756
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[160]	valid_0's binary_logloss: 0.0159129
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[161]	valid_0's binary_logloss: 0.015854
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[162]	valid_0's binary_logloss: 0.0157739
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[163]	valid_0's binary_logloss: 0.0157438
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[164]	valid_0's binary_logloss: 0.0157577
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[165]	valid_0's binary_logloss: 0.0156968
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[166]	valid_0's binary_logloss: 0.015696
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[167]	valid_0's binary_logloss: 0.0156258
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[168]	valid_0's binary_logloss: 0.0156293
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[169]	valid_0's binary_logloss: 0.0156323
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[170]	valid_0's binary_logloss: 0.0156008
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[171]	valid_0's binary_logloss: 0.0155484
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[172]	valid_0's binary_logloss: 0.0154854
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[173]	valid_0's binary_logloss: 0.0154107
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[174]	valid_0's binary_logloss: 0.0153663
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[175]	valid_0's binary_logloss: 0.0152886
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[176]	valid_0's binary_logloss: 0.0152386
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[177]	valid_0's binary_logloss: 0.0151989
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[178]	valid_0's binary_logloss: 0.0151477
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[179]	valid_0's binary_logloss: 0.0151166
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[180]	valid_0's binary_logloss: 0.0151008
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[181]	valid_0's binary_logloss: 0.015066
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[182]	valid_0's binary_logloss: 0.0150404

Trening klas:  88%|████████▊ | 438/500 [50:50<07:52,  7.62s/klasa, klasa=class_438, F1_klasy=0.4286, F1_macro=0.6357, drzewa=300]




Trening klas:  88%|████████▊ | 439/500 [50:50<08:20,  8.20s/klasa, klasa=class_438, F1_klasy=0.4286, F1_macro=0.6357, drzewa=300]

[294]	valid_0's binary_logloss: 0.0119818
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[295]	valid_0's binary_logloss: 0.0119864
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[296]	valid_0's binary_logloss: 0.0119857
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[297]	valid_0's binary_logloss: 0.0119696
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[298]	valid_0's binary_logloss: 0.0119689
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[299]	valid_0's binary_logloss: 0.0119656
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[300]	valid_0's binary_logloss: 0.0119364
[1]	valid_0's binary_logloss: 0.0514213
[2]	valid_0's binary_logloss: 0.0337159
[3]	valid_0's binary_logloss: 0.030762
[4]	valid_0's binary_logloss: 0.0296886
[5]	valid_0's binary_logloss: 0.0284981
[6]	valid_0's binary_logloss: 0.0277645
[7]	valid_0's binary_logloss: 0.0271007
[8]	valid_0's binary_logloss: 0.0264682
[9]	valid_0's binary_logloss: 0.0257405
[10]	valid_0's binary_logloss: 0.0250837
[11]	valid_0's binary_logloss: 0.0228386
[12]	valid_0's binary_logloss: 0.0223651
[13]	valid_0's binary_logloss: 0.0212643
[14]	valid_0's binary_logloss: 0.0207281
[15]	valid_0's binary_logloss: 0.0200083
[16]	valid_0's binary_logloss: 0.0187527
[17]	valid_0's binary_logloss: 0.0181648
[18]	valid_0's binary_logloss: 0.0177793
[19]	valid_0's binary_logloss: 0.0173576
[20]	valid_0's binary_logloss: 0.0170222
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0167486
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0163328
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.0159872
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0155725
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.0152807
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.01484
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.014548
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.0142155
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.0139174
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.0135816
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.0133518
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.0131614
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.0129878
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.0127666
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.0126094
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.0124504
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.0123052
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.0121575
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.0119909
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.0118356
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.0115906
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.0113922
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.0111319
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.0109115
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.010759
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.0104619
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.0102727
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.0100849
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.0099216
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.00976456
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.00958575
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.00942401
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.00930673
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.00914574
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.00902721
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.00890848
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.00885082
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.0088111
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.00878462
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.00870653
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.00863166
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.00850462
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.00844713
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.00838573
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.00826441
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.00821473
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.0081692
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.00811751
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.00808425
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.00805187
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.00796886
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.00773783
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.00763639
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.00748578
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.00742202
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.00741101
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.00731933
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.00730769
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.00726212
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.00721262
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.00715263
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.0071049
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.00708485
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.00707512
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.00705637
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.0070803
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.00708977
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.00706022
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.00707274
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.0070468
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.00705797
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.00708516
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.00709033
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.00709487
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.00711475
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.00710588
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.00708935
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.00706852
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.00707643
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.00706977
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.00708159
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.00705161
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.00702266
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.00699836
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.00699846
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.00696161
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.00695085
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.0069277
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.00690779
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.0069002
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.00690727
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 0.00690132
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 0.00689619
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 0.00691323
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 0.00690259
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[116]	valid_0's binary_logloss: 0.00689326
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[117]	valid_0's binary_logloss: 0.00687923
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[118]	valid_0's binary_logloss: 0.00687105
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[119]	valid_0's binary_logloss: 0.00685514
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[120]	valid_0's binary_logloss: 0.00684732
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[121]	valid_0's binary_logloss: 0.00686017
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[122]	valid_0's binary_logloss: 0.00683953
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[123]	valid_0's binary_logloss: 0.00685665
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[124]	valid_0's binary_logloss: 0.00686171
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[125]	valid_0's binary_logloss: 0.00689203
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[126]	valid_0's binary_logloss: 0.00688994
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[127]	valid_0's binary_logloss: 0.00687828
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[128]	valid_0's binary_logloss: 0.00686798
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[129]	valid_0's binary_logloss: 0.00683498
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[130]	valid_0's binary_logloss: 0.00682081
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[131]	valid_0's binary_logloss: 0.00682641
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[132]	valid_0's binary_logloss: 0.00680507
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[133]	valid_0's binary_logloss: 0.00677956
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[134]	valid_0's binary_logloss: 0.00675442
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[135]	valid_0's binary_logloss: 0.00674899
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[136]	valid_0's binary_logloss: 0.00676775
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[137]	valid_0's binary_logloss: 0.00678322
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[138]	valid_0's binary_logloss: 0.00677659
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[139]	valid_0's binary_logloss: 0.00674705
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[140]	valid_0's binary_logloss: 0.00675484
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[141]	valid_0's binary_logloss: 0.0066906
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[142]	valid_0's binary_logloss: 0.0066534
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[143]	valid_0's binary_logloss: 0.00662553
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[144]	valid_0's binary_logloss: 0.00658884
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[145]	valid_0's binary_logloss: 0.00655623
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[146]	valid_0's binary_logloss: 0.00656405
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[147]	valid_0's binary_logloss: 0.00657116
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[148]	valid_0's binary_logloss: 0.00654931
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[149]	valid_0's binary_logloss: 0.00653742
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[150]	valid_0's binary_logloss: 0.0065532
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[151]	valid_0's binary_logloss: 0.00656654
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[152]	valid_0's binary_logloss: 0.00658609
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[153]	valid_0's binary_logloss: 0.00658576
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[154]	valid_0's binary_logloss: 0.00659051
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[155]	valid_0's binary_logloss: 0.00659383
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[156]	valid_0's binary_logloss: 0.00657038
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[157]	valid_0's binary_logloss: 0.00658492
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[158]	valid_0's binary_logloss: 0.00659433
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[159]	valid_0's binary_logloss: 0.00660053
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[160]	valid_0's binary_logloss: 0.00662819
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[161]	valid_0's binary_logloss: 0.00662922
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[162]	valid_0's binary_logloss: 0.0066316
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[163]	valid_0's binary_logloss: 0.00663851
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[164]	valid_0's binary_logloss: 0.00664501
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[165]	valid_0's binary_logloss: 0.00665577
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[166]	valid_0's binary_logloss: 0.00666758
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[167]	valid_0's binary_logloss: 0.00666305
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[168]	valid_0's binary_logloss: 0.0066902
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[169]	valid_0's binary_logloss: 0.00667586
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[170]	valid_0's binary_logloss: 0.00668518
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[171]	valid_0's binary_logloss: 0.00653845
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[172]	valid_0's binary_logloss: 0.00643794
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[173]	valid_0's binary_logloss: 0.00638607
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[174]	valid_0's binary_logloss: 0.00631165
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[175]	valid_0's binary_logloss: 0.00625063
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[176]	valid_0's binary_logloss: 0.00623506
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[177]	valid_0's binary_logloss: 0.00623524

Trening klas:  88%|████████▊ | 439/500 [50:57<08:20,  8.20s/klasa, klasa=class_439, F1_klasy=0.8070, F1_macro=0.6361, drzewa=180]




Trening klas:  88%|████████▊ | 440/500 [50:57<07:50,  7.83s/klasa, klasa=class_439, F1_klasy=0.8070, F1_macro=0.6361, drzewa=180]

[205]	valid_0's binary_logloss: 0.00655055
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[206]	valid_0's binary_logloss: 0.00654843
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[207]	valid_0's binary_logloss: 0.00654751
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[208]	valid_0's binary_logloss: 0.00654303
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[209]	valid_0's binary_logloss: 0.00654738
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[210]	valid_0's binary_logloss: 0.00654357
[1]	valid_0's binary_logloss: 0.0164514
[2]	valid_0's binary_logloss: 0.0150267
[3]	valid_0's binary_logloss: 0.0125647
[4]	valid_0's binary_logloss: 0.0115069
[5]	valid_0's binary_logloss: 0.0107283
[6]	valid_0's binary_logloss: 0.00984968
[7]	valid_0's binary_logloss: 0.00930845
[8]	valid_0's binary_logloss: 0.00885279
[9]	valid_0's binary_logloss: 0.0083563
[10]	valid_0's binary_logloss: 0.00794514
[11]	valid_0's binary_logloss: 0.0075716
[12]	valid_0's binary_logloss: 0.00724002
[13]	valid_0's binary_logloss: 0.00690633
[14]	valid_0's binary_logloss: 0.00661982
[15]	valid_0's binary_logloss: 0.00635219
[16]	valid_0's binary_logloss: 0.0060799
[17]	valid_0's binary_logloss: 0.00582985
[18]	valid_0's binary_logloss: 0.00560351
[19]	valid_0's binary_logloss: 0.00540355
[20]	valid_0's binary_logloss: 0.0052102
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.00501465
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.00483094
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.00465759
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.00449596
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.00433891
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.00420365
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.00411202
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.00399739
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.00388794
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.00378156
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.0036655
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.00355396
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.00344921
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.00336024
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.00322291
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.00311316
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.00302765
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.0029273
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.00285202
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.00276207
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.00269575
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.00262966
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.00256151
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.00250388
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.00244571
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.0023771
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.00218734
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.00214347
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.0020927
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.00202165
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.00197093
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.00191246
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.00189483
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.0018728
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.00183838
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.00181688
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.00179747
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.00176755
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.00175105
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.00172199
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.0017056
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.00170506
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.00169115
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.00167705
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.00166392
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.00165144
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.00164207
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.00163324
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.00162661
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.00162384
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.00160578
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.00160956
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.00159314
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.00156848
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.00154686
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.00153843
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.00152417
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.00151777
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.0015096
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.00149806
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.00149933
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.00149806
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.00148603
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.00148787
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.0014901
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.00148331
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.00146961
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.00146169
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.0014562
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.00144654
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.0014374
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.00142889
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.00142419
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.00143351
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.0014406
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.0014477
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.00144582
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.00144644
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.00144547
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.00143818
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.00144983
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.0014508
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.0014623
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.00147312
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.00146945
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.00148184
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.00149865
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.00151399
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.00153133
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.00152806
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.00153299
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 0.00153835
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 0.00154627
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 0.00154906
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 0.00155549
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[116]	valid_0's binary_logloss: 0.00155752
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[117]	valid_0's binary_logloss: 0.00156047
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[118]	valid_0's binary_logloss: 0.00155687
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[119]	valid_0's binary_logloss: 0.00155927
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[120]	valid_0's binary_logloss: 0.00156145
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[121]	valid_0's binary_logloss: 0.00154602
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[122]	valid_0's binary_logloss: 0.00153428
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[123]	valid_0's binary_logloss: 0.00154587

Trening klas:  88%|████████▊ | 440/500 [51:01<07:50,  7.83s/klasa, klasa=class_440, F1_klasy=0.8571, F1_macro=0.6366, drzewa=93]




Trening klas:  88%|████████▊ | 441/500 [51:01<06:41,  6.80s/klasa, klasa=class_440, F1_klasy=0.8571, F1_macro=0.6366, drzewa=93]

[1]	valid_0's binary_logloss: 0.105516
[2]	valid_0's binary_logloss: 0.0615828
[3]	valid_0's binary_logloss: 0.0529069
[4]	valid_0's binary_logloss: 0.0487587
[5]	valid_0's binary_logloss: 0.0455961
[6]	valid_0's binary_logloss: 0.041961
[7]	valid_0's binary_logloss: 0.0398612
[8]	valid_0's binary_logloss: 0.0380819
[9]	valid_0's binary_logloss: 0.0362919
[10]	valid_0's binary_logloss: 0.0344814
[11]	valid_0's binary_logloss: 0.0326627
[12]	valid_0's binary_logloss: 0.0307628
[13]	valid_0's binary_logloss: 0.0286217
[14]	valid_0's binary_logloss: 0.0272559
[15]	valid_0's binary_logloss: 0.0257958
[16]	valid_0's binary_logloss: 0.0242552
[17]	valid_0's binary_logloss: 0.0231189
[18]	valid_0's binary_logloss: 0.0217676
[19]	valid_0's binary_logloss: 0.0208269
[20]	valid_0's binary_logloss: 0.0196768
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0188878
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0182122
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.0176196
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0170211
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.0164427
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.0157782
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.0151574
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.0145883
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.0141014
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.013711
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.0133404
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.0130191
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.0126619
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.0123626
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.0120885
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.0117049
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.0112952
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.0109303
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.0106714
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.0103644
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.0101
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.00987092
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.00963594
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.00943654
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.00924615
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.00904492
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.00884833
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.00867622
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.00848839
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.00831605
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.00817965
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.00802347
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.00788832
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.00776171
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.00766102
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.00754724
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.00745142
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.00730652
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.00720339
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.00712055
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.00698339
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.00685179
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.00672749
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.00661669
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.00653025
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.0064355
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.00637907
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.00628903
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.00623974
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.00619764
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.00608214
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.00603134
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.00597222
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.00588596
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.00583086
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.00576133
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.0056807
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.00565258
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.00560818
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.00553902
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.0055031
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.00546945
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.00543323
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.00540099
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.0053654
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.00528288
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.00521827
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.00520006
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.00511949
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.00508175
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.00508355
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.00505298
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.00506009
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.00502777
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.00500316
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.00496342
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.00495431
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.00491517
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.00490085
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.00489796
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.00492298
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.0049213
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.00492128
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.00491418
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.00492498
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.00487561
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.00489851
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.00485103
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.00480325
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.00478665
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.00479381
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 0.00481789
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 0.00484756
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 0.00482926
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 0.00484781
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[116]	valid_0's binary_logloss: 0.00487454
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[117]	valid_0's binary_logloss: 0.00487895
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[118]	valid_0's binary_logloss: 0.00489791
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[119]	valid_0's binary_logloss: 0.00490536
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[120]	valid_0's binary_logloss: 0.00492439
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[121]	valid_0's binary_logloss: 0.00491968
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[122]	valid_0's binary_logloss: 0.0048955
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[123]	valid_0's binary_logloss: 0.00492822
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[124]	valid_0's binary_logloss: 0.00490475
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[125]	valid_0's binary_logloss: 0.00490095
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[126]	valid_0's binary_logloss: 0.00492324
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[127]	valid_0's binary_logloss: 0.00491654
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[128]	valid_0's binary_logloss: 0.00490602
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[129]	valid_0's binary_logloss: 0.00492671
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[130]	valid_0's binary_logloss: 0.00492317
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[131]	valid_0's binary_logloss: 0.00493434
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[132]	valid_0's binary_logloss: 0.00494577
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[133]	valid_0's binary_logloss: 0.00494148
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[134]	valid_0's binary_logloss: 0.00495397
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[135]	valid_0's binary_logloss: 0.00496531
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[136]	valid_0's binary_logloss: 0.0049851
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[137]	valid_0's binary_logloss: 0.0049903
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[138]	valid_0's binary_logloss: 0.00501083
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

Trening klas:  88%|████████▊ | 441/500 [51:06<06:41,  6.80s/klasa, klasa=class_441, F1_klasy=0.4211, F1_macro=0.6361, drzewa=110]




Trening klas:  88%|████████▊ | 442/500 [51:06<05:58,  6.18s/klasa, klasa=class_441, F1_klasy=0.4211, F1_macro=0.6361, drzewa=110]

[139]	valid_0's binary_logloss: 0.00501836
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[140]	valid_0's binary_logloss: 0.00503933
[1]	valid_0's binary_logloss: 0.890608
[2]	valid_0's binary_logloss: 0.593999
[3]	valid_0's binary_logloss: 0.717099
[4]	valid_0's binary_logloss: 0.691653
[5]	valid_0's binary_logloss: 0.680472
[6]	valid_0's binary_logloss: 0.657588
[7]	valid_0's binary_logloss: 0.639428
[8]	valid_0's binary_logloss: 0.628528
[9]	valid_0's binary_logloss: 0.61825
[10]	valid_0's binary_logloss: 0.612931
[11]	valid_0's binary_logloss: 0.649203
[12]	valid_0's binary_logloss: 0.64382
[13]	valid_0's binary_logloss: 0.634129
[14]	valid_0's binary_logloss: 0.629305
[15]	valid_0's binary_logloss: 0.626818
[16]	valid_0's binary_logloss: 0.62353
[17]	valid_0's binary_logloss: 0.620217
[18]	valid_0's binary_logloss: 0.616427
[19]	valid_0's binary_logloss: 0.612906
[20]	valid_0's binary_logloss: 0.61152
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.603982
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.602903
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.597924
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.595808
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.593388
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.591011
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.586922
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.581184
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.578964
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.577197
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.574542
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.571533
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.568853
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.563091
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.559833
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.616999
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.605679
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.601033
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.598494
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.592434
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.603153
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.599196
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.597911
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.592103
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.592104
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.58925
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.585474
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.582904
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.582225
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.579651
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.576267
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.57428
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.572379
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.568424
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.565607
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.560087
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.557732
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.556508
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.556662
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.554762
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.55221
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.550677
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.548784
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.546553
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.544975
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.544155
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.542123
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.541237
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.538612
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.536536
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.533722
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.531704
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.530922
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.529069
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.526995
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.524529
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.523458
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.521828
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.515401
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.512338
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.51162
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.511008
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.511231
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.510319
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.509097
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.507194
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.504498
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.502188
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.499463
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.49864
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.51131
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.509318
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.505569
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.507736
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.507605
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.506908
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.504764
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.502907
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.501608
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.498285
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.497816
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.497089
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.495247
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.493967
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.493401
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 1.20338
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 1.17833
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.969533
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.58549
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.57878
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.573747
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 0.572268
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 0.570466
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 0.56799
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 0.568556
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[116]	valid_0's binary_logloss: 0.566966
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[117]	valid_0's binary_logloss: 0.562469
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[118]	valid_0's binary_logloss: 0.563356
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[119]	valid_0's binary_logloss: 0.562135
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[120]	valid_0's binary_logloss: 0.560865
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[121]	valid_0's binary_logloss: 0.557602
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[122]	valid_0's binary_logloss: 0.558514
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[123]	valid_0's binary_logloss: 0.558579
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[124]	valid_0's binary_logloss: 0.558133
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[125]	valid_0's binary_logloss: 0.555541
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[126]	valid_0's binary_logloss: 0.555843
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[127]	valid_0's binary_logloss: 0.5554
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[128]	valid_0's binary_logloss: 0.555365
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[129]	valid_0's binary_logloss: 0.556135
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

Trening klas:  88%|████████▊ | 442/500 [51:12<05:58,  6.18s/klasa, klasa=class_442, F1_klasy=0.3083, F1_macro=0.6354, drzewa=105]




Trening klas:  89%|████████▊ | 443/500 [51:12<05:55,  6.24s/klasa, klasa=class_442, F1_klasy=0.3083, F1_macro=0.6354, drzewa=105]

[130]	valid_0's binary_logloss: 0.555867
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[131]	valid_0's binary_logloss: 0.555896
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[132]	valid_0's binary_logloss: 0.554746
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[133]	valid_0's binary_logloss: 0.551812
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[134]	valid_0's binary_logloss: 0.549993
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[135]	valid_0's binary_logloss: 0.549007

[1]	valid_0's binary_logloss: 0.845386
[2]	valid_0's binary_logloss: 0.356703
[3]	valid_0's binary_logloss: 0.431645
[4]	valid_0's binary_logloss: 0.425969
[5]	valid_0's binary_logloss: 0.418977
[6]	valid_0's binary_logloss: 0.898708
[7]	valid_0's binary_logloss: 0.819026
[8]	valid_0's binary_logloss: 0.647529
[9]	valid_0's binary_logloss: 0.551688
[10]	valid_0's binary_logloss: 0.549994
[11]	valid_0's binary_logloss: 0.603032
[12]	valid_0's binary_logloss: 0.601775
[13]	valid_0's binary_logloss: 0.600322
[14]	valid_0's binary_logloss: 0.596805
[15]	valid_0's binary_logloss: 0.592251
[16]	valid_0's binary_logloss: 0.589693
[17]	valid_0's binary_logloss: 0.585361
[18]	valid_0's binary_logloss: 0.580401
[19]	valid_0's binary_logloss: 0.580353
[20]	valid_0's binary_logloss: 0.579252
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.57817
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.579766
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.579182
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.577397
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.57273
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.571506
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.569183
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.56587
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.564396
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.559106
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.55518
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

Trening klas:  89%|████████▊ | 443/500 [51:16<05:55,  6.24s/klasa, klasa=class_443, F1_klasy=0.2110, F1_macro=0.6344, drzewa=2]




Trening klas:  89%|████████▉ | 444/500 [51:16<05:04,  5.44s/klasa, klasa=class_443, F1_klasy=0.2110, F1_macro=0.6344, drzewa=2]

[32]	valid_0's binary_logloss: 0.552356
[1]	valid_0's binary_logloss: 0.00755577
[2]	valid_0's binary_logloss: 0.00603619
[3]	valid_0's binary_logloss: 0.00582571
[4]	valid_0's binary_logloss: 0.00557396
[5]	valid_0's binary_logloss: 0.00537058
[6]	valid_0's binary_logloss: 0.0067737
[7]	valid_0's binary_logloss: 0.00652975
[8]	valid_0's binary_logloss: 0.00627777
[9]	valid_0's binary_logloss: 0.00607119
[10]	valid_0's binary_logloss: 0.00585376
[11]	valid_0's binary_logloss: 0.00554812
[12]	valid_0's binary_logloss: 0.00535752
[13]	valid_0's binary_logloss: 0.00518168
[14]	valid_0's binary_logloss: 0.0050177
[15]	valid_0's binary_logloss: 0.00483939
[16]	valid_0's binary_logloss: 0.00468115
[17]	valid_0's binary_logloss: 0.0045434
[18]	valid_0's binary_logloss: 0.00441207
[19]	valid_0's binary_logloss: 0.00428086
[20]	valid_0's binary_logloss: 0.00416861
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.00405961
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.00394597
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.00384441
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.00374587
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.00364295
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.00354736
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.00345971
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.00337049
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.00330003
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.00321983
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.00314612
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.00307401
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.00300564
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.00293815
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.00287366
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.00281408
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.00274548
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.00269667
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.00264358
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.00258673
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.00253262
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.00249384
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.00246009
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.00241761
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.00239067
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.00234721
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.00231998
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.00228168
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.00226297
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.00224173
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.00220741
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.002188
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.00216064
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.00214599
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.00213123
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.00211675
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.00210493
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.00209438
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.00208504
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.00207731
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.00205477
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.0020393
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.00201906
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.00199994
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.00199713
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.00198103
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.00196606
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.00195192
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.00193858
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.00192599
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.00191894
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.0019098
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.0018994
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.00189054
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.00187734
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.00187181
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.00186338
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.00185777
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.0018528
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.00184813
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.00184941
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.00184849
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.00184241
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.00183652
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.00184724
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.00185445
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.00186169
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.00186726
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.00187501
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.00188229
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.00187887
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.00187503
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.00186596
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.00186268
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.00186751
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.00186448
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.0018651
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.00186721
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.0018661
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.00186986
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.00187398
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.00187494
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.00187352
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.00188123
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.00188561
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.00188536
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.00189232
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.00189267
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.00190007
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.00190957
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.00191589
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 0.00192209
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 0.00192847
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 0.00192834

Trening klas:  89%|████████▉ | 444/500 [51:20<05:04,  5.44s/klasa, klasa=class_444, F1_klasy=0.0000, F1_macro=0.6330, drzewa=84]




Trening klas:  89%|████████▉ | 445/500 [51:20<04:37,  5.05s/klasa, klasa=class_444, F1_klasy=0.0000, F1_macro=0.6330, drzewa=84]

[1]	valid_0's binary_logloss: 0.0347198
[2]	valid_0's binary_logloss: 0.025126
[3]	valid_0's binary_logloss: 0.0232246
[4]	valid_0's binary_logloss: 0.0223073
[5]	valid_0's binary_logloss: 0.0216132
[6]	valid_0's binary_logloss: 0.0361227
[7]	valid_0's binary_logloss: 0.0355143
[8]	valid_0's binary_logloss: 0.0335617
[9]	valid_0's binary_logloss: 0.0305291
[10]	valid_0's binary_logloss: 0.0240752
[11]	valid_0's binary_logloss: 0.0204119
[12]	valid_0's binary_logloss: 0.0198125
[13]	valid_0's binary_logloss: 0.0193776
[14]	valid_0's binary_logloss: 0.0190002
[15]	valid_0's binary_logloss: 0.0186554
[16]	valid_0's binary_logloss: 0.0181236
[17]	valid_0's binary_logloss: 0.0177598
[18]	valid_0's binary_logloss: 0.0174549
[19]	valid_0's binary_logloss: 0.0170826
[20]	valid_0's binary_logloss: 0.0167094
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0163857
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0161261
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.0158464
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0156444
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.0153985
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.0151563
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.0149529
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.0147151
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.0144139
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.0141546
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.0139495
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.0137879
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.0135933
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.0134345
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.0132742
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.0131536
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.0129484
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.0128005
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.0126461
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.0125006
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.0123666
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.0122365
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.0120954
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.0119396
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.0117943
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.0116555
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.0115032
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.0114128
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.011303
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.0111805
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.0110414
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.0109436
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.0108528
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.0107085
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.0106098
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.0105108
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.0103864
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.0103124
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.0102385
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.0101231
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.0100419
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.00992832
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.00981494
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.00970495
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.00958903
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.00949398
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.00941554
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.00933062
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.00929304
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.00920944
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.00910911
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.00905983
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.00897109
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.00888649
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.00884678
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.00877581
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.00867654
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.00864376
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.00854711
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.00850229
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.00840881
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.00834487
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.00826715
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.00822391
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.00818647
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.00810147
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.00801837
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.00793893
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.00788579
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.00781307
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.0077459
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.00768245
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.00761439
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.00754616
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.00748663
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.0074665
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.00741003
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.0073444
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.00730331
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.00723256
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.00721694
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.00718091
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.00715079
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.00712721
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.00709505
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.00705669
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.00700185
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.006956
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.00691717
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.0068761
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.0068178
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 0.00679399
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 0.00675926
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 0.00673523
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 0.00673306
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[116]	valid_0's binary_logloss: 0.00669283
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[117]	valid_0's binary_logloss: 0.00666552
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[118]	valid_0's binary_logloss: 0.00663893
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[119]	valid_0's binary_logloss: 0.00661627
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[120]	valid_0's binary_logloss: 0.00660461
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[121]	valid_0's binary_logloss: 0.00656446
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[122]	valid_0's binary_logloss: 0.00654495
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[123]	valid_0's binary_logloss: 0.00652481
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[124]	valid_0's binary_logloss: 0.00649256
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[125]	valid_0's binary_logloss: 0.00646273
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[126]	valid_0's binary_logloss: 0.0064381
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[127]	valid_0's binary_logloss: 0.00640326
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[128]	valid_0's binary_logloss: 0.00637915
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[129]	valid_0's binary_logloss: 0.00634561
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[130]	valid_0's binary_logloss: 0.00633547
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[131]	valid_0's binary_logloss: 0.00630422
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[132]	valid_0's binary_logloss: 0.00627325
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[133]	valid_0's binary_logloss: 0.00625557
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[134]	valid_0's binary_logloss: 0.0062249
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[135]	valid_0's binary_logloss: 0.00621832
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[136]	valid_0's binary_logloss: 0.0061926
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[137]	valid_0's binary_logloss: 0.00617571
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[138]	valid_0's binary_logloss: 0.00616119
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[139]	valid_0's binary_logloss: 0.0061484
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[140]	valid_0's binary_logloss: 0.00614398
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[141]	valid_0's binary_logloss: 0.00615055
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[142]	valid_0's binary_logloss: 0.00613574
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[143]	valid_0's binary_logloss: 0.00613529
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[144]	valid_0's binary_logloss: 0.00613763
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[145]	valid_0's binary_logloss: 0.00613859
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[146]	valid_0's binary_logloss: 0.00613915
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[147]	valid_0's binary_logloss: 0.00615038
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[148]	valid_0's binary_logloss: 0.00614558
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[149]	valid_0's binary_logloss: 0.00614097
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[150]	valid_0's binary_logloss: 0.00613372
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[151]	valid_0's binary_logloss: 0.00612048
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[152]	valid_0's binary_logloss: 0.0061197
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[153]	valid_0's binary_logloss: 0.00611861
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[154]	valid_0's binary_logloss: 0.00609764
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[155]	valid_0's binary_logloss: 0.00608623
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[156]	valid_0's binary_logloss: 0.00608461
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[157]	valid_0's binary_logloss: 0.00606226
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[158]	valid_0's binary_logloss: 0.00605662
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[159]	valid_0's binary_logloss: 0.00603744
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[160]	valid_0's binary_logloss: 0.00601965
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[161]	valid_0's binary_logloss: 0.00601612
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[162]	valid_0's binary_logloss: 0.00601413
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[163]	valid_0's binary_logloss: 0.00602227
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[164]	valid_0's binary_logloss: 0.00603135
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[165]	valid_0's binary_logloss: 0.0060378
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[166]	valid_0's binary_logloss: 0.00604546
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[167]	valid_0's binary_logloss: 0.00604001
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[168]	valid_0's binary_logloss: 0.00602586
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[169]	valid_0's binary_logloss: 0.00602466
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[170]	valid_0's binary_logloss: 0.00601349
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[171]	valid_0's binary_logloss: 0.00600809
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[172]	valid_0's binary_logloss: 0.00600869
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[173]	valid_0's binary_logloss: 0.00601069
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[174]	valid_0's binary_logloss: 0.00601438
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[175]	valid_0's binary_logloss: 0.00601045
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[176]	valid_0's binary_logloss: 0.00601013
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[177]	valid_0's binary_logloss: 0.00600891
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[178]	valid_0's binary_logloss: 0.00600446
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[179]	valid_0's binary_logloss: 0.00600796
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[180]	valid_0's binary_logloss: 0.00599978
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[181]	valid_0's binary_logloss: 0.00599528
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[182]	valid_0's binary_logloss: 0.00598441
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[183]	valid_0's binary_logloss: 0.00597474
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

Trening klas:  89%|████████▉ | 445/500 [51:28<04:37,  5.05s/klasa, klasa=class_445, F1_klasy=0.8539, F1_macro=0.6335, drzewa=250]




Trening klas:  89%|████████▉ | 446/500 [51:28<05:26,  6.04s/klasa, klasa=class_445, F1_klasy=0.8539, F1_macro=0.6335, drzewa=250]

[1]	valid_0's binary_logloss: 0.0113232
[2]	valid_0's binary_logloss: 0.0111457
[3]	valid_0's binary_logloss: 0.0109983
[4]	valid_0's binary_logloss: 0.010866
[5]	valid_0's binary_logloss: 0.0106925
[6]	valid_0's binary_logloss: 0.0105458
[7]	valid_0's binary_logloss: 0.0104263
[8]	valid_0's binary_logloss: 0.0102984
[9]	valid_0's binary_logloss: 0.0101863
[10]	valid_0's binary_logloss: 0.0100694
[11]	valid_0's binary_logloss: 0.00998808
[12]	valid_0's binary_logloss: 0.00984973
[13]	valid_0's binary_logloss: 0.00978864
[14]	valid_0's binary_logloss: 0.00972559
[15]	valid_0's binary_logloss: 0.0096719
[16]	valid_0's binary_logloss: 0.00956159
[17]	valid_0's binary_logloss: 0.00944862
[18]	valid_0's binary_logloss: 0.00939638
[19]	valid_0's binary_logloss: 0.00929555
[20]	valid_0's binary_logloss: 0.009193
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.00915283
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.00912629
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.00908737
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.00906713
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.00905274
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.00902593
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.00896074
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.0089249
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.00890451
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.00885909
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.008803
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.00881331
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.00879858
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.00879666
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.00875088
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.00876776
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.00871353
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.00871799
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.00873662
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.00876208
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.00872333
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.0087294
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.00875257
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.00871773
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.00870488
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.00868619
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.00859006
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.00857972
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.00857047
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.0085572
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.00851317
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.00847147
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.00846434
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.00842529
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.00838753
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.00839935
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.00835937
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.00837157
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.00839275
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.00835981
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.008348
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.00831993
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.00831806
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.00829104
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.00826472
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.00828935
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.00831451
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.00834016
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.00835832
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.00838458
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.00839042
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.00839387
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.00839724
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.00841421
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.00841813
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.00840184
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.00842702
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.00839351
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.00835798
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.00833212
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.00833844
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.00833195
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.00833148
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.00834081
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.00832386
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.00830257
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.00828596
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.00829005
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.00826956
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.00824515
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.00825713
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.00827683
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.0083036
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.00833136
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.00835469
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.00836418
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.00840132
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.00841081
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.00842582
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.00844343
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.00846171
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.00847661
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.00849426
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.00849961
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.00852038
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.00851327
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.0085446
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.0085009
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.00850188
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.0085379
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.00854435
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 0.00855923
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 0.00856538
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 0.00858453
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 0.00863004
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[116]	valid_0's binary_logloss: 0.00862704
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[117]	valid_0's binary_logloss: 0.00862945
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[118]	valid_0's binary_logloss: 0.00861994
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[119]	valid_0's binary_logloss: 0.00865419
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

Trening klas:  89%|████████▉ | 446/500 [51:32<05:26,  6.04s/klasa, klasa=class_446, F1_klasy=0.8727, F1_macro=0.6341, drzewa=90]




Trening klas:  89%|████████▉ | 447/500 [51:32<04:50,  5.48s/klasa, klasa=class_446, F1_klasy=0.8727, F1_macro=0.6341, drzewa=90]

[120]	valid_0's binary_logloss: 0.00865245
[1]	valid_0's binary_logloss: 1.16403
[2]	valid_0's binary_logloss: 0.205791
[3]	valid_0's binary_logloss: 0.287184
[4]	valid_0's binary_logloss: 0.282531
[5]	valid_0's binary_logloss: 0.279326
[6]	valid_0's binary_logloss: 0.891865
[7]	valid_0's binary_logloss: 0.895343
[8]	valid_0's binary_logloss: 0.488847
[9]	valid_0's binary_logloss: 0.362918
[10]	valid_0's binary_logloss: 0.362368
[11]	valid_0's binary_logloss: 0.361059
[12]	valid_0's binary_logloss: 0.3597
[13]	valid_0's binary_logloss: 0.358787
[14]	valid_0's binary_logloss: 0.357439
[15]	valid_0's binary_logloss: 0.356513
[16]	valid_0's binary_logloss: 0.354623
[17]	valid_0's binary_logloss: 0.352611
[18]	valid_0's binary_logloss: 0.350795
[19]	valid_0's binary_logloss: 0.349037
[20]	valid_0's binary_logloss: 0.34788

Trening klas:  89%|████████▉ | 447/500 [51:35<04:50,  5.48s/klasa, klasa=class_447, F1_klasy=0.3482, F1_macro=0.6334, drzewa=2]




Trening klas:  90%|████████▉ | 448/500 [51:35<04:06,  4.74s/klasa, klasa=class_447, F1_klasy=0.3482, F1_macro=0.6334, drzewa=2]

[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.346765
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.345743
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.343423
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.341737
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.340594
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.340114
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.338882
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.33773
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.335941
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.33472
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.334045
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.333545
[1]	valid_0's binary_logloss: 0.0164625
[2]	valid_0's binary_logloss: 0.0154546
[3]	valid_0's binary_logloss: 0.015075
[4]	valid_0's binary_logloss: 0.0146128
[5]	valid_0's binary_logloss: 0.0142853
[6]	valid_0's binary_logloss: 0.0138063
[7]	valid_0's binary_logloss: 0.0135304
[8]	valid_0's binary_logloss: 0.0131925
[9]	valid_0's binary_logloss: 0.0127445
[10]	valid_0's binary_logloss: 0.012335
[11]	valid_0's binary_logloss: 0.0120828
[12]	valid_0's binary_logloss: 0.0118381
[13]	valid_0's binary_logloss: 0.0115859
[14]	valid_0's binary_logloss: 0.0114212
[15]	valid_0's binary_logloss: 0.0112537
[16]	valid_0's binary_logloss: 0.01106
[17]	valid_0's binary_logloss: 0.0107943
[18]	valid_0's binary_logloss: 0.0106019
[19]	valid_0's binary_logloss: 0.0104267
[20]	valid_0's binary_logloss: 0.0102275
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0101239
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.00994143
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.00982049
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.00968722
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.00954462
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.00945915
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.00937688
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.00928133
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.00920093
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.00911721
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.00904062
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.00897182
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.00889629
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.00883425
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.00875861
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.00868563
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.00860892
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.00850608
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.00843172
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.00838061
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.00833712
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.00828314
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.00823803
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.00823925
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.00820042
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.00818509
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.00816184
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.00808388
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.00801153
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.00794539
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.00791139
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.00789291
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.0078306
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.00778095
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.00773431
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.00766779
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.00759724
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.00754988
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.00749619
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.00744686
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.00744093
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.00744014
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.00743552
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.0074549
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.00744189
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.00738852
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.00734635
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.00732463
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.00731309
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.00728522
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.0073084
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.00735154
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.00736788
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.00740695
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.00742824
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.00744065
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.00746624
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.00746738
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.00748069
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.00748721
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.0074987
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.00751808
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.00753183
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.00754485
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.00756799
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.0075971
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.00762671
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.0076187
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.0076465
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.00766824
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.00763463
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.00766247
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.00767434
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.00771714
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.00772622
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.00773811
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.00776081
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.00777478
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.00779289
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.00779865

Trening klas:  90%|████████▉ | 448/500 [51:40<04:06,  4.74s/klasa, klasa=class_448, F1_klasy=0.4571, F1_macro=0.6330, drzewa=70]




Trening klas:  90%|████████▉ | 449/500 [51:40<03:51,  4.53s/klasa, klasa=class_448, F1_klasy=0.4571, F1_macro=0.6330, drzewa=70]

[1]	valid_0's binary_logloss: 0.109345
[2]	valid_0's binary_logloss: 0.0763954
[3]	valid_0's binary_logloss: 0.0676375
[4]	valid_0's binary_logloss: 0.0638704
[5]	valid_0's binary_logloss: 0.0600891
[6]	valid_0's binary_logloss: 0.0570902
[7]	valid_0's binary_logloss: 0.05509
[8]	valid_0's binary_logloss: 0.0512835
[9]	valid_0's binary_logloss: 0.0494355
[10]	valid_0's binary_logloss: 0.0484067
[11]	valid_0's binary_logloss: 0.046964
[12]	valid_0's binary_logloss: 0.0462384
[13]	valid_0's binary_logloss: 0.0454823
[14]	valid_0's binary_logloss: 0.0450382
[15]	valid_0's binary_logloss: 0.043967
[16]	valid_0's binary_logloss: 0.0429526
[17]	valid_0's binary_logloss: 0.0421151
[18]	valid_0's binary_logloss: 0.0414627
[19]	valid_0's binary_logloss: 0.0408042
[20]	valid_0's binary_logloss: 0.0401967
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0396145
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.039081
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.0384582
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.037905
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.0373096
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.0368308
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.0363777
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.0359167
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.03554
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.0351341
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.0347963
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.0345625
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.0343134
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.0340801
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.0337874
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.0334759
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.0331229
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.0328207
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.0325226
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.0322325
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.0320734
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.0318301
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.0316133
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.0314259
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.0312055
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.0309401
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.0305842
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.0303074
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.0300048
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.029751
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.0295055
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.0293261
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.0291693
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.0289142
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.0287008
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.0284704
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.0282724
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.028028
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.0278261
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.0276295
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.0273859
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.0271633
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.026975
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.0267267
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.0265234
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.0262888
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.0260397
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.0258733
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.0256668
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.0255206
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.0253226
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.025138
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.0249673
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.0247914
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.0246511
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.0245016
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.0243561
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.0241545
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.0240456
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.0238526
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.0237114
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.0235106
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.0233547
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.0231979
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.023046
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.0229331
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.0228211
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.0227086
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.0226163
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.0225366
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.0223544
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.0221912
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.0219932
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.0218271
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.0216765
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.0215074
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.0213609
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.0212347
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.021101
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.0209477
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.0208176
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.0206843
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.0205252
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.0203643
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.0202406
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.0201345
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.0200636
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.0199587
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.0198996
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.0198278
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.0196518
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 0.0194846
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 0.0194197
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 0.0193491
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 0.0192526
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[116]	valid_0's binary_logloss: 0.0191208
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[117]	valid_0's binary_logloss: 0.0190452
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[118]	valid_0's binary_logloss: 0.0189958
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[119]	valid_0's binary_logloss: 0.0189256
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[120]	valid_0's binary_logloss: 0.0188336
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[121]	valid_0's binary_logloss: 0.0186941
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[122]	valid_0's binary_logloss: 0.0185924
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[123]	valid_0's binary_logloss: 0.0184676
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[124]	valid_0's binary_logloss: 0.0184232
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[125]	valid_0's binary_logloss: 0.0183286
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[126]	valid_0's binary_logloss: 0.0182296
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[127]	valid_0's binary_logloss: 0.0181314
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[128]	valid_0's binary_logloss: 0.0180565
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[129]	valid_0's binary_logloss: 0.0179884
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[130]	valid_0's binary_logloss: 0.0179729
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[131]	valid_0's binary_logloss: 0.0178417
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[132]	valid_0's binary_logloss: 0.017797
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[133]	valid_0's binary_logloss: 0.0177422
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[134]	valid_0's binary_logloss: 0.0177151
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[135]	valid_0's binary_logloss: 0.0176674
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[136]	valid_0's binary_logloss: 0.0175811
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[137]	valid_0's binary_logloss: 0.0175115
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[138]	valid_0's binary_logloss: 0.0174032
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[139]	valid_0's binary_logloss: 0.0173218
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[140]	valid_0's binary_logloss: 0.0172187
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[141]	valid_0's binary_logloss: 0.0171827
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[142]	valid_0's binary_logloss: 0.0171407
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[143]	valid_0's binary_logloss: 0.0170753
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[144]	valid_0's binary_logloss: 0.0170266
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[145]	valid_0's binary_logloss: 0.0169769
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[146]	valid_0's binary_logloss: 0.0169407
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[147]	valid_0's binary_logloss: 0.0169021
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[148]	valid_0's binary_logloss: 0.016901
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[149]	valid_0's binary_logloss: 0.0168366
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[150]	valid_0's binary_logloss: 0.016818
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[151]	valid_0's binary_logloss: 0.0167327
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[152]	valid_0's binary_logloss: 0.0166921
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[153]	valid_0's binary_logloss: 0.0166205
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[154]	valid_0's binary_logloss: 0.0165113
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[155]	valid_0's binary_logloss: 0.0164486
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[156]	valid_0's binary_logloss: 0.0164127
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[157]	valid_0's binary_logloss: 0.0163786
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[158]	valid_0's binary_logloss: 0.0163568
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[159]	valid_0's binary_logloss: 0.0163422
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[160]	valid_0's binary_logloss: 0.0163399
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[161]	valid_0's binary_logloss: 0.0163224
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[162]	valid_0's binary_logloss: 0.0162945
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[163]	valid_0's binary_logloss: 0.0162951
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[164]	valid_0's binary_logloss: 0.016303
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[165]	valid_0's binary_logloss: 0.0162576
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[166]	valid_0's binary_logloss: 0.0162626
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[167]	valid_0's binary_logloss: 0.0162275
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[168]	valid_0's binary_logloss: 0.016189
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[169]	valid_0's binary_logloss: 0.0161692
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[170]	valid_0's binary_logloss: 0.0161441
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[171]	valid_0's binary_logloss: 0.0160909
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[172]	valid_0's binary_logloss: 0.0160447
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[173]	valid_0's binary_logloss: 0.016022
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[174]	valid_0's binary_logloss: 0.0159845
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[175]	valid_0's binary_logloss: 0.0159504
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[176]	valid_0's binary_logloss: 0.0159704
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[177]	valid_0's binary_logloss: 0.0159364
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[178]	valid_0's binary_logloss: 0.0159224
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[179]	valid_0's binary_logloss: 0.0158844
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[180]	valid_0's binary_logloss: 0.0158758
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[181]	valid_0's binary_logloss: 0.0158334
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[182]	valid_0's binary_logloss: 0.0157883
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[183]	valid_0's binary_logloss: 0.0157433
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[184]	valid_0's binary_logloss: 0.0156982
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

Trening klas:  90%|████████▉ | 449/500 [51:46<03:51,  4.53s/klasa, klasa=class_449, F1_klasy=0.6923, F1_macro=0.6332, drzewa=300]




Trening klas:  90%|█████████ | 450/500 [51:46<04:22,  5.26s/klasa, klasa=class_449, F1_klasy=0.6923, F1_macro=0.6332, drzewa=300]

[1]	valid_0's binary_logloss: 0.40778
[2]	valid_0's binary_logloss: 0.272603
[3]	valid_0's binary_logloss: 0.418528
[4]	valid_0's binary_logloss: 0.410738
[5]	valid_0's binary_logloss: 0.397221
[6]	valid_0's binary_logloss: 0.456254
[7]	valid_0's binary_logloss: 0.452248
[8]	valid_0's binary_logloss: 0.442046
[9]	valid_0's binary_logloss: 0.440059
[10]	valid_0's binary_logloss: 0.435682
[11]	valid_0's binary_logloss: 0.429958
[12]	valid_0's binary_logloss: 0.426023
[13]	valid_0's binary_logloss: 0.422044
[14]	valid_0's binary_logloss: 0.418006
[15]	valid_0's binary_logloss: 0.415574
[16]	valid_0's binary_logloss: 0.411884
[17]	valid_0's binary_logloss: 0.408195
[18]	valid_0's binary_logloss: 0.391174
[19]	valid_0's binary_logloss: 0.38684
[20]	valid_0's binary_logloss: 0.383487
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.42169
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.418346
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.415157
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.412214
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.40859
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.405899
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.402655
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.40042
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.397888

Trening klas:  90%|█████████ | 450/500 [51:50<04:22,  5.26s/klasa, klasa=class_450, F1_klasy=0.2705, F1_macro=0.6323, drzewa=2]




Trening klas:  90%|█████████ | 451/500 [51:50<03:51,  4.73s/klasa, klasa=class_450, F1_klasy=0.2705, F1_macro=0.6323, drzewa=2]

[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.397001
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.395491
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.393238
[1]	valid_0's binary_logloss: 0.0524869
[2]	valid_0's binary_logloss: 0.0415115
[3]	valid_0's binary_logloss: 0.0379597
[4]	valid_0's binary_logloss: 0.0344673
[5]	valid_0's binary_logloss: 0.0334548
[6]	valid_0's binary_logloss: 0.0323544
[7]	valid_0's binary_logloss: 0.0313832
[8]	valid_0's binary_logloss: 0.0305654
[9]	valid_0's binary_logloss: 0.0298109
[10]	valid_0's binary_logloss: 0.0293606
[11]	valid_0's binary_logloss: 0.0290684
[12]	valid_0's binary_logloss: 0.0287352
[13]	valid_0's binary_logloss: 0.0284773
[14]	valid_0's binary_logloss: 0.028229
[15]	valid_0's binary_logloss: 0.0279633
[16]	valid_0's binary_logloss: 0.0277472
[17]	valid_0's binary_logloss: 0.0275388
[18]	valid_0's binary_logloss: 0.0273332
[19]	valid_0's binary_logloss: 0.026822
[20]	valid_0's binary_logloss: 0.0263612
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0262364
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0260749
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.025814
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0256237
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.0255058
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.0253313
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.0251742
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.024987
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.0246829
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.0244024
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.0241341
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.0239837
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.0238702
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.0237865
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.0237502
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.0211275
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.0209654
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.0207096
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.0205941
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.0203792
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.0203726
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.0204196
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.0204495
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.0205565
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.0206125
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.0204513
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.0202502
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.0202837
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.02034
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.0203566
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.0203096
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.0202762
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.0202915
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.0202582
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.0202241
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.0201068
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.01997
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.0199314
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.0199765
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.0200548
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.0201169
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.020153
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.020179
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.0202332
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.0202747
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.0203226
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.0202567
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.0201362
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.0200379
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.0200444
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.0200131
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.0198316
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.0197795
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.0197358
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.0197557
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.0196919
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.0197274
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.0195508
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.0193336
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.0191565
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.0193
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.0194319
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.0195729
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.0197268
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.0198797
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.019943
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.0199535
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.0200086
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.0200687
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.0201503
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.0202472
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.0203136
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.0203132
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.0203866
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.0205006
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.0204367
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.0205258
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.0206036
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.0206719
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.0207022
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.0207155
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.0207237
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.0207345
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.020763
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.0207939
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.0208778
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.0210099
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

Trening klas:  90%|█████████ | 451/500 [51:55<03:51,  4.73s/klasa, klasa=class_451, F1_klasy=0.7434, F1_macro=0.6326, drzewa=80]




Trening klas:  90%|█████████ | 452/500 [51:55<03:50,  4.79s/klasa, klasa=class_451, F1_klasy=0.7434, F1_macro=0.6326, drzewa=80]

[108]	valid_0's binary_logloss: 0.0211335
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.0211887
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.0213268
[1]	valid_0's binary_logloss: 0.0930672
[2]	valid_0's binary_logloss: 0.0586656
[3]	valid_0's binary_logloss: 0.0525117
[4]	valid_0's binary_logloss: 0.0486391
[5]	valid_0's binary_logloss: 0.0451042
[6]	valid_0's binary_logloss: 0.0556673
[7]	valid_0's binary_logloss: 0.052472
[8]	valid_0's binary_logloss: 0.0505379
[9]	valid_0's binary_logloss: 0.0489066
[10]	valid_0's binary_logloss: 0.0476344
[11]	valid_0's binary_logloss: 0.046748
[12]	valid_0's binary_logloss: 0.0460952
[13]	valid_0's binary_logloss: 0.0453269
[14]	valid_0's binary_logloss: 0.044697
[15]	valid_0's binary_logloss: 0.0441784
[16]	valid_0's binary_logloss: 0.0425554
[17]	valid_0's binary_logloss: 0.0420922
[18]	valid_0's binary_logloss: 0.0416727
[19]	valid_0's binary_logloss: 0.041153
[20]	valid_0's binary_logloss: 0.040782
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0401792
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0396665
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.039281
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.038983
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.0386546
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.0383068
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.0380162
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.0377423
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.0375382
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.0374183
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.0371747
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.0369272
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.0366181
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.0363038
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.0359748
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.0356945
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.0353909
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.0351396
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.0348554
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.0346171
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.0343169
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.0339755
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.0336231
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.03346
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.0332182
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.0331538
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.0330027
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.0329148
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.0328195
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.0327214
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.0325344
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.0323404
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.0322718
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.0322164
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.0322509
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.0321152
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.0320553
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.0319253
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.0317443
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.031628
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.0316418
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.0316359
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.0315137
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.0314243
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.0313238
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.0312474
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.0311755
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.031121
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.0310437
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.0310258
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.0313182
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.0312942
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.0313199
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.0313493
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.0313497
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.0312487
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.031102
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.030933
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.0308222
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.0306882
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.0306924
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.0306202
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.0305703
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.0304978
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.0303844
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.0303411
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.0302839
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.0301852
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.0300863
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.0301125
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.0300826
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.0300453
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.0299298
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.029877
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.029837
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.0297869
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.0297532
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.0297528
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.0296891
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.0296411
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.0298342
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.0301345
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.0303054
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.0305296
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.0306929
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.0305764
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.0304552
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.0303458
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.030277
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.0303221
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.0304
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 0.0304712
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 0.0301609
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 0.0302789
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 0.03007
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[116]	valid_0's binary_logloss: 0.0300431
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[117]	valid_0's binary_logloss: 0.0300156
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[118]	valid_0's binary_logloss: 0.0300347
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[119]	valid_0's binary_logloss: 0.0300758
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[120]	valid_0's binary_logloss: 0.0299548
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[121]	valid_0's binary_logloss: 0.0299432
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[122]	valid_0's binary_logloss: 0.0298888
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[123]	valid_0's binary_logloss: 0.0297348
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[124]	valid_0's binary_logloss: 0.0291722
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[125]	valid_0's binary_logloss: 0.0288072
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[126]	valid_0's binary_logloss: 0.0286018
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[127]	valid_0's binary_logloss: 0.0284822
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[128]	valid_0's binary_logloss: 0.0283105
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[129]	valid_0's binary_logloss: 0.0282319
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[130]	valid_0's binary_logloss: 0.0281491
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[131]	valid_0's binary_logloss: 0.0281936
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[132]	valid_0's binary_logloss: 0.028131
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[133]	valid_0's binary_logloss: 0.0281598
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[134]	valid_0's binary_logloss: 0.0281664
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[135]	valid_0's binary_logloss: 0.0281637
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[136]	valid_0's binary_logloss: 0.0281986
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[137]	valid_0's binary_logloss: 0.0282484
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[138]	valid_0's binary_logloss: 0.028325
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[139]	valid_0's binary_logloss: 0.0282638
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[140]	valid_0's binary_logloss: 0.0281911
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[141]	valid_0's binary_logloss: 0.0281845
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[142]	valid_0's binary_logloss: 0.0281904
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[143]	valid_0's binary_logloss: 0.0281891
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[144]	valid_0's binary_logloss: 0.0281622
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[145]	valid_0's binary_logloss: 0.0281282
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[146]	valid_0's binary_logloss: 0.0282368
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[147]	valid_0's binary_logloss: 0.0283666
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[148]	valid_0's binary_logloss: 0.0283737
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[149]	valid_0's binary_logloss: 0.0283199
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[150]	valid_0's binary_logloss: 0.0283376
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[151]	valid_0's binary_logloss: 0.0283288
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[152]	valid_0's binary_logloss: 0.0282909
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[153]	valid_0's binary_logloss: 0.0280189
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[154]	valid_0's binary_logloss: 0.027784
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[155]	valid_0's binary_logloss: 0.0275636
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[156]	valid_0's binary_logloss: 0.0276142
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[157]	valid_0's binary_logloss: 0.0276748
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[158]	valid_0's binary_logloss: 0.0276214
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[159]	valid_0's binary_logloss: 0.0275953
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[160]	valid_0's binary_logloss: 0.0276268
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[161]	valid_0's binary_logloss: 0.0277606
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[162]	valid_0's binary_logloss: 0.027843
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[163]	valid_0's binary_logloss: 0.0281348
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[164]	valid_0's binary_logloss: 0.0283135
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[165]	valid_0's binary_logloss: 0.0283563
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[166]	valid_0's binary_logloss: 0.028308
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[167]	valid_0's binary_logloss: 0.0282794
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[168]	valid_0's binary_logloss: 0.0283495
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[169]	valid_0's binary_logloss: 0.0282608
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[170]	valid_0's binary_logloss: 0.0282241
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[171]	valid_0's binary_logloss: 0.0282864
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[172]	valid_0's binary_logloss: 0.0282654
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[173]	valid_0's binary_logloss: 0.0283163
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[174]	valid_0's binary_logloss: 0.0283743
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[175]	valid_0's binary_logloss: 0.0283062
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[176]	valid_0's binary_logloss: 0.028338
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[177]	valid_0's binary_logloss: 0.0282258
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[178]	valid_0's binary_logloss: 0.0281511
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[179]	valid_0's binary_logloss: 0.0282338
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[180]	valid_0's binary_logloss: 0.0282929
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

Trening klas:  90%|█████████ | 452/500 [52:03<03:50,  4.79s/klasa, klasa=class_452, F1_klasy=0.5474, F1_macro=0.6324, drzewa=155]




Trening klas:  91%|█████████ | 453/500 [52:03<04:29,  5.73s/klasa, klasa=class_452, F1_klasy=0.5474, F1_macro=0.6324, drzewa=155]

[181]	valid_0's binary_logloss: 0.0282683
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[182]	valid_0's binary_logloss: 0.0283541
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[183]	valid_0's binary_logloss: 0.0284698
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[184]	valid_0's binary_logloss: 0.0284912
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[185]	valid_0's binary_logloss: 0.0285752
[1]	valid_0's binary_logloss: 0.118149
[2]	valid_0's binary_logloss: 0.0639983
[3]	valid_0's binary_logloss: 0.0579427
[4]	valid_0's binary_logloss: 0.0539082
[5]	valid_0's binary_logloss: 0.050433
[6]	valid_0's binary_logloss: 0.0478991
[7]	valid_0's binary_logloss: 0.0457101
[8]	valid_0's binary_logloss: 0.043546
[9]	valid_0's binary_logloss: 0.0417165
[10]	valid_0's binary_logloss: 0.0401769
[11]	valid_0's binary_logloss: 0.0387268
[12]	valid_0's binary_logloss: 0.0376446
[13]	valid_0's binary_logloss: 0.0366475
[14]	valid_0's binary_logloss: 0.0355896
[15]	valid_0's binary_logloss: 0.0345649
[16]	valid_0's binary_logloss: 0.0336666
[17]	valid_0's binary_logloss: 0.0328677
[18]	valid_0's binary_logloss: 0.0320589
[19]	valid_0's binary_logloss: 0.0312413
[20]	valid_0's binary_logloss: 0.0304741
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0296974
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0288766
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.0281357
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0274142
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.0267683
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.0259844
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.0253974
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.0249102
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.0241992
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.0236282
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.0230194
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.0223935
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.0218747
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.0215381
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.0210365
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.0206279
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.0203304
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.0200374
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.0197184
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.0194509
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.0192305
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.0189188
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.0186565
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.0183532
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.0181502
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.0178417
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.0176317
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.0173635
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.0171628
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.0168974
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.0166841
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.0164779
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.0161739
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.0160034
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.0156316
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.0155054
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.0154224
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.0153216
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.0151308
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.0150669
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.0148609
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.014672
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.0145493
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.0144554
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.0143358
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.0141306
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.0139141
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.0137298
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.0136836
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.0135626
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.0134394
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.01332
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.013158
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.0130223
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.0129712
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.0129353
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.0129062
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.0128612
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.0128239
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.0126509
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.0126475
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.012663
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.0126518
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.0125946
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.012574
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.0125464
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.0125041
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.0124604
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.0124639
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.0124
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.0123259
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.012271
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.0121876
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.0121412
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.0120958
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.0120397
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.0119374
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.0118849
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.0118914
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.0118264
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.0118338
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.011799
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.0117587
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.0116856
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.0116484
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.0115879
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.0115547
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.0114944
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.0114671
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.0114212
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.0114771
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 0.0114549
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 0.0114557
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 0.0114506
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 0.0115097
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[116]	valid_0's binary_logloss: 0.0114727
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[117]	valid_0's binary_logloss: 0.0114733
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[118]	valid_0's binary_logloss: 0.0114536
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[119]	valid_0's binary_logloss: 0.0114582
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[120]	valid_0's binary_logloss: 0.0114537
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[121]	valid_0's binary_logloss: 0.0114674
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[122]	valid_0's binary_logloss: 0.0114825
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[123]	valid_0's binary_logloss: 0.0114175
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[124]	valid_0's binary_logloss: 0.0113691
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[125]	valid_0's binary_logloss: 0.0114076
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[126]	valid_0's binary_logloss: 0.0113626
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[127]	valid_0's binary_logloss: 0.0113147
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[128]	valid_0's binary_logloss: 0.0113079
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[129]	valid_0's binary_logloss: 0.011272
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[130]	valid_0's binary_logloss: 0.0112772
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[131]	valid_0's binary_logloss: 0.0112695
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[132]	valid_0's binary_logloss: 0.0113173
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[133]	valid_0's binary_logloss: 0.0112871
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[134]	valid_0's binary_logloss: 0.0112644
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[135]	valid_0's binary_logloss: 0.0112632
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[136]	valid_0's binary_logloss: 0.0112732
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[137]	valid_0's binary_logloss: 0.0112817
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[138]	valid_0's binary_logloss: 0.0112565
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[139]	valid_0's binary_logloss: 0.0112269
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[140]	valid_0's binary_logloss: 0.0112569
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[141]	valid_0's binary_logloss: 0.0112964
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[142]	valid_0's binary_logloss: 0.0113056
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[143]	valid_0's binary_logloss: 0.0113138
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[144]	valid_0's binary_logloss: 0.0113541
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[145]	valid_0's binary_logloss: 0.0113747
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[146]	valid_0's binary_logloss: 0.011346
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[147]	valid_0's binary_logloss: 0.0113272
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[148]	valid_0's binary_logloss: 0.0113163
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[149]	valid_0's binary_logloss: 0.0112961
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[150]	valid_0's binary_logloss: 0.0112685
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[151]	valid_0's binary_logloss: 0.0112559
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[152]	valid_0's binary_logloss: 0.0112426
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[153]	valid_0's binary_logloss: 0.0112028
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[154]	valid_0's binary_logloss: 0.0112452
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[155]	valid_0's binary_logloss: 0.0112467
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[156]	valid_0's binary_logloss: 0.0112774
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[157]	valid_0's binary_logloss: 0.0112551
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[158]	valid_0's binary_logloss: 0.0112862
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[159]	valid_0's binary_logloss: 0.0113286
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[160]	valid_0's binary_logloss: 0.0113601
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[161]	valid_0's binary_logloss: 0.011296
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[162]	valid_0's binary_logloss: 0.0113047
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[163]	valid_0's binary_logloss: 0.0112944
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[164]	valid_0's binary_logloss: 0.0113012
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[165]	valid_0's binary_logloss: 0.0112405
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[166]	valid_0's binary_logloss: 0.0112494
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[167]	valid_0's binary_logloss: 0.0112626
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[168]	valid_0's binary_logloss: 0.0112186
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[169]	valid_0's binary_logloss: 0.0111807
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[170]	valid_0's binary_logloss: 0.0111563
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[171]	valid_0's binary_logloss: 0.0111572
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[172]	valid_0's binary_logloss: 0.0111465
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[173]	valid_0's binary_logloss: 0.0111472
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[174]	valid_0's binary_logloss: 0.0111643
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[175]	valid_0's binary_logloss: 0.0111548
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[176]	valid_0's binary_logloss: 0.0111578
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[177]	valid_0's binary_logloss: 0.0111604
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[178]	valid_0's binary_logloss: 0.0111631
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[179]	valid_0's binary_logloss: 0.0111536
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[180]	valid_0's binary_logloss: 0.011157

Trening klas:  91%|█████████ | 453/500 [52:08<04:29,  5.73s/klasa, klasa=class_453, F1_klasy=0.5000, F1_macro=0.6321, drzewa=190]




Trening klas:  91%|█████████ | 454/500 [52:08<04:17,  5.59s/klasa, klasa=class_453, F1_klasy=0.5000, F1_macro=0.6321, drzewa=190]

[1]	valid_0's binary_logloss: 0.0320966
[2]	valid_0's binary_logloss: 0.025892
[3]	valid_0's binary_logloss: 0.0233764
[4]	valid_0's binary_logloss: 0.0214745
[5]	valid_0's binary_logloss: 0.0198583
[6]	valid_0's binary_logloss: 0.0183796
[7]	valid_0's binary_logloss: 0.0175557
[8]	valid_0's binary_logloss: 0.0166457
[9]	valid_0's binary_logloss: 0.0156739
[10]	valid_0's binary_logloss: 0.0149827
[11]	valid_0's binary_logloss: 0.0142341
[12]	valid_0's binary_logloss: 0.0135497
[13]	valid_0's binary_logloss: 0.0129225
[14]	valid_0's binary_logloss: 0.0123845
[15]	valid_0's binary_logloss: 0.0117449
[16]	valid_0's binary_logloss: 0.0112543
[17]	valid_0's binary_logloss: 0.0108502
[18]	valid_0's binary_logloss: 0.0104572
[19]	valid_0's binary_logloss: 0.0100853
[20]	valid_0's binary_logloss: 0.00969962
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.00939928
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0091043
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.00886026
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0086228
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.00840038
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.00813718
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.00789331
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.00768784
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.00747654
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.0072259
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.00702277
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.00684157
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.00665929
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.00646874
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.00626409
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.00608088
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.00590764
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.00573941
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.00558771
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.0054615
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.0053143
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.00516951
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.00503504
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.00490114
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.00477918
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.00466019
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.00455324
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.0044632
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.00437796
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.00428723
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.00419437
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.00410616
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.00401527
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.00394796
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.0038788
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.00381251
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.00374438
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.00368312
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.00363599
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.003581
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.0035283
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.00347141
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.00342271
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.00337084
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.00333274
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.00329184
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.00324591
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.00320693
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.00318042
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.00314954
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.00311387
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.00309483
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.00304985
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.00303978
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.00300443
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.00298377
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.00296292
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.00293692
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.00291225
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.00289024
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.00286697
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.00284583
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.00282335
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.00280577
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.00278638
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.00277536
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.0027595
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.00275091
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.00274019
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.00272863
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.00270768
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.00269577
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.00268189
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.00266547
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.00265449
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.00265398
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.00263294
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.00262825
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.00263073
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.00262332
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.00261307
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.00260398
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.00259656
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.00258924
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.00258514
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.00258009
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.00258552
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.0025817
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.00257812
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.00257821
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.00257238
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 0.00256812
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 0.00256596
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 0.00256366
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 0.00255973
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[116]	valid_0's binary_logloss: 0.00255864
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[117]	valid_0's binary_logloss: 0.00255588
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[118]	valid_0's binary_logloss: 0.00255434
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[119]	valid_0's binary_logloss: 0.0025508
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[120]	valid_0's binary_logloss: 0.00255265
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[121]	valid_0's binary_logloss: 0.00255129
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[122]	valid_0's binary_logloss: 0.00255499
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[123]	valid_0's binary_logloss: 0.00255463
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[124]	valid_0's binary_logloss: 0.002554
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[125]	valid_0's binary_logloss: 0.00255367
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[126]	valid_0's binary_logloss: 0.00255663
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[127]	valid_0's binary_logloss: 0.00255983
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[128]	valid_0's binary_logloss: 0.00256316
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[129]	valid_0's binary_logloss: 0.00256661
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[130]	valid_0's binary_logloss: 0.00256799
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[131]	valid_0's binary_logloss: 0.00257096
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[132]	valid_0's binary_logloss: 0.00256879
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[133]	valid_0's binary_logloss: 0.00256565
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[134]	valid_0's binary_logloss: 0.00256324
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[135]	valid_0's binary_logloss: 0.002562
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[136]	valid_0's binary_logloss: 0.00256822
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[137]	valid_0's binary_logloss: 0.00257164
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[138]	valid_0's binary_logloss: 0.00257235
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[139]	valid_0's binary_logloss: 0.00257644
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[140]	valid_0's binary_logloss: 0.00256665
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[141]	valid_0's binary_logloss: 0.00257349
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[142]	valid_0's binary_logloss: 0.00257556
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[143]	valid_0's binary_logloss: 0.00257608
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[144]	valid_0's binary_logloss: 0.00258084
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[145]	valid_0's binary_logloss: 0.00258921
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

Trening klas:  91%|█████████ | 454/500 [52:15<04:17,  5.59s/klasa, klasa=class_454, F1_klasy=0.0000, F1_macro=0.6307, drzewa=119]




Trening klas:  91%|█████████ | 455/500 [52:15<04:26,  5.92s/klasa, klasa=class_454, F1_klasy=0.0000, F1_macro=0.6307, drzewa=119]

[146]	valid_0's binary_logloss: 0.00259398
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[147]	valid_0's binary_logloss: 0.00259987
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[148]	valid_0's binary_logloss: 0.00260494
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[149]	valid_0's binary_logloss: 0.00260782
[1]	valid_0's binary_logloss: 0.791934
[2]	valid_0's binary_logloss: 0.188755
[3]	valid_0's binary_logloss: 0.235105
[4]	valid_0's binary_logloss: 0.230957
[5]	valid_0's binary_logloss: 0.223164
[6]	valid_0's binary_logloss: 0.269677
[7]	valid_0's binary_logloss: 0.260999
[8]	valid_0's binary_logloss: 0.259016
[9]	valid_0's binary_logloss: 0.256885
[10]	valid_0's binary_logloss: 0.255341
[11]	valid_0's binary_logloss: 0.278686
[12]	valid_0's binary_logloss: 0.273391
[13]	valid_0's binary_logloss: 0.271842
[14]	valid_0's binary_logloss: 0.270278
[15]	valid_0's binary_logloss: 0.267896
[16]	valid_0's binary_logloss: 0.265857
[17]	valid_0's binary_logloss: 0.264872
[18]	valid_0's binary_logloss: 0.264208
[19]	valid_0's binary_logloss: 0.263485
[20]	valid_0's binary_logloss: 0.262784
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.331687
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.291524
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.282138
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.275107
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.272576
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.271576
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.2705
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.26978
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.269203
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.268647

Trening klas:  91%|█████████ | 455/500 [52:18<04:26,  5.92s/klasa, klasa=class_455, F1_klasy=0.3114, F1_macro=0.6300, drzewa=2]




Trening klas:  91%|█████████ | 456/500 [52:18<03:48,  5.20s/klasa, klasa=class_455, F1_klasy=0.3114, F1_macro=0.6300, drzewa=2]

[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.267313
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.266718
[1]	valid_0's binary_logloss: 0.810699
[2]	valid_0's binary_logloss: 0.312021
[3]	valid_0's binary_logloss: 0.314638
[4]	valid_0's binary_logloss: 0.297466
[5]	valid_0's binary_logloss: 0.291178
[6]	valid_0's binary_logloss: 0.390866
[7]	valid_0's binary_logloss: 0.384115
[8]	valid_0's binary_logloss: 0.381957
[9]	valid_0's binary_logloss: 0.380792
[10]	valid_0's binary_logloss: 0.379031
[11]	valid_0's binary_logloss: 0.375844
[12]	valid_0's binary_logloss: 0.371063
[13]	valid_0's binary_logloss: 0.370906
[14]	valid_0's binary_logloss: 0.370505
[15]	valid_0's binary_logloss: 0.369739
[16]	valid_0's binary_logloss: 0.368726
[17]	valid_0's binary_logloss: 0.367354
[18]	valid_0's binary_logloss: 0.36839
[19]	valid_0's binary_logloss: 0.368357
[20]	valid_0's binary_logloss: 0.36917
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.368577
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.36801
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.367186
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.365116
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.365462
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.366153
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.365872
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.365349
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.365388
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.363565
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

Trening klas:  91%|█████████ | 456/500 [52:21<03:48,  5.20s/klasa, klasa=class_456, F1_klasy=0.4128, F1_macro=0.6295, drzewa=5]




Trening klas:  91%|█████████▏| 457/500 [52:21<03:14,  4.53s/klasa, klasa=class_456, F1_klasy=0.4128, F1_macro=0.6295, drzewa=5]

[31]	valid_0's binary_logloss: 0.362845
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.361773
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.361174
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.361016
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.360539
[1]	valid_0's binary_logloss: 0.0405446
[2]	valid_0's binary_logloss: 0.0233997
[3]	valid_0's binary_logloss: 0.0220422
[4]	valid_0's binary_logloss: 0.0205177
[5]	valid_0's binary_logloss: 0.0190898
[6]	valid_0's binary_logloss: 0.0179984
[7]	valid_0's binary_logloss: 0.0168805
[8]	valid_0's binary_logloss: 0.016043
[9]	valid_0's binary_logloss: 0.0154476
[10]	valid_0's binary_logloss: 0.0147144
[11]	valid_0's binary_logloss: 0.0143113
[12]	valid_0's binary_logloss: 0.0136758
[13]	valid_0's binary_logloss: 0.0131864
[14]	valid_0's binary_logloss: 0.0127304
[15]	valid_0's binary_logloss: 0.0123144
[16]	valid_0's binary_logloss: 0.0118877
[17]	valid_0's binary_logloss: 0.0114764
[18]	valid_0's binary_logloss: 0.0110903
[19]	valid_0's binary_logloss: 0.0107215
[20]	valid_0's binary_logloss: 0.0103714
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0100418
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.00974314
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.00944154
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.00915929
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.00887906
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.00866462
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.00843291
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.00823455
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.00802888
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.00785143
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.00767562
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.00747796
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.0072618
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.00708273
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.00692035
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.00672451
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.00652637
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.00636763
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.00618699
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.0060461
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.00589339
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.00573894
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.00558531
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.00543803
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.00531814
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.00521061
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.0051127
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.00499425
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.00487985
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.00479088
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.00465944
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.00453546
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.00440253
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.00427113
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.00415403
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.00406404
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.00394973
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.00383597
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.00372615
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.00366125
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.00357078
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.00348332
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.00341693
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.0033302
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.00325346
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.00316433
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.0030743
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.00298993
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.0029071
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.00282659
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.00274388
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.00269501
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.00262571
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.00255806
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.00249232
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.0024273
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.00237207
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.00230185
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.00224103
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.00218729
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.00212002
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.00205473
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.00199132
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.00193356
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.00187329
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.00182378
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.0017769
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.00173101
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.00168592
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.00164885
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.00161464
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.00157255
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.00152885
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.00149602
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.00146359
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.00142142
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.00138066
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.00134127
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.00130316
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.00126642
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.00125108
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.00122903
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.00121857
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.00120591
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.00118652
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.00116603
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.00115578
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.00114615
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.00112727
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.00110186
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.00108765
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 0.00106445
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 0.00104207
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 0.0010205
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 0.000999705
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[116]	valid_0's binary_logloss: 0.000981457
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[117]	valid_0's binary_logloss: 0.000970516
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[118]	valid_0's binary_logloss: 0.000959636
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[119]	valid_0's binary_logloss: 0.000946162
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[120]	valid_0's binary_logloss: 0.000933002
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[121]	valid_0's binary_logloss: 0.000918479
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[122]	valid_0's binary_logloss: 0.00090521
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[123]	valid_0's binary_logloss: 0.000892572
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[124]	valid_0's binary_logloss: 0.000881735
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[125]	valid_0's binary_logloss: 0.000871947
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[126]	valid_0's binary_logloss: 0.000855836
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[127]	valid_0's binary_logloss: 0.000840515
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[128]	valid_0's binary_logloss: 0.000829406
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[129]	valid_0's binary_logloss: 0.000815811
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[130]	valid_0's binary_logloss: 0.00080476
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[131]	valid_0's binary_logloss: 0.000795237
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[132]	valid_0's binary_logloss: 0.000786669
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[133]	valid_0's binary_logloss: 0.000777799
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[134]	valid_0's binary_logloss: 0.0007694
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[135]	valid_0's binary_logloss: 0.000762658
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[136]	valid_0's binary_logloss: 0.000751287
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[137]	valid_0's binary_logloss: 0.000746346
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[138]	valid_0's binary_logloss: 0.000735725
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[139]	valid_0's binary_logloss: 0.000734391
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[140]	valid_0's binary_logloss: 0.000730099
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[141]	valid_0's binary_logloss: 0.000724637
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[142]	valid_0's binary_logloss: 0.000709962
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[143]	valid_0's binary_logloss: 0.000704072
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[144]	valid_0's binary_logloss: 0.000699906
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[145]	valid_0's binary_logloss: 0.000688242
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[146]	valid_0's binary_logloss: 0.00068295
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[147]	valid_0's binary_logloss: 0.000678153
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[148]	valid_0's binary_logloss: 0.000673275
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[149]	valid_0's binary_logloss: 0.00066866
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[150]	valid_0's binary_logloss: 0.000666826
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[151]	valid_0's binary_logloss: 0.000671932
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[152]	valid_0's binary_logloss: 0.000673013
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[153]	valid_0's binary_logloss: 0.000670574
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[154]	valid_0's binary_logloss: 0.0006731
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[155]	valid_0's binary_logloss: 0.000675387
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[156]	valid_0's binary_logloss: 0.000665662
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[157]	valid_0's binary_logloss: 0.000664421
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[158]	valid_0's binary_logloss: 0.000659248
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[159]	valid_0's binary_logloss: 0.000651776
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[160]	valid_0's binary_logloss: 0.000646099
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[161]	valid_0's binary_logloss: 0.000642073
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[162]	valid_0's binary_logloss: 0.000635888
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[163]	valid_0's binary_logloss: 0.000627597
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[164]	valid_0's binary_logloss: 0.000619664
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[165]	valid_0's binary_logloss: 0.000607526
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[166]	valid_0's binary_logloss: 0.000607215
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[167]	valid_0's binary_logloss: 0.000605388
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[168]	valid_0's binary_logloss: 0.000603634
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[169]	valid_0's binary_logloss: 0.000601318
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[170]	valid_0's binary_logloss: 0.000600325
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[171]	valid_0's binary_logloss: 0.000596999
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[172]	valid_0's binary_logloss: 0.000593239
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[173]	valid_0's binary_logloss: 0.000586697
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[174]	valid_0's binary_logloss: 0.000577584
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[175]	valid_0's binary_logloss: 0.000574642
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[176]	valid_0's binary_logloss: 0.000570188
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[177]	valid_0's binary_logloss: 0.000570173
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[178]	valid_0's binary_logloss: 0.000563299
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

Trening klas:  91%|█████████▏| 457/500 [52:28<03:14,  4.53s/klasa, klasa=class_457, F1_klasy=0.9333, F1_macro=0.6302, drzewa=299]




Trening klas:  92%|█████████▏| 458/500 [52:28<03:41,  5.28s/klasa, klasa=class_457, F1_klasy=0.9333, F1_macro=0.6302, drzewa=299]

[1]	valid_0's binary_logloss: 0.0236006
[2]	valid_0's binary_logloss: 0.0232049
[3]	valid_0's binary_logloss: 0.0223163
[4]	valid_0's binary_logloss: 0.0219335
[5]	valid_0's binary_logloss: 0.0217572
[6]	valid_0's binary_logloss: 0.0215368
[7]	valid_0's binary_logloss: 0.0212032
[8]	valid_0's binary_logloss: 0.0209817
[9]	valid_0's binary_logloss: 0.0207673
[10]	valid_0's binary_logloss: 0.0203002
[11]	valid_0's binary_logloss: 0.019869
[12]	valid_0's binary_logloss: 0.0193984
[13]	valid_0's binary_logloss: 0.0189285
[14]	valid_0's binary_logloss: 0.0186439
[15]	valid_0's binary_logloss: 0.0184034
[16]	valid_0's binary_logloss: 0.0180248
[17]	valid_0's binary_logloss: 0.0178218
[18]	valid_0's binary_logloss: 0.017775
[19]	valid_0's binary_logloss: 0.017615
[20]	valid_0's binary_logloss: 0.0174601
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.017168
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0170744
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.0169641
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.016773
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.016616
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.0164614
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.0163206
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.0162635
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.0161879
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.0160601
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.0160242
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.0158752
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.0157495
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.0157483
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.0156035
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.0155456
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.0154527
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.0153251
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.0151703
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.0150828
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.015027
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.0150584
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.0150088
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.0149649
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.0149167
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.0148268
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.0148316
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.0147933
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.0147864
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.0147996
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.0147165
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.0146725
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.0146624
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.0146836
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.0146459
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.0146594
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.0145931
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.0145759
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.0145522
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.0145066
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.0144077
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.0142865
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.014242
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.014197
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.0141507
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.0140924
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.0140597
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.0140212
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.0140003
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.0138859
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.0139081
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.0139101
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.0138613
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.0138487
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.0137879
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.0138186
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.0138397
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.0138126
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.0138165
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.0138224
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.0138319
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.013807
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.0137766
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.0137873
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.0137976
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.0137307
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.0137673
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.0137779
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.0136837
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.013635
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.0135736
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.0135129
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.0134754
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.013433
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.0133876
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.0133507
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.0132749
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.0131967
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.0131709
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.0131088
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.0131173
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.0130816
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.0130981
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.0130836
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.0130517
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.0130421
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.0130756
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.0130639
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.0130373
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.0130358
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.0130354
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 0.0130428
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 0.0130536
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 0.0130441
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 0.013037
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[116]	valid_0's binary_logloss: 0.0130339
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[117]	valid_0's binary_logloss: 0.0130396
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[118]	valid_0's binary_logloss: 0.0130415
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[119]	valid_0's binary_logloss: 0.012996
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[120]	valid_0's binary_logloss: 0.0130041
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[121]	valid_0's binary_logloss: 0.0129975
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[122]	valid_0's binary_logloss: 0.0129681
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[123]	valid_0's binary_logloss: 0.0129386
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[124]	valid_0's binary_logloss: 0.0129926
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[125]	valid_0's binary_logloss: 0.0129599
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[126]	valid_0's binary_logloss: 0.0129373
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[127]	valid_0's binary_logloss: 0.012907
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[128]	valid_0's binary_logloss: 0.0129011
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[129]	valid_0's binary_logloss: 0.0129021
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[130]	valid_0's binary_logloss: 0.012876
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[131]	valid_0's binary_logloss: 0.0128694
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[132]	valid_0's binary_logloss: 0.0128563
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[133]	valid_0's binary_logloss: 0.0128997
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[134]	valid_0's binary_logloss: 0.0128788
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[135]	valid_0's binary_logloss: 0.0128791
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[136]	valid_0's binary_logloss: 0.0128778
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[137]	valid_0's binary_logloss: 0.0128566
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[138]	valid_0's binary_logloss: 0.012812
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[139]	valid_0's binary_logloss: 0.0127882
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[140]	valid_0's binary_logloss: 0.0127378
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[141]	valid_0's binary_logloss: 0.0127124
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[142]	valid_0's binary_logloss: 0.0126793
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[143]	valid_0's binary_logloss: 0.0126499
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[144]	valid_0's binary_logloss: 0.0126211
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[145]	valid_0's binary_logloss: 0.0125954
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[146]	valid_0's binary_logloss: 0.012669
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[147]	valid_0's binary_logloss: 0.0127319
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[148]	valid_0's binary_logloss: 0.0128062
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[149]	valid_0's binary_logloss: 0.0128732
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[150]	valid_0's binary_logloss: 0.0128716
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[151]	valid_0's binary_logloss: 0.0128935
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[152]	valid_0's binary_logloss: 0.0128762
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[153]	valid_0's binary_logloss: 0.0128885
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[154]	valid_0's binary_logloss: 0.0129008
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[155]	valid_0's binary_logloss: 0.0129107
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[156]	valid_0's binary_logloss: 0.0129159
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[157]	valid_0's binary_logloss: 0.0129096
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[158]	valid_0's binary_logloss: 0.0129067
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[159]	valid_0's binary_logloss: 0.0129034
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[160]	valid_0's binary_logloss: 0.0128943
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[161]	valid_0's binary_logloss: 0.0128861
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[162]	valid_0's binary_logloss: 0.0128722
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[163]	valid_0's binary_logloss: 0.0128679
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[164]	valid_0's binary_logloss: 0.0128514
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[165]	valid_0's binary_logloss: 0.0128284
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[166]	valid_0's binary_logloss: 0.0128116
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[167]	valid_0's binary_logloss: 0.0127856
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[168]	valid_0's binary_logloss: 0.0127749
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[169]	valid_0's binary_logloss: 0.0127429
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[170]	valid_0's binary_logloss: 0.0127249
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[171]	valid_0's binary_logloss: 0.0127615
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[172]	valid_0's binary_logloss: 0.0128372
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[173]	valid_0's binary_logloss: 0.0129156
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

Trening klas:  92%|█████████▏| 458/500 [52:34<03:41,  5.28s/klasa, klasa=class_458, F1_klasy=0.7848, F1_macro=0.6305, drzewa=145]




Trening klas:  92%|█████████▏| 459/500 [52:34<03:37,  5.29s/klasa, klasa=class_458, F1_klasy=0.7848, F1_macro=0.6305, drzewa=145]

[174]	valid_0's binary_logloss: 0.0129514
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[175]	valid_0's binary_logloss: 0.0129772
[1]	valid_0's binary_logloss: 0.429526
[2]	valid_0's binary_logloss: 0.340049
[3]	valid_0's binary_logloss: 0.436595
[4]	valid_0's binary_logloss: 0.435489
[5]	valid_0's binary_logloss: 0.426142
[6]	valid_0's binary_logloss: 0.505081
[7]	valid_0's binary_logloss: 0.502534
[8]	valid_0's binary_logloss: 0.501667
[9]	valid_0's binary_logloss: 0.502395
[10]	valid_0's binary_logloss: 0.502172
[11]	valid_0's binary_logloss: 0.500193
[12]	valid_0's binary_logloss: 0.50008
[13]	valid_0's binary_logloss: 0.501701
[14]	valid_0's binary_logloss: 0.50067
[15]	valid_0's binary_logloss: 0.501936
[16]	valid_0's binary_logloss: 0.502219
[17]	valid_0's binary_logloss: 0.503306
[18]	valid_0's binary_logloss: 0.503407
[19]	valid_0's binary_logloss: 0.503455
[20]	valid_0's binary_logloss: 0.505811
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.50291
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.50521
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.505387
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.503983
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.504996
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.505334
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.505092
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.505156
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.50995
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.510697
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.509298
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.509252

Trening klas:  92%|█████████▏| 459/500 [52:37<03:37,  5.29s/klasa, klasa=class_459, F1_klasy=0.0649, F1_macro=0.6293, drzewa=2]




Trening klas:  92%|█████████▏| 460/500 [52:37<03:03,  4.60s/klasa, klasa=class_459, F1_klasy=0.0649, F1_macro=0.6293, drzewa=2]

[1]	valid_0's binary_logloss: 0.753286
[2]	valid_0's binary_logloss: 0.392325
[3]	valid_0's binary_logloss: 1.28474
[4]	valid_0's binary_logloss: 1.27428
[5]	valid_0's binary_logloss: 1.26611
[6]	valid_0's binary_logloss: 1.26198
[7]	valid_0's binary_logloss: 1.1766
[8]	valid_0's binary_logloss: 1.17317
[9]	valid_0's binary_logloss: 1.17089
[10]	valid_0's binary_logloss: 1.16687
[11]	valid_0's binary_logloss: 1.15605
[12]	valid_0's binary_logloss: 1.23821
[13]	valid_0's binary_logloss: 1.23716
[14]	valid_0's binary_logloss: 1.234
[15]	valid_0's binary_logloss: 1.33886
[16]	valid_0's binary_logloss: 1.32987
[17]	valid_0's binary_logloss: 1.32669
[18]	valid_0's binary_logloss: 1.32995
[19]	valid_0's binary_logloss: 1.3238
[20]	valid_0's binary_logloss: 1.39169
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 1.36495
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 1.36305
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 1.36215
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 1.35332
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 1.39221
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 1.62186
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 1.62078
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 1.62428
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 1.63627
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 1.73344
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 1.71868
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 1.70618

Trening klas:  92%|█████████▏| 460/500 [52:39<03:03,  4.60s/klasa, klasa=class_460, F1_klasy=0.0382, F1_macro=0.6280, drzewa=2]




Trening klas:  92%|█████████▏| 461/500 [52:39<02:38,  4.06s/klasa, klasa=class_460, F1_klasy=0.0382, F1_macro=0.6280, drzewa=2]

[1]	valid_0's binary_logloss: 0.0221926
[2]	valid_0's binary_logloss: 0.0142308
[3]	valid_0's binary_logloss: 0.0130884
[4]	valid_0's binary_logloss: 0.0121175
[5]	valid_0's binary_logloss: 0.0113025
[6]	valid_0's binary_logloss: 0.0108107
[7]	valid_0's binary_logloss: 0.0103143
[8]	valid_0's binary_logloss: 0.00975637
[9]	valid_0's binary_logloss: 0.00943012
[10]	valid_0's binary_logloss: 0.00912556
[11]	valid_0's binary_logloss: 0.00902697
[12]	valid_0's binary_logloss: 0.00872884
[13]	valid_0's binary_logloss: 0.00843343
[14]	valid_0's binary_logloss: 0.00815616
[15]	valid_0's binary_logloss: 0.00791586
[16]	valid_0's binary_logloss: 0.00769361
[17]	valid_0's binary_logloss: 0.0074357
[18]	valid_0's binary_logloss: 0.00723636
[19]	valid_0's binary_logloss: 0.00698283
[20]	valid_0's binary_logloss: 0.0067864
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.00657248
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.00638936
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.00621795
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.00604065
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.00587587
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.00573279
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.00560259
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.00544807
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.00532743
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.00520246
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.00508989
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.00497101
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.00488141
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.00472748
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.00456813
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.00446757
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.00435794
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.00423669
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.00412049
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.00402556
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.00390712
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.00379298
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.0036976
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.00365808
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.00356682
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.00348037
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.00338707
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.00329482
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.00322258
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.00313764
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.00306716
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.00297036
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.00292224
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.00285607
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.00278294
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.00274443
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.00268336
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.0026274
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.00257357
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.00250642
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.00246568
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.00243836
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.00238572
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.0023327
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.00230887
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.00225045
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.00219885
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.00217191
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.00212617
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.00208018
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.00204712
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.0020176
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.00198901
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.00196648
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.00193374
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.0019094
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.00188568
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.00185837
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.00183414
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.00181655
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.0017841
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.00176573
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.00173328
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.00171055
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.00169269
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.00167229
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.00165066
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.00163893
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.00162133
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.00160024
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.00157411
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.00154269
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.00151871
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.00149414
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.00147663
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.00146118
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.0014464
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.00143229
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.00141221
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.00139914
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.00140774
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.0014228
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.00143836
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.00142542
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.00142171
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.0014104
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.0013864
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.00137429
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.0013861
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.0013812
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.00137798
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 0.00137527
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 0.00137305
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 0.00137131
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 0.0013697
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[116]	valid_0's binary_logloss: 0.00136211
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[117]	valid_0's binary_logloss: 0.00135478
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[118]	valid_0's binary_logloss: 0.00134849
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[119]	valid_0's binary_logloss: 0.00134238
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[120]	valid_0's binary_logloss: 0.00132326
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[121]	valid_0's binary_logloss: 0.00131838
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[122]	valid_0's binary_logloss: 0.00131114
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[123]	valid_0's binary_logloss: 0.0013103
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[124]	valid_0's binary_logloss: 0.00130045
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[125]	valid_0's binary_logloss: 0.00130013
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[126]	valid_0's binary_logloss: 0.00128717
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[127]	valid_0's binary_logloss: 0.00128139
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[128]	valid_0's binary_logloss: 0.00126916
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[129]	valid_0's binary_logloss: 0.00125619
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[130]	valid_0's binary_logloss: 0.00123887
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[131]	valid_0's binary_logloss: 0.00123616
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[132]	valid_0's binary_logloss: 0.00122877
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[133]	valid_0's binary_logloss: 0.00123205
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[134]	valid_0's binary_logloss: 0.00121847
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[135]	valid_0's binary_logloss: 0.00120601
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[136]	valid_0's binary_logloss: 0.00120465
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[137]	valid_0's binary_logloss: 0.00120319
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[138]	valid_0's binary_logloss: 0.00120208
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[139]	valid_0's binary_logloss: 0.00120067
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[140]	valid_0's binary_logloss: 0.00119967
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[141]	valid_0's binary_logloss: 0.0012064
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[142]	valid_0's binary_logloss: 0.00120195
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[143]	valid_0's binary_logloss: 0.00120786
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[144]	valid_0's binary_logloss: 0.00120385
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[145]	valid_0's binary_logloss: 0.00121728
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[146]	valid_0's binary_logloss: 0.00121753
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[147]	valid_0's binary_logloss: 0.00121741
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[148]	valid_0's binary_logloss: 0.00121791
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[149]	valid_0's binary_logloss: 0.00121261
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[150]	valid_0's binary_logloss: 0.00120911
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[151]	valid_0's binary_logloss: 0.00120331
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[152]	valid_0's binary_logloss: 0.00119872
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[153]	valid_0's binary_logloss: 0.00119461
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[154]	valid_0's binary_logloss: 0.00119471
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[155]	valid_0's binary_logloss: 0.00119458
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[156]	valid_0's binary_logloss: 0.00119376
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[157]	valid_0's binary_logloss: 0.00119509
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[158]	valid_0's binary_logloss: 0.00119575
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[159]	valid_0's binary_logloss: 0.00119504
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[160]	valid_0's binary_logloss: 0.00118228
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[161]	valid_0's binary_logloss: 0.00118263
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[162]	valid_0's binary_logloss: 0.00118244
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[163]	valid_0's binary_logloss: 0.00118304
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[164]	valid_0's binary_logloss: 0.00118295
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[165]	valid_0's binary_logloss: 0.001177
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[166]	valid_0's binary_logloss: 0.0011634
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[167]	valid_0's binary_logloss: 0.00115878
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[168]	valid_0's binary_logloss: 0.00115438
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[169]	valid_0's binary_logloss: 0.00114247
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[170]	valid_0's binary_logloss: 0.00113543
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[171]	valid_0's binary_logloss: 0.00112375
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[172]	valid_0's binary_logloss: 0.00111257
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[173]	valid_0's binary_logloss: 0.00111689
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[174]	valid_0's binary_logloss: 0.00111279
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[175]	valid_0's binary_logloss: 0.00110627
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[176]	valid_0's binary_logloss: 0.00110019
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[177]	valid_0's binary_logloss: 0.00109758
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[178]	valid_0's binary_logloss: 0.00109672
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[179]	valid_0's binary_logloss: 0.00109091
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[180]	valid_0's binary_logloss: 0.00107966
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[181]	valid_0's binary_logloss: 0.00108243
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[182]	valid_0's binary_logloss: 0.00107639
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[183]	valid_0's binary_logloss: 0.00107586

Trening klas:  92%|█████████▏| 461/500 [52:46<02:38,  4.06s/klasa, klasa=class_461, F1_klasy=0.8750, F1_macro=0.6286, drzewa=260]




Trening klas:  92%|█████████▏| 462/500 [52:46<03:07,  4.94s/klasa, klasa=class_461, F1_klasy=0.8750, F1_macro=0.6286, drzewa=260]

[1]	valid_0's binary_logloss: 0.00456674
[2]	valid_0's binary_logloss: 0.0043341
[3]	valid_0's binary_logloss: 0.00411675
[4]	valid_0's binary_logloss: 0.00390929
[5]	valid_0's binary_logloss: 0.00370396
[6]	valid_0's binary_logloss: 0.0351153
[7]	valid_0's binary_logloss: 0.0307574
[8]	valid_0's binary_logloss: 0.0284528
[9]	valid_0's binary_logloss: 0.0267888
[10]	valid_0's binary_logloss: 0.024214
[11]	valid_0's binary_logloss: 0.0219135
[12]	valid_0's binary_logloss: 0.0201788
[13]	valid_0's binary_logloss: 0.0194279
[14]	valid_0's binary_logloss: 0.018057
[15]	valid_0's binary_logloss: 0.0168575
[16]	valid_0's binary_logloss: 0.0158186
[17]	valid_0's binary_logloss: 0.0153112
[18]	valid_0's binary_logloss: 0.0144388
[19]	valid_0's binary_logloss: 0.0136405
[20]	valid_0's binary_logloss: 0.0129044
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0122134
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0115717
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.0109738
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0104135
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.00989013
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.00939909
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.00902158
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.00858023
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.00817844
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.00778539
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.00741313
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.00706032
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.00676398
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.00647989
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

Trening klas:  92%|█████████▏| 462/500 [52:49<03:07,  4.94s/klasa, klasa=class_462, F1_klasy=0.0000, F1_macro=0.6272, drzewa=5]




Trening klas:  93%|█████████▎| 463/500 [52:49<02:40,  4.34s/klasa, klasa=class_462, F1_klasy=0.0000, F1_macro=0.6272, drzewa=5]

[35]	valid_0's binary_logloss: 0.00617561
[1]	valid_0's binary_logloss: 0.587527
[2]	valid_0's binary_logloss: 0.398909
[3]	valid_0's binary_logloss: 0.369137
[4]	valid_0's binary_logloss: 0.355374
[5]	valid_0's binary_logloss: 0.349626
[6]	valid_0's binary_logloss: 0.338242
[7]	valid_0's binary_logloss: 0.331463
[8]	valid_0's binary_logloss: 0.324566
[9]	valid_0's binary_logloss: 0.319
[10]	valid_0's binary_logloss: 0.313207
[11]	valid_0's binary_logloss: 0.308672
[12]	valid_0's binary_logloss: 0.305681
[13]	valid_0's binary_logloss: 0.302205
[14]	valid_0's binary_logloss: 0.299456
[15]	valid_0's binary_logloss: 0.296261
[16]	valid_0's binary_logloss: 0.293303
[17]	valid_0's binary_logloss: 0.290824
[18]	valid_0's binary_logloss: 0.288208
[19]	valid_0's binary_logloss: 0.285069
[20]	valid_0's binary_logloss: 0.282753
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.280447
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.278033
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.275581
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.273609
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.271759
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.269132
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.266624
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.264469
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.262918
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.261452
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.260081
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.258506
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.25695
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.255641
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.254373
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.252993
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.25123
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.249993
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.24832
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.246671
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.245131
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.243624
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.242047
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.240575
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.239209
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.237951
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.23675
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.235491
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.234134
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.232897
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.231445
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.23017
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.229055
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.227674
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.226348
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.22521
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.223718
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.222296
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.220948
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.219791
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.218629
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.217561
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.21642
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.215357
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.21425
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.213319
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.211866
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.21047
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.209405
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.207782
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.207032
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.206246
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.205332
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.204487
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.203414
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.202105
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.200906
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.199624
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.198473
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.19742
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.196697
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.195913
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.195054
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.194324
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.19346
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.192661
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.191611
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.190846
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.189793
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.189051
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.188444
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.187716
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.187091
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.186349
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.185465
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.184657
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.183372
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.182061
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.181191
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.1803
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.179859
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.17925
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.178604
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.177978
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.17741
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.176706
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.176025
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.175296
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.174564
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.173897
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.173083
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 0.172386
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 0.171766
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 0.171231
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 0.170492
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[116]	valid_0's binary_logloss: 0.170015
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[117]	valid_0's binary_logloss: 0.169416
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[118]	valid_0's binary_logloss: 0.168626
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[119]	valid_0's binary_logloss: 0.168045
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[120]	valid_0's binary_logloss: 0.16756
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[121]	valid_0's binary_logloss: 0.167267
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[122]	valid_0's binary_logloss: 0.166973
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[123]	valid_0's binary_logloss: 0.166534
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[124]	valid_0's binary_logloss: 0.166293
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[125]	valid_0's binary_logloss: 0.165924
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[126]	valid_0's binary_logloss: 0.165571
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[127]	valid_0's binary_logloss: 0.165085
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[128]	valid_0's binary_logloss: 0.164672
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[129]	valid_0's binary_logloss: 0.164242
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[130]	valid_0's binary_logloss: 0.163798
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[131]	valid_0's binary_logloss: 0.163419
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[132]	valid_0's binary_logloss: 0.163089
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[133]	valid_0's binary_logloss: 0.162836
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[134]	valid_0's binary_logloss: 0.162286
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[135]	valid_0's binary_logloss: 0.16183
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[136]	valid_0's binary_logloss: 0.161354
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[137]	valid_0's binary_logloss: 0.160827
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[138]	valid_0's binary_logloss: 0.16026
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[139]	valid_0's binary_logloss: 0.159768
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[140]	valid_0's binary_logloss: 0.159648
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[141]	valid_0's binary_logloss: 0.15917
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[142]	valid_0's binary_logloss: 0.158724
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[143]	valid_0's binary_logloss: 0.158459
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[144]	valid_0's binary_logloss: 0.158013
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[145]	valid_0's binary_logloss: 0.157618
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[146]	valid_0's binary_logloss: 0.157637
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[147]	valid_0's binary_logloss: 0.157371
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[148]	valid_0's binary_logloss: 0.157218
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[149]	valid_0's binary_logloss: 0.157015
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[150]	valid_0's binary_logloss: 0.156772
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[151]	valid_0's binary_logloss: 0.15672
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[152]	valid_0's binary_logloss: 0.156655
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[153]	valid_0's binary_logloss: 0.156309
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[154]	valid_0's binary_logloss: 0.156126
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[155]	valid_0's binary_logloss: 0.155832
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[156]	valid_0's binary_logloss: 0.155354
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[157]	valid_0's binary_logloss: 0.154947
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[158]	valid_0's binary_logloss: 0.15449
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[159]	valid_0's binary_logloss: 0.15416
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[160]	valid_0's binary_logloss: 0.153761
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[161]	valid_0's binary_logloss: 0.153543
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[162]	valid_0's binary_logloss: 0.15351
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[163]	valid_0's binary_logloss: 0.153117
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[164]	valid_0's binary_logloss: 0.152738
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[165]	valid_0's binary_logloss: 0.152352
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[166]	valid_0's binary_logloss: 0.152091
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[167]	valid_0's binary_logloss: 0.151825
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[168]	valid_0's binary_logloss: 0.151612
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[169]	valid_0's binary_logloss: 0.151271
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[170]	valid_0's binary_logloss: 0.151315
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[171]	valid_0's binary_logloss: 0.151185
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[172]	valid_0's binary_logloss: 0.150992
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[173]	valid_0's binary_logloss: 0.151085
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[174]	valid_0's binary_logloss: 0.151189
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[175]	valid_0's binary_logloss: 0.151093
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[176]	valid_0's binary_logloss: 0.150823
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[177]	valid_0's binary_logloss: 0.150484
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[178]	valid_0's binary_logloss: 0.150137
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[179]	valid_0's binary_logloss: 0.149894
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[180]	valid_0's binary_logloss: 0.149713
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[181]	valid_0's binary_logloss: 0.149382
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[182]	valid_0's binary_logloss: 0.149308
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[183]	valid_0's binary_logloss: 0.149162
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[184]	valid_0's binary_logloss: 0.148863
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[185]	valid_0's binary_logloss: 0.148575
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[186]	valid_0's binary_logloss: 0.14813

Trening klas:  93%|█████████▎| 463/500 [52:58<02:40,  4.34s/klasa, klasa=class_463, F1_klasy=0.0837, F1_macro=0.6260, drzewa=295]




Trening klas:  93%|█████████▎| 464/500 [52:58<03:25,  5.71s/klasa, klasa=class_463, F1_klasy=0.0837, F1_macro=0.6260, drzewa=295]

[1]	valid_0's binary_logloss: 0.00586028
[2]	valid_0's binary_logloss: 0.00553659
[3]	valid_0's binary_logloss: 0.00525067
[4]	valid_0's binary_logloss: 0.00502023
[5]	valid_0's binary_logloss: 0.00476711
[6]	valid_0's binary_logloss: 0.00458035
[7]	valid_0's binary_logloss: 0.00439318
[8]	valid_0's binary_logloss: 0.00421728
[9]	valid_0's binary_logloss: 0.00402546
[10]	valid_0's binary_logloss: 0.00383253
[11]	valid_0's binary_logloss: 0.00368752
[12]	valid_0's binary_logloss: 0.00353134
[13]	valid_0's binary_logloss: 0.00338563
[14]	valid_0's binary_logloss: 0.00324531
[15]	valid_0's binary_logloss: 0.00311883
[16]	valid_0's binary_logloss: 0.00300113
[17]	valid_0's binary_logloss: 0.00288376
[18]	valid_0's binary_logloss: 0.00276821
[19]	valid_0's binary_logloss: 0.00265832
[20]	valid_0's binary_logloss: 0.00255499
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.00244433
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.00234499
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.00225333
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.00215509
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.00206337
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.00198198
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.00190964
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.00183174
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.00176226
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.00169452
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.00162996
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.00156526
[33]	valid_0's binary_logloss: 0.00150546
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.0014476
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.00139194
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.00133954
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.00129001
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.00124311
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.00119406
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.00114952
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.00111041
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.00106333
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.00101765
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.000975369
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.000935397
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.000895399
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.000856935
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.000821412
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.000787579
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.000754958
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.000725097
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.000696874
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.000671183
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.000646493
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.000615472
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.000583049
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.000563998
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.000534956
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.000512821
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.000486977
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.000466813
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.000451413
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.000431795
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.000419319
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.000408465
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.000392036
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.000375328
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.000359569
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.000344329
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.000332458
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.000318698
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.000304899
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.000294761
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.00028189
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.000270346
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.000259199
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.000248108
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.000237883
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.000228303
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.000218999
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.000209733
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.000201191
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.000194929
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.000189062
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.000185209
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.000177704
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.000171877
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.000164441
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.000157658
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.000151085
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.0001448
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.000141923
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.000138346
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.00013288
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.000130061
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.000125418
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.000121044
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.000117233
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.000112562
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.000109005
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.000105433
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.000101453
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 9.9063e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 9.79042e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 9.39032e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 9.00993e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 8.6613e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 8.33641e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 8.00885e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 7.83734e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 7.63889e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 7.30585e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 7.04761e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 6.94031e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 6.90237e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[116]	valid_0's binary_logloss: 6.71929e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[117]	valid_0's binary_logloss: 6.49786e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[118]	valid_0's binary_logloss: 6.25159e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[119]	valid_0's binary_logloss: 5.99892e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[120]	valid_0's binary_logloss: 5.73326e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[121]	valid_0's binary_logloss: 5.66556e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[122]	valid_0's binary_logloss: 5.61584e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[123]	valid_0's binary_logloss: 5.44721e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[124]	valid_0's binary_logloss: 5.25058e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[125]	valid_0's binary_logloss: 5.04742e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[126]	valid_0's binary_logloss: 5.03469e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[127]	valid_0's binary_logloss: 5.05605e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[128]	valid_0's binary_logloss: 5.0395e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[129]	valid_0's binary_logloss: 4.83461e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[130]	valid_0's binary_logloss: 4.83555e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[131]	valid_0's binary_logloss: 4.31504e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[132]	valid_0's binary_logloss: 4.01112e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[133]	valid_0's binary_logloss: 3.77311e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[134]	valid_0's binary_logloss: 3.55007e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[135]	valid_0's binary_logloss: 3.4563e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[136]	valid_0's binary_logloss: 3.42534e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[137]	valid_0's binary_logloss: 3.3987e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[138]	valid_0's binary_logloss: 3.43139e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[139]	valid_0's binary_logloss: 3.29331e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[140]	valid_0's binary_logloss: 3.1594e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[141]	valid_0's binary_logloss: 3.14173e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[142]	valid_0's binary_logloss: 3.08906e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[143]	valid_0's binary_logloss: 3.13009e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[144]	valid_0's binary_logloss: 3.00552e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[145]	valid_0's binary_logloss: 2.88566e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[146]	valid_0's binary_logloss: 2.88226e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[147]	valid_0's binary_logloss: 2.77227e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[148]	valid_0's binary_logloss: 2.78464e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[149]	valid_0's binary_logloss: 2.84077e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[150]	valid_0's binary_logloss: 2.73458e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[151]	valid_0's binary_logloss: 2.72574e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[152]	valid_0's binary_logloss: 2.63633e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[153]	valid_0's binary_logloss: 2.61629e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[154]	valid_0's binary_logloss: 2.60272e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[155]	valid_0's binary_logloss: 2.60872e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[156]	valid_0's binary_logloss: 2.55136e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[157]	valid_0's binary_logloss: 2.51719e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[158]	valid_0's binary_logloss: 2.48889e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[159]	valid_0's binary_logloss: 2.42266e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[160]	valid_0's binary_logloss: 2.35763e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[161]	valid_0's binary_logloss: 2.26632e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[162]	valid_0's binary_logloss: 2.33166e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[163]	valid_0's binary_logloss: 2.31635e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[164]	valid_0's binary_logloss: 2.42156e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[165]	valid_0's binary_logloss: 2.47396e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[166]	valid_0's binary_logloss: 2.48364e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[167]	valid_0's binary_logloss: 2.47544e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[168]	valid_0's binary_logloss: 2.48181e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[169]	valid_0's binary_logloss: 2.58234e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[170]	valid_0's binary_logloss: 2.59075e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[171]	valid_0's binary_logloss: 2.61946e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[172]	valid_0's binary_logloss: 2.53024e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[173]	valid_0's binary_logloss: 2.45016e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[174]	valid_0's binary_logloss: 2.47984e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[175]	valid_0's binary_logloss: 2.38256e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[176]	valid_0's binary_logloss: 2.42233e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[177]	valid_0's binary_logloss: 2.4857e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[178]	valid_0's binary_logloss: 2.57113e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[179]	valid_0's binary_logloss: 2.63802e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[180]	valid_0's binary_logloss: 2.63589e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[181]	valid_0's binary_logloss: 2.53655e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[182]	valid_0's binary_logloss: 2.38706e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

Trening klas:  93%|█████████▎| 464/500 [53:09<03:25,  5.71s/klasa, klasa=class_464, F1_klasy=0.0000, F1_macro=0.6247, drzewa=224]




Trening klas:  93%|█████████▎| 465/500 [53:09<04:08,  7.10s/klasa, klasa=class_464, F1_klasy=0.0000, F1_macro=0.6247, drzewa=224]

[251]	valid_0's binary_logloss: 1.34402e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[252]	valid_0's binary_logloss: 1.32333e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[253]	valid_0's binary_logloss: 1.3013e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[254]	valid_0's binary_logloss: 1.25019e-05
[1]	valid_0's binary_logloss: 0.0809246
[2]	valid_0's binary_logloss: 0.029535
[3]	valid_0's binary_logloss: 0.027773
[4]	valid_0's binary_logloss: 0.0260358
[5]	valid_0's binary_logloss: 0.0246283
[6]	valid_0's binary_logloss: 0.0232202
[7]	valid_0's binary_logloss: 0.0212024
[8]	valid_0's binary_logloss: 0.0196496
[9]	valid_0's binary_logloss: 0.0186573
[10]	valid_0's binary_logloss: 0.0179082
[11]	valid_0's binary_logloss: 0.0172513
[12]	valid_0's binary_logloss: 0.0166233
[13]	valid_0's binary_logloss: 0.0159668
[14]	valid_0's binary_logloss: 0.0154103
[15]	valid_0's binary_logloss: 0.0148505
[16]	valid_0's binary_logloss: 0.0143894
[17]	valid_0's binary_logloss: 0.0139603
[18]	valid_0's binary_logloss: 0.0135532
[19]	valid_0's binary_logloss: 0.0131692
[20]	valid_0's binary_logloss: 0.0127779
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0124219
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.012061
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.0117131
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0113935
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.0110946
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.0108055
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.0105271
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.0102629
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.0100076
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.0097564
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.00953204
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.00929732
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.00905455
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.0088308
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.00860217
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.00834074
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.00813917
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.00794629
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.00775625
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.00762709
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.00743795
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.00725373
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.00707878
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.00690661
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.00675322
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.00659362
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.00645181
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.006315
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.00618306
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.00604254
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.00592997
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.00581824
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.00571253
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.00560102
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.00553116
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.00543457
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.00534208
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.00525255
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.00516498
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.00504056
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.00494455
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.00486518
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.00475861
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.00465832
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.00457039
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.00446811
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.00438765
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.00433439
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.00426806
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.00420473
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.00414936
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.00406926
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.00400159
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.00394286
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.00390178
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.00383917
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.00376966
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.00371968
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.00367007
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.00362784
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.00356845
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.00350593
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.0034547
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.00340414
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.00334309
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.00329767
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.00326118
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.0032067
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.0031697
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.0031386
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.00309948
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.00306233
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.00305003
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.00302126
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.00299921
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.00299107
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.0029539
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.00291853
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.00290046
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.00289586
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.002885
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.00287355
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.00284625
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.00283305
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.0028131
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.00282055
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.00281762
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.00283792
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.00282414
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.0028336
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.00281205
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 0.00278954
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 0.00276971
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 0.0027528
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 0.00272758
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[116]	valid_0's binary_logloss: 0.00271367
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[117]	valid_0's binary_logloss: 0.00268939
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[118]	valid_0's binary_logloss: 0.00266075
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[119]	valid_0's binary_logloss: 0.00264455
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[120]	valid_0's binary_logloss: 0.00262203
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[121]	valid_0's binary_logloss: 0.00262098
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[122]	valid_0's binary_logloss: 0.00261581
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[123]	valid_0's binary_logloss: 0.00261936
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[124]	valid_0's binary_logloss: 0.00262061
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[125]	valid_0's binary_logloss: 0.0026281
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[126]	valid_0's binary_logloss: 0.002623
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[127]	valid_0's binary_logloss: 0.00261085
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[128]	valid_0's binary_logloss: 0.00259881
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[129]	valid_0's binary_logloss: 0.00258573
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[130]	valid_0's binary_logloss: 0.00257692
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[131]	valid_0's binary_logloss: 0.0025817
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[132]	valid_0's binary_logloss: 0.00259549
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[133]	valid_0's binary_logloss: 0.00261722
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[134]	valid_0's binary_logloss: 0.00261005
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[135]	valid_0's binary_logloss: 0.00261373
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[136]	valid_0's binary_logloss: 0.00260934
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[137]	valid_0's binary_logloss: 0.00260421
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[138]	valid_0's binary_logloss: 0.0026063
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[139]	valid_0's binary_logloss: 0.00260197
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[140]	valid_0's binary_logloss: 0.00259369
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[141]	valid_0's binary_logloss: 0.00260159
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[142]	valid_0's binary_logloss: 0.00259727
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[143]	valid_0's binary_logloss: 0.00259807
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[144]	valid_0's binary_logloss: 0.0025924
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[145]	valid_0's binary_logloss: 0.00259382
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[146]	valid_0's binary_logloss: 0.00260672
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[147]	valid_0's binary_logloss: 0.00261055
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[148]	valid_0's binary_logloss: 0.00261193
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[149]	valid_0's binary_logloss: 0.00260752
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[150]	valid_0's binary_logloss: 0.00260331
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[151]	valid_0's binary_logloss: 0.00258493
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[152]	valid_0's binary_logloss: 0.00258132
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[153]	valid_0's binary_logloss: 0.00257368
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[154]	valid_0's binary_logloss: 0.00257151
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[155]	valid_0's binary_logloss: 0.0025658
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[156]	valid_0's binary_logloss: 0.00256843
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[157]	valid_0's binary_logloss: 0.00255626
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[158]	valid_0's binary_logloss: 0.0025445
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[159]	valid_0's binary_logloss: 0.00253426
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[160]	valid_0's binary_logloss: 0.00252411
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[161]	valid_0's binary_logloss: 0.00252981
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[162]	valid_0's binary_logloss: 0.00251561
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[163]	valid_0's binary_logloss: 0.00250276
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[164]	valid_0's binary_logloss: 0.00249344
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[165]	valid_0's binary_logloss: 0.00247639
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[166]	valid_0's binary_logloss: 0.0024639
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[167]	valid_0's binary_logloss: 0.00245481
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[168]	valid_0's binary_logloss: 0.00244595
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[169]	valid_0's binary_logloss: 0.0024375
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[170]	valid_0's binary_logloss: 0.00243881
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[171]	valid_0's binary_logloss: 0.00243854
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[172]	valid_0's binary_logloss: 0.00243815
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[173]	valid_0's binary_logloss: 0.00243298
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[174]	valid_0's binary_logloss: 0.00242631
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[175]	valid_0's binary_logloss: 0.00242446
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[176]	valid_0's binary_logloss: 0.0024188
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[177]	valid_0's binary_logloss: 0.00240218
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[178]	valid_0's binary_logloss: 0.00240218
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[179]	valid_0's binary_logloss: 0.00239784
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[180]	valid_0's binary_logloss: 0.00239398

Trening klas:  93%|█████████▎| 465/500 [53:16<04:08,  7.10s/klasa, klasa=class_465, F1_klasy=0.4000, F1_macro=0.6242, drzewa=230]




Trening klas:  93%|█████████▎| 466/500 [53:16<03:59,  7.04s/klasa, klasa=class_465, F1_klasy=0.4000, F1_macro=0.6242, drzewa=230]

[252]	valid_0's binary_logloss: 0.00231884
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[253]	valid_0's binary_logloss: 0.00231832
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[254]	valid_0's binary_logloss: 0.00232151
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[255]	valid_0's binary_logloss: 0.00232167
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[256]	valid_0's binary_logloss: 0.00231858
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[257]	valid_0's binary_logloss: 0.00231819
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[258]	valid_0's binary_logloss: 0.00231781
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[259]	valid_0's binary_logloss: 0.00231497
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[260]	valid_0's binary_logloss: 0.00231225
[1]	valid_0's binary_logloss: 0.818396
[2]	valid_0's binary_logloss: 0.286376
[3]	valid_0's binary_logloss: 0.288993
[4]	valid_0's binary_logloss: 0.271821
[5]	valid_0's binary_logloss: 0.265533
[6]	valid_0's binary_logloss: 0.365221
[7]	valid_0's binary_logloss: 0.35847
[8]	valid_0's binary_logloss: 0.356312
[9]	valid_0's binary_logloss: 0.355147
[10]	valid_0's binary_logloss: 0.353386
[11]	valid_0's binary_logloss: 0.350199
[12]	valid_0's binary_logloss: 0.345418
[13]	valid_0's binary_logloss: 0.345261
[14]	valid_0's binary_logloss: 0.34486
[15]	valid_0's binary_logloss: 0.344093
[16]	valid_0's binary_logloss: 0.343081
[17]	valid_0's binary_logloss: 0.341709
[18]	valid_0's binary_logloss: 0.342745
[19]	valid_0's binary_logloss: 0.342712
[20]	valid_0's binary_logloss: 0.343525
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.342932
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.342365
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.341541
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.339471
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.339817
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.340507
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.340227
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.339704
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.339743
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.33792
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

Trening klas:  93%|█████████▎| 466/500 [53:20<03:59,  7.04s/klasa, klasa=class_466, F1_klasy=0.4225, F1_macro=0.6238, drzewa=5]




Trening klas:  93%|█████████▎| 467/500 [53:20<03:22,  6.14s/klasa, klasa=class_466, F1_klasy=0.4225, F1_macro=0.6238, drzewa=5]

[31]	valid_0's binary_logloss: 0.3372
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.336128
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.335529
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.335371
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.334894
[1]	valid_0's binary_logloss: 0.0515142
[2]	valid_0's binary_logloss: 0.0246423
[3]	valid_0's binary_logloss: 0.022547
[4]	valid_0's binary_logloss: 0.0211882
[5]	valid_0's binary_logloss: 0.0198101
[6]	valid_0's binary_logloss: 0.0190998
[7]	valid_0's binary_logloss: 0.0182559
[8]	valid_0's binary_logloss: 0.0177154
[9]	valid_0's binary_logloss: 0.016658
[10]	valid_0's binary_logloss: 0.0161786
[11]	valid_0's binary_logloss: 0.0155791
[12]	valid_0's binary_logloss: 0.0151124
[13]	valid_0's binary_logloss: 0.0146503
[14]	valid_0's binary_logloss: 0.0141344
[15]	valid_0's binary_logloss: 0.0137161
[16]	valid_0's binary_logloss: 0.0134642
[17]	valid_0's binary_logloss: 0.013091
[18]	valid_0's binary_logloss: 0.0127594
[19]	valid_0's binary_logloss: 0.0124388
[20]	valid_0's binary_logloss: 0.0121644
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0118444
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0116242
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.0114358
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0111827
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.0109179
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.010809
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.0105791
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.0102654
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.00994684
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.00982983
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.00961261
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.00941656
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.0092267
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.00906017
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.00887543
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.00870832
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.00832147
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.00817661
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.00806091
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.00793296
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.00775345
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.00761033
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.0074569
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.00732225
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.0071916
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.00704208
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.00696676
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.00679179
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.00663086
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.00657149
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.00646389
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.00640359
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.00634825
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.00632363
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.00629535
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.00619373
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.00608484
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.00597386
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.00590081
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.00582647
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.00582378
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.00581899
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.005821
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.00571103
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.00570886
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.00566275
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.00556401
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.00552507
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.00545425
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.00544607
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.00539947
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.00534988
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.00535333
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.00531456
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.00532935
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.00530984
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.0052536
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.00519809
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.00515399
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.00510019
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.005033
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.00498079
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.00495496
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.0049305
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.00488995
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.00487713
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.00478352
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.00472791
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.00466767
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.00461823
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.00462086
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.00457791
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.00455825
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.00455017
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.00451373
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.00456315
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.00460132
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.00465024
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.00469869
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.00473785
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.00471424
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.00465793
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.00463679
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.00466862
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.00465461
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.0046002
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.00458731
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.00458404
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.0045394
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.00453713
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.00448413
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 0.00445995
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 0.0044769
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 0.00449708
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 0.0045114
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[116]	valid_0's binary_logloss: 0.00448297
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[117]	valid_0's binary_logloss: 0.00446564
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[118]	valid_0's binary_logloss: 0.00440969
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[119]	valid_0's binary_logloss: 0.00437054
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[120]	valid_0's binary_logloss: 0.00435402
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[121]	valid_0's binary_logloss: 0.00432555
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[122]	valid_0's binary_logloss: 0.00430735
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[123]	valid_0's binary_logloss: 0.00427888
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[124]	valid_0's binary_logloss: 0.0042359
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[125]	valid_0's binary_logloss: 0.00419273
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[126]	valid_0's binary_logloss: 0.00420345
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[127]	valid_0's binary_logloss: 0.00418285
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[128]	valid_0's binary_logloss: 0.00418755
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[129]	valid_0's binary_logloss: 0.00419298
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[130]	valid_0's binary_logloss: 0.00420471
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[131]	valid_0's binary_logloss: 0.00417904
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[132]	valid_0's binary_logloss: 0.00418109
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[133]	valid_0's binary_logloss: 0.00416904
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[134]	valid_0's binary_logloss: 0.00415828
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[135]	valid_0's binary_logloss: 0.00414072
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[136]	valid_0's binary_logloss: 0.00409152
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[137]	valid_0's binary_logloss: 0.00407618
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[138]	valid_0's binary_logloss: 0.00403107
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[139]	valid_0's binary_logloss: 0.00404568
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[140]	valid_0's binary_logloss: 0.00400505
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[141]	valid_0's binary_logloss: 0.00395777
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[142]	valid_0's binary_logloss: 0.00393589
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[143]	valid_0's binary_logloss: 0.0039236
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[144]	valid_0's binary_logloss: 0.00389915
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[145]	valid_0's binary_logloss: 0.00388158
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[146]	valid_0's binary_logloss: 0.00391353
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[147]	valid_0's binary_logloss: 0.00388702
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[148]	valid_0's binary_logloss: 0.00390918
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[149]	valid_0's binary_logloss: 0.00390776
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[150]	valid_0's binary_logloss: 0.00390664
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[151]	valid_0's binary_logloss: 0.0039039
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[152]	valid_0's binary_logloss: 0.00389616
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[153]	valid_0's binary_logloss: 0.00389533
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[154]	valid_0's binary_logloss: 0.00389867
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[155]	valid_0's binary_logloss: 0.00389783
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[156]	valid_0's binary_logloss: 0.00391051
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[157]	valid_0's binary_logloss: 0.0038989
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[158]	valid_0's binary_logloss: 0.00390678
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[159]	valid_0's binary_logloss: 0.00391927
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[160]	valid_0's binary_logloss: 0.00392757
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[161]	valid_0's binary_logloss: 0.00389167
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[162]	valid_0's binary_logloss: 0.00385778
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[163]	valid_0's binary_logloss: 0.00382248
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[164]	valid_0's binary_logloss: 0.00378782
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[165]	valid_0's binary_logloss: 0.00375408
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[166]	valid_0's binary_logloss: 0.00375905
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[167]	valid_0's binary_logloss: 0.00377943
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[168]	valid_0's binary_logloss: 0.00378673
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[169]	valid_0's binary_logloss: 0.0037913
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[170]	valid_0's binary_logloss: 0.00380338
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[171]	valid_0's binary_logloss: 0.00380984
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[172]	valid_0's binary_logloss: 0.00382606
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[173]	valid_0's binary_logloss: 0.00382932
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[174]	valid_0's binary_logloss: 0.00383157
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[175]	valid_0's binary_logloss: 0.00382514
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[176]	valid_0's binary_logloss: 0.00383185
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[177]	valid_0's binary_logloss: 0.00383189
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[178]	valid_0's binary_logloss: 0.00382863
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[179]	valid_0's binary_logloss: 0.00383349

Trening klas:  93%|█████████▎| 467/500 [53:26<03:22,  6.14s/klasa, klasa=class_467, F1_klasy=0.8205, F1_macro=0.6242, drzewa=165]




Trening klas:  94%|█████████▎| 468/500 [53:26<03:17,  6.18s/klasa, klasa=class_467, F1_klasy=0.8205, F1_macro=0.6242, drzewa=165]

[195]	valid_0's binary_logloss: 0.0038435
[1]	valid_0's binary_logloss: 0.356329
[2]	valid_0's binary_logloss: 0.231669
[3]	valid_0's binary_logloss: 0.205097
[4]	valid_0's binary_logloss: 0.193093
[5]	valid_0's binary_logloss: 0.181536
[6]	valid_0's binary_logloss: 0.550349
[7]	valid_0's binary_logloss: 0.389768
[8]	valid_0's binary_logloss: 0.305943
[9]	valid_0's binary_logloss: 0.293799
[10]	valid_0's binary_logloss: 0.287124
[11]	valid_0's binary_logloss: 0.279477
[12]	valid_0's binary_logloss: 0.275541
[13]	valid_0's binary_logloss: 0.270637
[14]	valid_0's binary_logloss: 0.265798
[15]	valid_0's binary_logloss: 0.26167
[16]	valid_0's binary_logloss: 0.257166
[17]	valid_0's binary_logloss: 0.25326
[18]	valid_0's binary_logloss: 0.249655
[19]	valid_0's binary_logloss: 0.246234
[20]	valid_0's binary_logloss: 0.242963
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.239992
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.238099
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.236497
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.23451
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.232734
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.230201
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.227539
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.22519
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.223109
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.220713
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.21835
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.216339
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.214577
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.212903

Trening klas:  94%|█████████▎| 468/500 [53:29<03:17,  6.18s/klasa, klasa=class_468, F1_klasy=0.0750, F1_macro=0.6230, drzewa=5]




Trening klas:  94%|█████████▍| 469/500 [53:29<02:44,  5.31s/klasa, klasa=class_468, F1_klasy=0.0750, F1_macro=0.6230, drzewa=5]

[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.211199
[1]	valid_0's binary_logloss: 0.234574
[2]	valid_0's binary_logloss: 0.205858
[3]	valid_0's binary_logloss: 0.186556
[4]	valid_0's binary_logloss: 0.162803
[5]	valid_0's binary_logloss: 0.132153
[6]	valid_0's binary_logloss: 0.318737
[7]	valid_0's binary_logloss: 0.317378
[8]	valid_0's binary_logloss: 0.316625
[9]	valid_0's binary_logloss: 0.316305
[10]	valid_0's binary_logloss: 0.315796
[11]	valid_0's binary_logloss: 0.309291
[12]	valid_0's binary_logloss: 0.303092
[13]	valid_0's binary_logloss: 0.299569
[14]	valid_0's binary_logloss: 0.298293
[15]	valid_0's binary_logloss: 0.297192
[16]	valid_0's binary_logloss: 0.295941
[17]	valid_0's binary_logloss: 0.294837
[18]	valid_0's binary_logloss: 0.293482
[19]	valid_0's binary_logloss: 0.291775
[20]	valid_0's binary_logloss: 0.290178
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.289029
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.28762
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.285926
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.285092
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.284406
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.283762
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.282994
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.282467
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.28193
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.281466
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.280894
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.280615
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.280456
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.279832
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.27959

Trening klas:  94%|█████████▍| 469/500 [53:33<02:44,  5.31s/klasa, klasa=class_469, F1_klasy=0.7513, F1_macro=0.6233, drzewa=5]




Trening klas:  94%|█████████▍| 470/500 [53:33<02:23,  4.79s/klasa, klasa=class_469, F1_klasy=0.7513, F1_macro=0.6233, drzewa=5]

[1]	valid_0's binary_logloss: 0.0406425
[2]	valid_0's binary_logloss: 0.0115343
[3]	valid_0's binary_logloss: 0.0102703
[4]	valid_0's binary_logloss: 0.00980639
[5]	valid_0's binary_logloss: 0.00928809
[6]	valid_0's binary_logloss: 0.00896688
[7]	valid_0's binary_logloss: 0.00852502
[8]	valid_0's binary_logloss: 0.00821883
[9]	valid_0's binary_logloss: 0.007945
[10]	valid_0's binary_logloss: 0.00770353
[11]	valid_0's binary_logloss: 0.00748423
[12]	valid_0's binary_logloss: 0.00727772
[13]	valid_0's binary_logloss: 0.00712511
[14]	valid_0's binary_logloss: 0.0069357
[15]	valid_0's binary_logloss: 0.00675721
[16]	valid_0's binary_logloss: 0.00658896
[17]	valid_0's binary_logloss: 0.00639318
[18]	valid_0's binary_logloss: 0.00615134
[19]	valid_0's binary_logloss: 0.00602734
[20]	valid_0's binary_logloss: 0.00587862
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0057713
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.00567308
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.00557007
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.00549746
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.00539253
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.00531677
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.00522918
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.0051469
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.00505566
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.00498848
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.00491281
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.00477909
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.00470204
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.0046356
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.0043302
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.0042895
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.00420635
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.00412151
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.00406753
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.00402276
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.00395381
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.00383456
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.00372106
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.00369332
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.00360748
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.00353601
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.00352255
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.00348181
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.003462
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.00345421
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.00343391
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.00340571
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.00338782
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.00335832
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.00332757
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.0033327
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.00334035
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.00333271
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.003338
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.00332925
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.00330259
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.00325485
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.00321581
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.00317091
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.00314038
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.00314505
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.00315042
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.00316858
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.00316416
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.00316929
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.00316788
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.00316486
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.00317383
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.00317159
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.00317541
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.00314871
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.00312379
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.00311887
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.00310447
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.00308182
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.00307251
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.00306225
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.00306935
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.0030916
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.00309361
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.0030627
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.00302842
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.00302422
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.00303003
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.0030167
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.00301853
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.00301674
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.00301529
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.00299863
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.00300566
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.00300391
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.00301005
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.00296299
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.0029681
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.00292819
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.00292248
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.00293072
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.00293938
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.00293877
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.00294406
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.00293027
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.00293784
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.00288863
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.00288329
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.00285201
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.00285293
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 0.00283674
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 0.00283332
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 0.00282311
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 0.00281344
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[116]	valid_0's binary_logloss: 0.0028312
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[117]	valid_0's binary_logloss: 0.00283406
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[118]	valid_0's binary_logloss: 0.00283383
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[119]	valid_0's binary_logloss: 0.00284141
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[120]	valid_0's binary_logloss: 0.002849
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[121]	valid_0's binary_logloss: 0.00283972
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[122]	valid_0's binary_logloss: 0.00279797
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[123]	valid_0's binary_logloss: 0.00279187
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[124]	valid_0's binary_logloss: 0.00277418
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[125]	valid_0's binary_logloss: 0.00277439
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[126]	valid_0's binary_logloss: 0.00264458
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[127]	valid_0's binary_logloss: 0.00262996
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[128]	valid_0's binary_logloss: 0.002645
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[129]	valid_0's binary_logloss: 0.00265322
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[130]	valid_0's binary_logloss: 0.00265633
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[131]	valid_0's binary_logloss: 0.00266268
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[132]	valid_0's binary_logloss: 0.00267918
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[133]	valid_0's binary_logloss: 0.002694
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[134]	valid_0's binary_logloss: 0.00272407
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[135]	valid_0's binary_logloss: 0.00275377
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[136]	valid_0's binary_logloss: 0.00277758
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[137]	valid_0's binary_logloss: 0.0028006
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[138]	valid_0's binary_logloss: 0.00280818
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[139]	valid_0's binary_logloss: 0.00282361
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[140]	valid_0's binary_logloss: 0.00282938
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[141]	valid_0's binary_logloss: 0.00281065
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[142]	valid_0's binary_logloss: 0.00281061
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[143]	valid_0's binary_logloss: 0.00276777
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[144]	valid_0's binary_logloss: 0.00276672
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[145]	valid_0's binary_logloss: 0.00276744
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[146]	valid_0's binary_logloss: 0.00274565
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[147]	valid_0's binary_logloss: 0.00276694
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[148]	valid_0's binary_logloss: 0.00276057
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[149]	valid_0's binary_logloss: 0.00274846
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[150]	valid_0's binary_logloss: 0.00274483
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[151]	valid_0's binary_logloss: 0.00274786
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[152]	valid_0's binary_logloss: 0.00275104
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[153]	valid_0's binary_logloss: 0.00274641
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[154]	valid_0's binary_logloss: 0.0027375
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[155]	valid_0's binary_logloss: 0.00274514
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[156]	valid_0's binary_logloss: 0.00262121
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[157]	valid_0's binary_logloss: 0.0025274
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[158]	valid_0's binary_logloss: 0.00252638
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[159]	valid_0's binary_logloss: 0.00255317
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[160]	valid_0's binary_logloss: 0.00256994
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[161]	valid_0's binary_logloss: 0.00257733
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[162]	valid_0's binary_logloss: 0.00255683
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[163]	valid_0's binary_logloss: 0.00254589
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[164]	valid_0's binary_logloss: 0.00255772
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[165]	valid_0's binary_logloss: 0.0025566
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[166]	valid_0's binary_logloss: 0.00256429
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[167]	valid_0's binary_logloss: 0.00256516
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[168]	valid_0's binary_logloss: 0.00259525
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[169]	valid_0's binary_logloss: 0.00259642
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[170]	valid_0's binary_logloss: 0.00260446
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[171]	valid_0's binary_logloss: 0.00263657
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[172]	valid_0's binary_logloss: 0.00264518
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[173]	valid_0's binary_logloss: 0.00264846
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[174]	valid_0's binary_logloss: 0.00263944
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[175]	valid_0's binary_logloss: 0.00265883
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[176]	valid_0's binary_logloss: 0.00253391
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[177]	valid_0's binary_logloss: 0.0025255
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[178]	valid_0's binary_logloss: 0.00246336
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[179]	valid_0's binary_logloss: 0.00240886
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[180]	valid_0's binary_logloss: 0.00236457
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[181]	valid_0's binary_logloss: 0.00236936
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[182]	valid_0's binary_logloss: 0.00239186
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[183]	valid_0's binary_logloss: 0.00240824

Trening klas:  94%|█████████▍| 470/500 [53:40<02:23,  4.79s/klasa, klasa=class_470, F1_klasy=0.6000, F1_macro=0.6233, drzewa=191]




Trening klas:  94%|█████████▍| 471/500 [53:40<02:42,  5.62s/klasa, klasa=class_470, F1_klasy=0.6000, F1_macro=0.6233, drzewa=191]

[216]	valid_0's binary_logloss: 0.00256615
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[217]	valid_0's binary_logloss: 0.00258028
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[218]	valid_0's binary_logloss: 0.00258782
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[219]	valid_0's binary_logloss: 0.00260942
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[220]	valid_0's binary_logloss: 0.0026131
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[221]	valid_0's binary_logloss: 0.00258826
[1]	valid_0's binary_logloss: 1.06025
[2]	valid_0's binary_logloss: 0.492738
[3]	valid_0's binary_logloss: 0.538071
[4]	valid_0's binary_logloss: 0.517447
[5]	valid_0's binary_logloss: 0.506354
[6]	valid_0's binary_logloss: 0.499484
[7]	valid_0's binary_logloss: 0.495423
[8]	valid_0's binary_logloss: 0.491986
[9]	valid_0's binary_logloss: 0.488333
[10]	valid_0's binary_logloss: 0.485978
[11]	valid_0's binary_logloss: 0.470703
[12]	valid_0's binary_logloss: 0.46386
[13]	valid_0's binary_logloss: 0.455156
[14]	valid_0's binary_logloss: 0.448739
[15]	valid_0's binary_logloss: 0.445856
[16]	valid_0's binary_logloss: 0.442449
[17]	valid_0's binary_logloss: 0.442153
[18]	valid_0's binary_logloss: 0.439303
[19]	valid_0's binary_logloss: 0.440639
[20]	valid_0's binary_logloss: 0.434433
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.4297
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.426218
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.420225
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.415485
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.413531
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.409168
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.406263
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.403805
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.403294
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.401595
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.400466
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.400799
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.397998
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.397997
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.397036
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.395814
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.392784
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.391086
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.393144
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.393741
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.39486
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.39531
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.394251
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.394983
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.395077
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.393547
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.392479
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.391932
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.391136
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.3896
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.389014
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.386743
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.384358
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.383719
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.383048
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.382149
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.381596
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.381583
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.380132
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.379373
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.379024
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.378445
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.378545
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.378117
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.3778
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.376913
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.376327
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.374776
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.369818
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.367274
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.369023
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.370242
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.373298
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.377173
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.378254
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.377644
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.376848
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.376431
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.374973
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.374761
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.3755
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.37454
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.374174
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.374381
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.373437
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.373351
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.372523
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.369113
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.368086
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.365499
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.363783
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.369753
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.375912
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.375911
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.377
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.377051
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.377049
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.376788
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.376724
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.37678
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.380119
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.380011
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.379855
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.379904
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.380352
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.380263
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.380139
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.380005
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.378409
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.378312
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.378653
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 0.378271
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 0.37796
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 0.3788
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 0.381072
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[116]	valid_0's binary_logloss: 0.380785
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[117]	valid_0's binary_logloss: 0.379044
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[118]	valid_0's binary_logloss: 0.379444
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[119]	valid_0's binary_logloss: 0.379761
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[120]	valid_0's binary_logloss: 0.379645
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

Trening klas:  94%|█████████▍| 471/500 [53:46<02:42,  5.62s/klasa, klasa=class_471, F1_klasy=0.1477, F1_macro=0.6222, drzewa=91]




Trening klas:  94%|█████████▍| 472/500 [53:46<02:40,  5.72s/klasa, klasa=class_471, F1_klasy=0.1477, F1_macro=0.6222, drzewa=91]

[121]	valid_0's binary_logloss: 0.37946
[1]	valid_0's binary_logloss: 0.184456
[2]	valid_0's binary_logloss: 0.0929525
[3]	valid_0's binary_logloss: 0.0908673
[4]	valid_0's binary_logloss: 0.0888871
[5]	valid_0's binary_logloss: 0.0865401
[6]	valid_0's binary_logloss: 0.0855003
[7]	valid_0's binary_logloss: 0.0835756
[8]	valid_0's binary_logloss: 0.0820825
[9]	valid_0's binary_logloss: 0.0811147
[10]	valid_0's binary_logloss: 0.0796729
[11]	valid_0's binary_logloss: 0.0782557
[12]	valid_0's binary_logloss: 0.0769972
[13]	valid_0's binary_logloss: 0.0760801
[14]	valid_0's binary_logloss: 0.0751203
[15]	valid_0's binary_logloss: 0.0740788
[16]	valid_0's binary_logloss: 0.0731624
[17]	valid_0's binary_logloss: 0.0723574
[18]	valid_0's binary_logloss: 0.0717964
[19]	valid_0's binary_logloss: 0.071351
[20]	valid_0's binary_logloss: 0.0704959
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0695152
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0685521
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.0676763
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0666721
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.0658409
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.0650472
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.0640705
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.0633841
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.0626934
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.0621064
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.0614296
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.0608246
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.0603136
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.0597125
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.0591559
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.0586357
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.0581969
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.0577003
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.0572564
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.0567582
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.0562798
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.0558933
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.055488
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.0550725
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.0546561
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.0540524
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.0534906
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.0529415
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.0522196
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.0516527
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.0511069
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.0507617
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.0502687
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.0498106
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.049287
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.0488301
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.0484838
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.0480931
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.0477402
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.0471768
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.0465763
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.0460543
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.0454959
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.0451501
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.045044
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.0445866
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.0441653
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.043726
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.0433624
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.0429153
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.0426493
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.0424058
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.0422616
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.042333
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.0421988
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.0419537
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.041625
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.0412996
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.0408089
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.0403895
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.0398118
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.0396165
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.0393947
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.0391312
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.0389691
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.0388059
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.0385111
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.0381626
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.0378991
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.0374884
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.0370945
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.0367062
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.0364486
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.0361535
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.0358715
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.0359232
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.0357137
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.0355145
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.0355379
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.0354854
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.0350087
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.0345712
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.0341626
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.0337268
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.0332592
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.0331375
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.0328458
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.0327207
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.0325209
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.0324789
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.0324101
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 0.0320625
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 0.0319739
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 0.0318829
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 0.0317861
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[116]	valid_0's binary_logloss: 0.0315676
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[117]	valid_0's binary_logloss: 0.0314671
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[118]	valid_0's binary_logloss: 0.031345
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[119]	valid_0's binary_logloss: 0.0311284
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[120]	valid_0's binary_logloss: 0.0309638
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[121]	valid_0's binary_logloss: 0.0307575
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[122]	valid_0's binary_logloss: 0.0304685
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[123]	valid_0's binary_logloss: 0.0302528
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[124]	valid_0's binary_logloss: 0.0301322
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[125]	valid_0's binary_logloss: 0.0298693
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[126]	valid_0's binary_logloss: 0.0296459
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[127]	valid_0's binary_logloss: 0.0295419
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[128]	valid_0's binary_logloss: 0.0293333
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[129]	valid_0's binary_logloss: 0.0289969
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[130]	valid_0's binary_logloss: 0.0286633
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[131]	valid_0's binary_logloss: 0.0284711
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[132]	valid_0's binary_logloss: 0.028308
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[133]	valid_0's binary_logloss: 0.0280909
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[134]	valid_0's binary_logloss: 0.0278962
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[135]	valid_0's binary_logloss: 0.0277852
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[136]	valid_0's binary_logloss: 0.0276703
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[137]	valid_0's binary_logloss: 0.0276458
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[138]	valid_0's binary_logloss: 0.0273074
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[139]	valid_0's binary_logloss: 0.0273118
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[140]	valid_0's binary_logloss: 0.0271259
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[141]	valid_0's binary_logloss: 0.0268776
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[142]	valid_0's binary_logloss: 0.0266229
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[143]	valid_0's binary_logloss: 0.0266236
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[144]	valid_0's binary_logloss: 0.0263915
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[145]	valid_0's binary_logloss: 0.0262337
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[146]	valid_0's binary_logloss: 0.0260509
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[147]	valid_0's binary_logloss: 0.0259003
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[148]	valid_0's binary_logloss: 0.0257648
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[149]	valid_0's binary_logloss: 0.0255806
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[150]	valid_0's binary_logloss: 0.0254135
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[151]	valid_0's binary_logloss: 0.0254324
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[152]	valid_0's binary_logloss: 0.0256027
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[153]	valid_0's binary_logloss: 0.0255696
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[154]	valid_0's binary_logloss: 0.0257681
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[155]	valid_0's binary_logloss: 0.0257267
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[156]	valid_0's binary_logloss: 0.0258244
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[157]	valid_0's binary_logloss: 0.0257539
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[158]	valid_0's binary_logloss: 0.0256643
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[159]	valid_0's binary_logloss: 0.0257049
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[160]	valid_0's binary_logloss: 0.0256331
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[161]	valid_0's binary_logloss: 0.025563
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[162]	valid_0's binary_logloss: 0.0255104
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[163]	valid_0's binary_logloss: 0.0254557
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[164]	valid_0's binary_logloss: 0.0255306
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[165]	valid_0's binary_logloss: 0.0255843
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[166]	valid_0's binary_logloss: 0.0254791
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[167]	valid_0's binary_logloss: 0.025351
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[168]	valid_0's binary_logloss: 0.0252693
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[169]	valid_0's binary_logloss: 0.0253769
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[170]	valid_0's binary_logloss: 0.0253092
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[171]	valid_0's binary_logloss: 0.0253622
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[172]	valid_0's binary_logloss: 0.0254581
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[173]	valid_0's binary_logloss: 0.0255599
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[174]	valid_0's binary_logloss: 0.0255234
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[175]	valid_0's binary_logloss: 0.02562
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[176]	valid_0's binary_logloss: 0.0254484
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[177]	valid_0's binary_logloss: 0.025275
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[178]	valid_0's binary_logloss: 0.0251718
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[179]	valid_0's binary_logloss: 0.0252101
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[180]	valid_0's binary_logloss: 0.0249635
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[181]	valid_0's binary_logloss: 0.0250376
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[182]	valid_0's binary_logloss: 0.0250389
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[183]	valid_0's binary_logloss: 0.025143
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[184]	valid_0's binary_logloss: 0.0251505

Trening klas:  94%|█████████▍| 472/500 [53:56<02:40,  5.72s/klasa, klasa=class_472, F1_klasy=0.2553, F1_macro=0.6215, drzewa=298]




Trening klas:  95%|█████████▍| 473/500 [53:56<03:03,  6.81s/klasa, klasa=class_472, F1_klasy=0.2553, F1_macro=0.6215, drzewa=298]

[1]	valid_0's binary_logloss: 0.200869
[2]	valid_0's binary_logloss: 0.12191
[3]	valid_0's binary_logloss: 0.11457
[4]	valid_0's binary_logloss: 0.109353
[5]	valid_0's binary_logloss: 0.105632
[6]	valid_0's binary_logloss: 0.337491
[7]	valid_0's binary_logloss: 0.291901
[8]	valid_0's binary_logloss: 0.28573
[9]	valid_0's binary_logloss: 0.282447
[10]	valid_0's binary_logloss: 0.279169
[11]	valid_0's binary_logloss: 0.439729
[12]	valid_0's binary_logloss: 0.434362
[13]	valid_0's binary_logloss: 0.428674
[14]	valid_0's binary_logloss: 0.421824
[15]	valid_0's binary_logloss: 0.416287
[16]	valid_0's binary_logloss: 0.408888
[17]	valid_0's binary_logloss: 0.403324
[18]	valid_0's binary_logloss: 0.397787
[19]	valid_0's binary_logloss: 0.392601
[20]	valid_0's binary_logloss: 0.389755
[21]	valid_0's binary_logloss: 0.431294
[22]	valid_0's binary_logloss: 0.367748
[23]	valid_0's binary_logloss: 0.367436
[24]	valid_0's binary_logloss: 0.362524
[25]	valid_0's binary_logloss: 0.355494
[26]	valid_0's binary_logloss: 0.349781
[27]	valid_0's binary_logloss: 0.345551
[28]	valid_0's binary_logloss: 0.341973
[29]	valid_0's binary_logloss: 0.338421
[30]	valid_0's binary_logloss: 0.333521
[31]	valid_0's binary_logloss: 0.330988
[32]	valid_0's binary_logloss: 0.32783
[33]	valid_0's binary_logloss: 0.325505
[34]	valid_0's binary_logloss: 0.323296

Trening klas:  95%|█████████▍| 473/500 [54:01<03:03,  6.81s/klasa, klasa=class_473, F1_klasy=0.0270, F1_macro=0.6202, drzewa=5]




Trening klas:  95%|█████████▍| 474/500 [54:01<02:42,  6.26s/klasa, klasa=class_473, F1_klasy=0.0270, F1_macro=0.6202, drzewa=5]

[35]	valid_0's binary_logloss: 0.319627
[1]	valid_0's binary_logloss: 0.403378
[2]	valid_0's binary_logloss: 0.260228
[3]	valid_0's binary_logloss: 0.222521
[4]	valid_0's binary_logloss: 0.205508
[5]	valid_0's binary_logloss: 0.195488
[6]	valid_0's binary_logloss: 0.264805
[7]	valid_0's binary_logloss: 0.249044
[8]	valid_0's binary_logloss: 0.212039
[9]	valid_0's binary_logloss: 0.201571
[10]	valid_0's binary_logloss: 0.19255
[11]	valid_0's binary_logloss: 0.184454
[12]	valid_0's binary_logloss: 0.177469
[13]	valid_0's binary_logloss: 0.171491
[14]	valid_0's binary_logloss: 0.165587
[15]	valid_0's binary_logloss: 0.161011
[16]	valid_0's binary_logloss: 0.157016
[17]	valid_0's binary_logloss: 0.153437
[18]	valid_0's binary_logloss: 0.148871
[19]	valid_0's binary_logloss: 0.144796
[20]	valid_0's binary_logloss: 0.141105
[21]	valid_0's binary_logloss: 0.137201
[22]	valid_0's binary_logloss: 0.133883
[23]	valid_0's binary_logloss: 0.130823
[24]	valid_0's binary_logloss: 0.128008
[25]	valid_0's binary_logloss: 0.125305
[26]	valid_0's binary_logloss: 0.122556
[27]	valid_0's binary_logloss: 0.119976
[28]	valid_0's binary_logloss: 0.117543
[29]	valid_0's binary_logloss: 0.115181
[30]	valid_0's binary_logloss: 0.112943
[31]	valid_0's binary_logloss: 0.110619
[32]	valid_0's binary_logloss: 0.108386
[33]	valid_0's binary_logloss: 0.106857
[34]	valid_0's binary_logloss: 0.10468
[35]	valid_0's binary_logloss: 0.103002
[36]	valid_0's binary_logloss: 0.10129
[37]	valid_0's binary_logloss: 0.0993444
[38]	valid_0's binary_logloss: 0.0973741
[39]	valid_0's binary_logloss: 0.0957463
[40]	valid_0's binary_logloss: 0.0940174
[41]	valid_0's binary_logloss: 0.0922916
[42]	valid_0's binary_logloss: 0.0905479
[43]	valid_0's binary_logloss: 0.0888267
[44]	valid_0's binary_logloss: 0.0871965
[45]	valid_0's binary_logloss: 0.0856139
[46]	valid_0's binary_logloss: 0.0838648
[47]	valid_0's binary_logloss: 0.0824299
[48]	valid_0's binary_logloss: 0.0813048
[49]	valid_0's binary_logloss: 0.0799354
[50]	valid_0's binary_logloss: 0.0787481
[51]	valid_0's binary_logloss: 0.0774116
[52]	valid_0's binary_logloss: 0.0764934
[53]	valid_0's binary_logloss: 0.0755811
[54]	valid_0's binary_logloss: 0.0744906
[55]	valid_0's binary_logloss: 0.0731868
[56]	valid_0's binary_logloss: 0.0720138
[57]	valid_0's binary_logloss: 0.0712257
[58]	valid_0's binary_logloss: 0.0702468
[59]	valid_0's binary_logloss: 0.0692954
[60]	valid_0's binary_logloss: 0.0685821
[61]	valid_0's binary_logloss: 0.0676464
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.0666409
[63]	valid_0's binary_logloss: 0.0657034
[64]	valid_0's binary_logloss: 0.0647292
[65]	valid_0's binary_logloss: 0.0637572
[66]	valid_0's binary_logloss: 0.0627543
[67]	valid_0's binary_logloss: 0.0616303
[68]	valid_0's binary_logloss: 0.0608231
[69]	valid_0's binary_logloss: 0.0600086
[70]	valid_0's binary_logloss: 0.0591338
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.058269
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.0574612
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.0567354
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.0558691
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.0549977
[76]	valid_0's binary_logloss: 0.0544785
[77]	valid_0's binary_logloss: 0.0537797
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.0531844
[79]	valid_0's binary_logloss: 0.0526049
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.0519875
[81]	valid_0's binary_logloss: 0.0512846
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.0505166
[83]	valid_0's binary_logloss: 0.0500245
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.0493479
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.0487941
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.0480542
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.0474031
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.046731
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.0460933
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.0454372
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.0449091
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.0443893
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.043974
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.0435209
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.0430739
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.0427227
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.0422613
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.0416981
[99]	valid_0's binary_logloss: 0.0413375
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.0410021
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.040713
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.0403869
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.0401246
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.0398889
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.0395551
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.0392663
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.0390105
[108]	valid_0's binary_logloss: 0.0386603
[109]	valid_0's binary_logloss: 0.0383445
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.0381563
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.0380364
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 0.0378414
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 0.0376487
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 0.037506
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 0.0372693
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[116]	valid_0's binary_logloss: 0.0372403
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[117]	valid_0's binary_logloss: 0.0371342
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[118]	valid_0's binary_logloss: 0.0370038
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[119]	valid_0's binary_logloss: 0.036955
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[120]	valid_0's binary_logloss: 0.0367376
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[121]	valid_0's binary_logloss: 0.0365562
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[122]	valid_0's binary_logloss: 0.0364136
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[123]	valid_0's binary_logloss: 0.0362966
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[124]	valid_0's binary_logloss: 0.0361606
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[125]	valid_0's binary_logloss: 0.0360107
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[126]	valid_0's binary_logloss: 0.0358618
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[127]	valid_0's binary_logloss: 0.0356689
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[128]	valid_0's binary_logloss: 0.035548
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[129]	valid_0's binary_logloss: 0.0355346
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[130]	valid_0's binary_logloss: 0.0354941
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[131]	valid_0's binary_logloss: 0.0352581
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[132]	valid_0's binary_logloss: 0.0350439
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[133]	valid_0's binary_logloss: 0.0347977
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[134]	valid_0's binary_logloss: 0.0345866
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[135]	valid_0's binary_logloss: 0.0344062
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[136]	valid_0's binary_logloss: 0.0341602
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[137]	valid_0's binary_logloss: 0.0340156
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[138]	valid_0's binary_logloss: 0.033762
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[139]	valid_0's binary_logloss: 0.0335325
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[140]	valid_0's binary_logloss: 0.033356
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[141]	valid_0's binary_logloss: 0.0333458
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[142]	valid_0's binary_logloss: 0.0332835
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[143]	valid_0's binary_logloss: 0.0333252
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[144]	valid_0's binary_logloss: 0.0332849
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[145]	valid_0's binary_logloss: 0.0332585
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[146]	valid_0's binary_logloss: 0.0332479
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[147]	valid_0's binary_logloss: 0.0332549
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[148]	valid_0's binary_logloss: 0.033235
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[149]	valid_0's binary_logloss: 0.0332086
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[150]	valid_0's binary_logloss: 0.033147
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[151]	valid_0's binary_logloss: 0.0329418
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[152]	valid_0's binary_logloss: 0.0327414
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[153]	valid_0's binary_logloss: 0.0325816
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[154]	valid_0's binary_logloss: 0.0324495
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[155]	valid_0's binary_logloss: 0.0322181
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[156]	valid_0's binary_logloss: 0.0321291
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[157]	valid_0's binary_logloss: 0.0320485
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[158]	valid_0's binary_logloss: 0.0319448
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[159]	valid_0's binary_logloss: 0.0318929
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[160]	valid_0's binary_logloss: 0.0318038
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[161]	valid_0's binary_logloss: 0.0318342
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[162]	valid_0's binary_logloss: 0.0317763
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[163]	valid_0's binary_logloss: 0.0316207
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[164]	valid_0's binary_logloss: 0.0315321
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[165]	valid_0's binary_logloss: 0.0315909
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[166]	valid_0's binary_logloss: 0.0313759
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[167]	valid_0's binary_logloss: 0.031232
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[168]	valid_0's binary_logloss: 0.0309819
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[169]	valid_0's binary_logloss: 0.0308496
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[170]	valid_0's binary_logloss: 0.0306584
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[171]	valid_0's binary_logloss: 0.0306852
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[172]	valid_0's binary_logloss: 0.0306483
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[173]	valid_0's binary_logloss: 0.0306548
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[174]	valid_0's binary_logloss: 0.030661
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[175]	valid_0's binary_logloss: 0.0306622
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[176]	valid_0's binary_logloss: 0.0306358
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[177]	valid_0's binary_logloss: 0.0307358
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[178]	valid_0's binary_logloss: 0.0307229
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[179]	valid_0's binary_logloss: 0.0306984
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[180]	valid_0's binary_logloss: 0.0306921
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[181]	valid_0's binary_logloss: 0.0306737
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[182]	valid_0's binary_logloss: 0.0306413
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[183]	valid_0's binary_logloss: 0.0306144
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[184]	valid_0's binary_logloss: 0.030584
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[185]	valid_0's binary_logloss: 0.0305683
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[186]	valid_0's binary_logloss: 0.0305147
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[187]	valid_0's binary_logloss: 0.0304417
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[188]	valid_0's binary_logloss: 0.0303556
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[189]	valid_0's binary_logloss: 0.0302626
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[190]	valid_0's binary_logloss: 0.0301942
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[191]	valid_0's binary_logloss: 0.030206
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[192]	valid_0's binary_logloss: 0.0302796
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[193]	valid_0's binary_logloss: 0.0302405
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[194]	valid_0's binary_logloss: 0.0302054
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[195]	valid_0's binary_logloss: 0.0301756
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[196]	valid_0's binary_logloss: 0.0301511
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[197]	valid_0's binary_logloss: 0.0301288
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[198]	valid_0's binary_logloss: 0.0300761
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[199]	valid_0's binary_logloss: 0.0300573
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[200]	valid_0's binary_logloss: 0.0300388
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[201]	valid_0's binary_logloss: 0.0300446
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[202]	valid_0's binary_logloss: 0.0300245
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[203]	valid_0's binary_logloss: 0.030008
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[204]	valid_0's binary_logloss: 0.029965
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[205]	valid_0's binary_logloss: 0.0299247
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[206]	valid_0's binary_logloss: 0.0298222
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[207]	valid_0's binary_logloss: 0.0298615
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[208]	valid_0's binary_logloss: 0.0297767
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[209]	valid_0's binary_logloss: 0.0297856
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[210]	valid_0's binary_logloss: 0.0297805
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[211]	valid_0's binary_logloss: 0.0298635
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[212]	valid_0's binary_logloss: 0.0298288
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[213]	valid_0's binary_logloss: 0.0299049
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[214]	valid_0's binary_logloss: 0.0298876
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[215]	valid_0's binary_logloss: 0.0298037
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[216]	valid_0's binary_logloss: 0.0297629
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[217]	valid_0's binary_logloss: 0.0297912
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[218]	valid_0's binary_logloss: 0.0297993
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[219]	valid_0's binary_logloss: 0.0297631
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[220]	valid_0's binary_logloss: 0.0297617
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[221]	valid_0's binary_logloss: 0.0297837

Trening klas:  95%|█████████▍| 474/500 [54:16<02:42,  6.26s/klasa, klasa=class_474, F1_klasy=0.1333, F1_macro=0.6192, drzewa=245]




Trening klas:  95%|█████████▌| 475/500 [54:16<03:47,  9.12s/klasa, klasa=class_474, F1_klasy=0.1333, F1_macro=0.6192, drzewa=245]

[275]	valid_0's binary_logloss: 0.0293356
[1]	valid_0's binary_logloss: 0.00505832
[2]	valid_0's binary_logloss: 0.00483243
[3]	valid_0's binary_logloss: 0.00463733
[4]	valid_0's binary_logloss: 0.00445907
[5]	valid_0's binary_logloss: 0.00428436
[6]	valid_0's binary_logloss: 0.00411828
[7]	valid_0's binary_logloss: 0.00396317
[8]	valid_0's binary_logloss: 0.00381664
[9]	valid_0's binary_logloss: 0.0036799
[10]	valid_0's binary_logloss: 0.0035512
[11]	valid_0's binary_logloss: 0.00342835
[12]	valid_0's binary_logloss: 0.0033128
[13]	valid_0's binary_logloss: 0.00320226
[14]	valid_0's binary_logloss: 0.00309663
[15]	valid_0's binary_logloss: 0.00299798
[16]	valid_0's binary_logloss: 0.00290443
[17]	valid_0's binary_logloss: 0.0028138
[18]	valid_0's binary_logloss: 0.00273106
[19]	valid_0's binary_logloss: 0.0026545
[20]	valid_0's binary_logloss: 0.00257815
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.00250763
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.00244077
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.00237604
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.00231944
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.00226658
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.0022112
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.00216042
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.00211258
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.00206916
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.00202698
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.00198903
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.00195408
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.0019192
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.00188232
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.00185025
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.00181846
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.0017884
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.00176044
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.0017338
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.00170899
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.00168766
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.00166677
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.00164847
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.00163166
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.00161641
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.00160088
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.00158669
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.00157289
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.00156017
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.00154851
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.00153913
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.00153125
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.00152403
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.0015165
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.00151046
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.00150443
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.00149912
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.00149469
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.00149064
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.00148717
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.00148334
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.00148081
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.00147797
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.00147557
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.0014736
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.00147289
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.00147256
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.0014726
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.00147298
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.00147369
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.00147486
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.00147634
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.00147808
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.00148009
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.00148234
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.00148317
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.00148419
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.00148538
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.00148672
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.00148821
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.00149146
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.00149487
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.00149846
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.00150213
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.00150592
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.00150981
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.00151403
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.00151836
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.00152254
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.00152705
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.00153142
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.00153586
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.00154036
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.00154491
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.00154951
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

Trening klas:  95%|█████████▌| 475/500 [54:20<03:47,  9.12s/klasa, klasa=class_475, F1_klasy=0.0000, F1_macro=0.6179, drzewa=67]




Trening klas:  95%|█████████▌| 476/500 [54:20<03:02,  7.58s/klasa, klasa=class_475, F1_klasy=0.0000, F1_macro=0.6179, drzewa=67]

[96]	valid_0's binary_logloss: 0.00155307
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.00155803
[1]	valid_0's binary_logloss: 0.624617
[2]	valid_0's binary_logloss: 0.152468
[3]	valid_0's binary_logloss: 0.703043
[4]	valid_0's binary_logloss: 0.701496
[5]	valid_0's binary_logloss: 0.727244
[6]	valid_0's binary_logloss: 0.724668
[7]	valid_0's binary_logloss: 0.722471
[8]	valid_0's binary_logloss: 0.721774
[9]	valid_0's binary_logloss: 0.730718
[10]	valid_0's binary_logloss: 0.729688
[11]	valid_0's binary_logloss: 0.754037
[12]	valid_0's binary_logloss: 0.757884
[13]	valid_0's binary_logloss: 0.76326
[14]	valid_0's binary_logloss: 0.761144
[15]	valid_0's binary_logloss: 0.755058
[16]	valid_0's binary_logloss: 0.893783
[17]	valid_0's binary_logloss: 0.893978
[18]	valid_0's binary_logloss: 0.889225
[19]	valid_0's binary_logloss: 0.887171
[20]	valid_0's binary_logloss: 0.883412
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.882068
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.879453
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.879143
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.875129
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.873184
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.865011
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.865637
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.866879
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

Trening klas:  95%|█████████▌| 476/500 [54:24<03:02,  7.58s/klasa, klasa=class_476, F1_klasy=0.0256, F1_macro=0.6167, drzewa=2]




Trening klas:  95%|█████████▌| 477/500 [54:24<02:27,  6.42s/klasa, klasa=class_476, F1_klasy=0.0256, F1_macro=0.6167, drzewa=2]

[29]	valid_0's binary_logloss: 0.865022
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.861393
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.860173
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.853396
[1]	valid_0's binary_logloss: 0.0525232
[2]	valid_0's binary_logloss: 0.0379097
[3]	valid_0's binary_logloss: 0.030157
[4]	valid_0's binary_logloss: 0.0284694
[5]	valid_0's binary_logloss: 0.0273084
[6]	valid_0's binary_logloss: 0.0255239
[7]	valid_0's binary_logloss: 0.0243573
[8]	valid_0's binary_logloss: 0.0235774
[9]	valid_0's binary_logloss: 0.0228674
[10]	valid_0's binary_logloss: 0.0222159
[11]	valid_0's binary_logloss: 0.0216534
[12]	valid_0's binary_logloss: 0.0210413
[13]	valid_0's binary_logloss: 0.020444
[14]	valid_0's binary_logloss: 0.0199797
[15]	valid_0's binary_logloss: 0.0195043
[16]	valid_0's binary_logloss: 0.0190887
[17]	valid_0's binary_logloss: 0.0186799
[18]	valid_0's binary_logloss: 0.0182942
[19]	valid_0's binary_logloss: 0.0179397
[20]	valid_0's binary_logloss: 0.0176521
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0173399
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0170445
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.0168098
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0165504
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.0162803
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.0159734
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.0157812
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.0154697
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.015307
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.0150455
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.0147627
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.0145637
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.014351
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.0141586
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.0139828
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.0138459
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.0137216
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.0135688
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.0134601
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.0133415
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.0131356
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.0129249
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.0127542
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.0125781
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.0124061
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.0122626
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.0121051
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.0119452
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.0117879
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.011593
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.0114623
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.0113307
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.0111789
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.0110615
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.0109315
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.0107875
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.0106399
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.0104919
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.0103491
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.0102269
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.0100826
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.00993782
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.0098179
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.00968341
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.00953268
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.00943391
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.0093204
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.00920152
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.00906743
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.00895564
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.0088512
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.00867106
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.00852551
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.00838028
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.00825927
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.00816122
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.0080378
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.00793249
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.00782703
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.00771741
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.00762333
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.00749571
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.00740934
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.00733632
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.00724547
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.00712316
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.00702609
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.00689661
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.00677146
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.00665047
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.00657417
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.00651302
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.00644318
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.00636641
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.00629044
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.00620894
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.00612173
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.00607907
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.00601427
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.00593673
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.00580646
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.00572122
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.00562082
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.00552259
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.00542447
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.00534107
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.00527328
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.00521274
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.00514153
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.00507423
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.00501127
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 0.0049972
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 0.00497435
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 0.00490542
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 0.00489572
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[116]	valid_0's binary_logloss: 0.00484995
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[117]	valid_0's binary_logloss: 0.00480268
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[118]	valid_0's binary_logloss: 0.00478786
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[119]	valid_0's binary_logloss: 0.00476942
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[120]	valid_0's binary_logloss: 0.00475177
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[121]	valid_0's binary_logloss: 0.00470859
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[122]	valid_0's binary_logloss: 0.0046754
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[123]	valid_0's binary_logloss: 0.00466197
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[124]	valid_0's binary_logloss: 0.00460846
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[125]	valid_0's binary_logloss: 0.00455709
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[126]	valid_0's binary_logloss: 0.0044913
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[127]	valid_0's binary_logloss: 0.00443526
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[128]	valid_0's binary_logloss: 0.00439461
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[129]	valid_0's binary_logloss: 0.00436133
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[130]	valid_0's binary_logloss: 0.0043226
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[131]	valid_0's binary_logloss: 0.00429554
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[132]	valid_0's binary_logloss: 0.00428918
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[133]	valid_0's binary_logloss: 0.00426456
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[134]	valid_0's binary_logloss: 0.00425759
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[135]	valid_0's binary_logloss: 0.00422343
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[136]	valid_0's binary_logloss: 0.00417498
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[137]	valid_0's binary_logloss: 0.00415263
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[138]	valid_0's binary_logloss: 0.00412385
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[139]	valid_0's binary_logloss: 0.00408036
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[140]	valid_0's binary_logloss: 0.0040448
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[141]	valid_0's binary_logloss: 0.00402696
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[142]	valid_0's binary_logloss: 0.00399837
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[143]	valid_0's binary_logloss: 0.00397456
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[144]	valid_0's binary_logloss: 0.00395543
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[145]	valid_0's binary_logloss: 0.00394871
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[146]	valid_0's binary_logloss: 0.00392929
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[147]	valid_0's binary_logloss: 0.00389807
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[148]	valid_0's binary_logloss: 0.00387092
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[149]	valid_0's binary_logloss: 0.00383461
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[150]	valid_0's binary_logloss: 0.00381329
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[151]	valid_0's binary_logloss: 0.00376822
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[152]	valid_0's binary_logloss: 0.00376175
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[153]	valid_0's binary_logloss: 0.00373938
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[154]	valid_0's binary_logloss: 0.00371743
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[155]	valid_0's binary_logloss: 0.00368129
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[156]	valid_0's binary_logloss: 0.00363956
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[157]	valid_0's binary_logloss: 0.00359921
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[158]	valid_0's binary_logloss: 0.00356871
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[159]	valid_0's binary_logloss: 0.00352596
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[160]	valid_0's binary_logloss: 0.00348358
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[161]	valid_0's binary_logloss: 0.00346575
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[162]	valid_0's binary_logloss: 0.00342707
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[163]	valid_0's binary_logloss: 0.00341244
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[164]	valid_0's binary_logloss: 0.00337827
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[165]	valid_0's binary_logloss: 0.00334872
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[166]	valid_0's binary_logloss: 0.00334033
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[167]	valid_0's binary_logloss: 0.00333222
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[168]	valid_0's binary_logloss: 0.00332436
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[169]	valid_0's binary_logloss: 0.00331725
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[170]	valid_0's binary_logloss: 0.00330988
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[171]	valid_0's binary_logloss: 0.00328928
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[172]	valid_0's binary_logloss: 0.00327048
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[173]	valid_0's binary_logloss: 0.00325205
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[174]	valid_0's binary_logloss: 0.00323398
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[175]	valid_0's binary_logloss: 0.0032225
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[176]	valid_0's binary_logloss: 0.00323236
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[177]	valid_0's binary_logloss: 0.00323024
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[178]	valid_0's binary_logloss: 0.00323735
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[179]	valid_0's binary_logloss: 0.00323972
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[180]	valid_0's binary_logloss: 0.00322771

Trening klas:  95%|█████████▌| 477/500 [54:32<02:27,  6.42s/klasa, klasa=class_477, F1_klasy=0.6667, F1_macro=0.6168, drzewa=300]




Trening klas:  96%|█████████▌| 478/500 [54:32<02:29,  6.81s/klasa, klasa=class_477, F1_klasy=0.6667, F1_macro=0.6168, drzewa=300]

[1]	valid_0's binary_logloss: 0.710681
[2]	valid_0's binary_logloss: 0.297919
[3]	valid_0's binary_logloss: 0.539092
[4]	valid_0's binary_logloss: 0.521199
[5]	valid_0's binary_logloss: 0.504497
[6]	valid_0's binary_logloss: 1.21841
[7]	valid_0's binary_logloss: 1.15626
[8]	valid_0's binary_logloss: 1.05174
[9]	valid_0's binary_logloss: 1.03594
[10]	valid_0's binary_logloss: 1.02642
[11]	valid_0's binary_logloss: 1.01149
[12]	valid_0's binary_logloss: 0.983324
[13]	valid_0's binary_logloss: 0.960335
[14]	valid_0's binary_logloss: 0.944763
[15]	valid_0's binary_logloss: 0.925614
[16]	valid_0's binary_logloss: 0.973564
[17]	valid_0's binary_logloss: 0.96784
[18]	valid_0's binary_logloss: 0.942589
[19]	valid_0's binary_logloss: 0.925425
[20]	valid_0's binary_logloss: 0.912707
[21]	valid_0's binary_logloss: 0.892791
[22]	valid_0's binary_logloss: 0.869716
[23]	valid_0's binary_logloss: 0.858533
[24]	valid_0's binary_logloss: 0.842975
[25]	valid_0's binary_logloss: 0.829355
[26]	valid_0's binary_logloss: 0.824885
[27]	valid_0's binary_logloss: 0.81236
[28]	valid_0's binary_logloss: 0.801121
[29]	valid_0's binary_logloss: 0.794882
[30]	valid_0's binary_logloss: 0.788994
[31]	valid_0's binary_logloss: 0.846309
[32]	valid_0's binary_logloss: 0.834298

Trening klas:  96%|█████████▌| 478/500 [54:36<02:29,  6.81s/klasa, klasa=class_478, F1_klasy=0.0746, F1_macro=0.6156, drzewa=2]




Trening klas:  96%|█████████▌| 479/500 [54:36<02:06,  6.04s/klasa, klasa=class_478, F1_klasy=0.0746, F1_macro=0.6156, drzewa=2]

[1]	valid_0's binary_logloss: 0.100517
[2]	valid_0's binary_logloss: 0.0843665
[3]	valid_0's binary_logloss: 0.0780214
[4]	valid_0's binary_logloss: 0.073774
[5]	valid_0's binary_logloss: 0.0701838
[6]	valid_0's binary_logloss: 0.0671308
[7]	valid_0's binary_logloss: 0.0645059
[8]	valid_0's binary_logloss: 0.0628381
[9]	valid_0's binary_logloss: 0.0612295
[10]	valid_0's binary_logloss: 0.05996
[11]	valid_0's binary_logloss: 0.0588628
[12]	valid_0's binary_logloss: 0.0571489
[13]	valid_0's binary_logloss: 0.0558575
[14]	valid_0's binary_logloss: 0.0546304
[15]	valid_0's binary_logloss: 0.0536589
[16]	valid_0's binary_logloss: 0.0528611
[17]	valid_0's binary_logloss: 0.0520369
[18]	valid_0's binary_logloss: 0.0512346
[19]	valid_0's binary_logloss: 0.0505838
[20]	valid_0's binary_logloss: 0.0499223
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0488394
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0481157
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.0473941
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0466496
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.0459015
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.045272
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.0446327
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.0440066
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.0433391
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.0427202
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.0420427
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.041318
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.0406611
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.0400326
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.0393798
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.0387948
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.038281
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.0377598
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.0373067
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.0367498
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.036264
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.0357849
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.0352921
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.0347782
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.0342686
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.0337551
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.0332215
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.0327977
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.0323061
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.0317799
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.0313949
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.0310122
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.0306361
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.0301768
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.0298125
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.0293726
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.0289559
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.028471
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.0282071
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.0277506
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.0274095
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.0270741
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.0267606
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.0264266
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.026146
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.0257665
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.0253709
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.0250145
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.0246801
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.0243314
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.0239661
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.0236238
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.023278
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.0229941
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.0226575
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.0223184
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.0219954
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.0216891
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.0214445
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.0212066
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.0209226
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.0206552
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.0204022
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.0201549
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.0198854
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.0196927
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.0195291
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.0193333
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.0191636
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.0189426
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.0187267
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.0184584
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.0182059
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.0179733
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.0178122
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.0176794
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.0175484
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.0173682
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.017235
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.0170247
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.016879
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.0166785
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.0164922
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.0163153
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.0161618
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.0160446
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.0158953
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.0157523
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.0156117
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.0154673
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.0152979
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 0.0151341
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 0.0149742
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 0.0148709
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 0.0147109
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[116]	valid_0's binary_logloss: 0.0145977
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[117]	valid_0's binary_logloss: 0.0144914
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[118]	valid_0's binary_logloss: 0.0144102
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[119]	valid_0's binary_logloss: 0.0143164
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[120]	valid_0's binary_logloss: 0.0142137
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[121]	valid_0's binary_logloss: 0.0140964
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[122]	valid_0's binary_logloss: 0.0139889
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[123]	valid_0's binary_logloss: 0.0138811
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[124]	valid_0's binary_logloss: 0.0138027
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[125]	valid_0's binary_logloss: 0.0137322
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[126]	valid_0's binary_logloss: 0.0136835
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[127]	valid_0's binary_logloss: 0.0136123
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[128]	valid_0's binary_logloss: 0.0135213
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[129]	valid_0's binary_logloss: 0.0134942
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[130]	valid_0's binary_logloss: 0.0134466
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[131]	valid_0's binary_logloss: 0.0133547
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[132]	valid_0's binary_logloss: 0.0133122
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[133]	valid_0's binary_logloss: 0.0132609
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[134]	valid_0's binary_logloss: 0.0131558
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[135]	valid_0's binary_logloss: 0.0131069
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[136]	valid_0's binary_logloss: 0.0130265
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[137]	valid_0's binary_logloss: 0.0129849
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[138]	valid_0's binary_logloss: 0.0129034
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[139]	valid_0's binary_logloss: 0.0127855
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[140]	valid_0's binary_logloss: 0.0126844
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[141]	valid_0's binary_logloss: 0.0126365
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[142]	valid_0's binary_logloss: 0.0125819
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[143]	valid_0's binary_logloss: 0.0125318
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[144]	valid_0's binary_logloss: 0.0124886
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[145]	valid_0's binary_logloss: 0.0124364
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[146]	valid_0's binary_logloss: 0.012364
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[147]	valid_0's binary_logloss: 0.012308
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[148]	valid_0's binary_logloss: 0.0122714
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[149]	valid_0's binary_logloss: 0.0122039
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[150]	valid_0's binary_logloss: 0.0121393
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[151]	valid_0's binary_logloss: 0.0120971
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[152]	valid_0's binary_logloss: 0.0120624
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[153]	valid_0's binary_logloss: 0.0120323
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[154]	valid_0's binary_logloss: 0.0120203
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[155]	valid_0's binary_logloss: 0.0119853
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[156]	valid_0's binary_logloss: 0.0119973
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[157]	valid_0's binary_logloss: 0.0119824
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[158]	valid_0's binary_logloss: 0.0120027
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[159]	valid_0's binary_logloss: 0.0120017
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[160]	valid_0's binary_logloss: 0.0119952
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[161]	valid_0's binary_logloss: 0.0119368
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[162]	valid_0's binary_logloss: 0.011888
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[163]	valid_0's binary_logloss: 0.011838
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[164]	valid_0's binary_logloss: 0.0117993
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[165]	valid_0's binary_logloss: 0.0117444
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[166]	valid_0's binary_logloss: 0.0117166
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[167]	valid_0's binary_logloss: 0.0117003
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[168]	valid_0's binary_logloss: 0.0116785
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[169]	valid_0's binary_logloss: 0.0116447
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[170]	valid_0's binary_logloss: 0.0116369
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[171]	valid_0's binary_logloss: 0.011583
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[172]	valid_0's binary_logloss: 0.0115488
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[173]	valid_0's binary_logloss: 0.0115052
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[174]	valid_0's binary_logloss: 0.0114625
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[175]	valid_0's binary_logloss: 0.0114205
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[176]	valid_0's binary_logloss: 0.0113769
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[177]	valid_0's binary_logloss: 0.011326
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[178]	valid_0's binary_logloss: 0.0112848
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[179]	valid_0's binary_logloss: 0.0112308
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[180]	valid_0's binary_logloss: 0.0111971
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[181]	valid_0's binary_logloss: 0.0112131
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[182]	valid_0's binary_logloss: 0.0112106
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[183]	valid_0's binary_logloss: 0.0112091
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[184]	valid_0's binary_logloss: 0.0112274
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

Trening klas:  96%|█████████▌| 479/500 [54:47<02:06,  6.04s/klasa, klasa=class_479, F1_klasy=0.3077, F1_macro=0.6150, drzewa=270]




Trening klas:  96%|█████████▌| 480/500 [54:47<02:29,  7.48s/klasa, klasa=class_479, F1_klasy=0.3077, F1_macro=0.6150, drzewa=270]

[299]	valid_0's binary_logloss: 0.0101914
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[300]	valid_0's binary_logloss: 0.010195
[1]	valid_0's binary_logloss: 0.300154
[2]	valid_0's binary_logloss: 0.190639
[3]	valid_0's binary_logloss: 0.500274
[4]	valid_0's binary_logloss: 0.501305
[5]	valid_0's binary_logloss: 0.496193
[6]	valid_0's binary_logloss: 0.798609
[7]	valid_0's binary_logloss: 0.797713
[8]	valid_0's binary_logloss: 0.795452
[9]	valid_0's binary_logloss: 0.795414
[10]	valid_0's binary_logloss: 0.790935
[11]	valid_0's binary_logloss: 0.796929
[12]	valid_0's binary_logloss: 0.781924
[13]	valid_0's binary_logloss: 0.786357
[14]	valid_0's binary_logloss: 0.787008
[15]	valid_0's binary_logloss: 0.785108
[16]	valid_0's binary_logloss: 0.783173
[17]	valid_0's binary_logloss: 0.781246
[18]	valid_0's binary_logloss: 0.781006
[19]	valid_0's binary_logloss: 0.780508
[20]	valid_0's binary_logloss: 0.792674
[21]	valid_0's binary_logloss: 1.1725
[22]	valid_0's binary_logloss: 1.1411
[23]	valid_0's binary_logloss: 1.12292
[24]	valid_0's binary_logloss: 1.11424
[25]	valid_0's binary_logloss: 1.10937
[26]	valid_0's binary_logloss: 1.10349
[27]	valid_0's binary_logloss: 1.101
[28]	valid_0's binary_logloss: 1.10079
[29]	valid_0's binary_logloss: 1.09847
[30]	valid_0's binary_logloss: 1.09591
[31]	valid_0's binary_logloss: 1.0931
[32]	valid_0's binary_logloss: 1.08991

Trening klas:  96%|█████████▌| 480/500 [54:51<02:29,  7.48s/klasa, klasa=class_480, F1_klasy=0.1707, F1_macro=0.6141, drzewa=2]




Trening klas:  96%|█████████▌| 481/500 [54:51<02:04,  6.53s/klasa, klasa=class_480, F1_klasy=0.1707, F1_macro=0.6141, drzewa=2]

[1]	valid_0's binary_logloss: 0.00926848
[2]	valid_0's binary_logloss: 0.00586454
[3]	valid_0's binary_logloss: 0.00536932
[4]	valid_0's binary_logloss: 0.0050375
[5]	valid_0's binary_logloss: 0.00466563
[6]	valid_0's binary_logloss: 0.00433692
[7]	valid_0's binary_logloss: 0.0040663
[8]	valid_0's binary_logloss: 0.00382155
[9]	valid_0's binary_logloss: 0.00359458
[10]	valid_0's binary_logloss: 0.00338942
[11]	valid_0's binary_logloss: 0.00316586
[12]	valid_0's binary_logloss: 0.00296576
[13]	valid_0's binary_logloss: 0.00281701
[14]	valid_0's binary_logloss: 0.00266557
[15]	valid_0's binary_logloss: 0.00252271
[16]	valid_0's binary_logloss: 0.00239221
[17]	valid_0's binary_logloss: 0.00226878
[18]	valid_0's binary_logloss: 0.00215809
[19]	valid_0's binary_logloss: 0.00204318
[20]	valid_0's binary_logloss: 0.00193912
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.00184496
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.00175229
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.00166275
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.00158321
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.00150778
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.00143395
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.00136321
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.00129629
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.00123256
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.00117523
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.00111979
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.00107001
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.00102295
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.000977805
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.00093518
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.00089011
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.000846601
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.000805914
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.000765124
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.000727907
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.00069097
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.000657454
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.000624179
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.000592814
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.000563161
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.000535626
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.000509471
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.000484628
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.000461029
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.00043837
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.000416933
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.000396583
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.000377265
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.000358883
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.000341469
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.000325196
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.000309128
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.000293883
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.000279431
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.00026572
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.00025267
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.000240294
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.000228545
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.000217565
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.00020698
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.000197493
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.000187952
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.00017928
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.00017347
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.000165906
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.000158147
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.000150735
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.000143764
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.000137069
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.000130651
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.000124844
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.000119237
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.000113216
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.000109217
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.000103802
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 9.91689e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 9.59146e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 9.17066e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 8.84499e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 8.43463e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 8.07534e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 7.73966e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 7.39652e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 7.07116e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 6.77644e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 6.47246e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 6.23424e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 5.94993e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 5.61847e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 5.41124e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 5.17514e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 4.89755e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 4.70523e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 4.50495e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 4.3286e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 4.17615e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 4.03142e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 3.92259e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 3.84534e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 3.68609e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 3.63883e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 3.53157e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 3.43157e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 3.27643e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 3.18784e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 3.08184e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 2.95865e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 2.85818e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 2.76392e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 2.65875e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[116]	valid_0's binary_logloss: 2.56287e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[117]	valid_0's binary_logloss: 2.42313e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[118]	valid_0's binary_logloss: 2.35151e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[119]	valid_0's binary_logloss: 2.28248e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[120]	valid_0's binary_logloss: 2.18256e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[121]	valid_0's binary_logloss: 2.14315e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[122]	valid_0's binary_logloss: 2.07369e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[123]	valid_0's binary_logloss: 1.99328e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[124]	valid_0's binary_logloss: 1.95038e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[125]	valid_0's binary_logloss: 1.91168e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[126]	valid_0's binary_logloss: 1.81829e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[127]	valid_0's binary_logloss: 1.76781e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[128]	valid_0's binary_logloss: 1.7289e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[129]	valid_0's binary_logloss: 1.7208e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[130]	valid_0's binary_logloss: 1.6475e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[131]	valid_0's binary_logloss: 1.56893e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[132]	valid_0's binary_logloss: 1.49565e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[133]	valid_0's binary_logloss: 1.42724e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[134]	valid_0's binary_logloss: 1.36794e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[135]	valid_0's binary_logloss: 1.35894e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[136]	valid_0's binary_logloss: 1.32176e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[137]	valid_0's binary_logloss: 1.30749e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[138]	valid_0's binary_logloss: 1.30378e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[139]	valid_0's binary_logloss: 1.2871e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[140]	valid_0's binary_logloss: 1.27847e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[141]	valid_0's binary_logloss: 1.26288e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[142]	valid_0's binary_logloss: 1.21843e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[143]	valid_0's binary_logloss: 1.20209e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[144]	valid_0's binary_logloss: 1.1849e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[145]	valid_0's binary_logloss: 1.17092e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[146]	valid_0's binary_logloss: 1.1302e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[147]	valid_0's binary_logloss: 1.11084e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[148]	valid_0's binary_logloss: 1.09325e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[149]	valid_0's binary_logloss: 1.06872e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[150]	valid_0's binary_logloss: 1.05207e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[151]	valid_0's binary_logloss: 1.01253e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[152]	valid_0's binary_logloss: 9.85127e-06
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[153]	valid_0's binary_logloss: 9.85307e-06
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[154]	valid_0's binary_logloss: 9.53288e-06
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[155]	valid_0's binary_logloss: 9.22999e-06
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[156]	valid_0's binary_logloss: 9.05598e-06
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[157]	valid_0's binary_logloss: 8.90142e-06
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[158]	valid_0's binary_logloss: 8.61748e-06
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[159]	valid_0's binary_logloss: 8.17972e-06
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[160]	valid_0's binary_logloss: 7.98429e-06
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[161]	valid_0's binary_logloss: 7.79614e-06
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[162]	valid_0's binary_logloss: 7.51638e-06
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[163]	valid_0's binary_logloss: 7.67314e-06
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[164]	valid_0's binary_logloss: 7.51619e-06
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[165]	valid_0's binary_logloss: 7.4048e-06
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[166]	valid_0's binary_logloss: 7.42459e-06
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[167]	valid_0's binary_logloss: 7.26342e-06
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[168]	valid_0's binary_logloss: 7.19848e-06
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[169]	valid_0's binary_logloss: 7.17555e-06
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[170]	valid_0's binary_logloss: 7.17226e-06
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[171]	valid_0's binary_logloss: 7.06245e-06
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[172]	valid_0's binary_logloss: 7.06511e-06
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[173]	valid_0's binary_logloss: 7.06688e-06
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[174]	valid_0's binary_logloss: 7.06813e-06
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[175]	valid_0's binary_logloss: 6.93356e-06
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[176]	valid_0's binary_logloss: 7.01408e-06
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[177]	valid_0's binary_logloss: 6.97471e-06
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[178]	valid_0's binary_logloss: 6.89449e-06
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[179]	valid_0's binary_logloss: 6.83035e-06
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[180]	valid_0's binary_logloss: 6.86958e-06
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[181]	valid_0's binary_logloss: 6.93101e-06
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[182]	valid_0's binary_logloss: 6.7864e-06

Trening klas:  96%|█████████▌| 481/500 [54:58<02:04,  6.53s/klasa, klasa=class_481, F1_klasy=0.0000, F1_macro=0.6128, drzewa=269]




Trening klas:  96%|█████████▋| 482/500 [54:58<02:00,  6.68s/klasa, klasa=class_481, F1_klasy=0.0000, F1_macro=0.6128, drzewa=269]

[299]	valid_0's binary_logloss: 4.76844e-06
[1]	valid_0's binary_logloss: 0.19533
[2]	valid_0's binary_logloss: 0.140028
[3]	valid_0's binary_logloss: 0.489997
[4]	valid_0's binary_logloss: 0.486012
[5]	valid_0's binary_logloss: 0.488024
[6]	valid_0's binary_logloss: 0.497055
[7]	valid_0's binary_logloss: 0.496922
[8]	valid_0's binary_logloss: 0.493897
[9]	valid_0's binary_logloss: 0.493831
[10]	valid_0's binary_logloss: 0.494179
[11]	valid_0's binary_logloss: 0.704331
[12]	valid_0's binary_logloss: 0.705044
[13]	valid_0's binary_logloss: 0.705235
[14]	valid_0's binary_logloss: 0.705054
[15]	valid_0's binary_logloss: 0.704708
[16]	valid_0's binary_logloss: 0.704906
[17]	valid_0's binary_logloss: 0.704471
[18]	valid_0's binary_logloss: 0.706422
[19]	valid_0's binary_logloss: 0.706301
[20]	valid_0's binary_logloss: 0.706142
[21]	valid_0's binary_logloss: 0.711727
[22]	valid_0's binary_logloss: 0.712964
[23]	valid_0's binary_logloss: 0.711069
[24]	valid_0's binary_logloss: 0.70495
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.693501
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.682054
[27]	valid_0's binary_logloss: 0.68163
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.676993
[29]	valid_0's binary_logloss: 0.674588
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

Trening klas:  96%|█████████▋| 482/500 [55:02<02:00,  6.68s/klasa, klasa=class_482, F1_klasy=0.1538, F1_macro=0.6118, drzewa=2]




Trening klas:  97%|█████████▋| 483/500 [55:02<01:38,  5.78s/klasa, klasa=class_482, F1_klasy=0.1538, F1_macro=0.6118, drzewa=2]

[30]	valid_0's binary_logloss: 0.671181
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.668742
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.665613
[1]	valid_0's binary_logloss: 0.0371961
[2]	valid_0's binary_logloss: 0.0287783
[3]	valid_0's binary_logloss: 0.0243225
[4]	valid_0's binary_logloss: 0.0217754
[5]	valid_0's binary_logloss: 0.0193858
[6]	valid_0's binary_logloss: 0.0176182
[7]	valid_0's binary_logloss: 0.0167219
[8]	valid_0's binary_logloss: 0.0155089
[9]	valid_0's binary_logloss: 0.014914
[10]	valid_0's binary_logloss: 0.0142077
[11]	valid_0's binary_logloss: 0.0136666
[12]	valid_0's binary_logloss: 0.013123
[13]	valid_0's binary_logloss: 0.012495
[14]	valid_0's binary_logloss: 0.0120187
[15]	valid_0's binary_logloss: 0.0116102
[16]	valid_0's binary_logloss: 0.0111708
[17]	valid_0's binary_logloss: 0.0107692
[18]	valid_0's binary_logloss: 0.0103594
[19]	valid_0's binary_logloss: 0.00997857
[20]	valid_0's binary_logloss: 0.00965205
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.00930867
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.00899994
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.00875606
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.00849451
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.0082186
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.00808031
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.00789868
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.00761433
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.00740543
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.0072734
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.00704998
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.00683429
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.00662642
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.0064166
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.00622578
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.00612863
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.00603294
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.00594575
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.00585069
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.00575721
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.00559846
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.00544164
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.00530234
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.00518547
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.00507166
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.00492954
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.00484834
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.00475364
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.00467822
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.00455113
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.00445683
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.00434556
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.00424593
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.00418603
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.00413716
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.00406645
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.00399836
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.00392642
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.00387936
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.00381671
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.00374058
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.00371361
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.00369112
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.00366231
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.00363122
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.00359477
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.00354805
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.00354751
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.00350364
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.00349332
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.00349074
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.00344546
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.00343579
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.00343156
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.00340625
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.00338974
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.00339492
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.00337065
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.00334747
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.00333151
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.00327579
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.00324609
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.00324162
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.00322436
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.00317209
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.00314495
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.00312282
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.00310934
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.00309412
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.00302155
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.0029916
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.00299516
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.00296985
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.0029704
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.0029383
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.00291979
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.00286428
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.00284841
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.00279638
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.00277924
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.00272005
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.00271929
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.00271945
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.00271981
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.00271907
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.00271399
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.00269581
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.00268649
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.00267541
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.00266007
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.00265519
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 0.00267634
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 0.00265758
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 0.00267288
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 0.00267688
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[116]	valid_0's binary_logloss: 0.00266716
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[117]	valid_0's binary_logloss: 0.0026431
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[118]	valid_0's binary_logloss: 0.00261983
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[119]	valid_0's binary_logloss: 0.00261518
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[120]	valid_0's binary_logloss: 0.00259314
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[121]	valid_0's binary_logloss: 0.00258174
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[122]	valid_0's binary_logloss: 0.00258137
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[123]	valid_0's binary_logloss: 0.00257178
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[124]	valid_0's binary_logloss: 0.00254842
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[125]	valid_0's binary_logloss: 0.00252866
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[126]	valid_0's binary_logloss: 0.00253559
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[127]	valid_0's binary_logloss: 0.00254285
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[128]	valid_0's binary_logloss: 0.00253311
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[129]	valid_0's binary_logloss: 0.00254071
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[130]	valid_0's binary_logloss: 0.00252365
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[131]	valid_0's binary_logloss: 0.00251912
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[132]	valid_0's binary_logloss: 0.00251939
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[133]	valid_0's binary_logloss: 0.00252026
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[134]	valid_0's binary_logloss: 0.00252121
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[135]	valid_0's binary_logloss: 0.00251755
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[136]	valid_0's binary_logloss: 0.00248657
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[137]	valid_0's binary_logloss: 0.00248549
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[138]	valid_0's binary_logloss: 0.00249511
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[139]	valid_0's binary_logloss: 0.00250488
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[140]	valid_0's binary_logloss: 0.00248571
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[141]	valid_0's binary_logloss: 0.00247825
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[142]	valid_0's binary_logloss: 0.00248465
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[143]	valid_0's binary_logloss: 0.00247914
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[144]	valid_0's binary_logloss: 0.00247475
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[145]	valid_0's binary_logloss: 0.00246599
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[146]	valid_0's binary_logloss: 0.00246392
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[147]	valid_0's binary_logloss: 0.00246196
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[148]	valid_0's binary_logloss: 0.00244895
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[149]	valid_0's binary_logloss: 0.00243294
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[150]	valid_0's binary_logloss: 0.0024206
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[151]	valid_0's binary_logloss: 0.00241438
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[152]	valid_0's binary_logloss: 0.00242508
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[153]	valid_0's binary_logloss: 0.00243525
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[154]	valid_0's binary_logloss: 0.00242756
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[155]	valid_0's binary_logloss: 0.0024224
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[156]	valid_0's binary_logloss: 0.00242101
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[157]	valid_0's binary_logloss: 0.00242534
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[158]	valid_0's binary_logloss: 0.00243227
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[159]	valid_0's binary_logloss: 0.00243816
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[160]	valid_0's binary_logloss: 0.00243932
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[161]	valid_0's binary_logloss: 0.00244664
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[162]	valid_0's binary_logloss: 0.00243872
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[163]	valid_0's binary_logloss: 0.00243302
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[164]	valid_0's binary_logloss: 0.00242303
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[165]	valid_0's binary_logloss: 0.00241562
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[166]	valid_0's binary_logloss: 0.00242421
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[167]	valid_0's binary_logloss: 0.0024183
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[168]	valid_0's binary_logloss: 0.00241638
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[169]	valid_0's binary_logloss: 0.00239799
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[170]	valid_0's binary_logloss: 0.00239293
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[171]	valid_0's binary_logloss: 0.00238076
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[172]	valid_0's binary_logloss: 0.00238365
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[173]	valid_0's binary_logloss: 0.00238029
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[174]	valid_0's binary_logloss: 0.00237547
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[175]	valid_0's binary_logloss: 0.00238552
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[176]	valid_0's binary_logloss: 0.00237895
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[177]	valid_0's binary_logloss: 0.00237829
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[178]	valid_0's binary_logloss: 0.00238752
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[179]	valid_0's binary_logloss: 0.00238167
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[180]	valid_0's binary_logloss: 0.00238011
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[181]	valid_0's binary_logloss: 0.00238369

Trening klas:  97%|█████████▋| 483/500 [55:10<01:38,  5.78s/klasa, klasa=class_483, F1_klasy=0.4000, F1_macro=0.6114, drzewa=185]




Trening klas:  97%|█████████▋| 484/500 [55:10<01:42,  6.38s/klasa, klasa=class_483, F1_klasy=0.4000, F1_macro=0.6114, drzewa=185]

[214]	valid_0's binary_logloss: 0.00238096
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[215]	valid_0's binary_logloss: 0.00238606
[1]	valid_0's binary_logloss: 0.73634
[2]	valid_0's binary_logloss: 0.349188
[3]	valid_0's binary_logloss: 0.984045
[4]	valid_0's binary_logloss: 0.981541
[5]	valid_0's binary_logloss: 0.990029
[6]	valid_0's binary_logloss: 1.14104
[7]	valid_0's binary_logloss: 1.13121
[8]	valid_0's binary_logloss: 1.12244
[9]	valid_0's binary_logloss: 1.11886
[10]	valid_0's binary_logloss: 1.11273
[11]	valid_0's binary_logloss: 1.11293
[12]	valid_0's binary_logloss: 1.10988
[13]	valid_0's binary_logloss: 1.10054
[14]	valid_0's binary_logloss: 1.09889
[15]	valid_0's binary_logloss: 1.09709
[16]	valid_0's binary_logloss: 1.09538
[17]	valid_0's binary_logloss: 1.09002
[18]	valid_0's binary_logloss: 1.08715
[19]	valid_0's binary_logloss: 1.08178
[20]	valid_0's binary_logloss: 1.07679
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 1.07627
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 1.07608
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 1.07589
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 1.07552
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 1.07532
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 1.07525
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 1.06984
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 1.06609
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 1.06739
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 1.06926
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 1.1844
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 1.19523

Trening klas:  97%|█████████▋| 484/500 [55:13<01:42,  6.38s/klasa, klasa=class_484, F1_klasy=0.0308, F1_macro=0.6102, drzewa=2]




Trening klas:  97%|█████████▋| 485/500 [55:13<01:21,  5.46s/klasa, klasa=class_484, F1_klasy=0.0308, F1_macro=0.6102, drzewa=2]

[1]	valid_0's binary_logloss: 0.28425
[2]	valid_0's binary_logloss: 0.218565
[3]	valid_0's binary_logloss: 0.173189
[4]	valid_0's binary_logloss: 0.157907
[5]	valid_0's binary_logloss: 0.154429
[6]	valid_0's binary_logloss: 0.150735
[7]	valid_0's binary_logloss: 0.128485
[8]	valid_0's binary_logloss: 0.12651
[9]	valid_0's binary_logloss: 0.125863
[10]	valid_0's binary_logloss: 0.125315
[11]	valid_0's binary_logloss: 0.124068
[12]	valid_0's binary_logloss: 0.123076
[13]	valid_0's binary_logloss: 0.122427
[14]	valid_0's binary_logloss: 0.12164
[15]	valid_0's binary_logloss: 0.120828
[16]	valid_0's binary_logloss: 0.12001
[17]	valid_0's binary_logloss: 0.119302
[18]	valid_0's binary_logloss: 0.118642
[19]	valid_0's binary_logloss: 0.118315
[20]	valid_0's binary_logloss: 0.117891
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.117435
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.117111
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.116807
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.116507
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.116231
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.115681
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.115261
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.11494
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.114698
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.114359
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.114233
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.113937
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.113803
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.113716
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.113578
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.113175
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.113118
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.112721
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.112371
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.11201
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.111578
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.111192
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.110971
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.110732
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.110463
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.110322
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.109792
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.109184
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.10877
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.108482
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.108218
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.10792
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.10764
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.10749
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.107232
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.106982
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.106779
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.106611
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.106691
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.106655
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.106347
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.106542
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.1062
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.106071
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.10573
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.105479
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.105406
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.105212
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.104992
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.104795
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.104716
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.104674
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.10452
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.104569
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.104564
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.104551
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.104531
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.104609
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.10445
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.104542
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.104377
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.104197
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.104026
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.103851
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.103736
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.103787
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.103669
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.103729
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.103698
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.103796
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.103606
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.103513
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.103417
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.103506
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.103407
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.103254
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.103259
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.103169
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.103222
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.103084
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.103087
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.103141
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.10306
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.102986
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.102965
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.101646
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.100558
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.099484
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.098496
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.0976103
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.0975116
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 0.0975797
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 0.0974772
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 0.0973926
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 0.0974906
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[116]	valid_0's binary_logloss: 0.097588
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[117]	valid_0's binary_logloss: 0.0977338
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[118]	valid_0's binary_logloss: 0.0978516
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[119]	valid_0's binary_logloss: 0.0979528
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[120]	valid_0's binary_logloss: 0.0980191
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[121]	valid_0's binary_logloss: 0.0981878
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[122]	valid_0's binary_logloss: 0.0980542
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[123]	valid_0's binary_logloss: 0.0979537
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[124]	valid_0's binary_logloss: 0.0978297
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[125]	valid_0's binary_logloss: 0.0977093
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[126]	valid_0's binary_logloss: 0.0969209
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[127]	valid_0's binary_logloss: 0.0960984
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[128]	valid_0's binary_logloss: 0.0952558
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[129]	valid_0's binary_logloss: 0.0952631
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[130]	valid_0's binary_logloss: 0.0953632
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[131]	valid_0's binary_logloss: 0.0954296
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[132]	valid_0's binary_logloss: 0.0955178
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[133]	valid_0's binary_logloss: 0.095582
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[134]	valid_0's binary_logloss: 0.0956754
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[135]	valid_0's binary_logloss: 0.0957768
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[136]	valid_0's binary_logloss: 0.0957024
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[137]	valid_0's binary_logloss: 0.0957299
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[138]	valid_0's binary_logloss: 0.0956343
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[139]	valid_0's binary_logloss: 0.0955882
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[140]	valid_0's binary_logloss: 0.0955879
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[141]	valid_0's binary_logloss: 0.095611
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[142]	valid_0's binary_logloss: 0.0951552
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[143]	valid_0's binary_logloss: 0.095048
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[144]	valid_0's binary_logloss: 0.094493
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[145]	valid_0's binary_logloss: 0.0945744
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[146]	valid_0's binary_logloss: 0.0946015
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[147]	valid_0's binary_logloss: 0.0945323
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[148]	valid_0's binary_logloss: 0.0944495
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[149]	valid_0's binary_logloss: 0.0943396
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[150]	valid_0's binary_logloss: 0.0943069
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[151]	valid_0's binary_logloss: 0.0942435
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[152]	valid_0's binary_logloss: 0.0944103
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[153]	valid_0's binary_logloss: 0.0945554
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[154]	valid_0's binary_logloss: 0.0945229
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[155]	valid_0's binary_logloss: 0.0944641
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[156]	valid_0's binary_logloss: 0.0932724
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[157]	valid_0's binary_logloss: 0.0922972
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[158]	valid_0's binary_logloss: 0.0914794
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[159]	valid_0's binary_logloss: 0.0907777
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[160]	valid_0's binary_logloss: 0.0901695
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[161]	valid_0's binary_logloss: 0.0901487
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[162]	valid_0's binary_logloss: 0.0903579
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[163]	valid_0's binary_logloss: 0.0905781
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[164]	valid_0's binary_logloss: 0.0908546
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[165]	valid_0's binary_logloss: 0.0909778
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[166]	valid_0's binary_logloss: 0.0908114
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[167]	valid_0's binary_logloss: 0.0909723
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[168]	valid_0's binary_logloss: 0.0911376
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[169]	valid_0's binary_logloss: 0.0913196
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[170]	valid_0's binary_logloss: 0.0915813
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[171]	valid_0's binary_logloss: 0.0917456
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[172]	valid_0's binary_logloss: 0.0919232
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[173]	valid_0's binary_logloss: 0.0920863
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[174]	valid_0's binary_logloss: 0.092239
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[175]	valid_0's binary_logloss: 0.0923882
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[176]	valid_0's binary_logloss: 0.0925913
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[177]	valid_0's binary_logloss: 0.0925048
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[178]	valid_0's binary_logloss: 0.0927241
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[179]	valid_0's binary_logloss: 0.0925907
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[180]	valid_0's binary_logloss: 0.0927895
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[181]	valid_0's binary_logloss: 0.0928679
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[182]	valid_0's binary_logloss: 0.0930611
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[183]	valid_0's binary_logloss: 0.0932554
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[184]	valid_0's binary_logloss: 0.0934333
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[185]	valid_0's binary_logloss: 0.0936177
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

Trening klas:  97%|█████████▋| 485/500 [55:18<01:21,  5.46s/klasa, klasa=class_485, F1_klasy=0.6138, F1_macro=0.6102, drzewa=190]




Trening klas:  97%|█████████▋| 486/500 [55:18<01:16,  5.44s/klasa, klasa=class_485, F1_klasy=0.6138, F1_macro=0.6102, drzewa=190]

[1]	valid_0's binary_logloss: 0.174103
[2]	valid_0's binary_logloss: 0.137981
[3]	valid_0's binary_logloss: 0.229596
[4]	valid_0's binary_logloss: 0.223396
[5]	valid_0's binary_logloss: 0.221446
[6]	valid_0's binary_logloss: 0.330786
[7]	valid_0's binary_logloss: 0.330355
[8]	valid_0's binary_logloss: 0.329711
[9]	valid_0's binary_logloss: 0.328056
[10]	valid_0's binary_logloss: 0.325846
[11]	valid_0's binary_logloss: 0.350402
[12]	valid_0's binary_logloss: 0.346307
[13]	valid_0's binary_logloss: 0.342696
[14]	valid_0's binary_logloss: 0.338912
[15]	valid_0's binary_logloss: 0.335408
[16]	valid_0's binary_logloss: 0.350988
[17]	valid_0's binary_logloss: 0.346348
[18]	valid_0's binary_logloss: 0.344534
[19]	valid_0's binary_logloss: 0.339897
[20]	valid_0's binary_logloss: 0.339939
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.378693
[22]	valid_0's binary_logloss: 0.377231
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.375302
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.372925
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.367324
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.367078
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.366865
[28]	valid_0's binary_logloss: 0.36447
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.363542
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.361521
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

Trening klas:  97%|█████████▋| 486/500 [55:22<01:16,  5.44s/klasa, klasa=class_486, F1_klasy=0.3333, F1_macro=0.6096, drzewa=2]




Trening klas:  97%|█████████▋| 487/500 [55:22<01:02,  4.79s/klasa, klasa=class_486, F1_klasy=0.3333, F1_macro=0.6096, drzewa=2]

[31]	valid_0's binary_logloss: 0.36013
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.354576
[1]	valid_0's binary_logloss: 0.579617
[2]	valid_0's binary_logloss: 0.21287
[3]	valid_0's binary_logloss: 0.518837
[4]	valid_0's binary_logloss: 0.44874
[5]	valid_0's binary_logloss: 0.444413
[6]	valid_0's binary_logloss: 0.605849
[7]	valid_0's binary_logloss: 0.607175
[8]	valid_0's binary_logloss: 0.608512
[9]	valid_0's binary_logloss: 0.608559
[10]	valid_0's binary_logloss: 0.60855
[11]	valid_0's binary_logloss: 0.606875
[12]	valid_0's binary_logloss: 0.60817
[13]	valid_0's binary_logloss: 0.609207
[14]	valid_0's binary_logloss: 0.609088
[15]	valid_0's binary_logloss: 0.60682
[16]	valid_0's binary_logloss: 0.60454
[17]	valid_0's binary_logloss: 0.604018
[18]	valid_0's binary_logloss: 0.604323
[19]	valid_0's binary_logloss: 0.603614
[20]	valid_0's binary_logloss: 0.6065
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.609276
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.610922
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.610857
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.610437
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.607427
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.606842
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.605747
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.604593
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.601411
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.597981
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.642627
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

Trening klas:  97%|█████████▋| 487/500 [55:24<01:02,  4.79s/klasa, klasa=class_487, F1_klasy=0.1439, F1_macro=0.6087, drzewa=2]




Trening klas:  98%|█████████▊| 488/500 [55:24<00:50,  4.19s/klasa, klasa=class_487, F1_klasy=0.1439, F1_macro=0.6087, drzewa=2]

[32]	valid_0's binary_logloss: 0.637352
[1]	valid_0's binary_logloss: 0.151303
[2]	valid_0's binary_logloss: 0.098611
[3]	valid_0's binary_logloss: 0.0921711
[4]	valid_0's binary_logloss: 0.0876124
[5]	valid_0's binary_logloss: 0.0833474
[6]	valid_0's binary_logloss: 0.0795242
[7]	valid_0's binary_logloss: 0.076149
[8]	valid_0's binary_logloss: 0.0734806
[9]	valid_0's binary_logloss: 0.0706181
[10]	valid_0's binary_logloss: 0.0681171
[11]	valid_0's binary_logloss: 0.0659766
[12]	valid_0's binary_logloss: 0.0638643
[13]	valid_0's binary_logloss: 0.0620366
[14]	valid_0's binary_logloss: 0.0601438
[15]	valid_0's binary_logloss: 0.058552
[16]	valid_0's binary_logloss: 0.0572456
[17]	valid_0's binary_logloss: 0.0558507
[18]	valid_0's binary_logloss: 0.0546539
[19]	valid_0's binary_logloss: 0.0533656
[20]	valid_0's binary_logloss: 0.0521076
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0509669
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0498548
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.0487403
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0477462
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.0469238
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.0460681
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.0452365
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.0444219
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.0436499
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.042864
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.0420389
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.0412622
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.0405788
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.0398608
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.0391566
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.0385073
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.0378768
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.0372037
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.0366065
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.035972
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.0353582
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.0347709
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.0341771
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.0336572
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.033043
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.0324981
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.031926
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.0314062
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.0308558
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.0303873
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.0298337
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.0293323
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.0288149
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.0283606
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.0278497
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.0273985
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.0268983
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.0264639
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.0260054
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.0256902
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.0253545
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.0249963
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.0246335
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.0242915
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.0239618
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.0235756
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.0231782
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.0228543
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.0224912
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.0221533
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.0218728
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.0215797
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.0212504
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.020928
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.0206507
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.0203417
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.0200186
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.0196975
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.0193289
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.0190554
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.018772
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.0185959
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.018319
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.0180489
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.017815
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.0175604
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.0172939
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.0171051
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.0169249
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.0167098
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.0164595
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.0162921
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.016085
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.0159197
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.0157637
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.0155896
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.0154093
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.0152406
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.0150376
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.0149121
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.0147608
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.0146386
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.014533
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.0144601
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.0143307
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.0142068
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.0140767
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.0139642
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.0138571
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.0137095
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.0136235
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 0.013535
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 0.0134681
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 0.0133626
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 0.0132376
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[116]	valid_0's binary_logloss: 0.013147
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[117]	valid_0's binary_logloss: 0.0130615
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[118]	valid_0's binary_logloss: 0.0129549
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[119]	valid_0's binary_logloss: 0.0128372
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[120]	valid_0's binary_logloss: 0.0127071
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[121]	valid_0's binary_logloss: 0.0126191
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[122]	valid_0's binary_logloss: 0.0125216
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[123]	valid_0's binary_logloss: 0.0124319
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[124]	valid_0's binary_logloss: 0.0123568
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[125]	valid_0's binary_logloss: 0.0122815
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[126]	valid_0's binary_logloss: 0.0122308
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[127]	valid_0's binary_logloss: 0.0121723
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[128]	valid_0's binary_logloss: 0.0121265
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[129]	valid_0's binary_logloss: 0.0120975
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[130]	valid_0's binary_logloss: 0.0120537
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[131]	valid_0's binary_logloss: 0.0119403
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[132]	valid_0's binary_logloss: 0.0118717
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[133]	valid_0's binary_logloss: 0.0118117
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[134]	valid_0's binary_logloss: 0.0117486
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[135]	valid_0's binary_logloss: 0.011643
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[136]	valid_0's binary_logloss: 0.0115561
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[137]	valid_0's binary_logloss: 0.0115043
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[138]	valid_0's binary_logloss: 0.0114469
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[139]	valid_0's binary_logloss: 0.0114208
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[140]	valid_0's binary_logloss: 0.0113854
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[141]	valid_0's binary_logloss: 0.0113157
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[142]	valid_0's binary_logloss: 0.0113019
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[143]	valid_0's binary_logloss: 0.011284
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[144]	valid_0's binary_logloss: 0.0112754
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[145]	valid_0's binary_logloss: 0.0112101
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[146]	valid_0's binary_logloss: 0.0111856
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[147]	valid_0's binary_logloss: 0.011117
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[148]	valid_0's binary_logloss: 0.011053
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[149]	valid_0's binary_logloss: 0.0109946
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[150]	valid_0's binary_logloss: 0.0109308
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[151]	valid_0's binary_logloss: 0.0108946
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[152]	valid_0's binary_logloss: 0.0108323
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[153]	valid_0's binary_logloss: 0.0107755
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[154]	valid_0's binary_logloss: 0.0107077
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[155]	valid_0's binary_logloss: 0.0106816
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[156]	valid_0's binary_logloss: 0.0106228
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[157]	valid_0's binary_logloss: 0.0105786
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[158]	valid_0's binary_logloss: 0.0105424
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[159]	valid_0's binary_logloss: 0.010491
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[160]	valid_0's binary_logloss: 0.0104559
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[161]	valid_0's binary_logloss: 0.0104283
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[162]	valid_0's binary_logloss: 0.0104017
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[163]	valid_0's binary_logloss: 0.0103934
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[164]	valid_0's binary_logloss: 0.0103719
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[165]	valid_0's binary_logloss: 0.0103446
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[166]	valid_0's binary_logloss: 0.01034
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[167]	valid_0's binary_logloss: 0.0103283
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[168]	valid_0's binary_logloss: 0.0103093
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[169]	valid_0's binary_logloss: 0.0102706
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[170]	valid_0's binary_logloss: 0.0102908
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[171]	valid_0's binary_logloss: 0.0102631
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[172]	valid_0's binary_logloss: 0.0102341
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[173]	valid_0's binary_logloss: 0.0102078
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[174]	valid_0's binary_logloss: 0.0101681
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[175]	valid_0's binary_logloss: 0.0101612
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[176]	valid_0's binary_logloss: 0.0101517
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[177]	valid_0's binary_logloss: 0.0101348
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[178]	valid_0's binary_logloss: 0.0101014
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[179]	valid_0's binary_logloss: 0.0100858
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[180]	valid_0's binary_logloss: 0.0100957
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[181]	valid_0's binary_logloss: 0.0100724
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[182]	valid_0's binary_logloss: 0.0100608
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[183]	valid_0's binary_logloss: 0.0100462
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[184]	valid_0's binary_logloss: 0.0100421

Trening klas:  98%|█████████▊| 488/500 [55:32<00:50,  4.19s/klasa, klasa=class_488, F1_klasy=0.3704, F1_macro=0.6082, drzewa=285]




Trening klas:  98%|█████████▊| 489/500 [55:32<00:56,  5.17s/klasa, klasa=class_488, F1_klasy=0.3704, F1_macro=0.6082, drzewa=285]

[300]	valid_0's binary_logloss: 0.00916475
[1]	valid_0's binary_logloss: 0.0654624
[2]	valid_0's binary_logloss: 0.0556661
[3]	valid_0's binary_logloss: 0.314772
[4]	valid_0's binary_logloss: 0.306966
[5]	valid_0's binary_logloss: 0.306887
[6]	valid_0's binary_logloss: 0.306022
[7]	valid_0's binary_logloss: 0.305863
[8]	valid_0's binary_logloss: 0.30567
[9]	valid_0's binary_logloss: 0.305621
[10]	valid_0's binary_logloss: 0.305381
[11]	valid_0's binary_logloss: 0.305122
[12]	valid_0's binary_logloss: 0.305061
[13]	valid_0's binary_logloss: 0.304822
[14]	valid_0's binary_logloss: 0.304596
[15]	valid_0's binary_logloss: 0.304969
[16]	valid_0's binary_logloss: 0.304819
[17]	valid_0's binary_logloss: 0.304739
[18]	valid_0's binary_logloss: 0.304588
[19]	valid_0's binary_logloss: 0.304556
[20]	valid_0's binary_logloss: 0.304491
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.304396
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.304353
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.304279
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.304167
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.303288
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

Trening klas:  98%|█████████▊| 489/500 [55:35<00:56,  5.17s/klasa, klasa=class_489, F1_klasy=0.8197, F1_macro=0.6086, drzewa=2]




Trening klas:  98%|█████████▊| 490/500 [55:35<00:45,  4.58s/klasa, klasa=class_489, F1_klasy=0.8197, F1_macro=0.6086, drzewa=2]

[26]	valid_0's binary_logloss: 0.303243
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.303205
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.303368
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.303316
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.303252
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.30318
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.303127
[1]	valid_0's binary_logloss: 0.178601
[2]	valid_0's binary_logloss: 0.0688934
[3]	valid_0's binary_logloss: 0.395362
[4]	valid_0's binary_logloss: 0.394029
[5]	valid_0's binary_logloss: 0.392528
[6]	valid_0's binary_logloss: 1.06817
[7]	valid_0's binary_logloss: 1.06669
[8]	valid_0's binary_logloss: 1.06742
[9]	valid_0's binary_logloss: 1.06785
[10]	valid_0's binary_logloss: 1.06644
[11]	valid_0's binary_logloss: 1.06507
[12]	valid_0's binary_logloss: 1.0357
[13]	valid_0's binary_logloss: 0.996532
[14]	valid_0's binary_logloss: 0.961713
[15]	valid_0's binary_logloss: 0.93045
[16]	valid_0's binary_logloss: 1.02473
[17]	valid_0's binary_logloss: 1.01076
[18]	valid_0's binary_logloss: 0.998696
[19]	valid_0's binary_logloss: 0.984078
[20]	valid_0's binary_logloss: 0.975371
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.965083
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.958059
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.954718
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.952946
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.945227
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.934027
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.925614
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.920209
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

[29]	valid_0's binary_logloss: 0.91663
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.912068
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.90981
[32]	valid_0's binary_logloss: 0.902113

Trening klas:  98%|█████████▊| 490/500 [55:39<00:45,  4.58s/klasa, klasa=class_490, F1_klasy=0.4110, F1_macro=0.6082, drzewa=2]




Trening klas:  98%|█████████▊| 491/500 [55:39<00:39,  4.39s/klasa, klasa=class_490, F1_klasy=0.4110, F1_macro=0.6082, drzewa=2]

[1]	valid_0's binary_logloss: 0.0435658
[2]	valid_0's binary_logloss: 0.028682
[3]	valid_0's binary_logloss: 0.0265839
[4]	valid_0's binary_logloss: 0.0251275
[5]	valid_0's binary_logloss: 0.0232025
[6]	valid_0's binary_logloss: 0.0221391
[7]	valid_0's binary_logloss: 0.0211261
[8]	valid_0's binary_logloss: 0.0201378
[9]	valid_0's binary_logloss: 0.0190824
[10]	valid_0's binary_logloss: 0.0181755
[11]	valid_0's binary_logloss: 0.0174981
[12]	valid_0's binary_logloss: 0.0169989
[13]	valid_0's binary_logloss: 0.0164485
[14]	valid_0's binary_logloss: 0.0159099
[15]	valid_0's binary_logloss: 0.0155101
[16]	valid_0's binary_logloss: 0.0149692
[17]	valid_0's binary_logloss: 0.0145464
[18]	valid_0's binary_logloss: 0.0141449
[19]	valid_0's binary_logloss: 0.0137794
[20]	valid_0's binary_logloss: 0.0133255
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0129299
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0125147
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.0121646
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0118278
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.0114804
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.0111709
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.0109471
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.0106118
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.0103279
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.0100822
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.00980445
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.00957311
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.00935247
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.00914199
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.00896211
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.00871463
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.00849273
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.00825612
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.00803761
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.0078254
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.00759359
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.00737753
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.00716295
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.0069591
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.00675634
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.00666274
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.00650044
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.00640914
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.0062289
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.00612672
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.00601467
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.0058797
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.0057805
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.00569033
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.00559215
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.00551363
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.00540036
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.0053181
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.00520481
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.00512206
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.0049749
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.00487495
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.00477911
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.00470124
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.0046123
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.00451095
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.00439787
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.00427261
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.00416186
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.00405315
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.00397766
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.00389473
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.00383126
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.00374453
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.00369268
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.00360294
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.00353057
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.00345624
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.0033989
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.00333944
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.00326894
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.00317777
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.00312414
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.0030671
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.00301425
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.0029538
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.00287451
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.0028148
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.00278631
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.00273269
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.00267933
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.00262087
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.00256358
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.00250921
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.00245322
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.00241974
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.00238075
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.00234405
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.00232089
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.00228879
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.00223719
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.00221984
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.00221036
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.00216684
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.00215901
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.0021211
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.0020815
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.0020523
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.00202892
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.00199549
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.00199312
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 0.00198238
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 0.00196858
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 0.00195883
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 0.00193186
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[116]	valid_0's binary_logloss: 0.00192266
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[117]	valid_0's binary_logloss: 0.00191479
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[118]	valid_0's binary_logloss: 0.00191411
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[119]	valid_0's binary_logloss: 0.0019116
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[120]	valid_0's binary_logloss: 0.00189949
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[121]	valid_0's binary_logloss: 0.00187191
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[122]	valid_0's binary_logloss: 0.00184215
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[123]	valid_0's binary_logloss: 0.00180982
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[124]	valid_0's binary_logloss: 0.00177319
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[125]	valid_0's binary_logloss: 0.00175741
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[126]	valid_0's binary_logloss: 0.00174702
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[127]	valid_0's binary_logloss: 0.00172263
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[128]	valid_0's binary_logloss: 0.00170618
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[129]	valid_0's binary_logloss: 0.00169778
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[130]	valid_0's binary_logloss: 0.00169471
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[131]	valid_0's binary_logloss: 0.00169343
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[132]	valid_0's binary_logloss: 0.00168765
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[133]	valid_0's binary_logloss: 0.00167896
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[134]	valid_0's binary_logloss: 0.00167164
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[135]	valid_0's binary_logloss: 0.001653
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[136]	valid_0's binary_logloss: 0.00164151
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[137]	valid_0's binary_logloss: 0.00164194
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[138]	valid_0's binary_logloss: 0.00165735
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[139]	valid_0's binary_logloss: 0.00167244
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[140]	valid_0's binary_logloss: 0.00168993
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[141]	valid_0's binary_logloss: 0.00168435
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[142]	valid_0's binary_logloss: 0.00167818
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[143]	valid_0's binary_logloss: 0.00167992
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[144]	valid_0's binary_logloss: 0.00168242
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[145]	valid_0's binary_logloss: 0.00168197
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[146]	valid_0's binary_logloss: 0.00166715
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[147]	valid_0's binary_logloss: 0.00164709
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[148]	valid_0's binary_logloss: 0.00162616
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[149]	valid_0's binary_logloss: 0.00159145
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[150]	valid_0's binary_logloss: 0.00155702
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[151]	valid_0's binary_logloss: 0.00154834
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[152]	valid_0's binary_logloss: 0.00154718
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[153]	valid_0's binary_logloss: 0.00154348
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[154]	valid_0's binary_logloss: 0.00154552
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[155]	valid_0's binary_logloss: 0.00155991
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[156]	valid_0's binary_logloss: 0.00154326
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[157]	valid_0's binary_logloss: 0.00153219
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[158]	valid_0's binary_logloss: 0.0015161
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[159]	valid_0's binary_logloss: 0.00151562
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[160]	valid_0's binary_logloss: 0.00150139
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[161]	valid_0's binary_logloss: 0.00150444
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[162]	valid_0's binary_logloss: 0.00151493
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[163]	valid_0's binary_logloss: 0.00152493
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[164]	valid_0's binary_logloss: 0.0015321
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[165]	valid_0's binary_logloss: 0.00152751
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[166]	valid_0's binary_logloss: 0.00151877
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[167]	valid_0's binary_logloss: 0.00151204
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[168]	valid_0's binary_logloss: 0.00151588
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[169]	valid_0's binary_logloss: 0.00150874
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[170]	valid_0's binary_logloss: 0.00151102
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[171]	valid_0's binary_logloss: 0.00151416
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[172]	valid_0's binary_logloss: 0.00150674
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[173]	valid_0's binary_logloss: 0.00150566
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[174]	valid_0's binary_logloss: 0.0014996
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[175]	valid_0's binary_logloss: 0.0014907
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[176]	valid_0's binary_logloss: 0.00149834
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[177]	valid_0's binary_logloss: 0.00150776
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[178]	valid_0's binary_logloss: 0.00149833
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[179]	valid_0's binary_logloss: 0.00149624
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[180]	valid_0's binary_logloss: 0.00150363
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[181]	valid_0's binary_logloss: 0.00150492
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[182]	valid_0's binary_logloss: 0.00150904
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[183]	valid_0's binary_logloss: 0.00151377

Trening klas:  98%|█████████▊| 491/500 [55:48<00:39,  4.39s/klasa, klasa=class_491, F1_klasy=0.0000, F1_macro=0.6070, drzewa=175]




Trening klas:  98%|█████████▊| 492/500 [55:48<00:45,  5.72s/klasa, klasa=class_491, F1_klasy=0.0000, F1_macro=0.6070, drzewa=175]

[1]	valid_0's binary_logloss: 0.121367
[2]	valid_0's binary_logloss: 0.0266719
[3]	valid_0's binary_logloss: 0.0202798
[4]	valid_0's binary_logloss: 0.019844
[5]	valid_0's binary_logloss: 0.0193207
[6]	valid_0's binary_logloss: 0.0845804
[7]	valid_0's binary_logloss: 0.0845968
[8]	valid_0's binary_logloss: 0.084376
[9]	valid_0's binary_logloss: 0.084219
[10]	valid_0's binary_logloss: 0.0844087
[11]	valid_0's binary_logloss: 0.084324
[12]	valid_0's binary_logloss: 0.0844235
[13]	valid_0's binary_logloss: 0.0845423
[14]	valid_0's binary_logloss: 0.0830838
[15]	valid_0's binary_logloss: 0.0821055
[16]	valid_0's binary_logloss: 0.0812636
[17]	valid_0's binary_logloss: 0.0811777
[18]	valid_0's binary_logloss: 0.0810822
[19]	valid_0's binary_logloss: 0.0806753
[20]	valid_0's binary_logloss: 0.0803456
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0799676
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0795927
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.0792335
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0789379
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.0787006
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.0783725
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.0780684
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.0779544
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.0777994
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.0775183
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.0789425
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.0788895
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.0788595
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.0788176
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.0787266

Trening klas:  98%|█████████▊| 492/500 [55:51<00:45,  5.72s/klasa, klasa=class_492, F1_klasy=0.0645, F1_macro=0.6059, drzewa=5]




Trening klas:  99%|█████████▊| 493/500 [55:51<00:34,  4.96s/klasa, klasa=class_492, F1_klasy=0.0645, F1_macro=0.6059, drzewa=5]

[1]	valid_0's binary_logloss: 0.132655
[2]	valid_0's binary_logloss: 0.094044
[3]	valid_0's binary_logloss: 0.0756469
[4]	valid_0's binary_logloss: 0.0708874
[5]	valid_0's binary_logloss: 0.068097
[6]	valid_0's binary_logloss: 0.0577865
[7]	valid_0's binary_logloss: 0.0548046
[8]	valid_0's binary_logloss: 0.053133
[9]	valid_0's binary_logloss: 0.0517986
[10]	valid_0's binary_logloss: 0.0502666
[11]	valid_0's binary_logloss: 0.0485223
[12]	valid_0's binary_logloss: 0.0470795
[13]	valid_0's binary_logloss: 0.0457265
[14]	valid_0's binary_logloss: 0.0446306
[15]	valid_0's binary_logloss: 0.0435147
[16]	valid_0's binary_logloss: 0.042712
[17]	valid_0's binary_logloss: 0.0419803
[18]	valid_0's binary_logloss: 0.0411513
[19]	valid_0's binary_logloss: 0.0402557
[20]	valid_0's binary_logloss: 0.0395372
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0387929
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0379877
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.0372803
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0365514
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.0358728
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.0352323
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.0346221
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.0339938
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.0334116
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.0328769
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.0323498
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.0318741
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.0314113
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.0309482
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.0304945
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.0300718
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.0297098
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.0292959
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.0288659
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.0285709
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.0281438
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.0278061
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.0274042
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.0269951
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.0266218
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.0262394
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.025796
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.0254848
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.0251038
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.0248001
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.0244746
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.0241216
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.023886
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.0235413
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.0232158
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.0228798
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.0226131
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.0223084
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.0219965
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.0216947
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.0214376
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.0211897
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.0209429
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.0206962
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.0204459
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.0202455
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.0200095
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.0198317
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.0196758
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.0194066
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.0192977
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.0191914
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.019062
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.0189187
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.0187189
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.018449
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.0181828
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.0179216
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.0176888
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.0174359
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.0171857
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.0170305
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.0167488
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.0164967
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.0162616
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.0161625
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.0160245
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.0159315
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.015798
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.0157471
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.0155736
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.0154109
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.0152377
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.0150746
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.0149139
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.0146908
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.0144775
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.0142738
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.014074
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.0138679
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.0137653
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.0136318
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.0134146
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.0132995
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.0131878
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.0130811
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.0129972
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.0128631
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.0127844
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.0127039
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.0125208
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 0.0123959
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 0.0122821
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 0.0121683
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 0.0120571
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[116]	valid_0's binary_logloss: 0.0119612
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[117]	valid_0's binary_logloss: 0.0119306
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[118]	valid_0's binary_logloss: 0.011843
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[119]	valid_0's binary_logloss: 0.011764
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[120]	valid_0's binary_logloss: 0.0117281
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[121]	valid_0's binary_logloss: 0.011603
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[122]	valid_0's binary_logloss: 0.0115014
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[123]	valid_0's binary_logloss: 0.0113733
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[124]	valid_0's binary_logloss: 0.0112596
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[125]	valid_0's binary_logloss: 0.0111482
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[126]	valid_0's binary_logloss: 0.011054
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[127]	valid_0's binary_logloss: 0.0109067
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[128]	valid_0's binary_logloss: 0.0107694
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[129]	valid_0's binary_logloss: 0.0106708
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[130]	valid_0's binary_logloss: 0.0105865
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[131]	valid_0's binary_logloss: 0.0104843
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[132]	valid_0's binary_logloss: 0.0103884
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[133]	valid_0's binary_logloss: 0.0102844
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[134]	valid_0's binary_logloss: 0.0101809
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[135]	valid_0's binary_logloss: 0.0100989
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[136]	valid_0's binary_logloss: 0.0100864
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[137]	valid_0's binary_logloss: 0.010044
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[138]	valid_0's binary_logloss: 0.00998158
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[139]	valid_0's binary_logloss: 0.00995573
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[140]	valid_0's binary_logloss: 0.00994758
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[141]	valid_0's binary_logloss: 0.00992382
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[142]	valid_0's binary_logloss: 0.00991192
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[143]	valid_0's binary_logloss: 0.00988706
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[144]	valid_0's binary_logloss: 0.00986816
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[145]	valid_0's binary_logloss: 0.00983262
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[146]	valid_0's binary_logloss: 0.00979289
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[147]	valid_0's binary_logloss: 0.00977469
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[148]	valid_0's binary_logloss: 0.0097296
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[149]	valid_0's binary_logloss: 0.00968645
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[150]	valid_0's binary_logloss: 0.0096065
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[151]	valid_0's binary_logloss: 0.00954687
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[152]	valid_0's binary_logloss: 0.00949146
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[153]	valid_0's binary_logloss: 0.00943688
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[154]	valid_0's binary_logloss: 0.00937428
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[155]	valid_0's binary_logloss: 0.00932431
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[156]	valid_0's binary_logloss: 0.00928374
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[157]	valid_0's binary_logloss: 0.00924726
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[158]	valid_0's binary_logloss: 0.0091958
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[159]	valid_0's binary_logloss: 0.00916437
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[160]	valid_0's binary_logloss: 0.00911619
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[161]	valid_0's binary_logloss: 0.00903336
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[162]	valid_0's binary_logloss: 0.008975
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[163]	valid_0's binary_logloss: 0.00889045
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[164]	valid_0's binary_logloss: 0.00885806
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[165]	valid_0's binary_logloss: 0.00886826
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[166]	valid_0's binary_logloss: 0.00886544
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[167]	valid_0's binary_logloss: 0.00883805
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[168]	valid_0's binary_logloss: 0.00877372
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[169]	valid_0's binary_logloss: 0.00871379
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[170]	valid_0's binary_logloss: 0.00870225
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[171]	valid_0's binary_logloss: 0.00866919
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[172]	valid_0's binary_logloss: 0.00861775
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[173]	valid_0's binary_logloss: 0.00856396
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[174]	valid_0's binary_logloss: 0.00851677
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[175]	valid_0's binary_logloss: 0.0084694
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[176]	valid_0's binary_logloss: 0.00846981
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[177]	valid_0's binary_logloss: 0.00846445
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[178]	valid_0's binary_logloss: 0.00846044
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[179]	valid_0's binary_logloss: 0.00846398
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[180]	valid_0's binary_logloss: 0.00845227
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[181]	valid_0's binary_logloss: 0.00842237
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[182]	valid_0's binary_logloss: 0.00840404
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[183]	valid_0's binary_logloss: 0.00837824
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[184]	valid_0's binary_logloss: 0.00833983

Trening klas:  99%|█████████▊| 493/500 [55:58<00:34,  4.96s/klasa, klasa=class_493, F1_klasy=0.6780, F1_macro=0.6060, drzewa=300]




Trening klas:  99%|█████████▉| 494/500 [55:58<00:33,  5.56s/klasa, klasa=class_493, F1_klasy=0.6780, F1_macro=0.6060, drzewa=300]

[1]	valid_0's binary_logloss: 0.0114352
[2]	valid_0's binary_logloss: 0.00997434
[3]	valid_0's binary_logloss: 0.00895272
[4]	valid_0's binary_logloss: 0.00818283
[5]	valid_0's binary_logloss: 0.00764045
[6]	valid_0's binary_logloss: 0.0070481
[7]	valid_0's binary_logloss: 0.0066301
[8]	valid_0's binary_logloss: 0.00619151
[9]	valid_0's binary_logloss: 0.00583969
[10]	valid_0's binary_logloss: 0.00557081
[11]	valid_0's binary_logloss: 0.00531336
[12]	valid_0's binary_logloss: 0.00506083
[13]	valid_0's binary_logloss: 0.00487091
[14]	valid_0's binary_logloss: 0.0046032
[15]	valid_0's binary_logloss: 0.00440439
[16]	valid_0's binary_logloss: 0.00424744
[17]	valid_0's binary_logloss: 0.00408861
[18]	valid_0's binary_logloss: 0.00391126
[19]	valid_0's binary_logloss: 0.00374837
[20]	valid_0's binary_logloss: 0.00361866
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.00348471
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.00333727
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.00320607
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.00308946
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.00297675
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.00287083
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.00276568
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.002665
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.00256906
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.00247986
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.00238575
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.0023078
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.00222462
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.00214439
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.00206854
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.00199405
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.00192203
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.0018547
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.00178462
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.00172209
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.00165959
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.00160376
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.00154901
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.00149704
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.00144311
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.0013927
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.00135201
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.00131642
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.00127391
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.00123274
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.00121681
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.00117821
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.00114307
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.00110637
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.00107346
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.00104113
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.0010099
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.000979224
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.000949788
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.000920494
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.000890544
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.000861551
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.00083291
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.000805864
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.000779965
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.000755264
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.000732549
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.000708989
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.000687723
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.000666725
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.000645127
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.000624188
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.000603671
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.000584598
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.000564601
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.000546659
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.000529065
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.00052161
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.00050505
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.000488831
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.000473384
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.000458711
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.000444504
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.000430802
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.000417433
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.000404592
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.000392731
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.000379613
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.000366955
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.000354761
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.000343151
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.000333343
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.000323741
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.000313145
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.000303058
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.000296963
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.00028715
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.000278319
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.000267766
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.00025975
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.000249443
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.000239561
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.000230202
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.000222538
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.00021411
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.000207072
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.000200305
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.000193797
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.000187027
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.000181025
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.000173528
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 0.000168001
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 0.000161103
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 0.000155656
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 0.000154992
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[116]	valid_0's binary_logloss: 0.000150132
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[117]	valid_0's binary_logloss: 0.00014548
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[118]	valid_0's binary_logloss: 0.000140581
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[119]	valid_0's binary_logloss: 0.000136428
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[120]	valid_0's binary_logloss: 0.000135022
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[121]	valid_0's binary_logloss: 0.000131347
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[122]	valid_0's binary_logloss: 0.000134002
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[123]	valid_0's binary_logloss: 0.000130478
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[124]	valid_0's binary_logloss: 0.000127148
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[125]	valid_0's binary_logloss: 0.000122286
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[126]	valid_0's binary_logloss: 0.000121263
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[127]	valid_0's binary_logloss: 0.000121445
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[128]	valid_0's binary_logloss: 0.00012053
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[129]	valid_0's binary_logloss: 0.000120773
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[130]	valid_0's binary_logloss: 0.000119969
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[131]	valid_0's binary_logloss: 0.000116796
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[132]	valid_0's binary_logloss: 0.000113787
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[133]	valid_0's binary_logloss: 0.000111082
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[134]	valid_0's binary_logloss: 0.000108265
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[135]	valid_0's binary_logloss: 0.000105555
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[136]	valid_0's binary_logloss: 0.000102404
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[137]	valid_0's binary_logloss: 9.91879e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[138]	valid_0's binary_logloss: 9.66783e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[139]	valid_0's binary_logloss: 9.39345e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[140]	valid_0's binary_logloss: 9.25891e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[141]	valid_0's binary_logloss: 9.01405e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[142]	valid_0's binary_logloss: 8.99609e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[143]	valid_0's binary_logloss: 8.97291e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[144]	valid_0's binary_logloss: 8.82202e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[145]	valid_0's binary_logloss: 8.8131e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[146]	valid_0's binary_logloss: 8.57768e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[147]	valid_0's binary_logloss: 8.36069e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[148]	valid_0's binary_logloss: 8.13319e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[149]	valid_0's binary_logloss: 7.92554e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[150]	valid_0's binary_logloss: 7.74752e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[151]	valid_0's binary_logloss: 7.59416e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[152]	valid_0's binary_logloss: 7.56296e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[153]	valid_0's binary_logloss: 7.41913e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[154]	valid_0's binary_logloss: 7.39241e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[155]	valid_0's binary_logloss: 7.25513e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[156]	valid_0's binary_logloss: 7.03076e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[157]	valid_0's binary_logloss: 6.83839e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[158]	valid_0's binary_logloss: 6.62957e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[159]	valid_0's binary_logloss: 6.45352e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[160]	valid_0's binary_logloss: 6.30233e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[161]	valid_0's binary_logloss: 6.23356e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[162]	valid_0's binary_logloss: 6.14539e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[163]	valid_0's binary_logloss: 6.07818e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[164]	valid_0's binary_logloss: 6.00473e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[165]	valid_0's binary_logloss: 5.93672e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[166]	valid_0's binary_logloss: 5.92878e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[167]	valid_0's binary_logloss: 5.77706e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[168]	valid_0's binary_logloss: 5.63687e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[169]	valid_0's binary_logloss: 5.50749e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[170]	valid_0's binary_logloss: 5.36898e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[171]	valid_0's binary_logloss: 5.36662e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[172]	valid_0's binary_logloss: 5.33523e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[173]	valid_0's binary_logloss: 5.30754e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[174]	valid_0's binary_logloss: 5.24858e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[175]	valid_0's binary_logloss: 5.22181e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[176]	valid_0's binary_logloss: 5.06799e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[177]	valid_0's binary_logloss: 4.92114e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[178]	valid_0's binary_logloss: 4.78118e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[179]	valid_0's binary_logloss: 4.69173e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[180]	valid_0's binary_logloss: 4.60502e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[181]	valid_0's binary_logloss: 4.53455e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[182]	valid_0's binary_logloss: 4.46633e-05

Trening klas:  99%|█████████▉| 494/500 [56:06<00:33,  5.56s/klasa, klasa=class_494, F1_klasy=0.0000, F1_macro=0.6048, drzewa=300]




Trening klas:  99%|█████████▉| 495/500 [56:06<00:32,  6.41s/klasa, klasa=class_494, F1_klasy=0.0000, F1_macro=0.6048, drzewa=300]

[292]	valid_0's binary_logloss: 1.54276e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[293]	valid_0's binary_logloss: 1.5424e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[294]	valid_0's binary_logloss: 1.54205e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[295]	valid_0's binary_logloss: 1.54172e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[296]	valid_0's binary_logloss: 1.53749e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[297]	valid_0's binary_logloss: 1.53619e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[298]	valid_0's binary_logloss: 1.53228e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[299]	valid_0's binary_logloss: 1.52854e-05
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[300]	valid_0's binary_logloss: 1.52581e-05
[1]	valid_0's binary_logloss: 0.0112751
[2]	valid_0's binary_logloss: 0.0101711
[3]	valid_0's binary_logloss: 0.00965013
[4]	valid_0's binary_logloss: 0.00870265
[5]	valid_0's binary_logloss: 0.0085138
[6]	valid_0's binary_logloss: 0.00718604
[7]	valid_0's binary_logloss: 0.00639527
[8]	valid_0's binary_logloss: 0.00598812
[9]	valid_0's binary_logloss: 0.00582757
[10]	valid_0's binary_logloss: 0.00547269
[11]	valid_0's binary_logloss: 0.00534053
[12]	valid_0's binary_logloss: 0.00514778
[13]	valid_0's binary_logloss: 0.00500197
[14]	valid_0's binary_logloss: 0.00483458
[15]	valid_0's binary_logloss: 0.00468398
[16]	valid_0's binary_logloss: 0.00456915
[17]	valid_0's binary_logloss: 0.00446091
[18]	valid_0's binary_logloss: 0.00435526
[19]	valid_0's binary_logloss: 0.0042543
[20]	valid_0's binary_logloss: 0.00415804
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.00407619
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.00399928
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.00392603
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.00385058
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.00377858
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.00370495
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.00363675
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.00355989
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.00349893
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.00342967
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.00337956
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.00332057
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.00326408
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.00321951
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.0031724
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.00312736
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.00309301
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.00306087
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.00299524
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.00296703
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.00293235
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.00289955
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.00284179
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.00281241
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.00275964
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.00274089
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.00272361
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.0026961
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.00268151
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.00265058
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.00260597
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.00256083
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.00251894
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.00247838
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.00243933
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.0024186
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.00240567
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.0023933
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.00238169
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.00237085
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.00235089
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.00233171
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.00231428
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.00229657
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.0022645
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.00224842
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.00221786
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.0022029
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.00217374
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.00214771
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.00213289
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.00211864
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.00210501
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.00209208
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.00207963
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.00206769
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.00204937
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.00203716
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.00202635
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.00201485
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.00199194
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.00196963
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.00194791
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.00192682
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.00190624
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.00190481
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.00188508
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.00186598
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.00185943
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.00184115
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.0018406
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.00183513
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.00183004
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.00182517
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.00182067
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.00180891
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.00179297
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.00177752
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.00176242
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.00174773
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.00174171
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.00173929
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.0017335
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.00172493
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.00171939
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.00170973
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.00170799
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.00169538
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.00169406
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.00168213
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.00169118
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 0.00170027
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 0.00169934
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 0.00170571
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 0.00171454
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[116]	valid_0's binary_logloss: 0.0017031
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[117]	valid_0's binary_logloss: 0.00169197
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[118]	valid_0's binary_logloss: 0.0016811
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[119]	valid_0's binary_logloss: 0.00167414
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[120]	valid_0's binary_logloss: 0.00166377
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[121]	valid_0's binary_logloss: 0.00165462
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[122]	valid_0's binary_logloss: 0.00164572
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[123]	valid_0's binary_logloss: 0.00163706
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[124]	valid_0's binary_logloss: 0.00162866
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[125]	valid_0's binary_logloss: 0.00162922
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[126]	valid_0's binary_logloss: 0.00162977
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[127]	valid_0's binary_logloss: 0.00162612
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[128]	valid_0's binary_logloss: 0.00162679
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[129]	valid_0's binary_logloss: 0.00162548
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[130]	valid_0's binary_logloss: 0.00162713
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[131]	valid_0's binary_logloss: 0.00161931
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[132]	valid_0's binary_logloss: 0.00161174
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[133]	valid_0's binary_logloss: 0.00160439
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[134]	valid_0's binary_logloss: 0.00159735
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[135]	valid_0's binary_logloss: 0.00159055
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[136]	valid_0's binary_logloss: 0.00159725
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[137]	valid_0's binary_logloss: 0.00160386
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[138]	valid_0's binary_logloss: 0.00160526
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[139]	valid_0's binary_logloss: 0.0016067
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[140]	valid_0's binary_logloss: 0.00161148
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[141]	valid_0's binary_logloss: 0.00161793
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[142]	valid_0's binary_logloss: 0.00161365
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[143]	valid_0's binary_logloss: 0.00161794
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[144]	valid_0's binary_logloss: 0.00161505
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[145]	valid_0's binary_logloss: 0.00162117
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[146]	valid_0's binary_logloss: 0.0016228
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[147]	valid_0's binary_logloss: 0.00162446
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[148]	valid_0's binary_logloss: 0.00162158
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[149]	valid_0's binary_logloss: 0.00162324
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[150]	valid_0's binary_logloss: 0.00162491
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[151]	valid_0's binary_logloss: 0.00162433
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[152]	valid_0's binary_logloss: 0.00161998
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[153]	valid_0's binary_logloss: 0.00161947
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[154]	valid_0's binary_logloss: 0.00162125
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[155]	valid_0's binary_logloss: 0.00161729
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

Trening klas:  99%|█████████▉| 495/500 [56:10<00:32,  6.41s/klasa, klasa=class_495, F1_klasy=0.8333, F1_macro=0.6053, drzewa=135]




Trening klas:  99%|█████████▉| 496/500 [56:10<00:22,  5.65s/klasa, klasa=class_495, F1_klasy=0.8333, F1_macro=0.6053, drzewa=135]

[156]	valid_0's binary_logloss: 0.00161449
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[157]	valid_0's binary_logloss: 0.00161304
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[158]	valid_0's binary_logloss: 0.00161039
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[159]	valid_0's binary_logloss: 0.0016078
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[160]	valid_0's binary_logloss: 0.00160519
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[161]	valid_0's binary_logloss: 0.00160144
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[162]	valid_0's binary_logloss: 0.00160294
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[163]	valid_0's binary_logloss: 0.00160444
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[164]	valid_0's binary_logloss: 0.00160593
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[165]	valid_0's binary_logloss: 0.00160741
[1]	valid_0's binary_logloss: 0.242393
[2]	valid_0's binary_logloss: 0.150395
[3]	valid_0's binary_logloss: 0.130274
[4]	valid_0's binary_logloss: 0.122032
[5]	valid_0's binary_logloss: 0.116967
[6]	valid_0's binary_logloss: 0.112971
[7]	valid_0's binary_logloss: 0.1098
[8]	valid_0's binary_logloss: 0.107148
[9]	valid_0's binary_logloss: 0.105164
[10]	valid_0's binary_logloss: 0.102958
[11]	valid_0's binary_logloss: 0.101389
[12]	valid_0's binary_logloss: 0.0996512
[13]	valid_0's binary_logloss: 0.0983328
[14]	valid_0's binary_logloss: 0.0968004
[15]	valid_0's binary_logloss: 0.0952257
[16]	valid_0's binary_logloss: 0.0938254
[17]	valid_0's binary_logloss: 0.0924787
[18]	valid_0's binary_logloss: 0.0912418
[19]	valid_0's binary_logloss: 0.0898836
[20]	valid_0's binary_logloss: 0.0887416
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0878854
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0867064
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.0853795
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0843198
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.0833068
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.0826601
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.0814963
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.0806071
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.0797123
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.0788013
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.0776788
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.076636
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.0757703
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.0749835
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.0742609
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.0733122
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.0723947
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.0715251
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.0706461
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.0697661
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.0691283
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.0682909
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.0676839
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.0671244
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.0662048
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.0656936
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.0652662
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.0646618
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.0640951
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.0636506
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.0629504
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.0622395
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.0615126
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.0607877
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.0600489
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.0595019
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.058971
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.058376
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.0577465
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.0571682
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.0567494
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.0562051
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.0556689
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.055141
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.0547509
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.0544583
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.0540448
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.0537833
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.0533976
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.0528944
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.0524541
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.0520487
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.0514865
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.0510213
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.0506264
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.0500642
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.0496429
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.0491004
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.0485789
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.0480975
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.0476982
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.0474077
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.0470017
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.0466049
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.0463245
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.045861
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.0454864
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.0451373
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.0448734
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.0445798
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.0443807
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.0441893
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.0441384
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.0437635
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.0433895
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.0430297
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.0425715
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.0421647
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.0418086
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.0414794
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.0413128
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.0410018
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.0408362
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.0405652
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.0403025
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.0399546
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.0396824
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.0395138
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.0392451
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.0389704
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.0387428
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 0.0384753
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 0.0381291
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 0.0378594
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 0.0375308
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[116]	valid_0's binary_logloss: 0.0374157
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[117]	valid_0's binary_logloss: 0.03721
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[118]	valid_0's binary_logloss: 0.0369195
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[119]	valid_0's binary_logloss: 0.0366548
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[120]	valid_0's binary_logloss: 0.0364438
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[121]	valid_0's binary_logloss: 0.0362525
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[122]	valid_0's binary_logloss: 0.0360503
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[123]	valid_0's binary_logloss: 0.0358914
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[124]	valid_0's binary_logloss: 0.0357833
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[125]	valid_0's binary_logloss: 0.0356061
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[126]	valid_0's binary_logloss: 0.0353281
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[127]	valid_0's binary_logloss: 0.0350795
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[128]	valid_0's binary_logloss: 0.0349524
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[129]	valid_0's binary_logloss: 0.0346858
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[130]	valid_0's binary_logloss: 0.0344223
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[131]	valid_0's binary_logloss: 0.0341971
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[132]	valid_0's binary_logloss: 0.0340458
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[133]	valid_0's binary_logloss: 0.0338239
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[134]	valid_0's binary_logloss: 0.0336353
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[135]	valid_0's binary_logloss: 0.0334139
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[136]	valid_0's binary_logloss: 0.0333574
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[137]	valid_0's binary_logloss: 0.0331402
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[138]	valid_0's binary_logloss: 0.0329625
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[139]	valid_0's binary_logloss: 0.0327846
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[140]	valid_0's binary_logloss: 0.0326473
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[141]	valid_0's binary_logloss: 0.0325046
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[142]	valid_0's binary_logloss: 0.0323962
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[143]	valid_0's binary_logloss: 0.0322944
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[144]	valid_0's binary_logloss: 0.0320784
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[145]	valid_0's binary_logloss: 0.0319417
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[146]	valid_0's binary_logloss: 0.0318664
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[147]	valid_0's binary_logloss: 0.0317948
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[148]	valid_0's binary_logloss: 0.0317715
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[149]	valid_0's binary_logloss: 0.0316908
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[150]	valid_0's binary_logloss: 0.0316644
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[151]	valid_0's binary_logloss: 0.0315406
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[152]	valid_0's binary_logloss: 0.0314021
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[153]	valid_0's binary_logloss: 0.0313518
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[154]	valid_0's binary_logloss: 0.031195
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[155]	valid_0's binary_logloss: 0.0310509
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[156]	valid_0's binary_logloss: 0.0309098
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[157]	valid_0's binary_logloss: 0.0307743
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[158]	valid_0's binary_logloss: 0.0306266
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[159]	valid_0's binary_logloss: 0.0305103
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[160]	valid_0's binary_logloss: 0.0304059
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[161]	valid_0's binary_logloss: 0.0303109
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[162]	valid_0's binary_logloss: 0.0302217
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[163]	valid_0's binary_logloss: 0.0301084
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[164]	valid_0's binary_logloss: 0.0300212
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[165]	valid_0's binary_logloss: 0.0299245
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[166]	valid_0's binary_logloss: 0.0298301
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[167]	valid_0's binary_logloss: 0.0297224
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[168]	valid_0's binary_logloss: 0.0295941
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[169]	valid_0's binary_logloss: 0.0295012
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[170]	valid_0's binary_logloss: 0.0293759
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[171]	valid_0's binary_logloss: 0.0292314
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[172]	valid_0's binary_logloss: 0.0291501
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[173]	valid_0's binary_logloss: 0.0290522
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[174]	valid_0's binary_logloss: 0.0290252
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[175]	valid_0's binary_logloss: 0.0289281

Trening klas:  99%|█████████▉| 496/500 [56:18<00:22,  5.65s/klasa, klasa=class_496, F1_klasy=0.3562, F1_macro=0.6048, drzewa=299]




Trening klas:  99%|█████████▉| 497/500 [56:18<00:18,  6.22s/klasa, klasa=class_496, F1_klasy=0.3562, F1_macro=0.6048, drzewa=299]

[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[296]	valid_0's binary_logloss: 0.0247458
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[297]	valid_0's binary_logloss: 0.0247069
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[298]	valid_0's binary_logloss: 0.0246798
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[299]	valid_0's binary_logloss: 0.0246387
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[300]	valid_0's binary_logloss: 0.0245902
[1]	valid_0's binary_logloss: 0.065755
[2]	valid_0's binary_logloss: 0.0415455
[3]	valid_0's binary_logloss: 0.0405905
[4]	valid_0's binary_logloss: 0.0391054
[5]	valid_0's binary_logloss: 0.0379865
[6]	valid_0's binary_logloss: 0.0367737
[7]	valid_0's binary_logloss: 0.0360205
[8]	valid_0's binary_logloss: 0.0356126
[9]	valid_0's binary_logloss: 0.0350159
[10]	valid_0's binary_logloss: 0.0345734
[11]	valid_0's binary_logloss: 0.034217
[12]	valid_0's binary_logloss: 0.0338241
[13]	valid_0's binary_logloss: 0.0335911
[14]	valid_0's binary_logloss: 0.033362
[15]	valid_0's binary_logloss: 0.0330568
[16]	valid_0's binary_logloss: 0.0326192
[17]	valid_0's binary_logloss: 0.0320222
[18]	valid_0's binary_logloss: 0.0316336
[19]	valid_0's binary_logloss: 0.031459
[20]	valid_0's binary_logloss: 0.0311827
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.0309115
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.0307066
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.0305385
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.0303971
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.0302167
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.0299779
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.02977
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.0296111
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.0294629
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.0293144
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.0291553
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.0291098
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.0290847
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.0289802
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.0289191
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.0287901
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.0286918
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.0286334
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.0285303
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.0284345
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.0283357
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.0282559
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.0281804
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.0281545
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.028075
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.0281085
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.0281338
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.0281243
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.0281582
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.0280927
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.0279905
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.0279433
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.0278769
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.0278017
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.027751
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.0277174
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.0276293
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.0275679
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.0275344
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.0275053
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.0274434
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.0274136
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.0273909
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.027359
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.0273262
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.027217
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.0272359
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.0272392
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.0271927
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.0271227
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.0270908
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.0270604
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.027071
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.027028
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.0269889
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.0269635
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.0269751
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.0269194
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.026905
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.0268237
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.02676
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.0267234
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.0266297
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.0265948
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.0265218
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.0265041
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.0264321
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.0264181
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.0263697
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.0263459
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.0263239
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.0262798
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.026306
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.0262354
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.0261918
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.0261726
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.0261219
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.026078
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.0260897
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.0260259
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.0259854
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.0259496
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.0259096
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.0258699
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.0258157
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.0258077
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.0257928
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.0257635
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.0257302
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.0257265
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.0257005
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 0.0256899
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 0.025675
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 0.0256366
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 0.0256427
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[116]	valid_0's binary_logloss: 0.0256348
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[117]	valid_0's binary_logloss: 0.0256114
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[118]	valid_0's binary_logloss: 0.0255983
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[119]	valid_0's binary_logloss: 0.0255853
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[120]	valid_0's binary_logloss: 0.0255588
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[121]	valid_0's binary_logloss: 0.0255519
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[122]	valid_0's binary_logloss: 0.0255786
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[123]	valid_0's binary_logloss: 0.0256151
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[124]	valid_0's binary_logloss: 0.0256519
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[125]	valid_0's binary_logloss: 0.0256603
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[126]	valid_0's binary_logloss: 0.0256489
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[127]	valid_0's binary_logloss: 0.0256415
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[128]	valid_0's binary_logloss: 0.0256096
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[129]	valid_0's binary_logloss: 0.0256058
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[130]	valid_0's binary_logloss: 0.0255786
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[131]	valid_0's binary_logloss: 0.025585
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[132]	valid_0's binary_logloss: 0.0255616
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[133]	valid_0's binary_logloss: 0.025565
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[134]	valid_0's binary_logloss: 0.0255573
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[135]	valid_0's binary_logloss: 0.0255454
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[136]	valid_0's binary_logloss: 0.0255327
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[137]	valid_0's binary_logloss: 0.0255041
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[138]	valid_0's binary_logloss: 0.0254735
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[139]	valid_0's binary_logloss: 0.0254465
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[140]	valid_0's binary_logloss: 0.0254318
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[141]	valid_0's binary_logloss: 0.0254296
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[142]	valid_0's binary_logloss: 0.0254013
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[143]	valid_0's binary_logloss: 0.0254093
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[144]	valid_0's binary_logloss: 0.0254037
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[145]	valid_0's binary_logloss: 0.0253935
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[146]	valid_0's binary_logloss: 0.0253472
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[147]	valid_0's binary_logloss: 0.0253346
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[148]	valid_0's binary_logloss: 0.0252902
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[149]	valid_0's binary_logloss: 0.0252652
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[150]	valid_0's binary_logloss: 0.0252471
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[151]	valid_0's binary_logloss: 0.0252497
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[152]	valid_0's binary_logloss: 0.0252593
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[153]	valid_0's binary_logloss: 0.0252872
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[154]	valid_0's binary_logloss: 0.0252878
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[155]	valid_0's binary_logloss: 0.025268
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[156]	valid_0's binary_logloss: 0.0252355
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[157]	valid_0's binary_logloss: 0.0251786
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[158]	valid_0's binary_logloss: 0.0251836
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[159]	valid_0's binary_logloss: 0.0251583
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[160]	valid_0's binary_logloss: 0.0251545
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[161]	valid_0's binary_logloss: 0.0251683
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[162]	valid_0's binary_logloss: 0.0251705
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[163]	valid_0's binary_logloss: 0.025173
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[164]	valid_0's binary_logloss: 0.0251569
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[165]	valid_0's binary_logloss: 0.0251414
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[166]	valid_0's binary_logloss: 0.0251244
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[167]	valid_0's binary_logloss: 0.0251531
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[168]	valid_0's binary_logloss: 0.0251386
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[169]	valid_0's binary_logloss: 0.0251225
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[170]	valid_0's binary_logloss: 0.0251213
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[171]	valid_0's binary_logloss: 0.0251267
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[172]	valid_0's binary_logloss: 0.0250905
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[173]	valid_0's binary_logloss: 0.025078
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[174]	valid_0's binary_logloss: 0.0250382
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[175]	valid_0's binary_logloss: 0.0250049
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[176]	valid_0's binary_logloss: 0.0250053
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[177]	valid_0's binary_logloss: 0.0250211
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[178]	valid_0's binary_logloss: 0.0250137
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[179]	valid_0's binary_logloss: 0.0250148
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

Trening klas:  99%|█████████▉| 497/500 [56:25<00:18,  6.22s/klasa, klasa=class_497, F1_klasy=0.4074, F1_macro=0.6044, drzewa=229]




Trening klas: 100%|█████████▉| 498/500 [56:25<00:13,  6.59s/klasa, klasa=class_497, F1_klasy=0.4074, F1_macro=0.6044, drzewa=229]

[253]	valid_0's binary_logloss: 0.0248841
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[254]	valid_0's binary_logloss: 0.0248854
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[255]	valid_0's binary_logloss: 0.0248754
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[256]	valid_0's binary_logloss: 0.0248823
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[257]	valid_0's binary_logloss: 0.0248721
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[258]	valid_0's binary_logloss: 0.0248673
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[259]	valid_0's binary_logloss: 0.024876
[1]	valid_0's binary_logloss: 1.54695
[2]	valid_0's binary_logloss: 0.275842
[3]	valid_0's binary_logloss: 1.07543
[4]	valid_0's binary_logloss: 1.01748
[5]	valid_0's binary_logloss: 1.01637
[6]	valid_0's binary_logloss: 1.43875
[7]	valid_0's binary_logloss: 1.44053
[8]	valid_0's binary_logloss: 1.44946
[9]	valid_0's binary_logloss: 1.45563
[10]	valid_0's binary_logloss: 1.43101
[11]	valid_0's binary_logloss: 1.45754
[12]	valid_0's binary_logloss: 1.45145
[13]	valid_0's binary_logloss: 1.44121
[14]	valid_0's binary_logloss: 1.43782
[15]	valid_0's binary_logloss: 1.43226
[16]	valid_0's binary_logloss: 1.44537
[17]	valid_0's binary_logloss: 1.4328
[18]	valid_0's binary_logloss: 1.43294
[19]	valid_0's binary_logloss: 1.42831
[20]	valid_0's binary_logloss: 1.42095
[21]	valid_0's binary_logloss: 1.41539
[22]	valid_0's binary_logloss: 1.41432
[23]	valid_0's binary_logloss: 1.40609
[24]	valid_0's binary_logloss: 1.40544
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 1.40428
[26]	valid_0's binary_logloss: 1.40177
[27]	valid_0's binary_logloss: 1.40684
[28]	valid_0's binary_logloss: 1.40315
[29]	valid_0's binary_logloss: 1.40228
[30]	valid_0's binary_logloss: 1.4139
[31]	valid_0's binary_logloss: 1.4103

Trening klas: 100%|█████████▉| 498/500 [56:29<00:13,  6.59s/klasa, klasa=class_498, F1_klasy=0.0000, F1_macro=0.6032, drzewa=2]




Trening klas: 100%|█████████▉| 499/500 [56:29<00:05,  5.75s/klasa, klasa=class_498, F1_klasy=0.0000, F1_macro=0.6032, drzewa=2]

[32]	valid_0's binary_logloss: 1.40949
[1]	valid_0's binary_logloss: 0.370678
[2]	valid_0's binary_logloss: 0.248573
[3]	valid_0's binary_logloss: 0.236462
[4]	valid_0's binary_logloss: 0.226897
[5]	valid_0's binary_logloss: 0.221886
[6]	valid_0's binary_logloss: 0.220913
[7]	valid_0's binary_logloss: 0.213429
[8]	valid_0's binary_logloss: 0.207237
[9]	valid_0's binary_logloss: 0.202789
[10]	valid_0's binary_logloss: 0.197378
[11]	valid_0's binary_logloss: 0.192185
[12]	valid_0's binary_logloss: 0.188466
[13]	valid_0's binary_logloss: 0.184514
[14]	valid_0's binary_logloss: 0.180584
[15]	valid_0's binary_logloss: 0.177474
[16]	valid_0's binary_logloss: 0.174315
[17]	valid_0's binary_logloss: 0.171185
[18]	valid_0's binary_logloss: 0.16794
[19]	valid_0's binary_logloss: 0.165453
[20]	valid_0's binary_logloss: 0.162576
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[21]	valid_0's binary_logloss: 0.159789
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[22]	valid_0's binary_logloss: 0.157271
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[23]	valid_0's binary_logloss: 0.154646
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[24]	valid_0's binary_logloss: 0.152044
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[25]	valid_0's binary_logloss: 0.1496
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[26]	valid_0's binary_logloss: 0.147379
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[27]	valid_0's binary_logloss: 0.145265
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[28]	valid_0's binary_logloss: 0.14313
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[29]	valid_0's binary_logloss: 0.141036
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's binary_logloss: 0.138887
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[31]	valid_0's binary_logloss: 0.13679
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[32]	valid_0's binary_logloss: 0.134717
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[33]	valid_0's binary_logloss: 0.132801
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[34]	valid_0's binary_logloss: 0.130945
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[35]	valid_0's binary_logloss: 0.129079
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[36]	valid_0's binary_logloss: 0.127237
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[37]	valid_0's binary_logloss: 0.12537
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[38]	valid_0's binary_logloss: 0.123639
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[39]	valid_0's binary_logloss: 0.121978
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's binary_logloss: 0.120179
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[41]	valid_0's binary_logloss: 0.118575
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[42]	valid_0's binary_logloss: 0.117042
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[43]	valid_0's binary_logloss: 0.115461
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[44]	valid_0's binary_logloss: 0.113916
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[45]	valid_0's binary_logloss: 0.112419
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[46]	valid_0's binary_logloss: 0.11094
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[47]	valid_0's binary_logloss: 0.109454
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[48]	valid_0's binary_logloss: 0.107997
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[49]	valid_0's binary_logloss: 0.106586
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's binary_logloss: 0.105117
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[51]	valid_0's binary_logloss: 0.103572
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[52]	valid_0's binary_logloss: 0.10211
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[53]	valid_0's binary_logloss: 0.100565
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[54]	valid_0's binary_logloss: 0.0990296
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[55]	valid_0's binary_logloss: 0.097668
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[56]	valid_0's binary_logloss: 0.0963341
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[57]	valid_0's binary_logloss: 0.0950014
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[58]	valid_0's binary_logloss: 0.0936774
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[59]	valid_0's binary_logloss: 0.0923341
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[60]	valid_0's binary_logloss: 0.0910555
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[61]	valid_0's binary_logloss: 0.089742
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[62]	valid_0's binary_logloss: 0.0885298
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[63]	valid_0's binary_logloss: 0.087322
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[64]	valid_0's binary_logloss: 0.0861282
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[65]	valid_0's binary_logloss: 0.0849342
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[66]	valid_0's binary_logloss: 0.0838112
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[67]	valid_0's binary_logloss: 0.0827807
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[68]	valid_0's binary_logloss: 0.0816548
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[69]	valid_0's binary_logloss: 0.0806161
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[70]	valid_0's binary_logloss: 0.0795212
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[71]	valid_0's binary_logloss: 0.0786986
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[72]	valid_0's binary_logloss: 0.0780394
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[73]	valid_0's binary_logloss: 0.0770421
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[74]	valid_0's binary_logloss: 0.0762614
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[75]	valid_0's binary_logloss: 0.0752775
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[76]	valid_0's binary_logloss: 0.074354
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[77]	valid_0's binary_logloss: 0.0733419
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[78]	valid_0's binary_logloss: 0.0722845
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[79]	valid_0's binary_logloss: 0.0712851
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's binary_logloss: 0.070359
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[81]	valid_0's binary_logloss: 0.06937
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[82]	valid_0's binary_logloss: 0.0683582
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[83]	valid_0's binary_logloss: 0.0673574
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[84]	valid_0's binary_logloss: 0.0663643
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[85]	valid_0's binary_logloss: 0.0656297
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[86]	valid_0's binary_logloss: 0.0648365
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[87]	valid_0's binary_logloss: 0.0639577
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[88]	valid_0's binary_logloss: 0.0633151
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[89]	valid_0's binary_logloss: 0.062541
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's binary_logloss: 0.0618981
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[91]	valid_0's binary_logloss: 0.0609693
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[92]	valid_0's binary_logloss: 0.0602479
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[93]	valid_0's binary_logloss: 0.0593836
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[94]	valid_0's binary_logloss: 0.0585468
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[95]	valid_0's binary_logloss: 0.0577593
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[96]	valid_0's binary_logloss: 0.0568271
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[97]	valid_0's binary_logloss: 0.0558966
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[98]	valid_0's binary_logloss: 0.0549813
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[99]	valid_0's binary_logloss: 0.0540511
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's binary_logloss: 0.0531902
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[101]	valid_0's binary_logloss: 0.052779
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[102]	valid_0's binary_logloss: 0.0522457
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[103]	valid_0's binary_logloss: 0.0517018
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[104]	valid_0's binary_logloss: 0.0511031
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[105]	valid_0's binary_logloss: 0.0506203
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[106]	valid_0's binary_logloss: 0.0502017
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[107]	valid_0's binary_logloss: 0.0494279
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[108]	valid_0's binary_logloss: 0.0490436
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[109]	valid_0's binary_logloss: 0.0482891
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[110]	valid_0's binary_logloss: 0.0477175
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[111]	valid_0's binary_logloss: 0.0473312
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[112]	valid_0's binary_logloss: 0.0470638
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[113]	valid_0's binary_logloss: 0.0465354
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[114]	valid_0's binary_logloss: 0.0461519
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[115]	valid_0's binary_logloss: 0.0458389
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[116]	valid_0's binary_logloss: 0.0455148
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[117]	valid_0's binary_logloss: 0.0450756
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[118]	valid_0's binary_logloss: 0.044452
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[119]	valid_0's binary_logloss: 0.0439229
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[120]	valid_0's binary_logloss: 0.0435524
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[121]	valid_0's binary_logloss: 0.0430514
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[122]	valid_0's binary_logloss: 0.0429054
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[123]	valid_0's binary_logloss: 0.0424588
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[124]	valid_0's binary_logloss: 0.0420456
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[125]	valid_0's binary_logloss: 0.0415363
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[126]	valid_0's binary_logloss: 0.0413535
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[127]	valid_0's binary_logloss: 0.0411371
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[128]	valid_0's binary_logloss: 0.0407787
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[129]	valid_0's binary_logloss: 0.0404253
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[130]	valid_0's binary_logloss: 0.0401748
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[131]	valid_0's binary_logloss: 0.0399988
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[132]	valid_0's binary_logloss: 0.0397272
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[133]	valid_0's binary_logloss: 0.0392872
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[134]	valid_0's binary_logloss: 0.0389835
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[135]	valid_0's binary_logloss: 0.0388298
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[136]	valid_0's binary_logloss: 0.0386188
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[137]	valid_0's binary_logloss: 0.0384823
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[138]	valid_0's binary_logloss: 0.0383415
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[139]	valid_0's binary_logloss: 0.0381759
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[140]	valid_0's binary_logloss: 0.0380709
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[141]	valid_0's binary_logloss: 0.0376203
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[142]	valid_0's binary_logloss: 0.0372488
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[143]	valid_0's binary_logloss: 0.0368584
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[144]	valid_0's binary_logloss: 0.0364354
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[145]	valid_0's binary_logloss: 0.0360843
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[146]	valid_0's binary_logloss: 0.0357282
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[147]	valid_0's binary_logloss: 0.035387
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[148]	valid_0's binary_logloss: 0.0349939
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[149]	valid_0's binary_logloss: 0.0345926
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[150]	valid_0's binary_logloss: 0.0342079
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[151]	valid_0's binary_logloss: 0.0339455
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[152]	valid_0's binary_logloss: 0.0336683
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[153]	valid_0's binary_logloss: 0.0333722
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[154]	valid_0's binary_logloss: 0.0331545
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[155]	valid_0's binary_logloss: 0.0329158
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[156]	valid_0's binary_logloss: 0.0326269
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[157]	valid_0's binary_logloss: 0.0325219
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[158]	valid_0's binary_logloss: 0.0320796
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[159]	valid_0's binary_logloss: 0.0319803
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[160]	valid_0's binary_logloss: 0.0315834
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[161]	valid_0's binary_logloss: 0.0313232
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[162]	valid_0's binary_logloss: 0.0311006
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[163]	valid_0's binary_logloss: 0.0308635
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[164]	valid_0's binary_logloss: 0.0306319
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[165]	valid_0's binary_logloss: 0.0303773
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[166]	valid_0's binary_logloss: 0.030104
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[167]	valid_0's binary_logloss: 0.0299205
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[168]	valid_0's binary_logloss: 0.0297604
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[169]	valid_0's binary_logloss: 0.0295196
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[170]	valid_0's binary_logloss: 0.0293584
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[171]	valid_0's binary_logloss: 0.0293364
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[172]	valid_0's binary_logloss: 0.029265
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[173]	valid_0's binary_logloss: 0.0291909
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[174]	valid_0's binary_logloss: 0.0291281
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[175]	valid_0's binary_logloss: 0.0289836
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[176]	valid_0's binary_logloss: 0.0288575
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[177]	valid_0's binary_logloss: 0.0287058
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[178]	valid_0's binary_logloss: 0.0285869
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[179]	valid_0's binary_logloss: 0.0284909
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[180]	valid_0's binary_logloss: 0.0283358
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[181]	valid_0's binary_logloss: 0.0282059
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[182]	valid_0's binary_logloss: 0.0280579
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[183]	valid_0's binary_logloss: 0.0278299
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[184]	valid_0's binary_logloss: 0.0276871
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

Trening klas: 100%|█████████▉| 499/500 [56:38<00:05,  5.75s/klasa, klasa=class_499, F1_klasy=0.4324, F1_macro=0.6028, drzewa=300]




Trening klas: 100%|██████████| 500/500 [56:38<00:00,  6.80s/klasa, klasa=class_499, F1_klasy=0.4324, F1_macro=0.6028, drzewa=300]

=======================================================
  TRENING ZAKOŃCZONY  (56.6 min)
  Macro-averaged F1 (test): 0.6028
=======================================================

Najgorsze 5 klas:
  class_106: 0.0000
  class_121: 0.0000
  class_123: 0.0000
  class_162: 0.0000
  class_167: 0.0000

Najlepsze 5 klas:
  class_244: 1.0000
  class_246: 1.0000
  class_247: 1.0000
  class_290: 1.0000
  class_421: 1.0000

In [122]:
# ============================================================
# CELL 8 — Ewaluacja końcowa + propagacja DAG
# ============================================================
y_pred_raw = (prob_matrix_test >= THRESHOLD).astype(np.int8)
y_pred_dag = propagate_labels_upward(y_pred_raw, dag, label_cols)

f1_before = f1_score(y_test, y_pred_raw, average="macro", zero_division=0)
f1_after  = f1_score(y_test, y_pred_dag, average="macro", zero_division=0)
incons    = count_dag_inconsistencies(prob_matrix_test, dag, label_cols)

print(f"\nF1 macro — bez propagacji DAG : {f1_before:.4f}")
print(f"F1 macro — po  propagacji DAG : {f1_after:.4f}  (+{f1_after - f1_before:.4f})")
print(f"Niespójności DAG : {incons}")

F1 macro — bez propagacji DAG : 0.6028
F1 macro — po  propagacji DAG : 0.5832  (+-0.0196)
Niespójności DAG              : 1137628

In [123]:
# ============================================================
# CELL 9 — Analiza wyników per klasa
# ============================================================
import pandas as pd
from sklearn.metrics import precision_score, recall_score

rows = []
for i, class_name in enumerate(label_cols):
    y_true_col = y_test[:, i]
    y_pred_col = y_pred_dag[:, i]
    y_prob_col = prob_matrix_test[:, i]

    n_positive = int(y_true_col.sum())
    n_predicted = int(y_pred_col.sum())

    f1  = f1_score(y_true_col, y_pred_col, average="binary", zero_division=0)
    pre = precision_score(y_true_col, y_pred_col, zero_division=0)
    rec = recall_score(y_true_col, y_pred_col, zero_division=0)

    rows.append({
        "klasa":        class_name,
        "f1":           round(f1, 4),
        "precision":    round(pre, 4),
        "recall":       round(rec, 4),
        "n_pozytywnych": n_positive,
        "n_przewidzianych": n_predicted,
        "prev_%":       round(100 * n_positive / len(y_true_col), 2),
    })

df_results = pd.DataFrame(rows).sort_values("f1", ascending=True).reset_index(drop=True)

In [126]:
df_results

,klasa,f1,precision,recall,n_pozytywnych,n_przewidzianych,prev_%
0,class_386,0.0,0.0,0.0,0,2,0.00
1,class_416,0.0,0.0,0.0,0,0,0.00
2,class_420,0.0,0.0,0.0,0,0,0.00
3,class_384,0.0,0.0,0.0,1,7,0.01
4,class_300,0.0,0.0,0.0,0,0,0.00
...,...,...,...,...,...,...,...
495,class_246,1.0,1.0,1.0,1,1,0.01
496,class_247,1.0,1.0,1.0,1,1,0.01
497,class_290,1.0,1.0,1.0,1,1,0.01
498,class_191,1.0,1.0,1.0,52,52,0.77
499,class_0,1.0,1.0,1.0,6734,6734,100.00

In [125]:
df_results.to_csv("results.csv", index = False)

In [121]:
import joblib
import os

# Tworzymy folder na model, jeśli nie istnieje
os.makedirs("model_output", exist_ok=True)

# Budujemy słownik z kompletnym stanem modelu
model_artifact = {
    "models": models,            # Lista 500 modeli Booster
    "label_cols": label_cols,    # Nazwy klas (kluczowe do predict!)
    "threshold": THRESHOLD       # Próg decyzyjny użyty w treningu
}

# Zapisujemy wszystko do jednego skompresowanego pliku
model_filename = "model_output/chebi_lgbm_ensemble.joblib"
joblib.dump(model_artifact, model_filename, compress=3)

print(f"Sukces! Model zapisany w: {model_filename}")

Exception ignored in: <function tqdm.__del__ at 0x00000200679A6950>
Traceback (most recent call last):
  File "C:\Users\domin\PycharmProjects\ml-train-lgbm\.venv\lib\site-packages\tqdm\std.py", line 1145, in __del__
    self.close()
  File "C:\Users\domin\PycharmProjects\ml-train-lgbm\.venv\lib\site-packages\tqdm\notebook.py", line 283, in close
    self.disp(bar_style='danger', check_delay=False)
AttributeError: 'tqdm_notebook' object has no attribute 'disp'
Exception ignored in: <function tqdm.__del__ at 0x00000200679A6950>
Traceback (most recent call last):
  File "C:\Users\domin\PycharmProjects\ml-train-lgbm\.venv\lib\site-packages\tqdm\std.py", line 1145, in __del__
    self.close()
  File "C:\Users\domin\PycharmProjects\ml-train-lgbm\.venv\lib\site-packages\tqdm\notebook.py", line 283, in close
    self.disp(bar_style='danger', check_delay=False)
AttributeError: 'tqdm_notebook' object has no attribute 'disp'
Exception ignored in: <function tqdm.__del__ at 0x00000200679A6950>
Traceback (most recent call last):
  File "C:\Users\domin\PycharmProjects\ml-train-lgbm\.venv\lib\site-packages\tqdm\std.py", line 1145, in __del__
    self.close()
  File "C:\Users\domin\PycharmProjects\ml-train-lgbm\.venv\lib\site-packages\tqdm\notebook.py", line 283, in close
    self.disp(bar_style='danger', check_delay=False)
AttributeError: 'tqdm_notebook' object has no attribute 'disp'
Exception ignored in: <function tqdm.__del__ at 0x00000200679A6950>
Traceback (most recent call last):
  File "C:\Users\domin\PycharmProjects\ml-train-lgbm\.venv\lib\site-packages\tqdm\std.py", line 1145, in __del__
    self.close()
  File "C:\Users\domin\PycharmProjects\ml-train-lgbm\.venv\lib\site-packages\tqdm\notebook.py", line 283, in close
    self.disp(bar_style='danger', check_delay=False)
AttributeError: 'tqdm_notebook' object has no attribute 'disp'
Exception ignored in: <function tqdm.__del__ at 0x00000200679A6950>
Traceback (most recent call last):
  File "C:\Users\domin\PycharmProjects\ml-train-lgbm\.venv\lib\site-packages\tqdm\std.py", line 1145, in __del__
    self.close()
  File "C:\Users\domin\PycharmProjects\ml-train-lgbm\.venv\lib\site-packages\tqdm\notebook.py", line 283, in close
    self.disp(bar_style='danger', check_delay=False)
AttributeError: 'tqdm_notebook' object has no attribute 'disp'

Sukces! Model zapisany w: model_output/chebi_lgbm_ensemble.joblib